### ISSUE TITLE
Auto-submit login forms has stopped working

### ISSUE THREAD

**Issue by mara004** [keepassxreboot/keepassxc-browser#1002]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Even though I have auto-submit login forms enabled in the browser extension settings, none of my forms are submitted automatically at least since the time of KeePassXC 2.6.1 release.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable automatic form submission in the extension settings
2. Visit a website where something can be filled in.
3. Click on the icon appearing next to the username/password field
4. The data will be filled in correctly, but it won't be submitted

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When auto-submit login forms is enabled, username/password should be sent automatically after getting filled in.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Username and password are filled in correctly, but nothing gets submitted automatically.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I believe this feature is broken since an update of either KeePassXC or the browser extension. I remember it worked previously.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba
KeePassXC Browser 1.7.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 8.1

**Comment by varjolintu** [comment]
Fixed in 1.7.1.

**Comment by mara004** [comment]
Wow, thanks! You are impressively fast! Sorry for reporting the issue at the worng place first.

**Comment by mara004** [comment]
Fix confirmed. Thanks!

**Comment by mara004** [comment]
It doesn't work again, at least on some sites (including github). Could you please reopen this bug and investigate the problem? (KeePassXC-Browser 1.7.1, Win10, Firefox 82.0, KeePassXC 2.6.2 Portable)
