### ISSUE TITLE
Skrill.com

### ISSUE THREAD

**Issue by TimRob01** [keepassxreboot/keepassxc-browser#1004]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Can't fill the password using chrome extension of keepassxc (all of the methods - right click, through icon or extension on the panel)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open account.skrill.com
2. Try to fill the password using keepass extension (all of the methods)
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
It will be great if it work again in next update . 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Well. Something is happened after chrome or keepassxc update. Even keepassxc icon placed on the password field. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.1
Revision: 9a35bba

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 
Browser: Chrome 85.... (latest)
![Skr](https://user-images.githubusercontent.com/70913308/92411028-e4683880-f14e-11ea-9032-33a4ac341503.JPG)

**Comment by TimRob01** [comment]
My problem is solved by version 1.7.1 i dont know what file did you rewrite for this bug, i change all of them and upload to chrome. And problem with Skrill.com solved.

**Comment by varjolintu** [comment]
I made a change to the TOTP field detection. The email field was detected as a TOTP field, not as username field.
