### ISSUE TITLE
AWS login page inputs are not detected

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1005]
## Expected Behavior

At https://signin.aws.amazon.com/console I expect the email address field to be fillable with an entry from my database.
I also expect to be able to fill in the remaining credentials on the pages afterwards.

This login works for non-root (IAM) logins

## Current Behavior

The input fields are not detected. With manual field selection, _sometimes_ the email field will start working. In that case the password field on the next page is not detected.
Most often though, the manual field assignment does nothing and even after that the email is not entered. :)

## Possible Solution

I don't see what's special about this login page.

## Steps to Reproduce (for bugs)

It should not work right away without any special steps.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Windows 10
Browser: ChromiumEdge

**Comment by varjolintu** [comment]
Have you tried adding `https://signin.aws.amazon.com/*` to Site Preferences and enabling the _Username-only Detection_?

**Comment by oliversalzburg** [comment]
So far, the former has never been necessary for any other entry, but I tried it anyway and did't feel like it had an impact on the issue

The latter options is what I meant with the manual selection. It allows me to temporarily progress to the second page, which asks for the password, where there will be no KPXC button.
When I then return to the email page (through the "Sign in to a different account" link), the KPXC button from before will be gone again. After a refresh the button is sometimes there, sometimes not.

Although while trying to reproduce at home right now in Chrome, the button appears pretty reliably for the email input now. The password on the second page is still not happening though.

**Comment by varjolintu** [comment]
Gotta verify that, and try to fix the icon for the password field. The password fill should still work from keyboard and the context menu though.

**Comment by oliversalzburg** [comment]
Funny you mention that, because the context menu also doesn't work. I click through the selections and the input box stays empty. I wasn't aware of this option so far.

Not sure which keyboard option you're referring to. I'm just copying the password from the KPXC and paste it manually for now.

**Comment by oliversalzburg** [comment]
Seems to me like this is working fine now for whatever reason.
