### ISSUE TITLE
Key-Exchange not possible since Update to 1.7.0

### ISSUE THREAD

**Issue by Wastl2IT** [keepassxreboot/keepassxc-browser#1006]
## Expected Behavior

KeePassXC-Browser-Extension connects to KeePassXC-Database

## Current Behavior

Connection from Browser-Extension to Database fails since Update to 1.7.0:

> Die Verbindung zu KeePassXC ist nicht möglich. Überprüfen Sie, ob die Browser-Integration in den KeePassXC-Einstellungen aktiviert ist.
Connection to KeePassXC not possible...

> Schlüsselaustausch war nicht erfolgreich.
Key Exchange was not possible...

## Debug info

KeePassXC -2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Mac/Win
Browser: Firefox - 80.0.1

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by Wastl2IT** [comment]
Thanks, I was able to solve the problem.
keepassxc-proxy.exe didn't exist, so I reran the setup using the repair-option, but there still was no keepassxc-proxy.exe.
after rebooting the pc, everything worked fine again.
in german there is a saying: "Reboot tut gut!" 👍 

I already rebootet the pc before, so I don't really know, what went wrong.
