### ISSUE TITLE
https://accounts.google.com/ stuck at loading

### ISSUE THREAD

**Issue by TimRob01** [keepassxreboot/keepassxc-browser#1007]
Gmail.com stuck at loading when function "Use dynamic input field detection." is activated in options.

## Steps to Reproduce (for bugs)

1. Install keepassxc-browser and keepasxc
2. Open https://accounts.google.com/
![gmail](https://user-images.githubusercontent.com/70913308/92784740-838b6b00-f3af-11ea-8f5b-946687356466.JPG)

3. Now it stuck until press F5 and u can fill login or password and press next
4.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0 and 1.7.1 (with 5 fixes where 1004 last,tested)
Operating system: Win
Browser: Chrome (tested on the 84 and last updated)

**Comment by varjolintu** [comment]
Could not reproduce this with Firefox, Edge or Chromium. Is there any messages in the JavaScript console? Have you tried disabling every other extension?

**Comment by TimRob01** [comment]
Sorry " Is there any messages in the JavaScript console?" - i dont know where to watch this) i'm newbie)
"Have you tried disabling every other extension?" - it's clean installation for chrome and keepassxc and windows. 
i switch off all google extensions (docs, docs offline, etc.) 
I can even press on keepass icon and fill the  password but cannot press next :)
![gmail2](https://user-images.githubusercontent.com/70913308/92788311-83409f00-f3b2-11ea-97b5-46dc02d3ab65.JPG)
help only turn off "Use dynamic input field detection."

**Comment by TimRob01** [comment]
![image](https://user-images.githubusercontent.com/70913308/92790585-96546e80-f3b4-11ea-9b04-964a4ef40871.png)

**Comment by varjolintu** [comment]
I cannot reproduce this, and the only way you could help is to debug the content script. If you are a newbie (as you said), that is beyond your skills. I have no problems viewing the GMail page in Russian either.

**Comment by TimRob01** [comment]
I will try. If i didnt find in 1-2 days steps to reproduce it. I will close this topic. Anyway thank you for fast answers.

**Comment by varjolintu** [comment]
For now the only workaround is to disable Dynamic Input Field detection.
