### ISSUE TITLE
Webpages aren't refreshed automatically with browserextension enabled

### ISSUE THREAD

**Issue by itsmealso** [keepassxreboot/keepassxc-browser#1008]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # In chromium browsers (Edge, Chrome), with the Keepassxc browserxtension loaded, webpages aren't refreshing automatically. Only when using F5 the page is refreshed. Without  the extension (or in a inprivate) window, auto-refresh is working.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC-Browser versie: 1.7.0
KeePassXC versie: 2.6.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
Could not reproduce. Can you give an example?

**Comment by itsmealso** [comment]
Hi Sami,

I’ve attached a word file with some screenshots

Regards,

Wim

Van: Sami Vänttinen <notifications@github.com>
Verzonden: vrijdag 11 september 2020 14:30
Aan: keepassxreboot/keepassxc-browser <keepassxc-browser@noreply.github.com>
CC: Wim Minkjan <w.minkjan@stolwijkkelderman.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [keepassxreboot/keepassxc-browser] Webpages aren't refreshed automatically with browserextension enabled (#1008)


Could not reproduce. Can you give an example?

**Comment by varjolintu** [comment]
Word file with screenshots? Sorry. I'm not able to open those.

**Comment by itsmealso** [comment]
Hi Sami,

What about a PDF? 😊

I can’t give you access to this site because it is filled with data about taxes from people.
Met vriendelijke groet,

Wim Minkjan

________________________________
E


w.minkjan@stolwijkkelderman.nl

[cid:image001.png@01D68887.195A9E60]<https://stolwijkkelderman.nl/>

Bezoekadres
Terborgseweg 25 b Doetinchem
Mercurion 3 Zevenaar

T
M

+31 314 741127
+31 6 20394786

www.stolwijkkelderman.nl<https://www.stolwijkkelderman.nl>
KvK nr. 09197964

Postadres
Postbus 595 7000 AN Doetinchem


<https://twitter.com/SK_Netwerk>  <http://www.linkedin.com/company/stolwijk-kelderman>

route<https://stolwijkkelderman.nl/contact/route/>

________________________________
Op dit e-mailbericht is een disclaimer van toepassing.  Klik hier<https://stolwijkkelderman.nl/disclaimer/> voor de disclaimer.
PS Wilt u ons nog beter leren kennen? Lees hier<https://stolwijkkennisnetwerk.nl> ons online transparantieverslag met volop feiten, foto’s, video’s en verrassende interviews.
P Denk aan het milieu voor u deze e-mail afdrukt.
Van: Sami Vänttinen <notifications@github.com>
Verzonden: vrijdag 11 september 2020 17:31
Aan: keepassxreboot/keepassxc-browser <keepassxc-browser@noreply.github.com>
CC: Wim Minkjan <w.minkjan@stolwijkkelderman.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [keepassxreboot/keepassxc-browser] Webpages aren't refreshed automatically with browserextension enabled (#1008)


Word file with screenshots? Sorry. I'm not able to open those.
