### ISSUE TITLE
Possible KeepassXC-browser issue: auto fill not working on some pages with latest version of Chrome

### ISSUE THREAD

**Issue by dpb657** [keepassxreboot/keepassxc-browser#1009]
I am noticing an issue with KeepassXC-browser on some pages with the latest version of Chrome (85.0.4183.102) where the username and password will not auto fill as they have for the same pages in the pass. Even the button is not appearing in the username field. Is anyone else experiencing similar issues? 

The pages I am seeing the issue with so far are internal to the University I work at so any URLs I can provide as examples will be inaccessible to most everyone. If there are troubleshooting steps I can do please let me know.

I am working on a Mac Mac OS 10.15.6. I did run into the problem at a non-University site but regrettably it is not a public site either.

**Comment by dpb657** [comment]
Ok @droidmonkey where did you transfer this to? I want to add information to this.

**Comment by varjolintu** [comment]
@dpb657 Can you provide source code for the input fields where the button/icon is not appearing?

**Comment by dpb657** [comment]
I have attached a copy of the page source.

[footprints_logon.txt](https://github.com/keepassxreboot/keepassxc-browser/files/5210534/footprints_logon.txt)

**Comment by varjolintu** [comment]
I have no problems with that source if I load it locally.

**Comment by dpb657** [comment]
Oh fun. Thanks for looking. I will look at trying the page without the other extensions I have loaded. Maybe one of those is interfering.

**Comment by varjolintu** [comment]
Some fixes are made for Auto-Fill in 1.7.1, and it was just released. Please give an update if the new release fixes this.

**Comment by dAnjou** [comment]
Not sure if I'm experiencing the same issue. The extension connects with the application it seems but nothing happens when clicking the icon in the login field. 

KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: macOS 10.15
CPU architecture: x86_64
Kernel: darwin 19.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC-Browser - 1.7.1
Operating system: MacIntel
Browser: Chrome/Chromium 85.0.4183.102

<img width="300" src="https://user-images.githubusercontent.com/117147/93016611-df7a0d80-f5c2-11ea-94fc-fe07b0a60b22.png">
<img width="300" src="https://user-images.githubusercontent.com/117147/93016613-e143d100-f5c2-11ea-9088-1e8db18949a4.png">
<img width="300" src="https://user-images.githubusercontent.com/117147/93016665-3a136980-f5c3-11ea-9955-95039a3fce13.png">
<img width="300" src="https://user-images.githubusercontent.com/117147/93016666-3b449680-f5c3-11ea-8e8d-b73d9b9be6e2.png">
<img height="150" src="https://user-images.githubusercontent.com/117147/93016667-3bdd2d00-f5c3-11ea-9425-0dca6e26d71a.png">

**Comment by varjolintu** [comment]
@dAnjou Does the same happen with KeePassXC 2.6.0?

**Comment by dAnjou** [comment]
@varjolintu 2.6.0 works, thanks!

**Comment by varjolintu** [comment]
@dAnjou Then you're affected by a bug that will be fixed in KeePassXC 2.6.2. In the meanwhile you can use 2.6.0.

**Comment by ArnoBuschmann** [comment]
I experience this Problem on Ubuntu 20.04 with KeepassXC version 2.6.2 on various browsers such as Chrome, Brave and Firefox. The browsers are properly connected, KeepassXC is running, the database unlocked. The KeepassXC icon appears in the the form fields but neither clicking it, nor right mouse click -> KeepassXC -> fill user and password works and the fields stay empty.  Any idea what I could check to fix this?

**Comment by varjolintu** [comment]
@ArnoBuschmann Check that your entry URL really matches the site, including URL scheme (http/https)? You can also hive an example of an entry and a site.

**Comment by ArnoBuschmann** [comment]
@varjolintu thanks for your quick response. I just checked on the URL scheme, let's say Twitter for example:

https://twitter.com/login

The entry is:

Titel: My account on Twitter
User name: my Twitter user name
Password: my Twitter password
URL: https://twitter.com/login

**Comment by varjolintu** [comment]
@ArnoBuschmann I have no problems filling that URL with an identical entry. If you create a new temporary database, does the same happen with that one?

**Comment by ArnoBuschmann** [comment]
Interesting! When creating a new database, it works. Do you think the first database could have been corrupt?

**Comment by varjolintu** [comment]
@ArnoBuschmann It's rare but possible. I'd suggest you try to clear all the connected keys from your database (Disconnect Keys from Database Settings -> Browser Integration). You can also try to use the other functions, like Forget all site-specific settings on entries. Refreshing the root group ID couldn't hurt too. That should reset all the browser integration related stuff in the database. Give it a try.

**Comment by ArnoBuschmann** [comment]
I just think, after installing Ubuntu 20.04 and Chrome, it asked me to set a key for Chrome. Now, whenever I start the computer and Chrome thereafter, it always asks me for that key again. Could it be, that this is interferring with the key used by KeepassXC to connect to the browser?

**Comment by varjolintu** [comment]
@ArnoBuschmann You should use unique keys for each browser. It's strange if it asks it again every time. The connection keys are stored and only asked again if something else has overwritten them.

**Comment by ArnoBuschmann** [comment]
Yes, it's not KeepassXC asking again, it is Ubuntu, when starting Chrome. I am not even sure, why it does that and I should try switch it off. I just thought, that that could interfere with your KeepassXC key management?

**Comment by varjolintu** [comment]
@ArnoBuschmann If that has something to do with localStorage access, it could interfere.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
