### ISSUE TITLE
Regression: Url matching stops working if the path is different

### ISSUE THREAD

**Issue by tzugen** [keepassxreboot/keepassxc-browser#1012]
Since a recent update, I can't autofill most of my logins anymore.
After checking I found that I can only autofill those where the Browser URL is exactly! the same as the URL saved in KeepassXC.

## Expected Behavior
When a user visits a site https://example.com/login , keepassxc should suggest any entries saved with a example.com domain, independent of the path.

## Current Behavior
KeepassXC finds no matching entries.

## Steps to Reproduce (for bugs)
1. Using the Versions listed below (Debian Sid)
2. Create an entry for example.com
3. Visit example.com/login
4. KeepassXC can't find an entry.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

**Comment by ChatDeBlofeld** [comment]
I unchecked "Return only best-matching credentials" in browser integration settings and now it works like before again.

**Comment by droidmonkey** [comment]
This is being fixed in keepassxc 2.6.2. Already merged in
