### ISSUE TITLE
Username is not submitted on several pages when selecting login from list via keyboard

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc-browser#1013]
## Expected Behavior

Given more than 1 login stored for a nextcloud instance in keepassxc, the username is not submitted on the nextcloud login page when using only the keyboard to select the login and submit the form.

This also happens with gmail (accounts.google.com), even with username only option applied, and with Microsoft Azure (login.microsoftonline.com).

The `username` field on the login page gets cleared when pressing `Enter` to submit the login form.

For nextcloud, the network inspection tab in the browser's development tools shows that the `username` field is empty in the submitted form data.

It also does not help to explicitly select the username and password fields using keepassxc-browser's "choose custom login fields" feature.

Login data is correctly submitted when selecting the login from the login list using the mouse and clicking on the "Login" button to submit the login form.

## Current Behavior

`username` is not submitted.

## Steps to Reproduce (for bugs)

1. Create multiple (> 1) logins for a nextcloud instance and store them in KeepassXC
2. Go to the nextcloud instance
3. Press `Shift+Alt+u` to show the list of possible logins to select from
4. Press `up` or `down` arrrow keys and `Enter` to select a login
5. Press `Enter` again to submit the login form

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux (Manjaro Gnome Edition)
Browser: Firefox 80.0.1

**Comment by varjolintu** [comment]
I reproduced this but I'm still inspecting why this happens.

**Comment by philipreimer** [comment]
@varjolintu I did some more testing and here is what I found so far. Maybe it helps narrowing down the cause...

* the issue does not occur when using the `master` branch
* the issue does not occur, when *clicking* on the login from the autocomplete list in step **4**, instead of *pressing* `enter`.
  So maybe there is a difference in handling `click` event and `keypress` event?
* so far I could reproduce this on Google's and Microsoft's login pages, as well as on my nextcloud instance's login page.
  For Nextcloud I know that it uses vuejs. For google I assume they are using angular? And maybe Microsoft uses one of their own SPA frameworks? Could the issue be related with how those frameworks handle input fields?

**Comment by varjolintu** [comment]
How the frameworks handle input fields was my original idea as well, and maybe the override some handling here and there but.. It sounds strange. The `master` branch haven't been updated (luckily), and it's good to know it doesn't happen there. I can make some comparison to the current codebase.
