### ISSUE TITLE
Cannot record a new password with console error : Empty result from get_database_groups 

### ISSUE THREAD

**Issue by flibustenet** [keepassxreboot/keepassxc-browser#1016]
## Expected Behavior
I write my password, the extension is asking me to click the button to add it.

## Current Behavior
Nothing append, the banner stay on the screen.

## Debug info

On the console log :
`banner.js:141 Error: Empty result from get_database_groups`

KeePassXC - 2.3.4
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64 (Debian stretch with backport of KeePassXC)
Browser: Chrome/Chromium 85.0.4183.83 (Brave)

**Comment by varjolintu** [comment]
And you have groups in your database?

**Comment by flibustenet** [comment]
Yes, many groups. It was working not long time ago, i believe it's after an upgrade of the extension (not of the app which i didn't upgrade since long time).
If i update a password it works.

**Comment by RizzoV** [comment]
I am facing the same exact problem, my config:

KeepassXC 2.3.4
KeepassXC-Browser 1.7.1
Operating system: Linux x86_64 (Debian Buster)
Browser: Mozilla Firefox 81.0.1

**Comment by varjolintu** [comment]
Getting the groups is only supported with KeePassXC 2.4.0 and newer. We need to make a fix that ensures the backward compatibility.
