### ISSUE TITLE
When auto-submit is enabled, the keepassxc-browser script ignores the site's eventHandler

### ISSUE THREAD

**Issue by GuimLe** [keepassxreboot/keepassxc-browser#1017]
## Expected Behavior
When auto-submit is enabled, submit events attached by _addEventHandler_ should be triggered, as constraint validation, even when the form is pointing to an other URL than current page.

## Current Behavior
When auto-submit happens, if form action URL is not the same as the page itself, submit button is never returned by the function _getFormSubmitButton_, causing a call to the function submit on the form which did not raise submit event, neither constraint validation.

## Possible Solution
Test if input is type button OR submit instead of just button.
getFormSubmitButton, lines 174 to 179 function of keepassxc-browser.js : 
```
for (const e of form.elements) {
    if ((e.nodeName === 'BUTTON' && (e.type === 'button' || e.type === 'submit' || e.type === ''))
        || (e.nodeName === 'INPUT' && (e.type === 'button' || e.type === 'submit'))) {
        return e;
    }
}
```

## Steps to Reproduce (for bugs)

1.  create a page located on an URL which is not root : let's say https://yoursite.com/user/info/
2.  create a form on that page pointing to another location with username and password : `<form action="/user/login/">`
3.  attach a submit event handler to document : `document.addEventHandler('submit', function(e) { console.log('You will never see this message'); });`
4.  trigger auto-fill with auto-submit on that form.
5.  submit eventHandler never executed.

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win32
Browser: Mozilla Firefox 81.0

**Comment by varjolintu** [comment]
This goes to the list of events that are overridden even if they shouldn't be overridden. Another one is `transitionend`.

Thanks for the possible solution. It doesn't hurt to check the input for `submit` type.
