### ISSUE TITLE
False positive in input detection

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1018]
## Expected Behavior

KPXC buttons only appear on valid inputs.

## Current Behavior

Sometimes invalid fields received a KPXC button.

## Possible Solution

It would be nice to be able to exclude/ignore a certain input box maybe.

## Steps to Reproduce (for bugs)

1. The UI for Jaeger has an input that is incorrectly detected as a TOTP input. 
![image](https://user-images.githubusercontent.com/1658949/93761673-77ed3f00-fc0e-11ea-80cc-13c83f447d18.png)

The input element looks suspicious, but nothing that indicates to me why it's detected as TOTP input.

```html
<input class="ant-input" meta="[object Object]" placeholder="http.status_code=200 error=true" type="text" value="">
```

I don't know of a publicly accessible web UI for this sadly :(

## Debug info
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win
Browser: Chromium (Edge)

**Comment by oliversalzburg** [comment]
So this is because the `placeholder` of the input contains `code`. IMHO that is too lax.

**Comment by varjolintu** [comment]
And then there's multiple sites that use `code` for the attribute values. We don't want to break the compatibility with them.

**Comment by oliversalzburg** [comment]
Yes, that is totally understandable. It's tricky, because even looking for word boundaries before and after `code` would hit this false positive 🤔 I sadly have no good suggestion either.

**Comment by varjolintu** [comment]
For now I've enabled the calculation for one mutation only. But in this case there are 8 mutations, and allowing more than 3-5 would probably cause some problems. Many sites can trigger multiple calls to MutationObserver in a row, each containing more than one mutation.

**Comment by oliversalzburg** [comment]
@varjolintu I'm not quite sure how that relates to this issue. What calculations are you referring to?

**Comment by varjolintu** [comment]
@oliversalzburg Seems I replied to wrong issue! Sorry :D

**Comment by oliversalzburg** [comment]
Oh nice :) Thanks
