### ISSUE TITLE
Icon obstructs input text on RTL forms that rely on text-align:right

### ISSUE THREAD

**Issue by anon324875693** [keepassxreboot/keepassxc-browser#1019]
The code here https://github.com/keepassxreboot/keepassxc-browser/blob/c90cff8f65d2ef67b30c51e38dcf1fedd620a97e/keepassxc-browser/content/ui.js#L104-L106

checks if the page has set `document.dir` to `rtl` to see if 
the inputs are RTL. But at least one major bank in israel doesn't
use that, but instead uses the `text-align:right` CSS property,
for the inputs.

So on this site, input text writes from right-to-left but keepassxc-browser 
doesn't detect that and puts the icon on the right-hand side of input, which
hides what the user types.

Website:
https://www.mercantile.co.il/MB/private (Use big green button)

**Comment by varjolintu** [comment]
Providing check for `text-align: right` would only work if `getComputedStyle()` is used, and that's something we want to avoid. This would be called every time any icon changes position (on scrolling, etc.), so this will be not fixed. I suggest you contact the page developer and suggest using the standard way `<html dir="rtl">`.

**Comment by anon324875693** [comment]
It's unlikely that a bank would retool their website for a fringe group of customers.
How about adding a manual setting or override? part of the custom field detection UI perhaps?

**Comment by varjolintu** [comment]
A custom option for a rare situation like this would be too much. It's better to suggest others using standard methods, instead of adding support to every non-standard method for some random page.

**Comment by anon324875693** [comment]
Sound advice, but basically you're saying I'm SOL.

All the same, thank you for responding so quickly I appreciate it, and  thank you also of course  for all the work you do on KeepassXC.

**Comment by anon324875693** [comment]
If you don't mind, I'll stretch your patience and ask: why does `getComputedStyle()` need to be called on every UI event? if you assume the text-align direction is fixed per input (reaosnable), wouldn't  it be sufficient to call it once for every input you detect on the page?

**Comment by anon324875693** [comment]
Thank you!

Also, I checked the site for two of the largest banks in israel:
https://hb2.bankleumi.co.il/H/Login.html
https://www.bankhapoalim.co.il/he/login

and both have `dir=rtl` set on `<body>` and not on the `<html>` tag, and `document.dir` always returns the empty string. So they have the same problem I think.

https://www.mercantile.co.il/MB/private   and https://www.discountbank.co.il/DB/private
(different brands for same bank I think) don't have `dir=rtl` set anywhere.

Put together that's probably 80% of the bank market share in israel, so this isn't just some  issue with some fringe website.

Actually, maybe document direction is not what the code should check at all? `text-align` determines the alignment of the text, and don't you  always want the Icon on the opposite side of that in any case?

**Comment by varjolintu** [comment]
So the `dir` must be also checked for `body` element. Checking that is needed because there are not guarantees that site with `dir=rtl` would use `text-align` for input fields. We need to check both. In this case the check is needed only if `dir=rtl` is not used.

**Comment by anon324875693** [comment]
I'll be glad to test and report back on any PR you put up.

**Comment by anon324875693** [comment]
> We need to check both. In this case the check is needed only if dir=rtl is not used.

I think if `text-align` is present it has precedence, so in that case it's the rtl check that would  only needed if text-align isn't set. 

(by the way, issue still marked `wontfix`).

**Comment by varjolintu** [comment]
I added the fix for this to https://github.com/keepassxreboot/keepassxc-browser/pull/1021.
