### ISSUE TITLE
Input detection fails on login page with iframe

### ISSUE THREAD

**Issue by anon324875693** [keepassxreboot/keepassxc-browser#1024]
The input detection fails in several ways on the login page for one of Israel's largest banks:
https://www.bankhapoalim.co.il/he/login

The site is a little unusual because the login form is embedded as an iframe inside the loaded page.

## Expected Behavior
Field detection should work or at least the Custom field login procedure should work.

## Current Behavior + Steps to Reproduce
1. the user code field (an assigned alphanumeric code which serves as username) is detected as TOTP
2. activating `choose custom login fields` shows multiple instruction popups (the ones with the dismiss/confirm buttons)
3. after dismissing the foreground popup, the second one becomes active. After assigning the username role to the user code input, the overlay for the second input disappears
4. clicking "See more" exposes the second input overlay again and lets you choose it.
5. after skip totp, hit confirm and then do a page reload, and the key icon now appears on the field assigned as password.
6. If I repeat the procedure: do "discard selection" and then reassign the fields, everything now works as it should.

## Debug info
no errors in console

KeePassXC - 2.6.1
KeePassXC-Browser - git master
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
I have troubles loading the site. Gotta check this later.

**Comment by droidmonkey** [comment]
I couldn't load it either

**Comment by anon324875693** [comment]
hmm. Might be the holiday or perhaps security preventing access from abroad.
Could you try again in a couple of days? if it still fails, maybe i'll put up a repo example.

**Comment by anon324875693** [comment]
I'll split this into individual issues instead.
