### ISSUE TITLE
Question: how to exclude either localhost or 127.0.0.1 from asking to save user credentials?

### ISSUE THREAD

**Issue by stefanos82** [keepassxreboot/keepassxc-browser#1026]
Hello everyone.

I work locally with Django on various demos and all projects have the common `127.0.0.1:8000`, but of course with different credentials from project to project.

I'm forced to lock my KeePassXC database to stop it from suggesting to either save my credentials or attempt to use existing ones in case I have saved any.

Is there a way to add an exclusion list with IPs (such as localhost and LAN IP range), and / or domain names that could be bypassed?

It's really frustrating that I have to do the locking every single time and then have to remember to open it for later use.

Any feedback?

**Comment by varjolintu** [comment]
Extension settings -> Site Preferences -> Add your URL to the list, and enable option "Disable new/modified credentials".

**Comment by stefanos82** [comment]
Thank you @varjolintu :100:
