### ISSUE TITLE
2 Requests if possible: 1) edit URL(s) from Settings > Site Preferences 2) checkboxes to delete multiple URLs

### ISSUE THREAD

**Issue by stefanos82** [keepassxreboot/keepassxc-browser#1027]
I have multiple URLs that are in reality a variable of the same domain name:

- http://example.com/
- http://example.com/admin/
- http://example.com/yet-another-slug/admin/login/

This could be edited under a single URL: `http://example.com/*`

Can we also add a checkbox option to select the URLs we want to delete in bulk?

It's quite annoying to delete each URL one by one!

**Comment by varjolintu** [comment]
Just use `https://example/` as the entry URL. It works as a wildcard.
