### ISSUE TITLE
Things break if  password field has type=text

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc-browser#1029]
If a login form has ambiguous markup which prevents the detection of the password field:
1. the key icon does not appear even if the username field **is** detected
2. if the password field has type="text" instead of "password" (and even if the name/id indicate
that it is a password field), when using "choose custom login fields" and clicking on the username field, the password field overlay disappears and the user has to click "see more"
to unhide the field again in order to assign it as the password.
3. this may be a glitch in the logic for pruning overlays, or it might mean that the password field is not being detected as a password field at all.

## Expected Behavior
- Icon should always appear on the field detected as username
- in the case where multiple fields have "type=text", the detection code should be clever enough to realize that the one with "id/name='*password*'"  is the password field.

## Current Behavior
described above

## Possible Solution
- password field should get its own icon, just like username field and totp field do.
If it's missing, the user realizes something is wrong.
- tweak field detection code to rely on id/name when multiple fields appear with the same type.

## Steps to Reproduce (for bugs)

login.html
```
<html>

<head>
  <meta charset="utf-8">
  <title></title>
</head>

<body>
  <form novalidate="">
    <div class="accountForm" style="display: block;">
      <div class="row">
        <h3>Login</h3>
      </div>
        <fieldset>
          <input id="loginEmail" type="text" placeholder="Your Email" class="form-control">
          <input id="loginPassword" type="text" placeholder="Password" class="form-control">
          <button class="form-control btn btn-success">Log In</button>
        </fieldset>
    </div>
  </form>

```
**Note** that type for `loginPassword` is `text` and not `password`. 
1. Load this html
2. see that no icon appears

## Debug info

KeePassXC-Browser - 2.7.1

Note: was #1024

**Comment by varjolintu** [comment]
Things are working here as it should. Forms and input fields are handled as a combinations in the extension. This means a password field must have a corresponding username field. It also handles a single username and a single password fields. But if there are two fields that are identified as username fields, well, this is what Choose Custom Fields is for.

Checking for id/name of course is possible, but it's kind of rare to even find pages that use `type="text"` for password fields.

**Comment by anon324875693** [comment]
Understood. But both the `id` and the placeholder contain the string password, and yet the field isn't detected, I think that's a legit bug.

**Comment by anon324875693** [comment]
I don't know the reason, but solely on chrome they serve up an input with `type=text` and use [-webkit-text-security](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-text-security) to mask the password. Apparently it's a legacy thing now deprecated but still found in the wild.

**Comment by varjolintu** [comment]
We try to avoid any stupid non-standard methods. Some of the Chrome's methods are great examples.

**Comment by anon324875693** [comment]
In principle, would you accept a PR that checks element id/name for "password" if no password field was detected on the page?

**Comment by varjolintu** [comment]
I would. And I can make some when I have some extra time. (It's quite limited now)

**Comment by anon324875693** [comment]
The logic is spread out all over and it looks like its been modified to handle many corner cases, but there are no tests. So not a good choice for a first PR. Sorry, I would have liked to help.

**Comment by varjolintu** [comment]
I know the lack of tests, and I'm currently rewriting a PR for it. In the older version with the original test PR the extension used attributes that were added to the input fields, so identifying them in the tests were easy. We are doing that no longer, and the input fields are only visible inside the extension's internal variables. So all tests for content scripts needs to be rewritten.

**Comment by anon324875693** [comment]
How can I help?

**Comment by varjolintu** [comment]
Isn't it easier to just use Custom Login Fields for these kind of things?

**Comment by anon324875693** [comment]
It would be ok, but there's also https://github.com/keepassxreboot/keepassxc-browser/issues/1028 and the disappearing field issue with "Custom Login Fields"  that I mentioned in the bug report.

**Comment by kronenpj** [comment]
> Things are working here as it should. Forms and input fields are handled as a combinations in the extension. This means a password field must have a corresponding username field. It also handles a single username and a single password fields. But if there are two fields that are identified as username fields, well, this is what Choose Custom Fields is for.
> 
> Checking for id/name of course is possible, but it's kind of rare to even find pages that use `type="text"` for password fields.

Try: https://www.isc2.org/Sign-In

Here's the HTML code for username:
`<input id="signIn__input-email" class="form-element-field skipped" placeholder="  " type="input" required="" name="username" v-model="auth.userName" v-on:keyup="textKey()">`

Password:
`<input id="signIn__input-password" type="password" class="form-element-field skipped" type="text" name="password" placeholder=" " v-model="auth.password" v-on:keyup="textKey()" v-on:keyup.13="login">`

WHY they do this, I do not know.

For this site, custom login fields doesn't work because they have a TOTP prompt on the next page (same URL) that's ignored if custom fields are set, but the TOTP option isn't available until username/password has been submitted.

**Comment by varjolintu** [comment]
Let's close this one. Using Custom Login Fields is the preferred solution for these. The overlay problem is also solved.
