### ISSUE TITLE
[bug] password generator does not work

### ISSUE THREAD

**Issue by MauroMombelli** [keepassxreboot/keepassxc-browser#103]
if i try to generate a password for a field, I click the key icon, a popup apper (grafically "broken", see attacment), and when i try to "generate" nothing happen.

## Debug info
Error: Promised response from onMessage listener at @moz-extension://a9c06885-7e1c-4c0e-b3cf-a1d61cabd0d9/background/init.js:77:1 went out of scope

keepassxc-browser.js:278:25

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Firefox
Proxy used: NO

![image](https://user-images.githubusercontent.com/6372561/38191255-4467dabe-3668-11e8-95df-bbe1cd570dfb.png)

**Comment by varjolintu** [comment]
Is your database open and connected? Maybe there's a room for improvement: the password generator should work even if the database is closed.

**Comment by MauroMombelli** [comment]
yes it is, the only error in the setup I get is "Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?"

**Comment by varjolintu** [comment]
You need to reload.

**Comment by rugk** [comment]
In the screenshot the displayed entrophy is also kinda wrong… "123 bit" for an empty string?!

**Comment by varjolintu** [comment]
That's the default string. I need to change that as well.

**Comment by MauroMombelli** [comment]
@varjolintu what I need to reload? pressing reload on the page or on the plugin does nothing.

I can write in the password text area, copy and copy and fill wors, generate and the entropy calculator does not.

just to give a bit of context, is the change password form in the www.rcgroups.com forum

**Comment by varjolintu** [comment]
I think this is related to connection errors and not to the password generator itself because it needs a working connection to deliver generated passwords from KeePassXC's password generator.

**Comment by MauroMombelli** [comment]
But the software say it is connected and also seems able to save and reload
password, is just the generation that seems broken. I'm using a password
instead of a key to encrypt the DB.

**Comment by varjolintu** [comment]
Does autofill work normally? The next step is to debug the extension itself. In `keepass.js` the function `keepass.retrieveCredentials` put a breakpoint after the `keepass.sendNativeMessage` response.

**Comment by varjolintu** [comment]
Still having the issue?

**Comment by MauroMombelli** [comment]
yes, I just check and i dont have keepass.js but only keepass-browser.js and does not have the function you nominated. retriveCredential is a boolean and no sendNativeMessage.


As quick test i tried to generate a password on gmx.net for the free email, and the error i get is 

Error: "Promised response from onMessage listener went out of scope"
<anonymous>moz-extension://a9c06885-7e1c-4c0e-b3cf-a1d61cabd0d9/background/init.js:84:1

**Comment by varjolintu** [comment]
`keepass.js` can be found when inspecting the background page/scripts.

**Comment by MauroMombelli** [comment]
here what i get, please note i an not a we programmer so i don't know those tool more than basics stuff

![image](https://user-images.githubusercontent.com/6372561/43039683-f539bbac-8d32-11e8-8b5f-10eddec33562.png)

**Comment by varjolintu** [comment]
You can access `keepass.js` using `about:debugging` tab.

**Comment by MauroMombelli** [comment]
KeePassXC version: 2.3.3

gmx.net seems to work, ill do some more test in the next days

**Comment by varjolintu** [comment]
This is an old issue and I'm about to close it. But just to verify: are things working properly?
