### ISSUE TITLE
Keepassxc-browser refuses to connect to the database when google chrome beta is used on Linux Mint

### ISSUE THREAD

**Issue by dicksmits** [keepassxreboot/keepassxc-browser#1031]
Environment is Linux Mint 20 with Cinnamon desktop.
Chrome Beta was installed via apt by adding the source ppa:
 deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main

The user data is stored under $HOME/.config/google-chrome-beta
The extension in the browser stores file org.keepassxc.keepassxc_browser.json in $HOME/.config/google-chrome
In this case the database connect button does nothing and the extension does not see the running keepassxc. 

Moving the file to $HOME/.config/google-chrome-beta fixes this.

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 86.0.4240.53

**Comment by dicksmits** [comment]
Addition: after logging this issue, i found that this was reported earlier in 2018. At that time it was mentioned that this would be fixed in future versions.

**Comment by droidmonkey** [comment]
Keepassxc 2.6.0 has a custom browser option
