### ISSUE TITLE
Official Keepass XC browser plugin having troubles in Auto-Fill Login for Apple-ID

### ISSUE THREAD

**Issue by Msg1992** [keepassxreboot/keepassxc-browser#1033]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When trying to Auto-Fill Username and Password on Apple-ID Site the browser Plugin isn't filling out the username when you click for auto-type.

Dear Community. First of all.. Thanks to all of you for providing this great tool! I hope my reported "bug" is one, instead of a user problem. I can't reproduce it since I don't have somebody else that is using Keepass XC as well. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go on https://appleid.apple.com/#!&page=signin
2.  klick on the green symbol of the KeePass plugin so that it should fill the username in
3.  see that it's not working

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The username from the database entry is filled in

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Is doing nothing

## Context
[NOTE]: # ( Give us any additional information you may have. )
![image](https://user-images.githubusercontent.com/35180591/94999503-0de37b00-05ba-11eb-85f2-19a1c6b9d516.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.1
Revision: 9a35bba

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
I couldn't reproduce this with the current stable or develop branch. Make sure your entry has an URL that's either `https://apple.com` or `https://idmsa.apple.com`.

**Comment by Msg1992** [comment]
Hello varjolintu,

Thanks for your try! You're right. I added the wrong URL... I used https://appleid.apple.com/#!&page=signin. Now I can fill in the username by clicking on the Keepass extension button. 

But still, the extension is not recognizing the password field. I guess it is a similar issue with this apple website like on websites that uses a new page for the password. If you click on the "next" button only then the password field appears. But this is somehow not recognized by the browser extension. What I have to configure to make this work? Or is this an open issue?

Thanks again for this! I love Keepass XC so far :)

**Comment by varjolintu** [comment]
I need to test this some more. Maybe the dynamic input field detection misses it.

**Comment by Msg1992** [comment]
Hi varjolintu,

I got some more sites that have strange behavior:

**Google Login:**
https://accounts.google.com/Login/identifier?hl=de&flowName=GlifWebSignIn&flowEntry=AddSession
Here the field is not recognized (green button not shown). 

Username (First Site) | Password (Second Site)
--- | ---
![](https://user-images.githubusercontent.com/35180591/95052200-d1656b80-06ee-11eb-9a3c-2e368af06a7e.png) | ![](https://user-images.githubusercontent.com/35180591/95052319-04a7fa80-06ef-11eb-9251-4bb179b7060c.png)

I get it to work that it fills the username but the following page the password field is not recognized. This can only be done if I "teach in" the field as username field. See picture.
How can I "teach" also the password field on the next side? I am talking about the user defined login in the extension.

I read the following issue report: https://github.com/keepassxreboot/keepassxc-browser/issues/36  and added the site https://accounts.google.com. 


**OneDrive Login:** 
https://onedrive.live.com/about/de-de/signin/
Here the field is "recognized" by the browser extension, but it's not filling in the username when clicking on it. 
<p align="center">
<img src="https://user-images.githubusercontent.com/35180591/95052946-0625f280-06f0-11eb-9fd4-d5c8aca91754.png" width="400" height="400">
</p>

Surprisingly on [Microsoft Login](https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=13&ct=1601884250&rver=7.0.6738.0&wp=MBI_SSL&wreply=https:%2F%2Faccount.microsoft.com%2Fauth%2Fcomplete-signin%3Fru%3Dhttps%253A%252F%252Faccount.microsoft.com%252F%253Frefp%253Dsignedout-index%2526refd%253Dwww.google.com&lc=1031&id=292666&lw=1&fl=easi2) it works compared to the **OneDrive Login** perfect! Even the password is filled on the next side.

**Using Keepass** 
I still don't know if I have to add the URL also in the Browser Extension and in which format.... How should the URLs be added?

For the Keepass XC application I do it like that:
<p align="center">
<img src="https://user-images.githubusercontent.com/35180591/95052710-b2b3a480-06ef-11eb-9720-dbe9e6d44e28.png" width="800" height="150">
</p>

In the Browser Extension I do it always like this:
<p align="center">
<img src="https://user-images.githubusercontent.com/35180591/95054707-8d746580-06f2-11eb-82da-45cfcb9f27be.png" width="800" height="400">
</p>

I want to ensure that I add it correctly to don't steal your time for debugging an issue that is only caused by myself.

Am I doing something wrong or is this a real issue on some sites? 

Thanks and Greets Maximilian

**Comment by varjolintu** [comment]
We are adding those common sites to this PR so users don't have to add those URL's to Site Preferences manually: https://github.com/keepassxreboot/keepassxc-browser/pull/1010.

This PR also addresses the Apple login problem with the password field, and I'll check those Google and Live sites too if it's possible to improve the login flow.
