### ISSUE TITLE
(Brave) Cant use the extension when installed through the .zip file

### ISSUE THREAD

**Issue by Luis-L-B** [keepassxreboot/keepassxc-browser#1038]
## Expected Behavior
I should be able to see the window where I can grant the extension accses to my database
If I install the extension from the Chrome Web store the extension works as expected

## Current Behavior
I first get the message saying that the connection to KeePassXC was not successful and that I should check if the Browser Intigration for KeePassXC is enabled (It is). If I then klick refresh I get a message "The Key exchange was not succsesfull" 

## Steps to Reproduce (for bugs)
1. Download the zip from the Github release Page 
2. Unzip it 
(2,5 Enable the Developer mode in the Extension menu)
3. Select the extension and install it in braves extension menu
4. Open the floating Window (Or what its called not the full page with all the Settings)
5. Click on refresh

## Debug info
Connecting to native messaging host org.keepassxc.keepassxc_browser
Failed to connect: Access to the specified native messaging host is forbidden.
Error: No content script available for this tab.

KeePassXC - {2.6.1-2}
KeePassXC-Browser - {1.7.1}
Operating system: Arch Linux (5.8.14-arch1-1)
Browser: Brave (Chromium)

**Comment by varjolintu** [comment]
You need to modify the JSON script file manually: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

**Comment by Luis-L-B** [comment]
I added the ID under ~/.config/chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json but it didnt work, same behaviour. I tried installing installing the extension like I did in brave under Chromium and it works perfectly there without any modification. I guess its a Brave issue?

**Comment by varjolintu** [comment]
Shouldn't it be under `~/.chromium/`? Brave sometimes uses Chrome/Chromium config path instead of its own (dunno why).

**Comment by Luis-L-B** [comment]
That folder doesnt exsist. The ~/.config/chromium folder exsisted before I installed chromium with the keepassxc json file

**Comment by varjolintu** [comment]
The official path for Brave is `.config/BraveSoftware/Brave-Browser/NativeMessagingHosts`. Does that work?

**Comment by Luis-L-B** [comment]
Editing the file in that folder worked, thank you so much, At first the changes I made were removed after restarting brave, after that I needed to edit the file again and click on the refresh button like 15 times because I always got "key exchange not successful" but then I got the windows where I had to grant access to my database and it works perfectly now. Again thank you
