### ISSUE TITLE
No save banner for gmail

### ISSUE THREAD

**Issue by msVirk** [keepassxreboot/keepassxc-browser#1042]
## Expected Behavior

I am connected to my password's database using browser extension, but when I enter credentials for gmail, no save banner is showing up.

## Current Behavior

I am unable to save login credentials for gmail. KeePassXC doesn't show the save login banner. However, I tried few other websites and it is working on them. I have used chrome and Microsoft edge browsers, and this occurs on both of them.
My KeePassXC version is 2.6.1, and browser extension version is 1.7.1.

## Steps to Reproduce (for bugs)

1. Install chrome or Microsoft edge on windows 10 Home Single Languae Edition version 2004.
2. Install KeePassXC and browser extension and connect to database.
3. Try login in gmail, login is successful but no save banner is shown by KeePassXC.
4. No other browser extension is installed.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
This probably fixes it, but gotta test it to be sure: https://github.com/keepassxreboot/keepassxc-browser/pull/1015

**Comment by varjolintu** [comment]
I'm going to add the fix to #1010.

**Comment by varjolintu** [comment]
I've been able to solve this when user clicks the Next button, but when submitting the form using keyboard, the `submit` event doesn't trigger at all.
