### ISSUE TITLE
Use one shortcut for standard fields (username, password, otp)

### ISSUE THREAD

**Issue by mrahs** [keepassxreboot/keepassxc-browser#1043]
## Expected Behavior

The extension already detects the input type and fills in username or password accordingly. The OTP field
is also auto-detected and can be filled by clicking the overlayed icon. It would be great if the same shortcut
triggered filling the OTP as well rather than having to use another one.

## Current Behavior

The shortcut for filling the OTP is different from the one used to fill username and password.

## Possible Solution

The unified shortcut should fill the value according to the detected input type. In case the input detection fails
or the input is not marked up properly, the auto-complete menu can be used to let the user decide which field to fill.
An alternative shortcut can also be used to trigger the menu in case the user wishes to fill a different field from the one
the extension detected.

I know this brings us back to two shortcuts, but the improvement is worth it imo. That is, one shortcut to fill
all three standard fields automatically, and another one to choose which field to fill, including custom attributes as in #993.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Win
Browser: Firefox

**Comment by droidmonkey** [comment]
Not a good idea, the shortcuts are there to overcome situations where the fields are NOT auto detected properly.

**Comment by mrahs** [comment]
Reading the proposal again, I think I just described #993, but for any field not just custom ones.

Would you agree that it's worth having a way to let the user choose which field to fill (using the auto-complete menu for example)?
It would useful for websites that ask for unusual combinations such as an email or a card number instead of a username. Or a contract number, a certificate number and password as is the case for some insurance websites.

If that sounds reasonable, please feel free to merge this with #993.

**Comment by mrahs** [comment]
I think it's also worth making the first shortcut work for username, password and otp (when detected properly), but defaults to username. There are already shortcuts for password and otp only for when the detection fails.
