### ISSUE TITLE
Firefox 81 Integration issues

### ISSUE THREAD

**Issue by Shaggy1444** [keepassxreboot/keepassxc-browser#1045]
Using:

KeePassXC - Version 2.6.1
Revision: 9a35bba
Distribution: Snap

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 5.4.0-48-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

Browser Integration:
ran keepassxc-snap-helper.sh script after installing Firefox plugin

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 81.0

Issue:
-everything integrates (database accessible; able to create accounts using browser interface and saved to KPXC)
-setup custom login fields
-tried with multiple Gmail accounts
-nothing works (depress key icon in username field displays nothing)
-even right-click on username(id) field and selecting "fill username and password" on another site doesn't work
-everything looks great and integrates great, or, well enough, but <no auto-username and/or password> isn't working

Would be nice if everything worked.

**Comment by droidmonkey** [comment]
Unrelated to Firefox and this is a duplicate
