### ISSUE TITLE
Browser cannot fill credential on Charles Schwab bank site

### ISSUE THREAD

**Issue by minhchuvolam** [keepassxreboot/keepassxc-browser#1046]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When visiting this site https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx
The icon for the KPXC is shown but clicking on it does not fill the credential.  I tried custom login fields but still not work.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Install browser integration
2. Visit https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx
3. Click KPXC icon to fill credentials

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Fill credentials on this site https://client.schwab.com/Login/SignOn/CustomerCenterLogin.aspx

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Credentials not filled

## Context
[NOTE]: # ( Give us any additional information you may have. )
Tested on both Firefox and Brave

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome/Mate
Windowing System: X11

**Comment by minhchuvolam** [comment]
@droidmonkey Are you on 2.4.3?

**Comment by droidmonkey** [comment]
No, but shouldn't make a difference. 2.4.3 is very old..

**Comment by minhchuvolam** [comment]
I tested with 2.6.1 still not working. Weird.

**Comment by varjolintu** [comment]
@minhchuvolam What is your entry URL?

**Comment by minhchuvolam** [comment]
@varjolintu Apparently the link I posted is no longer reachable from the main site https://www.schwab.com/.  But it still not working even on the this main site.  Would you please test with browser extension 1.7.1.  I am on Ubuntu 20.04.

**Comment by varjolintu** [comment]
@minhchuvolam You didn't answer my question.

**Comment by minhchuvolam** [comment]
@varjolintu I guess there is no entry URL.  I grab that URL after I logout.  That was a long time ago.  The entry URL now should be the main site.

**Comment by varjolintu** [comment]
@minhchuvolam If the login page is under `https://client.schwab.com` you must use that or `https://schwab.com` as your entry URL. The latter works as a wildcard to `*.schwab.com`.

**Comment by minhchuvolam** [comment]
@varjolintu Oh. That's what you mean.  I will try it. Thanks.

**Comment by minhchuvolam** [comment]
@varjolintu It works. Thanks. I guess we can close this issue now.

**Comment by lxg208** [comment]
Looks like the issue is coming back. It worked for me earlier but now it's not working. 

I'm using KeePassXC 2.7.6 and KeePassXC-Browser 1.8.11 (2024-01-06). Error message is "no logins found, https://sws-gateway-nr.schwab.com"

**Comment by varjolintu** [comment]
@lxg208 The issue is already fixed for the next version. It's related to the iframe permission changes.
