### ISSUE TITLE
Bug - Cannot Enter Login and Password for Many Websites

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc-browser#1048]
## Expected Behavior
It seems to be happening more these past couple of months.  The icon for the login and password does not show up for fields in certain websites.  Just now, I can't fill in at: https://www.biggerpockets.com/forums

But, it's been happening in Amazon.com, Gmail.com, etc.  It used to work but now I have to type my login manually.  Sometimes, after typing in manually, I might be given the options for the passwords.

## Current Behavior
I simply enter the website and KeePassXC doesn't recognize the login and password fields.

## Possible Solution
I have been tinkering with the settings to see if that might fix it but unfortunately, it doesn't.  If you, guys could help in any way, I would give you my left hand.  (I need my right hand to still type.)

## Debug info
(I don't know if this is what you want but tried to follow the directions)

    at ui.js:53
ui.js:53 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null
    at ui.js:53
keepassxc-browser.js:1681 initContentScript error:  TypeError: Cannot read property 'nodeType' of null
    at keepassxc-browser.js:1579
    at Array.some (<anonymous>)
    at Object.kpxcObserverHelper.ignoredNode (keepassxc-browser.js:1579)
    at Object.kpxcObserverHelper.getInputs (keepassxc-browser.js:1458)
    at Object.kpxcFields.getAllPageInputs (keepassxc-browser.js:342)
    at Object.kpxc.initCredentialFields (keepassxc-browser.js:1046)
    at async initContentScript (keepassxc-browser.js:1656)
keepassxc-browser.js:1681 initContentScript error:  TypeError: Cannot read property 'nodeType' of null
    at keepassxc-browser.js:1579
    at Array.some (<anonymous>)
    at Object.kpxcObserverHelper.ignoredNode (keepassxc-browser.js:1579)
    at Object.kpxcObserverHelper.getInputs (keepassxc-browser.js:1458)
    at Object.kpxcFields.getAllPageInputs (keepassxc-browser.js:342)
    at Object.kpxc.initCredentialFields (keepassxc-browser.js:1046)
    at async initContentScript (keepassxc-browser.js:1656)
js-agent.newrelic.com/nr-1184.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
keepassxc-browser.js:160 Uncaught (in promise) TypeError: Cannot read property 'elements' of undefined
    at Object.kpxcForm.getFormSubmitButton (keepassxc-browser.js:160)
    at Object.kpxc.fillInCredentials (keepassxc-browser.js:858)
stats.pusher.com/timeline/v2/jsonp/2?session=NjQ4OTA5NTMz&bundle=MQ%3D%3D&key=NzM5YjVlZTZjN2QxNWRjNjQ3ZmY%3D&lib=anM%3D&version=NC4zLjE%3D&cluster=bXQx&features=WyJ3cyJd&timeline=W3siY2lkIjoxLCJzdGF0ZSI6ImNsb3NlZCIsInBhcmFtcyI6eyJjb2RlIjo0MDA5LCJyZWFzb24iOiJDb25uZWN0aW9uIG5vdCBhdXRob3JpemVkIHdpdGhpbiB0aW1lb3V0Iiwid2FzQ2xlYW4iOnRydWV9LCJ0aW1lc3RhbXAiOjE2MDI3ODcyMzcwNjh9LHsic3RhdGUiOiJkaXNjb25uZWN0ZWQiLCJ0aW1lc3RhbXAiOjE2MDI3ODcyMzcwNjl9XQ%3D%3D:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/lodash.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

KeePassXC - Version 2.6.1
KeePassXC-Browser Version: 1.7.1
Operating system: Windows 10
Browser: Chrome

**Comment by varjolintu** [comment]
Try the same with KeePassXC 2.6.0 or 2.6.2 snapshot.

**Comment by CerebralFreeze** [comment]
I'm not a computer person so I didn't know what you meant for a couple of days.  I just figured out that you mean that I should uninstall the KeePassXC version I have installed and reinstall the previous version?

If this is true, how come it doesn't happen to everyone else and they aren't complaining?

**Comment by varjolintu** [comment]
@CerebralFreeze The are/did: https://github.com/keepassxreboot/keepassxc/issues/5299

**Comment by powerman** [comment]
I'm not sure this happens because of KeePassXC, it looks more like a browser plugin issue because login/pass fields are either not detected at all, or only one of them is detected.

My issue sounds very similar to this one: previously I was able to login on websites which uses separate pages for login and password, but now this isn't working. I've tried to play with different options, add login or pass fields manually - nothing helps.

Actually I don't really understand how to add manually such fields - it looks like right now I can't mark some field as "login" and continue using website to submit login and see second page with password field, instead I have to skip "password" and "one time" fields and confirm before I'll be able to submit form and get password field… then I can repeat the procedure, but this time I have to skip "login" field because it's not on the screen anymore… which result in recording either login or password fields but not both.

Example of websites which have this issue:
- https://next.privat24.ua/ - banking (login button is at top right corner, login form is loaded from another domain, you can use login 972222222 for debugging, to see password prompt)
- https://account.kyivstar.ua/cas/login - cell phone provider (you can use login 380674961489 for debugging, to see password prompt)

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 81.0

**Comment by powerman** [comment]
It looks like I've found a workaround!

In KeePassXC-Browser's settings I've checked `[✓] Automatically fill in single-credential entries.` and it starts working again… but it auto-fills forms, which I dislike, so I've unchecked it `[ ] Automatically fill in single-credential entries.` and, wow, it continue to work in manual mode, just as before!

**Comment by CerebralFreeze** [comment]
> @CerebralFreeze They are/did: [keepassxreboot/keepassxc#5299](https://github.com/keepassxreboot/keepassxc/issues/5299)

I uninstalled and reinstalled into a different version and it still does it.  I have a hunch that the websites themselves are increased their security measures and changed something so KeePassXC is having trouble with identifying the fields.  This just happened to slowly from website to website about 1-2 months ago.  And, it's like spreading to other websites.  It's frankly annoying and making me want to switch out of KeePassXC although I'm going to still stick it out with you, guys.  Just being honest, that's all so it helps you so you don't lose users.

**Comment by CerebralFreeze** [comment]
> It looks like I've found a workaround!
> 
> In KeePassXC-Browser's settings I've checked `[✓] Automatically fill in single-credential entries.` and it starts working again… but it auto-fills forms, which I dislike, so I've unchecked it `[ ] Automatically fill in single-credential entries.` and, wow, it continue to work in manual mode, just as before!

Powerman,

Thanks!  I feel exactly the same as you.  I don't want to auto-fill the entries.

The question becomes is the recent trouble with filling fields is due to a 3rd party?  Some sort of virus?  Then, that means they could have interjected something between the website acknowledging the login/password and the website starting up so that they could steal our login/password.

If it's the website developers just changing something to increase security, it doesn't matter because they know our logins anyway.

I feel unsafe checking that box to automatically fill in single credential entries.

Wait, I get it.  You're saying to check and uncheck it and it'll work again.  Thanks, I'll try it!

**Comment by varjolintu** [comment]
@powerman Kyivstar sited worked fine when I added the URL to Site Preferences (extension settings) with Username-only Detection enabled.

Privat24 uses an iframe for logging in, which is under a different subdomain. This means your entry URL needs to be `https:/login-widget.privat24.ua` or just `https://privat24.ua` for accepting any subdomain.

**Comment by varjolintu** [comment]
So. If you are having problems with some fields, you can right-click the input field from your browser and select _Inspect_ to see if the actual login page URL is inside an iframe.

Every single-login field that has username field and password field in separate pages, you'll need to use the Username-only Detection via Site Preferences. 

This pull request will add the most common sites automatically to an internal list: https://github.com/keepassxreboot/keepassxc-browser/pull/1010

**Comment by powerman** [comment]
@varjolintu Looks like I had an issue with these (and some other) sites because of some bug related to KeePassXC-Browser's settings - after checking and unchecking one option (mentioned above in https://github.com/keepassxreboot/keepassxc-browser/issues/1048#issuecomment-711168961) these sites begin to work. Maybe something goes wrong with settings because of updating KeePassXC-Browser at some moment, not sure.

**Comment by varjolintu** [comment]
@powerman It's possible. Sometimes you'll need to restart your browser.

**Comment by powerman** [comment]
This has nothing with restarting browser - I had this issue in several (4-8) weeks, browser was restarted and updated several times within this period.

**Comment by varjolintu** [comment]
@powerman If you encounter the situation again, please take a look at the JavaScript console if there's any errors.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
