### ISSUE TITLE
Deactivated Entrys can't be reactivated

### ISSUE THREAD

**Issue by MG-96** [keepassxreboot/keepassxc-browser#1050]
## Expected Behavior
Ability to reactivate a deactivated Entry for a specific website.
Display of deactivated Entrys in Keepassxc-browser's Sitesettings. (or something like that)

## Current Behavior
When an entry is deactivated for a site there is no way to undo this.

## Possible Solution
List entrys in Sitesettings or enable users to reopen the banner when on the specific website.

## Steps to Reproduce (for bugs)

This has been tested on sites for wich multiple entrys were stored.
1. Open a site and deactivate one of the entrys for that site in the open banner
2. Tick the remember option
3. Close the Banner
4. No way to undo this ¯\\\_(ツ)_/¯

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 2.6.1
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
You can do this from KeePassXC. Edit the entry, go to Properties and remove the _KeePassXC-Browser Settings_ key.

**Comment by droidmonkey** [comment]
We should bubble this up into the browser settings tab for the entry. Even a simple button that clears the deny setting for starters.
