### ISSUE TITLE
KeepassXC doesnt recognize gog.com Login Frame when url is www.gog.com

### ISSUE THREAD

**Issue by Linkinsoldier** [keepassxreboot/keepassxc-browser#1051]
## Steps to Reproduce
1.  Go go https://www.gog.com/
2.  click on login / "einloggen"
3.  try to input the password via KeepassXC (and the required addons)

## Expected Behavior
It is possible to input password as usual - no matter if Keepass data has the url https://www.gog.com

## Actual Behavior
Button appears but there is no input on clicking it when keepass login data url is https://www.gog.com. 
However when I change it to https://gog.com it now works. Is this expected? I would expect that www.gog.com is the same as *.gog.com to keepass

## Context
doesnt matter if cookie provides email adress or email adress is entered manuall

KeePassXC - Version 2.6.1
Revision: 9a35bba

Operating System: Windows 10
Mozilla Firefox

![grafik](https://user-images.githubusercontent.com/24806068/96556139-e9291c00-12b8-11eb-9499-313dc993aece.png)

**Comment by varjolintu** [comment]
Use `https://gog.com` or `https://auth.gog.com` as your entry URL.

**Comment by Linkinsoldier** [comment]
Thank you

**Comment by scharmach** [comment]
> 
> 
> Use `https://gog.com` or `https://auth.gog.com` as your entry URL.

For anybody finding this in the future, like me:

They seem to have changed `https://auth.gog.com` to `https://login.gog.com`.

Guess this is why it's better to use `https://gog.com` anyway.
