### ISSUE TITLE
Method to fill username only unclear

### ISSUE THREAD

**Issue by Packbat** [keepassxreboot/keepassxc-browser#1052]
## Expected Behavior

When I'm logging into a website which has two stages - one where only a username field is available, followed by one where a password becomes available as well - my instinct is to look for an option to fill username only, and no such option is listed.

## Current Behavior

After I selected "Fill Username and Password", the username filled and no apparent error message occurred.

## Possible Solution

If this is how the browser integration is intended to be used, incorporating a clarifying note into the UI - like "Fill Username and (if available) Password" or a parenthetical on the line below saying "(If no password field is available, this will fill username only)" - would make the process clearer.

If this is not how the browser integration is intended to be used, a separate "Fill Username Only" option would be appropriate.

**Comment by varjolintu** [comment]
Easiest approach is to add the site to extension's Site Preferences tab and enable _Username-Only Detection_ option. This ensures the single username field is detected correctly.

**Comment by Packbat** [comment]
That is a very good feature to know about!

...although, bizarrely, the site I was logging into today has a login field in a mouseover popup that disappears if I either move the mouse to select a right-click menu item _or_ mouse over the KeyPassXC-Browser symbol, so it looks like I'll have to keep using the Alt+Shift+U keyboard shortcut.

**Comment by Packbat** [comment]
...I don't understand why this issue was closed. While the information about the Site Preferences tab is useful, it doesn't affect the section of the UI I was talking about - this isn't a "the system is broken" issue, this is a "the system UI is unclear" issue.

**Comment by varjolintu** [comment]
Because when talking about the UI, this is a duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/159

**Comment by Packbat** [comment]
Oh, nice! I didn't find that when I searched for it - thanks for the link!
