### ISSUE TITLE
Keyboard shortcut to fill username and password does not work if username field does not have focus

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc-browser#1053]
## Expected Behavior

Previously (I think maybe before version 1.7.0) it was possible to just press `Alt+Shift+u` to fill out username and password on any website, even if the username field was not focused.
I would like to have the "old" behaviour restored.

## Current Behavior

Now, it only works on pages where the username field automatically gets the focus after loading, i.e. the cursor is positioned in the username field.
If the username field is not focused, pressing `Alt+Shift+u` does not have any effect.

## Steps to Reproduce (for bugs)

1. Open https://www.netflix.com/de/Login
2. The KeepassXC Icon appears in the username field
3. Press `Alt+Shift+u`
4. Nothing happens
5. Click into the username field
6. The KeepassXC popup to select the username / password combination pops up.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 81.0

**Comment by Drowze** [comment]
I can confirm the same for:

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: MacIntel
Browser: Mozilla Firefox 82.0
