### ISSUE TITLE
Firefox 81.0 64-Bit: add-on not active on start, needs manual dis-/enable

### ISSUE THREAD

**Issue by 2019-05-10** [keepassxreboot/keepassxc-browser#1054]
Keepassxc add-on is not active when starting Firefox.
Add-on is marked as enabled.
I need to open the add-ons manager and manually toggle the switch to "disabled" and back to "enabled" to make it appear and active.

In Vivaldi it works.

## Expected Behavior
Add-on is active (icon shown) and proposes credentials.

## Current Behavior
Add-on is enabled.
Icon is not visible.
Credentials are not proposed.

## Steps to Reproduce (for bugs)
1. start FF
2. Keepassxc icon is missing in the area to the right of the url/search field
3. go to a site requiring login
4. no keepassxc icon in the user name or password fields, no banner to create a new entry nor any proposals

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Try this with a new temporary profile?

**Comment by 2019-05-10** [comment]
Worked.
Starting again with the default profile, the plugin was enabled also.

Next start, plugin again was inactive.

**Comment by varjolintu** [comment]
This happens only with one computer and one user?

**Comment by 2019-05-10** [comment]
Can't say since I currently have no access to another computer.
FYI: I am now at FF 82, the issue persists.

Can you give me some pointers on how to debug the plugin's initialization?

**Comment by varjolintu** [comment]
Go to `about:debugging#/runtime/this-firefox` and inspect the exception. You can put breakpoints at the start of `init.js`.

**Comment by 2019-05-10** [comment]
`about:debugging#/runtime/this-firefox`

shows:
`Warning details
Reading manifest: Warning processing version_name: An unexpected property was found in the WebExtension manifest.`

and

`Warning details
Reading manifest: Warning processing key: An unexpected property was found in the WebExtension manifest.`

![image](https://user-images.githubusercontent.com/50481865/97563033-cf878300-19e2-11eb-9f7b-c8b756c0727a.png)

It's just a warning, though.

**Comment by varjolintu** [comment]
That has nothing to do with your situation.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
