### ISSUE TITLE
Librus - fields are detected, but can't be filled without waiting

### ISSUE THREAD

**Issue by jedenastka** [keepassxreboot/keepassxc-browser#1058]
## Expected Behavior

I can fill the login and password fields on Librus website.

## Current Behavior

I can fill the login and password fields on mentioned website, however the fields and my credentials from DB are detected:

![image](https://user-images.githubusercontent.com/33988779/96892348-dc0f5700-1489-11eb-9342-df4df1f63405.png)

![image](https://user-images.githubusercontent.com/33988779/96892408-e893af80-1489-11eb-9c1a-683b89520ede.png)

![image](https://user-images.githubusercontent.com/33988779/96893776-5ab8c400-148b-11eb-82a6-af09ca4ecc8d.png)

Every other website I use the extension with works fine.

It sometimes works if I wait several minutes with the tab open (randomness I guess). After refreshing or opening another tab with the site, it breaks again.

## Steps to Reproduce (for bugs)

1. Create an database entry with username, password and URL https://portal.librus.pl/rodzina/synergia/loguj.
2. Go to https://portal.librus.pl/rodzina/synergia/loguj. Notice how the fields are detected
3. Check the extension menu. Notice how credentials are detected.
4. Click on the username field. Notice how the usual droplist doesn't show.
5. Rightclick on the field, select the `KeePassXC Browser` option, then `Fill username and password`. Notice how nothing happens.
Additional step (might not work):
6. Leave the tab open in background. After several minutes, repeat steps 4 and 5 and notice how it now fills the credentials in.

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64 (Debian Sid)
Browser: Chromium 83.0.4103.116

**Comment by varjolintu** [comment]
The login form is inside iframe with a different URL. Just put `https://librus.pl` as your entry URL and it works.
