### ISSUE TITLE
No username shown, after manual choice only the first will be used

### ISSUE THREAD

**Issue by tinokorth** [keepassxreboot/keepassxc-browser#1059]
I've got for example lots of google accounts.
At https://accounts.google.com/ the login fields are not recognized and no "green icon" is shown.
When using the manual fillout function (right click into username field / fill out username & password) the first entry of a list of usernames will be used instead of a dropdown list to choose the right username.

## Expected Behavior
The username field shows the green icon to fill out the username.

## Current Behavior
No icon is shown and the manual function inserts the first entry of a list of usernames.

## Possible Solution
unknown

## Steps to Reproduce (for bugs)
1. insert lots of google accounts in your KPXC database.
2. visit https://accounts.google.com/
![image](https://user-images.githubusercontent.com/46132772/96912994-5d271800-14a3-11eb-811d-f4b3bd53383c.png)
3. right click into username field and use function "fill out username and password"
![image](https://user-images.githubusercontent.com/46132772/96913357-cc047100-14a3-11eb-8858-a21b9cacfba0.png)
4. the first entry KPXC finds will be filled out.
![image](https://user-images.githubusercontent.com/46132772/96913579-1980de00-14a4-11eb-9ad4-124a1565f543.png)

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.1
Operating system: Win32
Browser: Chrome/Chromium 85.0.4183.121

**Comment by tinokorth** [comment]
An additional info:

When visiting the Google Login page the icon in the browser bar shows

![image](https://user-images.githubusercontent.com/46132772/96913942-9ad87080-14a4-11eb-83e0-0d7f69d899a0.png)

And after using the right click function to put in the username the icon shows

![image](https://user-images.githubusercontent.com/46132772/96914004-b0e63100-14a4-11eb-835a-67ad91302dbf.png)

I don't know if this is a boring info or not. ;-)

**Comment by varjolintu** [comment]
You'll have to manually put `https://accounts.google.com/*´ to Site Preferences tab in the extension settings and enable _Username-only Detection_. However, the next version of the extension does this automatically to the most common sites, Google included.

**Comment by tinokorth** [comment]
Hello varjolintu, I've already done this, but it does not work. :-(

**Comment by varjolintu** [comment]
@tinokorth Even with 1.7.2? If you still have a Site Preferences setting for this page, you can delete it.
