### ISSUE TITLE
Plugin shows "checking status" in Firefox (works in Chrome)

### ISSUE THREAD

**Issue by netshin** [keepassxreboot/keepassxc-browser#1061]
### Expected Results:
Clicking FireFox Extension should show status of database and allow locking if connected.
Login information should be filled in relevant forms.
### Actual Behavior:
1. a rotating circle with "Checking Status" is displayed when clicking the browser window in Firefox. No login information is available.
This works a expected in Chrome and previously worked on Firefox as well.

2. Using the "settings" link in the displayed window opens General Settings as required, however this window is not operational - can't change settings, unable to use e.g. navigation menu to display "about" or any other control.

### Steps to Reproduce:
1. install Keepass - enable browser integration, open a database
2. start Firefox, install keepassxc latest extension (also enabled in Private Browsing mode)
3. attempt to connect to existing database by clicking the Keepassxc icon in toolbar - rotating circle with "Checking Status..." is displayed and never changes.
or
4. click Settings
attempt to use any of the displayed controls - click "about" - nothing happens.

### Context
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by varjolintu** [comment]
Can you check the JavaScript console for any error messages? You can see background script logs using `about:debugging`.

**Comment by netshin** [comment]
I see these repeating:
(adding screenshot to make it more readable)
`Uncaught (in promise) TypeError: page.settings is undefined
    keePassXCUpdateAvailable moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/keepass.js:958
    generateIconName moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:67
    show moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:14
    showDefault moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:46
keepass.js:958:9
page.initSettings error: Error: An unexpected error occurred page.js:130:17
onLoadSettings error: undefined event.js:41:17
UnknownError: The operation failed for reasons unrelated to the database itself and not covered by any other error code. ExtensionStorageIDB.jsm:831
Error: Cannot show default popup: TypeError: right-hand side of 'in' should be an object, got undefined browserAction.js:32:17
Uncaught (in promise) TypeError: page.settings is undefined
    keePassXCUpdateAvailable moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/keepass.js:958
    generateIconName moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:67
    show moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:14
    showDefault moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:46
keepass.js:958:9
Error: Cannot show default popup: TypeError: right-hand side of 'in' should be an object, got undefined browserAction.js:32:17
Uncaught (in promise) TypeError: page.settings is undefined
    keePassXCUpdateAvailable moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/keepass.js:958
    generateIconName moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:67
    show moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:14
    showDefault moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:46
keepass.js:958:9
Cannot send activated_tab message:  Error: Could not establish connection. Receiving end does not exist.
    switchTab moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/page.js:158
page.js:159:17
Error: Cannot show default popup: TypeError: right-hand side of 'in' should be an object, got undefined browserAction.js:32:17
Uncaught (in promise) TypeError: page.settings is undefined
    keePassXCUpdateAvailable moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/keepass.js:958
    generateIconName moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:67
    show moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:14
    showDefault moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/browserAction.js:46
keepass.js:958:9
Cannot send activated_tab message:  Error: Could not establish connection. Receiving end does not exist.
    switchTab moz-extension://5a71d14e-d5ad-7340-a344-1e7d73998dad/background/page.js:158`

![keepassxc firefox plugin debug log](https://user-images.githubusercontent.com/10653668/97046975-bb1d3380-1567-11eb-862d-437a07946caf.png)

**Comment by varjolintu** [comment]
This means the extension cannot load its settings from localStorage. Does reinstalling it help? Or using a new temporary profile?

**Comment by netshin** [comment]
using a new profile resolves this. I retain the original profile - will be happy to assist if you wish to debug - if not, I'll just use the new one. Thanks for your help!
