### ISSUE TITLE
KeepassXC Icon disappears after 0.5sec on proshop.dk

### ISSUE THREAD

**Issue by criemen** [keepassxreboot/keepassxc-browser#1063]
## Expected Behavior
The Firefox extension is able to provide an icon to fill in credentials on https://www.proshop.dk/.
## Current Behavior

On https://www.proshop.dk/, when clicking on "Log ind", a dropdown opens with username/password fields.
There is a KeepassXC icon visible for about 0.5sec in the username field, which then disappears, leaving no automatic way to fill in credentials.

## Steps to Reproduce (for bugs)
See current behaviour

## Debug info

No errors in the JS console visible.

KeePassXC - 2.6.2
KeePassXC-Browser -     1.7.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
They use a Glyphicon to cover the KeePassXC icon.
