### ISSUE TITLE
Does not detect login fields/show keepassxc icon within an iFrame (cloud.huawei.com)

### ISSUE THREAD

**Issue by trettet** [keepassxreboot/keepassxc-browser#1067]
## Expected Behavior

Should show keepassxc icon besides login field

## Current Behavior

Does not show keepassxc icon on login field

## Possible Solution

Detect login fields in iFrame

## Steps to Reproduce (for bugs)

1. Go to https://cloud.huawei.com/
2. See login field
![image](https://user-images.githubusercontent.com/1276544/97095224-59f07f80-168f-11eb-8392-1ebfcda7819f.png)

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.1
Operating system: Win 10 2004.19041
Browser: Chrome

**Comment by trettet** [comment]
Going to the [iframe source](https://id5.cloud.huawei.com/CAS/portal/cloudIframeLogin.html?loginUrl=https%3A%2F%2Fcloud.huawei.com%3A443%2Fothers%2Flogin.action&service=https%3A%2F%2Fcloud.huawei.com%3A443%2Fothers%2Flogin.action&loginChannel=1000002&reqClientType=1&lang=en-us&countryCode=cn&lowLogin=true&scenesType=0&time=1603580645587) works
![image](https://user-images.githubusercontent.com/1276544/97095311-704b0b00-1690-11eb-9b13-5b04a6cd03fe.png)

**Comment by droidmonkey** [comment]
That is by design

**Comment by trettet** [comment]
@droidmonkey If i right click on the iframe and click on Reload source
![image](https://user-images.githubusercontent.com/1276544/97095367-01ba7d00-1691-11eb-9fc9-46a6acd187df.png)
The keepassxc icon is back
![image](https://user-images.githubusercontent.com/1276544/97095377-16971080-1691-11eb-9050-1d33b7851aec.png)
Do I need to change something on my KeepassXC browser plugin settings?

**Comment by trettet** [comment]
The entire huawei.com domain is also set on my KeepassXC app, and the iframe source is on huawei.com? Is this by design as well?

**Comment by trettet** [comment]
I can see on #1058 that there were no issues on detecting fields within an iframe....

**Comment by droidmonkey** [comment]
The url for the entry is https://huawei.com ?

**Comment by varjolintu** [comment]
That page has some strange script that marks the username field `readonly` when it's not focused.
