### ISSUE TITLE
Multiple accounts: The toolbar icon shows all accounts, whereas the green lock only fills first username (no popup) 

### ISSUE THREAD

**Issue by ericschdt** [keepassxreboot/keepassxc-browser#1069]
You can use the toolbar icon to choose one of your accounts. However, if you click on the green lock which is displayed within in a username field on the website, only the details of the first account in the list is filled in. 

I believe in earlier versions this worked as intended.

## Expected Behavior
Show a popup context menu to select the desired account

## Current Behavior
First username is selected.

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux
Browser: Firefox 82.0

**Comment by varjolintu** [comment]
If there are multiple credentials, clicking the icon will show the Autocomplete Menu. I use this feature daily, so I haven't reproduced your problem.

Only if single credentials are found, the only entry is filled.

If you encounter this problem with every site, can you give an example of the site where this happens + the URL's you use in your entries?

**Comment by ericschdt** [comment]
I now have set `Activate Autocompletion for Username Fields.` -- I am not sure if this was the trick, but now it works as intended. Weird. Thank you anyway!
