### ISSUE TITLE
fetchclcdetdtcredbhdfjdrdnjtgggbulffbgbnuuui

### ISSUE THREAD

**Issue by jpjpjp** [keepassxreboot/keepassxc-browser#1072]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by phoerious** [comment]
Thanks, we'll definitely take that into account.
