### ISSUE TITLE
Unable to get password fill to work on ebay.com

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#1073]
## Expected Behavior

When signing in to ebay.com, the first username field should have a drop-down of the keepass username. After that form is submitted, the password field should have a drop-down of the keepass password.

## Current Behavior

When adding the username-only option to https://signin.ebay.com/signin/, the username field drop-down will work. When that form is submitted, the next dialog for the password will not have a drop-down, and doing a right-click "Fill password only" does not work either. After using the "Choose custom login fields" on the password page, not only does the drop-down not appear and the right-click "Fill password only" still not work, but when returning to the initial page with the username field, the username can no longer be filled either.

## Steps to Reproduce (for bugs)

1. Add username/password for ebay.com to keepass.
2. Go to https://signin.ebay.com/signin/ (or go to ebay.com and click sign-in in the upper left corner)
3. Enable the "Add username-only option for the site" option.
4. Click on the username field and select the username from the drop-down.
5. The password page should appear. Try clicking on the password field. The password should not show up on the drop-down. Try right-click "Fill password only", it should not work either.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.1
Operating system: Linux
Browser: Firefox 82.0

**Comment by varjolintu** [comment]
I'll try to improve the login flow in https://github.com/keepassxreboot/keepassxc-browser/pull/1010.
