### ISSUE TITLE
KeepassXC-Banner appears in printed webpage in Firefox

### ISSUE THREAD

**Issue by derhagen** [keepassxreboot/keepassxc-browser#1074]
## Expected Behavior
When asking to save a new password, the browser plugin shows a banner on top of the Webpage: "Username or password changed! Save it? Username: foo@bar.com". This should not be included when printing the page.

## Current Behavior
Ctrl+P printing this page to a PDF, having the banner opened, includes the banner, including my email address. This could potentially disclose sensitive information.

## Possible Solution
Attach a `display: none` to the banner in the print view

## Steps to Reproduce (for bugs)
1. (optional) Adjust settings so the banner doesn't disappear too quick
2. Change or create login data in Firefox. The Banner appears.
3. Ctrl+P -> print to file
4. See Banner including username in printed file

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 82.0

**Comment by varjolintu** [comment]
May I ask why don't you simply dismiss the banner before printing?

**Comment by derhagen** [comment]
I might not have noticed it at all. My point is not, that I'm not technically able to print the page without the banner at all. But I might _accidentally_ include it in printed or PDF-exported documents. Since I don't see any single case where this might be desired, I consider this unexpected and potentially risky behaviour.

**Comment by droidmonkey** [comment]
Concur with display none in print view
