### ISSUE TITLE
Hide entry from HTTP Basic Auth

### ISSUE THREAD

**Issue by PhilippVerpoort** [keepassxreboot/keepassxc-browser#1076]
Currently, there's an option to use an entry only with HTTP Basic Auth. Would it be possible to add an option that works the opposite way? I.e., use an entry for everything except HTTP Basic Auth.

The reason is this: Imagine you're navigating to a webpage, where you've define a single entry for HTTP Basic Auth, as well as 5 login credentials. In that case, you'd have to select one of the those total 6 entries every time the HTTP Basic Auth form pops open, even when actually just one single entry is intended for this form.

There's already an option to hide an entry entirely from the browser extension, but it'd be great if it were possible to hide it only from HTTP Basic Auth forms. This would greatly improve usability for me for pages where both HTTP Basic Auth credentials and normal credentials are defined.

**Comment by droidmonkey** [comment]
Already part of develop branch: https://github.com/keepassxreboot/keepassxc/pull/5394
