### ISSUE TITLE
KEEPASSXC-BROWSER prompts to update and save the wrong password

### ISSUE THREAD

**Issue by GithubABCDEFG** [keepassxreboot/keepassxc-browser#1078]
This is a very strange question:

When I logon to the website of pdawiki.com, the KEEPASSXC-BROWSER will prompt this message ( the Password has been changed, updated or added ?) in every time. When I choose to add, it will add a wrong password to the Keepass XC database every time after I logon . If you select Update, the correct password will be updated to the wrong password. This is really weird, and I don't know where the wrong password comes from.

**Comment by varjolintu** [comment]
The site changes the password (encodes it somehow). When I tested it, it gave me the right password on two tries, but the third one added the encoded one (something like `8848a7755c69bc67775265761069823b`.

There was some previous issue where the same thing happened in a separate password fill page, but I cannot find it now. It might be good to investigate these kind of issues some more, and perhaps save the entered value to some internal variable so the input field alterations could be ignored when saving credentials.

**Comment by GithubABCDEFG** [comment]
This doesn't happen if you use Chrome's password management feature, so I think it's a bug.

**Comment by varjolintu** [comment]
The wrong password comes from the input field itself when the submit happens. If the site decides to change it before submit, there's little we can do.

Chrome's password management possibly actively monitors all input fields and what have been entered to them. We don't currently do that.
