### ISSUE TITLE
login into websites that ask credentials in two steps

### ISSUE THREAD

**Issue by hugodu69** [keepassxreboot/keepassxc-browser#1079]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

having the abilities to autofill login and password in the case it's asked in two steps instead of one

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

heres how it could works : you arrive on the website login page, there is only one field for the id, you click on the autofill keepassxc icon, then hit enter, the second field appears and you click on a second autofill icon, and it's done

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

some websites, such as bitbucket.org, ask for the credentials in two times : first the id, with just one field, and only when this field is validated another one appears for the password. The ff extension of keepassxc doesn't provide an easy way of creating and filling these credentials

it's not essential and you're doing an amazing work anyway, thank you !

**Comment by varjolintu** [comment]
1. Add the URL to extension's _Site Preferences_ tab page
2. Enable _Username-only Detection_ for it.

@droidmonkey This is the most frequently asked question. It's totally missing from the User Guide.

**Comment by droidmonkey** [comment]
I agree! Was thinking the same thing

**Comment by hugodu69** [comment]
thanks :) I wondered if that was the solution, but when i tried it didn't work. Now that you tell me it's the right way to do it, I tried harder and it kind of work, but with two bugs :
- the flow to save the informations into keepassxc is weird, i had to go outside the browser extension an directly edit the informations into the laptop app, and if i completely erase it to start fresh i can select the "username only detection" from the extension but then it doesn't save any inormation of username nor password.
- And once it's saved in keepassxc, the extension detect the first field, username, but to make it detect and autofill the second field i have to click on the extension icon and select "redetect login field"

or am i doing something wrong ?
