### ISSUE TITLE
Dropdown list with logins is not displayed on page where login fields are not autofocused

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc-browser#1081]
## Expected Behavior

On a page, where the login form does not get the focus automatically on page load, and there are multiple logins available for that site, pressing `Alt+Shift+u` should display the dropdown list with available logins to select from.

## Current Behavior

Pressing `Alt-Shift-u` fills in the first available login from the available logins.
You don't get the option to select.
You have to press `Alt-Shift-u` again (or the `down` arrow) for the drop-down list to appear.

## Possible Solution

Might be related to the fix for #1053

## Steps to Reproduce (for bugs)

1. Go to a page that does not set focus to the login field automatically, and for which you have more than one login saved in KeepassXC, e.g. https://www.otto.de/user/login
2. Press `Alt-Shift-u`
3. First login is automatically filled in to the login form, there is no option to select from the list of logins

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.2
Operating system: Linux x86_64
Browser: Mozilla Firefox 82.0

**Comment by varjolintu** [comment]
This can be done easily.
