### ISSUE TITLE
Cannot fill in username on www.fidelity.com, even after choosing custom login fields

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#1083]
## Expected Behavior
The login form on www.fidelity.com should allow filling the username field either via the normal drop-down, or by right-click "Fill username or password". At worse case, this should happen after choosing custom login fields.

## Current Behavior
Even after choosing custom login fields and forcing a page refresh or new tab, the username field cannot be filled. However, the password field can be filled.

## Steps to Reproduce (for bugs)

1. Create a keepass entry for https://www.fidelity.com
2. Go to https://www.fidelity.com
3. Try clicking on username field, a drop down should not appear.
4. Try right clicking on username field and choosing "Fill username or password". It should not be filled.
5. Try choosing custom login fields, and forcing refresh or open a new tab. The dropdown should not appear, and choosing "Fill username or password" should not work either.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.2
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
I was only able to fix the site for using Custom Login Fields. It's a messy login page.

**Comment by nbartos** [comment]
You got it to work using custom login fields? Did you do anything special? I have tried multiple times but was unable to get it to work.

**Comment by varjolintu** [comment]
Yes, the fix I made allows using the Custom Login Fields. With that fix both username and password fields are regognized as a username field, so Custom Login Fields must be used to set the password field. Still, I can try to improve that login flow a bit more. It takes some time.
