### ISSUE TITLE
[bug] False username field detecting

### ISSUE THREAD

**Issue by LightTemplar** [keepassxreboot/keepassxc-browser#1088]
The extension has false detected a field as username, and when I try to enter there something, it will be replaced by username.
There: https://www.lingvolive.com/en-us/

**Comment by varjolintu** [comment]
This is propably related to the new Predefined Sites feature that includes *.live.com to the list.

You can add the URL `https://www.lingvolive.com/en-us/translate/*` to Site Preferences and select _Disable all features_ as a workaround.

**Comment by LightTemplar** [comment]
> You can add the URL `https://www.lingvolive.com/en-us/translate/*` to Site Preferences and select _Disable all features_ as a workaround.

Thanks, it worked with that field, but it has disabled also actual username/password fields detecting.

**Comment by varjolintu** [comment]
Gotta double check why *.live.com is actually enabling _Username-only Detection_ for *live.com instead.

**Comment by droidmonkey** [comment]
If it is a regex then the . Will match anything once
