### ISSUE TITLE
problem with browser integration 1.7.2 Firefox

### ISSUE THREAD

**Issue by hahacjnl** [keepassxreboot/keepassxc-browser#1089]
hi since the last browser plugin upgrade (1.7.2) in Firefox (also in Chrome not in EDGE) I get on my amazon search field the keepassxc button for password selection, before it didn't. 
How can I exclude this because now for every search  in amazon my userid is filled after typing search item and enter (have to use the find button)

**Comment by varjolintu** [comment]
This is related to the new Predefined Sites option. You can disable it from the settings while waiting for the fix.
