### ISSUE TITLE
keepass doesn't use forum account and asks for new entry in database every single login

### ISSUE THREAD

**Issue by jorigel** [keepassxreboot/keepassxc-browser#1091]
Hi Folks,

https://forum.repetier.com/entry/signin?Target=categories
keepass doesn't use the existing account and if the data is given by hand wants to create a new record.

## Steps to Reproduce
just create an account and try to use it

## Expected Behavior
using the existing record

## Actual Behavior
user and password keeps empty

## Context
I think KP is not trained or programmed to use the mask that shows up on the upper page.

# ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.1

Operating System: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

Desktop Env: XFCE

thanX 4 Ur attention
jori

**Comment by varjolintu** [comment]
For me that seems to behave like a normal login field. What is your entry URL? It should be `https://forum.repetier.com`.

**Comment by jorigel** [comment]
Yes, it is.
jori

**Comment by droidmonkey** [comment]
You probably denied access to the entry at some point. Go to the properties of the entry and delete the browser custom data

**Comment by jorigel** [comment]
Hi,
I assume that this is what You ment(?):
![browsersettings](https://user-images.githubusercontent.com/5578691/98144383-a4ad9b00-1eca-11eb-8849-709f1e0eaff3.png)

but unfortunately, that doesn't help to make either an automatic or manual insert of data.
jori

**Comment by droidmonkey** [comment]
Yah you are not denying anything

**Comment by jorigel** [comment]
Hi folks,
so am I right, that the mask/script used here on this page meets a program(KP) that is not prepared to manage such a challange?

Has anybody tried to login with an account on that page that I former mentioned getting similar results?

Is this a bug or just a missing skill?

What am I supposed to do now to make it run?

regards
jori

**Comment by droidmonkey** [comment]
This site worked perfectly for me.

**Comment by jorigel** [comment]
Hi,
thank You Jonathan for making efforts to help me. I'm sorry to ask newbie questions, but I don't see a username and/or password in Your login window. Maybe You don't even have an account there, so KP can't set them. But that is, what I expected. What I see in Your picture is (with the exception of the grey window) an empty login like mine. The green kp-icon and a key in the password line is what I see in my window, as well. But I don't get the input of username and password by KP, it doesn't matter if I try to get that via automatic infill or by manual call (ctrl-shift-v).

And that's the point, where I don't know where to get further. Hope, not to be too annoying, regards
jori

**Comment by varjolintu** [comment]
@jorigel You can see the Browser Access Request popup window in that screenshot. It means the credentials have been requested from KeePassXC, so the site URL has been matched. After allowing you could fill the credentials received. This also worked for me.

Does your KeePassXC toolbar icon switch to a one with a question mark?

Do you have _Automatically retrieve credentials_ enabled in the extension settings?

**Comment by jorigel** [comment]
Hi,
to make clear, what my problem is:
![login](https://user-images.githubusercontent.com/5578691/98232933-94df9680-1f5e-11eb-950b-33a46081a5c9.png)
that is , what I get and nothing more and I have an account over there and the access-data is in the database of kp, but kp refuses to fill in that data.

@varjolintu don't know exactly what and where You ment it to be switched on. I try to manage this in a different language than Yours, so a picture might be helpful to find what You mean.

**Comment by varjolintu** [comment]
Your only solution is to inspect the content script and try to figure out if credentials are found by inspecting what `kpxc.credentials` holds inside.

Does filling using the context menu work? Right-click the mouse on the input field to see the KeePassXC menu.

**Comment by jorigel** [comment]
@varjolintu  yes, by right clicking I get the menu. First point is "fill in user and password". Using it, nothing happens and no, the window stays like in the upper picture no change to a question mark.

Is that what You wanted to know?
jori

**Comment by varjolintu** [comment]
The icon in the username field does not change to a question mark icon (yet, but that feature will be implemented). I meant the icon in the browser toolbar (which shows database is locked in this picture):

<img width="242" alt="Screenshot 2020-11-05 at 13 26 04" src="https://user-images.githubusercontent.com/24570482/98235434-77b0c500-1f6a-11eb-8d22-c6e5d38165e4.png">

**Comment by jorigel** [comment]
no, @varjolintu it doesn't change to a question mark or a key-lock it shows a '+'- sign, see here:
![icon](https://user-images.githubusercontent.com/5578691/98361823-8495ed00-202c-11eb-9c3e-288f795bbc32.png)
jori

**Comment by varjolintu** [comment]
@jorigel Try to update KeePassXC to 2.6.2. Use the official AppImage to test it if you're not using the PPA. See if the error happens after that.

**Comment by jorigel** [comment]
A word and a blow, thanks to all helpers esp. @varjolintu,
after asking for my permission to read the database while logging in, it takes the data and placed it correctly. So the problem is solved. The only thing I wonder is why that happened. Is there something special about this page, or did I do anything wrong creating the account?

thanX 2 all
regards
jori

**Comment by varjolintu** [comment]
@jorigel You were affected by a URL matching bug in 2.6.1. Sorry I didn't figure it out sooner.
