### ISSUE TITLE
[Firefox] key exchange failed

### ISSUE THREAD

**Issue by palvarezcordoba** [keepassxreboot/keepassxc-browser#1092]
## Expected Behavior
KeePassXC-Browser extension should connect to my KeePass database

## Current Behavior
When I click on the extension icon, I get the following error:
```
El cifrado del mensaje falló. ¿Se está ejecutando KeePassXC?
```
Which in english, should be something like:
```
Encryption of the message failed. Is KeePassXC running?
```
Then, I click the reload button and get this error:
``` 
Intercambio de claves no tuvo éxito. 
```
Which in english is something like:
```
Key exchange was unsuccessful.
```
If I go to settings > connected databases > connect, it does nothing.

## Steps to Reproduce (for bugs)

1. Open KeePassXC, open database, and enable browser integration for firefox
2. Install the extension
3. Try to connect to the database

## Debug info

Debug info from KeePassXC-Browser' about page:
KeePassXC - unknown
KeePassXC-Browser - 1.7.2
Operating system: Linux x86_64
Browser: Mozilla Firefox 82.0

KeePassXC version: 2.6.2-1ppa1~focal1 (installed with apt from ppa repository)
OS: Ubuntu 20.04.1 LTS (codename: focal)

```
$ cat ~/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

Also, I readed https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide but that don't solve the issue.

**Comment by varjolintu** [comment]
Is your Firefox installed via Snap or Flatpak? If so, use a normal repository instead.

**Comment by palvarezcordoba** [comment]
Thanks for your fast response, @varjolintu
First of all, I edited the issue (you can see only the changes, like a git diff).
But, for convinience, here you have the 2 lines I added:
If I go to settings > connected databases > connect, it does nothing.
Also, I readed https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide but that don't solve the issue.

And no, I'm not using Firefox from Snap or Flatpak. My Firefox version is written in the issue.
But here it is again: 
`KeePassXC version: 2.6.2-1ppa1~focal1 (installed with apt from ppa repository)`

**Comment by palvarezcordoba** [comment]
Just in case, this is the ppa I'm using: `deb http://ppa.launchpad.net/phoerious/keepassxc/ubuntu focal main`

**Comment by varjolintu** [comment]
Are you sure about your Firefox? What is the Profile Folder printed in `about:support`?

**Comment by palvarezcordoba** [comment]
The profile folder is: `~/.mozilla/firefox/oqnlfk30.default-release`
And yes, I'm sure I'm not using Firefox from Snap nor Flatpak.
Check this:
```
$ snap list | grep -i firefox
$ LANG=en apt list firefox
Listing... Done
firefox/focal-updates,focal-security,now 82.0+build2-0ubuntu0.20.04.1 amd64 [installed,automatic]
N: There is 1 additional version. Please use the '-a' switch to see it
$ dpkg -s firefox | egrep "^Status|^Version"
Status: install ok installed
Version: 82.0+build2-0ubuntu0.20.04.1
$ firefox --full-version
Mozilla Firefox 82.0 20201014125134 20201014125134 
$ snap list | grep -i firefox   
$ which firefox 
/usr/bin/firefox
```
I have the Firefox of apt.

**Comment by palvarezcordoba** [comment]
I have several entensions, but it is not the cause because I have tried running Firefox with a new profile (so, 0 extensions installed) but it also fails, so my installed extensions does not interfere with KeePassXC-Browser

**Comment by varjolintu** [comment]
And your Browser Integration settings in KeePassXC looks like..?

**Comment by palvarezcordoba** [comment]
KeePassXC Browser integrations config:
![imagen](https://user-images.githubusercontent.com/37622818/98170783-eb14f100-1eee-11eb-8a68-e4287db53da2.png)
![imagen](https://user-images.githubusercontent.com/37622818/98170812-fb2cd080-1eee-11eb-8a8c-7a0fc89af011.png)

The keepassxc-proxy command is no running. And Firefox seems to not event read the Native Messaging script file:
If I run `strace -e trace=file ^Crefox 2>&1 | grep native-messaging-hosts` the output is empty.

**Comment by yannpub** [comment]
I have noticed an approaching behaviour on Firefox on MacOS recently. The browser extension keeps losing the connection to the application and the database. Don't know if it's related to the same issue though.

**Comment by palvarezcordoba** [comment]
@yannpub Thanks for commenting but it is not related, I guess. In my case, the extension never event connects to the database nor the app (I guess).

**Comment by varjolintu** [comment]
`strace` should definitely show something. It's hard to say where the problem here actually is.

**Comment by palvarezcordoba** [comment]
What command should I run and what should I search on the output?

**Comment by varjolintu** [comment]
Sorry for the late response.

You should first seek the PID of your Firefox's main process (the first PID that shows /usr/bin/firefox).

Then use the following command: `sudo strace -p PID -f -e trace=file -o strace.log`

Then got to your Firefox, open the extension popup and press reload. That should trigger the Native Messaging to open the script file. Then exit the `strace` and open the `strace.log` file. Seek for `json` and you should see a line similar to this:

`5390  openat(AT_FDCWD, "/home/varjolintu/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = 124`

**Comment by michael1maass** [comment]
sorry for intruding: 
this problem is common to other browsers and OS too. Win10, Edge 2: the extension shows exactly the same behavior. Did it ever work with KeepassXC Versions prior to 2.6.2?

**Comment by palvarezcordoba** [comment]
Ok, it works now. It was failing because apparmor didn't allowded execution of `/usr/bin/keepassxc-proxy`
