### ISSUE TITLE
Cannot reliably change keyboard shortcuts on Linux

### ISSUE THREAD

**Issue by Moilleadoir** [keepassxreboot/keepassxc-browser#1093]
The default fill shortcut (Alt+Shift+U) is useless to me; in my language it activates Firefox’s Tools menu. When I went to change it I first managed to get Alt+OS+U into the dialog, but it wouldn’t save. Figured out this is from the web extension API, so I’ve tried many options using Ctrl+Somekey or Alt+Somekey, but nothing ever appears in the dialog. It seems like the input is being filtered, but I can’t figure out if there’s any combination that will work.

## Expected Behavior
Dialog should either give some feedback (e.g. invalid shortcut) or accept a shortcut.

Also “shortcut could not be saved” is not very informative when it’s actually a shortcut that is not allowed.

## Current Behavior
Dialog remains blank no matter what shortcut is typed. Typed shortcuts activate various other things if they exist (which is disconcerting).

## Debug info
No errors appear in console.
KeePassXC - 2.6.1-1 (yes Manjaro has not updated yet!)
KeePassXC-Browser - 1.7.2
Operating system: Linux (Manjaro Cinnamon)
Browser: Firefox

**Comment by varjolintu** [comment]
See if your shortcuts are in line with https://developer.chrome.com/extensions/commands (the same API is in Firefox).

Does the same shortcuts work if you define them using Firefox's own methods/page?

**Comment by Moilleadoir** [comment]
As I said I’ve tried Ctrl and Alt with most letters, numbers and punctuation. Nothing appears in the dialog box. If I type just letters they are briefly appear before being ‘backspaced’.

I’m not sure what you mean by “Firefox’s own methods/page”. There doesn’t seem to be any (easy) way to change Firefox shortcuts.

**Comment by varjolintu** [comment]
`about:addons` -> click the gear icon, choose _Manage Extension Shortcuts_.

When Firefox is able to provide a URL for managing shortcuts for each extension, we are gonna switch to that. This is already possible with Chromium-based browsers.

**Comment by Moilleadoir** [comment]
Wow, that’s so buried I’d forgotten it was there. Shortcuts can be changed there with no problem.

**Comment by varjolintu** [comment]
Gotta check what's wrong with out replacement. There's a two year old ticket at Mozilla for the shortcut feature, and I don't expect it to be resolved soon.
