### ISSUE TITLE
Browser javascript error and failure to auto-populate entry

### ISSUE THREAD

**Issue by jakeparis** [keepassxreboot/keepassxc-browser#1095]
## Overview
Using the browser extension (Vivaldi (chromium-based)), an entry is not auto-filled, and instead throws a javascript error: 
```
initContentScript error:  TypeError: form.action.startsWith is not a function
    at Object.kpxcForm.getFormSubmitButton (keepassxc-browser.js:161)
    at Object.kpxcForm.init (keepassxc-browser.js:229)
    at Object.kpxc.initCombinations (keepassxc-browser.js:1059)
    at async Object.kpxc.identifyFormInputs (keepassxc-browser.js:997)
    at async Object.kpxc.initCredentialFields (keepassxc-browser.js:1077)
    at async initContentScript (keepassxc-browser.js:1686)
```

Same keepass database and same url on the same machine works fine in Firefox. 

## Expected Behavior
I expected my stored entry to either autofill or be available in the keepass dropdown of matches. 

## Actual Behavior
No matches display, the keepass icon doesn't show in the field (like it usually does)

## Debug 
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.6

Operating System: macOS

**Comment by varjolintu** [comment]
What's the site URL? This could be easy to fix but at first I'm interested to see what the `form.action` holds.

**Comment by jakeparis** [comment]
It's a [Scalar application ](https://github.com/anvc/scalar)install. Our install is at https://kent.bates.edu/scalar/system/login

**Comment by varjolintu** [comment]
I tried the page with Firefox and Edge. Couldn't reproduce the problem.

**Comment by jakeparis** [comment]
I know, as I said in the comments, it only happens in a chromium browser. Firefox worked fine for me as well.

**Comment by varjolintu** [comment]
Gotta test Vivaldi then.

**Comment by RichardZett** [comment]
This bug is reproducable at [https://www.mindfactory.de/login.php]( https://www.mindfactory.de/login.php).
I added some debugging outputs:

![image](https://user-images.githubusercontent.com/74097016/98440155-5b8e5e80-20f7-11eb-9d4c-fb2338c680ad.png)

Obviously `form.action` refers to the `input` element with `name="action"` and not the action url.
