### ISSUE TITLE
Amazon search box detected as username field

### ISSUE THREAD

**Issue by FPSlacker** [keepassxreboot/keepassxc-browser#1096]
## Expected Behavior
Don't detect the search box as a login.

## Current Behavior
Adds the icon and account dropdown to the search box.

## Possible Solution
Fix detection for Amazon. Or as a more general fix, add a way to selectively ignore fields.

## Steps to Reproduce (for bugs)
Same behavior in both Firefox and Chrome, either logged in or not.
Open any amazon.com page. Also does the same on amazon.co.uk but _not_ on amazon.ca even though the HTML for the search box is the same on all three.

`<input type="text" id="twotabsearchtextbox" value="" name="field-keywords" autocomplete="off" placeholder="" class="nav-input" dir="auto" tabindex="0" aria-label="Search">`

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.2
Operating system: Win32
Browser: Mozilla Firefox 82.0

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.2
Operating system: Win32
Browser: Chrome/Chromium 86.0.4240.111

**Comment by ErinMorelli** [comment]
+1

I am experiencing the exact same issue. I'm using the same browser, but on a Mac running macOS 10.15.7.

**Comment by varjolintu** [comment]
Already fixed.
