### ISSUE TITLE
Use custom data to save browser connection keys

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc-browser#11]
## Expected Behavior

With https://github.com/keepassxreboot/keepassxc/pull/1494, KeePassXC properly supports custom plugin data.
Browser integration should use these instead of advanced string fields for storing browser keys.

**Comment by varjolintu** [comment]
Should the Allow/Deny rules to be saved as custom data also instead of attributes?

**Comment by phoerious** [comment]
I would say so, yes.

**Comment by varjolintu** [comment]
PR https://github.com/keepassxreboot/keepassxc/pull/1497 opened. Waiting for the merge before rebasing.
