### ISSUE TITLE
Copy of OTP doesn’t work (V 1.7.1)

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#1100]
Hi team , 

I can imagine that this has worked some releases ago .

When I copy / auto fill a login I see on some websites a field for OTP codes . 

But your extension doesn't copy this code in the clipboard anymore .

**Comment by varjolintu** [comment]
The extension has never copied TOTP to clipboard.

**Comment by F3000** [comment]
Is it possible that you can add this for a future release ?

**Comment by droidmonkey** [comment]
No, the extension does not interact with the clipboard. This is on purpose and never will be implemented.
