### ISSUE TITLE
login field detection overly broad and eager after recent update (at least on amazon)

### ISSUE THREAD

**Issue by metaxis** [keepassxreboot/keepassxc-browser#1101]
## Expected Behavior
login field detection should trigger on username/password fields.  Also, typing into a matched field and hitting enter should simply submit with the typed text

## Current Behavior
on amazon.com, the search bar is detected as a login field:

![search bar match](https://user-images.githubusercontent.com/251061/98455538-dd49b080-2126-11eb-920f-628c09fc0cab.PNG)

It's hard to capture in the snipping tool, but when the text field is active, the top credential is highlighted green, and when I hit "enter" after typing my search string is replaced with the **username** from that credential.

It also was matching the price "max" field:

![kpass price match](https://user-images.githubusercontent.com/251061/98455541-dfac0a80-2126-11eb-8d87-d9d8ef0b868f.PNG)

## Possible Solution

I tried a few other sites other than amazon.com but could not recreate the necessary conditions, which I **suspect** may be: text fields but no regular login fields, and existing credentials for the site.

## Steps to Reproduce (for bugs)

1. visit amazon.com.   example: https://www.amazon.com/s?k=banana+male+female&ref=nb_sb_noss_2
2. click on search and start typing 
3. observe the kp icon and popup appear with your amazon credentials ( I have several)
4. hit enter and observe your search text removed and credential username appear in the search bar

### Workaround

3a.  hit escape before hitting enter

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser -  1.7.2
Operating system: Win 7
Browser: Firefox 81.0.1 (64-bit)

- I have no custom fields set at all.  
- I have no site preferences at all.  
- I do not have any autofill behavior turned on. 
- I *do* have dynamic field detection turned on -  the same since I started using it - but this has not been a problem in the past

source excerpt from search field:
```
      <div class="nav-search-field ">
        <input type="text" id="twotabsearchtextbox" value="banana male female" name="field-keywords" autocomplete="off" placeholder="" class="nav-input" dir="auto" tabindex="0" aria-label="Search" fetched="true">
      </div>
      <div id="nav-iss-attach"></div>
```
   
source excerpt from price fields: 
```  
     <form method="get" action="/s">     
            <input type="hidden" name="k" value="banana male female">
            <input type="hidden" name="qid" value="<<numeric deleted>>">
            <input type="hidden" name="rnid" value="<<numeric deleted>>">
            <input type="hidden" name="ref" value="sr_nr_p_36_5">
         
         <span class="a-color-base s-ref-small-padding-left s-ref-price-currency">$</span>
         <input type="text" maxlength="9" id="low-price" placeholder="Min" name="low-price" class="a-input-text a-spacing-top-mini s-ref-price-range s-ref-price-padding">
         <span class="a-color-base s-ref-small-padding-left s-ref-price-currency">$</span>
         <input type="text" maxlength="9" id="high-price" placeholder="Max" name="high-price" class="a-input-text a-spacing-top-mini s-ref-price-range s-ref-price-padding" autocomplete="off">
         <span class="a-button a-spacing-top-mini a-button-base s-small-margin-left" id="a-autoid-1"><span class="a-button-inner"><input class="a-button-input" type="submit" aria-labelledby="a-autoid-1-announce"><span class="a-button-text" aria-hidden="true" id="a-autoid-1-announce">
            Go
         </span></span></span>
      </form>
```

**Comment by droidmonkey** [comment]
Already fixed for next release
