### ISSUE TITLE
KeepassXC autostarts after opening Firefox (the first time after system startup)

### ISSUE THREAD

**Issue by Leleat** [keepassxreboot/keepassxc-browser#1102]
## Expected Behavior

KeepassXC shouldn't autostart on startup of Firefox.

## Current Behavior

KeepassXC autostarts on startup of Firefox (if the extension is enabled). Seems to only happen on system startup. If I quit KeepassXC and open Firefox, it won't autostart. (I don't have any of "startup" settings enabled.)

## Possible Solution

Disable the extension in Firefox.

## Steps to Reproduce (for bugs)

1. Have the extension enabled during system startup
2. Open Firefox
=> KeepassXC will autostart

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux x86_64 (Fedora 33, GNOME, X11)
Browser: Mozilla Firefox 78.0 (according to the debug info but it's actually Firefox 82.0.2)

**Comment by droidmonkey** [comment]
This is a flatpak bug. Or you need to update keepassxc.
