### ISSUE TITLE
FF 82 64-bit - popup doesn't really open

### ISSUE THREAD

**Issue by kanunnikau** [keepassxreboot/keepassxc-browser#1103]
Hello
Recently I have encountered an issue with opening the KeePassXC-Browser Firefox browser extension popup. Basically, it doesn't open. The filling behaviour (autofill, context menus on fillable fields) work as before.

## Expected Behavior
- Click on the extention icon
- See extension popup body

## Current Behavior
Extension popup body is transparent

## Steps to Reproduce (for bugs)
- Click on the extention icon
- Observe a little spinner
- Observe completely transparent popup body. Basically, it is only showing the popup frame. Within the frame the underlying webpage is visible.
![ezgif-2-a44168710a47](https://user-images.githubusercontent.com/2588408/98535424-5e6b8980-2286-11eb-9844-c9579a18e901.gif)

## Debug info
No errors displayed
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Does the same happen with a new temporary profile? Can you debug the popup and see if there's any JavaScript errors? Are you using stable Firefox version?

**Comment by kanunnikau** [comment]
Hello
I guess this is not a KeepassXC issue in the end as I am starting to see the same issue in other extension popups and even some of Firefox own menus :)
Sorry for bothering you

**Comment by varjolintu** [comment]
No worries! I hope you get your problem solved.
