### ISSUE TITLE
HMI bug on fields manual settings

### ISSUE THREAD

**Issue by Wanou38** [keepassxreboot/keepassxc-browser#1109]
## Expected Behavior

A menu is displayed in a dark division above the login page of the site where i want to manually select the fields.
This menu contains a title that describe the current field the user must select, a description of some keyboard shortcut and some buttons to control the operation.
The division end after the buttons.

## Current Behavior

A menu is displayed in a dark division above the login page of the site where i want to manually select the fields.
This menu contains only a title but no other contents.
The division has no ending on screen.
![KeePassXC - HMI Bug on fields detection](https://user-images.githubusercontent.com/74499060/99188354-cffe7880-275b-11eb-9a73-bdc865c1801f.png)

## Steps to Reproduce (for bugs)

1. Get to the URL: https://saintmartindheres.espace-famille.net/saintmartindheres/index.do
2. From the KeePassXC-Browser menu, select "Custom Id fields".

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Windows 10
Browser: Firefox 82.0.3

**Comment by varjolintu** [comment]
This happens because the page as a global style `div.height: 100%`. We'll have to override that.

**Comment by Wanou38** [comment]
Well done. Many Thanks for this fix.
