### ISSUE TITLE
Browser extension not linked with database, Brave browser, Mas OSX

### ISSUE THREAD

**Issue by tonitri** [keepassxreboot/keepassxc-browser#1110]
## Expected Behavior

I'd like to link the Brave extension with by keepassXC - However I can't

## Current Behavior

1. Click on the Brave extension icon, below error message is displayed
Une erreur est survenue dans KeePassXC-Browser :
Impossible de se connecter à KeePassXC. Vérifiez que l’intégration au navigateur est activée dans les paramètres de KeePassXC.

2. Click on "Recharger" (Reload?) blue button. Error message displayed "L’échange de clé a échoué." (Key exchange failed)

I understand that the extension is not able to detect my keepassxc database, however it's already opened on my iMAC

## Debug info
KeePassXC - unknown
KeePassXC-Browser - 1.7.3
Operating system: MacIntel OS High Sierra 10.13.6
Browser: Chrome/Chromium 86.0.4240.99 (Brave checkbox checked)

**Comment by varjolintu** [comment]
What is Brave extension?

Do you mean you use Brave but cannot connect KeePassXC-Browser to it? Try enabling Chrome and Chromium checkboxes.

**Comment by michael1maass** [comment]
Same problem here, with edge 2 edge and chromium checkboxes are enabled in KeepassXC .

**Comment by varjolintu** [comment]
And you both have checked the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)?

**Comment by michael1maass** [comment]
﻿Sure, and followed the rabithole of another Thread here that ended in checking the Malware guard blocking the native messaging, which is what I have my Infrastructure Friends doing right now for settings in f-secure.

Michael, 

Ständig unterwegs aber Dank iPhone im Bilde



Von meinem iPhone gesendet

**Comment by michael1maass** [comment]
Hi,  
sure, and I went down the rabbithole of another thread here that endet checking the malware defense for blocking native messaging. So thats, what I asked my friends  from „Infrastructure“ to do with  our f-Secure konfiguration. I keep you posted. 
So many linux and Mac users here, they never  come across Antvirus-/Malware Problems...... ;-) 

Von meinem iPad gesendet

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
