### ISSUE TITLE
[bug] The extension doesn't ask to save a password 

### ISSUE THREAD

**Issue by LightTemplar** [keepassxreboot/keepassxc-browser#1111]
The extension doesn't ask to save credentials on https://help.univention.com/
It does recognize fields, but after I filled them and logged in, the banner suggesting saving credentials doesn't show up at all.  

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: KDE Neon
Browser: Mozilla Firefox 82.0

**Comment by LightTemplar** [comment]
offtop: what a number for my issue! :sunglasses:

**Comment by varjolintu** [comment]
The fix I made only applies when the form button is pressed. Login via <kbd>Enter</kdb> is not regognized though.
