### ISSUE TITLE
Crash with read error in main memory on specific URL

### ISSUE THREAD

**Issue by mashme** [keepassxreboot/keepassxc-browser#1114]
## Current Behavior

When visiting this site https://konsoleh.your-server.de/ keepassXC crashes with a read error in main memory. Please see screenshot attached. This is reproducible, it happens every time. After a restart keepassXC won*t autofill the fields, but I can  manually copy user name and password. 
![keepassCrash](https://user-images.githubusercontent.com/8281753/99414630-4b486180-28f7-11eb-8d57-64d1089b5d41.JPG)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {2.6.2}
KeePassXC-Browser - {1.7.3}
Operating system: Windows 10 Vs. 20H2
Browser: Firefox 82.0.3 (64bit)

**Comment by varjolintu** [comment]
Does this happen with every database? What is you entry URL? Could you possibly share the crash dump log?

**Comment by droidmonkey** [comment]
Pinned issue in keepassxc issue board

**Comment by mashme** [comment]
Thank you for this hint varjolintu!
I only use one large DB (320 KB) that has 40 entries for the url https://konsoleh.your-server.de/
Some of them are duplicate entries, as I see now. I created a copy of the db and deleted all entries for this url, accept one. KeepassXC works, no more crash. The prob has to do with the number of entries or with the duplicates.  I will delete the duplicates next and will report here.
