### ISSUE TITLE
Username / password field not detected in chrome: https://b2b.dab-bank.de/smartbroker/

### ISSUE THREAD

**Issue by foben** [keepassxreboot/keepassxc-browser#1116]
## Expected Behavior
That username/password fields are auto-detected, or can be selected manually.

## Current Behavior
Can't even select as custom username/password field.
It works in Firefox but not in Chrome.

## Steps to Reproduce (for bugs)

1. Go to https://b2b.dab-bank.de/smartbroker/
2. In the extension, click "custom username/password field"
3. None of the input fields will be selectable

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - {VERSION}
Operating system: Win & Linux
Browser: Chrome Version 86.0.4240.198

**Comment by varjolintu** [comment]
For some reason `getBoundingClientRect()` for the `form` element returns its height as 0.

**Comment by KuenzelIT** [comment]
I have the exact same problem with Firefox. Can I somehow define the input fields in the config?

**Comment by varjolintu** [comment]
@KuenzelIT Seems that's not working either. The plugin thinks those input fields have no size, so they are ignored.

**Comment by KuenzelIT** [comment]
Well, smartbroker does not even call it's password field a password field, but an "identifier". So I assume it's not surprising if they do some crazy JavaScript magic. Still pretty annoying that every other website works perfectly, but not smartbroker.

**Comment by varjolintu** [comment]
@KuenzelIT The only way to get this work for now is to force fill through the context menu, but then you'll have to fill username and password separately. Another way is to use KeePassXC's Global Auto-Type.

**Comment by KuenzelIT** [comment]
> @KuenzelIT The only way to get this work for now is to force fill through the context menu, but then you'll have to fill username and password separately. Another way is to use KeePassXC's Global Auto-Type.

Thanks, I'm using the force fill for now. Global Auto Type sounds a little scary to me.

**Comment by varjolintu** [comment]
> > @KuenzelIT The only way to get this work for now is to force fill through the context menu, but then you'll have to fill username and password separately. Another way is to use KeePassXC's Global Auto-Type.
> 
> Thanks, I'm using the force fill for now. Global Auto Type sounds a little scary to me.

It just means launching the Auto-Type using a global keyboard shortcut. Makes sometimes things much easier.

**Comment by KuenzelIT** [comment]
> > > @KuenzelIT The only way to get this work for now is to force fill through the context menu, but then you'll have to fill username and password separately. Another way is to use KeePassXC's Global Auto-Type.
> > 
> > 
> > Thanks, I'm using the force fill for now. Global Auto Type sounds a little scary to me.
> 
> It just means launching the Auto-Type using a global keyboard shortcut. Makes sometimes things much easier.

Thanks a lot, this is very useful. Now I unterstand what you meant, it works only for one field, but is a lot quicker than using the context menu.

**Comment by varjolintu** [comment]
This is now tracked in #1358.
