### ISSUE TITLE
[bug] Field detection not correctly working on Replicon in Firefox

### ISSUE THREAD

**Issue by CubeTheThird** [keepassxreboot/keepassxc-browser#1119]
When attempting to login to Replicon.com, the username and password fields do not get auto-filled
## Expected Behavior
Being able to auto-fill the username and password fields, either through the icon, or right-click context menu.

## Current Behavior
The KeepassXC auto-fill icon does not appear, nor does the right-click context menu to enter in username and/or password actually do anything.

## Steps to Reproduce (for bugs)
1. Navigate to the Replicon login page here: https://login.replicon.com/DefaultV2.aspx
2. Enter in a company name
3. Click Next
4. Attempt to auto-fill in the username and password fields

## Debug info

Dump of console output when loading and filling the page:
```
This page uses the non standard property ?zoom?. Consider using calc() in the relevant property values, or using ?transform? along with ?transform-origin: 0 0?. DefaultV2.aspx
Some cookies are misusing the recommended ?SameSite? attribute 2
```

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Windows 10
Browser: Firefox

### Additional Info
This page used to work without issue, however it seems the creators have been making many changes to the login system (the layout has changed several times), and I suspect something they did is messing with the extension. The current version (as of writing this) does not use a redirect, but upon entering in the Company Name, a new section appears for the username and password.
I also understand that it may be difficult to reproduce this without test login information. Please let me know if there is any additional information I can provide.

**Comment by varjolintu** [comment]
Does it help if you enable add the site URL (or `https://login.replicon.com/*`) to Site Preferences in the extension settings and enable _Username-only Detection_? In that way you can improve the single username login forms.

**Comment by CubeTheThird** [comment]
Sadly this does not solve the problem. It does allow the initial Company Name field to be recognized, however the subsequent Username and Password fields are still not.

**Comment by varjolintu** [comment]
I need some login info for this. If you have a test account or anything, contact me.

**Comment by CubeTheThird** [comment]
> I need some login info for this. If you have a test account or anything, contact me.

I unfortunately no longer have an account on this site, although the issue persisted when I last did.
