### ISSUE TITLE
http vs https

### ISSUE THREAD

**Issue by NealBScott** [keepassxreboot/keepassxc-browser#1121]
In Keepass I stumbled on some old entries that had the prefix of the url as:
http://
which, at the time, was correct.   As time moved on these same web sites started using https://   So now any site that uses ONLY
https://
no longer auto form fills when you click the keepass-browser icon.

For example I have an entry for Expedia, and long ago I defined its url as:
http://www.expedia.com/
but now keepassxc-browser no longer works its autofill magic unless I edit the url to be
https://www.expedia.com/

KeePassXC-Browser Version: 1.7.3
KeePassXC Version: 2.6.2
Operating system: Windows 10
Browser: Chrome/Edge

**Comment by droidmonkey** [comment]
This is by design for security.
