### ISSUE TITLE
KeepassXC icon overlays the login button for the password prompt at Nextcloud for public shares

### ISSUE THREAD

**Issue by ericschdt** [keepassxreboot/keepassxc-browser#1126]
Share a file or folder via a public link in Nextcloud 19+, which is secured by a password. 
On this server/domain also have account credentials saved at KeepassXC.

If you now open the public link and enter the the password, you won't be able to login, because hitting enter is absorbed by KeepassXC and the login button is covered by the KeepassXC icon.

## Expected Behavior
![NC1](https://user-images.githubusercontent.com/43318127/100515586-219ffd80-3175-11eb-9f9e-01a8db91fb28.png)

## Current Behavior
![NC2](https://user-images.githubusercontent.com/43318127/100515583-1c42b300-3175-11eb-85bb-136b633f4471.png)

## Possible Solution
a) disable the KeepassXC addon
b) Delete the icon via the developer tools

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser -  1.7.3
Operating system: Linux
Browser: Firefox 83

**Comment by ericschdt** [comment]
In case it helps you, that's the HTML structure:
![html_login](https://user-images.githubusercontent.com/43318127/101672977-733a6900-3a4e-11eb-9868-5f372da6a090.png)

**Comment by varjolintu** [comment]
I have no problems entering the password even if the icon is visible on the field. If you see the credential list, you can just press <kbd>Esc</kbd> to dismiss it.

**Comment by ericschdt** [comment]
> I have no problems entering the password even if the icon is visible on the field. If you see the credential list, you can just press Esc to dismiss it.

I can enter the password of course, but I cannot click on the login button or somehow trigger it as the KeePassXC icon prevents me from doing so.
The credential list does not have anything to do with the issue here. :)

**Comment by droidmonkey** [comment]
Press enter?

**Comment by ericschdt** [comment]
> Press enter?

As I already said in the first post, it doesn't work straight forward:

1) Type password
2) Hit enter
Now KeePassXC replaces the password with the first one from the credentials list
3) Hit enter again
The wrong password is submitted and the auth failed

Thus, what one has to do is:

1) Click into the password field
2) Hit enter
Now KeePassXC enters the password of the first credential in the list
3) Now enter the correct password
4) Hit enter

That's not really convenient to me. :)

**Comment by varjolintu** [comment]
As I said before, I cannot reproduce this. Entering the password and pressing enter works normally, and it doesn't use any credentials from KeePassXC.

**Comment by ericschdt** [comment]
If you cannot reproduce it, how should we proceed? Shall we close it if it only affects me as I know how to workaround it myself now?

**Comment by varjolintu** [comment]
I can try later to re-reproduce this :)
