### ISSUE TITLE
lottoland.at: login fields (username/password) not detected (Firefox, Chromium)

### ISSUE THREAD

**Issue by z1atk0** [keepassxreboot/keepassxc-browser#1127]
The browser extension fails to detect the login fields (username & password) on https://www.lottoland.at/. Neither "Redetect login fields" nor "Choose custom login fields" works.

## Expected Behavior
Login fields _should_ be detected and filled out properly on request.

## Current Behavior
Login fields are _not_ detected automatically. I tried both "Redetect login fields" and "Choose custom login fields", but neither worked. The latter did not detect _any_ input fields that could be chosen.

## Steps to Reproduce (for bugs)
1. Go to https://www.lottoland.at/
2. Click on "Zum Login" at the top, right of the "Search" button (magnifying glass)
3. Try to make keepassxc-browser work as expected
4. :man_shrugging: 

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux (Slackware 14.2 32bit)
Browser: Firefox 78.5.0esr (32-bit), Chromium 86.0.4240.198 (Developer Build) (32-bit)

Please let me know if you need any additional information.

**Comment by varjolintu** [comment]
The login fields are inside `shadowRoot` and not detected for some reason. We only have a partial support for it.

**Comment by z1atk0** [comment]
Okay, thanks ... I have no idea what a `shadowRoot` is, but I understand for the time being I'll have to workaround with copy/pasting the username & password from KeePassXC manually - right?

**Comment by varjolintu** [comment]
Yes, although I suggest using Auto-Type instead of copy/paste.

**Comment by varjolintu** [comment]
Now tracked in #1358.
