### ISSUE TITLE
Understanding connections

### ISSUE THREAD

**Issue by MasinAD** [keepassxreboot/keepassxc-browser#1129]
Every now and then KeePassXC or KeePassXC Browser asks me to name a connection – again. This brings me to the question, what is the scope of these connections?

As far as I understand, each opened database needs a connection for each browser. If I have two browsers (which I have) and two databases (which I have) there are four connections at most: B1 <-> D1, B1 <-> D2, B2 <-> D1, B2 <-> D2.

Do these connections get invalid after some time? Do they get lost after a browser restart? These four connections have been re-established at least a dozen times but I don't recognize a pattern yet. Is there a way to avoid re-establishing the connections? Or is this a conceptual issue? I could live with that if I knew why this happens.

**Comment by droidmonkey** [comment]
Are you using unique names for each connection? Do your databases share a history with each other (ie you copied the database file and edited it)?

**Comment by MasinAD** [comment]
Yes, I use unique names for my connections like "Firefox <-> personal" or "Chrome <> work".

No, they don't share a history with each other. They are independently created databases. They are linked in minor ways like using AutoOpen and before that I used the KeeShare sync feature but I was just playing around with the latter until I discovered the former.

**Comment by droidmonkey** [comment]
If you can confirm the connections still exist in your database and in your browser extension settings when it asks for a new connection, then this could be a bug. Too many variables atm to know whats going on. Try to narrow the conditions leading up to a new request.

**Comment by MasinAD** [comment]
Okay, I'll observe it. If I see anything suspicious I'll report again.

**Comment by varjolintu** [comment]
For me these connections get invalid only if I load a develop version of the extension when my DB is open. It doesn't always happen, but this could be the way to inspect the reasons for it.
