### ISSUE TITLE
Console pops up when KeePassXC-Browser seems to be connected, but is not

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#113]
## Expected Behavior

At least show a proper error.

## Current Behavior

![grafik](https://user-images.githubusercontent.com/11966684/38387008-ccef7aa8-3916-11e8-850f-6d001fd70fbe.png)

## Possible Solution

Is it trying to use "alert" there? In any case a web extension should provably never use alert at all in production code, so mhh…

## Steps to Reproduce (for bugs) (possibly)

1. Open database and browser, connect etc.
2. Lock your computer. (GNOME here) -> KeePassXC closes database
3. Notice database is closed. Unlock (& reconnect).
4. (Password autofill does not work now)
    This error happens when I now right-click into a (password) input field -> KeePassXC-Browser -> Fill User + Pass.

## Debug info
KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1
Operating system: Linux
Browser: Firefox 59
Proxy used: yes

**Comment by varjolintu** [comment]
This PR already removes all alerts and replaces them with notifications: https://github.com/keepassxreboot/keepassxc-browser/pull/53. So it will be fixed in the next release. Also, if you have multiple credentials, the autocomplete menu will be visible instead of just an alert or notification.
