### ISSUE TITLE
Firefox Plugin Crash on specific website

### ISSUE THREAD

**Issue by michael-sfx** [keepassxreboot/keepassxc-browser#1130]
## Current Behavior
KeyPass Crash

## Steps to Reproduce bug
1. goto https://account.shopware.com
2. KeyPass will Crash and close
3. Error Message: 

> Die Anweisung in 0x00000000004BB556 verwies auf Arbeitsspeicher bei 0x000000011000000A8. Der Vorgang read konnte im Arbeitsspeicher ncht ausgeführt werden.
> Klicken Sie auf "OK", um das Programm zu beenden.

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Mozilla Firefox 83.0

![crash-keypass](https://user-images.githubusercontent.com/47634835/100745687-f240f900-33df-11eb-9302-4d4987cbddd2.jpg)

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/issues/5596 - Are you having the same issue?

**Comment by michael-sfx** [comment]
> 
> 
> [keepassxreboot/keepassxc#5596](https://github.com/keepassxreboot/keepassxc/issues/5596) - Are you having the same issue?

maybe. I have 23 entries for the mentioned website. maybe thats the reason?

**Comment by varjolintu** [comment]
That's it. The bug has been already fixed, so closing this.
