### ISSUE TITLE
Some websites no longer work in Edge

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1131]
## Expected Behavior

Browser integration works across all browser consistenly and reliably.

## Current Behavior

When I try to access the AWS console, I visit https://console.aws.amazon.com/

Sometimes, I get redirected to `signin.aws.amazon.com`, sometimes to a local portal at `us-east-1.aws.amazon.com`. I have all possible domains registered under **Browser Integration** in my entry.

On Edge, on `signin.aws.amazon.com`, the browser extension refuses to work. No buttons are displayed in the input fields and the hotkeys to auto-fill have no effect.

I don't see why the domain is making any difference here, maybe they're running some A/B tests on their login page or something.

On `us-east-1.aws.amazon.com` in Edge, everything works as expected.

On Chrome, all cases work as expected.

## Possible Solution

This only started happening since the last Edge update I believe. They must have broken something, but I don't see it yet. I'm hoping for a more stable overall approach, as this login page has been causing issues for me in various scenarios already.

## Steps to Reproduce (for bugs)

1. Add an entry for the AWS console login page.
2. Visit the AWS console login page.

## Debug info
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Microsoft Edge 75.0.131.0

**Comment by varjolintu** [comment]
Thanks for reporting. Gotta check out if this is related to Predefined Sites feature or Edge update.

**Comment by oliversalzburg** [comment]
Let me know if there's anything I can look into.

I took a brief look and could at least confirm that the `formInputs` are correctly found and contain the 3 input fields I'd expect.

But no buttons are created and when I use the hotkey, I get the entry selection on the username field, click my entry and then nothing happens.

**Comment by oliversalzburg** [comment]
![image](https://user-images.githubusercontent.com/1658949/100855984-1dcced80-348b-11eb-9d1e-4b17a7742dfb.png)

This doesn't seem right...

**Comment by varjolintu** [comment]
Is there any difference if you disable Predefines Sites from the extension settings?

On `signin.aws.amazon.com` everything works for me with Edge.

**Comment by oliversalzburg** [comment]
That wasn't it. But I realized that the site has made it into some unexpected preferences in the KeePass extension settings somehow. After deleting the domain-specific entries from the settings, the login buttons are back.
