### ISSUE TITLE
Norisbank Webpage not able to parse / detect fields correctly

### ISSUE THREAD

**Issue by Linkinsoldier** [keepassxreboot/keepassxc-browser#1132]
## Overview
Since 2 Factor authorization is introduced in all banking sides (in europe), I feel more secure to store banking passwords in KeepassXC. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to: https://meine.norisbank.de/trxm/noris/
2. Try to input data via keepass
3. No correct detection possible - even if one manually tries to detect the fields again

## Expected Behavior
Fields are detected and Input is possible:
Filiale = 3 digit number - as far as I know it is always 431 
Kundennr = 7 digit customer ID - this is unique
Unterkonto = 2 digit number - as far as I know it is always 00 or 01
PIN(5-stellig) = is the actual password

## Actual Behavior
One can store the PIN and the "Unterkonto" (almost always 00) - but I think it would be best to store all 4 fields or at least the "customer ID" (Kundennummer) and PIN. For me, the customer ID is the only one I can not remember :)

## Context
Bankling Login to norisbank. Maybe the demo mode helps to understand the issue:
https://www.norisbank.de/demokonto/loginpin/goto.do

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.2
Firefox Addon UptoDate

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
Here are the steps:
- In your entry, use Kundennr as your username and PIN as your password
- Add two attributes to your entry: `KPH: filiale` with value `431` and `KPH: underkonto` with value `01` (or `00`)
- Go to the web page, select `Custom Login Fields` from the extension popup.
- Select Konto as username field, and PIN and password field, skip TOTP field
- After that select Filiale (shows as String Field 1) and Underkonto (shows as String Field 2)

Then fill the credentials normally. The extra fields shoul be filled also. String Field 1 will use the first `KPH` attribute, so it fills the value of `KPH: filiale`. Second String Fields fills the second KPH attribute.

**Comment by Linkinsoldier** [comment]
Awesome - works as a charm! Thank you

**Comment by droidmonkey** [comment]
This should form the foundation of the documentation example
