### ISSUE TITLE
Focus vault password input field when reopening the db

### ISSUE THREAD

**Issue by silas229** [keepassxreboot/keepassxc-browser#1133]
## Expected Behavior

The opened window should also be focused so that the Tresor password is not accidentally entered in the browser input field and you do not have to click on the new window

## Current Behavior

KeePassXC is opened in the foreground, but the window is not focused, so you cannot enter the password directly.

## Possible Solution

I don't know if this change has to be done in the browser extension or in KeePassXC itself, probably in both?
## Steps to Reproduce (for bugs)

1. Lock your db
2. Click on an login input field in your browser
3. Click on "Open database"

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win
Browser: Chromium Edge

**Comment by silas229** [comment]
Do you have a reference to the original issue?

**Comment by droidmonkey** [comment]
Its pinned
