### ISSUE TITLE
Repeat Preferences in Firefox Extension Settings

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc-browser#1134]
The extension’s General Settings contain two labels for two separate checkboxes that are identical — or confusingly similar — even though the extension’s code suggests that the checkboxes control two different settings.

## Expected Behavior

Extension settings should be laid out so that it is immediately obvious what each control does and what the status of a particular feature is.

## Current Behavior

On Firefox, in the extension’s “General Settings,” there are two instances of "Save domain only,” both of which state "When saving new credentials, save only the domain instead of full URL.” It appears once in General Settings → Saving Credentials and once in General Settings → Advanced Settings.

Furthermore, the status of the boxes does not synchronise: it is possible to enable one without enabling the other, leaving the user in doubt as to the status of the feature.

## Possible Solution

① If the boxes control different features, re-write their labels to make them clearer.

② If this is a mistake and the two checkboxes control the same setting in the background, remove one of the two.

## Steps to Reproduce (for bugs)

1. Install the extension in Firefox
2. Open the extension’s settings by clicking on its icon
3. Scroll down the General Settings

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: macOS (probably irrelevant)
Browser: Firefox 84.0

**Comment by varjolintu** [comment]
The help texts already makes the difference clear.
