### ISSUE TITLE
No autofilling nor autosubmit for TOTP Fields

### ISSUE THREAD

**Issue by Skity** [keepassxreboot/keepassxc-browser#1136]
## Expected Behavior
There is an option for username & password to AutoFill and submit forms.
But, there is not for OTP Fields.
What's expected is the OTP field is automatically fill up and form submitted.
In case it's a TOTP and it submits just at the bad timing where the OTP is resetted, we should have an option to retry a second time automatically just after the first auto submit with a small delay which could be setup (1, 5, 10s...).

## Current Behavior
We have to click manually on the icon at the end of the input field form and submit manually the form

## Possible Solution
cf Expected Solution

## Steps to Reproduce (for bugs)
Setup TOTP entries on KeepassXC software/database
enable "Activate 2FA/OTP field icons." on the Browser plugin.
Click on the field icon instead of having it auto fillup

## Debug info
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Mozilla Firefox 83.0

**Comment by varjolintu** [comment]
Related: https://github.com/keepassxreboot/keepassxc-browser/issues/728

**Comment by varjolintu** [comment]
Handling this in the original feature request issue.
