### ISSUE TITLE
Credentials no longer loaded after checking "remember my decision"

### ISSUE THREAD

**Issue by alephzerox** [keepassxreboot/keepassxc-browser#1143]
## Expected Behavior
Load the username and the password upon clicking the KeePassXC-Browser icon that appears in the username field.

## Current Behavior
There is a specific site where nothing happens when the button is clicked. I've already seen it work on this very site so the addon is able to identify the correct HTML fields, find the KeePass entry and fetch it from KeePassXC. That shouldn't be the problem. The same feature works perfectly on other sites as well.

The feature stopped working on this specific site after I made the addon remember my decision to allow access to the credentials.

## Possible Solution
Is it possible that I accidentally clicked on "Deny" instead of "Allow"? Note that the green key icon is still displayed in the username field. How can I make it forget that decision?

Is there any other way (log, etc.) I can tell why the form is not filled in?

## Steps to Reproduce (for bugs)
See current behavior.

## Debug info
KeePassXC - 2.3.1
KeePassXC-Browser - 1.7.3
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
Very possible you clicked deny. You can go to that entry and delete the custom data for the browser extension under properties.

**Comment by alephzerox** [comment]
Yes, this solved the issue, thanks. Suggestion: this is a UX issue. Can you add a hint to the "remember this" label as to how to revert that decision?
