### ISSUE TITLE
the extension doesn't auto type on http://site.com when you signup on http://www.site.com

### ISSUE THREAD

**Issue by x0rld** [keepassxreboot/keepassxc-browser#1145]
## Expected Behavior
That could be usefull if the extension detect the domain not the url saved

## Current Behavior
I have to add a new url or a new entry to make the auto type work
![image](https://user-images.githubusercontent.com/45242856/102069855-9c684a00-3dfe-11eb-8b81-5b1a97cfef49.png)

## Steps to Reproduce (for bugs)
1. signup on a website
2. try login on the website without typing the www before the domain name
3. the extension doesn't know http//site.com is the same as http://www.site.com

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux x86_64
Browser: Vivaldi/Chromium 86.0.4240.198

**Comment by varjolintu** [comment]
`http://site.com` works as a wildcard for `https://*.site.com`, just as `https://subdomain.site.com` would match `https://*.subdomain.site.com`. So, if your entry URL has `www` in it, it tries to match the `www` subdomain instead of `site.com`.

**Comment by droidmonkey** [comment]
There might be an opportunity to improve the ux here. WWW is a widely used subdomain and we can make an exception for this case, perhaps.

**Comment by varjolintu** [comment]
@droidmonkey That could propably lead to some problems if user wants to match `https://subdomain.site.com` but not `https://www.site.com`.

**Comment by droidmonkey** [comment]
Good point, tough problem to solve.

**Comment by x0rld** [comment]
I always thought the wildcard is not possible cause when I try it, it's in red like it cannot work 
![image](https://user-images.githubusercontent.com/45242856/102111299-7bbbe680-3e36-11eb-8f2e-ab2f6a2c2ba4.png)

**Comment by droidmonkey** [comment]
It is implied
