### ISSUE TITLE
Autofill not working for verizon.com, even when using custom fields

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#1147]
## Expected Behavior
Should be able fill the login form on https://secure.verizon.com/vzauth/UI/Login either by default or with manually specifying custom fields.

## Current Behavior
When going to https://secure.verizon.com/vzauth/UI/Login, there is no drop-down on the username field. Right clicking and doing "Fill username and password" does nothing. Setting custom fields, refreshing the page, and trying again does nothing.

## Steps to Reproduce (for bugs)

1. Create keepass entry for https://secure.verizon.com
2. Go to https://secure.verizon.com/vzauth/UI/Login and try to get auto fill to work with our without custom login fields

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Cannot reproduce. I had no problems filling the credentials to the site after choosing the correct input fields via Custom Login Fields.

**Comment by nbartos** [comment]
I tried again and after specifying the fields, I did a shift+reload and also tried going to the URL again in the same tab, and it did not work. However I was able to get it to work in a new tab. I guess for some reason that is required.
