### ISSUE TITLE
Two steps credentials plus custom fields (better use of "KPH: inputName")

### ISSUE THREAD

**Issue by freMea** [keepassxreboot/keepassxc-browser#1149]
## Steps to Reproduce (for bugs)
Here is a link to page 1 of credential. You won’t be able to see page 2 if you don’t have an account in this administration (sorry for the inconvenience) : [https://wwwd.caf.fr](https://wwwd.caf.fr/wps/portal/caffr/login/!ut/p/a1/04_Sj9CPykssy0xPLMnMz0vMAfGjzOID_A3dPbyDDdz9A1yNDTxdzQNDXJ19DS0CjYAKIoEKDHAARwNC-sP1o8BK8JhQkBthkO6oqAgArtbX2Q!!/dl5/d5/L2dBISEvZ0FBIS9nQSEh/#/authmotdepasse)

Page 1 is currently properly filled by extension with this values (according to their alphabetical order and when _choose own credential fields_ is set)
![image](https://user-images.githubusercontent.com/22337329/102130467-335df200-3e51-11eb-8f67-e2fd4be5ac4e.png)

This is page 2 with password input undetected because of custom credentials saved in browser storage, I guess.
![image](https://user-images.githubusercontent.com/22337329/102128536-51762300-3e4e-11eb-8e50-712a82dee94f.png)

Username html code:
![image](https://user-images.githubusercontent.com/22337329/102138025-06fba300-3e5c-11eb-8327-277712a0bf09.png)

## Current Behavior
_Domain (https://wwwd.caf.fr/) added with **detect username only** option with no success._

Currently, with _choose own credential fields_ button I can set _**keepassxc-browser**_ and **_keepassxc_** to fill username + KPH in page 1. But password input in page 2 (same url) won’t be detected and cant not even be filled via context menu. 

If I don’t customize _own credential fields_, extension won’t detect the username in page 1 (because exotic input name: **_numeroAllocataire_** I guess) but will detect password (because of its type I guess) in page 2.

So no way to have them both autofilled/detected. Either one or the other.

## Expected Behavior
Extension should always check `KPH: inputName` (that matches the input html code instead of using them alphabetically) and fill any fields that match **inputName** and url. There should be no need to play with _choose own credential fields_ button. Anyway, not until it’s not able to create/update proper `KPH: inputName` in database instead of using browser's localStorage that user can not edit.

And this auto read `KPH: inputName` shouldn’t prevent two steps credentials.

### Manual edition of entry, add additional attributes.
* Save custom field in `KPH: inputName`.
* Even save the username and password whose value would be {username} or {password} but protected. (Would it be a security breach ? I hope not.)
* Of course, password should only fill input with `type="password"`

![image](https://user-images.githubusercontent.com/22337329/102127296-a31dae00-3e4c-11eb-9b7b-7d2eb34083f3.png)
![image](https://user-images.githubusercontent.com/22337329/102127670-10c9da00-3e4d-11eb-941a-7054dc2bd17c.png)

* Add a setting section in extension to custom input name include/exclude list like **Kee - Password Manager** extension. This would make the `KPH: inputName` for username non-mandatory.
![image](https://user-images.githubusercontent.com/22337329/102133537-8a65c600-3e55-11eb-97c1-7e8e3fc7797b.png)

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Vivaldi 3.5.2115.81 (Stable channel) (64 bits) (Chromium 87.0.4280.107)

**Comment by varjolintu** [comment]
You can use the attributes as `KPH: 1 inputName`, `KPH: 2 secondField` etc. instead of alphabetical order.

> Extension should always check KPH: inputName (that matches the input html code instead of using them alphabetically) and fill any fields that match inputName and url.

This will not work. There's no standard way to define a input field name and most of the sites doesn't use anything the identify the username/password fields. This is why the extension generates a unique ID for the input fields.

I agree there can be a possible issue with two step login pages and Custom Login Fields, especially if the page URL doesn't change. There's some room for improvement.

**Comment by freMea** [comment]
> You can use the attributes as `KPH: 1 inputName`, `KPH: 2 secondField` etc. instead of alphabetical order.

I know. It’s still alphanumeric order.

> This will not work. There's no standard way to define an input field name and most of the sites doesn't use anything the identify the username/password fields. This is why the extension generates a unique ID for the input fields.

On what criterion input fiel ID are generate ? Can’t it be saved in database where user could possibly edit it ?

> I agree there can be a possible issue with two step login pages and Custom Login Fields, especially if the page URL doesn't change. There's some room for improvement.

Yes. Coming from kee extension where anything is possible with keepass, I think I will stay with this duo until **keepassxc-browser** improve.

**Comment by mtnakayama** [comment]
I have run into this problem as well. There are some sites that have pages which do not need the username to login but require other fields in addition to the password.

**Comment by varjolintu** [comment]
Anyone who wants to help and has a site with problems, please test the branch where https://github.com/keepassxreboot/keepassxc-browser/pull/1390 is created from. It would help a lot to catch any remaining problems with the new implementation before the new release. Thanks :)
