### ISSUE TITLE
Brave Browser Native Messaging Host not connecting to keepassxc-proxy

### ISSUE THREAD

**Issue by Neurognostic** [keepassxreboot/keepassxc-browser#1150]
# Brave Browser NativeMessagingHost not executing keepassxc-proxy

## Expected Behaviour

Connect [keepassxc-browser](https://github.com/keepassxreboot/keepassxc-browser)  extension from Brave Browser with [keepassxc](https://github.com/keepassxreboot/keepassxc) database.

> NB. Firefox works as expected.

## Current Behaviour

KeepassXC-Browser fails to start `keepassxc-proxy` and connect to KeepassXC database.

## Steps to Reproduce (for bugs)

1. Add Brave and Chromium (just in case) check in KeepassXC Settings->Browser Integration->General->Enable integrations for these browsers:
2. Start Brave Browser
3. Click "Reload" in KeepassXC extension  _or_ navigate to `chrome-extension://oboonakemofpalcgghocfoadofidjkkk/options/options.html` and click "Connect" in "Connected Databases."
4. See error message "Key exchange was not successful."

## Debug info

Console messages when clicking "Reload" in the extension menu:
 
```console
keepass.js:1142 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings/
keepass.js:1059 Connecting to native messaging host org.keepassxc.keepassxc_browser   keepass.js
keepass.js:1029 Failed to connect: Specified native messaging host not found.
keepass.js:1142 Error 9: Key exchange was not successful.
```

When running the `strace(1)` command from the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) for `brave-browser(1)` processes nothing gets printed for `keepass`.

Contents of `$XDG_CONFIG_HOME/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`:

```json
{
    "allowed_origins": [
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.3
Operating system: Linux
Browser: [Brave Browser](https://brave.com/)

**Comment by droidmonkey** [comment]
Is brave installed as a snap? Do you use firejail or similar?

**Comment by teslations** [comment]
I get the same error messages. Brave is not installed as a snap and it's not sandboxed in any other way.
KeepPassXC 2.3.4, KeePassXC-Browser 1.7.6, Linux debian 4.19.0-14-amd64, Brave Browser 1.20.103
Firefox also gets the same errors.

**Comment by varjolintu** [comment]
@teslations I suggest trying to use newer version of KeePassXC. If your Debian repos doesn't have the latest version, you can always download the official AppImage.

**Comment by teslations** [comment]
Thank You very much varjolintu. It now works.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
