### ISSUE TITLE
Cannot detect OpenWRT router's login fields

### ISSUE THREAD

**Issue by weiwang11** [keepassxreboot/keepassxc-browser#1151]
## Expected Behavior
Should be able to detect Username and Password field on Firefox.

## Current Behavior
Does not detect Username and Password field even after setting custom login fields on Firefox.

## Steps to Reproduce (for bugs)

1. Go to router's OpenWRT page on Firefox.
2. KeePassXC-Browser doesn't detect the login fields on Firefox.
3. I have not tested this on another browser besides Firefox.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Browser: Firefox

**Comment by varjolintu** [comment]
As I don't have an OpenWRT router, could you please share the source code of the login page?

**Comment by weiwang11** [comment]
I pasted the code here: https://gist.github.com/weiwang11/a0244d7e746716f6d5309fba194f96ba

**Comment by varjolintu** [comment]
I had no problems detecting fields with that source file.

**Comment by weiwang11** [comment]
I think I fixed the issue on my end.

It was due to the KeePassXC-Browser Settings denying the ip address for openwrt, I forgot that I set it as I copied it from a previous entry with the stock router firmware as it had http basic auth.

However, I didn't see the configuration for the ip address in Keepass-Browser's setting denying it, nor on the entry in the password manager.
