### ISSUE TITLE
UX of credential selection is broken

### ISSUE THREAD

**Issue by KleinByte** [keepassxreboot/keepassxc-browser#1153]
## Summary
![image](https://user-images.githubusercontent.com/57239407/102367064-f5f78280-3f7e-11eb-9fc2-12e1ed38f1ba.png)
UI behavior and appearance are wacky, unpredictable, and unintuitive.

The autocomplete/finish is too aggressive. ( keepassxc detects fields that are not even close to login fields on some websites. When fields are incorrectly detected, it's impossible to enter anything into the field as keepassxc clears and overwrites login credentials once the field is submitted

This is very annoying when it comes to entering a different login than what's in keepassxc database. 

Opinion:

- Make the auto-complete on login forums less aggressive.
- Add keepassxc right-click menu option to disable a selected field. 
- Move the UI into a spot that's less likely to create conflict or issues

**Consideration?** 
![image](https://user-images.githubusercontent.com/57239407/102370515-c34f8900-3f82-11eb-8451-6d654480969e.png)
Is it possible to move the interface as a dropdown? This method is much easier/intuitive from a user perspective.

**Comment by varjolintu** [comment]
You can disable the Autocomplete feature and use just the popup for filling, if that suits you better.
