### ISSUE TITLE
Reports Win32 when on x86_64 on the about page of the Chrome browser extension

### ISSUE THREAD

**Issue by gianttor** [keepassxreboot/keepassxc-browser#1155]
## Expected Behavior

Display the correct OS info on the extension page.

## Current Behavior

The settings page of the extension lists win32 as the OS when on x86_64

I don´t know how important this is but If anything relies on this info it will not act properly

## Steps to Reproduce (for bugs)

Go to settings on the browser extension page and click on the About page. It reports OS as win32 when on x86_64

1.
2.
3.
4.

## Debug info

About info provided by:

**EXTENSION**
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.3
Operating system: Win32
Browser: Chrome/Chromium 87.0.4280.88

**APPLICATION**
KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**cheers!!!**

**Comment by droidmonkey** [comment]
You are probably running a 32 bit browser.

**Comment by gianttor** [comment]
Not really...
From my chrome About page...
Google Chrome is up to date
Version 87.0.4280.88 (Official Build) (64-bit)

I figure that it is prolly irrelevant, but its there... and it´s wrong.
Sorry if I wasted your time...

**Comment by droidmonkey** [comment]
Good to know!

**Comment by varjolintu** [comment]
Gotta finally fix this. Windows still wants to show "Win32" in the browser info even if you are running a 64-bit system. Need to parse the info from somwhere else.
