### ISSUE TITLE
Limit Frequency of Auto-submit Login Forms

### ISSUE THREAD

**Issue by bkonia** [keepassxreboot/keepassxc-browser#1161]
The Auto-submit Login Forms option is convenient. However, if you accidentally store invalid credentials, or if saved credentials expire, it can result in an infinite loop, whereby it attempts to log in, the authentication fails and the website redirects back to the login page, where the extension tries to log in again and so on... Since each attempt occurs so quickly, this could be interpreted by the website as a brute force hack attempt, resulting in your IP address being banned.

Therefore, I'd like to suggest an option that would temporarily disable the Auto-submit feature for a configurable number of seconds after each login attempt. For example, you could configure it for five seconds. So, if it tries to log in and is redirected back to the login page within five seconds, it would not perform the auto-submit a second time. It could still fill the credentials, but the user would have to click the login button manually.  The extension could simply store the time of the most recent log in attempt for each entry and if it receives another login page for the same entry within the specified number of seconds, it would not perform the auto-submit.

**Comment by varjolintu** [comment]
Note to myself: This would need a implementation to the background script because content scripts will change on every login attempt.
