### ISSUE TITLE
Weird things with sites not actually fill in

### ISSUE THREAD

**Issue by ubronan** [keepassxreboot/keepassxc-browser#1163]
For example i have f-secure being set triple in the database but its amazing it does not find them nor actually does not fill it.
So i tried to add a few but nope nothing ... so no clue why this happens on several sites, so there is login info saved at the exact same page but it simply refuses to fill the data...
https://my.f-secure.com/login?locale=nl_NL&ccid=safelogin thats the page where i detected it, and it still needs to be filled by hand from the databse it simply does not fill at all.
I do not remember all the sites which fail this is just the last one where i have this weirdness

**Comment by varjolintu** [comment]
You can add more URL's to the same entry when you edit it and go to Browser Integration page.

For F-Secure page, use `https://my.f-secure.com` as you entry URL.

**Comment by ubronan** [comment]
ah lol darn i never noticed that sorry about that :D

Op do 7 jan. 2021 om 16:15 schreef Sami Vänttinen <notifications@github.com

**Comment by varjolintu** [comment]
So.. does everything work now?
