### ISSUE TITLE
Loss of synchronisation between keepassXC and keepass-browser

### ISSUE THREAD

**Issue by HDInfautre** [keepassxreboot/keepassxc-browser#1165]
Hello
I have the latest versions of keepassXC and keepass-browser under Ubuntu 20.04
I have 5 databases (personal, professional, association ...)
3 databases are open in an appimage
2 databases are open in a 2nd instance appimage
Each database is linked to a Firefox profile
Everything works fine most of the time :-) except that if I'm on a profile, I have to focus on the corresponding database of the keepassXC appimage.

I have the impression that the problem happens when I have 2 appimage instances open at the same time (which can happen from time to time).
At a given moment if I open database n°3 with keepassXC/appimageA, no more recognition is done if I have the 2nd instance appimageB open at the same time (even if the databases are closed) !
I may have closed the 2nd instance keepassXC/appimageB, but I can't do anything anymore. I sometimes have to restart the keepassxc-snap-helper.sh script.
regards

## Debug info

 KeePassXC-Browser version : 1.7.4
Version de KeePassXC : 2.6.2 
Ubuntu 20.04
Firefox (latest version).

**Comment by varjolintu** [comment]
May I ask why are you using two KeePassXC's at the same time? I doubt that works flawlessly. Do you have the similar problem if you use only one KeePassXC and all 5 databases with it?

**Comment by HDInfautre** [comment]
Because I have a usb key with the 2nd instance and these 2 bases. I don't want the bases to be visible in the 1st instance.
Could there be a solution by keeping these 2 instances?

**Comment by varjolintu** [comment]
Even if all the databases are visible in the 1st instance those have no connection with each other. Are you assuming there's some kind of threat situation?

**Comment by HDInfautre** [comment]
HI
Thank you for your prompt follow up
1/ Each one works well. It's just annoying to re-run the script that links the 2 programs and restart firefox!
If you reproduce the problem, maybe you can consider putting it in the roadmap?
2/ Would it be possible that the firefox profile connects automatically to the database that is linked, even if you have the focus on another keepassXC database?
Regards

**Comment by droidmonkey** [comment]
We don't support running multiple instances of keepassxc like this. We will not support that. The proxy run location, for one reason, is a big problem to overcome. Also the two instances will both try to open the native messaging socket. This is not going to happen, pick one to use and stick to it.

**Comment by HDInfautre** [comment]
Hi,
sad but I understand that it is difficult to put in place. I was pushed into another thread to set up keepassXC in appimage.

I hope that a developer member will be able to do a step by step tutorial (faq, video?) to get a snap instance and an appimage instance, which would probably be the best solution?
Good continuation

**Comment by droidmonkey** [comment]
There is no sense in doing what you are attempting. Perhaps a snap instance with Firefox could coexist with an appimage instance with Chrome, for example.

**Comment by HDInfautre** [comment]
This is exactly what I wanted to put in place.
**I got firefox snap to work with firefos appimage (not chrome)** by following this
https://docs.appimage.org/user-guide/portable-mode.html
https://discourse.appimage.org/t/portable-configuration-data/105/10
That's not the subject here but if I understood how to do that would solve the post here. 
Afterwards, if you don't want to help me (tutorial ...), I have nothing more to say. Thank you for your work
