### ISSUE TITLE
It does not work on amazon.ca

### ISSUE THREAD

**Issue by rhazegh** [keepassxreboot/keepassxc-browser#1166]
## Expected Behavior

Fill in the username (the email in this case)

## Current Behavior

Does not fill in the username

## Possible Solution

None that I could find.

## Steps to Reproduce (for bugs)

1. Browse to https://amazon.ca an then try to login

2. On the login page, you will only see "E-mail address or mobile phone number". 
<img width="435" alt="Screen Shot 2021-01-08 at 16 52 40 " src="https://user-images.githubusercontent.com/2200559/104067895-fd065f00-51d1-11eb-8402-60b49cd55f5c.png">

3. Clicking on Keepass icon won't fill the user name.

4. Go to "KeePassXC-Browser > Site Preferences" and add this URL: https://www.amazon.ca/* and check the "Userrname-only Detection"
<img width="1425" alt="Screen Shot 2021-01-08 at 16 55 18 " src="https://user-images.githubusercontent.com/2200559/104068223-89b11d00-51d2-11eb-9986-b2bdee1ac810.png">

5. Refresh the login page. Click on the keepass icon and it will not fill in the user name.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: MacIntel
Browser: Mozilla Firefox 84.0

**Comment by rhazegh** [comment]
Never mind.  I restarted the Keepass and the browser. Tried again and now it work.

Thanks for making this great extension ❤️

**Comment by varjolintu** [comment]
Ps. You don't need the entry for Amazon in the Site Preferences anymore. It's handled automatically.
