### ISSUE TITLE
"Disable for this Site" not remembered on Brave Browser

### ISSUE THREAD

**Issue by antrys** [keepassxreboot/keepassxc-browser#1167]
## Expected Behavior
When you have multiple entries for passwords for a site (because of subdomains, multiple accounts, etc) the extension gives you the option in the pop-up dialog do "disable for this site."    When you choose to disable a particular login for a site, it should remember your choice.

## Current Behavior
With Brave browser, these choices are never remembered and it asks you every time, regardless of what you have previously chosen to disable.

## Possible Solution
Is brave blocking some scripting that the plugin uses?

## Steps to Reproduce (for bugs)

1. Go to site where you have multiple logins.
2. Plugins give you choice to disable for this site.  Click it and it disappears.
3. Close Browser, reopen and reload page.
4. Disabled login is back as a choice.

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Linux Mint 20
Browser: Brave

**Comment by droidmonkey** [comment]
That pop-up comes from keepassxc application itself and does not matter what browser you are using at that point.
