### ISSUE TITLE
Bug : Synology NAS login Page have two KeepassXC icons

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#1175]
Attached you can find the behavior ? 

Tested with MS Edge chromium . 

Which logs do you need ?

![image](https://user-images.githubusercontent.com/8161283/104368903-ff8fee00-551c-11eb-86e2-9b24f56c86fc.jpeg)

**Comment by varjolintu** [comment]
Can you give the page source code that contains the form?

**Comment by F3000** [comment]
Is this OK for you ? 

<img width="484" alt="Bildschirmfoto 2021-01-17 um 21 29 29" src="https://user-images.githubusercontent.com/8161283/104855238-e36cc200-590b-11eb-8feb-d47cd0137fa5.png">

<img width="546" alt="Bildschirmfoto 2021-01-17 um 21 29 49" src="https://user-images.githubusercontent.com/8161283/104855244-e798df80-590b-11eb-887a-f92a774d2593.png">

<img width="660" alt="Bildschirmfoto 2021-01-17 um 21 30 37" src="https://user-images.githubusercontent.com/8161283/104855253-f384a180-590b-11eb-8288-e4fbf06d22d7.png">

<img width="555" alt="Bildschirmfoto 2021-01-17 um 21 30 18" src="https://user-images.githubusercontent.com/8161283/104855247-ec5d9380-590b-11eb-9719-1a37618e4c02.png">

<img width="603" alt="Bildschirmfoto 2021-01-17 um 21 30 55" src="https://user-images.githubusercontent.com/8161283/104855258-fa131900-590b-11eb-8dd3-438f43d45dbe.png">

<img width="660" alt="Bildschirmfoto 2021-01-17 um 21 32 51" src="https://user-images.githubusercontent.com/8161283/104855264-0008fa00-590c-11eb-9112-879ce44a2adc.png">

<img width="632" alt="Bildschirmfoto 2021-01-17 um 21 43 37" src="https://user-images.githubusercontent.com/8161283/104855447-211e1a80-590d-11eb-84d6-4d83de9a883e.png">




First field (username) 
`<input type="text" class="x-form-text x-form-field textfield" id="login_username" name="username" maxlength="256" aria-describedby="ext-gen51" aria-label="Benutzername" aria-readonly="false" aria-required="false" aria-disabled="false" aria-invalid="false">`


Second field (password) 
`<input type="password" class="x-form-text x-form-field textfield" id="login_passwd" name="passwd" maxlength="256" autocomplete="off" aria-describedby="ext-gen52" aria-label="Passwort" aria-readonly="false" aria-required="false" aria-disabled="false" aria-invalid="false">`

Checkbox text: 
`<div class="x-form-check-wrap syno-ux-form-check-wrap" id="ext-gen45" style="margin-left: 0px; width: 278px;"><input type="checkbox" role="checkbox" autocomplete="off" class="syno-ux-checkbox-icon x-form-checkbox x-form-field" id="login_rememberme" name="rememberme" aria-describedby="ext-gen44" aria-label="Bleibe angemeldet" aria-readonly="false" aria-required="false" aria-disabled="false" aria-level="1" aria-checked="false" aria-invalid="false" aria-labelledby="login_rememberme-label-el"><div class="syno-ux-checkbox-icon" id="login_rememberme-icon-el"></div><label for="login_rememberme" class="syno-ux-checkbox-label" id="login_rememberme-label-el">Bleibe angemeldet</label><div role="presentation" class="x-form-hidden-error-msg" id="ext-gen44"></div></div>`

checkbox:
`<div class="syno-ux-checkbox-icon" id="login_rememberme-icon-el"></div>`


Button :
`<span id="login-btn" cellspacing="0" class="x-btn syno-ux-button syno-ux-button-blue x-btn-noicon" style="margin-left: 0px; width: 278px; height: 38px;"><em class=" x-unselectable" unselectable="on"><button type="button" id="ext-gen48" aria-label="Anmelden" class=" x-btn-text" aria-level="1" aria-disabled="undefined">Anmelden</button></em></span>`

Error message : 
`<div class="x-form-item x-hide-label" tabindex="-1" id="ext-gen38"><label for="sds-login-dialog-status" style="width:180px;" class="x-form-item-label" id="ext-gen39"></label><div class="x-form-element" id="x-form-el-sds-login-dialog-status" style="padding-left:185px"><div id="sds-login-dialog-status" name="sds-login-dialog-status" class="x-form-display-field error" aria-describedby="ext-gen40" aria-readonly="false" aria-required="false" aria-disabled="false">Das Konto oder Passwort ist ungültig. Bitte versuchen Sie es noch einmal.</div><div role="presentation" class="x-form-hidden-error-msg" id="ext-gen40"></div></div><div class="x-form-clear-left"></div></div>`

**Comment by varjolintu** [comment]
I need the whole source code of the form.

**Comment by F3000** [comment]
So here is the whole source code for the login page : 
[synology-source-code.txt](https://github.com/keepassxreboot/keepassxc-browser/files/5832229/synology-source-code.txt)

**Comment by F3000** [comment]
You can visit this site to test it online : https://demo.synology.com/de-de/dsm#dsm70beta

https://a182.dsmdemo.synology.com:5001/

**Comment by varjolintu** [comment]
I cannot no longer reproduce this problem.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
