### ISSUE TITLE
Twitter Search field falsely identified as login field

### ISSUE THREAD

**Issue by topgearbw** [keepassxreboot/keepassxc-browser#1176]
Using current Firefox and KeepassXC Browser Plugin the Twitter search field is falsely recognized as a login field and, given the according Settings, the Key Symbol and the Login Dropdown appear.
When I try to enter a search term and press Enter one of my twitter Login entries is picked and [Username] is entered as search term.
Current workaround is disabling autofill dropdown (which i would really like to keep active) when using Twitter search.
So far Twitter has been the only site where this happend to me.
Somehow that very search field seems to meet the criteria to be seen as a login input field.
Maybe an option to explixitly rule out false positive fields in the user-defined site-specific field picker could do the trick.
![twSearchKeepassxc](https://user-images.githubusercontent.com/15685256/104357515-9785db80-550d-11eb-8ed7-c106da38711c.png)

**Comment by varjolintu** [comment]
I cannot reproduce this. Does this happen with every Twitter page, for example https://twitter.com/signalapp? Or when you are logged in? Are there any settings in your Site Preferences?

**Comment by topgearbw** [comment]
Could not reproduce on new empty Firefox Profile as well.
Deleting site preferences in the default profile solved the above Problem. My apologies.
Funfact: Twitter only showed the User Field on the login page afterwards, no password field, which is why I had created those site preferences initially. Deleting all twitter cookies brought back the default two-field login page.
