### ISSUE TITLE
fill credentials icon doesn't show for paypal login page

### ISSUE THREAD

**Issue by FischLu** [keepassxreboot/keepassxc-browser#1177]
Normally, for a login page, a "fill credentials" icon should be there at the right side of username input box. But here is nothing for Paypal, I tried Paypal US and Germany, both doesn't work. I have used "choose custom login fields" function to select the username and password field, but doesn't help. Now the only working way is to use Auto-type function from KeePassXC.

![Clipboard01](https://user-images.githubusercontent.com/10261662/104431011-b759e580-5587-11eb-9666-10e107d4a19d.jpg)

## Steps to Reproduce (for bugs)

please try
https://www.paypal.com/us/signin
https://www.paypal.com/de/signin

## Debug info

KeePassXC - 2.62.
KeePassXC-Browser - 1.7.4
Operating system: Windows 10
Browser: Chrome and Firefox

**Comment by varjolintu** [comment]
Both pages look like this for me:
![Screenshot 2021-01-13 at 11 36 13](https://user-images.githubusercontent.com/24570482/104434172-97c8ba00-5593-11eb-9755-e56b8a308a02.png)

Refreshing the page doesn't help?

**Comment by FischLu** [comment]
> 
> 
> Both pages look like this for me:
> ![Screenshot 2021-01-13 at 11 36 13](https://user-images.githubusercontent.com/24570482/104434172-97c8ba00-5593-11eb-9755-e56b8a308a02.png)
> 
> Refreshing the page doesn't help?

I double checked, for Paypal US with Chrome it works like yours, but Firefox doesn't. For Paypal Germany, both browsers don't work..

for Paypal Germany I see some error message in Firefox console, not sure whether it is a reason, because the source of message is not from keepassxc-browser.js. The error is
```
XML Parsing Error: no root element found
Location: https://www.paypal.com/auth/verifygrcenterprise
Line Number 1, Column 1:
```
it is from verifygrcenterprise:1:1

**Comment by varjolintu** [comment]
Can you confirm from the web page sources that there are no iframes? I wonder if it redirects somewhere else.

**Comment by FischLu** [comment]
> 
> 
> Can you confirm from the web page sources that there are no iframes? I wonder if it redirects somewhere else.

I have partly solved the problem, but still feel strange. refresh page doesn't help till I switch off the add-on ublock origin. Then the icon is always there even I switch on the add-on again. I don't have any special block rule of the add-on. Anyway, it works, I will update when I figure out the real reason..
