### ISSUE TITLE
Browser Integration doesn't work on Ebay (and other sites)

### ISSUE THREAD

**Issue by YellowOnion** [keepassxreboot/keepassxc-browser#1178]
## Steps to Reproduce
1.  prompt generate password dialog
2. click "fill password"
3. 

## Expected Behavior
the password fills the password box

## Actual Behavior
fills some phantom input box

##Extra
I've noticed this behaviour on several different sites, must be some sort of common pattern used on sites for password boxes.

https://user-images.githubusercontent.com/364160/104539774-118ba100-5683-11eb-8400-c177edce3f23.mp4

KeePassXC - Version 2.6.2
Revision: e9b9582

Qt 5.15.1
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.6

**Comment by varjolintu** [comment]
Might be related to: https://github.com/keepassxreboot/keepassxc-browser/issues/861
