### ISSUE TITLE
Wrong OTP generation when multiple accounts for the same website

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc-browser#118]
When KeepassXC has multiple records for the same website (e.g. multiple amazon or google accounts), the OTP generation fails for all but the first one in the list.

## Expected Behavior
The OTP generation should  work for all records of the same website

## Current Behavior
The OTP generation fails when a website has multiple records stored in KeepassXC

## Possible Solution
It looks like that keepassxc-browser only picks the first OPT seed from the first, upmost list item for the website

## Steps to Reproduce (for bugs)
I have three google accounts: AccountA, AccountB, AccountC, all with 2FA enabled. When I choose to login with AccountB or AccountC, the OPT generated is always refused. OTP for AccountA is always accepted.

## Debug info
KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 Revision: 2fcaeea
Operating system: Ubuntu 17.10, x86_64, 4.13.0-38-generic
Browser: Firefox+Chromium
Proxy used: YES

**Comment by krenkel** [comment]
The issue id still present: Wrong OTP generation when multiple accounts for the same website

KeePassXC - 2.5.3

**Comment by varjolintu** [comment]
@krenkel Can you reproduce this with any site, or just one?

**Comment by krenkel** [comment]
> @krenkel Can you reproduce this with any site, or just one?

It occur for me at digitalocean.com, but i found the the way - to make different links for each account (eg cloud.digitalocean.com/login and cloud.digitalocean.com/login?i=06fb6c and its work)

**Comment by jahnf** [comment]
I can confirm that something is wrong with the OTP generation. 
When generating it from the GUI (Linux, 2.5.4), it is correct.
When generating it - filling it in with the TOPT field in the browser with the extension (2.5.4, Firefox, Linux) it seems sometimes correct on the first fill - but after that always incorrect and it seems not change (even after 30s have passed)

**Comment by droidmonkey** [comment]
Totally different issue. The browser extension does not continually poll for a new TOTP token, you'll have to refresh the page at this time. This is tracked over on the browser extension repo.
