### ISSUE TITLE
cannot connect to more than 1 database - have to define new connection after switching database

### ISSUE THREAD

**Issue by harpogo** [keepassxreboot/keepassxc-browser#1180]
I have two databases in KeepassXC. Always when I switch to to the other db KeepassXC-Browser extension only shows the 'Connect'-button and when I Click it Keepass asks for saving a new connection and I have to define a new one with a new key - when I give it the same name like the old existing it asks for overwriting. 

Same behavior in KeepassXC-Browser settings in 'connected Databases': there i always only the actual connected db shown. After clicking 'Connect' same behavior like above and after reloading preferences-page only the new connection is shown.

In Keepass itself 'Browser-Integration'-preference shows all of the defined connections (for each database and browser). But KeepassXC-Browser cannot find them after switching the database and I have to define a new connection. 

The actual connection is kept when I close and reopen the browser or Keepass or restart the system. It's the same behavior in Linux and in Windows and in both systems with Firefox and Vivaldi. Of course it's per browser, for each browser the last connection defined there is kept.

Is this a bug or works as implemented? I often use 2 or sometimes 3 databases at the same time and it's quite annoying always to connect to the other database with defining a complete new connection.

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Kubuntu 20.04 /Windows 10 x64
Browser: Mozilla Firefox 84.0 / Vivaldi 3.5

**Comment by droidmonkey** [comment]
Are you naming the connection the same name between each database?

**Comment by varjolintu** [comment]
Are your databases copy from the original one? Try using the following option before trying making a new connection: _KeePassXC -> Database Settings -> Browser Integration page -> Refresh database root group ID_.

**Comment by harpogo** [comment]
> Are you naming the connection the same name between each database?

No. Every connection gets a distinct name

**Comment by harpogo** [comment]
> Are your databases copy from the original one? Try using the following option before trying making a new connection: _KeePassXC -> Database Settings -> Browser Integration page -> Refresh database root group ID_.

@varjolintu Thanks. That seems to be the solution. Indeed 2 of 3 databases were copies. I deleted all connections on all databases, refreshed root group IDs and now after defining new connection it works.
