### ISSUE TITLE
ING.pl split password support

### ISSUE THREAD

**Issue by selfisekai** [keepassxreboot/keepassxc-browser#1181]
## Expected Behavior

logging into https://login.ingbank.pl/mojeing/app/#login and filling the password from KPXC

## Current Behavior

this monster appears
![image](https://user-images.githubusercontent.com/11798442/104751011-19b41100-5755-11eb-9848-572281f2d87c.png)

kpxc-browser doesn't know how to handle it and tries to fill the whole password into each input
![image](https://user-images.githubusercontent.com/11798442/104751391-9d6dfd80-5755-11eb-8341-4b42bfc61f46.png)

## Possible Solution

website-specific code for handling these things

## Steps to Reproduce (for bugs)

1. https://login.ingbank.pl/mojeing/app/#login
2. enter the login (clients only :cry:)

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Void Linux
Browser: Firefox

**Comment by varjolintu** [comment]
If I could I would sink that monster..

So, every time you login there's 5 random input fields activated?

**Comment by droidmonkey** [comment]
This is going to be supported in 2.7.0 with Auto-Type pickchars

**Comment by droidmonkey** [comment]
This is going to be supported in 2.7.0 with Auto-Type pickchars
