### ISSUE TITLE
Keepassxc-browser cannot connect to Keepassxc on Dissenter Web Browser

### ISSUE THREAD

**Issue by gonegoin** [keepassxreboot/keepassxc-browser#1182]
The extension is not connecting to Keepassxc. Tried Reload command to no avail
## Expected Behavior
Dissenter browser is based on Brave Browser, Chromium essentially and on Brave the extension works no problem, so it should work on Dissenter as well

## Current Behavior
The extension cannot connect to Keepassxc

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {latest}
KeePassXC-Browser - {latest}
Operating system: Linux Mint 20.1
Browser: Chromium (Dissenter)

**Comment by varjolintu** [comment]
Use the Custom Browser feature in KeePassXC's Browser Integration settings. This means you'll have to provide a path for Native Messaging with your browser. If you don't know it or can't find it from the browser's docs, you can use `strace` to search for the path. You can see an example here: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace

**Comment by gonegoin** [comment]
> Use the Custom Browser feature in KeePassXC's Browser Integration settings. This means you'll have to provide a path for Native Messaging with your browser. If you don't know it or can't find it from the browser's docs, you can use `strace` to search for the path. You can see an example here: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace

Thanks for the quick reply!  Your tip worked. The only trouble I had was to figure out what the PID is for Dissenter.  There were apparently a dozen or so PIDs, and I had to test them one by one to determine the correct one. 

Cheers
