### ISSUE TITLE
Browser extension displays  notification to update  keepassXC - hinders usability (and it's nagging)

### ISSUE THREAD

**Issue by ieugen** [keepassxreboot/keepassxc-browser#1184]
Hi,

Right now the browser extension displays a notice to update my KeepassXC version in a way that hides the button underneath. 

I've attached an screenshot.

![nagging-update-message](https://user-images.githubusercontent.com/1050920/104877769-40479700-5963-11eb-89d1-7a2ced816a99.png)

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 84.0

**Comment by droidmonkey** [comment]
Turn it off in the settings in the meantime

**Comment by ieugen** [comment]
Thanks, I disabled the look for updates option and it's gone.
