### ISSUE TITLE
2.6.3 did not work with Firefox extension

### ISSUE THREAD

**Issue by mooms06** [keepassxreboot/keepassxc-browser#1185]
In 2.6.3, the identifiers are not proposed anymore in the Firefox extension. Database is open, no errors showed.
I have downgraded to 2.6.2, everything is working again.

Windows 10 230h2 x64.
Firefox 84.0.2 x64
KeepassXC 2.6.2/2.6.3 x64

**Comment by varjolintu** [comment]
Please check the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and report what you find, thanks.

**Comment by mooms06** [comment]
I tried tu install 2.6.3 again today, it asked me to reboot, then after reboot everything is working.
Case closed.
