### ISSUE TITLE
Nothing happens when clicking KeePassXC icon (Firefox, Mac)

### ISSUE THREAD

**Issue by sunenj** [keepassxreboot/keepassxc-browser#1189]
I am using
KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: MacIntel
Browser: Mozilla Firefox 84.0
Extension connected to database and KeePassXC icons appear in fields, but nothing happens when I click them. Tried different sites, and also Chrome. Same problem.
Went through troubleshooting but found nothing.
Sune

**Comment by varjolintu** [comment]
Check your entry URL's first. Those should match the site. You can give an example about a site that doesn't work by telling both the login URL and your entry URL.

**Comment by sunenj** [comment]
Here is one example
login url: https://appleid.apple.com/da-dk/
entry url: https://appleid.apple.com/da-dk/
It finds the fields and adds icons, but nothing happens when I click

**Comment by varjolintu** [comment]
Apple uses an iframe for the login field. You'll have to modify your credential URL's to `https://idmsa.apple.com/` or just `https://apple.com`.
