### ISSUE TITLE
Browser integration doesn't work on Disneyplus.com

### ISSUE THREAD

**Issue by mekaneck** [keepassxreboot/keepassxc-browser#1190]
## Current Behavior

This website has separate pages for username and password. No keepass icon is shown on either page, and the right-click option to fill username or password does not work. Setting custom dialog boxes does not affect the issue. After logging in, the browser does not prompt to save the login.

## Steps to Reproduce (for bugs)

1. visit [www.disneyplus.com](url)

## Debug info
KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Win32
Browser: Chrome/Chromium 87.0.4280.141

**Comment by varjolintu** [comment]
Add `https://disneyplus.com/*` to extension's Site Preferences tab and enable `Username-only Detection` for it.

**Comment by mekaneck** [comment]
Thank you very much. Had to modify your answer with the WWW subdomain (`https://www.disneyplus.com/*`) but then it started working. The key was the asterisk, which I didn't have before. 

Is there a forum for asking for help like this so I don't clutter the issues list?

**Comment by varjolintu** [comment]
@mekaneck No separate forum available. Making a new issue about these kind of questions is ok. We are also available at #keepassxc (chat.freenode.net), which is also synced with #keepassxc:matrix.org.
