### ISSUE TITLE
Ubuntu Login (Launchpad) sends to password forgotten page, rather than hitting 'Log in' button

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#1192]
When trying to log in to [Ubuntu One/Launchpad](https://login.launchpad.net/) I can click on the green key icon KPXC's browser plugin. It fills in the login details, but then sends me to the password reset page.

This only seems to happen when I come from https://askubuntu.com and want to log in with my Launchpad credentials. So I'm on the page https://login.launchpad.net/4Qfm3QTOmhZ9cVA9/+decide and not on https://login.launchpad.net/ where I don't seem to have this issue.

## Expected Behavior

Fill in credentials and be logged in

## Current Behavior

Fill in credentials and open password reset page

## Steps to Reproduce (for bugs)

see above

## Debug info

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
I can't replicate. Do you have auto-submit enabled?

**Comment by keunes** [comment]
Autosubmit as in immediately on page load: no
Autosubmit as in fill in when hitting the key icon: yes

**Comment by droidmonkey** [comment]
Autosubmit as in the form submits after the information is filled. Or are you pressing ENTER?

**Comment by keunes** [comment]
> Autosubmit as in the form submits after the information is filled. Or are you pressing ENTER?

In that sense it's autosubmitting :) Not hitting enter.

**Comment by droidmonkey** [comment]
Both buttons are "submit" buttons under the same form. This is poor practice, in my opinion, and makes it very difficult for us to determine which one is correct. I am not sure why landing on this page from different start points causes the bug to occur or not, but I could replicate it easily when auto-submit was enabled.

![image](https://user-images.githubusercontent.com/2809491/105255038-d5f44980-5b50-11eb-9c0f-d994a2fd358b.png)

**Comment by varjolintu** [comment]
@droidmonkey Ignoring `formaction` should be fine. I haven't seen any forms that has "reverted" the actions, meaning `formaction` is the actual login and `action` is something else. So this should be fine.

**Comment by keunes** [comment]
Thanks both for looking into it!

**Comment by keunes** [comment]
I had created a bug report against Ubuntu SSO, and this was the reply:
> Sounds like a problem with the password manager - the ones built into chrome, firefox and standalone lastpass and 1password, at least, have no problem with the "forgot password" button.
> "forgot password" is a submit button because, if you type your email address and password, but they are incorrect, you get sent back to the login page, and if you then click "forgot password", the "email" field in the recovery page is helpfully prefilled with what you'd entered in the login page - which was explicitly requested by users as well.

Not sure I agree with the argumentation of it being a 'submit' button, but ok.

**Comment by droidmonkey** [comment]
This is only a bug with the auto submit option because there are multiple submit buttons. An edge case we were not expecting.

**Comment by varjolintu** [comment]
Even if it's said that `formaction` overrides the form's `action` value, it actually looks like the default `formaction` value for the button is `document.location.href` if it's not set at all.

**Comment by keunes** [comment]
Thanks both! 🙏
