### ISSUE TITLE
Documentation: How to setup browser extension to work with sandboxie

### ISSUE THREAD

**Issue by RedTailBullet** [keepassxreboot/keepassxc-browser#1194]
KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Win10
Browser: Firefox

Sandbox setting -> Resource Access -> Add File/Folder -> Set the path to `\Device\NamedPipe\org.keepassxc.KeePassXC.BrowserServer_*`

Then your KeePass Browser extension should work as normal.

Hope this helps.

**Comment by varjolintu** [comment]
Please write any information to this issue: https://github.com/keepassxreboot/keepassxc-browser/issues/267
