### ISSUE TITLE
travelesolutions.com: custom login fields not working

### ISSUE THREAD

**Issue by mekaneck** [keepassxreboot/keepassxc-browser#1195]
The page `https://travelesolutions.com/app/login` has 3 fields: username, password, and company short name. Username and password can be filled successfully with no custom settings. However, once the 3rd field is set up as a string field using the custom login fields, then none of the fields work.

## Expected Behavior

KeepassXC logo shows on the username field, and clicking it results in all 3 fields (Username, password, and company short name) filled

## Current Behavior

KeepassXC logo does not show next to any fields

## Steps to Reproduce (for bugs)

1. Set up an entry in KeepassXC for the page `https://travelesolutions.com/app/login` and provide some text for username and password
2. Visit the site in a browser. Observe that the browser extension recognizes the username and password fields correctly and fills in the information
3. Set up custom login fields so that the "company short name" field is selected for string field #1
4. Edit KeepassXC entry to add attribute "KPH: Company Short Name" and put data in such as "abcd"
5. Visit `https://travelesolutions.com/app/login` again and note that no fields are recognized
6. Right-clicking on any of the 3 fields to select filling in username & pw, or pw only, results in nothing happening. 
7. Right-clicking on any of the 3 fields to select filling in an attribute "company short name" works correctly.

## Debug info

KeePassXC - 2.6.3
KeePassXC-Browser - 1.7.4
Operating system: Win32
Browser: Chrome/Chromium 87.0.4280.141

**Comment by varjolintu** [comment]
Sadly there's no easy fix for this. But as a workaround you can change the attribute name to `KPH: {TOTP}` and then use the context menu with Fill TOTP to enter that extra string. That `KPH` attribute will override it.
