### ISSUE TITLE
Zendesk detection problems

### ISSUE THREAD

**Issue by tobiasKaminsky** [keepassxreboot/keepassxc-browser#1196]
## Expected Behavior
- Keepass should auto fill in username / password

## Current Behavior
- no fill in, even not when manually choosing the correct entry

## Possible Solution
/

## Steps to Reproduce (for bugs)

1. I have trouble with https://helpdesk.onlyoffice.com (which requires a login, unfortunately even official ZenDesk needs some data for having a trial version
2. tried to manually detect username/password field

## Debug info
<!--- Please copy/paste the browser's Java
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 84.0

**Comment by varjolintu** [comment]
The login window is inside an iframe. Modify your entry URL to `﻿﻿https://onlyofficesupport.zendesk.com` and everything should work.

**Comment by tobiasKaminsky** [comment]
You are my hero!
I "suffered" from this months, but did not dared to ask over here.
And you solved it within hours 💙
