### ISSUE TITLE
LibreWolf based on Firefox can't connect to the keepass database

### ISSUE THREAD

**Issue by TheMMcOfficial** [keepassxreboot/keepassxc-browser#1197]
## Expected Behavior
That the extension will connect to the database.

## Current Behavior
Like Firefox I had installed the extension but I click to connect the database nothing happen.

## Steps to Reproduce (for bugs)

1. Download LibreWolf on gitlab
2. Install the KeepassXC extension
3. Try to connect to the database

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Linux
Browser: LibreWolf (based on Firefox)

**Comment by droidmonkey** [comment]
Use the custom browser feature

**Comment by DJCrashdummy** [comment]
FWIW: at https://github.com/keepassxreboot/keepassxc-browser/issues/2064#issuecomment-1874331946 is a little bit more extensive answer.
