### ISSUE TITLE
Existing Issue w/ Username Only Login - Including Predefined Sites

### ISSUE THREAD

**Issue by Saj5h7** [keepassxreboot/keepassxc-browser#1198]
Hello,

I have read through a number of issues that are apparently resolved, however I am having the issue with current/new versions with existing predefined sites enabled, etc.

I have had this issue with both Brave and Firefox. KeePassXC-Browser Version: 1.7.4, KeePassXC Version: 2.6.3

## Expected Behavior
Identifies split/username only login and the corresponding/following password only login.

## Current Behavior
It either identifies both as a username or does not identify the password field. I have attempted to set custom logins with no change either. This includes popular split logins like Gmail, Amazon, eBay, Paypal, etc.

Additionally it noes not offer to save, etc. because it is not recognizing the fields.

This occurs in both Brave and Firefox.

## Possible Solution
Not sure, I can't find any settings which would cause this and the bug/issue I believe has been considered resolved in new versions?

## Steps to Reproduce (for bugs)
Visit Gmail, Amazon, Paypal, eBay, etc. split login pages in Firefox or Brave running KeePassXC-Browser Version: 1.7.4, KeePassXC Version: 2.6.3

Thanks in advance for any help.
![Screen Shot 2021-01-26 at 1 05 07 PM](https://user-images.githubusercontent.com/77465386/105899174-8e017680-5fd7-11eb-8624-cbe9bed4ef47.png)
![Screen Shot 2021-01-26 at 1 05 13 PM](https://user-images.githubusercontent.com/77465386/105899176-8e9a0d00-5fd7-11eb-9788-98d21e89ee3e.png)
![Screen Shot 2021-01-26 at 1 08 31 PM](https://user-images.githubusercontent.com/77465386/105899211-9bb6fc00-5fd7-11eb-80fa-950e93ad566a.png)

**Comment by varjolintu** [comment]
Sounds a bit strange. I'm sure you've disabled all the Custom Login Fields for those sites? Also, any Site Preferences should not be needed for any of those sites.

**Comment by Saj5h7** [comment]
Update, if I manually input the entries into KeePassXC it will recognize them on predefined sites and allow me to effectively update them through the toolbar. The issue seems to be with it giving the option to add to your DB after logging in the first time. Afterwards updating, etc. is fine.

**Comment by varjolintu** [comment]
If might be that the newly saved credentials are not yet received by the browser extension. Still, a simple reload should do the trick.

**Comment by varjolintu** [comment]
If you still have problems with the latest version, let's reopen this.
