### ISSUE TITLE
Feature request : using KeepassXC-browser without the need of KeepassXC to be installed.

### ISSUE THREAD

**Issue by ericxuo** [keepassxreboot/keepassxc-browser#1199]
Hi,

Currently, it is mandatory to have KeepassXC to be installed and running on the PC running the Web browser (firefox in my case) on which KeepassXC-browser is installed.
Then it means it is difficult to use KeepassXC-browser when not on my personal PC (friend's one, work PC, ...).
At the same time, it is possible to access the KeepassXC database from (let's say) the Cloud (through NextCloud for example => this is what I do using the KeeWeb extension).
Then it could be useful to use KeepassXC-browser to fill the Internet page fields if KeepassXC-browser was able to read the database without the need of the KeepassXC executable.

Is it possible to add this feature ?

Regards.

Xuo.

**Comment by varjolintu** [comment]
KeePassXC-Browser is meant to transfer data from KeePassXC, not from any KeePass database directly. So this is not going to happen in the near future.

If we ever have a KeePassXC-Server or something similar, it can be possible.
