### ISSUE TITLE
MAC OSX - BRAVE don't connect to KeePass-XC database

### ISSUE THREAD

**Issue by trougeron** [keepassxreboot/keepassxc-browser#1204]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Hello, the connection between brave by the KeePass-XC Browser plugin does not work. There is no link between the two.
Thanks for your help and feedback,
Machine used: mac Mini - OSX Mojave
Browser: Brave 1.19.88
KeePass XC v. 2.6.4

**Comment by varjolintu** [comment]
Try enabling support for Chrome and Chromium also. Brave has a weird thing going on that they use other browser's settings path as their own.

**Comment by trougeron** [comment]
Hello,

Thanks.
It’s ok now !
👍

De : Sami Vänttinen <notifications@github.com>
Répondre à : keepassxreboot/keepassxc-browser <reply@reply.github.com>
Date : lundi 1 février 2021 à 14:53
À : keepassxreboot/keepassxc-browser <keepassxc-browser@noreply.github.com>
Cc : Thierry Rougeron <trougeron@paruvendu.com>, Author <author@noreply.github.com>
Objet : Re: [keepassxreboot/keepassxc-browser] MAC OSX - BRAVE don't connect to KeePass-XC database (#1204)


Try enabling support for Chrome and Chromium also. Brave has a weird thing going on that they use other browser's settings path as their own.
