### ISSUE TITLE
FireFox 85 can't use arrow-keys to select login

### ISSUE THREAD

**Issue by FlyveHest** [keepassxreboot/keepassxc-browser#1207]
## Expected Behavior
When cursor is in a username field, that is marked with the Keepass icon, pressing down arrow normally shows a dropdown containing usernames for the given site.

## Current Behavior
Nothing happens, no drop-down is presented.

Clicking on the Keepass icon correctly fills the username / password box.

## Steps to Reproduce (for bugs)

1. Go to site with a username/password box
2. Activate username entry field
3. Press down arrow

## Debug info
KeePassXC-Browser - 1.7.5
Operating system: Win
Browser: Firefox 85.0

This seems to have been introduced with Firefox 85, or maybe it was the addons v1.75 which I just saw was updated on the 31st of january.

Might be related to #1205

**Comment by varjolintu** [comment]
I cannot reproduce this. Can you copy/paste the JavaScript console output?

**Comment by FlyveHest** [comment]
There are no output in the console.

But, I just noticed, the keepass icon in the browser has a red ? on it, clicking on it lets me select login, which is pasted to the box just fine.

Page in question is webmail (dot) reinhold (dot) dk if you want to take a look yourself, if I can enable debugging in the extension in some way, let me know.

**Comment by varjolintu** [comment]
Fixed it. Seems when you re-opened your database using the icon, events related to the input field to initialized more than once, causing these kind of issues. Good find!
