### ISSUE TITLE
How to Verify Packet Integrity?

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc-browser#1211]
I checked the FAQ on how to verify packet integrity with gpg, such as using the following command:
```
gpg --verify KeePassXC-2.6.4-x86_64.dmg.asc
```
Unfortunately, I could not find any help. I guess that not offering a clear support on how to verify packet integrity will lead most people not to verify the packet integrity. Not everyone is a GPG specialist, and I'm not one of those.

However, you do offer a “PGP signature” and “SHA-256 digest”.

First of all, what is “digest”? Shall I just open this file in an editor and simply compare the hash with the one provided by the command `shasum -a 256`?

Now, the real stuff. How do I deal with `KeePassXC-2.6.4-x86_64.dmg.sig` file? As I usually deal with `.asc` file.

---
Operating system: MacOS Mojave
Browser: Firefox 85

**Comment by droidmonkey** [comment]
https://keepassxc.org/verifying-signatures/

**Comment by faxotherapy** [comment]
Thanks for the prompt answer. Too bad! I have not scrolled down far enough to grab the info. From the top, I clicked the link to download the package for my OS. So, why the need to scroll even further down the page then? It was then logical for me to go to the FAQ page, from which could not find anyting.

If you allow me to give you a friendly feedback. Why not moving the verifying signature info to the top of the download page?

**Comment by droidmonkey** [comment]
It's not the preferred method, its not our fault you stopped reading.

**Comment by droidmonkey** [comment]
Its an advanced operation, you really shouldn't be doing it unless you know what you are doing. Our getting started guide does have this detailed right at the beginning as well. https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_downloading_keepassxc
