### ISSUE TITLE
Microsoft Edge und Chrome Erweiterung / KeepassXC 2.6.4 Fehler: Schlüsselaustausch war nicht erfolgreich

### ISSUE THREAD

**Issue by xdukemasterx** [keepassxreboot/keepassxc-browser#1214]
Guten Tag und ich bitte um Entschuldigung das ich hier in deutscher Sprache poste, jedoch ist mein englisch zu schlecht.

Mein Betriebssystem: Windows 10 Professional x64 Version 20H2 und KeepassXC 2.6.4

Folgendes Problem:
Im Microsoft Edge und Chrome kann ich die Browser-Erweiterung nicht mit KeePassXC verbinden. Es erscheint als Fehlermeldung immer:  Schlüsselaustausch war nicht erfolgreich. Im Firefox funktioniert es ohne Probleme.

Kann mir bitte jemand helfen?

Danke und Gruß Mathias

KeePassXC - unknown
KeePassXC-Browser - 1.7.6
Operating system: Win64
Browser: Microsoft Edge 88.0.705.63

**Comment by varjolintu** [comment]
Haben Sie die Erweiterung aus dem Edge Store installiert? Versuchen Sie stattdessen, sie aus dem Chrome Web Store zu installieren.

**Comment by xdukemasterx** [comment]
Hallo varjolintu,
ja habe beide Erweiterungen versucht, leider ohne Erfolg.

Viele Grüße
Mathias

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by xdukemasterx** [comment]
Hallo varjolintu und danke für deine schnelle Antwort,

den Troubleshooting-Guide bin ich auch schon durchgegangen. Auch hier, leider ohne Erfolg.

Viele Grüße, Mathias

**Comment by phoerious** [comment]
Chrome ist in den Einstellungen zur Browserintegration aktiviert? Siehst du im Task-Manager im Tab "Details" einen Prozess, der keepassxc_proxy.exe heißt?

**Comment by xdukemasterx** [comment]
Guten Abend phoerious,

ich gehe davon aus, dass Du den Windows Task Manager meinst. Und nein, in Details ist kein Prozess keepassxc_proxy.exe vorhanden. Was von Keepass dort zu finden ist, ist der Prozess KeepassXC.exe

Viele Grüße und danke für Deine Hilfe, Mathias

**Comment by xdukemasterx** [comment]
Ich habe jetzt erst die keepassxc_proxy.exe manuell gestartet und anschließend die keepassxc.exe und die Datenbank freigeschaltet. Nun den Edge und Chrome gestartet. Bei beiden Browsern immer noch die selbe Fehlermeldung "Schlüsselaustausch war nicht erfolgreich."

Viele Grüße, Mathias

**Comment by phoerious** [comment]
Hast du in den KeePassXC-Settings alles aktiviert? So geht's:

![enable-browser-extension](https://user-images.githubusercontent.com/911270/108403370-e9add100-721e-11eb-9d41-abc10d60f3be.png)

Im Advanced-Tab noch sicherstellen, dass diese Option an ist (sollte standardmäßig an sein):
![enable-browser-extension-2](https://user-images.githubusercontent.com/911270/108403374-eb779480-721e-11eb-8271-e2cacaf5d008.png)

Dann im Browser auf Reload drücken. Dann sollte das zu einem Connect-Button werden, mit dem du den Browser mit KeePassXC verbinden kannst.
![enable-browser-extension-3](https://user-images.githubusercontent.com/911270/108403381-ed415800-721e-11eb-8074-7eabc2afa1a9.png)

**Comment by IDevTrooper** [comment]
Ich hatte gerade das gleiche Problem und bin zu folgendem Ergebnis gekommen: Es lag an der (Gruppen-)Richtlinie `NativeMessagingUserLevelHosts` für MS Edge.
Ggf. wäre hierfür ein entsprechender Hinweis ganz nett.

Die Debugausgabe sah folgendermaßen aus:
![image](https://user-images.githubusercontent.com/32335796/154309501-77998925-63c8-4154-93e8-845982ca711a.png)
Die erste Zeile kam direkt bei Klick auf die Erweiterung.
Die anderen Zeilen kamen beim Klick auf "Reload".

Daraufhin habe ich mich gefragt, ob MS Edge vielleicht Sicherheitseinstellungen bzgl. "native messaging" hat und tatsächlich:
![image](https://user-images.githubusercontent.com/32335796/154309954-443c862a-3a6f-4b8d-b4e0-11dbdea92724.png)
Quelle: https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#native-messaging

Also habe ich unter edge://policy mal gesucht: (bei der ersten Suche stand das noch auf "false")
![image](https://user-images.githubusercontent.com/32335796/154310231-eca418b0-0e48-495c-80ec-b470c55d5fdc.png)

Dann habe ich die entsprechende Gruppenrichtlinie in der Registry angepasst, der Pfad dafür steht [hier](https://docs.microsoft.com/en-us/deployedge/microsoft-edge-policies#nativemessaginguserlevelhosts)

Dann nochmal auf edge://policy auf "Richtlinien neu laden" und tada, der Schlüsselaustausch ist erfolgreich und ich kann wie gewohnt KeepassXC verwenden.

**Comment by dhalmsimuth** [comment]
Und wie sollte es auf Google Chrome funktionieren?
