### ISSUE TITLE
Autocomplete sort order should take group into account

### ISSUE THREAD

**Issue by kosli** [keepassxreboot/keepassxc-browser#1217]
Currently there are two options for the sorting of the returned credentials:
- Sort matching credentials by title
- Sort matching credentials by username

Neither of these takes into account the group where the entry is stored. Whereas in the list of returned credentials, the entries are displayed as: [group] title (username) 
As I have multiple entries with the same title and similar usernames (e.g. when managing for multiple companies the same service, and having a normal and an admin user) I get now a list shown in quite a "random" order, because the entries listed start with the group name, so it is quite difficult to find the right entry. 

It would be great if there would be an option to take the group into account when sorting.
Current:
[groupC] theWebService (user1)
[groupA] theWebService ADMIN (user2)
[groupB] theWebService (user3)

WIth sort by group:
[groupA] theWebService ADMIN (user2)
[groupB] theWebService (user3)
[groupC] theWebService (user1)

e.g. have the two additional options:
- Sort matching credentials by title
- Sort matching credentials by username
- **Sort matching credentials by group & title**
- **Sort matching credentials by group & username**

**Comment by varjolintu** [comment]
Hmm. This feature is now made to the KeePassXC side. I wonder if it could be smarter to do this only in the extension side.
