### ISSUE TITLE
Matching credentials as table instead of simple text list

### ISSUE THREAD

**Issue by kosli** [keepassxreboot/keepassxc-browser#1218]
The list of matching credentials that is currently displayed is just a simple list of text entries. If there are many matching entries, like I have in #1217, the list gets quite difficult to read. 
As the list includes for each entry the 3 parts:
 [group] title (username)
It would be great if the entries could be displayed as a table = have the group, title and username aligned on the same horizontal position for all entries.

Exmple:
![image](https://user-images.githubusercontent.com/203928/107784013-3e4adb00-6d4b-11eb-8af5-2b8fffcb2393.png)

**Comment by droidmonkey** [comment]
I like this idea
