### ISSUE TITLE
No documentation about the personalized "String fields #" can be set

### ISSUE THREAD

**Issue by emilio-aburto** [keepassxreboot/keepassxc-browser#122]
Hello, please could somebody help me to get this sorted out?

## Expected Behavior
- Click the plugin icon in the browser bar to display config menu.
- Click "Choose own credencial fields for this page"
- Choose or dismiss User and Password fields
- Choose to add other "String field"
- Display list of atributes starting with "KPH:"
- Select the chosen option and confirm.
- Next time in this page autocomplete the field or display a list of options if more than one account exists

## Current Behavior
- Click the plugin icon in the browser bar to display config menu.
- Click "Choose own credencial fields for this page"
- Choose or dismiss User and Password fields
- Choose to add other "String field"
- Select the field and it's automatically named `String field #1`
- Confirm the selection
- Next time in the page there is nothing to try to complete the field

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Firefox 60.0b12
Proxy used: YES

**Comment by varjolintu** [comment]
The same explanation can be found from the official manual PR:
https://github.com/keepassxreboot/keepassxreboot.github.io/blob/564120a8619b70f73f720fffd293f45282f06f5d/docs/keepassxc-browser-manual.md#17-fill-additional-values-using-string-fields

@hpg-mheck Are you having trouble using the String Fields, because you said it was a bug?

**Comment by dieterlohrstraeter** [comment]
> 
> 
> The same explanation can be found from the official manual PR:
> https://github.com/keepassxreboot/keepassxreboot.github.io/blob/564120a8619b70f73f720fffd293f45282f06f5d/docs/keepassxc-browser-manual.md#17-fill-additional-values-using-string-fields
> 
> @hpg-mheck Are you having trouble using the String Fields, because you said it was a bug?

I'm using version 2.5.4 and it doesn't take over the attributes.
I'm using exact this example URL from deutsche-bank as described in doc.
I can choose the custom fields as explained and save, but when reloading the page, only username and password/pin is filled. None of the custom string fields are considered. Fields keep empty.

BTW: The doc is not 100% clear described. On github link above, there is a blank between "KPH:" and the attributes, but on KeepassXC FAQ, there is none and I don't know if this is relevant.
And, the example might be misleading. Is "Account" to be replaced by the bank-account number or is it a mandatory key-field?
A simple example with dummy-values would be very helpful, e.g. one of these variants are in the range of description, but I don't know, which is really correct:
KPH:Account:1234567
KPH: Account:1234567
KPH:123456

**Comment by varjolintu** [comment]
@dieterlohrstraeter You need to use space after `KPH:`.

**Comment by dieterlohrstraeter** [comment]
> 
> 
> @dieterlohrstraeter You need to use space after `KPH:`.

Thanks, that was very helpful and now, after several different trials, I got it working.
Nevertheless, the problem is still the unclear description.

1. The korrect order seems not to be a problem, although this is suggested even by you "(in this order)". I cannot keep the order, even not with space after the colon.
2. It seems that strings after "KPH: " are the names of the input-fields from Web-page, because I cannot save them in the order as described but it still works. I have saved in following order (account,branch,subAccount).
3. The description should give a better explanation, that the value should be written into the right field. I haven't recognized it and assumed to be a comment field first.

**Comment by iamjibesh** [comment]
I was having a similar problem. I had three fields to fill. But I was not able to fill the string field. I tried all methods explained above. All in vain.

Then I inspected the field in the browser and got the field id from the page source. Then I put that id after KPH and it worked. 

(The field name was Digispace, But the field id inside the source was Workspace, so I had to put KPH: Workspace for it to work)

So the conclusion is the plugin detects the source id to fill in the details.

**Comment by s-KaiNet** [comment]
> I was having a similar problem. I had three fields to fill. But I was not able to fill the string field. I tried all methods explained above. All in vain.
> 
> Then I inspected the field in the browser and got the field id from the page source. Then I put that id after KPH and it worked.
> 
> (The field name was Digispace, But the field id inside the source was Workspace, so I had to put KPH: Workspace for it to work)
> 
> So the conclusion is the plugin detects the source id to fill in the details.

I used the same procedure, but cannot make it work. Could you tell if this approach works for the latest versions?

**Comment by varjolintu** [comment]
@s-KaiNet This still applies:
https://github.com/keepassxreboot/keepassxc-browser/issues/122#issuecomment-458010611

**Comment by s-KaiNet** [comment]
> @s-KaiNet This still applies: [#122 (comment)](https://github.com/keepassxreboot/keepassxc-browser/issues/122#issuecomment-458010611)

Yeah, I followed exact same steps for the mentioned site, but custom fields are not populated.
![image](https://user-images.githubusercontent.com/10658276/147248007-ca494d69-8525-44b6-a55e-7003a1caf3e3.png)

**Comment by varjolintu** [comment]
@s-KaiNet And you have selected three fields as String Fields from the extension side using Custom Login Fields?

**Comment by s-KaiNet** [comment]
> @s-KaiNet And you have selected three fields as String Fields from the extension side using Custom Login Fields?

Correct. I also checked that I have a new entry under "Custom login fields" in the extension settings for this URL.

**Comment by varjolintu** [comment]
@s-KaiNet And you are able to fill username and password normally for that page, but not the String Fields?

**Comment by s-KaiNet** [comment]
Yes, this is what I tried:

https://user-images.githubusercontent.com/10658276/147258562-e4174840-bebd-42cf-9c27-89fb1a6067f3.mp4

**Comment by varjolintu** [comment]
Let me check if something's broken with the current release. Just tested the feature recently.

**Comment by varjolintu** [comment]
Have you enabled this option:
![Screenshot 2021-12-23 at 17 12 45](https://user-images.githubusercontent.com/24570482/147259225-b04a1dc4-b192-4e14-8ae4-b28449d558f9.png)

In your video you skipped settings the username and/or password. Set (for example) branch as username, account and password and then the rest as String Fields.

**Comment by s-KaiNet** [comment]
Yes, I have "Return advanced .... with KPH" enabled. 
I followed your advice and selected username and password fields, skipped TOTP, then selected the rest as custom string fields. In this case it worked for me.

**Comment by varjolintu** [comment]
@s-KaiNet String Fields are supposed to be used as an addition to username and/or password field. Currently they cannot work alone with just them selected.

**Comment by s-KaiNet** [comment]
@varjolintu Is it difficult to add such support? I see cases when it might be useful, like filling in credit cards information, when there are no user/pass fields or providing additional info on form submission. 
Also, it seems that documentation needs to be updated, since it clearly says that "You can skip the Username, Password, and TOTP fields if not needed"

**Comment by varjolintu** [comment]
@s-KaiNet Then it might be a bug that those cannot be filled without username/password, if it has been working before. Support for credit card information is coming later, and it will be a separate feature not directly related how String Fields are selected.

**Comment by s-KaiNet** [comment]
@varjolintu Sorry I didn't catch the idea. What I'm suggesting is to have an additional feature to fill String Fields without username and password specified. It shouldn't break anybody since currently, you cannot use String Fields without username/password. But maybe I don't know all the internals and the extension history, so please correct me if I'm wrong.

**Comment by smil2k** [comment]
> > I was having a similar problem. I had three fields to fill. But I was not able to fill the string field. I tried all methods explained above. All in vain.
> > Then I inspected the field in the browser and got the field id from the page source. Then I put that id after KPH and it worked.
> > (The field name was Digispace, But the field id inside the source was Workspace, so I had to put KPH: Workspace for it to work)
> > So the conclusion is the plugin detects the source id to fill in the details.
> 
> I used the same procedure, but cannot make it work. Could you tell if this approach works for the latest versions?

For me the key was the extra space! (Additionally I marked the string fields as such.)

**Comment by krodelabestiole** [comment]
I wonder if I miss something...

Relying on custom fields starting with _KPH:_ **order** and having to tweak custom login fields via the plugin doesn't look much clean or reliable...

Is there any way to simply autofill a form depending on input fields names ?
Depending on keepass custom fields corresponding to these form field names i.e.


I've tried to weak things using keepassXC autofill functionnality but I'm not sure keepass-browser relies on this...


And what does KPH stand for ? Sorry I can't find any doc on the matter.

**Comment by varjolintu** [comment]
> I wonder if I miss something...
> 
> Relying on custom fields starting with _KPH:_ **order** and having to tweak custom login fields via the plugin doesn't look much clean or reliable...
> 
> Is there any way to simply autofill a form depending on input fields names ? Depending on keepass custom fields corresponding to these form field names i.e.
> 
> I've tried to weak things using keepassXC autofill functionnality but I'm not sure keepass-browser relies on this...
> 
> And what does KPH stand for ? Sorry I can't find any doc on the matter.

The reason it's done in order is that there's no guarantee the element even has a static id or name. Many web pages generate id's and other parameters dynamically, so KeePassXC uses them in the order those are saved to the extension side (using element paths).

**Comment by krodelabestiole** [comment]
I might be wrong but from my understanding `KPH:` order we speak about (`field #1`, etc.) refers to the order additional attributes are stored in the keepass database.
These attribute names are chosen by us - keepass users - and the plugin could display what comes after `KPH:` instead (that would be one step clearer and more reliable)

On the form side, I get field names might be dynamic (though it is mostly not the case), and in that case keepassxc-browser could provide with a way to use keepass autotype sequence e.g. ?

**Comment by varjolintu** [comment]
> I might be wrong but from my understanding `KPH:` order we speak about (`field #1`, etc.) refers to the order additional attributes are stored in the keepass database. These attribute names are chosen by us - keepass users - and the plugin could display what comes after `KPH:` instead (that would be one step clearer and more reliable)
> 
> On the form side, I get field names might be dynamic (though it is mostly not the case), and in that case keepassxc-browser could provide with a way to use keepass autotype sequence e.g. ?

Yes. The order is the same. So String Field number 2's corresponding attribute is the second attribute in the list starting `KPH: `. Plugin could display the values, sure, but then the user must fist set the attributes and only after that setting the Custom Login Fields could be possible. Also, if the names would be used for the fields instead of order, what happens if used changes the names in the attributes? Currently the order based system is a bit more reliable in my opinion.

The extension context menu already has a menu item for triggering a Global Auto-Type request. It handles the URL automatically, so no window title matchinge etc. are needed.

**Comment by github-throwaway** [comment]
@varjolintu Terve, according to the docs "_Dropdown elements can be choosed also._" However I fail to make that work in my case. Any guidance on how to pick a entry form a dropdown? I tried to mark the dropdown as a String field and put the matching value in the database, but it does not work. Is it even possible add all to mix String fields, usernames and password? Any help would be much appreciated :)

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/25488086/f3d52f3b-1834-4b9e-9322-b2849fdea97f)

**Comment by varjolintu** [comment]
@Rubber-Duckie Custom Login Fields are what they're named after: manually selectable custom fields. Automatically detecting all possible fields and saving the data to an entry automatically is not a feature that would have any use.

What are these production quality standards concerning custom input fields you speak of? How this could be more intuitive and simpler to use?

**Comment by varjolintu** [comment]
> Instead of addressing usability concerns or comparisons to LastPass, it does seem your response deflects by questioning "production quality standards" rather than acknowledging frustration with manual field designation. The issue isn’t the ability to select custom login fields, an important feature of course, but the rigid syntax and cumbersome configuration, especially compared to other password managers that automate detection more effectively.
> 
> If usability and accessibility are key goals, a more constructive approach would be to recognise these limitations and explore improvements, such as better adaptive field detection with manual overrides. Power users should still be able to customise fields, but without the unnecessary prefix syntax. Instead, users could hover over an input field, select from their predefined custom fields in KeePass if already created, or indeed create them if not through the users selection in the browser extension, and have the mapping upserted to their KeePass database via the KeePass browser integration API, ensuring a more seamless and intuitive experience.

I only asked about the standards because I'm not aware such things exist. There are multiple different ways to do the same.

The only thing that could actually improve this is to provide a method to select or create the KPH attribute immediately after selecting a String Field from the extension side. You are free to make a feature request for that if that is something you'd wish to see.
