### ISSUE TITLE
GUI - Search box

### ISSUE THREAD

**Issue by pipiscrew** [keepassxreboot/keepassxc-browser#1221]
The identity entries, can be used also as bookmarks. Meaning, for example when I carry the kdbx file to work, I dont have the bookmarks and will be very easy way through the browser, addon pop, to make a search. A mockup, displaying multiple results.

<kbd>![s2](https://user-images.githubusercontent.com/3852762/107861038-cadcc280-6e4b-11eb-95d8-b009da21f396.png)</kbd>

when the **identity name** entry clicked, a **new tab** will open with the identity URL.

## Expected Behavior
hi

## Current Behavior
hi

## Possible Solution
hi

## Steps to Reproduce (for bugs)
hi

## Debug info
hi

**Comment by droidmonkey** [comment]
We are not going to allow arbitrary searching of the database from the browser extension. This is a security feature.
