### ISSUE TITLE
Keepass Browser Extension Preventing Input, - Normal Behaviour or a Bug?

### ISSUE THREAD

**Issue by XyjpcpXNF6UGaQ** [keepassxreboot/keepassxc-browser#1224]
I have been having an issue with the latest KeePassXC-2.6.4-Win64 and I am wondering whether or not the behaviour is intended or a bug.

The problem usually occurs where I need to input fields that are outside of those stored in the Keepass database (for example, adding additional verification details - Keepass only seems to support username and password, never additional field values), or when I am trying to update details or change passwords (all using Firefox 85.0.2 (x64)) and what usually happens is that the browser extension actively prevents me from inputting field values or tries to overwrite values I have entered, even when avoiding clicking on the usual drop-down box.

This is highly frustrating and annoying, has never happened previously, and usually results in having to remove the addon only to have to re-install it again once I have finished whatever it is that I was trying to do.

**Comment by varjolintu** [comment]
@XyjpcpXNF6UGaQ Can you give an example of a site where this happens?

**Comment by XyjpcpXNF6UGaQ** [comment]
My apologies for the late reply. The last time I encountered this issue was on the IG Markets website, - a date of birth field on the password reset form, where I was able to enter the two dates but not the year (for some reason I could enter two digits, not four, and the value was being automatically submitted, - or validated, - immediately on entering the first two digits).

**Comment by varjolintu** [comment]
Are you using the Auto-Submit option? Does it matter if you disable the _Use dynamic input field detection_ ffrom the options?

**Comment by XyjpcpXNF6UGaQ** [comment]
Thanks. - I will try your suggestions and see if they work, but it may take several days before I encounter this issue again, as it depends on which websites I am visiting and, in the case of IG Markets, whether I am needing to reset my password or not.

**Comment by XyjpcpXNF6UGaQ** [comment]
I have found another problem website: HSBC online banking: two fields, - Memorable Question and Security Code.

I do not use KeepassXC for either of these: I remember the answer to the Memorable Question, and the Security Code is generated using a hardware widget; so KeepassXC should not interfering on this page at all, never mind actively forcing focus from the Memorable Question to the Security Code input field.

I tried unticking Use dynamic input field detection, but it has not fixed the problem.

**Comment by varjolintu** [comment]
Testing and identifying this bug I would need an access to a site where I don't need any credentials. Obviously online banking sites are totally out of the question.

**Comment by XyjpcpXNF6UGaQ** [comment]
I realize that, and will provide you with details of any sites I find where I encounter this problem; but, in the meantime, there are two known sites where other KeepassXC users will potentially have the same issue as myself, even if not yourself; so that should give you some corroboration of the problem even if nothing else.

I will continue to try and debug this problem and will update you should I find anything that works (or a website where you can test without credentials).

**Comment by varjolintu** [comment]
One thing you could try is to add the page URL to Site Preferences tab in the extension settings and select _Disable all features_ from the combobox. It's best to use `https://example.com/*` as the URL, so the wildcard is recommended. This disables the extension totally for a certain pages.

**Comment by XyjpcpXNF6UGaQ** [comment]
That solution looks promising, - thanks, - I have already added one website and will be adding more as I encounter them. I have fully tested disabling the automatic features of the browser addon and can confirm that (in my setup, at least) doing so has not the slightest effect on the problems I have been experiencing with the addon; so if excluding web sites works then that is what I will use.
