### ISSUE TITLE
make it possible to autoprovision settings for KeePassXC-Browser add-on

### ISSUE THREAD

**Issue by tuxcrafter** [keepassxreboot/keepassxc-browser#1226]
KeePassXC-Browser 1.7.6
KeePassXC 2.6.4

1. Please make it possible to fully auto provision the settings for the KeePassXC-Browser add-on from a system-wide json/ini file.

Example let the plugin do a lookup at: /usr/lib/firefox/native-messaging-hosts/org.keepassxc.keepassxc_browser_settings.json? and import any changed settings from this file. This way I can mange organization wide settings

2. Please make it possible to also import a JSON file to automate the creation of the database connection from Firefox (with for example firefox01) and Chrome (connection name: chrome01) with maybe predefined keys when needed.

I will donate an other 150 euro if the above features get implemented in the next KeePassXC-Browser Chrome and Firefox release.

Jelle de Jong

**Comment by varjolintu** [comment]
For this we should use https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage (requires a new permission).

The biggest problem implementing this one would be what default path should the plugin read as default on each OS? This should be configurable which already makes the feature a bit complicated if anyone wants this to be fully automatic. Also, I can imagine a lot of users don't want the extension to access local disk at all, which already makes this kind of feature harder to do if the option is disabled by default. But, this is doable if the setting is totally disabled by default and the path has to be configured by the user(s).

Also, should the extension update the settings from that file with each browser restart if the content is changed?

**Comment by varjolintu** [comment]
Point 2: at this point there is no support for importing/exporting any of the database connection keys. Automating the connection would mean we'd have to implement a way to put connection key to KeePassXC database manually (yes, keys are stored in the encrypted database, not in the application itself), and adding support for importing encryption keys to the browser extension.

**Comment by tuxcrafter** [comment]
How is the process of the autoprovision options progressing?

**Comment by varjolintu** [comment]
Take a look at: https://github.com/keepassxreboot/keepassxc-browser/pull/2366. This includes the part 3 in your request.

Those first two steps are probably not gonna happen. You can always make a new connection with a unique name.

**Comment by varjolintu** [comment]
I would say this feature request is met with the #2366.
