### ISSUE TITLE
KeepassXC-browser is unable to detect and save creditionals

### ISSUE THREAD

**Issue by Sukhman723** [keepassxreboot/keepassxc-browser#1230]
I already have creditionals present in KeepassXC but KeepassXC-browser is unable to detect it. I've tried _choose custom field login_ so that it can detect my creditionals but with no success. Likewise, I'm not a technical person, so I don't know what is going on with it.

Errors: When I fill username/password fields or create a new "_sign in_" KeepassXC-browser pops out a message to save my creditionals but when I click on "_yes_" it says _Error occurred_.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
I need more details. What site are you having problems with? There's no "Yes" button when saving new credentials. Can you take screenshots and give some more explanations about the issue? Thanks.

**Comment by Sukhman723** [comment]
not just one site its every site

**Comment by varjolintu** [comment]
Please check these:
https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_setup_browser_integration

**Comment by Sukhman723** [comment]
I followed all the steps as mentioned in documentation but i don't know why it is not working.

**Comment by varjolintu** [comment]
Make sure your entry URL is `https://mail.protonmail.com/login` or `https://mail.protonmail.com/`.

**Comment by Sukhman723** [comment]
You are saying that it can be the problem with URL. But let me inform you that I just made a new Google account only to test whether keepassxc-browser will pop out any message to store my creditionals, but it didn't. I mean this extension is literally doing nothing.

**Comment by varjolintu** [comment]
So you are having two different problems? Credentials are not filling & credential saving doesn't work?

**Comment by Sukhman723** [comment]
Yep! You got it.

**Comment by varjolintu** [comment]
I use Protonmail almost daily and I don't have any problems with the site. Could you share your entry URL just in case?

**Comment by Sukhman723** [comment]
here is it:
https://mail.protonmail.com/login

**Comment by varjolintu** [comment]
Can you confirm that you can fill credentials for other pages normally? Protonmail is totally working for me.

**Comment by ThisNekoGuy** [comment]
Personally, I'm having a similar issue with LibreWolf (FireFox fork) and I had imported my data from a plain CSV from LastPass and have seemingly identical behavior going on here is well.

Try to log into Google, doesn't make any database suggestions, even if I enter everything manually.
After doing it manually, it just act like I never entered anything and doesn't ask to save any data. It's weird

**Comment by almereyda** [comment]
This seems related to #1358.
