### ISSUE TITLE
keepassxc-browser does not fill the password in the password field

### ISSUE THREAD

**Issue by z-Wind** [keepassxreboot/keepassxc-browser#1233]
## Expected Behavior
Be able to fill the password to the password field

## Current Behavior
I try the function of Custom Login Fields, but it does not work.
![image](https://user-images.githubusercontent.com/16359142/108587224-6fe82580-738d-11eb-8ac0-138221c30c15.png)

## Steps to Reproduce (for bugs)
1. link: https://www.ctbcbank.com/twrbc/twrbc-general/ot001/010
2. click button and it failed

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win64
Browser: Chrome/Chromium 88.0.4324.182

**Comment by varjolintu** [comment]
This is probably due to a heavy scripting of the page. I suggest using Auto-Type instead for these kind of issues.

**Comment by z-Wind** [comment]
When I export the settings, I find that the the password & username have the same settings as below.
```
"https://www.ctbcbank.com": {
            "fields": [
                "INPUT text ng-untouched ng-pristine ng-valid  "
            ],
            "password": "INPUT password ng-untouched ng-pristine ng-valid ",
            "totp": null,
            "username": "INPUT password ng-untouched ng-pristine ng-valid  "
        }
```
Then I use violentmonkey to change the html class property of the password filed as below.
```
elem.classList.remove("ng-untouched");
elem.classList.add("appendExtra");
```
After doing custom login again, it works.

**Comment by varjolintu** [comment]
These kind of sites are problematic because the often add or remove classes from the input fields based on the focus, if it has text etc. This makes it hard to identify them properly next time after those have been saved once before.
