### ISSUE TITLE
Cannot autofill username and password in www.126.com.

### ISSUE THREAD

**Issue by bytedynamic** [keepassxreboot/keepassxc-browser#1235]
## Overview
Cannot autofill username and password in www.126.com.

## Actual Behavior
My database has password of www.126.com, but cannot autofill the username and password in this site.

[NOTE]: 
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

**Comment by varjolintu** [comment]
This is probably due to a heavy scripting of the page. I suggest using Auto-Type instead for these kind of issues.
