### ISSUE TITLE
Deactivate for this site used in browser promt. Cannot reactivate it for this site.

### ISSUE THREAD

**Issue by mintberrycrunch89** [keepassxreboot/keepassxc-browser#1237]
## Expected Behavior
I configured KeePassXC for a specific website in Mozilla and accidentally pressed "deactivate for this site" in the prompt. 
I want to activate the functionality for this website again. I would expect this website to be shown somewhere in the settings so I can remove it from the list of deactivates websites.

## Current Behavior
I configured KeePassXC for a specific website in Mozilla and accidentally pressed "deactivate for this site" in the prompt. 
I cannot find any setting to reactivate this site to make KeePassXC work again for this site. Hence, it is blocked without the user having the possibility to integrate the functionality for this website again.

## Possible Solution
Show the websites deactivated in the user prompt somewhere in the settings. 

## Steps to Reproduce (for bugs)
1. Open KeePassXC data and unlock your database
2. Enter a new entry in KeePassXC for a random site which should work well
3. Go to this site and go to the login
4. KeePassXC will ask you to check the login suggestion. Press 'deactivate for this site'

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win/
Browser: Firefox

**Comment by varjolintu** [comment]
You can edit the entry in KeePassXC and from its Properties page you can delete the saved KeePassXC-Browser Settings. In the future this accidental kind of thing can be reverted from the popup, but that fix hasn't been implemented yet.

**Comment by mintberrycrunch89** [comment]
Thank you varjolintu.
Didn't expect to find this setting in the main program, searched in the browser integration all the time.

**Comment by varjolintu** [comment]
This is why we want to improve this a little bit. Maybe the extension popup could show that "This site has credentials but access to those has been denied. Reset permissions?" or something similar.
