### ISSUE TITLE
AWS Login returns JSON with state FAIL

### ISSUE THREAD

**Issue by rvernica** [keepassxreboot/keepassxc-browser#1240]
## Current/Expected Behavior and Steps to Reproduce

On the AWS login page https://us-east-1.signin.aws.amazon.com/oauth I click on the KeePassXC logo in the `IAM user name` field. The username and password auto-complete and the page is submitted. The response is a JSON page: https://us-east-1.signin.aws.amazon.com/authenticate
```
{
  "state": "FAIL",
  "properties": {
    "Message": "Invalid request",
    "Title": "Bad Request",
    "header": "Bad Request",
    "text": "Invalid request"
  }
}
```

I was expecting the AWS console or a login failed AWS error. In any case, I was expecting a valid HTML page not a JSON response.

## Debug info

KeePassXC - `2.6.4`
KeePassXC-Browser - `1.7.6`
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
So this happens when Auto-Submit is enabled?

**Comment by rvernica** [comment]
_Auto-submit login forms_ is enabled
