### ISSUE TITLE
Clear text password shown in input dropdown selection

### ISSUE THREAD

**Issue by davidakerr** [keepassxreboot/keepassxc-browser#1241]
## Expected Behavior
The dropdown list of possible logins should not include the clear text password.

## Current Behavior
When clicking the keepassxc icon all logins are shown with passwords in clear text.

## Possible Solution
Please add an option to hide the password from this list. One screen share and all your passwords are comprised.

## Steps to Reproduce (for bugs)
1.  Go to a site with stored passwords
2. Click the login field
3. See all the passwords on screen in clear text

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment]
This is not possible unless you have password in your usename fields in your entries. Have you imported your credentials from a CSV file or from another password manager? Maybe the CSV export is not working properly.

**Comment by davidakerr** [comment]
Ahh don't set things up at 7am when you roll out of bed. Thanks for taking the time to point this out.
