### ISSUE TITLE
KeePassXC-browser failure to connect to databases on Firefox and Chrome/Brave

### ISSUE THREAD

**Issue by umaru-UMR** [keepassxreboot/keepassxc-browser#1242]
While using browser, it supposed to fill out saved login and passwords on desired website, but it doesn't.

_KeePassXC-Browser has encountered an error:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings._

After clicking Reload:
_Key exchange was not successful._

In KeePassXC itself I have enabled integration with browsers, installed both add-ons on respective browsers and the issue is same everywhere. I do not know if its Ubuntu issue, but Used it on 20.10 and 20.04 and all issues where the same...

In settings of add-ons there is _No connected databases found._ in connected database tab.

1.Run KeePassXC
2.Unlock database
3.Open browsers and pages to login
4.on add-on click reload
5. Click on KeePassXC Icon to fill login: fail to connect to KeePass

For Brave
KeePassXC - unknown (actually I have 2.6.4)
KeePassXC-Browser - 1.7.6
Operating system: Linux x86_64 Ubuntu 20.04 and 20.10
Browser: Chrome/Chromium 88.0.4324.152

For Firefox
KeePassXC - unknown (actually I have 2.6.4)
KeePassXC-Browser - 1.7.6
Operating system: Linux x86_64 Ubuntu 20.04 and 20.10
Browser: Mozilla Firefox 85.0:

**Comment by varjolintu** [comment]
Are you using your browser as a Snap? It won't work.

**Comment by umaru-UMR** [comment]
I have installed KPXC with discover... my big mistake, it was snap version...
reinstalled with normal version and Firefox add-on worked.
check all snapped softwre with
`snap list`
and uninstall snap KPXC and browsers
then install unsnapped KPXC:

```
sudo add-apt-repository ppa:phoerious/keepassxc
sudo apt-get update
sudo apt install keepassxc
```

install unsapped version of Browser:
```
sudo apt install apt-transport-https curl gnupg
curl -s https://brave-browser-apt-release.s3.brave.com/brave-core.asc | sudo apt-key --keyring /etc/apt/trusted.gpg.d/brave-browser-release.gpg add -
echo "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
sudo apt update
sudo apt install brave-browser
```
and that solved the issue. Why the hell discover inserts snap versions... snap is evil! inefficient and source code can be changed...
