### ISSUE TITLE
Focus Bug when having multiple forms on page

### ISSUE THREAD

**Issue by brainfoolong** [keepassxreboot/keepassxc-browser#1244]
As you can see in attached animated screenshot, when i am on a page with multiple forms, on focus one field with mouse it  immediately jumps to another input field which effectively makes the first form unusable.

There is a workaround of tabbing thorugh the fields until you get to the correct field, but it's awful.

I have the testfile attached.

![bug](https://user-images.githubusercontent.com/1684236/109019971-cf11a700-76b9-11eb-8afc-b05c1f637cd6.gif)

[test.html.txt](https://github.com/keepassxreboot/keepassxc-browser/files/6036874/test.html.txt)

Hope this help to find the bug.

## Debug info
KeePassXC-Browser-Version: 1.7.6
KeePassXC-Version: 2.6.4
Operating system: Win 10
Browser: Chrome

**Comment by Nothing4You** [comment]
I'm seeing the same on Firefox:

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: MacIntel
Browser: Mozilla Firefox 85.0
