### ISSUE TITLE
access.redhat.com/sso.redhat.com username-only login broken

### ISSUE THREAD

**Issue by z1atk0** [keepassxreboot/keepassxc-browser#1245]
On Chromium and Firefox, the username-only login on access.redhat.com (authentication actually happens on sso.redhat.com, the auto-generated "Site preferences" entry with the "Username-only Detection" box ticked is "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/*") is broken. The username detection/selection is actually fine (I have 3 different RedHat logins), ie. I get the dropdown to select the username. Only when I select the desired login and click "Continue", the password is not automatically filled in, as if the password field is not detected as such. There's also no other way to get it to enter the password automatically, other than switching to the running keepassxc instance, and do either use Autotype, or hit Ctrl+C on the proper login, switch back to Chromium, and Ctrl+V paste it into the password field manually.

## Expected Behavior
* go to a protected (subscriber-only) KB entry on access.redhat.com (eg. https://access.redhat.com/solutions/1232133)
* click the "LOG IN" button on the bottom
* select the desired username from the drop-down & hit "NEXT"
* have keepassxc-browser fill in the correct password automatically
* klick "LOG IN"

## Current Behavior
* go to a protected (subscriber-only) KB entry on access.redhat.com (eg. https://access.redhat.com/solutions/1232133)
* click the "LOG IN" button on the bottom
* select the desired username from the drop-down & hit "NEXT"
* nothing happens, I have to either Ctrl+C/Ctrl+V the password, or RMB -> Perform Auto-type Sequence -> {PASSWORD}

## Possible Solution
:man_shrugging: I think this used to work fine in some previous versions, I have no idea when exactly it broke.

## Steps to Reproduce (for bugs)
See "Current Behavior". :wink: You don't even need a valid login, just make one up and try to get keepassxc-browser to fill the password in automatically.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux i686
Browser: Mozilla Firefox 78.0 ESR, Chrome/Chromium 88.0.4324.182

**Comment by varjolintu** [comment]
Add `https://sso.redhat.com/auth/*` to extension's Site Preferences settings and enable "Username-only Detection" for it.

**Comment by z1atk0** [comment]
Hm, that solution doesn't seem to work for me, it shows exactly the same behaviour as before, both on Firefox and on Chromium. I do get the dropdown with my three logins on the first (username) page, but once I chose one of the three logins and klick "NEXT", the password field on the second (password) page remains emtpy, no matter what I do and which entry I selected.

Are there any other relevant settings that I need to enable or disable in either KeepassXC itself of keepassxc-browser for this to work properly?

**Comment by varjolintu** [comment]
Hmm. Let's reopen this then. I'll see what I can do.

**Comment by z1atk0** [comment]
Thanks for your help! :smile: :+1: If you need any further information or testing from me just let me know.

**Comment by varjolintu** [comment]
I tried this again and seems it's not an easy fix. It's possibly related to the "awesome" CSS animation, so we try to enable the icon way too early before the input field is even actually visible, and the detection fails for it.

**Comment by linux-guru-com** [comment]
I can confirm the same (buggy) behaviour for:
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.8.1
Operating system: Win 20H2 (19042.1052)
Browser: Chrome 91.0.4472.106

**Comment by varjolintu** [comment]
Now tracked in #1358.
