### ISSUE TITLE
Add one-click viewing of all passwords associated with this website, and allow copying

### ISSUE THREAD

**Issue by BlueDrink9** [keepassxreboot/keepassxc-browser#1246]
## Expected Behavior

Sometimes, it happens that keepassxc-browser doesn't fill things correctly, or won't fill, or has some other issue. But reporting and getting bugs fixed has a significant turnaround time, and I want things filled *now*. Also, sometimes I don't even know if it's a filling bug or a URL issue, when I'm on a site and I expect a field to be filled with a certain password.

Lastpass has a convenient interface this when it screws up. If you click the extension logo, it shows a list of all entries associated with that URL, and each entry can be clicked to copy either the username or password (or other field).
This is independent of any form to be filled, and it would be very useful to have on this extension.

## Current Behavior

Currently, clicking the extension icon is largely unhelpful after the original connection setup.

**Comment by droidmonkey** [comment]
We offer a better solution called Auto-Type.  With my most recent major refactor, Auto-Type will allow you to search the database for an entry and type it in very fast. Using the clipboard is not a secure solution and we try to avoid that behavior as much as possible.

**Comment by droidmonkey** [comment]
See https://keepassxc.org/docs/KeePassXC_UserGuide.html#_auto_type on how to use it and https://github.com/keepassxreboot/keepassxc/pull/5864 for the improvements PR

**Comment by BlueDrink9** [comment]
Thanks for the tip, but I know about (and use) autotype.

Copying/pasting is not the core of this feature request. The core is seeing the applicable entries from the browser extension. It would be a fine solution to click on them to autotype the username/password into a chosen field instead.

**Comment by droidmonkey** [comment]
If you don't see the entries already then you haven't configured them to work with the browser extension. Check that the entry url is correct and you haven't blocked it from the extension.

**Comment by BlueDrink9** [comment]
Should I be seeing them when clicking the extension button? I see them in the login form if there are multiple, but forms aren't always recognised or doesn't fill properly. Sometimes I click the form button and no entry fills, sometimes the only entry immediately fills.

Additionally, if the url *is* incorrect, the fact that it doesn't show up in a list of "entries for this page" helps users recognise that the url is the issue and not the form.

**Comment by droidmonkey** [comment]
Ok sorry, you are correct, sometimes the extension pop-up does not show the available entry list, that is a bug.

**Comment by BlueDrink9** [comment]
Brilliant if that is intended behaviour. To clarify, when I click on the extension icon in the top right, I should see a list of entries available for this url?

**Comment by droidmonkey** [comment]
Yes, but only if there are login fields detected on the page.

**Comment by BlueDrink9** [comment]
Ah. Would it be possible to change that? So that if the fields exist but aren't detected or aren't the usual kind of form, we can still access the entry? Or just as a shortcut to check the username/email for that website?

**Comment by droidmonkey** [comment]
Probably not, this would trigger a credential request on every page. If you don't have that auto authorized you would see the requesting credentials pop-up from keepassxc every time you navigated the pages.

**Comment by BlueDrink9** [comment]
Ah, that makes sense. Thank you.

The bug still stands in the sense that even with login input fields visible, clicking the extension icon in the top doesn't show any entries, even if the autofill does work. But if I have misunderstood that behaviour, feel free to close.

**Comment by varjolintu** [comment]
I think this should be fixed with 1.8.5.
