### ISSUE TITLE
Can't fill mailbox password on app.protonmail.ch / mail.protonmail.com

### ISSUE THREAD

**Issue by Ketchup901** [keepassxreboot/keepassxc-browser#1249]
## Expected Behavior

KeePassXC-Browser should fill both the login username / password and the mailbox decrypt password.

## Current Behavior

The login username / password is filled but not the mailbox decrypt password, even if you manually tell it to.

## Possible Solution

I think the bug is happening because KeePassXC-Browser is not detecting the mailbox decrypt box as a password input. This could be solved by either adding more customizability (scripting support) or pre-programming Protonmail support into the extension.

## Steps to Reproduce (for bugs)

1. Open https://app.protonmail.ch or https://mail.protonmail.com.
2. Fill login details automatically or explicitly.
3. Page takes you to the mailbox decryption step, where you will be unable to fill it using KeePassXC-Browser.

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux
Browser: Waterfox G3 (basically Firefox)

**Comment by varjolintu** [comment]
It's a known issue (for me). We must create an exception for the mailbox password page with Protonmail.
