### ISSUE TITLE
Source Code Understanding

### ISSUE THREAD

**Issue by abilogos** [keepassxreboot/keepassxc-browser#1253]
Hi,

i was reading a function in [keepassxc-browser/keepassxc-browser/content/keepassxc-browser.js](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js) but i couldnt understand what is its purpose and what is the **Mutation** means exaclty. 

Line #1564 :

```
   // Stores mutation style to an cache array
// If there's a single style mutation, it's safe to calculate it
kpxcObserverHelper.cacheStyle = function(mut, styleMutations, mutationCount) {
    if (mut.attributeName !== 'style') {
        return;
  
```

Thanks for The Useful Extension.

**Comment by varjolintu** [comment]
Mutation (here `mut`) is a single change to the page DOM tree. A mutation can include CSS changes, HTML element additions/removal etc.

Here's a great and simple page that explains it: https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver
