### ISSUE TITLE
keepassxc-browser interferes with unrelated input fields on pypi.org

### ISSUE THREAD

**Issue by ziegenberg** [keepassxreboot/keepassxc-browser#1254]
## Expected Behavior

When clicking into the field "Add email" in the section "Account emails" on https://pypi.org/manage/account/, the input focus stays in the field "Add email".

## Current Behavior

When clicking into the field "Add email" in the section "Account emails" on https://pypi.org/manage/account/, the input focus changes to the field "Confirm new password," and it's impossible to enter information into the field "Add email".

Disabling the KeePassXC-Browser extension makes the bug disappear.

## Steps to Reproduce (for bugs)

1. open https://pypi.org/manage/account/ and login
2. in the section "Account emails", click into the field "Add email".
3. the input focus changes to the field "Confirm new password", and it's impossible to enter information into the field "Add email".

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux (Fedora 33)
Browser: Chrome and Firefox

**Comment by luni3359** [comment]
I can't recall which websites I've experienced this in, but I can confirm that the focus-stealing behavior of the extension is making it impossible to enter information.

**Comment by varjolintu** [comment]
This is already fixed in the current develop branch. Just wait for a new release.
