### ISSUE TITLE
KPH: usage doc fix

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc-browser#1258]
I don't think this is a bug with either KeePassXC or the Browser add-on.  Just an issue with clarifying the documentation a bit... however I couldn't find an appropriate bit to raise this on GitHub (closest may have been keepassxreboot/keepassxc-wiki... but it seems to have no commits or issues).

https://keepassxc.org/docs/#faq-browser-string-fields

![Selection_376](https://user-images.githubusercontent.com/10448369/110204899-679fe800-7e6d-11eb-8b20-a280e45a89b0.png)

Following the example that documentation talks about (on the same website it mentions), we start by selecting the custom fields...

![Selection_374](https://user-images.githubusercontent.com/10448369/110204611-dbd98c00-7e6b-11eb-8503-f2ae166a5317.png)

Then entering them into Advanced | Additional attributes in same order that we picked those fields above...

So this means creating 'KPH: Branch' first... but then, hang on... if we make 'KPH: Account' next - the UI is automatically sorting it to be above 'KPH: Branch' in the list.  But we carry on entering them anyway, and it looks like this when we're done (it's sorted them like this... but we entered 'KPH: Branch' first)...

| Attribute  | Value |
| ------------- | ------------- |
| KPH: Account  | 1234567  |
| KPH: Branch  | 666  |
| KPH: Sub-account  | 99  |

But you'll see it then puts them in the wrong place...

![Selection_375](https://user-images.githubusercontent.com/10448369/110204815-0a0b9b80-7e6d-11eb-84a5-128311d4c966.png)

But if we rename them with a few numbers added to force the sorting...

| Attribute  | Value |
| ------------- | ------------- |
| KPH: 1 Branch  | 666  |
| KPH: 2 Account  | 1234567  |
| KPH: 3 Sub-account  | 99  |

We get the right outcome...

![Selection_377](https://user-images.githubusercontent.com/10448369/110205021-16dcbf00-7e6e-11eb-9e31-96b3048bc2e1.png)

The other option of course would be to select the custom fields in the order of how your KPH: attributes show in KeePassXC (if you've done the process the other way around... i.e. do the KeePassXC end first, then KeePassXC-Browser custom fields after).

So ultimately the issue is that the documentation...
- Says the order they're added to the entry is critical... when it isn't... it's how the names you gave them are sorted which is critical.
- Implies giving a memorable 'short name' after the 'KPH: ' prefix is optional... when it's entirely how it'll determine the order of what to read.

Personally I think the documentation should advise using a number in the name.  As that way if a new attribute is added to the login form in the future... someone just needs to match up the custom field numbers with the numbers in the attributes... rather than re-figure out what now comes alphabetically (which would have potentially changed).

That's all.

**Comment by varjolintu** [comment]
I think we should just use the attribute order in KeePassXC so there's no extra documentation needed for this.

**Comment by Lantizia** [comment]
Attribute order?

**Comment by varjolintu** [comment]
See: https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-situations-and-debugging
