### ISSUE TITLE
TOTP isn't usable on Proxmox VE

### ISSUE THREAD

**Issue by Lantizia** [keepassxreboot/keepassxc-browser#1259]
I can get a demo Proxmox VE system online if anyone needs it to test against it.

But basically if you're just doing user/pass then the auto-fill is fine.

However if also doing TOTP then that comes up afterwards but it doesn't reload the page to show it (it's like an extra HTML div on top).  So the icon doesn't show to click it to fill in TOTP.

Have tried to do this with custom fields... (as I can still select user/pass fields behind that TOTP div)... but it just results in it only filling out the password oddly...

How things look if you enable the overlay to show fields...

![Selection_378](https://user-images.githubusercontent.com/10448369/110207244-134f3500-7e7a-11eb-8f46-fd6bdc2962ef.png)

How the TOTP screen looks normally...

![Selection_379](https://user-images.githubusercontent.com/10448369/110207256-26fa9b80-7e7a-11eb-9b5d-ad6613199009.png)

How you can select the TOTP field to be used as the TOTP field...

![Selection_380](https://user-images.githubusercontent.com/10448369/110207265-3843a800-7e7a-11eb-8e53-0608508085d0.png)

Finally how if you do all that... the auto-fill just oddly fills in the password...

![Selection_381](https://user-images.githubusercontent.com/10448369/110207289-74770880-7e7a-11eb-8fa0-4720115ca7cd.png)

**Comment by varjolintu** [comment]
A demo system is totally needed for fixing this.

**Comment by droidmonkey** [comment]
Recommend using Auto-Type in this scenario, this website looks crazy stupid

**Comment by varjolintu** [comment]
The new Custom Login Fields PR solves this. Also, it's possible to define TOTP manually to the entry attributes and use context menu's Fill Attribute feature to fill it.

**Comment by Lantizia** [comment]
Demo system to test on temporarily supplied... and...

Yay!  (this comment was not strictly needed... but an expression of joy was absolutely required).
