### ISSUE TITLE
"Activate autocomplete for username fields." in Firefox extension causes undesirable behaviour on Bandcamp website

### ISSUE THREAD

**Issue by S4qFBxkFFg** [keepassxreboot/keepassxc-browser#1260]
## Overview
When the option "Activate autocomplete for username fields." is enabled in the Firefox extension, it prevents changing the text in one of the fields on the Bandcamp website.

## Steps to Reproduce
1. ensure the "Activate autocomplete for username fields." option is enabled in KeePassXC-Browser settings (General Settings,  Filling credentials) 
2. log in to bandcamp.com
3. go to https://bandcamp.com/settings?pane=profile
4. click in the "Email:" field

## Expected Behavior
A new email address can be entered.

## Actual Behavior
The cursor immediately jumps to the "New Password: (again)" field lower down the page.

## Context
deactivating "Activate autocomplete for username fields." and reloading the bandcamp page prevents the problem

KeePassXC-Browser Version: 1.7.6
KeePassXC Version: 2.6.4 

Operating System: Linux x86_64
Desktop Env: XFCE
Windowing System: X11
Browser: Mozilla Firefox 86.0

**Comment by varjolintu** [comment]
I'm glad to inform you that this has been already fixed in the current develop branch :) Just wait for the new release.
