### ISSUE TITLE
Keepassxc extension on Libre wolf browser can't connect to database.

### ISSUE THREAD

**Issue by tati1454** [keepassxreboot/keepassxc-browser#1262]
The keepassxc extension throws an error when connecting to the DB using the browser libre wolf.

## Expected Behavior
I expect the extension successfully connecting to the database.

## Current Behavior
The extension throws `Key exchange was not successful.` error.

## Steps to Reproduce (for bugs)
1. Install keepassxc extension from the mozilla store in the libre wolf browser.
2. Enable browser integration in keepassxc. 
3. Open the keepassxc browser popup and click on `reload`.

## Debug info
```
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1142:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Failed to connect: Unknown error keepass.js:1029:13
Error: No content script available for this tab. keepass.js:1262:25
Error 9: Key exchange was not successful. keepass.js:1142:13
Error: No content script available for this tab. keepass.js:1262:25
```

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux Mint 20.1
Browser: Libre wolf 86 (64 bits)

**Comment by droidmonkey** [comment]
Use the custom browser feature in keepassxc under the application settings-> browser-> advanced.

**Comment by keizah7** [comment]
https://github.com/keepassxreboot/keepassxc/discussions/7669#discussioncomment-6694506
