### ISSUE TITLE
Logon to kobo not working

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc-browser#1266]
Autotype does not work and typing manuall results in the display attached
Fedora / FireFox
![Screenshot from 2021-03-14 11-32-57](https://user-images.githubusercontent.com/1612152/111065341-7152cc80-84b9-11eb-8a4c-770c9c1a9810.png)

**Comment by varjolintu** [comment]
I need more information. I had no problems filling the login information.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
