### ISSUE TITLE
Browser access request does not remember denial

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1268]
## Expected Behavior

My selection for credentials available to a specific page is rememberd when I check the **Remember** checkbox in the dialog.

## Current Behavior

Only allowed entries are remembered. The dialog keeps popping up every single time I visit the page.

## Possible Solution

Remember my selection.

## Steps to Reproduce (for bugs)

1. Create a password entry with a browser integration on a certain domain.
2. Visit the domain in your browser.
3. Check **Remember**
4. Click **Deny All**.
5. Visit the same domain again.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win64
Browser: Chrome/Chromium 89.0.4389.82

**Comment by varjolintu** [comment]
Click the button "Disable for this site" at the right side of the URL in the dialog.
