### ISSUE TITLE
Cannot autofill password on Mailgun

### ISSUE THREAD

**Issue by Arzaroth** [keepassxreboot/keepassxc-browser#1269]
As the title suggests, the autofill is broken for Mailgun. I can fill the username just fine but I have to paste the password manually.

## Expected Behavior

* Navigate to https://login.mailgun.com
* Grant access to the relevant entry
* Autofill the username
* Click Next
* Autofill the password
* Login

## Current Behavior

* Navigate to https://login.mailgun.com
* Grant access to the relevant entry
* Autofill the username
* Click Next
* The password cannot be autofilled.

I don't recall it ever working (but I've only been using Mailgun for the last 5 months or so).

## Steps to Reproduce (for bugs)

Cf. Current Behavior. You need a valid account to get to the password part though.
They argue on their website that "Getting Started With Mailgun Is Free And Takes 57 Seconds", but I understand that creating an account just for the sake of squashing a bug that does not affect you is bothersome.

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win64
Browser: Mozilla Firefox 86.0

I see no error messages in the console.

**Comment by varjolintu** [comment]
This happens because of some CSS animations. We don't support them properly yet.

**Comment by varjolintu** [comment]
Now tracked in #1358.
