### ISSUE TITLE
keepassxc-browser (Firefox) does not offer to save new credentials with https://www.pixton.com/

### ISSUE THREAD

**Issue by akatekar** [keepassxreboot/keepassxc-browser#127]
Trying to login to the above website, the keepassxc browser extension does not offer to save new credentials.
## Expected Behavior
It should offer to save new credentials just entered. 

## Current Behavior
It does not offer to save the newly entered credentials. Shows the red cross (x) over the icon on entering the username and password. 

## Steps to Reproduce (for bugs)
1. Got to LogIn on the website https://www.pixton.com/
2. Enter your username and password. 
3. Does not offer to save new credentials. 
4. For most sites, I have to click on the blinking red lock 2 times before I get the prompt to save new/updated credentials. 

## Debug info
KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Windows 10 x64.
Browser: Firefox
Proxy used: NO
![image](https://user-images.githubusercontent.com/38507029/38951025-f16c2656-430c-11e8-8382-aa1fce1d0597.png)
![image](https://user-images.githubusercontent.com/38507029/38951095-1fa48220-430d-11e8-80ea-808b28eefcbf.png)
![image](https://user-images.githubusercontent.com/38507029/38951160-55eeb846-430d-11e8-823c-ba6273018986.png)

**Comment by varjolintu** [comment]
Duplicate issue https://github.com/keepassxreboot/keepassxc-browser/issues/67.
