### ISSUE TITLE
Feature request: add a button to capture and save the url to database

### ISSUE THREAD

**Issue by flynxea** [keepassxreboot/keepassxc-browser#1270]
## Feature request: add a button to capture and save the URL to database

The feature is for using keepass database as a bookmarks system.
Just want to save the url and title by one key.

thanks.

**Comment by varjolintu** [comment]
There is someone using KeePass database as a bookmarks system?

**Comment by droidmonkey** [comment]
I suppose you could just use the add credentials menu option in the next release to create an empty entry with only the url and title. This seems very silly to me though.

**Comment by flynxea** [comment]
> There is someone using KeePass database as a bookmarks system?

Yes, I want to use Keepass as a bookmarks system.  I cannot find a bookmarks management system, and found Keepass may be the good choice.

**Comment by flynxea** [comment]
> I suppose you could just use the add credentials menu option in the next release to create an empty entry with only the url and title. This seems very silly to me though.

You mean the next release of keepassxc-browser would contain the feature to capture the whole URL?
OK, thanks a lot and waiting for the next release.

**Comment by varjolintu** [comment]
> > I suppose you could just use the add credentials menu option in the next release to create an empty entry with only the url and title. This seems very silly to me though.
> 
> You mean the next release of keepassxc-browser would contain the feature to capture the whole URL?
> OK, thanks a lot and waiting for the next release.

This feature seems a bit silly for me too. I'm not sure if this is something worth spending time on.

**Comment by flynxea** [comment]
> > > I suppose you could just use the add credentials menu option in the next release to create an empty entry with only the url and title. This seems very silly to me though.
> > 
> > 
> > You mean the next release of keepassxc-browser would contain the feature to capture the whole URL?
> > OK, thanks a lot and waiting for the next release.
> 
> This feature seems a bit silly for me too. I'm not sure if this is something worth spending time on.

Then, could you please help recommended a bookmarks manager software?  I cannot find a better one over the internet.

I'd like to collect bookmarks with tags (not folder), and sync among different PCs.
I don't like online services because the bookmarks maybe privacy and online service may shut down some days later.
It should be simple to collect the URL instead of manually copy-paste to the software, I know I could copy the url and paste to keepass.
Finally, someway keepass is also a bookmarks system for url with login credential, so why not save all the bookmarks to a same app in spite of has credential or not.

**Comment by droidmonkey** [comment]
There seems to be a bunch to choose from: https://github.com/search?q=bookmark+manager&type=

Every browser I have used also syncs bookmarks and allows for exporting them. I am closing this because we aren't going to be a bookmark manager and technically you can use the app as such already with copy paste.
