### ISSUE TITLE
Extension log unnecessary information

### ISSUE THREAD

**Issue by kris7453** [keepassxreboot/keepassxc-browser#1272]
## Expected Behavior
Extension shouldn't log unnecessary information to console.

## Current Behavior
Extension log mouse move event information to console.

## Steps to Reproduce (for bugs)

1. Open browser console on any page.
2. Move mouse cursor over the page.

## Debug info

KeePassXC - 1.7.6
KeePassXC-Browser - 2.6.3
Operating system: Windows 10
Browser: Firefox

**Comment by varjolintu** [comment]
What do you mean? Can you give a screenshot or an example? The extension only logs some error situations to the console, but nothing more.

**Comment by droidmonkey** [comment]
Never seen this before. You must be mistaking for a different extension or the page itself.

**Comment by varjolintu** [comment]
@droidmonkey Actually it does. `mousemove` is registered for moving around Custom Login Fields and Password Generator dialog. `mouseup` and `mousedown` are registered for disabling Mutation Observer when needed, and `click` is registered for detecting clicks outside the Autocomplete Menus (which closes them).

**Comment by droidmonkey** [comment]
Ooooh well then you learn something every day. I didn't know about the mouse move events.

**Comment by kris7453** [comment]
Sorry that I response 2 days later. I don't know, why it looks like that, but I can't find the script that register event in extension, but firefox saying that the script comes from KeePassXC-Browser.

Those are events logged to my console:
![console](https://user-images.githubusercontent.com/20442936/111880319-20f0d880-89ab-11eb-9303-d03370f13463.jpg)

This is script that register that event:
![console2](https://user-images.githubusercontent.com/20442936/111880326-25b58c80-89ab-11eb-8d2e-71c67871ba02.jpg)

Here is "inspected" extension in firefox:
![extension](https://user-images.githubusercontent.com/20442936/111880329-2817e680-89ab-11eb-8c05-e541138a30a1.jpg)

I couldn't find the script here, but id is the same for the script and the extension, what is visible on last two pictures.

**Comment by varjolintu** [comment]
You've probably enabled these settings which are just for debugging purposes. It prints all the events to the console. The extension itself is not doing so. Closing the issue.
<img width="712" alt="Screenshot 2021-03-20 at 20 19 50" src="https://user-images.githubusercontent.com/24570482/111881588-b7c49180-89b9-11eb-8ce3-f429331d8db9.png">

**Comment by kris7453** [comment]
Yeah you have right, I didn't notice, that I have enabled logging events to console. My stupid fault. Thanks for your help and sorry for wasted time.

**Comment by varjolintu** [comment]
@kris7453 Don't be sorry! I didn't know this kind of feature even existed, so I had a possibility to learn a few new things :)
