### ISSUE TITLE
Auto-reconnect

### ISSUE THREAD

**Issue by FrankyBoy** [keepassxreboot/keepassxc-browser#1273]
## Expected Behavior
If KeepassXC is running (no matter when it was started) I want to be able to fill my passwords without manually having to establish a connection.

## Current Behavior
When KeepassXC is started after the browser, the user needs to manually reconnect through the extensions button.

## Possible Solution
If the user triggers a function that requires KeepassXC to be connected, try reconnecting first.

**Comment by varjolintu** [comment]
There's already Auto-Reconnect feature in the extension, although it's an experimental feature.
