### ISSUE TITLE
Amazon splited login is not working for long time

### ISSUE THREAD

**Issue by claire1990** [keepassxreboot/keepassxc-browser#1274]
Dear KeePassXC-Team,

thanks for the great extension!

But the Amazon login does not work. Have tried Custom Fields, no chance.

## Expected Behavior
The browser plugin detects Amazon credential fields and fills it. It doesn't.

## Current Behavior
The Key Symbol appears, but clicking on it makes nothing happen. Also right-click/fill in does not work.

## Steps to Reproduce (for bugs)
Trying to log in over this link:
https://www.amazon.de/ap/signin?***
***lots of letters and digits, maybe contains personal information, will not post here

## Debug info
KeePassXC-Version: 2.6.4
KeePassXC-Browser-Version: 1.7.6
Operating system: Linux Manjaro, actual Version. It is based on Arch Linux
Browser: Firefox 86.0.1 (64-Bit)

Thanks for help

**Comment by varjolintu** [comment]
Amazon works for me nicely. What's your entry URL?

**Comment by claire1990** [comment]
Don't know what have changed, but it is working now. Thanks & close :)
