### ISSUE TITLE
Where does KeePassXC store login+passwd? Error "Cannot conect to KeePassXC"?

### ISSUE THREAD

**Issue by tobwz** [keepassxreboot/keepassxc-browser#1279]
I am new to KeePassXC and have some questions about the AddOn (for Firefox v87 on Windows).

After installation of the KeePassXC Addon it is telling me:

"Cannot connect to KeyPassXC. Check that browser integration is enabled in KeePassXC settings"

I never changed the settings. So that means KeyPassXC does not work out of the box?

What exactly do I have to switch in settings to get it working?

"Connect" sounds  that the AddOn tries to connect to external KeePassXC tool outside of the browser.
So passwords are not stored inside the browser? Additional, external KeyPassXC installation on the same machine is always required. Is this correct?

If yes: Can I install external KeyPassXC AFTER AddOn? Or is the opposite installation order required?

**Comment by varjolintu** [comment]
See: https://keepassxc.org/docs/KeePassXC_UserGuide.html#_setup_browser_integration

In short: KeePassXC must be opened in the background. The extension doesn't access your database directly.
