### ISSUE TITLE
[bug] The extension doesn't ask to save a password on vonovia.de

### ISSUE THREAD

**Issue by LightTemplar** [keepassxreboot/keepassxc-browser#1281]
The issue looks same as this: 
https://github.com/keepassxreboot/keepassxc-browser/issues/1111#issue-743426150

Site: https://www.vonovia.de/

I click form button, not "enter", but it still doesn't ask for saving credentials.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux x86_64, Kubuntu 20.04
Browser: Mozilla Firefox 86.0

**Comment by varjolintu** [comment]
Cannot reproduce. When I click Anmelden, the Credential Bar appears normally.

**Comment by LightTemplar** [comment]
@varjolintu 
thanks for your feedback. I cleared cookies and site data and now it works also for me.
