### ISSUE TITLE
Browser Extansion not working in Tor-Browser - Message Encryption failed

### ISSUE THREAD

**Issue by JulianFP** [keepassxreboot/keepassxc-browser#1282]
## Expected Behavior
- Browser Extension should connect to the Keepass Database like it does in Firefox

## Current Behavior
- When I am opening the Tor-Browser, it says " Message encryption failed. Is KeePassXC running?"
- When I click "Reload", it says "Key exchange was not successful."
- In Keepassxc, I enabled the browser integration for both Firefox and Tor-Browser. Still not working

## Steps to Reproduce (for bugs)
1. Enable Tor-Browser Integration
2. Install Keepassxc Browser Extension in Tor
3. Click on the Icon of the Extension an see the error messages

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Linux (Manjaro)
Browser: Tor-Browser

**Comment by varjolintu** [comment]
Check the Tor Browser section here and see if it helps solving the issue: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by brightphaeton** [comment]
It unfortunately not helped. The `org.keepassxc.keepassxc_browser.json` is in place at `/home/<user>/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/` and has the correct path variable (`/usr/bin/keepassxc-proxy`) and extension ID in it. keepassxc-proxy is running

**Comment by varjolintu** [comment]
So Tor Browser starts the keepassxc-proxy normally? Each browser will start an own instance of it.

**Comment by brightphaeton** [comment]
Oh, I didn't know that. After closing all Firefox Windows I discovered, that Tor doesn't start keepassxc-proxy. `sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass` doesn't show anything ether.

**Comment by varjolintu** [comment]
That means Tor probably doesn't load the JSON script from the correct location. You can use `strace` to find out the correct path.

**Comment by brightphaeton** [comment]
`sudo strace -f -p $(pgrep firefox.real) 2>&1 | grep keepass` (where firefox.real is the parrent-process of tor) delivers the following:
[pid 22360] openat(AT_FDCWD, "/home/{User}/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid 21995] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 22377] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/{User}/.local/share/torbro"..., "keepassxc-browser@keepassxc.org"], 0x7fbd41b71000 /* 68 vars */) = -1 EACCES (Permission denied)

What is the problem? I ran `sudo chmod 777` on both the .json and the /usr/bin/keepassxc-proxy, so the process should have the permissions to access this files...

**Comment by varjolintu** [comment]
That's very strange. Never seen that one before. But it might be related to Flatpak, as it seems TorBrowser Launcher is currently using that. Maybe this thread can help you: https://github.com/keepassxreboot/keepassxc-browser/issues/297

**Comment by brightphaeton** [comment]
I installed Tor over the Manjaro Repository, and not as Flatpak. In spite of that I tried your solution from this post but the error remains the same:

[pid 26453] openat(AT_FDCWD, "/home/julian/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Dsts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid 26438] stat("/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC.proxy",  <unfinished ...>
[pid 26658] execve("/var/lib/flatpak/exports/bin/org.keepassxc.KeePassXC.proxy", ["/var/lib/flatpak/exports/bin/org".., "keepassxc-browser@keepassxc.org"], 0x7f5d2a316000 /* 68 vars */) = -1 EACCES (Permission denied)

**Comment by droidmonkey** [comment]
This is most likely due to flatpak firejail settings

**Comment by salperinlea** [comment]
I would like to say that I am having this same issue on Ubuntu, using the torbrowser-launcher version one can obtain via apt-get; everything works fine in Firefox, but in the tor browser, all is malfunct. All details are the same as for JulianFP, including the permission denial in strace.

I note that, when installing the addon, _the dialog to create a connection never occurs_, unlike for straight firefox, in which one is prompted to create a connection with a unique identifier. I suspect that this is relevant.

KeePassXC - 2.6.6  (I think. Wasn't autodetecting).
KeePassXC-Browser - 1.7.10.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 91.0

**Comment by varjolintu** [comment]
Let's follow this thread instead: #1503.
