### ISSUE TITLE
[Feature request] Add option to disable TOTP

### ISSUE THREAD

**Issue by a14219** [keepassxreboot/keepassxc-browser#1284]
I never use TOTP function, yet every time I must choose custom login fields where more fields are required, I have to skip TOTP in order to get to my custom KPH strings.
A while back, the TOTP could be skipped by simply clicking again over it, but now that's not possible anymore. I'm not sure when or why was this changed, but it's quite annoying since I'm forced to use the keyboard now to skip TOTP and I must start over again if I missed it.

## Current Behavior
TOTP can't be skipped clicking again over it, nor it can be disabled in any way.
![Z9PK49KtU0](https://user-images.githubusercontent.com/64659987/112746678-bf36fc80-8fb0-11eb-8211-ed348cd06e0b.gif)

## Possible Solution
+ Give an option to disable TOTP entirely or based on URL.
+ Bring back the option to skip TOTP by clicking again on the form field.

## Steps to Reproduce (for bugs)
1. Get to any login form with more than 2 fields.
2. Choose custom login fields.
3. Click on one field for username, next for password, next for TOTP.
4. Click again on 3rd field to select String field 1 from KPH Strings.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Win
Browser: Edge/Vivaldi/Chromium

**Comment by varjolintu** [comment]
I think the easiest option is to enable skipping the TOTP by clicking again on the form field. I actually had no idea that was missing!

**Comment by a14219** [comment]
> EDIT 2: There's the Skip button available. No need to use the keyboard if you don't want to.

Thanks. I didn't notice those were buttons.
Anyway, it would be nice to disable it altogether.

**Comment by varjolintu** [comment]
This is fixed by https://github.com/keepassxreboot/keepassxc-browser/pull/1390.
