### ISSUE TITLE
Custom user and password fields are not filled

### ISSUE THREAD

**Issue by euakll** [keepassxreboot/keepassxc-browser#1285]
On the website of deepl.com you can not login. you have to define the custom user and password fileds.
afterwards the user field gets the keepass symbol but does not react.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.6
Operating system: Mac
Browser: Firefox 87.0

**Comment by varjolintu** [comment]
Works just fine for me without any custom fields.
