### ISSUE TITLE
Password Generator; ability to change password strength in popup?

### ISSUE THREAD

**Issue by mxmilkiib** [keepassxreboot/keepassxc-browser#1287]
4 small buttons next to the existing yellow ones for toggling symbols, extended ascii, and changing the length, would be handy.

The character inclusion toggles could have three letters of that character class as a label.

**Comment by varjolintu** [comment]
I consider this as a duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/932

**Comment by mxmilkiib** [comment]
Good point, my search-fu was off there.
