### ISSUE TITLE
TypeError: form.id.includes is not a function at keepassxc-browser.js:410

### ISSUE THREAD

**Issue by nextonphotos** [keepassxreboot/keepassxc-browser#1289]
I've been getting JavaScript errors in the console on Chrome when working with various forms that don't involve login or using the extension.

## Expected Behavior
Ideally, these errors shouldn't happen so they don't clutter the console.

## Current Behavior
The errors I'm receiving are as follows:
Uncaught (in promise) TypeError: form.id.includes is not a function at keepassxc-browser.js:410
Uncaught (in promise) TypeError: form.name.includes is not a function at keepassxc-browser.js:410

## Possible Solution
It seems to be happening because the form in question has hidden inputs with name="id" and name="name".  Perhaps a fix would be as simple as adding a check for this situation, or checking that includes is a function prior to calling it?

## Steps to Reproduce (for bugs)
This fiddle demonstrates the error: https://jsfiddle.net/czqLm1y8/1/
Both the hidden id and the hidden name inputs cause an error. Deleting the id input and rerunning the fiddle will cause the name to error.

## Debug info
Uncaught (in promise) TypeError: form.id.includes is not a function
    at keepassxc-browser.js:410
    at Array.some (<anonymous>)
    at Object.kpxcFields.getSegmentedTOTPFields (keepassxc-browser.js:410)
    at Object.kpxcFields.getAllCombinations (keepassxc-browser.js:381)
    at Object.kpxc.initCombinations (keepassxc-browser.js:1263)
    at Object.kpxcObserverHelper.handleObserverAdd (keepassxc-browser.js:1873)
    at MutationObserver.<anonymous> (keepassxc-browser.js:1972)

KeePassXC-Browser Version: 1.7.7
KeePassXC Version: 2.6.4
Operating system: Windows 10
Browser: Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
Always missing some check.. let's fix this asap.

**Comment by varjolintu** [comment]
This is happening because of a strange Chrome/Chromium bug (or is it a bug, I dunno?) I've encountered before. The form's ID is actually set to the input field element because its name is "id". That why it's not regognized as a proper string. It's surely a strange behaviour that element ID can override the parent element's property. We need to add some extra checks here for Chromium.
