### ISSUE TITLE
Feature Request: bookmark sync

### ISSUE THREAD

**Issue by hrez** [keepassxreboot/keepassxc-browser#129]
Any thoughts on bookmark sync to keepass?
That would allow cross-browser sync.

**Comment by varjolintu** [comment]
I think that kind of feature is not related to KeePassXC or password management at all. Browsers already deliver their own sync methods for bookmarks.

**Comment by hrez** [comment]
Not cross-browser though.
Keepassxc being cross-browser would fit nicely there.
Arguably, the key part of browser password management is URL of the resource.
Which is basically a bookmark.
