### ISSUE TITLE
Fills wrong account information

### ISSUE THREAD

**Issue by jakeparis** [keepassxreboot/keepassxc-browser#1295]
## Expected Behavior

Going to a site for which I have many different saved credentials, I click the icon to see a dropdown of available credentials. I click the one I want and expect to see those creds filled into the user/pass fields. 

## Current Behavior

Instead, one of the other available credentials are entered into the user/pass fields. It's consistently wrong: if I click the 1st item in the list, I always get the 8th instead. If I click the 2nd, I always get the 7th, etc.

## Steps to Reproduce (for bugs)

1. 🤷‍♂️ 

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: MacIntel
Browser: Mozilla Firefox 88.0

**Comment by jakeparis** [comment]
I can confirm that this happens in my "chromium" browser also (Vivaldi). 

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: MacIntel
Browser: Chrome/Chromium 89.0.4389.91

**Comment by jakeparis** [comment]
AND, in both cases, the password is filled correctly, but the username is incorrect.

**Comment by varjolintu** [comment]
I cannot reproduce this. Tried it with Edge and Firefox.

**Comment by jakeparis** [comment]
I have two databases open. Do you want a screen gif of it happening?

**Comment by varjolintu** [comment]
I'll test it with multiple databases. With a single one I didn't see anything strange.

**Comment by jakeparis** [comment]
Ok, I closed one of my dbs (only have one open) and have some issue. How else can I help troubleshoot?

**Comment by varjolintu** [comment]
This would need debugging of the content script keepassx-browser.js inside the `kpxc.fillInCredentials()` function where `selectedCredentials` is set. Breakpoint after that should show the correct credential with matching password and uuid.

**Comment by jakeparis** [comment]
`predefinedUsername` is showing the wrong username. The one displayed there (jakeparis in this screenshot) is the one that ultimately gets filled into the form. 


<img width="831" alt="Screen Shot 2021-04-02 at 2 17 26 PM" src="https://user-images.githubusercontent.com/7408985/113442545-3825c200-93be-11eb-8f8f-972497acb4d2.png">

**Comment by jakeparis** [comment]
going up the call stack, the next function is `kpxc.fillFromPopup`. in that function the UUID _is_ correct, but the id is wrong... 

Next item in the call tree:
line:2048 with `browser.runtime.onMessage.addListener(async function(req, sender) {` where action=`fill_user_pass_with_specific_login` also has the wrong id...

Not sure what to do from there.

**Comment by varjolintu** [comment]
Thanks. This will help.

**Comment by varjolintu** [comment]
Fixed it. Thanks for the help! I didn't realize you were filling from the popup and not from Autocomplete Menu.
