### ISSUE TITLE
Chromium >= 90 sometimes fails to show up if automatic database reconnection is enabled

### ISSUE THREAD

**Issue by mara004** [keepassxreboot/keepassxc-browser#1298]
## Expected Behavior

Chromium browser >= 90 should always start up correctly with the main window visible.

## Current Behavior

If KeePassXC-Browser is configured to automatically re-connect, it sometimes does not. A number of chromium processes are running but the main window is not visible.

## Temporary Measure

If it takes longer to find a fix, maybe blacklist the option for Chromium >= 90 ?

## Steps to Reproduce (for bugs)

It's difficult to provide specific steps, since the issue only happens sometimes. Try to start chromium-browser repeatedly. There might also be a correlation to whether the database is opened when starting chromium.

## Notes
It worked without problems for older versions of chromium.
Chromium is configured to use its Wayland backend (`--enable-features=UseOzonePlatform --ozone-platform=wayland`).

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.7
Operating system: Linux (Wayland) (KDE Neon User based on Ubuntu Focal)
Browser: Chromium 90.0.4430.30 (beta, ppa build `https://launchpad.net/~saiarcot895/+archive/ubuntu/chromium-beta`)

**Comment by droidmonkey** [comment]
Auto connect is experimental and we don't support beta versions of browsers. Closing this for those points.

**Comment by mara004** [comment]
Okay, fine. Let's see whether the issue still exists when the stable version of Chromium is updated.
Nevertheless, I'm wondering what is causing this, especially since it happens relatively often (I'd estimate that it fails about 40% of all times).
Maybe it would be possible to add a timer to start the auto-reconnect feature a bit later, when we can be confident the main window is already visible? This could perhaps work around the problem.
