### ISSUE TITLE
Fill TOTP pulling from wrong account when 2 exist in different groups in KeePassXC database (tested with ProtonMail)

### ISSUE THREAD

**Issue by WildManiac** [keepassxreboot/keepassxc-browser#1302]
[Edited due to additional information being found [here](https://github.com/keepassxreboot/keepassxc-browser/issues/1302#issuecomment-817181649)]

## Expected Behavior

The OTP code that is generated when when using the browser extension is accepted, and for the correct account.

## Current Behavior

When the OTP code is generated via the KeePassXC-browser extension, it is denied. Additional investigation determined that it is being pulled from the wrong account.

## Steps to Reproduce (for bugs)

1. Have 2 ProtonMail accounts (with 2FA enabled) in the same folder in KeePassXC.
2. Login to ProtonMail with one account.
3. On OTP page, witness OTP dropdown stating the other ProtonMail account

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8
Operating system: Windows 10
Browser: Firefox 87, Vivaldi Snapshot 3.8.2254.3

**Comment by varjolintu** [comment]
Strange, because I use Protonmail very often and I haven't had any problems with the OTP code. Can you copy the TOTP from KeePassXC normally?

**Comment by WildManiac** [comment]
> Can you copy the TOTP from KeePassXC normally?

Yep, that way works perfectly fine. That was the second thing I checked, just to make sure that it was configured correctly. I even cleared it and reconfigured it.

But, I think I just found out what is going on. I have 2 protonmail accounts (1 main and 1 secondary). On the login page, it shows both in the KeePassXC-Browser dropdown. When it goes to the OTP section, it only has the secondary one in the dropdown. Never noticed this until now, but I think that is what is going on.

**Comment by WildManiac** [comment]
Alright, I think what is going on is this: I have 2 ProtonMail accounts, each account is in a separate folder in my KeePass database. When I attempt to login with either account, it attempts to pull the OTP from the OTHER account.

However, if both accounts are in the same folder there is no issue. Each accounts pulls their respective OTP.

**Comment by droidmonkey** [comment]
Oooh that's interesting!

**Comment by varjolintu** [comment]
Gotta check that out.

**Comment by WildManiac** [comment]
I have tested this with a new database, leaving everything default during the setup wizard. The issue is still occurring.

Database Hierarchy of Test Database:
- Root
  - Email
    - Account 1 (w/ OTP)
  - Internet
    - Account 2 (w/ OTP)

I have also changed the title and contents of this issue to better reflect the issue at hand.

**Comment by droidmonkey** [comment]
Maybe related to the entry sorting feature we put in the extension recently?

**Comment by WildManiac** [comment]
> Maybe related to the entry sorting feature we put in the extension recently?

You might be right. Just tested to see if the sort option affected this.

Sort matching credentials by:
Title: Works as expected
Username: Works as expected
Group and Title: Does not work as expected
Group and Username: Does not work as expected

Looks like when sorting involves the group is when things start getting wonky.

**Comment by varjolintu** [comment]
@WildManiac Thanks for testing this out! Making a fix soon.

**Comment by varjolintu** [comment]
I couldn't reproduce the issue but I still made an improvement that _should_ solve it. @WildManiac If you can, could you test https://github.com/keepassxreboot/keepassxc-browser/pull/1304 as a temporary extension and see if it helps? Thanks.

**Comment by WildManiac** [comment]
Loading as a temporary extension, both  sort by group options worked as expected (each account pulled their respective OTP information). I tested this with both my primary database as well as a new database).
