### ISSUE TITLE
Connect multiple databases

### ISSUE THREAD

**Issue by Carsten3000** [keepassxreboot/keepassxc-browser#1305]
## Expected Behavior

I have split my database into two (work and privat) and set up the auto open (https://keepassxc.org/docs/KeePassXC_UserGuide.html#_automatic_database_opening).

On my private systems i only want to setup my privat database, on my work system and i want to setup both. So the experience on my work system should be the same as if they were one database.

## Current Behavior

I can successfully add both databases in the browser, upon refreshing the website the older database vanished.

## Steps to Reproduce (for bugs)

1.
![image](https://user-images.githubusercontent.com/43674046/114303694-baee0180-9acf-11eb-828e-d0a98643493b.png)
2. press f5
3.
![image](https://user-images.githubusercontent.com/43674046/114303743-eec92700-9acf-11eb-8ae5-bc401d01e123.png)

The connection key inside the database is set and remains. 

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8
Operating system: Win64
Browser: Chrome/Chromium 89.0.4389.116

**Comment by varjolintu** [comment]
Open your second database and generate a new root group ID for it. This can be found in KeePassXC's Database Settings, Browser Integration tab.

**Comment by Carsten3000** [comment]
Thank you, that fixed it.

Is it right that the plugin is only gets fetched by the foreground database?

Now i get only passwords from Arbeit:
![image](https://user-images.githubusercontent.com/43674046/114307459-06101080-9ae0-11eb-9a49-41906fa4d45d.png)


and now only from Privat:
![image](https://user-images.githubusercontent.com/43674046/114307466-090b0100-9ae0-11eb-8c54-62bcdf092192.png)

**Comment by varjolintu** [comment]
You can enable search from multiple databases in KeePassXC's Browser Integration settings.
