### ISSUE TITLE
Extension stopped working today with the message "Key exchange was not successful."

### ISSUE THREAD

**Issue by Mar0xy** [keepassxreboot/keepassxc-browser#1307]
## Issue
It should just connect without any issue as always
but for some reason it stopped working today and now it won't connect anymore it keeps throwing the same error opening up KeePassXC and that's it. I have already reinstalled the extension and also restarted KeePassXC but that didn't help.

## Expected Behaviour
As explained in the issue it should just connect without any issue.

## Info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Have you checked the Troubleshooting Guide from the wiki? Is it possible that Firefox is replaced with a Snap version?

**Comment by smoebody** [comment]
Same here.

KeePassXC - 2.6.4 (flatpak)
KeePassXC-Browser - 1.7.8.1
Operating system: Fedora 33
Browser: Chromium 89.0.4389.90 (rpm)

Yesterday was working fine, today the error from title.

**Comment by smoebody** [comment]
Here is what I see from `journalctl -xe`:
```
Apr 15 10:05:02 ilng002v98 systemd[70018]: Started app-flatpak-org.keepassxc.KeePassXC-95116.scope.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ A start job for unit UNIT has finished successfully.
░░
░░ The job identifier is 4732.
Apr 15 10:05:02 ilng002v98 kernel: xfs filesystem being remounted at /newroot/var/lib/docker supports timestamps until 2038 (0x7fffffff)
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: QSocketNotifier: Can only be used with threads started with QThread
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0755 instead of 0700
Apr 15 10:05:02 ilng002v98 keepassxc[95125]: Failed to load module "canberra-gtk-module"
Apr 15 10:05:02 ilng002v98 keepassxc[95125]: Failed to load module "pk-gtk-module"
Apr 15 10:05:02 ilng002v98 keepassxc[95125]: Failed to load module "canberra-gtk-module"
Apr 15 10:05:02 ilng002v98 keepassxc[95125]: Failed to load module "pk-gtk-module"
Apr 15 10:05:02 ilng002v98 gnome-shell[72029]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: QLocalSocket::waitForDisconnected() is not allowed in UnconnectedState
Apr 15 10:05:02 ilng002v98 gnome-shell[95125]: Another instance of KeePassXC is already running.
Apr 15 10:05:02 ilng002v98 gnome-shell[72029]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 15 10:05:02 ilng002v98 gnome-shell[72029]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 15 10:05:02 ilng002v98 gnome-shell[72029]: qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
Apr 15 10:05:02 ilng002v98 systemd[70018]: app-flatpak-org.keepassxc.KeePassXC-95116.scope: Succeeded.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░
░░ The unit UNIT has successfully entered the 'dead' state.
```
This message repeats itself over and over.

When i close keepassxc it opens up itself immediately, but the message keeps coming.

**Comment by N0R7H** [comment]
I have the same issue but on Pop!_OS with Brave. On two machines with one day delay, strangely enough.
KeePassXC, Browser and Extension where not updated, but these have been:
> xserver-common:amd64 (2:1.20.9-2ubuntu1.1, 2:1.20.9-2ubuntu1.3),
> xserver-xorg-core:amd64 (2:1.20.9-2ubuntu1.1, 2:1.20.9-2ubuntu1.3),
> xserver-xorg-legacy:amd64 (2:1.20.9-2ubuntu1.1, 2:1.20.9-2ubuntu1.3),
> xserver-xephyr:amd64 (2:1.20.9-2ubuntu1.1, 2:1.20.9-2ubuntu1.3),
> xwayland:amd64 (2:1.20.9-2ubuntu1.1, 2:1.20.9-2ubuntu1.3),
> libhogweed6:amd64 (3.6-2, 3.6-2ubuntu0.1),
> libhogweed6:i386 (3.6-2, 3.6-2ubuntu0.1),
> libnettle8:amd64 (3.6-2, 3.6-2ubuntu0.1),
> libnettle8:i386 (3.6-2, 3.6-2ubuntu0.1)

And the issues started after that.

Here is the output of KeePassXC-Browser's:
KeePassXC - unknown
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 86.0.4240.111

And here is what it should be:
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64 (Pop!_OS 20.10)
Browser: Chrome/Chromium 86.0.4240.111 (Brave Version 1.15.76)

**Comment by Mar0xy** [comment]
> Have you checked the Troubleshooting Guide from the wiki? Is it possible that Firefox is replaced with a Snap version?

No, I have the normal Firefox version and since a lot of other people that use ubuntu have the issue I assume something broke through updsting xserver

**Comment by smoebody** [comment]
I installed the rpm-version of keepassxc and it worked.

**Comment by N0R7H** [comment]
Installing the official PPA-Version instead of the flatpack also did the trick for me.

**Comment by droidmonkey** [comment]
The flatpak is broken currently with the browser extension

**Comment by Mar0xy** [comment]
> The flatpak is broken currently with the browser extension

Why did the flatpak break?

**Comment by droidmonkey** [comment]
Have no idea, we don't manage that distribution, but this isn't the first report of flatpak failing to connect

**Comment by raffaem** [comment]
I have installed keepassxc with `sudo dnf install keepassxc` on Fedora 34 and the addon from the Firefox addon website and I have this error (I am the reporter of #1325 possible duplicate)

**Comment by ianchanning** [comment]
I have this problem with Fedora 34 and a flatpak install of KeepassXC. Only interesting point is that my Firefox browser extension does work, but Chromium and Brave both fail.

**Comment by varjolintu** [comment]
Has Fedora updated the package or does the problem still exist?
