### ISSUE TITLE
Vivaldi Browser Integration Never Succeeds

### ISSUE THREAD

**Issue by tohuw** [keepassxreboot/keepassxc-browser#131]
## Expected Behavior
When selecting the "Vivaldi" browser integration option in KeePassXC on Windows 10 and installing the extension into the browser, integration should function as it does in my Firefox browser on the same system.

## Current Behavior
Instead of the "Connect" button in the dialog, it reads "Reload", with an error message: `Timeout or not connected to KeePassXC`. When I go to settings in the extension and try to connect from the "Connected Databases" tab, nothing happens.

## Steps to Reproduce (for bugs)
1. Open KeePassXC and open a database
2. Tools > Settings > Browser Integration > "Enable KeePassXC browser integration"
3. Same screen, select "Vivaldi" and press OK
4. Install KeePassXC Browser extension in Vivaldi, ensure extension ID is `oboonakemofpalcgghocfoadofidjkkk`
5. Observe `org.keepassxc.keepassxc_browser_vivaldi.json` is created at `AppData\Local\keepassxc`
6. Observe the path to this file is correct in registry entry `[HKEY_CURRENT_USER\Software\Vivaldi\NativeMessagingHosts\org.keepassxc.keepassxc_browser]`
7. Observe `keepassxc-proxy.exe` is not running, but runs as expected when the Firefox extension is used
8. Further observe the launching the proxy application manually does nothing.

## Debug info
No console messages or errors seem to appear.

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Windows 10
Browser: Vivaldi
Proxy used: YES

**Comment by varjolintu** [comment]
Some people have said that Vivaldi has changed to use Chrome preferences, so please try to enable Chrome support from the settings and see what happens. It seems we have to remove the Vivaldi checkbox in the future.

**Comment by tohuw** [comment]
That worked. Please remove the Vivaldi checkbox and perhaps change the Chrome checkbox to read "Google Chrome/Vivaldi".

Incidentally, I found out Vivaldi existed from this very settings dialog, and I'm really liking it. So, thanks for that. :)
