### ISSUE TITLE
Warning! OTP not found

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc-browser#1311]
Can't use OTP on AWS loging page by default. A warning box is displayed.

## Expected Behavior
I should be able to follow complete logging in process: enter user/password on first screen and then fill OTP by clicking on the KeePassXC icon in the OTP field.

## Current Behavior
Currently on the OTP page when clicking on the green icon I receive warning that no OTP was found ("Warning!No se ha encontrado TOTP.").
Surprisingly if I click on the KeePass toolbar icon and select one of the stored credentials (I have two) then clicking on the green icon in OTP field I get the pop-up to select credential that would source OTP.

It seems that afterwards it works just fine (close tab and re-login: each time the OTP selection is offered in the field)

## Possible Solution
The OTP credential selection should work immediately without the need to click on the toolbar icon.

## Steps to Reproduce (for bugs)
1. Go to AWS loging page (https://….signin.aws.amazon.com/console)
2. Enter credentials (username/password) on the first screen
3. click on the green icon in OTP field

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: MacIntel
Browser: Mozilla Firefox 87.0

**Comment by woj-tek** [comment]
I tried to collect some sort of logs but there is nothing in the JS console (dev tools) when clicking on the green button (nor toolbar icon). What's interesting is that toolbar icon has "?" overlay symbol.

**Comment by varjolintu** [comment]
This would need some debugging. I tried to reproduce this yesterday but everything worked just fine. Gotta try it again later.

**Comment by woj-tek** [comment]
OK. I played with it some more:
1) restarting the browser helps to reproduce it
2) it seems to happen when I use firefox password manager in the first step (to select username/password) and then try to use keepass for OTP in the second step. If I use KeePass in the first step to select password then it seems to work for OTP already. (I know that this is probably kinda unusual to still have passwords in Firefox but I just consider it a backup)

**Comment by varjolintu** [comment]
Well, your first actual step is to disable Firefox's password manager and try everything without it. Using multiple password manager extensions simultanously (integrated still counts) is not recommended. I think the whole problem arises because you don't use KeePassXC-Browser to fill yout credentials. The extension doesn't know what you've filled and cannot connect credentials to the correct TOTP before you've choosen them from the extension popup (like you described it in your first message).

**Comment by woj-tek** [comment]
> I think the whole problem arises because you don't use KeePassXC-Browser to fill yout credentials. The extension doesn't know what you've filled and cannot connect credentials to the correct TOTP before you've choosen them from the extension popup (like you described it in your first message).

Well, that seems like the case, but... when it works it still offers a pop-up to select the credentials I want to use so this somewhat contradicts the above.

Let me clarify - when the issue happens:
1) clicking on the green bubble icon does nothing
2) only clicking on the toolbar icon changes nothing
3) clicking on the toolbar icon and selecting one of the credentials from it's pupup causes that clicking on the green bubble icon in the OTP field brings up a dropdown list with credentials to select.
4) in the second pass (when the issue doesn't happen) clicking on the green bubble icon in the OTP field still brings up dropdown selection list with credentials.

Thus, it seems that KeePass doesn't care nor store what's selected in the first login step hence your last sentence seems to not apply here (?).

**Comment by varjolintu** [comment]
And the issue happens when Firefox's password manager is disabled?

**Comment by woj-tek** [comment]
Well, no because we end up in the situation when in first step I use KeePass. I doesn't matter if the Fx is enabled or disabled. The differentiating factor is whether I click/use KeePass in the first step. What's more - if I were to type the user/pass manually in the first step then in the second step I end-up in the same situation.

**Comment by droidmonkey** [comment]
This needs some work because this would also be the case if you stored your totp in a separate entry or database from your main credentials.

**Comment by varjolintu** [comment]
I'll try to reproduce the case and do some improvements.

**Comment by woj-tek** [comment]
I think there are somewhat two issues here:
1) (main one that I run into) KeePass doesn't recognise OTP field/credentials if it wasn't triggered in the session yet (works on re-logins, even if we close all the tabs)
2) KeePass doesn't store selected credentials info from user/pass screen to use them in OTP screen (whatever we do, we are always presented with credential selection dropdown, even if we used KeePass in user/password screen)

**Comment by varjolintu** [comment]
Reminder to myself: we need to make sure filling 2FA from another database with matching credentials still works if some restrictions will be made to the TOTP selection.

**Comment by gbsf** [comment]
I did some debugging, and it seems that the `page_set_login_id` message is not sent if the credentials are auto-filled when the database is opened (as opposed to being selected on the drop-down menu).
Then, in the OTP page, the stored `uuid` might not match, for example if I used the drop-down on another site, returning the `OTP not found` message.

https://github.com/keepassxreboot/keepassxc-browser/blob/2d1401aadac2cee2b8a24007cac1f567584acbbe/keepassxc-browser/content/keepassxc-browser.js#L899-L903

**Comment by varjolintu** [comment]
As I couldn't reproduce all problems described here, I'd suggest you try to load this PR as a temporary extension and see if it fixes your issues as well: https://github.com/keepassxreboot/keepassxc-browser/pull/1350

**Comment by woj-tek** [comment]
@varjolintu I assume I should build that branch as described in https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually#build-extension-into-zip-file-and-load and then load to Firefox (or are there any branch builds available)?

**Comment by varjolintu** [comment]
@woj-tek No need to build anything. You can just clone the branch (or unzip it) and just load it as a Temporary Extension. We like to keep things simple.

**Comment by woj-tek** [comment]
OK, tested it and still the same issue.

**Comment by varjolintu** [comment]
@woj-tek Are you able to debug the TOTP filling situation from content script because I still cannot reproduce your problem?

**Comment by woj-tek** [comment]
I tried to do that (even though JavaScript and Fx extensions are not my forte) and I placed a breakpoint in `keepass.getTotp = async function(tab, args = [])` (from the extension sources that I got from `about:debugging`, "KeePassXC-Browser/background/keepas.js") and it seems it's never executed (once on the screen with TOTP field and clicking green TOTP bubble from KPXC). Interestingly enough, at the end of that method there is a secion:
```js
    } catch (err) {
        console.log('getTotp failed: ', err);
    }
```

and I don't see it logged anywhere (neither JS console in extension sources nor in the devtools of the tab with TOTP field).

Any hint, even broad, where to look would be appreciated :-)

**Comment by varjolintu** [comment]
@woj-tek A good place to start is `content/keepassxc-browser.js:960`. That's the first line inside `kpxc.fillFromTOTP()`.

**Comment by varjolintu** [comment]
> So I just made a discovery that fix the issue - one has to select credentials from KeePassXC dropdown (so ignore/delete Firefox one) and then TOTP works perfectly and can select if just fine in the next step (though KPXC could remember which credentials I used and use it to fill out TOTP automatically)

The extension should already do that. Plus I have a issue in my TODO list that the TOTP is retrieved automatically in these kind of situations without the need of selecting it manually.
