### ISSUE TITLE
ally.com drop down menu selection does not get assigned.

### ISSUE THREAD

**Issue by famewolf** [keepassxreboot/keepassxc-browser#1314]
## Overview
ally.com's main login page (go to the main page and click login) has a dropdown menu that wants you to select "Bank of Invest Login" or "Auto Financing".  I have read the section on adding fields.  I have added string keepassxreboot/keepassxc#1 inside the browser plugin as an additional field.  I have gone into the entry for ally.com in the database and under advanced added an entry under "additional attributes" with a field name of "KPH: login_type" and tried both 0 and 1 to get it to select an entry.  I've even gone into the html and found the element name of "allysf-login-v1-account" which assigns a value of "aob" if the entry I want is selected.  I've tried setting that.  I've changed the field name in various ways including adding and removing KPH: and renaming the field the element name.   How exactly is this supposed to work?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to Ally.com
2. Click Login
3. Make sure dropdown menu is showing "Bank or Invest Login"

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I fill the screen in addition to user and password it should select the Bank or Invest Login choice.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After changing the selection to show the auto finance selection I filled the page.  User and Pass populated as expected but nothing I did would get the menu to pick "Bank or Invest Login".

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Manjaro Linux 20.1
Desktop Env: KDE
Browser: iridium (chromium based)

**Comment by varjolintu** [comment]
Using `KPH: login_type` for attribute name is just fine, but for the value you need an actual `<option>` value for it, meaning the actual content. So if I'd like to choose the "aaos" here, I need to put ` Auto Financing` as the attribute value. And please notice there's space included at the beginning.
