### ISSUE TITLE
Firefox v88.0 login doesn't work on https://okcupid.com, did in prior versions of FF

### ISSUE THREAD

**Issue by craigarno** [keepassxreboot/keepassxc-browser#1315]
## Expected Behavior
Prior to Firefox v88 upgrade KeepassXC was able to provide login credentials for https://www.okcupid.com .
Prior to v88 I was able to select sign-in credentials from the drop-down list and login.

## Current Behavior
Username and Password won't fill from the drop down list of ID's using mouse click.
Username and Password can be filled using keyboard arrow and enter keys

## Possible Solution
It appears the mouse actions are no longer recognized in FFv88

## Steps to Reproduce (for bugs)
1. https://www.okcupid.com 
2. setup Keepassxc entry to allow login to https://www.okcupid.com (I have 3 entries for different logins, don't know if this is relevant)
3. Select "Sign-In" button on page, top right
4. Click on credentials using mouse, notice nothing happens
5. Try pressing the Enter Key and notice email and password fields fill as expected/desired from credential list

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Win64  (Windows 10 Professional)
Browser: Mozilla Firefox 88.0

**Comment by varjolintu** [comment]
This has nothing to do with the extension. The page's own scripts intercept mouse click and mouse focus stuff. You can still fill your credentials normally using the extension popup from the toolbar icon.
