### ISSUE TITLE
Randomly get "Warning! No saved custom login fields found" message

### ISSUE THREAD

**Issue by jakeparis** [keepassxreboot/keepassxc-browser#1316]
At unusual (randomish) times, a yellow message box pops up saying:
<img width="629" alt="Screen Shot 2021-04-28 at 9 04 20 AM" src="https://user-images.githubusercontent.com/7408985/116409086-7ec1dd00-a801-11eb-9832-99edbba3c33f.png">

I have not interacted with the extension at all, nor are there any login forms on the page I'm on. The _site_ does have an entry in KeePass, but I'm not on the login page. 

If I _do_ click on the extension icon, it tells me there are no saved credentials for the current site (which is correct).

## Expected Behavior
KeePass will be quiet until needed. ;)

## Current Behavior
Pops up the confusing box

## Steps to Reproduce (for bugs)
This is not the only time it pops up, but here's one way:
1. Login to a wordpress site, for which I have multiple usernames stored
2. Navigate to the pages index page, e.g. `/wp-admin/edit.php?post_type=page`
3. Random message pops up.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Mac
Browser: Vivaldi

**Comment by alicroche** [comment]
Same thing here with exact same configuration (mac Intel (Catalina), Vivaldi 3.7, KeePassXC 2.6.4, KP-Browser 1.7.8.1).
The unwanted popup seems to occur with websites that fancy unusual login procedure, i.e. login through 2 different pages, visual keyboard to enter PIN etc…

**Comment by kosta880** [comment]
I am too getting this, reproducible, on OPNsense Firewall, when I browse certain pages, like Services -> DHCPv4 -> any network.
Also there are no login fields there.

**Comment by N-Upchurch** [comment]
I am having this issue currently. Is there any way to disable the banner?

**Comment by varjolintu** [comment]
Disable notifications from the settings.

**Comment by RexTC** [comment]
This is actually a saved "modified credentials" cause issue.
Go to your keepassXC extention preferences and remove the setting in "Site preferences"

**Comment by Grief** [comment]
I have a site in a corporate network which is created as a single page React application with the menu with the login fields in the outer iframe and the app content in the inner iframe. Extension doesn't find the fields automatically, so I had to specify them manually. When I do that, two forms appear, for the outer and for the inner iframes. When I complete reassignment of the fields for the outer iframe, I click 'cancel' in the inner iframe (because it doesn't contain any login fields at all) and it causes the warning 'no saved custom fields found' to appear every time the inner iframe reloads

**Comment by varjolintu** [comment]
@Grief I suggest re-testing this with the current develop branch. That iframe bug has been fixed.

**Comment by Grief** [comment]
@RexTC I am trying to test that with the version from develop branch, but for some reason it doesn't connect to the db: "key exchange failed'

**Comment by Grief** [comment]
@RexTC My bad, you were right, the bug I was talking about is fixed on develop branch. The only issue I have (those I've mentioned before a caused my mistakes during the installation) is that this blue button doesn't work at all:
![image](https://user-images.githubusercontent.com/7239315/175039798-05b73f8b-bc4a-4640-a322-bb407e51d68f.png)
I suppose the yellow one is a replacement for it.

**Comment by varjolintu** [comment]
@Grief The yellow one is the old Choose Custom Login Fields button. Redecting the credentials might not yet work on iframes properly.
