### ISSUE TITLE
Key Exchange was not successful -Close/Re-open Chrome 

### ISSUE THREAD

**Issue by patrickfixedit** [keepassxreboot/keepassxc-browser#1318]
## Current Behavior

Several times per day I notice the browser extension has lost connection. The only way to reconnect it is to close Google Chrome and reopen.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Windows 10
Browser: Chrome

**Comment by varjolintu** [comment]
Please monitor if `keepassxc-proxy.exe` is running when the disconnect happens. There are some reports that certain anti-virus software can interfere with the proxy process.

**Comment by patrickfixedit** [comment]
It happened just now. Checked taskman and keepassxc-proxy.exe is running but I'm unable to get it to talk to keepassxc:
"key exchange was not successful"

**Comment by varjolintu** [comment]
Does it have any effect if you close your database and reopen it, or switch to another database?

**Comment by patrickfixedit** [comment]
I have tried closing keepassxc and reopening it but that doesn't reconnect it. I have only one database.

**Comment by varjolintu** [comment]
Does the extension's background script has any errors in the log? You can inspect it from `chrome://extensions`.

**Comment by patrickfixedit** [comment]
Checked chrome://extensions but do not see any log files or logging options

**Comment by varjolintu** [comment]
You'll have to enable the Developer Mode first from that extension page. Then you should see a "Background page" link inside the extension card.

**Comment by patrickfixedit** [comment]
OK I've been waiting for it to error again, it just happened again. Here is what I got in the extension log:

keepass.js:1059 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:638 Server public key: cF8XgU3RynKdF6M1PO0YC7d/H6i7Qc1FNj6Eqnm49mM=
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
keepass.js:1029 Failed to connect: Error when communicating with the native messaging host.
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
page.js:201 Cannot send activated_tab message:  Object
keepass.js:1142 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:1059 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1142 Error 9: Key exchange was not successful.
page.js:201 Cannot send activated_tab message:  Object

**Comment by varjolintu** [comment]
Check the https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide and report if there's still problems.
