### ISSUE TITLE
Detection of login fields not working on greenpeace-energy.de

### ISSUE THREAD

**Issue by chrthi** [keepassxreboot/keepassxc-browser#1319]
On https://mein.greenpeace-energy.de/ keepassxc-browser fails to detect the login and password fields. Even when trying "Choose custom login fields", the fields aren't offered for selection.

## Expected Behavior
The KeePassXC icon appears in the "E-Mail" field.
Username and password are filled in when clicked.

## Current Behavior
The KeePassXC icon is not shown in any field.
Choosing "Fill Username and Password" from the context menu of either field does nothing.
Clicking the KeePassXC-Browser button in the browser's menu bar and choosing "Choose custom login fields" greys out the entire page; no fields are offered for selection.
On other pages KeePassXC works normally.

## Possible Solution
I suspect that the algorithm for detecting login fields doesn't work with this specific kind of SPA and could be extended.

## Steps to Reproduce (for bugs)
1. Prepare a KeePassXC with an opened database and working KeePassXC-Browser integration
2. Add an entry (made up, if needed) for https://mein.greenpeace-energy.de/
3. Visit the page

## Debug info
No messages in the the browser's JavaScript console.
KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.4
Operating system: Linux x86_64
Browser: Chrome/Chromium 90.0.4430.93

**Comment by varjolintu** [comment]
Those login fields are inside a Shadow Root DOM which we support only partially.

**Comment by varjolintu** [comment]
Now tracked in #1358.
