### ISSUE TITLE
Firefox extension thinks password change every time

### ISSUE THREAD

**Issue by kAlvaro** [keepassxreboot/keepassxc-browser#1323]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

The Firefox extensions displays a **Username or password changed! Save it?** prompt every time you log into a site. Choosing **Update** generates duplicate entries.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Log into a site.
2. In the _Username or password changed! Save it?_ prompt click "New".
3. Sign off.
4. Sign in again with previous credentials.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

No banner is displayed because neither user nor password have changed.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

_Username or password changed! Save it?_ displays. If you click "New" you get a duplicate entry.

## Context
[NOTE]: # ( Give us any additional information you may have. )

If it matters, I haven't disabled Firefox password manager yet. The extension doesn't report any error and passwords are stored normally. I've removed the _KeePassXC-Browser Passwords_ group to start over and tried different settings.

I followed the [trouble-shooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and all looks good, but the console tab displays this message:

> Cannot send activated_tab message:  Error: Could not establish connection. Receiving end does not exist.
switchTab moz-extension://1fa91b22-775f-46e8-8ea1-6805cdaab6c0/background/page.js:200

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19042

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
- libgcrypt 1.9.1-unknown

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
Is there any difference if Save Domain Only is enabled/disabled?

**Comment by kAlvaro** [comment]
No, there isn't.

**Comment by varjolintu** [comment]
Can you give me an example of a site where this happens? I can try to reproduce it. Or does it happen with every site? If so, that's very strange.

**Comment by raffaem** [comment]
I also experienced this bug when running Ubuntu 20.10

**Comment by kAlvaro** [comment]
I don't have many accounts yet but I'd say it happens everywhere. I've just reproduced it in https://gitlab.com/.

![Duplicate GitLab accounts](https://user-images.githubusercontent.com/1327350/117249715-5d38a500-ae42-11eb-98df-a1f919104f94.png)

It's indeed strange. I can't conceive it's broken for everyone but I can't figure out what's different in my computer.

**Comment by varjolintu** [comment]
I created a test account for Gitlab but couldn't reproduce the issue. This would need debugging from your side to see why the banner triggers and fails to identify that you already have identical account in your database.

**Comment by kAlvaro** [comment]
Is there some logging I can enable/inspect? At `about:devtools-toolbox?id=keepassxc-browser%40keepassxc.org&type=extension` I only see the _Cannot send activated_tab message_ entries I mentioned but they don't seem to be triggered by sign in process.

**Comment by varjolintu** [comment]
Open the Web Developer Tools in the login page and check (for example) this breakpoint from the content script:
<img width="1693" alt="Screenshot 2021-05-06 at 16 43 38" src="https://user-images.githubusercontent.com/24570482/117308932-a3b1f200-ae8a-11eb-8ac2-66f161527d49.png">

**Comment by kAlvaro** [comment]
I don't have any **KeePassXC-Browser** entry among GibLab assets and the one in about:devtools-toolbox has different code and structure. Is it possible that I reported to the wrong repository? I'm using [this extension](https://addons.mozilla.org/en-GB/firefox/addon/keepassxc-browser) linked from [keepassxc.org](https://keepassxc.org/) :-?

**Comment by varjolintu** [comment]
Different structure? What do you mean? That is the correct extension.

**Comment by kAlvaro** [comment]
Please bear with me since I'm not familiar with Firefox extension development but:
* When I open developer tools in e.g. GitLab I cannot see the **KeePassXC-Browser** folder you have in your screenshot.
* When I open `about:devtools-toolbox?id=keepassxc-browser%40keepassxc.org&type=extension` and go to **KeePassXC-Browser**, I don't get **common** and **content** as you do but **background** and **common**; none have a **keepassxc-browser.js** file.

I surely omitted one step but I don't know which.

**Comment by varjolintu** [comment]
Make sure to select the _Debugger_ tab in the Developer Tools.

**Comment by kAlvaro** [comment]
Since the extension wasn't showing up in the debugger, I've tried editing the extension source code to add `console.log()` calls and replacing the XPI file on my profile. The source code does contain the file you mentioned. Unfortunately, Firefox seems to verify the signature. I'm not a Firefox extension developer and I can't get past this :(

![image](https://user-images.githubusercontent.com/1327350/119337868-99b42f80-bc8f-11eb-9234-f8165f12a07f.png)

**Comment by varjolintu** [comment]
I really have no idea why the extension would not appear in the debugger. It should show every extension you use.

**Comment by kAlvaro** [comment]
I found out: I need to select "Enable browser chrome and add-on debugging toolboxes" in dev tools settings. I'll report back when I collect some diagnostic information.

**Comment by z1atk0** [comment]
> Can you give me an example of a site where this happens? I can try to reproduce it. Or does it happen with every site? If so, that's very strange.

For me, this always used to happen on the Nintendo eStore (login URL `https://accounts.nintendo.com/*`). I had to add "Disable new/modified credentials" for this URL in site preferences to make it stop. Didn't happen anywhere else for me, though, so I'm not sure it's actually related to @kAlvaro's problem.

**Comment by varjolintu** [comment]
@z1atk0 I tried to reproduce the problem with Nintendo's site but everything worked normally.

**Comment by z1atk0** [comment]
Hm, maybe it's because I have more than one account stored in KeepassXC (my own, my wife's and my daughter's)? Sorry, forgot to mention that ... :man_shrugging: :innocent:

**Comment by varjolintu** [comment]
#1782 improves this a bit. Let's reopen the ticket if the problem still occurs.
