### ISSUE TITLE
Filling login form doesn't work on "workflowy.com"

### ISSUE THREAD

**Issue by broot5** [keepassxreboot/keepassxc-browser#1324]
## Expected Behavior

It needs to be logged in to [workflowy.com](https://workflowy.com/)

## Current Behavior

When I try logging in to [workflowy.com](https://workflowy.com/), KeePassXC-browser doesn't work.

## Possible Solution

It seems to be because "workflowy.com" is a site with user names only in the login form.

I think that adding `https://workflowy.com/login` to [/keepassxc-browser/common/sites.js](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/common/sites.js) will solve this problem.

## Steps to Reproduce (for bugs)

1. Go to [https://workflowy.com/login/](https://workflowy.com/login/)
2. Try logging in via KeepassXC-browser

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: All
Browser: All

**Comment by varjolintu** [comment]
Add the URL to extension's Site Preferences tab in the settings and enable "Username-only Detection" for it.
