### ISSUE TITLE
Addon doesn't connect with Fedora 34 / GNOME 40

### ISSUE THREAD

**Issue by raffaem** [keepassxreboot/keepassxc-browser#1325]
## Expected Behavior
The Firefox addon should connect to the application

## Current Behavior
The addon displays "Key exchange was not successful." also when KeePassXC is open and unlocked

## Steps to Reproduce (for bugs)
1. Install the Firefox addon
2. Install KeePassXC (I used `dnf install keepassxc` on Fedora 34)
3. The addon is unable to connect to the application
4.

## Debug info

KeePassXC

KeePassXC - Version 2.6.4
Revision: 34a78f0

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora 34 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.11.17-300.fc34.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.3-unknown

KeePassXC-Browser - 1.7.8.1
Operating system: Fedora 34 Workstation
Browser: Firefox 88

**Comment by varjolintu** [comment]
Possible duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1307

**Comment by raffaem** [comment]
It's working now
