### ISSUE TITLE
Chase.com Fill Credentials Error 

### ISSUE THREAD

**Issue by Jimmy-Py** [keepassxreboot/keepassxc-browser#1326]
When I visit chase.com and click the little KeePassXC icon (from the firefox extension) that appears in the username field, it does not work. I have the credentials for chase.com stored in my database, associated with the URL. All my other accounts on other websites function fine. Any tips?

**Comment by varjolintu** [comment]
Please check that your entry URL is `https://chase.com`.

**Comment by normanr** [comment]
They use multiple login servers, so you have to list them all: https://secure01a.chase.com/ https://secure01b.chase.com/ https://secure01c.chase.com/ https://secure03a.chase.com/ https://secure03b.chase.com/ https://secure03c.chase.com/ https://secure05a.chase.com/ https://secure05b.chase.com/ https://secure05c.chase.com/ https://secure07a.chase.com/ https://secure07b.chase.com/ https://secure07c.chase.com/

**Comment by droidmonkey** [comment]
Just put in https://chase.com to cover all the subdomains

**Comment by Jimmy-Py** [comment]
> Just put in https://chase.com to cover all the subdomains

https://www.chase.com/ is the one stored in that entry's URL field.

**Comment by varjolintu** [comment]
@Jimmy-Py That's not the URL of the login page.

**Comment by Jimmy-Py** [comment]
> @Jimmy-Py That's not the URL of the login page.

Wow, changing the database's URL to https://chase.com from https://www.chase.com/ did the trick. Thanks!  

Also, is there a basic explanation as to why this makes such a profound difference?

**Comment by droidmonkey** [comment]
www is a defined subdomain. We added a condition to treat www as no subdomain, but I think that is on develop branch. @varjolintu ?

**Comment by varjolintu** [comment]
@droidmonkey I think we should do that.

**Comment by Jimmy-Py** [comment]
@droidmonkey What is the signifcance of subdomain in KeePassXC? I didn't find any mention of it in the "`[Getting Started](https://keepassxc.org/docs/KeePassXC_GettingStarted.html)`" doc.

**Comment by droidmonkey** [comment]
Matching occurs at the defined subdomain and below. Matching looks like "*www.domain.com" or "*domain.com" where the * matches anything.
