### ISSUE TITLE
Apple AppStoreConnect login does not work

### ISSUE THREAD

**Issue by rocketraman** [keepassxreboot/keepassxc-browser#1327]
## Expected Behavior

I would expect my login on https://appstoreconnect.apple.com/login to work. It does not -- the plugin is unable to find a password field, even though it does match the correct password entries in keepassxc.

## Current Behavior

Sometimes this comes up, though not always:

"Warning! Error: Unable to find a password field"

## Steps to Reproduce (for bugs)
1. Create a password entry for https://appstoreconnect.apple.com/login
2. Attempt to login

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
You can use the fill from context menu as a workaround.

**Comment by rocketraman** [comment]
> You can use the fill from context menu as a workaround.

Actually I should have specified in the OP -- that doesn't work on this site either.

**Comment by rocketraman** [comment]
Thank you -- it looks like my URL was too specific -- I had `https://appstoreconnect.apple.com` because I didn't realize the login box is in an iframe, as you noted to `﻿﻿﻿https://idmsa.apple.com`. Next time I'll use dev tools to check that.

Will the browser plugin be updated to handle these types of cases automatically?

**Comment by varjolintu** [comment]
There's a feature that allows doing exception for certain pages. Gotta inspect if that is possible in this case.

**Comment by rocketraman** [comment]
> There's a feature that allows doing exception for certain pages. Gotta inspect if that is possible in this case.

The "custom login fields"? If that's what you mean, that didn't work in this case with the non-matching iframe URL.

**Comment by varjolintu** [comment]
@rocketraman No, it's an internal feature. It must be added to the code itself.

**Comment by varjolintu** [comment]
This is already fixed.
