### ISSUE TITLE
Many instances of keepassxc-proxy.exe running 

### ISSUE THREAD

**Issue by mbtools** [keepassxreboot/keepassxc-browser#1330]
After some time away from my PC with Chrome + KeepassXC extension open, I find that many (dozens) instances of cmd.exe/conhost.exe/keepassxc-proxy.exe are running. This uses up a lot of memory and slows down the PC.

I would expect that one instance connecting to the main KeepassXC.exe is sufficient. Is this because of my environment/settings or a new issue? What additional infos shall I provide to help resolve this?

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Win64
Browser: Chrome/Chromium 90.0.4430.212

**Comment by varjolintu** [comment]
Are you using Automatic Reconnect? If so, disable it.

**Comment by mbtools** [comment]
yes, it was on. thank you.
