### ISSUE TITLE
Memory leak when KeePassXC is not already opened

### ISSUE THREAD

**Issue by 66mike** [keepassxreboot/keepassxc-browser#1333]
## Expected Behavior

Browser operates as if I was not using the plugin

## Current Behavior

After around 10-15 seconds, the browser crashes and my computer explodes.

## Possible Solution

After looking at the task manager, it appears the extension is continually constructing multiple instances of "keepassxc-proxy.exe" in an attempt to successfully connect to KeePassXC. Simply closing these upon a failed connection or turning off the loop behavior would be sufficient.

## Steps to Reproduce (for bugs)

1. If KeePassXC is on, close it.
2. Open your browser of choice.
3. Wait 10 - 15 seconds.
4. Start a GoFundMe for hospital bills, because you now have computer shrapnel in your thigh.

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Win
Browser: Brave (Chromium)

**Comment by varjolintu** [comment]
Disable the automatic reconnect.
