### ISSUE TITLE
[bug] The extension doesn't ask to save a password on litres.ru

### ISSUE THREAD

**Issue by LightTemplar** [keepassxreboot/keepassxc-browser#1334]
The extension doesn't ask to save credentials on https://www.litres.ru/pages/login/
It also doesn't recognize fields, I had to choose custom. And after I filled them and logged in, the banner suggesting saving credentials doesn't show up at all. I used the login button, not "enter". 

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 88.0

**Comment by varjolintu** [comment]
The reason those field are not identified and/or handled is that those are inside an iframe and using host `connect.mail.ru`. Browser's content script don't have access to sites from other domains, so there's nothing that can be done. You can use Auto-Type instead.
