### ISSUE TITLE
Autofill not working

### ISSUE THREAD

**Issue by edrngrc** [keepassxreboot/keepassxc-browser#1336]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. 
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
When I click the autofill button it is not working on every sites

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC -  2.6.4
Revision: 34a78f0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
If you encounter a site where you have a problem with this, please check:
- Is the extension icon showing a question mark? If so, credentials for the site are identified.
- What is the URL of your entry? Does it actually match the page URL?
- Check if the login fields are inside an iframe. The URL might differ from your entry URL.

**Comment by Warmuser** [comment]
The same to me, also after I selected the Nickname and Password spaces with the custom method offered by the extension. 
Some examples:

[1](https://forum.tomshw.it/login/)
[2](https://www.hwupgrade.it/forum/index.php)

**Comment by varjolintu** [comment]
@Warmuser Both of those sites work normally for me with Autofill.

**Comment by raspher** [comment]
sometimes when i click on account in accounts list, it's not filling. 2nd click on item in list, it's working... never mind...

it would be nice to keep track of last used account, or sort them alphabetically (i'm using 50+ account on one website, business specific example). This scenario su*ks

Chrome 93.0.4577.82 on windows

![image](https://user-images.githubusercontent.com/23345803/134824650-929b1ad3-da76-47d5-9218-f3a81e7616b7.png)

**Comment by raspher** [comment]
Nice support... Why u ignore that fact?

> sometimes when i click on account in accounts list, it's not filling. 2nd click on item in list, it's working...

**Comment by droidmonkey** [comment]
If you have a unique issue make a new issue. This one is devoid of useful information.
