### ISSUE TITLE
URLs start with file:/// should be ignored

### ISSUE THREAD

**Issue by duongdominhchau** [keepassxreboot/keepassxc-browser#1337]
When I login while viewing a local file, the extension prompts for saving password. If I choose never ask again, the extension breaks **for all sites** because URLs starting with `file:///` is unexpected, the label in **Settings** page explicitly says `The URL must start with either https://, http://, or ftp://`, but this URL doesn't get into the settings through that box so there is no check.

About the case after that URL got into the settings, the extension will fails with an exception, like this:
`initContentScript error:  TypeError: "file:///THE_PATH/*" does not have a valid host`. This exception prevents the extension from providing autocompletion.

## Expected Behavior

No prompt displayed when browsing local files.

## Current Behavior

A prompt for saving password is displayed when submit form even when browsing local files.

## Possible Solution

Just check `window.location` and cancel the display if the location starts with `file:///`

## Steps to Reproduce (for bugs)

Open this form in Firefox

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
    <form>
        <input id="username" type="text">
        <input id="password" type="password">
        <input type="submit">
    </form>
</body>
</html>
```

Enter something for both fields and submit. The prompt (https://i.imgur.com/DRQmjQh.png) will be shown.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: ArchLinux
Browser: Firefox

**Comment by varjolintu** [comment]
Check https://github.com/keepassxreboot/keepassxc-browser/pull/1317
