### ISSUE TITLE
Problems connecting to KeepassXC when running Browser as a different user.

### ISSUE THREAD

**Issue by tzugen** [keepassxreboot/keepassxc-browser#1339]
For various reasons I have my browsers running inside a non-priviledged user. 
When I log in as this user, the connection between Firefox and Keepass works fine.
If I start both inside my default account, using `sudo -u browser-user firefox` and `sudo -u browser-user keepassxc` then I can't get them to connect.

Top shows that the proxy is running.
The Firefox developer console shows this:
```
keepass.js:1262:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Error: No content script available for this tab. keepass.js:1262:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1059:13
Error: No content script available for this tab. keepass.js:1262:25

```

Do you have an idea how I could get this working?

**Comment by varjolintu** [comment]
Use `strace` to figure out where Firefox is trying to load the Native Messaging manifest file.
