### ISSUE TITLE
Ubuntu Firefox extension process keeps 100% CPU

### ISSUE THREAD

**Issue by miro-janosik** [keepassxreboot/keepassxc-browser#1343]
One process that says it is '/usr/lib/firefox/firefox -contentproc -childID ....'  starts using 100% CPU and does it forever. It happens to me once a day.

## Expected Behavior
CPU usage should be low when PC is idle.

## Current Behavior
I can't tell how, when or why; I do only know that it happens only when browser extension is enabled. 
I could not find anything in Firefox profiling, so I did narrow things down by disabling Firefox extensions, and it happens only when this one is enabled.
It does not happen if I enable the extension; use it to fill in the credentials; and then disable it again.

## Possible Solution
Is there a better way how to track down why is it doing it, so that I can provide more information?

## Steps to Reproduce (for bugs)
Don't know, as I don't see it would start after some specific action.

## Debug info

No JS console errors right now, I have to enable extension and wait for it to happen again.
"Automatically reconnect to KeePassXC" - is disabled in browser extension

KeePassXC - 2.6.1
KeePassXC-Browser - 1.6.6
Operating system: Linux ubuntu 20.10
Browser: Firefox 88.0.1

**Comment by varjolintu** [comment]
Are you using KeePassXC as a flatpak or something similar? The version is not the latest it seems.

**Comment by miro-janosik** [comment]
So I have the condition again. I am looking into browser JS console and see no errors.

Installed from system repositories where it served me 2.6.1 for Ubuntu 20.10
I see that if I would move my OS version then it could offer 2.6.2: https://packages.ubuntu.com/source/keepassxc

**Comment by varjolintu** [comment]
Use the official PPA: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by miro-janosik** [comment]
Using the mentioned PPA, updated to:
KeePassXC - 2.6.5
KeePassXC-Browser - 1.6.6 (not latest, I am not sure how did I get that as it was not installed via browser extension)
retesting.

**Comment by miro-janosik** [comment]
After testing bug does not appear anymore. Closing.

**Comment by miro-janosik** [comment]
Bug appears, less frequent but it still does.
If I kill the Firefox process taking 100% CPU and then I try to use browser plugin it can't connect to the database.

**Comment by droidmonkey** [comment]
Your extension version is wildly out of date. Make sure you installed the official keepassxc extension from the addin store.
 https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

Without a stack trace or perf report we won't be debugging this. You also need to be on the latest version and make sure you aren't using a beta version of the browser. Narrowing down what/when/where the course utilization starts is also essential. 

Closing this until that information can be provided.

**Comment by miro-janosik** [comment]
Agreed, so the version installable from Ubuntu repositories is outdated. Removed and replaced with suggested 1.7.8.1 ... retesting.

**Comment by miro-janosik** [comment]
Retesting for 3-4 days shows that bug does not appear anymore. Can remain closed. 
Thank you for advices.
