### ISSUE TITLE
KeepassXC-Browser offering to save passwords but can't click any buttons in popup bar

### ISSUE THREAD

**Issue by sovamind** [keepassxreboot/keepassxc-browser#1344]
## Expected Behavior
In the past KeepassXC-browser would properly prompt to save or update a password.  It would provide the notice bar at the top of the page where you could click "new", "update", or dismiss.  Choosing these options would allow a site to be saved or updated to the Keepass database that was currently selected in Keepass.

## Current Behavior
For the last few weeks, we have multiple users reporting they can no longer click on any of the buttons in the password save/update bar.  It acts like it never receives the clicks on any of the buttons.

## Possible Solution
Not sure, we have already tried uninstalling and reinstalling the extension.  Continues to happen but occasionally will start working again, then suddenly stop again.

## Steps to Reproduce (for bugs)
1.  Install KeepassXC-browswer in Microsoft Edge
2.  Connect to a keepass instance/db
3.  Login to a new website
4.  When save/update bar appears at the top, try and click on any of the buttons, which won't work.

## Debug info
KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8
Operating system: Win64
Browser: Microsoft Edge 91.0.864.41

KeepassXC-browser settings:
{"autoCompleteUsernames":true,"autoFillAndSend":false,"autoFillSingleEntry":false,"autoReconnect":true,"autoRetrieveCredentials":true,"autoSubmit":false,"checkUpdateKeePassXC":7,"clearCredentialsTimeout":30,"colorTheme":"system","credentialSorting":"sortByGroupAndTitle","defaultGroup":"","defaultGroupAlwaysAsk":true,"redirectAllowance":4,"saveDomainOnly":true,"saveDomainOnlyNewCreds":true,"showGroupNameInAutocomplete":true,"showLoginFormIcon":true,"showLoginNotifications":true,"showNotifications":true,"showOTPIcon":true,"sitePreferences":

**Comment by varjolintu** [comment]
It would help to see if there's any errors in the Web Developer Console when trying the click the buttons.

**Comment by rpushd** [comment]
This has happened to me countless times on different sites, the latest one being https://prime.stably.io/.
It seems to happen more when there is a secondary redirect to a 2FA screen, though I'm not sure if it's actually related.

**Comment by MuadDibIII** [comment]
It happens to me with Firefox esr, on Debian

**Comment by FinixFighter** [comment]
I also use Firefox on Mint 20.3, but I have not much time for clicking, because I only have a couple of seconds for clicking, then the pop up closes itself. I think it should remain there until we do something (save, update or simply close it).

**Comment by varjolintu** [comment]
@FinixFighter You can set it from the options that it never closes (Number of allowed redirects).

**Comment by FinixFighter** [comment]
> @FinixFighter You can set it from the options that it never closes (Number of allowed redirects).

I didn't know that, thank you so much! Sorry for bothering with this.

**Comment by varjolintu** [comment]
I think this is already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1667
