### ISSUE TITLE
KeepassXC on ubuntu

### ISSUE THREAD

**Issue by GitRolf1** [keepassxreboot/keepassxc-browser#1345]
## Expected Behavior

I'm using
KeePassXC - 2.4.3
but the settings in the firefox browser show, that the newest version is 2.6.4. 
The command "sudo apt install keepassxc" did not help to install the newest version. 

Please help
Best regards
Rolf

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 89.0

**Comment by varjolintu** [comment]
The extension gets the latest KeePassXC version from GitHub. 2.6.6 is coming soon and it's not updated yet to the repositories.
