### ISSUE TITLE
Login fields on smartbroker.de not recognized

### ISSUE THREAD

**Issue by funnym0nk3y** [keepassxreboot/keepassxc-browser#1346]
## Expected Behavior

I expect the browser extension to recognize the login fields on smartbroker.de.

## Current Behavior

Not recognizing the fields.

## Debug info

KeePassXC - latest
KeePassXC-Browser - latest
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/1116
