### ISSUE TITLE
No password entry found for Jitsi Meet

### ISSUE THREAD

**Issue by cnmicha** [keepassxreboot/keepassxc-browser#1347]
## Expected Behavior

I expect the browser extension to find the password entry of a Jitsi Meet instance by its URL.

## Current Behavior

No password entry seems to be detected for the website, although the URL is correctly set:

![image](https://user-images.githubusercontent.com/10116544/121789659-ef696100-cbd7-11eb-80d0-d974f70cd97a.png)

Settings of the password entry in KeePassXC:

![image](https://user-images.githubusercontent.com/10116544/121789700-4e2eda80-cbd8-11eb-9356-fba18bd2ee9e.png)

On other websites, everything is working fine.

## Possible Solution

The issue does not exist using the [keeweb-connect](https://github.com/keeweb/keeweb-connect) browser extension.

## Steps to Reproduce (for bugs)

1. Open the website of a Jitsi Meet instance that requires users to authenticate using the built-in login mechanism. If you contact me via email, I can provide a demo instance to you.
2. Create a new meeting
3. The message "The conference ... has not yet started. If you are the host then please authenticate" appears.
4. Click "I am the host"
5. The following login window appears:

![image](https://user-images.githubusercontent.com/10116544/121789458-70bff400-cbd6-11eb-8388-9a44ad305d18.png)

## Debug info

KeePassXC - 2.6.4
KeePassXC-Browser - 1.7.8.1
Operating system: Linux
Browser: Brave

**Comment by varjolintu** [comment]
Did you try to add the Username-only options for the site as the popup suggested? Does filling through context menu work?

**Comment by cnmicha** [comment]
Without adding the username-only option, a click onto "Fill Username and Password" in the context menu only fills the username field. Then, clicking into the password field and using the context menu option "Fill password only",  both fields are filled correctly.

Clicking "Add username-only option for this site" leads to the credential entry now appearing in the toolbar popup:

![image](https://user-images.githubusercontent.com/10116544/121805614-34c77600-cc4c-11eb-9a93-88bc7d40c363.png)

Clicking onto the found credential entry, none of the input fields is filled. The toolbar popup just closes (as it does on other websites where the credentials are filled correctly).

**Comment by varjolintu** [comment]
A demo instance would be nice so I could test a proper fix.

**Comment by varjolintu** [comment]
Thanks for the demo instance. I managed to fix the bug quickly :)
