### ISSUE TITLE
SourceMap warning in Firefox for browser-polyfill.min.js

### ISSUE THREAD

**Issue by jaller94** [keepassxreboot/keepassxc-browser#135]
Firefox shows me a warning for a missing source map.

![Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://e23c43c8-3d07-4e32-a91b-f0dc82afaa0e/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map](https://user-images.githubusercontent.com/10872136/39669780-719ea628-50aa-11e8-9822-91d8df388fee.png)

Can the invalid link to a source map be removed in the production build?

https://github.com/keepassxreboot/keepassxc-browser/blob/7d631b5f9476c14f33f5ef9ab0c6c5b20d52e2b6/keepassxc-browser/browser-polyfill.min.js#L2

**Comment by borys-p** [comment]
So... maybe it's time to do it?
