### ISSUE TITLE
Cannot sync with LibreWolf?

### ISSUE THREAD

**Issue by closewall** [keepassxreboot/keepassxc-browser#1353]
I've tried both the flatpak and snap version of LibreWolf, but I have no idea how to configure the Keepass XC Password Manager with LibreWolf. I got the addon from the Firefox addons page, but it won't sync with my Keepass XC database. I keep getting the error:

`Cannot connect to KeePassXC. Check that browser integration is enabled in the KeePassXC settings.`

Of course, it is enabled. I'm pretty sure this error occurs because it's configured to use the "Firefox" data directory, and not LibreWolf's, but I don't know where LibreWolf's data directory is. It isn't in the user directory like Firefox, even though the profile creator appears to indicate it is.

Also, in Keepass XC, once I browse for a custom directory in the flatpak version, a file browser window pops up, and you can't do anything in it. It's basically frozen and cannot be closed without using the terminal/system monitor. There is no option for this in the snap version.

## Debug info

KeePassXC - 2.6.4 (flatpak) and 2.6.6 (snap)
KeePassXC-Browser - 1.7.8.1
Operating system: Linux
Browser: LibreWolf 89.0 Flatpak

**Comment by droidmonkey** [comment]
We don't support alt browsers. The native messaging folder is probably under ~/.librewolf/

**Comment by closewall** [comment]
> We don't support alt browsers. The native messaging folder is probably under ~/.librewolf/

Ok, but what about the bug where once you click "browse" inside KeepassXC, I encounter a soft-freeze? Like I can't click anything within the popup filebrowser, or even close it.

**Comment by varjolintu** [comment]
Use the Custom Browser feature in Browser Integration settings to set a custom path.

**Comment by mwip** [comment]
You could also link the native messaging folder to the .librewolf config: 

```bash
ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
```

**Comment by keizah7** [comment]
> You could also link the native messaging folder to the .librewolf config:
> 
> ```shell
> ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> ```

thank you!

**Comment by keizah7** [comment]
> > You could also link the native messaging folder to the .librewolf config:
> > ```shell
> > ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> > ```
> 
> thank you!

for some reason it doesn't work anymore

**Comment by keizah7** [comment]
> > > You could also link the native messaging folder to the .librewolf config:
> > > ```shell
> > > ln -s ~/.mozilla/native-messaging-hosts ~/.librewolf/native-messaging-hosts
> > > ```
> > 
> > 
> > thank you!
> 
> for some reason it doesn't work anymore

https://github.com/keepassxreboot/keepassxc/discussions/7669#discussioncomment-6694506
