### ISSUE TITLE
Randomly KeepassXC-browser extension disconnect from Keeweb with Error "Key exchange was not successful."

### ISSUE THREAD

**Issue by PritishParihar** [keepassxreboot/keepassxc-browser#1354]
Randomly  KeepassXC-browser extension disconnect on restart Edge browser. I'm new to the KeepassXC-extension and as well Keeweb, so kindly let me know if this is right place for issue, since keeweb don't have issues option on github repo I guess. 

## Current Behavior
Key exchange was not successful.

Inspecting extension > "Console" tab output

[Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: chrome-extension://oboonakemofpalcgghocfoadofidjkkk/fonts/forkawesome-webfont.woff2?v=1.1.7

DevTools failed to load source map: Could not load content for chrome-extension://oboonakemofpalcgghocfoadofidjkkk/fonts/fork-awesome.min.css.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

## Steps to Reproduce (for bugs)
Since error is random, I can barely connect very few times, most times end up disconnecting.

## Debug info
KeePassXC-Browser - 1.7.8.1
Operating system: Win64
Browser: Microsoft Edge 91.0.864.48
KeeWeb v1.18.6
Edge Version 91.0.864.48 (Official build) (64-bit)

**Comment by varjolintu** [comment]
While KeeWeb might support our protocol, our extension doesn't support the additions KeeWeb is expecting. As far as I know, KeeWeb-Connect is the official extension to use.
