### ISSUE TITLE
Browser extension unresponsive on a number of websites

### ISSUE THREAD

**Issue by simurq** [keepassxreboot/keepassxc-browser#1355]
Like on these ones:  

[AliExpress](https://aliexpress.com)

[MobileRead](https://www.mobileread.com/forums/)

[FSDeveloper](https://www.fsdeveloper.com/forum/login/)

[4PDA](https://4pda.to/forum/index.php?act=auth)

[FantLab](https://fantlab.ru/)

... and a few others.

Although I can see the extension's icon in login field. All settings are default. I use the latest `KeePassXC v2.6.6` + `Brave` on Linux `Pop_OS 20.04`. I also tried to reload login pages after completely disabling uBlockOrigin and Tampermonkey, to no avail yet. It didn't work on Chrome on Windows 7 x64 either. Brave comes from its own repository, as described [here](https://brave.com/linux/), so it's neither a snap nor a flatpak package. I've started using the browser extension recently with `KeePassXC v2.6.4`. But due to these symptoms, I switched to v2.6.6 on `Brave 64-bit v1.25.72` (Chromium: 91.0.4472.101) - the latest version. 

On some pages (e.g. [4pda.to](https://4pda.to/forum/index.php?act=auth)), the context menu is not available at all, while the browser extension detects only the username field with the following message: `Only a single username field was detected. Add the URL to Site Preferences with Username-only option enabled?`!

Any clue what might affect the injection of extension data onto login page?

Thanks!

**Comment by varjolintu** [comment]
Any messages in the page's JavaScript console?

**Comment by simurq** [comment]
> Any messages in the page's JavaScript console?

Yes, the following error message pops up in the dev console: `initContentScript error:  Error: Cannot read property 'errorMessage' of undefined at n (browser-polyfill.min.js:1)` pointing at line 2,051 of `keepassxc-browser.js`. Tested on pages listed in OP.

**Comment by varjolintu** [comment]
> > Any messages in the page's JavaScript console?
> 
> Yes, the following error message pops up in the dev console: `initContentScript error: Error: Cannot read property 'errorMessage' of undefined at n (browser-polyfill.min.js:1)` pointing at line 2,051 of `keepassxc-browser.js`. Tested on pages listed in OP.

Interesting. Just made a fix for that. I'll test it. Thanks for the information.

**Comment by simurq** [comment]
I don't know if this is a complete solution to the problem, but I've noticed that the URLs of the troublesome websites above (see: original post) had been defined in my KeePassXC database using the HTTP protocol instead of HTTP**S**. When I updated them e.g. like this `http**s**://fantlab.ru/`, and reloaded the page, the browser extension recognised the fields appropriately. Hope it helps!

**Comment by varjolintu** [comment]
> I don't know if this is a complete solution to the problem, but I've noticed that the URLs of the troublesome websites indicated above (see: my original post) had been defined in my `KeePassXC` database using the HTTP protocol instead of HTTP**S**. When I updated them e.g. like this `httpS://example.com/`, and reloaded the page, the browser extension recognised the fields appropriately. Hope it helps!

A correct way to handle these are:
1) Add an additional URL to the entry with a HTTP scheme
2) Disable scheme matching from KeePassXC's Browser Integration settings
