### ISSUE TITLE
Web Documentation missing: Connecting to a browser installed as a Snap

### ISSUE THREAD

**Issue by ianp5a** [keepassxreboot/keepassxc-browser#1359]
The **documentation** on how to connect KeepassXC application to the snap version of Vivaldi browser on Linux is unclear or missing on the web and in the application. **Symptom**: The Browser extensions says it cannot connect to the Application. And does not give a reason. _"KeePassXC-Browser has encountered an error: Key exchange was not successful."_

The Extension **Github Troubleshooting page** here "https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide" says: _"if you are using Linux and your browser is installed via Snap, it won't work. Use the official PPA or AppImage instead._" and gives no further help in connecting the browser to the App

**KeepassXC** itself says in Settings-Browser Integration: _"Due to sandboxing you must obtain a script from "https://keepassxc.org/download/#linux"_ where you can download the file. But downloading the file did not help. It does not say if any further steps are needed. This does not help the user, who cannot proceed.

**Requirements**: Instructions for non IT trained people are needed. Or an alternative solution, perhaps directly in an application that would make connecting them possible and obvious to normal users. Also the documentation should be updated to remove the conflicting information about snaps.

- KeePassXC-Browser extension Version1.7.8.1
- KeePassXC - Version 2.6.6  Revision: 9c108b9  Distribution: Snap
- Vivaldi 4.0.2312.33 (Stable channel) stable (64-bit)

**Comment by varjolintu** [comment]
Well, it won't work because if the browser is installed via Snap it cannot escape the sandbox for using Native Messaging to connect KeePassXC. The script for KeePassXC is only for Snap version of KeePassXC. That side is working normally.

**Comment by ianp5a** [comment]
> Well, it won't work because if the browser is installed via Snap it cannot escape the sandbox for using Native Messaging to connect KeePassXC. The script for KeePassXC is only for Snap version of KeePassXC. That side is working normally.

This report is about missing information in the **documentation**. This is the likely cause of the script failing to solve the problem.

**Comment by droidmonkey** [comment]
A non-IT trained perosn using Linux? That is a head scrstcher for me. When you decide to use Linux you had better be ready for the additional mental gymnastics that follow. Not saying we couldn't document this slightly better, but this is not an expectation I hold for Linux users.

**Comment by ianp5a** [comment]
> A non-IT trained person using Linux? That is a head scratcher for me. When you decide to use Linux you had better be ready for the additional mental gymnastics that follow. Not saying we couldn't document this slightly better, but this is not an expectation I hold for Linux users.

A lot of people put a lot of hard work in to making desktop environments and applications easy to use for a broad range of user types. Trying to reduce the need for mental gymnastics that are not needed on other OSs. Non IT people can do most things as easy, if not easier than the commercial OSs. But sometimes there are traps to catch people out. Where they can't progress, despite help from well meaning techies. But when they don't speak the same language, these people have to give up and go back to Windows, just because people didn't realise that not everyone is IT experienced. It's problems like this that keep the number of users on Linux low. Making manufacturers less likely to make drivers and popular program makers less likely to port to Linux.

**Comment by droidmonkey** [comment]
I mean when you run the script it explicitly asks you if your browser is running as a snap, and of it is it tells you that connection is not possible. I'm really not sure how much clearer to make it.

**Comment by varjolintu** [comment]
> > Well, it won't work because if the browser is installed via Snap it cannot escape the sandbox for using Native Messaging to connect KeePassXC. The script for KeePassXC is only for Snap version of KeePassXC. That side is working normally.
> 
> This report is about missing information in the **documentation**. This is the likely cause of the script failing to do it's job. I'm willing to work together and go through step by step and clarify those things the documentation, if that helps.

I'm not sure if that sentence would help if the requirement is "Instructions for non IT trained people are needed". Of course I can add some generic advice to the guide.

**Comment by ianp5a** [comment]
My offer still stands to help find the missing pieces and complete the documentation if anyone want to work with me on this. I've now gone back through it all and wither something is broken or I'm doing it wrong despite following the steps. Please let me know.

**Comment by ianp5a** [comment]
> I mean when you run the script it explicitly asks you if your browser is running as a snap, and if you answer yes it tells you that connection is not possible. I'm really not sure how much clearer to make it.
> 
> 1. You self discovered the browser documentation that states the above
> 2. You self discovered the script from the application itself
> 3. The script walks you through the process and bails with message if not possible
> 4. Our getting started and user guide go over connecting to the browser step by step.
> 
> Using snaps and sandboxing makes this complicated because of the snaps and sandboxing, not because we want to make it complicated.

Following your hint here, I did some further research and think I have solved the problem with the documentation. I could not find any help explaining what to do with the _KeePassXC-Browser Helper Script_, apart from "_Right click -> Save link as..._".  
You mentioned to _run_ it. I found that you can right click the file in the file manager and go "run in Konsole" (I'm on Kubuntu). This brought up a window where I could choose a browser. Afterwards, starting KeepassXC then connecting to it in the browser enabled it to work. 

I suggest adding a few lines of help for the script in an appropriate place, so that people who don't know the missing steps can progress with KeepassXC.  Thanks for your patience.

**Comment by droidmonkey** [comment]
If you are still trying to do this:

> how to connect KeepassXC application to the snap version of Vivaldi browser on Linux

Then that is impossible as discussed above.

**Comment by varjolintu** [comment]
> My offer still stands to help find the missing pieces and complete the documentation if anyone want to work with me on this. I've now gone back through it all and either something is broken or I'm doing it wrong despite following the steps. Please let me know.

I already added some more text to the part you were quoting. I hope it's enough. Of course it doesn't help solving the actual problem with Snap browsers.

**Comment by ianp5a** [comment]
> > My offer still stands to help find the missing pieces and complete the documentation if anyone want to work with me on this. I've now gone back through it all and either something is broken or I'm doing it wrong despite following the steps. Please let me know.
> 
> I already added some more text to the part you were quoting. This is why I closed the issue. I hope it's enough. Of course it doesn't help solving the actual problem with Snap browsers.
Thanks. That's great. Where did you add it?

**Comment by varjolintu** [comment]
> > I already added some more text to the part you were quoting. This is why I closed the issue. I hope it's enough. Of course it doesn't help solving the actual problem with Snap browsers.
> 
> Thanks. That's great. Where did you add it?

To the Troubleshooting Guide.
