### ISSUE TITLE
multiple instances of KeepassXC-browser active in Task Manager

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#136]
## Expected Behavior
I'd think that only one connection between browser and KeepasXC would be sufficient.
Then why am I seeing multiple instances of keepassxc-browser active in the Task Manager?

## Steps to Reproduce
1. Start Vivaldi browser (does this happen with other browsers too?)
2. Connect Keepasxc-browser with keepassxc
3. Throw in a couple of periods of Sleep mode, each time re-connecting with KeepassXC
4. Check the Task Manager and see multiple instances of keepassxc-browser active

## Debug info
KeePassXC - {2.3.1}
keepassxc-browser - {1.0.1}
Operating system: Win 10 (1803)
Browser: Vivaldi
Proxy used: NO

![snipaste_2018-05-07_09-00-24](https://user-images.githubusercontent.com/10008599/39689161-06a48b26-51d6-11e8-8e71-dbf19694f036.png)

**Comment by varjolintu** [comment]
This happens because Chromium-based browsers are handling native messaging hosts differently. For some reason the processes won't exit and multiple of them might stay active in the background. AFAIK there's no solution for this.

**Comment by droidmonkey** [comment]
It looks like we may not be terminating the proxy program correctly which is causing it to hang around. See https://stackoverflow.com/questions/21086962/chrome-native-messaging-not-closed-when-chrome-closed

**Comment by varjolintu** [comment]
I'll make a few tests to see if that's really the case.

**Comment by Techman-** [comment]
I can confirm that this issue happens to me as well. However, it hasn't always been this way.

It seems like a runaway process, spawning them at multiple times a second at worse. I've disabled the extension for now because it basically prevents me from using Chrome in the meantime.

**Comment by phoerious** [comment]
The problem should only occur when KeePassXC is not running.
