### ISSUE TITLE
Browser Extension Stops Working With Installed Version Of KPXC

### ISSUE THREAD

**Issue by lnxwalt** [keepassxreboot/keepassxc-browser#1360]
## Expected Behavior

Once the extension connects to KeepassXC, it should just keep working. 

## Current Behavior

Instead, once it does a version check, it won't work again (possibly until distro packages update KeepassXC version). 

## Possible Solution

Possible workaround: default to extension not checking for KPXC update.

## Steps to Reproduce (for bugs)

1.  Install KeepassXC from synaptic
2.  Install browser extension, go through connection dance.
3. Close and reopen browser
4. Click the extension icon.

## Debug info

KeePassXC - unknown - 2.4.3 (latest available in Ubuntu repository)
KeePassXC-Browser - 1.7.8.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 78.12.0 (Waterfox G2.3.3) and Mozilla Firefox 89.0.1

Browser console has this on Waterfox: `stderr output from native app org.keepassxc.keepassxc_browser: QObject::startTimer: Timers cannot have negative intervals`

**Comment by varjolintu** [comment]
Use https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc to install the latest version.
