### ISSUE TITLE
Ubuntu & Windows - KeePassXC-Browser won't "Connect" with KeePassXC

### ISSUE THREAD

**Issue by craigarno** [keepassxreboot/keepassxc-browser#1361]
Older versions of KeePassXC and KeePassXC-Browser have worked for years in Firefox Linux (and Windows), now they don't.
Specifically, the ability to add entries to the Connected Databases using the "Connect" button no longer works under Linux and Windows 10 Pro.
Existing entries still appear to work under Windows 10 Pro and Linux.
**Database "Connect" button function appears to be broken** under Linux and Windows.

## Expected Behavior

When KeePassXC-Browser tells me "_Message Encryption Failed.  Is KeePassXC Running?_"
I press "**Reload**" and get "_Key exchange was not successful._"
Go to Settings, select Connected Databases, press the green "Connect" button, nothing happens under Linux and Windows.

## Current Behavior

If the needed database already exists from previous versions, the setup works.
If a New "Connection" is needed, the normal method of adding, by pressing the green "Connect" button doesn't work.
I discovered this while adding Tor to Linux which also uses **KeePassXC** + **KeePassXC-Browser**

## Possible Solution

Looks like something in version creep broke the "Connect" functionality.

## Steps to Reproduce (for bugs)

1. Install Keepassxc 2.6.6
2. Install Firefox 89.0.2
3. Install KeePassXC-Browser 1.7.8.1
4. Settings->Connected Databases->Connect

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.8.1
Operating system: Ubuntu 16.04.7 LTS (xenial) x86_64
Operating system: Windows 10 Pro, latest version (no control over forced MS version updates)
Browser: Mozilla Firefox 89.0.2
Browser: Tor Browser 10.0.18 (based on Mozilla Firefox 78.11.0esr)

**Comment by varjolintu** [comment]
Does downgrading KeePassXC help? Just trying to figure out at what point everything broke.

**Comment by RandomInhabitant** [comment]
Under Windows I downgraded to KeePassXC 2.6.4 and 2.5.4.  Neither worked.
2.6.4 behaved the same as 2.6.6.
2.5.4 tells me there is a key exchange error.

**Comment by craigarno** [comment]
Under Windows I downgraded to KeePassXC 2.6.4 and 2.5.4. Neither worked.
2.6.4 behaved the same as 2.6.6.
2.5.4 tells me there is a key exchange error.
Win10 was nagging about another upgrade.  I did, no difference in behavior (existing entries work, "Connect" doesn't)

**Comment by varjolintu** [comment]
I just installed KeePassXC 2.6.6 and KeePassXC-Browser yesterday to a new Windows 10 system and everything worked normally. I suggest you go through the https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by craigarno** [comment]
What Browser and version are you using?

**Comment by varjolintu** [comment]
@droidmonkey Good idea.

**Comment by craigarno** [comment]
The issue I have with this reasoning is this all worked until the somewhat recent past.  KeePassXC and KeePassXC-Browser -are- communicating because if there is a valid connection (in Windows), KeePassXC-Browser will lookup login information and fill in the blanks.  I don't make "new" connections very often, so I'm not sure when it broke.  The Linux system which is a substantial personal server (8-core, 24TB, substantial HW/SW development tools, etc) was working until the database connection table magically emptied itself.

To test this theory of "the browser doesn't matter", I fired up "New Microsoft Edge" (based on Chromium) under Windows, and am experiencing the same issue.  I'll move upstairs again shortly and test this on "New Microsoft Edge-Linux" on the Linux Server.

I'll start looking for the "manifest file" on both OS's.

This is disturbing because I have come to depend on KeePassXC on all the systems I use (often in the 3-10 count range, various OS's).  So it's worth derailing me from other projects to see if we can figure this out.  I'm hoping this will either be a legitimate bug, or a slap my forehead (duh) moment where I have to apologize for wasting all your time.

**Comment by varjolintu** [comment]
If it would be only Windows, it could be possible that some anti-malware/virus tool prevents the Native Messaging for working properly. But if you are having the same problem with Linux too, it's quite strange. And this happened almost at the same time?

**Comment by craigarno** [comment]
I "discovered" it at the same time, I don't know exactly when it stopped working.  Going backwards to KeePassXC prior to 2.6.x seems to also be a no-go.  Both systems are fairly stable fully fleshed out development environments, not sandbox systems.

**Comment by droidmonkey** [comment]
We don't support edge on Linux yet. We made no changes to the connection api or process since 2.5.0. I also tested connecting a database recently and it works fine. You should also make sure your databases do not have the same uuid because they are copies of each other. There is a button in the database settings -> browser settings to reset the database uuid.

**Comment by craigarno** [comment]
Um, I keep the KeePassXC file on a network drive, accessible from all network connected systems.  This greatly reduces the amount of "Database Merging..." which has to be done.  There are local copies of the password file, but these are used more as a "backup" of the network shared database, and I've been operating this way for over a year.  It didn't seem to break until KeePassXC 2.6.x came out..  At least this is my thinking.  So, did I shoot myself in the foot, and every installation has to have a local HD copy with different UUID's?  (If so, this would be a real pain)

As for Edge on Linux, it does seems to work, though I can appreciate your comment of, "We don't support edge on Linux yet.", which means something totally different from "it so far operates correctly under Linux".  ;)  Like I said, MS is moving toward using/incorporating more open source code, like Chromium.  FWIW, I don't work for MS at this time, but do have friends who keep my up to date.

**Comment by droidmonkey** [comment]
A shared database across multiple platforms is fine. However if you try to connect a backup of that database, and you have conflicting access codes for the same uuid, then you'll run into problems.

**Comment by craigarno** [comment]
Oh good, then I should be okay.  The name is usually a hybid of "NetName-Browser" so there are no duplicate names.

**Comment by craigarno** [comment]
> The browser is not relevant as long as the native messaging manifest is installed correctly (checkboxes in browser settings).
> 
> > When KeePassXC-Browser tells me "Message Encryption Failed. Is KeePassXC Running?"
> > I press "Reload" and get "Key exchange was not successful."
> 
> This sequence of events tells me you do not have a manifest file correctly installed. You could also have access issues with running the proxy application even with a valid manifest. The connect button in the extension settings is a misnomer (@varjolintu we should disable that button if not communicating to a running keepassxc program). That button is always enabled even if not communicating with keepassxc at all.

I read and tried to interpret this and to me it comes down to what are the KeePassXC Browser Settings? (here is a screen shot)
![image](https://user-images.githubusercontent.com/4262930/123737462-d4455500-d857-11eb-99a1-c0391c55baa9.png)

KeePassXC version information
![image](https://user-images.githubusercontent.com/4262930/123738000-dbb92e00-d858-11eb-86c5-dadcee5c73c6.png)

The KeePassXC Password Database is unlocked
![image](https://user-images.githubusercontent.com/4262930/123738411-99dcb780-d859-11eb-883b-1e69c4e54db8.png) 

Lots of KeePassXC-Browser entries from Firefox, Chrome, Chromium, New MS-Edge (Chromium based)
![image](https://user-images.githubusercontent.com/4262930/123738980-bcbb9b80-d85a-11eb-8422-395693c04858.png)


If I understand what you are saying, now the database should show in KeePassXC-Browser (screen shot)
![image](https://user-images.githubusercontent.com/4262930/123737824-8250ff00-d858-11eb-87e7-2a03bfdd9cfa.png)

KeePassXC-Browser version information
![image](https://user-images.githubusercontent.com/4262930/123738200-36528a00-d859-11eb-9bf6-4c3ae1e59589.png)

Windows 10 Pro is showing similar problems with the same version tools, except Windows 10 does show KeePassXC version information, which to me indicates an actual connection between KeePassXC and KeePassXC-Browser.

**Comment by droidmonkey** [comment]
On Linux you have no connection to keepassxc. Is the browser running as a snap?

**Comment by craigarno** [comment]
> On Linux you have no connection to keepassxc. Is the browser installed as a snap?

No, it isn't running in any container type system.  Snap was introduced in Ubuntu 18.x, because of the large number of applications which will likely break when I "upgrade", I'm still running 16.x.  I know I'll eventually have to upgrade, but last time I did, it cost me one month of my time to fix all the stuff which broke; phone system, email, web presence, A/V media applications, development tools, revision control setup, etc., etc.

And this KeePassXC setup was working not that long ago, so I'm stumped about what changed.  Only excuse I can come up with is all the "auto-upgrade" activity which Ubuntu is now starting to do.  Used to be my system had uptimes of 227 days.  Not anymore, and I think we're calling this "progress".

**Comment by varjolintu** [comment]
@craigarno I'm curious if there's any difference if KeePassXC is used from the PPA or AppImage instead of the official repos? Of course this doesn't explain the problems with Windows.

**Comment by craigarno** [comment]
> @craigarno I'm curious if there's any difference if KeePassXC is used from the PPA or AppImage instead of the official repos? Of course this doesn't explain the problems with Windows.

Interesting idea.  I have KeePassXC updating from your official source.  I'm not sure at the moment how to undo this and return to what is delivered with the 16.04.7 system.  Will investigate as time permits.

**Comment by velaar** [comment]
Same issue but only with WIndows. (On Edge/Chrome/etc). Went through troubleshooting guide couple times. 

On linux (Archlinux) works as intended. On Windows it seems there is completely no communication with keepass_proy.exe.

**Comment by varjolintu** [comment]
@velaar On Windows, do you have any anti-virus or anti-malware software that could interfere?

**Comment by craigarno** [comment]
I went ahead with my plans to upgrade to Ubuntu 20.04.3 Server with ubuntu-gnome-desktop.
$ **sudo snap install keepassxc**
Firefox 91.0.2 Addon
**KeePassXC-Browser** Add

I had a _very difficult time finding the script_ I needed to run to allow KeePassXC snap container access
https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh
Right clicked, Save As...
**chmod +x keepassxc-snap-helper.sh
./keepassxc-snap-helper.sh**
_Firefox in snap container = NO_
then it worked...

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 91.0

The reason the script was so hard to find is because all the Firefox links I followed in KeyPassXC and KeyPassXC-Browser dumped me at the top level sites for browser and AddOn, which was almost worthless as I ran into other false leads about enabling snapd container USB functionality,  All I needed was to find the **keepassxc-snap-helper.sh** script, download, and run it!  It was on page https://keepassxc.org/download/#linux and I had to look in the Snap column, then figure out what a Snap Helper Script might be.  Turns out this sciprt works for the other browsers too!  It would help if the Firefox link would take me straight to a page which described what I need instead of a general page with a lot of unrelated information for me to sort through and try to understand.

Ubuntu 16.04 LTS hit end of life, and constant automatic security updates are causing the towering deck of cards to crumble.  So I'm being forced to upgrade and fix many 100's of applications to achieve the same functionality.  The bright side so far is 20.04.3 seems to run slightly faster on the same hardware, and with snap containers and LVM I hope will be more secure and more easily maintained, both new concepts since 16.04.

After a few more Windows 10 upgrades, the Windows installation started working again too.  Never did figure out what was going on there.

My issues with KeePassXC and KeePassXC-Browser are now resolved.  I hope explaining how lost I got will help reorganize both sites/information and links so someone who isn't an "insider" will more easily figure it out.  This should reduce drain on your time to answer help support questions freeing you up to do more productive/useful things.

Thank you to everyone who offered replies.

**Comment by droidmonkey** [comment]
The link to download the script is directly in the application under the browser settings where you would normally enable a browser for access. On a snap install it instead tells you about the script and links you to the downloads page.

**Comment by RandomInhabitant** [comment]
No, it isn't "directly in the application under the browser settings" in
Ubuntu 20.04.3 or Windows 10 Professional.  Clicking on the Firefox link
takes me to
https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/ ,
-not- to https://keepassxc.org/download/#linux where the Snap
information exists.  Or https://keepassxc.org/download/#windows where
Windows install information exists.  Go check it on an up to date install.


Also no links in the KeePassXC-Browser Settings either


Craig

**Comment by craigarno** [comment]
No, it isn't "directly in the application under the browser settings" in
Ubuntu 20.04.3 or Windows 10 Professional.  Clicking on the Firefox link
takes me to

https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/ ,
-not- to https://keepassxc.org/download/#linux where the Snap
information exists.  Or https://keepassxc.org/download/#windows where
Windows install information exists.  Go check it on an up to date install.
![image](https://user-images.githubusercontent.com/4262930/131530906-17404c06-b79e-4f1d-bf32-221a6e497aa2.png)

Also no links in the KeePassXC-Browser Settings either
![image](https://user-images.githubusercontent.com/4262930/131531074-cef84da1-d185-41ce-ab1e-032744d25bc2.png)

**Comment by droidmonkey** [comment]
If you don't see it then you are not running the snap version. Windows 10 is obviously not running a snap version nor requires a script.

**Comment by craigarno** [comment]
True, but I still expect the link to take me to the right location for installation instructions, which it currently does not.  This wasted a lot of my time.
