### ISSUE TITLE
reCAPTCHA activates credential retrieval for Google

### ISSUE THREAD

**Issue by Eleison23** [keepassxreboot/keepassxc-browser#1365]
## Expected Behavior

The website displayed in the URL bar should cause KeepassXC-browser to retrieve credentials associated with it.

## Current Behavior

When I visit https://secure.newegg.com/identity/signin KeepassXC-browser pops up a dialog to accept a Google account and does not offer my Newegg credentials which are configured with URL: https://newegg.com/
This appears to be because of the presence of reCAPTCHA (passive) in the web page source and a small icon in lower right corner.

## Possible Solution

Detect and ignore reCAPTCHA-related URLs. Also need to properly detect newegg.com URL?

## Steps to Reproduce (for bugs)

1. Create two accounts in KeepassXC: a Google account with URL https://google.com/ and a Newegg account with URL https://newegg.com/
2. Visit https://secure.newegg.com/identity/signin
3. Observe the behavior of the dialog box offering Google but not Newegg.
4. File issue on GitHub.
5. Wait for suggestions.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.8.1
Operating system: Ubuntu Linux 18.04.5 LTS bionic
Browser: Chrome 91.0.4472.114 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
I'll look into it. I'd strongly suggest that you use `https://accounts.google.com` as the URL for Google accounts.

**Comment by varjolintu** [comment]
This should be fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1634.
