### ISSUE TITLE
Improved way to match entries to URLs

### ISSUE THREAD

**Issue by msard-oz** [keepassxreboot/keepassxc-browser#137]
As mentioned in similar [issues](https://github.com/keepassxreboot/keepassxc-browser/issues/84), it would be nice to have an improved, more flexible way to match credentials to URLs.

## Expected Behavior
Using regex or wildcards it should be possible to match all domains where the user logs-in with the same account to a single DB entry. 

## Current Behavior
As of now it seems that new entries are simply associated with the current URL and then stored in the DB. This is how most browser-based password-managers work, but:
In some cases, such as Microsoft services that all have separate domains which are accessed with the same Microsoft-account, this means that my DB ends up with several entries that actually just duplicates of one another. In some cases this also leads to dozens of duplicates, for instance if I need to login to several different "country versions"  (.com .co.uk ...) of the same domain, like on eBay. 
This also means that changing credentials means that I need to change them for all of these duplicate entries.

## Possible Solution
By using a user-provided regex in the URL field, the plugin could match multiple domains to a single DB entry. This would allow slightly advanced users to drastically reduce the clutter in their DB in such cases,  while also make credential updates easier.

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc/pull/1769

**Comment by msard-oz** [comment]
Thank you. I'm going to close this issue.
