### ISSUE TITLE
fields not detected for app.at.cafe

### ISSUE THREAD

**Issue by lusitania** [keepassxreboot/keepassxc-browser#1372]
## Expected Behavior

Login fields have been detected and populated.

## Current Behavior

No fields are detected. "Choose custom login fields" does not show any candidates.
![image](https://user-images.githubusercontent.com/4135918/125603197-ab07f86c-ad20-4f2f-bac6-00dff3f32af7.png)

## Possible Solution

The XPath reveals some unusual elements.
```
/html/body/div[1]/div/div/div/div[2]/amplify-authenticator/amplify-sign-in//amplify-form-section/amplify-auth-fields//div/amplify-email-field//amplify-form-field//div/div[2]/slot/amplify-input/input
```

## Steps to Reproduce (for bugs)

https://app.at.cafe/

1.
2.
3.
4.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - ??
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
This is related to: #446.
