### ISSUE TITLE
KeePassXC-Browser never finds TOTP setup

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc-browser#1377]
## Overview

I've been testing KeePassXC-Browser in Firefox for a bit, and while it's perfectly capable of filling in the username and password for a lot of sites the TOTP lookup always fails with

> Warning! No TOTP found.

## Steps to Reproduce

1. Create a login for a site like GitLab, Google, GitHub or others
2. Enable MFA using TOTP
3. Set up TOTP in KeePassXC (that is, ensure that "Copy TOTP" and "Show TOTP" work for the given entry)
4. Install KeePassXC-Browser and connect to the unlocked KeePassXC instance
4. Try to log in to the relevant site

## Expected Behavior

When clicking the TOTP field button the value should be filled in, just as the username and password.

## Actual Behavior

When clicking the TOTP field button to fill in the value, the warning above shows up and the TOTP field stays empty.

## Context

Workaround: Ctrl-t on the entry in KeePassXC works to copy the TOTP value into the clipboard.

This has shown up on every version of KeePassXC for the last few months.

KeePassXC - Version 2.6.4

Qt 5.15.2
Debugging mode is disabled.

Operating system: NixOS 21.05 (Okapi)
CPU architecture: x86_64
Kernel: linux 5.10.48

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- libgcrypt 1.9.2

Operating System: Linux
Desktop Env: Gnome
Windowing System: XWayland

**Comment by varjolintu** [comment]
This is probably already fixed in the new 1.7.9 release.

**Comment by varjolintu** [comment]
Did the latest release 1.7.9.1 fix the issue?

**Comment by l0b0** [comment]
Looks like it, thanks!
