### ISSUE TITLE
plugin cannot detect login form after latest update (1.7.9)

### ISSUE THREAD

**Issue by DonCaramello** [keepassxreboot/keepassxc-browser#1379]
## Expected Behavior
* Should (and did) identify login form on page https://welt1.freewar.de/freewar/ (in latest chrome 92.0.4515.107)

## Current Behavior
* does not identify login form (in latest chrome 92.0.4515.107)
![image](https://user-images.githubusercontent.com/7680220/126621699-002df76f-1f89-426a-93e9-a166d97c760f.png)
* trying to manually identify login fields also doesnt find the form 
![image](https://user-images.githubusercontent.com/7680220/126621766-586bf151-76fc-46f0-baaa-7afbce89e78a.png)

## Steps to Reproduce (for bugs)
1. https://welt1.freewar.de/freewar/ (in latest chrome 92.0.4515.107)
2. try to identify login form
![image](https://user-images.githubusercontent.com/7680220/126622216-2e03dc56-336c-4cf1-a93d-6df9008b0ed7.png)

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
I also noticed one site that is broken. Gotta fix it ASAP.
