### ISSUE TITLE
Add username only or password only entry when click XC icon

### ISSUE THREAD

**Issue by dnai05** [keepassxreboot/keepassxc-browser#1384]
## Summary
Some of the email sites ask for username on one screen and password on second screen. And they sometimes remember the last username so only display password entry. I know I can right-click entry in XC and choose password sequence "{password}{enter}'". Would it be possible to display password sequence options when you click on the XC icon in the browser?
Example 1: add "username only" and "password only" options in XC browser extension icon.
Example 2: if cannot see username field will offer password only from XC icon in field in browser.

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
![image](https://user-images.githubusercontent.com/85871268/127260034-14e099cb-92a9-4b5e-82ac-24884e439a05.png)
![image](https://user-images.githubusercontent.com/85871268/127260471-791d5e1b-48bf-4cd7-8817-4a106f3e907d.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
It would be much easier and faster if we can select this from browser

**Comment by varjolintu** [comment]
The whole idea of the icon is to provide an easy way to fill. You can already fill just the password using the context menu. For sequences you can use Auto-Type instead.

**Comment by dnai05** [comment]
Ahha! I was right-clicking on the icon itself. If I right-click on the password **field** I see the KeePassXC options. Thanks for the tip.
