### ISSUE TITLE
Deal with hidden password fields

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#1385]
## The issue:
https://www.ethias.be/myethias/public/nl/connexion hides the password field by default:
![afbeelding](https://user-images.githubusercontent.com/11229646/127289389-7729f911-ef53-453b-add6-65d27c9a21db.png)
As a consequence, the fill-and-submit button doesn't show up. I currently have two options:
* I can activate the 'Only username option' - then the fill-and-submit button shows up on page load, but only fills the username and it activates the password field. But the password field then stays empty because I indicated only a username field should be considered.
* I could keep 'Only username option' inactive - then I have to manually 

## Expected Behavior
As indicated in https://github.com/keepassxreboot/keepassxc-browser/issues/1358#issuecomment-888244133, hidden password fields can/should/are better not filled automatically.
I would expect KPXC-browser to still offer me a way to log in without typing anything manually.

## Current Behavior

See 'The issue', I guess.

## Possible Solution

Thinking of another solution: I can imagine three options
* even for sites that have the 'Only username option' activated, the fill-and-submit button is shown even after submitting for the first time (I'd have to click twice, but that's still an improvement)
* even for sites that don't have this option activated, the fill-and-submit button is shown when there is only a username field (I'd have to click twice, but that's still an improvement)
* the 'Only username' boolean is changed into dropdown, which adds the option 'Password initially hidden' (in addition to 'Both' and 'Only username'), possibly combined with a way to indicate a 'Submit button/link' (in addition to the existing options to select username, password & TOTP fields)

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Linux
Browser: Firefox

Thanks a lot for your great work!

**Comment by varjolintu** [comment]
I can try to add an exception for the site. I'm actually just looking at it :)

**Comment by droidmonkey** [comment]
We really need to introduce the concept of a login workflow. This would be an enhancement to the custom fields picker, but allow you to navigate the site while picking.

**Comment by varjolintu** [comment]
> We really need to introduce the concept of a login workflow. This would be an enhancement to the custom fields picker, but allow you to navigate the site while picking.

I've already started it. Progressing, but slowly.

**Comment by heynemax** [comment]
I'm having a similar problem were the visibility check is not working correctly on https://b2b.dab-bank.de/smartbroker/
Because `<html>` has the element style `opacity:0` no input element will be found. The function `kpxcFields.isVisible(field)` is failing on all elements because of this element style. Still all the elements are visible obviously in my browser. How can this be fixed?

**Comment by droidmonkey** [comment]
Use Auto-Type

**Comment by heynemax** [comment]
I've created a tampermonkey script to sanitize this website and this made it work.
