### ISSUE TITLE
KeePassXC-browser failure to connect to databases Brave + Mac Silicon M1

### ISSUE THREAD

**Issue by alexonbstudio** [keepassxreboot/keepassxc-browser#1387]
## Expected Behavior

The exchange of key is failed

## Steps to Reproduce (for bugs)

<img width="1313" alt="Capture d’écran 2021-08-01 à 09 29 45" src="https://user-images.githubusercontent.com/65239996/127763121-05458082-8997-4b14-8c1f-c74d886afc3f.png">

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1 
Operating system: Mac silicon M1
Browser: Brave

**Comment by varjolintu** [comment]
Check the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by alexonbstudio** [comment]
Is not easy to fix now is works thanks
