### ISSUE TITLE
Don't retrieve credentials when no login fields are found

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc-browser#139]
## Expected Behavior

The extension should not ask KeePassXC to provide credentials when there are no login fields on a page. Additional heuristics to determine if a user is already logged in are welcome as well.

## Current Behavior

KeePassXC-Browsers tries to retrieve credentials every time when "Automatically retrieve credentials" is enabled, even if I'm already logged in.

## Debug info
KeePassXC - Version 2.3.3-snapshot
Build Type: Snapshot
Revision: b02bd59

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 4.16.7-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- YubiKey

**Comment by ramenchef** [comment]
To add on top of this, if you also have "Automatically fill-in single credentials entry." it seems to fill in the username into every search bar it finds on matching webpages. In keepass, if you check "remember choice" and then click deny, it ignores the setting and still asks for permission to retrieve the credentials.

**Comment by varjolintu** [comment]
I agree with you. All these changes are very welcome. I'll make them to the next version.

**Comment by sxe** [comment]
I absolutely agree and I would also call this a bug cause the behaviour changed. It never happened to me before. It started occuring after i update the keepassxc 2.3.3 (from 2.3.1).

Happy to provide more info if necessary.

Cheers

**Comment by varjolintu** [comment]
@sxe Probably this happens even if you try to downgrade back to 2.3.1 because I'm quite certain that the change is happening in the extension side.

**Comment by ArchangeGabriel** [comment]
Yeah, I think that 1.1 changed that behaviour. Now I get asked as soon as there is any input field on a website for which I have credentials, and this is very annoying…

**Comment by phoerious** [comment]
Please update to 1.1.1.

**Comment by ArchangeGabriel** [comment]
I did, the issue remains.

**Comment by varjolintu** [comment]
I'm going to fix this ASAP.

**Comment by olifre** [comment]
Could we also get another release incorporating that fix? 
The current 1.1 and 1.1.1 are really almost unusable due to this, especially when notifications are enabled for each query in KeepassXC, which now are shown on almost every page load.

**Comment by jtl999** [comment]
I'm still getting some slowdown with KeePassXC 2.3.3 and KeePassXC-Broser 1.1.2 on Firefox 59.0.3 under Linux despite removing and reinstalling the extensions and disabling the automatic retrieval of credentials.

![KeePassXC browser slowdown](https://i.imgur.com/JOSJCZA.png)

**Comment by phoerious** [comment]
Slowdown may be related to #1765. Could you check if you have multiple keepassxc_proxy processes running?

**Comment by jtl999** [comment]
No

```
[jtl@jtl-desktop ~]$ ps -ef |grep keepassxc |grep -v grep
jtl       1436  1074  0 09:29 ?        00:00:19 keepassxc
jtl      13800 13641  0 13:01 ?        00:00:00 /usr/bin/keepassxc-proxy /home/jtl/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
```

**Comment by jtl999** [comment]
Quick five minute test of 1.1.3 this morning. Havn't had Firefox freeze at all despite "Automatically retrieve credentials" turned on.

I will update if I have further problems.
