### ISSUE TITLE
Ubuntu Firefox can not connect to database (no prompt)

### ISSUE THREAD

**Issue by axi92** [keepassxreboot/keepassxc-browser#1393]
## Expected Behavior
I installed KeepassXC and the Plugin in my firefox (not snap i think). And have the option to use the browser integration enabled. 
On my other ubuntu 18 LTS it is working fine.
On my laptop ubuntu 20 LTS it is not working. 
![grafik](https://user-images.githubusercontent.com/1394837/129548810-37ad7d4a-a218-4644-8afd-0c0fab7406d5.png)

## Current Behavior

When I go to settings in the browser plugin and click the "connect" button nothing happens.
If I use the icon in the top bar it says that the connection to the application is not possible and I should check if the browser integration is enabled. Then I click on "reload" -> "key exchange was not successful"

## Steps to Reproduce (for bugs)

1. Normal installation like in the docs
2.
3.
4.

## Debug info

KeePassXC - unknown (2.6.6 the firefox plugin is not able to read the information)
KeePassXC-Browser - 1.7.9.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 91.0

**Comment by varjolintu** [comment]
Check the Firefox install from `about:support`.  The application binary path should tell you if it's installed via Snap.

**Comment by axi92** [comment]
Not snap right? "/usr/lib/firefox/firefox"
I checked also with snap list and there was no firefox.

**Comment by varjolintu** [comment]
Yeah. No Snap. Is your KeePassXC installed via Snap though?

**Comment by axi92** [comment]
Yes it is installed via snap. Have I missed permissioins for that?

**Comment by varjolintu** [comment]
You need to use an extra helper script for Snap version. You can download it from here: https://keepassxc.org/download/#linux

**Comment by axi92** [comment]
Ah thank you very much! I missed that script =)
