### ISSUE TITLE
Browser Access Request window doesn't show up on some website

### ISSUE THREAD

**Issue by ponyodc** [keepassxreboot/keepassxc-browser#1395]
## Expected Behavior
The "Browser Access Request" window shows up for any new website I visit and after selecting "remember" and "allow selected" I can fill in the username/password

## Current Behavior
The "Browser Access Request" window doesn't show up on some websites like : 
- https://accounts.adafruit.com/users/sign_in
- https://www.decathlon.fr/
- https://www.airbnb.com/
- https://www.fnac.com/
- https://identify.plantnet.org/sign_in
- ...

Since I can't allow the browser to access the website I can't fill in the username/password. 

Everything works fine for these websites (for instance) :
- https://github.com/
- https://www.ebay.com/
- https://www.paypal.com
- https://www.rei.com/
- https://newyork.craigslist.org/
- ...

## Possible Solution
I have really no idea where the problem could come from

Is there a way to allow the access request for all websites ? I've seen someone writing about something like that on the keepassXC-browser side but I can't find it. 
I guess that could solve the problem even if less secure. 

## Steps to Reproduce (for bugs)
See websites list above

## Debug info
KeePassXC - 2.6.6 Standalone
KeePassXC-Browser - 1.7.9.1
Operating system: Win64
Browser: Chrome/Chromium 92.0.4515.131

Thank you for your help !

**Comment by droidmonkey** [comment]
Check http vs https in your url fields

**Comment by ponyodc** [comment]
All websites seem to be https nowadays no ? Actually, I can't even find a http website...

**Comment by varjolintu** [comment]
@ponyodc Check that your entry URL's in your database have `https://` at the beginning of the URL.

**Comment by ponyodc** [comment]
Most of the URL in my database are https and some have http. Others are like "xxxxx.com" without the http or https. I don't see any correlation

Also, I should precise that on the websites which don't show the request access window the keepass logo (green disk with the key) is present near the username field to fill in. That let me think that the keepassxc-broswer found a match in my database, no ? 

Digging the potential issue with non-matching database entry : for instagram I face the same issue (no request access window appears). In my database, I have : 
- URL : androidapp://com.instagram.android
- Advanced > Attributes >> URL_1 : https://instagram.com

I would expect KeepassXC-browser to find the associated entry, but maybe it only looks at the URL field and not the other "attributes" ? 

That could be the issue since some of my entries have several associated addresses. What should I do to have those extra addresses detected by keepassxc-browser ?

**Comment by varjolintu** [comment]
@ponyodc URL scheme matters with KeePassXC, unless you disable the "Match URL scheme" checkbox from Browser Integration settings.

Some websites might need a Username-Only Detection enabled (extension settings -> Site Preferences), some are automatically set. This only applies to single username field logins.

Instagram site doesn't work properly with the extension at this point, so if the icon is not visible, another page should work with Additional URL. All sites added to Additional URL list will be detected.

**Comment by droidmonkey** [comment]
URL_1 is not the name of the extra urls in keepassxc. Use the browser integration page when editing an entry to add additional urls.

**Comment by ponyodc** [comment]
I see. Ok, that seems to solve my problem. Thank you ! I understand better how works KeepassXC. 

Is there a reason why keepassxc-browser is not providing a simple search function like KeePass Tusk ? I think that would help a lot when the address is not strictly the same or changed a little bit over time.

**Comment by droidmonkey** [comment]
Because that would require exposing your entire database to your browser. Tusk is a very very insecure extension. It is never a good idea to let your entire database ride on the browser's backbone, that reduces your security to that of the browser.... which we know is not good.

**Comment by varjolintu** [comment]
> Is there a reason why keepassxc-browser is not providing a simple search function like KeePass Tusk ? I think that would help a lot when the address is not strictly the same or changed a little bit over time.

Plus, every entry needs a permission to be accessed by the extension. Overriding that permission would not be a great idea.

**Comment by ponyodc** [comment]
Thanks for the explanation and the help everyone !
