### ISSUE TITLE
HTTP Basic Auth Not Working

### ISSUE THREAD

**Issue by katsar0v** [keepassxreboot/keepassxc-browser#1397]
## Overview
HTTP Basic Authication not working on Chrome (Ubuntu 20.04).
Enabling the option `Automatically fill in HTTP Basic Auth dialogs and submit them.` does not work properly

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enable `Automatically fill in HTTP Basic Auth dialogs and submit them.` in the Chrome extension
2. Save any http basic authentication login data in keepassxc with the url
3. Try 

## Expected Behavior
I expect the extension to fill the login data, in best case also auto-submit.

## Actual Behavior
Nothing happens. The window appears, I click on "allow selected" and nothing happens. I have to manually enter the login data.

![image](https://user-images.githubusercontent.com/7236157/130355944-65663966-899b-41f3-bd48-8cf56bb8b266.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.6
Revision: 9c108b9

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Ubuntu
Desktop Env: Gnome
Windowing System: X11
KeePassXC-Browser Version: 1.7.9.1
KeePassXC Version: 2.6.6

**Comment by varjolintu** [comment]
Not event this test page? https://httpbin.org/#/Auth

**Comment by katsar0v** [comment]
Not even this one @varjolintu

**Comment by varjolintu** [comment]
Does normal credentials work then?

**Comment by katsar0v** [comment]
As mentioned in the initial issue description, yes

**Comment by varjolintu** [comment]
Seems that page has made some changes to the authentication.
This should work normally https://jigsaw.w3.org/HTTP/Basic/ with guest:guest.

**Comment by katsar0v** [comment]
Manually entering the login data works, yes, no need to test if http basic as protocol works.
Saving the data in keepassxc and trying to automatically login with http basic does not. 

![image](https://user-images.githubusercontent.com/7236157/130461335-7b10af8c-5f5d-4b69-a027-7dfd17e5c445.png)

Is this feature beta, alpha or unfinished/not compatible?
![image](https://user-images.githubusercontent.com/7236157/130461438-9aa87959-d6d8-4eb1-b533-de1e94aa74ad.png)

Some more explanation would be great.

**Comment by varjolintu** [comment]
I just tested that example site with one and multiple entries and it worked normally. Cache needs to be refreshed if HTTP Basic Auth must be used again to trigger the credential choosing.

**Comment by katsar0v** [comment]
Can you test with a more complex password with symbols?

**Comment by varjolintu** [comment]
It would be helpful to know those sites where it doesn't work.

**Comment by katsar0v** [comment]
If that's of any help, I face the issue currently only on websites with Plesk Hosting System. I created katsarov.info/test/ as example (U: `test` P: `z(wWH!D?{R` ) and it doesn't work there, can you reproduce this?

**Comment by varjolintu** [comment]
That URL and credentials worked normally for me for HTTP Basic Auth.

**Comment by katsar0v** [comment]
You are correct, it is a local problem. Just tried on another PC with the extension for Chrome and it works. Now because I have 10+ Browser extensions, how can I debug this?

**Comment by varjolintu** [comment]
It's possible that some other extension interferes with this one. Maybe the best way is to enable just KeePassXC-Browser and then enable other extensions one by one and see where it fails. Then only enable KeePassXC-Browser and the problematic extension.

**Comment by katsar0v** [comment]
Ok, am now confused. Just tested on freshly installed firefox and https://katsarov.info/test/ works but other websites still do not, so the problem is not because of Plesk or extension compatibility. Because of information privacy I cannot share the website with you, but I can share this screenshot from firefox if it helps:

![image](https://user-images.githubusercontent.com/7236157/130605679-598b864e-7933-47e0-ba46-76cc483c0640.png)

**Comment by varjolintu** [comment]
I'd have to have an access to a site that doesn't work so I can debug it. Or, alternative, you can try to debug it. But it's a slow progress if you're not familiar to it.

**Comment by katsar0v** [comment]
Well I just found out it works with Bitwarden...

**Comment by varjolintu** [comment]
> Well I just found out it works with Bitwarden...

Well that isn't really helpful.

**Comment by twigit** [comment]
I know this issue is closed, but for anyone struggling with the same problem in the future, here is what worked for me.

HTTP Basic Auth worked on the test URL provided above in the comments, but not on any of the sites where I needed it. Those sites were access to tools I used in my job, and I realized they had something in common that the test URL didn't have : multiple credentials on the same domain, one basic HTTP Auth protecting several tools with their own credentials. The fact that the tools credentials pointed to more precise URLs was not enough and KeepassXC was confused when finding credentials for the basic auth.

The trick for me was to set "Do not use this entry with HTTP Basic Auth" for all the tools credentials and "Use this entry only with HTTP Basic Auth" for the basic auth credentials. I don't know if it's intended to work that way, but it's not really an obvious behaviour and it requires extra time setting up your credentials correctly, so I would recommand changing this anyway.

**Comment by varjolintu** [comment]
@twigit It shouldn't work in a way that tweaking multiple settings is the only solution. I would need a good test site for this where the problem can be reproduced every time. I don't have any real sites in my database that requires HTTP Basic Auth. Of course I can try to make a local server one, but that would work identically with the tests sites.

**Comment by vasyugan** [comment]
I have several sites, where I cannot make this work for the life of me, and tweaking those settings does not make a difference, I just never get offered any credentials at all for completion.

**Comment by varjolintu** [comment]
@vasyugan Can you give some example site where this can be reproduced? No need for any credentials, just a site that has the HTTP Basic Auth prompt.

**Comment by vasyugan** [comment]
> 

https://nagios.uferwerk.org

**Comment by varjolintu** [comment]
@dark-rider I just tested the feature when making the latest fix and I had no problems with it. Can you record a video about it? The better, debug the content script so the output can be seen from JavaScript console.

**Comment by vasyugan** [comment]
> @dark-rider I just tested the feature when making the latest fix and I had no problems with it. Can you record a video about it? The better, debug the content script so the output can be seen from JavaScript console.

What do you mean by "debug the content script"? Is this about a script used by the browser extension? Because, of course there are no scripts on the page, prior to login.
I have made [a video](https://youtu.be/ITPKjS8gbk8) but there isn't much to see there.

**Comment by varjolintu** [comment]
@vasyugan Your video indicates that some of these are missing in your config/db:
- Your entry URL is incorrect
- Your entry or group has denied access to HTTP Basic Auth
- You haven't enabled support for HTTP Basic Auth in the extension

**Comment by dark-rider** [comment]
I cannot supply a video, but now with the current version the behaviour is as follows:

- If you have not yet opened the KeePassXC database (but only this browser addin is active) and if you have also saved the credentials within Firefox, they are offered to be filled in by Firefox.
- If HTTP auth forms appear in Firefox and "HTTP-Basisauthentifizierungsdialoge automatisch ausfüllen und absenden" (HTTP autofill in German) is enabled and the KeePassXC database is open, you have to confirm to use the credentials for this website and they are filled in.
- If you have had opened the KeePassXC database once and close it, autofill via Firefox does not work any more.
- If you disable HTTP autofill in KeePass-XC browser and you have not also saved the credentials in Firefox, there is no possibility to choose suitable credentials. If you click the KeePass-XC browser icon, there is no list of credentials to choose.

Additional questions:
- HTTP basic auth ist mentioned. HTTP digest auth seems also to work, if it works in general?
- It seems to cause additional problems if you open the credentials database and close it shortly after use everytime. But that should be the normal case, i.e. keeping the databse open all the time should not be recommendable?
- Saving credentials in KeePass-XC as well as directly in Firefox should be OK?

**Comment by varjolintu** [comment]
@dark-rider Do not use Firefox's password manager at the same time. Try to disable it and see if the HTTP Basic Auth works better with the extension.

There's no need to keep database open at all times.

**Comment by dark-rider** [comment]
Firefox's password manager cannot be disabled, as far as I see.

**Comment by varjolintu** [comment]
Of course it can be disabled.

**Comment by vasyugan** [comment]
> * You haven't enabled support for HTTP Basic Auth in the extension

After enabling auto submit for HTTP basic auth in the extension settings, it works. But why do you have to enable auto submit, which is generally considered a security risk?

**Comment by varjolintu** [comment]
@vasyugan Any auto-submit should not be enabled by default. Simply.

**Comment by dark-rider** [comment]
> After enabling auto submit for HTTP basic auth in the extension settings, it works. But why do you have to enable auto submit, which is generally considered a security risk?

I can also confirm again that there is no dropdown to select the credentials for HTTP auth as it was longer time ago via the addin icon. Only with enabled HTTP autofill, it works.

**Comment by vasyugan** [comment]
> 



> Any auto-submit should not be enabled by default. Simply.

I totally agree. But with auto submit disabled, the form isn't filled out at all. To be sure: I have move the entry into a separate group to ensure that the settings regarding HTTP are as they should be and still it is getting ignore - unless I check "auto submit". What  am I missing?

**Comment by varjolintu** [comment]
@dark-rider The icon should be used for selection only if there are multiple credentials for the HTTP Basic Auth site. If the same URL is used for HTTP Basic Auth and normal credentials, the other entry must set "Use this entry only with HTTP Basic Auth" in the Edit Entry's Browser Integration tab. Using multiple password managers simultaneously in browsers always has problems because two different implementation are trying to listen similar things.

@vasyugan Could you clarify what do you mean by "Auto-Submit" here? The only needed setting that needs to be enabled is _Automatically fill in HTTP Basic Auth dialogs and submit them._

The normal Auto-Submit I am referring to is the setting _Auto-submit login forms_.

**Comment by vasyugan** [comment]
> 



> @vasyugan Could you clarify what do you mean by "Auto-Submit" here? The only needed setting that needs to be enabled is _Automatically fill in HTTP Basic Auth dialogs and submit them._

Yes. "automatically [...] submit them" sounds an awful lot like auto submit, doesn't it?
 
 Why do http basic out credentials have to be submitted _automatically_? Why can't the extension just fill out the form and let the user click on "submit"?

**Comment by varjolintu** [comment]
@vasyugan Because the API doesn't support that. The HTTP Basic Auth window is not a normal dialog in DOM that can be filled, modified or inspected. It's an internal dialog in the browser itself.

The only options for HTTP Basic Auth is to fill credentials automatically (after those have been accepted from KeePassXC confirm dialog, so it's not entirely automatic isn't it?), or display a separate dialog every time before filling. And because there's no DOM in the Basic Auth dialog, it must be done using the extension icon. Which is already done if there are multiple credentials user must select the correct one.

**Comment by vasyugan** [comment]
> @vasyugan Because the API doesn't support that. The HTTP Basic Auth window is not a normal dialog in DOM that can be filled, modified or inspected. It's an internal dialog in the browser itself.

[...]

I see. Thanks for the explanation. In that case, it is a problem that auto submit for http basic auth is disabled by default. I have to say that I wasn't even aware that there is a separate setting for this, until you told me.

**Comment by hype11** [comment]
I had the problem too, in my case it was a website with NTLM Auth, not Basic Auth, but it looks like Basic Auth.
KeePassXC Browser ask me to fill credentials in, but nothing happens after click OK
