### ISSUE TITLE
Autofill HTTP authentication login forms

### ISSUE THREAD

**Issue by John4266** [keepassxreboot/keepassxc-browser#1402]
I don't think its a bug since its more like a question.

How can i get the KeePass extension to autofill the following form:
![image](https://user-images.githubusercontent.com/70203256/132535444-71952639-02f6-4a63-8499-4e77e4789556.png)
If it's not implemented then i would like to suggest adding it.
Since the browser itself does allow automatic login for such forms but not the extension.

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Win 10 - 64 Bit
Browser: Firefox

**Comment by varjolintu** [comment]
Is that a HTTP Basic Authentication form?

**Comment by John4266** [comment]
> 
> 
> Is that a HTTP Basic Authentication form?

yes

**Comment by varjolintu** [comment]
Enable the "Automatically fill in HTTP Basic Auth dialogs and submit them" setting from the extension and your entry should be filled normally.

**Comment by John4266** [comment]
> 
> 
> Enable the "Automatically fill in HTTP Basic Auth dialogs and submit them" setting from the extension and your entry should be filled normally.

How did i miss that? 😅
Tysm.
