### ISSUE TITLE
keepassxc recognize fields but notthing happens when pussing button

### ISSUE THREAD

**Issue by JeroenBenJHWH** [keepassxreboot/keepassxc-browser#1403]
## Expected Behavior 
 
 
<img width="934" alt="Schermafbeelding 2021-09-10 124103" src="https://user-images.githubusercontent.com/90452429/132841729-781f873c-9fd1-41a8-a309-b6fb1af0f3d2.png">

## Current Behavior
 **On the website of my Bank it is not possible to use the web extention. It recognize the fields for username and password but notthing happens when i push te key button. It is the only website where it does nothing.**

https://mijn.ing.nl/login

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Win64
Browser: Mozilla Firefox 92.0

**Comment by varjolintu** [comment]
Cannot reproduce it. Both pressing the button and <kbd>Enter</kbd> works normally.
