### ISSUE TITLE
Forgotten Connected Database

### ISSUE THREAD

**Issue by protontrigg3r** [keepassxreboot/keepassxc-browser#1405]
KeePassXC Version: 2.6.6
KeePassXC-Browser Version: 1.7.9.1

For a few years now, my KeePassXC databases have been stored in a folder on my private **NextCloud** platform, so I can use them on some PCs with Ubuntu (all recently updated to 20.04) and on a notebook with Windows 10.

Sometimes the KeePassXC-Browser **Firefox** extension forgets one of the connected databases. I had 4 connected databases and this is what happens ...

The extension no longer detects one of the databases:

![Screenshot from 2021-09-15 15-18-12](https://user-images.githubusercontent.com/38140509/133449737-c1a6fae7-e41b-4f51-b2b9-de51bc34dbeb.jpg)

So I **reconnect** it:

![Screenshot from 2021-09-15 15-18-32](https://user-images.githubusercontent.com/38140509/133449833-8dcd8970-59b8-4dde-9462-96c6dbbb105f.jpg)

Obviously the extension already finds the ID in the database, so it asks me for confirmation to overwrite it:

![Screenshot from 2021-09-15 15-18-44](https://user-images.githubusercontent.com/38140509/133449882-877d77b7-10fd-4303-9fc5-af6f659f094d.jpg)

And after my confirmation, here's what happens:

![Screenshot from 2021-09-15 15-18-54](https://user-images.githubusercontent.com/38140509/133449919-3af6d53b-8ab4-4ec8-b31b-8d3b2634a623.jpg)

The extension not only shows the new connection but also detects the previous connection for the same database (and also another duplicate connection, because this problem has already occurred for another database ...)

So: in some cases, the extension appears to incorrectly read the file with Connected Databases info.

**Comment by varjolintu** [comment]
How does the KeePassXC side look from _Database Settings_ -> _Browser Integration_?

**Comment by protontrigg3r** [comment]
Each database shows among the "stored keys" the keys related to the connections with the extensions in the various PCs (now I only have one because I have deleted the others, to try to solve ...):

![Screenshot from 2021-09-15 16-49-48](https://user-images.githubusercontent.com/38140509/133457900-4cf27b10-dac6-4afc-88fb-aaa2ea253833.jpg)

**Comment by protontrigg3r** [comment]
It seems that when Firefox starts, the extension loads only 3 databases, regardless of how many are connected ...

**Comment by varjolintu** [comment]
I suggest to try deleting all connected keys from the database(s) and the extension settings. Then try connecting them again. If there's a pattern that clearly reproduces this every time, let us know.

**Comment by protontrigg3r** [comment]
it seems that "_Refresh database root group ID_" helps to solve this kind of problem ...
