### ISSUE TITLE
keepass xc mozilla plugin don't  work for grafana username and password field

### ISSUE THREAD

**Issue by ofaruk89** [keepassxreboot/keepassxc-browser#1406]
Hello,

i am using "Grafana v5.3.2 (commit: 0d821d0)" . Username and password not filling auto. I cant define or re define username and password fields

I am sure url in db ( i have a lot of addresses )
https://pasteboard.co/uVU69sNXIpMk.png

When I drag the cursor over the boxes, no blue boxes or selection boxes appear. 
https://pasteboard.co/OPYvIMcWIeZe.png

Operating System: macOS Bigsur 11.6
Browser : Mozilla Firefox 92.0.1 (64 bit)
Plugin vers: .7.9.1 (22-07-2021)

KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 11.6
CPU architecture: x86_64
Kernel: darwin 20.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
- libgcrypt 1.9.3

**Comment by varjolintu** [comment]
Can you inspect the web page and see if there's an iframe that contains the login fields?

**Comment by marco44** [comment]
Same problem for me. The login fields are in this:
```
          <div class="login-form">
            <input type="text" name="username" class="gf-form-input login-form-input ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" required="" ng-model="formModel.user" placeholder="email or username" autofocus="" autocomplete="on" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
          </div>
          <div class="login-form">
            <input type="password" name="password" class="gf-form-input login-form-input ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" required="" ng-model="formModel.password" id="inputPassword" placeholder="password" autocomplete="on" style="background-image: url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPhJREFUOBHlU70KgzAQPlMhEvoQTg6OPoOjT+JWOnRqkUKHgqWP4OQbOPokTk6OTkVULNSLVc62oJmbIdzd95NcuGjX2/3YVI/Ts+t0WLE2ut5xsQ0O+90F6UxFjAI8qNcEGONia08e6MNONYwCS7EQAizLmtGUDEzTBNd1fxsYhjEBnHPQNG3KKTYV34F8ec/zwHEciOMYyrIE3/ehKAqIoggo9inGXKmFXwbyBkmSQJqmUNe15IRhCG3byphitm1/eUzDM4qR0TTNjEixGdAnSi3keS5vSk2UDKqqgizLqB4YzvassiKhGtZ/jDMtLOnHz7TE+yf8BaDZXA509yeBAAAAAElFTkSuQmCC&quot;); background-repeat: no-repeat; background-attachment: scroll; background-size: 16px 18px; background-position: 98% 50%; cursor: auto;">
          </div>
          <div class="login-button-group">
            <button type="submit" class="btn btn-large p-x-2 btn-inverse" ng-click="submit();" ng-class="{'btn-inverse': !loginForm.$valid, 'btn-primary': loginForm.$valid}" autocomplete="on">
              Log In
            </button>
            <div class="small login-button-forgot-password">
              <a href="user/password/send-reset-email">
                Forgot your password?
              </a>
            </div>
          </div>
```
That's inside other divs, all in a flex container. No iframe around the login fields, it seems.

**Comment by ofaruk89** [comment]
```
<div class="login-content">
    <div class="login-branding">
      <img class="logo-icon" src="public/img/grafana_icon.svg" alt="Grafana">
      <i class="icon-gf icon-gf-grafana_wordmark"></i>
    </div>
    <div class="login-outer-box">
      <div class="login-inner-box" id="login-view">
        <form name="loginForm" class="login-form-group gf-form-group ng-pristine ng-invalid ng-invalid-required" ng-hide="disableLoginForm">
          <div class="login-form">
            <input type="text" name="username" class="gf-form-input login-form-input ng-pristine ng-empty ng-invalid ng-invalid-required ng-touched" required="" ng-model="formModel.user" placeholder="email or username" autofocus="">
          </div>
          <div class="login-form">
            <input type="password" name="password" class="gf-form-input login-form-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" required="" ng-model="formModel.password" id="inputPassword" placeholder="password">
          </div>
```
          <div class="login-button-group">
            <button type="submit" class="btn btn-large p-x-2 btn-inverse" ng-if="!loggingIn" ng-click="submit();" ng-class="{'btn-inverse': !loginForm.$valid, 'btn-primary': loginForm.$valid}">
              Log In
            </button>
            
            <div class="small login-button-forgot-password">
              <a href="user/password/send-reset-email">
                Forgot your password?
              </a>
            </div>
          </div>
        </form>
        <div class="text-center login-divider ng-hide" ng-show="oauthEnabled">
          <div>
            <div class="login-divider-line">
            </div>
          </div>
          <div>
            <span class="login-divider-text">
              <span ng-hide="disableLoginForm">or</span>
            </span>
          </div>
          <div>
            <div class="login-divider-line">
            </div>
          </div>
        </div>
        <div class="clearfix"></div>
        <div class="login-oauth text-center ng-hide" ng-show="oauthEnabled">
          
          
          
          
          
        </div>
        <div class="login-signup-box ng-hide" ng-show="!disableUserSignUp">
          <div class="login-signup-title p-r-1">
            New to Grafana?
          </div>
          <a href="signup" class="btn btn-medium btn-signup btn-p-x-2">
            Sign Up
          </a>
        </div>
      </div>
      <div class="login-inner-box remove hidden" id="change-password-view">
        <div class="text-left login-change-password-info">
          <h5>Change Password</h5>
          Before you can get started with awesome dashboards we need you to make your account more secure by changing your password.
          <br>You can change your password again later.
        </div>
        <form class="login-form-group gf-form-group ng-pristine ng-invalid ng-invalid-required">
          <div class="login-form">
            <input type="password" id="newPassword" name="newPassword" class="gf-form-input login-form-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" required="" ng-model="command.newPassword" placeholder="New password">
          </div>
          <div class="login-form">
            <input type="password" name="confirmNew" class="gf-form-input login-form-input ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required" required="" ng-model="command.confirmNew" placeholder="Confirm new password">
          </div>
          <div class="login-button-group login-button-group--right text-right">
            <a class="btn btn-link" ng-click="skip();">
              Skip
              <info-popover mode="no-padding" class="gf-form-help-icon gf-form-help-icon--no-padding drop-help drop-hide-out-of-bounds drop-target"><i class="fa fa-info-circle"></i></info-popover>
            </a>
            <button type="submit" class="btn btn-large p-x-2 btn-inverse" ng-click="changePassword();" ng-class="{'btn-inverse': !loginForm.$valid, 'btn-success': loginForm.$valid}">
              Save
            </button>
          </div>
        </form>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>

**Comment by varjolintu** [comment]
Are you still having the same problem with the latest version? I tried using the sources you pasted and everything worked just fine.

**Comment by thePanz** [comment]
Same problem here, grafana v6.7.3 login page's form is not recognized (nor the "choose custom login fields" is showing the form fields neither)

```
KeePassXC - 2.7.0
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 98.0
```

**Comment by tolik518** [comment]
This issue still persists with grafana v6.7.2

> KeePassXC Version: 2.6.4
> KeePassXC-Browser Version: 1.7.12
> Operating system: Ubuntu 20.04.4 LTS x86_64 
> Browser: Chromium 101.0

**Comment by tolik518** [comment]
[Here](https://map.freifunk-3laendereck.net/grafana/login) is a grafana board I found for testing, or [here](https://www.freifunk-suedpfalz.de/grafana/login).

**Comment by varjolintu** [comment]
Ah, this is because we ignore fields based on the `opacity` CSS style. Maybe we could decrease the limit a little bit. It's just a precaution not to include any fields that are intentionally transparent/hidden.

**Comment by tolik518** [comment]
I understand the decision on the one hand, but on the other I think I still should be able to select it manually or not?

**Comment by varjolintu** [comment]
> 

Yes. That should be still allowed. This is why I'd rather make the changet to https://github.com/keepassxreboot/keepassxc-browser/pull/1390 which already refactors the whole Custom Fields selection.
