### ISSUE TITLE
Selecting from accounts list not working

### ISSUE THREAD

**Issue by raspher** [keepassxreboot/keepassxc-browser#1408]
sometimes when i click on account in accounts list, it's not filling. 2nd click on item in list, it's working... 

## Expected Behavior
After clicking an element, fill login inputs

## Current Behavior
![image](https://user-images.githubusercontent.com/23345803/134826058-19a04405-08e0-4648-9b95-86bf60914ce7.png)

## Possible Solution
Idk, I'm not clicking between elements. On this site upper image appears for less than 1 secound, then boxes are filled. They are not always filled, it's the issue!

## Steps to Reproduce (for bugs)
1. Select item in list 
![image](https://user-images.githubusercontent.com/23345803/134826231-07978210-98be-46c5-b7cc-4c10eea1ad3a.png)
2. Expect to have this behavior, repeat if not seen
![image](https://user-images.githubusercontent.com/23345803/134826058-19a04405-08e0-4648-9b95-86bf60914ce7.png)

I have big list of items...

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Win 10
Browser: Chrome

**Comment by droidmonkey** [comment]
The site is probably doing something stupid with Javascript

**Comment by raspher** [comment]
Debug info from console needed? I'm working now, but can collect :) I must censure sensitive information...

**Comment by droidmonkey** [comment]
Nah we can debug it on our end

**Comment by raspher** [comment]
https://allegro.pl/

**Comment by raspher** [comment]
The same happens, when selecting text from list. Probably the best solution is to disable selecting text or invoke filling by mouseDown event

**Comment by varjolintu** [comment]
I had no problems with the site. Tried it with uBlock and without. Does filling work from the extension icon popup?

**Comment by raspher** [comment]
Try mousedown , move mouse and mouse up (select few letters from login in
KeePass account list). It will always not fill 😅. I'm using list under
text input.

Pon., 27 wrz 2021, 18:11 użytkownik Sami Vänttinen ***@***.***>
napisał:

**Comment by varjolintu** [comment]
I'm not sure if I undestand. I really need a video/screencapture of this.
