### ISSUE TITLE
KeePaasXC is saving spacebar after login name

### ISSUE THREAD

**Issue by raspher** [keepassxreboot/keepassxc-browser#1409]
From start... I don't have saved anything in this example. I double-click on login and copy (with a space after login f.e. "admin123 "). Then I paste, fill password and save when prompted, this login is saved with spacebar!
## Expected Behavior
.trim() login

## Current Behavior
it saves with spacebar, which can result in dupliated logins, one with a spacebar and one without

## Possible Solution
.trim()

## Steps to Reproduce (for bugs)
just save login, when login had a space as last character?

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Win 10
Browser: Chrome

**Comment by droidmonkey** [comment]
Good finding.
