### ISSUE TITLE
KeePassXC-Browser never finds TOTP setup

### ISSUE THREAD

**Issue by apastuszak** [keepassxreboot/keepassxc-browser#1420]
## Expected Behavior

You right click on a TOTP field and go to KeepassXC-Browser→ Fill TOTP and the TOTP is filled in

## Current Behavior

You right click on a TOTP field and go to KeepassXC-Browser→ Fill TOTP and you get an error that says:

Warning! NO TOTP found.

## Possible Solution

Sadly, no clue.  I see there was a previous bug ( #1377 ) that was filed with this and it was fixed.

## Steps to Reproduce (for bugs)

1. Store TOTP code in KeepassXC
2. Install browser extension and link
3. Try to login to a website and and have KeepassXC-Browser fill in your TOTP code.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: MacOS 11/.6 Intel
Browser: Firefox 92.0.1

**Comment by apastuszak** [comment]
Confirmed I am having the issue on Microsoft Edge as well using the Chromium version of the extension.

**Comment by apastuszak** [comment]
Tried this on Firefox for Linux and it does not fill in the TOTP code, but it also doesn't popup the error message I get on Mac. It just doesn't do anything.

**Comment by varjolintu** [comment]
What's the website? Does the 2FA page URL differ from the entry URL? Do you have multiple credentials for the site?

**Comment by apastuszak** [comment]
github.com was the one I was testing on. I only have one set of credentials. I went into my entry for Github and changed the URL to be the exact URL of the Github 2FA page: https://github.com/sessions/two-factor

**Comment by apastuszak** [comment]
Just tried on discogs.com and got the same error. So, it's not just github.

**Comment by apastuszak** [comment]
switched it to https://github.com. Getting the same error on Linux and Mac.

**Comment by varjolintu** [comment]
Are you able to debug the extension and see where the problem might be? I can give some directions.

**Comment by Slater91** [comment]
I am seeing the same behaviour with Firefox on Linux when trying to fill in the TOTP for my WordPress blog.
Looking in about_debugging, this is the message that pops up whenever I try to fill the TOTP:
` Cannot send activated_tab message:  Error: Could not establish connection. Receiving end does not exist.
    switchTab moz-extension://30062923-f1ed-46bd-8ff0-3e528590fcad/background/page.js:203`
I hope this proves helpful. Let me know if I can be of any more assistance.

**Comment by totpet** [comment]
I have the same error on 1.7.10.1, KeePassXC 2.6.6 in Ubuntu Firefox 94.0, this appears in the add-on console: ` Error 15: No logins found    keepass.js:1183:13`. I only get it when using the context menu, not when clicking the button in the field itself. The  warning popup appears in both cases.

**Comment by moeffju** [comment]
I've been seeing this for a long time including now on Firefox 96. If the database was open and active and the TOTP overlay button appears, that usually works, but if I have to reopen the database while already on the target page, there is no TOTP button and the right-click menu only gives "No TOTP found", even after redetecting login fields. Funny enough it _does_ suggest the correct password entry if it's not been saved/remembered yet, so it should really know the TOTP.

**Comment by moeffju** [comment]
Hmm, I was pretty sure that Firefox 96.0 was the current stable version because it dropped the beta suffix a few days ago, but you're right, it's not been officially released yet. I'll try a parallel install of stable and I'll let you know.

**Comment by Slater91** [comment]
> @moeffju Does this happen with the stable Firefox release?

I can chime in to confirm that it does. In my case, though, it doesn't work even when the database is already open and active.

**Comment by moeffju** [comment]
If I choose custom login fields, then skip username & password and select the input as OTP field, then reload the page, the bubble icon shows up and that works.

**Comment by varjolintu** [comment]
I'll check the behavior with Amazon. I've had hard time reproducing these kind of things.

**Comment by varjolintu** [comment]
@moeffju Just tried logging to amazon.de and had no problems with it. I have the TOTP icon visible and it fills just by clicking that. There's no need to choose credentials from the popup unless the TOTP filling totally fails and somehow it doesn't find it. The toolbar icon always shows a question mark if there's credentials available.

**Comment by varjolintu** [comment]
@moeffju Do you have amazon.de set to Site Preferences? Seems they've changed the login URL again and the automatic detection was broken for me. The popup suggested to add a Username-Only option for the page, and `https://www.amazon.de/-/en/ap/*` was added to Site Preferences with Username-Only option enabled. Are you using that?

**Comment by moeffju** [comment]
I think I have an idea what might be the issue. I use Amazon Smile, and I had installed the [AmazonSmiley extension](https://addons.mozilla.org/en-US/firefox/addon/amazon-smiley/) to automatically redirect Amazon Storefronts to the Smile subdomain. So my login flow looks like this:

1. I type amazon.de in the URL bar
2. Smiley redirects to https://smile.amazon.de/gp/chpf/homepage?orig=%2F
3. I tap the sign in link in the top right corner
4. This loads https://smile.amazon.de/ap/signin with openid params, which has a username input field. KeePassXC-Browser does not offer to autofill. When I _Redetect login fields_ it offers to add a single-username option. I do that, it stores in site preferences. Then I autofill and submit the form.
5. This loads https://smile.amazon.de/ap/signin (without query args) and shows my username in text and a password field. KeePassXC-Browser offers to autofill, which works. I click submit.
6. This loads the 2FA input on https://smile.amazon.de/ap/mfa, which has only one input field. KeePassXC-Browser does not offer to autofill. Right-click fill TOTP does nothing, not even an error message.

![2FA login prompt](https://user-images.githubusercontent.com/14829/148382205-f8e8e632-6df7-4f27-8da6-d02dc5f1f60f.png)

So something is different between the Smile login flow and the regular.
It's not due to the extension - the same thing happens when I manually go to smile.amazon.de and try to log in.
Without the extension, logging in through the main amazon.de site works incl. the TOTP.

For reference, the Site URL in my KeePass DB was set to 'https://amazon.de/', but I also made one run with 'https://smile.amazon.de/' which made no difference in the result.

**Comment by moeffju** [comment]
I just noticed today that the same issue happens with PayPal, but unfortunately it was in the paypal popup flow so I couldn't click the toolbar icon. Anyway, TOTP was not found, stored entry has 'https://www.paypal.com/' as URL and there were no site preferences. It's really weird.

**Comment by Slater91** [comment]
It does happen on my Wordpress blog, so I would be happy to create a user for any developer who would like to test it there.

**Comment by varjolintu** [comment]
@Slater91 That would be helpful. You can share the credentials for example via Matrix.

**Comment by Slater91** [comment]
@varjolintu (whom I thank) helped me delve deeper into the matter and we found that the issue was with my Firefox extension going amok. Removing it, restarting Firefox and re-installing it fixed the issue. In case other people haven't tried this, I suggest them to try it.

**Comment by varjolintu** [comment]
Please check if these changes fixes the issue: https://github.com/keepassxreboot/keepassxc-browser/pull/1530

**Comment by moeffju** [comment]
Unfortunately the issue has recurred, on a different site, mocoapp.com, with version 1.7.12.

MOCO uses per-tenant subdomains, so if the tenant is `example`, the URLs are:

* login: https://example.mocoapp.com/sessions/new
* 2fa: https://example.mocoapp.com/otp/new

the form on the latter looks like this:

```
<form class="simple_form last form-horizontal js-focus-first" id="new_session_otp_form" novalidate="novalidate" action="/otp" accept-charset="UTF-8" method="post"><input type="hidden" name="authenticity_token" value="…" autocomplete="off" /><input class="string required form-control input-lg tc" autocomplete="off" placeholder="123 456" maxlength="19" size="19" type="text" name="session_otp_form[otp]" id="session_otp_form_otp" />
<p class='help-block'>Alternatively, enter the recovery code</p>
<input value="/…" autocomplete="off" type="hidden" name="session_otp_form[redirect_to]" id="session_otp_form_redirect_to" />
<div class='form-group mt50'>
<div class='col-xs-offset-2 col-xs-12'>
<input type="submit" name="commit" value="Login" class="btn btn-default btn-success" />
<a class="btn btn-default" href="/activities">Cancel</a>
</div>
</div>
</form>
```

My entry in KPXC has the full tenant domain in its URL field, so `https://example.mocoapp.com/`.

I’ve already asked them to add `autocomplete="one-time-code"` to the input field, but I am not hopeful that that would fix it if the manual approach (right-click field > KeepassXC-Browser > Fill TOTP) does not.

**Comment by varjolintu** [comment]
@moeffju Does it help if you define the TOTP field using Custom Login Fields?

**Comment by moeffju** [comment]
@varjolintu I tried the following:

1. Toolbar icon > Choose custom login fields
2. Skip username, Skip password, choose input field for TOTP
3. Reload page

This causes the speech bubble icon to appear in the field, but clicking it still results in the "Warning! No TOTP found!" message. Same for right-click > Fill TOTP.

**Comment by varjolintu** [comment]
@moeffju In the TOTP page, does it still show a question mark in the toolbar icon? If so, try selecting credentials there first and then fill. This should be fixed in the next version, and it does that automatically if only one TOTP is found.

**Comment by moeffju** [comment]
@varjolintu No, there is no indicator.

Page with input field and bubble icon:
![image](https://user-images.githubusercontent.com/14829/164456517-b86967a7-c68d-4ed6-b6ff-0718809009c7.png)

Toolbar button:
![image](https://user-images.githubusercontent.com/14829/164456550-297932c8-0769-4b85-bbba-edb4054e31f2.png)

Toolbar button popout:
![image](https://user-images.githubusercontent.com/14829/164456582-b2561e54-67d9-4250-ad15-d40bd8069ebf.png)

Both clicking the speech bubble indicator and right-click > Fill TOTP result in the same "Warning! no TOTP found!" message.

**Comment by varjolintu** [comment]
@moeffju Hmm. So it doesn't find any credentials for the site. https://github.com/keepassxreboot/keepassxc-browser/pull/1580 should fix this though, because it allows you to fill credentials with looser restrictions.

**Comment by moeffju** [comment]
I’ll try loading the extension from dev later and see if that fixes it!

**Comment by moeffju** [comment]
Loading temporary addon, reloading, and selecting the credential once from the icon - then the bubble icon in the input works as well. So, confirmed fixed by #1580!

**Comment by theking2** [comment]
I had exactly the same problem the text "Warning! No TOTP found. " Is a bit of a misnomer. 
If there are multple accounts available for the specific url one _has_ to select an item from the list of available entries. On github I have a number of machine accounts:

<img width="472" height="386" alt="Image" src="https://github.com/user-attachments/assets/591240ee-5fff-4f98-b0c3-c690c8775756" />

After selecting the right one the totp _is_ found and entered.

**Comment by qoldey** [comment]
> I had exactly the same problem the text "Warning! No TOTP found. " Is a bit of a misnomer. If there are multple accounts available for the specific url one _has_ to select an item from the list of available entries. On github I have a number of machine accounts:
> ...
> After selecting the right one the totp _is_ found and entered.

I am running into this same 'issue', and am wondering if there is any workaround that has been found?

In my case, I am logging into "https://login.microsoftonline.com/login.srf" where I have two accounts saved, but only one of them actually has a TOTP code assigned to it. The actual site saved in-app is just "https://login.microsoftonline.com" if that has an impact.

<img width="1380" height="160" alt="Image" src="https://github.com/user-attachments/assets/80092542-6317-4701-beb0-67842679e1ba" />

It may be tedious to manually click the plugin icon every time to select the account with a TOTP code, when the other that shows up in the menu will never be used if I have gotten to this screen asking for TOTP. For context, the "O" account redirects to an external verification site after entering an email/password on "https://login.microsoftonline.com/common/oauth2/..."

<img width="368" height="201.5" alt="Image" src="https://github.com/user-attachments/assets/fad73f86-6d3e-4e79-b912-08f9d9f879b0" />

Additionally, these accounts do not actually show up within the menu until _after_ I click on the "Fill TOTP from KeePassXC" button.

<img width="453.5" height="153.5" alt="Image" src="https://github.com/user-attachments/assets/81f60539-5f34-4aa8-93ff-a5635d961244" />

---

Is there a way to detect that the site I am viewing is asking for a TOTP code, then only show accounts which have a TOTP available, or automatically fill the value after selecting the "Fill TOTP..." option if there is only a single account? Maybe a drop-down menu similar to what we see in other pages that use passwords on sites with multiple accounts?

<img width="303" height="225.5" alt="Image" src="https://github.com/user-attachments/assets/7ebcc3a4-32d5-4a1c-87be-aefd8149633b" />

Should I instead be managing my links in-app with specific sub-pages?

Sorry to post on an old/closed issue, should a new issue be opened for this?

Thanks in advance.

**Comment by varjolintu** [comment]
@qoldey Gotta check that. I think it shouldn't require selecting a credential if only one of them has a TOTP set. If it does that, it should be fixed.

**Comment by theking2** [comment]
> [@qoldey](https://github.com/qoldey) Gotta check that. I think it shouldn't require selecting a credential if only one of them has a TOTP set. If it does that, it should be fixed.

If you do that please also change **Warning: No TOTP found** to a more descriptive **Please select the entry for the TOTP**

**Comment by teal-bauer** [comment]
And maybe even pop the list of possible matches with TOTP up near the icon, right now I always have to click the browser toolbar icon, sometimes Redetect login fields, then try the TOTP icon again for the list to show up.
