### ISSUE TITLE
Popup Bar kann nicht deaktiviert werden

### ISSUE THREAD

**Issue by dobrist61** [keepassxreboot/keepassxc-browser#1421]
Die Popup-Leiste oben, mit der Bemerkung "Nicht erneut für diese Seite fragen"  (siehe Beilage), kann nicht deaktiviert werden. Die Meldung erscheint immer wieder, auch wenn der Haken gesetzt wird. HILFE.....

The pop-up bar at the top with the remark "Do not ask again for this page" (see enclosure) cannot be deactivated.  The message appears again and again, even if the check mark is set.  HELP.....

![Keepass](https://user-images.githubusercontent.com/91866188/135799302-fcc84041-04a6-4eef-abbd-a79d1732cf30.jpg)
.

**Comment by varjolintu** [comment]
What is the page URL so I could test it? Also, what URL is stored to the Site Preferences tab?

**Comment by dobrist61** [comment]
Hi,the URL in the Site Prefereces is:
https://quotes-global2.ubs.com/go/?login&locale=de-CH&NavLB_QG=1631515010


BRDaniel




    Am Montag, 4. Oktober 2021, 13:58:56 MESZ hat Sami Vänttinen ***@***.***> Folgendes geschrieben:  
 
  


What is the page URL so I could test it? Also, what URL is stored to the Site Preferences tab?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by varjolintu** [comment]
Try enabling "Save Domain Only" option from the settings. Or delete that URL from Site Preferences and add `https://quotes-global2.ubs.com/go/*` there manually with the same ignore option enabled.

**Comment by dobrist61** [comment]
Hi Sami
I couldnt find this option, can you explain me, where in the menue to find it?

Thanks
BRDaniel


    Am Montag, 4. Oktober 2021, 18:14:09 MESZ hat Sami Vänttinen ***@***.***> Folgendes geschrieben:  
 
 


Try enabling "Save Domain Only" option from the settings. Or delete that URL from Site Preferences and add https://quotes-global2.ubs.com/go/* there manually with the same ignore option enabled.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by varjolintu** [comment]
_Settings_ -> _Saving Credentials_ card.
