### ISSUE TITLE
Cannot choose from multiple logins on Linux Mint

### ISSUE THREAD

**Issue by mariomadproductions** [keepassxreboot/keepassxc-browser#1422]
## Expected Behavior
Clicking on the keepassxc icon in the login field should display a drop-down with all the logins in the database for that website

## Current Behavior
This works on Windows with chromium, but not on Linux Mint with chromium. On Linux Mint, clicking the icon just inputs one of  the saved logins (the lastest created one?).

## Possible Solution
Not sure, I think this is a bug.

## Steps to Reproduce (for bugs)
1. Go to a login page, e.g. https://accounts.google.com/
2. Click the keepassxc icon in the username box

## Debug info
No javascript console messages
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Linux Mint 20.2 Cinnamon
Browser: Chromium 94.0.4606.71

**Comment by varjolintu** [comment]
Interesting. What are the entry URL's?

**Comment by mariomadproductions** [comment]
for google, its simply `https://accounts.google.com/`. same sort of thing for other sites.

**Comment by varjolintu** [comment]
Does it make any difference if you make a new entry with identical information to the one that doesn't work?

**Comment by droidmonkey** [comment]
Do you have "Return best matching credentials " enabled on your Linux keepassxc? Under application settings then browser integration.

**Comment by mariomadproductions** [comment]
> Does it make any difference if you make a new entry with identical information to the one that doesn't work?
Well its not that just one doesn't work, you can (and I do) have more than two accounts on some websites. Only the last-made account shows up.

**Comment by varjolintu** [comment]
> > Does it make any difference if you make a new entry with identical information to the one that doesn't work?
> 
> Well its not that just one doesn't work, you can (and I do) have more than two accounts on some websites. Only the last-made account shows up.

Hmm. Does any of the sorting options affect what credentials are shown?

**Comment by mariomadproductions** [comment]
Well that particular sorting option makes not difference. Either way its set, the last-created login is inputted into the field.

**Comment by varjolintu** [comment]
What about the different sorting options in the extension settings as I asked before?

**Comment by droidmonkey** [comment]
Yah that is supposed to be disabled

**Comment by mariomadproductions** [comment]
> What about the different sorting options in the extension settings as I asked before?

Not really sure which ones you mean, sorry.

**Comment by varjolintu** [comment]
<img width="644" alt="Screenshot 2021-10-04 at 21 35 17" src="https://user-images.githubusercontent.com/24570482/135905606-843f59cd-f2db-427d-96bb-c97c9ba51fab.png">

Just want to make sure the possible bug is not related to that.

**Comment by mariomadproductions** [comment]
I tried each of the options (refreshing the google login page each time), and it didn't make a difference unfortunately.

**Comment by varjolintu** [comment]
This problem would need some content script debugging to see if there's actually one or more credentials retrieved from KeePassXC. How is your KeePassXC installed in Linux? Does it matter if it's installed via PPA or used from AppImage?

**Comment by mariomadproductions** [comment]
Installed via PPA.

**Comment by varjolintu** [comment]
> > This problem would need some content script debugging
> 
> Is this something I can do? Or is this more something for developers to try on their end?

You can also do it. It's hard for us to find these kind of problems if we cannot reproduce the exact bug you're having.

**Comment by mariomadproductions** [comment]
Okay, well I am happy to test/debug things.

**Comment by mariomadproductions** [comment]
(Assuming you give me specific instructions.)

**Comment by varjolintu** [comment]
- Open Web Developer tools on the login page, select Sources/Debugger tab, upper left double arrow menu should be set to Content scripts with Chromium-based browsers
- Search from KeePassXC-Browser from the tree menu, open `content/keepassxc-browser.js`
- Put a breakpoint to line 1582. It should be the first line inside `kpxc.retrieveCredentialsCallback()` function
- Reload the page with database open. The `credentials` variable should show all credentials for the page.

**Comment by varjolintu** [comment]
Oh. Then I suggest you debug the `autocomplete.js` and see if the credentials are there. And I forgot to ask earlier, does the extension popup (from the icon) show all credentials? Trying to narrow down the possible point where this strange behaviour happens.

**Comment by mariomadproductions** [comment]
The extension pop-up doesn't appear at all - when I click the icon, the last-created credentials are entered.

I added breakpoints for line 61 ( `async showList(inputField) {`) and line 152 (`getAllItems()`) in `autocomplete.js`, refreshed the page and clicked the keepassxc icon, but it doesn't seem like those functions were called. But maybe those weren't the right functions to set breakpoints on.

**Comment by mariomadproductions** [comment]
Sorry, I mean the debugger shows various variables when the breakpoint is triggered, including the relevant credentials.
And I was also confirming that you were correct when you suggested "the popup doesn't appear at all".

**Comment by varjolintu** [comment]
I'm a little confused here. Previously you said the extension popup doesn't appear at all, now it does.
So the debugger shows all credentials for you, but Autocomplete Menu lists only one of them? And now the popup works and it shows them all?

**Comment by mariomadproductions** [comment]
Here's a demonstration video:
https://user-images.githubusercontent.com/9919020/137531803-e3da504e-1774-4da3-9e57-7d3a3b3eb2a5.mp4

**Comment by varjolintu** [comment]
I did exactly the same credentials for the same page and I cannot reproduce the bug.

More breakpoint locations that could help:
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js#L1419
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/autocomplete.js#L84

Those should show both logins.

**Comment by mariomadproductions** [comment]
The keepassxc-browser.js breakpoint is triggered and the "scope" panel in the debugger displays some info on the two logins. The autocomplete.js breakpoint does not seem to trigger.
