### ISSUE TITLE
temporarly turn the keepassxc-browser extension off

### ISSUE THREAD

**Issue by hugodu69** [keepassxreboot/keepassxc-browser#1424]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

in some situations the firefox extension interfere with the UX of a web page, such as it makes it impossible to operate some actions, by hiding things or overwriting operations, it literally prevents me of using a web page

then i have no choice but to open the settings in a new tab and disable keepassxc-browser (or a part of it, like autocomplete, which shows the dropdown list, and without it, keepassxc is almost of no use, for each time where i have several credentials)

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )

that could be like a button "on-off" in the pop up windows, alongside the blue `redetect login fields` for exemple ? many extensions have an "on-off" button, which disable the extensions either for this specific tab or untill you turn it on again (i don't think this second option is necessary,  because it's rather rare that the keepassxc extension is a probleme)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

here are two exemples where i'm completely stuck because of keepassxc :

1. i receive an invitation for a shared folder on nextcloud : this is a simple page with one single password field, and this password is not already in my keepasxc database (but i have other nextcloud passwords for this base url, so they will show up). So i fill the field with the password, but i cannot validate it ! indeed, if i press enter, this will not validate the POST action, this will instead autocomplete (therefore replace) my password with the first one of the list that showed up from keepasxc ; and if i want to validate by clicking the "send" button to the right of the field, i cannot neither because it is replaced by the keepasxc icon
2. still in nextcloud, i'm using the app cospend, and there is a field to choose a group name among groups that already exists. This field works like this : when i focus on it, the cursor appears waiting for my input, and a drop down list of choice appears, among which i have to click, and updating while i'm typing. i can't enter the name and validate, i have to click on the list. But i absolutely cannot do it ! indeed, the list is hided behind the keepassxc list of proposal for password (because for some reason it think this is a password field)

in both situation, i need to temporarily disable keepasxc from my browser, that's too bad

(actually, for the first situation, i could definitely disable the function to `Activate username field icons` in the settings, so i could always click on the send button, without the keepassxc icon hiding it)

**Comment by varjolintu** [comment]
> if i disable the autocomplete (which is what i did in my situation), once and for all, i can't use keepassxc when i have several passwords for one url, because it automatically fill it with the first one (or did i miss a feature ?)

You can use the popup (the extension icon from browser's toolbar) to select credentials when Autocomplete Menu is disabled.

**Comment by hugodu69** [comment]
interesting :) i tried and it didn't work, but i might have done something wrong
I think i wouldn't do that because it benefits for rare situations, but is a downgrade for more common situations (i prefer to have the proposals as a list in most of the cases

anyway, i already have workarounds for these situations, i didn't post this issue to ask for helps, even though i appreciate the ideas :) that was a feature request (ho damn, i just realized i didn't put the tag "feature request" ! i don't know how to do that ?)

**Comment by michielvanerp** [comment]
Same here: I cannot drag tasks in the Google Tasks sidebar at https://mail.google.com when I have the plugin enabled. When I add that address to the site preferences and 'disable all features', the problem remains. I need to disable the complete extension to enable drag & drop behavior again.

**Comment by varjolintu** [comment]
@michielvanerp That's a bug we've already fixed.

**Comment by michielvanerp** [comment]
@varjolintu Ah, thanks! I guess I've to wait for the plugin to be back in the Chrome store again, as I've read in another post.

**Comment by droidmonkey** [comment]
Just disable the extension in the browser
