### ISSUE TITLE
Browser plugin ignores password generator setup

### ISSUE THREAD

**Issue by frasou** [keepassxreboot/keepassxc-browser#1425]
## Expected Behavior
The browser plugin should respect a password generator setup in main app.

## Current Behavior
When a password is generated through the browser plugin, it ignores characters which are mentioned in "Also choose from:" and "Do not include:" fields in the password generator of the main application.

## Possible Solution
The browser plugin should respect whole passwd. generator setup.

## Steps to Reproduce (for bugs)
1. setup some characters to "Also choose from" field
2. go to a web browser, activate passwd. generator through browser plugin
3. try to generate several passwords - none of them will have requested characters
4. try the opposite approach - write something to "Do not include", repeat step 2-3 and unwanted characters are still there

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 92.0

**Comment by droidmonkey** [comment]
Will be corrected in keepassxc 2.7.0 with pulling up the native generator
