### ISSUE TITLE
Move location of username popup to above entry box <FEATURE REQUEST>

### ISSUE THREAD

**Issue by vliggio** [keepassxreboot/keepassxc-browser#1427]
## Expected Behavior
Instead of hiding behind browser autocomplete dropdown, the KeePassXC-Browser item should pop up above the login box

## Current Behavior
Username is hidden by browser provided autocomplete entries. Have to click on ESC button to get the autocomplete entries to disappear.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: MacIntel
Browser: Chrome/Chromium 94.0.4606.81
<img width="401" alt="Screen Shot 2021-10-15 at 15 57 42" src="https://user-images.githubusercontent.com/2916193/137546943-d5bb69c6-4e2b-42ad-a669-141b845c57c7.png">
<img width="381" alt="Screen Shot 2021-10-15 at 15 56 16" src="https://user-images.githubusercontent.com/2916193/137546962-58ebca5a-4017-4a41-b9af-51b913def4b0.png">

**Comment by varjolintu** [comment]
I'm not 100% sure what do you mean by this request? Could you elaborate some more? Thanks.

**Comment by varjolintu** [comment]
> I've got the same issue on Brave. The built-in Password manager from Brave (Chome?) has a higher Z-index than KeePassXC-browser extension. That way you can't see the KeePassXC entries right away. You'll have to press ESC to make the built-in psw manager disappear in order to accesss the KeePassXC menu.
> 
> @vliggio Thanks for the ESC-key tip. I missed that 🤦‍♂️
> 
> KeePassXC - 2.6.6 KeePassXC-Browser - 1.7.10.1 Operating system: Win64 Browser: Chrome/Chromium 96.0.4664.45

It's not recommended to use two password managers at the same time. It can cause strange behavior.

**Comment by MKBontwikkeling** [comment]
@varjolintu I disabled everything I could disable in Brave. Maybe deleting all the passwords in Brave will help, but that's an unnecessary workaround and not very user friendly.

**Comment by vliggio** [comment]
It's the browser field autocomplete, not password management. I do not use chrome password manager at all. But field autocomplete is pretty useful.

**Comment by varjolintu** [comment]
It's highly probable that browser's own autocomplete doesn't even have a `z-index`, but it's a built-in feature and there's no way to get on the top of that.
