### ISSUE TITLE
Use Port in URL

### ISSUE THREAD

**Issue by patrick7** [keepassxreboot/keepassxc-browser#143]
KeePassXC-Browser should also take a look on the port specified in URL. I have 2 SSH tunnels (Local Port 1000 & 1001), and KeePass always shows the password of both entries on both port 1000 / 1001

**Comment by varjolintu** [comment]
This can be accessed using `document.location.port` so it shouldn't be so hard to do.

**Comment by varjolintu** [comment]
This needed a change to KeePassXC side because the credentials should be ignored as soon as possible if the port doesn't match. PR is for version 2.3.4.
