### ISSUE TITLE
KeePassXC Browser Not Detecting

### ISSUE THREAD

**Issue by ToeJet** [keepassxreboot/keepassxc-browser#1430]
Originally posted under KeePass at https://github.com/keepassxreboot/keepassxc/discussions/7049.  Reposting here since it is the more appropriate forum.

I am running KeePassXC with browser plugin on multiple linux machines. Firefox on both Ubuntu 20.04 LTS and Fedora 34. I encounter issues where I will load a login page but the plugin does not detect any fields. I click the plugin icon (added to shortcut bar) then click redetect login fields. It still does not find login fields. I then reload the page (F5 or reload icon) and all fields are detected. Is there some setting or configuration that could be causing this issue?

## Expected Behavior
Login fields should detect from redetect login button.

## Current Behavior
Will not detect fields without page load.

## Possible Solution
It is possible that the login detection failure is causes page redirects (i.e.  Login redirects to session specific login page) with the plugin somehow remembering the original page.  When reloading the final page,  the plugin can properly detect since no redirection.

## Steps to Reproduce (for bugs)
1. Start Firefox
2. Login to office 365 for webmail.
3. Redirects to a Company login page.
4. No login fields detected
5. Click plugin -> redetect logins.
6. No login fields detected
7. Reload  page
8. Login fields detected.
9. If I do not close firefox,  login page will redetect.

## Debug info
KeePassXC Version: 2.6.6
KeePassXC-Browser Version: 1.7.9.1
Operating system: Linux
Browser: Firefox

**Comment by amandabee** [comment]
I think I'm having the same issue.
I'm running KeePassXC version 2.6.6 on Ubuntu Linux and 
KeePassXC-Browser version 1.7.10.1


If I go into my KeePassXC-Browser settings at moz-extension://c485a669-674d-4a35-a513-78cb76a2dd92/options/options.html under "Connected Databases" it shows none found:

![image](https://user-images.githubusercontent.com/150791/142698373-ac409909-6554-4b3f-a8a2-76e24f732a87.png)

Clicking the "connect" button has no obvious effect.

**Comment by varjolintu** [comment]
@amandabee Check that you are not running Firefox as a Snap. You can check your binary path from `about:support`.

**Comment by lolzim** [comment]
Hi, same here on Mac (macOS 11.6.1, firefox 94.0.2, keepassxc 2.6.6 & KeePassXC-Browser 1.7.10.1)
Clicking the 'Connect' button does nothing and the connected database no longer is connected to either KeePassXC and/or Firefox:

![image](https://user-images.githubusercontent.com/20860210/143575452-cc50da2f-8968-4e0c-beb7-142ea66b1a55.png)

If I click on the 'reload' button:
![image](https://user-images.githubusercontent.com/20860210/143575503-14a7a98b-223b-4fa5-b216-49bc5af7df37.png)
(Key exchange failed)

The permissions are all green marked.

**Comment by varjolintu** [comment]
@lolzim https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration & https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide Report your findings.

**Comment by lolzim** [comment]
@varjolintu: thanks for spreading ideas :) I fixed it by uninstalling KeePass-Browser, quitting both KeePassXC & firefox, run firefox, install extension, quitting again, launching KeePassXC then Firefox, remade the link and, Tadam!, it now works again!

**Comment by jee-r** [comment]
Hi,

do you use Muti-Accounts Containers Add-on ? 
https://github.com/mozilla/multi-account-containers

Because i had the same issue when i open a web-site (no matter which one) in a container tab for the first time since firefox start. i need to reload with F5 or sometimes  `CTRL+SHIFT+R`. After that keepassxc-broswer detect corectly fields on web sites that i open i **this container** (eg. work_container), but if i open a web site in other new container (eg. banking_container) keepassxc-browser don't detect fields and i need to reload again ...etc

i hope this help

**Comment by varjolintu** [comment]
@jee-r Interesting. I'll check if containers have something to do with this. Usually it's just a corrupted Firefox profile if nothing helps.

**Comment by ToeJet** [comment]
Yes,  Muti-Accounts Containers Add-on is in use.  I doubt it is profile since it happens on multiple machines.  Clean build of Fedora 35 machine did not affect it.

**Comment by varjolintu** [comment]
I tested multiple sites with Multi-Account Containers (I also use it daily) and had no problems detecting credentials. Is anyone able to debug the content script when happens? Or at least see what the JavaScript Console says if there's any errors?

**Comment by ToeJet** [comment]
Experimenting seems to support the multi-account containers.   If I start firefox, then go to a bookmark/link/url that has an assigned container other than the current container,  it does not detect the credential field.  It does open in the assigned container. Redetect does not work.  If I then refresh the page which does not change containers,  it detects the field properly.  If I do not have to switch containers or have already hit the page in the browser session, it works fine.

**Comment by varjolintu** [comment]
@ToeJet I got it reproduced once and then hit a dead end. So there's definitely a bug somewhere, and I already have an idea. Thanks for testing!

**Comment by ph00lt0** [comment]
I have this exact issue in both Brave and Firefox on MacOS Monterey

**Comment by ToeJet** [comment]
> @ToeJet Could you test the current develop branch? I haven't been able to reproduce the bug with that. So it's probably already fixed.
Is there an easy way to install the development branch?

**Comment by ph00lt0** [comment]
@droidmonkey why is this closed. This issue still persists. I am unable to connect to any database from firefox on MacOS monterey

**Comment by droidmonkey** [comment]
Literally a hundred issues saying the same thing. READ THE TROUBLESHOOTING GUIDE.

**Comment by ph00lt0** [comment]
@droidmonkey nope, I even tried in a new completely empty firefox profile. Didn't work.

**Comment by ph00lt0** [comment]
![image](https://user-images.githubusercontent.com/15004290/158275328-4075f4a9-2117-4258-a638-753d55e38704.png)

All i am getting.

**Comment by droidmonkey** [comment]
Have you verified the json file is installed in the proper location?

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#macos

**Comment by ph00lt0** [comment]
@droidmonkey yep all seem good when going through that guide.

Only odd thing maybe that with `otool -L /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy` I am getting 
```
Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy:
        @loader_path/../Frameworks/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.15.0, current version 5.15.2)
        @loader_path/../Frameworks/libsodium.23.dylib (compatibility version 27.0.0, current version 27.0.0)
        @loader_path/../Frameworks/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.2)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```
Instead of `@executable_path` I have `@loader_path`

**Comment by varjolintu** [comment]
You could try to use `opensnoop` to detect file access with macOS (gonna add this to the guide):
`sudo opensnoop -n firefox-bin | grep org.keepassxc`

At least with that you verify the path is correct.

**Comment by ph00lt0** [comment]
@varjolintu very useful tool thank you. But I can see here as well that the paths are all correct.

**Comment by varjolintu** [comment]
@ph00lt0 It's supposed to be empty. Just verifying it exists.

**Comment by ph00lt0** [comment]
Any other suggestions? I can't seem to find any reason why this wouldn't work.

**Comment by varjolintu** [comment]
@ph00lt0 Did you confirm the script file points to the correct `keepassxc-proxy` location? One thing you can try is to completely remove any existing connection from KeePassXC from Database Settings and try to start from a clean slate.

**Comment by ph00lt0** [comment]
Yeah also removed all connections indeed, didn't do anything. 
I just reinstalled the KeepassXC app and now it seems to work. Have not been able to figure out what and where this went wrong.

**Comment by ph00lt0** [comment]
@droidmonkey, @varjolintu I think i have discovered what causes the issue. The add-on seems to work only with one firefox user profile. Now I use many different profiles, for different configurations, but it seems KeepassXC only connects to either one of them.

**Comment by ph00lt0** [comment]
@varjolintu yes I would do that, but the connect button doesn't seem to do anything in other profiles then the one that is working.

**Comment by varjolintu** [comment]
@ph00lt0 Well that sounds strange. Does the popup still show the Connect button? Or are you talking about the button in the Connected Databases tab?

**Comment by varjolintu** [comment]
The tab does not update the status in the current version. I'll be fixed of course. That overflow bug is already fixed. I'll make some tests using multiple profiles.

**Comment by jee-r** [comment]
related to https://github.com/mozilla/multi-account-containers/issues/2290
