### ISSUE TITLE
Won't connect to database on LibreWolf 93

### ISSUE THREAD

**Issue by gianmarcogg03** [keepassxreboot/keepassxc-browser#1436]
The extension won't connect to the database on LibreWolf version 93, it just gives me a `Key exchange was not successful.` error.
## Expected Behavior

Should connect to the database successfully.

## Current Behavior

It gives that key exchange error.

## Steps to Reproduce (for bugs)

1. Load a page or click "Reload" in the extension's popup.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.8.1
Operating system: Arch Linux
Browser: LibreWolf

**Comment by droidmonkey** [comment]
Use the custom browser feature on keepassxc in the advanced browser settings if on Linux or macOS.

**Comment by gianmarcogg03** [comment]
That worked, I set it to `~/.librewolf/native-messaging-hosts`. Thank you!
