### ISSUE TITLE
Autofill in other browser extension popups especially web3 wallets like metamask

### ISSUE THREAD

**Issue by gotjoshua** [keepassxreboot/keepassxc-browser#1437]
## Expected Behavior

I need the browser extension to autofill in urls like these:
### Metamask
moz-extension://9e3e1ff1-4ecf-7a4d-a09a-2ea557c30e11/home.html#
chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/home.html

### Binance wallet
chrome-extension://fhbohimaelbohpjbbldcngcnapndodjp/popup.html#/en/unlock

## Current Behavior
there is no way to add an entry, nor to detect fields. 
nothing happens when i use the context menu to "save credentials" 
nor when i click choose custom login nor redetect fields... no error no nothing.

i can switch to the KeepassXC window and use auto type, but i would love for this extension to make that step unneeded.

## Possible Solution
in the context menu have a way to choose an entry from KeepassXC (similar to how the android app does it)
also a way to remember the choice and offer to use it next time

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Mac
Browser: Chrome + Firefox

**Comment by varjolintu** [comment]
As far as I know injecting content scripts is not possible in extension's own pages, especially if it's from another extension. You'll have to rely on Auto-Type with these kind of situations.
