### ISSUE TITLE
keepassxc-proxy not starting on OSX and Brave Browser

### ISSUE THREAD

**Issue by grzegorz-borczuch** [keepassxreboot/keepassxc-browser#1442]
## Expected Behavior

When I launch Brave Browser (having browser integration enabled for Brave) an instance of keepassxc-proxy should be started.

## Current Behavior

No keepassxc-proxy instance available when Brave is up. When in Debug mode it logs `Failed to connect: Specified native messaging host not found.` When manually verified, correct `org.keepassxc.keepassxc_browser.json` file is present in `~/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts`.

## Possible Solution

The issue has been mitigated by configuring browser integration against regular Google Chrome browser. (enabling integration and installing keepassxc-browser extension). When such integration was enabled, `keepassxc-proxy` started to launch whenever either Brave and Google Chrome browser was launched.

Most probably root cause of the issue is that Brave Browser is looking for `org.keepassxc.keepassxc_browser.json` in wrong directory. Instead of looking into standard `~/Library/Application Support/BraveSoftware/Brave-Browser/NativeMessagingHosts` it must be looking into Google Chrome's specific folder, i.e. `~/Library/Application Support/Google/Chrome/NativeMessagingHosts`.

Since it looks keepassxc-browser extension is using native `browser.runtime.connectNative()` call to find the correct messaging host descriptor, it might not be possible to do much with it. Thus, I recommend adding information about this issue (and proposed workaround) in keepassxc-browser extension and in online documentation.

## Steps to Reproduce (for bugs)

1. Install KeepPassXC
2. Enable browser integration for Brave
3. Open Brave browser and install keepassxc-browser extension
4. Restart browser
5. Try to connect with KeePassXC desktop app using "Reload" button.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.9.1
Operating system: Mac (11.6.1)
Browser: Brave

**Comment by droidmonkey** [comment]
This is a bug with brave. It has been reported to them and on our issue list. Thank you!

**Comment by grzegorz-borczuch** [comment]
Thanks. Could you point me to an issue on yours issue list? Was trying to find is using "brave" keyword and wasn't able.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc/issues/6212

This is the extension issue board, tracking of native message installers and such is over on the application side.
