### ISSUE TITLE
KeePassXC doesn't want to connect with Chrome - Linux Mint 20.2 - All other browsers work.

### ISSUE THREAD

**Issue by bryn1u** [keepassxreboot/keepassxc-browser#1444]
## Expected Behavior
Connect KeePassXC-browser plugin to KeePassXC database.

## Current Behavior
There is no way to connect KeePassXC-browser with KeePass database. I always get 

> "KeePassXC-Browser has encountered an error:
> Key exchange was not successful."

The funny thing is, it works on all other browsers like Firefox, Vivaldi, Opera besides the Chrome.

## Possible Solution
Doesn't exists

## Debug info

KeePassXC - keepassxc 2.4.3, qt5ct: using qt5ct plugin
KeePassXC-Browser -  1.7.9.1
Operating system: Linux Mint 20.02
Browser: Google Chrome 96.0.4664.45 beta

> bryn1u@Proton:~/.config/google-chrome/NativeMessagingHosts$ cat org.keepassxc.keepassxc_browser.json 
> {
>     "allowed_origins": [
>         "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
>         "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
>     ],
>     "description": "KeePassXC integration with native messaging support",
>     "name": "org.keepassxc.keepassxc_browser",
>     "path": "/usr/bin/keepassxc-proxy",

**Comment by varjolintu** [comment]
Check if you are running a Snap version of Chromium. Sandboxed browser will not work.

**Comment by bryn1u** [comment]
> Check if you are running a Snap version of Chromium. Sandboxed browser will not work.

Im using only repo version of keepassxc and the same for chrome.

**Comment by varjolintu** [comment]
What does  `chrome://support/version` show?

**Comment by bryn1u** [comment]
> chrome://support/version

Says nothing:

> This site can’t be reachedThe webpage at chrome://support/version might be temporarily down or it may have moved permanently to a new web address.
> ERR_INVALID_URL

But the version is: Version 96.0.4664.45 (Official Build) beta (64-bit)

**Comment by varjolintu** [comment]
Sorry, `chrome://version/`

**Comment by bryn1u** [comment]
> Google Chrome | 96.0.4664.45 (Official Build) beta (64-bit)
> -- | --
> Revision | 76e4c1bb2ab4671b8beba3444e61c0f17584b2fc-refs/branch-heads/4664@{#947}
> OS | Linux
> JavaScript | V8 9.6.180.12
> User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
> Command Line | /usr/bin/google-chrome-beta --enable-crashpad --flag-switches-begin --flag-switches-end --origin-trial-disabled-features=CaptureHandle
> Executable Path | /opt/google/chrome-beta/google-chrome-beta
> Profile Path | /home/bryn1u/.config/google-chrome-beta/Default
> Variations | f475deb0-377be55a3e7d7783-8be3926f7e184ca7-49a0f45090a7075b-e839088216b16054-377be55a8e73c278-3f4a17df1fa5b2f3-377be55a59b6f412-377be55a60d4b352-377be55a5fff72eb-377be55a152bdf52-3f4a17dfb3249ec4-3f4a17dfa9ef513c-3f4a17df273268f8-b0c3cd256cb5e962-377be55a6e08fc3e-21c0b11e481fc7e7-8be3926feddd0d82-68d27168da89714-b2d39dc087f33ad6-59e9c05938eb801c-3f4a17df4d936449-37049b31e799dcad-67287f4aedb58ea9-377be55aa2629469-377be55a1bb6a450-5139e56d6c5f69af-709ee4c4deb1cb12-fefff3a47bd2c48-1d5726141e940a7c-ee63ae021c752ce9-7e8fd1fe76cbd0ec-18c8e9444701a278-3f4a17df47b5f350-377be55a7c2504d0-ca7d8d80f2cb61f-377be55aa2fd384c-5c0c03aa3f6e921e-b122a9ce5d77151b-377be55abf4029fe-a7ad20a4e3ec83a-73f1fa9f65570806-676edf5353fd5552-a745d337dd8d67e-3f4a17dff6f5c542-8cecea9fa582a1b8-ad75ce17fa659f2e-cab82eb6da2d8531-8b463fc2e87da360-e41752376a5f15b-3f4a17df56dcde30-ee63ae021d606bb5-cdda86d5d89faab1-57c5a2f6722b8030-547a33d95f2c0f7c-f9ffdd25e4a357e9-2045969cc129e4cd-377be55a3fd33f16-fb81768fd9384a1d-15ef174a2ba47366-5419e7bd248c3fbd-3f4a17dff96fd6bf-a1d01cddff5d84e6-75133ae0e79de56c-e6f4d7fa357a64de-e6f4d7fa8bccc03b-5419e7bd29c62d4-d70c498e178e8b37-d5ba3efbfacdb7bf-3beb05d7a1e2fead-3f4a17dfd809cc5d-377be55a727723f1-f6e4284e7a911e9f-80311101b75782da-f23d1dea8c8d8faf-28b04c22255dfea8-db94162b4962f2e-31b30f25e153f4cb-377be55aca5a2953-ff983c323487aa71-380815a5c2983992-377be55a8bfdd36f-e629ebb25fe247df-8dd458c2ad46906e-773120b2234de0a0-ff508b81261b9697-377be55ad3566fbd-2d3942684ea303a6-aea692d9f48aee36-377be55ac9e4cf65-12ede6a22d5bcfa8-f23d1dea950809af-f23d1dea77e44b8e-ee63ae029af490f6-3769bbad143c8a-3807f4b22e36b1b8-ce2253d3c1003591-1559097dfbe267b5-cc56f95a0da97d6-f23d1deaa8a03ccf-cfce2b51f323d3f0-377be55a5d2c15d5-c215f90e5176c13e-88055aa67760b5b2-3dd63aa6eb084fc2-377be55a9dea8d36-f23d1deae8c68789-b51e90ccee30fb75-8a392cc754410569-3f4a17dfad4acdda-5a06985c931c5f72-327d0ded494d8760-52325d437b2873c2-652559963ac60855-486e2a9cf48c01d3-8e682dbb63dcb6a3-7da8925ae706e746-9d9eea77f296190c-970d9ef14442aae2-d7f6b13cf690cf64-7158671eed1d377-e1cc0f1475f0f0a0-a5822863e2b18481-a90023b1e7e71889-4ad605756aa685f2-f417caf325692333-f23d1dea6ab03ba1-8cd0bc9c7975f5b5-bd3f65072d3dfd19-13a09d1c762bb3b2-c416a536e1368496-a2d707c6248e3a0-7e68dd203b96a1d-8c99120fdba92675-f23d1dea595f5eb0-ee63ae023673692f-aa4c63b8bef5c006-ffe1a538a16ee973-850c9543b4e05be7-3b0e14f21b4184a1-12040260662773da-dffd1505fb50494f-72cac062547e761a-3f4a17dfc3859e82-9bb82bbf5e31bb48-75513c66a461b170-377be55adef27776-f3cd32488d7344de-44ddd419733cb831-220b86f16598898b-377be55ab53f3ef9-a0b34ca02856aa31-21bd9a67
> 
>

**Comment by varjolintu** [comment]
Seems you are using a beta release. Probably the Native Messaging script is not at `~/.config/google-chrome/NativeMessagingHosts` but under `google-chrome-beta` or something like that. Add that path to KeePassXC's Browser Integration settings (Advanced tab) as Custom Browser and you're good to go.

**Comment by bryn1u** [comment]
> Seems you are using a beta release. Probably the Native Messaging script is not at `~/.config/google-chrome/NativeMessagingHosts` but under `google-chrome-beta` or something like that. Add that path to KeePassXC's Browser Integration settings (Advanced tab) as Custom Browser and you're good to go.

Ehh. I can't find that option:
"Add that path to KeePassXC's Browser Integration settings (Advanced tab) as Custom Browser and you're good to go."

**Comment by varjolintu** [comment]
Then make a symbolic link (or just copy the script file) to the beta config folder.

**Comment by bryn1u** [comment]
> Then make a symbolic link (or just copy the script file) to the beta config folder.

I copied to google-chrome-beta and yes, you're right it works like a charm now. Thanks for your help.
