### ISSUE TITLE
Google calendar issue after KeepassXC firefox extension update

### ISSUE THREAD

**Issue by jamz216** [keepassxreboot/keepassxc-browser#1446]
Starting today I am unable to drag google calendar appointments to new days/times. I followed Firefox's troubleshooting procedure and found that the KeepassXC extension for Firefox was causing the issue, and it seems the extension was updated today.

**Comment by varjolintu** [comment]
Strange. Gotta investigate this one asap.

**Comment by v-karbovnichy** [comment]
I just narrowed down problems happening on 2 my laptops to this issue.
I have 2 sites (after log in) that are affected up to complete unusability: https://notion.so and https://eyewire.org.

When will the extension have an update in Chrome Web Store? It's still 1.7.10 there.

**Comment by varjolintu** [comment]
@v-karbovnichy It's already submitted to the store. Firefox already updated for me.
