### ISSUE TITLE
KeePassXC-Browser blocks access to buttons in header of single page app

### ISSUE THREAD

**Issue by MartinKirchner** [keepassxreboot/keepassxc-browser#1449]
## Expected Behavior

![grafik](https://user-images.githubusercontent.com/17732361/142168565-32aaec2b-8464-465f-8448-42d10122b2a1.png)
Buttons in the header of the single page application CAS PIA are clickable.

## Current Behavior

Buttons are not clickable as if there is an invisible div.
It works if I deactivate the browser addin.

## Steps to Reproduce (for bugs)

1. Open https://login.cas-pia.com/pia/login?username=Robert+Glaser&action=autologin&demo=true&language=de in Firefox
2. Try to click logout button in the top bar.

## Debug info
Javascript console:
09:53:07.185 window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. login:24:104
09:53:07.312 unreachable code after return statement
PIA:293
09:53:07.482 Versuch, eine verbotene Kopfzeile zu verwenden, wurde abgelehnt: Referer 2 PIA:201:2235
09:53:17.059 unreachable code after return statement
PIA:293
09:53:17.375 Versuch, eine verbotene Kopfzeile zu verwenden, wurde abgelehnt: Referer 5 PIA:201:2235

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10
Operating system: Win64
Browser: Mozilla Firefox 94.0

**Comment by varjolintu** [comment]
Already fixed. New release is going online asap.

**Comment by MartinKirchner** [comment]
You are great! Thank you.
