### ISSUE TITLE
Extension crashes / locks up browser due to infinte loop

### ISSUE THREAD

**Issue by mymindstorm** [keepassxreboot/keepassxc-browser#145]
## Expected Behavior
The browser does not crash when opening a page

## Current Behavior

Browser crashes when opening page

## Possible Solution

Someone needs to stop the loop:
![screenshot_2018-05-10_17-17-19](https://user-images.githubusercontent.com/27789806/39897146-9e227664-5476-11e8-9120-040d559be588.png)
Ignore the invalid tab id message, that was probably because I managed to close the tab

## Steps to Reproduce (for bugs)

1. Connect a database to the extension
2. Browse to http://humblebundle.com
3. Wait ~5 seconds for everything to lock up

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.1.1
Operating system: Fedora 27
Browser: Firefox 59.0.2
Proxy used: NO

**Comment by droidmonkey** [comment]
It doesn't crash in chrome but it certainly is taking up a bunch of CPU. I wonder if this is due to the dynamic element listener.
