### ISSUE TITLE
Keepass extention on new chrome v96 breaks drag and drop

### ISSUE THREAD

**Issue by vlebert** [keepassxreboot/keepassxc-browser#1450]
Hi everybody

Since this morning I had issues in chrome and I realised that keepass extension is guilty :) Disabling it solve the issue

The issue : when the extension is activated, drag&drop in websites is buggy (for example in google calendar, moving an event by dragging is impossible)

Chrome :
Version 96.0.4664.45 (Build officiel) (64 bits)

Keepass Chrome extension:
Version
1.7.10

Anyone have the same issue?

**Comment by varjolintu** [comment]
Already fixed, and the new release has been submitted to Chrome Web Store hours ago. Just wait for the update to arrive.

**Comment by vlebert** [comment]
Thanks
