### ISSUE TITLE
Security verification is not working in chrome / binance.com

### ISSUE THREAD

**Issue by ismaczny** [keepassxreboot/keepassxc-browser#1451]
## Expected Behavior
https://accounts.binance.com/
On next page is security verification with puzzle to slide bot not is not working (in chrome)
Security verification is working correctly in chrome when extension is disable

## Current Behavior

A week ago it was working fine! But now it doesn't work in chrome and I have to do it in firefox.
I want to make security verification in chrome.

## Possible Solution

Disable extension on chrome
Use firefox.

## Steps to Reproduce (for bugs)

1. Connect to https://accounts.binance.com/
2. Write (automaically) user and pass
3. Try to slide puzzle
4.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10
Operating system: Win64
Browser: Chrome/Chromium 96.0.4664.45

**Comment by droidmonkey** [comment]
Fixed and waiting for the store to update..
