### ISSUE TITLE
Chrome version 1.7.10 prevents clicking on certain sites (e.g. hbomax.com) 

### ISSUE THREAD

**Issue by AquaeAtrae** [keepassxreboot/keepassxc-browser#1452]
## Expected Behavior
On https://hbomax.com/ I should be able to click UI elements (buttons, etc) to navigate the site. 

## Current Behavior
On https://hbomax.com/ I see the mouse hovers over UI elements but clicking has no affect. 

## Possible Solution
Until fixed, only option is to uninstall the extension.

## Steps to Reproduce (for bugs)
With the KeePassXC-Browser 1.7.10 Chrome extension installed , I find I am unable to click any buttons on the popular https://hbomax.com/ website. I'm guessing it affects other websites with similar IO designs. I did not observe this problem prior to version 1.7.10. As soon as I uninstall the extension, the website works normally again.  

As there are no obvious error messages, it was very difficult to isolate and identify this errant extension, but once found the results are consistent and reproduceable. 

I will not be able to use the extension until this is resolved. Hoping you are able to resolve this conflict in the next release.

## Debug info
7x Failed to decode downloaded font: <URL>
7x OTS parsing error: invalid sfntVersion: 1008813135
​ Unrecognized feature: 'conversion-measurement'.
mc @ conversion.js:32
conversion.js:32 Unrecognized feature: 'conversion-measurement'.
mc @ conversion.js:32
​ Unrecognized feature: 'conversion-measurement'.
mc @ conversion.js:32
DevTools failed to load source map: Could not load content for https://play.hbomax.com/js/app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10
Operating system: Win 10
Browser: Chrome 96.0.4664.45 (Official Build) (64-bit)

**Comment by droidmonkey** [comment]
Already fixed and deployed
