### ISSUE TITLE
Invalid support email listed on official Chrome Web Store listing

### ISSUE THREAD

**Issue by AquaeAtrae** [keepassxreboot/keepassxc-browser#1453]
## Expected Behavior
Able to email support from Chrome Web Store.

## Current Behavior
Email bounces with error...
550 info@keepassxc.org That recipient is not allowed

## Possible Solution
Google search found this github so I'm reporting here instead.

## Steps to Reproduce (for bugs)
Send email to info@keepassxc.org

## Debug info
N/A

**Comment by droidmonkey** [comment]
Should be team@keepassxc.org

**Comment by varjolintu** [comment]
I've found absolutely no way to change the Group Publisher contact email address. It cannot be changed from Developer Dashboard or from groups.google.com. Contacted the support. Hopefully this will be solved soon.

**Comment by droidmonkey** [comment]
We can open up that email on our end if that's the case.

**Comment by phoerious** [comment]
I don't even want to know how much spam is being sent to that address already. But, oh well... I'll add it as an alias later. :roll_eyes:

**Comment by AquaeAtrae** [comment]
Looks like the official Chrome extension page is now offline. This is the URL that appears in both Google Search results and is referenced from the documentation at 
https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk

`
404. That’s an error.

The requested URL was not found on this server. That’s all we know.`

**Comment by varjolintu** [comment]
@AquaeAtrae We are aware: https://github.com/keepassxreboot/keepassxc-browser/issues/1457

**Comment by phoerious** [comment]
> I don't even want to know how much spam is being sent to that address already. But, oh well... I'll add it as an alias later. 🙄

Done.
