### ISSUE TITLE
Chrome extension got pulled from webstore (?)

### ISSUE THREAD

**Issue by cibolog** [keepassxreboot/keepassxc-browser#1454]
Used this [webstore URL](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk?hl=en) just yesterday, and now it is 404. Cannot find the extension via search on the webstore as well.

**Comment by varjolintu** [comment]
We know:
https://github.com/keepassxreboot/keepassxc-browser/pull/1447#issuecomment-972525492
