### ISSUE TITLE
Extension removed from Chrome web store

### ISSUE THREAD

**Issue by sbcgm** [keepassxreboot/keepassxc-browser#1455]
The KeePassXC extension was removed from the Chrome web store. The [link](https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk) in the [official documentation](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_install_the_browser_extension) yields a 404.

**Comment by varjolintu** [comment]
We already know.
See: https://github.com/keepassxreboot/keepassxc-browser/pull/1447#issuecomment-972525492
