### ISSUE TITLE
Addon not listed in the Chrome Store.

### ISSUE THREAD

**Issue by fbnkrs** [keepassxreboot/keepassxc-browser#1457]
## Expected Behavior
The Addon URL should bring you to the Addon page.

## Current Behavior
Error 404 not found

## Steps to Reproduce (for bugs)

1. https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk
2. Error 404

**Comment by varjolintu** [comment]
We know. I'll pin this issue because we get a new issue every fifteen minutes. Do not create duplicates, please.

Five hours ago I updated to the PR which is included in the fix:
> This did not go as planned with Chrome Web Store. I got en email hour ago which informed that they decided to take our extension down because it has an "excessive and / or irrelevant keywords" in the description. The violating content is "Fix".

> Didn't know release notes were a bad thing. Oh well, in the future there's just a link to the changelog. New version is already > submitted for re-view.

**Comment by fbnkrs** [comment]
Thank you very much

**Comment by rramaswamy1070** [comment]
Because of this, I started experiencing strange "side-effects" on some pages. A resize handle started exhibiting strange behaviour - became "sticky", i.e., once I clicked on it to resize the element, I couldn't release it. By the process of elimination, I found out that this extension was the culprit. How exactly it was affecting the resize handle, I have no clue.

**Comment by varjolintu** [comment]
Anyone having this issue can always download the zipped extension from the releases page and load it as a temporary extension. However, this only works if you modify the native messaging JSON script and change the extension ID inside it to the one temporary extension has.

Google, what's taking so long?

**Comment by varjolintu** [comment]
Still no news from Google. It has been over 48 hours already.

**Comment by varjolintu** [comment]
The extension is back online.
