### ISSUE TITLE
How to use same Key Exchange for multi Firefox Profiles

### ISSUE THREAD

**Issue by Narga** [keepassxreboot/keepassxc-browser#1460]
Hello,
I'm using Firefox on Windows/Linux and the KeePass database is syncing via Dropbox and OneDrive. That's mean I need same Key Exchange for 2 Firefox profiles when I switch between 2 OS.
In the past, I connected the first profile (on Linux) with KeePass then I copy complete 'connected profile' to Windows, it's possible to continue using on Windows after the KeePass database synced.
Yesterday, I refreshed the Firefox profile on Linux but I don't want to replace it on the Windows version.
So, in my opinion, I'm just need copy the KeePassxc-browser extension data files/config's string in old Firefox profile folder to the new one! But after I spent 2h to research about it, it's not found.
Is my method correctly? If yes, please help me solve it.
Thank you very much.

**Comment by varjolintu** [comment]
Is there any reason why you need the same key for both? Just connect both of them, upload your database and you can use it from both operating systems? Just use a different name for the keys.

**Comment by Narga** [comment]
Thanks, it's easy way.
But I wonder if my method is possible :D

**Comment by varjolintu** [comment]
It's possible but I don't recommend it. Also, it's not easy. In theory you could modify the extension's localStorage. And there's always a risk that gets corrupted. And that wouldn't work without modifying the extension source code, or by accessing the localStorage with some tools.
So I'd recommend that you take the easy way :)

**Comment by Narga** [comment]
Thank you very much. Your information is usefull, I won't invest more time about it.
