### ISSUE TITLE
KeePassXC causes mouse drag'n'drop issue in Hubspot Workflow editor

### ISSUE THREAD

**Issue by sacerro** [keepassxreboot/keepassxc-browser#1461]
## Expected Behavior
On drag'n'drop events, mouse should drag while left click is pressed and stop when left click release.

## Current Behavior

When left click and drag with mouse, there is no way to stop (drop). Is like mouse lose left click track.
If this extension is disabled, website works correctly.
I try to add hubspot in settings to ignore, but is not working. The only solution is disable extension.
![image](https://user-images.githubusercontent.com/1681325/142646138-e52bd5f9-b70d-4f66-b87d-301aefc7cdbe.png)

## Steps to Reproduce (for bugs)

1. Open a Workflow, section "actions"
2. Left click and drag mouse
3. Release left click and move mouse
4. Now you cannot stop drag effect.

## Debug info

No JS message was displayed.

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10
Operating system: MacIntel
Browser: Chrome/Chromium 96.0.4664.55

**Comment by varjolintu** [comment]
Duplicate with #1452.
