### ISSUE TITLE
Translation: when are they imported from Transifex ?

### ISSUE THREAD

**Issue by tenzap** [keepassxreboot/keepassxc-browser#1467]
I noticed the french translation is only partial.

However in transifex almost everything is translated. Status says: `50% reviewed 99.64% translated`

Many string in _locales/fr/messages.json are not translated and last update is 3years old (actually the file has never been updated since 1st commit)

What's wrong here?

**Comment by varjolintu** [comment]
We are pulling translations on every release build using `tx pull -af` which forces the pull from Transifex. Gotta check out why this problem happens.

**Comment by varjolintu** [comment]
Solved it. The name had been changed in transifex and the script didn't found a match anymore.

**Comment by tenzap** [comment]
Thanks for the new version containing the translations, but they haven't been updated here: https://github.com/keepassxreboot/keepassxc-browser/tree/develop/keepassxc-browser/_locales. Normal?

**Comment by varjolintu** [comment]
@tenzap This is normal. The latest versions are always in Transifex.
