### ISSUE TITLE
Bug: unable to save and auto-fill AWS IAM Role login type

### ISSUE THREAD

**Issue by cibolog** [keepassxreboot/keepassxc-browser#1476]
## Expected Behavior
When I log into [AWS Console](https://console.aws.amazon.com/console/home?nc2=h_ct&src=header-signin) as an IAM Role user (not the root user), I expect to be able to save and then auto-fill the multiple-step login form with OTP enabled.

## Current Behavior
Saving credentials with this login method does not work due to the additional field, which is neither login, nor password field - it's an account ID field, and I am unable to add it to a database entry as a string field. No prompt to save credentials after successful login appears either.

## Steps to Reproduce (for bugs)
- Have an AWS IAM Role account with OTP enabled
- Navigate to [AWS Console login page](https://console.aws.amazon.com/console/home?nc2=h_ct&src=header-signin)
- Manually assign the field types (including the account ID as string field #1)
- Enter valid credentials
- Press next (to get to the step with the OTP form)
- Enter OTP 
- Submit
Then it redirects to a different subdomain and there is no prompt at the top of the page to save the credentials. 

Maybe I'm doing something wrong, at least in regard with account ID field? No prompt after successful login seems like a bug.

## Debug info
- KeePassXC-Browser Version: 1.7.10.1
- KeePassXC Version: 2.6.6
- Operating system: Ubuntu 20.04
- Browser: Chromium

**Comment by varjolintu** [comment]
Related: https://github.com/keepassxreboot/keepassxc-browser/issues/432.

**Comment by git-noise** [comment]
Hello,

Also want to report, that manually selecting fields is not working as the TOTP is on another webpage. So manually selection username/password leads to TOTP not working on the next windows.

Best,

**Comment by varjolintu** [comment]
@git-noise Selecting custom fields shouldn't be needed for AWS, but still the page is not working for everyone. Extension's next release will allow you to select single fields as Custom Login Fields even if those are on the next "page".

**Comment by git-noise** [comment]
@varjolintu 
Great thanks a lot.
Yeah sadly I am in the case of the AWS console with IAM role, so the three fields Account ID, Username and Password

**Comment by varjolintu** [comment]
The latest extension version should allow selecting Custom Login Fields even from another page. Does it work properly that way?

**Comment by git-noise** [comment]
@varjolintu
Sorry just could test today, so it seems to work indeed, I can select TOTP on the separate page.
That plus String Field allows to handle the AWS IAM case in my setup.
Thanks!
