### ISSUE TITLE
Icon persists after auto-fill

### ISSUE THREAD

**Issue by nilueps** [keepassxreboot/keepassxc-browser#1478]
## Expected Behavior

The little green icon that appears next to auto-fillable inputs should disappear when clicked -- or at least after the page changes/updates.

## Current Behavior

After clicking the icon and login in, the icon persists on the next page. Sometimes it disappears on mouseover, sometimes not. Disappears after subsequent page changes.

## Possible Solution

Add an event listener for page/location change?

## Steps to Reproduce (for bugs)

1. Open a login form that KP can autofill
2. Click the auto-fill icon
3. Log in

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Do you have the site where this happens? Probably the detection for input field hiding is not working properly here.

The icon does and will not disappear after fill.

**Comment by fusionneur** [comment]
just a mention: resizing the window just a bit, makes the icon disappear

**Comment by varjolintu** [comment]
I repeat my question: what is the site?

**Comment by fusionneur** [comment]
In my case it is https://app.standardnotes.org/

**Comment by Wiggy2342** [comment]
For me this also happens for the Threema Web Client: [https://web.threema.ch](url). The KeepassXC icon stays after logging in, always at the same position on the page, overlaying the page content; stays at the same window position also when scrolling the content. It disappears when the windows is resized and then does not re-appear.

**Comment by yan12125** [comment]
On https://glowing-bear.org/ (a Weechat frontend), the icon persists after login. Is this the code to hide the icon?

https://github.com/keepassxreboot/keepassxc-browser/blob/9323eff6532f149199a23ef235a98b6b5820d948/keepassxc-browser/content/username-field.js#L120-L124

I do use custom login fields to make the hostname field as the username field.

> just a mention: resizing the window just a bit, makes the icon disappear

Nice workaround! Also works on https://glowing-bear.org/.

**Comment by varjolintu** [comment]
Made a fix. Feel free to test it.

**Comment by yan12125** [comment]
Thanks a lot! I can confirm #1677 fixes the issue on glowing-bear.org.
