### ISSUE TITLE
~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/ bash: user: No such file or directory

### ISSUE THREAD

**Issue by ncorder** [keepassxreboot/keepassxc-browser#1480]
Hello,

**Basic Issue**:
The file `/home/<user>/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/` does not exist:

```
usr@usr:~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser$ ls
Caches  profile.default  profiles.ini
usr@usr:~/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser$ 
```

**Why this matters**:

I'm attempting to follow the troubleshooting guide: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#linux

**Basic OS and version details**:
OS: Trisquel 9 Etiona

**Package information**:
```
Package: torbrowser-launcher
Version: 0.2.9-2ubuntu1
```

**Comment by droidmonkey** [comment]
Create the folder structure necessary and set that as a custom browser in the advanced browser integration settings.
