### ISSUE TITLE
Bug: when browser runs out of disk space keepassxc-browser loses it's handshake key

### ISSUE THREAD

**Issue by fishman** [keepassxreboot/keepassxc-browser#1481]
## Expected Behavior

When firefox runs out of space and doesn't allow access to browser localstore keepassxc-browser should not lose it's settings

## Current Behavior

When disk space runs low firefox disallows storing data. For some reason keepassxc-browser loses it's handshake information and on the next browser restart i am forced to reconnect to the database.

## Possible Solution

Maybe there is a way to check if that case is happen and keepassxc-browser suspends all attempts to store new config.

## Steps to Reproduce (for bugs)

1. fill harddrive until there is only a couple hundred megabytes of space left
2. firefox will issue a warning on running out of space
3. do anything with keepassxc
4. restart firefox

## Debug info

KeePassXC - latest
KeePassXC-Browser - latest
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
This isn't our bug and frankly not a bug at all. Running out of disk space causes all sorts of side effects.
