### ISSUE TITLE
KeePassXC breaks login in Firefox on engelbert-strauss.de

### ISSUE THREAD

**Issue by gene-pavlovsky** [keepassxreboot/keepassxc-browser#1489]
## Overview
KeePassXC used to work with a German online workwear store engelbert-strauss.de

It seems that the website developers updated something, and as of now, when using Firefox, it's not possible to log in to the website. The username input is obscured by a yellow rectangle, which seems to be a `kpxc-notification-warning`.
![2021-12-05 12_53_03-www engelbert-strauss de - Engelbert Strauss Workwear _ STRAUSS WORKS — Mozilla ](https://user-images.githubusercontent.com/2841193/144746112-5c2783cb-d42a-48bf-8d10-3b2096c9ec19.png)
![2021-12-05 12_59_36-Developer Tools — Engelbert Strauss Workwear _ STRAUSS WORKS — https___www engel](https://user-images.githubusercontent.com/2841193/144746119-8b669b46-8ed8-43c7-b420-48e066717a39.png)

In Chrome, this problem doesn't exist, there is nothing obscuring the username input.

However, for some reason, KeePassXC is not offering to autofill the login form on either browser. The URL I have in the entry should match.
![2021-12-05 13_10_53-root kdbx - KeePassXC](https://user-images.githubusercontent.com/2841193/144746134-2efed38c-a9d5-446b-b7f4-8b02f4f48a54.png)

I also tried "Choose custom login fields" out of curiosity, and when doing that, the KeePassXC instructions notification looks really bad, it gets cropped.
![2021-12-05 13_07_35-Engelbert Strauss Workwear _ STRAUSS WORKS - https___www engelbert-strauss de_](https://user-images.githubusercontent.com/2841193/144746144-9da28157-ca7b-4d66-a320-d204daec5999.png)

## Steps to Reproduce
Preconditions: 
- Firefox with KeePassXC integration enabled
1. Open https://www.engelbert-strauss.de/en/
2. Click the user account icon in the menu located in the upper right corner

## Expected Behavior
1. Username/password fields accessible
2. Autofill working correctly (if a relevant entry exists in the currently open db)
3. When using "Choose custom login field", the info notification should be fully visible and readable

## Actual Behavior
1. Username input is obscured by a yellow rectangle
2. Autofill is not working
3. The info notification is cropped by the (rather small) dimensions of the login form.

## Context
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.2
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7601: SP 1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

**Comment by varjolintu** [comment]
The iframe for login fields are loaded from a different subdomain. Use `https://engelbert-strauss.de` as your entry URL.

**Comment by gene-pavlovsky** [comment]
@varjolintu Thanks for your suggestion. In the future, how do I check where is the iframe (if present) is loaded from?

What about the other issues mentioned in the bug report? They are relevant even if the URL is fixed. I don't understand why the issue is closed already/

**Comment by varjolintu** [comment]
You can check the page source. The easiest way is to right mouse click the element and select _Inspect_ from the context menu.

The iframe issue is already reported here: https://github.com/keepassxreboot/keepassxc-browser/issues/454. I'm also aware of the notification issue and I'm fixing it ASAP.

**Comment by droidmonkey** [comment]
It might be nice to list iframe urls on the page when selecting custom fields.

**Comment by gene-pavlovsky** [comment]
I agree there should be some kind of help from KeePassXC browser extension, a developer or a power user might figure out how to use DevTools/inspect, but you can't expect that from an average user. And some websites these days do make things difficult with those pesky iframes and whatnot.

**Comment by varjolintu** [comment]
I'd suggest that we implement some debug messages to the content scripts, and we write those to the console if the debug log message option is enabled. This could also include how many input fields are detected and from which URL, including iframes.

**Comment by gene-pavlovsky** [comment]
That would be quite convenient for me. How would you explain the existence of this feature to an average user?
Is the debug log message option a new proposed option, or does it already exist somewhere? I didn't find it in the browser extension options.

**Comment by varjolintu** [comment]
@gene-pavlovsky It's not yet anywhere. It would just work by looking at the JavaScript/Developer Console which is quite easy to access.

**Comment by gene-pavlovsky** [comment]
All right, that sounds good. To be honest, I am somewhat baffled why on some sites credentials are not auto-filled, now it's clear one of the possibilities are those pesky iframes with different domains. Having a debug log would make life so much simpler, to be able to track down the correct domain and adjust the entry in the KeePassXC db.
Much appreciated if you implement this feature. When it's done, it would make sense to mention it in some FAQ or README so people can learn about it's existence.
Are you going to create a separate ticket for this? If so, can you please link it here, so I can start watching it?

**Comment by varjolintu** [comment]
I'm creating a separate PR draft for it. Not a ticket.
The easiest way to handle sites with (possible) iframes is to use only the top-level domain as the entry URL. That covers all subdomains.
