### ISSUE TITLE
Not save domain only

### ISSUE THREAD

**Issue by extrajoker** [keepassxreboot/keepassxc-browser#149]
KeePassXC - 2.3.3
keepassxc-browser - 1.1.2

[save domain only] option, does this option work?

Specified credential fields, I deleted all.
I try again, but full URL are registered.

I would like to register as follows instead of [domain only] or [full URL]
http://abc.com/aaa/
http://abc.com/bbb/
http://abc.com/ccc/

**Comment by varjolintu** [comment]
Problem found and fixed.

**Comment by extrajoker** [comment]
keepassxc-browser - 1.1.3

Does Specified credential fields  setting work correctly?
I have problem.

**Comment by varjolintu** [comment]
It didn't. The fix will be included in the next release.
