### ISSUE TITLE
Match entry for multiple domains url wise unrelated to each other

### ISSUE THREAD

**Issue by 9Lukas5** [keepassxreboot/keepassxc-browser#1491]
I'm not sure how, or in which fields a match is searched for and with a few keyword searches in the tickets I couldn't quickly find a yet existing one that would answer my question, so sorry if it was discussed somewhere already.

I have a multiple entries for various SSO systems.
I tried to make them available by adding all fqdns to the notes field or adding own custom fields per fqdn, but it won't get found.
So I guess the only field that get's searched for a match is the `URL` one?

For the most parts of my university stuff e.g. this works fine with `https://*.university-domain.tld`.
With Ubuntu One / Launchpad that's another story, because there the same entry should match for `https://login.ubuntu.com` as well as for `https://login.launchpad.net` as both login with the same SSO backend.

So, is there a way to make my entry found by both sites?

## Expected Behavior

Entry should be found for two totally different domains sharing the same SSO backend.

## Current Behavior

I seem not to be able to create my entry in a way, that it contains both needed domains/url that should match and be picked up by the browser extension

## Possible Solution

Maybe search the notes field for lines holding urls or allow additional fields to be created where additional url patterns get matched with?

## Steps to Reproduce (for bugs)

1. create entry for Ubuntu One SSO
2. use `https://login.ubuntu.com` in URL field
3. try to somehow add `https://login.launchpad.net` to this entry
4. try to get the entry show up for the launchpad login

## Debug info

KeePassXC - `2.4.3`
KeePassXC-Browser - `1.7.10.1`
Operating system: Linux (Ubuntu 20.04)
Browser: Firefox (95)

**Comment by varjolintu** [comment]
Do not use wildcards like `*`, those are currently not supported. Instead, just omit the subdomain if you match to all of them. `https://example.com` matches `https://*.example.com`. You can add multiple URL's for Browser Integration when editing your entry and going to the browser page.

**Comment by 9Lukas5** [comment]
Ok, for the university sites the wildcard seems to work fine any ways :shrug: , but for this issue that's not the burning problem.

You say I can add multiple URL's to my entry, then the question would be: HOW do I do that appropriately?

After you said that I tried something I didn't before, because it seems somehow idiotic, but:  
putting both URLs into the `URL` field of an entry, split by a space or semicolon works indeed, now the entry pops up for both sites. But this comes with the problem that I no longer can open this urls with a double click, right?

So could this be summarized by:
- for single entries there's one url in the url field that's clickable.
- for SSO entries there are multiple urls in the url field split by space/semicolon from each other and clickability doesn't matter for SSO entries anyways?

Maybe adding this information would be helpful on the [FAQ section](https://keepassxc.org/docs/#faq-browser)?

**Comment by 9Lukas5** [comment]
Oh, well. I just added [this ppa][1] to my system, which updated KeepassXC from 2.4.3 (as I mentioned in my Debug Info above) to 2.6.6, now I have the Browser Integration page in the entry settings. That's not available in 2.4.3, which is the version bundled with the current Ubuntu LTS release without adding third party repositories.

[1]: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc?field.series_filter=focal
