### ISSUE TITLE
“Key exchange was not successful”

### ISSUE THREAD

**Issue by xplosionmind** [keepassxreboot/keepassxc-browser#1492]
## Expected Behavior

KeePassXC browser successfully connecting to KeePassXC

## Current Behavior

I get the following error message:
<img width="379" alt="Screenshot 2021-12-07 at 11 11 37 AM" src="https://user-images.githubusercontent.com/42862428/145009957-636f6619-5b5b-4658-8253-44467ea34ae3.png">
<img width="378" alt="Screenshot 2021-12-07 at 11 11 27 AM" src="https://user-images.githubusercontent.com/42862428/145009964-7fa25648-771b-4ece-972c-17e5d3adcdf6.png">

## Possible Solution

No idea

## Steps to Reproduce (for bugs)

0. Activating browser intagration in KeePassXC settings
1. Opening the browser
2. Opening KeePassXC client
3. Connecting to KeePassXC through the button

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10.1
Operating system: MacIntel
Browser: Mozilla Firefox 94.0

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by xplosionmind** [comment]
Solved. Even though I have no idea how. Thanks a lot!
