### ISSUE TITLE
All entries for URLs with different paths of the same domain are returned

### ISSUE THREAD

**Issue by swizard12** [keepassxreboot/keepassxc-browser#1493]
## Expected Behavior

We have multiple environments of a modular web app running on the same host. Each module within an environment has a specific login url. I would expect to be able to add username / password entries with a partial URL that matches the domain and part of the path so that it is returned for any module in that environment. Example urls are below:

URLs
1) http://domain.com/EnvA_Module1/Login/Login...
2) http://domain.com/EnvA_Module2/Login/Login...
3) http://domain.com/EnvB_Module1/Login/Login...
4) http://domain.com/EnvB_Module2/Login/Login...

Entry URLs
a) http://domain.com/EnvA_
b) http://domain.com/EnvB_

Entry a should match URLs 1 & 2
Entry b should match URLs 3 & 4

domain.com is within our internal network so it is the fully qualified hostname of the VM serving these applications (this may or may not be relevant)

## Current Behavior

Using the URLs and Entries from above, navigating to URL 1 returns Entries 1 and 2 as suggestions. Entry 1 is the valid response.

## Steps to Reproduce (for bugs)

I am unable to provide links to the application. Hopefully the examples above are sufficient.

Apologies if this is more for the application rather than the extension.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.10.1
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
Have you tested if "Return only best-matching credentials" option affects this?

**Comment by swizard12** [comment]
I have, the behavior appears to be the same with it on or off.

Just in case I've configured something else wrong, here are the browser integration settings:
![image](https://user-images.githubusercontent.com/35807828/145196237-a65312c1-9881-44de-9568-d7ae5b5612c3.png)
![image](https://user-images.githubusercontent.com/35807828/145196271-ed426864-438d-41be-9102-c38630ce3d9d.png)

**Comment by Moilleadoir** [comment]
I regularly get this behaviour on Firefox too despite ‘Return only best-matching credentials’.

**Comment by varjolintu** [comment]
Let's track this feature here instead: https://github.com/keepassxreboot/keepassxc/issues/4509
