### ISSUE TITLE
Cannot fill splitted input field

### ISSUE THREAD

**Issue by Skeeve** [keepassxreboot/keepassxc-browser#1495]
Please visit https://userguide.volkswagen.de/public/vin/login/de_DE
and try to fill out the "password" field, i.e. the 6 input fields displayed.
It seems to be impossible

While you can paste the 17 character long string into the first field and it will happily fill the 6 fields, I did not succeed in filling them with KeepassXC-Browser

Maybe I'm doing it wrong?

## Expected Behavior

When selecting my KeepassXC entry in the first input field, I would expect it to get filled with my "Password", the same way it gets filled whe I Copy the password from keepassxc and pasting it into this field.

## Current Behavior

When selecting the entry nothing is happening

## Possible Solution

No clue

## Steps to Reproduce (for bugs)

1. Create a keepassxc entry with no username for https://userguide.volkswagen.de/public/vin/login/de_DE
2. Password is "WVWZZZE1ZN0000000"
3. Visit the page https://userguide.volkswagen.de/public/vin/login/de_DE
4. set the first input field as the password field
5. revisit
6. select the newly created input

## Debug info

KeePassXC-Browser Version: 1.7.10.1

KeePassXC Version: 2.6.6

 Operating system: Mac
Browser: Vivaldi

KeePassXC - Version 2.6.6
Revision: 386b79a

Qt 5.15.2
Diagnosemodus ist deaktiviert.

Betriebssystem: macOS 10.15
CPU-Architektur: x86_64
Kernel: darwin 19.6.0

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- TouchID

Kryptographische Bibliotheken:
- libgcrypt 1.9.3

**Comment by varjolintu** [comment]
We don't support this kind of filling directly. Please use Auto-Type instead.

**Comment by Skeeve** [comment]
Thanks for telling me what I missed. Autotype works.
