### ISSUE TITLE
TOTP proposed instead of password on https://www.totalenergies.fr/clients/connexion

### ISSUE THREAD

**Issue by mooms06** [keepassxreboot/keepassxc-browser#1500]
## Expected Behavior
When I want to login on my account in https://www.totalenergies.fr/clients/connexion, KeepassXC Browser extension should autocomplete the login & password, as on every other site.

## Current Behavior
When I want to login on my account in https://www.totalenergies.fr/clients/connexion, KeepassXC Browser extension is showing the (non existent) TOTP instead of the login/password

By default:
![image](https://user-images.githubusercontent.com/25405517/146011516-e26f8292-7588-427f-864f-92fa9fc2c115.png)

After choosing custom identifications fields it's still broken:

![image](https://user-images.githubusercontent.com/25405517/146011718-22dcdb20-d528-4dc9-946a-0a029b8017c1.png)

## Steps to Reproduce (for bugs)

1. try to login on https://www.totalenergies.fr/clients/connexion
2.
3.
4.

## Debug info

 KeePassXC-Browser version : 1.7.11

Version de KeePassXC : 2.6.6 
Operating system: Win 10 x64
Browser: tested on Firefox & ungoogled chomium

**Comment by varjolintu** [comment]
That works just fine after selecting Custom Login fields.

**Comment by mooms06** [comment]
> That works just fine after selecting Custom Login fields.

Nope, see the second capture.

Also, why TOTP is displayed, since no TOTP is available for this entry ?

**Comment by mooms06** [comment]
That's why I did, and I ended with the TOTP in the password field. I tried several times.

**Comment by varjolintu** [comment]
Tried it with three different browsers, both current develop and stable builds. Custom Login Fields worked in each of those :)

**Comment by varjolintu** [comment]
Still, the identification for TOTP field could be improved to ignore `login` word if `auth` or something else is already found. But it's highly possible that breaks more sites than adds support to.

**Comment by mooms06** [comment]
Me too, I tried on two different browsers...

See in ungoogled chromium (same behavior in Firefox)
![Animation](https://user-images.githubusercontent.com/25405517/146018668-1530446a-5aba-4db8-83ce-fa5e9f57402c.gif)

**Comment by varjolintu** [comment]
Refresh the page.

**Comment by mooms06** [comment]
You're right, it works after a refresh.

Thank you !
