### ISSUE TITLE
Browser Integration not working properly

### ISSUE THREAD

**Issue by SquigglyDog** [keepassxreboot/keepassxc-browser#1501]
## Overview
Yesterday after working without fail in the morning KeepassXC would not input Logins or passwords online. I have the extension in both firefox and brave (I am fairly certain neither are flatpaks). 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Input masterpassword into Keepassxc
2. Open browser and go to  site requiring credentials
3. green icon is present next to login but clicking on it does not do anything. 3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expect login and password to work as it did yesterday morning. I have looked at update history and browsers nor keepasxc seem to have been updated recently

## Actual Behavior
nothing happens

## Context
I have purged KeepassXC and reinstalled to the same result. I have uninstalled and reinstalled browser extensions. I timeshifted to a few days ago and the problem persists

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.6
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux Mint 20.2
Desktop Env: Cinnamon
Windowing System: X11

One other note. I have never used the Secret Service feature but in settings it says it is in use

**Comment by varjolintu** [comment]
Please go through the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and report your findings.

**Comment by SquigglyDog** [comment]
Thank You for answering
1)Yes
2)Yes
3)Yes. I checked system monitor
4)I am not quite sure how to find  backgroung page link after the Inspect views however there is a message under Console?Issues that reads" 
/orgs/keepassxreboot/survey_banner:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by varjolintu** [comment]
With Firefox:
- Go to `about:debugging#/runtime/this-firefox`
- Find KeePassXC-Browser
- Press Inspect button
- Move the tab to a new window so you can try the icon at the same time and view the console

**Comment by SquigglyDog** [comment]
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
Error 11: No saved databases found. keepass.js:1187:13
Cannot send activated_tab message:  Error: Could not establish connection. Receiving end does not exist.
    switchTab moz-extension://5e135df0-88dd-4202-972c-6e348e8b529d/background/page.js:208
page.js:209:17

**Comment by SquigglyDog** [comment]
Under Secret Service Integration it says "Warning: Another secret service is running (PID: 1343, Executable: /usr/bin/gnome-keyring-daemon).
Please stop/remove it before re-enabling the Secret Service Integration."
I have never used this feature should I be worried

**Comment by varjolintu** [comment]
The error means no databases are connected to the extension. Check your extension settings, especially the Connected Databases tab.

**Comment by SquigglyDog** [comment]
The database is opening up in KeepassXC and passwords etc are there.
I tried with an older copy of the database and it worked fine. Does this mean the new DBB is corrupted? I guess there are a few entries in the old DB I will need to update

**Comment by SquigglyDog** [comment]
I don's see the "Connected Database TAB" and what about that warning ?
Warning: Another secret service is running (PID: 1343, Executable: /usr/bin/gnome-keyring-daemon).
Please stop/remove it before re-enabling the Secret Service Integration."

**Comment by SquigglyDog** [comment]
Fond the DB TAB and it works thanks. Do I need to worry about that Secret Service warning?

**Comment by varjolintu** [comment]
See these about the warning, if it helps:
https://github.com/keepassxreboot/keepassxc/issues/3945
https://github.com/keepassxreboot/keepassxc/issues/6274

**Comment by varjolintu** [comment]
@SquigglyDog So you were able to connect to your database normally? We can close the ticket?

**Comment by SquigglyDog** [comment]
Yes.The only issue I am unsure of is this Warning: Another secret service is running (PID: 1343, Executable: /usr/bin/gnome-keyring-daemon).
Please stop/remove it before re-enabling the Secret Service Integration."

Is this a security risk. I am not clear on whether this indicates KeepassXC has been hacked

**Comment by varjolintu** [comment]
@SquigglyDog Did you take a look at the other tickets I linked to you above? Those are related to your issue. You can continue the discussion in those.

**Comment by droidmonkey** [comment]
Secret service has nothing to do with browser integration.

**Comment by SquigglyDog** [comment]
It was a separate question. I noticed the warning when I was trying to trouble shoot the issue. I can start a new thread
