### ISSUE TITLE
brave connection works but chromium fails

### ISSUE THREAD

**Issue by Chris56** [keepassxreboot/keepassxc-browser#1504]
## Expected Behavior

Successfully connect to keepassxc
Brave: Version 1.32.113 Chromium: 96.0.4664.45 (Official Build) (64-bit)
Chromium: Version 95.0.4638.54 (Official Build, ungoogled-chromium) Ubuntu (64-bit)
## Current Behavior

Brave works, initial connect leads to the expected keepassxc popup and connects afterwards.
Chromium initial connect request does not lead to a popup! And therefore no connection.

## Possible Solution

No idea how to debug. I looked for a keepassxc debug switch or enable a debug plugin, but could not find anything.
It is very strange, as brave and chromium are mostly identical.

## Steps to Reproduce (for bugs)

See above.
1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
2.6.6
KeePassXC-Browser - {VERSION}
1.7.11
Operating system: Mac/Win/Linux
Mint Mate 20.04 (Ubuntu based)
Browser: Chrome/Firefox/Vivaldi/Chromium
Chromium and Brave

Chris

**Comment by droidmonkey** [comment]
You are using ungoogled chromium which is a custom build. Use the custom browser option in the advanced tab of the browser integration settings in keepassxc.

**Comment by Chris56** [comment]
Well, it used to work ...
a) However, where do I find a template for the "custom" browser. Apart from the name almost everything should be identical.
b) With ungoogled chromium you can of course install additions for the chrome webstore. It is very unluky (at least very obscure) to the user, when the extension doen't work afterwards.

**Comment by varjolintu** [comment]
If you are using Ungoogled Chromium and you must install extensions outside the Chrome Web Store, the extension ID changes. You need to use the Custom Browser option, but the file content must be still changed. The extension ID must be replaced with your current one.

If you want to create the file manually, the script templates can be found here:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Native-messaging-script-files

**Comment by Chris56** [comment]
Thanks for your reply.
I did as you told and added the third (my installed extension) line to the json file.
However: no change. no popup from keepassxc when I try to initially connect.

**Comment by varjolintu** [comment]
Are you sure you put the file to the correct path? It should be under Ungoogled Chromium's config.

**Comment by Chris56** [comment]
Yes about the file I'm absolutely sure.
However, when debugging this issue, I stumbled upon a ungoogled chromium problem: chrome://flags is unresponsive, even after an uninstall, purge, purge of local configuration and a reinstall: all the same.
Thus currently I suspect it to be a problem with the current version of ungoogled chromium.
With earlier version of ungoogled chrome I was even able to install through the web store (with the webstore extension: https://github.com/NeverDecaf/chromium-web-store
Not anymore ... something weired with ungoogle chrome.
When this problem will be solved, I get back.

**Comment by droidmonkey** [comment]
Good example of why we don't officially support these alt browsers. 🤔

**Comment by Chris56** [comment]
I downgraded the ungoogled chromium and everything is as it was before, meaning keepassxc from the webstorew works again. This also means one does not have to  use the Custom Browser option, just checking chromium suffices as the id is the same.

**Comment by Chris56** [comment]
It is very understandable to NOT support every derivative of browsers. However, ungogled chromium is probably closer to chromiun than brave is. And with the webstore extension you don't even have to configure an alternate browser.
