### ISSUE TITLE
After closing keepassxc or ignoring the password prompt when browser opens, nothing happens when clicking the autofill button

### ISSUE THREAD

**Issue by hamishmb** [keepassxreboot/keepassxc-browser#1505]
## Expected Behavior
If keepassxc has been closed or was ignored when the browser was opened, it should prompt for the password again when the autofill button is clicked.

## Current Behavior
If keepassxc has been closed or was ignored when the browser was opened, nothing happens when clicking the autofill icon.

## Possible Solution
I don't have enough understanding of how this works.

## Steps to Reproduce (for bugs)
1. Open firefox.
2. Dismiss the keepassxc window when it appears.
3. Go to a website for which you have the password saved (and the URL).
4. Click the autofill button.
5. Nothing happens.

## Debug info

I don't know how to access the debug logs. I will have to do this later as I have a very old session at the moment and a lot of browser tabs open - probably not helping.

KeePassXC - 2.6.6 (flatpak)
KeePassXC-Browser - 1.7.11 (from Mozilla store)
Operating system: Linux Mint 20.2
Browser: Firefox (has happened in various versions, currently 95.0.1.

**Comment by varjolintu** [comment]
Dismiss the KeePassXC window? You mean the Access Confirm popup? If you close it, the credentials are denied for that site. However, a page refresh should ask them a gain if the setting was not used with the Remember checkbox.

**Comment by hamishmb** [comment]
No, I mean when you open the browser and keepassxc pops up asking for the password. Or if you just ignore or minimise it.

**Comment by droidmonkey** [comment]
You have the strange Firefox bug that launched keepassxc from Firefox. You are likely using a very old version of keepassxc.

**Comment by hamishmb** [comment]
Hmm, I'm running 2.6.6 though, which is apparently the latest in github.

**Comment by hamishmb** [comment]
Hmm okay. I would use the repo version but it's ancient. Is there a PPA I can use to avoid the issue/test if it is a Flatpak thing?

**Comment by varjolintu** [comment]
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by hamishmb** [comment]
I'm giving that a try now. It does seem to have started behaving better since this report, so I wonder if it was an access prompt that I was ignoring. If keepassXC isn't open, it will be opened when I open the browser though, so on the other hand, maybe not.

I have found that sometimes I need to use the keepassxc-browser menu in the toolbar and click refresh or retry a few times to coax it back into life - maybe have it try that automatically periodically if it encounters an error?

**Comment by hamishmb** [comment]
Okay, have got it working and integrated with the browser extension. I will report back when I've been using it long enough to see if it is any different.

**Comment by varjolintu** [comment]
@hamishmb I've also encountered this, especially on macOS when sometimes the KeePassXC popup doesn't get the focus. And in between I've refreshed the page or done something else, and after that reacted to the popup. In those cases the popup doesn't seem to reappear. In this case only thing that seems to work is closing and reopening the database. I'm trying to investigate why this happens. Needs to be fixed, obviously.

**Comment by hamishmb** [comment]
Okay good to know.

The PPA version doesn't seem to have fixed it. I think on suspend/resume the browser extension sometimes loses the connection to KeepassXC, and I then need to hit retry a few times in the menu. Perhaps we could try to auto-reconnect if the system has just woken from sleep/hibernate somehow?

**Comment by varjolintu** [comment]
I'm trying if it would be possible to make Access Confirm Dialog asynchronous, just like we did with the new password generator popup. It would probably solve a lot of problems.

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/8273 This change should fix it.

**Comment by varjolintu** [comment]
This should be already fixed.

**Comment by hamishmb** [comment]
Seems fixed to me.
