### ISSUE TITLE
UX: If no password is saved with the relevant URL, nothing happens when clicking the autofill icon

### ISSUE THREAD

**Issue by hamishmb** [keepassxreboot/keepassxc-browser#1506]
## Expected Behavior
I think if no password is saved for the URL open, keepassxc/the extension  (whichever is responsible) should allow you to search for the password you want, and then update the URL in the manager.

Perhaps, instead, at least a popup should indicate there is no password saved for that site.

## Current Behavior
Nothing happens.

## Possible Solution
I'm not sure how this would work, but a simple text search in a small popup dialog would work nicely.

## Steps to Reproduce (for bugs)
1. Go to a website for which you don't have a password saved (or you forgot to add the URL, which I usually do).
2. Click the autofill icon.
3. Nothing happens.

## Debug info

As with my other bug report, I will have to do this later as I have a very old session and too many tabs open to close everything right now.

KeePassXC - 2.6.6 (flatpak)
KeePassXC-Browser - 1.7.11 (from mozilla store)
Operating system: Linux Mint 20.2 x86_64
Browser: Firefox 95.0.1 (but happened in various versions over time)

**Comment by varjolintu** [comment]
Search for the password including all entries will be not implemented. Entries are restricted per URL.

There's already a PR that will change the autofill icon to grey when there's no credentials available for the current site.

**Comment by hamishmb** [comment]
That's an improvement. Is there some discussion that says why this won't be implemented?

**Comment by varjolintu** [comment]
The same feature has been asked multiple times. We restrict entries by the URL. Searching all of them would expose all credentials for all sites. That doesn't sound like something we want to do here.

**Comment by hamishmb** [comment]
Makes sense, thanks!
