### ISSUE TITLE
No detection of disabled password field

### ISSUE THREAD

**Issue by ogendogen** [keepassxreboot/keepassxc-browser#1514]
KeePass plugin can't detect form fields which are disabled at page startup. Even if I set custom form fields when they aren't disabled, then it's still not detected after page reload.

## Expected Behavior
Detect disabled form fields (which tag disabled)

## Current Behavior
Lack of disabled fields detection

## Possible Solution
Detect form fields with disabled tag

## Steps to Reproduce (for bugs)
1. Create new record in KeePass
2. Go to https://nowekonto.bik.pl/login
3. KeePass detects only login text field, because password field is disabled when login is empty

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Mozilla Firefox 95.0

**Comment by varjolintu** [comment]
Sorry, but it's impossible to fix the site. It even clears the password if it's filled via script. Use Auto-Type for this one.
