### ISSUE TITLE
No connected databases found (librewolf)

### ISSUE THREAD

**Issue by peepopoggers** [keepassxreboot/keepassxc-browser#1515]
## Expected Behavior
When keepassXC is open, the extension can connect and it works like it is supposed to. However, when keepassXC is closed, the extension says: 
![image](https://user-images.githubusercontent.com/72892531/148117357-9e88a684-eff7-4259-b0e6-69044103acfe.png)

Also even when keepassXC is open and the database works, "Connected Databases" tab in setting returns:
No connected databases found.

and "Connect" button does nothing.

## Current Behavior
It should not disconnect when I close keepassxc

## Possible Solution
:shrug: 

## Steps to Reproduce (for bugs)

1. Install keepassxc on ubuntu 20.04
2. Install librewolf by using their deb repo
3. Create a new database and add a test entry. Visit settings and add use custom browser with config - "~/.librewolf/native-messaging-hosts"
4. Visit browser, connect with extension while keepassXC is open. Then close keepassXC from the background and it gives the top image.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux (ubuntu 20.04 based)
Browser: LibreWolf (deb installed)

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by droidmonkey** [comment]
You have to have keepassxc running to use it.... there is no other option. You can enable the tray icon to hide it from view.

**Comment by peepopoggers** [comment]
alright :<
