### ISSUE TITLE
Firefox freezing on many sites

### ISSUE THREAD

**Issue by Moilleadoir** [keepassxreboot/keepassxc-browser#1516]
For many months now, I’ve had intermittent problems with Firefox freezing, but it’s become much more common lately and when I look at about:performance it’s KeepassXC that seems to be the culprit.

## Expected Behavior
Should be able to use pages with input boxes without freezing.

## Current Behavior
Any page with input boxes (& presumably code behind them) has a chance of freezing.

## Possible Solution
I know you can blacklist sites, but this seems backward to me.  I’d prefer a mode where KP didn’t assume every page was a login page, even if that meant I had to manually add logins to the database.

## Steps to Reproduce (for bugs)
1. Use a page with an input box, e.g. verification code
2. Firefox will freeze
3. Kill Firefox & restart
4. Try again
5. Firefox will freeze
6. Kill Firefox & restart
7. Disable KeepassXC
8. Input succeeds with no freeze

## Debug info
KeePassXC -  2.6.6 Revision: 9c108b9
KeePassXC-Browser - 1.7.11 (11-12-2021)
Operating system: Manjaro Linux
Browser: Firefox

**Comment by varjolintu** [comment]
A few questions:
- Is there any difference if you disable _Use dynamic input field detection_ from the extension settings?
- Is Automatic Reconnect setting disabled?
- Are you able to debug the content script?
- Does `about:performance` show anything?
- Does this happen with other browser, have you tried to reinstall the extension etc?

**Comment by varjolintu** [comment]
Did the Firefox 96.0 affected to anything?

**Comment by varjolintu** [comment]
Please check that it's not the current Firefox issue:
>What worked for me was disabling HTTP3 support with the network.http.http3.enabled key in about:config and then restarting Firefox. Seems like it's stuck in the 'SocketThread', repeatedly doing this:

> 2022-01-13 08:20:53.075936 UTC - [Parent 4106991: Socket Thread]: V/nsHttp Http3Stream::OnReadSegment count=333 > state=4 [this=7f6e295623a0]
