### ISSUE TITLE
"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." after reload " Key exchange was not successful."

### ISSUE THREAD

**Issue by Gal-AnonimObviously** [keepassxreboot/keepassxc-browser#1519]
## Expected Behavior
Extension should connect to KeePassXC

## Current Behavior
When I open the extension I have this error "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." and after I click reload I have this error " Key exchange was not successful."

## Steps to Reproduce (for bugs)

1. Open LibreWolf/Tor and KeePassXC
2. Allow browser integration in KeePassXC settings
3. Open extension

## Debug info

KeePassXC - {2.6.6}
KeePassXC-Browser - {1.7.11}
Operating system: Linux
Browser: LibreWolf/Firefox/Tor

**Comment by varjolintu** [comment]
Use the Custom Browser feature for LibreWolf. Make sure your browser is not installed via Snap.

For Tor and other problems, check https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by Gal-AnonimObviously** [comment]
> 

I have already done Troubleshooting

**Comment by varjolintu** [comment]
And what are your findings for example with LibreWolf?

**Comment by Gal-AnonimObviously** [comment]
I still have the same error

**Comment by varjolintu** [comment]
Please tell what did you find? Where are the script files located? How is your browser installed? More info is needed.

**Comment by Gal-AnonimObviously** [comment]
Where and what find? ~/.mozilla/native-messaging-hosts/ . Using yay (AUR).

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/issues/1342#issuecomment-936167095

**Comment by Gal-AnonimObviously** [comment]
Still the same error

**Comment by varjolintu** [comment]
You need to give some more information about the steps you are making, and where the scripts files are etc.

**Comment by Gal-AnonimObviously** [comment]
What scripts?

**Comment by varjolintu** [comment]
The `org.keepassxc.keepassxc_browser.json` scripts mentioned in the Troubleshooting Guide.

**Comment by Gal-AnonimObviously** [comment]
`sudo find / -iname org.keepassxc.keepassxc_browser.json`
I have been searching on the whole drive and I cant find it

**Comment by Gal-AnonimObviously** [comment]
I will reinstall extension

**Comment by varjolintu** [comment]
If you enable support for Firefox, you should find the script at `~/.mozilla/native-messaging-hosts`.

**Comment by Gal-AnonimObviously** [comment]
yeap I have this file in /home/ludwik/.mozilla/native-messaging-hosts/

**Comment by varjolintu** [comment]
And Firefox still does not work? You didn't say how your Firefox is installed.
You can do the following to get rid of the Snap version if that's installed:
```
$ sudo snap remove firefox
$ apt install firefox
```

**Comment by Gal-AnonimObviously** [comment]
But I dont use Firefox, I use LibreWolf, and even though I mounted ~/.mozilla/native-messaging-hosts to ~/.librewolf/native-messaging-hosts I still dont work

**Comment by Gal-AnonimObviously** [comment]
Edit, I have found solution I have to bind native-messaging-hosts from mozilla to native-messaging-hosts in librewolf and then select the ~/.librewolf/native-messaging-hosts in custom browser location

**Comment by JIGASHI** [comment]
Librewolf is installed through pop store, same with keepassxc, messaging-hosts is correctly navigated to and the json file is there, firefox is the only browser checked. Still getting KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 

Key exchange was not successful. upon refresh

**Comment by varjolintu** [comment]
@JIGASHI With Librewolf you'll have to use the Custom Browser feature. But you cannot install it as a Flatpak. That and Snap are not currently supported.
