### ISSUE TITLE
Not Automatically immediately retrieve credentials

### ISSUE THREAD

**Issue by extrajoker** [keepassxreboot/keepassxc-browser#152]
KeePassXC: 2.3.3
keepassxc-browser: 1.1.3
Browser: Vivaldi

When the tab is activated, KeePassXC-Browser does not immediately retrieve.
I switch another tab, and I return to the first page.
Then, KeePassXC-Browser retrieve.

**Comment by varjolintu** [comment]
Duplicate with https://github.com/keepassxreboot/keepassxc-browser/issues/150.
