### ISSUE TITLE
Removal of single autocompletion entries

### ISSUE THREAD

**Issue by q-wertz** [keepassxreboot/keepassxc-browser#1521]
## Expected Behavior

Allow the removal of single suggested entries in the selector.
![Screenshot from 2022-01-10 09-25-51](https://user-images.githubusercontent.com/20948931/148739344-4c8d884a-ca60-468a-8424-6b39199498c5.png)

## Current Behavior

Currently after one has selcted several accounts for the autofll it is not possible to remove single accounts for the website (as far as I found out). One has to go to the entry in KeePassXC -> Properties and delete the whole entry `KeePassXC-Browser Settings` which will also remove it from all other pages and has to be newly added for every one of these.

Related: https://github.com/keepassxreboot/keepassxc/issues/2975

## Possible Solution

e.g.
- Small `x` at the end of the entry to remove it
- Remove entry that is currently selected by the selection curser by hitting `del`

## Steps to Reproduce (for bugs)

1. Have multiple fitting URLs for a website
2. Allow some of them
3. Try to remove a single one

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win & Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Not an easy task. Do you mean you want to allow some URL's only for some subdomains?  Then use the subdomain in the entry URL.

**Comment by q-wertz** [comment]
That is currently already working. When the dialogue which accounts you want to enable for that website pops up first all fitting entries are shown and when you select only a subset only these will be shown the next time (due to the `Allow` and `Deny` entiries in the `KeePassXC-Browser Settings` field).
But this can never be edited afterwards.

I would like to have a way to edit this. One way would be to make the field editable in KeepassXC itself but in the linked issue they state that's nothing they want to do and properties should be edited by the plugin that created these properties.

> Then use the subdomain in the entry URL.

Why does the plugin then not directly use the information from the `Browser integration` tab and the `Additional URLs` function but creates the property? This seems like the same functionality implemented twice? :thinking:

**Comment by varjolintu** [comment]
Marking this as a duplicate for https://github.com/keepassxreboot/keepassxc/issues/2975. There's also issue https://github.com/keepassxreboot/keepassxc-browser/issues/1159 which is related to this.

The permission for this is needed for user interactive based confirmation if a domain is allowed to retrieve credentials for certain entry. It's a precaution that prevents automatic harvesting of credentials, which is very unlikely, but possibly in theory. Basically it prevents accessing any credentials through the browser API without user knowing about it.
