### ISSUE TITLE
[bug] Keepassxc or FF ext combo :  Form filling broken again

### ISSUE THREAD

**Issue by succeedmr123** [keepassxreboot/keepassxc-browser#1522]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Form filling broken again (FF ext recognize/connect to KeepassXC/ database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Do everything as usual 
2. Notice it just does not work (entries does not show in fields/can not choose any entries)
3. _Do this bug report

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Everything to run rock-solid

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Can not choose entries in FF although KeepassXC is connected to the KeepassXC external app/database

## Context
[NOTE]: # ( Give us any additional information you may have. )
Using containers in FF (although it worked until this point in time)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION 2.6.6
Revision: REVISION no revisions

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 95.0

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS Linux
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon XFCE
Windowing System: X11/Wayland X11

**Comment by varjolintu** [comment]
Check your Firefox install. It's not reinstalled by Snap or anything? Does previous versions or some other browser work?

**Comment by succeedmr123** [comment]
@varjolintu Thanks for the feedback. I will see what I can check, as production time disallows me even to lose time writing this request. I doubt it is just here, henceforth the anchor here for other users chime in with their own findings and experiences of this type

Best

**Comment by varjolintu** [comment]
I think there would be a lot of reports if it's more wide.

**Comment by succeedmr123** [comment]
Yes, I hope for more reports, albeit I do not count on a normal user willing at all to break their life workflow to make a report on partial websites not working. Let us see.

My promise is that when I will have an opportunity to dig deep and hard, I will do so and share it here for the benefit of making it less likely to occur for all of us in another form of interuption.

**Comment by varjolintu** [comment]
Did Firefox 96.0 fixed anything?

**Comment by chilliger** [comment]
I have problems with https://b2b.dab-bank.de/Tradingcenter/

Browser plugin is unable to autofill. I am able to fill the user and password by manually right klick on the fields and choose to fill them.

**Comment by varjolintu** [comment]
@chilliger That site has been already reported.

**Comment by geolaw** [comment]
Came to mention this same problem. I thought I was going crazy here the last couple of days (been sick with covid and thought I was losing my mind) 
Non-working machine : 
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64  (Fedora 35)
Browser: Mozilla Firefox 96.0


I've got access to a RHEL8 laptop where the plugin appears to be filling fine but with an older version of FF : 
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64 (RHEL8 Internal RH build)
Browser: Mozilla Firefox 91.0

**Comment by varjolintu** [comment]
@geolaw So what's the difference in these browsers? Are both installed as normal binaries from the repos? Or are these Snap/Flatpak/WhateverOhSnap?

**Comment by geolaw** [comment]
both .rpm installs

Updated Fedora today  to 96.0.3-1
firefox-96.0.3-1.fc35.x86_64

plugin appears to be working again
