### ISSUE TITLE
Autofill of password using extension popup does not work at accounts.google.com

### ISSUE THREAD

**Issue by BoundedChenn31** [keepassxreboot/keepassxc-browser#1523]
## Expected Behavior
User should be able to fill password field using extension popup without having to refresh a page

## Current Behavior
Password field stays empty after described above action.

## Possible Solutions
1. Refresh page with password field using F5. After that autofill from popup starts working.
2. Use dropdown list 
![Screenshot (2)](https://user-images.githubusercontent.com/44954031/148850081-cd316b74-99b6-46f6-b28d-373fcbac2e4e.png)

## Steps to Reproduce

1. Have multiple gmail accounts, log out of all of them
2. Head to https://mail.google.com
3. Click _Sign in_ in page header, page with username field opens
4. Click extension icon and select any account from filter
![Screenshot (3)_LI](https://user-images.githubusercontent.com/44954031/148851190-e1be80cf-0d41-425d-8818-754737c34ae4.jpg)

5. Proceed to password page
6. Try to repeat step 4

Password field should be filled but it's not.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win64-10
Browser: Vivaldi 5.0.2497.35 (Chromium 96.0.4664.137)/fresh Edge 97.0.1072.55

**Comment by varjolintu** [comment]
This needs some special handling. Through the username icon and Autocomplete Menu it fills everything just fine. The popup however doesn't have any information about the password field. That information has to be parsed from the saved field combinations or from the icon's properties. Fixing it soon.
