### ISSUE TITLE
Auto-fill icons hide form buttons

### ISSUE THREAD

**Issue by Gertalitec** [keepassxreboot/keepassxc-browser#1527]
## Expected Behavior

Auto-fill icons should not interfere with any functionality built into the forms (most often, a little "eye" button to toggle the option to view or hide the entered password)

## Current Behavior

![screenshot](https://user-images.githubusercontent.com/97767846/149598174-42be5c85-5e90-46db-913c-48723cb030e2.png)

## Possible Solutions

- Move the auto-fill icons to outside the forms
- Somehow check if they are overriding something
- Hide buttons after auto-fill is complete

**Comment by varjolintu** [comment]
On what site this happens? Sometimes these icons are triggered by the browser itself and those are not detectable.

**Comment by varjolintu** [comment]
Closed due to inactivity.
