### ISSUE TITLE
TOTP field on Pushover login page not detected

### ISSUE THREAD

**Issue by Programie** [keepassxreboot/keepassxc-browser#1528]
## Expected Behavior

The TOTP field of the login flow should be filled by KeePassXC.

## Current Behavior

After letting KeePassXC-Browser fill my email-address and password and submitting the login form, the page asks me for my TOTP. Unfortunately, KeePassXC-Browser is not providing a button in the field to insert the TOTP into the field. Right-clicking on the field and selecting KeePassXC-Browser > Fill TOTP also does nothing.

I've tried to fix it using the "Chose custom login fields" option but that doesn't work neither.

Currently, the only way to provide the TOTP is by manually search for the entry in KeePassXC, copying it and pasting it into the TOTP field.

## Steps to Reproduce (for bugs)

1. Go to https://pushover.net/login
2. Let KeePassXC-Browser fill the email-address and password
3. Submit the form resulting in getting redirected to https://pushover.net/login/login
4. Try to let KeePassXC-Browser provide the TOTP. It does not work.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux
Browser: Firefox 96.0

**Comment by varjolintu** [comment]
Can you provide HTML code for the TOTP input field?

**Comment by Programie** [comment]
That's the HTML code for the TOTP field:

```html
<input autofocus="autofocus" inputmode="numeric" pattern="[0-9]*" autocomplete="one-time-code" style="width: 6em;" type="text" name="user[twofa_code]" id="user_twofa_code">
```

As you can see, the button for inserting the TOTP is missing:

![image](https://user-images.githubusercontent.com/1206521/149748541-aa480249-74d8-4d3f-b7f6-1063b173ac55.png)

**Comment by varjolintu** [comment]
Got it. The field is ignored because `user` is in the id and name. Some other sites can give false positives for fields containing the `user` string, but in this case `twofa` is included in the same property, so it should be still accepted.

**Comment by Jebtrix** [comment]
I have the same bug scenario. In my case:

```html
<input autocomplete="one-time-code" autofocus="autofocus" id="user_session_totp_token" inputmode="numeric" maxlength="6" name="totp_token" type="text" value="">
```

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/pull/1573 This should help filling the TOTP in the future.

**Comment by sonalvrioss-svyatos** [comment]
I am also facing the same problem with my own website. I'm using a plugin for TOTP and despite using custom login fields, KeePassXC extension does not recognise it. Here's my HTML code for the TOTP input field:

`<input type="text" name="two_factor_code" id="simba_two_factor_auth" autocomplete="off" data-lpignore="true">`

**Comment by Programie** [comment]
This issue has been fixed for me a while ago. I'm not exactly sure which version fixed it. So, this issue can be closed.
