### ISSUE TITLE
[KeepassXC Browser Extension] Autofill doesn't work

### ISSUE THREAD

**Issue by Giga-Pudding** [keepassxreboot/keepassxc-browser#1529]
Hello everyone,

This issue is regarding this website: https://login.aliexpress.com/
Login fields (username/password) are detected correctly, but autofill doesn't work. Can anyone confirm?

BR,
Giga-Pudding

**Comment by varjolintu** [comment]
The login form is using an iframe from a different subdomain. Use `https://aliexpress.com/` as your entry URL instead.
