### ISSUE TITLE
Google dialog to use stored passwords hides KeePassXC dialog

### ISSUE THREAD

**Issue by igittigitt** [keepassxreboot/keepassxc-browser#1533]
## Overview
When using the plugin in Chrome (here i use version 87.0.4280.88) and logged into my Google-Account, the hint-dialog of Chrome sometimes overlays the selections of KeePass in a way, that the actual entries (especially if there was only one) are completely hidden by it, so no selection is possible (you can only imagine there is an entry by the small green line marked):
![hidden_dialog](https://user-images.githubusercontent.com/909922/150101888-9c47c0e8-f1bb-41e0-93bb-71ba639df723.png)

I've already disabled password-sync for Google in Chrome-Settings:
![19-01-_2022_10-32-37](https://user-images.githubusercontent.com/909922/150103331-245af855-8574-46ff-b910-d6338cc0b608.png)

## Steps to Reproduce
This does not always happen, but i did not found any pattern right now.

## Expected Behavior
The KeePass dialog should not interfere with the Chrome/Google dialog. Maybe overlay it?

KeePassXC - 2.6.6
Revision: 9c108b9
Operating System: Windows 10

**Comment by varjolintu** [comment]
I doubt that is possible because the Google dialog is probably integrated to the browser itself, not to the web page.
