### ISSUE TITLE
Password generator only works with wordlist with name "eff_large.wordlist"

### ISSUE THREAD

**Issue by hemanti0503** [keepassxreboot/keepassxc-browser#1535]
## Expected Behavior
1. Open PW generator in browser
2. Generate PW with generator settings from KeePassXC

## Current Behavior
Word list only works if I rename my custom word list (that I placed in `/usr/share/keepassxc/wordlists` as told in the FAQ) to `eff_large.wordlist`.

## Possible Solution
a) Let me choose the wordlist in browser, or
b) Use the woorlist chosein KeePassXC. 

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
We added custom work lists to the next release
