### ISSUE TITLE
Decentr (chromium) browser support

### ISSUE THREAD

**Issue by Terramoto** [keepassxreboot/keepassxc-browser#1536]
I'm switching browsers to Decentr (brave/chrome alternative) and upon installing the extension from google store, the extension doesn't seem to be able to communicate with the application. I was wondering if this is just the app rejecting communication from the browser or the browser that's having difficulty communicating with the keepass app.

I currently have other browsers installed with the extension and they are working fine.

KeePassXC - unknown
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Chrome/Chromium 96.3.4664.32 Decentr

**Comment by varjolintu** [comment]
Use the Custom Browser Feature found in KeePassXC's Browser Integration Advanced settings.
