### ISSUE TITLE
Password generator does not work for passphrase title case

### ISSUE THREAD

**Issue by parkel42** [keepassxreboot/keepassxc-browser#1537]
## Expected Behavior

When generating a password through KeePassXC using the Passphrase + Title Case option, the password gets generated like so: 

![image](https://user-images.githubusercontent.com/50959479/150463291-3db08a76-8b8c-4caa-9acb-cc6e676805cd.png)

The same behaviour should be expected in KeePassXC browser plugin when generating a password.

## Current Behavior

The password instead gets generated without the title case option, even though it does conform to the number of words selected:

![image](https://user-images.githubusercontent.com/50959479/150463383-7909d40b-7b88-45d9-9807-2583a76562d7.png)

## Steps to Reproduce (for bugs)

1. Go to any website with a password field.
2. Click on the icon to the right of the password field and generate a password.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Windows 10 
Browser: Firefox

**Comment by varjolintu** [comment]
We are no longer developing the extension's password generator further. Next version of KeePassXC will directly launch its own password generator instead of that minimal popup.
