### ISSUE TITLE
Be able to give a search string to search the database when you are on a site

### ISSUE THREAD

**Issue by jcompagner** [keepassxreboot/keepassxc-browser#1538]
Maybe i am mistaken but i have quite often that i am on a site and keepassxc-browser doesn't give me any hint
And when pressing the keepass icon in the browser i don't get a search field where i can just say "query for this"
Because i know i do have a password for this site but the url is just a bit different..

It would be very nice if i can just search for it, then select the one 1 want and then maybe get the question:

"Do you want to add this url to the url list of that entry? "

so the next time it will find it automatically..

Because now i always have to go to keepassxc itself search for it my self, then go to the browser integration section add the url myself and then yes -browser does find it..

**Comment by varjolintu** [comment]
We are not going to implement a wide search of all entries in the database.
Your best bet is to modify the entry URL's in a way those work with wildcards. For example `https://example.com` will work with all subdomains of that site, like: `https://*.example.com/`.
