### ISSUE TITLE
Keepassxc Browser on multiple devices with Windows 10 and Chrome browser with user profile synced - database synced with Google Drive

### ISSUE THREAD

**Issue by cleforweb** [keepassxreboot/keepassxc-browser#1539]
## Expected Behavior

After making a database edits concernig browser integration (allow/disallow entries for certain sites) on the first computer I expected that Keepass xc Browser will read those changes on other computer which is not the case.

## Current Behavior

My database is successfully imported from a CSV file.
I have many sites with many login data for each.
I reviewed, sorted, organized every item, opened every site (keepassxc browser installed and connected)
and allowed/disallowed items per site.
After many hours of work Kepassxc browser worked fine on the first computer.
Then I opened Chrome on the second computer.
The database is synced with Google Drive.
As I have a profile synced on Chrome, Keepassxc browser extension was already there
asked me to connect to the database using a unique name.
First I entered a new unique name and connected - no allowed/disallowed entries were visible in the database
(I am talking about the "Plugin data" in the "Edit entry" "Properties" option).
Next, I disconnected the extension and try to connect again,
this time with the same name as on the first computer.
Asked me to overwrite, I wasn't sure, made a mistake, and lost all my work.

## Possible Solution

Option to choose (and read) the same Keepassxc Browser profile on the multiple computers.

## Steps to Reproduce (for bugs)

1. On the first windows 10 computer and Chrome browser, open a webpage with multiple login profiles.
2. Allow/disallow some profiles.
3. On the second computer sync database with a Google Drive.
3. Connect Keepassxc browser extension with an unique name.
4. In the Keepass "Edit entry" "Properties" check if any plugin data (added on the first computer) exist?

## Debug info

No errors visible in the Console.
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Windows 10
Browser: Chrome

**Comment by varjolintu** [comment]
> First I entered a new unique name and connected - no allowed/disallowed entries were visible in the database

Not sure what you mean by this. There were not settings in the entry properties even when there should've been?
Always use a unique name when making the connection with extension.

> and lost all my work

Could you elaborate what this means?

Could you also confirm that the database shows identical data from both computers? Let's make sure this is not some kind of sync issue after all.

**Comment by varjolintu** [comment]
@cleforweb Did you solve the problem or why did you close the ticket?
