### ISSUE TITLE
Can I change default entry icon when I save it ?

### ISSUE THREAD

**Issue by iamrealmarsel** [keepassxreboot/keepassxc-browser#1543]
Hi there!
When I save login/password, the entry is saved with a specific icon (earth) by default. 
Can I choose another default icon ?

![Screen Shot 2022-01-23 at 10 04 27 PM](https://user-images.githubusercontent.com/20097612/150693992-54bf4d6e-36db-4ef4-91ae-deee0a26139d.png)

**Comment by varjolintu** [comment]
With KeePassXC 2.7.0 you can enable an option that retrieves the site favicon when saving.

**Comment by iamrealmarsel** [comment]
KeePassXC 2.7.0 is in beta testing? can I install it?

**Comment by varjolintu** [comment]
You can test it from here: https://snapshot.keepassxc.org/latest/
