### ISSUE TITLE
Browser add-on fails to detect log-on fields for iCloud.com

### ISSUE THREAD

**Issue by jacnel2** [keepassxreboot/keepassxc-browser#1546]
## Expected Behavior
1. Upon clicking the green Keepass-xc icon, the application should fill the username and password fields for the website.
2. Only one Keepass-xc icon should appear for the entire log-in form.
3. Choose custom log-in field should behave correctly, displaying only one setup wizard. 

## Current Behavior

1. Currently, clicking the green Keepass-xc icon fails to fill the username and password for the form. This is despite the fact that in my Keepass-xc database the url for the icloud.com log-in page is correct.
2. Two Keepass-xc icons appear for each log-in field, see image: 
![Screenshot 2022-01-25 123721](https://user-images.githubusercontent.com/47191302/151031209-7320fe4f-ef07-4f21-ac20-3e603794d249.png)
3. Choose custom log-in field wizard is screwed up, see image: 
![Screenshot 2022-01-25 123732](https://user-images.githubusercontent.com/47191302/151031210-0e2533c9-97b3-4aa1-b83a-bb31e261b910.png)

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
_Assumes that in Keepass-xc there is an entry for iCloud.com_
1. Go to iCloud.com
2. Click green keepass-xc icon (for issue 1.)
2. Enter Apple ID username, press enter (for issue 2.)
3. Select "Choose custom login fields" (for issue 3.)

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Microsoft Edge 97.0.1072.69

**Comment by varjolintu** [comment]
You should use `https://idmsa.apple.com` as your entry URL. There's no need for Custom Login Fields. The login page works without it.

**Comment by jacnel2** [comment]
> You should use `https://idmsa.apple.com` as your entry URL. There's no need for Custom Login Fields. The login page works without it.

Ahh thank you, I tried this URL as suggested and the issue was resolved. Sorry to waste your time.
