### ISSUE TITLE
Connected databases disappearing from Firefox

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [keepassxreboot/keepassxc-browser#1548]
## Expected Behavior

I have multiple databases opened in KeePassXC (8) and I needed to connect each one of them to KeePassXC Browser by activating the tab in KeepassXC and then using the connect button in Firefox. After changing the tab in KeepassXC the browser extension should display the connect button if there is not yet a connection to the "active" database.

## Current Behavior

After adding the 8th database connection it seems that KeePassXC is deleting one of the others.
Update: it seems it has nothing to do with the amount of DBs. after connecting an additional database another one just disappears from "Connected Databases"
Also I have to switch the tab multiple times in KeePassXC (or do something else (wait?, change tabs in browser, have not found out what exactly - maybe closing the KeepassXC window?) until KeepPassXC Browser realises a new database is "active" and displays the connect button.
I have not found out if there is any regularity to which databases gets kicked out 

## Steps to Reproduce (for bugs)

1. connect 7 databases to keepassxc browser (maybe the number is not important)
2. connect another one
3. in keepassxc switch tab to database that was removed after step 2 and keepassxc browser will not offer the connect button (it will still say connected to .... but its not the currently active database)

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Mozilla Firefox 96.0

**Comment by varjolintu** [comment]
Please make sure that none of your databases is not identican with same Root Group UUID. This causes the database identification key to be non-unique. You can reset the Root Group UUID from KeePassXC's database settings.

**Comment by tofuSCHNITZEL** [comment]
thanks for the tipp! I refreshed the root group ID for every database and will let you know if problem appears again.
thanks!

**Comment by varjolintu** [comment]
Let's reopen this if the problem appears.
