### ISSUE TITLE
M1 Mac identified as a MacIntel

### ISSUE THREAD

**Issue by DanielAbsi** [keepassxreboot/keepassxc-browser#1550]
My settings from KeePassXC Browser extension:
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: MacIntel
Browser: Chrome/Chromium 97.0.4692.99

My mac is an Apple Silicon M1 mac: 
![Screen Shot 2022-01-28 at 9 05 27 AM](https://user-images.githubusercontent.com/15313941/151560496-cc74aef4-24c1-4952-9cd4-77b55c2e2964.png)

**Comment by varjolintu** [comment]
We are reading this from browser's `navigator.platform`. Does `navigator.userAgent` still say something about M1?

**Comment by varjolintu** [comment]
According to search results around the web user agents also show "Mac Intel" on M1 machines. Nothing we can do here.
