### ISSUE TITLE
password can't be filled in on login.microsoftonline.com, but only when I get there from outlook.office365.com

### ISSUE THREAD

**Issue by nsajko** [keepassxreboot/keepassxc-browser#1553]
## Expected Behavior
It should be possible for the keepassxc extension to fill in the password for me on login.microsoftonline.com (independently of how I got there).

## Current Behavior
My password can't be filled in on https://login.microsoftonline.com if I got there through https://outlook.office365.com. I tried different ways to do this, but none work. The password input field cursor stops blinking while the extension is supposed to be filling in the password, so *something* is happening.

## Workaround
Go to other Microsoft Web sites and login through there. (office.com, office365.com, or going directly to login.microsoftonline.com all work).

## Steps to Reproduce (for bugs)
1. Go to https://outlook.office365.com. This redirects to https://login.microsoftonline.com.
2. Try filling in the username with the extension. Works for me.
3. Now there's no way to fill in the password

## Possibly related
https://github.com/keepassxreboot/keepassxc-browser/issues/1087

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Arch Linux
Browser: Chromium 98.0.4758.80

**Comment by varjolintu** [comment]
I couldn't reproduce this. I'm using `https://login.microsoftonline.com/` as the entry URL.

**Comment by nsajko** [comment]
> I couldn't reproduce this. I'm using `https://login.microsoftonline.com/` as the entry URL.

Yeah, I tried to make this clear in the original post already. E.g., in the Workaround section I already said it works when you go directly to https://login.microsoftonline.com. What does *not* work is if I go to https://outlook.office365.com.

**Comment by varjolintu** [comment]
The login page worked normally for me from both URL's, so I cannot reproduce this.

**Comment by tofuSCHNITZEL** [comment]
Also cant reproduce it. https://outlook.office365.com/ redirects to https://login.microsoftonline.com/ and filling works just fine

**Comment by nsajko** [comment]
I couldn't reproduce this anymore after restarting Chromium.
