### ISSUE TITLE
Odd Pivotal Tracker interaction with KeePassXC-Broswer extension

### ISSUE THREAD

**Issue by mann** [keepassxreboot/keepassxc-browser#1554]
## Overview
Toast Message pops up in top-right of browser every time I access a story in Pivotal Tracker

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. KeePassXC-browser installed
2. Login into PivotalTracker.com
3. Toggle open any story within Pivotal
4. then a yellow toast message displays stating "Warning! No saved login fields found." 
5. toggle another story same toast message appears.

## Expected Behavior
I do not expect KeePassXC to display any message since I am not on a page where i need to login. I'm already logged in.

## Actual Behavior
See steps to reproduce above.

## Context
Accessing Pivotal through Firefox v 96.0.3

KeePassXC - v 2.6.6
KeePassXC-Browser - v 1.7.11

Operating System: macOS

![Toast-Warning-20220211](https://user-images.githubusercontent.com/149050/153675185-1a2cda99-cdce-4047-804c-18547f68c0ee.png)

**Comment by varjolintu** [comment]
Are you using auto-fill? Maybe there's some error identifying Custom Login Fields. Have you saved any for the site?

**Comment by varjolintu** [comment]
Closed due inactivity.
