### ISSUE TITLE
Browser integration, don't display "fills creditials" icon when there's no match

### ISSUE THREAD

**Issue by freedriven** [keepassxreboot/keepassxc-browser#1556]
## Summary
Browser integration, do not show the "fills credentials from XkeePassxc" icon when URL doesn't match any entry in keepassxc

## Context
When using the browser integration, it's annoying that the keepassxc "fills credentials" icon shows up even if I don't have matching URL or credentials saved in keepassxc. The keepassxc "fills credentials" icon shouldn't appear on all login prompts by default.

**Comment by varjolintu** [comment]
Already under work:
https://github.com/keepassxreboot/keepassxc-browser/pull/1490

It doesn't hide the icon but displays it with grayscale.

**Comment by freedriven** [comment]
Awesome, thanks!
