### ISSUE TITLE
Don't detect Passwords on "other" open Databases (if you have multiples)

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc-browser#1557]
This issue looks nearly like this one [#1430](https://github.com/keepassxreboot/keepassxc-browser/issues/1430), but it's not similar. 
As the reason of the issue might be the same, I notice this other issue here.

## Environment
I do have 4 Password-Databases open in Keepassx:
![image](https://user-images.githubusercontent.com/1778068/153853528-96edefdf-1806-42f8-a91c-5764e9e543a0.png)

If I've focused the first Tab (as you see on the screenshot above) and open a Page in the Browser, which has it's password in Tab No.4, it wouldn't be recognized. 
I have to open KeepassXC, switch the Tab to No. 4, and go back to the browser. Then I immediately see that he keepassxc-browser found the entries. 

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system:Linux (Manjaro)
Browser: Chrome (Brave)

**Comment by varjolintu** [comment]
And you have "Search in all opened databases" option enabled in KeePassXC?

**Comment by jfdtse** [comment]
> And you have "Search in all opened databases" option enabled in KeePassXC?
Thanks. Works for me.

**Comment by xstable** [comment]
@varjolintu I can't find this setting, can you show me where it is?

**Comment by varjolintu** [comment]
@xstable KeePassXC settings -> Browser Integration page, General tab.

**Comment by xstable** [comment]
@varjolintu great, that's work like a charm. I was searching for it in the browser-plugin itself on chrome :)
