### ISSUE TITLE
Autoenable Username Only for Synology DSM 7 Login pages

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [keepassxreboot/keepassxc-browser#1558]
## Expected Behavior

Username only filling should be enabled by default for Synology DSM 7 login pages.

## Current Behavior

KeepassXC fill icon is missing from the Username field in step 1 (it is present for password in step 2)
![image](https://user-images.githubusercontent.com/5708088/153868038-42d5b260-9c9d-4135-9c0f-72b932ff8ff4.png)
Login URL has to be manually added to "Add Username only option for this site"

## Possible Solution

create or extend a "detection logic" to determine that a page is a DSM 7 login page e.g. by detecting if a field with `syno-id="username"` is present
![image](https://user-images.githubusercontent.com/5708088/153868201-35c1758c-8e54-4572-bb51-c387b8514b2c.png)

## Steps to Reproduce (for bugs)

1. open a synolgy dsm 7 login page
2. username cant be autofilled (keepassxc icon missing)
3. enable user name only for the site
4. fill username and then password in step 2

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Win64
Browser: Mozilla Firefox 97.0

**Comment by tofuSCHNITZEL** [comment]
I know this is the way I do it know... but I manage over 50 synologys and I would need to add them all manually on all devices I use... so I thought there would be a way to have the browser extension recognise a username only field automatically...
(to have such a mechanic would be good for loads of different sites that have username only, right?)

**Comment by droidmonkey** [comment]
You can expert the extension settings and import them elsewhere

**Comment by tofuSCHNITZEL** [comment]
is there a way to have them synced over the mozilla sync feature?
would it be possible to implement some sort of username only site detection in future versions?
in this case the username only field could be easily identified by `syno-id="username"` could this not be integrated into the input field detection code?

**Comment by tofuSCHNITZEL** [comment]
yes the popup does suggest it.

**Comment by varjolintu** [comment]
It's very automatic after the click! ;)
