### ISSUE TITLE
Password input stopped working

### ISSUE THREAD

**Issue by davidak** [keepassxreboot/keepassxc-browser#1559]
I think since 15.2.2022 the input of passwords does not work anymore.

## Expected Behavior

When i load a page i have a password saved in keepassxc for it shows the icon in the login form.

![Screenshot from 2022-02-17 21-45-45](https://user-images.githubusercontent.com/91113/154568394-6778286c-bda8-43fd-86ca-7110e147bcf3.png)

When i click it, the password in put in.

## Current Behavior

When i click the icon nothing happens.

Reproducible on these URL:

https://www.gls-online-filiale.de/banking-private/entry?pk_campaign=gls__KONTO&partnerId=c-gls__KONTO
https://login.mailbox.org/
https://www.fairmondo.de/user/sign_in
https://gitlab.com/users/sign_in
https://www.pornhub.com/login
https://soundcloud.com/
https://bandcamp.com/login
https://sourceforge.net/auth/

**This affects all tested websites!**

## Possible Solution

I thought an update of the extension may broke it, but the version did not change recently.

I also did not update Chrome or KeePassXC recently.

It's also not likely that every website change their form.

So i have no idea. But at least it's reproducible and you can hopefully debug it.

## Steps to Reproduce (for bugs)

1. Try to login with the extension on any Website. If it works, try any of the listed above.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Chrome/Chromium 97.0.4692.99

**Comment by davidak** [comment]
I **had** a second database open that was already closed, but i had to restart the program to get it working again.

Can this behavior get improved?

**Comment by droidmonkey** [comment]
You can enable "Search in all open databases" in the browser integration settings. We have another request already tracking this improvement. Going to close this one.
