### ISSUE TITLE
URL path is ignored

### ISSUE THREAD

**Issue by cjaone** [keepassxreboot/keepassxc-browser#156]
## Steps to Reproduce

1. add new entry in KeePassXC with URL https://github.com/login
2. load page https://github.com/ (without the "/login" path) in your browser

## Current Behavior

KeePassXC-Browser already wants to fill in fields at https://github.com/ But on that page there's just the registration form, not the login form.

## Expected Behavior

No KeePassXC-Browser popup on the https://github.com/ page.

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.1.3
Operating system: Linux
Browser: Chromium
Proxy used: NO

**Comment by varjolintu** [comment]
KeePassXC settings -> Browser Integration -> [x] Return only best-matching credentials
