### ISSUE TITLE
bikeinn.com login fields are not detected

### ISSUE THREAD

**Issue by lucamp** [keepassxreboot/keepassxc-browser#1563]
## Current Behavior

login fields at bikeinn.com are not detected, even with custom login fields

## Steps to Reproduce (for bugs)

1. go to [https://www.bikeinn.com/bike](https://www.bikeinn.com/bike)
2. click sign in my account

Bikeinn.com is part of other stores from tradeinn.com. If you want to use others site (such as outletinn.com) you need to manually add them in Keepassxc browser integration tab.

## Workaround
right click in the username field -> KeepassXC-Browser -> Fill username and password

## Debug info

KeePassXC - 2.6.2
KeePassXC-Browser - 1.7.11
Operating system: Linux debian bullseye
Browser: Firefox
![bikeinn custom login](https://user-images.githubusercontent.com/15078341/155836994-9ff8873a-4bc0-4142-bca7-813c9952ba5f.jpg)

**Comment by varjolintu** [comment]
The fields are actually correctly identified, but the input field size is not properly set/identified, so the icon is missing. You should still be able to fill the credentials using the extension icon from browser toolbar, context menu or keyboard shortcut.

**Comment by KIMWW** [comment]
> You should still be able to fill the credentials using the [...] keyboard shortcut.

What's the shortcut for that?

**Comment by varjolintu** [comment]
@KIMWW You can see the current shortcuts directly from the extension settings page.

**Comment by KIMWW** [comment]
Thanks @varjolintu but, as I said, in fact it is NOT mention on your help page: KeePassXC - Keyboard Shortcuts. See screenshot
![FireShot Capture 017 - KeePassXC - Keyboard Shortcuts - ](https://user-images.githubusercontent.com/30148003/173567050-23bbd970-5821-4495-94c3-a8443da7af4f.png)
.

**Comment by varjolintu** [comment]
@KIMWW That's help page for KeePassXC, not for KeePassXC-Browser.

**Comment by KIMWW** [comment]
@varjolintu Okay! My mistake. Thanks for having clarified this.
And congrats for the FF KeePassXC-Browser add-on.
