### ISSUE TITLE
User-only option not working for https://help.citavi.com/oauth/login

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [keepassxreboot/keepassxc-browser#1564]
This is not a real bug report against KeePassXC or its browser AddIn. I assume that the problem is the website itself. I just need a confirmation of that problem from a third party.

I am using KeePassXC (2.6.2 on Debian stable; 2.6.6 on Windows 10) with the KeePassXC-browser AddIn for Firefox (Debian) and MS Edge (Windows).

This login side separate the field for username and password like Google does it.
https://help.citavi.com/oauth/login

KeePassXC offers a username-only option for that. This works very well on Google and other sites like this.
But not on that Citavi site I linked here.
**EDIT**: KeePassXC does insert the username correct here but not the password.

Maybe I am doing something wrong? Or maybe the website use an exotic/unusual technology to separate the username and password field. Maybe some of you can give a hint to the WebDesiger about what could be improved on that site.

**Comment by varjolintu** [comment]
The Username-Only option added from the popup seems to work fine. The URL however for your entry should be `https://login.qsrinternational.com/`.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
You haven't tested that yourself, right?

Of course my URL is set correct. The username is entered without problems, but the password is not.

**Comment by varjolintu** [comment]
I have no logins to the site. I only tested entering the username. There was no mention about the password in the original message.

**Comment by varjolintu** [comment]
Seems the actual field has `display: none` which is why the extension ignores it. Please wait for a fix where entering a password from context menu / keyboard shortcut which allows setting the value for any input field. Currently we also ignore "hidden" fields with that method.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Thanks for analysing this thing.
But why is this closed when there is currently no fix for that?

**Comment by varjolintu** [comment]
Because there's no fix for the current issue :) Allowing fields that are hidden in DOM are ignored correctly. However, this issue should be followed instead: https://github.com/keepassxreboot/keepassxc-browser/issues/1574.
