### ISSUE TITLE
Does not work on subdomains

### ISSUE THREAD

**Issue by Saectar** [keepassxreboot/keepassxc-browser#1566]
The add-on is not able to detect subdomains.

For example, in my database I have added the Wikipedia site (`https://www.wikipedia.org/`), the plugin is unable to show me the login credentials when I enter some regional version of Wikipedia as `https://en.wikipedia.org/` or `https://es.wikipedia.org/`. The same thing happens to me with various subdomains of other websites.

Please, fix this issue.

**Comment by droidmonkey** [comment]
Just remove the www from the url field in KeePassXC

**Comment by Saectar** [comment]
I have over five hundred passwords, many of which have this same problem. It would be quite useful if the add-on was able to recognize subdomains.

**Comment by droidmonkey** [comment]
We recognize them as long as you don't define one. Believe it or not, www is a subdomain. We will match the provided domain and any subdomain under it. So www.wikipedia.com will match that and something like de.www.wikipedia.com. 

We do this very explicitly for both security and scoping reasons.
