### ISSUE TITLE
Filling in credentials via context menu not working for bahn.de and several other websites (macOS / Chrome)

### ISSUE THREAD

**Issue by timotgl** [keepassxreboot/keepassxc-browser#1567]
## Expected Behavior
Given that I have saved the credentials for a website in KeePassXC, right-clicking on a username or password input on a website and selecting "Fill Username and Password" or "Fill Password only" from the KeePassXC-Browser context menu fills in username and password, or only the password respectively.

## Current Behavior
Nothing is filled in, the input(s) remain as they were (empty), no error message is shown, the browser extension is not responding to this in any way. The browser's JS console does not show any messages.

## Steps to Reproduce (for bugs)
 1. Create a valid user account with bahn.de (german train and railroad provider)
 1. Go to https://www.bahn.com/en and select "Login" -> "Private Customers" from the upper right menu.
 1. Arriving on the login from, which has a URL in the format `https://accounts.bahn.de/auth/realms/db/protocol/openid-connect/auth?cancel_uri=<someUrl>&<moreUrlParamsHere>`, right-click on the password input and select "Fill Password Only" from the KeePassXC-Browser context menu
 1. Notice that nothing happens.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: macOS 12.2.1
Browser: Chrome 99.0.4844.51 (Official Build) (arm64)

The markup of the login form appears pretty normal to me, here's a screenshot:
<img width="1199" alt="Screenshot 2022-03-06 at 12 15 20" src="https://user-images.githubusercontent.com/366377/156920737-375cc821-0413-4cb4-b877-feec5d2896d9.png">

The credentials in KeePassXC are saved liked this:
<img width="1102" alt="Screenshot 2022-03-06 at 12 18 36" src="https://user-images.githubusercontent.com/366377/156920857-0cf82ea0-a7b1-48eb-b4c6-4e1368a51d15.png">

The browser extension doesn't seem to report anything unusual and is properly connected with the desktop app:
<img width="450" alt="Screenshot 2022-03-06 at 12 20 03" src="https://user-images.githubusercontent.com/366377/156920875-72c2e64f-1457-4f3b-b590-ae82a2fd02c4.png">
(clicking "Redetect login fields" doesn't do anything)

It's entirely possibly that I'm just using KeePassXC and KeePassXC-Browser wrong. I only recently migrated to it from 1password. Filling in credentials doesn't really work for any website, only occasionally it works for me on PayPal. Is there possibly a requirement for the URL to be an exact match? Do I need to use a wildcard so that when I'm on `https://accounts.bahn.de/auth/realms/db/protocol/openid-connect/auth?cancel_uri=<someUrl>&<moreUrlParamsHere>` in the browser it is matched to the correct credentials by saving `https://accounts.bahn.de/auth/realms/db/protocol/openid-connect/auth?*` in the desktop app? Any help is welcome, thank you in advance.

**Comment by varjolintu** [comment]
Just use `https://bahn.de` as the entry URL?

**Comment by timotgl** [comment]
@varjolintu Neither `https://accounts.bahn.de` nor `https://bahn.de` work unfortunately. Same issue.

**Comment by varjolintu** [comment]
That's very strange. I tried it with the current 1.8.0-dev and Microsoft Edge and with the current 1.7.11-stable with Firefox. Both worked fine with `https://bahn.de` as the entry URL. On macOS of course.

Can you check that you haven't set any Custom Login fields for the page? Or you haven't denied the access to your entry in KeePassXC? Create a new entry to test it, or go to the current entry's Properties tab and see the permissions.

**Comment by timotgl** [comment]
@varjolintu I didn't have any custom login fields defined, access to the entry was also granted.

But I found the culprit, disabling my [uBlock Origin chrome extension](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm) solves the problem. Even though I had `bahn.de` and `accounts.bahn.de` listed as trusted sites in the ad-blocker, there is some kind of interference.

Thanks for your time anyway!
