### ISSUE TITLE
Browser addon suggests entries despite disabled auto-type for group of entry

### ISSUE THREAD

**Issue by J-Lakeman** [keepassxreboot/keepassxc-browser#1572]
## Expected Behavior
Entries in the database where auto-type has been disabled for the group shouldn't be suggested by the browser add-on.

## Current Behavior
Entries with disabled auto-type still get suggested, e. g. every single 2FA device password.

## Possible Solution
Make the browser extension respect the auto-type group setting.

## Steps to Reproduce (for bugs)

1. Create a group in the Keepass database
2. Disable auto-type for the group
3. See suggestions in the browser

## Debug info

KeePassXC - {2.6.6}
KeePassXC-Browser - {1.7.11}
Operating system: Linux
Browser: Firefox

![Bildschirmfoto von 2022-03-15 21-50-09 cleaned](https://user-images.githubusercontent.com/101660243/158470929-833ad49b-8214-4e7d-9845-a8096c1e727c.png)

**Comment by droidmonkey** [comment]
Browser integration has nothing to do with Auto-Type. 2.7.0 introduces group settings for browser integration.
