### ISSUE TITLE
Username field not detected for banking.bankaustria.at

### ISSUE THREAD

**Issue by sphh** [keepassxreboot/keepassxc-browser#1583]
## Expected Behavior

When I open the online banking website of Bank Austria:
https://banking.bankaustria.at/wps/portal/retail/de/login/login
only the password field is automatically detected, but not the username field (that one above the password field and having ‘Verfügernummer’ in it).

## Current Behavior

Opening the online banking website, the password field gets the keepassxc icon, but not the username field above it.

Right-clicking on the username field, selecting `Fill Username and Password` does not fill the username (and neither the password).

`Fill Password Only` does work.

## Steps to Reproduce (for bugs)

1. Open https://banking.bankaustria.at/wps/portal/retail/de/login/login
2. Right click on the username field with ‘Verfügernummer’ in it.
3. Select `Fill Username and Password`
4. Username is not filled in

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Could not reproduce it. Used 1.7.11 with Firefox and 1.8.0-dev with Edge. Check that your entry URL is `﻿https://banking.bankaustria.at/`.

**Comment by sphh** [comment]
I used tried it with https://banking.bankaustria.at/wps/portal/retail/de/login/login/ and https://banking.bankaustria.at/, both as URL in Firefox and in KeePassXC. The `KP2A_URL` is https://banking.bankaustria.at/ and `Autotype` is disabled.

The Firefox version is 98.0.1 and here is a screenshot with the missing green icon in the username field:
![Screenshot from 2022-03-22 09-46-49](https://user-images.githubusercontent.com/4856462/159442871-5086728e-f6a5-49c5-a2fa-908968af9153.png)

**Comment by varjolintu** [comment]
Do you have some Custom Login Fields enabled for the site? Nothing else explains that.

**Comment by sphh** [comment]
Not that I am aware of. Where would I find this setting, so that I can check?

**Comment by varjolintu** [comment]
Extension settings, Site Preferences tab. You could also try to make a new temporary profile for Firefox and see if it behaves differently. Or test the same page with another browser.

**Comment by sphh** [comment]
No, no Custom Login Fields enabled … But if I enable them and select the appropriate fields, I can get the green KeePassXC icon in the user name and the green key in the password field. Unfortunately when I now press the KeePassXC icon (or select `Fill Username and Password` from the context menu), nothing happens at all.

Maybe some other add-ons are interfering here? I will switch them off one by one; maybe I can figure out, which one is the ‘culprit’ …

**Comment by varjolintu** [comment]
That might be one reason. Hopefully you'll find it. I cannot provide any more help from my end.

**Comment by sphh** [comment]
I disabled _all_ add-ons, but this has not improved the situation: The username field is still not detected.

Is there something, I can do to figure out, why it is not detected?

**Comment by varjolintu** [comment]
You can always try the current dev version and see if it already fixes the issue.
Download https://github.com/keepassxreboot/keepassxc-browser/archive/refs/heads/develop.zip and load the `manifest.json` file through `about:debugging#/runtime/this-firefox` using _Load Temporary Add-On_  button.

**Comment by sphh** [comment]
The current dev version could not detect the username field either.

But I could now set the username and password field with the help of `Choose custom login fields`. Now both are detected correctly.

Since it works for me at the moment (with custom login fields), I close this issue. If you want to investigate further, I'll be more than happy to provide whatever information you need!

Thanks for your great help! :bowing_man:
