### ISSUE TITLE
Browser integration not working with QNAP

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc-browser#1585]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to my qnap page (local ip like https://192.168.10.150/
2.  I see login page with username and password
3. there is keepass icon next to password field which only fills in password but not the username

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
both username + password filled in

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Only password fills in

## Context
[NOTE]: # ( Give us any additional information you may have. )
I also tried "Choose custom login fields" but i cant make it work. I dont see confirm button when i select the right combination + most time field 1 (username) is stuck with TOTP. With this combination i see confirm but never with the right combination. See attachments.
![Screenshot 2022-03-26 142513](https://user-images.githubusercontent.com/4087127/160241657-5ae33219-6e46-41bc-9c4f-650ac251597e.png)
![Screenshot 2022-03-26 142914](https://user-images.githubusercontent.com/4087127/160241729-7fe83708-86b0-42cd-8c23-ddef5d007f9e.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.0
Revision: d7a9ef4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 x64

**Comment by varjolintu** [comment]
Is there some free demo page available where I can test this? If not, can you give the HTML code of that login form? Thanks.

**Comment by vampyren** [comment]
> Is there some free demo page available where I can test this? If not, can you give the HTML code of that login form? Thanks.

I dont think there is a demo page since the server is run on the hardware itself but i right click and saved the html if that help.
[view-source_https.zip](https://github.com/keepassxreboot/keepassxc-browser/files/8355739/view-source_https.zip)

**Comment by varjolintu** [comment]
Just send the source of the login form, not the whole page, thanks.

**Comment by vampyren** [comment]
> 

Not sure exactly how i get that but i go to debug and select the login section as in picture, is that what you need?
Otherwise please give me some instruction how to get it for you.
![Screenshot 2022-03-26 234904](https://user-images.githubusercontent.com/4087127/160259555-38ea05d9-3cf7-4164-a82a-7e3473764f3e.png)

**Comment by varjolintu** [comment]
Seems it's a `textarea` element. That should be still allowed for selection in Custom Login Fields. What if you press <kbd>M</kdb> (more) before selecting the username?

**Comment by vampyren** [comment]
> 

I show that above in picture, i can only select TOTP, but if i press A and play around so i can select correct as in picture then there is no confirm option so i cant do anything.

**Comment by varjolintu** [comment]
You'll have to either skip the TOTP field or select it.

**Comment by vampyren** [comment]
> 

Not sure what you mean, should it say TOTP on username when i confirm? 
I tried it and this is how it went
![image](https://user-images.githubusercontent.com/4087127/160348850-4f126926-921d-447b-9adc-f11460b2e8e3.png)

![image](https://user-images.githubusercontent.com/4087127/160348923-dcee5de2-a6dd-4262-a236-c23a9666df55.png)

**Comment by vampyren** [comment]
hmm not sure what i just did, maybe press Skip once and then suddenly confirm was shown with the right combination so i had Username instead of TOTP. Now it works! 
Its not really straight forward to be honest but works now.

**Comment by varjolintu** [comment]
The upcoming extension version refactors the whole Custom Login Fields selection, so it's going to change anyway.

**Comment by vampyren** [comment]
ah sounds great! I'm loving KeePassXC and moving to it. All the better if the extension also gets updated and gets easier to use :D 
Cheers.
