### ISSUE TITLE
Password generator not working in Firefox with released extension (1.17.11) and released keepassxc (2.7.0)

### ISSUE THREAD

**Issue by sdrik** [keepassxreboot/keepassxc-browser#1586]
## Expected Behavior
The native password generator dialog should be launched when a password generation is requested.

## Current Behavior
Nothing happens.
There is a "Cannot decrypt message" error in the extension debugging console.

## Possible Solution
After building the extension from the develop branch and loading it (unsigned) in a Firefox Developer Edition instance, everything seems to work as expected.
A bisection leads to 4a0cf3abcec8a1ed3c468e1aa887a396affb09fe which is the first working commit.

A new release of the extension would be much appreciated.

**Comment by varjolintu** [comment]
A new version fixes the problem, yes. We'll try to releaes it soon. Currently there are still few PR's left for review.

**Comment by gnemesure** [comment]
This is also broken on Chromium on Arch Linux and Chrome on Windows 10.

**Comment by gnemesure** [comment]
This is also broken on Chromium on Arch Linux and Chrome on Windows 10.

**Comment by gnemas** [comment]
This is also broken in Chromium on Arch Linux and Chrome on Windows 10.

**Comment by MattTheTechLV** [comment]
Also Experiencing this in Chrome & Firefox On Windows

**Comment by aftadizca** [comment]
also broken in Vivaldi Browser... got message like this
![image](https://user-images.githubusercontent.com/16900725/162021531-b72e306c-f885-4f03-a904-dd7915a343df.png)

**Comment by varjolintu** [comment]
It's broken on all browsers because only releasing the next extension version solves it. No need to report browsers, thanks :)

**Comment by TomasEkeli** [comment]
seems like something that could deserve its own release instead of waiting for other pull-requests, no?

**Comment by varjolintu** [comment]
@TomasEkeli Easier said than done at this point. The master branch is protected and it's a PITA to update, and of course it's not up-to-date with 1.7.11. With 1.8.0 I'm gonna make a separate branch 1.8.x, just like we've done with KeePassXC repository so these kind of issues are easier to fix.

**Comment by varjolintu** [comment]
Aaand 1.7.12 has been released to the extension stores.

**Comment by xcasxcursex** [comment]
1.7.12 Working great here. Thanks very much for your hard work.
