### ISSUE TITLE
Vivaldi browser and Pop_OS! 21.10

### ISSUE THREAD

**Issue by patschwork** [keepassxreboot/keepassxc-browser#1589]
## Expected Behavior
Browser plugin shows "Connect" (German "Verbinden") and you are able to connect to an KeePass database file.
A dialog appears with the name for the new connection

## Current Behavior
The plugin shows "Schlüsselaustausch war nicht erfolgreich" (in German / translated in English "key exchange not successful")

## Possible Solution
There is already a hint mentioned here: https://github.com/keepassxreboot/keepassxc-browser/issues/405#issuecomment-460052033

After I made a symlink...
```sh
ln -s /home/<USERNAME>/.var/app/org.keepassxc.KeePassXC/config/vivaldi/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json /home/<USERNAME>/.config/vivaldi/NativeMessagingHosts/
```
...and restarted the Vivaldi browser it worked as expected

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.7.11
Operating system: Linux Pop_OS! 21.20
Browser: Vivaldi 5.1.2567.66 (Stable channel) stable (64-Bit) 

If somebody is having similar issues, maybe this is also a solution

**Comment by varjolintu** [comment]
AFAIK your [Helper Script](https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh) does this also.
