### ISSUE TITLE
KeePassXC-browser (chrome) fails to connect after KeePassXC update to 2.7.0

### ISSUE THREAD

**Issue by borkborkNFork** [keepassxreboot/keepassxc-browser#1593]
## Expected Behavior

KeepassXC-browser extension should be able to connect to KeepassXC and access the database after the KeepassXC app is updated from the previous major version to version 2.7.0

Clicking on the browser extension icon in Chrome >> Reload should reconnect to a running instance of KeepassXC.

## Current Behavior

Previously, before the update of the application, the browser extension worked flawlessly.

I have installed Firefox and the browser extension on the computer and ~I am~  *was* encountering the same problem.

I am documenting my troubleshooting attempts here with regards to the browser extension as I have not noticed anyone else with this issue. I am not ruling out that there could be an issue with the application instead.

Currently in Chrome I see the following message:
```
KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
```

Clicking the Reload button reports the following:

```
KeePassXC-Browser has encountered an error:

Key exchange was not successful.
```

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

I have not been (and I am not physically) able to replicate this bug on a different computer.

However I would suggest the following steps as I believe it closely matches my experience before encountering this problem.

1) With a KeepassXC version pre 2.7.0 installed on a Windows 10 computer with Chrome and the KeepassXC-browser extension installed and working correctly...
2) Download the KeepassXC version 2.7.0 MSI for Windows 10.
3) While KeepassXC is still running, attempt to update it.
4) Click OK on the prompt that states *"The setup must update files or services that  cannot be updated while the system is running. If you choose to continue, a  reboot will be required to complete the setup."*
5) Finish the install & reboot the computer.
6) Launch KeepassXC and Chrome.
7) Attempt to connect KeepassXC-browser to the database.
8) Observe the error message described previously in this issue.

Additionally, I have tried installing Firefox and I *was* encountering the same error messages...

## Debug info

KeePassXC - 2.7.0
KeePassXC-Browser - 1.7.11
Operating system: Windows 10
Browser: Chrome 99.0.4844.84 (Official Build) (64-bit)  & Firefox 98.0.2 (64-bit)

Following the Troubleshooting guide...

I have verified that my instance of KeepassXC has...
1) the ✔️ **Enable browser integration** 
2) integrations for  *"Chrome, Vivaldi, and Brave"*, & *"Firefox and Tor Browser"* are checked.

I have purged the Connected Databases list from the extension in Chrome.

Chrome registry entry: `HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\` Name: (Default), Type: Reg_SZ, Data: `C:/Users/glowbox-user/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_brave.json`
**Note** When first inspected, this registry's data value was blank. Running the MSI installer and selecting Repair did populate it with the above.

Firefox registry entry: `HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\` Name: (Default), Type: REG_SZ  Data: `C:/Users/glowbox-user/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_tor-browser.json`

Uninstalling and Reinstalling KeePassXC and trying Firefox again, and it now appears to be working but still failing in Chrome. 🤷 

### Check if keepassxc-proxy is launched and running.

There are no steps on how to verify this in the troubleshooting guide for Windows. However, since I have this working on Firefox now, I assume this isn't the problem?

### Checking the AppData/Local/KeePassXC  json files
Opening the `org.keepassxc.keepassxc_browser_chrome.json` file:

```
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}

```
1) shows two(?) allowed origins. The second value matches the ID of the KeePassXC-browser extension in Chrome.
2) The path looks good, and I verified that something is at that destination.

Firefox: 

```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```

###  Check if keepassxc-proxy is launched and running
The troubleshooting guide does not have instructions for how to "Find the native messaging configuration path with strace" in Windows.

### Background Page:
The developer console shows the following upon attempting to connect.

```
Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:1104 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1074 Failed to connect: Failed to start native messaging host.
keepass.js:1187 Error 9: Key exchange was not successful.
```

> If you are a developer and know these things you can use the Sources tab and debug the extension and find the exact point where it fails.

I am not a good developer, I do not know these things (yet). I am not sure how to proceed further with these console errors.

**Comment by borkborkNFork** [comment]
The only thing that I noticed that was odd was the registry entry for the chrome extension points to the wrong browser? I have read that the Firefox registry is correct to point to the Tor entry.

I will attempt to edit the chrome registry entry, reboot everything and see what happens.

**Comment by borkborkNFork** [comment]
After restart the registry data values are as follows:

Chrome: `C:/Users/glowbox-user/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_brave.json` (it has reverted...)
Firefox: `C:/Users/glowbox-user/AppData/Local/KeePassXC/org.keepassxc.keepassxc_browser_tor-browser.json`

I just noticed there's a registry entry for Chromium as well (HKEY_CURRENT_USER\SOFTWARE\Chromium\NativeMessagingHosts\org.keepassxc.keepassxc_browser) where the data is not set. 🤷 

Chrome is still afflicted 😢 . Firefox is behaving correctly. 🤔 

Further advice on how to proceed would be appreciated.

Thank you!

**Comment by varjolintu** [comment]
> The troubleshooting guide does not have instructions for how to "Find the native messaging configuration path with strace" in Windows.

https://docs.microsoft.com/en-us/sysinternals/downloads/procmon Is the correct way to check the paths.

**Comment by ConvarDeutschland** [comment]
Same Problem with Brave since installation from new Brave version. Connection of DB not working
Brave: [Version 1.36.111 Chromium: 99.0.4844.51 (Official Build) unknown (64-bit)]
KeepassXC: 2.6.6
KeepasXC Browser: 1.7.11

Firefox and chrome work well

**Comment by varjolintu** [comment]
@ConvarDeutschland Try enabling Chromium support also. Sometimes Brave uses those settings, dunno why. Look at the troubleshooting guide and report your findings.

**Comment by borkborkNFork** [comment]
> > The troubleshooting guide does not have instructions for how to "Find the native messaging configuration path with strace" in Windows.
> 
> https://docs.microsoft.com/en-us/sysinternals/downloads/procmon Is the correct way to check the paths.

Thank you.

I've isolated a chunk of Process Monitor logs filtered around just the Chrome process while I opened and the browser extension and clicked Reload.

I see some registry queries for NativeMessagingHosts, chrome reading the `org.keepassxc.keepassxc_browser_brave.json` file and the keepassxc-proxy getting created(?)/read.

Additionally I see there's a command line executed by I assume some method similar to Start > Run (windows enviroments are not my forte) `C:\Windows\system32\cmd.exe /d /c "C:\Program Files\KeePassXC\keepassxc-proxy.exe" chrome-extension://oboonakemofpalcgghocfoadofidjkkk/ --parent-window=0 < \\.\pipe\chrome.nativeMessaging.in.94d8e70637609cd3 > \\.\pipe\chrome.nativeMessaging.out.94d8e70637609cd3`

Later on in the logs I see the following which look like errors relating to the above command. Namely the attempt to create a file at `C:\d` and `C:\c` and the Invalid Name error with the query containing the extension ID

```
11:36:10.8578505 AM	chrome.exe	11988	CreateFile	C:\Windows\System32\cmd.exe	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
11:36:10.8578749 AM	chrome.exe	11988	QueryBasicInformationFile	C:\Windows\System32\cmd.exe	SUCCESS	CreationTime: 2022-01-21 8:24:09 PM, LastAccessTime: 2022-04-04 11:36:10 AM, LastWriteTime: 2022-01-21 8:24:09 PM, ChangeTime: 2022-03-09 11:35:40 AM, FileAttributes: A
11:36:10.8578807 AM	chrome.exe	11988	CloseFile	C:\Windows\System32\cmd.exe	SUCCESS	
11:36:10.8579669 AM	chrome.exe	11988	CreateFile	C:\d	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
11:36:10.8580327 AM	chrome.exe	11988	CreateFile	C:\c	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
11:36:10.8581163 AM	chrome.exe	11988	CreateFile	C:\Program Files\KeePassXC\keepassxc-proxy.exe	SUCCESS	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
11:36:10.8581273 AM	chrome.exe	11988	QueryBasicInformationFile	C:\Program Files\KeePassXC\keepassxc-proxy.exe	SUCCESS	CreationTime: 2022-03-21 8:51:06 PM, LastAccessTime: 2022-04-04 10:57:12 AM, LastWriteTime: 2022-03-21 8:51:06 PM, ChangeTime: 2022-04-03 9:00:10 PM, FileAttributes: A
11:36:10.8581317 AM	chrome.exe	11988	CloseFile	C:\Program Files\KeePassXC\keepassxc-proxy.exe	SUCCESS	
11:36:10.8581853 AM	chrome.exe	11988	CreateFile	C:\Program Files\Google\Chrome\Application\100.0.4896.60\chrome-extension:\oboonakemofpalcgghocfoadofidjkkk\	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
11:36:10.8582595 AM	chrome.exe	11988	CreateFile	C:\Program Files\Google\Chrome\Application\100.0.4896.60\--parent-window=0	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
11:36:10.8583227 AM	chrome.exe	11988	CreateFile	C:\Program Files\Google\Chrome\Application\100.0.4896.60\.	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
11:36:10.8583961 AM	chrome.exe	11988	CreateFile	C:\Program Files\Google\Chrome\Application\100.0.4896.60\.	NAME INVALID	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

```

Not sure how to interpret this so far. I have full logs saved in a text file If that would be useful. Alternatively I'll be happy to collect new logs if you have a suggested process monitor filter set.

**Comment by ConvarDeutschland** [comment]
@varjolintu enabling Chromium support does not help.

Also check with version 2.7.0 problem is still the same for Brave. 

I also copied the file org.keepassxc.keepassxc_browser.json from ".config/google-chrome/NativeMessagingHosts/" in the different folders from the other Browsers under ./config but this also did not help. Error message remaining "key exchange was not successful"

**Comment by varjolintu** [comment]
@ConvarDeutschland Are you on macOS or Linux? You didn't say your OS. If Linux, check that Brave is not running as a Snap or Flatpak. Use the troubleshooting guide's method for `strace` for inspecting the correct path.

**Comment by ConvarDeutschland** [comment]
@varjolintu 
I'm on Linux (Manjaro) Brave is not running as a Snap or Flatpak

Where can I fing the troubleshooting guide's method for strace

**Comment by varjolintu** [comment]
@ConvarDeutschland https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace=

**Comment by ConvarDeutschland** [comment]
@varjolintu

here the result of the trace, can you see anything wrong?
for me the path is the right one for KeePassXC.AppImage

[pid 24960] access("/home/userone/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json", F_OK <unfinished ...>
[pid 24960] openat(AT_FDCWD, "/home/userone/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 24960] access("/hdd/Programs/keepassxc/KeePassXC.AppImage", F_OK) = 0
[pid 25117] chdir("/hdd/Programs/keepassxc") = 0
[pid 25117] execve("/hdd/Programs/keepassxc/KeePassXC.AppImage", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x2526004c88c0 /* 51 vars */) = 0
[pid 25117] readlink("/proc/self/exe", "/hdd/Programs/keepassxc/KeePassX"..., 4096) = 42
[pid 25118] readlink("/proc/25118/exe", "/hdd/Programs/keepassxc/KeePassX"..., 1023) = 42
[pid 25118] readlink("/hdd/Programs/keepassxc", 0x7fff4a881060, 1023) = -1 EINVAL (Invalid argument)
[pid 25118] readlink("/hdd/Programs/keepassxc/KeePassXC.AppImage", 0x7fff4a881060, 1023) = -1 EINVAL (Invalid argument)
[pid 25118] openat(AT_FDCWD, "/hdd/Programs/keepassxc/KeePassXC.AppImage", O_RDONLY) = 3
[pid 25117] access("/hdd/Programs/keepassxc/KeePassXC.AppImage.home", W_OK <unfinished ...>
[pid 25117] access("/hdd/Programs/keepassxc/KeePassXC.AppImage.config", W_OK <unfinished ...>
[pid 25117] <... getcwd resumed>"/hdd/Programs/keepassxc", 1024) = 24
[pid 25117] execve("/tmp/.mount_KeePas0v6hMJ/AppRun", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x14739b0 /* 55 vars */ <unfinished ...>
[pid 25117] <... getcwd resumed>"/hdd/Programs/keepassxc", 4096) = 24
[pid 25117] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc",  <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc",  <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", X_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", R_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", X_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc",  <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", R_OK <unfinished ...>
[pid 25117] execve("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", ["keepassxc", "chrome-extension://oboonakemofpa"...], 0x55592899cab0 /* 56 vars */ <unfinished ...>
[pid 25117] readlink("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", 0x7ffe2aeefb90, 1023) = -1 EINVAL (Invalid argument)
[pid 25117] read(7, "keepassxc\0chrome-extension://obo"..., 4096) = 63
[pid 25117] writev(7, [{iov_base="\22\0\t\0\1\0\340\5\"\0\0\0\37\0\0\0\10\30\0\0\n\0\0\0keepassx"..., iov_len=244}, {iov_base=NULL, iov_len=0}, {iov_base="", iov_len=0}], 3) = 244
[pid 25117] openat(AT_FDCWD, "/tmp/keepassxc-userone.lock", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = -1 EEXIST (File exists)
[pid 25117] openat(AT_FDCWD, "/tmp/keepassxc-userone.lock", O_RDONLY|O_CLOEXEC) = 14
[pid 25117] read(14, "21908\nkeepassxc\nfabrice-pc\n26ceb"..., 16384) = 97
[pid 25117] lstat("keepassxc", 0x7ffe2aef0bf0) = -1 ENOENT (No such file or directory)
[pid 25117] stat("/tmp/keepassxc-userone.lock", {st_mode=S_IFREG|0644, st_size=97, ...}) = 0
[pid 25117] openat(AT_FDCWD, "/tmp/keepassxc-userone.lock.rmlock", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0666) = 14
[pid 25117] write(14, "25117\nkeepassxc\nfabrice-pc\n26ceb"..., 97) = 97
[pid 25117] openat(AT_FDCWD, "/tmp/keepassxc-userone.lock", O_RDONLY|O_CLOEXEC) = 15
[pid 25117] read(15, "21908\nkeepassxc\nfabrice-pc\n26ceb"..., 16384) = 97
[pid 25117] lstat("keepassxc", 0x7ffe2aef0bf0) = -1 ENOENT (No such file or directory)
[pid 25117] openat(AT_FDCWD, "/tmp/keepassxc-userone.lock", O_WRONLY|O_CLOEXEC) = 15
[pid 25117] unlink("/tmp/keepassxc-userone.lock.rmlock") = 0
[pid 25117] access("/home/userone/.cache/keepassxc/keepassxc.ini", F_OK) = 0
[pid 25117] access("/home/userone/.config/keepassxc/keepassxc.ini", F_OK) = 0
[pid 25117] access("/home/userone/.config/keepassxc/keepassxc.ini", F_OK) = 0
[pid 25117] openat(AT_FDCWD, "/home/userone/.config/keepassxc/keepassxc.ini", O_RDONLY|O_CLOEXEC) = 14
[pid 25117] stat("/home/userone/.config/keepassxc/keepassxc.ini", {st_mode=S_IFREG|0644, st_size=5226, ...}) = 0
[pid 25117] access("/home/userone/.cache/keepassxc/keepassxc.ini", F_OK) = 0
[pid 25117] openat(AT_FDCWD, "/home/userone/.cache/keepassxc/keepassxc.ini", O_RDONLY|O_CLOEXEC) = 14
[pid 25117] stat("/home/userone/.cache/keepassxc/keepassxc.ini", {st_mode=S_IFREG|0644, st_size=2612, ...}) = 0
[pid 25117] connect(14, {sa_family=AF_UNIX, sun_path="/tmp/keepassxc-userone.socket"}, 110) = 0
[pid 25117] connect(16, {sa_family=AF_UNIX, sun_path="/tmp/keepassxc-userone.socket"}, 110) = 0
[pid 24785] <... read resumed>"25117 (keepassxc) Z 24763 1529 1"..., 4096) = 177

**Comment by varjolintu** [comment]
@ConvarDeutschland Ok, so Brave seems to find the script without any problems. Still, I don't understand why Firefox and Chrome work with the same KeePassXC AppImage? I'm wondering if there's some bug in Brave itself. Can you debug the background script and see if there's anything in the JavaScript console?

**Comment by ConvarDeutschland** [comment]
@varjolintu 

Console is showing this

Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1074 Failed to connect: Native host has exited.
keepass.js:1307 Error: No content script available for this tab.
keepass.js:1187 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
2keepass.js:1307 Error: No content script available for this tab.
keepass.js:1187 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:1104 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1187 Error 9: Key exchange was not successful.
keepass.js:1307 Error: No content script available for this tab.
keepass.js:1074 Failed to connect: Native host has exited.
keepass.js:1307 Error: No content script available for this tab.
keepass.js:1187 Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
keepass.js:1104 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:1187 Error 9: Key exchange was not successful.
keepass.js:1307 Error: No content script available for this tab.
keepass.js:1074 Failed to connect: Native host has exited.
keepass.js:1307 Error: No content script available for this tab.

**Comment by ConvarDeutschland** [comment]
@varjolintu 

I also try it with Brave-beta and with an older version of brave and it give me the same problem.
I can not understand what changed as ist was working for a long time.

**Comment by varjolintu** [comment]
@ConvarDeutschland Can you check the `strace` with Chrome/Chromium so I could compare if there's any different?

**Comment by ConvarDeutschland** [comment]
@varjolintu 

here the trace for chrome

[pid 29239] read(178, "29520 (keepassxc-proxy) S 29210 "..., 4096) = 330
[pid 29739] <... read resumed>"29520 (keepassxc-proxy) S 29210 "..., 4096) = 330
[pid 29293] access("/home/userone/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json", F_OK <unfinished ...>
[pid 29293] openat(AT_FDCWD, "/home/userone/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 29293] access("/hdd/Programs/keepassxc/KeePassXC.AppImage", F_OK) = 0
[pid 29740] chdir("/hdd/Programs/keepassxc") = 0
[pid 29740] execve("/hdd/Programs/keepassxc/KeePassXC.AppImage", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x3140073ce00 /* 54 vars */) = 0
[pid 29740] readlink("/proc/self/exe", "/hdd/Programs/keepassxc/KeePassX"..., 4096) = 42
[pid 29741] <... readlink resumed>"/hdd/Programs/keepassxc/KeePassX"..., 1023) = 42
[pid 29741] readlink("/hdd/Programs/keepassxc",  <unfinished ...>
[pid 29741] readlink("/hdd/Programs/keepassxc/KeePassXC.AppImage",  <unfinished ...>
[pid 29741] openat(AT_FDCWD, "/hdd/Programs/keepassxc/KeePassXC.AppImage", O_RDONLY) = 3
[pid 29740] access("/hdd/Programs/keepassxc/KeePassXC.AppImage.home", W_OK <unfinished ...>
[pid 29740] access("/hdd/Programs/keepassxc/KeePassXC.AppImage.config", W_OK <unfinished ...>
[pid 29740] <... getcwd resumed>"/hdd/Programs/keepassxc", 1024) = 24
[pid 29740] execve("/tmp/.mount_KeePas7pr1AA/AppRun", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0xbae7c0 /* 58 vars */ <unfinished ...>
[pid 29740] <... getcwd resumed>"/hdd/Programs/keepassxc", 4096) = 24
[pid 29740] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc",  <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc",  <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=2129936, ...}, 0) = 0
[pid 29740] access("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", X_OK) = 0
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=2129936, ...}, 0) = 0
[pid 29740] access("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", R_OK) = 0
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=2129936, ...}, 0) = 0
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=2129936, ...}, 0) = 0
[pid 29740] access("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", X_OK <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 29740] access("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", R_OK <unfinished ...>
[pid 29740] execve("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", ["keepassxc-proxy", "chrome-extension://oboonakemofpa"...], 0x55fb32f9cde0 /* 58 vars */ <unfinished ...>
[pid 29740] connect(6, {sa_family=AF_UNIX, sun_path="/run/user/1000/org.keepassxc.KeePassXC.BrowserServer"}, 110) = 0

**Comment by varjolintu** [comment]
These lines show the significant differences:
Chrome
```
[pid 29740] execve("/tmp/.mount_KeePas7pr1AA/AppRun", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0xbae7c0 / 58 vars / <unfinished ...>
[pid 29740] <... getcwd resumed>"/hdd/Programs/keepassxc", 4096) = 24
[pid 29740] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc", <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc", <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", <unfinished ...>
[pid 29740] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", {st_mode=S_IFREG|0755, st_size=2129936, ...}, 0) = 0
[pid 29740] access("/tmp/.mount_KeePas7pr1AA/usr/bin/keepassxc-proxy", X_OK) = 0
```

Brave:
```
[pid 25117] execve("/tmp/.mount_KeePas0v6hMJ/AppRun", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x14739b0 / 55 vars / <unfinished ...>
[pid 25117] <... getcwd resumed>"/hdd/Programs/keepassxc", 4096) = 24
[pid 25117] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc", <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/hdd/Programs/keepassxc", <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", X_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", R_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", X_OK <unfinished ...>
[pid 25117] newfstatat(AT_FDCWD, "/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", <unfinished ...>
[pid 25117] access("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", R_OK <unfinished ...>
[pid 25117] execve("/tmp/.mount_KeePas0v6hMJ/usr/bin/keepassxc", ["keepassxc", "chrome-extension://oboonakemofpa"...], 0x55592899cab0 / 56 vars */ <unfinish
....
```
Looking at these it seems Brave is trying to start KeePassXC itself and not the proxy?
Can you check the contents of the JSON scripts in `/home/userone/.config/google-chrome/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` and `/home/userone/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json"` to confirm they are using an identical paths?

**Comment by ConvarDeutschland** [comment]
@varjolintu 

both the same, I did already overwrite the brave one with the google one yesterday to make sure there is no difference

brave:
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/hdd/Programs/keepassxc/KeePassXC.AppImage",
    "type": "stdio"
}

Chrome:
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/hdd/Programs/keepassxc/KeePassXC.AppImage",
    "type": "stdio"
}

**Comment by varjolintu** [comment]
@ConvarDeutschland 
I'd like to see the differences in these arrays:
Brave: `[pid 25117] execve("/hdd/Programs/keepassxc/KeePassXC.AppImage", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x2526004c88c0 /* 51 vars /) = 0`
Chrome: `[pid 29740] execve("/hdd/Programs/keepassxc/KeePassXC.AppImage", ["/hdd/Programs/keepassxc/KeePassX"..., "chrome-extension://oboonakemofpa"...], 0x3140073ce00 /* 54 vars /) = 0`

Brave here is giving different amount of arguments to the  `execve`. So it's definitely doing something different here.

**Comment by ConvarDeutschland** [comment]
@varjolintu 

In some old post I find the brave may block keepass by addblocker and disable it should solve it, but that also did not solved it
also adding @@localhost ans @@127.0.0.1 to the addblock urls did not help

**Comment by varjolintu** [comment]
@ConvarDeutschland I don't know the details but maybe it's trying to restrict launching of the `keepassxc-proxy` binary because it differs from the main `keepassxc` one? You could try to install KeePassXC without using the AppImage and test if that solves it.

**Comment by ConvarDeutschland** [comment]
@varjolintu 

Version 2.6.6-1 from community does connect without problem.
/home/userone/.config/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json is pointing to keepass-proxy in this case.

I hope last version will be available soon on community

Thanks for all the help

**Comment by borkborkNFork** [comment]
I seem to have resolved this problem. While I have tried this before, it seems to have worked today.

KeepassXC-browser extension > Settings > Connected Databases > Connect

KeepassXC receives a prompt to name the connection and confirm, and then behaves as expected. 🎉 

It could be an interaction with Malwarebytes (version 4.5.7)'s "Web Protection". I'll try turning that back on and see if it's the culprit after a reboot.

**Comment by varjolintu** [comment]
@borkborkNFork If Malwarebytes is the reason, please close the issue.

**Comment by borkborkNFork** [comment]
@varjolintu turning on the Web Protection feature of Malwarebytes does not appear to be the cause of the problem. I am currently unable to replicate the bug, and my setup is working correctly now.

Feel free to close this issue unless you would like me to investigate something specific.

**Comment by varjolintu** [comment]
@borkborkNFork Thanks. Let's reopen this if something new appears.

**Comment by Shrikrishnan** [comment]
I am Facing this issue
