### ISSUE TITLE
KeePassXC not working in firejailed Browsers.

### ISSUE THREAD

**Issue by GoldenGlimpse** [keepassxreboot/keepassxc-browser#1594]
## Issue

Just did a clean Linux Mint install, rebuilding my system, but KeePassXC doesn't work after `firejail brave-browser` or `firejail firefox`.

When running `brave-browser` or just `firefox`, without Firejail, the extension works.

The extension asked me to create a new Identifier Key, which i did, but still doesn't work.
I've searched github for solution but couldn't find any.

## Current Behavior

KeePassXC can't connect to database when browser (Brave, Firefox) is firejailed. 
```
Error: "Message encryption failed. Is KeePassXC running?" 

and after clicking Reload button:
"Key exchange was not successful."
```

## Steps to Reproduce (for bugs)

1.  Install Brave
```
sudo apt install apt-transport-https curl

sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg

echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list

sudo apt update

sudo apt install brave-browser
```
2. Install KeePassXC from Package Manager.
3. Install KeePassXC browser extension from chrome store. (and enable browser integration in KeePassXC)
4. Install Firejail.
```
sudo apt-get install git build-essential libapparmor-dev pkg-config
git clone https://github.com/netblue30/firejail.git
cd firejail
./configure && make && sudo make install-strip
```
5. In Browser, Click "Reload" to connect to KeePass Database.

## Debug info

KeePassXC - {2.7.0}
KeePassXC-Browser - {1.7.11}
Operating system: Linux Mint 20.3 Una, Cinnamon 5.2.7
Browser: Brave-Browser, Version 1.37.111 Chromium: 100.0.4896.79 (Official Build) (64-bit)
Firejail Version - {0.9.69}

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc-browser/issues/267.
