### ISSUE TITLE
Standard Notes - login dialog goes away after clicking KeePassXC icon

### ISSUE THREAD

**Issue by logicalwillow** [keepassxreboot/keepassxc-browser#1597]
Standard Notes' login dialog disappears when clicking outside of it, and when clicking on icons or list items from the browser extension the dialog goes away, which is really annoying.

## Expected Behavior
The login dialog on Standard Notes should stay there so I can log into the site.

## Current Behavior
The login dialog disappears when clicking on anything from KeePassXC

## Steps to Reproduce (for bugs)
1. Go to app.standardnotes.com (maybe this happens on other websites?)
2. Click on the account icon at the bottom left and click "Sign in"
3. Click on the KeePassXC icon or the autofill list

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 99.0

**Comment by droidmonkey** [comment]
Should file this bug with them due to their terrible user interface. You could try using Auto-Type to overcome this.

**Comment by logicalwillow** [comment]
Okay, thanks!
