### ISSUE TITLE
Cannot connect from snap-based Firefox

### ISSUE THREAD

**Issue by kwill** [keepassxreboot/keepassxc-browser#160]
## Expected Behavior

* Install KeePassXC 2.3.1 via system (`apt install`)
* Open system browser (PureBrowser 52.8.0 on PureOS ~= Firefox ESR 52.8.0 on Debian)
* Install [KeePassXC-Browser](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/) from AMO
* Connect to KeePassXC
* Open snap-based Firefox (60.0 from Snap store, installed with `sudo snap install firefox`)
* Install KeePassXC-Browser from AMO
* Connect to KeePassXC

## Current Behavior

* Connecting to KeePassXC from system browser works as expected
* In snap-based Firefox the following error message appears: "KeePassXC-Browser has encountered an error: Timeout or not connected to KeePassXC"

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.1.3
Operating system: PureOS (~= Debian GNU/Linux main testing)
Browser: PureBrowser (based on Firefox 52) / Firefox 60
Proxy used: YES?

**Comment by varjolintu** [comment]
Have you tried to upgrade to KeePassXC 2.3.3?

**Comment by droidmonkey** [comment]
This likely has nothing to do with us. Native messaging is near impossible with snaps at this time.

**Comment by kwill** [comment]
Hmmm, I wonder if this would be solved by installing the Firefox snap with the `--classic` parameter. If I get time I'll try it out and leave a comment, and/or log a query with the snap project. Thanks for the feedback.

**Comment by droidmonkey** [comment]
That totally defeats the purpose of running Firefox as a snap. It also doesn't change anything in terms of file system isolation. All classic means is that ALL plugs are turned on by default.
