### ISSUE TITLE
Dicord login dont work

### ISSUE THREAD

**Issue by vampyren** [keepassxreboot/keepassxc-browser#1600]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to https://discord.com/login
2. Try using Keepass web plugin
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
username + pass filled in

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Nothing happens when i click the keepasxc icon

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.1
Revision: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 x64

![Screenshot 2022-04-10 112448](https://user-images.githubusercontent.com/4087127/162611635-d85989b5-9840-4296-b58b-a50f9e52f621.png)

**Comment by varjolintu** [comment]
Set your entry URL to: `﻿https://discord.com`.

**Comment by vampyren** [comment]
> Set your entry URL to: `﻿https://discord.com`.

eh sorry my bad, i see i had the old url for the site. Can close this.
