### ISSUE TITLE
[Critical] KeePass extension spawns multiple console window processes causing climbing memory leak.

### ISSUE THREAD

**Issue by MrTeeXD** [keepassxreboot/keepassxc-browser#1608]
When the main KeePassXC Window is closed, the Browser Extension keeps trying to detect the application but continues to spawn multiple Console Windows causing increasing memory leak.

## Expected Behavior
The RAM Usage should not continue to climb when the main application is closed.

## Current Behavior
Increasing Memory/RAM Usage by spawning multiple Console Windows processes.

## Possible Solution
None of what I can think of.

## Steps to Reproduce (for bugs)
1. Close the main KeePassXC application
2. Open the task manager and observe the RAM Usage
3. Within 10 minutes, the RAM Usage has raised to 2GB. Within 15 minutes, the RAM Usage climbed to 5GB

## Debug info
KeePassXC - 2.7.0
KeePassXC-Browser - 1.7.12
Operating system: Win64
Browser: Chrome/Chromium 100.0.4896.60

Screenshot of issue:
![Taskmgr_Ni9GmpmL1L](https://user-images.githubusercontent.com/37266538/163741119-05fbe8ec-bb80-45b4-9c31-0dbe2b1c1160.png)

**Comment by droidmonkey** [comment]
Turn off automatic connect in the extension settings

**Comment by varjolintu** [comment]
@droidmonkey Sure. Let's take it away until problems with it are solved.
