### ISSUE TITLE
imports from 1password fail to match due to `www.` presence

### ISSUE THREAD

**Issue by psifertex** [keepassxreboot/keepassxc-browser#1610]
## Expected Behavior
I'm a new user who imported his data from 1password into keepasscx. I've noticed that the browser extension fails to match a number of otherwise common websites and whenever I investigate it's due to 1password saving the matched URL of `www.$site` but the current site is redirected to `$site`.

## Current Behavior
Many of my imported passwords fail to match unless I manually adjust the URL to remove the `www.` field.

## Possible Solution
Allow an optional setting that would attempt to automatically match both with and without `www.` which in particular helps with users migrating with large databases from 1p where manually updating each entry would be extremely tedious and time-consuming. 

## Steps to Reproduce (for bugs)
1. Import a PW database from 1p (Or save a password on a `www.` form of a website)
2. Try to use the plugin on the website when not using `www.` in the URL

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment]
While this feature has been suggested before, it has one big problem: there are those people who want possibly to keep `www` and other subdomains separate from the main domain. So we definitely need an extra option for it, but it's going to be on KeePassXC's side.

**Comment by psifertex** [comment]
Sure, making it optional was in my suggestion above. Why does an option have to exist in the core versus the browser extension? Being able to search both forms of the url seems straight-forward?

**Comment by varjolintu** [comment]
Mostly because all URL matching and parsing is done on KeePassXC's side, including scheme matching option. The extension just passes the raw URL to the application.

..BUT in this case I have to agree with you I gave it a thought. Omitting `www` from the request would be better to be included to the extension side because otherwise older KeePassXC versions couldn't support it. The scheme matching option has been there since the old KeePassHTTP implementation so there's no worries with that. But actually that option should be also transferred to the extension side.

**Comment by psifertex** [comment]
Thanks for considering it. 

It looks like maybe another option for me is to programmatically strip all URLs from my 1p database before I import it. If I export into one of the plain text formats I can give that a go, I do have the "only save domain" in my browser options which presumably this would match the behavior of.

**Comment by varjolintu** [comment]
I'm going to do this for the next release (1.8.0) which is going to be a bigger one anyway.

**Comment by psifertex** [comment]
Much appreciated!

**Comment by droidmonkey** [comment]
I think we have an open request to treat www subdomain the same as having no subdomain, or at least an option to do so.

**Comment by varjolintu** [comment]
@droidmonkey We do, but I couldn't find it.

**Comment by psifertex** [comment]
Looks like you did, but it was closed: https://github.com/keepassxreboot/keepassxc-browser/issues/1566

At the time your suggestion was "just make it that way in the first place" which doesn't really help when I'm importing over 3k passwords from 1p...

**Comment by droidmonkey** [comment]
That's but one of a thousand suggestions made by me 😇 I'm sure I contradicted that in several other posts including those one.

**Comment by varjolintu** [comment]
I'll back up a little: the change must be made to KeePassXC side because in this case the URL sent from extension doesn't have the `www` subdomain, but the entry in database does. I'm not comfortable with adding the subdomain to the request URL "just in case" if it happens to match with the entry, which is the only way to trigger a match from extension side.

**Comment by psifertex** [comment]
Thanks, I understand a bit better now. 

It actually looks like what I'm being impacted by is documented in keepassxreboot/keepassxc#6519 and the solution there would solve my problem. I've essentially got a massive database of passwords from another tool where domain matching is the primary matching technique and it's really unusable with keepass right now unless I go through and script the creation of "additional" URLs that are basically just the second level domain -- except I've also gotta double check for country codes and what not so it's a bit of a headache. The ability to have a primary setting of "ignore subdomains" on keepascx itself would not only match other tools but would mean I don't have to spend the time time setting up such a janky hack.

Anyway, I'm all in favor of closing this in favor of the above since I believe it captures the problem I'm having. Unless there's something captured here distinct from that that I'm missing.

**Comment by droidmonkey** [comment]
@varjolintu maybe we can make this a database or group level setting so people don't have to compromise between application level options for the sake of one database.

**Comment by varjolintu** [comment]
@droidmonkey I agree. That's even better.

**Comment by varjolintu** [comment]
See: https://github.com/keepassxreboot/keepassxc/pull/7988

**Comment by varjolintu** [comment]
Fixed in KeePassXC 2.7.2.
