### ISSUE TITLE
Blizzard website bugging out

### ISSUE THREAD

**Issue by Franz321** [keepassxreboot/keepassxc-browser#1613]
## Expected Behavior

It should just put my email and password in and wait. 

## Current Behavior

After I submit my email and pass I get to the authenticator page and then get thrown back for no reson

## Possible Solution

idk

## Steps to Reproduce (for bugs)

1.Just sign in

## Debug info

16Failed to decode downloaded font: <URL>
us.battle.net/:215 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:215 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Regular.2aXeg.woff2
us.battle.net/:1 Failed to decode downloaded font: https://bnetaccount.akamaized.net/login/static/css/toolkit/fonts/noto-sans/NotoSans-Bold.4ej6Y.woff2
16OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:215 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:215 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
us.battle.net/:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
VM100:18 [FastForward] Couldn't define ysmm
ODP @ VM100:18
VM100:18 [FastForward] Couldn't define initLbjs
ODP @ VM100:18
VM100:18 [FastForward] Couldn't define safelink
ODP @ VM100:18
VM100:18 [FastForward] Couldn't define soralink
ODP @ VM100:18
VM100:18 [FastForward] Couldn't define adtival_base64_encode
ODP @ VM100:18
blizzard-regular.3GHNU.woff:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Bold.4MlbQ.woff2:1          Failed to load resource: the server responded with a status of 404 ()
NotoSans-Regular.2aXeg.woff2:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Medium.3S5XI.woff2:1          Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.2v4iV.woff2:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Regular.4Bfgc.woff2:1          Failed to load resource: the server responded with a status of 404 ()
NotoSans-Bold.4ej6Y.woff2:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Bold.2z4wD.woff:1          Failed to load resource: the server responded with a status of 404 ()
NotoSans-Regular.0RsFi.woff:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Medium.49FEW.woff:1          Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.2ZgOB.woff:1          Failed to load resource: the server responded with a status of 404 ()
ObjectSans-Regular.2Vxjx.woff:1          Failed to load resource: the server responded with a status of 404 ()
NotoSans-Bold.1nSFW.woff:1          Failed to load resource: the server responded with a status of 404 ()
fa-solid-900.ttf:1          Failed to load resource: the server responded with a status of 404 ()
DevTools failed to load source map: Could not load content for chrome-extension://hnmpcagpplmpfojmgmnngilcnanddlhb/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

KeePassXC - {2.7.1}
KeePassXC-Browser - {1.7.12}
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
Are you sure this is not because of Windscribe browser extension you are using? None of those errors is related to KeePassXC-Browser.

**Comment by Franz321** [comment]
I remived the extension and it still is the same, aguess the errors are not the reason.Am 20.04.22, 05:44 schrieb "Sami Vänttinen" ***@***.***>:

   
  Are you sure this is not because of Windscribe browser extension you are using? None of those errors is related to KeePassXC-Browser.

**Comment by droidmonkey** [comment]
Make sure you don't have any ad blockers or whatever interfering with the site.

**Comment by Xanax-C-137** [comment]
It's probably FastForward
