### ISSUE TITLE
Unable to auto-fill credentials through Apple ID sign in URL

### ISSUE THREAD

**Issue by andrearollon06** [keepassxreboot/keepassxc-browser#1615]
KeepassXC can't auto-fill my password in this URL https://appleid.apple.com/
As per clicking the "Sign In" link, it redirects in the given url. Kinda hassle I still have to save my passwords in Google Account instead of using keepass

## Expected Behavior
Should auto-fill or ask suggestions from KeepassXC database

## Current Behavior
Not auto-filling or asking suggestions from KeepassXC database

## Possible Solution
If possible, do the same thing that's done in Google Account (works fine in google sign in).

## Steps to Reproduce (for bugs)
1. Add apple id creds in KeepassXC database in desktop. Add url as https://appleid.apple.com/
2. Go to https://appleid.apple.com/
3. Check if it auto-fills or ask suggestion from KeepassXC database

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Windows
Browser: Chrome

**Comment by varjolintu** [comment]
Use `https://idmsa.apple.com` or `https://apple.com` as you entry URL.
