### ISSUE TITLE
feature request: respect autocomplete="new-password"

### ISSUE THREAD

**Issue by derflocki** [keepassxreboot/keepassxc-browser#1617]
According to MDN autocomplete="new-password" can be used to [prevent "browsers" from autofilling](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#preventing_autofilling_with_autocompletenew-password)

It would be great if keepassxc would also respect this.

KeePassXC - 2.7.1
KeePassXC-Browser - 1.17.12
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Seems we already support this.

**Comment by amcsi** [comment]
It doesn't seem to be working, though.

![image](https://user-images.githubusercontent.com/116494/174597933-d97f47fe-f1ad-431c-9413-801b47e6696e.png)
