### ISSUE TITLE
Can't Choose Login Fields for Charles Schwab Site

### ISSUE THREAD

**Issue by ourichermath** [keepassxreboot/keepassxc-browser#1618]
## Overview
On the Charles Schwab web site (https://www.schwab.com/), I cannot get KPXC to let me select username/password fields (let alone fill them in).  In my KPXC database for Schwab, I have exactly the above URL listed.  On the web page, clicking on the username field (with the KPXC icon in it) does nothing.  Clicking on Redetect Login Fields does nothing.  When I try to Choose Custom Login Fields, it puts a highlighted "1" in the top Search field and a dimmed "1" and "2" in the actual username/password fields, below.  But, clicking on the correct field does nothing and typing any numbers does nothing.  The only thing I've managed to get working is setting up an Auto-Type entry with https://www.schwab.com* as the Window Title and {USERNAME}{TAB}{PASSWORD}{ENTER} for the sequence.  Then, I can do a global autotype to get it to fill in the fields.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Go to https://www.schwab.com
2. Click the KPXC Browser extension field in the browser and tell it to Choose Custom Login Fields
3. Try either clicking on the correct fields or typing their numbers (though 1 is duplicated).

## Expected Behavior
The KPXC Browser extension should let me select the username/password fields and, later, allow me to click on the username field to fill them in.

## Actual Behavior
It doesn't work.  I cannot select fields at all.

## Context
Brave Browser V1.38.109

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: Fedora Linux 35 (Workstation Edition)
CPU architecture: x86_64
Kernel: linux 5.17.4-200.fc35.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.18.2

Operating System: Fedora Linux 35
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.91.0
Qt Version: 5.15.2
Kernel Version: 5.17.4-200.fc35.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 15.6 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT

**Comment by varjolintu** [comment]
Use `https://lms.schwab.com/` or `https://schwab.com/` as you entry URL. The login iframe has a different subdomain.
