### ISSUE TITLE
Not Working on Uptobox

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc-browser#1619]
## Expected Behavior

Uptobox login properly registered in my KeePassXC.

KeePassXC-Browser works well for me on other login pages, such as Amazon, etc.

## Current Behavior

I can see the green icon on the login name field, described as letter `C` in your doc page. Unfortunately, although credentials registered in KeePassXC, green icon does not respond when clicking on it.

Even using the “Choose custon login fields” option in KeePass-XC toolbar icon does not work. I select the login and password field, but afterwards, still not detected.

## Steps to Reproduce (for bugs)

1. Registere credentials in KeePass-XC
2. Visit Uptobox/login
3. Registered data in KeePass-XC not detected.
4.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.11
Operating system: MacOS
Browser: Firefox

Thanks for your help

**Comment by varjolintu** [comment]
This URL? https://uptobox.com/login?referer=register
I had no problems with identifying credentials with that page.

**Comment by faxotherapy** [comment]
In fact, I use [https://uptobox.com/login](https://uptobox.com/login)

**Comment by varjolintu** [comment]
Is that also your entry's URL?

**Comment by faxotherapy** [comment]
yes

**Comment by varjolintu** [comment]
Have you accidentally denied access to that site in your entry? Check you entry's Properties tab when you edit it.

**Comment by faxotherapy** [comment]
I'm currently looking to isolate the problem. I suspect it might be related to Firefox Containers. I've assigned this Uptobox site to a specific container.

**Comment by faxotherapy** [comment]
Retried with containers, now it works. Apparently, restarting KeePass-XC app and re-opening the site worked. Sorry for the false alarm and wasting your time.
