### ISSUE TITLE
Cloudflare 2FA needs 3x fill

### ISSUE THREAD

**Issue by Nuklon** [keepassxreboot/keepassxc-browser#1622]
## Expected Behavior
If you open dash.cloudflare.com with 2FA enabled, right click > KeePassXC-Browser > Fill TOTP should fill it in.

## Current Behavior
Right now you need to click Fill TOTP three times before the TOTP token is filled.

## Possible Solution
N/A.

## Steps to Reproduce (for bugs)

1. Open dash.cloudflare.com
2. Try to enter TOTP.
3. See it doesn't get filled.
4. goto 2. two more times.

## Debug info

KeePassXC - 2.7.1.
KeePassXC-Browser - Latest from Firefox store.
Operating system: Win.
Browser: Firefox 100.

**Comment by varjolintu** [comment]
Does the toolbar icon show a question mark? If so, does selecting credentials there and filling after that work?

**Comment by Nuklon** [comment]
> Does the toolbar icon show a question mark? If so, does selecting credentials there and filling after that work?

If you mean the 2FA/OTP field icons? That works in one go, but I have disabled that as that gets added on some other sites that are not using OTA icons.

**Comment by Nuklon** [comment]
There's no question mark there, no.

**Comment by varjolintu** [comment]
Does the JavaScript Console (inspect the page to see that / Web Developer Tools) show any error messages after the first fills that fail?

**Comment by Nuklon** [comment]
Nothing.

**Comment by fernvenue** [comment]
I just found out that Cloudflare 2FA back to normal now.
