### ISSUE TITLE
KeePassXC Browser (Firefox 100) isn't working well

### ISSUE THREAD

**Issue by andbenn** [keepassxreboot/keepassxc-browser#1623]
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Linux x86_64
Browser: Mozilla Firefox 91.0

Since updating to Firefox 100 a few days ago, I've noticed that my keyboard shortcuts and form filling that previously worked doesn't work anymore.

I'm totally broken with KeePassXC browser.  I'm copy/pasting in fields at this time.

Visit a previously working site
In Username field, use keyboard shortcut for username.  Nothing happens.
Click the green KeePass icon at the right of the field to fill it - nothing.

On the same computer, switch to Brave with KeePassXC browser.  Form fill works when activated by mouse.  Keyboard shortcuts work.

Theory: Firefox 100 changed some APIs or broke some APIs.

## Current Behavior

Nothing happens.

## Possible Solution

Manual copy user, copy pass, copy TOTP when needed in a multi-step act between apps and windows on my desktop.

## Steps to Reproduce (for bugs)

1. Go to page that has a login that previously worked well with KeePassXC
2. Alt-Shit-U (Username keyboard shortcut.  Nothing.
3. Click the green KeePass logo in the right of the field.  Nothing.
5.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Linux x86_64 (Arch and up to date)
Browser: Firefox 91.0 (100.0 64-bit)

**Comment by varjolintu** [comment]
Try creating a new temporary profile in Firefox and test if that fixes it. Maybe the current profile has been corrupted because of the upgrade. Before that you could try to remove and reinstall the extension.

**Comment by andbenn** [comment]
@varjolintu you had excellent advice and a good guess.  After creating a new Firefox profile, several sites with logins now work that don't work in my original profile.

I'll resolve this and figure out how to migrate my settings after going through some steps to maybe uninstall keepassxc-browser and bring it back.  Thanks.
