### ISSUE TITLE
Browser Integration on Linux Ubuntu with Firefox not possible

### ISSUE THREAD

**Issue by simonklamt** [keepassxreboot/keepassxc-browser#1625]
Hey everyone, 

I am just trying to install the browser integration for firefox of keepass xc on linux ubuntu 22.04. But I can't actually connect the desktop software with the browser integration, because it always says "Key exchange was not possible". I already enabled the brwoser integration in the settings. 

Does anyone is aware of this problem? Is it probably a bug? 

Thanks very much in advance! 

Best, 

Simon

**Comment by varjolintu** [comment]
Uninstall the Snap version of Firefox and use a normal package instead. See https://github.com/keepassxreboot/keepassxc-browser/issues/1426.
