### ISSUE TITLE
Facebook requests access for an entry that doesn't exist

### ISSUE THREAD

**Issue by emj04** [keepassxreboot/keepassxc-browser#1627]
When I go to [facebook.com](https://www.facebook.com/) I get an access request for an email that is not in my KeepassXC database and that I've never seen before. I have not had this happen on any other site. I'm not positive about the timing, but this may have started to happen after updating to Firefox 100.

![Screenshot from 2022-05-16 17-16-36](https://user-images.githubusercontent.com/44931622/168628339-9cfb59ea-e4fb-467d-8a03-6cb0c6a8a629.png)

KeePassXC-Browser Version: 1.7.12
KeePassXC Version: 2.7.1 
Operating system: Fedora 35
Browser: Firefox 100

**Comment by droidmonkey** [comment]
So when you search your database for that email nothing comes up?

**Comment by varjolintu** [comment]
Even the entry title says it's for Facebook so it's not even an entry for a different site. Do you have multiple databases open?

**Comment by emj04** [comment]
@droidmonkey Correct, nothing comes up when I search for that email.

@varjolintu I only have one database open.

**Comment by varjolintu** [comment]
What if you search for "Facebook" which is the entry title? You could also use the Browser Statistics from Database Reports to see if it helps, and for some reason find doesn't show the entry.

**Comment by emj04** [comment]
Searching Browser Statistics found it! It was in a Group that I keep some family member's info in. Nothing in that Group will show up in search. Any idea what caused it to suddenly make a request?

**Comment by droidmonkey** [comment]
Just disable that group or specific entry from being sent to the browser extension if you don't want it to be sent over. No reason for it "working" all of a sudden, hard to tell.
