### ISSUE TITLE
I want to share my website's passwords with several applications, So how I can change default password group-name to retrieve password?

### ISSUE THREAD

**Issue by hamedsbt** [keepassxreboot/keepassxc-browser#1633]
I set "Default group for saving new passwords:" to **Public** as my prefer group name

## Expected Behavior
save and retrieve password from the  **Public** group name.

## Current Behavior
It save to **Public** group, but it can't retrieve save password from it.

## Possible Solution
use user provided group name ("Default group for saving new passwords:") to save and load passwords.

## Debug info
KeePassXC - v2.7.1
KeePassXC-Browser - v1.7.12
Operating system: Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
What are you trying to do? It is unclear from your title and body text what the problem is.

**Comment by hamedsbt** [comment]
I set "Default group for saving new passwords:" to **Public** 
It save password to **Public** group properly, but it can't retrieve saved passwords from it.

KeePassXC - v2.7.1
KeePassXC-Browser - v1.7.12
Operating system: Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Edit your group and check the access settings from Browser Integration page/tab.

**Comment by hamedsbt** [comment]
My configs: 

![image](https://user-images.githubusercontent.com/7298328/170853982-1eec7a3e-02ca-403d-abeb-9f61977c4e9f.png)

![image](https://user-images.githubusercontent.com/7298328/170853999-e09edd19-d6d5-4641-858e-7327e76e6cfb.png)

Are correct?!

**Comment by varjolintu** [comment]
Edit the Public group. These are not the settings you are looking for.
