### ISSUE TITLE
Firefox plugin: username-only detection not working on some sites

### ISSUE THREAD

**Issue by netgrims** [keepassxreboot/keepassxc-browser#1640]
Not sure if this is the correct way to flag this issue. I couldn't find a previous mention of it anyway.

This is about the Firefox browser plugin. When I try to fill credentials on sites where the username and password are entered separately, I sometimes run into problems. 

One example of this is eBay. When I try to log in to eBay, Keepass won't fill in my credentials at all, not when I click on the icon in the username field, nor when I try the keyboard shortcut. I already set "username-only detection" to 'true' in the site preferences of the Firefox plugin, but this doesn't help. 

I've also tried to set custom login fields, but this doesn't work either. The problem with the custom login fields is also that it only works on sites where the username and password are entered at the same time on a single page.

Maybe there should be a shortcut or button to enter username only?

Firefox's built-in password manager doesn't have any trouble with this.

I'm using Firefox 99.0.1, KeepassXC-Browser 1.7.12, and KeePassXC 2.7.1 Flatpak version on Fedora Linux 35 (Workstation).

**Comment by varjolintu** [comment]
"Fill Username and Password" should also fill just the username for single username fields.

Selecting Custom Login Fields for situations where username and password fields are shown on a single page but not at the same time is already fixed with the upcoming release.

**Comment by netgrims** [comment]
Well, on some sites with single username fields that does work, but on others (like eBay) it doesn't seem to work. I don't know if the problem is with the custom login fields, since it doesn't work when I set a custom username field for the first page either.

**Comment by droidmonkey** [comment]
You could have a conflicting extension in your browser that is preventing ours from working on certain sites.

**Comment by varjolintu** [comment]
What eBay site are you using?

**Comment by netgrims** [comment]
I normally use benl.ebay.be, but tried it on ebay.co.uk and ebay.com as well. It doesn't work on any of them. Although, on .co.uk and .com, it does show the keepass icon in the username field (not on .be), but when I click it, nothing happens. Same for the keyboard shortcut (alt+shift+u). Clicking the extension icon in the menu bar doesn't show any options apart from 'redetect login fields', and clicking that doesn't do anything either.

**Comment by netgrims** [comment]
Okay, I seem to have got it to work. I added all the subdomains of signin.ebay.com/ws/ (and .co.uk and .be) and then had to enable the option for username only field. I guess the problem comes from importing the database from the Firefox password manager, which doesn't need to refer to the exact subdomains. 

Thanks for the help!

**Comment by varjolintu** [comment]
I must see if that eBay site is not in our Predefined Sites list. Gonna add it to that if not.
