### ISSUE TITLE
Addon silently disconnected from KeePassXC

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc-browser#1641]
## Current Behavior

Sometimes I have an invalid status of Keepassxc and the Keepassxc Firefox addon, like now: The addon says it's connected, the database is unlocked. But I can't get a password autofilled. If I enter the password manually, it asks to add or update a new password, which after I press "New", fails.
Looking at the addon settings, connected databases, I see the Identifier for my addon. But with "Last used" yesterday.

What can I do to debug that further?

## Possible Solution

Only solution is to restart Firefox.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.1-r1
KeePassXC-Browser - 1.7.12
Operating system: Linux
Browser: Firefox-91.9.1

**Comment by Massimo-B** [comment]
The bug is there again, just because I restarted Keepass in the background.
Web Developer Console has only 2 errors:

Content Security Policy, pages settings blocked the loading of ...https://googleads..., conversion_async.js
Error: Promised response from onMessage listener went out of scope, background.js

Nothing Keepass related.

**Comment by varjolintu** [comment]
We don't have an automatic reconnect available at the moment. If you restart KeePassXC in the background, the extension must be connected again manually using the extension popup (from the toolbar icon) and click Reload.

**Comment by varjolintu** [comment]
Restarting the add-on is done the way I described it in my previous message. Use the extension popup.

**Comment by Massimo-B** [comment]
Ok, then the reload does not work.

**Comment by varjolintu** [comment]
Reload should do the same thing as restarting the browser. Go to `about:debugging#/runtime/this-firefox` and inspect the extension. That should give you access to the background script's log. See if there's any errors after KeePassXC restart.

**Comment by Massimo-B** [comment]
I did the reload. After that the only button there is "Redetect login fields". This results in debug errors: 

```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    sendMessageToTab moz-extension://c36f8edc-9368-43d7-bdcb-474f29f42b3c/popups/popup.js:46
[popup.js:46:24](moz-extension://c36f8edc-9368-43d7-bdcb-474f29f42b3c/popups/popup.js)
```
