### ISSUE TITLE
Synology DSM 6.2 login form: username is not auto-filled

### ISSUE THREAD

**Issue by pandruszkow** [keepassxreboot/keepassxc-browser#1645]
## Expected Behavior
When trying to log into Synology DSM, KeePassXC-Browser auto-fills the entire login form based on a matching password entry

## Current Behavior
The form is autofilled only partially - password is autofilled, but the username field remains blank, like in the image below

![image](https://user-images.githubusercontent.com/47523691/173578683-99f9e986-1392-4781-a711-af211d646d76.png)

## Possible Solution
My guess is that the login form has a piece of JavaScript that erases the contents of the username field, and that field only. The password field seems to contain the right password from the auto-fill - when I re-enter the correct username without erasing the password field, the login is successful.

## Steps to Reproduce (for bugs)

1. Navigate to the public Synology DSM 6.2 demo site (https://demo.synology.com/en-uk/dsm)
2. Log out of the demo
3. When the login form is shown, enter any username+password and choose the option to save those as a new entry in KeePassXC
4. Refresh the login form while logged out. Observe that only the password field is autofilled, while the username field contains nothing.

## Debug info

KeePassXC Version: 2.7.1
KeePassXC-Browser Version: 1.7.12
Operating system: Ubuntu 20.04 (amd64)
Browser: Firefox 100.0.2 (64-bit) from default system repos

**Comment by varjolintu** [comment]
I could not reproduce this. Tried it even without any other extensions. The right URL for this is of course `﻿https://a170.dsm6demo.synologydemo.com:5001/` shown after login.

**Comment by varjolintu** [comment]
Let's reopen this if needed.
