### ISSUE TITLE
Feature request: search for similar entries or by Note/Label

### ISSUE THREAD

**Issue by mmarodin** [keepassxreboot/keepassxc-browser#1647]
## Feature request
New URL: I can't use the browser extension to search for similar entries or by Note/Label fields to use a saved credential, that has already been used for a similar URL, or simply the same username/password.

## Expected Behavior
It will be easier to search for similar credential with the browser extension, and then save it as new entry (if necessary).

## Current Behavior
I have to clone the entry manually from the desktop app, or I have to enter manually (the same) credentials and save them as new entry.

**Comment by droidmonkey** [comment]
This won't be implemented. The point of our browser extension is minimal access and integration necessary. You need to setup your entries with the proper urls for them to be found and offered.
