### ISSUE TITLE
Allow keyboard simulation

### ISSUE THREAD

**Issue by tusooa** [keepassxreboot/keepassxc-browser#1648]
## Expected Behavior

We should be able to fill in passwords by simulating keyboard presses (just like KeePassXC autotype).

## Current Behavior

No such simulation is done.

This is problematic for websites hostile to a password manager, for example, they might require the user to *type* before even submitting the forms.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Use KeePassXC's Auto-Type.

**Comment by tusooa** [comment]
> Use KeePassXC's Auto-Type.

It's not available on Wayland.

**Comment by varjolintu** [comment]
> > Use KeePassXC's Auto-Type.
> 
> It's not available on Wayland.

Then wait until it's available. Implementing a similar thing definitely won't solve problems with websites that dislike browser extensions. Auto-Type is a direct and easiest solution for that.

If the browser extension is a must, I'd suggest trying Custom Login Fields and other ways to solve the credential filling.
