### ISSUE TITLE
Unwanted Data-cip-id in CKEditor

### ISSUE THREAD

**Issue by JeroenED** [keepassxreboot/keepassxc-browser#165]
When the extension is running and CKEditor is editing a page with input fields in HTML-view, several attributes are added to input fields. Additionally, when loading a page that already has these attributes but KeepassXC is unable to find them in the database, the form fields are losing their type and name attributes.

## Expected Behavior
Fields should not be changed when CKEditor (or another WYSIWYG editor) is loaded.

## Current Behavior
* Additional attributes (data-cip-id) are added to input tags containing a unique identifier
* When loading a page containing saved data-cip-id attributes that were not saved in the database name and type attributes are removed.

## Possible Solution
* Exclude ckeditor classes from running the browser-addon

## Steps to Reproduce (for bugs)

1. Make keepassbrowser running
2. Open CKEditor page with input-fields in html-mode
3. (data-cip-id is added)
4. Save the page
5. Reopen page in CKeditor
6. (name and type attributes are gone)

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.3 
Operating system: Win
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
Maybe the correct approach for this is extending Ignored Sites feature. A checkbox could be added which prevents loading the content script(s) for a certain pages.

**Comment by JeroenED** [comment]
I do believe this could be a more feasable solution. But it would require support for wildcards. In my case the url is `https://test.jeroened.be/admin/pages/edit/2` where `2` is the ID of the page.

Is there a workaround possible for now that I can use? Maybe by using a additional add-on?

**Comment by varjolintu** [comment]
For now the only workaroung would be to modify the extension's `manifest.json` with `exclude_matches`. This of course means downloading the source code and loading extension manually.

An example:
```
"content_scripts": [
    {
      "exclude_matches": ["*://developer.mozilla.org/*"],
      "matches": ["*://*.mozilla.org/*"],
      "js": ["jquery.js", "borderify.js"]
    }
  ]
```

**Comment by varjolintu** [comment]
With https://github.com/keepassxreboot/keepassxc-browser/pull/176 you can add the site to a ignore list and with `Full ignore` option enabled no input fields are modified or handled at all.

**Comment by varjolintu** [comment]
Good news. I added wildcard support to the Ignored Sites PR. It follows the [match patterns](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Match_patterns).

**Comment by varjolintu** [comment]
@JeroenED So no even the wildcards won't work? I'm having a hard time to get the added input fields regognized.

**Comment by varjolintu** [comment]
The extension is already using `document.location.href` which is the URL. Reproduced it now. What's interesting is that Chromium doesn't seem to regognize those added input fields at all, so I assume you are also using Firefox?

**Comment by JeroenED** [comment]
Yes, indeed. Using firefox 63.0 on Linux Mint 19.0 x86_64 from official LM repository

**Comment by JeroenED** [comment]
@varjolintu Is it possible to re-open te issue? I just tested it again and the issue still persists :(
