### ISSUE TITLE
Auto fill in of credentials does not work if Keepassxc is minimized to tray.

### ISSUE THREAD

**Issue by thstyl2000** [keepassxreboot/keepassxc-browser#1650]
## Expected Behavior
Using browser integration without the need of having keepassxc open.

## Current Behavior
After clicking on the padlock icon and entering password, database remains locked and no passwords are filled. If Keepassxc is not minimized to tray, everything works fine.

Have already tried to reinstall extension without any success.

## Steps to Reproduce (for bugs)

1. Minimize Keepasscx to tray.
2. Click on padlock icon.
3. Enter password to database.
4. Keepassxc unlock window closes and credentials are not filled in.

## Debug info

JS console reports no errors.
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.12
Operating system: Ubuntu 22.04 
Browser: Firefox 101.0.1

**Comment by droidmonkey** [comment]
Do you have "lock database when minimized" enabled in the settings?

**Comment by thstyl2000** [comment]
Yes I do, but it used to work fine before the update to 2.7.1. (when I was on hirsute, don't remember the latest version on the repos...)

**Comment by droidmonkey** [comment]
#1090 captures this problem but for copying to clipboard. The fix is the same so closing.

**Comment by thstyl2000** [comment]
@droidmonkey I am probably wrong, but this pull was merged in the 1.7.3 version a couple of years ago, so isn't this a new bug...?

**Comment by droidmonkey** [comment]
Sorry I didnt realize I was on the browser repository, fixed the link.

**Comment by thstyl2000** [comment]
@droidmonkey ...but this issue has always been open, hasn't it? What I am describing was not happening with the keepassxc v2.6.2.....

**Comment by droidmonkey** [comment]
Can't explain why but it is not relevant, disable the setting and everything will work.

**Comment by thstyl2000** [comment]
Ok, tried the following:

1. Unchecked "lock database when minimized"
2. Lock database
3. Minimize Keepassxc to tray -> Database remains locked
4. Go to login page and click on padlock icon -> Keepass unlock window pops up
5. Enter database password -> Credentials are entered in website, database remains minimized and **unlocked.** 

That is not what was happening up to now. I guess I could tell keepassxc to lock the database after a few seconds of inactivity, but this is certainly only a workaround, I don't think that the extension is meant to behave like that (since it was anyway not doing that until previous versions!).

Yes, I can work around the problem and it is only mildly annoying, but it is certainly a bug (extension cannot unlock database when minimzed to tray), so it would be great if you reopen the issue.

Thank you for this great software and all the work!

**Comment by droidmonkey** [comment]
This isn't an extension bug.

**Comment by thstyl2000** [comment]
Since I am able to "just click" on the taskbar icon and bring keepassxc to desktop, I assumed that this is a bug of the extension. So should I refile this at the keepassxc tracker?

**Comment by droidmonkey** [comment]
The linked issue I posted above is the already open issue tracking this

**Comment by thstyl2000** [comment]
Sorry, I am really not an expert, but this doesn't make any sense to me: the issue you have posted above exists for a long time. What I am describing is new and was not an issue with the versions in the issue you linked.

**Comment by droidmonkey** [comment]
There is only one place in the code where the lock on minimize code exists. We change and improve window behavior quite frequently when interacting with the browser extension and things do change outside our program that modify window behavior. It is likely one of these changes results in the lock on minimize code being triggered. The fix for all this is to add a small delay between when the lock on minimize code is triggered and when the lock actually occurs.

**Comment by thstyl2000** [comment]
Alright, thank you!
