### ISSUE TITLE
Banner asking to save/update entry does not close anymore

### ISSUE THREAD

**Issue by shaoran** [keepassxreboot/keepassxc-browser#1656]
## Overview

Since the last update of the Browser extension, every time you log in on a site typing your user name and password, the banner that asks whether to save/update the entry appears, but when you click for example on the *Dismiss* button, nothing happens, the banner does not go away.

I opened the developer tools to see whether an JS exception is raised when you click on the button, but no error message is displayed.

It seems that the problem is that the banner itself cannot be closed. Just for testing purposes, I clicked on the *New* button of the banner and the entry was added on my password file, the green notification that a new entry was stored also appeared. However the banner remains in place. I have to press F5 to get rid of the banner.

## Expected Behavior

The banner should go away after clicking any button

## Current Behavior
The banner does not go away

## Steps to Reproduce (for bugs)
1. Go to  a page that requires login
2. Enter your user name & password
3. Click on any of the buttons (for example the *Dismiss* button)

## Debug info

KeePassXC - `2.7.1`  
KeePassXC-Browser - `1.8.0`  
Operating system: GNU/Linux  
Browser:
  - GNU/Linux on Google chrome Version 102.0.5005.115 (Official Build) (64-bit)
  - GNU/Linux on Firefox 91.10.0esr (64-bit)

**NOTE** the behaviour is present on both browsers that I tested.

**Comment by varjolintu** [comment]
What site gives you this error? I tried a few and could not reproduce it.

**Comment by shaoran** [comment]
@varjolintu so far every single site so far has had this behaviour.

**Comment by shaoran** [comment]
@varjolintu strange, I found one page (self hosted redmine) where this doesn't happen, the *Dismiss* button worked there. But most pages so far have had this behaviour on both browsers and that since they both updated to `1.8.0`.

**Comment by droidmonkey** [comment]
Most likely this is conflicting with another extension you have in the browser. Please list them if you don't mind.

**Comment by varjolintu** [comment]
Give me any site where this happens? It's strange because I cannot reproduce this at all. Does the same happen if you trigger Save Credentials manually from the context menu?

**Comment by okloecker** [comment]
Can't give a public site, but happens for me for a few days now. This is in console:
```
Uncaught (in promise) TypeError: Failed to execute 'removeChild' on 'Node': parameter 1 is not of type 'Node'.
    at kpxcBanner.destroy (banner.js:29:37)
```
And banner.js:29 is `window.parent.document.body.removeChild(window.parent.document.body.querySelector('#kpxc-banner'));`

KeePassXC-Browser Version: 1.8.0
KeePassXC Version: 2.7.1
Google Chrome Version 103.0.5060.53 (Official Build) (64-bit) on Linux

**Comment by varjolintu** [comment]
@okloecker Thanks. This helps.

**Comment by varjolintu** [comment]
Isolated the bug: this happens when extension detects a submit from both the form and the submit button. In this case two banners are created almost at the same time, and the second one thinks the first one does not exist yet. This causes the banner destroy to fail because we are trying to find the first element, but it's actually replaced with the element created from the second submit.
Gotta narrow this down and find a way to restrict creating multiple banners with this kind of situation, or we just don't do double-submits.
