### ISSUE TITLE
Extension is slowing down Firefox when RES infinite comment scroll activates

### ISSUE THREAD

**Issue by yllekz** [keepassxreboot/keepassxc-browser#1660]
## Expected Behavior
The KeepassXC-Browser Firefox extension is causing temporary browser performance degradation when scrolling through old.reddit.com with the RES extension. 

KeepassXC-Browser shouldn't be slowing down the browser just because one is scrolling through reddit comments

## Current Behavior

The extension is performing something strange in the background when using old.reddit.com with the RES extension. Firefox displays a banner prominently stating that the KeePassXC-Browser extension is causing a significant performance issue when scrolling down  comment threads to the point where more are loading in. I don't recall this issue happening before so I think it might have been the result of a recent update to the extension?

## Possible Solution

Examine what KeePassXC-Browser is doing to scan dynamically expanding content? Not entirely sure.

## Steps to Reproduce (for bugs)

0. Have KeepassXC-Browser and Reddit Enhancement Suite installed as extensions. RES should have infinite comment scroll enabled (usually a default setting).
1. Browse a large comment thread on reddit (example: [this one](https://old.reddit.com/r/sysadmin/comments/vn8oz1/manager_upset_about_order_of_recipient_in_an_email/))
2. Scroll to the very bottom of the comments, normally RES loads the next set, but instead you see "loading" and eventually Firefox throws up a banner stating "KeePassXC-Browser is slowing down firefox."

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.0
Operating system: Mac/Win/Linux - Bug observed on Linux and Windows.
Browser: Chrome/Firefox/Vivaldi/Chromium - Firefox 101.0.1

**Comment by varjolintu** [comment]
Did this already happen with 1.7.12?

**Comment by varjolintu** [comment]
This is probably because of the new more aggressive dynamic input field detection. Gotta investigate this.

**Comment by varjolintu** [comment]
It's clearly because of the new addition to the input field detection. Removing it will probably break some sites. I'm thinking maybe an extra option is needed for this, maybe a site-specific one which can be enabled when needed.

**Comment by Tremolo4** [comment]
I'm recently noticing freezes while playing games on https://www.boardgamearena.com
Seems to be caused by this extension, there's a small popup appearing sometimes telling me "KeePassXC-Browser is slowing down [...]". I'm not sure if this should be a new ticket or not.

**Comment by varjolintu** [comment]
@Tremolo4 It's the same issue. Already fixed, and I'm planning to release 1.8.1 soon. The new Improved Input Field Detection will be purely optional, and only meant for sites which have trouble to identify fields otherwise. Shouldn't be enabled by default anymore.

**Comment by gwarser** [comment]
Old bug, but I still have this issue on https://www.reddit.com/r/uBlockOrigin/comments/1etvawp/youtube_ads_detection_breakages_2024_08_16_ubo/

Profiling https://share.firefox.dev/405jcjU

KeePassXC - unknown
KeePassXC-Browser - 1.9.5
Operating system: Linux x86_64
Browser: Mozilla Firefox 135.0

Did you just blacklisted the domain? Because it seems to be fine on `old.reddit.com` but I'm using the `www.` with old UI set in settings.

**Comment by varjolintu** [comment]
@gwarser I made a fix for the login field identification in the previous release. Seems the new Shadow DOM identification method is a bit too aggressive.
