### ISSUE TITLE
Cannot connect KeepassXC from Firefox

### ISSUE THREAD

**Issue by zhum** [keepassxreboot/keepassxc-browser#1661]
Cannot connect KeepassXC from Firefox.

## Expected Behavior

After enabling browser integration in the KeepassXC and pressing extension icon on FF I should get green icon.

## Current Behavior

Get error:
```
KeePassXC-Browser has encountered an error:

Key exchange was not successful.
```

## Steps to Reproduce (for bugs)
1. Install FF from ubuntu 22.04 repo
2. Install KeepassXC from ubuntu 22.04 repo
3. Install keepassxc extension to FF
4. Enable Firefox and Chrome integration in the KeepassXC
5. Check integration works.

## Debug info
KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.0
Operating system: Linux x86_64 (Ubuntu 22.04)
Browser: Mozilla Firefox 101.0

**Comment by Mannshoch** [comment]
Something is coming.
https://www.omgubuntu.co.uk/2022/07/ubuntu-devs-fix-another-frustrating-firefox-snap-flaw
Firefox Snap beta and Gnome shell extension are working now. The whole thing is still beta.
