### ISSUE TITLE
feat: Implement support of remote DB

### ISSUE THREAD

**Issue by vitonsky** [keepassxreboot/keepassxc-browser#1663]
I use few devices and i want to get access to intermediate database which place on my trusted PC from another PC which in my local network.

I would to have ability to configure IP while connect new DB, to i can specify IP of my trusted PC, approve there the connect request and then use remote DB from my work PC.

This feature also would allow me to avoid copy my database to not trusted PC and unlock it there

**Comment by droidmonkey** [comment]
This is duplicate request, but honestly is impossible. Unlocking a database on an untrusted pc, even if the file is technically stored remotely, is still going to have the same risk. The database is stored in memory when in use.

**Comment by vitonsky** [comment]
Let's implement it in bridge then. To proxy DBs from another PC throw bridge

**Comment by droidmonkey** [comment]
you are welcome to implement all that, but we will not.
