### ISSUE TITLE
Keepassxc not connecting (Brave Browser)

### ISSUE THREAD

**Issue by Harpper** [keepassxreboot/keepassxc-browser#1669]
If I unlock my keepassxc database and then go onto a web site to login the icon is grey. I am unable to login
## Current Behavior
get message keepassxc can not connect

## Possible Solution
A work around seems to be to disabble the addon and immediately re-enabble. Once the login page is refreshed login works with keepassxc

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC -2.7.1
KeePassXC-Browser - 1.80
Operating system: Linux Mint 20.3
Browser: Brave

I have tried purging keepassxc, and addon and reinstalling with new stored keys (under Browser integration), but it only corrected things for one session(ie after reboot of PC problem repeats). Next time I used the computer had same issue. Same issue may be happening with Firefox which I only seldom use

**Comment by varjolintu** [comment]
And you've checked the https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide ?

**Comment by Harpper** [comment]
Thanks for your reply. The org.keepassxc.keepassxc_browser.json is in the correct place for both browsers. The file points to the path "path": "/usr/bin/keepassxc-proxy" that file exists there as does the file keepassxc. Is it pointing to the right file? I am guessing by the instructions further down that might be correct. I checked system monitor and keepassxc-proxy appears to be running
![Selection_006](https://user-images.githubusercontent.com/26712977/177768968-68c4cb92-05fa-4147-bc76-a17febfc0812.jpg)
![Selection_007](https://user-images.githubusercontent.com/26712977/177770027-d03983dc-0ad3-4d5c-a691-2a26bd38515d.jpg)
![Selection_008](https://user-images.githubusercontent.com/26712977/177770030-60dd5020-8ebe-4aca-bdbf-168bac5dcf13.jpg)
I logged into keepassxc midpoint on enabling developers mode

**Comment by varjolintu** [comment]
Have you tried enabling Chrome and Chromium support from KeePassXC? Can you see what process has started the `keepassxc-proxy` process?

**Comment by Harpper** [comment]
Chrome  was enabled already and I will now enable Chromium and see if that helps. Not sure how to determine the process that started keepassxc-proxy. Here is a screenshot of properties of the process taken from system monitor
![Selection_009](https://user-images.githubusercontent.com/26712977/177823629-1f462c8b-3cc1-4eee-9b0c-cf44b6840ef3.jpg)

**Comment by varjolintu** [comment]
It's clearly started from a Chromium-based browser, and if Brave is the only one running, then that's it. I have no idea why it woudn't work. Have you tried another browser, or older version of Brave? A couple of times Brave is to blame. They might have some internal blocking mechanism that has broken things.

**Comment by Harpper** [comment]
Seems to happen with Firefox 102.1 also, that is not chromium based is it?

**Comment by varjolintu** [comment]
You didn't mention how KeePassXC is installed though. Have you tried between PPA, Flatpak and AppImage?

**Comment by Harpper** [comment]
Installed from PPA. I should state that the only settings changed in the install is I increased the lockout time considerably and created 2 keys one for firefox and one for Brave. If I have time I will try the App image but I try to avoid Flatpaks

**Comment by Harpper** [comment]
That's funny. I reset the lockout time from 3600 sec to 60sec. And it worked
![Selection_011](https://user-images.githubusercontent.com/26712977/177860474-ef56b03a-0962-498b-8bef-0ac273a4f612.jpg)
Is this setting adjustable to only a certain time?
I will keep an eye on things this way. But my preference is not to have to log into keepassxc every 60 sec

**Comment by Harpper** [comment]
May have been false hope. I rebooted the PC and keepassxc would not connect with the browser. When I have time I will try an appimage. Can the two exist at once or do I need to uninstall the PPA and it's deb keepassxc

**Comment by varjolintu** [comment]
In this case I'd just leave one install at a time.

**Comment by Harpper** [comment]
Using the solution here https://github.com/keepassxreboot/keepassxc-browser/issues/1391 of making org.keepassxc.keepassxc_browser.json  a read only file seems to have solved this matter. I installed the addon from the Brave extension page

**Comment by varjolintu** [comment]
What file contents are changed if only read-only works? You can try disabling KeePassXC's settings Browser Ingegration -> Advanced -> [ ] Update native messaging manifest files at startup, but this returns the defaults to the JSON scripts. And as far as I know Brave installs extension from Chrome Web Store, so extension ID's are identical.

**Comment by Harpper** [comment]
I rebooted the PC this morning and again a little later and both time Keepassxc worked fine. So I don't pretend to understand why this works but I am satisfied and not likely to pursue it further despite it not working on one previous reboot
