### ISSUE TITLE
Automatic reconnect when using the username input icon

### ISSUE THREAD

**Issue by MatthiasSchmitz93** [keepassxreboot/keepassxc-browser#1675]
## Expected Behavior
When using the username field icon with no active connection, a connection is automatically established in the background if possible, and the input fields are filled afterwards. Only a single click is required.

## Current Behavior
Currently, an error message is shown, and the connection needs to be (re-) established manually using the browser extension toolbar icon, and only then can the icon be used. Sometimes, I even have to reload the page. Three or even four manual steps are required.

![67489401-cea26f80-f671-11e9-87dc-47976ad86f6a](https://user-images.githubusercontent.com/34464190/178059742-b5b22456-9901-470e-b9a1-f7d085c532a7.gif)

This issue has occurred before (#650); I just updated the debug info.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.0
Operating system: Win64
Browser: Chrome/Chromium 103.0.0.0

**Comment by bllngr** [comment]
I can confirm that it reappeared in Firefox on both Windows and Linux.
