### ISSUE TITLE
Errors querySelectorAll is not a function in console when used on an angular-based website

### ISSUE THREAD

**Issue by victornoel** [keepassxreboot/keepassxc-browser#168]
## Expected Behavior

The browser console should not be polluted by the following messages:
```
keepassxc-browser.js:1147 Uncaught TypeError: mut.target.querySelectorAll is not a function
    at MutationObserver.<anonymous> (keepassxc-browser.js:1147)
```

****
## Current Behavior

When going to an angular-based website and some events are triggered, I get those errors in the browser console

## Possible Solution

I suppose keepassxc-browser is polluting the global javascript namespace with something that makes it being triggered or whatever when an event is dispatched by angular…

## Steps to Reproduce (for bugs)

1. Go to https://angular.io/tutorial
2. Open the browser console
3. Click and move your mouse everywhere on the left bar menu until the error logs appear

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.3
Operating system: Linux
Browser: Chromium
Proxy used: NO

**Comment by varjolintu** [comment]
This has been already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/157. Just wait for the next release.

**Comment by victornoel** [comment]
@varjolintu perfect, thanks a lot for the update!

**Comment by victornoel** [comment]
@varjolintu any ETA for the next release? This is really painful :)

**Comment by varjolintu** [comment]
Soon. That's all I now.
