### ISSUE TITLE
Reconnect & fill when using the username input icon

### ISSUE THREAD

**Issue by Matt-Schmitz** [keepassxreboot/keepassxc-browser#1680]
## Expected Behavior
If you use the username field icon without being connected, a connection should be established and the input fields should be filled in with just one click.

## Current Behavior
Two clicks are required to fill input fields. The first click reconnects to the database and a second click is required to fill the fields.

Also, thank you @varjolintu for #1676. I no longer need to press the reload button in 1.8.1.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Win64
Browser: Chrome/Chromium 103.0.0.0

**Comment by varjolintu** [comment]
Ah, of course. Lets also fix this one.
