### ISSUE TITLE
Does not work on https://login.aliexpress.ru domain

### ISSUE THREAD

**Issue by ratijas** [keepassxreboot/keepassxc-browser#1682]
## Overview

On russian aliexpress login page, KeePassXC can not fill in login and password. The fields are supposedly detected, but the key icon is gray instead of green.

I suspect this chineese website does a lot of cursed stuff under the hood that may affect text field detection and scripting.

![image](https://user-images.githubusercontent.com/6737986/179188395-7896f076-767a-4e54-8784-90a46fad9c6a.png)

![image](https://user-images.githubusercontent.com/6737986/179190023-ae2c2406-0a18-41bd-a359-4c06fd1ed8f5.png)

## Steps to Reproduce
1. Store a password for aliexpress.com, "allow" plugin to use it on .ru counterpart
2. Open URL https://login.aliexpress.ru

## Expected Behavior

Login & password should be auto-filled.

## Actual Behavior

Nope, they aren't.

## Context

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.5
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.18.10-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.2

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
I had no problems with the site. Please check that your entry URL is `﻿https://login.aliexpress.ru/`.

**Comment by ratijas** [comment]
> Please check that your entry URL is ﻿https://login.aliexpress.ru/.

It most definitely is.

![image](https://user-images.githubusercontent.com/6737986/179206243-825b29c8-f531-45b3-8a2f-06f600f5218c.png)

Any other ideas?

**Comment by varjolintu** [comment]
Enable Debug Logging from the browser settings and check what the Javascript Console says when you Inspect the page.

**Comment by ratijas** [comment]
Sometimes the icon turns green, but still nothing happens.

> Enable Debug Logging from the browser settings and check what the Javascript Console says when you Inspect the page.

eh, how do I export it as a text log…

![image](https://user-images.githubusercontent.com/6737986/179208448-dd40c086-fb01-4795-b437-b43d22005b10.png)

```
Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
[keepassxc-browser.js:10](moz-extension://26bf26bb-a188-4925-8c9f-e8a6e4980542/content/keepassxc-browser.js)
    sendMessage moz-extension://26bf26bb-a188-4925-8c9f-e8a6e4980542/content/keepassxc-browser.js:10
```

**Comment by varjolintu** [comment]
Seems like a really strange error messages. Few things you can test:
- Disable all other extension except KeePassXC-Browser
- Create a new temporary profile to Firefox

**Comment by varjolintu** [comment]
Closing this. We track these issues in: #1358.
