### ISSUE TITLE
Cant connect to KeepassXC database

### ISSUE THREAD

**Issue by aiaiduo** [keepassxreboot/keepassxc-browser#1685]
## Expected Behavior

KeepassXC database is enabled. When you open your Chrome browser, the web plug-in will tell you that you cannot connect to the KeepassXC database. Find a solution.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Win 11 21H2 64bit
Browser: Chrome/Chromium 103.0.5060.114 （64 位）

**Comment by varjolintu** [comment]
Definitely a duplicate issue. Please see the following threads:
https://github.com/keepassxreboot/keepassxc-browser/issues/1681
https://github.com/keepassxreboot/keepassxc-browser/issues/1671
https://github.com/keepassxreboot/keepassxc-browser/issues/1267
