### ISSUE TITLE
Add menu for database entries

### ISSUE THREAD

**Issue by Awem** [keepassxreboot/keepassxc-browser#169]
It would be great to have menu/dropdown of all the entries in the database. It should be similar to the menu of the "Kee" browser addon. It would:

- open, when user clicks the KeePassXC-Browser toolbar button
- render the same tree view, show in KeePassXC
- open the URL of the entry, when clicked (maybe also doing autofill)

**Comment by varjolintu** [comment]
I'm not comfortable with this kind of feature. In my opinion the browser extension shouldn't have a direct access to every entry in the database, only the ones user grants access to.

**Comment by Awem** [comment]
Maybe restrict it then to entries, where access was granted? Or just render a tree of links, built from entries that include an URL?

**Comment by varjolintu** [comment]
That could be possible. I'll get back to this when I have some extra time.

**Comment by varjolintu** [comment]
Closing this as the extension already behaves almost identically on pages where credentials are found.
