### ISSUE TITLE
Ignore Sites not working

### ISSUE THREAD

**Issue by akovia** [keepassxreboot/keepassxc-browser#1692]
## Expected Behavior

I am unable to prevent the "KeepassXC - Browser Access Request" dialog from showing. Even using Remember with Deny All doesn't prevent it from popping up.

## Current Behavior

On our BigCommerce website I have to go in and edit customer information for each customer, and every time I do I get this dialog I have to dismiss because there is an option for customer passwords. It seems to want to match every credential for BigCommerce I have.

![KeepassXC-BrowserExt-Dismiss2](https://user-images.githubusercontent.com/10238233/182393603-8edfe436-4b25-4023-9d45-540c0c0aa909.jpg)

I thought I could use the Site Preferences in the settings to filter it out, but it doesn't seem to work or I'm doing it wrong. I also can't determine if you can use wildcards or not.

![KeepassXC-BrowserExt-Dismiss3](https://user-images.githubusercontent.com/10238233/182391915-72351d2d-e38e-480b-95c5-2e20ab06996a.jpg)

## Steps to Reproduce (for bugs)

1. Go to a customer record and choose edit on BigCommerce (https://store-xxxxxx.mybigcommerce.com/manage/customers/xxx/edit

## Debug info

KeePassXC - **2.7.1**
KeePassXC-Browser - **1.8.1**
Operating system: **Win**
Browser: **Brave**

**Comment by varjolintu** [comment]
Does it help if you use `https://*.mybigcommerce.com/manage/customers/*` as the URL?

**Comment by akovia** [comment]
@varjolintu 
Thanks but that does not seem to work either.

**Comment by varjolintu** [comment]
Strange. I could not reproduce this kind of behavior with any of the sites I have stored.
If you are able, please debug the following function at the page load:
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js#L667

**Comment by akovia** [comment]
I'm afraid this is to far out of my wheelhouse. I'm technically inclined, but I'm not a programmer. (Bash scripts are as adventurous as I get) If you can give exact instructions of what I should do, I'm fairly confident I can follow them.

I can make a video if need be, but I would have a ton of masking to do as this has to do with customer data. Might not be worth the trouble if I am the only one affected. Either way, thanks for the quick responses.

**Comment by varjolintu** [comment]
I could try to find another page with URL structure like that and test it.

**Comment by varjolintu** [comment]
Can you retry the feature with the latest release 1.8.5? The wildcards should now work better.

**Comment by varjolintu** [comment]
Let's reopen this if the problem still occurs.
