### ISSUE TITLE
Custom Fields Not Working During Fill

### ISSUE THREAD

**Issue by GuardianMajor** [keepassxreboot/keepassxc-browser#1695]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. go to https://www.tsc1099.com/
2. define custom field for the site id
3. try to log in with credentials

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
the custom field setup based on (https://keepassxc.org/docs/#faq-browser-string-fields) should fill the first field, username the next and password final and submit

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
it only ever fills the username/password

## Context
[NOTE]: # ( Give us any additional information you may have. )
the instructions also says "the order is critical" but the additional attributes automatically sort alphabetically you have no control over the order, try it with the items on your instructions, it will put it in order of Account, Branch, Sub-Account, not the order you have it

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Win64
Browser: Microsoft Edge 103.0.1264.77

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
Select Custom Login Fields for the site like this:
<img width="651" alt="Screenshot 2022-08-06 at 10 43 09" src="https://user-images.githubusercontent.com/24570482/183239768-a93de3a0-b8c7-48c6-a3b7-3fb7b7fbd67a.png">

Add a new `KPH: Site ID` attribute your entry and give it the right value (I used `SITE_ID` for testing).

Result:
<img width="357" alt="Screenshot 2022-08-06 at 10 45 13" src="https://user-images.githubusercontent.com/24570482/183239829-986f463a-6fa7-401b-9000-a95e24a895f1.png">

**Comment by GuardianMajor** [comment]
Thank you, I am glad that I am not going crazy, I did all of that exactly except I called it `KPH: SiteId`.

Question for you: 

1) does the fact that my package is portable version matter?
2) did you get it to fill all of it through the single click fill or did you do something special, like say auto-type?

I'm just trying to narrow down what I might be doing differently that might be causing my issues. Bear with me, thank you.

**Comment by GuardianMajor** [comment]
I am redoing it just in case, here is mine, nearly identical

![image](https://user-images.githubusercontent.com/5274181/183274869-371670df-1d29-4ab6-a228-4762e3aee7cd.png)

Used your syntax for the attribute: `KPH: Site ID` and when I try to fill it only puts the U/P and not the first field which you have as `SITE_ID` for the value :(

**Comment by varjolintu** [comment]
Make sure you have space after `KPH:`.

**Comment by GuardianMajor** [comment]
Yes, I do. I even went back to double check.

**Comment by varjolintu** [comment]
Then make sure this option is enabled:
Settings -> Browser Integration -> Advanced -> [ ] Return advanced string fields which start with "KPH: ".

**Comment by GuardianMajor** [comment]
That was it, that did it. Thank you, much appreciate the help.
