### ISSUE TITLE
Feature Request: fill forms

### ISSUE THREAD

**Issue by jonnytest1** [keepassxreboot/keepassxc-browser#1696]
## Expected Behavior
i think it would be cool to have a way to fill out forms from a keepass entry with properties

idea: make an entry in keepass 
add additional properties under "advanced" like Name,LastName,...
then this extension could analyze the page for forms and their "name" attribute , and try to match them up to the attributes from keepass 

## Current Behavior

feature doenst exist

## Possible Solution
for the name attr:convert to lowercase , split and permutate around [-_ ], replace(/[^a-zA-Z]/,'') 
maybe add a small overlay where the user can check off on which fields will be filled (and or report cases that may be missing)

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by jonnytest1** [comment]
its currently possible to use a generic auto-type sequence to achieve something approximating this - but minor differneces on websites can trip this up relatively quickly

**Comment by droidmonkey** [comment]
This is a duplicate request
