### ISSUE TITLE
Unable to auto-paste username and password

### ISSUE THREAD

**Issue by RichardAmes** [keepassxreboot/keepassxc-browser#1698]
Unable to auto-paste username and password
at https://servicecentre.latitudefinancial.com.au/login

and I don't understand how to overcome this.

Regards, Richard.

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 103.0

**Comment by varjolintu** [comment]
Entry with the page URL worked without any problems for me.

**Comment by varjolintu** [comment]
Please inform if you haven't been able to solve the issue.
