### ISSUE TITLE
defineStringField (Zeichenkettenfeld #1) don't work

### ISSUE THREAD

**Issue by xstable** [keepassxreboot/keepassxc-browser#1699]
in the Browser-Plugin I have defined an additional String-Field: 

![image](https://user-images.githubusercontent.com/1778068/185612568-76881657-a086-4226-ab43-5e8cfa8dd040.png)

Now in the Browser, I'd like to assign the value of this "Additional Property" to an input-field in a page: 

![image](https://user-images.githubusercontent.com/1778068/185612915-872f4f53-a3b6-4e01-88aa-633121df3e07.png)

If I click on the blue button, it assign "Zeichenkettenfeld #1" to it: 
![image](https://user-images.githubusercontent.com/1778068/185613146-5e45ec94-a975-4d08-b6f8-d8aad215a905.png)

But even If I reload the page and try to let keepassxc-plugin fill the input-fields, there are never any value in this assigned field.

# Question
Am I doing something wrong?
Is there (and if, how) a way to assign the previous created {S:ZUGANGSNR} to an Input-Field?

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Linux x86_64
Browser: Chrome/Chromium 104.0.5112.81

**Comment by varjolintu** [comment]
The attribute name should start with `KPH: ` so use `KPH: ZUGANGSNR` instead.

**Comment by xstable** [comment]
thanks a lot @varjolintu  for your answer.

I've tried this, didn't get it to work.

![image](https://user-images.githubusercontent.com/1778068/185644944-c7bf9d11-5f2c-47ee-940d-eaea9f569487.png)

And in the Plugin in the browser I still only see this `Zeichenkettenfeld #1` which are not replaced.
Any Idea, what the issue might be.

**Comment by xstable** [comment]
I did, the screenshot only shows the selection of the first one. 
I've added username and password after that. 
Anyway, first field are never filled with data.

**Comment by varjolintu** [comment]
Double check the setting I mentioned earlier. If you right-click the mouse on the extra field, can you see Fill Attribute in the context menu?

**Comment by xstable** [comment]
Today it works without changes. It might be that I need to fully reboot the browser and keepass to make it work
