### ISSUE TITLE
BUG: KeepassYC extension does not remember deny choices for credentials

### ISSUE THREAD

**Issue by Sebi2020** [keepassxreboot/keepassxc-browser#1701]
## Expected Behavior

The extension should remember deny choices, if I mark the "Remember" or in german "Merken" checkbox.

## Current Behavior

Currently the KeepassXC extension only remembers allow choices for credentials if I mark the "Remember" or in german "Merken" checkbox. 

## Possible Solution

Also save deny choices. It's annoying if KeepassXC extension asks me over and over if I want to allow credential x for page y.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
This is a known issue and already fixed.

**Comment by Sebi2020** [comment]
@varjolintu  Where and when? This behaviour is still present in the current version (v. 1.8.1)

**Comment by varjolintu** [comment]
It's fixed with: https://github.com/keepassxreboot/keepassxc/pull/8273
