### ISSUE TITLE
PayPal new TOTP

### ISSUE THREAD

**Issue by yeezy69** [keepassxreboot/keepassxc-browser#1703]
Feature request :-)

PayPal has launched a new TOTP interface. Instead of one input field, there are now six individual fields for one digit each. Unfortunately, the automatic filling out doesn't work anymore. Maybe there is a way to have this field filled in automatically again in the future.

Thank you for the effort!

![Screenshot_001](https://user-images.githubusercontent.com/22444686/186495817-5c483d75-6e6b-4e73-a914-0d5fec5b0d06.png)

## My versions
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Linux
Browser: Vivaldi

**Comment by varjolintu** [comment]
Of course.. We already support segmented TOTP fields like this but including all the stuff PayPay has done before to their login process, this might be again some non-standard implementation. Fixing this ASAP.

**Comment by varjolintu** [comment]
@Nou4r It works fine for me. Just tested it. Make sure you have "Use predefined sites for compatibility." enabled in your extension settings.

**Comment by acordtag** [comment]
> I have it enabled

you need to right click on the first input box and select "Fill OTP" and it will do it.
