### ISSUE TITLE
Fail to fill the username of a SSO login page

### ISSUE THREAD

**Issue by unexperiensd** [keepassxreboot/keepassxc-browser#1707]
A [SSO login page](http://webmail.studenti.unipd.it) is not correctly recognized by the add-on.

## Expected Behavior
Case 1: the clickable icon should appear at the username field, and after clicking it the username and password fields should be filled. 

Case 2: by clicking at the add-on icon in the toolbar, the field(s) of the saved accounts should appear and, after clicking one the username and password fields should be autofilled.

## Current Behavior
Case 1: the icon does not appear in the username field, just the password generator icon in the password field (Fig. 1). If the empty username field is clicked, the drop-down rows of the saved accounts (2 in my case) appear. If I click on the row, only the password is filled. If I select the rows with the arrow keys and press Enter, the fields are correctly filled. After the page is reloaded due to an unsuccessful login attempt, the icon in the username field appears, but again by clicking on the field the username is not filled.

Case 2: again by clicking on the field, only the password is filled. 

## Steps to Reproduce (for bugs)

1. Click on the link
2. Create a dummy account
3. Try to fill the fields, either by clicking or by keystrokes.

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system:Linux
Browser: Firefox

![Fig. 1](https://user-images.githubusercontent.com/38072190/187396098-1af905ea-1f5e-4557-a865-9fd391e46e31.png)

**Comment by varjolintu** [comment]
There's a script in the page that deletes the content entered by the extension. Nothing we can do here.
