### ISSUE TITLE
High cpu in some search boxes

### ISSUE THREAD

**Issue by DreamingGhost** [keepassxreboot/keepassxc-browser#171]
## Expected Behavior
Typing in the search field in http://puzzledragonx.com results in little/no increase in cpu.

## Current Behavior

Typing in the search field on http://puzzledragonx.com results in high cpu usage. This goes away after 5-10 seconds.

![image](https://user-images.githubusercontent.com/39640809/40572367-66ae375a-6078-11e8-9751-80f6bc1a616f.png)

## Steps to Reproduce (for bugs)

1. Go to http://puzzledragonx.com
2. Type in the search box
3.
4.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.3
Operating system: Win
Browser: Firefox 60.0.1
Proxy used: NO

**Comment by varjolintu** [comment]
For me this happens even when I disable the extension. Can you confirm the same behaviour?

**Comment by DreamingGhost** [comment]
With the extension disabled, I get a brief delay (~1 sec or less) and no Firefox warning about any extension or webpage causing firefox to slow down.

**Comment by varjolintu** [comment]
I can definitely reproduce that. Looks like https://github.com/keepassxreboot/keepassxc-browser/pull/166 will solve the issue.
