### ISSUE TITLE
Steam new TOTP

### ISSUE THREAD

**Issue by herrwusel** [keepassxreboot/keepassxc-browser#1710]
Similar to #1703 steam has a new interface for handling TOTPs. Keepassxc-browser currently does not identify the field as totp and one has to copy/paste to fill in. It would be nice if the extensions handle this field correctly. Thanks!

![image](https://user-images.githubusercontent.com/8242787/188563990-61f4e5e4-78eb-480e-b243-a1edd7a1afeb.png)

**Comment by varjolintu** [comment]
Sure, let's fix this one too.
