### ISSUE TITLE
[Steam Deck] Key exchange was not successful

### ISSUE THREAD

**Issue by skibbipl** [keepassxreboot/keepassxc-browser#1712]
## Expected Behavior

I'm trying to setup keepassxc browser plugin in firefox in steam deck Arch linux. Unfortunately I'm constantly getting error message.

## Current Behavior

Key exchange was not successful.

## Possible Solution

Wish I knew

## Steps to Reproduce (for bugs)

1. Install KeepassXC from discover app store
2. Install KeepassXC plugin from Mozilla
3. Enable browser integration in app
4. Try to reload browser extensions

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.1
Operating system: Linux steamdeck 5.13.0-valve21.1-1-neptune-02211-gc54cda5a36f3 #1 SMP PREEMPT Mon, 08 Aug 2022 22:27:56 +0000 x86_64 GNU/Linux
Browser: Firefox 104.0.2 (64-bit)

```
[Error keepass.js:270] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. [global.js:178:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/common/global.js)
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:317:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/background/client.js)
[Error ] KeePassXC-Browser - Failed to connect: Unknown error [global.js:178:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/common/global.js)
[Error client.js:336] KeePassXC-Browser - No content script available for this tab. [global.js:178:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/common/global.js)
[Error keepass.js:753] KeePassXC-Browser - 9: Key exchange was not successful. [global.js:178:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/common/global.js)
[Error keepass.js:440] KeePassXC-Browser - No content script available for this tab. [global.js:178:13](moz-extension://85fc7d70-ab77-4352-a414-5633c3b5f84d/common/global.js)
```
I followed troubleshooting wiki but everything seems to be fine including strace part.

**Comment by droidmonkey** [comment]
Is Firefox installed as a snap?

**Comment by skibbipl** [comment]
No, it's a flatpack

**Comment by varjolintu** [comment]
@skibbipl Please install a non-Snap or non-Flatpak version.

**Comment by droidmonkey** [comment]
Flatpak support for native messaging is coming soon, but that is on Firefox to implement and deploy, not us.

**Comment by benjamin051000** [comment]
Looks like it may come out soon: https://github.com/flatpak/xdg-desktop-portal/pull/705
