### ISSUE TITLE
Visiting paypal.com doesn't autofill and breaks other sites

### ISSUE THREAD

**Issue by Lucki** [keepassxreboot/keepassxc-browser#1713]
## Expected Behavior

Paypal.com should autofill, and other sites visited afterwards should still autofill as before visiting paypal.com.

## Current Behavior

Paypal.com does not autofill. Visiting another site afterwards yields `Nonce compare failed` in the console.

## Steps to Reproduce (for bugs)

Context: Autofill means clicking on the symbol, so the credentials will appear in the input fields. This working is the verification.

1. Verify a site working. For this test I'm using `https://posteo.de/de` which works perfectly fine.
    There are some messages already in the console, but they seem unrelated, and the extensions is still working:
    * `[Error keepass.js:770] KeePassXC-Browser - No content script available for this tab. global.js:178:13`
    * `[Error init.js:66] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. global.js:178:13`
    * `[Debug page.js:317] KeePassXC-Browser - Found 1 entries for url https://posteo.de/de global.js:170:13`
3. Now visit `https://www.paypal.com/signin/`.
    * The extension shows the clickable symbol in the username input but clicking it doesn't fill anything.
    * There aren't any new messages in the console.
5. Now go back to the previously working site and notice that it isn't working anymore.
    * Like on `paypal.com` clicking the symbol now doesn't fill anything.
    * There's an error message in the console: `[Error client.js:175] KeePassXC-Browser - Nonce compare failed global.js:178:13`
7. Reloading the background extensions tab resets the nonce and the extension will work again until `paypal.com` is visited/reloaded again.

I've already tried without any other addons and with Firefox internal security setting turned down to the lowest possible setting.
~~I will try with a temporary new profile in a minute and edit this post.~~ This also happens with a brand new Firefox profile.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2
Operating system: Win10
Browser: Firefox 104.0.2

**Comment by varjolintu** [comment]
Good catch. Seems this PR breaks it: https://github.com/keepassxreboot/keepassxc-browser/pull/1684. I need to add a version check for that. I tested that to be backwards compatible but something strange still happens there.

**Comment by Lucki** [comment]
Well, I wanted to debug why the extension sometimes doesn't autofill for some sites. This is going on for longer than the release window of that PR (many months) and PayPal was always a constant site that didn't work at all.

Seems like I found a brand-new bug which is good but also means I have to do all testing again when the fix arrives to debug the initial problems I wanted to debug in the first place. :-/

**Comment by unicorn855** [comment]
This is interesting, I have the exact same behaviour for https://almaweb.uni-leipzig.de
After the 'nonce compare failed' error, I get an 'Uncaught (in promise) Error: No tab with id: xx at browser-polyfill.min.js:1:6365'
I believe they are related. 

This has only started happening for me starting today (both sites worked fine just yesterday).

I am on version 2.7.1 of KeePassXC and version 1.8.2 of KeePassXC-Browser
I use Edge version 105.0.1343.27 (64Bit)
Windows 11 Home 22622.590

**Comment by varjolintu** [comment]
This is already fixed. I'll make a quick release right away.

**Comment by Lucki** [comment]
Confirmed fixed.

I also was able to figure out why paypal autofill doesn't work: The entry had a property set as "Deny". I have no idea how that got in there.

**Comment by varjolintu** [comment]
@Lucki Good to hear! I remember I encountered the bug before but it was during a debug session so I didn't check it out any further. For now, the extra parameter that caused the problem is removed, but I need to make a proper fix for this after the related PR is merged in KeePassXC side.
