### ISSUE TITLE
How do I enable auto-fill for https://www.eevblog.com/forum/

### ISSUE THREAD

**Issue by tonyjonespdx** [keepassxreboot/keepassxc-browser#1717]
How do I enable auto-fill for https://www.eevblog.com/forum/

If I try to manually identify the username/password fields it gets very confused.

**Comment by varjolintu** [comment]
That site worked like a charm without any adjustments. I need more info about how this fails for you.

**Comment by tonyjonespdx** [comment]
I'm using Firefox.  
The "fill credentials from KeepassXC" icon is present in the password field box but it's greyed out.  
Clicking on the extension "redetect login fields" does nothing.

**Comment by varjolintu** [comment]
Check your entry URL then. Clearly it doesn't match.
