### ISSUE TITLE
Password save prompt disappears if site redirects

### ISSUE THREAD

**Issue by MightyPork** [keepassxreboot/keepassxc-browser#172]
I had this on a couple sites, but most recently eBay.

The icon starts flashing, but then the save prompt disappears as the page redirects (maybe multiply).  Actually, there is no save prompt until you click the icon, which is surprising, as the native password manager opened a little dialog with the Save button automatically.

You have to either be very quick with saving the password, or do it manually in the keepassxc GUI.

keepasxc is 2.3.3 and i'm using the latest firefox extension version for FF quantum 60.0.1 on Arch Linux

**Comment by varjolintu** [comment]
There's one fix coming to this icon and the remember dialog (a case where it doesn't appear on a first click). But if the icon disappears because of page redirects you can increase the allowed redirect amount from the settings (Redirect Allowance).

**Comment by MightyPork** [comment]
ah, i'll try the redirect allowance and see if it helps

**Comment by MightyPork** [comment]
okay i think the slider helped. Have definitely seen the *other* bug you mentioned happening as well, but that's a different issue

**Comment by PatRiot1337** [comment]
I have the same problem even with infinite redirect amounts on some websites.... is it a bug?
