### ISSUE TITLE
Checkboxes on dark background in site settings do not work

### ISSUE THREAD

**Issue by marcelmore** [keepassxreboot/keepassxc-browser#1720]
## Expected Behavior

I wanted to add an url in the site settings to activate username only detection for it. After adding the URL I wanted to toggle the checkbox for username only detection by clicking on it.

## Current Behavior

Clicking on the checkbox for username only detection does not toggle it. After adding more URLs I found out, that I can only toggle the checkboxes with light background. I can not toggle the checkboxes on the dark background. I made a screenshot to illustrate, which checkboxes work or do not work:

<img width="1136" alt="checkboxes" src="https://user-images.githubusercontent.com/2975481/189541174-49e93ab3-6b9d-410f-bc37-788ca1142166.png">

## Steps to Reproduce (for bugs)

1. Add multiple URLs.
2. Try toggle checkboxes on dark background.
3. Try to toggle checkboxes on light background.
4.

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.1
Operating system: MacIntel
Browser: Mozilla Firefox 104.0

**Comment by varjolintu** [comment]
Wow, that's strange. Gotta take a look.

**Comment by varjolintu** [comment]
Those checkboxes were actually working just fine, but the problem was within the CSS theme. If you change the theme to Dark you can see checked checkboxes normally.

**Comment by marcelmore** [comment]
Yup, works for me. Thanks.
