### ISSUE TITLE
Does not detect password-only login after logging in with username + password

### ISSUE THREAD

**Issue by l0b0** [keepassxreboot/keepassxc-browser#1721]
## Steps to Reproduce

1. Start Chromium with the KeePassXC-Browser extension
1. Get an account on gog.com
3. Log in using the KeePassXC-Browser auto-fill (this seems to save the username in the browser)
4. Log back out
5. Click "SIGN IN"

At this point, a login dialogue shows up _with my username pre-filled._

## Expected Behavior

The password should be auto-filled by KeePassXC-Browser.

## Current Behavior

The password field is empty: 
![Screenshot from 2022-09-12 12-37-11](https://user-images.githubusercontent.com/168301/189633518-ebd42137-bad4-43d1-ace7-68b186c3975a.png)

To fill it I have to manually click the KeePassXC-Browser icon.

## Debug info

KeePassXC - Version 2.7.1
KeePassXC-Browser - 1.8.2.1
Operating system: Linux
Browser: Chromium

**Comment by droidmonkey** [comment]
You have auto-fill enabled? If so, then this is absolutely the desired behavior. We don't want to just place a password in any old password field that happens to be on a page. Auto fill is rather dangerous.

**Comment by l0b0** [comment]
I don't understand the "any old password field" argument at all. On some web sites auto-fill works flawlessly, but on others (quite a few) I always have to manually press the KeePassXC icon.

**Comment by varjolintu** [comment]
Just tested this and I had no problems with the password auto-fill after logout.

**Comment by varjolintu** [comment]
Let's reopen this if needed.
