### ISSUE TITLE
Terrible Failure

### ISSUE THREAD

**Issue by pepponia** [keepassxreboot/keepassxc-browser#1729]
## Expected Behavior
I have the extension for ChromeBrowser: KeePassXC-Browser

## Current Behavior
If I am NOT connect with Keypass I am able to read my password (Keepass)under The Bottom "Settings"!
So everybody can read my password in "connected databases" in plain text!

## Debug info

KeePassXC - {2.7.1}
KeePassXC-Browser - {?}
Operating system: Mac/Win/
Browser: Chrome/

**Comment by pepponia** [comment]
It was my fault! SORRY

**Comment by varjolintu** [comment]
Seems there's no limits what CSS can do nowadays.
