### ISSUE TITLE
Feature Request: Redetection of credential fields should be done automatically

### ISSUE THREAD

**Issue by XIncognito10** [keepassxreboot/keepassxc-browser#173]
## Expected Behavior

It would be easier for keepassxc to automatically redetect credentials using a polling loop. If the method isn't too CPU intensive then it should be able to be done, every one second. This polling loop could also detect other events, such as when the database is opened, when an entry is saved or updated, ect

## Current Behavior

currently, the reloading of the plugin, after opening the database sometimes doesnt work and has to be done manually. Also the redetection of credential fields often needs to be done manually, especially if its on the same website that one has logged into and then logged out of without reloading

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.3
Operating system: Mac/Win/Linux
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
Actually that is exactly what the older versions did. Newer version switched to use MutationObserver which is slightly more CPU intensive but works faster. There are already fixes waiting for the next release that will solve the problems you described.
