### ISSUE TITLE
connection to database lost after about 5 minutes - Chrome Windows 10

### ISSUE THREAD

**Issue by mickeydaley** [keepassxreboot/keepassxc-browser#1732]
## Overview
The connection to KeePassXC database is lost after about 5 to 10 minutes.  I get it going again by going into the chrome extension for KeePassXC and cycling "Allow access to file URLs".  Once its reconnected, I can refresh my web page login screen and all is good.  I'd rather not have to do this kluge though as it should just be connected after I start my Chrome browser.  IF I can figure this one out, I'd likely contribute a couple sheckles as I like to support products that I use.  If I can't figure this one out....I may need to move to something like (cough cough) Dashlane or the like.  I like KeePassXC because it 1. keeps my passwords local to my laptop 2. interfaces somewhat easily with my browser.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Start KeePassXC in the morning and login.  Settings are set to keep database open all day.
2. Start Chrome browser and wait 5 to 10 minutes.
3. Connection from browser to KeePassXC is "lost".  The login key icon to right of site link shows grey key with a red X.
4. Open up another tab to Chrome settings --> Extensions --> Details button for 
KeePassXC-Browser --> turn feature "Allow access to file URLs" off then on   
The connection to the database connects again.  I don't have to go to the widget in the chrome again.  

Yes, I know there is a button that says "reconnect database", but I don't do that because it doesn't work.  That button doesn't work for me.  When I click the reload button, I get the message "Message encryption failed. Is KeePassXC running?"  So I have to do the 4 odd steps above to get the database reconnected.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect the database to stay connected 100% of the time
I expect to not to have to reload the database every time I restart my laptop. 
I do expect to have to login when I start my laptop and possibly every time I login to my laptop.
I do not expect to have to login to the KeePassXC after I lock my laptop which I do every time I get up and away from my laptop.  (Yes, I have TeamMates near me willing to send out e-mails to large number of other TeamMates with snarky comments.)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Chrome browser disconnects from database about every 5 to 10 minutes

## Context
[NOTE]: # ( Give us any additional information you may have. )
Note, this is my corporate laptop (hence I'm willing to contribute actual $'s) and there may be group policies in Windows and locked down policies on Chrome that I won't be able to change.  NOTE: I do know that my password tool in Chrome is locked out.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION: 2.7.1
Revision: REVISION: 5916a8f

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS  ----------------> Windows OS: Windows 10 Build 19044
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by mickeydaley** [comment]
I FINALLY FIXED MY ISSUE.  I had KeePassXC automatically start when I booted.  I need passwords right away before I open my browser.  The solution was to NOT automatically start KeePassXC (KeePassXC.exe) and let Chrome start keepassxc-proxy.exe.

When I was starting KeePassXC.exe automatically, it would also start keepsassxc-proxy.exe.  Then when I started Chrome it had a connection for about 5 minutes.  After 5 minutes my Chrome browser wouldn't connect, then I'd click the "Reload" button off the address button and it would always fail.  My workaround for about 1 year has been to open the Chrome Extensions in a new tab, select the KeePassXC extension, then toggle off/on the "Allow access to file URLs" and "Collect errors" then go back to the page I needed and recycle and it connected.

Not automatically starting KeePassXC has been my problem all along.  I don't auto start it and I start Chrome FIRST before opening KeePassXC and all is good.

**Comment by varjolintu** [comment]
@mickeydaley FYI: KeePassXC does not start the `keepassxc-proxy.exe` process. That is started by the browser.

**Comment by JohnLGalt** [comment]
Yeah, I autostart KPXC as well and haven't lost connection to the browser.

I wonder if the browser itself is pausing the kpxcproxy process after a certain time out period?

**Comment by varjolintu** [comment]
@JohnLGalt It may be possible. Could it be that if Chrome allows background processes to stay up even when Chrome is closed affect the proxy's behavior?

**Comment by JohnLGalt** [comment]
Ahhh, that's another good thing to look at. I disallow all Chromium browsers from running in the background when closed.
