### ISSUE TITLE
manifest_version: 2 error

### ISSUE THREAD

**Issue by lessfoobar** [keepassxreboot/keepassxc-browser#1733]
When importing the extension from github https://github.com/keepassxreboot/keepassxc-browser/releases/download/1.8.2.2/keepassxc-browser_1.8.2.2_chromium.zip to vivaldi browser it is poping up the following error:

Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{
    "manifest_version": 2,
    "name": "KeePassXC-Browser",
    "version": "1.8.2.2",
    "version_name": "1.8.2.2",
    "description": "__MSG_extensionDescription__",
    "author": "KeePassXC Team",
    "icons": {
        "16": "icons/keepassxc_16x16.png",
        "48": "icons/keepassxc_48x48.png",
        "64": "icons/keepassxc_64x64.png",
        "96": "icons/keepassxc_96x96.png",
        "128": "icons/keepassxc_128x128.png"
    },
    "browser_action": {
        "default_icon": {
            "16": "icons/keepassxc_16x16.png",
            "18": "icons/keepassxc_18x18.png",
            "19": "icons/keepassxc_19x19.png",
            "32": "icons/keepassxc_32x32.png",
            "36": "icons/keepassxc_36x36.png",
            "38": "icons/keepassxc_38x38.png",
            "64": "icons/keepassxc_64x64.png"
        },
        "default_title": "KeePassXC-Browser",
        "default_popup": "popups/popup.html"
    },
    "options_ui": {
        "page": "options/options.html",
        "open_in_tab": true
    },
    "background": {
        "scripts": [
            "common/browser-polyfill.min.js",
            "common/global.js",
            "common/sites.js",
            "background/nacl.min.js",
            "background/nacl-util.min.js",
            "background/client.js",
            "background/keepass.js",
            "background/httpauth.js",
            "background/browserAction.js",
            "background/page.js",
            "background/event.js",
            "background/init.js"
        ]
    },
    "content_scripts": [
        {
            "matches": [
                "<all_urls>"
            ],
            "js": [
                "common/browser-polyfill.min.js",
                "common/global.js",
                "common/sites.js",
                "content/ui.js",
                "content/banner.js",
                "content/autocomplete.js",
                "content/credential-autocomplete.js",
                "content/custom-fields-banner.js",
                "content/fields.js",
                "content/fill.js",
                "content/form.js",
                "content/icons.js",
                "content/keepassxc-browser.js",
                "content/observer-helper.js",
                "content/pwgen.js",
                "content/totp-autocomplete.js",
                "content/totp-field.js",
                "content/username-field.js"
            ],
            "run_at": "document_idle",
            "all_frames": true
        }
    ],
    "commands": {
        "fill_username_password": {
            "description": "__MSG_contextMenuFillUsernameAndPassword__",
            "suggested_key": {
                "default": "Alt+Shift+U",
                "mac": "MacCtrl+Shift+U"
            }
        },
        "fill_password": {
            "description": "__MSG_contextMenuFillPassword__",
            "suggested_key": {
                "default": "Alt+Shift+I",
                "mac": "MacCtrl+Shift+I"
            }
        },
        "fill_totp": {
            "description": "__MSG_contextMenuFillTOTP__",
            "suggested_key": {
                "default": "Alt+Shift+O",
                "mac": "MacCtrl+Shift+O"
            }
        },
        "show_password_generator": {
            "description": "__MSG_contextMenuShowPasswordGenerator__",
            "suggested_key": {
                "default": "Alt+Shift+G",
                "mac": "MacCtrl+Shift+G"
            }
        },
        "save_credentials": {
            "description": "__MSG_contextMenuSaveCredentials__"
        },
        "redetect_fields": {
            "description": "__MSG_popupRedetectButton__"
        },
        "choose_credential_fields": {
            "description": "__MSG_popupChooseCredentialsText__"
        },
        "retrive_credentials_forced": {
            "description": "__MSG_popupReopenButton__"
        },
        "request_autotype": {
            "description": "__MSG_contextMenuRequestGlobalAutoType__"
        },
        "reload_extension": {
            "description": "__MSG_popupReloadButton__"
        }
    },
    "web_accessible_resources": [
        "icons/disconnected.svg",
        "icons/help.svg",
        "icons/keepassxc.svg",
        "icons/key.svg",
        "icons/locked.svg",
        "icons/otp.svg",
        "css/autocomplete.css",
        "css/banner.css",
        "css/button.css",
        "css/colors.css",
        "css/define.css",
        "css/notification.css",
        "css/pwgen.css",
        "css/username.css",
        "css/totp.css"
    ],
    "permissions": [
        "activeTab",
        "contextMenus",
        "clipboardWrite",
        "nativeMessaging",
        "notifications",
        "storage",
        "tabs",
        "webNavigation",
        "webRequest",
        "webRequestBlocking",
        "https://*/*",
        "http://*/*",
        "https://api.github.com/"
    ],
    "content_security_policy": "script-src 'self' 'sha256-4nJ8uLezzRE3SiBFdkVN/uNwV9YTOGCqRXg6AvB5rCY='; object-src 'none'",
    "default_locale": "en"
}

**Comment by droidmonkey** [comment]
Thank you we are aware and there is a draft PR to convert to manifest 3

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc-browser/pull/1723
