### ISSUE TITLE
Hamburger menu in settings doesn't have any effect

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1734]
## Expected Behavior

I assume a menu should open.

## Current Behavior

![image](https://user-images.githubusercontent.com/1658949/192460298-36fa7626-b341-4f1d-bf95-97d232108def.png)
You click the icon in the top-left and nothing happens.

## Possible Solution

I don't know.

## Steps to Reproduce (for bugs)

1. Open the settings in Edge
2. Open the DevTools and slide the main content area to be small enough for the icon to appear
3. Click the icon

## Debug info

KeePassXC - Version 2.7.1
Edge Browser Extension: 1.8.2.2
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by varjolintu** [comment]
Good find! Already fixed it :)

**Comment by oliversalzburg** [comment]
Nice. Thanks :)

...now on to the _real_ issue :D

**Comment by varjolintu** [comment]
According to this the bug in Firefox should be fixed: https://bugzilla.mozilla.org/show_bug.cgi?id=1783972. Needs to be checked if that's really the case.
