### ISSUE TITLE
Unable to connect Edge to database

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1736]
## Expected Behavior

I want to use my KeePassXC with the Edge browser. It is working fine with Firefox on this computer, so I expect Edge to work as well.

## Current Behavior

The extension in Edge indicates: "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."

When I _reload_ the error changes to "Key exchange was not successful.".

## Possible Solution

- `"C:\Users\salzburg\AppData\Local\KeePassXC\org.keepassxc.keepassxc_browser_edge.json"` exists.
- `HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\` points to the JSON file.
- The `path` inside points to the file `C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe`, which exists and is executable.
- `keepassxc-proxy` is already running
- I looked into the calls being made with Process Monitor, but I couldn't see anything that would raise concerns.
- `ComSpec` points to `cmd.exe`

## Steps to Reproduce (for bugs)

This is a new computer I got for work. I installed KeePassXC and the Edge extension. It never worked.

## Debug info

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.3
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19044

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.18.1

**Comment by oliversalzburg** [comment]
It seems like https://github.com/keepassxreboot/keepassxc-browser/issues/1214#issuecomment-1041851453 has the solution to my case.

The group policy being mentioned there is also active on this machine. Which causes
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\NativeMessagingUserLevelHosts` to be set to `0`, which in turn causes the KeePassXC browser extension to not work.

I would ask that this be included in the troubleshooting guide or maybe even be detected proactively by KeePassXC itself if at all possible.

**Comment by varjolintu** [comment]
This seems like a similar issue: https://github.com/keepassxreboot/keepassxc-browser/issues/1401
