### ISSUE TITLE
My password is shown plaintext

### ISSUE THREAD

**Issue by xversion1** [keepassxreboot/keepassxc-browser#1737]
## Overview
I use Keepassxc extension on Firefox to login into Yahoo mail. After I filled the username using drop-down list Keepassxc produced, the _Next_ button showed my password of my account plaintext. I think there's a wrong detection of password field so I "Clear saved data" in Keepassxc extension and the _Next_ button doesn't show my password anymore. 
I think the password should be appear as ******* instead of plaintext so that in case the extension detects fields wrongly, there's no real danger of showing password to human eyes.
![Screenshot_20220928_094706](https://user-images.githubusercontent.com/40853683/192677816-6599dc81-3c7d-49e1-a297-bdb15191796f.png)

**Comment by varjolintu** [comment]
"Clear saved data" ? Have you set some Custom Login Fields for the login page? That shouldn't be necessary. I couldn't reproduce this .

Enable the debug logging from extension settings and see what input fields are detected when this happens?

**Comment by xversion1** [comment]
> 

I couldn't reproduce this as well. I tried a lot of settings, removed and re-added the extension several times so I don't think there's a trace of this bug left in my PC. That's why I didn't hope to fix the extension but somehow mark the password as ******** just in case any mistake happens. Don't know whether it's possible or not?

**Comment by varjolintu** [comment]
@xversion1 I think it's only possible if Custom Login Fields was used and for some strange reason that button has exactly the same path identification with the password input field.
