### ISSUE TITLE
Auto-submit is broken on certain sites (Microsoft login)

### ISSUE THREAD

**Issue by sbot50** [keepassxreboot/keepassxc-browser#1738]
~~Ok so, the "Automatically fill in single-credential entries." option ignores custom autotype sequences in keepass, and also ignores if its enabled at all.~~

## ~~Expected Behavior~~
~~1. Check if autotype is enabled
2. Use correct autotype sequence~~

## ~~Current Behavior~~
~~What? autotype options in the keepassxc program? what are those? never heard of them, lets just ignore they exist and always enable autotype on every site regardless of preference, and also ignore any custom sequences the user might have set.~~

## ~~Possible Solution~~
~~Just check if auto type is enabled first, and then if a custom sequence is set.~~

## ~~Steps to Reproduce (for bugs)~~

~~1. Setup a microsoft account with keepassxc
2. Enable the "Automatically fill in single-credential entries." in keepassxc-browser plugin
3. Either set a custom autotype sequence or change autotype to disabled in keepass.
4. (probably not necessary) close browser and reopen, just to make sure it has the latest data
5. Try logging in to the microsoft site.
6. See that it completely ignores preferences~~

## ~~Debug info~~
~~KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: Windows 11
Browser: FireFox~~

### ~~If any other information is needed, just tell me~~

# Edited version:
Autosubmit clicks the wrong button on Microsoft login.

## Expected Behavior
1. fill in credentials
2. Click next button

## Current Behavior
1. Fill in credentials
2. Click "more login options" button

## Possible Solution
Change the button clicked on the site in the code itself, or let us change the button clicked ourselves somehow?

## Steps to Reproduce (for bugs)
1. Setup a microsoft account with keepassxc
3. Enable the "Automatically fill in single-credential entries." in keepassxc-browser plugin
4. Try logging in to the microsoft site.
5. It clicks the login options button and you're stuck.

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: Windows 11
Browser: FireFox

## Edit
Maybe good to mention for anyone else having this issue, if you still want it to autofill but not auto-submit meaning it'll work fine go to KeepassXC-browser plugin settings, go to "Site Preferences", add microsoft's login url and then under the ignore tab set it to "Disable auto-fill" (and maybe also click username-only detection but it should do that automatically by default)

**Comment by sbot50** [comment]
Other than that the feature works perfectly fine everywhere else i tested it, pretty sure it just hates microsoft cause it sends you to the sign-in options screen, so i assume whaat the plugin is doing is {USERNAME}{TAB}{ENTER}

**Comment by varjolintu** [comment]
AutoType sequences has nothing to do with the extension. Use Custom Login Fields feature from the extension to achieve custom filling options.

**Comment by sbot50** [comment]
> AutoType sequences has nothing to do with the extension. Use Custom Login Fields feature from the extension to achieve custom filling options.

I fail to see how custom login fields are the solution here, it enters the information correctly both username and password (and also totp but you have to manually click that anyways) the problem is that it clicks the wrong button afterwards.

On the image, the green circled button is the one thats supposed to be clicked and the red circled button is the one that it automatically clicks.

The reason i brought up autotype is because the keepassXC-browser plugin (i assume) has full access to the database, so if it just used autotype instead of whatever its doing now then the whole problem wouldnt exist.

![oYppz6g](https://user-images.githubusercontent.com/54210646/193443603-bcd6c7b4-79ac-42c3-b4b3-fad15c5e81e9.png)

**Comment by varjolintu** [comment]
So the Auto-Submit here is broken, not the Auto-Fill? Microsoft sites should work without any tweaking, but of course the Auto-Submit bug must be investigated.

**Comment by sbot50** [comment]
> So the Auto-Submit here is broken, not the Auto-Fill? Microsoft sites should work without any tweaking, but of course the Auto-Submit bug must be investigated.

I suppose so, sorry for the confusion.
