### ISSUE TITLE
Key Exchange failure on Waterfox G5.0.1

### ISSUE THREAD

**Issue by Jelloeater** [keepassxreboot/keepassxc-browser#1742]
## Expected Behavior

Database connects and auto fills in Websites

## Current Behavior

When trying to connect extension, getting: Key exchange was not successful. Error in browser

## Possible Solution

Can try rolling back to previous version of Waterfox.
Plugin works fine on Firefox 105.0.2 (64bit)
Also works fine on Waterfox G4.1.5
Does NOT work on Waterfox G5.0.1

## Steps to Reproduce (for bugs)

1. Try and autofill website

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: MacIntel (Actually M1)
Browser: Mozilla Firefox 102.0 (Actually G5 5.0.1)

KeePassXC - Version 2.7.1
Revision: 5916a8f

Qt 5.15.2
Debugging mode is disabled.

Operating system: macOS 12.4
CPU architecture: arm64
Kernel: darwin 21.5.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by droidmonkey** [comment]
We don't support waterfox and, given that the extension works on the previous version, this isn't a problem with our extension. Please route a bug report to the waterfox team.

**Comment by Jelloeater** [comment]
I raised this w/ the Waterfox team.
https://github.com/WaterfoxCo/Waterfox/issues/2847
Hope they can help.
