### ISSUE TITLE
Use URL hash to determine if on page that should be filled or not

### ISSUE THREAD

**Issue by christophehenry** [keepassxreboot/keepassxc-browser#1745]
Some… *old school* sites still use the `#hash-part` of the URL as a router (to keep support on IE11, I suppose). Namely Synology's web manager. This part does not seem to be considered as relevant by `keepassxc-browser` to determine wheter or not to fill a form. This result in `keepassxc-browser` filling every `input` it can on every page of the site which is a bit annoying.

## Expected Behavior
If I specify `https://example.com/#/login` as a URL in KeepassXC, `keepassxc-browser` should fill form only when URL is `https://example.com/#/login`. Not `https://example.com/` and not `https://example.com/#/something-else`

## Current Behavior
The `#hash-part` is ignored by `keepassxc-browser`

## Possible Solution
In case this clashes with a current desired behaviour, this can be a per-site option clearly accessible somewhere.

## Steps to Reproduce (for bugs)

1. Create a KeepassXC entry for a site that doesn't use hashes as router and add a hash part 
2. Go to the login page (don't add the hash part)
3. `keepassxc-browser` should autofill the form even when the hash is not present

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.2.2
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Need to check this one what Qt does to the URL's. We remove fragments (URL parts at the end which start with `#`) from URL's for matching, but there's always a possibility that Qt detects those kind of paths as fragments.

**Comment by droidmonkey** [comment]
Fragments should only be acknowledged with best matching credentials enabled. Also we do not recommend you enable auto fill off forms from the extension.

**Comment by christophehenry** [comment]
> Also we do not recommend you enable auto fill off forms from the extension.

This causes problem especially for search inputs that performs some kind filtering. Then the extension always alters what's displayed.

**Comment by varjolintu** [comment]
This PR allows exact URL's and should solve the issue: https://github.com/keepassxreboot/keepassxc/pull/9835
