### ISSUE TITLE
Unable to connect to Firefox on Linux

### ISSUE THREAD

**Issue by chelmi00** [keepassxreboot/keepassxc-browser#1746]
When I try to connect to Firefox on my Ubuntu 22.04, it fails: "Key exchange was not successful."

## Expected Behavior
When I click on connect in the browser extension, a popup appears where I should write the name, and the database connects.

## Current Behavior
No connection happens, when I open the extension "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." (it is enabled), when I click on reload: "Key exchange was not successful.". I search in settings, connected databases: "No connected databases found."
This steps are independent whether database is locked or unlocked.

## Steps to Reproduce (for bugs)

1. Open Keepassxc app and Firefox
2. Click on Keepassxc extension
3. Click on connect

## Debug info
I don't think there are any console errors, but not sure, appreciated it if I was told how to make sure
KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.2.2
Operating system: Linux, Ubuntu 22.04.1 LTS
Browser: Firefox version 106.0 (installed with apt, not snap, and checked with _snap list_)

**Comment by droidmonkey** [comment]
Did you try our troubleshooting steps in the wiki? Also recommend you update keepassxc to 2.7.1

**Comment by chelmi00** [comment]
I have the 2.6.6 version because it is the latest on my apt. If it's recommended, I will figure out how to do it.
Have been checking the troubleshooting, and figured that I should mention that it works fine on my microsoft edge. Have been debugging too, and found the following from checking on common.global.js:
line: "async*keepass.reconnect@moz-extension://46df8a07-4455-4899-b35e-9362354461a7/background/keepass.js:757:43"
result: "keepass.js:757"

Also, in the console tab, there are some logs:
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:317:13]
[Error init.js:10] KeePassXC-Browser - Failed to connect: Unknown error [global.js:178:13]
[Error init.js:10] KeePassXC-Browser - No content script available for this tab. [global.js:178:13]
[Error keepass.js:757] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. [global.js:178:13]
[Error keepass.js:274] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. [global.js:178:13]
[Error keepass.js:880] KeePassXC-Browser - No content script available for this tab. [global.js:178:13]

**Comment by droidmonkey** [comment]
You can use the ppa, appimage, or flatpak distribution to get the latest version of KeePassXC.  Make sure you aren't using a beta or nightly version of Firefox.

**Comment by chelmi00** [comment]
I just did, version 2.7.1 installed. However nothing changed.
Yes, it is, but I searched and installed it without snap. So snap isn't the issue

**Comment by chelmi00** [comment]
![Here you can see that everything is as, I believe, it should](https://user-images.githubusercontent.com/80181207/196026727-8d154c28-7f84-4936-812d-3e9ecca16916.png)

**Comment by chelmi00** [comment]
I found a workaround, maybe not the best alternative, but fine with me: using the firefox-esr package rather than the firefox one
