### ISSUE TITLE
Password generator - Unable to receive password

### ISSUE THREAD

**Issue by DinizBortolotto** [keepassxreboot/keepassxc-browser#1747]
## Expected Behavior
When registering on a website we can use KeePassXC Password Generator and click on key symbol to get a new password generated from KeePassXC and put it directly on pass field of website.

## Current Behavior
When clicking on key symbol we are getting a pop-up that says: 
Unable to receive generated password. Is KeePassXC running and connected?

KeePassXC is, for sure, running and we are able to retrieve usernames, passwords and TOTP for all websites on database.

## Debug info
KeePassXC - 2.7.1
KeePassXC-Browser - 1.7.6
Operating system: Linux x86_64
Browser: Chrome/Chromium 106.0.0.0

![keepassxc_passgenerator_error](https://user-images.githubusercontent.com/4468840/196015121-46ad4b47-8104-4e14-a988-43458d54d6f3.png)

**Comment by droidmonkey** [comment]
Your browser extension version is over 2 years old. You need to update.
