### ISSUE TITLE
Browser extension killed by Edge update to Version 106.0.1370.52 (Official build) (64-bit)

### ISSUE THREAD

**Issue by rogercreagh** [keepassxreboot/keepassxc-browser#1749]
MS Edge on Linux (ubuntu 22.04) has just updated to Version 106.0.1370.52 (Official build) (64-bit)

The Keepassxc browser extension can no longer connect to the database

Keepassxc version 2.7.1 
Browser extension version 1.8.3

Clicking the extension icon in the browser gives
![Screenshot from 2022-10-25 12-59-21](https://user-images.githubusercontent.com/44980188/197767897-671f0ba3-0a46-44cb-b562-d9fe7f4eaba5.png)

Clicking reload gives "Key exchange failed"

The extension settings show
![image](https://user-images.githubusercontent.com/44980188/197768070-50b5be11-1c29-41c5-a9e8-878a65348735.png)

Clicking connect does nothing

KeePassXc setting - browser integration has Edge checked and advanced settings show:
![image](https://user-images.githubusercontent.com/44980188/197768678-1c7dca44-7984-41b7-8132-c07759b9b745.png)
which was working before the Edge update.

Tried uninstalling and reinstalling browser extension and restarting browser and keeppassxc in various orders - still the same

**Comment by varjolintu** [comment]
There's no possibility Ubuntu installed Edge as Snap during the update? What does `edge://support/version` say for the command line?

**Comment by varjolintu** [comment]
Let's keep the conversation inside one thread: #1751.
