### ISSUE TITLE
Can we please add addresses to Ignored Sites manually?

### ISSUE THREAD

**Issue by mfearby** [keepassxreboot/keepassxc-browser#175]
I would like to be able to add a site manually to the list of Ignored Sites (such as 'localhost') so that Chrome dev tools doesn't get filled with keepassxc-browser.js error messages.

## Expected Behavior
I can't get KeePassXC to show the "Never ask for this page" icon/button for 'localhost', it would be nice if this button was always visible or we could manually add addresses to Ignored Sites.

## Current Behavior
The "Never ask for this page" icon/button never seems to appear for pages that don't prompt you for credentials.

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 2.3.3
Operating system: Windows 10
Browser: Chrome 66.0.3359.181
Proxy used: YES

Thank you.

**Comment by varjolintu** [comment]
I'll do this to the next release.
