### ISSUE TITLE
support multiple URL for single entrty

### ISSUE THREAD

**Issue by ZenMasta** [keepassxreboot/keepassxc-browser#1759]
## Summary
I know that you can clone an entry and make references to the user/pass. But it would be nice to be able to add alternative URLS to a single entry. Perhaps via additional attributes.

## Examples
I have a bank and their home page is www.localbank.com
If you log in through the home page, it redirects you to www.localbankonline.com.

This may also work for accessing your router via local IP vs fqdn or public ip.

It's a minor convenience. And certainly cloning with references immediately provides a solution. But I thought this could be one of those random things that might not be too difficult to add.

**Comment by phoerious** [comment]
Go to the entry settings -> Browser integration -> Additional URLs.
