### ISSUE TITLE
Credential loading broken after attempting to pull non-existent credentials for website

### ISSUE THREAD

**Issue by botchedcode** [keepassxreboot/keepassxc-browser#1760]
## Overview
Regarding to closed issue 8706 and all of the other bug reports related to the broken browser integration in 2.7.3 unfortunately I have to report that the browser integration is still partially broken 2.7.4:

Whenever I enter a login form on a website for which I have no matching credentials stored in my opened an connected KeePassXC database, the browser integration is broken, doesn't matter if later I click in the username field, clicking the KeePassXC icon in the username field or using the contect menu -> "Fill Username and Password". Only the Auto-Type function works then. I need to close and reopen my browser to get the browser integration back working.

## Steps to Reproduce
Situation 1:

A.1.: open the browser, open website 1 with credentials stored in KeePassXC
A.2.: get the credentials with browser integration, login -> works
A.3.: open website 2 with credentials stored in KeePassXC
A.4.: get the credentials with browser integeration, login -> works
A.5.: repeat that as often as you like

Situation 2:

B.1.: open the browser, open website 1 *without* (!) credentials stored in KeePassXC
B.2.: browser integeration can't give you credentials -> correct
B.3.: open website 2 with credentials stored in KeePassXC
B.4.: try to get the credentials from browser integeration -> nothing
B.5.: browser integration is broken from now on
B.6.: need to restart the browser

## Expected Behavior
The browser integration should always give me stored credentials for any website - even after I loaded a website with a login form for which I do not have credentials stored.

## Actual Behavior
It does not longer give me credentials after there was loaded a login form without matching credentials stored in my KeePassXC database - until I close and reopen my browser.

## Context
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.3
Debugging mode is disabled.

Operating system: TUXEDO OS 1 (Kubuntu 22.04.1 LTS)
CPU architecture: x86_64
Kernel: linux 5.19.8-cw

**Comment by botchedcode** [comment]
No, I do not think so. I'm sure it is a KeePassXC problem, because this never happened with KeePassXC 2.7.1 and older versions.

While the version of keepassxc-browser extensions is still the same, this problem does not occur when using KeePassXC 2.7.1, it only can be provoked and reproduced with KeePassXC 2.7.4.

**Comment by varjolintu** [comment]
@botchedcode Can you test manually that the extension version 1.8.0 works? Or the branch in the PR that is linked to this issue?

**Comment by botchedcode** [comment]
> Sounds like an extension problem

No, I do not think so. I'm sure it is a KeePassXC problem, because this never happened with KeePassXC 2.7.1 and older versions.

While the version of keepassxc-browser extensions is still the same, this problem does not occur when using KeePassXC 2.7.1, it only can be provoked and reproduced with KeePassXC 2.7.4.

**Comment by botchedcode** [comment]
> @botchedcode Can you test manually that the extension version 1.8.0 works? Or the branch in the PR that is linked to this issue?

I did the some tests and can reproduced the following:

1.: started Firefox with **extension 1.8.3**, loaded website 1 (**with** matching credentials in KeePassXC database) and then website 2  (**without** matching credentials in KeePassXC database) -> browser integration **is broken** from now on
2.: started Firefox again, but now with **extension 1.8.0**, loaded website 1 (**with** matching credentials in KeePassXC database) and then website 2  (**without** matching credentials in KeePassXC database) -> browser integration **still works**
3.: updated extension from 1.8.0 to **1.8.3** in Firefox and restarted Firefox, loaded website 1 (**with** matching credentials in KeePassXC database) and then website 2  (**without** matching credentials in KeePassXC database) -> browser integration **is broken** again

Summary:

- the problem never occurs when using KeePassXC 2.7.1, no matter if using extension 1.8.3 or 1.8.0
- the problem does not occur when using keepass-browser extension 1.8.0
- the problem as described above occurs when using keepass-browser extension 1.8.3 with KeePassXC 2.7.4

**Comment by varjolintu** [comment]
@botchedcode Then I would assume the fix linked to this thread (1.8.3.1) also works for you.

**Comment by botchedcode** [comment]
Wow, this was extremely quick bug fix. Got automatic update to 1.8.3.1 in Firefox right now and I can report, that the problem has gone. Now I'm waiting for the update in Chrome Web Store to be completely happy. Many thanks :)
