### ISSUE TITLE
Error!Credentials cannot be saved or updated.

### ISSUE THREAD

**Issue by Delimer** [keepassxreboot/keepassxc-browser#1764]
## Steps to Reproduce (for bugs)

1. Login on site
2. A popup with a suggestion to save
3. Click "Save"
4. Popup - Error!Credentials cannot be saved or updated.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Win64
Browser: Chrome/Chromium 104.0.5112.124 YaBrowser/22.9.4.863 Yowser/2.5

**Comment by varjolintu** [comment]
What does the JavaScript console say if you open the Web Inspector?

**Comment by Delimer** [comment]
[Error banner.js:151] KeePassXC-Browser - Empty result from get_database_groups

**Comment by varjolintu** [comment]
- Do you have any groups in your database?
- Have you changed default group settings in the extension's options page?

**Comment by Delimer** [comment]
- Yes, I have groups
- No, I set option "Always ask where to save new credentials"

**Comment by varjolintu** [comment]
Does it work if you disable the ﻿"Always ask where to save new credentials" option?

**Comment by Delimer** [comment]
Now I try again set "Always ask where to save new credentials"  ant it works!

**Comment by varjolintu** [comment]
Strange. This needs to be reproduced somehow. So previously there were no default group (KeePassXC-Browser Passwords) in your database? And now it is there and the option works again?

**Comment by Delimer** [comment]
- After install extension, I connect to database and test fill credentials on site
- Then change settings and set  "Always ask where to save new credentials"
- Try to save new credentials and get Error
- Then unset "Always ask where to save new credentials" and set default group
- Try save and it work
- Then again set "Always ask where to save new credentials" and when try save credentials popup with groups

**Comment by varjolintu** [comment]
I can reproduce the error, but luckily the credentials are still stored to the Root group.

**Comment by varjolintu** [comment]
I cannot reproduce this with the latest version.

**Comment by varjolintu** [comment]
If you are truly using Yander Browser (I assume YaBrowser means it), we don't support it officially. Can you reproduce this with somet other browser?

**Comment by Delimer** [comment]
Yes it Yandex Browser. In Chrome browser I also take this problem.

**Comment by varjolintu** [comment]
I'm unable to reproduce this. The Root group always shows in the Credential Banner even with a new database.

**Comment by Delimer** [comment]
I try debug extension, but error no longer occurred.

**Comment by dreua** [comment]
Same error on Firefox, JS console says `[Error banner.js:82] KeePassXC-Browser - Empty result from get_database_groups`

How can I help debugging this? Otherwise I'll try the same workaround, but I'll wait a few days in case you want to get to the root of it. ("Always ask where to save new credentials" is a setting in the browser plugin btw, I spent some time searching for it in KeepassXC itself :facepalm: )

**Comment by dreua** [comment]
Can't reproduce anymore, probably vanished when I restarted the browser.
