### ISSUE TITLE
keepassxc addon icon in login field is often invisible

### ISSUE THREAD

**Issue by soredake** [keepassxreboot/keepassxc-browser#1766]
## Expected Behavior

Button should be visible.

## Current Behavior

Button is often invisible until i click on it (then bug disappears for the some time).
![изображение](https://user-images.githubusercontent.com/5204968/199768227-fe532904-f5d5-45f7-936c-e63af46ffb8e.png)

## Possible Solution

Fix this.

## Steps to Reproduce (for bugs)

1. Install firefox on windows 11
2. Go to some site with login fields
3. Icon will be invisible (maybe)

## Debug info

KeePassXC - 2.7.1
KeePassXC-Browser - 1.8.3
Operating system: Windows 11 Pro
Browser: Firefox

**Comment by varjolintu** [comment]
Not very helpful. What site is that? What other sites this can be reproduced?

**Comment by soredake** [comment]
@varjolintu it happens on all sites for me, there is no specific.

**Comment by varjolintu** [comment]
Any errors in the JavaScript console? Does the same happen with another browser?

**Comment by soredake** [comment]
When the bug returns i'll into console, and i'll try in another browser.

**Comment by soredake** [comment]
Nothing interesting in console, what i did to trigger this bug:
1) Gone to this page https://store.steampowered.com/login/?redir=&redir_ssl=1&snr=1_4_4__global-header
2) Icon is shown
3) I've pressed on icon in login field and entered my pin, keepassxc database was now unlocked
4) I reloaded the page
5) Icon is invisible, keepassxc-browser icon shows that it's still not connected to database (uses [this](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/icons/disconnected.svg) icon)
6) After i click on addon icon in header it now shows that it connected to database, reloading the page makes icon in login field appear again

Extensions knows that keepassxc is running so icon in login field is shown, but then after entering pin (in windows hello prompt) connection is lost (maybe?) so it makes icon invisible.

**Comment by soredake** [comment]
I've found MUCH easier way to reproduce this, i've just need to press "Lock database" button in addon menu, then icon becomes invisible, but still present as i can hover it.

**Comment by varjolintu** [comment]
Cannot reproduce this. After locking the database from popup, the icon still stays visible.

**Comment by soredake** [comment]
My firefox profile was broken in someway, closing.

**Comment by soredake** [comment]
After two days, the problem returned.
