### ISSUE TITLE
[Error ui.js:255] KeePassXC-Browser - NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.

### ISSUE THREAD

**Issue by Lcstyle** [keepassxreboot/keepassxc-browser#1767]
Sites that leverage stripe.com payment process/portal don't work.

## Expected Behavior
fields stay open for manual user input

## Current Behavior
The Stripe CC#, Expiration Date, and CVV Fields break, so users cannot enter details manually.

## Possible Solution
https://stackoverflow.com/questions/71300970/shadow-root-cannot-be-created-on-a-host-which-already-hosts-a-shadow-tree

## Steps to Reproduce (for bugs)
1. visit waldenlocalmeat.com
2. go through their subscription signup portal until you hit step 6 Payment

## Debug info
[Error ui.js:255] KeePassXC-Browser - NotSupportedError: Failed to execute 'attachShadow' on 'Element': Shadow root cannot be created on a host which already hosts a shadow tree.

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Win10
Browser: Chrome Version 107.0.5304.88 (Official Build) (64-bit)

**Comment by Lcstyle** [comment]
when i say the fields break it means they are blocked from user input.  
![ScreenShot-11-3-2022_6 49 31 PM](https://user-images.githubusercontent.com/1028272/199852243-9e2fb1c7-c10c-46dd-ad41-bc157326a478.png)

There is a message momentarily displayed "Warning!No saved custom login fields found." before the fields get locked out.

**Comment by Lcstyle** [comment]
please note that the element selector is selecting a very tiny element in this screenshot:
![ScreenShot-11-3-2022_7 25 03 PM](https://user-images.githubusercontent.com/1028272/199853867-49bbac3a-84cb-4b5a-af44-72f386b95391.png)

Which is an element inside the element selected in this screenshot.  (you must notice the color is darker than the other fields for the hovered or selected element).  I don't know if this makes a difference, but I thought I would point it out explicitly.

![ScreenShot-11-3-2022_7 24 53 PM](https://user-images.githubusercontent.com/1028272/199853868-db80002c-dd81-43ce-afca-8349447933e9.png)


![ScreenShot-11-3-2022_7 24 21 PM](https://user-images.githubusercontent.com/1028272/199853870-f7e44b33-ea58-4657-981f-890dc717d899.png)

**Comment by varjolintu** [comment]
It would be helpful to know some other site where this happens. Going through all those steps and filling information is a bit exhausting.

**Comment by Lcstyle** [comment]
> It would be helpful to know some other site where this happens. Going through all those steps and filling information is a bit exhausting.

https://dossier.substack.com/

type your email into the subscribe field and click the subscribe button.
on the subsequent page, notice immediately the same issue with keePassXC locking out a form field for a credit card number.
![ScreenShot-11-4-2022_6 26 53 AM](https://user-images.githubusercontent.com/1028272/199951367-559b69db-a882-4634-a5d1-965b5533661f.png)

Ignore this select any paying option, and click start free trial.
Notice the site complains your "Your card number is incomplete.".

![ScreenShot-11-4-2022_6 27 47 AM](https://user-images.githubusercontent.com/1028272/199951438-b3af5485-4e5b-4580-8865-4d0b33707e16.png)

**Comment by Lcstyle** [comment]
stripe is a payment portal processing b2b platform.
You can find any and all of their customers here:

https://stripe.com/customers/all

**Comment by varjolintu** [comment]
Do you have any Custom Login Fields for this (or any) site? I cannot reproduce the bug in Substack's page.

**Comment by Lcstyle** [comment]
Yes I do. The issue has been resolved when I removed them. Please close this ticket as resolved.
