### ISSUE TITLE
Keepass results in slowdown error on AWS calculator page

### ISSUE THREAD

**Issue by woj-tek** [keepassxreboot/keepassxc-browser#177]
After navigating to http://calculator.s3.amazonaws.com/index.html Firefox shows number of times that KeePass extension is causing a slowdown.

## Debug info

KeePassXC - 1.1.3
keepassxc-browser - 2.3.3.
Operating system: Mac
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
That page has over 2000 input fields which is causing the slowdown. I'll have to do some more optimizations to https://github.com/keepassxreboot/keepassxc-browser/pull/166.

**Comment by varjolintu** [comment]
I decided to put an internal limit to the script. If there are more than 100 inputs on one page, KeePassXC-Browser won't handle those at all. While that might not be the best solution, I'm quite certain that page with over 2000 input fields is not a "normal" one with login fields.

**Comment by woj-tek** [comment]
I would say that anything about 10 input fields doesn't classify as anything that KeePassXC-Browser should be concerned with :-) But if setting a limit of 100 solves the hiccup then that should be enough I guess.

Thanks! 👍
