### ISSUE TITLE
Firefox KeePassXC-Browser extension issue: "Cannot connect to KeePassXC"

### ISSUE THREAD

**Issue by nix-tux** [keepassxreboot/keepassxc-browser#1772]
Using KeePassXC and KeePassXC-Browser since many years on different distros and never had such a issue. After a fresh install of KDE Neon 5.26 the plugin doesn't work anymore.  The settings and configuration are correct so far. 

This workaround did not help: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

SOFTWARE/OS VERSIONS
**KeePassXC 2.7.4** (ppa: phoerius-ubuntu-keepassxc-jammyI
**KeePassXC-Browser** 1.8.3.1
**Firefox** 106.0.5 (ppa: org.kde.neon.net.launchpad.ppa.mozillateam / no snap; no flatpack) 
Linux/KDE Plasma 5.26
KDE Plasma Version: 5.26.2
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7

![org keepassxc keepassxc_browser json](https://user-images.githubusercontent.com/117588592/200182869-ff20a25c-2027-4200-8919-05ca46d4c95a.png)
![strace](https://user-images.githubusercontent.com/117588592/200183046-3d42b973-09eb-4cae-b165-9896d5a0eb9e.png)

Btw: Thanks a lot for your great work! - And for your help ...

Greatings from switzerland 
Daniel

**Comment by varjolintu** [comment]
Probably you checked these already from the troubleshooting guide, but just to make sure:
- Have you checked the socket path in  `$XDG_RUNTIME_DIR` that it has a symbolic link under the real socket under `$XDG_RUNTIME_DIR/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer/`?
- Is there Firejail or something else that could interfere?

**Comment by Zszywek** [comment]
I have the same problem and I have checked the troubleshooting. I use Firejail but it worked with it before as I have whitelisted the directory for the socket

**Comment by droidmonkey** [comment]
Whitelist the new sun directory under xdg run, ./app/org.keepassxc.KeePassXC

**Comment by Zszywek** [comment]
I tried that already, my firefox.local under ~/.config/firejail reads:
`whitelist /run/user/1000/app/org.keepassxc.KeePassXC`
Although I just caught an information while trying to run firefox throught hte console, that is:
`Warning: not remounting /run/user/1000/app/org.keepassxc.KeePassXC`.
May this be the culprit here?

**Comment by droidmonkey** [comment]
You forgot the trailing slash

**Comment by Zszywek** [comment]
I tried with the slash at the end but it didn't work. It turns out the problem is known for the Firejail team and they are working on making it work automatically. To make the thing work I'll leave the [link](https://github.com/netblue30/firejail/discussions/5444) for other people with a similar problem.
Thank you for trying to help anyway, keep up with a your work and have a nice day :)

**Comment by domker** [comment]
I have exactly the same problem, but under Arch Linux.
I also use Firejail and additionally PSD (profile-sync-daemon).
The problem occurred with **KeepassXC versions above 2.7.1**.

Operating System: Arch Linux
KDE Plasma Version: 5.26.3
KDE Frameworks Version: 5.99.0
Qt Version: 5.15.7
Kernel Version: 6.0.8-arch1-1 (64-bit)
Graphics Platform: X11
KeepassXC: 2.7.4-1
KeePassXC-Browser: 1.8.3.1

Adding "_whitelist /run/user/1000/app/org.keepassxc.KeePassXC/_" or "_whitelist /run/user/1000/org.keepassxc.KeePassXC_" to the local file does nothing either.

The last working version of KeepassXC is **2.7.1-1**
The difference I noticed between KeepassXC 2.7.1-1 and 2.7.2-1 and above is:

KeepassXC 2.7.1-1:
_/run/user/1000/org.keepassxc.KeePassXC.BrowserServer_
(**socket not symbolic link**)
additionally:
_/run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer_
(**also socket**)

KeepassXC 2.7-2-1 and above:
_/run/user/1000/org.keepassxc.KeePassXC.BrowserServer_
(**symbolic link to the socket below**)
_/run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer_
(socket)

From the level of the browser, the file is visible, but it cannot be accessed.

**Comment by droidmonkey** [comment]
You need to "noblacklist ${RUNDIR}/app"

**Comment by varjolintu** [comment]
Firejail section added to the troubleshooting guide.
