### ISSUE TITLE
Broken image in wiki

### ISSUE THREAD

**Issue by stefansundin** [keepassxreboot/keepassxc-browser#1774]
## Expected Behavior

There is an image that is broken on this page: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually#modify-the-native-messaging-json-script-for-chromium

## Current Behavior

Image is displayed like this:

![Screenshot 2022-11-06 at 20 52 55](https://user-images.githubusercontent.com/1991151/200229171-97e20172-a367-4be8-9678-5c038b50d1ed.png)

## Possible Solution

Upload the image somewhere reliable (you can clone the wiki and I think you can add images to that repository that way).

![Screenshot 2022-11-06 at 20 53 55](https://user-images.githubusercontent.com/1991151/200229318-436e698b-1379-4779-9087-567aa8630166.png)

**Comment by varjolintu** [comment]
Decided to remove the image and modify the text.
