### ISSUE TITLE
Compatibility: don't require a new version for EVERY MINOR VERSION

### ISSUE THREAD

**Issue by georgehank** [keepassxreboot/keepassxc-browser#1776]
Not sure where the fuckup is, but… I was happily using both browser ext and app, when, IN THE MIDDLE OF WORK, the browser ext stopped complaining about a new version.  2.7.3 to 2.7.4

WHY?

Can't you warn and keep working at least for a bit?  Is this really impossible, or is it because ********?

**Comment by phoerious** [comment]
You can turn off update checks if you don't want them, but 2.7.3 had bugs with the browser extension, so I highly recommend you do upgrade.
