### ISSUE TITLE
browser ext selectively losing db connection?

### ISSUE THREAD

**Issue by ZenMasta** [keepassxreboot/keepassxc-browser#1777]
Password autocomplete is inconsistently available. 

## Expected Behavior
I would expect to see the kp icon on all password fields for sites that I have added to my database.

## Current Behavior
There are some sites where the browser extension will not display the kp icon in the password fields, yet the icon is green in the browser toolbar, and other sites where everything works normally.

## Steps to Reproduce (for bugs)
I have tried this on 2 different pc's on the same network (db shared via cloud).
Both pc's seem to share the same issue on the same sites. 

One thing that I noticed which is odd, is on PC A, it doesn't know the kp version, which would make me think that it isn't connected to the database. But considering there are sites where it does work, that makes my theory invalid. 

I haven't been able to intentionally reproduce it. But closing and reloading the database on both seems to have put me back on track.

## Debug info
PC A
KeePassXC -
KeePassXC-Browser - 1.8.3.1
Operating system: Win64
Browser: Mozilla Firefox 106.0

PC B (no pun intended)
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Win64
Browser: Mozilla Firefox 106.0

**Comment by varjolintu** [comment]
What is the site? It's possible that the login fields are inside an iframe that's in another subdomain. One thing you could try is to change the entry URL to a simpler form, for example `https://subdomain.example.com/path` -> `https://example.com`.

**Comment by ZenMasta** [comment]
I suppose it's possible. But I don't think so. When I view the source of the page, there's not much there.
A few scripts in a subfolder and one script at a cdn.
https://www.convergepay.com/converge-webapp/#!/login

**Comment by ZenMasta** [comment]
Right.  have been using the KPH: attributes and it's been working fine for that field. I guess I'll have to report if it happens again. But no issues today, on both pcs.
