### ISSUE TITLE
Won't connect to database

### ISSUE THREAD

**Issue by NicWow** [keepassxreboot/keepassxc-browser#178]
## Expected Behavior

I expected this:
![image](https://user-images.githubusercontent.com/26805521/40881302-d6720864-6677-11e8-801b-d3aae13acef6.png)
and for the connect button to work.

## Current Behavior

I click "connect" nothing happens. Also the "settings" page is missing certain fields like browsers.
Reference:
![file](https://user-images.githubusercontent.com/26805521/40881350-25b3d5aa-6679-11e8-921d-f17643fd01e9.jpeg)

As you can see it looks different than listed on website. It doesn't even ask what web browser you use. 
Could the repository have an older version?

## Possible Solution

Has the repository not been updated yet?

## Steps to Reproduce (for bugs)

1. Download in TemplateVm (this is how we get apps in Qubes OS)
2. Add App (shouldn't matter another Qube Setting)
3. Delete AppImage (was trying to sync between Qubes/VMs and AppImage doesn't seem to be compatible yet so I am trying to switch to repository)
4. Open app then Restart Computer (shouldn't matter but could)
5. Open app
6. Create new database and import CSV
7. Finish import
8. Remove old database from extension
9. Try browser integration
10. (see image for details)
11. click connect 
## Debug info

KeePassXC - Downloaded it today so should be the newest one
keepassxc-browser - Re-downloaded today so shouldn't be a problem.
Operating system: Linux, Qubes OS to be more specific but I am running in Fedora AppVM so it should run same as in Fedora.
Browser: Firefox
Proxy used: Fire-wall only
Error Message: Only one I got was "Timeout or not connected to KeePassXC" in the extension.

**Comment by droidmonkey** [comment]
You need to update to v2.3.3...

**Comment by droidmonkey** [comment]
You can use whatever you want, but what you currently using is v2.2.x
