### ISSUE TITLE
Path error on FreeBSD

### ISSUE THREAD

**Issue by Peter2121** [keepassxreboot/keepassxc-browser#1787]
Chromium 103.0.5060.53 on FreeBSD 13.1-RELEASE
KeePassXC-Browser Version: 1.8.3.1
KeePassXC 2.7.1

Impossible to connect to database.

Following the troubleshooting guide, I found that `org.keepassxc.keepassxc_browser.json` is not installed in `~/.config/chromium/NativeMessagingHosts`, but in `~/chromium/NativeMessagingHosts`.

Symlinking the two folders has solved the issue.

**Comment by droidmonkey** [comment]
That would mean Qt on FreeBSD doesn't have a configuration directory defined or it is defined in your XDG environment variables as your home folder. https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/NativeMessageInstaller.cpp#L234

**Comment by Peter2121** [comment]
> That would mean Qt on FreeBSD doesn't have a configuration directory defined or it is defined in your XDG environment variables as your home folder. This is not a problem on other Linux distros. https://github.com/keepassxreboot/keepassxc/blob/develop/src/browser/NativeMessageInstaller.cpp#L234

No.

```
#elif defined(Q_OS_LINUX)
    if (browser == SupportedBrowsers::TOR_BROWSER) {
        basePath = QStandardPaths::writableLocation(QStandardPaths::GenericDataLocation);
    } else if (browser == SupportedBrowsers::FIREFOX) {
        basePath = QDir::homePath();
    } else {
        basePath = QStandardPaths::writableLocation(QStandardPaths::ConfigLocation);
    }
```

It just means that one more `#elif` should be added [https://doc.qt.io/qt-6/qtglobal.html#Q_OS_FREEBSD](https://doc.qt.io/qt-6/qtglobal.html#Q_OS_FREEBSD)

FreeBSD is not Linux.

**Comment by droidmonkey** [comment]
No it needs to be an OR FREE BSD
