### ISSUE TITLE
Question to troubleshooting wiki page

### ISSUE THREAD

**Issue by CarstenGrohmann** [keepassxreboot/keepassxc-browser#1788]
Quote:

> Also there should be a registry entry found in the following location(s):
>
> Chrome: HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\
> Chromium: HKEY_CURRENT_USER\\Software\\Chromium\\NativeMessagingHosts\\
> Firefox: HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\
> Vivaldi: HKEY_CURRENT_USER\\Software\\Vivaldi\\NativeMessagingHosts\\
> Tor Browser: HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\
> Edge: HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\

In my case, the directoy `HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\` exists but just contains a "(Standard)" (REG_SZ) item:

![image](https://user-images.githubusercontent.com/4849907/203485968-7c6f5f89-a00b-41d6-8c4c-9409efb48e9a.png)

Which entry is meant? Should only the directory exists or should it contains a individual entry?

Please clarify that point in the [wiki page](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by varjolintu** [comment]
There should be just `(Default)` under `HKEY_CURRENT_USER\\Software\\Microsoft\\Edge\\NativeMessagingHosts\\` and then the path set to `(Default)` variable under `\\org.keepassxc.keepassxc_browser` subfolder.

**Comment by CarstenGrohmann** [comment]
Both entries exists and set as you decribed. 

It would be great if you could clarify the section with these details.

Thank you!

BTW: In Windows 10, Task Manager also shows proxy processes, which makes checking easier, as Process Monitor is no longer necessary for this.

![image](https://user-images.githubusercontent.com/4849907/203496644-3ca88516-58dc-48e4-8bd3-ec27beaf8663.png)

**Comment by varjolintu** [comment]
@CarstenGrohmann Process Monitor is a great way to see where the browser reads the registry and tries to start the proxy. This is useful for situations where the proxy does not start and something is wrong. Task Manager is quite limited for that kind of problem solving.

**Comment by varjolintu** [comment]
Added the help text to wiki.
