### ISSUE TITLE
facilitate navigating 'save credentials?' banner by keyboard

### ISSUE THREAD

**Issue by KiaraGrouwstra** [keepassxreboot/keepassxc-browser#1789]
the extension offers the ability to:
> Show a banner on the page when new credentials can be saved to the database.

however, i haven't figured out how to navigate this banner without resorting to using the mouse.

## Expected Behavior
able to get by using the keyboard

## Current Behavior
'Configure shortcuts' lists nothing about the banner

## Possible Solution
either:
- able to Tab my way to the banner from the address bar
- keyboard shortcuts to navigate the banner as part of the existing/configurable shortcuts

**Comment by varjolintu** [comment]
This is already possible.
