### ISSUE TITLE
Have to reload site after database unlock

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#179]
## Expected Behavior

After a database unlock, it should work.

## Current Behavior

It only displays the icons (for password e.g.), but when you click into input fields, it does not show you a dropdown or so.

You have to actually reload the website – only then it does work.

## Steps to Reproduce (for bugs)

1. Lock database.
2. Reload website.
3. Unlock database.
4. Reconnect + Redetect fields.

## Debug info

 KeePassXC-Browser Version: 1.1.3

KeePassXC Version: 2.3.3 

Operating system:/Linux
Browser: Firefox
Proxy used: yes

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/pull/153 already fixes it. Just wait for the next release.
