### ISSUE TITLE
Source code does not include Transifex settings needed to build

### ISSUE THREAD

**Issue by bignose-debian** [keepassxreboot/keepassxc-browser#1790]
The source code does not include what a recipient needs to build the project.

This prevents building by a person who does not have a network connection, or whose computer cannot connect to the required online services, or who does not have accounts with the required online services.

    $ npm build
    
    > KeePassXC-Browser@1.8.3.1 build
    > node build.js
    
    Pulling translations from Transifex, please wait...

The build hangs indefinitely.

I assume this is because, as listed in https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

> Prerequisites
> […] Log into Transifex (e.g., with your GitHub account) […]

This causes the source code to be dependent on a Transifex account or GitHub account, in order to build. A person who has neither, or who cannot connect to those services for any reason, cannot continue the build according to the instructions.

Please ensure that a person who has the source code and the necessary build dependencies, can build the entire 'keepassxc-browser' from only the source code. (This is a requirement for people who wish to redistribute the work under GNU GPLv3.)

**Comment by bignose-debian** [comment]
One way to resolve this is to make the translation data available in this repository, so that a person who gets the source code has the translation data without needing another account to download it.

**Comment by bignose-debian** [comment]
Another way to resolve this is to ensure the build can continue even when there is no network connection: if there is no Transifex session available, continue without downloading any translations.

**Comment by varjolintu** [comment]
Building the sources is actually only needed when making a new release to the extension stores. The extension can be loaded directly to the browser without building it, although only the English translation is then up-to-date.

But sure, I can update the translation files to the repository.

**Comment by bignose-debian** [comment]
Thanks for responding promptly.

> Building the sources is actually only needed when making a new release to the extension stores.

That's assuming why people will want to build from source; there can be any number of reasons, and the GPL guarantees to any recipient that they can build from source no matter what their reasons.

An example: I would like to convince OS distributions to build the extension from source, which requires reproducible building from only source code, without any network connection.

Another reason: a person may want to test custom changes, and no need for a network connection.

> But sure, I can update the translation files to the repository.

Thank you.

**Comment by varjolintu** [comment]
Made a PR that includes an optional `--skip-translations` for the build script.

**Comment by droidmonkey** [comment]
>  the GPL guarantees to any recipient that they can build from source no matter what their reasons.

I just read the license and saw no such clause. Can you point to the clause you think specifies this? 

The GPL just requires that source code be conveyed. There is no guarantee that it can be built. Translations are not source code. Additionally, you are free to comment out the build step that pulls translations of you need to or pull them on your own and distribute. That is what the GPL guarantees.

We are happy to fix this but I want to understand where you got your opinion from regarding the GPL.

**Comment by bignose-debian** [comment]
> @bignose-debian wrote:
> > the GPL guarantees to any recipient that they can build from source no matter what their reasons.
> 
> I just read the license and saw no such clause. Can you point to the clause you think specifies this?

Thank you for engaging on this important issue.

The GNU GPLv3 requires of anyone redistributing the work (for example, me; or someone who wants to customise and redistribute; or someone who wants to package this work for an operating system; etc.), that what is conveyed must be the source corresponding to the built package.

> The GPL just requires that source code be conveyed. There is no guarantee that it can be built.

The official [FAQ for the GNU GPL](https://www.gnu.org/licenses/gpl-faq.en.html) clarifies this:

> you must supply the source code that corresponds to the binary. Corresponding source means the source from which users can rebuild the same binary.
>
> Part of the idea of free software is that users should have access to the source code for the programs they use. Those using your version should have access to the source code for your version.

So, that would include all the source for what ends up in the built package, including the build configuration and scripts and any other inputs like translated message files.

> Translations are not source code.

If they are part of what a recipient needs to modify the work and build it, then the GPL definition of "corresponding source for the work" includes those translated messages as part of the corresponding source for the work.

> Additionally, you are free to comment out the build step that pulls translations if you need to; or pull them on your own and distribute. That is what the GPL guarantees.

One problem there is that doing so fails to convey the corresponding source for the work as it was built. That's the aim of this issue: To resolve this problem by getting the corresponding source, including translated messages that end up in the built package.

I hope that helps?
> 
> We are happy to fix this but I want to understand where you got your opinion from regarding the GPL.
