### ISSUE TITLE
Support for Arc browser

### ISSUE THREAD

**Issue by devployment** [keepassxreboot/keepassxc-browser#1793]
## Expected Behavior

The browser extension should work with Arc, a Chromium based browser

Arc: https://arc.net/
Vendor: https://thebrowser.company/

Arc is currently in closed beta, behind auth-wall. I know, this is a no go for many people. But it would be awesome to have KeePassXC running in Arc. 

## Current Behavior

The extension cannot connect to KeePassXC. Chrome and Chromium are enabled in KeePassXC. Testing the extension in a regular Chrome installation works as expected.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/7137845/204641413-17242f69-6fe6-4a51-a14e-8cb3a117e6c5.png">

## Possible Solution

As I have currently no idea how this browser works, the only thing I can imagine is that there is some whitelisting involved, and Arc seems not to be known.

## Steps to Reproduce (for bugs)

1. Install Arc (I can provide invitations if needed)
2. Install extension
3. Try to connect to KeePassXC

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Apple M1 Pro, macOS Ventura 13.0.1 (22A400) 
Browser: Arc Version 0.77.2 (36015) Chromium Engine Version 107.0.5304.122

**Comment by droidmonkey** [comment]
You need to setup a custom browser in the browser integration settings of keepassxc. We don't generally support alt browsers, especially in beta.

**Comment by devployment** [comment]
Not exactly sure what to setup exactly. Will try to figure out. 

But seems like copying 

`~/Library/Application Support/Chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json` to 

`~/Library/Application Support/Arc/User Data/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json`

does the trick as well. Not sure if this is sufficient or everything. But at least it starts communicating.

**Comment by droidmonkey** [comment]
Setup the custom browser to point to `~/Library/Application Support/Arc/User Data/NativeMessagingHosts/`

Do this in the advanced browser settings.

**Comment by Jonhy75** [comment]
Hello, I setup the custom browser point in KeepassXC (~/Library/Application Support/Arc/User Data/NativeMessagingHosts/) but it's not working.

Thanks for your help
---

KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.7
Operating system: Apple M2 Pro, macOS Ventura 13.5
Browser: Arc Version 1.2.1 Chromium Engine Version 107.0.5304.122

**Comment by git-commit** [comment]
Seeing as arc is out of beta now and seems pretty established on macOS, maybe it's worth considering opening this issue again? Seeing as there's support for Tor Browser, Vivaldi, Brave and Edge, there already seem to be a lot of "alt browsers" in the list of integrations.
