### ISSUE TITLE
No fill in of username or password in browsers

### ISSUE THREAD

**Issue by Bladerunnerkc** [keepassxreboot/keepassxc-browser#1798]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Although all enabled to have Keypassxc fill in username and password, no fill in occurs. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Using chrome, extension loaded and enabled.
2. url captured and stored in entry, several different sites attempted. 
3. keypassxc appears to recognize the page as the icon appears next to the username. 
4. No autofill so attempted right click and selected fill username and password. No fill occured

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The username and password should fill in. 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
No fill in occurred. 

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows/Linux/macOS  windows 10
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon 
Windowing System: X11/Wayland

**Comment by varjolintu** [comment]
What is the site you are using?

**Comment by Bladerunnerkc** [comment]
There's some financial sites but two I would mention are the Home Again pet finder site and Paycom. None of the sites have filled in username or password. Each have indicated with the Keypassxc icon that the url was recognized, I believe. But none fill. This could really be some stupid user issue I am having but I just have had no luck with auto fill. I would prefer stupid user tricks actually LOL.

**Comment by varjolintu** [comment]
With Home Again something in the page prevents the Username Icon and Autocomplete menu to appear. However, you can still fill the credentials from the popup (use the toolbar icon) or from context menu with right mouse click.

With Paycom there seems to be a third field you must fill. For this you can use the Custom Login Fields to determine that field for your entry. In short, create a new attribute `KPH: Client Code` with a proper value to your entry and then use the Custom Login Fields selector from the extension popup. Select Username and Password fields, plus a single String Field for the new attribute.

**Comment by Bladerunnerkc** [comment]
When I try to right click to fill on either, I get no entries.

I am not sure what could be blocking the fill.

Is there something about Chrome that can prevent fill?

**Comment by varjolintu** [comment]
What is your entry URL? `https://homeagain.com` should work.

**Comment by Bladerunnerkc** [comment]
Yes, it should.

I entered that url, Keypassxc was acknowledged as it required me to 
enter my password to open it to allow access to the stored data. 
However, then entries were not entered into the fields either by 
autofill or right click.

**Comment by Bladerunnerkc** [comment]
I wondered about that as well.

I tried turning off Chrome's password manager but it did not change. 
Also, later today I will try disabling the protections on my firewall 
software that has additional protections for web interaction.

Since this is happening on all password entries in Keypassxc, it has to 
be something systematic.

I just wish that whatever is blocking it would jump up and say "I did 
that".  It doesn't block Chrome's password manager though.

**Comment by varjolintu** [comment]
You should disable Chome's password manager. It's not recommended to use multiple simultaneously.

**Comment by Bladerunnerkc** [comment]
Yes, I had done that. I have switched it back and forth as Keypassxc 
isn't really helping much now until this issue is resolved.

I have a ticket in to my protection software to see if there's something 
in their product that is blocking the autofill even though it doesn't 
block Chrome's Password Manager.

**Comment by ronnysteiner** [comment]
I have the same issue on a few different sites like https://www.icloud.com with Firefox (108.0.1) KeePassXC 2.7.4 and the KeePassXC-Browser Extension 1.8.4 on Windows 11 22H2. I also have 1Password and their extension installed. But disabling their extension did not help. The green KeePassXC icon appears in the username field and database is connected but nothing happens when I click on the icon or right click 'fill username and password'. Also clicking on the KeePassXC Browser extension and 'Redetect login fields' doesn't help either. Firefox' Password Manager is also disabled.
Any help would be appreciated.

**Comment by varjolintu** [comment]
@ronnysteiner For Apple, try setting `https://idmsa.apple.com` as your entry URL.

**Comment by ronnysteiner** [comment]
works perfectly, thank you!

**Comment by droidmonkey** [comment]
Maybe we should hardcode this as an exception @varjolintu
