### ISSUE TITLE
Keepass isn't detected by extention

### ISSUE THREAD

**Issue by starndust31** [keepassxreboot/keepassxc-browser#180]
## Expected Behavior
Keepass should connect

## Current Behavior
Keepass doesn't connect and I just see the message "Timeout or not connected to KeePassXC".

## Steps to Reproduce (for bugs)
1. Press extension icon in top right corner
2. Press Reload

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 1.3.3
Operating system: Win
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
Have you checked the [Browser Migration](https://keepassxc.org/docs/keepassxc-browser-migration/) document?

**Comment by starndust31** [comment]
Yes, I've also done everything on the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by varjolintu** [comment]
And everything was in order? Registry entries are found and they are pointing to the correct .json file, which points to a correct binary? Did you check what your browser's debug console log said? All this info helps.

**Comment by aaronvasic** [comment]
I'm also having this problem on NixOs. I have never developed firefox addons, and I can't find any sort of detailed error information so debugging is a little difficult for me.

**Comment by starndust31** [comment]
Ok, I checked the registry again. The first time I was just checking that the registry was in the right location. This time I checked what was in it and I realized it was pointing to the wrong location. It works now. Thanks.

**Comment by varjolintu** [comment]
Where was the registry pointing to?

**Comment by starndust31** [comment]
Well it pointed to an non-existent drive. You see, before I was using keepass xc portable but I decided to switch to the desktop version because my USB had met an unfortunate accident. The registry was just still pointed to where the usb was.

**Comment by varjolintu** [comment]
You can use the KeePassXC setting from Browser integration -> Advanced: `Update native messaging manifest files at startup` if you encounter these kind of problems again.
