### ISSUE TITLE
"No connected databases found"  Chromium Ubuntu 22.04

### ISSUE THREAD

**Issue by brianmichalk1** [keepassxreboot/keepassxc-browser#1800]
Summary:
Fresh install of Ubuntu 22.04
Fresh install of Chromium
Fresh install of Keepassxc
Configured KP for browser integration
Will not connect because of sandboxing issues.

I reinstalled for other non-related issues, and for this instance, I do not want to use the third party PPA that provides Chromium.  I want to use apt, appimages, flatpak, or snap install ... basically any method that is blessed by the maintainers.

How I've tested installing Chromium:
  18  apt install chromium
   19  apt install chromium-browser
  165  flatpak permission-set webextensions org.keepassxc_browser snap.chromium yes
  171  apt remove chromium-browser 
  174  snap install chromium
  178  vi /mnt/sdc1/home/michalk/.config/chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json 

How I've installed Keepass:
   60  apt install keepassxc
 6279  sudo apt remove keepassxc 
 6282  sudo snap install keepassxc

I have also tested running with the appImages.

KeePassXC-Browser Version: 1.8.3.1

So, I've tried several ways of installing.
I've tried to ensure the json file is in the correct location, and has correct path.
I've also run the keepassxc-snap-helper.sh script.

The json file:
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/mnt/sdc1/home/michalk/appimages/KeePassXC-2.7.4-x86_64.AppImage",
    "type": "stdio"
}

Can someone provide a concise set of instructions?  Doesn't have to be detailed, just tell me what methods of install I should be using, and which json I should be using, and which helper script I should be running, and what permissions need to be set for dbus.

**Comment by brianmichalk1** [comment]
That's a concise answer.  I thought I read somewhere that native messaging was now working.  Bummer.
Thank you.

**Comment by droidmonkey** [comment]
Yah the whole apt experience is terrible in Ubuntu 22. Not sure who's bright idea it was to replace previously native packages with snaps without changing the name or making it explicit decision.
