### ISSUE TITLE
Feature Request: Automatically save generated passwords

### ISSUE THREAD

**Issue by ForsakenHarmony** [keepassxreboot/keepassxc-browser#1801]
It would be nice to have an option to automatically save generated passwords in a temporary entry (including the current domain).

In an ideal world, keepassxc-browser would detect logins on every website, but we're not living in an ideal world and that's never going to happen.

I would rather have 2 entries for a website with the same password than none.

## Current Behavior
Assuming a login form isn't detected properly:

1. generate password for a website
2. click submit
    - you might already run into an issue here if the website wants you to enter the password twice and that's not detected by keepassxc-browser
4. keepassxc-browser doesn't detect the submission, the generated password is gone
    - if you copied it to the clipboard, it might have already been cleared
    - the password generator closes when you click apply, so that can't be used to recover either 
5. do password recovery, use workaround 3

## Workarounds
None of these are reasonable to be expected of a user.

1. don't click apply in the password generator
    1. copy the password to the clipboard instead of clicking apply
    2. paste it into the website form
    3. if it doesn't get saved, use workaround 3
        - caveat: you have to close the generator to do this, so copy to clipboard first
2. copy every password you generate to notepad in case it doesn't save (this is what I'm currently doing)
    1. in the generator you have to click copy to clipboard
    2. paste the password somewhere else
    3. go back to the generator and click apply
    4. if it doesn't get saved, use workaround 3
3. manually create every entry in keepass before using them in the browser

**Comment by droidmonkey** [comment]
#7297 and #6323

**Comment by ForsakenHarmony** [comment]
Bad links, but I guess it's supposed to be https://github.com/keepassxreboot/keepassxc/issues/7297 & https://github.com/keepassxreboot/keepassxc/issues/6323

Both are not necessarily duplicates of this, unless keepassxc receives the domain from the extension when you generate a password?
