### ISSUE TITLE
Extension only works if Firefox is launched AFTER KeePassXC

### ISSUE THREAD

**Issue by mitohund** [keepassxreboot/keepassxc-browser#1802]
## Expected Behavior
I would expect the extension to work no matter which application is launched first, Firefox or KeePassXC.

## Current Behavior

Everything works flawlessly if I launch Firefox AFTER KeePassXC. If Firefox is already running and I launch KeePassXC, I get:
- "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
- upon clicking on "Reload" I get: "Key exchange was not successful."

## Possible Solution

Restarting Firefox fixes this. But that's quite inconvenient and sometimes not possible.

## Steps to Reproduce (for bugs)

1. launch Firefox
2. launch KeePassXC
3. click on browser extension -> does not work

## Debug info

KeePassXC - 2.7.4 AppImage
KeePassXC-Browser - 1.8.3.1
Operating system: Linux - Debian Sid
Browser: Firefox 107.0.1

**Comment by varjolintu** [comment]
You don't need to restart your browser. Just reconnect to KeePassXC using the popup. Currently there's no way to do the reconnect automatically, but it's a known issue.

**Comment by mitohund** [comment]
What popup? I'm not getting one.

**Comment by varjolintu** [comment]
In your browser toolbar there's a KeePassXC icon. There's a Reload button.

**Comment by mitohund** [comment]
As described in the first post, this does not work for me:

> If Firefox is already running and I launch KeePassXC, I get:
>
> - "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
> - upon clicking on "Reload" I get: "Key exchange was not successful."

**Comment by varjolintu** [comment]
Read through the https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide and report your findings.

**Comment by mitohund** [comment]
OK so this took me a while (not a developer and not a Linux pro). Here are my findinds:

1. org.keepassxc.keepassxc_browser.json does exist in ~/.mozilla/native-messaging-hosts
2. path variable points to the AppImage
3. allowed_extensions is keepassxc-browser@keepassxc.org
4. keepassxc-proxy is running
5. strace result includes "[pid  8801] openat(AT_FDCWD, "/home/USERNAME/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>"
6. socket file exists under /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer
7. symbolic link is pointing to /run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer
8. There's no firejail folder
9. I tried debugging the extension. Not a developer in any way though. The only line that stood out to me on top of the previous error messages were these two: "[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist." and "[Error ] KeePassXC-Browser - 4: Cannot decrypt message"

Could this be related to me running the AppImage via AppImageLauncher?

**Comment by varjolintu** [comment]
AppImage should work normally. And because everything seems to be fine, I'd suggest creating a new temporary profile to Firefox and try the connection again. Does other browser's have the same issue?

**Comment by mitohund** [comment]
I tried a new Firefox profile. Did not help.

I'm quite convinced now that the issue lies somewhere between KeePassXC and AppImageLauncher. As soon as I uninstalled AIL, the issue went away. I filed a [bug](https://github.com/TheAssassin/AppImageLauncher/issues/552) with them. However, I am unable to tell if this is something KeePassXC-Browser or AppImageLauncher needs to fix.

**Comment by varjolintu** [comment]
Good to know that it's possibly related to AppImageLauncher. If you are able, switch to the PPA or Flatpak version instead.

**Comment by mitohund** [comment]
Good suggestion, thank you, will try the Flatpak version instead. Is that one built by the KeePassXC team or somebody else? I still don't quite understand how to verify who built a specific Flatpak. As in: can I trust a Flatpak I find on Flathub.

**Comment by droidmonkey** [comment]
We own the flatpak build repo

**Comment by mitohund** [comment]
Thank you again for the support here!
