### ISSUE TITLE
Disable overlay

### ISSUE THREAD

**Issue by proofy** [keepassxreboot/keepassxc-browser#1803]
## Expected Behavior
I would like to disable the overlay easy with a menu entry of the extension. 
Sometimes the overlay icons block the view of the content below. Then I would like to be able to simply switch off the overlay and switch it on again when I want it.

## Current Behavior
No easy way to disable overlay?

## Steps to Reproduce (for bugs)

1. reset password on homepages with Verification code (generated pictures)
![Screenshot 2022-12-14 at 12-02-35 OneHikID Login](https://user-images.githubusercontent.com/580891/207559737-9d2df8a9-84f8-43b3-96bf-846c25acf3e3.png)

**Comment by varjolintu** [comment]
You can disable the icons from the extension settings. In this case the verification code field is regognized as a TOTP field for some reason. Can you provide the HTML code of it? Thanks.

**Comment by proofy** [comment]
https://cloudsso.hikvision.com/login?service=https://www.hikvision.com/sso/login-redirect/

**Comment by varjolintu** [comment]
I would need an account for that. This is why I asked for the HTML code.

**Comment by proofy** [comment]
No, you can go to reset the password and the next page will be the problem, still if you haven't open or connected to a keepassx database

**Comment by varjolintu** [comment]
Ok. Got it.

**Comment by varjolintu** [comment]
Sadly this is not something that can be fixed easily. The TOTP input field is actually the correct length but right after loading the field size is changed and the verification code is appended to it. So the icon is just misplaced instead of showing a faulty icon.

**Comment by proofy** [comment]
That's what I thought. You can't react correctly to every wildly programmed login page. That's why I had the idea of simply switching off the overlay and not having to go to the trouble of switching it on and off via the settings.

**Comment by proofy** [comment]
so my ticket was a feature request. Why do you close it?

**Comment by varjolintu** [comment]
Because this feature is not going to be implemented. The extension monitors the icon positions on scroll and resize, but a support for every possible input field resize detection is maybe too much. In the worst case scenario those might not be event detected properly. It's a lot of work for a single site.
