### ISSUE TITLE
TOTP button is not working on upwork.com

### ISSUE THREAD

**Issue by ZenMasta** [keepassxreboot/keepassxc-browser#1804]
I can't click the ellipses icon to auto-fill the totp on this site. 
(https://www.upwork.com/ab/account-security/login)

I don't have issues logging into other sites today with kp and kp browser.
 
The only obvious difference between the other sites and this one is that upwork uses a 3-step login. 1st for username/email 2nd for password and 3rd for totp. I really don't think that should matter, but it's the only thing odd that I can really think about. FWIW the URL does not change during these 3 steps. 

## Steps to Reproduce (for bugs)
Try to log in at https://www.upwork.com/ab/account-security/login
Click the ellipses icon
[image](https://user-images.githubusercontent.com/823528/207910702-5b469381-2a67-4225-9c81-6dae9c9a2ad0.png)

## Debug info
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.3.1
Operating system: Win64
Browser: Mozilla Firefox 108.0

**Comment by varjolintu** [comment]
It has worked earlier, so gotta check what's changed.

**Comment by varjolintu** [comment]
I could not reproduce this. TOTP worked normally with an entry `https://www.upwork.com/ab/account-security/login` as the URL.

**Comment by ZenMasta** [comment]
Still encountering the same issue with Firefox and Microsoft edge. I wish there was a way to send more detailed information

**Comment by varjolintu** [comment]
It could help if you can provide the HTML code of the input field, or a Web Inspector screenshot showing the TOTP field and all the elements around the input. You can also enable the debug logging from the extension settings and see if there's any messages in the console when the TOTP field has appeared in the screen.

**Comment by ZenMasta** [comment]
![image](https://user-images.githubusercontent.com/823528/219089575-7e061802-38c5-450d-bb1a-6477841c3b33.png)
In Microsoft edge, I was only able to finally get the TOTP to populate when I clicked on the console tab in developer tools. I did a screen recording, I hope that helps. I can't test again in firefox, even with private tab because having just logged in on edge from this same IP, it's not asking for TOTP anymore.

https://youtu.be/oIH-fWlCj80

At :31 in my video I tried clicking the totp button several times, and again at 1:06.
Only after I opened the console and clicked again, did it load the code.

**Comment by ZenMasta** [comment]
Eh, I didnt mean to click the close button. 🙄

**Comment by varjolintu** [comment]
@ZenMasta That's a totally different issue. Seem the TOTP field is identified correctly. Just your TOTP is not filling properly? How have you setup it in your entry?

**Comment by ZenMasta** [comment]
How is it a totally different issue? "click the ellipses icon to auto-fill the totp on this site." is literally the issue and clearly demonstrated. But if I suddenly enable the developer tools and open the console tab it works. I haven't done anything special to setup the entry.

**Comment by varjolintu** [comment]
At 0:31 you tried to click the button when Element selection was on. The click was recorded only when another tab in the developer view was active. Nothing indicates that you _cannot_ click the icon. Just nothing happens when you click it?
