### ISSUE TITLE
Auto-fill not working for citi.com

### ISSUE THREAD

**Issue by mikeweilgart** [keepassxreboot/keepassxc-browser#1806]
I haven't been able to autofill my password at citi.com for at least three years or possibly longer, so this isn't a new issue, but I've just made sure I'm running the latest KeePassXC version and the issue persists.

I don't have site-specific settings for citi.com in KeePassXC.

I do have the "saved username" dropdown built into the website itself.

When I load the page, the KeePass fill credentials button appears and for just an instant it is green before it flashes to grey.  The icon then remains grey.

As the page finishes loading, the entry box for the password moves up perhaps a quarter of an inch from its initial rendered position and the KeePass icon stays where it initially appeared so it's offset downward a little from where it should be—but I don't think this part is relevant.

Pasting isn't disabled in the password entry box (though it used to be a couple years ago on this site) so I can search the entry in KeePassXC and then copy and paste from there to my browser (which is what I've been doing), but that's a bit of a pain compared to just clicking the button.  Maybe there is a fix I can apply here to make autofill work?  Also as a side note, I'm not really sure what the grey icon is supposed to indicate.

KeePassXC - 2.7.4
KeePassXC-Browser - 2.7.4
Operating system: MacOS 12.4
Browser: Firefox 102.5.0esr

**Comment by droidmonkey** [comment]
Have you tried setting custom form fields?

**Comment by mikeweilgart** [comment]
Yes, I tried custom fields, but the password field is already detected correctly.  Setting it as the "custom" password field and reloading the page produces exactly the same behavior as without any custom field setting.  (There is no username field since that's the dropdown menu, since I've visited the site before.)

**Comment by varjolintu** [comment]
Created a new entry with `https://citi.com` as the URL and had no problems when filling.

**Comment by mikeweilgart** [comment]
Oops.  :D  I fixed the URL on the password entries and granted permission and now it works fine.

I think I missed it because it never prompted me in the browser to add the password to KeePassXC, but that may have been because I was copy-pasting *from* KeePassXC to fill the passwords in the first place; I'm not sure.

**Comment by mikeweilgart** [comment]
The issue began showing up again, this time in another variation where no KeePassXC fill button would show up at all (gray or green).  Double checked URL and made sure everything was up to date and recently restarted, still no joy.

I finally cleared the citi.com related data from the browser cache, and now that I'm logging in *without* selecting the "remember my username on this computer" box on the webpage (and there is consequently no dropdown list for remembered usernames), things seem to be working fine.
