### ISSUE TITLE
cannot fill with mail.126.com

### ISSUE THREAD

**Issue by xmokay** [keepassxreboot/keepassxc-browser#1808]
## Overview
cannot auto fill mail.126.com username and password.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. add new entry with 
url: https://mail.126.com/
username: user
password: password
3. install KeePassXC extension to browser(firefox or chrome)
4. open https://mail.126.com/

## Expected Behavior
can fill username and password

## Actual Behavior
no effect

## Context
firefox build in password manager work fine.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

**Comment by varjolintu** [comment]
Use `https://passport.126.com` or just `https://126.com` as your entry URL.
