### ISSUE TITLE
Question: keyboard shortcut inconsistency between mac and linux? (Alt vs MacCtrl)

### ISSUE THREAD

**Issue by karlicoss** [keepassxreboot/keepassxc-browser#1809]
I got a macbook recently and noticed an inconsistency -- on my linux the extension is using `Alt+Shift+key` whereas on mac it's `MacCtrl+Shift+key`.
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/manifest.json#L81-L82

Alt on "standard keyboards" and Ctrl on "mac keyboards" are located at different spots, so I stumble when I switch between systems.

Of course it's possible to remap, so I'm just curious why the default is like this? I've seen [some other extesions use](https://grep.app/search?current=3&q=mac.%2AMacCtrl%5C%2BShift%5C%2B&regexp=true&filter[lang][0]=JSON) `Ctrl/MacCtrl` on linux/mac correspondingly and it feels like this makes more sense.
I can remap in the extension settings of course, but I'm also a developer of a couple of browser extensions. So hoping your answer would provide me with an insight into best practices for web extension hotkeys.

Thanks :)

**Comment by varjolintu** [comment]
The only reason is that many `Ctrl+Shift` shortcuts on Windows and Linux are already in use for the browser itself, or for other extensions and the OS/WM itself. So instead of a possible collision, those are mapped with `Alt` by default.
