### ISSUE TITLE
KeePassXC-Browser shows an update message on some pages

### ISSUE THREAD

**Issue by sakishrist** [keepassxreboot/keepassxc-browser#181]
## Expected Behavior
The expected behavior is to not show such message.

## Current Behavior
Please see the following video which demonstrates the issue as I believe that will be more suitable as an explanation:

(Also please look at the first comment about what extension might be in conflict with this one)

[![KeePassXC-Browser issue](https://img.youtube.com/vi/HNGmafC7eTA/0.jpg)](https://www.youtube.com/watch?v=HNGmafC7eTA)

Things to note:
* The update message that appears
* The extensions I have: AdBlock plus, Chrome Regex Search, Tampermonkey (no active scripts), Practical startpage, SelectorGadget, Message Templates, Ghostery, Reddit enchantment suite, Autofill rules, Strong Password Generator, Stream Keys
* The message does not appear every single load of the page, but it does so frequently.
* The error messages that appear in the console (One has been reported and is said to be fixed in the next release)

## Steps to Reproduce (for bugs)
Please see the video.

## Debug info
Log: [www.freelancer.com-1528358883006.log.zip](https://github.com/keepassxreboot/keepassxc-browser/files/2079497/www.freelancer.com-1528358883006.log.zip)
KeePassXC - 2.3.3
keepassxc-browser - 1.1.3
Operating system: Linux Mint 18.3
Browser: Chromium 65.0.3325.181 (Official Build) Built on Ubuntu
Proxy used: NO

**Comment by varjolintu** [comment]
There's one error message visible that is fixed in the next version. I'll inspect the conflict.
