### ISSUE TITLE
keepassxc-browser connection firefox snap

### ISSUE THREAD

**Issue by dom21121** [keepassxreboot/keepassxc-browser#1810]
Hello,

I'm on firefox snap version 108
Everything was working fine before the extension update to 1.8.4
Back to version 1.8.3, and it works again!
Isn't there a problem with version 1.8.4 of your awesome extension?
Thank you
cheers

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info
KeePassXC -
KeePassXC-Browser - 1.8.3.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 108.0

**Comment by varjolintu** [comment]
There's no major differences in the versions. This must be a Firefox Snap issue. Restart your browser after the update.

**Comment by dom21121** [comment]
I updated, restart firefox and it works with version 1.8.4
it's a fresh install, but I'm sure it didn't work. Going through the 1.8.3 update, it's ok, so perfect!
Thank-you for your prompt response.
Cordially
