### ISSUE TITLE
Cannot use one KeePass database per Chrome profile

### ISSUE THREAD

**Issue by sandromario** [keepassxreboot/keepassxc-browser#1811]
## Expected Behavior
I would like to use multiple Chrome profiles concurrently: one for work, one for private stuff. Each Chrome profile is connected to a dedicated KeePassXC database containing credentials for the intended use case. In this way, I cannot accidentally use work credentials outside of working hours.

I was expecting both databases to be available concurrently after unlocking them; more concretely: I expect database 1 to be available in Chrome profile A, and database 2 to be available in Chrome profile B, without me having to interact with KeePassXC any more.

## Current Behavior
The relevant database is only available in keepassxc-browser if the relevant database's tab in KeePassXC is currently active. Otherwise I only see messages such as "KeePassXC-Browser has not been configured..." (if the database on the active tab is already unlocked) or "Database not opened" (if the database on the active KeePassXC tab has not been unlocked).

## Possible Solution
None that I can think of.

## Steps to Reproduce (for bugs)

1. Create two Chrome profiles A and B.
2. Connect each profile to its own KeePassXC database (let's call them C for A and D for B).
3. Open Chrome with profile A.
4. In KeePassXC, navigate to tab representing database D. Optionally, unlock the database.
5. Observe the problem described above.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Mac
Browser: Chrome

**Comment by sandromario** [comment]
It should; but it's not, although I have the option active.

**Comment by sandromario** [comment]
The issue is that KeePassXC in Chrome profile A detects that database D has not yet been connected with profile A (which I do not want!), and prompts me to add a new connection. But I only want to keep using database C with profile A (already connected).

**Comment by sandromario** [comment]
So I guess the feature I would need in KeePassXC-Browser is something like "ignore further databases that are currently open in KeePassXC but have not been connected yet".

**Comment by varjolintu** [comment]
Let's mark this a duplicate for: #1275.

**Comment by sandromario** [comment]
Thanks, this seems to be related. Any intuition on how it will take to finish the work you have on the branch? Thanks and all best.

**Comment by varjolintu** [comment]
Cannot say anything about the estimate yet.
