### ISSUE TITLE
Error!Credentials cannot be saved or updated.

### ISSUE THREAD

**Issue by isp** [keepassxreboot/keepassxc-browser#1813]
Steps to Reproduce (for bugs)

    Login on site
    A popup with a suggestion to save
    Click "Save"
    Popup - Error!Credentials cannot be saved or updated.
    Web console shows:  [Error banner.js:151] KeePassXC-Browser - Empty result from get_database_groups

Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 108.0|

This seems to be the same as [Issue #1764 ](url), although when I disable and enabling "Always ask where to save new credentials" does not do anything. Uninstalling KeepassXC-Browser seems to work for the first credential being saved, then after that it will no longer work. 

This is happening on 2 devices (both linux mint and firefox), database is stored in dropbox folder.

**Comment by varjolintu** [comment]
I haven't been able to reproduce this error, even if it has been reported multiple times. If you can reproduce it every time with your steps, it could be helpful to debug the extension and figure out where the exact error happens. The correct place is: https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/banner.js#L152

**Comment by isp** [comment]
@varjolintu Sure I can help do that. I'm unsure what you mean by the correct place or what I should do with the URL you sent.

**Comment by isp** [comment]
@varjolintu any direction would be great. I can confirm this happens 100% of the time across both devices which makes KeepassXC-Browser unusable.

**Comment by varjolintu** [comment]
Debug the content script on the browser https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

**Comment by varjolintu** [comment]
Does it matter if you enable Developer Mode in the extension page?

**Comment by isp** [comment]
@varjolintu The instructions in the Troubleshooting guide are out of date, the about:debugging has been updated is there is no longer an "Enable add-on debugging". The only difference I see see is on no pages and no where does KeePassXC-Browser load in sources unless I go to "about:debugging" and inspect KeePassXC-Browser, where keepassxc-browser.js is not present.

**Comment by varjolintu** [comment]
The scripts are visible when you debug the content scripts. That wiki page also describes how to do that.

**Comment by isp** [comment]
I'll just use another solution. Thanks!

**Comment by varjolintu** [comment]
As you wish. I could've helped more if this error would've been easier to reproduce. Good luck for your search.
