### ISSUE TITLE
Why is there a lock on the icon?

### ISSUE THREAD

**Issue by dark-passages** [keepassxreboot/keepassxc-browser#1814]
## Expected Behavior

I understand that the lock means that KeePassXC will not enter any data on the webpage. 
But my question is always "Why?"
I know it's modern to hide as much information from the user, NEVER let them know something went wrong, especially don't tell the user the reason why. So hoping the developers of KeePassXC have a different opinion about that. 

## Current Behavior

I opened the desktop app and filled in my password, the desktop app is running fine.
The plugin in the browser does not show a lock in the plugin bar
But the icon on the webpage shows a lock, but WHY?

## Possible Solution

Always hoping to see a popup message when I hover my mouse over the icon or when I click on it. 
Does not have to be the icon used in the webpage (I can imagine it's hard to add extra code that plays nice with all websites, but the icon in the toolbar of the browser should be able to tell the user why it will refuse to fill my data on the page.

## Steps to Reproduce (for bugs)

1. If only I knew WHY it's not working I might be able to write down these steps.
2. Open desktop app and enter password correctly.
3. Open a webpage that has a password field and usually works fine. In my case it was miro.com where I tried to open a board that is password protected. The exact URL is https://miro.com/app/board/uXjVPKXUJ_k=/ 
4. 

## Debug info

KeePassXC-Browser Version: 1.8.4
KeePassXC Version: 2.7.4
Operating system: Win
Browser: Brave

**Comment by varjolintu** [comment]
The icon has three different states:

1. Green icon means your active database is open and there are credentials to fill.
2. Gray icon means your active database is open but no credentials are found for the site.
3. Lock icon means your active database is locked or not connected to KeePassXC.

If the page shows a lock icon but the toolbar icon doesn't maybe the database state didn't update correctly to the web page side. Also, the toolbar icon has no gray state. It's either green or locked.

It's unclear what the error here actually is. Could you clarify it a bit?

- Different icon on the page and toolbar?
- Cannot fill credentials?
- Feature request to add popup/hover messages on icons?
