### ISSUE TITLE
After closing and reopening of KeePassXC the Firefox plugin dose not connect to database automatically

### ISSUE THREAD

**Issue by GitHubinatrix** [keepassxreboot/keepassxc-browser#1819]
Up to updating to **_Firefox 109.0b9_** (64-bit) everything was working A-OK. But now If I close KeePassXC [as I use only one database] and the reopen it [be it right away or after reset of system] Firefox is unable reestablish connection with it by itself. And thus I need to go to icon of the KeePassXC-Browser plugin and click the **_Reload_** button

If I close Firefox instead of KeePassXC and reopen it, then surprisingly I do not have to _**Reload**_ the plugin, as the browser reconnects with the still running database

I am using KeePassXC 2.6.6 on Windows 10 Enterprise 20H2 19042.746 x64

**Comment by Lcstyle** [comment]
I am using 2.7.4, in both chrome and firefox the behavior is the same.

**Comment by varjolintu** [comment]
The automatic reconnect has been disabled for some time, so this behavior is expected. Maybe you had the option enabled and for some reason the extension did not disable it.

So it's preferred to open KeePassXC before your browser. You'll have to reconnect it if you do it another way around.

**Comment by Lcstyle** [comment]
this presents a usability pattern conflict.  For example, when the host os goes into sleep, both the browser and keepass are running.  However keepass is locked, and browser is disconnected.  @varjolintu what you are suggesting is that keepassXC should be unlocked first.  However, this does not restore the browser connection.  You would still have to click the browser icon, click reload, then click reopen.

What I am suggesting is, when user interacts with keepass in any way, for the auto-reload/auto-reconnect to happen automatically, to avoid repeatedly clicking reload, then reopen, then enter credentials, it maybe would be best to go -> (auto reload, auto-reopen) and user would only see enter credentials dialog.

**Comment by varjolintu** [comment]
@Lcstyle This is a known issue and we are trying to solve this by implementing an automatic reconnect to the proxy itself. This is still under work though. Some problems on the way.

**Comment by GitHubinatrix** [comment]
After recent updates of Firefox I once again do not have to re-connect to my database- they stay in sync

As for using latest version uf KeePassXC: some time ago I tried using **_2.7.4_**, but I could not connect to my database at all

And so unless this problem of having to re-connect comes back, I am not updating my KeePassXC

**Comment by GitHubinatrix** [comment]
After updating to **_KeePassXC 2.7.4 Portable_** I did manage to connect my database with _**Firefox**_ [currently version _**110.0**_]

And even before this it was working much better- but nevertheless every now and then I need to make a re-connection from within the web-browser. And I do not see a pattern in this, nevertheless now less often occurring, ill-behavior

**Comment by varjolintu** [comment]
@GitHubinatrix There's no automatic reconnect in the current extension. Please check your Firefox install.

**Comment by droidmonkey** [comment]
This is not how our software works. It is almost certainly something unique with your computer. It is likely a firejail or similar setup you have made.

**Comment by droidmonkey** [comment]
Sorry this issue is specific to the auto connect option which is still experimental. My mistake.

**Comment by varjolintu** [comment]
@tenzap No news or fixes yet. There are multiple issues why this isn't solved yet.
