### ISSUE TITLE
Unable to use KeePassXC-Browser

### ISSUE THREAD

**Issue by HDInfautre** [keepassxreboot/keepassxc-browser#1821]
Hello
A long time ago, everything worked perfectly.
Now I have to copy/paste the username and password by hand to connect to a website.
I upgraded to the latest version of KeepassXC with a blank Ubuntu 22.10 installation.
I use Firefox SNAP (v108 now) for ease of use.
I have tried different versions of keepassXC (appImage preferably, then Snap).
I'm desperate; what do I need to do to use KeePassXC-Browser v1.8.4 properly with KeePassXC on Ubuntu?

Regards

**Comment by HDInfautre** [comment]
I didn't see the magic KeePassXC-Browser Helper Script :-)
https://keepassxc.org/download/#linux

**Comment by varjolintu** [comment]
Firefox Snap has been already resolved: https://github.com/keepassxreboot/keepassxc-browser/issues/1426.

See
