### ISSUE TITLE
Doesn't work with https://connect.garmin.com/signin

### ISSUE THREAD

**Issue by ardabro** [keepassxreboot/keepassxc-browser#1824]
1) Correctly navigates to KeepassXC login window when database is locked
2) Correctly discovers user/password fields
3) Icons key icons inside user/password fields remain grey (inactive) and keyboard shortcuts don't work as well.
4) Password generator keyboard shortcut brings the generator popup but it seems to be "embedded" in the site's login dialog box and it is visible only partially.

**Comment by droidmonkey** [comment]
You need to set your entry's URL to: https://sso.garmin.com

**Comment by ardabro** [comment]
Nope. Changing the URL doesn't help at all

**Comment by droidmonkey** [comment]
Worked perfectly for me, make sure you aren't hiding the entry from the browser extension and also make sure you haven't declined sending the details.
