### ISSUE TITLE
Cannot connect to KeepassXC in Firefox

### ISSUE THREAD

**Issue by hirseboy** [keepassxreboot/keepassxc-browser#1829]
## Current Behavior
Installed Keepass via "sudo apt install keepassxc"
Installed KeepassXC Browser Extension in Firefox
Activated Browser support in KeepassXC
Cannot find KeepassXC in Browser

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 108.0

**Comment by hirseboy** [comment]
KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Diagnosemodus ist deaktiviert.

Betriebssystem: Ubuntu 22.04.1 LTS
CPU-Architektur: x86_64
Kernel: linux 5.15.0-58-generic

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

Kryptographische Bibliotheken:
- libgcrypt 1.9.4

**Comment by varjolintu** [comment]
Duplicate of: https://github.com/keepassxreboot/keepassxc-browser/issues/1426
