### ISSUE TITLE
Can't connect browser to KeePassXC (not Snap!)

### ISSUE THREAD

**Issue by pludi** [keepassxreboot/keepassxc-browser#1830]
After the upgrade to Firefox 109 (**not** Snap, `.deb` from the Mint package repos) the browser extension didn't connect to an open database anymore. Attempted to fix by removing the connection & reconnecting.

## Expected Behavior
Going into KeePassXC browser add-on settings, "Connected Databases", clicking "Connect" I'd expect a connection dialog to pop up.

## Current Behavior
Nothing happens

## Steps to Reproduce (for bugs)
1. Update from Firefox 108 to 109
2. Remove all connection keys for the browser
3. Try to reconnect

## Debug info

KeePassXC - 2.7.4, installed via `apt`
KeePassXC-Browser - 1.8.4
Operating system: Linux (Mint 21.1)
Browser: Firefox 109

**Comment by pludi** [comment]
Same issue with Chrome 109.0.5414.74 with a fresh install of the browser extension.

**Comment by varjolintu** [comment]
And what are your findings from the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)? If you encounter such strange problems with Firefox update, you should restart KeePassXC and Firefox just in case, and make sure `keepassxc-proxy` process is also killed.

I've seen some other reports too concerning Firefox update 108 -> 109 with Linux. It's highly possible that the Firefox update has done something strange to Native Messaging or extension handling. Can you try to downgrade?

As for Chrome, does it run as Snap/Flatpak etc?

**Comment by pludi** [comment]
Restarting Firefox or KeePassXC on it's own did not change anything, closing & restarting both re-enabled functionality.

Chrome installed as `.deb` from the official Google repos.

Mint doesn't support Snaps in any capacity.
