### ISSUE TITLE
Icon has the wrong index value and is always displayed in a TAB system.

### ISSUE THREAD

**Issue by enerspace** [keepassxreboot/keepassxc-browser#1833]
## Expected Behavior

The icon should be delivered on the same level as the input field. So the index value must be read and stored accordingly in the source code.

## Current Behavior

If you enable the option: "Enable icons for username fields." in the KeePassXC Browser Extension for Chrome, the icon will always be displayed in a TAB system, for example Bootstrap. 

First Tab:
![image](https://user-images.githubusercontent.com/40614728/214303965-4cda4320-ae4f-4644-a064-ac32860ed83d.png)

Second Tab:
![image](https://user-images.githubusercontent.com/40614728/214303794-7867e061-ef39-46ba-bb55-e86cfa6826fd.png)

## Possible Solution

Read out the index values of the input field in question. 

## Steps to Reproduce (for bugs)

Sorry, I can't give an example of this for privacy reasons.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
Still, some kind of example would be nice.

**Comment by varjolintu** [comment]
Thanks. I got it fixed.
