### ISSUE TITLE
Entered password should be observed only on the actual URL

### ISSUE THREAD

**Issue by enerspace** [keepassxreboot/keepassxc-browser#1834]
Preface: This problem has already been discussed here several times. But I have to open a new thread about it, because in my opinion this is a design error. You could use the plugin more effectively with the right regex setting. Unfortunately, you can not use the plugin at all full extent at the moment. The function of the plugin: "Automatically fill entries with individual credentials" could be used more effectively.

## Expected Behavior

If a password has been entered for the page: https://www.domain.com/login , the password must not be played out on the subpages. For example, in a form at https://www.domain.com/register .

## Current Behavior

At the moment the password is valid for each URL of the respective domain.

## Possible Solution

Introduce a new regex or set the parameter: KeePassCS Browser Settings customize: {"Allow":["www.domain.com/login"]

## Steps to Reproduce (for bugs)

Known behavior.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
This is actually a duplicate for a KeePassXC issue: https://github.com/keepassxreboot/keepassxc/issues/4509
