### ISSUE TITLE
Completing arbitrary fields

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc-browser#1837]
## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 102.0

Hello, could you add support to complete arbitrary fields like credit card numbers and similar things? Actually Firefox could autocomplete that itself, but 1st I don't get this working and 2nd after moving all password store out from Browsers and their clouds into my own key store I would also like to keep other sensitive data like credit cards there.

You could provide completion for arbitrary fields using advanced attributes in Keepass.
Currently I only see in the context menu of an edit fields, to "save credentials" or "fill password only".

**Comment by varjolintu** [comment]
This is tracked here: https://github.com/keepassxreboot/keepassxc/issues/863.

For extra fields you can user attributes, but those are entry-specific.

**Comment by Massimo-B** [comment]
Thanks. The referenced ticket explains how to store in Keepassxc. Custom attributes are possible there. But finally I need to get them completed inside the browser anyhow which keepassxc-browser is responsible for.

**Comment by varjolintu** [comment]
There's already this as work-in-progress: https://github.com/keepassxreboot/keepassxc-browser/pull/1614
