### ISSUE TITLE
Firefox & Chrome not loading + trgging an Anti-Malware Alert

### ISSUE THREAD

**Issue by shadowcyberdeck** [keepassxreboot/keepassxc-browser#1839]
Edit: disregard

**Comment by droidmonkey** [comment]
What regressive anti malware software is your company using?

**Comment by shadowcyberdeck** [comment]
> What regressive anti malware software is your company using?

We utilize the enterprise version of Sophos.

**Comment by varjolintu** [comment]
You'll probably have to make an exception for `keepassxc-proxy.exe`.
