### ISSUE TITLE
Readonly input boxes are filled with credentials

### ISSUE THREAD

**Issue by oliversalzburg** [keepassxreboot/keepassxc-browser#1840]
## Expected Behavior

I'm on OWA, trying to change the password for my account. I see this form:

![image](https://user-images.githubusercontent.com/1658949/214850864-c858730a-c61d-4758-918b-c37930d845cc.png)

KeePassXC offers to have credentials auto-filled here, which seems convenient enough to have my current password entered there. When I click the KeePassXC icon, I would expect my current password to be filled.

## Current Behavior

When I navigate to the form for the first time, my user name is already filled in and the textbox is readonly.

When I click the icon, my current password is filled in, but it also replaced the `Domain\user name` part in the readonly text input above it.

I'm not sure if this is even a problem, but I log in on the page with `user@domain.tld` and this input box displays/expects `domain\user`, which might be conflicting.

## Possible Solution

Don't change values already present in readonly text inputs.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win64
Browser: Chrome/Chromium 109.0.0.0

**Comment by pdinc-oss** [comment]
This breaks other sites. E.g. Dell iDRAC v9
