### ISSUE TITLE
Unable to connect Firefox KeepassXC-Browser extension to Keepassxc DB

### ISSUE THREAD

**Issue by Acsigen** [keepassxreboot/keepassxc-browser#1843]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run the helper script to enable communication between Firefox Extension and Keepassxc DB
2. Close the browser as instructed
3. Click the connect button from the Firefox Extension and nothing happends

## Expected Behavior

I should be able to connect the Firefox extension to Keepassxc DB

## Actual Behavior

Nothing happends

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: 7729648
Distribution: Snap

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.10
Desktop Env: Gnome
Windowing System: X11

**Comment by droidmonkey** [comment]
Did you attempt to search for a similar issue (there are hundreds)  or read the troubleshooting guide in this wiki and as linked on the extension pop up?

**Comment by varjolintu** [comment]
Check the pinned issue about Ubuntu Snap: https://github.com/keepassxreboot/keepassxc-browser/issues/1426

**Comment by Acsigen** [comment]
It seems that there are multiple related issues to this one.
