### ISSUE TITLE
Better support for installing browser extension manually, not from extension store

### ISSUE THREAD

**Issue by TomasRiker** [keepassxreboot/keepassxc-browser#1845]
One reason for preferring KeePassXC over LastPass, 1Password etc. is that it isn't cloud-based, so there's no risk of a big hack potentially leaking millions of vaults, like it happened to LastPass.

But as soon as one installs the KeePassXC browser extension from the Chrome/Firefox extension store, one exposes oneself to exactly that risk: If some hacker gains access to a developer's machine (by whatever means: hacking, extortion, bribery, ...), he can upload a malicious update for the browser extension that will automatically be installed on thousands of machines, since browser extensions installed from the extension store are updated automatically. That malicious update could secretly steal all passwords and send them to the hacker.

If one wants to reduce that risk, one should install the browser extension manually, not from the extension store (and whenever there is an update, wait for some time before installing it, just in case).

There are some instructions on how to install the browser extension manually, but they are somewhat hidden, and the process could be made much easier. Simply installing the zip file provided with each release doesn't work. On Windows, a registry entry has to be edited. Also, a JSON file must be edited. This could be automated by an installer script.

**Comment by droidmonkey** [comment]
We have this feature for debug builds already, I don't see why we can't just expose this for all builds.

**Comment by varjolintu** [comment]
Closing this. Let's track the issue here: https://github.com/keepassxreboot/keepassxc/issues/9074
