### ISSUE TITLE
Chase.com Autofill not Working

### ISSUE THREAD

**Issue by emkay5771** [keepassxreboot/keepassxc-browser#1846]
## Expected Behavior
chase.com should have the fields autofilled.

## Current Behavior
Regardless of autodetect or choosing specific fields, it fails to autofill.
![image](https://user-images.githubusercontent.com/52011243/217110480-4a52bbfe-41b0-4122-a13f-77a57fca0e2e.png)

## Steps to Reproduce (for bugs)

1. Go to chase.com
2. Try logging in
3. Try selecting fields manually

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Win
Browser: Brave

**Comment by varjolintu** [comment]
This same issue has been reported multiple times during the years. You don't need to use custom fields. Just use `https://chase.com` as your entry URL.
