### ISSUE TITLE
org.keepassxc.keepassxc_browser.json not created on chromium linux in custom user directory

### ISSUE THREAD

**Issue by dkebler** [keepassxreboot/keepassxc-browser#1853]
## Expected Behavior
when installing the browser extension  
`org.keepassxc.keepassxc_browser.json`
is created in `NativeMessagingHosts`

## Current Behavior
the file is not created, unable to connect

## Steps to Reproduce (for bugs)
1. Install latest chromium (in manjaro arch linux)
2. Install latest keepassxc (in manjaro arch linux)
3. run chromium like this `/usr/bin/chromium --user-data-dir=/opt/chromium/testing`
4. Install extension into chromium
5. first error message `Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`
6. click reload,  `Key exchange was not successful.`

I had the same issue with other chrome engine variants like vivaldi so not chromium specific.   I did check and it works fine without custom user data directory so issue just seems to be with this way of launching.

# Fix 
is to create/copy
`org.keepassxc.keepassxc_browser.json`
with
```
{
    "allowed_origins": [
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/bin/keepassxc-proxy",
    "type": "stdio"
}

```
into `NativeMessagingHosts` folder under the data directory, in this case `/opt/chromium/testing`
 

## Debug info
inspected browser and there are no browser errors 
```
KeePassXC-Browser Version: 1.8.4
Operating system: Linux Manjaro Arch
Browser: Chromium Version 110.0.5481.100 (Official Build) Manjaro Linux (64-bit)
```
```
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.8
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.1.11-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.3
```

**Comment by droidmonkey** [comment]
You are responsible for setting up a custom browser integration if you don't use the standard configuration file location.
