### ISSUE TITLE
TOTP problem with input field - no totp icon present

### ISSUE THREAD

**Issue by thalunil** [keepassxreboot/keepassxc-browser#1859]
With the following html source i don't get the totp input field i have on other websites:

`<input class="form-element form-field" id="fudis_otp_input" name="fudis_otp_input" type="password" value="" autocomplete="off" autofocus="">
`

What is the issue with this input field not being recognized as an totp field by keepassxc-browser?

**Comment by varjolintu** [comment]
The input field type is `password` so it's not regognized as a TOTP field. Use the Custom Login Fields to select it as one.
