### ISSUE TITLE
initContentScript error: Error: Cannot read properties of undefined (reading 'errorMessage')

### ISSUE THREAD

**Issue by yktoo** [keepassxreboot/keepassxc-browser#1860]
keepassxc-browser often gets unresponsive on web pages, in which situation the following error is shown in the console:

```
[Error keepassxc-browser.js:806] KeePassXC-Browser - initContentScript error: Error: Cannot read properties of undefined (reading 'errorMessage')
```

This might be related to #1355, but I don't face any possible causes described in that issue.

The problem often goes away for a specific page after a refresh; this makes me think it's a race condition. The error is apparently re-thrown [here](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js#L818), I'm not sure where it originates.

As this is happening quite frequently for me, but arguably not others (as I don't see a lot of related reports), this is perhaps caused by some other extension (like uBlock Origin). Yet, it's not the behaviour that should be shown in any circumstances.

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.2.2 (was actually troubling me over the past couple of years already)
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
1.8.2.2? The latest version if 1.8.4.

**Comment by yktoo** [comment]
My apologies. I've upgraded to 1.8.4, the problem is exactly the same, only the line number's changed:

```
global.js:177 [Error keepassxc-browser.js:814] KeePassXC-Browser - initContentScript error: Error: Cannot read properties of undefined (reading 'errorMessage')
```

Like I said, I've been seeing this over the past couple of years, so no change here either.

Is there anything I can do to diagnose/address that?

**Comment by varjolintu** [comment]
Is there some site you can reproduce this every time? Does it happen with all browsers? Does reinstalling the extension help?

**Comment by yktoo** [comment]
No, it's not always reproducible on any website, but it occurs so often (with ~60% likelihood) and *on every website* that I can easily reproduce that. It really looks like a race condition.

If with "other browsers" you mean other Chrome instances, then yes, it happens on every device with desktop Chrome (I have a desktop and 2 laptops).

Reinstalling the extension doesn't help at all.

**Comment by droidmonkey** [comment]
What version of chrome are you running?

**Comment by yktoo** [comment]
Version 110.0.5481.177 (Official Build) (64-bit)

Although I honestly don't think it matters

**Comment by droidmonkey** [comment]
At thus point every detail matters because it is unique to you 😉

**Comment by varjolintu** [comment]
Not sure if Chrome tries to synchronise the extension settings also? If it does that, maybe something is missing when trying to load the settings.

**Comment by droidmonkey** [comment]
Easily tested just create a new chrome profile and only install keepassxc extension. 

You have no provided us your list of extensions.

**Comment by yktoo** [comment]
I've added some debug logging and here's what I've figured out. Here's the console output right upon the initialization:

```
KeePassXC-Browser - ---sendMessage 1---
KeePassXC-Browser - ---sendMessage 2---
KeePassXC-Browser - ---A---
KeePassXC-Browser - ---A3---
KeePassXC-Browser - ---updateDatabaseState 1---
KeePassXC-Browser - ---sendMessage 1---
KeePassXC-Browser - initContentScript error: Error: Cannot read properties of undefined (reading 'errorMessage')
KeePassXC-Browser - ---sendMessage 1---
KeePassXC-Browser - ---sendMessage 2---
...
```
These are excerpts with the logging:

```js

[...]
// Wrapper
const sendMessage = async function(action, args) {
logError('---sendMessage 1---');
    let x = await browser.runtime.sendMessage({ action: action, args: args });
logError('---sendMessage 2---');
    return x;
};

[...cut...]

// Updates the database state to the content script
kpxc.updateDatabaseState = async function() {
logError('---updateDatabaseState 1---');
    const res = await sendMessage('get_status', [ true ]);
logError('---updateDatabaseState 2---');

    if (!res.keePassXCAvailable) {
logError('---updateDatabaseState 3---');
        kpxc.databaseState = DatabaseState.DISCONNECTED;
        return;
    }
logError('---updateDatabaseState 4---');

    kpxc.databaseState = res.databaseClosed ? DatabaseState.LOCKED : DatabaseState.UNLOCKED;
logError('---updateDatabaseState 5---');
};

[...cut...]

/**
 * Content script initialization.
 */
const initContentScript = async function() {
    try {
        const settings = await sendMessage('load_settings');
        if (!settings) {
            logError('Error: Cannot load extension settings');
            return;
        }

        kpxc.settings = settings;
logError('---A---');

        if (await kpxc.siteIgnored()) {
logError('---A1---');
            logDebug('This site is ignored in Site Preferences.');
logError('---A2---');
            return;
        }
logError('---A3---');

        await kpxc.updateDatabaseState();
logError('---B---');
        await kpxc.initCredentialFields();
logError('---C---');

        if (kpxc.settings.useObserver) {
            await kpxcObserverHelper.initObserver();
        }
logError('---D---');

        // Retrieve submitted credentials if available.
        const [ creds, redirectCount ] = await Promise.all([
            await sendMessage('page_get_submitted'),
            await sendMessage('page_get_redirect_count')
        ]);
logError('---E---');

        if (creds && creds.submitted) {
logError('---F---');
            // If username field is not set, wait for credentials in kpxc.retrieveCredentialsCallback.
            if (!creds.username) {
                return;
            }
logError('---G---');

            if (redirectCount >= kpxc.settings.redirectAllowance) {
                await sendMessage('page_clear_submitted');
            }
logError('---H---');

            kpxc.rememberCredentials(creds.username, creds.password, creds.url, creds.oldCredentials);
        }
logError('---I---');

        kpxcIcons.switchIcons();
    } catch (err) {
        logError('initContentScript error: ' + err);
    }
};
```

So apparently it crashes during this call in `sendMessage`: `await browser.runtime.sendMessage({ action: action, args: args })`

Does this clear anything up?

**Comment by yktoo** [comment]
@droidmonkey As crazy as it sounds, I've almost identified the bastard. It seems to be the [Angular DevTools](https://chrome.google.com/webstore/detail/angular-devtools/ienfalfjdbdpebioblfackkekamfmbnh) extension (made by Google by the way).

If I switch it on, the problem's gone. As soon as I disable it, a simple page like [this one](https://pkg.go.dev/builtin#any) almost certainly causes the error, which doesn't reoccur on refresh.

There was, though, one occasion when I saw the error when the Angular DevTools extension was off. Which puzzles me even more...

**Comment by droidmonkey** [comment]
Can you limit the angular devtools extension to only be active on certain pages?

**Comment by yktoo** [comment]
Ouch. I think I was wrong about the Angular extension. With other extensions enabled, it still happens. Apologies.

It does seem to happen a way less frequently though when there's no extension at all, except KeePassXC :)

**Comment by yktoo** [comment]
Interesting. I've stubbed `updateDatabaseState()` so that it doesn't call `sendMessage()` at all and simply sets
```js
kpxc.databaseState = DatabaseState.UNLOCKED;
```

Now I'm consistently getting this:
![image](https://user-images.githubusercontent.com/1675911/220988380-7d43d870-c8ab-4f4d-9ac1-23c68c9cdfe9.png)

**Comment by droidmonkey** [comment]
The error is not occurring in send message. It is occurring in an async process. Reading the error, it sounds like some extension you have is stripping properties from DOM elements on a page that we are trying to access.

**Comment by yktoo** [comment]
Hmmm. It still happens with **all** extensions disabled except for KeePassXC-Browser. But it doesn't happen in incognito.

**Comment by yktoo** [comment]
Hehe, delaying KeePassXC-Browser's initialization does seem to make the problem go away:

```js
const initContentScript = async function() {
    await new Promise(resolve => setTimeout(resolve, 500));
    ...
```

It's a stupid solution, but the problem's been driving me crazy...

**Comment by varjolintu** [comment]
Both errors can be probably seen when inspecting the background scripts. There's `kpxcEvent.showStatus()` in `event.js` where both `page.tabs[tab.id].errorMessage` and `page.tabs[tab.id].usernameFieldDetected` can be found. Maybe there's no such tab in the list. The function doesn't check if it exists.  Can you check the background script logs via chrome://extensions when you enable the Developer Mode?

**Comment by yktoo** [comment]
Yes, your guess seems a right one:
![image](https://user-images.githubusercontent.com/1675911/222971886-8ec6b864-4c60-4f03-b71c-1f5f3cb5f857.png)

Not sure what all that means though.

**Comment by varjolintu** [comment]
Not sure why that happens, but some extra checks are needed so those exceptions are not thrown.

**Comment by yktoo** [comment]
Still happens in 1.8.5.1 :-(

**Comment by varjolintu** [comment]
Can you debug the extension again and see where the issue is now?

**Comment by yktoo** [comment]
Sure I can, but correct me if I'm wrong: this fix is not released yet, is it? So 1.8.5.1 isn't supposed to fix that

**Comment by yktoo** [comment]
I will. What's the planning for releasing this?

**Comment by varjolintu** [comment]
Soon. Not a planned date though.
