### ISSUE TITLE
Login form for overleaf.com is not filled

### ISSUE THREAD

**Issue by abeham** [keepassxreboot/keepassxc-browser#1861]
## Overview
When I go to overleaf.com and press "Login", the username and password fields are recognized, but the icon turns gray (after briefly flashing green). Selecting "Fill Username and Password" manually does not enter any login information. There is an entry in the database with URL "https://overleaf.com". I am using the KeepassXC Browser plugin for Vivaldi. I also tested in Firefox, but same issue. I tested on multiple computers and also asked colleagues to verify.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC and unlock the database that contains a key for overleaf.com
2. Open the browser with the KeePassXC Browser plugin and ensure that it is connected to the database
3. Go to overleaf.com and press "Login"

## Expected Behavior
The login information should be filled.

## Actual Behavior
No login information is filled, the icon is shown, but is grayed out.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.4
Revision: 63b2394

Qt 5.15.6
Debugging mode is disabled.

Operating system: Windows 10 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.19045

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.1

Operating System: Windows

**Comment by varjolintu** [comment]
Use `https://overleaf.com/` as your entry ID. I had no problems filling the site.

**Comment by abeham** [comment]
Your are right, I took a deeper look into all the settings and saw that there were some strange entries, among others a Deny from the browser plugin. Probably, I clicked Deny with remember once and didn't realize it?? Thanks for checking!
