### ISSUE TITLE
Not working on Newegg?

### ISSUE THREAD

**Issue by undeference** [keepassxreboot/keepassxc-browser#1862]
## Expected Behavior
I should be able to autofill on newegg.com, but I can't. Even setting custom fields doesn't work.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 110.0

**Comment by varjolintu** [comment]
Add a Username-Only option for the site. That can be achieved from the extension popup (if the extra button for that does now show, redetect credentials first). Plus use `https://newegg.com` as your entry URL.

**Comment by undeference** [comment]
I tried that, plus I tried various settings at in the "SITE PREFERENCES" with https://newegg.com and https://secure.newegg.com as well as the more complete path added by the popup. Nothing works.

And after entering my credentials, the TOTP field couldn't be autofilled either.

**Comment by varjolintu** [comment]
For me the Site Preferences URL was `https://secure.newegg.com/identity/*` and it worked normally.

**Comment by undeference** [comment]
I thought it might make a difference that I'm using the global site, but it doesn't work on the US site either :shrug: 

Only the "Request Global Auto-Type" menu option does anything. None of the others do anything, including "Fill Password Only" and "Fill TOTP".

**Comment by undeference** [comment]
It also doesn't work in Chrome
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.4
Operating system: Linux x86_64
Browser: Chrome/Chromium 110.0.0.0

**Comment by varjolintu** [comment]
Can you check the JavaScript console logs from both background and content scripts if there's some relevant messges? You can also enable Debugging from the extension settings to get some extra output about detected fields etc.

**Comment by undeference** [comment]
All I see that seems relevant are
> 19:22:51.197 [Error client.js:175] KeePassXC-Browser - 8: KeePassXC association failed, try again global.js:177:13

in the console and when debugging the addon.

**Comment by varjolintu** [comment]
That error means you haven't connected the extension to your database.

**Comment by undeference** [comment]
That's strange. Now it's saying 

10:46:35.051 [Error client.js:175] KeePassXC-Browser - 15: No logins found global.js:177:13

I have the entry's URL set to "newegg.com"

**Comment by varjolintu** [comment]
> I have the entry's URL set to "newegg.com"

Without the scheme? Use `https://newegg.com`.

**Comment by undeference** [comment]
It makes no difference. Still says No logins found.

**Comment by varjolintu** [comment]
And you have Site Preferences enabled for the site with the Username-Only Detection on?

**Comment by undeference** [comment]
Yes

**Comment by varjolintu** [comment]
And you are sure the permissions in your entry in the database has this site as allowed? That's the only reason why this might happen. You can check the permissions by editing your entry and go to the Properties page. See "Plugin Data".

**Comment by undeference** [comment]
I don't know why it was set to deny. It seems like everything that can go wrong has gone wrong.

Now it says 

11:12:50.294 [Error client.js:175] KeePassXC-Browser - 8: KeePassXC association failed, try again 4 global.js:177:13

**Comment by undeference** [comment]
Okay, had to reassociate again. There are definitely bugs somewhere here. But I finally got it working.

**Comment by varjolintu** [comment]
Do you have to reassociate often? Is something clearing your browser's localStorage or are the keys properly saved in your database? That doesn't sound normal.

**Comment by undeference** [comment]
I haven't noticed it before.
