### ISSUE TITLE
Problems with basic authentication on Chrome

### ISSUE THREAD

**Issue by Tassleh0ff** [keepassxreboot/keepassxc-browser#1868]
I recently noticed a problem with http basic authentication using the plugin on sites with Chrome.

The target site is a regular https site on Apache 2.4 where I host several applications using ProxyPass directive, each of those applications has its own login, so I have several Keepass entries for the same site.
The root of the site requires basic authenticaiton, so when I access it KepassXC Browser asks for the right entry to use for the basic authentication (I enabled this type of authentication on the extention options), and after selecting it the index is loaded and evenrything is fine.

A few days ago I noticed a problem: when I access the site KeepassXC Browser detect basic authentication, it asks for the right entry to login, but after selecting the right entry it doesn't load the index page, and the browser keep showing the loading icon, as if it was waiting for the authentication from the extension.

Looking to the webserver access logs seems like there's no http request coming from the browser after I select the right login entry for the basic authentication.

I also checked on Firefox, and everything works fine, but the last KeepassXC Browser version availble among Firefox add-ons is 1.8.4, while on Chrome is version 1.8.5

I tried also to enable debug logs and look to the dev tools using "Inspect views:" feature as described in the troubleshooting guide, but the only debug message I got was the number of entries found by the extension:
`[Debug keepass.js:161] KeePassXC-Browser - Found 6 entries for url https://www.site.tld/`

I noticed that also the option to abort the authentication and present the browser form for basic authentication do not work anymore.

Keepass version 2.53.1
KeePassXC-Browser version 1.8.5
KeePassNat Msg version 2.0.14.0
Operating system: Win 10 Pro 22H2
Browser: Chrome 110.0.5481.178

**Comment by varjolintu** [comment]
Good catch! It's caused by this change: https://github.com/keepassxreboot/keepassxc-browser/pull/1822

**Comment by Tassleh0ff** [comment]
Thank you @varjolintu, I updated to 1.8.5.1 and works perfectly.
Great work buddy!
