### ISSUE TITLE
Solution for librewolf + macos + keepassxc

### ISSUE THREAD

**Issue by jqtmviyu** [keepassxreboot/keepassxc-browser#1870]
## Current Behavior
can't connect to keepassxc

## Possible Solution
copy `~/Library/Application Support/Mozilla/NativeMessagingHosts` to `/Users/nuc/Library/Application Support/librewolf/`

## info
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.5.1
Operating system: Mac
Browser: librewolf

**Comment by jqtmviyu** [comment]
a better solution
```bash
ln -s ~/Library/Application\ Support/Mozilla/NativeMessagingHosts ~/Library/Application\ Support/LibreWolf/NativeMessagingHosts
```

**Comment by varjolintu** [comment]
A better solution: Use the Custom Browser feature directly from KeePassXC and put your Librewolf native messaging path there.

**Comment by finnlogin** [comment]
Hi there!
I'm having a problem with the Keepassxc extension for Librewolf on macOS. It used to work before I reinstalled the system though. Now I'm trying to follow the same steps, but it doesn't work.
I copied org.keepassxc.keepassxc_browser.json from ~/Library/Application Support/Mozilla/NativeMessagingHosts
to ~/Library/Application Support/librewolf/NativeMessagingHosts but it still keeps throwing an error:
Key exchange was not successful.
I tried the latest version of Keepassxc which is 2.7.6. Also, I tried 2.7.4. I tried to provided a custom browser configuration location too but it didn't work.
Any thoughts? I've been trying to fix it for two days now and I ran out of ideas. I'd appreciate any help in this matter.

**Comment by finnlogin** [comment]
@varjolintu It used to work for me too, but after the latest macOS installation it stopped working. I'm wondering if it has something to do with the case sensitivity I chose this time for my file system. The contents of my org.keepassxc.keepassxc_browser.json file are as follows:

```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy",
    "type": "stdio"
}
```

**Comment by varjolintu** [comment]
@finnlogin Not sure about that. At least the path is correct in the file, but I'm not sure how Firefox/Librefox will handle native messaging if filesystem is case sensitive.
