### ISSUE TITLE
Domain filter by pattern *.domain.com if I'm on sub.domain.com

### ISSUE THREAD

**Issue by vukitoso** [keepassxreboot/keepassxc-browser#1871]
Hello.
KeePassXC - 2.7.4
KeePassXC-Browser 1.8.5.1
Operating system: Linux
Browser: Firefox

I have passwords for domain.com, test.domain.com, mail.domain.com in the KeePassXC database.
When I open a site with the test.domain.com subdomain, the KeePassXC-Browser extension only gives me passwords for test.domain.com.
Is it possible to make the extension show passwords for both the domain.com second-level domain and all *.domain.com subdomains?
Thank you.

**Comment by varjolintu** [comment]
Use `https://domain.com` as your entry URL. It's basically the same as `https://*.domain.com`.
