### ISSUE TITLE
Autocomplete positioning issue when document is in quirks mode

### ISSUE THREAD

**Issue by stefansundin** [keepassxreboot/keepassxc-browser#1872]
## Expected Behavior

The autocomplete dropdown should be properly positioned when a page is in quirks mode.

## Current Behavior

I noticed that on https://identity.pagerduty.com/, the autocomplete dropdown is not positioned properly. Turns out that the page is rendered in quirks mode and `document.scrollingElement` is `null`. (see below for javascript error)

![Screenshot 2023-03-03 at 17 22 55](https://user-images.githubusercontent.com/1991151/222869136-cd9c20f5-517b-424d-9a53-3d48075c4e08.png)

## Possible Solution

I tried this:

```javascript
const scrollingElement = document.scrollingElement || document.documentElement;

// replace references to document.scrollingElement with just "scrollingElement"
```

This works fine until you scroll the document. When the document is scrolled the dropdown is not following along. If this had fully solved the problem then I would have opened a PR.

## Steps to Reproduce (for bugs)

1. Create an entry for https://identity.pagerduty.com/.
2. Go to https://identity.pagerduty.com/.
3. Click the username input field.
4. Open javascript console and see `scrollingElement` error (screenshot below).

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.5.1
Operating system: Mac
Browser: Chrome

![Screenshot 2023-03-03 at 17 22 14](https://user-images.githubusercontent.com/1991151/222868817-64e910da-fb69-493e-b0ce-700ede8f48d9.png)

An errant `<meta>` tag is causing the page to render in quirks mode:

![Screenshot 2023-03-03 at 17 27 17](https://user-images.githubusercontent.com/1991151/222868827-ba2c7932-6867-4ddc-ba1c-b018a8f16b1a.png)

```
document.compatMode
'BackCompat'
```

**Comment by varjolintu** [comment]
Same happens with the Username Icon when scrolling. I noticed that even with `document.documentElement` the `scrollTop` value is 0. But the actual value can be retrieved from `document.defaultView.scrollY`.

Probably it could possible to use directly only `document.defaultView.scrollY` and `document.defaultView.scrollX`.
