### ISSUE TITLE
Password Generator causes database to become unresponsive

### ISSUE THREAD

**Issue by dec-xii** [keepassxreboot/keepassxc-browser#1874]
## Expected Behavior
Password Generator should close with the 'X' button without interfering with the database window.

## Current Behavior
If the X button in the Password generator panel is used to close the window instead of the "Close" button, the currently open data base window will become unresponsive. The issue can be fixed by reopening the Password Generator and pressing "Close".

## Steps to Reproduce Bug
1. Right click on a password entry field
2. Select "Show Password Generator"
3. Use the 'X' button to close the panel
4. KeePassXC database will become unresponsive when attempting to click into the window

## Debug info
KeePassXC 2.7.4
KeePassXC-Browser 1.8.5.1
Operating system: Windows 10 home
Browser: Chrome/Firefox

**Comment by varjolintu** [comment]
The issue is tracked here: https://github.com/keepassxreboot/keepassxc/issues/7952
