### ISSUE TITLE
Unable to connect to connect with the Database under Windows 10 and with Microsoft Edge

### ISSUE THREAD

**Issue by noodles101** [keepassxreboot/keepassxc-browser#1878]
I've done all hint in the documentation.

I also deinstalled and installed the Edge plugin and KeePassXC itselve several times. But no luck.

In the past the connection worked fine for me with several browsers (Firefox, Chrome and also Edge). But someday only on Edge the connection lost and can't be established again.

I've tried the same steps with the Chrome browser and there all functional as aspected.

So I create now this ticket.

I've currently installed KeePassXC via WinGet from the winget-store.

**Comment by varjolintu** [comment]
Checked this one already? https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#7-windows-specific-with-chromium-based-browsers-chrome-edge-vivaldi-brave-etc

**Comment by noodles101** [comment]
Thanks for hint. The [NativeMessagingUserLevelHosts](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#nativemessaginguserlevelhosts) was disabled.

This should be in the Troubleshooting Guide.

**Comment by varjolintu** [comment]
> Thanks for hint. The [NativeMessagingUserLevelHosts](https://learn.microsoft.com/en-us/deployedge/microsoft-edge-policies#nativemessaginguserlevelhosts) was disabled.
> 
> This should be in the Troubleshooting Guide.

It is.

**Comment by noodles101** [comment]
> It is.

here is "0" and not "1" --> file:///C:/Program%20Files/KeePassXC/share/docs/KeePassXC_UserGuide.html#_advanced_setup

**Comment by droidmonkey** [comment]
That's because it uses the allow list..
