### ISSUE TITLE
Browser extension will not connect.

### ISSUE THREAD

**Issue by TexasTechnician** [keepassxreboot/keepassxc-browser#1883]
## Expected Behavior
click the browser extensions option to connect to db.  db opens and prompts for approval (new setup of new browser and install of keepass).

## Current Behavior

I'm running keepassxc browser extension (latest) in firefox v111.0 (installed via snap) on kubuntu 22.10.

I've tried keepassxc via apt, snap and the app image.  The snap version was the only one which produced a different result.  

The all produce the same problem.  When trying to connect (prompt from the browser plugin) keepass pops up.  But is locked (even when it was unlocked, the browser extension call is locking the db).  And I am unable to connect the db.

The browser plugin only gives the generic error, "Key exchange was not successful".  

The config is:
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/home/txtechnician/Downloads/KeePassXC-2.7.4-x86_64.AppImage",
    "type": "stdio"
}

```

I decided to try the edge version instead.  It worked with no problems.  

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {2.7.4}
KeePassXC-Browser - {1.8.5.1}
Operating system: Linux  Kubuntu v 22.10
Browser: Firefox 111.0 Snap

**Comment by droidmonkey** [comment]
Checkout other issues please that discuss this very problem. It is with Firefox snap not us.

**Comment by varjolintu** [comment]
See the pinned issue: #1426
