### ISSUE TITLE
KeePassXC extension does not connect in TorBrowser version 12.04 installed in openSuse Tumbleweed manually

### ISSUE THREAD

**Issue by serial02** [keepassxreboot/keepassxc-browser#1890]
Hey guys

 Can you help me on this issue?

 TorBrowser browser version 12.04 manually installed in openSuse Tumbleweed does not connect KeePassXC version: 1.8.5.1 extension in KeePassXC 2.7.4 application.  See the image below:

![Captura de tela de 2023-04-02 17-17-00](https://user-images.githubusercontent.com/32621790/229379240-b0905e0b-f527-44d7-ab8a-6dce49b6c3be.png)

Note: On the page in the image above, when we click on NoSript, which is standard in TorBrowser, the following information appears: "This is a page with privileges, whose permissions cannot be changed".  I don't know if this information is relevant, okay?

I saw and read several reports and followed some suggestions, but I was not successful in making this connection.  Are there any other suggestions you can give me?

Apparently the host is installed correctly.  See the image below:

![Captura de tela de 2023-04-02 18-09-10](https://user-images.githubusercontent.com/32621790/229379192-87a3a471-14af-453a-8209-9630c523628d.png)

I already replaced the org.keepassxc.keepassxc_browser.json from the native /.mozilla folder and transported it to the folder ( /home/edson/.local/share/torbrowser/tbb/x86_64/tor-browser_en-US/Browser/TorBrowser/Data/Browser /.mozilla/native-messaging-hosts ) , but that didn't work either.

## Current Behavior
When clicking on connect in (Connected Databases) it does not open the permission to connect to the keepassxc app putting the name for the new connection.

## Possible Solution
A simple solution would be if the TorBrwoser browser automatically allows opening the connection, or the KeePassXC browser extension tells us why the connection is being blocked.
When installing the extension, can it not make the other settings automatically, in case it finds the necessary proxy that the browser itself performs if this is the case?
 It will definitely help users.

## Steps to Reproduce (for bugs)
When clicking on connect in (Connected Databases) it does not open the permission to connect to the keepassxc app putting the name for the new connection.

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.8.5.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 102.0

When you click copy the folder, the information above is the only one sent.

**Comment by varjolintu** [comment]
Use [strace](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace) to find out the correct path. Tor Browser can have multiple ones, and KeePassXC doesn't check them all.

**Comment by serial02** [comment]
> Use [strace](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace) to find out the correct path. Tor Browser can have multiple ones, and KeePassXC doesn't check them all.

Hello @varjolintu 

I was in doubt which correct line to be inserted.
 In order not to do anything wrong, you can check and see if it is the last line that needs to be inserted in the browser torbrowser?

```
edson@localhost:~> sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass
[sudo] senha para root: 
[pid  9076] openat(AT_FDCWD, "/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid  9076] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
```

Grateful!

**Comment by varjolintu** [comment]
Try both of those paths. Add them to the Custom Browser settings in KeePassXC.

`/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/`
`/usr/lib/mozilla/native-messaging-hosts/`

**Comment by serial02** [comment]
> Try both of those paths. Add them to the Custom Browser settings in KeePassXC.
> 
> `/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/` `/usr/lib/mozilla/native-messaging-hosts/`

Holla @varjolintu 

Can you show me with an image where this command is placed, since it doesn't open the extension's pop-up?

**Comment by varjolintu** [comment]
You can put the path here after you have enabled the setting in KeePassXC. Keep the Firefox option.
<img width="802" alt="Screenshot 2023-04-03 at 14 50 24" src="https://user-images.githubusercontent.com/24570482/229501033-a60bf7d1-6e61-453a-b396-2f4330b1587b.png">

**Comment by varjolintu** [comment]
It's in KeePassXC -> Settings -> Browser Integration -> Advanced Tab. Enable `[ ] Use custom browser configuration location:`. Browser type is `Firefox` and set the path below.

**Comment by serial02** [comment]
> It's in KeePassXC -> Settings -> Browser Integration -> Advanced Tab. Enable `[ ] Use custom browser configuration location:`. Browser type is `Firefox` and set the path below.

Now I understand, thanks.

 It looked like this:


![Captura de tela de 2023-04-03 08-54-37](https://user-images.githubusercontent.com/32621790/229501972-db1e7a3a-73a8-4cf8-97f6-58596b740d89.png)

Correct?

But it did not work!

**Comment by varjolintu** [comment]
Try both paths. Restart your browser in between.

**Comment by serial02** [comment]
> Try both paths. Restart your browser in between.

It only worked with one of them!  Thank you so much @varjolintu 

/opt/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/

I can't live without this app and extension

 Look!

![Captura de tela de 2023-04-03 09-12-49](https://user-images.githubusercontent.com/32621790/229505969-7ab8eac3-6ee8-4ef4-976d-1c089f6709bd.png)

**Comment by varjolintu** [comment]
Great! :) Closing the issue.
