### ISSUE TITLE
1.8.6 cannot connect to KeePassXC

### ISSUE THREAD

**Issue by zaw007** [keepassxreboot/keepassxc-browser#1892]
KeePassXC v2.7.4
KeePassXC-Browser v1.8.6
System：Windows 10 21H2
Browser：360 极速浏览器 v13.5（chromium v86）

After clicking the plug -in,always like the picture,but 1.8.5 is normal.

![20230405175934](https://user-images.githubusercontent.com/25732226/230048530-1e8ed963-a545-42b2-9d19-099560400d60.png)

**Comment by droidmonkey** [comment]
Your browser is wildly out of date, at least 2.5 years old
