### ISSUE TITLE
Browser extension keeps "checking status" on firefox with 1.8.6

### ISSUE THREAD

**Issue by tenzap** [keepassxreboot/keepassxc-browser#1894]
## Expected Behavior

I expect the extension to connect to keepassxc.

## Current Behavior

Since update to 1.8.6, when opening the extension on firefox 91.13.0esr the extension keeps displaying "Checking status" and nothing happens.

## Possible Solution

If I downgrade to 1.8.5.1 it works fine.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6
Operating system: Linux Debian
Browser: Firefox 91.13.0esr

**Comment by varjolintu** [comment]
What does the logs say? The recent changes made should be covered with Firefox 91. Firefox ESR should be at version 102 even with Debian Buster (oldstable).

Maybe we need to revert some changes :(

**Comment by varjolintu** [comment]
You don't need to enable debugging. `about:debugging` already works.
For detailed instructions: https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-situations-and-debugging#firefox-debug-background-scripts

And if you want to keep popup active and inspect them, you need to enable this setting:
<img width="317" alt="Screenshot 2023-04-09 at 10 02 26" src="https://user-images.githubusercontent.com/24570482/230759266-38dc325d-eead-49f8-adae-05855bda573d.png">

**Comment by varjolintu** [comment]
Ah yes. `hasOwn()` has a minimum version of Firefox 92, not 91. My bad.

**Comment by droidmonkey** [comment]
91 esr went end of life 6 months ago 😦

**Comment by varjolintu** [comment]
@tenzap It's possible, but it means everyone who have already updated to 1.8.6 the solution will not work. Shit has already hit the fan, so to say.

**Comment by droidmonkey** [comment]
The best solution is to update your browser however possible for you. Win-win, security is maintained.
