### ISSUE TITLE
Extension stuck at `Checking status...` on GNU IceCat 91.13.0esr

### ISSUE THREAD

**Issue by BeanieBarrow** [keepassxreboot/keepassxc-browser#1896]
## Expected Behavior
The extension should connect to my database. On the settings page of the extension, I shouldn't see errors under `Keyboard shortcuts`

## Current Behavior
The extension doesn't load the database, even though in KeePassXC, I enabled browser integration for all browsers. It's stuck at `Getting status...`.

When visiting the settings page of the extension, under keyboard shortcuts, every entry displays `error`:

```
 Keyboard shortcuts

Fill Username and Password: error
Fill Password Only: error
Fill TOTP: error
Show Password Generator: error 
```

## Steps to Reproduce (for bugs)

1. Use GNU IceCat 91.13.0esr (got it from here under Debian 11: https://software.opensuse.org//download.html?project=home%3Alosuler%3Aicecat&package=icecat)
2. Use KeePassXC 2.7.4
3. Install the extension
4. Visit the settings page of the add-on or click on the icon in the toolbar of the browser.

## Debug info

```
[Error ] KeePassXC-Browser - initContentScript error: Error: Object.hasOwn is not a function
```
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6
Operating system: Pop!_OS 22.04 LTS
Browser: GNU IceCat 91.13.0esr

**Comment by varjolintu** [comment]
The minimum for Firefox is 93. The requirement is fixed in 1.8.6.1. If you already got an update, you'll have to manually reverse to 1.8.5.1. That's the last version that will be supported with older browsers.

Hint: Update your browser. 91 ESR's [end of life](https://endoflife.date/firefox) was already in September 2022.
