### ISSUE TITLE
Credential fields are no longer detected on urls with port

### ISSUE THREAD

**Issue by Hativ** [keepassxreboot/keepassxc-browser#190]
Since 1.1.4 credential fields are no longer detected on urls with port.

## Expected Behavior
Credential fields should be detected, credentials should be selectable.

## Current Behavior
Credential field are not detected, credentials could not be selected.

## Steps to Reproduce (for bugs)
1. Save test credentials for https://aurelius.metanet.ch:8443
2. Go to https://aurelius.metanet.ch:8443/login_up.php
3. Try to get the credentials filled in

I even tested it with saving the url as:
https://aurelius.metanet.ch
https://aurelius.metanet.ch:8443/login_up.php

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 1.1.4
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/pull/189 fixes this.

**Comment by droidmonkey** [comment]
I don't think it does?

**Comment by varjolintu** [comment]
@droidmonkey It does. There's a typo in line 914: https://github.com/keepassxreboot/keepassxc-browser/pull/189/files#diff-5625214326e4998376bc48f849da95b8R914. That keeps input fields unidentified.
