### ISSUE TITLE
TOTP request happens too soon

### ISSUE THREAD

**Issue by Julius-Babies** [keepassxreboot/keepassxc-browser#1903]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
When I want to login to some accounts which are using TOTP 2FA I have to reload the page sometimes because the TOTP in the browser-extension cache already expired.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a website which supports TOTP 2FA
2. Login using username and password
3. Wait 30s (so the TOTP in the cache expires)
4. Try to login

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The browser plugin requests the TOTP when you click the TOTP icon in the inout field

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
The browser plugin requests the TOTP when you load the page.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.4
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: all
Desktop Env: all
Windowing System: -

**Comment by varjolintu** [comment]
The extension should retrieve the TOTP again every time when doing the fill.

**Comment by varjolintu** [comment]
I still cannot reproduce this. Please test this the following way:
- Go to the website which requires TOTP
- Login and stay on the TOTP page
- Open KeePassXC and select "Show TOTP" from your entry
- Fill the TOTP from extension and check if the value is the same
- Wait for timer to run out in KeePassXC
- Press the TOTP icon again from the extension
- New TOTP value should be filled

**Comment by Julius-Babies** [comment]
Sorry, I actually had the wrong Timezone Set in my PC. Syncing the clock fixed the issued.
