### ISSUE TITLE
Unable to detect password and username fields on Authentik

### ISSUE THREAD

**Issue by scolastico** [keepassxreboot/keepassxc-browser#1904]
I'm a user of keepassxc and I've noticed that the browser extension is unable to detect the password and username fields on Authentik (example URL: https://auth.scolasti.co/). Even if I try to select the fields manually using the extension's selection tool, nothing happens when I click on them.

I would like to report this as a bug and request assistance in fixing it. This is quite inconvenient as I have to manually copy and paste my credentials every time I want to log in to Authentik.

**Steps to reproduce:**
1. Navigate to https://auth.scolasti.co/
2. Attempt to use the keepassxc browser extension to autofill the username and password fields
3. Note that the extension is unable to detect or select the fields

**Expected behavior:**
The keepassxc browser extension should be able to detect and autofill the username and password fields on Authentik.

**Actual behavior:**
The keepassxc browser extension is unable to detect or select the username and password fields on Authentik.

**Additional information:**
- I've tested the extension on other websites and it works fine.

**Debug info:**
- KeePassXC - 2.7.4
- KeePassXC-Browser - 1.8.6.1
- Operating system: Linux
- Browser: Vivaldi

**Comment by varjolintu** [comment]
This happens because the form is under Shadow DOM, and the `div` that contains the form is under another Shadow DOM. The extension only has a limited support for Shadow DOM elements, so there's no solution for this problem right now.

**Comment by mfbehrens99** [comment]
Still not working for me :(
I checked my version but it seems to be up-to-date. I cannot even manually assign fields to any of the textboxes.

Can somebody confirm?

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 125.0

**Comment by varjolintu** [comment]
@mfbehrens99 Read my message above.

**Comment by virtualdxs** [comment]
@varjolintu Your PR, more recent than your message above, stated that it fixed this issue, but it's still occurring. It's fine if it's a wontfix, just worth clarifying that.

**Comment by varjolintu** [comment]
@virtualdxs Add `https://auth.scolasti.co/` to extension's Site Preferences page and enable Improved Input Field Detection for it.
