### ISSUE TITLE
Cannot Keepass Browser with Firefox Developer

### ISSUE THREAD

**Issue by Alex9001** [keepassxreboot/keepassxc-browser#1907]
I am using Artix Linux x64 with GTK3 and MATE.

I have firefox, firefox developer, and librewolf. I am using KeepassXC. I have installed KeepassXC Browser extension. It works in Firefox but not in Firefox Developer. I have /home/user/.mozilla/native-messaging-hosts but it only works with regular firefox not developer even though they both share this folder. There is no separate folder for developer. I copied native-messaging-hosts to librewolf folder and that works fine. How to make it work with firefox developer?

## Expected Behavior

KeepassXC Browser should work with Firefox Developer. It does not. Documentation suggests to place a native-messaging-hosts to ~/.mozilla but this does nothing for Firefox Developer which shares ~/.mozilla with Firefox Regular.

## Current Behavior
Install KeepassXC and KeepassXC Browser. Enable Firefox support. Launch firefox developer. KeepassXC Browser not work.

## Possible Solution
Provide instructions on how to make it work with multiple Mozilla browsers.

## Steps to Reproduce (for bugs)
1. Install Artix GTK3
2. Install Firefox Developer
3. Install KeepassXC
4. Install KeepassXC Browser
5. KeepassXC Browser not work with Firefox Developer. Only work with Firefox Regular.

## Debug info
KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6.1
Operating system: Linux Artix GTK3 MATE
Browser: Firefox **Developer**

**Comment by droidmonkey** [comment]
> Firefox Developer which shares ~/.mozilla with Firefox Regular

A couple sources I found said this is not true. Please verify your profile folder for Firefox Developer.

**Comment by varjolintu** [comment]
Please check the Developer Edition doesn't use some path under `/opt/`etc. You can use `strace` to check the folder. It's also possible that the Developer build has some bugs in the browser API's and things are just broken.

**Comment by Alex9001** [comment]
Sorry I dumped that install. It was a fresh install of artix-community-gtk-openrc-20230403-x86_64.iso and I was using the gui package installer it had.

I installed the KDE version of artix and using Pacman everything is cool. Weird. I guess this is Artix fault not yours. Closing.
