### ISSUE TITLE
extension cannot connect to database on firefox nightly

### ISSUE THREAD

**Issue by MrJudge77** [keepassxreboot/keepassxc-browser#1908]
## Expected Behavior

expect extension to connect to database.

## Current Behavior

gives out error: Key exchange was not successful.
extension cannot connect to database on firefox nightly. the extension does work on ffx beta.
something may have changed on ffx nightly that caused the error.

## Possible Solution

fix extension so it may work with ffx nightly again.

## Steps to Reproduce (for bugs)

1. install extension in ffx nightly
2. try to connect to database

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6.1
Operating system: Win64
Browser: Mozilla Firefox 114.0

**Comment by droidmonkey** [comment]
Duplicate. Wait for an upcoming nightly release
