### ISSUE TITLE
I constantly get "Confirm Access Dialog"

### ISSUE THREAD

**Issue by oguzhantopcu** [keepassxreboot/keepassxc-browser#191]
## Expected Behavior
I do not want to get encountererd by confirm access dialog unnecessarily

## Current Behavior
I visit a website,
I get Confirm Access Dialog, even if there is no input on the page.
## Steps to Reproduce (for bugs)
1. Visit a website.
2. Get the following behaviour in the picture.
![image](https://user-images.githubusercontent.com/2956166/41238479-b23dcd9c-6d9e-11e8-9595-8cf6f1fc5352.png)

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 1.1.4
Operating system: Fedora 28
Browser: Chrome
Proxy used: NO

**Comment by varjolintu** [comment]
This has been just fixed: https://github.com/keepassxreboot/keepassxc-browser/pull/189. Wait for the official update.
