### ISSUE TITLE
entries with url reference are not showing on the page

### ISSUE THREAD

**Issue by hugodu69** [keepassxreboot/keepassxc-browser#1910]
## Expected Behavior

if an entry use a url reference {REF:A@I:93AA5F3F7F64E0CD8FE6DD65867/BAE4} (as explained here : https://keepassxc.org/docs/KeePassXC_UserGuide#_entry_cross_reference), the browser extension should propose, when on the page of this url, both the first entry and the one with the reference

## Current Behavior

the reference works in the desktop application (the preview of the entry shows a url field as : "Ref: the_rigth_url.com"), but it doesn't work in the browser extension : only the first entry is shown, not the referenced one

## Steps to Reproduce (for bugs)

1. (optional) in desktop application, clone an entry, and use reference for username and password -> useful to get the reference id
2. for the url, use a reference, like this : {REF:A@I:93AA5F3F7F64E0CD8FE6DD65867/BAE4} (replace the last field by the reference id)
3. check that the reference worked : when you search for the entry, the preview shows the url field like this : "Ref: the_rigth_url.com"
4. try to go on the page, see that the cloned entry doesn't show in the suggestions

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.6.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
This is already fixed :) See: https://github.com/keepassxreboot/keepassxc/pull/8788
