### ISSUE TITLE
Not working on the website telugumatrimony.com

### ISSUE THREAD

**Issue by Karbi123** [keepassxreboot/keepassxc-browser#1913]
**URL: https://www.telugumatrimony.com/#loginpopup**

When I click on the keepassxc icon in the username field, the username and password are populated to the respective fields. Then after I press the login button, the password field is erased and the website throws the error "Please enter password". Then I enter the password manually. After that, I could log in to the website.

There is an issue with the password from keepassxc being accepted by the website.

![Telugumatrimony - Keepassxc Error](https://github.com/keepassxreboot/keepassxc/assets/20335072/b019f7b1-74c7-49c1-a882-672155f29be2)

**Comment by varjolintu** [comment]
I could not reproduce this. The password was filled normally. After that when I focused the field it seemed to disappear, but changing focus outside the input field was showing the password again.

**Comment by Karbi123** [comment]
I agree with you that when the focus is outside the password field, the password is visible. But when you hit the orange LOGIN button, the password disappears and you can't log in.
Did you try to hit the login button?

**Comment by Karbi123** [comment]
While populating the password field keepassxc first unmasks the password and populates it. The website rejects the unmasked password.
But when you enter the password manually, the password remains masked and the website accepts it.
So the problem is that the keepassxc unmasks the password and populating it.
How to force the keepassxc to not unmask the password while populating the password field?

**Comment by varjolintu** [comment]
I tried, but at least with invalid logins it seems to work normally. There's probably a page script that interferes with the fill, and maskes it if it's entered manually. For me the password is always masked. Not sure why it works different in your case.

**Comment by Karbi123** [comment]
I am not having this issue with all other websites, where the password remains masked. I am facing this issue with only this website.
I wonder how come your password is always masked??

**Comment by varjolintu** [comment]
I just retested it and the password isn't masked. So I can reproduce that. This is because the site is using `<input type="text">` as a password field which is not the standard way to do it. The masking is probably just made using scripts.

I'd suggest using Auto-Type for the login.

**Comment by Karbi123** [comment]
Ok....Thank You...
I will try with Auto Type

**Comment by Karbi123** [comment]
It works with Auto-Type. The password is masked. Thank You.
