### ISSUE TITLE
Browser Extension reports outdated version but CLI shows newest version

### ISSUE THREAD

**Issue by micsport13** [keepassxreboot/keepassxc-browser#1914]
## Expected Behavior

On the updates tab, it should show that my version is the same as the most recent version

## Current Behavior

It shows that I am running KeepassXC version 2.7.4, but my system reports that it is running 2.7.5, which is the most updated version.

## Possible Solution

Potentially it's caused by my browser because I was unable to update it due to GitLab maintenance but I believe this behavior was the case before as well.

## Steps to Reproduce (for bugs)

1. Open KeepassXC and unlock the DB
2. Open Browser and click on extension
3. Run `keepassxc --version` in terminal
4. Check status of version in browser extension settings and it shows the versions are mismatched

## Debug info

KeePassXC - System: 2.7.5  (Browser states version 2.7.4)
KeePassXC-Browser - 1.8.6.1
Operating system: Linux (Vanilla Arch)
Browser: Librewolf (Firefox Fork) v112.0.1-2

**Comment by droidmonkey** [comment]
Make sure you don't have two keepassxc running at the same time and maybe restart.

**Comment by micsport13** [comment]
Rebooting appeared to fix the issue.  Is there a reason why rebooting may have fixed the issue?

**Comment by droidmonkey** [comment]
You had two instances running. Most likely conclusion
