### ISSUE TITLE
Deny not remembering

### ISSUE THREAD

**Issue by witchpiggie** [keepassxreboot/keepassxc-browser#1915]
Selecting remember and clicking deny all, does not remember.
This was previously registered as an issue in #1701 
And apparently fixed with this pull [8273](https://github.com/keepassxreboot/keepassxc/pull/8273)

However, this seems to be present in the current versions.

## Current Behavior
Does not remember deny

## Steps to Reproduce (for bugs)
1. Goto site
2. click remember check box
3. click deny all
4. revisit site

## Debug info
KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.6.1
Operating system: Win
Browser: Brave (maybe more?)

**Comment by varjolintu** [comment]
This is already fixed with: https://github.com/keepassxreboot/keepassxc/pull/9136
