### ISSUE TITLE
Wrong order / labels of passwords on gmail's password input field when having multiple gmail accounts

### ISSUE THREAD

**Issue by heapifyman** [keepassxreboot/keepassxc-browser#1917]
## Expected Behavior

keepassxc-browser should display account labels in the same order for both gmail username input and gmail password input

## Current Behavior

keepassxc-browser shows the label of the account that was selected in the gmail username field at the top of the list of account in the gmail password field. But the label is wrong, the underlying password does not belong to that account.

## Steps to Reproduce (for bugs)

1. have multiple gmail accounts saved in keepassxc, say accountA, accountB, accountC
2. open gmail.com
3. press shortcut to select username - the order of accounts in the presented list is accountA, accountB, accountC
4. select accountC (last in the list) and press enter
5. press shortcut or icon to select password
6. notice that accountC is at the top of the list - the order is now accountC, accountA, accountB
7. select accountC (top of the list)
8. notice that the password is wrong
9. select accountB (last in the list), which was the position of accountC in step 4
10. notice that login succeeds

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.8.6.1
Operating system: Linux
Browser: LibreWolf, Brave

**Comment by varjolintu** [comment]
Is there any difference if you adjust the order options in the extension settings?

**Comment by CuriousDoggie** [comment]
I also had this issue with Gmail.

**Comment by advanced-media** [comment]
Have the same issue with google login (separated username-/password-steps). 

Regardless of "sort matching", if I choose NOT the first listed user, then in the password step: \
The password of the selected user seems to occur on first position.
- Selecting the first password row by **mouse-click** pastes the **correct** password.
- Selecting the first password row by **keyboard** pastes a **wrong** password.

**Comment by varjolintu** [comment]
Thanks for the reports. I got the issue fixed.
