### ISSUE TITLE
Path shown on the title bar is not dynamic

### ISSUE THREAD

**Issue by Karbi123** [keepassxreboot/keepassxc-browser#1920]
## Expected Behavior
The path shown on the title bar of the KeepassXC window should always reflect the path of the database. If the database changes, the new path should be shown on the title bar.

## Current Behavior

The path on the title bar reflects that of the old database. 
## Possible Solution

The path shown on the title bar should be dynamic and show always reflect the path of the current database.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
We show the path if there is no database name. We show the database name otherwise.

**Comment by Karbi123** [comment]
I deleted the database name.
Now, it shows only the file name, but not the full path.

**Comment by droidmonkey** [comment]
The full path is shown when hovering over the root group and I believe the tab itself when visible.

**Comment by Karbi123** [comment]
It would be nice to have a feature, to show a dynamic full path along with the file name on the title bar of the window, instead of hovering.
