### ISSUE TITLE
autocomplete="new-password" / autocomplete="off" not supported?

### ISSUE THREAD

**Issue by AdamPerkins** [keepassxreboot/keepassxc-browser#1921]
I have designed a webpage with form. I added to the form and to the input fields attributes like autocomplete="new-password" and/or autocomplete="off" to prevent autofilling.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

But there is always the keepassx icon to offer the insertion of username/password.

How can I prevent that or is it just not supported this way?

**Comment by droidmonkey** [comment]
Generally speaking we don't support paying attention to those labels because some sites use them to break password managers on purpose. You  can disable keepassxc for specific sites in the extension settings.
