### ISSUE TITLE
Detect authentik auth dialog input fields

### ISSUE THREAD

**Issue by tuxmainy** [keepassxreboot/keepassxc-browser#1922]
## Expected Behavior

The input fields of [authentik](https://github.com/goauthentik/authentik) authentication dialog are not detected by the browser plugin. All other used websites are working will.

## Current Behavior

Neither detects the plugin the input field by itself neither one could assign custom fields.

## Possible Solution

Detect the input fields.

## Steps to Reproduce (for bugs)

1. go to an authentik authentication dialog
2. try to login by browser plugin

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.6.1
Operating system: Linux
Browser: Firefox (LibreWolf)

![grafik](https://github.com/keepassxreboot/keepassxc-browser/assets/27895250/d43d69d3-53e6-457f-bc0f-748a4231d8ba)

**Comment by droidmonkey** [comment]
Authentik is adding the login form to the shadow DOM. Nothing we can do about this, the point of shadow DOM is to be inaccessible to extensions and other aspects of the site.

**Comment by tuxmainy** [comment]
If one is interested in a solution: https://github.com/goauthentik/authentik/issues/5864 . Put the flow forms in "browser compatibility mode"

**Comment by woodworker** [comment]
my admins told me "browser compatibility mode" is not an option, what now?

**Comment by varjolintu** [comment]
@woodworker Use Auto-Type.

**Comment by woodworker** [comment]
yeah - i think its a me problem, tiled window manager with keepassxc forced on a different desktop breaks autotype - ill copy username and password

**Comment by domints** [comment]
> Authentik is adding the login form to the shadow DOM. Nothing we can do about this, the point of shadow DOM is to be inaccessible to extensions and other aspects of the site.

It's interesting point, this issue was raised to me by my friend who's using KeePassXC, while I'm administrator of Authentik service.

It works properly with 1Password, in Firefox on Windows, so maybe this changed in the meantime and this statement is not true? Maybe there's known workaround?

**Comment by varjolintu** [comment]
@domints Try adding the URL site Site Preferences and enable Improved Input Field Detection. It parses Shadow DOM as well.

**Comment by domints** [comment]
Got the report from friend, that it worked, thanks! So this issue got actually fixed :D
