### ISSUE TITLE
More than one password for a single entry

### ISSUE THREAD

**Issue by Karbi123** [keepassxreboot/keepassxc-browser#1924]
## Expected Behavior

Many Bank websites require more than one password, for example, login password, transaction password, and profile password.
Now I can add an entry for the login password. But how can I store these extra passwords in that same entry? Here the domain will be the same but with different URLs within that domain.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
Use additional attributes in the entry. See here for how to connect this with the browser: https://keepassxc.org/docs/#faq-string-fields

**Comment by Karbi123** [comment]
I did all that as given in the documentation. But it is populating the login password instead of the string field (transaction) password.
I specified the transaction password as string field #1 in the browser extension. But it is not working. Please look at the screenshots of the website field and additional attributes in Keepassxc

![Bank Password Field](https://github.com/keepassxreboot/keepassxc-browser/assets/20335072/6023c6d9-4bd6-4fc8-9827-2d109c1a606f)

![Additional Attributes](https://github.com/keepassxreboot/keepassxc-browser/assets/20335072/ca3e40c5-e2b0-4389-acba-d1da8f8776bb)

**Comment by droidmonkey** [comment]
You need to setup the custom fields on the browser side. Remove the second : in your attr name as well, the name is actually not relevant

**Comment by Karbi123** [comment]
I did setup the custom fields on the Chrome browser extension.
If the name is not relevant then how does it matter with the second :  Even then I removed the second : in the attr name.
The option _"Return advanced string fields which start with "KPH: "_ is enabled, by default.
Still, it didn't work.

If the name is not relevant, then what are the matching criteria for the attr names to work? 

KeePassXC version: 2.7.5
KeePassXC-Browser version: 1.8.6.1
Windows 10 Pro 22H2 (64-bit)
Google Chrome Browser version:  114.0.5735.110 (Official Build) (64-bit)

**Comment by droidmonkey** [comment]
It is based on order not name. I just thought the second colon might be causing problems.

**Comment by Karbi123** [comment]
Then, what went wrong?
Why it is not working for me?
Any ideas to fix this?

**Comment by Karbi123** [comment]
It is not detecting the string field. The keepassxc icon doesn't appear on the field, even after I press Redetect login fields.
Any help?

**Comment by droidmonkey** [comment]
What website are you trying to use?

**Comment by Karbi123** [comment]
https://netbanking.netpnb.com/

**Comment by Karbi123** [comment]
More precise

https://netbanking.netpnb.com/corp/AuthenticationController?FORMSGROUP_ID__=AuthenticationFG&__START_TRAN_FLAG__=Y&__FG_BUTTONS__=LOAD&ACTION.LOAD=Y&AuthenticationFG.LOGIN_FLAG=1&BANK_ID=024

**Comment by Karbi123** [comment]
This is the subsequent screen where the transaction password is required to be entered

https://netbanking.netpnb.com/corp/Finacle?bwayparam=L2609L6786z8IZwlPF4mui6Dzg1O54D5ZU%2FT2WyGuqM%3D

**Comment by droidmonkey** [comment]
Due to the multiple pages here, your only option as I see it is to use Auto-Type and not the browser extension to file this field.

**Comment by Karbi123** [comment]
Does Auto-Type work for Additional Attributes??

**Comment by droidmonkey** [comment]
Yes of course, use the same `{S:attribute name}` syntax

**Comment by Karbi123** [comment]
I used the window association auto type as you said.
When I open the webpage, the Keepassxc icon appears on the field.

Then I press the global auto type hotkey, it displays the dialog with attribute. 
But when I double click or press enter nothing happens.
It doesn''t auto-type the password into the field.
But when I press the Keepassxc icon on the field,  it populates the login password, which is wrong. 

Please have a look at the screenshots.
Please let me know where I have gone wrong.

![20230615_083954](https://github.com/keepassxreboot/keepassxc-browser/assets/20335072/d71ab49e-1c84-40c2-9f7c-d8fdae0f4218)
![20230615_084024](https://github.com/keepassxreboot/keepassxc-browser/assets/20335072/434eef23-8712-4f92-ae81-54f57632d72b)

**Comment by droidmonkey** [comment]
Did you remove the `KPH: ` from the attribute name?

**Comment by Karbi123** [comment]
Nope.

**Comment by droidmonkey** [comment]
Well then you'll have to either remove that prefix or change your Auto-Type to `{S:KPH: Transaction Password}`

**Comment by Karbi123** [comment]
Great .....This worked.
Thank You very much for the support.

The text string after S: should match exactly with the attribute name.
It doesn't matter whether KPH: is there or not.
BTW what is the full form of KPH?
