### ISSUE TITLE
Only one entry is shown in autofill dropdown although there are multiple accounts / entries for that domain

### ISSUE THREAD

**Issue by AlexanderOpran** [keepassxreboot/keepassxc-browser#1925]
I have saved a couple of entries for the same domain (google.com), multiple accounts. Whenever I try to login, I only have 1 account shown in the username / password autofill dropdown that the extension provides (and autofill will always just autofill the credentials for that one, ignoring for example even if I entered a completely different username).

is this a bug? Is it intended? Can I somehow have the whole list of accounts / entries for that domain displayed in the dropdown? Right now the only solution is the manually opne KeePassXC, go to that entry and manually copy and paste the username and password. 

KeePassXC-Browser Version: 1.8.6.1
KeePassXC Version: 2.7.5
Operating system: Windows 11
Browser: Chromium

**Comment by droidmonkey** [comment]
Make sure the other entries don't have more specific url domains. Also make sure you haven't previously denied access to them. Open the entries for editing and go to properties tab and then delete any custom data for the browser.

**Comment by AlexanderOpran** [comment]
Seems the issue was from the URL, one was with www and one was without www (I presume it is intended).
