### ISSUE TITLE
Notify user when no logins are found for a given site

### ISSUE THREAD

**Issue by Yentis** [keepassxreboot/keepassxc-browser#1927]
I was trying to get the extension to work on [https://www.gog.com/](url), but nothing was showing despite entering this url in KeePassXC. After debugging the extension, I noticed that no logins were found. With some further debugging using breakpoints, I found out that the login field wasn't actually from gog.com but login.gog.com despite still having gog.com in the address bar.

## Expected Behavior
Some indication of why no entries are shown when selecting a login field.

## Current Behavior
Nothing happens at all when clicking in the login field.

## Possible Solution
It would be useful if the extension could show some sort of message like "No logins found for \<url\>" to remedy this case.
If intrusiveness is an issue, it could show only if you click the key icon in the login field manually.

## Debug info
KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.6.1
Operating system: Win
Browser: Brave

**Comment by varjolintu** [comment]
I think this would be a little too much. User would get a notification from every page that has no credentials. When the Username Icon in the login field is colored as gray it means there are no credentials for the site. So there's already an indication for that.

**Comment by Yentis** [comment]
That's true (even though it doesn't always turn gray), but there's no way to know for what url it failed to find credentials. As seen in the site above there's a mismatch between the url in the address bar and the url of the login field which the user can't easily know about.

**Comment by varjolintu** [comment]
@Yentis Oh, that's true. The notification could show the actual URL. It might differ, as you said. I'll see what I can do. Debug messages could also show the URL. Now it just logs "Credential list is empty." error.
