### ISSUE TITLE
Random text fields get auto-filled with username

### ISSUE THREAD

**Issue by jlindgren90** [keepassxreboot/keepassxc-browser#193]
## Expected Behavior
Only username fields should get auto-filled with username.
In a previous version (1.1.3?) it seemed that the plugin would only look for a username field if there was also a password field on the same page.  This wasn't perfect, but it's better than what v1.1.5 is doing.

## Current Behavior
Random text fields get auto-filled with username.

Some examples:
The "Estimated time" field on a Redmine bug edit got auto-filled: https://i.imgur.com/cldlg4i.png
The title field of this bug has gotten auto-filled with my GitHub username THREE TIMES while I've been typing this report (overwriting the title I entered!): https://i.imgur.com/k1BVu5m.png

v1.1.4 was even worse (for example, auto-filling the main search field on google.com) but it seems that the general problem wasn't fixed, only specific fields (like search fields) blacklisted.

## Possible Solution
Revert to the behavior of v1.1.3

## Steps to Reproduce (for bugs)
1. Click the "New Issue" button in this GitHub project with GitHub credentials saved and auto-fill enabled

## Debug info
KeePassXC - 2.3.3 (irrelevant)
keepassxc-browser - 1.1.5
Operating system: Linux
Browser: Firefox
Proxy used: I don't think so? How would I tell?

**Comment by tohn** [comment]
I also have this issue. Whenever this happens, I have to kill the browser tab so I can use the browser again ...
