### ISSUE TITLE
Lots of pages that login through those kinds are not filled by Plugin 

### ISSUE THREAD

**Issue by tcAllmight** [keepassxreboot/keepassxc-browser#1930]
version:1.8.6.1

I've noticed that the keepassXC browser plugin works fine on most pages, but some pages are not filled. After some rough comparison, I found that such websites generally do not have a separate login page, but use a js-like pop-up window (not a new page or program, but the kind embedded in a webpage). At this time, plug-ins cannot be used, whether it is key icon is clicked or other ways. Only the global padding  setted in Keepassxc can work,which meanings not work by browser itself. 1password bitwarden, and chrome's built-in fill can recognize this type of window.
In some countries ,this kind of login windows is popular in developer ,So many websites cant work correctly.

**Comment by droidmonkey** [comment]
It is likely the popup window is actually loading in a different URL than that main page. For example, webpage.com versus login.webpage.com. We have seen a lot of times where the URL entered into KeePassXC is https://www.webpage.com which _will not work_ with login.webpage.com. Make sure that isn't the case for your examples.
