### ISSUE TITLE
Credentials are not filled in basic auth dialog in Firefox

### ISSUE THREAD

**Issue by TheHacker66** [keepassxreboot/keepassxc-browser#1935]
## Expected Behavior

I should be able to fill in credentials from Keepass not only with web forms but also with the browser's basic auth dialog.

## Current Behavior

When being asked for credentials on a basic auth protected website, I get the browser's prompt, Keepass asks for an authorization which I give, but then credentials are not filled in.

## Steps to Reproduce (for bugs)

1. Try to access a basic auth protected website
2. ???

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.6.1
Operating system: Win64
Browser: Mozilla Firefox 116.0

**Comment by droidmonkey** [comment]
You need to update to 2.7.5

**Comment by TheHacker66** [comment]
Just did, nothing's changed.

**Comment by droidmonkey** [comment]
Review this issue thread, you might need to apply some changes based on the discussion: https://github.com/keepassxreboot/keepassxc-browser/issues/1397

**Comment by TheHacker66** [comment]
Enabling the option to autofill and submit basic auth credentials made everything work. Suggest to add an entry to the faqs and troubleshooting tips and maybe enable said option as deafult.

**Comment by droidmonkey** [comment]
@varjolintu need to make this ux better / more understandable. I think "auto fill" is incorrect here. It should be "Allow filling HTTP Basic Auth Credentials", the automatic part might be throwing people off

**Comment by varjolintu** [comment]
> @varjolintu need to make this ux better / more understandable. I think "auto fill" is incorrect here. It should be "Allow filling HTTP Basic Auth Credentials", the automatic part might be throwing people off

I agree. Making some changes.
