### ISSUE TITLE
Clicking on locked icon opens both the main KeePassXC application and a second unlock database dialog window

### ISSUE THREAD

**Issue by MarkWieczorek** [keepassxreboot/keepassxc-browser#1946]
## Current Behavior
Here is the situation: The KeePassXC database is locked and the application is minimized. Clicking on the locked KeePassXC icon in a browser username field does the following:

1. It brings the KeePassXC application to the foreground which shows the standard "unlock database" dialog screen,
2. An additional "unlock database" dialog window, which is smaller than the main KeePassXC application window, opens and is superposed on top the main KeePassXC application. This smaller window shows the same "unlock database" dialog as the main application window.

## Expected Behavior
Only a single "unlock database" dialog window should open, not two. One of the two is redundant. Of the two windows that open, the smaller window is perhaps the most useful for this situation (there is no need to interact with the KeePassXC window: I only want to unlock the database).

## Debug info

KeePassXC - 1.8.7
KeePassXC-Browser - 2.7.5
Operating system: MacOS
Browser: Firefox

Here is a screenshot if the above is not clear
![screenshot](https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/0558bc3d-a403-485a-bda7-7791dc6c943f)

**Comment by droidmonkey** [comment]
Unfortunately with macOS we need to bring up the main window to show the unlock dialog as well. This is tracked on the keepassxc repository already.

**Comment by MarkWieczorek** [comment]
https://github.com/keepassxreboot/keepassxc/issues/9297

**Comment by MarkWieczorek** [comment]
Could you let me know where this is being tracked? I just searched through the issues and found two that are the same as this one, but they are both closed, even though the problem was never resolved.

**Comment by droidmonkey** [comment]
The two you mentioned are not this issue
