### ISSUE TITLE
[Broken Site] account.here.com

### ISSUE THREAD

**Issue by OdinVex** [keepassxreboot/keepassxc-browser#1950]
I can't get KeePassXC to either detect or allow choosing custom inputs for account.here.com.

First issue: Account creation doesn't trigger a query to save a new entry.
Second issue: Attempting to choose custom input fields won't show any selection around the inputs. The KeePassXC "Choose a Custom Login Field" banner shows and operates correctly, but fields aren't selectable.

KeePassXC - 2.7.5
KeePassXC-Browser - 2.7.5
Operating system: Linux x64, Manjaro, KDE
Browser: LibreWolf (Firefox)

Edit:
The browser console showed nothing useful until I attempted to right-click an input and try to force KeePassXC to fill in something (anything, just to see how it'd detect fields). After trying that, the site's JS throws an error as if it is attempting to intercept or hook (or whatever). Maybe the site has some 'protection' \*eyeroll\* stuff going on.

**Comment by varjolintu** [comment]
This is because the page is not using standard `<input>` elements. The login fields are implemented with `<hds-input>` elements which are not regognized.

**Comment by droidmonkey** [comment]
We do "walk" the entire DOM. They may also be inside a shadow dom that is deployed via Javascript. We can't do anything about that, shadow dom is hidden from view to extensions.

**Comment by varjolintu** [comment]
> > We do "walk" the entire DOM. They may also be inside a shadow dom that is deployed via Javascript. We can't do anything about that, shadow dom is hidden from view to extensions.
> 
> Any way to tell? Unfamiliar with shadow DOM and such.

If you open the Web Inspector on the element, it will show where it's located in the DOM. In this case it's inside Shadow DOM. (For some reason my browser did not show the Shadow DOM yesterday, but now I can clearly see the `<input>` elements are inside it.)

**Comment by varjolintu** [comment]
This issue can be tracked in #446.

**Comment by varjolintu** [comment]
@OdinVex In this case no, because extension does not know the fields which it should fill.

**Comment by varjolintu** [comment]
The only way to do this is to parse _all_ elements form the page and look for the Shadow DOM, which is very time-consuming. Another way would be to add support for non-standard `hds-input` node. I have no idea how widely it is used.

**Comment by varjolintu** [comment]
> > The only way to do this is to parse _all_ elements form the page and look for the Shadow DOM, which is very time-consuming. Another way would be to add support for non-standard `hds-input` node. I have no idea how widely it is used.
> 
> Maybe per site setting of 'parse all for shadow dom' or on specific URI might be a stop-gap measure that would be more seamless? Off by default, manually turn on, maybe even remember the chain of elements to access each shadow-dom entry necessary for quicker walking. At the very least, 'parse for all shadow dom' would get things working.

We already have a "Improved Input Field Detection" in Site Preferences. That could be extended to Shadow DOM with all elements. Gotta try it out.

**Comment by varjolintu** [comment]
See: https://github.com/keepassxreboot/keepassxc-browser/pull/1968.
