### ISSUE TITLE
In KDE Neon, KeepassXC doesn't open automatically for entering my master password when trying to login and KeepassXC is closed

### ISSUE THREAD

**Issue by Terkyz** [keepassxreboot/keepassxc-browser#1951]
## Expected Behavior

It is my understanding, the KeepassXC extension should open my KeepassXC database if it is not currently open, to enter my master password and access my logins. But in my case it is not like that, when I click on the symbol to fill in login information with my database closed, I simply receive a message from the extension saying "Error! Not connected to KeepassXC", and I want to clarify that everything is already configured, and with my DB open everything just works fine. I want to mention that I have not changed any configuration just from the minimum for the extension to work.

## Current Behavior

When pressing the button in the KeepassXC extension to fill in my login information, I receive "Error! Not connected to KeepassXC" when KeepassXC should instead open and allow me to enter my master password to complete the login.

## Steps to Reproduce (for bugs)

1. Try to login anywhere with my KeepassXC database closed 
 2. Click on the KeepassXC icon next to the login box 
 3. I get the error ¨Error! Not connected to KeepassXC¨

(If I can later I will add a video demonstrating the problem, I was going to do it but it exposes a lot of personal information and I have to edit it).

## Debug info

KeePassXC - {2.7.5}
KeePassXC-Browser - {1.8.7}
Operating system: Linux-KDE Neon
Browser: Firefox

**Comment by varjolintu** [comment]
What does the JavaScript Console say, from both background and content scripts?

**Comment by Terkyz** [comment]
Where can I see that? I already have the Debug logging option checked in KeepassXC-Browser.

**Comment by droidmonkey** [comment]
If it's not connected then that means the extension cannot talk to KeePassXC at all. You need to run-through the browser troubleshooting guide. Transferring to browser repo, this isn't an application problem.

**Comment by droidmonkey** [comment]
If it's not connected then that means the extension cannot talk to KeePassXC at all. You need to run-through the browser troubleshooting guide. Transferring to browser repo, this isn't an application problem.

**Comment by Terkyz** [comment]
No, KeepassXC-Browser is already connected to my KeepassXC database and within the KeepassXC-Browser settings I can see in Connected Databases the database connected to the extension, and in fact, if I have the database open everything works perfectly as it should, but if the database is closed, KeepassXC-Browser doesn't open KeepassXC automatically to allow me to type my database's master password, but I have to open it manually and enter the password, after that, everything works fine.

**Comment by varjolintu** [comment]
Copy/paste the logs here, please.

**Comment by Terkyz** [comment]
I couldn't find where the logs are, but I hope [this](https://imgur.com/RVzRPZ5) video helps.

**Comment by droidmonkey** [comment]
Being "connected" in the settings is more like being registered. That does NOT mean you are connected to the application. The error message you received tells me that. Are you sure keepassxc is running?

**Comment by varjolintu** [comment]
@Terkyz If you close KeePassXC entirely, there's no way the extension can connect to it.

**Comment by Terkyz** [comment]
Oh ok, I thought that KeepassXC-Browser in case the registered database was closed, it would open KeepassXC automatically as if it was a popup window and once I entered the master password of my database, the focus would return back to the browser.

I mean, I understand that KeepassXC-Browser cannot access my database unless it is open, but I thought that in case it was closed it would make it easier for me to find the program in my list of programs and open it directly for me to enter my master password.

**Comment by varjolintu** [comment]
Related feature request: https://github.com/keepassxreboot/keepassxc-browser/issues/707

**Comment by Terkyz** [comment]
To anyone who wants to have a similar experience before implementing #707 I recommend enabling in KeepassXC settings KeepassXC to boot to system, boot minimized, boot to tray, the close button minimize (thus minimizing the tray) and that After entering the master password, it will automatically close. 

 This is the closest I've found so far to KeepassXC launching automatically, and it works for me.
