### ISSUE TITLE
Multiple bugs

### ISSUE THREAD

**Issue by dement6d** [keepassxreboot/keepassxc-browser#1954]
## Current Behavior
- I get the pop up if i want to load in credentials for a website but no matter what i click the pop up very often pops up every time i switch onto the tab, so switching back and forth between tabs is really annoying.
- Often, the credentials don't even load in after i press allow, even when i choose custom login fields or right click and press on fill credentials.
- The "New" button for saving new credentials is also very bugged. It often doesn't work unless you press it twice or something, I'm not sure, the behavior is very weird. Sometimes it works quite a bit later after dismissing the popup

## Debug info

KeePassXC - Version 2.7.5
KeePassXC-Browser - 1.8.7
Operating system: Archcraft (linux 6.3.9-arch1-1)
Browser: Brave, Version 1.55.13 Chromium: 115.0.5790.40 (Official Build) nightly (64-bit)

**Comment by varjolintu** [comment]
> I get the pop up if i want to load in credentials for a website but no matter what i click the pop up very often pops up every time i switch onto the tab, so switching back and forth between tabs is really annoying.

You can increase the timeout extension remembers credentials. After the timeout, credentials are cleared from the memory and asked again.

> Often, the credentials don't even load in after i press allow, even when i choose custom login fields or right click and press on fill credentials.

This is a known bug, and sadly there's no workaround for it. Except to close & reopen the database.

> The "New" button for saving new credentials is also very bugged. It often doesn't work unless you press it twice or something, I'm not sure, the behavior is very weird. Sometimes it works quite a bit later after dismissing the popup

Not sure what you mean by this. Credentials are asked to be saved, but also asked to access to?

**Comment by varjolintu** [comment]
Let's reopen this if some response is received.
