### ISSUE TITLE
Arc browser support

### ISSUE THREAD

**Issue by Jonhy75** [keepassxreboot/keepassxc-browser#1955]
## Expected Behavior
The KeepassXC browser extension should work with [Arc, a Chromium based browser](https://arc.net/)

## Current Behavior
The extension cannot connect to KeePassXC. Chrome and Chromium are enabled in KeePassXC. Testing the extension in a regular Chrome installation works as expected.

<img width="464" alt="Capture d’écran 2023-08-04 à 15 01 54" src="https://github.com/keepassxreboot/keepassxc-browser/assets/37046154/b220ad19-9c6c-4b45-9643-7c8b33b10b97">

## Possible Solution
I tried to setup the custom browser to point to ~/Library/Application Support/Arc/User Data/NativeMessagingHosts/ without change.

## Steps to Reproduce (for bugs)

1. Install Arc web browser
2. Install KeepassXC
3. Install KeepassXC-browser extension
4. Open KeepassXC database
5. Open settings and activate browser integration chromium
6. Click on browser extension

## Debug info

KeePassXC - 2.7.5 
KeePassXC-Browser - 1.8.7 
Operating system: Apple M2 Pro, macOS Ventura 13.5 Browser: Arc Version 1.2.1 Chromium Engine Version 107.0.5304.122

**Comment by droidmonkey** [comment]
We will not support this browser natively. You need to use the custom browser definition.
