### ISSUE TITLE
[RESOLVED] forum.manjaro.org - KeePassXC-Browser can't find relevant entry in spite of correct URL

### ISSUE THREAD

**Issue by KataFF** [keepassxreboot/keepassxc-browser#1958]
Disclaimer: I've checked all the points in [the Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide); The only thing that did not match was that `~/.config/firejail/firefox.local` does not exist, but I'm on Manjaro Linux and I don't use FireJail (don't even have it installed); KeePassXC-Browser also works fine with other websites, so I don't think that's the issue.
I also checked #1358 , but I think the issue is not directly with the website itself and therefore decided to create this issue.

## Expected Behavior
On https://forum.manjaro.org/ , a user can log in via a "Log In" button, which opens the login popup. The KeePassXC icon appears next to the username field, and clicking on it with the password database open in the background and connected to the KeePassXC-Browser should suggest credentials from the database, and enter(fill) the the username & password.

## Current Behavior
The login window pops up, the KeePassXC icon appears, and upon clicking it an "Error!No logins found. https://forum.manjaro.org" message appears and nothing else happens. Everything depicted on a screenshot below:
![The issue](https://github.com/keepassxreboot/keepassxc-browser/assets/62726159/6cbc5878-583c-423a-87ff-c43ea2fa5005)

Here's the relevant entry in KeePassXC:
![Screenshot from 2023-08-09 17-25-14](https://github.com/keepassxreboot/keepassxc-browser/assets/62726159/1b547115-e501-4aef-a1e7-2765d7765ce5)

## Possible Solution
I have no idea, which is why I brought myself to spend an hour of my time writing this issue. See some steps I tried below in hope of fixing this very cryptic issue:
- Remove the database connection in the KeePassXC-Browser Firefox plugin settings webpage
- Manually choosing the login fields with the yellow "Choose custom login fields" button on the KeePassXC-Browser login field, and selecting the login/passwords field respectively.
- Quadruple-check the correctness of the URL, keepassxc-proxy running, all the config files mentioned in the Troubleshooting guide, Javascript console
- Restart KeePassXC, restart Firefox

## Steps to Reproduce (for bugs)
0. Create a "Manjaro Forums" entry in your KeePassXC database, and set `https://forum.manjaro.org/` as its URL. Enter some login data so that we can later observe the KeePassXC-Browser plugin doing it's job (filling in the login fields).
1. Open https://forum.manjaro.org/ in Firefox, with the KeePassXC-Browser extension installed and set-up per [the guide](https://keepassxc.org/docs/KeePassXC_GettingStarted#_setup_browser_integration) (this includes getting your database connected, and keeping the database unlocked in the background).
2. Open the login pop-up by clicking on the "Log In" (translated to your locale) button in the top-right corner of the website UI.
3. Click the KeePassXC icon to the right of the Email / Username field.
4. Observe the error depicted in the screenshot above.

#### On the `https://forum.manjaro.org/` website, upon clicking the KeePassXC icon next to the login field a few times:
```
[Error fill.js:197] KeePassXC-Browser - NotSupportedError: Operation is not supported [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
```
#### In `about:debugging#/runtime/this-firefox` and "Inspect" next to KeePassXC-Browser:
```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:317:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/background/client.js)
KeePassXC-Browser: Server public key: <I redacted this, the key probably should not be shared online> [keepass.js:435:17](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/background/keepass.js)
[Error ] KeePassXC-Browser - No content script available for this tab. 2 [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
[Error client.js:175] KeePassXC-Browser - 15: No logins found [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 3 [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
[Error client.js:175] KeePassXC-Browser - 15: No logins found [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
[Error ] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:145:13](moz-extension://3ff25167-3858-48a9-a33a-3cce45743113/common/global.js)
<The last two lines/error messages repeat themselves over and over>
```

### From "Help > About > Debugging info" in KeePassXC desktop app:
```
KeePassXC - Version 2.7.5
Revision: 9d0537b

Qt 5.15.10
Debugging mode is disabled.

Operating system: Manjaro Linux
CPU architecture: x86_64
Kernel: linux 6.5.0-1-MANJARO

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.1.1
```
### From the Firefox extension's "Settings > About" page:
```
KeePassXC - 2.7.5
KeePassXC-Browser - 1.8.7
Operating system: Linux x86_64
Browser: Mozilla Firefox 116.0
```
### Extra info by me, probably not that relevant but won't hurt:
Operating system: newest Manjaro Linux at the time of writing this (21 I think? It's a rolling-release so I never remember the version info), all packages and AUR packages up-to-date.
`uname -a` ending (kernel version): 6.5.0-1-MANJARO #1 SMP PREEMPT_DYNAMIC Mon Jul 24 20:16:38 UTC 2023 x86_64 GNU/Linux
Manjaro package branch: `stable`
Browser: Mozilla Firefox 116.0 (64-bit)
Desktop Environment: GNOME 44.3
Server: Wayland (note: Firefox ran in native Wayland mode with the MOZ_ENABLE_WAYLAND=1 env variable set)

Also, just wanted to say "Thank you" to all the contributors who made KeePassXC and this browser extension possible

**Comment by droidmonkey** [comment]
Go to the entry in KeePassXC (your manjaro one) and edit it, go to properties tab, then delete the browser custom data shown. Should work after that.

**Comment by KataFF** [comment]
> Go to the entry in KeePassXC (your manjaro one) and edit it, go to properties tab, then delete the browser custom data shown. Should work after that.

Thank you, this was it! 

**I can confirm that the extension works now.**
I did not know that the per-site browser extension preferences are stored in the "Properties" panel (it's not even visible in the default entry edit view, didn't notice you can scroll the categories). Perhaps it'd be nice to be able to view those preferences in a more user friendly manner than a JSON structure hidden somewhere within an entry, but that's a discussion for another issue.

Thanks again for the help! Closing the issue now, and changing the title to [RESOLVED].

**Comment by varjolintu** [comment]
> > Go to the entry in KeePassXC (your manjaro one) and edit it, go to properties tab, then delete the browser custom data shown. Should work after that.
> 
> Thank you, this was it!
> 
> **I can confirm that the extension works now.** I did not know that the per-site browser extension preferences are stored in the "Properties" panel (it's not even visible in the default entry edit view, didn't notice you can scroll the categories). Perhaps it'd be nice to be able to view those preferences in a more user friendly manner than a JSON structure hidden somewhere within an entry, but that's a discussion for another issue.
> 
> Thanks again for the help! Closing the issue now, and changing the title to [RESOLVED].

I am going to make some changes to this. The Browser Integration page should show directly what sites are Allowed/Denied etc.
