### ISSUE TITLE
Extension on firefox PPA not working

### ISSUE THREAD

**Issue by Welved** [keepassxreboot/keepassxc-browser#1959]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Enabled all browser integrations
2. Opened Firefox and installed extension
3. I get error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Operate my database via extension as I do with any other browser.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Error: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I tried the snap, flatpak and now the PPA. None of them work with KeepassXC. The PPA used to work atleast, but not anymore.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.5
Revision: REVISION

[NOTE]: # ( Pick choices based on your environment )
Operating System: Ubuntu 22.04 (Linux)
Desktop Env: Gnome
Windowing System: Wayland

**Comment by varjolintu** [comment]
Please check if AppArmor has something to do about your problem: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

**Comment by Welved** [comment]
> You didn't provide your distro information, but please check if AppArmor has something to do about your problem: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

The version of KeepassXC that I have installed is the Ubunt PPA version and my OS Ubuntu 22.04

**Comment by varjolintu** [comment]
Then go through the troubleshooting guide and report your findings.

**Comment by varjolintu** [comment]
Closing the issue. If the problem still persists, we can take another look.
