### ISSUE TITLE
Let Ubuntu users know of AppArmor profile changes being needed for Firefox integration

### ISSUE THREAD

**Issue by arshadrr** [keepassxreboot/keepassxc-browser#1960]
## Summary
In the browser integration tab, if Firefox is selected by Ubuntu users, it would be great if it informs us we need to make some modifications to the AppArmor profile for Firefox as described [in the wiki](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu). This would save having to work through the entire wiki page.

## Context
I'm a new Ubuntu user and spent quite a while trying to get browser integration working. I had no idea Ubuntu comes with AppArmor by default (much less what AppArmor was). Similar to how KeepassXC when installed through Snap in the browser integration tab links to a script that needs to be run to get it to work, it would be helpful to have this.

Firefox comes installed through Snap on new Ubuntu installations and this isn't supported, so installing through the PPA I imagine will be the most frequently used method by KeepassXC users. So, this will affect many and should be placed more prominently in the browser integration tab.

**Comment by arshadrr** [comment]
@droidmonkey I don't think this  issue should be under the keepassxc-browser tracker. I was suggesting something informational be shown in the "browser integration" tab in the settings for the desktop app. Sort of like the warning about browsers installed using snap:
![Screenshot](https://github.com/keepassxreboot/keepassxc-browser/assets/61007604/dc6d28fe-5980-4f7a-b05f-3eb6b537f861)

**Comment by droidmonkey** [comment]
That warning needs to be removed at this point. I am not a fan of baking generic warnings in the application. I'm also unclear why Firefox would auto deploy an apparmor profile that blocks basic functionality of the browser (native messaging)
