### ISSUE TITLE
Can't update newer version due to needing permissions

### ISSUE THREAD

**Issue by Janno51** [keepassxreboot/keepassxc-browser#1962]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Let's reopen the ticket after you actually provide some more information.

**Comment by Janno51** [comment]
By more information, I am hoping you need more details about what my problem is. I am trying to update KeePassxc and when I download it from the site the download says it needs permission. I have been attempting to figure this out all morning and I am about to give up. Is this something you can help with? I am using a Macbook Pro with the M1 chip if that is needed for a reply.

**Comment by droidmonkey** [comment]
Choose a download folder that you can write to?

**Comment by Janno51** [comment]
I don't get an opportunity to choose a folder. I click the link to download
the upgrade and it just says it needs permission.
*Jan Williams*

**Comment by varjolintu** [comment]
Change your browser settings so you can choose a download directory?

Seems this issue is not related to the extension at all.

**Comment by Janno51** [comment]
Thank you. I went into my browser settings and have it asking me now what
folder to send downloads and I created a folder. It was finally saved. The
only issue I'm working with now is being able to locate the upgraded
version on my dock. Any thoughts? Again, thank you for your help.
*Jan Williams*

**Comment by varjolintu** [comment]
Locate upgraded version on your dock? You should start KeePassXC where you moved the KeePassXC.app inside the .dmg file and pin it to the dock when the icon appears.

**Comment by Janno51** [comment]
Thanks. Done. You have been very helpful Sent from my iPhoneOn Aug 16, 2023, at 15:19, Sami Vänttinen ***@***.***> wrote:﻿
Locate upgraded version on your dock? You should start KeePassXC where you moved the KeePassXC.app inside the .dmg file and pin it to the dock when the icon appears.
