### ISSUE TITLE
Cannot connect to KeePassXC database

### ISSUE THREAD

**Issue by aljustiet** [keepassxreboot/keepassxc-browser#1963]
## Overview
I am experiencing an issue where I cannot connect to my KeePassXC database. This problem occured when I wanted to integrate brave with keepassxc database, and I have not been able to find a solution.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open KeePassXC.
2. Attempt to connect to the database.
3. Observe the connection failure.

## Expected Behavior
Expect to connect to the database without any issues.

## Actual Behavior
I receive an error message (KeePassXC-Browser has encountered an error: Key exchange was not successful.) and cannot access my database.

## Context
- KeepassXC version: 2.76
- Revision: dd21def
- OS: MacOS Sonoma beta 5
- Browser: Brave v1.57.47

**Comment by varjolintu** [comment]
There are tons of similar issues here. Try to enable support for Chrome and Chromium in KeePassXC and try again. Sometimes Brave is not using its own configuration folders.
