### ISSUE TITLE
Chromium: PW input not working on appleid.apple.com or www.icloud.com/mail when extension "site access" is set to "on click"

### ISSUE THREAD

**Issue by bf** [keepassxreboot/keepassxc-browser#1964]
## Expected Behavior

Right click on password field -> keepass ->Fill Password Only does not work when on https://appleid.apple.com/ or https://www.icloud.com/mail/

Selection of custom input field does not work on this page

## Current Behavior

Nothing happens, I need to open keepass app and copy paste password manually

## Possible Solution

Improve detection

## Steps to Reproduce (for bugs)

1. go to https://www.icloud.com/mail/
2. notice that email field is not automatically input by the keepass browser extension
3. put in email manually
4. press next
5. notice password is not put in manually by keepass browser extension
6. right click on password input -> contecxt menu -> keepass -> Fill Password Only
7. password field stay blank

## Debug info

KeePassXC - 2.7.5
KeePassXC-Browser Version: 1.8.7
Operating system: arch linux
Browser: Chromium Version 116.0.5845.96 (Official Build) Arch Linux (64-bit)

There was a related issue in the past https://github.com/keepassxreboot/keepassxc-browser/issues/1546 which was solved by a workaround of using a different login page for apple.com. now it seems apple has changed their login to a unified portal which is not working with the keepass chrome browser extension

**Comment by varjolintu** [comment]
Are you using `https://idmsa.apple.com` as your entry URL?

**Comment by bf** [comment]
Maybe you didnt see my edit referencing the old workaround in issue #1546 which does not work any more.

https://idmsa.apple.com forwards to https://appleid.apple.com/ then a click on login forwards to https://appleid.apple.com/sign-in which has exactly same login field as https://www.icloud.com/mail/

The login fields dont get detected. When I right click "Fill Password Only" a question mark appears on the keepassxc toolbar icon.
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/464537/372186a8-43df-4b14-88e0-f844ad216b00)

**Comment by bf** [comment]
Thanks, I found the issue. I've set the extension to "read and change all data on websites: on click" and not to "always". See screenshot. When setting it to always it works. 

Obviously this has big security implications, because I like to enable it on click only for sites I trust, not for all random sites.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/464537/fea2f912-8431-4b59-8f5b-5d0e4d4e16be)

**Comment by bf** [comment]
I want to point out that "on click" works fine with all other websites I'm using.

**Comment by varjolintu** [comment]
This is probably because Apple is using `iframe` element for the login elements. It's probably only working with the main content script or background script, and is not triggering the possibility to allow the site from the popup in these cases.

**Comment by bf** [comment]
Thank you. So this seems to be a chromium bug, because when user clicks on the toolbar icon to enable extension for specific page, it should be enabled for that page and all it's currently rendered sub-pages (at least on same domain?!).

Nothing for fix here for KeepassXC it seems.

Thanks for your very quick response time and your kind help. Keep up the good work, I love the extension.
