### ISSUE TITLE
Problem with links of url's in KeePassXC

### ISSUE THREAD

**Issue by InekeVos** [keepassxreboot/keepassxc-browser#1967]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by InekeVos** [comment]
The Url doesn't open when I click the link to open it. it doesn't  matter what item I choose. All items referring to passwords have this problem lately. Before it worked correct.
KeePassXC - 2.7.4
Operating system: Win64
Browser: Microsoft Edge 116.0.1938.54

**Comment by droidmonkey** [comment]
Update to 2.7.6
