### ISSUE TITLE
Icon not shown in Firefox 116.0, but extension is working fine

### ISSUE THREAD

**Issue by purejava** [keepassxreboot/keepassxc-browser#1972]
## Expected Behavior
Extension is installed in FF and is working, icon should be shown

## Current Behavior
Incon does not show up

![2](https://github.com/keepassxreboot/keepassxc-browser/assets/1822238/9c3ed0b2-fa03-4f86-ad09-0d875c22bcaf)

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Linux aarch64
Browser: Mozilla Firefox 116.0

**Comment by droidmonkey** [comment]
You need to do it yourself, thanks Firefox...

https://support.mozilla.org/en-US/kb/extensions-button#w_manage-pinned-extensions

**Comment by purejava** [comment]
Oh, yeah. Thanks. I think I clicked everywhere else through all other options.
