### ISSUE TITLE
Filling with Autocomplete Menu disabled does not fill the whole combination

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#1973]
## Expected Behavior
I expect to fill usernames and passwords.

## Current Behavior
Filling of logins is not working well since I upgraded recently.

1. It works from the toolbar button
2. If I use the keyboard shortcut or the right-click menu for "Fill username and password" then it fills the username into wherever my cursor is. If there are multiple logins it does not show a menu it just picks one.
3. If I do "Fill password only" then it puts the password into wherever my cursor is, even if that's the username field. Again it doesn't show a menu.

## Steps to Reproduce (for bugs)
As above. Here are some of my settings:

- OFF Activate username field icons.
- OFF Activate autocomplete for username fields
- ON Auto-submit login forms

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Linux x86_64
Browser: Mozilla Firefox 117.0

**Comment by varjolintu** [comment]
You just updated Firefox to 117? Please close Firefox and KeePassXC, and start them again. Sometimes during the browser update with Firefox some strange things can happen.

I cannot reproduce this on my computer.

**Comment by varjolintu** [comment]
Sure, debug logs from background and content scripts when you have enabled Debug Logging in the extension settings. I'm interested to see what happens during the context menu fill.

**Comment by AdamPS** [comment]
Sorry you are right - when I enable that option it works, thanks.

I had misunderstood that option - the sub-text says "Show a dropdown list containing available credentials for all username fields on a page." and I got it mixed up with "Activate username field icons.".

Even so, the behavior with the option disabled seems bugged - even when I only had one possible completion it filled data in the wrong place.

**Comment by AdamPS** [comment]
Great thanks
