### ISSUE TITLE
Credentials popup menu misaligned in Firefox

### ISSUE THREAD

**Issue by DarkPreacher** [keepassxreboot/keepassxc-browser#1975]
## Expected Behavior

Credentials popup menu aligned somewhere near login/password fields.

## Current Behavior

It appearing under all page contents, on the bottom of the page, 
<details><summary>for example:</summary>
<p>
<img src="https://github.com/keepassxreboot/keepassxc-browser/assets/301685/3e6a3031-9994-45e7-8bd0-e61d56ac32d0">
</p>
</details> 

## Steps to Reproduce (for bugs)

1. Click login field on any site.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Win
Browser: Firefox 117

**Comment by varjolintu** [comment]
URL for a page where this happens?

**Comment by DarkPreacher** [comment]
It happens to me on any site with login form.
URL from example is `https://login.oracle.com/mysso/signon.jsp`, also `https://account.msi.com/login`, 
<details><summary>as another example</summary>
<p>
<img src="https://github.com/keepassxreboot/keepassxc-browser/assets/301685/d51a3100-d188-449a-be00-7cf462770177">
</p>
</details> 
or any other site.

**Comment by varjolintu** [comment]
Both sites work just fine for me. Please enable Debug Logging from the extension settings and copy paste content script logs here after you have opened the Autocomplete Menu. Also, what other extension do you have? Is it possible that some of them are affecting the behavior of ours?

**Comment by DarkPreacher** [comment]
I have a few other extensions, tried to turn most of them off – no luck.
Dev console shows this
```
TypeError: window.self.visualViewport is undefined autocomplete.js:279:29
```

**Comment by varjolintu** [comment]
Can you write to the JavaScript console both of these and paste the output? From the same login page.
- `window.visualViewport.height`
- `window.self.visualViewport.height`

**Comment by DarkPreacher** [comment]
Sure, `window.visualViewport.height`
```
Uncaught TypeError: window.visualViewport is undefined
    <anonymous> debugger eval code:1
debugger eval code:1:1
```
`window.self.visualViewport.height`
```
Uncaught TypeError: window.self.visualViewport is undefined
    <anonymous> debugger eval code:1
debugger eval code:1:1
```

**Comment by varjolintu** [comment]
That shouldn't be possible, unless your Firefox is older than version 91. I'd suggest you try a new temporary profile or reinstall Firefox completely.

This error is not related to the extension, so closing this.
