### ISSUE TITLE
Firefox 116/fedora: can't find any entries, can't save; native messaging *seems* to work

### ISSUE THREAD

**Issue by marcusmueller** [keepassxreboot/keepassxc-browser#1977]
## Expected Behavior

Go to an arbitrary website for which I have credentials; right-click on user field, KeePassXC->Fill Username and Password  should work

## Current Behavior

doesn't – it says "Error! No login found https://example.com"; saving credentials isn't possible either.

This has been going on since I installed keepassxc-browser, a couple months ago. Since then, both firefox and keepassxc-proxy have been updated.

## Possible Solution

none I could come up with. 

## Steps to Reproduce (for bugs)

1. KeepassXC starts on login
2. Unlock the database (there's only 1)
3. open firefox
4. navigate to arbirary website
5. request fill-in of credentials

## Debug info

KeePassXC - 2.7.6 (from the keepassxc-2.7.6-1.fc38.x86_64 package)
KeePassXC-Browser - 1.8.7
Operating system: Linux (Fedora 38, cinnamon-session), X11, native (no flatpak)
Browser: Firefox 116.0.3 (from the firefox-116.0.3-1.fc38.x86_64)

- keepassxc-proxy starts properly when run manually
- firefox & sleep 0.25; strace -f -p $(pgrep firefox) shows the socket to be opened
- no mention of the string "keepass" in dmesg/journalctl – but other audits are in there
- inspecting the log of the browser extension yields 

```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:317:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/background/client.js)
KeePassXC-Browser: Server public key: GvNVtXNGNECE0WRvdNBwKHPG4TWuerHc3+Cr5ghnvjU= [keepass.js:435:17](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/background/keepass.js)
[Error ] KeePassXC-Browser - No content script available for this tab. 2 [global.js:145:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/common/global.js)
[Error ] KeePassXC-Browser - 11: No saved databases found. [global.js:145:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/common/global.js)
[Error keepass.js:107] KeePassXC-Browser - 11: No saved databases found. 4 [global.js:145:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:145:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/common/global.js)
[Error keepass.js:107] KeePassXC-Browser - 11: No saved databases found. [global.js:145:13](moz-extension://e5f22a8a-4b5c-4352-9a87-6ea89c195f2b/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
```

requesting credentials for fields while looking at the addon debug console does not add further messages. 

The only thing that works is "Request Global Auto-Type"; that works reliably, including prompting to unlock the database first, if it's currently closed.

**Comment by marcusmueller** [comment]
[firefox.strace.txt](https://github.com/keepassxreboot/keepassxc-browser/files/12489998/foo.strace.txt)

(only string-replaced my user name with "username" and my firefox profile lettersalad with "profileid"

**Comment by varjolintu** [comment]
According to the JavaScript log you haven't connected the extension to your database.

**Comment by marcusmueller** [comment]
True! But: contrary to the instructions, the extension never asked me to, and I was getting "green" keypassxc icons in user name text boxes on websites all the time, so I was a bit like "hm, that must now work automatically". 

So, anyways, YESSS :-) this works now! Thanks!

Does that mean we should close this issue, or is "false green icons" a bug we should track separately? Seeing it might be hard for me now to reproduce, I'm not sure.

**Comment by varjolintu** [comment]
The next version will have a icon with a `!` mark in the toolbar to indicate that the active database is not yet connected. In the current version that situation is not visible enough :(

**Comment by marcusmueller** [comment]
Don't think that ! will help in all too many cases, the keepassxc might not be visible directly, but behind the "extensions" menu bar icon, screenshot:
![Untitled](https://github.com/keepassxreboot/keepassxc-browser/assets/958972/bf9d8f08-9466-4362-b69d-b1aa5db7586d)

I'd argue what would be more useful is improving the error overlay text: 

> Error! No login found …

is just telling half the story; 

> Error! Can't find logins; no database connected (see Settings)

(ideally even with a link to open the settings) would be more accurate.

**Comment by varjolintu** [comment]
The icon on the username fields should be gray when there are no credentials, or the extension is not connected. So that's one more indication.

**Comment by marcusmueller** [comment]
yep, but it's not been consistently gray, definitely. It turns green after you "request global auto-type", for example (and I don't think that's the only situation), which I interpreted as "comms with keepasscx does work fine".

And since there's no way for a new user to be forced to pin the extension icon, it's not going to be visible.

**Comment by varjolintu** [comment]
Yes, Request Global Auto-Type is an exception because it does not need a connected database, just a working connection between the extension and KeePassXC. Gotta check that icon color on that command. It shouldn't change.

**Comment by marcusmueller** [comment]
Just: again, thanks for being so helpful in addition to development; it's been a real pleasure :) This turned out to be way more a problem on my side than I anticipated, and you've been really supportive.
