### ISSUE TITLE
Cannot connect DB to Brave browser

### ISSUE THREAD

**Issue by gpags1911** [keepassxreboot/keepassxc-browser#1979]
## Current Behavior
 
I get the following from the extension:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

Clicking Reload:
Key exchange was not successful.

Browser Integration is enabled in Keepass.

In the extension settings it shows no connected databases. When i click the Connect button nothing happens. The database is unlocked at the time I do this.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - Version 2.6.6
Revision: 9c108b9

Qt 5.15.3
Debugging mode is disabled.

Operating system: Pop!_OS 22.04 LTS
CPU architecture: x86_64
Kernel: linux 6.4.6-76060406-generic

KeePassXC-Browser - 1.8.7
Operating system: Linux
Browser: Brave - [Version 1.57.53 Chromium: 116.0.5845.114 (Official Build) unknown (64-bit)](https://brave.com/latest/)

**Comment by varjolintu** [comment]
There are multiple threads about this issue. Use the search please.

**Comment by nhilo32** [comment]
I ran into the same problem. If you installed via flatpak (I did, was being lazy) the extension will probably not work. Your sandboxed. You will need to go to https://brave.com/linux/ and pick your linux version and install via command line. After that I was good to go.
