### ISSUE TITLE
username / Postbank ID not accepted on postbank login

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc-browser#1984]
macOS 13.5.2
Firefox 117.0.1
keepassxc-browser 1.8.7
KeepassXC 2.7.6

When trying to login on https://banking.postbank.de/#/login the website will not accept the username aka Postbank ID for fast majority of attempts.

The software from Postbank is probably a nightmare, they are known for the poor trasition to deutsche bank software. So making this work will probably mean, working around poor coding on Postbank side of things 🙄

## Expected Behavior
Login via username should work.

## Current Behavior
keepassxc-browser fills the username field, but Postbank website does not accept the value and does not proceed to password entry. Error message shown is Please enter your Postbank ID, which clearly makes no sense.

## Possible Solution
1Password 7 + Firefox add-on manages to fill that field and website accepts the entry without complaint. Maybe it is possible to learn, how they solved this.

**Comment by varjolintu** [comment]
This is a known issue. Some script in the page thinks a filled username is copy-pasted or not inserted correctly. You can verify this by deleting the last number manually and then entering it again.
