### ISSUE TITLE
Trouble with custom attribute "KPH:"

### ISSUE THREAD

**Issue by ZenMasta** [keepassxreboot/keepassxc-browser#1991]
I'm trying to log in to a new service but I can't figure out how to map the one field correctly. 

The site has 3 fields

Here is the input name for these fields per the HTML:

Merchant ID :user_code
Pin: username
Password: password

I tried creating a custom attribute to populate the merchant id field but it's not working for me.
"KPH: user_code" along with my string value
I also tried "KPH: Merchand ID" but that didn't work for me either. 

What am I doing wrong? 

![image](https://github.com/keepassxreboot/keepassxc/assets/823528/3fcc8863-0fd3-436d-8f4e-36608e311022)

![image](https://github.com/keepassxreboot/keepassxc/assets/823528/f2775610-d4fb-4914-890a-de12e781a123)

Here is the website I'm trying to log into 
https://www.merchantsupportcenter.com/back_to_login.php

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.7
Operating system: Win64
Browser: Mozilla Firefox 117.0

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-situations-and-debugging#filling-extra--third-field

**Comment by ZenMasta** [comment]
Thank you.
