### ISSUE TITLE
Latest version (1.8.8) not pushed to addons.mozilla.org

### ISSUE THREAD

**Issue by FlyveHest** [keepassxreboot/keepassxc-browser#1992]
## Expected Behavior
Newest version available on addons.mozilla.org

## Current Behavior
1.8.8 not available on addons.mozilla.org,

## Possible Solution
Push latest version to addons.mozille.org :)

## Steps to Reproduce (for bugs)

1. Check for update on addons.mozilla.org

## Debug info

KeePassXC - -
KeePassXC-Browser - 1.8.7
Operating system: Mac/Win/Linux
Browser: Firefox

**Comment by varjolintu** [comment]
It's up to Mozilla's review queue.. I cannot speed up the process.
