### ISSUE TITLE
KeeppassCX adds div to bottom of my DOM

### ISSUE THREAD

**Issue by evert** [keepassxreboot/keepassxc-browser#1994]
I'm working on a static side and suddenly noticed I have a bonus div at the bottom of my HTML:

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/178960/83d5d893-5898-4728-b364-75f9ae31a256)

Since I wrote no Javascript I was confused. It also messes with my layout because I used `display: flex` and `flex:1` on all direct descendants of `<body>`

## Debug info

KeePassXC-Browser - 1.8.7
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
Yes this is how extensions can show elements on a page.
