### ISSUE TITLE
Firefox browser extension - Cannot read keepassxc version (cannot connect to database)

### ISSUE THREAD

**Issue by techrivertree** [keepassxreboot/keepassxc-browser#1995]
## Overview
On firefox 117.01 keepassxc browser cannot read keepassxc version number.
On brave, everything works correctly.

## Steps to Reproduce
1. Open firefox
2. Try to connect to database
3.  Open browser settings and see that keepassxc version is unknown.

## Expected Behavior
The browser extension should connect to the database, just like it does with brave.

## Actual Behavior
KeePassXC-Browser has encountered an error:

Key exchange was not successful. 

## Context
None

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.6
Revision: ?
Keepassxc brower extension: 1.8.8

![Screenshot from 2023-09-29 21-51-46](https://github.com/keepassxreboot/keepassxc/assets/69227859/9eb80003-897d-4931-ac19-3404746315f0)

Operating System: Ubuntu 22.04
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu Check your AppArmor settings for Firefox.

**Comment by techrivertree** [comment]
> Did you select Firefox in the browser settings as well as brave? Did you connect to your database within firefox?

Yes and Yes.

**Comment by droidmonkey** [comment]
You also have check for updates set to never in Firefox based on your screenshot....

So the ONLY problem is you don't see the version of KeePassXC? Your report says key exchange was not successful.

**Comment by techrivertree** [comment]
I should clarify that the that kp browser extension used to connect to my database. Besides normal updates, nothing changed.

**Comment by varjolintu** [comment]
Did you check the AppArmor settings? Also make sure Firefox has not updated to a Snap version by itself and Snap's native messaging implementation has not been enabled.

**Comment by varjolintu** [comment]
@techrivertree Btw, if the check update is set to "Never" the version is not checked automatically when you open the Settings page. Does it work if you press the button?

**Comment by varjolintu** [comment]
Let's open this if the issue still persists.

**Comment by techrivertree** [comment]
I completely forgot about this. I do not like to have duplicate issues but since I cannot get either Tor or Firefox to connect to my database, lets reopen this.

**Comment by varjolintu** [comment]
I still need more info about your problem. How is Firefox installed etc?

Have you tried another method: https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
