### ISSUE TITLE
Browser extension may prevent HTTP Basic Authentication showing up sometimes

### ISSUE THREAD

**Issue by JacksonChen666** [keepassxreboot/keepassxc-browser#1997]
## Expected Behavior

The HTTP basic authentication dialog shows up, or the database permission prompt shows up to fill the password.

## Current Behavior

Sometimes, the extension may prevent the HTTP auth dialog from showing up, not even prompting for database access.

This causes the page to forever load without an obvious reason of why.

## Possible Solution

Workaround: Turning the extension off and on again makes the page not stuck on thing.

## Steps to Reproduce (for bugs)

Cause is currently mostly certain. **Other causes unknown**.

1. **Have KeePassXC open and database unlocked, and browser extension connected, and HTTP auth credential fill out enabled in browser extension**
2. Open site that requires HTTP basic auth (e.g. <https://vore.jacksonchen666.com/>)
3. Deny database permission and cancel HTTP auth
4. Force quit KeePassXC (For convenience, press Command-Option-Shift-Escape while the current focused application is KeePassXC to force quit it)
5. Reload page
6. No prompt for HTTP basic auth credentials, nor prompt for permission to use database. Page stuck in loading.
7. (Optional, workaround beyond this point) Do workaround: Turn off the extension and turn it on again

Video:
https://github.com/keepassxreboot/keepassxc-browser/assets/50755746/72d5320d-dc9e-48d4-8426-86cc40014008

## Debug info

```
12:25:06.331 [Error client.js:186] KeePassXC-Browser - 15: No logins found global.js:145:13
12:25:06.332 [Error httpauth.js:42] KeePassXC-Browser - No logins found for HTTP Basic Auth. global.js:145:13
12:25:09.193 [Error keepass.js:262] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 2 global.js:145:13
12:25:27.320 [Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 2 global.js:145:13
```

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8
Operating system: MacIntel (wrong!)
Browser: Mozilla Firefox 118.0 (LibreWolf 118.0.1-1 actually)

Also on the following:

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8
Operating system: MacIntel (wrong!)
Browser: Mozilla Firefox 118.0 (actually firefox)

**Comment by droidmonkey** [comment]
I cannot reproduce this on Edge/Windows 11. I suspect this is a specific bug with LibreWolf.

**Comment by droidmonkey** [comment]
You might have another browser request that popped up and is hidden behind a window.

**Comment by varjolintu** [comment]
Can you provide logs from the background scripts? Instructions [here](https://github.com/keepassxreboot/keepassxc-browser/wiki/HowTo:-Special-situations-and-debugging#firefox-debug-background-scripts).
