### ISSUE TITLE
(question/potential bug) KEEPASSXC extension not recognizing my KEEPASS app 

### ISSUE THREAD

**Issue by ArandomHitman** [keepassxreboot/keepassxc-browser#1998]
I use Keepass Touch with my Mac (IOS 17) and my KeepassXC extension for Librewolf (firefox client) isn't recognizing my app anymore).
## Expected Behavior
I could access my database and autofill my passwords.

## Current Behavior
The extension doesn't recognize my Keepass touch app or database.

## Possible Solution
If the extension isn't compatible with KeePass touch for Mac, add compatibility? the XC version doesn't work with my Mac.

## Steps to Reproduce (for bugs)
<img width="455" alt="Screenshot 2023-10-02 at 11 08 09 AM" src="https://github.com/keepassxreboot/keepassxc-browser/assets/138054584/8b6774c2-3092-4155-a8af-b6b006edfcdf">

1. Download and use KeePass Touch with any Mac
2. Download Librewolf (if not Firefox) and add keepassXC to it
3. Check the extensions tab and click on keepassXC

## Debug info
KeePassXC version - Latest
Operating system: MacOS (IOS17)
Browser: Librewolf (firefox client)

**Comment by varjolintu** [comment]
What is KeePass Touch? We don't support that application, unless they have implemented a compatible API for it.

**Comment by ArandomHitman** [comment]
oh, did I go to the wrong repository? apologies for wasting your time.

**Comment by ArandomHitman** [comment]
Fixed. I was talking about the wrong keepass, they're both quite similar both in name and in looks

**Comment by ArandomHitman** [comment]
sorry for wasting your time, and have a good day.
