### ISSUE TITLE
Transfering old repositories

### ISSUE THREAD

**Issue by hyviquel** [keepassxreboot/keepassxc-browser#2]
Why not transferring old repositories from @varjolintu account instead of duplicating them?
This would allow you to keep all issues for example...
You can do it by going to each repository page then Settings > Danger Zone > Transfer ownership

**Comment by phoerious** [comment]
There aren't that many issues and the old repository is going to be maintained at least until we stabilize everything over here, so we decided to start fresh.

**Comment by hyviquel** [comment]
In my opinion closed issues are always useful as documentation but it's your choice of course 😉 
Good luck!
