### ISSUE TITLE
latest v1.1.6 updated today June 12 made auto-detect login/pwd fields fail

### ISSUE THREAD

**Issue by muchqs** [keepassxreboot/keepassxc-browser#200]
## Expected Behavior

Before the update when I clicked on a login/pwd field, my entries would show up in a little menu and I can click on one and it auto-fills the spots. This worked at least for most sites.

## Current Behavior

After the update to 1.1.6, now it doesn't auto-detect any field. I click in an empty login/pwd box nothing shows up. I click "redetect credential fields", nothing happens. (this used to work before the update). So now I have to right click the box and select "fill User + Pass" or "fill pass only" for the little menu to show up. I wish the extension didn't auto-update.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - v2.3.3
keepassxc-browser - v1.1.6
Operating system: Windows 10
Browser: Vivaldi
Proxy used: NO

**Comment by anonymousghoul** [comment]
Same issue with Firefox on Linux.

Sticking with 1.1.3 as although it doesn't work with the most sites, it is the most stable.

**Comment by droidmonkey** [comment]
We are discussing the series of issues with the last couple releases on IRC. We can do better than this, and we will.

**Comment by phoerious** [comment]
Issue is fixed, should be working again.
