### ISSUE TITLE
Question about modifying this extension

### ISSUE THREAD

**Issue by Andereoo** [keepassxreboot/keepassxc-browser#2000]
Apologies in advance; this is not an issue or bug, rather it is a quick question. I modified a couple likes of code in `browserAction.js` and `manifest.json` to switch the extension icon from a `browserAction` to a `pageAction` so that it shows in the urlbar. I am installing the modified extension on Firefox my computer, but first want to make sure that there are no major security issues with doing so?

Thanks in advance for your help, and by the way, amazing extension!

**Comment by varjolintu** [comment]
Any possible security issues depend on the changes you make.

**Comment by Andereoo** [comment]
I deleted the `META-INF` folder, changed `browser_action` to `page_action` in `manifest.json`, and under `browserAction.show` in `browserAction.js` I replaced `browser.browserAction` with `browser.pageAction`, added `tabId: tab.id` to `browser.pageAction.setIcon`, and added `browser.pageAction.show(tab.id);`. I also tried getting my modified extension signed by AMO but to do so I had to change its `id` in `manifest.json`, after which it stopped connecting to KeepassXC. I don't think any of these changes would introduce any security breaches, unless deleting `META-INF` or having the extension unsigned and manually installed would cause problems. I figured I'd ask anyway because I don't know much about how you guys ensure secure transfer of data between the app and the browser, and I'd rather not accidentally compromise my 500 passwords :)

**Comment by droidmonkey** [comment]
Question: if you are concerned, then why are you modifying the extension at all?

**Comment by Andereoo** [comment]
Not quite concerned; mostly curious.

**Comment by varjolintu** [comment]
Signing the extension by AMO is only relevant if you plan to release something. Otherwise you are of course free to modify the code locally.
