### ISSUE TITLE
Librewolf Flatpak and KeePass Flatpak dont connect

### ISSUE THREAD

**Issue by Milor123** [keepassxreboot/keepassxc-browser#2001]
## Current Behavior

KeePassXC-Browser has encountered an error:

- Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/14153649/9952a19b-78d7-41fe-93f7-7a890082c542)

I tried a clean installation with new firefox profile, but dont work.

## Steps to Reproduce (for bugs)

1. Try AppArmor rules but it dont allow me
After create the file using this guide [Troubleshooting-guide#6-apparmor-with-ubuntu
](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu)
```
$ sudo aa-enforce /etc/apparmor.d/usr.bin.firefox

ERROR: Syntax Error: Unexpected path entry found in file: /etc/apparmor.d/usr.bin.firefox line: 1
```

but like it dont work for me, **I tried stopping the service of appamor** and try run.

2. Add manually the location `~/.librewolf/native-messaging-hosts` to keepass (Flatpak + Flatseal Permissions) and also with `/home/noe/.var/app/io.gitlab.librewolf-community/.librewolf`

The which create a file with the next path:
`"path": "/home/noe/.local/share/flatpak/exports/bin/org.keepassxc.KeePassXC",`
but i also try change it for:
also try use this path: `/run/user/1000/org.keepassxc.KeePassXC.BrowserServer`
and also try use `/usr/bin/keepassxc-proxy` with the non flatpak version.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/14153649/ac83c8be-a651-4d54-9f13-7a68f45d5b9f)
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/14153649/e03155a1-05cb-4ae9-9383-33a02e7ab011)

Nothings works

3. Permissions

I am not sure the correctly app name, by this reason, i try add it.
```
$ flatpak permissions webextensions
Table         Object                                App                           Permissions Data
webextensions keepassxc.KeePassXC                   io.gitlab.librewolf-community yes         0x00
webextensions keepassxc.KeePassXC.BrowserServer     io.gitlab.librewolf-community yes         0x00
webextensions org.keepassxc.KeePassXC.BrowserServer io.gitlab.librewolf-community yes         0x00
webextensions org.keepassxc.keepassxc_browser       io.gitlab.librewolf-community yes         0x00
webextensions org.keepassxc.KeePassXC               io.gitlab.librewolf-community yes         0x00

```
5. Runtime variiable

```
$ echo $XDG_RUNTIME_DIR
/run/user/1000
```

## Debug info

KeePassXC - 2.7.6 (Flatpak as user + Flatseal permissions)
KeePassXC-Browser Version: 1.8.8.1
Operating system: Linux Ubuntu 22.04 LTS
Browser: Librewolf (Flatpak as system)

**Comment by droidmonkey** [comment]
This is on librefox and flatpak itself, not us.
