### ISSUE TITLE
Mullvad Browser base on TOR/Firefox can't connect to the keepassxc database

### ISSUE THREAD

**Issue by krlabs** [keepassxreboot/keepassxc-browser#2002]
## Expected Behavior
KeepassXC Firefox browser exension will connect to the keepassxc database.

## Current Behavior
KeePassXC-Browser has encountered an error: "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."  

"Custom browser configuration location" option in KeepassXC Desktop nothing change. 

Other browsers connect to kepassxc database without any problems, including Librewolf.

## Steps to Reproduce (for bugs)
1. Download Mullvad Browser from the official site: https://mullvad.net/en/browser
2. Install the KeepassXC-Browser extension from Firefox repository: https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/
3. Turn on all browsers integration in KeepassXC Desktop settings.
4. Try to connect to the database

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.8.1
Operating system: Kali Linux
Browser: Mullvad Browser 12.5.6 (based on Mozilla Firefox 102.15.1esr) (64-bit)

**Comment by varjolintu** [comment]
If the configuration path for native messaging scripts is not clear, use `strace` to detect it?

**Comment by krlabs** [comment]
> If the configuration path for native messaging scripts is not clear, use `strace` to detect it? But check `about:support` first if it lists the path.

At the moment, I'm using the program's home folder directory for native-messaging-hosts location:
~/mullvad-browser/native-messaging-hosts/

Do I understand correctly that this directory should be empty?

I did not use the `strace` method. Could you download the Mullvad Browser and try it on your Linux machine (if possible)? 
And which kind of path should check in `about:support`?

**Comment by varjolintu** [comment]
If you enter that path to the Custom Browser feature in KeePassXC, that browser should work. The folder should not be empty after Custom Browser option is enabled.

**Comment by krlabs** [comment]
I had the same problem with Waterfox browser + KeepassXC-Desktop + KeepassXC-Browser extenstion, but this fixed very easy by copy ~/.mozilla/native-messaging-hosts to the ~/.waterfox config directory. 

Mullvad Browser does not have such config directory. Maybe this browser dont supported by KepassXC and no point to trying?

In about:support of Mullvad Browser i see:

Update directory: ~/mullvad-browser/Data/UpdateInfo
Profile direcory: ~/mullvad-browser/Data/xxxxx.default-release

I trying copy ~/.mozilla/native-messaging-hosts to this location, but nothing changes. 

In my opinion, we need someone from the KepassXC development team to install Mullvad Browser and test the connection and share all the nuances in this thread.

**Comment by droidmonkey** [comment]
We do not support mulvad and it might not support native messaging.

**Comment by krlabs** [comment]
> We do not support mullvad and it might not support native messaging.

Thanks for the answer. I so sad. Because, Mullvad Browser is the most better privacy and security browser.  I hope, in the future we will support this browser.

**Comment by feskehau** [comment]
Hi, Keepass browser extension works with Mullvad Browser. This issue can be closed.
Strace shows where Mullvad Browser tries to load the native-messaging-hosts file from. In my case, installed in /opt/mullvad-browser:
```
$ sudo strace -f -p $(pgrep mull) 2>&1 | grep keepass
[pid  3576] openat(AT_FDCWD, "/opt/mullvad-browser/Data/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)
[pid  3576] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
```

**Comment by krlabs** [comment]
> Hi, Keepass browser extension works with Mullvad Browser. This issue can be closed. Strace shows where Mullvad Browser tries to load the native-messaging-hosts file from. In my case, installed in /opt/mullvad-browser:
> 
> ```
> $ sudo strace -f -p $(pgrep mull) 2>&1 | grep keepass
> [pid  3576] openat(AT_FDCWD, "/opt/mullvad-browser/Data/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY) = -1 ENOENT (No such file or directory)
> [pid  3576] openat(AT_FDCWD, "/usr/lib/mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
> ```

Its dont work.

**Comment by krlabs** [comment]
> We do not support mullvad and it might not support native messaging.

Please, open issue.

**Comment by droidmonkey** [comment]
Yeah, it works. You just need to configure your native messaging correctly in KeePassXC using the custom browser feature in the browser settings page.

**Comment by krlabs** [comment]
Yes, now it works. In my opinion, issue can be closed only, if it's confirmed by the user who opened it, and other users...  And we need to give a more detailed and specific description, including evidence and screenshots, if issue was solved.

So, what was done to solve it?

1. Updated KeepassXC 2.6.6 to 2.7.4 version. 
1. Moved `~/mullvad-browser` to `/opt` directory.
2. Copied `~/.mozilla/native-messaging-hosts` to `/opt/mullvad-browser/Data` directory.
3. In KeepassXC-Desktop -> Application Settings -> Browser Integration enabled setting "Use a custon browser configuration location" and put actual native-messaging-hosts path: 

`/opt/mullvad-browser/Data/.mozilla/native-messaging-hosts`

Evidence: https://imgur.com/hmMm2Jv.png

4. Reinstalled KeepassXC-Desktop extension for Firefox. And successfully connected database. 

Evidence: https://imgur.com/mbyh5tR.png

**Comment by krlabs** [comment]
> Step 2 and 3 seem entirely unnecessary.

It may "seem", but without steps 2 and 3, it didn't work for me. For this reason, I wrote in my previous post about this.

> And no, we definitely don't need to provide evidence or anything to close an issue. This isn't a paid support system.

It's not about support... There was no support from you. It's just logical!

**Comment by droidmonkey** [comment]
So I took some time out of my day because I am curious... 

With mullvad browser "installed" to `~/mullvad-browser` AND KeePassXC custom browser configured to `~/mullvad-browser/Browser/.mozilla/native-messaging-hosts`, THEN if you run the browser with the .desktop entry or directly using `~/mullvad-browser/Browser/start-mullvad-browser`, native messaging will not work. HOWEVER, if you start it with `~/mullvad-browser/Browser/mullvadbrowser` then everything works fine.

I think this should be a bug report to Mullvad.

**Comment by krlabs** [comment]
> So I took some time out of my day because I am curious...
> 
> With mullvad browser "installed" to `~/mullvad-browser` AND KeePassXC custom browser configured to `~/mullvad-browser/Browser/.mozilla/native-messaging-hosts`, THEN if you run the browser with the .desktop entry or directly using `~/mullvad-browser/Browser/start-mullvad-browser`, native messaging will not work.
> 
> HOWEVER, if you start it with `~/mullvad-browser/Browser/mullvadbrowser` then everything works fine.
> 
> I think this should be a bug report to Mullvad.

Thank you for this remark.

**Comment by droidmonkey** [comment]
After I commented out these lines everything worked fine with native messaging:

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/2809491/b40d47d3-5d37-4ad9-8dfe-2abe72f45645)

**Comment by droidmonkey** [comment]
And this is why...

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/2809491/fcb6dda6-5b77-48e5-8e21-2be7a1a8e40e)

When the Flatpak (or really anything) is run with this invalid $HOME context then it looks in the wrong place for the executable.
