### ISSUE TITLE
Cannot update credentials via browser, only save new ones

### ISSUE THREAD

**Issue by TheElbinho** [keepassxreboot/keepassxc-browser#2003]
## Expected Behavior

When typing modified credentials into a login screen for a site where credentials are already stored a popup appears asking whether to save the credentials as a new set, or to update the old credentials.

## Current Behavior

Saving credentials as a new set works as expected, updating the old credentials generates the error "credentials could not be saved or updated"

## Steps to Reproduce (for bugs)

1. Login to a site with saved (outdated) credentials, manually entering the new credentials
2. Press "update" in the opening keepassxc-browser popup
3. Error

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8.1
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
Any errors in the JavaScript console?

**Comment by TheElbinho** [comment]
KeepassXC doesn't prompt anything, just the popup from the browser plugin. I'm not quite sure if I am looking for errors in the right spot, but I found an error in what I assume to be the debugging console you ask for saying "[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist."

Nevertheless saving the credentials as a new entry works just fine

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/9853 This is probably related to this fix.
