### ISSUE TITLE
Remove connection not work

### ISSUE THREAD

**Issue by LeonardVertighel** [keepassxreboot/keepassxc-browser#2004]
## Expected Behavior
Pressing the "Remove" button must delete the connection.
![RemoveNotWork](https://github.com/keepassxreboot/keepassxc-browser/assets/45466797/5ec38a5e-e641-485f-b527-fc8cfb039d30)

## Current Behavior
Pressing the "Remove" button does nothing.

In browser console there is an error:
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/45466797/6dc7deb2-8ddc-4880-a7f3-bb43fa166b4d)

## Possible Solution
Show a deletion confirmation popup

## Steps to Reproduce (for bugs)

1. Craete a database on KeepassXC 
2. Enable Browser integration option
3. Install extension in browser
4. Open extension option
5. Create a key to connect to the database
6. Click on remove button.

## Debug info

The same happens with multiple browsers and multiple operating systems
### First
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8.1
Operating system: Windows 10 64bit Pro - 19045.3448
Browser:  Edge - 117.0.2045.60 

### Second
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8.1
Operating system: Windows 10 64bit Pro - 19045.3448
Browser:  Brave - 1.58.137 (Based on Chromium 117.0.5938.153)

**Comment by varjolintu** [comment]
I have no idea why that modal dialog is not found, and I cannot reproduce this, but I can add some extra checks to this.
