### ISSUE TITLE
KPXC-Browser extension UI language fixed at English?

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#2006]
It'd appear as if KPXC-Browser version 1.8.8.1 is fixed at an English UI language

## Expected Behavior
KPXC-Browser to pick up on the UI language setting of the browser and follow suit

## Current Behavior
My browsers are in Dutch language. KPXC-Browser extension is in English

## Additional insights
My KeePassXC app is also set to Dutch language
Could it be something to do with short/long language codes e.g. NL/NL-nl

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.8.1
Operating system: Win64
Browser: Microsoft Edge 118.0.2088.46
Browser: Vivaldi 6.2.3105.58 (Stable channel) (64-bits)

**Comment by varjolintu** [comment]
Only `nl_NL` locale exists currently. There was a request to remove the plain `nl` because it's a duplicate. If you copy the locale folder or rename it (where the extension is installed), does that fix the problem?

**Comment by Stephan-P** [comment]
NICE!

- In C:\Users\USERNAME\AppData\Local\Vivaldi\User Data\Default\Extensions\oboonakemofpalcgghocfoadofidjkkk\1.8.8.1_0\_locales I copied the folder nl_NL into one called nl
- I restarted Vivaldi
- And PRESTO! KPXC-Browser showed up in Dutch language alright

So, my hunch was correct. Somehow there's a misconfiguration around locale nl_NL.
Maybe, the simplest solution is to rename nl_NL in Transifex into nl, which will be consistent with the main app KPXC as well.

**Comment by Stephan-P** [comment]
So, for Vivaldi I had made a copy of the folder nl_NL. And after the restart KPXC-Browser showed up in Dutch language.

In Edge I renamed the folder nl_NL into nl and here it did not give the desired result. 
On second thought the same copy nl_NL to nl does not appear to work either.... 
But, I've got a number of Edge PWA's running. 
Let's use the taskmanager to make sure no Edge instances are running and try again.
Still no Dutch language in Edge....

**Comment by varjolintu** [comment]
If we rename `nl_NL` to `nl`, then people will probably complain that `nl_NL` is not working :) Not sure which direction we should take here. Is there a misconfiguration in the browser or in the operating system? Are both locales needed just to make sure?

**Comment by droidmonkey** [comment]
Creating an nl in transifex is the way

**Comment by varjolintu** [comment]
I readded `nl` to Transifex.
