### ISSUE TITLE
[BUG?] Nextcloud + WebAuthn (Passkeys) on KeePassXC v2.8.0 (pre-release)

### ISSUE THREAD

**Issue by mas1701** [keepassxreboot/keepassxc-browser#2010]
Situation:

I've just migrated from KeePass 2.x to KeePassXC v2.8.0-snapshot (provided by varjolintu) for Passkey-Support, since it is used more and more on websites.

As far as the normal use goes, everything is working well, including browser extension in Brave.

What isn't working:

I was trying to enable WebAuthn for my Nextcloud account. That is, after all, what I changed to KeePassXC for.

## Expected Behavior

When clicking on "add WebAuthn device" on my Nextcloud account security page, KeypassXC-Browser should kick in and handle the authentication data.

## Current Behavior

With fallback enabled in KeepassXC-Browser, the Brave window for authentication by security device or mobile device opens.

Without fallback enabled, nothing happens aside from a tiny moment were it says "please authenticate with your WebAuthn device" on the Nextcloud account security page. Then it disappears again and the process seems to be aborted.

## Possible Solution

Should just work. It is supposed to be simple.

## Steps to Reproduce (for bugs)

Try to enable WebAuthn within a Nextcloud account.

Developer: In need for a test account? Don't hesitate to ask.

## Debug info

KeePassXC - v2.8.0-snapshot by varjolintu
KeePassXC-Browser - v1.8.9
Operating system: Windows 10 Enterprise LTSC 2019
Browser: Brave   (note: no difference between "Brave Shields" being up or down)
[log-1697630436540.txt](https://github.com/keepassxreboot/keepassxc-browser/files/13025039/log-1697630436540.txt)
[log-1697630561469.txt](https://github.com/keepassxreboot/keepassxc-browser/files/13025042/log-1697630561469.txt)

**Comment by mas1701** [comment]
> Are you compiling the snapshot by yourself or using the build I provided months ago? It's not up-to-date.

Thanks for your reply.

I'm using your version. I'm not aware of any other. Is there a more up-to-date version that I could try?
(I have no compiler environment on Windows.)

**Comment by varjolintu** [comment]
Not yet. But if it seems we are delaying an actual snapshot, I can make a new build.

**Comment by mas1701** [comment]
> I'm ready to merge but too busy atm to make sure everything is kosher

I don't intend to eat software, so it doesn't need to be kosher. And I'm not jewish anyway. ;-)

Take your time. I appreciate the effort taken.

**Comment by droidmonkey** [comment]
It shall be blessed though! 🙏

**Comment by varjolintu** [comment]
@mas1701 I uploaded new builds to https://github.com/varjolintu/keepassxc/releases/tag/2.8.0-passkeys for testing purposes.

**Comment by mas1701** [comment]
> @mas1701 I uploaded new builds to https://github.com/varjolintu/keepassxc/releases/tag/2.8.0-passkeys for testing purposes.

Thanks a lot! First test with Nextcloud indicates it seems to work properly now. Will test with other services as the chance presents itself and report problems.

Does this still work by injecting JS code or does it interface with any kind of browser authentification API? I remember reading something about code injection ...

**Comment by varjolintu** [comment]
@mas1701 It's injecting JavaScript code, just like every other password manager browser extension there is. No browser has opened their Passkeys/WebAuthn API.

**Comment by mas1701** [comment]
> @mas1701 It's injecting JavaScript code, just like every other password manager browser extension there is. No browser has opened their Passkeys/WebAuthn API.

Maybe it's a stupid question, but how does it work with USB security keys supported by browsers? Would it not be possible to "emulate" a security stick in software to avoid JS code injection? Or would this be too complicated and not worth the effort, even it possible?

**Comment by varjolintu** [comment]
@mas1701 I think there's at least one solution available that does this. Cannot remember the name though.

**Comment by mas1701** [comment]
> @mas1701 I think there's at least one solution available that does this. Cannot remember the name though.

Hi Sami,

not sure if it is interesting for you and possibly for KeePassXC:

A Virtual FIDO2 USB Device - MIT License
https://github.com/bulwarkid/virtual-fido

Bulwark Passkey (uses virtual-fido) - MIT License
https://bulwark.id/
https://github.com/bulwarkid/bulwark-passkey

Might be worth a look?
