### ISSUE TITLE
Choose custom login fields for multipage logins

### ISSUE THREAD

**Issue by tofuSCHNITZEL** [keepassxreboot/keepassxc-browser#2012]
## Expected Behavior

Websites that use an authentication flow over multiple pages are becoming (unfortunately) more common
It would be great if the "Choose custom login fields" function would also work over multiple pages.

## Current Behavior

Currently if you select custom fields on step 1 and save it and then continue to step2 of the authentication flow and choose custom fields there (eg. to select a password field that is present in step2) it will remove the settings done in step 1.

## Possible Solution

my suggestion - if possible - make the "choose custom fields" function on the same url additive instead of starting from scratch every time. in this way it would also be possible to have string fields over multiple pages of the authentication flow.

## Steps to Reproduce (for bugs)

I have created a "test jig" that simulates the case I describe (and mimics a bank login flow where is issue originated)
https://bitconnect.at/kptest/

1. on the index page use the "Choose custom login fields" - select input1 as username and input2 as string fields - confirm selection
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/5708088/e126c80f-33e7-4a0d-bccb-f11be81cd246)
2. on step2 page use the "Choose custom login fields" again and select the password field as password - this will remove the already set selection from. this can be tested by going back to step 1 and it will not fill the lower input field

you can test this by creating a keepass entry for the url with user/pass and KPH: attribute
also interesting to observe is that if you make keepassxc fill the fields on step2 (before selecting the pw field) it will overwrite the content of the submit button with the content of the first KPH: attribute
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/5708088/56777b25-3777-4e9f-96a0-1d35091b2caf)

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Win64
Browser: Mozilla Firefox 118.0

**Comment by varjolintu** [comment]
This can achieved by:
- Go to Settings and disable "Save domain only" under "Advanced settings".
- Go to https://bitconnect.at/kptest/index.html and save the Custom Login Fields.
- Login and save the password field to Custom Login Fields from `https://bitconnect.at/kptest/step2.html` page.

Seems the extension doesn't distinquish `https://bitconnect.at/kptest/` from `https://bitconnect.at/kptest/step2.html` so that's a bug.

**Comment by tofuSCHNITZEL** [comment]
Okay thanks for the info, I will try that.
Unfortunately with the real world example I derived this test site from the url does not change between the steps so I think this setting would not help...
Would it be feasible to change the behaviour of the custom fields functions to be "additive"? If you select a field for an url that was not already defined?

**Comment by varjolintu** [comment]
Alternatively you can just username and password normally for the front page, and on the next page use the attribute instead. If Custom Login Fields does not work for it, you can fill it also from the context menu using right-click on the input field.
