### ISSUE TITLE
Only the most recent database connection is remembered

### ISSUE THREAD

**Issue by ferenczy** [keepassxreboot/keepassxc-browser#2013]
I have multiple KeePass databases. When I connect a database in KeePassXC-Browser, only the most recently added connection is remembered, in other words, there's always only one database connection saved, even if I connect multiple databases and use a different identifier for each one.

## Expected Behavior

There are multiple database connections remembered in KeePassKC-Browser settings.

## Current Behavior

Only the most recently added database connection is remembered. When a second connection is added, the _Connected databases_ settings page lists both connections, but when I reload the page, it shows only the most recently added one (even when they had different identifiers).

So when I switch to another database, I always have to connect it again, because its connection has been "overwritten" by the previous database connection (again, I used a different identifier for each connection).

## Steps to Reproduce (for bugs)

1. Open the first KeePass DB in KeePassXC
2. Go to KeePassXC-Browser _Settings_ and open _Connected databases_
3. Click _Connect_
4. Enter the connection identifier, e.g. "DB 1" and hit Enter
5. Open the second KeePass DB in KeePassXC
6. Open KeePassXC-Browser _Settings_ > _Connected databases_
7. Click _Connect_
8. Enter the connection identifier, e.g. "DB 2" and hit Enter
9. There should be 2 connected databases in the list now
10. Reload the page
11. Only the most recently added connection is listed

## Debug info

KeePassXC-Browser Version: 1.8.9
KeePassXC Version: 2.7.6
OS: Ubuntu 22.04.3 64bit
Browser: Vivaldi 6.2.3105.58 64bit

**Comment by droidmonkey** [comment]
I cannot reproduce this on Edge, I have two databases connected and both show.

**Comment by varjolintu** [comment]
This sounds like a scenario where your second database is a copy of the  first one, so they share an identical hash used for identification.

Choose either one of the databases, go to Database Settings, Browser Integration tab and click the "Refresh database root group ID". After that disconnect all databases from the extension and remove all the keys from that same KeePassXC page that holds the Stored Keys. Reconnect both databases from the extension and see if it helped.

User will be alerted for this kind of scenario in the upcoming protocol version.

**Comment by ferenczy** [comment]
**So it was my fault.** I'm sorry for a stupid issue! 

Long story short: I have used the same key identifier for multiple connections in the extension, so the last one has always overwritten the previous one.

More detailed answer: The KeePassXC's _New key association request_ dialog suggests to use an identifier in the format "chrome-laptop". And that's what I was expecting - I'll have a separate key for each browser on each machine I'm using. But sometimes I also need to use another database, so I thought other databases will be sharing the same connection keys.

As it's currently implemented, it's obvious I need a separate key for each database-browser-machine combination so key identifiers are becoming quite huge (e.g. "_Browser @ Machine (database-name-YYYY-MM-dd @ SomeCloud)_").

Is it possible to share connection keys among several databases? I mean somehow automatically.

I have found a workaround:

1. Let's say I have the database `DB1.kbdx` with the connection key "Browser@Machine"
2. Open another database `DB2.kbdx` without any connection key
3. Initiate the connection from the browser extension
4. Use the same key identifier "Browser@Machine" so the previous key is overwritten in the extension (this step is needed to just create a key entry in the `DB2.kbdx` as I cannot do it manually)
5. Copy&paste the key from the `DB2.kbdx` to the `DB1.kbdx`

Now, I have both the `DB1.kbdx` and `DB2.kbdx` with the same key named "Browser@Machine".

But it's not very user-friendly and it gets worse as the number of databases increases.

**Comment by droidmonkey** [comment]
> Is it possible to share connection keys among several databases? I mean somehow automatically.

No, that would violate a core security feature of independent database connections. 

We do have an option called "Search all open databases" in the browser settings that emulates this behavior though. If one database is connected, then it acts as the gateway for the other open non-connected databases.

**Comment by ferenczy** [comment]
OK, that sounds usable, I have one main database permanently opened so it should work for me. Thank you!
