### ISSUE TITLE
App fails on openSUSE Tumbleweed but works on openSUSE Leap 15.5

### ISSUE THREAD

**Issue by Budgie2** [keepassxreboot/keepassxc-browser#2015]
## Overview
I work on workstations on two sites, one running openSUSE Tumbleweed (TW) and one running openSUSE Leap 15.5.  Both are configured with KDE desktop and have essentially the same configuration in use with KeePassXC (KP) app being run from appimage and using the same database.   I use Firefox browser and have the KP browser add-on installed on both machines and browsing configured in KP on both machines.

The Leap 15.5 works as usual and expected with a KP icon showing in task bar and when browser is running a small KP icon in browser, all green when database has been opened.

In TW the browser has no icon of any colour showing and when I try and log in from browser I usually have a grey KP icon appear but this never functions and invariably I have to enter my username and password by copying from the KP window.  

## Steps to Reproduce
1. Enter address of target site, in this case a Qnap NAS device on my Lan.
2. The log in screen is presented with grey KP icon in right hand end of username window. 
3. Mousing over KP icon there is a popup saying "Fill credentials from eKeePassXC
4. No credentials are offered but clicking on the grey KP icon I get a pink popup in browser with Error! No logins found.  
5. If I enter the credentials manually from KP window I am logged into the NAS.   

## Expected Behavior
I expect the credentials for my NAS log in to be entered.

## Actual Behavior
See the steps to reproduce. 

Please note if I carry out the same series of actions on the Leap 15.5 machine the credentials are entered by KP and I am logged in.  

## Context
I could not establish a time when this problem started as TW has updates on an almost daily basis.  I do have a Laptop with TW installed and so far this has not exhibited the same problem

KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: openSUSE Tumbleweed
CPU architecture: x86_64
Kernel: linux 6.5.6-1-default

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: openSUSE Tumbleweed
Desktop Env: KDE
Windowing System: Plasma X11
See:-
Operating System: openSUSE Tumbleweed 20231020
KDE Plasma Version: 5.27.8
KDE Frameworks Version: 5.111.0
Qt Version: 5.15.11
Kernel Version: 6.5.6-1-default (64-bit)
Graphics Platform: X11
Processors: 24 × Intel® Xeon® CPU E5-2620 v3 @ 2.40GHz
Memory: 62.8 GiB of RAM
Graphics Processor: AMD Radeon Pro WX 7100 Graphics
Manufacturer: Hewlett-Packard
Product Name: HP Z640 Workstation

**Comment by varjolintu** [comment]
Just the grey icon, not with the white X on red background on the corner? If so, it means your entry URL is incorrect.

**Comment by Budgie2** [comment]
Thanks for your comment.  I have been through the Troubleshooting-guide and am still working on it but the problem as far as I can see is that the path set in the json file is not correct but the /usr/bin/keepassxc-proxy is not present either.
I am going to re-install with a plain vanilla setup and try again.  Will report back.

**Comment by Budgie2** [comment]
Well I am not a coder and have failed to understand where the problem lies.  I now have the KeePassXC browser add-on working after a fashion but the small KP icon does appear in my browser toolbar and I cannot force re-connect from browser to KP as there is no pop up or drop down if you wish.  I really would like to resolve this but will need help so am asking if anybody has time please?

**Comment by varjolintu** [comment]
No popup or drop-down? Not sure what you mean. If you want some help, we need detailed info and maybe some screenshots, and steps to reproduce the problem.

**Comment by Budgie2** [comment]
Hi and many thanks, I will try my best.  
![Existing_browser_Screenshot_20231023_204224](https://github.com/keepassxreboot/keepassxc-browser/assets/1523295/e43e9b4b-946b-47ec-9553-7f2dc870e50f)

This is intended to show my browser screen and you can see there is no small KP-Browser icon in the Toolbar top right.
I have not been able to reselect login fields because there is no button and no icon to bring up this button.

I have been through the above Troubleshooting-guide and can see the jason file is in the ~/.mozilla/native-messaging-hosts and the file has the path to the AppImage file in a subdirectory of my Downloads directory.  After several re-installations of KP, KP-Browser and enabling the browser connection in different order I now have all the proxy connections working so I am much happier than I was but why no Toolbar icon?

**Comment by Budgie2** [comment]
Hi and thanks.  I have been trying to find all the hidden parts in the new wave Firefox for a couple of weeks - a nightmare made worse by the changed defaults thrust upon us.

Even so I still have the little green KP icon in my Toolbar on my Leap 15.5 machine and my TW laptop is also working as required.  It is only the subject problem TW machine that has the problems.  I had already found the jigsaw button (aptly named,) but this does not help me restore the KP icon, just confirms that KP is installed and enabled.
Any ideas?

**Comment by droidmonkey** [comment]
Right click the kpxc icon after showing it in the jigsaw and click on 'pin to toolbar' or similar

**Comment by Budgie2** [comment]
Hi Jonathan and many thanks.  That was the help I needed.  Still love your app and relieved it is working correctly on all my systems.  Not so much in love with Firefox!!!
Thanks again.
Budge

**Comment by droidmonkey** [comment]
Excellent, glad to help!
