### ISSUE TITLE
Brave + uBlock Origin = banner showing up without buttons on some sites

### ISSUE THREAD

**Issue by Nietzscheanman** [keepassxreboot/keepassxc-browser#2016]
## Expected Behavior
Right click -> KeepassXC Browser -> save credentials = banner on top of page to save new credentials

## Current Behavior
Small banner pops up as expected but there is no text or buttons in it. This happens only in Brave, only for certain websites (worked fine on github.com).

Also, updating credentials does not work (pushing button does nothing), even when using the workaround solution below.

## Possible Solution
Click on uBlock Origin extension icon. Disable cosmetic filters.
The problem does not appear when using Chrome with the same extensions.
**-> I assume I have to allow the extension to pass the uBlock Origin cosmetic filter somehow on Brave? No idea how to go about that, or it could be an issue with the extension itself perhaps?**

## Steps to Reproduce (for bugs)
1. Brave browser + uBlock Origin + KeepassXC Browser Extension with database unlocked
2. Go to for example https://alternate.be
3. Create new account or try to log in with account not saved to database
4. Right click -> KeepassXC Browser -> save credentials = banner on top of page to save new credentials pops up but has no text or buttons in it.

## Debug info
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'attribution-reporting'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'run-ad-auction'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'join-ad-interest-group'.
Error with Permissions-Policy header: Unrecognized feature: 'idle-detection'.
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'browsing-topics'.

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Win
Browser: Brave

Would be grateful for any insights - thank you

**Comment by varjolintu** [comment]
This is definitely something to do with Brave's own filtering if you cannot reproduce this with Chrome.

**Comment by Nietzscheanman** [comment]
> This is definitely something to do with Brave's own filtering if you cannot reproduce this with Chrome.

Thanks for your quick reply. Seems strange though that the workaround is to deactivate cosmetic filtering in uBlock Origin?

**Comment by varjolintu** [comment]
I don't find it strange. Maybe their cosmetic filtering is a bit too aggressive.
