### ISSUE TITLE
Does not work with FF 61.0b13

### ISSUE THREAD

**Issue by amnk** [keepassxreboot/keepassxc-browser#202]
Passwords should be retreived from the database on all supported browsers.

Password are not filled in with latest FF Developer Edition.

Steps to reproduce the problem:
1. Goto any site with previously saved passwords (I tried several, including AWS)
2. Passwords are not being retrieved.

## Debug info
I found this in console log (uuid is keepassxc-browser)
```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://86eec8f7-a4e4-694e-9d3e-ff39598f2916/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map
```
KeePassXC - 2.3.3
keepassxc-browser - 1.1.6
Operating system: MacOS High Sierra 10.13.5 (firewall is disabled)
Browser: Firefox
Proxy used: YES

It was all working just a day before, so I'm kinda lost :( Can someone at least suggest steps to debug the connectivity?

**Comment by varjolintu** [comment]
Upgrade to 1.1.7 and see if it fixes the issue.

**Comment by amnk** [comment]
Oh gosh I'm stupid. @varjolintu thanks!
