### ISSUE TITLE
Browser extension not working - "Key exchange was not successful."

### ISSUE THREAD

**Issue by MickaelOnTheWave** [keepassxreboot/keepassxc-browser#2021]
I get the "Key exchange was not successful." error when trying to connect the extension to KeePassXC. 

## Expected Behavior
I read the troubleshooting guide and could not find an answer to my problem there.
There is an interesting finding though, when I run the "sudo strace -f -yy -e read,write -s 1000000 -p xxx" command (xxx being the id of the keepassxc-proxy process), I don't get the same output as stated in the guide. What I get is :

strace: Process 23441 attached with 2 threads
[pid 23442] --- stopped by SIGTTIN ---
[pid 23441] --- stopped by SIGTTIN ---

## Debug info

KeePassXC - 2.7.6 (Installed from official website after adding your repository to APT)
KeePassXC-Browser - 1.8.9
Operating system: Ubuntu 22.04
Browser: Firefox installed with apt (Snap has been removed and disabled to prevent confusion)

**Comment by droidmonkey** [comment]
xxx needs to be the process id of your browser.

**Comment by MickaelOnTheWave** [comment]
I provided xxx to not publish the id of the process, I did not use 'xxx' literally in the command.
But anyway, you were right about AppArmor : I followed the instructions in the guide regarding AppArmor and it worked! Thank you.

(I didnt't know about AppAmor before nor that it was used on my sustem)

**Comment by droidmonkey** [comment]
No, you said you used the process id of keepassxc-proxy, but it should be the browser instead. I know you didn't actually use xxx.
