### ISSUE TITLE
Unable to connect on ubuntu linux with ms edge to keepass xc

### ISSUE THREAD

**Issue by federico-duppa** [keepassxreboot/keepassxc-browser#2023]
keepass xc does not show "edge" as an option

the browser extension is installed from the microsoft edge addons

extension debug info:
KeePassXC - unknown
KeePassXC-Browser - 1.8.9
Operating system: Linux x86_64
Browser: Microsoft Edge 118.0.2088.46

---

keepass-xc --debug-info

KeePassXC - Version 2.4.3
Revision: 5d6ef0c

Qt 5.12.8
Debugging mode is disabled.

Operating system: Ubuntu 20.04.6 LTS
CPU architecture: x86_64
Kernel: linux 5.15.0-87-generic

Enabled extensions:
- Auto-Type
- Integración con Navegadores
- Agente de SSH
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

---

browser integration is enabled and working OK with firefox

**Comment by varjolintu** [comment]
Does not show Edge option at all? Do you have a screenshot? All browser options should be there if Browser Integration is enabled. If you are running KeePassXC as Snap, you must use an extrenal script that is linked on the page.

But of course, I'd suggest you update your KeePassXC at first. Use the official [PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc) or Flatpak.

**Comment by droidmonkey** [comment]
You need to update keepassxc. We are on version 2.7.6.

**Comment by federico-duppa** [comment]
I confirm it works after updating and it feels so good. Thank you
