### ISSUE TITLE
Activating keepassxc-browser does not allow use of keyboard to navigate to the filtered list.

### ISSUE THREAD

**Issue by DavidPesticcio** [keepassxreboot/keepassxc-browser#2024]
When activating the keepassxc-browser with a browser keyboard shortcut or mouse click, on a page that yields multiple entries, then typing in the filter box to narrow the search list you cannot select the desired entry using keyboard navigation. Using TAB cycles through the existing buttons and the filter box, the UP/DN arrow keys do not work to move the focus to the filtered list.

## Expected Behavior
When using TAB or the UP/DN arrow keys to navigate from the filter box, the focus should move to the filtered list.

## Current Behavior
Using TAB cycles through the existing buttons, the UP/DN arrow keys do not work to move the focus to the filtered list.

## Possible Solution
Enable keyboard navigation to the filtered list with TAB, and/or UP/DN arrow keys.

## Steps to Reproduce (for bugs)
1. Visit a website that will yield multiple entries
2. Activate the plugin - either with a keyboard shortcut, or mouse click
3. Start typing in filter box to reduce the list
4. Try to navigate with keyboard to the filtered list - you can't. :sob: 

## Debug info
No errors in the browser's JavaScript console messages.

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Linux x86_64
Browser: Chrome/Chromium 118.0.0.0

**Comment by varjolintu** [comment]
Are you talking about the list visible in the popup? The keyboard is not supported there, but the Autocomplete Menu seen on the login field itself should work with keyboard as well.

**Comment by DavidPesticcio** [comment]
> Are you talking about the list visible in the popup? The keyboard is not supported there, but the Autocomplete Menu seen on the login field itself should work with keyboard as well.

Oh, that's a shame - it would be a nice to have! :smiley: 

The login field behaves better, as in it is more usable. Although it doesn't actually filter/reduce the list, or reduce the selection by cursor movement to only those containing the letters in the filter box. - Could that be a feature request? :wink:

**Comment by varjolintu** [comment]
Closing this as there's already a feature request.
