### ISSUE TITLE
Cannot log in with non-default browser

### ISSUE THREAD

**Issue by debmint** [keepassxreboot/keepassxc-browser#2025]
When specifying an alternate browser in keepassxc "cmd://browsername <url>" keepassxc brings up the correct url in the specified browser, but keepassxc-browser does not fill in credentials

## Expected Behavior

keepassxc-browser would fill in the credentials

## Current Behavior

keepassxc-browser does not provide the credentials.  brave-browser simply does nothing but a popup appears in firefox stating that the url cannot be found.

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.9
Operating system: Linux
Browser: Firefox, brave-browser

There may be some setting that I'm missing, but I've done web searches as well as look through all pertinent (that I know of) documentation and have found nothing helpful.  I use Librewolf as my default browser, but have a few where it apparently blocks something thus requiring me to use something else, and I also use different browsers for certain purposes.

This could simply be an issue of "operator error" and if so, any instruction would be appreciated.  From observation, it appears that perhaps keepassxc-browser might not be stripping out the "cmd://browser " part and thus failing to match the url

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

Please go through this, you likely need to adjust apparmor policies.

**Comment by debmint** [comment]
> https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
> 
> Please go through this, you likely need to adjust apparmor policies. We are also on version 2.7.6 of KeePassXC.

I  had looked through this already, but have reviewed i again, paying especial attention to the apparmor section.  I'm sure it's not a permissions issue.

> You can define an alternative url un the browser tab when editing an entry. If you have just the cmd url, then you will have to do that.

Not sure what you mean by alternative url.. I did just try this for github, To log in with my default browser, I simply have "https://github.com/login". To log in with firefox, for example, I add "cmd://firefox " in front of this url to get "cmd://firefox https://github.com/login" and this did, indeed work.  However, if I try this with a site like "https://url.com/something/somethigelse?<long list of query strings>" I get the error "No logins for https://url.com" where the web address is truncated to simply the base url  The afore-mentioned web address is a little over 200 chars.  Could it be that keepassxc-browser is not transferring a string this long? I ran the strings command on keepassxc, and all I got was "No logins found", but the above error should have been "No logins for %s" so I'd assume that this must be coming from the extension.

I can live with it, but if it's a simple-to-fix but, it would be nice to have it working.

Thank you for your time in responding.

**Comment by varjolintu** [comment]
@debmint You should use as short version of the URL possible. So instead of `https://url.com/something/somethigelse?` the matching would probably succeed better with `https://url.com/something` without any extra paths or variables starting `?` at the end.

**Comment by debmint** [comment]
> @debmint You should use as short version of the URL possible. So instead of `https://url.com/something/somethigelse?` the matching would probably succeed better with `https://url.com/something` without any extra paths or variables starting `?` at the end.

I wish I could, but in this particular instance, it's something like a third-party login manager used by the website I wish to access, and I don't see any way to avoid it.  It's OK.  I don't access it on a regular basis.  I can always access the site through keepassxc and copy/paste the fields.  Thanks for the input.  I would like to note that if I remove the cmd://firefox part and make firefox my default browser, the login works flawlessly.  Additionally, this problem is not restricted to firefox,  any browser I try as the alternate fails, also.

**Comment by droidmonkey** [comment]
Like I said before, you need to setup alternate urls for these cmd:// entries. Foll these directions: https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage

**Comment by debmint** [comment]
> Like I said before, you need to setup alternate urls for these cmd:// entries. Foll these directions: https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_usage

I finally see.  Somehow I overlooked this part of the docs.  Thought I'd read about Browser Integration thoroughly but apparently not.  Following your link, it works like a charm.  Thanks for bearing with me through my denseness.
