### ISSUE TITLE
Message of the day causes username to not populate 

### ISSUE THREAD

**Issue by ZenMasta** [keepassxreboot/keepassxc-browser#2026]
https://secure2.procharge.com/Merchantlogin.aspx
This website sometimes has a warning/alert and when that happens, the username field won't populate on firefox and in chrome the fields are shifted down one...

## Current Behavior/steps to reproduce
On Firefox when I click the green key icon it only populates the regkey and password field and the green icon appears in the username field.
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/823528/2e707a3a-259a-4bdc-8781-b1e7b733ab98)
But on chrome, the green icon appears in the regkey field and although it does not populate the username (login field) it puts the username in the regkey field.
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/823528/bafc4b83-2896-44ea-bb77-379f994d58f3)

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Win64
Browser: Mozilla Firefox 119.0
Browser: Chrome/Chromium 119.0.0.0

**Comment by varjolintu** [comment]
Use Custom Login fields to set these.

**Comment by ZenMasta** [comment]
I already use custom login fields and they work fine. As mentioned, the only problem is when there is a message of the day at the top of the page.

**Comment by varjolintu** [comment]
Sometimes these kind of messages and banners alters the page content and it's not detected by the extension. If you refresh the page after that, does it still show the icon at the wrong position?

**Comment by ZenMasta** [comment]
Yes but only on chrome and I only tried chrome for the sake of testing. Firefox (which I use as my default browser) has the icon in the correct position still (but as mentioned won't fill in the username ("login" field)

**Comment by varjolintu** [comment]
I set the fields like this in Firefox and had no problems when filling:
<img width="369" alt="Screenshot 2023-11-06 at 21 40 18" src="https://github.com/keepassxreboot/keepassxc-browser/assets/24570482/041d3919-c549-4a0c-971b-90b9aa7beebc">

**Comment by ZenMasta** [comment]
That's how it was configured in the first place. There is something else I noticed. 
When I click the icon, the login (username) field is populated, but only for few miliseconds.

If I click the icon from the browser menu bar, and then select from the list, it does populate the fields just fine 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/823528/ca5307ea-84bd-4b11-894a-6be79e5e6656)

So I guess that's what I'll do since they have these MOTD's pretty often. Still doesn't help with chrome but since I don't use chrome I didn't bother trying to redetecct the fields to see if that helped.

**Comment by varjolintu** [comment]
That's probably because the page has some script that possible modifies the input field value if the field or document is focused. Filling from the popup doesn't have that kind of scenario. Some web pages act the opposite: popup fill clears up but the Username Icon works. Sadly there's not much we can do here.
