### ISSUE TITLE
feature request: keyboard shortcut for reconnecting to keepassxc database

### ISSUE THREAD

**Issue by raveit65** [keepassxreboot/keepassxc-browser#2027]
## Expected Behavior
Usually i started firefox automaticlly with desktop user session (fedora mit Mate desktop). Keepassxc will be started after a internet browser is open. At this point keepassxc-browser isn't connected with a opened database from keepassxc.
Now a working keyboard shortcut for a reconnect to database would be world class.

## Current Behavior
It's only possible to use a mouse or a trackball device to reconnect keepassxc-browser-plugin to database :/

## Possible Solution
Adding a keyboard shortcut to keepassxc-browser-plugin

## Steps to Reproduce (for bugs)
Not a bug.

## Debug info
fedora 38 linux with firefox, chromium and chrome browser.

I hope this would be possible. Thanks

**Comment by varjolintu** [comment]
There's already a keyboard shortcut option implemented you can configure: https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/manifest.json#L123

Alternatively you can just use a keyboard shortcut for filling credentials. It should do the reconnect as well.

**Comment by raveit65** [comment]
```
"reload_extension": {
            "description": "__MSG_popupReloadButton__"
        }
```
Ok, but which keyboard shortcut is used for this function?

**Comment by raveit65** [comment]
@varjolintu  ^^^

**Comment by varjolintu** [comment]
> ```
> "reload_extension": {
>             "description": "__MSG_popupReloadButton__"
>         }
> ```
> 
> Ok, but which keyboard shortcut is used for this function?

None. You'll have to configure that by ourself from your browser. Extensions only allow four different keyboard shortcuts defined by default, and all four are already used for filling.

**Comment by raveit65** [comment]
> None. You'll have to configure that by ourself from your browser. Extensions only allow four different keyboard shortcuts defined by default, and all four are already used for filling.

Got it.

> Alternatively you can just use a keyboard shortcut for filling credentials. It should do the reconnect as well.

This works well, thanks for helping.
