### ISSUE TITLE
TOTP filling does not work

### ISSUE THREAD

**Issue by cornercase** [keepassxreboot/keepassxc-browser#203]
When using either Ctrl-Shift-T or selecting "Fill TOTP" from the context menu does not cause TOTPs to be filled.

## Expected Behavior
When using the previously mentioned functions, the TOTP should fill in correctly.

## Current Behavior
TOTPs do not fill with Ctrl-Shift-T or "Fill TOTP" menu option.  The behavior is the same whether or not there are multiple entries that match the URL.  Copying the OTP from KeepassXC directly works fine.

## Steps to Reproduce (for bugs)
1. Set up a TOTP token in a KeepassXC entry
2. Test that it generates OTPs
3. Go to the site, attempt to use KeepassXC to fill the TOTP field in the chosen website

## Debug info
There are no js console messages at all.

KeePassXC - 2.3.3
keepassxc-browser - 1.1.7
Operating system: Mac High Sierra 10.13.4 (17E199)
Browser: Reproduced in both Chrome 66.0.3359.181 and Firefox 60.0.2
Proxy used: No

**Comment by varjolintu** [comment]
Have you selected/filled the credentials before filling TOTP?

**Comment by cornercase** [comment]
Yes, the credential filling works fine in both the case where only one
entry matches the URL and when multiple entries match the URL.

On June 13, 2018 at 11:49:43 AM, Sami Vänttinen (notifications@github.com)
wrote:

Have you selected/filled the credentials before filling TOTP?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/keepassxreboot/keepassxc-browser/issues/203#issuecomment-397008236>,
or mute the thread

**Comment by varjolintu** [comment]
The reason why I asked this is that TOTP filling requires you to fill credentials first. It still doesn't work?

**Comment by cornercase** [comment]
I am navigating to a site, then filling the user and password, and pressing enter.  It takes me to another page on the site to fill the TOTP.  I tried running the "Fill username and password" first on the TOTP page (which only has one field), and it puts my username in the TOTP field and then reports that it can't find fields to fill the other data.

**Comment by varjolintu** [comment]
I assume you have multiple credentials for that site? I could confirm a situation where the credential order has somehow changed in the next page when trying to fill the TOTP.

**Comment by cornercase** [comment]
I have tested it in both the case where there is only one entry and when there are multiple entries.  Neither works.  I also tried on multiple sites and none of them worked.

**Comment by varjolintu** [comment]
Are you able to debug the extension? I cannot reproduce the issue. With Chrome, open the Inspector to the page you enter the TOTP and put a breakpoint to this function:
https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/keepassxc-browser.js#L1673

**Comment by cornercase** [comment]
I'm trying to debug the extension but if I view the background page for the plugin through the extension management page in Chrome, I don't see browser.js but I do get an error that no URL is being provided in keepass.js.  If I inspect the page I'm trying to add the TOTP to, I don't see anything related to the plugin.  Do I need to load an unpacked extension to do this debugging or am I just missing something?

**Comment by varjolintu** [comment]
Content scripts are not visible in the background pages. You need to right click on the page and select "Inspect" from the context menu. Then go to debugging tab and you should be able to open keepassxc-browser.js from there.

**Comment by cornercase** [comment]
OK, finally figured it out.  There was an extra space in the "KPH: {TOTP}" entry, so it was failing to find the entry.  It works now, problem between the seat and the keyboard.

**Comment by vasyugan** [comment]
It 

> OK, finally figured it out. There was an extra space in the "KPH: {TOTP}" entry, so it was failing to find the entry. It works now, problem between the seat and the keyboard.

Can you be specific? Because for me it also doesn't work. I am using it for two Nextcloud instances, on both, filling in the credentials works fine, but fill in TOTP does nothing.
