### ISSUE TITLE
"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." Arc Browser based on chromium 

### ISSUE THREAD

**Issue by Mahmoud-Skafi** [keepassxreboot/keepassxc-browser#2037]
Keepassxc can't connect to the database that I created, I tried with Google Chrome and it works, The problem happened when I used Arc Browser based on Chromium.

I enabled browser integration with Chromium and It did not work, I tried it with Google Chrome and it works fine.

## Steps to Reproduce (for bugs)
1. Download Arc Browser.
2. Download the extension.
3. Try to connect to the database.

## Debug info
KeePassXC-Browser Version: 1.8.9
KeePassXC Version: 2.7.6
Operating system: Mac
Browser: Arc Browser Chromium

**Comment by varjolintu** [comment]
Use the Custom Browser feature to add path to the Arc Browser's native-messaging-host folder.

**Comment by droidmonkey** [comment]
Use the custom browser feature. Settings -> Browser -> Advanced tab

**Comment by kifeo** [comment]
in my case the path to configure in KeepassXC at is Settings -> Browser -> Advanced tab ~/.config/chromium/NativeMessagingHosts
