### ISSUE TITLE
Shortcut for Fill TOTP would be great

### ISSUE THREAD

**Issue by eloo** [keepassxreboot/keepassxc-browser#204]
Hi,
what do you think if a shortcut for "Fill TOTP" would be useful?

In my case it would be nice to fill totp without using the mouse ;)

thanks

**Comment by varjolintu** [comment]
It's already there. Alt+Shift+T or Ctrl+Shift+T with macOS. Sorry the lack of documentation (I'm writing it as we speak).

**Comment by eloo** [comment]
awesome.. thanks 👍
