### ISSUE TITLE
Changing password doesn't update keepass

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc-browser#2044]
## Expected Behavior

The password should be updated

## Current Behavior

The password is not updated.

## Steps to Reproduce (for bugs)

I have several Paypal accounts. I tried changing the password via the Paypal webpage:

1. Go to https://www.paypal.com/myaccount/security/password/change
2. As expected KeepassXC does enter the password into the old password and offers a password generator on the new password
3. Generate a new password and also copy it to the clipboard
4. Paste it to the 2nd field for the new password
5. Enter to apply the new password
6. KeepassXC offers updating the password. Because I have several accounts it also offers all available Paypal accounts and I choose the matching one. But the password is not updated. I need to copy the new password from my clipboard manually inside KeepassXC to that account. I tried it several times with the other accounts and I was always able to reproduce the issue.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.9
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
This is fixed with: https://github.com/keepassxreboot/keepassxc/pull/9853
