### ISSUE TITLE
Not working on ibank.bog.ge

### ISSUE THREAD

**Issue by Kobaxidze256** [keepassxreboot/keepassxc-browser#2045]
## Expected Behavior
Detect log-in fields on https://ibank.bog.ge or let me select them manually.

## Debug info

KeePassXC - 2.7.6 dd21def
KeePassXC-Browser - 1.8.9
Operating system: Arch Linux
Browser: librewolf-bin 119.0.1-1

**Comment by varjolintu** [comment]
This is currently not possible because there's a an iframe behind Shadow DOM, and currently we have no support for such scenario. We only detect input fields behind Shadow DOM, but not whole iframes.

**Comment by varjolintu** [comment]
Tracked in: https://github.com/keepassxreboot/keepassxc-browser/issues/1358
