### ISSUE TITLE
Can't use KeePassXC-Browser extension unpacked or from self-packed CRX

### ISSUE THREAD

**Issue by bananakid** [keepassxreboot/keepassxc-browser#2046]
**First of all, sorry for lengthy explanation!** TL;DR I'd like to be able to stick with the working combination of browser+KeePassXC+KeePass-Braowser for stability reasons, but it appears it can't be done at the moment.

## Expected Behavior

When I download ZIP of Chromium extension from releases section, I should be able to "Pack extension" using my PEM file (with PEM ID included in browser's allowed extensions policy) via Chromium browser or just unzip downloaded file and use the option "Load unpacked" for the extension. This should make it possible to escape some bugs caused by extension/browser updates because the function of TOTP authorization provided by KeePassXC is critical. 

## Current Behavior

When I download ZIP of Chromium extension from releases section and "Pack extension" via my Chromium browser, and then install the packed extension from CRX file (with PEM ID included in browser's allowed extensions policy), the extension 100% of the time fails to connect to local KeePassXC database. When I try to load the extension without building CRX just using "Load unpacked", it loads but fails to connect to local KeePassXC database too. However if I download a CRX from Edge Extensions of Chrome Web Store and install it without modifying, the extension connects to local KeePassXC database no problem. If I then unpack the downloaded CRX and edit it's manifest to exclude the update line with the update URL (to prevent updating automatically), the extension once again cannot connect to local KeePassXC database.

## Possible Solution

Some browser policy to prevent extension from updating. Or some changes to internal checks of KeePassXC-Browser.

## Steps to Reproduce (for bugs)

Listed in behavior paragraphs.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.10
Operating system: Windows 10, version 21H2
Browser: Microsoft Edge 100, Google Chrome 120

**Comment by varjolintu** [comment]
"Load unpacked" with the temporary extension ID added to the JSON scripts should work. Just make sure KeePassXC has "Update native messaging manifest files at startup" option disabled in the Browser Integration -> Advanced tab. Not sure why you want to pack the extension as an extra step.

**Comment by droidmonkey** [comment]
As varjolintu said, you need to add the extension ID, that your side-loaded extension is using, to the native messaging json file(s). However, I have no idea why you are side loading the extension in the first place. You mention something about totp breaking, but that isn't a known problem at this time.
