### ISSUE TITLE
Not working on flatex

### ISSUE THREAD

**Issue by Massimo-B** [keepassxreboot/keepassxc-browser#2047]
## Current Behavior

On https://www.flatex.de/, Keepassxc-Browser does not offer username and password, eventhough all URLs are added to the entry:
https://www.flatex.de/
https://konto.flatex.de

Manually adding username/password from context menu, the error message is:
`Not found. https://konto.flatex.de`

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.10
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Tracked ihttps://github.com/keepassxreboot/keepassxc-browser/issues/1358.
