### ISSUE TITLE
UX: Don't show cryptic error messages

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#205]
## Expected Behavior

User experience: There should be clear messages:
* Database is clocked. Please unlock. (possible right now and implemented) Link -> Unlock database.
* No database is opened. Please open a database. Link -> start keeepassxc

## Current Behavior

* "KeePassXC native messaging encryption error communication fail" something-like-this (loosely translated into how the user sees this error message :wink: )

## Possible Solution

I guess, you could try to keep the KeePassXC proxy active and use it to implement some features like probing for active KeePassXC instances.
In the result, the add-on (and thus users) should be able to detect what prevents the add-on from being used, e.g. KeePassXC is closed (user should then be able to start it with one click on a button), or locked (user click -> unlock, that is implemented AFAIK).

Possibly it could even detect when you have the wrong database selected, but that may be https://github.com/keepassxreboot/keepassxc-browser/issues/206.

## Steps to Reproduce (for bugs)

1. I guess it happens, when KeePassXC is closed.

**Comment by varjolintu** [comment]
This is actually in my to-do list. I want the proxy be active all the time and it can reconnect to KeePassXC on-the-fly. This feature is not going to work good enough in the extension side. With a proper reconnect in the proxy those cryptic error messages are gone.

**Comment by varjolintu** [comment]
The error messages are improved, so closing this.
