### ISSUE TITLE
Auto-tick "remember me" boxes on login pages

### ISSUE THREAD

**Issue by jerome-tgl** [keepassxreboot/keepassxc-browser#2050]
Many pages let users tick a "remember me" box after entering login details so the session can remain active after leaving the website.

These check-boxes are usually not checked by default so one must re-log into these websites if the the extension was used to fill-in and submit the login details automatically.

This could be implemented by creating a "KPH: Remember" boolean attribute, saved as a Custom login field so user can manually select the check box. And the extension could have rules to auto-detect them on login pages and tick them by default on auto-fill.

I know KeepassXC has an advanced setting to "Never ask before accessing credentials" but it doesn't tell the website to remember the login so new logins are always required.

NB: a [similar issue](https://github.com/keepassxreboot/keepassxc-browser/issues/1474) was closed in 2021 but it was confused with the "Never ask before accessing credentials" feature.

**Comment by mbeko** [comment]
I have the same problem. Earlier, I used auto-type which I had configured to tick those "remember" check boxes on the website where it's not ticked by default. Now that Firefox switched to Wayland, auto-type is not available anymore.

So I switched to the browser extension, but it can only interact with the username and password fields, not the check box. It's a bit tiresome to do more clicks on websites that forget the session after 15 minutes if the box is not ticked.

**Comment by danw-eth** [comment]
Same issue here, would really appreciate if the Chrome extension Auto-Submit function could tick the usual "remember me" or "stay logged in" boxes that many websites have. Some websites log you out fairly quickly, which can be time consuming if you have to use google authenticator or another key to finalise your login each time.

**Comment by varjolintu** [comment]
This would be quite difficult to implement. There's no standard how to present these buttons in the login forms, so there would be many hit-and-miss situations if some automatic detection would be done. Implementing this only to the Custom Login Fields side would make more sense.

**Comment by danw-eth** [comment]
> Implementing this only to the Custom Login Fields side would make more sense.

Custom login fields would be great, currently there's only a "string" option to choose a custom field but if we could assign a value to a selected Boolean/checkbox field that would be fine.

**Comment by varjolintu** [comment]
> > Implementing this only to the Custom Login Fields side would make more sense.
> 
> Custom login fields would be great, currently there's only a "string" option to choose a custom field but if we could assign a value to a selected Boolean/checkbox field that would be fine.

This would be the preferred solution, yes. In this way there's no extra option needed in the extension settings.
