### ISSUE TITLE
Error trying to connecgt

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc-browser#2062]
KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 
## Debug info

KeePassXC - latest
KeePassXC-Browser - latest
Operating system: FEDORW
Browser: LIBREFOX

**Comment by droidmonkey** [comment]
Please search these issues and go through the troubleshooting guide

**Comment by theking2** [comment]
If search for fedora and nothing came up
