### ISSUE TITLE
Error upgrading credentials

### ISSUE THREAD

**Issue by Darknet** [keepassxreboot/keepassxc-browser#2063]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

We need to add keepassXc extension to brave browser and configure to connect to database

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Change an entry on any webpage.
2. logon to this webpage
3. Wait until message appear, if you press upgrading button no action appear, if you press New, a message with success appear.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

When i'm trying to upgrade a password on my database the only way is add a new entrry, because upgrade credentials isn't working

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Versión 2.7.6
Revisión: dd21def

Qt 5.15.10
Depurated mode disabled

OS: Windows 11 Version 2009
CPU Architecture: x86_64
Kernel: winnt 10.0.22621

Enabled Extensions:
- Autowrite
- Browser IntegrationIntegración con navegadores
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

**Comment by varjolintu** [comment]
This is already fixed in: https://github.com/keepassxreboot/keepassxc/pull/9853
