### ISSUE TITLE
Connection not working on Librewolf on Fedora

### ISSUE THREAD

**Issue by theking2** [keepassxreboot/keepassxc-browser#2064]
Fedora:Linux fedora 6.5.12-100.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Nov 20 22:28:44 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Librewolf : 120.0.1-1
KeepassXC : 2.7.6
KeePassXC-Browser Version: 1.8.10

KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 

KeepassXC-Browser works fine in Chromium.

**Comment by varjolintu** [comment]
Please do not create multiple issues. The [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) says you'll have to use KeePassXC's Custom Browser feature (Settings -> Browser Integration -> Advanced tab).

Enable the option, choose Firefox and set `~/.librewolf/native-messaging-hosts` as the Custom Browser path.

**Comment by theking2** [comment]
maybe you should include your solution in the Troubleshooting guide. As it is now it is overly long convoluted and therefor useless.

You want me to update the guide to be understandable? It would reduce the noise here.

**Comment by droidmonkey** [comment]
If you can do better, then by all means copy the wiki page into a gist and make your proposed changes.
