### ISSUE TITLE
Cannot connect to keepass database from browser extension

### ISSUE THREAD

**Issue by waeh** [keepassxreboot/keepassxc-browser#2077]
After reinstalling my machine and reinstalling keepassxc, I cannot connect to my keepass database file from the edge browser extension.
I have read through the troubleshooting guide.
## Expected Behavior
When I click the 'reload' button, i want to connect to my local keepass.

## Current Behavior
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

## Possible Solution
keepassxc-proxy.exe was not started, had to start it manually. Did not work, nonetheless.
This is a corporate controlled machine, antimalware protection could be a cause.

## Steps to Reproduce (for bugs)
1. Start keepass and allow for broswer integration.
2. Install and start extension i edge browser.
3. Click 'reload'

## Debug info
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
 [Error client.js:387] KeePassXC-Browser - Failed to connect: Specified native messaging host not found.
 [Error keepass.js:811] KeePassXC-Browser - changePublicKeys failed: TypeError: Cannot read properties of null (reading 'postMessage')

KeePassXC - KeePassXC 2.7.6
KeePassXC-Browser - 1.8.10
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
If the `keepassxc-proxy.exe` cannot be started by the browser, it must be some restriction in your computer's policies.
Did you also check this one? https://keepassxc.org/docs/KeePassXC_UserGuide#_advanced_setup

**Comment by waeh** [comment]
I did not check that, thanks for pointing it out. I'll contact the it-dept. Get back to you, if problem not solved.
