### ISSUE TITLE
"No TOTP found" on auto-complete in Brave

### ISSUE THREAD

**Issue by FADE-UP** [keepassxreboot/keepassxc-browser#2078]
Hello!
I am using a TOTP for the login page at my university. Everything was working fine. About two months ago, the TOPT token did not fill anymore.

## Expected Behavior
TOTP code gets added to the input field to complete the login

## Current Behavior
Error message is shown: "Warning! No TOTP found."

If I open KeepassXC, go to the password entry, right click, TOTP and "copy TOTP" I get a valid TOTP token and can manually past it to the input field. The basic TOTP setup seems to be correct but the browser plugins fails to fetch it.

I already tried removing and reconnecting the database.

## Steps to Reproduce (for bugs)
1. Setup TOTP for a password entry
2. Login to the page
3. On the TOTP input field try to click the "auto-fill" button from the keypassxc plugin

## Debug info
I am using dual boot system on Surface Book 2.
My database lies in a onedrive folder, if that's maybe the problem. Idk
On both OS it does not work anymore, but it has worked previously before.

Windows:
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Win64 (Pro)
Browser: Chrome/Chromium 120.0.0.0

Ubuntu:
KeePassXC - 2.6.6
KeePassXC-Browser - 1.8.11
Operating system: Linux x86_64 (Ubuntu 22.04.3 LTS)
Browser: Chrome/Chromium 119.0.0.0

**Comment by varjolintu** [comment]
Is the TOTP's page URL different from the entry URL? If so, add another URL to Additional URL's list.

**Comment by FADE-UP** [comment]
Okay, I changed the URL and this was indeed the problem. Embarrassing mistake from my side. Thank you for the hint :)
