### ISSUE TITLE
Error - No logins found on local website, URL is entered in KeepassXC entry

### ISSUE THREAD

**Issue by Bart80-1** [keepassxreboot/keepassxc-browser#2080]
Hi,
I cannot get the login/password to fill in to the (local) Synology NAS web interface (DSM). The interface is running on port 5000 and I know from experience that sometimes you have to enter .local after the hostname and sometimes not... (Linux client). So all possible combinations are entered in the KeepassXC entry:
hostname
hostname.local
hostname:5000
hostname.local:5000

Other website logins work, so the issue must be something with this entry... Can anyone help?

## Expected Behavior

When visiting the web interface of the NAS: when clicking the key icon, username gets filled in (it is a 2 page login, password is on a second page). When clicking next, password gets autofilled in as well (possibly also after having clicked the key icon).

## Current Behavior

When visiting the web interface of the NAS: icon appears, but when clicking it, error message: Error: no logins found http://hostname.local:5000

## Steps to Reproduce (for bugs)
Not easy to give reproduction steps as I only have this for one website, so no idea what the cause could be. Can be for various reasons: local website, http instead of https, ... 

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 121.0

**Comment by varjolintu** [comment]
Make sure your entry url has `http` if your local URL is only provided under `http` scheme. The extension and KeePassXC defaults to `https`.

**Comment by Bart80-1** [comment]
> Make sure your entry url has `http` if your local URL is only provided under `http` scheme. The extension and KeePassXC defaults to `https`.

Yes, that did the trick! Thanks!
