### ISSUE TITLE
Incorrect translation of Passkey related messages in French

### ISSUE THREAD

**Issue by Sildulir** [keepassxreboot/keepassxc-browser#2085]
The translation of messages related to passkeys in French is incorrect and refers to "mot(s) de passe" ("password(s)") instead.

## Expected Behavior

The translation correctly refers to either "passkey" (which has yet to get a term in French as far as I am aware and is how they are called by Google anyway).

## Current Behavior

Currently, multiple messages, most importantly the configuration options refer to passkeys as "mots de passe" which is the term for password. **That make enabling passkey support and properly understanding passkey related error messages much harder than it needs to be.**

## Possible Solution

The messages `optionsPasskeysTitle`, `optionsPasskeysEnable`, `optionsPasskeysEnableHelpText`, `optionsPasskeysEnableFallback`, `optionsPasskeysEnableFallbackHelpText` and `errorMessagePasskeysRequestCanceled` should all be fixed to talk about passkeys instead of passwords.

I would use the following translations instead of the current ones personally:

* `optionsPasskeysTitle`: "Passkey" (again, this is what Google use so it is most likely what is going to be looked for by a user)
* `optionsPasskeysEnable`: "Activer les Passkey"
* `optionsPasskeysEnableHelpText`: "Activer le support pour l'authentification sans mot de passe avec passkey." (I am keeping the infinitive here, but I would probably use "Active <...>" personally)
* `optionsPasskeysEnableFallback`: "Activer les Passkey de secour" (I am not happy with this one but I can't think of a better version off the top of my head right now.)
* `optionsPasskeysEnableFallbackHelpText`: "Si activé, dans le cas où une requête de passkey à KeepassXC est annulée ou échoue, l'implémentation des passkey par le navigateur sera utilisé. Si désactivé, la connexion avec KeePassXC reste nécessaire et toute requête infructueuse se soldera par un échec. Activé par défaut."
* `errorMessagePasskeysRequestCanceled`: "La demande de passkey a échouée." 

## Steps to Reproduce (for bugs)

Not particularly certain this is useful in this case but here is a way to see the incorrect translation for yourself:

1. Have your browser interface in French (at least in Firefox this is what define the language used in the configuration page)
2. Restart your Browser if you had to change this setting (this is definitely needed on Firefox, not certain for Chromium-based Browsers)
3. Look for the configuration options for passkeys
4. You should only see references to "mot de passe" (password)

## Debug info
KeePassXC - N/A
KeePassXC-Browser - 1.8.11
Operating system: N/A (the translation is the same regardless of OS)
Browser: N/A (the translation is the same regardless of Browser)

**Comment by varjolintu** [comment]
Translations and errors related to them are handled in Transifex: https://explore.transifex.com/keepassxc/keepassxc/
