### ISSUE TITLE
When changing password from within browser, password is not saved in KDBX file

### ISSUE THREAD

**Issue by Bart80-1** [keepassxreboot/keepassxc-browser#2088]
## Expected Behavior
I found this out while changing my password on Github. But possibly it is the same problem on other pages. 

When I change my password via the appropriate page on Github, Keepassxc-browser correctly finds out that the password is changed and shows the dialog where it mentions that username or password has changed with the options to either create a new entry or to update the existing one. When clicking the option to update the existing entry, I would expect that the password is changed in the existing entry.

## Current Behavior

When clicking the option to update the existing entry, nothing happens - the banner is not removed and the entry is not saved. Also, no new entry is created in the KDBX file.

## Steps to Reproduce (for bugs)

1. Visit https://github.com/settings/security
2. Update your password. I used the password generated (in case this is relevant)
3. Save the password using the Update password button
4. A banner appears displaying the message (translated myself from Dutch, so possibly not literally the message) "Username of password changed! Save?" with the buttons "New", "Update" and "Ignore". 
5. When clicking Update, nothing happens - banner remains and no entries are added or updated in the KDBX file. 

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 121.0

**Comment by varjolintu** [comment]
This is already fixed in the KeePassXC side. Wait for the new release.

**Comment by Bart80-1** [comment]
> This is already fixed in the KeePassXC side. Wait for the new release.

Ok thanks. 
Just for my info, what issue is this exactly linked to on KeepassXC side? Cannot immediately find something that fits in...

**Comment by varjolintu** [comment]
@Bart80-1 https://github.com/keepassxreboot/keepassxc/pull/9853
