### ISSUE TITLE
KeepassXC browser plugin does not work anymore with Firefox

### ISSUE THREAD

**Issue by dkotsikau** [keepassxreboot/keepassxc-browser#2089]
## Expected Behavior

Browser integration works and Firefox connects to the database

## Current Behavior

Browser integration is broken and Firefox fails to connect to the database

## Steps to Reproduce (for bugs)
1.
`sudo snap refresh firefox --beta`
`sudo add-apt-repository ppa:phoerious/keepassxc`
`sudo apt update`
`sudo apt install keepassxc`
`sudo flatpak permission-set webextensions org.keepassxc.keepassxc_browser snap.firefox yes`

2. install https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/
3. Open keepasxc configuration and press connect
4. `tail -n 100 /var/log/syslog | grep firefox`
It reports:
`Jan 21 13:52:05 ubuntu firefox_firefox.desktop[40413]: [Parent 40413, Main Thread] WARNING: OnGetManifestDone error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “GetManifest”: 'glib warning', file /build/firefox/parts/firefox/build/toolkit/xre/nsSigHandlers.cpp:187
Jan 21 13:52:05 ubuntu firefox[40413]: OnGetManifestDone error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such method “GetManifest”
`

## Debug info

KeePassXC - 2.7.6 from ppa and 2.8.0 from appimage
KeePassXC-Browser - 1.8.11
Operating system: Ubuntu 22.04
Browser: Firefox

**Comment by varjolintu** [comment]
We don't support dev/beta browser. You'll have to use the Custom Browser feature in the Browser Integration settings to enable a custom path where beta browser's settings are stored. In Firefox's case it might be something like `~/.mozilla-beta/native-messaging-hosts`.

If the beta browser still does not work or has some strange bugs, we suggest you use a stable version of the browser.

**Comment by jheld** [comment]
Similar issue just started at least as of today, seeing the same error.

I am running keepassxc and firefox both as snaps and have all along. Firefox channel `latest/stable:    122.0-2      2024-01-23 (3687)`

**Comment by varjolintu** [comment]
> Similar issue just started at least as of today, seeing the same error.
> 
> I am running keepassxc and firefox both as snaps and have all along. Firefox channel `latest/stable: 122.0-2 2024-01-23 (3687)`

Someone else ran to the issue also with Snaps: https://github.com/keepassxreboot/keepassxc-browser/issues/2091
