### ISSUE TITLE
Pops up, but doesn't fill.

### ISSUE THREAD

**Issue by Welved** [keepassxreboot/keepassxc-browser#2090]
## Overview
On version 121.0.1 of Firefox for Ubuntu 22.04, when clicking the little fill icon via the extension; while opens up to prompt keepassxc to unlock as a whole, but it doesn't actually fill. All it seems to do is open keepassxc.

In order to actually have it fill, I have to click that keyboard icon in keepassxc to auto fill.

1. Go to a online service.
2. Click the keepassxc browser extension icon
3. The extension opens up KeepassXC, prompting for a unlock of the database
4. I have KeepassXC to minimize to the taskbar, so I have to click the icon once more to open to fill.
5. Click the keyboard icon to do a manual fill.

## Expected Behavior
Click the KeepassXC extension within the username and password fields and have it auto fill the fields.

## Actual Behavior
Clicking either the extension icon or the icon within the fields, it only opens up KeepassXC, bring it to the foreground.

## Context
I have no issues with KeepassXC with brave or chrome. The issue with firefox has improved, but still needs some work.

[NOTE]: # ( Paste debug info from Help → About here )

KeePassXC - Version 2.7.6
Revision: dd21def
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Ubuntu 22.04.3 LTS
CPU architecture: x86_64
Kernel: linux 6.5.0-14-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: Gnome
Windowing System: X11/Wayland

**Comment by Welved** [comment]
I believe I have the entry set correctly, every other browser has no issues detecting the entry for the specific login page. Native message json file? If you are talking about the browser integration, I have all browsers enabled. The firefox variant that I have installed on my Ubuntu 22.04 is snap.

**Comment by varjolintu** [comment]
Have you read the Troubleshootin Guide?
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

**Comment by varjolintu** [comment]
Let's reopen this if there's something new.
