### ISSUE TITLE
browser extension connection problem after updating firefox to version 122.0

### ISSUE THREAD

**Issue by gica3618** [keepassxreboot/keepassxc-browser#2091]
## Current Behavior
After updating firefox to version 122.0, the keepassxc browser extension is unable to connect.

## Steps to Reproduce (for bugs)
1. update firefox (snap) to version 122.0
2. attempt to connect the browser extension

As a test, I reverted to firefox version 121.0.1. Then, the extension works fine.
Other things I tried:

- uninstall and re-install the browser extension
- re-run the script to setup the browser extension (keepassxc-snap-helper.sh)

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Ubuntu 22.04.3
Browser: Firefox Snap for Ubuntu, version 122.0

Some output from `sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass` is here: [strace_output.txt](https://github.com/keepassxreboot/keepassxc-browser/files/14032233/strace_output.txt)
Picture of the weblog console:
![Screenshot from 2024-01-24 12-20-40](https://github.com/keepassxreboot/keepassxc-browser/assets/28126658/0314cb55-3767-4db6-8ea9-da45638253d0)

**Comment by varjolintu** [comment]
This is a known issue. Sometimes after Firefox update the Native Messaging gets broken. The only solution for now is to restart both KeePassXC and Firefox. Try that first. If the problem is in the Snap package itself, I'd recommend using a normal .deb package instead.

**Comment by gica3618** [comment]
Thank you @varjolintu. Sorry for my ignorance, but if you say "restart", you simply mean quitting both KeePassXC and Firefox and opening again, right? That doesn't help, the extension can still not connect. Or do I need to type specific commands in the terminal to restart?

**Comment by jheld** [comment]
Agreed, I have restarted both several times and rebooted the machine twice. Nothing works.

**Comment by varjolintu** [comment]
A normal restart should work. However, if this is something that Snap itself has broken in their Firefox package, there's nothing we can do about it. I haven't investigated the issue yet.

**Comment by oidarnam** [comment]
I am having the same problem after update yesterday to Firefox 122.0 using https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/

Restarted both applications...no luck. Apparently, Mozilla broke something. All the other browsers I have using keepassxc-browser continue to work.

**Comment by oidarnam** [comment]
> I am having the same problem after update yesterday to Firefox 122.0 using https://ppa.launchpadcontent.net/mozillateam/ppa/ubuntu/
> 
> Restarted both applications...no luck. Apparently, Mozilla broke something. All the other browsers I have using keepassxc-browser continue to work.

I installed the .deb from [varjolintu](https://github.com/varjolintu)'s provided [link](https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions) and everything is working again. Thank you!

So on closer investigation, apparently I did have Firefox snap. The ppa wasn't installing the deb package. Apt says I have the latest Firefox snap. I specifically used the ppa to install the deb because of keepassxc connection issues with snap. I'd been thwarted!

**Comment by antiftw** [comment]
Having the same issue, I have created a bug-report in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1876495

**Comment by varjolintu** [comment]
> Having the same issue, I have created a bug-report in Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1876495

I doubt this bug has anything to do with Mozilla. This is probably because of Ubuntu's Snap and their Native Messaging implementation.

**Comment by varjolintu** [comment]
With Ubuntu, please also check if any AppArmor settings has been changed:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#6-apparmor-with-ubuntu

**Comment by antiftw** [comment]
@varjolintu Seems you were partly right. The bug-report I created has been closed as a duplicate, while referring to another bug-report that does have something to do with the Native Messaging:

https://bugzilla.mozilla.org/show_bug.cgi?id=1876447

They are working on resolving it:

> Thanks for the bug report. The messaging portal patch is indeed part of the snap and not upstream at this point. The patch was refreshed to apply cleaning to 122 and rebased at the same time on the current phabricator version which made it use a new dbus method. We didn't notice that this method hadn't been backported to the Ubuntu 22.04 portal package. We are working now on reverting the patch to not depends on the new method.

**Comment by droidmonkey** [comment]
So glad snaps are robust and healthy ecosystem not filled with app specific workarounds and silly fake sandboxing.

**Comment by paulrouget** [comment]
FYI, the bug has been identified, and Canonical is on it.

https://bugs.launchpad.net/ubuntu/+source/firefox/+bug/2051188

https://bugzilla.mozilla.org/show_bug.cgi?id=1876447

**Comment by gica3618** [comment]
Just updated Firefox Snap to the newest version, and it works again!

**Comment by hlongmore** [comment]
For anyone who arrives here from a search engine, and is running Ubuntu and Chrome, I found this info from the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#2-check-the-native-messaging-script-file-path-and-extension-ids) really useful:

> After finding the org.keepassxc.keepassxc_browser.json check the path variable inside it. It should point to the exact location to the KeePassXC binary.

On my system, after downloading and launching from the latest KeePassXC AppImage, I needed to update the new AppImage file:
```shell
~/.config/google-chrome/NativeMessagingHosts$ diff org.keepassxc.keepassxc_browser.json org.keepassxc.keepassxc_browser.json.bak 
8c8
<     "path": "/home/hlongmore/keepassxc/KeePassXC-2.7.9-x86_64.AppImage",
---
>     "path": "/home/hlongmore/keepassxc/KeePassXC-2.6.6-x86_64.AppImage",
```

and then restart Chrome.
