### ISSUE TITLE
No logins found for https://e-banking.winbank.gr/ when said url is inside frame

### ISSUE THREAD

**Issue by qwazix** [keepassxreboot/keepassxc-browser#2092]
This page `https://www.winbank.gr/sites/corporate/el/Pages/default.aspx` contains an iframe with this url `https://e-banking.winbank.gr/_Login/EBloginCorp.html?sitecode=GR&lang=el-GR&v=2`. If you load the frame directly the recommendations from the database work correctly. In the original page, since a recent update they are not.

This is important, because this stupid bank shows 2FA popups inside other vendor's pages that ask you for your ebanking username and password, trusting keepassxc-browser to check the iframe src is the only way to make sure the site is legit save for digging into the devtools.

## Expected Behavior

The autofill dropdown with suggestions from the database appears.

## Current Behavior

A banner is shown that no logins are found for this page. The database contains urls for both the parent page and the frame. I also checked the allow list and it contains "e-banking.winbank.gr". It does not contain the parent page nor does it ask me to give permission for that.

## Steps to Reproduce (for bugs)

1. Add an entry to your database with url `winbank.gr`
2. Visit https://www.winbank.gr/sites/corporate/el/Pages/default.aspx
3. Click the green icon.
4. Observe `No logins found. https://e-banking.winbank.gr` message

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Arch Linux
Browser: Firefox and Chromium

**Comment by varjolintu** [comment]
Already fixed with: https://github.com/keepassxreboot/keepassxc-browser/pull/2079
