### ISSUE TITLE
Firefox: KeePassXC-Browser could not be verified for use in Firefox and has been disabled.

### ISSUE THREAD

**Issue by yagarea** [keepassxreboot/keepassxc-browser#2094]
My keepassxc plugin was disabled and browser is showing this message:

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/14349169/f40ba4b0-2b2d-4fd7-800a-d39192cb9a66)

- KeePassXC - 2.7.6
- KeePassXC-Browser - 1.8.11
- Operating system: Linux
- Browser: Firefox

**Comment by droidmonkey** [comment]
Are you using a managed browser experience (from your work)? What does "More Information" lead to? Looks like there is a setting that you or someone enabled that requires extensions to be "verified".

**Comment by yagarea** [comment]
More info button lead to [support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct](https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u&utm_source=inproduct).

This is on my personal computer with firefox from arch repository. I am not aware about any configuration change. Maybe it did firefox itself during update.

> requires extensions to be "verified".

I use this plugin to store very sensitive data like passwords. I am really scared to trust plugin marked as unverified with my sensitive data... Is there a way to check authenticity of this plugin by myself (some checksum or GPG signature) ?

**Comment by droidmonkey** [comment]
Looks like you installed the extension yourself and not through the add-on store. Get the extension here to resolve your issue: https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

**Comment by yagarea** [comment]
> Looks like you installed the extension yourself and not through the add-on store. Get the extension here to resolve your issue: https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/

Installing add-on from mozilla store resolved this issue. Thank you for support.
