### ISSUE TITLE
KeePassXC Browser Extension Does Not Function Correctly on Walmart Login Webpage

### ISSUE THREAD

**Issue by TESTER-sec** [keepassxreboot/keepassxc-browser#2095]
The KeePassXC browser extension does not show the KeePassXC username and password elements in the fields on:

https://www.walmart.com/account/login?vid=oaoh&ref=domain

Also KeePassXC does not function correctly on that webpage; the KeePassXC content script is not functioning as expected. 

This is not a Microsoft Edge issue; it is a KeePassXC browser extension issue.

## Expected Behavior

The KeePassXC element should appear in the username field on the above webpage URL so that the user can select it and fill the username.

## Steps to Reproduce (for bugs)

1. Navigate to https://www.walmart.com/account/login?vid=oaoh&ref=domain.
2. KeePassXC does not detect the URL\webpage and fill the username field with the KeePass element.

## Debug info

KeePassXC-Browser
MBVersion: 1 . 8 . 11
Version1.8.11
Operating system: Windows 11 23H2
Browser: Microsoft Edge

**Comment by droidmonkey** [comment]
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/2809491/0f8b9bb3-63a4-4911-ac03-2e0d63ce0987)
