### ISSUE TITLE
KeePassXC Browser Extension Not Detecting F-Secure Account Login Page

### ISSUE THREAD

**Issue by TESTER-sec** [keepassxreboot/keepassxc-browser#2096]
The KeePassXC browser extension is not detecting the F-Secure account login page.

This is not a Microsoft Edge issue; it is a KeePassXC browser extension issue.

## Expected Behavior

The KeePassXC browser extension should detect the F-Secure account login page so that the user can use KeePass to log into their F-Secure account. KeePassXC content script should show the KeePassXC element in both the username & password fields. The right-click --> Fill username & password should work. Also KeePassXC should detect the URL and a pop-up should appear so that the user can allow the field fill if they have not already permanently allowed it.

## Steps to Reproduce (for bugs)

1. Navigate to https://my.f-secure.com/login .
2. KeePassXC cannot detect a login, even though one exists in KeePassXC.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Windows 11 23H2
Browser: Microsoft Edge

**Comment by droidmonkey** [comment]
Your url needs to be set to:
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/2809491/ba97004b-8f30-489f-8752-7a51f910d5e6)

**Comment by droidmonkey** [comment]
Also, this website will suffer from this problem: https://github.com/keepassxreboot/keepassxc-browser/issues/2076

We are releasing a new extension version soon to fix it
