### ISSUE TITLE
KeePassXC Browser Extension Does Not Function Correctly for Walmart Login Page

### ISSUE THREAD

**Issue by TESTER-sec** [keepassxreboot/keepassxc-browser#2097]
The KeePassXC browser extension is not detecting the Walmart account login page.

This is not a Microsoft Edge issue; it is a KeePassXC browser extension issue.

Expected Behavior
The KeePassXC browser extension should detect the Walmart account login page so that the user can use KeePass to log into their Walmart account. KeePassXC content script should show the KeePassXC element in both the username & password fields. The right-click --> Fill username & password should work. Also KeePassXC should detect the URL and a pop-up should appear so that the user can allow the field fill if they have not already permanently allowed it.

Current Behavior
Steps to Reproduce (for bugs)
1. Navigate to https://www.walmart.com/account/login?tid=0&returnUrl=%2F .
2. KeePassXC does not fill the username field with the KeePassXC element even though a login exists in KeePassXC.

Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Windows 11 23H2
Browser: Microsoft Edge

**Comment by varjolintu** [comment]
@TESTER-sec I already answered for you in the third or fourth duplicate issue you created. There was an original issue https://github.com/keepassxreboot/keepassxc-browser/issues/2076 which was closed by https://github.com/keepassxreboot/keepassxc-browser/pull/2079. We'll just close any duplicates you create.

**Comment by varjolintu** [comment]
> @TESTER-sec I already answered for you in the third or fourth duplicate issue you created. There was an original issue #2076 which was closed by #2079. We'll just close any duplicates you create.

> If KeePassXC does not work on websites, then whom am I supposed to report it to? The website owners point their fingers at KeePassXC. So you want to leave us users holding the bag?

If you look closely, there's a pinned issue "Non-working sites" (https://github.com/keepassxreboot/keepassxc-browser/issues/1358) at the top. That's where you normally report single sites that are not working.

**Comment by varjolintu** [comment]
> I am not a developer and I rarely spend any time in GitHub. I am not going to sit here in front of the monitor and spend an hour carefully studying the GitHub pages. That's not going to happen. Any expectation that users need to do this is unrealistic.

I am a developer and I have to spend time constantly in GitHub, reading through various issues, and i'm doing in in the front of my monitor. If a user comes here and wishes to have some support, it's only common sense and good manners to go through the pinned issues and look if the same issue has been already reported. This makes our work easier here. It's unrealistic that we could fill every expectations from all users who come here. And when whe fail to do that, it's also common sense not to engage any negative behavior towards us.

Have a nice weekend.
