### ISSUE TITLE
Key exchange not successful if browser running before KeePassXC started

### ISSUE THREAD

**Issue by corey851** [keepassxreboot/keepassxc-browser#2101]
## Overview
If KeePassXC is running before I start the browser, the browser extension connects to the program just fine. 
If the browser is running first, then starting KeePassXC and even clicking the "Reload" button does not connect properly.
"Key exchange was not successful"

## Steps to Reproduce
1. I'm testing on Debian Linux so grab the KeePassXC 2.8.0-snapshot AppImage (latest, revision 442d65e), and install the KeePassXC-browser extension (1.8.11) in Firefox 115.6.0esr.  (actually browser doesn't matter, same result in Chromium.)
Go ahead and create a database and get the browser extension all synced up so everything's  working.  
2. Quit both the browser and KeePassXC.
3. Start the browser.
4. Start KeePassXC.
5. Click the KeePassXC browser icon and then click the Reload button 

## Expected Behavior
Key exchange and connection should be established. 

## Actual Behavior
error: Key exchange was not successful

## Context
Disabling and re-enabling the browser extension will quickly and properly connect.  So I know it can connect, and all the credentials must be okay, it's just the Reload button isn't doing what it should. 

----------------
**KeePassXC** -  Version 2.8.0-snapshot
Build Type: Snapshot
Revision: 442d65a
Distribution: AppImage

Qt 5.15.2
Debugging mode is disabled.

Operating system: Debian GNU/Linux 12 (bookworm)
CPU architecture: x86_64
Kernel: linux 6.1.0-17-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 2.19.1

------------------------
**KeePassXC-browser** - 1.8.11

-------------------------
Operating System: Linux (Debian 12) 
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
Just tested the latest 2.8.0 AppImage with Debian Bookworm and the extension connected to KeePassXC normally. Please check the guide as suggested above.

**Comment by corey851** [comment]
Ok, so I have figured out what is causing my problem.  

Some time ago I installed the AppImageLauncher program (https://github.com/TheAssassin/AppImageLauncher) and have been using it to integrate my appimage programs so they can be launched like installed programs.  With KeePassXC integrated in that way I get the error as described above.  On the other hand if I run KeePassXC as an installed package or even as an appimage (but not started through AppImageLauncher) then it works correctly.

I'm not interested in trying to debug this any further, and I'm not sure if the issue is with AppImageLauncher or in how KeePassXC talks to the browser extension, but if anyone else has the time or interest, that's where you can start.

**Comment by droidmonkey** [comment]
The launcher likely interferes with our appimage run script that chooses the proxy executable when invoked by the browser.
