### ISSUE TITLE
Fill Password Only keyboard shortcut fills in plaintext fields

### ISSUE THREAD

**Issue by ThinkChaos** [keepassxreboot/keepassxc-browser#2102]
Sometimes I accidentally press the shortcut for filling in the password instead of TOTP, and the password ends up in clear in the field. I guess the shortcuts could be adjusted, but the defaults are quite prone to this mistake, at least with a QWERTY layout.

## Expected Behavior

It would be nice if KeepassXC-Browser didn't autofill the password in a plaintext field.

## Current Behavior

It does.

## Possible Solution

Don't autofill the password in plaintext inputs unless it's been setup as a custom field.  
Or maybe ask for confirmation, such as requiring the user to press the shortcut a second time (seems like more work though).

## Debug info
None of these really matter here, it's easily reproducible with any existing version of the extension.

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Linux x86_64
Browser: Mozilla Firefox 120.0

---

P.S. thanks for all the work, I use this extension daily and it's generally great!

**Comment by varjolintu** [comment]
This is a valid request. I agree with that restriction.

**Comment by TomasEkeli** [comment]
this breaks my flow when using swagger-ui on development servers - can we get either a whitelisting possibility, or by marking a field as a custom login field it could be allowed to get passwords?

cc @varjolintu

**Comment by varjolintu** [comment]
@TomasEkeli Custom Field selection should already allow filling to these fields.

**Comment by TomasEkeli** [comment]
it does not, so that's probably a bug then. I'll file one
