### ISSUE TITLE
Browser autofill for icloud.com login not working

### ISSUE THREAD

**Issue by Nezbitt** [keepassxreboot/keepassxc-browser#2103]
## Expected Behavior

Autofill username when clicking on green keepassxc icon.

## Current Behavior

Although I have https://idmsa.apple.com as the url field for my entry whenever I click on the green keepassxc icon next to the username field I receive an error stating: 
Error: No logins found. https://idmsa.apple.com

## Steps to Reproduce (for bugs)

1. Login to database.
2. Open the database in the keepassxc-browser extension.
3. Go to https://icloud.com.
4. Click on the green keepassxc icon in the username field.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.11
Operating system: Win
Browser: Chrome

**Comment by droidmonkey** [comment]
Fixed by #2079. Please wait for browser stores to finally update with the latest release.
