### ISSUE TITLE
Input only the password when no username exists

### ISSUE THREAD

**Issue by ghost** [keepassxreboot/keepassxc-browser#2105]
## Expected Behavior
If no username exists for a given entry, the username field on the website should not be touched.

## Current Behavior
Currently, the username field is emptied of its content.

## Explanation
For those not keeping usernames in KeePassXC (for instances, not to put all one's eggs in the same basket), it is very troublesome that a previously-entered username is deleted when KeePassXC-Browser inputs the password; when no username exists, that field should stay as it is -- or, at the very least, an option should be given to users whether or not they want to overwrite the username field with a blank username.

## Debug info
KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.12
Operating system: MacIntel
Browser: Mozilla Firefox 123.0

**Comment by droidmonkey** [comment]
Usernames are usually damn near public info. Your email address, your forum name, etc. Quite trivial to guess if I went through the trouble of actually hacking your keepass database. Just saying you aren't actually preventing anything, just making your life harder for no gain.

**Comment by varjolintu** [comment]
@xiaolilo Your username is free to parse with any site, script and extension after you enter it. Your method really doesn't improve the security.

**Comment by varjolintu** [comment]
It would make more sense to split username/password and 2FA's to a separate databases. The extension already supports that kind of scenario.

**Comment by varjolintu** [comment]
You can already achieve the password fill using the keyboard shortcut or context menu. It will only fill the password, and you are able to select the credential from to fill.

**Comment by droidmonkey** [comment]
I guess this would be a simple change, of username is empty don't clear the field
