### ISSUE TITLE
"Update" (credientials; from popup bar.) does not work in Firefox.

### ISSUE THREAD

**Issue by D33M0N** [keepassxreboot/keepassxc-browser#2108]
## Expected Behavior

Credientials get updated in the KeePassXC database.

## Current Behavior

KeePassXC-Browser when clicking on "Update" button on popup bar, loses the entire connection to KeePassXC, so I have to "Reload" from the plugin icon to do anything else.

Otherwise works perfectly. I mean fetching credientials from my running KeePassXC. Even adding new credentials into the base. Just the "update" part seems to be broken.

## Possible Solution

No idea. I just copy the password to clipboard and edit the already existing entry in KeePassXC manually (paste into the password field)

## Steps to Reproduce (for bugs)

1. change the password on webpage. (popup which offers to save or update the credientials in DB pops up)
2. Click "Update" -> seemingly nothing happens. but in the background the KeePassXC-Browser loses the connection to KeePassXC. 
3. Reload doesn't help. It still fails and disconnects itself.
4.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.12
Operating system: Linux - Manjaro; KDE Plasma Wayland session.
Browser: Firefox 122.0 (also running in Wayland mode)

**Comment by varjolintu** [comment]
Tihs is already fixed in KeePassXC 2.7.7 which is released soon.

**Comment by D33M0N** [comment]
> Tihs is already fixed in KeePassXC 2.7.7 which is released soon.

So you are saying this is not the plugin error, but KeePassXC error instead? ok.
