### ISSUE TITLE
Browser extension sporadically loses connection to an existing database [Firefox, multiple operating systems]

### ISSUE THREAD

**Issue by MarkWieczorek** [keepassxreboot/keepassxc-browser#2110]
## Expected Behavior

After associating the browser extension with a KeepassXC database, the browser should remain connected to the database.

## Current Behavior

Summary. The browser extension works most of the time. However, sporadically, the browser extension will lose the connection to an existing database. This forces the user to reassociate the browser extension with the keepassXC database.

The problem exists on multiple operating systems (macOS, Fedora, Asahi Linux) using Firefox.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

1. This image shows that the Keepass browser extension was (at one point) connected to a Keepass database
![Screenshot from 2024-02-04 19-49-26](https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/be69124f-1312-4af3-aa97-f5c8167cf338)
2. Next, I click on the browser extension icon, but it returns the message that "The KeepassXC-browser has not been configured", which is false.

![Screenshot from 2024-02-04 19-49-51](https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/62988c31-affd-4f28-8124-01423027055c)
3. Clicking on connect opens the "New Key association request" dialog box.
![Screenshot from 2024-02-04 19-50-17](https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/2a940ce5-945a-42d4-af87-39d3e2b74224)
4. After typing in a name for the database, you can check the database is properly connected
![Screenshot from 2024-02-04 19-50-35](https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/50a65fde-80c8-4cee-b60e-054a6d1788bd)
5. At this point KeepassXC-brower extension will work.... until it doesn't, at which point you go back to step 1. I can find no pattern as to when the browser extension loses the connection to the database. Usually, it will work for several hours.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.12
Operating system: Linux x86_64
Browser: Mozilla Firefox 122.0

Note that the same problem exists on macOS with the most recent version of keepassXC and the browser extension

**Comment by varjolintu** [comment]
Couple of questions:
- Is this related to Access Confirm dialog? If it's shown and you are not immediately accepting it? (A known bug)
- Are you using multiple databases? Those might have identical root group UUID if one is a clone of another. You can generate a new one in the Database Settings.
- What does happen to `keepassxc-proxy` process when this situation occurs? Does it exists?
- Does your database have a identical Key and Identifier when the situation occurs? (Database Settings -> Browser Integration)

**Comment by MarkWieczorek** [comment]
>     * Is this related to Access Confirm dialog? If it's shown and you are not immediately accepting it? (A known bug)

I don't know, all the steps are shown above. I've read all the documentation of KeepassXC but I have zero knowledge of how the code actually works.

>     * Are you using multiple databases? Those might have identical root group UUID if one is a clone of another. You can generate a new one in the Database Settings.

The problem exists when using a single database. On one machine that uses two databases, the same problem exists.

>     * What does happen to `keepassxc-proxy` process when this situation occurs? Does it exists?
I couldn't find any documentation on this. It is not a command-line utility on my machine.

>     * Does your database have a identical Key and Identifier when the situation occurs? (Database Settings -> Browser Integration)
I can only find the key identifier in the browser extension. Where do I find it in the "other place"?

**Comment by droidmonkey** [comment]
Please share a screenshot of your database settings for browser. You may have to use `View -> Allow Screencapture` first. Then go to `Database -> Database Settings -> Browser tab` and take a screenshot.

**Comment by MarkWieczorek** [comment]
Here they are. This is on macOS, but I have the identical settings on Fedora and Asahi. I have not touched the advanced settings.

<img width="743" alt="Screenshot 2024-02-05 at 13 06 22" src="https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/6a7d6d81-1d64-4497-9d64-d9390aad456b">
<img width="650" alt="Screenshot 2024-02-05 at 13 06 41" src="https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/ec9852f3-6f12-41d5-a139-896327589254">

**Comment by droidmonkey** [comment]
The database settings please, not application settings.

**Comment by MarkWieczorek** [comment]
Where do I find the database settings? The first image in the original post is a screenshot of the "connected databases" in the browser. If you are looking for something else, could you let me know where to find it?

**Comment by MarkWieczorek** [comment]
Sorry about the confusion. I thought you were asking for the settings in the browser. Here are the database settings in the application.
<img width="730" alt="Screenshot 2024-02-05 at 14 23 44" src="https://github.com/keepassxreboot/keepassxc-browser/assets/8697285/303cb9a5-5144-490c-9339-5009f096963a">
I note that I usually just use the same name when creating a new association, which overwrites the old one.

**Comment by droidmonkey** [comment]
Ok, so it looks like you use a unique name per computer, per browser, maybe. That would be a primary cause of this problem if you used the same name for a connection on two different computer/browser combos.

**Comment by MarkWieczorek** [comment]
Looking at the above screenshot, I think I might understand what the problem is. You are using key-value pairs and thus the key (probably) needs to be unique. Not only does it need to be unique within each browser, but it probably needs to be unique for all other browsers that are connecting to the KeepassXC database from different computers. 

I see in the dialog that you are asked to "give a unique name or ID" when creating the key-value entry. However, the average (even advanced) user could easily misunderstand what is being asked here. I just assumed that the name was unique only within the context of a single browser, and that you might have multiple names within that browser because you might be connecting to multiple databases.

If this is correct, what I would do is the following: Change the wording of the dialog to make this all a little more clear. For example

"Give the connection a unique name, such as chrome-laptop-database-name. Please note that this name must be unique in order to distinguish this browser from all other browsers that are connecting to the same KeebassXC database."

**Comment by droidmonkey** [comment]
Correct

**Comment by varjolintu** [comment]
@MarkWieczorek We'll modify the text. Of course you are ready to open a PR if you wish.

> I also wonder (though I might be naive) if it would be better to switch the key and value. Its seems to me that the "value" is the unique object, and that the "key" is just a simple text field that is not even necessary.

In the extension side it's just an Object with separate `id` and `key` values, so the order here doesn't really matter. The Object's "key" itself is based on the database hash.

**Comment by droidmonkey** [comment]
We should warn users if we are going to overwrite an existing key, at a minimum.

**Comment by varjolintu** [comment]
@droidmonkey I think we are already displaying that kind of warning?

**Comment by droidmonkey** [comment]
Not sure, I didn't test it recently
