### ISSUE TITLE
The browser integration with tor browser is broken in recently updates.

### ISSUE THREAD

**Issue by sakurawald** [keepassxreboot/keepassxc-browser#2113]
## Overview
[NOTE]: Before recently updates, I setup the browser integration with tor browser following the guide `https://www.reddit.com/r/KeePass/comments/uzum35/tor_keepassxc_integration_linux_solution/`. And everything works great.
In recently updates, the integration is broken.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Update the `tor-browser` and `keepass-xc` to the latest version

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The integration with tor browser should work.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
After the update, the integration is broken.
I get error message in tor-browser `keepassxc` browser extension
```
KeePassXC-Browser has encountered an error:

Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 
```

```
KeePassXC-Browser has encountered an error:

Key exchange was not successful. 
```

## Context
The configuration of `keepassxc` and `tor-browser` is the same as it's updated.

Before the update, i create the `native message json` in `/home/sakurawald/Programs/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json` and the content is 
```
{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```

This configuration makes the `tor browser` contacts `keepassxc`

[NOTE]: # ( Paste debug info from Help → About here )
```
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.12
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 6.7.4-arch1-1

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.2.0
```

And here is the browser extension debug info
```
Extension

KeePassXC-Browser Version: 1.8.12
KeePassXC Version: unknown

Visit KeePassXC-Browser in the Chrome Web Store.
Visit KeePassXC-Browser in the Mozilla Add-ons directory.
Visit KeePassXC-Browser in the Edge Add-ons page.
Visit KeePassXC-Browser on GitHub.

Contributors:
[Sami Vänttinen](https://github.com/varjolintu)
[Andy Brandt](https://github.com/smorks)
[Perry Nguyen](https://github.com/pfn)
[Lukas Schulze](http://lukas-schulze.de/)
[Stefan Sundin](https://github.com/stefansundin)
[dynobo](https://github.com/dynobo)
```

[NOTE]: 
Operating System: Linux
Desktop Env: KDE
Windowing System: X11

**Comment by varjolintu** [comment]
Use the `strace` to find out what is the real path your Tor Browser tries to access when looking for the JSON script.

**Comment by vferrenq** [comment]
I have the same problem in Ubuntu 22.04. It was working perfectly before the last updates:
- KeePassXC-Browser - 1.8.12
- Browser: Mozilla Firefox 122.0
- KeePassXC - Version 2.7.6 Revision : dd21def
- Qt 5.15.3
- **Everything installed as apt packages, not snaps**

**Comment by bvdloo** [comment]
I have the same problem on Ubuntu 23.10 with Chrome and firefox. 
Same versions for browser-extension and keepassxc.

**Comment by droidmonkey** [comment]
> I have the same problem in Ubuntu 22.04. It was working perfectly before the last updates:

Ok, what was updated on your system in the last updates then?

**Comment by sakurawald** [comment]
Finally, I found the workaround: There may be some problems during the `startup` of the `firefox`

To make the `firefox` starts `keepassxc-proxy` at startup time. You should use the right way to launch `firefox` browser.
e.g.
Don't exec the `firefox` directly like:
`/home/sakurawald/Programs/tor-browser/Browser/firefox`

Instead, you should exec the script file
`/home/sakurawald/Programs/tor-browser/Browser/start-tor-browser`



By the way: if you use `strace -o ./log /path/to/firefox`, you will see that the `firefox` program will call `firefox.real` and the latter program will start the `keepassxc-proxy`
