### ISSUE TITLE
Alt + Shift + I password autofill keyboard shortcut collides with Chrome's "Send feedback" functionnality

### ISSUE THREAD

**Issue by T4ngml** [keepassxreboot/keepassxc-browser#2115]
I often take advantage of Alt + Shift + U / I / O KeepassXC Browser shortcuts. Mostly on Firefox and Brave up to recently.
Since Firefox is getting crap late, I replaced it with Chrome, much faster and stable. 

That's when I relalizer that I can't use the Alt + Shift + I's KeepassXC Browser  shortcut (to fill only the password) with Chrome since it's already taken by the later's native "Send FeedBack" functionnality.
Of course, I could remap this, but let's be realistic: out of the box, that's not very plug and play. 

Do you plan to change that?

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.12
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
Yes, we can change that. Although it's a bit problematic because the default shortcuts can vary between different browsers, and sometimes it's already in use internally. Either we find a one that is not used, or just leave this one undefined.
