### ISSUE TITLE
Not showing multiple logins for one site

### ISSUE THREAD

**Issue by ChiefBodo7** [keepassxreboot/keepassxc-browser#2117]
## Expected Behavior

Show multiple site logins

## Current Behavior

Only showing 1 of my site logins (same url for both)
I removed the site detections and when I redetect for logins it still only shows the one account

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
You need to provide more info, like the URL's in your entries, the site you are using etc..

**Comment by ChiefBodo7** [comment]
I  cannae share that information unfortunately. Close case. No help. I'll get another password filler.

**Comment by varjolintu** [comment]
You could've shared that info via Matrix privately. But it's your choice.

**Comment by ChiefBodo7** [comment]
Maybe it should mention that so people know lel

**Comment by varjolintu** [comment]
If there's some data that the issue maker does not wish to share publicly, it's ok to ask in the issue description if there is a safe way to provide that information.
