### ISSUE TITLE
Passkeys/Webauthn support broken on Mac or if another authenticator device is present (?)

### ISSUE THREAD

**Issue by agnosticlines** [keepassxreboot/keepassxc-browser#2124]
## Expected Behavior

Similar to 1Passwords behaviour if the register button is clicked on webauthn.io it should trigger the popup from KeepassXC

## Current Behavior

On MacOS or any other device that supports passkeys natively the browser hijacks control of the Passkey setup/login, and if you click cancel on it the request fails as it was denied

## Possible Solution

1Password and other extensions seem to be getting the notification/trigger regardless of other installed webauthn/passkey providers

## Steps to Reproduce (for bugs)

1. On MacOS go to https://webauthn.io
2. Enter a username, click register
3. Chrome/Edge Passkey support will hijack the passkey login/setup
4. If you click cancel the request will be denied

## Debug info

KeePassXC - 2.8.0-snapshot
KeePassXC-Browser - 1.8.12
Operating system: Mac
Browser: Chrome/Edge

There's no logs in the console for the extension page/background script, but the extension is loaded and connected, I'm just assuming that the issue is that the browser is beating the extension to it, there also doesn't seem to be a way to turn off the default browser passkey support to validate this :(

**Comment by droidmonkey** [comment]
Compile #10318 and the latest browser extension to see if that behavior persists.

**Comment by agnosticlines** [comment]
> Make sure the Passkeys option is enabled in the browser settings. Also enable Debug Logging and report any messages in the console.

Ah shit.. I totally missed that option, I checked it and it works, really sorry about that!
