### ISSUE TITLE
Adding Passkey for Amazon shows error, but is saved in KeePassXC

### ISSUE THREAD

**Issue by DigitallyRefined** [keepassxreboot/keepassxc-browser#2126]
## Expected Behavior

Passkey is created/saved and is usable on Amazon

## Current Behavior

Amazon Passkey is created and saved in KeePassXC, but an error is shown on the Amazon Passkeys page with `TypeError: e.getTransports is not a function` shown in the console.

Passkey wasn't saved on Amazon and I'm unable to login using the Passkey that was saved in KeePassXC.

## Possible Solution

It seems that the Amazon's implementation of Passkeys might be expecting a `getTransports` function to exist, could be an issue with their code or perhaps an issue with the event callback in KeePassXC Browser.

I've tested their Passkey implementation on Android, Windows and a YubiKey 5C, all were saved and work as a login method, except for KeePassXC.

## Steps to Reproduce (for bugs)

1. Navigate to https://www.amazon.com (or https://www.amazon.co.uk)
2. Login to an existing account and click Account > Your Account > Login & Security > Passkey
3. Press Add and accept the KeePassXC confirmation
4. Passkey is saved in KeePassXC
5. Error is shown on Amazon Passkeys page and is not saved by Amazon

### Screenshots

1. ![Screenshot from 2024-02-24 12-24-17](https://github.com/keepassxreboot/keepassxc-browser/assets/129616584/70c9c4a2-e53d-422d-9a45-b3e8420b526a)
2. ![Screenshot from 2024-02-24 12-26-20](https://github.com/keepassxreboot/keepassxc-browser/assets/129616584/346eb738-60ad-4102-9a50-cdd823914124)
3. ![Screenshot from 2024-02-24 12-24-33](https://github.com/keepassxreboot/keepassxc-browser/assets/129616584/90a427ca-8986-4469-8d10-c8d6e9c5ddde)

## Debug info

KeePassXC - 2.8.0-snapshot
KeePassXC-Browser - 1.8.12
Operating system: Windows 11/Linux x86_64
Browser: Chrome/Chromium 122.0.0.0

**Comment by varjolintu** [comment]
I'm happy to report that the PR I linked earlier already works. Although it seems that Amazon prevents creating or logging in with a Passkey with Firefox.
