### ISSUE TITLE
KeePassXC-Browser and keepassxc will not communicate in Linux Fedora Bazzite, Vivaldi browser

### ISSUE THREAD

**Issue by drjenk** [keepassxreboot/keepassxc-browser#2128]
## Expected Behavior
When trying to connect the browser plugin to keepassxc, I cannot get the two to communicate

## Current Behavior
I cannot seem to get them to communicate, tried initiation from both sides.  Never had a problem in any other distro.
I do indeed have the browser integration enabled in keepassxc and the vivaldi box checked.  

## Possible Solution
I did go through the troubleshooting guide, I do not see the keepassxc-proxy process.  Where can I find this binary to run it manually and see if that solves the problem?
Also org.keepassxc.KeePassXC does not point directly to the binary, but via symbolic link:
org.keepassxc.KeePassXC -> ../../app/org.keepassxc.KeePassXC/current/active/export/bin/org.keepassxc.KeePassXC

Not sure if this is a problem?

## Steps to Reproduce (for bugs)

1. Bring up the plugin interface in browser, hit connect.  No communication
2. Restart both browser and KeepassXC, re-initiate above, no communication
3.
4.

## Debug info

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.12
Operating system: Linux x86_64
Browser: Chrome/Chromium 122.0.0.0

**Comment by varjolintu** [comment]
You are using KeePassXC as AppImage? What about Vivaldi? How it is installed?

**Comment by drjenk** [comment]
Both are flatpak installs.

On Mar 3, 2024 at 12:41 AM, "Sami Vänttinen" ***@***.***> wrote:

You are using KeePassXC as AppImage? What about Vivaldi? How it is installed?

**Comment by varjolintu** [comment]
Then you are out of luck. As far as I know, Flatpak still hasn't a proper support for Native Messaging. There's nothing we can do about it. There are other issue threads if you search them that might provide some help, but there's no easy way around of this. Unless you want to install a non-Flatpak browser.

**Comment by drjenk** [comment]
FYI I was able to solve my issue by installing both vivaldi and keepass in a debian distrobox, installing .deb files.  Thank you for pointing me in the right direction.

On Mar 3, 2024 at 1:01 AM, "Sami Vänttinen" ***@***.***> wrote:

Then you are out of luck. As far as I know, Flatpak still hasn't a proper support for Native Messaging. There's nothing we can do about it. There are other issue threads if you search them that might provide some help, but there's no easy way around of this. Unless you want to install a non-Flatpak browser.
