### ISSUE TITLE
Autofill does not work with flatex.de

### ISSUE THREAD

**Issue by sam1919** [keepassxreboot/keepassxc-browser#2129]
## Expected Behavior
Login fields should be filled.

## Current Behavior
Login and password are not filled.

## Steps to Reproduce (for bugs)

1. Go to https://www.flatex.de/ and click on "Login" at the top right

## Debug info

Fehler beim Verarbeiten des Wertes für 'transition-duration'.  Deklaration ignoriert. 2 [www.flatex.de:1:1](https://www.flatex.de/#)
Object { https: true, httpsAutoUpgrade: true, privacyScore: 2, entitiesBlocked: {…}, entitiesNotBlocked: {}, scores: null }
[background.js:42250:21](moz-extension://3d68383c-431e-44f0-a311-7ccce3abfa02/public/js/background.js)
Einige Cookies verwenden das empfohlene "SameSite"-Attribut inkorrekt. 82
Unbekannte Eigenschaft '-moz-tap-highlight-color'.  Deklaration ignoriert. [css.auto-bundle:1:7558](https://konto.flatex.de/login/css/css.auto-bundle?v=5FED350D3302CC83BB55116C75C6E9F2)
Unbekannte Eigenschaft 'zoom'.  Deklaration ignoriert. [css.auto-bundle:76:10](https://konto.flatex.de/login/css/css.auto-bundle?v=5FED350D3302CC83BB55116C75C6E9F2)
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. [css.auto-bundle:120:13](https://konto.flatex.de/login/css/css.auto-bundle?v=5FED350D3302CC83BB55116C75C6E9F2)
Fehler beim Verarbeiten des Wertes für 'transition-duration'.  Deklaration ignoriert. 2 [www.flatex.de:1:1](https://www.flatex.de/#)
LoginRecipes: Falling back to a synchronous message for: https://konto.flatex.de/. [LoginRecipes.sys.mjs:284:16](resource://gre/modules/LoginRecipes.sys.mjs)
Die Ressource unter "https://widget.moin.ai/fonts/rubik-v9-latin-500.woff2" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. [www.flatex.de](https://www.flatex.de/#)
Die Ressource unter "https://widget.moin.ai/fonts/rubik-v9-latin-regular.woff2" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. [www.flatex.de](https://www.flatex.de/#)

KeePassXC - 2.7.6
KeePassXC-Browser - 1.8.6
Operating system: Linux x86_64 
Browser: 123.0 (64-Bit)

**Comment by varjolintu** [comment]
The site is already reported here: https://github.com/keepassxreboot/keepassxc-browser/issues/1358
