### ISSUE TITLE
Filter block in popup_login hidden after 1.9.0 update.

### ISSUE THREAD

**Issue by Syuks** [keepassxreboot/keepassxc-browser#2136]
## Overview

After the 1.9.0 update, the filter block inside the popup_login dissappeared, and it won't show up when more than one entry is available. This happens because the inline styling it had inside `popup_login.html` was moved to `popup.css`, which broke the show/hide functionality inside `popup_login.js`.

See the git blame in this line:
https://github.com/keepassxreboot/keepassxc-browser/blob/2777b15149b05e8109af4e51395787313f912459/keepassxc-browser/popups/popup_login.html#L42

That line used to be `<div id="filter-block" style="display: none;">`, and inside `popup_login.js` the `filter-block` would show up because of this line:

https://github.com/keepassxreboot/keepassxc-browser/blob/8e4ecdb59e5bdf2bbf5f41df4e5958d443f1970b/keepassxc-browser/popups/popup_login.js#L42

But now, the `display: none` is not an inline style, because it was moved inside `popup.css`:
https://github.com/keepassxreboot/keepassxc-browser/blob/2777b15149b05e8109af4e51395787313f912459/keepassxc-browser/popups/popup.css#L119

## Steps to Reproduce

Open the extension popup in a page that has more than one entry. See how the filter block doesn't appear.

## Expected Behavior

I expected the filter block to show up when more than one entry is available.

## Actual Behavior

The filter block never appears despite being more than one entry available.

## Context

Browser: Microsoft Edge Version 122.0.2365.66 (64 bits)

KeePassXC: Version 2.7.6

Operating System: Windows 10

**Comment by varjolintu** [comment]
I'm releasing 1.9.0.1 soon. Adding fix for this to it.
