### ISSUE TITLE
No login data found for this domain, but it exists

### ISSUE THREAD

**Issue by ygoe** [keepassxreboot/keepassxc-browser#2138]
## Overview
The Firefox extension shows the error message that no login data was found for the current domain, but it exists.

## Steps to Reproduce
1. Create an entry for the domain https://my.onvista.de
2. Open the URL https://my.onvista.de/login
3. Try to let the login form be filled out by clicking the green button in the user name field

## Expected Behavior
Login fields filled out

## Actual Behavior
Error message

![grafik](https://github.com/keepassxreboot/keepassxc/assets/868315/44f1ece6-5d9e-452c-89fb-0aae9b9cb33e)

(I can't show a partial screenshot of KeePassXC with the entry for that URL, it's blacked out when I try.)

## Context
KeePassXC - Version 2.7.6
Revision: dd21def

Qt 5.15.10
Debugging mode is disabled.

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 2.19.3

Browser: Firefox 123.0.1
Add-on: KeePassXC-Browser 1.9.0.1 (2024-03-06)

**Comment by rlinhard** [comment]
I have the same issue on the homepage of Consorsbank during the login popup-window. It's the same error message despite I use the correct URL for the main page. If I press the login-button the login popup window appear. 

Does it have something to do with popup windows as login mask?

**Comment by varjolintu** [comment]
@rlinhard It might be that the CSS transition is not detected properly, or the input fields are visible only after some animation period has passed. Sometimes these go undetected. After the popup appeas, does the redetect button in popup work?

**Comment by rlinhard** [comment]
Following happens after the popup appears:
You have both input fields "Kontonummer / UserID" and "PIN / Password" and the login-button. After loading the popup for first time, no KeePass-Icon (green key, 'Transfer login data from KeePass') at the first field "UserID" is shown.
 
After clicking the redetect button, the KeePass-Icon appears at the field "UserID" but when clicking the KeyPass-Icon to fill the input fields with username and password the error message is shown.

I also tried to map the two input fields of the popup to the corresponding username and password fields in KeePassXC. This doesn't help. The same error message is shown.

The URL of the Consorsbank hompage is: https://www.consorsbank.de

Any further idea? Dou you need screenshots?

**Comment by varjolintu** [comment]
@rlinhard For me it works with that URL in the entry after using the redetect button. Sometimes the icon is not seen, but Autocomplete Menu still works. If I'm using context menu to fill the entry before the fields are detected, then only username fiels is filled, so something here is not detected correctly.

**Comment by rlinhard** [comment]
Today I had the time to test the idea of adding (just) a new KeePassXC-entry for the banking company. The new entry  works fine as it should.

But I haven't an explanation why the old entry with the same information doesn't work. At least a further example for good workarounds...

**Comment by josephcsible** [comment]
> (I can't show a partial screenshot of KeePassXC with the entry for that URL, it's blacked out when I try.)

Per https://keepassxc.org/docs/KeePassXC_UserGuide#_screenshot_security, you need to start KeePassXC with `--allow-screencapture` to be able to take screenshots of it on Windows or macOS.

**Comment by ygoe** [comment]
> Did you deny access to that entry at some point? Go to the properties of the entry and delete browser custom data field.

Thank you, that was the reason. I removed that metadata entry and then I was asked again when opening the page. Now I've set it to allowed and remember. The login data is filled in as expected.
