### ISSUE TITLE
Passkey support forwarding to security key does not work

### ISSUE THREAD

**Issue by luzat** [keepassxreboot/keepassxc-browser#2140]
## Expected Behavior
With "Enable Passkeys" and "Enable Passkeys fallback" enabled, I want to be able to login to GitHub with an already registered external security key (YubiKey).

I do expect a popup from my browser telling me to touch my inserted YubiKey.

## Current Behavior
When searching for the security key, the browser extension displays "Error! No logins found" and the browser does not ask me to touch my key. This happens in Firefox and Chrome.

GitHub is "Waiting for input from browser interaction...".

## Possible Solution
If possible, there should be an option to forward the request to the browser (possibly with confirmation popup and an option ) or KeePassXC should forward the request to a security key (browser native functionality would be preferred, though). As of now, I need to disable Passkeys support in the browser extension to use my security keys.

## Steps to Reproduce (for bugs)
1. Create an account at github.com (or some other site)
2. Register an external security key (e.g. YubiKey) using the browser's functionality.
3. Install KeePassXC and the KeePassXC browser extension in Firefox or Chrome.
4. Enable Passkeys support in the browser extension.
5. Try to log in with the security key.

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 124.0

**Comment by varjolintu** [comment]
The fallback feature should already cover this, but maybe the error message interrupts this. Gonne check and fix it.

**Comment by luzat** [comment]
Slightly related: When registering a key, should requests be forwarded by the current implementation, too? I did not test that yet.

Like, if I cancel registration with KeePassXC, would my browser try to ask me for a key? Could be better UX if the user could select the method to use before forwarding to KeePassXC.

**Comment by varjolintu** [comment]
If a register or authentication is canceled from KeePassXC side, the extension should fall back to the original dialog.

**Comment by varjolintu** [comment]
I'm trying to get this fixed for the hotfix release 1.9.0.2.

**Comment by jasperweiss** [comment]
@varjolintu Does this also fix the fallback for registration? Choosing cancel on the dialog does not bring up the usual Windows Hello prompt on the release build for me. I have to disable passkey support completely in order to use platform/USB security keys.

**Comment by varjolintu** [comment]
@jasperweiss Are you already using 1.9.0.2?

**Comment by jasperweiss** [comment]
@varjolintu ah, it's not on the store yet. I'll wait for it to be released there since installing it through developer mode doesn't allow it to communicate with keepassxc it seems.

**Comment by pmorange** [comment]
Hi,
Updated to version 1.9.0.2 from the store. 
Yubikey integration works well now, many thanks !
