### ISSUE TITLE
Search Feature in the Browser Extension is gone.

### ISSUE THREAD

**Issue by Creative-Ben** [keepassxreboot/keepassxc-browser#2142]
## Expected Behavior

When on a certain website, if you have a lot of logins for that one website, you can search to find the login credentials you want. This is useful if you have a lot of clients and you have an account for each one.

## Current Behavior

The search feature is not showing up anymore, when using the browser extension 

## Possible Solution

Not sure?

## Steps to Reproduce (for bugs)

<img width="513" alt="Screen Shot 2024-03-11 at 1 05 34 PM" src="https://github.com/keepassxreboot/keepassxc-browser/assets/163021530/7f7b9da1-26ca-482c-a6b7-bd81bd0aab87">

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0
Operating system: MacIntel
Browser: Chrome/Chromium 122.0.0.0

**Comment by Creative-Ben** [comment]
I was working with browser extension today and looks like this was fixed with the new update from a couple days ago and I didn't noticed there was an update.

**Comment by varjolintu** [comment]
Yes, 1.9.0.1 fixed it quickly after 1.9.0. It just took a while for the stores to update the version.
