### ISSUE TITLE
Add the password generator directly to the browser integration

### ISSUE THREAD

**Issue by nbro** [keepassxreboot/keepassxc-browser#2145]
## Expected Behavior

Allow us to directly generate passwords from the browser.

Other password managers, like JumpCloud Password Manager, allow us to do this.

## Current Behavior

Right now, when you're signing up, the only way to generate a new password with KeePassXC is to 

1. Right click on the password entry
2. Select `KeePassXC-Browser`
3. Click `Show Password Generator`
4. Go to the `KeePassXC` application (not the browser plugin) where the password generator is opened
5. Once you've generated the password you want, click `Apply password` (which is a bit weird because it will apply to the browser, not an entry in the app)

Of course, this is too cumbersome. We need many clicks and we need to use both the plugin and standalone application, so we need to go back and forth between applications.

> Btw, if this is not documented in the official docs, it should. I found this solution in a GitHub issue. I'm willing to update the docs. Just point me in the right direction.

## Possible Solution

The KeePassXC icon should appear on the right of the password field (so the plugin should be able to detect inputs of type password), then we should just click the icon, and small dialog with a password generator (exactly like the one in the desktop app) should appear in the browser (either at the top where the plugin is shown or close to the password input), where we can choose how our password should be generated and then be able to apply it directly

> Of course, the password generator that we have in the desktop app should still remain there.

## Steps to Reproduce (for bugs)

See above

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.1
Operating system: MacIntel
Browser: Chrome/Chromium 122.0.0.0

**Comment by varjolintu** [comment]
The password generator in the extension was removed for a reason. It's much more easier to setup different settings on-the-fly when using KeePassXC's own password generator and just pass the value to the extension.

**Comment by varjolintu** [comment]
@nbro As I said, the internal password generator was legacy code and it only worked with very old KeePassXC versions. Every newer version has been using the KeePassXC one for years. The internal password generator is not coming back.

**Comment by droidmonkey** [comment]
What makes it awful? 

You right click on the password field, go to KeePassXC then password generator... or bind that to a keyboard shortcut. Generate your password, press apply and it will fill into original and repeat fields, press submit and we will ask to save the entry or update an existing one.

**Comment by varjolintu** [comment]
The best I can do is to add an option (or a new optional context menu item) for filling a password directly without showing the KeePassXC popup at all, even if the user loses the possibiltiy to configure the password generation before the fill.

**Comment by hex-m** [comment]
For me the problem was, that the setting `Activate password generator icons` is not enabled by default. Enabling it leads to this:

<img width="573" height="160" alt="Image" src="https://github.com/user-attachments/assets/27c1e1fb-de89-4e12-8d2b-d3288a1aeb3a" />

I think this is more or less exactly what the original posting mentions as possible solution.
