### ISSUE TITLE
KeePassXC does not correctly fill the credentials for the Udemy website

### ISSUE THREAD

**Issue by nbro** [keepassxreboot/keepassxc-browser#2146]
## Overview

The browser plugin does not suggest anything for the udemy website. See the screenshot below. I don't know if this should be moved to the other repo. Feel free to do it

<img width="1434" alt="Screenshot 2024-03-13 at 17 37 32" src="https://github.com/keepassxreboot/keepassxc/assets/9349000/0d98172e-be6b-4794-8018-b0801e2c94a6">

## Expected Behavior

The browser plugin suggest the credentials correctly

## Actual Behavior

The opposite. Actually, to be more specific, if I click on the browser plugin, it suggest to select the credentials, but it only inserts the password when I click it. Anyway, this behaviour is different from other websites, where the KeePassXC icon is shown on the right side of the input fields

## Context

Note: I'm accessing `https://www.udemy.com/join/login-popup/` and my DB entry contains URLs `https://www.udemy.com/join/login-popup/` and `https://www.udemy.com`

**Comment by alcon678** [comment]
@nbro it doesn't show the green tooltip under the fields, but you can fill them anyway using the keyboard shortcuts in the meanwhile 😁

Fill Username and Password: Alt+Shift+U
Fill Password Only: Alt+Shift+I

**Comment by alcon678** [comment]
@nbro it doesn't show the green tooltip under the fields, but you can fill them anyway using the keyboard shortcuts in the meanwhile 😁

Fill Username and Password: Alt+Shift+U
Fill Password Only: Alt+Shift+I
