### ISSUE TITLE
Passkey-feature blocks Yubikey

### ISSUE THREAD

**Issue by darealdemayo** [keepassxreboot/keepassxc-browser#2148]
I'm not sure if this is a keepassxc-browser issue or a keepassxc issue, sorry.

## Expected Behavior
Yubikey should be used when KeePassXC Passkey Auth is canceled or KeepassXC does not hold any passkey for the origin.

## Current Behavior
Error!Passkeys request canceled. And no fallback to hardware security keys.

Or:

Origin and RP ID does not match. If no Passkey is stored for that origin.

## Steps to Reproduce (for bugs)
Situation1
1. add yubikey and keepassxc as passkeys
2. try to use yubikey by cancelling the auth request from keepass
3. Error!Passkeys request canceled. 

Situation2
1. add yubikey, but no keepassxc passkey
2. try to use yubikey
3. Error!Origin and RP ID do not match

## Debug info
syno-vue-components.min.js?v=1691459833:2 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

There are also a bunch of "issues" for which I don't know how to copy them.

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0
Operating system: Win10 22H2
Browser: Chromium (Edge)

**Comment by droidmonkey** [comment]
This is fixed in the extension version 1.9.0.2 just released
