### ISSUE TITLE
Allow registering new passkeys onto existing entries

### ISSUE THREAD

**Issue by darkdragon-001** [keepassxreboot/keepassxc-browser#2149]
## Expected Behavior
When creating a new passkey, I should be asked if I want to create a new entry or if I would like to save this to an existing one.

## Current Behavior
The extension always creates a new entry.

## Possible Solution
Allow choosing an existing entry (maybe filter based on URL).

## Steps to Reproduce (for bugs)
1. Create an entry for some website
2. Try to add a passkey for that website
3. A new additional entry is added to the KeePassXC database

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.1
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
Already done: https://github.com/keepassxreboot/keepassxc/pull/10408
