### ISSUE TITLE
Auto-Type does not submit forms automatically with auto-filling options enabled

### ISSUE THREAD

**Issue by nestukh** [keepassxreboot/keepassxc-browser#215]
## Expected Behavior
- on Linux, using Firefox ESR 60 (current), last keepassxc-browser and last keepassxc
- 'Automatically retrieve credentials' activated
- 'Automatically fill-in single credentials entry' activated
- Auto-Type is enabled for an entry in the keepass database
---> going to the proper website should auto-fill the login form and auto-submit it (just like with Kee + keepass2, or using lastpass)

## Current Behavior
Everything works ok, up to auto-submit. Credientials are auto-filled, but auto-login does not happen. Enter/Login/Confirm has to be pushed.
Auto-Type works if performed from KeePassXC using ctrl+v on the selected entry. So it is not broken?
Or maybe am I missing something?

## (a side note)
It might seem silly and lazy, but if you ever had to care for elderly people's cumputers, _remotely_, automated functions like 'autologin' solve a lot of problems. Ctrl+V the right entry from a database in another program window, it's not going to happen. Force them to type passwords or PINs, maybe with chars like L l 1 7 i I 0 o O . , ; : - _ in it, pure hell. 
KeeFox + keepass2 combination does have this automatism, but there are other problems, as you know. Lastpass was most likely hit by _some random acts of management_ as quality has declined over time so, with the new Firefox ESR, here we are.

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 1.1.7
Operating system: Debian Stretch
Browser: Firefox ESR 60.0.2 (64-bit), tarball installation
Proxy used: YES

**Comment by droidmonkey** [comment]
Auto-Type and the browser plugin are two completely separate features. The browser plugin DOES NOT submit the form for you. Auto-Type by default presses "ENTER" after it types Username/Password which is why is submits. All of this is by design.
