### ISSUE TITLE
browser autofill uses passkey-username instead of username for entries that have a passkey

### ISSUE THREAD

**Issue by darealdemayo** [keepassxreboot/keepassxc-browser#2150]
## Expected Behavior
After importing a passkey into existing entry, I should be able to use the passkey and the username/password.

## Current Behavior
After importing a passkey into existing entries, keepass-xc browseruse the passkey-username instead of the correct username to fill forms.

## Possible Solution
I don't even know if this is a keepass-xc browser problem or keepassXC problem...

## Steps to Reproduce (for bugs)

1. import a passkey, which has a username that is different from the actual username used to login, into an existing entry
2. try to use keepassxc-browser with that entry

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0
Operating system: Win10 22h2
Browser: Chromium Edge

**Comment by varjolintu** [comment]
Are you trying to combine two different accounts in to one entry? Normally the passkey username is identical.

**Comment by varjolintu** [comment]
This is fixed in: https://github.com/keepassxreboot/keepassxc/pull/10874
