### ISSUE TITLE
auth.openai.com: doesn't automatically detect username-only form

### ISSUE THREAD

**Issue by cnmicha** [keepassxreboot/keepassxc-browser#2151]
## Expected Behavior

1. Open https://chat.openai.com/
2. It redirects to https://auth.openai.com/ and in the first step, it shows a username-only login form:
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/10116544/26f434cf-77e8-4099-a494-ea28f89d9372)
3. The KeePassXC icon is shown in the username-only field

## Current Behavior

The KeePassXC icon is not shown in the username field.

## Possible Solution

* Add auth.openai.com to a list of websites that have username-only fields.
* Workaround: click on the "add username-only option for this site" button in the toolbar popup. Then, it works. However, this step needs to be done manually on each computer I am using to access this website

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.2
Operating system: Linux
Browser: Brave

**Comment by varjolintu** [comment]
The solution you described is the actual solution.
