### ISSUE TITLE
Passkeys are saved to default group even when custom default group is configured

### ISSUE THREAD

**Issue by snwflake** [keepassxreboot/keepassxc-browser#2153]
## Expected Behavior

Passkeys should either be saved to the default group set by the user for password credentials or it might benefit from having an alternative option dialogue to define a separate group for saving them.

## Current Behavior

Saving a Passkey ignores the value set by a user in `Saving Credentials -> Default group to save new passwords` and saves it to `KeePassXC-Browser Passwords` regardless of what group the user specified in aforementioned option.

## Possible Solution

Either apply the custom group name to saving the Passkey to said group, or introduce another text field in order to provide a separate group to save Passkeys in.

### Tangent

I am fully aware that this is probably obsolete, once [keepassxcreboot/keepassxc#10408](https://github.com/keepassxreboot/keepassxc/pull/10408) gets merged, but this is a bug regardless...maybe

## Steps to Reproduce (for bugs)

1. Set new default group for entries in the extension
2. Create new Passkey

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.2
Operating system: Linux x86_64
Browser: Chrome/Chromium 122.0.0.0 (Brave)

**Comment by varjolintu** [comment]
Yes, I'm aware that option is not respected now. I think a separate option field could be used for this. I would assume users would like to use a different group for passkeys if possible.

**Comment by varjolintu** [comment]
This change is required to the KeePassXC side for the feature: https://github.com/keepassxreboot/keepassxc/pull/11260
