### ISSUE TITLE
Checking status endlessly : "browserAction is not defined" at page.js:130

### ISSUE THREAD

**Issue by jjustra** [keepassxreboot/keepassxc-browser#2158]
Hello. Today I noticed extension stopped working, doing Checking status loop endlessly. And inspection repeats:

```
Uncaught (in promise) ReferenceError: browserAction is not defined
    switchTab moz-extension://9a242b73-1b60-46d8-98d5-3b91ce4aae47/background/page.js:130
    <anonymous> moz-extension://9a242b73-1b60-46d8-98d5-3b91ce4aae47/background/init.js:62
```

## Expected Behavior
Doing little bit of "checking status" then connect.

## Current Behavior
Doing a LOT of checking status, forgets the connect bit :(

## Possible Solution / Tried solutions
Reinstall extension won't work. Restart firefox / Restart computer won't eighter.

## Steps to Reproduce (for bugs)
1. Open program
2. Start/Restart firefox
3. Click icon
4. See popup

## Debug info

```
Uncaught (in promise) ReferenceError: browserAction is not defined
    switchTab moz-extension://9a242b73-1b60-46d8-98d5-3b91ce4aae47/background/page.js:130
    <anonymous> moz-extension://9a242b73-1b60-46d8-98d5-3b91ce4aae47/background/init.js:62
```

KeePassXC - 2.6.2
KeePassXC-Browser - 1.9.0.2
Operating system: Linux ... uname -a : Linux PrawnOS 5.10.1-gnu-PrawnOS #1 SMP PREEMPT Tue Dec 15 19:20:04 PST 2020 armv7l GNU/Linux
Browser: Firefox 78.15.0esr (32-bit)

**Comment by varjolintu** [comment]
You Firefox is too old. The minimum supported version is 96. The new build script transition had a bug that allowed older versions of Firefox to be used.

I highly suggest updating your KeePassXC and Firefox to the latest versions.
