### ISSUE TITLE
It ignores everything in Root/Passwords/

### ISSUE THREAD

**Issue by another4til7** [keepassxreboot/keepassxc-browser#2160]
The browser extension connects with the KeepPassXC app. However, it only looks in the /Root folder not /Root/Passwords

## Expected Behavior

Expected that it would look in the /Root/Passwords folder in KeePassXC for items. 

## Current Behavior

It appears to look in /Root so if finds no existing matches.
If saves new items in /Root/

## Possible Solution

Look for and save items in the location that KeePassXC created: /Root/Passwords/

## Steps to Reproduce (for bugs)

1. Open a website login form
2.
3.
4.

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.2
Operating system: Linux
Browser: Firefox

**Comment by another4til7** [comment]
Correction:
It creates them in /Root/KeePassXC-Browser Passwords

**Comment by another4til7** [comment]
Additional Information:
If I set up the connection again *and* have the Root>Passwords folder manually selected in KeePassXC, the browser plugin will work as expected.

Bug report refers to missing steps in the portion of the manual that covers browers plugin configuration

**Comment by droidmonkey** [comment]
No idea what you are referring to, unfortunately. Did you setup any browser settings on your /root/passwords group that would block browser integration?

**Comment by another4til7** [comment]
I created a database. I didn't change any settings on those groups. I merely put account passwords in /Root/Passwords. 

Then I turned on the browser plugin, restarted the browser, and connected the plugin to the desktop app per the instructions. 

I tried to login to a website but it couldn't find a match. 
I manually entered the login info. 
It offered to save my login. 
it created a new group "/root/KeePassXC-Browser Passwords" and saved the login in there

On a lark,
1) I moved the "KeePassXC-Browser Passwords" group to "/root/Recycle Bin/" (see screenshot)
2) I selected "/Root/Passwords" (e.g. clicked on it on the left)
3) I deleted the connection and created it again

Now when I attempt to login, it searches /Root/Passwords

IMHO, the setup instructions in the manual should mention the click on "/Root/Passwords" step

[Screenshot from 2024-03-27 21-25-47](https://github.com/keepassxreboot/keepassxc-browser/assets/60616549/9836da84-f136-4040-bee1-5dfcc0710107)

**Comment by droidmonkey** [comment]
Clicking on a group has nothing to do with searching for passwords from the browser integration. You most likely didn't setup your urls correctly in your entries when you first made them.

**Comment by another4til7** [comment]
Creative theories that plame the user? lol. The URLs were copied from the browser location bar and were not changed by me. Perhaps they fixed themselves.

**Comment by droidmonkey** [comment]
Well yah, what information is in your database is up to you. Not all websites use the address bar location for their login forms. It's a common problem. We show you the url that is being looked for in our error message when entries aren't found. Use that url and you'll be all set.

**Comment by another4til7** [comment]
You're not making any sense.

I was not using the app to go *to* the website. I used my browser to go to a website and used the buttons that the plugin added to the webpage.

The give away that it has nothing to do with URLs is that the plugin started creating entries in the wrong group.

If the expected behavior is that the database will *by default* end up with a bunch of different silos of data, from a UX/usability viewpoint, that's seriously busted data architecture.

**Comment by varjolintu** [comment]
Have you changed this setting in the extension?
<img width="894" alt="Screenshot 2024-03-28 at 16 58 34" src="https://github.com/keepassxreboot/keepassxc-browser/assets/24570482/15b14c18-259d-4a87-bfd1-0ba820e3c6bb">

**Comment by another4til7** [comment]
I'm not even sure where to find that setting

At this point, I'm going to back out of this discussion. *I have gotten my setup to work* All that's left is the suggestion that the browser usage and config instructions have several issues including (IMHO) this one (at least on Firefox). Beyond that... I'm not interested in being called a PEBCAK by droidmonkey. 

Be well

**Comment by varjolintu** [comment]
@another4til7 It's in the main page when you open the extension settings.
