### ISSUE TITLE
Browser extension does not work in Opera on Linux (Fedora)

### ISSUE THREAD

**Issue by QL568A6** [keepassxreboot/keepassxc-browser#2165]
## Expected Behaviour
Browser extension behaves like it does for every other browser on Windows and Linux.

## Current Behaviour
When the extension icon is clicked, the box says "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." This message is sometimes replaced with "checking status" and a spinning wheel, but goes back to the message immediately when that is finished.

Right-clicking a fillable field and selecting "KeePassXC-Browser > Fill username and password" does nothing.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/25498543/522c539a-015b-491f-8e97-bcf5779ef1f7)

## Possible Solution
Determine how to integrate properly with Opera for Linux and formally add it to the Browser Integration settings in the KeePassXC client.

## Steps to Reproduce (for bugs)
1. Open Opera browser
2. Click extension icon or "Fill" icon in username/password box

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Fedora 39 (KDE)
Browser: Opera

**Comment by QL568A6** [comment]
I've just discovered that it has the same problem in Vivaldi.

**Comment by varjolintu** [comment]
At first check how your browsers are installed. If those are Flatpak browsers, I have some bad news for you.

**Comment by QL568A6** [comment]
I tried the Snap version and it doesn't work there either.

**Comment by droidmonkey** [comment]
Snap'd browsers don't support native messaging with exception to the official Firefox. Flatpak'd browsers don't support native messaging at all.
