### ISSUE TITLE
 Option to add new url to existing entry.

### ISSUE THREAD

**Issue by Omnibrain007** [keepassxreboot/keepassxc-browser#2167]
## Background
I have some company domains which have many subdomains. 
Some of this subdomains using the same main-credentials (username/password), but not all subdomains, some have special credentials.
So I need to add in cases the new subdomain to existing entry under browser integration as additional url. 

## Expected Behavior
Performing a Global Auto-Type for a new subdomain with using the credentials (username/password) of an existing entry. 
In this case the extension should provide an additional option, not only to create a new entry or to update, but to add only the new url to this used existing entry.

## Current Behavior
When performing Global Auto-Type on a website then I just can afterwards create a new entry with the same credentials.
So instead I have to open KeepassXC search for the entry and add manually the new additional url.

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Win 10
Browser: Firefox

**Comment by droidmonkey** [comment]
Global Auto-Type is a different feature from browser integration,  but I get what you are asking for.

**Comment by GuillaumeLagrange** [comment]
I have no idea of the intricacies of the code, but could this feature could be something like an update existing entry next to the `New` button after logging in, and clicking on the button would open an auto-type like window where one could fuzzy search the entry to add the url to ?

**Comment by Omnibrain007** [comment]
I think it is better the other way round. 
You search with Auto-Type for a username/password of existing entry, then double click to enter it in the fields. 
After this you normally see the dialog with Add or Update.
On that dialog there could be just on additional button "Add URL" to just add the new url to the existing entry.

**Comment by droidmonkey** [comment]
This issue conflates auto-type with browser integration. This issue is ONLY about browser integration. There are other requests on the keepassxc side that relate to improving auto-type.

**Comment by Omnibrain007** [comment]
Yes it is the browser integration where I want to easy as possible to add new domains or subdomains to an existing entry.

Auto-Type I just mentioned because this is the way for me at the moment to easy search directly on a webpage for existing credentials, enter them and to login to the new website. 
So for me the step to search for the entry where I want to add this new url on "browser integration" would be done already. And after doing like this I see already a dialog to add new entry or update existing. 

But for sure there can be also a separate new search dialog on right click in an open webpage to add the URL to the "browser integration" page of an existing entry.  But from my point of which is this much more coding work.

**Comment by varjolintu** [comment]
I think this belongs to https://github.com/keepassxreboot/keepassxc-browser/issues/1234. The URL field could be possible to modify before saving.
