### ISSUE TITLE
Browser integration error when first starting web browser

### ISSUE THREAD

**Issue by agsteele** [keepassxreboot/keepassxc-browser#2168]
Since a recent update of KeePassXC I am getting a browser integration error as follows:

        KeePassXC-Browser has encountered an error:

        Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 

It is resolved by clicking on the Reload button in the toolbar button

Should add that I have attempted reinstalling KeePassXC and the browser plugin to no effect

Firefox 124.0.2
KeePassXC 2.7.7
KeePass-Browser plugin 1.9.0.3

## Steps to Reproduce
1. Close and reopen browser
2. Plugin toolbar icon shows an error warning
3. Click plugin icon to see error:  Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 
4. Resolve by clicking reload

## Expected Behavior
Connection to KeePassXC would happen without need to manually reload

## Actual Behavior
Plugin fails to connect automatically

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.7.7
Revision: 68e2dd8

KeePassXC-Browser plugin 1.9.0.3

Browser Firefox 124.0.2

Operating system: Windows 11 Version 2009
CPU architecture: x86_64
Kernel: winnt 10.0.22631

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

**Comment by varjolintu** [comment]
Did Firefox just self-update? You can try the following steps:
- Close both browser and KeePassXC, and make sure keepassxc-proxy.exe is not running
- Open KeePassXC first, then the browser
- If it does not work, go to KeePassXC settings, Browser Integration's Advanced tab and enable (or turn off and re-enable) the option "Update native messaging manifest files at startup" and try the first step again.

**Comment by agsteele** [comment]
You're correct, of course, that this could be a Firefox issue.  There have been a couple of Firefox updates since this issue seemed to start.

I followed the steps suggested but with no effect.

On one restart of KeePassXC then the browser it did seem to work correctly. I closed and reopened Firefox and then found the issue as before.

Sorry for the bad news.

Happy to provide logs/tests etc if this is an issue that needs attention.

**Comment by varjolintu** [comment]
So restarting both -> works. Just restarting Firefox -> problem appears? Can you reproduce this every time?

**Comment by agsteele** [comment]
Yes restarting Firefox and the issue arises.
I'll debug the Firefox addins and report back.

**Comment by agsteele** [comment]
I've been able to work through the various add-ons that I have installed with Firefox.  It seems that it is the AdBlock Plus add-on that is causing the issue. Disabling this add-on seems to resolve the KeePassXC-browser issue.

FWIW AdBlock Plus v3.25.1

**Comment by varjolintu** [comment]
That's strange. I wonder what does it do that interferes with the extension. Anyway, I'd recommend switching to uBlock Origin instead.
