### ISSUE TITLE
Update Wiki Troubleshooting Guide with Arc Browser

### ISSUE THREAD

**Issue by mschmidtkorth** [keepassxreboot/keepassxc-browser#2171]
Hi, there does not seem to be a way to create a PR for Wiki pages, so I'm posting it here.

**Proposed change:**
- For https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
- Add an entry for "[Arc](https://arc.net/)" after MacOS -> Edge with the following path
- `~/Library/Application Support/Arc/User Data/NativeMessagingHosts`

Thanks for all your development!

**Comment by droidmonkey** [comment]
Done
