### ISSUE TITLE
Cannot connect to KeePassXC on Windows10/Vivaldi

### ISSUE THREAD

**Issue by Shadow-Devil** [keepassxreboot/keepassxc-browser#2172]
I am trying to setup KeePassXC on my Windows 10 PC with Vivaldi but currently run into issues.
1. There was no Registry Entry for the json config file created, so I created it manually. It somehow was created for Chrome so I could copy paste it and changed the file name.
2. It seems like the keepassxc-proxy is not running automatically. I also tried to run it manually but the Browser extension still doesn't connect to the KeePass Application.

## Expected Behavior

Connect the browser extension with the local App.

## Current Behavior

The connection can not be established. (Also, see logs below)

## Steps to Reproduce (for bugs)

1. Install KeePassXC on Windows
3. Install KeePassXC in Vivaldi
4. Enable Browser Integration
5. Try to connect

## Debug info

```
Unchecked runtime.lastError: Cannot create item with duplicate id fill_username_password
Unchecked runtime.lastError: Cannot create item with duplicate id fill_password
Unchecked runtime.lastError: Cannot create item with duplicate id fill_totp
Unchecked runtime.lastError: Cannot create item with duplicate id fill_attribute
Unchecked runtime.lastError: Cannot create item with duplicate id show_password_generator
Unchecked runtime.lastError: Cannot create item with duplicate id save_credentials
Unchecked runtime.lastError: Cannot create item with duplicate id request_autotype
client.js:383 KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:132 [Error client.js:403] KeePassXC-Browser - Failed to connect: Failed to start native messaging host.
global.js:132 [Error keepass.js:313] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
2global.js:132 [Error keepass.js:313] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
2global.js:132 [Error keepass.js:941] KeePassXC-Browser - No content script available for this tab.
global.js:132 [Error keepass.js:313] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
client.js:383 KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:132 [Error client.js:403] KeePassXC-Browser - Failed to connect: Failed to start native messaging host.
global.js:132 [Error keepass.js:418] KeePassXC-Browser - 9: Key exchange was not successful.
client.js:383 KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:132 [Error client.js:403] KeePassXC-Browser - Failed to connect: Failed to start native messaging host.
global.js:132 [Error keepass.js:418] KeePassXC-Browser - 9: Key exchange was not successful.
```

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Win
Browser: Vivaldi

**Comment by droidmonkey** [comment]
You need to enable Vivaldi browser within the keepassxc browser settings.

**Comment by Shadow-Devil** [comment]
I did enable it. There is one button for all `Chrome, Vivaldi, and Brave` which is checked.

**Comment by Shadow-Devil** [comment]
Registry is also edited like this: 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/29004905/31886519-9f68-4f5f-8f17-c7f897b1e393)

**Comment by Shadow-Devil** [comment]
Registry was edited like this: 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/29004905/2981a10c-ef80-4a83-9c61-b017243f4cab)

**Comment by Shadow-Devil** [comment]
I also restarted my PC

**Comment by varjolintu** [comment]
Check:
- The executable path in that JSON file is correct
- You can start `keepassxc-proxy.exe` manually

**Comment by Shadow-Devil** [comment]
I copy pasted the path of the JSON file in the file explorer and it directly opened in Notepad:
```
{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}
```
I also started the `keepassxc-proxy.exe` manually but still receive the same error message in the Extension:
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/29004905/753a8d27-4592-4d40-83df-8144dc92ff64)

**Comment by Shadow-Devil** [comment]
I also sometimes get the following errormessage:
`[Error keepass.js:418] KeePassXC-Browser - 9: Key exchange was not successful.`
