### ISSUE TITLE
Passkey object is not of type PublicKeyCredential

### ISSUE THREAD

**Issue by m-baertschi** [keepassxreboot/keepassxc-browser#2173]
## Expected Behavior

When a new Passkey is registered with "navigator.credentials.create()" the returned type should be "PublicKeyCredential" and the response of type "AuthenticatorAttestationResponse". Some Websites fail or expect options that are otherwise not available. 

The Webauthn Standart is very clear that the return object type must be verified. See point 3 of section 7.1: https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential

## Current Behavior

The currently returned object by the extension does not pass the check "instanceof PublicKeyCredential".

## Possible Solution

The returned Objects must have the correct prototype hierarchy. 

## Debug info

KeePassXC-Browser - 1.9.0.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
I'm aware of this. Fixing soon.
