### ISSUE TITLE
https://account.here.com/ KeePassXC-Browser is not working

### ISSUE THREAD

**Issue by hieuck** [keepassxreboot/keepassxc-browser#2174]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Auto-fields, Choose custom login fields is not working

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Visit the website (https://account.here.com/)
2. Use autofill
3. function is not working

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.7
Revision: 68e2dd8

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11 Version 2009
Desktop Env: Gnome/KDE/XFCE/Mate/Cinnamon
Windowing System: X11/Wayland

**Comment by varjolintu** [comment]
The login field is inside Shadow DOM. Add `https://account.here.com/sign-in` to Site Preferences in the extension settings and enable "Improved Input Field Detection".
