### ISSUE TITLE
WordPress集成通行密钥

### ISSUE THREAD

**Issue by baishu12** [keepassxreboot/keepassxc-browser#2180]
我的环境:
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Win64
Browser: Microsoft Edge 124.0.0.0
WordPress 6.5.2
使用插件Two Factor 0.9.1，官网https://cn.wordpress.org/plugins/two-factor/
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/80586922/b236dbdb-95bf-4360-add8-08a679e07622)
我在注册通行密钥时遇到了问题

**Comment by varjolintu** [comment]
English please.

**Comment by varjolintu** [comment]
I have no problems creating and authenticating with a passkey for Wordpress account. I need more info.
