### ISSUE TITLE
KeePassXC-Browser not connecting to database on ungoogled-chromium (Ubuntu 24.04)

### ISSUE THREAD

**Issue by nachtreiher** [keepassxreboot/keepassxc-browser#2182]
## Expected Behavior

The extension should be able to connect to the KeePassXC database without problems.

## Current Behavior

Keeps displaying "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." when trying multiple times to connect. 

The extension debug console via DevTools prints this everytime the "Reload" button is pressed:
```
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
[Error client.js:403] KeePassXC-Browser - Failed to connect: Specified native messaging host not found.
[Error keepass.js:812] KeePassXC-Browser - changePublicKeys failed: TypeError: Cannot read properties of null (reading 'postMessage')
```

It does work on Mozilla Firefox (installed via [Mozilla's PPA](https://launchpad.net/~mozillateam/+archive/ubuntu/ppa)).

## Steps to Reproduce (for bugs)

1. Install Ubuntu 24.04
2. Install ungoogled-chromium via [berkley4's](https://github.com/berkley4/ungoogled-chromium-debian) builds
3. Install KeePassXC (either default repos or PPA), and configure Browser Integration w/ Chromium checked
4. Install the KeePassXC-Browser extension via the Chrome Web Store
5. Try connecting to an opened database

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.03
Operating system: Linux (Ubuntu 24.04 - Noble Numbat)
Browser: ungoogled-chromium

**Comment by droidmonkey** [comment]
Ungoogled Chromium is NOT Chromium. You need to move the native messaging configuration file into the proper place.

**Comment by nachtreiher** [comment]
> Ungoogled Chromium is NOT Chromium. You need to move the native messaging configuration file into the proper place.
> 
> Probably `~/.config/ungoogled-chromium/NativeMessagingHosts`

This is not the solution. ungoogled-chromium's configuration is located in `~/.config/chromium`.
Also, I used ungoogled-chromium w/ KeePassXC-Browser for years and this is the first time this happened. Every other time it did connect to the database without problems. Maybe a problem with Ubuntu?

**Comment by droidmonkey** [comment]
Well in that case, proceed to the troubleshooting guide: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by nachtreiher** [comment]
> Well in that case, proceed to the troubleshooting guide: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

Found the error when stracing the process, apparently Chromium was trying to read the file out of `/etc/chromium/native-messaging-hosts/` instead of `~/.config/chromium/NativeMessagingHosts` for some reason. No idea if that's a global thing with Chromium in general or if i just fucked up my browser installation. Either way it works now, thanks for the help.

**Comment by varjolintu** [comment]
@nachtreiher I think it's strange to store browser settings in a system path instead of user's own home. That's not how it's usually done.

**Comment by nachtreiher** [comment]
> @nachtreiher I think it's strange to store browser settings in a system path instead of user's own home. That's not how it's usually done.

No idea if that's an issue with my build of ungoogled-chromium, or if it has something to do with Chromium in general, or maybe Ubuntu. All the previous times, it instantly connected to the database OOBE, with the messaging host file in the `.config/chromium` folder. I'll try previous builds and other Chromium-based browsers to see if that's a recurring problem or if it's just this build.

**Comment by nachtreiher** [comment]
Seems like it's trying to read the system-wide path (https://developer.chrome.com/docs/extensions/develop/concepts/native-messaging) instead of the user-specific one. Maybe an issue with how dpkg installs packages.

**Comment by droidmonkey** [comment]
That would make sense in a managed deployment scenario where you wanted to restrict users with what extensions and native messaging applications you allow.

**Comment by dpenztech** [comment]
I had this problem using chromium-ungoogled on Slackware64 15.0. What I found was that the file  org.keepassxc.keepassxc_browser.json that is installed by the extension is placed in .config/chromium/NativeMessagingHosts/, not .config-chromium-ungoogled/NativeMessagingHosts/. I copied the file to the correct location, restarted the chromium-ungoogled, and everything now works.
