### ISSUE TITLE
Keepassxc Browser Extension - key exchange was not successfull Qubes Whonix Torbrowser

### ISSUE THREAD

**Issue by adamwebber2** [keepassxreboot/keepassxc-browser#2183]
UPDATE. THIS IS FIXED HERE: https://github.com/keepassxreboot/keepassxc-browser/issues/1399#issuecomment-1246145118

Keepassxc doesnt connect with torbrowser extension.

Working with whonix-17. All updated. Fresh install of keepassxc (sudo apt install keepassxc)
TorBrowser comes preinstalled and is also updated (13.0.14 (based on Mozilla Firefox 115.10.0esr). 

Browser Integration is activated
Browser extension is installed

I've checked the troubleshooting guide but I dont know how to proceed
Troubleshooting point 1 done: Checked for the .json file -> all good.
Troubleshooting point 2 done: Checked for the .json path to keepassxs-proxy -> all good

Troubleshooting point 3: 
I did: "Use the following command: sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass"

Result:
```

[pid 18564] openat(AT_FDCWD, "/home/user/.tb/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid 18564] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 18564] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 18564] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 18564] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 18564] stat("/usr/bin/keepassxc-proxy",  <unfinished ...>
[pid 19060] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/user/.tb/tor-browser/Brows"..., "keepassxc-browser@keepassxc.org"], 0x7ec6ea877800 /* 79 vars */ <unfinished ...>
```

Then I did: ps aux | grep keepassxc-proxy
Result: 
user       19618  0.0  0.0   6468  2048 pts/2    S+   13:47   0:00 grep --color=auto keepassxc-proxy

Would be great if someone can help me out here

**Comment by varjolintu** [comment]
Some questions:
- Does normal Firefox work?
- Are you using the Custom Browser feature with `/home/user/.tb/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts` path set?

**Comment by varjolintu** [comment]
Or maybe some of the Whonix features, like "Malware protection" or "App Stream Isolation" prevents Native Messaging working normally?

**Comment by adamwebber2** [comment]
> Or maybe some of the Whonix features, like "Malware protection" or "App Stream Isolation" prevents Native Messaging working normally?

What would be the fix for that?

> Could be an apparmor policy preventing access to /usr/bin/keepassxc-proxy.

Could be but how do I enable access?

**Comment by droidmonkey** [comment]
At this point, you'll have to go to the whonix forums or similar and ask them. We have no knowledge of whonix and how it would potentially interfere with keepassxc.

**Comment by adamwebber2** [comment]
Here is the fix:
https://github.com/keepassxreboot/keepassxc-browser/issues/1399#issuecomment-1246145118
