### ISSUE TITLE
AutoOpen entries "are not considered" until KP is focused before retrying on the browser

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#2191]
## Expected Behavior

1. Open the page to authenticate
2. Click the gray KeePass icon
3. Type your password
4. _... wait for the auto-open db to open_
5. KeePass icon on the username becomes green
6. Credentials come by clicking it

## Current Behavior

1. Open the page to authenticate
2. Click the gray KeePass icon
3. Type your password
4. _... wait for the auto-open db to open_
5. KeePass icon on the username stays gray, no credentials come by clicking it
6. Refresh the page
7. KeePass icon on the username is green, no credentials come by clicking it
8. Focus KeePass in order to verify that the db has opened
9. Focus the tab of the new DB (that contains the entry)
10. Go back to Chrome
11. "Miraculously" credentials already wait me

## Steps to Reproduce (for bugs)

1.
12.
13.
14.

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Linux x86_64
Browser: Chrome/Chromium 114.0.0.0

```
19:51:21.044 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:05:39.400 global.js:132 [Error keepass.js:385] KeePassXC-Browser - 1: Database not opened
22:05:39.401 global.js:132 [Error httpauth.js:76] KeePassXC-Browser - No logins found for HTTP Basic Auth.
22:05:58.124 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:06:12.373 global.js:132 [Error keepass.js:385] KeePassXC-Browser - 1: Database not opened
22:06:22.801 global.js:132 [Error client.js:211] KeePassXC-Browser - 15: No logins found
22:06:24.050 global.js:132 [Error client.js:211] KeePassXC-Browser - 15: No logins found
22:06:33.645 global.js:132 [Error client.js:211] KeePassXC-Browser - 15: No logins found
22:06:53.406 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:08:29.208 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:10:43.367 global.js:132 [Error keepass.js:385] KeePassXC-Browser - 1: Database not opened
22:10:43.389 global.js:132 [Error keepass.js:385] KeePassXC-Browser - 1: Database not opened
22:15:34.803 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:15:56.355 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
22:16:38.385 global.js:132 [Error page.js:132] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.
```

**Comment by stdedos** [comment]
I'd be nice if there were some other information too (namely, successes)

**Comment by stdedos** [comment]
Is the wiki btw up-to-date? https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

My extension options looks like this
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/133706/3053940e-a095-4f39-942c-c280fd948c25)

**Comment by droidmonkey** [comment]
This is the only step that matters:

> Focus the tab of the new DB (that contains the entry)

We have an issue already tracking needed improvements to "focused DB" behavior.

**Comment by stdedos** [comment]
Can you mention it / close this as duplicate? 😄

**Comment by varjolintu** [comment]
This is related to https://github.com/keepassxreboot/keepassxc-browser/issues/1275 and https://github.com/keepassxreboot/keepassxc-browser/issues/206
