### ISSUE TITLE
Login data not correctly filled

### ISSUE THREAD

**Issue by Omnibrain007** [keepassxreboot/keepassxc-browser#2192]
I have one login page which seems to have a very uncommon structure.
https://www.stadtwerke-flensburg.de/kundenkonto/#/loginRegistration/

On this login page the password field will not be correctly identified.
Fill the login is working but for the password I only see the keepassxc symbol to generate a password.
The function to manual define the login and password fields are not working.

 KeePassXC-Browser-Version: 1.9.0.3
KeePassXC-Version: 2.7.8 
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
Use Custom Login Fields feature to select the fields manually for the site.

**Comment by Omnibrain007** [comment]
Strange. For me it is not working. 
Did this with custom login fields several times but always only login but not password will be filled. 
Also tried all the different special site options, like Single login field recognition, Cross-Origin, etc.
Can I somehow see the exact html field information which are saved for custom login field?

**Comment by Omnibrain007** [comment]
It seems to be a problem with the new internal cookie consent management in Firefox. 
I deactivate the feature for this site then it is working but only without custom login fields.
When I define now custom login fields then I got the same error as before. 
So my issue is solved but it seems that there is perhaps an general issue with custom login field and this special password field on that site.

**Comment by varjolintu** [comment]
I got a situation reproduced where the fields are identified correctly, but after clicking the username icon, the password field somehow disappears from the combination. Very strange. Maybe the page renders the element again after username fill. Only filling password separately after that works.

**Comment by Omnibrain007** [comment]
Oh good, that you can reproduce it. ;) 
At the moment after I have disabled firefox consent management and agreed the consent for cookies manual, it seems to work correctly without custom login fields.  
But as I have written, still not with custom fields.

**Comment by varjolintu** [comment]
That's even more strange that the cookies popup somehow affects this.
