### ISSUE TITLE
Unable to connect to KeepassXC 2.7.8 with Firefox 125 & keepass-browser 

### ISSUE THREAD

**Issue by HDInfautre** [keepassxreboot/keepassxc-browser#2194]
Hello
I just downloaded KeepassXC version 2.7.8 appimmage

I have activated the connection to Firefox and Brave browsers
I can no longer connect to Firefox snap 125.0.3 (it worked before with keepass-browser 1.9.0.3)
I can connect to Brave which automatically updated to 1.9.0.4

I downloaded the keepassxc-browser_1.9.0.4_firefox.zip package because it seems that Firefox is not yet offering the update?
The problem is that I don't see what I should do with this zip file!

A few years ago, I used a batch sh but I don't see it anymore
I admit that I also have difficulty with the very technical documentation
thank you for helping me

**Comment by varjolintu** [comment]
If you want to use the zip package directly, see: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

If the Snap does not connect, it's probably a bug in the Snap package. We are unable to help with that.

**Comment by HDInfautre** [comment]
> If you want to use the zip package directly, see: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually
> 
> If the Snap does not connect, it's probably a bug in the Snap package. We are unable to help with that.
Hi
Thank you for the quick reply
I applied (and noted ;-) ) the manual procedure.
It does not work; If I understand correctly, this comes from Firefox snap?
1/ will this change if I switch keepass XC from appimage to snap?
(At one point it worked like this)
2/ could this be resolved with the next version firefox snap ?

**Comment by varjolintu** [comment]
You must change your browser to a non-Snap version.
