### ISSUE TITLE
Unable to connect ppa Firefox with keepass

### ISSUE THREAD

**Issue by Mallo321123** [keepassxreboot/keepassxc-browser#2196]
## Expected Behavior

Keepassxc Browser connect to Keepassxc Desktop

## Current Behavior

Keepasscx browser says:

KeePassXC browser has detected an error:
The connection to KeePassXC is not possible. Check whether the browser integration is activated in the KeePassXC settings. 

When I click on reload, it says:

KeePassXC browser has detected an error:
Key exchange was not successful. 

## Possible Solution

Its wheard, because I swiched from the Kubuntu Firefox Snap package (which shouldn't work, but has worked) to the kubuntu Firefox ppa (which should work), but now its not working

## Steps to Reproduce (for bugs)

enable firefox browser support in keepassxc
try to connect to keepass db

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.9.0.3
Operating system: Kubuntu
Browser: Firefox (kubuntu ppa) version: 126.0

**Comment by droidmonkey** [comment]
Adjust your firejail or apparmor settings for Firefox. See our troubleshooting guide.
