### ISSUE TITLE
XML pretty-print gets broken (Firefox)

### ISSUE THREAD

**Issue by jze** [keepassxreboot/keepassxc-browser#2198]
With the plugin enabled Firefox does not pretty-print XML documents anymore. It seems that some kind of default stylesheet is applied that only displays text content. Until a few weeks ago, it still worked.

## Expected Behavior

Enabling the extension should not change Firefox's way to display XML documents. When loading an XML document the XML tags will be displayed.

## Current Behavior

Only text content is displayed but not XML tags.

## Possible Solution

Apparently the problem has already existed in the past: #50, #301  A solution must have been found back then. 

## Steps to Reproduce (for bugs)

1. Disable plugin if enabled
2. Visit an XML document online, e.g. https://www.w3schools.com/xml/note.xml → will be pretty-printed
3. Enable plugin. 
4. reload the page → you only see the text "Tove Jani Reminder Don't forget me this weekend!" but no XML tags

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.3
Operating system: Linux
Browser: Firefox 125.0.3 (64-Bit)

**Comment by varjolintu** [comment]
This happens because of the passkey script injection. I'll investigate the issue.
