### ISSUE TITLE
Save credentials right click menu storing password as username

### ISSUE THREAD

**Issue by srwareham** [keepassxreboot/keepassxc-browser#22]
## Expected Behavior

Using the "Save credentials" dialog after right clicking on a username **or** password should allow the creation of a new login with the correct attributes.

## Current Behavior

Accessing the "Save credentials" dialog by right clicking on the username field correctly creates a new login.

Accessing the "Save credentials" dialog by right clicking on the password field creates a new login with the username and password values **both** being set to the password. E.g.:

![screen shot 2018-02-27 at 8 53 33 pm](https://user-images.githubusercontent.com/3392952/36765911-88e58442-1c01-11e8-8168-abbef2d706c3.png)

## Steps to Reproduce (for bugs)

1. Open firefox and navigate to any login page
2. Enter a username and password
3. Right click on the password field and Select "KeepassXC-Browser->Save credentials"
4. Observe the popup dialog has the password displayed in the username field
5. (Optional) open the new record in Keepassxc and observe both the username and password values contain the password

## General Info
KeePassXC fork - 2.3.0 (default settings)
keepassxc-browser - 1.0.0 (default settings)

Operating system: macOS 10.13.3
Browser: Firefox 58.0.2 (64-bit)
Proxy used: No

**Comment by varjolintu** [comment]
Nice catch.
