### ISSUE TITLE
SimpleTax password form doesn't work

### ISSUE THREAD

**Issue by Hello71** [keepassxreboot/keepassxc-browser#220]
## Steps to Reproduce (for bugs)
1. Add a KeepassXC entry with URL "https://app.simpletax.ca/".
2. Navigate to https://app.simpletax.ca/.
3. Select "I've used SimpleTax before".

## Expected Behavior
Username and password are filled in, or an offer is made to fill them in (depending on settings)

## Current Behavior
Nothing happens.

## Possible Solution
When attempting to choose own credential fields, selecting username or password for username results in all fields being unselectable. This is despite `#email` and `#password` being siblings, both children of the same form.

## Debug info
KeePassXC - 2.3.3
keepassxc-browser - 1.1.7
Operating system: Linux
Browser: Firefox
Proxy used: NO

**Comment by Hello71** [comment]
However, pressing Alt-Shift-U successfully fills the form.

**Comment by varjolintu** [comment]
I can reproduce the issue. Will inspect it later.

**Comment by varjolintu** [comment]
Closing this as the page clearly modifies the input fields on-the-fly and prevents adding any extension related data.
