### ISSUE TITLE
Chase Online: Input Fields Not Found

### ISSUE THREAD

**Issue by nikduvall** [keepassxreboot/keepassxc-browser#2200]
A site that previously worked for me is now showing the following error in the Console:

```
[Debug observer-helper.js:195] KeePassXC-Browser - Input fields found:
global.js:127 []

```

When I try to use _**Choose Custom Login Fields**_, nothing on the screen highlights.

Site: [Chase Online](https://secure.chase.com/)

The login form on their main [homepage](https://www.chase.com) still works.

## Expected Behavior
Auto-fill button appears and _**Choose Custom Login Fields**_ feature allows me to select login fields

## Current Behavior
Neither work

## Possible Solution
Inspect code for the new approach to displaying login forms to identify how to fix both issues

## Steps to Reproduce (for bugs)
1. Navigate to [Chase Online](https://secure.chase.com/)
2. Auto-fill button missing
3. Error Code above in Console (if debug logging is enabled)
4. _**Choose Custom Login Fields**_ feature does not highlight any fields

## Debug info
KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.2
Operating system: MacIntel
Browser: Chrome/Chromium 122.0.0.0

**Comment by varjolintu** [comment]
This is already tracked in https://github.com/keepassxreboot/keepassxc-browser/issues/1358 and errors have been reported multiple times for this.:
https://github.com/keepassxreboot/keepassxc-browser/issues/1846
https://github.com/keepassxreboot/keepassxc-browser/issues/1326

If setting entry URL to `https://chase.com` does not work, try adding the site to Site Preferences with cross-origin iframe support enabled.

**Comment by varjolintu** [comment]
Another tip:
Add `https://*.chase.com/*` to Site Preferences and enable "Improved input field detection".

**Comment by nikduvall** [comment]
> https://*.chase.com/*

This fixes the issue!

**Comment by tfvlrue** [comment]
I just ran into the same problem, but the Site Preferences page refuses to accept `https://*.chase.com/*`. It says "Invalid URL. Please check the input."

However, `https://secure.chase.com/*` seems to work fine (and solves the field detection problem).
