### ISSUE TITLE
How to ignore all localhost(including 127.0.0.1 and all ports) pages?

### ISSUE THREAD

**Issue by goldingdamien** [keepassxreboot/keepassxc-browser#2201]
Is there a way to easily ignore all localhost pages?
I know one port can be ignored with something like http://localhost:5173/ in options.html#site-preferences
However, I often have different ports used for different projects.

※ Reason for wanting this is I often want to perform automatic checks or screen captures in development environment, but this changes the UI.

## Expected Behavior

Ignore all origins regardless of port if specified so.

## Current Behavior

No mention of being able to do something like globbing so assuming it is not possible.
Need to set each port separately.

## Possible Solution

Allow multiple port setting via glob or special setting.

## Debug info

KeePassXC - Latest
KeePassXC-Browser - Chrome
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
Did you try setting wildcards, for example`http://localhost/*` or just `http://localhost`?

**Comment by goldingdamien** [comment]
I haven't tried wildcards. Are they documented somewhere? Are they supposed to work(including on ports)?

**Comment by varjolintu** [comment]
I double checked this, and it seems we are not supporting wildcards with ports, and if URL has a port, Site Preferences is expecting that to be used. Marking this as a bug.

**Comment by varjolintu** [comment]
I made a fix for this that ignores all ports by default. In optimal situation we should also allow single ports even if a global ignore rule exists, but that does not work at this point. Is it something you'd prefer?

**Comment by goldingdamien** [comment]
Thank you.
I think this is good: Not setting a port means all ports, setting a port means only that port.
I am fine, with all ports and localhost only, but do think it would be best if what I just stated worked fully for all domains.
