### ISSUE TITLE
Not detecting login fields on https://my.wealthsimple.com/app/login

### ISSUE THREAD

**Issue by brianjmurrell** [keepassxreboot/keepassxc-browser#2204]
## Expected Behavior
I should be able to log into WealthSimple using this extension.

## Current Behavior
Does not detect login fields, even when I open the extension and _Redetect login fields_

## Steps to Reproduce (for bugs)
1. With KeepassXC and the browser extension installed and working
2. Go to https://my.wealthsimple.com/app/login
3. Observe that you cannot get KeePassXC-Browser to identify the login/password fields

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.0.5
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
Use Custom Login Fields to select username and password fields.
