### ISSUE TITLE
KeepaassXC Browser Extension Cannot Read/Recognize Bitwarden's PassKey Login Attempt 

### ISSUE THREAD

**Issue by linuxtopia** [keepassxreboot/keepassxc-browser#2205]
## Expected Behavior

Extension should store and recognize/read the passkey demand when login process via passkey login on Bitwarden Vault.

## Current Behavior

The extension can catch passkeys when storing on kdbx database however after the record of passkey that login attempt to Bitwarden Vault via passkey the extension cannot see or recognize the requesting of Bitwarden Vault for passkey login. It stuck on reading mode.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/19939134/ea85b160-4c14-4b0c-a6a0-13161dbc8994)

## Steps to Reproduce (for bugs)

1. Go to Bitwarden Vault via web ui and activate passkey from settings and store passkey with KeepassXC
2. Then check if the passkey login attempt works on Bitwarden Vault after logout
3. Click on "Login with Passkey" on Bitwarden Vault web ui
4. Bitwarden Vault tries to read passkey but KeepassXC extension cannot answer the request.

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: openSUSE Leap 15.5 KDE 5.27.9
Browser: Brave Version 1.66.115 Chromium: 125.0.6422.112 (Official Build) (64-bit)

**NativeMessagingHosts**
`{
    "allowed_origins": [
        "chrome-extension://pdffhmdngciaglkoonimfcmckehcpafo/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
`

**Comment by varjolintu** [comment]
This is already tracked here: https://github.com/keepassxreboot/keepassxc/issues/10374#issuecomment-1994443215

We don't support the PRF support yet that is needed for Bitwarden's login.
