### ISSUE TITLE
When creating a new entry, optionally use the website title for the Title

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#2208]
## Expected Behavior

When creating a new entry, optionally use the website title for the Title

## Current Behavior

When creating a new entry, Title is website url (`localhost` for localhost urls)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

https://github.com/keepassxreboot/keepassxc-browser/issues?q=is%3Aissue+create+entry+website+title

**Comment by varjolintu** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc-browser/issues/662
