### ISSUE TITLE
Keepassxc-browser causes a delay in Firefox Startup time.

### ISSUE THREAD

**Issue by roaminghawk** [keepassxreboot/keepassxc-browser#221]
## Expected Behavior

Hello,
Keepassxc-browser causes a delay in Firefox Startup time.
When I disable the Keepassxc-browser and start Firefox it starts in less than 1-2 seconds, when Keepassxc-browser is enabled it adds 3-4 seconds to the startup time of Firefox.

## Current Behavior

A delay of 3-4 seconds in Firefox startup time when Keepassxc-browser is enabled.

## Steps to Reproduce (for bugs)

This was tested on my main profile and on a new profile with no other add-ons installed, and behavior is the same.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.7
Operating system: Windows 10
Browser: Firefox/
Proxy used: NO

**Comment by varjolintu** [comment]
I cannot reproduce this. Can you provide some more info or detailed statistics on browser start (debugging etc)?

**Comment by roaminghawk** [comment]
Unfortunately Mozilla removed Health report which used to show startup time.

Here is a crude way to show the difference, This is an empty profile with nothing but keepassxc-browser - 1.1.7 addon installed, that blue button is a restart button and does not affect the performance.

This gif is with the addon disabled:
https://i.imgur.com/0BnYYL5.gif

And this gif is with the addon enabled:
https://i.imgur.com/AP8hd3s.gif

**Comment by varjolintu** [comment]
Yes, I know. I wonder if this branch helps the issue: https://github.com/keepassxreboot/keepassxc-browser/tree/no_jquery

**Comment by roaminghawk** [comment]
I don't know how to compile a Firefox add-on from that link.

**Comment by varjolintu** [comment]
There's no need to compile. I can make a package for you later if you want to try it.

**Comment by roaminghawk** [comment]
Yes I want to try it please.

**Comment by roaminghawk** [comment]
Thanks.
I tried the no-jquery version on a Developer Edition and the delay in Firefox startup time is still there.
I rebooted into safe mode (On Windows 10) and tried again, and still the same delay on the official add-on version and no-jquery version.

I tried the no-jquery and normal version on a windows 7 host machine on Developer Edition Firefox and there was no delay in either of them. Startup time is almost the same with either of the add-ons enabled or disabled!

**Comment by roaminghawk** [comment]
Does the add-on preform any functions when Firefox is shutting down?
Reason for asking is that cold start-up time (Starting Firefox when it was closed) is fast with the add-on enabled, while restarting Firefox or closing it and opening it again quickly does show the lag in startup.!

**Comment by varjolintu** [comment]
Nope. I wonder if this might be related to native messaging. If you disable your browser support from KeePassXC so the native messaging host cannot be started, does it still show the delay?

**Comment by roaminghawk** [comment]
That delay is independent of the KeePassXC. It happens whether the KeePassXC is enabled or disabled. I tried disabling it and still that delay persists.

**Comment by varjolintu** [comment]
Does this still happen with 1.3.3?

**Comment by roaminghawk** [comment]
No. It seems to have been resolved with one of Firefox updates a a while ago, but I'm not sure which update.
