### ISSUE TITLE
A webpage (terminalserver) does not work anymore

### ISSUE THREAD

**Issue by st-anton** [keepassxreboot/keepassxc-browser#2210]
A terminalserver application (here: citrix) does not work anymore with this plugin. The initial splash screen is displayed endlessly. The form to login will not be displayed. 

## Expected Behavior
login form is displayed
![grafik](https://github.com/keepassxreboot/keepassxc-browser/assets/2517417/4743caa4-197f-4669-828f-536743fa36fa)

## Current Behavior
The initial splash screen is displayed endlessly. The form to login will not be displayed. 
![grafik](https://github.com/keepassxreboot/keepassxc-browser/assets/2517417/df4fc310-9824-46d9-afeb-39dc7f9c8174)

## Possible Solution
workaround 1: add the website URL to the plugin settings, so the plugin is disabled on this page.
workaround 2: disable the plugin

## Steps to Reproduce (for bugs)
open [https://access.rohde-schwarz.com/](https://access.rohde-schwarz.com/)

## Debug info
KeePassXC-Browser-Version: 1.9.0.5
KeePassXC-Version: 2.7.8 
Operating system: Win 10
Browser: Firefox 126.0.1

**Comment by varjolintu** [comment]
`Uncaught SyntaxError: Identifier 'stringToArrayBuffer' has already been declared`. Seems the web page clashes with one of our functions. Extensions are able to override such things for some reason..

Workaround while waiting for the fix is to disable passkeys from the extension side.
