### ISSUE TITLE
KeePassXC-Browser Key exchange was not successful.

### ISSUE THREAD

**Issue by guanmengxu** [keepassxreboot/keepassxc-browser#2212]
## Current Behavior

I delete my windows user, and create a new user, I login my windows use my new user. 
It seems that my KeePassXC-Browser can't connected to my database.
I have reinstall my KeePassXC and KeePassXC-Browser, but still have this error. I try the Troubleshooting-guide, but still not work.
I have tried the Portable version and msi install. but have not solved.
Thank you so much.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win64
Browser: Chrome/Chromium 123.0.0.0

**Comment by droidmonkey** [comment]
You need to reconnect your browser. Read the getting started guide.

**Comment by guanmengxu** [comment]
> You need to reconnect your browser. Read the getting started guide.

I have readed the started guide, and has follow the guide, but the error still in this. thank you so much
KeePassXC-Browser has encountered an error:

Key exchange was not successful.

**Comment by guanmengxu** [comment]
> You need to reconnect your browser. Read the getting started guide.

@droidmonkey 

I have readed the started guide, and has follow the guide, but the error still in this. 
The keepassXC not have any message to found, I think it should be a pop window to allow connect.
thank you so much
KeePassXC-Browser has encountered an error:
Key exchange was not successful.

**Comment by droidmonkey** [comment]
There is nothing we can do for you, unfortunately. You must be missing a step or haven't told us a critical detail.
