### ISSUE TITLE
KeePassXC-Browser Key exchange was not successful.

### ISSUE THREAD

**Issue by guanmengxu** [keepassxreboot/keepassxc-browser#2213]
## Expected Behavior

I delete my windows user, and create a new user, I login my windows use my new user.
It seems that my KeePassXC-Browser can't connected to my database.
I have reinstall my KeePassXC and KeePassXC-Browser, but still have this error. I try the Troubleshooting-guide, but still not work.
I have tried the Portable version and msi install. but have not solved.
Thank you so much.

## Steps to Reproduce (for bugs)

1.I have readed the getting started guide.
2.I try the Troubleshooting-guide
3.I have tried the Portable version and msi reinstall. also I reinstall my Chrome, but have not solved.
4.The KeePassXC have no pop window let me to allow to access my database.

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win64
Browser: Chrome/Chromium 123.0.0.0

**Comment by droidmonkey** [comment]
There is nothing we can do to help you, unfortunately. You must be missing a step in the initial setup.
