### ISSUE TITLE
how to use it on ungoogled-chromium

### ISSUE THREAD

**Issue by norcx** [keepassxreboot/keepassxc-browser#2218]
how to use it on [ungoogled-chromium](https://github.com/ungoogled-software/ungoogled-chromium)
Always displays: Unable to connect to KeePassXC. check that browser integration is enabled in the KeePassXC settings.

**Comment by droidmonkey** [comment]
Look at the troubleshooting guide or search this issue board plenty of answers

**Comment by varjolintu** [comment]
Use the Custom Browser feature in the KeePassXC's Browser Integration's Advanced tab to provide the path to Ungoogled Chromium's `native-messaging-hosts`.
