### ISSUE TITLE
Cant connect from ungoogled-chromium (.deb)

### ISSUE THREAD

**Issue by ElEd0** [keepassxreboot/keepassxc-browser#2219]
## Expected Behavior

Chromium should connect to the database

## Current Behavior

Connection fails with message: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
Extension works in firefox.
Browser integration checked options: firefox, chromium and google chrome
file gets correctly created at /home/[user]/.config/chromium/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
Ungoogled-chormium official .deb binary installed via apt install ./*.deb (NOT snap, NOT flatpak, NOT any other garbage)

## Steps to Reproduce (for bugs)

1. Install official ungoogled-chromium binary with apt
2. Install browser integration extension
3. Activate browser integration in KeePassXC for chromium
4. Follow steps to connect both
5. Fails

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.9.0.3
Operating system: Linux x86_64
Browser: Chrome/Chromium 124.0.0.0

System: Debian bookworm
DE: KDE Plasma
Browser: ungoogled-chromium

**Comment by varjolintu** [comment]
Ungoogled Chromium is not supported be default. Use the Custom Browser feature to add the browser specific path. It's probably `~/.config/ungoogled-chromium/NativeMessagingHosts` or something similar. depending on the configuration path.

**Comment by ElEd0** [comment]
> Ungoogled Chromium is not supported be default. Use the Custom Browser feature to add the browser specific path. It's probably `~/.config/ungoogled-chromium/NativeMessagingHosts` or something similar. depending on the configuration path.

Ungoogled chromium uses ~/.config/chromium as its configuration path. There is no specific ungoogled-chromium config directory. I tried it anyway but it does not work

**Comment by droidmonkey** [comment]
Search is your friend

https://github.com/keepassxreboot/keepassxc-browser/issues/2182#issuecomment-2081352826

**Comment by ElEd0** [comment]
> Search is your friend
> 
> [#2182 (comment)](https://github.com/keepassxreboot/keepassxc-browser/issues/2182#issuecomment-2081352826)

It worked! You are a legend! Thank you very much

**Comment by bombonatti** [comment]
After moving NativeMessagingHosts folder to correct path, could connect to database.

In my case:
`mv ~/.config/chromium/NativeMessagingHosts/ ~/.config/chromium-ungoogled/`
