### ISSUE TITLE
French l10n: "Guide de démarrage configurer" for Getting Started Guide

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2220]
## Current Behavior
When trying to use KeePassXC-Browser in Firefox, one gets an error. When trying to open the extension to solve that with Firefox in French, the following dialog shows: 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/486141/3936619d-fbf7-4f34-8a34-1195e80fd7dc)
The message above is:

> Est-ce votre première utilisation ? Veuillez consulter notre guide de démarrage.
> [Guide de démarrage configurer – Configurer l’intégration au navigateur](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration)

This is because [the French text for the `popupGettingStartedLinkText` message](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/_locales/fr/messages.json#L413) (which is "Getting Started Guide - Setup Browser Integration" in English) is:

> Guide de démarrage configurer – Configurer l’intégration au navigateur

## Possible Solution
A proper translation would be just:

> Guide de démarrage – Configurer l’intégration au navigateur

That being said, that dialog contains a question which cannot be answered (I guess a rhetorical question). A clearer text would be:

> First time users are advised to check [the _Setup Browser Integration_ section of the _Getting Started Guide_](https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration).

## Steps to Reproduce (for bugs)
1. Ensure that Firefox is running in French.
2. Ensure that KeePassXC-Browser is not associated with KeePassXC. If needed, go to KeePassXC's browser integration settings and make sure that "Enable browser integration" is not checked.
3. Click on Firefox's _Extensions_ button (puzzle icon top right).
4. Click on the KeePassXC-Browser entry

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.5
Operating system: Microsoft Windows
Browser: Mozilla Firefox

**Comment by droidmonkey** [comment]
Head on over to https://transifex.com/keepassxc/keepassxc-browser and make the corrections.
