### ISSUE TITLE
French l10n: "Error! Erreur : Aucun identifiant trouvé."

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2222]
## Expected Behavior
When clicking the "Fill credentials from KeePassXC" icon, credentials should be entered or a proper error reported.

## Current Behavior
At least on https://online.achieva.mb.ca/login, all I get is an error displayed top right. With Firefox in English, the error reads:

> Error! No logins found.

But in French, it reads:

> **Error! Erreur** : Aucun identifiant trouvé. https://online.achieva.mb.ca

In other words, the word "Error" is displayed twice.

## Cause
_locales/en/messages.json contains 2 messages which are identical, at least regarding their English text:
```
    "errorMessageNoLogins": {
        "message": "No logins found.",
        "description": "No logins found."
    },
[...]
    "credentialsNoLoginsFound": {
        "message": "No logins found.",
        "description": "Shown when no credentials are found for the current page."
    },
```
In French, [the latter is mistranslated](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/_locales/fr/messages.json#L317C1-L320C7), with a spurious "Erreur":
```
    "credentialsNoLoginsFound": {
        "message": "Erreur :\nAucun identifiant trouvé.",
        "description": "Shown when no credentials are found for the current page."
    },
```
I am guessing whoever translated `credentialsNoLoginsFound` noticed that "Error" was not being translated and added the translation to the wrong string, obviously causing that awkward result.

## Possible Solution
If there is no difference between both messages, `credentialsNoLoginsFound` could be merged into `errorMessageNoLogins`. Otherwise, its French text should be changed to be identical to the `errorMessageNoLogins`.

<details>
  <summary>By the way</summary>

1. The "Error!" string should be translatable.
1. "login" is an ambiguous term. The French translator visibly misunderstood the sense which was meant. I believe "No credentials found" would be better.

</details>

## Steps to Reproduce
1. Go to https://online.achieva.mb.ca/login
1. Click on the "Fill credentials from KeePassXC" icon

## Debug info

KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.0.5
Operating system: Windows
Browser: Firefox

**Comment by droidmonkey** [comment]
Fix this over on transifex.com

**Comment by Chealer** [comment]
Is there a reason why this ticket is showing as closed?

**Comment by Chealer** [comment]
It turns out this actually affects several messages (and likely several languages). This was introduced by c96724c, a 2019 commit which visibly intended to refactor messages by [avoiding to duplicate "Error" in 3 messages, but only updated the English messages](https://github.com/keepassxreboot/keepassxc-browser/commit/c96724c56afab72d690e1467ea953a9fe679db9b#diff-635b114d9c928c18949d8216d7d022d34009a099f851abce537c4c223af66efaR234-R249).

**Comment by droidmonkey** [comment]
> Is there a reason why this ticket is showing as closed?

I'm not sure how much clearer I can be. I posted exactly what to do in the first issue you made about translations. Stop making more issues about translations. Go to our transifex and fix them directly.

**Comment by Chealer** [comment]
> > Is there a reason why this ticket is showing as closed?
> 
> I'm not sure how much clearer I can be. I posted exactly what to do in the first issue you made about translations.

Nobody asked what should be done. What I asked is why this ticket displays as closed.


> Stop making more issues about translations. Go to our transifex and fix them directly.

I am not "making issues about translations". Stop telling others what you think should (or should not) be done. If you can't answer or help, just wait until someone else does.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/issues/2220#issuecomment-2155223315
