### ISSUE TITLE
Some status messages missing final period

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2224]
In Romance languages and many more, a sentence should be terminated by a full stop (the "." character). I noticed this character missing in the following KeePassXC status messages:

1. [usernameLockedFieldText](https://github.com/search?q=repo%3Akeepassxreboot/keepassxc-browser%20%22usernameLockedFieldText%22&type=code) ("Database is locked")
2. [usernameDisconnectedFieldText](https://github.com/search?q=repo%3Akeepassxreboot/keepassxc-browser%20%22usernameDisconnectedFieldText%22&type=code) ("KeePassXC is disconnected")

By the way, the latter is misleading. It happens when "KeePassXC is not running or is disconnected". Both the message and its formulation could be fixed by rephrasing to:

> Not connected to KeePassXC

This affects KeePassXC-Browser 1.9.0.5.

**Comment by Chealer** [comment]
The above change does not solve the problem in French and other languages, but it does solve for English.

**Comment by varjolintu** [comment]
> The above change does not solve the problem in French and other languages, but it does solve for English.

This is something you solve in Transifex.
