### ISSUE TITLE
Username field KeePassXC icon variants undocumented

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2226]
The extension adds the KeePassXC icon to the right of username fields. Depending on different factors, a grey variant of the icon may be shown instead. As shown in [the _Using the Browser Extension_ section of the User Guide](https://keepassxc.org/docs/KeePassXC_UserGuide#_using_the_browser_extension), some variants include a sub-icon (bottom right), like a lock.

While the meaning of some of these variants is indirectly documented in there, the following variant (a gray icon without a sub-icon), the one I seem to get most often, is not: 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/486141/3a39f21e-4aca-4bee-8281-343ef7ac39a4)
(Note that in this case, the KeePassXC icon is overlapping another icon displayed by the website itself.)

Properly documenting the difference between all of these would greatly help. [According to @varjolintu](https://github.com/keepassxreboot/keepassxc-browser/issues/1814#issuecomment-1367874848):

> Gray icon means your active database is open but no credentials are found for the site, or your database is not connected to KeePassXC.

This seems to contradict [the tooltip](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/_locales/en/messages.json#L213C1-L216C7), but does look basically right in practice. From what I have seen, on sites where the extension displays this variant, it fails to fill in.

## Debug info
KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Windows
Browser: Firefox

**Comment by varjolintu** [comment]
Fixed in https://github.com/keepassxreboot/keepassxc/pull/10875.

**Comment by Chealer** [comment]
Thank you @varjolintu, however this report was not about the browser extension toolbar icons, nor about the added variant.

**Comment by Chealer** [comment]
The "variant" I was getting, i.e. the simple gray icon (without any sub-icon) apparently no longer appears for me. I now use KeePassXC 2.7.10 with extension version 1.9.7, and it seems I now get variant A (the one with the red X sub-icon). I assume that was a fix, but I don't know which version it came from.
