### ISSUE TITLE
macOS/OSX and Firefox. Interacting with "Confirm Access" dialog brings KeePassXC main window to front.

### ISSUE THREAD

**Issue by jtl999** [keepassxreboot/keepassxc-browser#223]
## Expected Behavior
1) Interact with KeePassXC-Browser confirm access dialog should not bring main KeePassXC window to front

## Current Behavior
1) Interacting with the confirm access dialog brings the main KeePassXC window to front

## Steps to Reproduce (for bugs)

1. Have KeePassXC with Firefox browser integration enabled and the KeePassXC browser extension installed
2. Browse to a site login of which KeePassXC has a login for the site.
3. Interact with the confirm access dialog
4. Even clicking on the confirm access dialog will bring KeePassXC to the front

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.1.7
Operating system: OS X 10.11
Browser: Firefox 61.0
Proxy used: NO

Here is the debug info from "About KeePassXC"

```
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: OS X El Capitan (10.11)
CPU architecture: x86_64
Kernel: darwin 15.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey
```

**Comment by varjolintu** [comment]
After PR https://github.com/keepassxreboot/keepassxc/pull/1904 is merged, it's possible to use the same method for confirmation dialogs.

**Comment by varjolintu** [comment]
Just to clarify this old ticket: AFAIK it's not possible to bring just a popup to the front with macOS. You'll have to set the main window active when the popup is on the top as a workaround.

**Comment by droidmonkey** [comment]
That's correct, macos requires the owning window to be in focus to show a modal dialog.

**Comment by varjolintu** [comment]
Nothing we can do there.
