### ISSUE TITLE
Restarting KeepassXC unable to reconnect, `Key exchange was not successful` prompted

### ISSUE THREAD

**Issue by kazutoiris** [keepassxreboot/keepassxc-browser#2232]
## Expected Behavior

When I restart the KeepassXC main program, the browser extension should reconnect properly instead of popping up with `Key exchange was not successful`.

## Current Behavior

Popping up with `Key exchange was not successful`.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/78157415/e03e52ce-7820-45ef-941f-d30f764b1d4b)

## Possible Solution

Disabling and re-enabling the extension will make it work properly again.

## Steps to Reproduce (for bugs)

1. Connect to KeepassXC
2. Terminate and restart the KeepassXC
3. Unable to connect, always receiving `Key exchange was not successful` popup

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.3
Operating system: Win64
Browser: Chrome/Chromium 123.0.0.0

**Comment by varjolintu** [comment]
Fixed with #2234.

**Comment by e-t-l** [comment]
> Fixed with #2234.

When can we expect this update to be released? I've been frequently having the same issue as OP (and have been tearing my hair out over it - until I read the suggestion above to disable/re-enable the extension. That solved it immediately.)

**Comment by varjolintu** [comment]
@e-t-l Soon.
