### ISSUE TITLE
Can´t connect on Fedora 40

### ISSUE THREAD

**Issue by Af0x** [keepassxreboot/keepassxc-browser#2235]
Using version 1.9.0.5 with KeePass 2.7.8 on Fedora 40 testing branch it is currently not possible to connect to the database.

When clicking on the KeePassXC-Browser icon on the top right of Firefox it says
>Checking status...

but nothing happens.

I made sure the Firefox integration was enabled in the KeePassXC settings and successfully connected the database in Chromium on the same system.

**Comment by varjolintu** [comment]
There are multiple threads about similar issues. Please search for them first for a possible solution.

**Comment by varjolintu** [comment]
First things to check is that Firefox is not installed as Flatpak. Also go through the: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by varjolintu** [comment]
That looks like the browser has some problems with localStorage. Is there any difference if you download Linux version manually? https://www.mozilla.org/en-US/firefox/linux/

**Comment by varjolintu** [comment]
Seems there something wrong with the default package of Firefox for Fedora? It has happened before though.

**Comment by varjolintu** [comment]
One other thing to try is to make a new temporary profile to Firefox and see if it helps. The current one could be corrupted.
