### ISSUE TITLE
keepassxc-browser not connecting to my keepassxc

### ISSUE THREAD

**Issue by kingmaj0r** [keepassxreboot/keepassxc-browser#2236]
my keepassxc-browser is not connecting to keepassxc
## Expected Behavior

im trying to get my keepassxc-browser to connect to keepassxc

## Current Behavior

So im trying to setup keepassxc and followed the instructions but my keepassxc-browser is not connecting to my keepassxc
I've installed chrome and keepassxc through flatpak

## Steps to Reproduce (for bugs)

1. installed chrome and keepassxc through flatpak
2. install keepassxc-browser on chrome
3. enable keepassxc browser integration for chrome
4. clicked connect in the connected databases tab

## Debug info

[Error keepass.js:313] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

KeePassXC - unknown
KeePassXC-Browser - 1.9.0.5
Operating system: Linux x86_64 (fedora 39 workstation)
Browser: Chrome/Chromium 125.0.0.0

extra:
KeePassXC - Version 2.7.8
Revision: f6757d3
Distribution: Flatpak

Qt 5.15.10
Debugging mode is disabled.

Operating system: KDE Flatpak runtime
CPU architecture: x86_64
Kernel: linux 6.7.10-200.fc39.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Secret Service Integration

Cryptographic libraries:
- Botan 3.3.0

**Comment by varjolintu** [comment]
Chrome as Flatpak is not supported.
