### ISSUE TITLE
KeepassXC doesn't connect with browser

### ISSUE THREAD

**Issue by Mallo321123** [keepassxreboot/keepassxc-browser#2237]
## Expected Behavior

Keepasscx Browser connects to Keepassxc.

## Current Behavior
After trying to connect, Keepassxc browser responses with: "key exchange not possible"

Logs with: sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass

    [pid 260684] openat(AT_FDCWD, "/home/**/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json",   O_RDONLY <unfinished ...>
    [pid 260684] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
    [pid 260684] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
    [pid 260684] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
    [pid 260684] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
    [pid 260684] newfstatat(AT_FDCWD, "/usr/bin/keepassxc-proxy",  <unfinished ...>
    [pid 269257] execve("/usr/bin/keepassxc-proxy", ["/usr/bin/keepassxc-proxy", "/home/**/.mozilla/native-mess"..., "keepassxc-browser@keepassxc.org"], 0x71ad41f05400 /* 63 vars */ <unfinished ...>

## Steps to Reproduce (for bugs)

1. Try to connect Keepassxc Browser with KeepassXC

## Debug info

KeePassXC - 2.6.6
KeePassXC-Browser - 1.9.0.5
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
First, update your KeePassXC.

- Distro?
- How Firefox is installed (Snap? Flatpak? .deb/rpm?)

**Comment by Mallo321123** [comment]
Sorry, already Fixed it, Appamour was wheard and neded two restarts instead of one
