### ISSUE TITLE
Manually link an URL to an entry

### ISSUE THREAD

**Issue by felixschndr** [keepassxreboot/keepassxc-browser#2238]
Is it possible to manually link one or more URLs to an entry?
Example:

- At work we use active directory to login into different websites
- I have an entry called `active directory`. Currently it does not have any URL associated with it
- It like to use the entry `active directory` for URL `first-site.mycompany.com` `second-site.mycompany.com` and `third-site.mycompany.com`

## Expected Behavior

Add an attribute to an entry that describes its `URL`s.
Example: The KeepassXC app on android saves this like this:
- `KP2A_URL_1`: `myfirstsite.com`
- `KP2A_URL_2`: `mysecondsite.com`

## Debug info

KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
This is already supported in KeePassXC. When you edit and entry, there's a Browser Integration tab that let's you define additional URL's.

**Comment by felixschndr** [comment]
Sure, I don't know how I was able to overlock this... Thank you :)
