### ISSUE TITLE
Options: Unclear Connect button in Connected Databases tab

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2241]
The extension's options contain a _Connected Databases_ tab which ends with a button. This button has no tooltip, _Connect_ as only label, offers no feedback and is part of an undocumented tab.

## Possible Solution
Implementing at least one of the following would mitigate/solve:

1. Labelling clearly or adding a tooltip
2. Documenting options
3. Adding feedback

## Debug info
KeePassXC-Browser - 1.9.0.5
Operating system: Microsoft Windows
Browser: Mozilla Firefox

**Comment by varjolintu** [comment]
The feedback for this is added to Protocol V2 draft that also listens to the current database state.

**Comment by Chealer** [comment]
4b55cc958385edf268ee9000650d93f21e943bf1 attempts to address this [by defining a `connectButtonTitle` label](https://github.com/keepassxreboot/keepassxc-browser/pull/2244/commits/4b55cc958385edf268ee9000650d93f21e943bf1#diff-635b114d9c928c18949d8216d7d022d34009a099f851abce537c4c223af66efaR14-R17):

> Connect current active database to KeePassXC-Browser.

Unfortunately, while this may clarify a bit, this is far from solving the issue. What "current active database" means is very unclear.

Note that such labels are not terminated with periods.

**Comment by varjolintu** [comment]
"Current active database" cannot be any more clear than this. It's the active database tab in KeePassXC.

I decided that those labels are terminated with periods, so those would be possible to use elsewhere later. I'm not going to make changes just because some user is not happy.
