### ISSUE TITLE
Confuses a user identifier input field with an OTP

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2243]
## Expected Behavior
On Desjardins's customer login page, which has a standard user id + password form, KeePassXC should:
1. offer to fill the fields with the saved credentials
2. not offer to fill a TOTP

## Current Behavior
The extension adds 2 icons, as the following screenshot shows: 
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/486141/1a8a2fd7-f639-4373-b716-e0fd07724696)

1. The KeePassXC icon is shown in the password field (circled in yellow).
2. A TOTP icon is added in the first field (user identifier), as shown in the red circle, which is broken.

## Steps to Reproduce (for bugs)
1. Browse to [Desjardins's website](https://www.desjardins.com) (and deal with the usual cookie/region crap)
2. Click "Se connecter à AccèsD"

## Debug info
KeePassXC-Browser - 1.9.0.5
Operating system: Microsoft Windows 11
Browser: Firefox

**Comment by varjolintu** [comment]
This happens because they use strings in the input field name/id that identifies it as a 2FA field. We cannot change those, so your option is to use Custom Login Field and define the fields manually.

**Comment by Chealer** [comment]
> This happens because they use strings in the input field name/id that identifies it as a 2FA field.

What? Which strings are you referring to?

> We cannot change those, so your option is to use Custom Login Field and define the fields manually.

Thanks anyway, but that doesn't scale.

**Comment by varjolintu** [comment]
> > This happens because they use strings in the input field name/id that identifies it as a 2FA field.
> 
> What? Which strings are you referring to?

As I said, the `id` and `name` of the input field is `codeUtilisateur` which does not tell the extension this is a username field, but it is detected as a 2FA field because `code` is quite common identification string used in these fields.

> 
> > We cannot change those, so your option is to use Custom Login Field and define the fields manually.
> 
> Thanks anyway, but that doesn't scale.

That is your only solution here because we will not remove the identification `code` from the 2FA field implementation.

**Comment by Chealer** [comment]
> > > This happens because they use strings in the input field name/id that identifies it as a 2FA field.
> > 
> > 
> > What? Which strings are you referring to?
> 
> As I said, the `id` and `name` of the input field is `codeUtilisateur` which does not tell the extension this is a username field

Of course not... neither the `id` nor the `name` attributes are designed to tell that to KeePassXC-Browser (or any browser). And even if they were, this field wouldn't do that, since it's not designed for usernames (properly speaking).

> but it is detected as a 2FA field because `code` is quite common identification string used in these fields.

I'm not sure I understand... what do you mean by "a 2FA field"?

> > > We cannot change those, so your option is to use Custom Login Field and define the fields manually.
> > 
> > 
> > Thanks anyway, but that doesn't scale.
> 
> That is your only solution here because we will not remove the identification `code` from the 2FA field implementation.

What you're describing is called a _workaround_, not a solution.

**Comment by varjolintu** [comment]
> Of course not... neither the `id` nor the `name` attributes are designed to tell that to KeePassXC-Browser (or any browser). And even if they were, this field wouldn't do that, since it's not designed for usernames (properly speaking).

That's the only way to identify fields because pages don't like to use standards. In this case, the field is designed to be a username field, and even the page title says so.

> I'm not sure I understand... what do you mean by "a 2FA field"?

The input field properties are defined in a way it looks more like a 2FA field than username field.

> What you're describing is called a _workaround_, not a solution.

This is because there's no solution, only a workaround, which works with minimal effort.

**Comment by droidmonkey** [comment]
This is the web pages fault for not choosing sensible attributes and names for their fields. We have plenty of _solutions_ already in place, but they are worthless if the website itself is coded to be obscure. Discussion is over, the solution is a workaround, have a great day.
