### ISSUE TITLE
Use "Tags" field of password database when matching credentials?

### ISSUE THREAD

**Issue by chconnor** [keepassxreboot/keepassxc-browser#2245]
It seems that keepassxc-browser does not use the "tags" from the password database when searching for matching credentials, is that correct?

I used to use the keepass2 linux client, and have recently switched to keepassxc, which seems to read my existing (and large) database without issue.

But the browser plugin doesn't match any of the websites because I don't have the "URL" field populated for anything. Instead, I have, for example "GitHub" in the tags. With keepass2 this would work fine with the autotype feature because "GitHub" would match the window/tab name.

With keepassxc I have to go to every website, see that it fails to find the credentials, then add the URL to the DB, save, reload the page, and then submit. Not the end of the world, but it seemed strange to me that it doesn't use the tags when trying to decide which credentials might match.

I looked but didn't find an option for the keepassxc-browser plugin to use the tag field. Am I missing something? If not, it seems like it would be a useful feature request.

(Or maybe I'm misusing the tag field in the first place -- let me know if that's the case.)

Thanks for the great software!

**Comment by droidmonkey** [comment]
Hello, welcome! I am intrigued by your user of tags in this way, that is a first. The bad news is you will have to populate your url fields to make use of the browser extension, matching entries is done only with the url. There are security and data uniformity reasons for that. 

Tags are not meant for features to find an entry. They are meant to be meta groups that are dynamically invoked. We have a panel in the bottom left side of the application that let's up quickly invoke the tag search to show all entries that share 1 or more tags. 

Autotype in keepass did not use tags either. Autotype matches the title of the entry with the window title by default.

**Comment by chconnor** [comment]
I appreciate the response, thanks, and thanks for the explanation re: tags.

keepass2 does (optionally) use tags for matching (Options -> Advanced -> Auto-Type -> "An entry matches if one of its tags is contained in the target window title", not enabled by default), but I understand what you mean.

Still, if there is a notion in keepassxc of optionally making an "educated best guess" about which credentials might apply, it might be nice to have this as an option. That said, it seems like the KPXC philosophy is to be very careful about not offering false positives, which I respect.

**Comment by omnicortex** [comment]
I have a different use case. I have multiple profiles in Firefox. The credentials in KeePassXC are tagged per profile. So depending on which profile is in use by Firefox I would need KeePassXC to filter the credentials based on the tags.

**Comment by droidmonkey** [comment]
Use the tag search filter
