### ISSUE TITLE
Connect to specific database by name

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [keepassxreboot/keepassxc-browser#2247]
## Expected Behavior
Like vanilla KeePass with the KeePassNatMsg addon, I'd like to be able to specify the name of the database I want the KeePassXC-Browser extension to connect to. I don't want it to just try and connect to the currently selected database.

I have my personal database where I store my browser extension connections, and I have a shared work database that I am able to access through AutoOpen and searching using all available databases. However I don't want the browser extension to connect through the work database. It's pointless to make yet another account-and-browser-specific connection through the extension if I already have access to all database entries through an existing connection on my personal database.

## Current Behavior
The extension attempts a connection to whatever database in currently selected in keepassxc. All databases can be open, but it's only connecting with the actively selected database.

## Possible Solution
Either provide a text field that allows us to set the name of the database by typing it in, or provide a dropdown list of the names of the already connected databases.

## Debug info
KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.0.5
Operating system: Win
Browser: Edge

**Comment by droidmonkey** [comment]
You are not thinking about this correctly, you don't connect "through" a database, it is an authorization to use that database with the extension. If you want to use your work database then you need to establish a connection to it independent of your personal database. If you want to return credentials from all unlocked and connected databases, enable the "Search credentials in all open databases" setting.

There is an issue where an unconnected database will prevent access to a valid connected database, that is catalogued here: https://github.com/keepassxreboot/keepassxc/issues/5238
