### ISSUE TITLE
Entry selection hidden by update warning

### ISSUE THREAD

**Issue by BrutuZ** [keepassxreboot/keepassxc-browser#2253]
## Expected Behavior

Entry selection buttons should be displayed

## Current Behavior

Entry selection is impossible. Window has a fixed size and no overflow, with the added space of the update suggestion the entries get hidden. Tab navigation doesn't include them either
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/7104931/5f1ffef2-5f7c-4d0c-b079-e8a5612fd165)

## Possible Solution

1. Enable overflow in the window to let it scroll if necessary.
2. Expand window to account for the update warning.

## Steps to Reproduce (for bugs)

1. Have multiple entries for a site
2. Have an update pending for KeepassXC
3. Try to fill the credentials on the second entry for site on `1`

## Debug info

KeePassXC - 2.7.8 (latest available as of writing: 2.7.9)
KeePassXC-Browser - 1.9.0.5
Operating system: Windows 10
Browser: Firefox 115.12.0esr (64-bit)

**Comment by varjolintu** [comment]
I cannot reproduce this. Does this happen for every site? Does refreshing the page help?

**Comment by BrutuZ** [comment]
It happened with GitHub.
The entry buttons did show up once after juggling around KPXC versions (updated to 2.7.9, wouldn't launch, rolled back to 2.7.8), which involved full browser restarts.

I'll re-check if it happens again tomorrow

**Comment by BrutuZ** [comment]
It worked just fine even after a long browser session.
I wonder if it was caused by something corrupted in my KPXC files and the reinstall from updating>downgrading somehow fixed it.
