### ISSUE TITLE
There is no drop down menu from keepassxc-browser icons in username/password field when I clicked icon

### ISSUE THREAD

**Issue by dust2k** [keepassxreboot/keepassxc-browser#2260]
I have multiple google accounts and they all use "https://accounts.google.com/v3/signin/challenge" as Keepass entry item's URL, everytime when I get to the second screen to input password, I normally click the icon in password field right side and then there will be a menu popup, so I select the one I want and then the correct password auto fill in, but this morning I try to click the icon in password field and there is nothing happened...

## Expected Behavior
when I clicked password field icon, there should be menu with all my acocunts popup so I can select one.

## Current Behavior
clicked the icon, nothing happened, move the mouse on top of icon, a message popup said "no credentials to fill"

## Possible Solution
when i click the extension icon, then click button "redetect login fields", there is an error message popup  in console windows of developer tools, the message is:

keepassxc-browser.js:419 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at sortLoginItemBy (keepassxc-browser.js:419:36)
    at keepassxc-browser.js:452:35
    at Array.sort (<anonymous>)
    at kpxc.initLoginPopup (keepassxc-browser.js:452:20)
    at kpxc.prepareCredentials (keepassxc-browser.js:509:10)
    at kpxc.retrieveCredentialsCallback (keepassxc-browser.js:650:20)
    at kpxc.retrieveCredentials (keepassxc-browser.js:639:20)
    at async kpxc.initCredentialFields (keepassxc-browser.js:383:9)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC -  Keepass 2.57
KeePassXC-Browser -  1.91
Operating system: Windows 11 
Browser: Chrome 126.0.6478.127 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
The TypeError is something I'm concerned, and that should be checked. Try setting the entry URL's to `https://accounts.google.com` instead and see if those are found again.

**Comment by varjolintu** [comment]
Could you give some more details? I'm pretty sure why the error happens but I cannot reproduce it myself.
- Are you using the new compact mode for Autocomplete Menu?
- Is the "display the group name" setting enabled?
- Is your "Sort matching credentials by" setting set to "Group and title"?

**Comment by dust2k** [comment]
> The TypeError is something I'm concerned, and that should be checked. Try setting the entry URL's to `https://accounts.google.com` instead and see if those are found again.

tried to update all URL to "https://accounts.google.com" and the problem is same... I don't have problem yesterday, it's only happened today, I also tried to use different Google profile..but the problem is same, seems this error blocked extension to read multiple entries ...

**Comment by dust2k** [comment]
> Could you give some more details? I'm pretty sure why the error happens but I cannot reproduce it myself.
> 
> * Are you using the new compact mode for Autocomplete Menu?

No, I just tried these setting after I got this problem, and no help at all.

> * Is the "display the group name" setting enabled?

Yes.

> * Is your "Sort matching credentials by" setting set to "Group and title"?

Yes.

**Comment by varjolintu** [comment]
I think this error should only happen if for some reason your entry does not have a group defined at all, which shouldn't be possible. If you have the skills to debug content scripts, it would be helpful to confirm this setting a breakpoint to `keepassxc-browser.js:452` and see what the `loginItems` Array contains.

**Comment by dust2k** [comment]
Same database and extension from Firefox and Edge are all working fine like yesterday's Chrome....

**Comment by varjolintu** [comment]
> Same database and extension from Firefox and Edge are all working fine like yesterday's Chrome....

I bet the extension has updated to 1.9.1 only with Chrome.

**Comment by dust2k** [comment]
> > Same database and extension from Firefox and Edge are all working fine like yesterday's Chrome....
> 
> I bet the extension has updated to 1.9.1 only with Chrome.

Yes, is 1.91 a release with bug? how can I go back to old version? or lock on some old versions??

I have debug both scripts in Edge and Chrome, group field is alway empty in both environment, so I leave this to you guys.

**Comment by varjolintu** [comment]
> > > Same database and extension from Firefox and Edge are all working fine like yesterday's Chrome....
> > 
> > 
> > I bet the extension has updated to 1.9.1 only with Chrome.
> 
> Yes, is 1.91 a release with bug? how can I go back to old version? or lock on some old versions??
> 
> I have debug both scripts in Edge and Chrome, group field is alway empty in both environment, so I leave this to you guys.

Ok. Thank you. Just to make sure, is it empty or `undefined`? I'll make some extra checks for the function and around it. Maybe it will solve the issue.

**Comment by dust2k** [comment]
> > > > Same database and extension from Firefox and Edge are all working fine like yesterday's Chrome....
> > > 
> > > 
> > > I bet the extension has updated to 1.9.1 only with Chrome.
> > 
> > 
> > Yes, is 1.91 a release with bug? how can I go back to old version? or lock on some old versions??
> > I have debug both scripts in Edge and Chrome, group field is alway empty in both environment, so I leave this to you guys.
> 
> Ok. Thank you. Just to make sure, is it empty or `undefined`? I'll make some extra checks for the function and around it. Maybe it will solve the issue.

Yes, it's empty or undefined.

**Comment by pushcom** [comment]
I have the same problem with Vivaldi. Your extension with version 1.9.0.5 works as exptected, 1.9.1 does not.

I add some errors from the extension:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

`content/keepassxc-browser.js:419 (Anonyme Funktion)`

Firefox works with 1.9.1 without problems.

One of the urls that are not working:
https://sso.geschaeftskunden.dhl.de

Thanks and kind regards

**Comment by varjolintu** [comment]
If you can, please test the fix: https://github.com/keepassxreboot/keepassxc-browser/pull/2262

I'm interested why the group is not defined at all in your entries. In what group your entries are? Do they have a title, a group name?

**Comment by pushcom** [comment]
Hi!

I've tested the fix #2262 (replace keepassxc-browser.js) and it seems to 
work again.

Thanks a lot for your work!

Regards

Konrad


------ Originalnachricht ------
Von "Sami Vänttinen" ***@***.***>
An "keepassxreboot/keepassxc-browser" 
***@***.***>
Cc "pushcom" ***@***.***>; "Comment" 
***@***.***>
Datum 04.07.2024 13:16:59
Betreff Re: [keepassxreboot/keepassxc-browser] There is no drop down 
menu from keepassxc-browser icons in username/password field when I 
clicked icon (Issue #2260)

**Comment by chotaire** [comment]
For KeepassNatMsg users who can't wait until v1.9.2, download the develop branch. Then do this: https://github.com/keepassxreboot/keepassxc-browser/pull/2262#issuecomment-2210997184

**Comment by wadabum** [comment]
Thanks for yanking this back into 1.9.1.1  
ChromeStore is updated and everything seems to be working again.
