### ISSUE TITLE
firefox plugin still not updated to 1.9.1

### ISSUE THREAD

**Issue by piyushgarg** [keepassxreboot/keepassxc-browser#2264]
Firefox plugin is still at 1.9.0.5 [versions](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/versions/)

## Expected Behavior
it should show latest version 1.9.1.0

## Current Behavior
showing older version <= 1.9.0.5
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/246124/74469579-ef3d-4395-93b7-f813cbd3baa5)

## Debug info

KeePassXC - {2.7.9}
KeePassXC-Browser - {1.9.0.5}
Operating system: Linux
Browser: LibreWolf 127.0.2-2

**Comment by varjolintu** [comment]
This is because of Mozilla's review queue. It's the same with Chrome and Edge. Each store has their own policy how to do reviews, and how long it takes. We cannot affect to this. 1.9.1 was uploaded to every store at the same time right after GitHub release.
