### ISSUE TITLE
Unable to auto fill on some sites in Firefox

### ISSUE THREAD

**Issue by d4em0nsp4wn** [keepassxreboot/keepassxc-browser#2266]
## Expected Behavior

Show list of available credentials and/or auto populate the login fields when I right click and choose "Fill in Username and Password" 

## Current Behavior

Nothing happens. 

## Steps to Reproduce (for bugs)

1. Pull up login page for a website
2. Click on the Username field, right click and choose Keepass-XC-Brower
3. Click Fill Username and Password
4. Expect the fields to be filled in.

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1
Operating system: Win64
Browser: Mozilla Firefox 127.0
[Debug keepassxc-browser.js:230] KeePassXC-Browser - Input fields found: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ input#LoginUsername, input#LoginPassword
 ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug ] KeePassXC-Browser - Login field combinations identified: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ {…} ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug fields.js:167] KeePassXC-Browser - Input fields found: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ input#LoginUsername, input#LoginPassword
 ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug ] KeePassXC-Browser - Login field combinations identified: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ {…} ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Error ] KeePassXC-Browser - initContentScript error: TypeError: a.group is undefined [global.js:132:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
TypeError: a.group is undefined
[keepassxc-browser.js:419:28](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/content/keepassxc-browser.js)
[Debug keepassxc-browser.js:230] KeePassXC-Browser - Input fields found: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ input#LoginUsername, input#LoginPassword
 ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug ] KeePassXC-Browser - Login field combinations identified: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ {…} ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug fields.js:167] KeePassXC-Browser - Input fields found: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ input#LoginUsername, input#LoginPassword
 ]
[global.js:127:17](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
[Debug ] KeePassXC-Browser - Login field combinations identified: [global.js:124:13](moz-extension://ab5a7036-f306-4bfe-bb2c-cc626a54b99a/common/global.js)
Array [ {…} ]

- Did test other browers and this issue appears to only be isolated to Firefox.

**Comment by varjolintu** [comment]
Can you give an example site where this happens, and what URL your entry is using for that?

**Comment by d4em0nsp4wn** [comment]
Most recent URL is,
https://www.zoom.us/signin#/login

**Comment by droidmonkey** [comment]
worked instantly for me
