### ISSUE TITLE
Without proxy, extension never stops keepassxc instance that is running with no gui windows

### ISSUE THREAD

**Issue by sheavner** [keepassxreboot/keepassxc-browser#227]
## Expected Behavior
After I close a keepass.exe instance that was connected to the plugin, I expect to be able to relaunch keepass from the start menu.  I also expect that newly launched keepass to be able to connect to the plugin, but I might understand if it needed to be launched in a special way.

## Current Behavior
After closing keepass, a keepass.exe process keeps running.   This process prevents starting a new GUI version of keepass.

## Possible Solution
* Abort keepass when closing GUI window
* Add a task tray icon or taskbar icon i could use to re-open the gui to a running keepass instance.

## Steps to Reproduce (for bugs)
1. Uncheck "use a proxy" in the browser integration setup.
2. Stop chrome and keepass, from the task manager if necessary.
3. Launch chrome.  Observe a keepass instance is started.
4. Close keepass prior to logging in with the X button in the upper right corner.
5. Attempt to launch keepass from the start menu.   It won't launch.
6. Observe keepass is still running in task manager.
7. Stop chrome.
8. Observe keepass is still running in the task manager.
9. Attempt to launch keepass from the start menu.   It won't launch.
10. Kill keepass from the task manager.
11. Launch keepass from the start menu.   Now you can use the GUI to access and manage passwords.

## Debug info
KeePassXC-Browser Version: 1.1.7
KeePassXC Version: 2.3.3
Operating system: Win10-64bit
Browser: Chrome
Proxy used: NO

##Chrome about: 
Google Chrome | 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)
Revision | a337fbf3c2ab8ebc6b64b0bfdce73a20e2e2252b-refs/branch-heads/3396@{#790}
OS | Windows
JavaScript | V8 6.7.288.46
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

**Comment by varjolintu** [comment]
This is a known issue with Chromium based browsers on Windows. Termination of native messaging host (in this case it means either keepassxc.exe or keepassxc-proxy.exe) is not working properly, but you need a special handling for it. I have already a fix coming for this for keepassxc-proxy but haven't tested this with just KeePassXC, without the proxy.

**Comment by varjolintu** [comment]
Fixing this to the KeePassXC side is slightly more difficult and will take some time.

**Comment by varjolintu** [comment]
The listener for `stdin` will be removed in the next version of KeePassXC, so closing this issue.
