### ISSUE TITLE
Show username in compact mode

### ISSUE THREAD

**Issue by iarp** [keepassxreboot/keepassxc-browser#2272]
Can we please set compact mode back to how it was originally? Reading over PR #2119 i understand that they claim its cramped but now this new layout doesn't even display the basic information about who you're logging in as. I don't use titles, username is all i care for and now thats hidden while compact or I'm stuck using a dropdown box that's 3 times larger than it needs to be.

That or drop the group and add the username in its place.

Additionally the ability to change the font style back. This is rather soft around the edges and I find it harder to read.

## Debug info

 KeePassXC-Browser Version: 1.9.1
KeePassXC Version: 2.7.9 
Operating system: Win
Browser: Firefox

**Comment by iarp** [comment]
I have closed this because i neglected to read the comments on the PR and there seems to be a lot of people happy with the redesign. So i'm choosing to go back a version and prevent my browser from updating beyond [1.9.0.5](https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.9.0.5)

**Comment by varjolintu** [comment]
Try enabling the new Compact Mode from the settings, and disable Display Groups setting from the Advanced section. Then it should only show username and/or title.

**Comment by iarp** [comment]
When i first started firefox this morning and saw this change all of my dropdown options in compact mode were left aligned title and right aligned group. The username was not displayed. I've disabled group in advanced and can now see usernames thanks.

I'm thinking maybe I can use tampermonkey to alter the font styling.
