### ISSUE TITLE
The password list is too long when selecting a password in the Edge Browser

### ISSUE THREAD

**Issue by icegrassdream** [keepassxreboot/keepassxc-browser#2273]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )
The password list is too long when selecting a password in the Edge Browser.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Problems occurring during normal use, no special operation.
2. 
3. 

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
![Snipaste_2024-07-08_11-33-04](https://github.com/keepassxreboot/keepassxc/assets/162453861/00cb61b3-a4b3-4eff-917f-088cb00186b4)

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
![Snipaste_2024-07-08_11-27-34](https://github.com/keepassxreboot/keepassxc/assets/162453861/4e7dd4b0-0459-432b-8e0f-7ed1ca8b2c6a)

## Context
[NOTE]: # ( Give us any additional information you may have. )
When logging in at the following link
https://ec.iot.10086.cn/

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 版本 2.7.6
Revision: dd21def

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Desktop Env: 
Windowing System:

**Comment by varjolintu** [comment]
You can scroll it with your mouse, or use a keyboard to navigate up and down.

**Comment by icegrassdream** [comment]
I mean the password list is too long horizontally, not vertically. The vertical list is too much I know can mouse scroll to select it.
![Snipaste_2024-07-08_11-27-34](https://github.com/keepassxreboot/keepassxc-browser/assets/162453861/98b6f77a-e0bd-4aaf-9bf0-8fdba2a6c91d)
![Snipaste_2024-07-08_13-35-18](https://github.com/keepassxreboot/keepassxc-browser/assets/162453861/7e23e91e-7218-4a31-8d91-fa8b71bf0c76)
