### ISSUE TITLE
no available entrys on insecure http-sites

### ISSUE THREAD

**Issue by Bond246** [keepassxreboot/keepassxc-browser#2275]
Hello,

since updating today to the latest veresion of this beautiful firefox extentison i can't use it anymore on insecure local selfhosted web-systems.

## Expected Behavior
I connect to my selfhosted stuff via hostname of the application/server including the app-based network-port.
Normally firefox warns me not to input credentials on insecure http-sites. If i make another click into the user-/password-field the keepasscx suggestions are listed. Then i can select one of these and can login.

## Current Behavior
Actually nothing is display. I see the windows-notification that keepassxc browser is requesting for some accounts from my database but no suggestions in the plugin are listed.

If i test it in edge, everything is fine but there is no insecure http-page warning like in firefox.

## Steps to Reproduce (for bugs)

1. open a insecure page in firefox with its hostname (not ip-address)
2. wait for keepassxc browser to present some suggested logins
3. no list is presented

## Debug info

KeePass v2.57 with KeePassNatMsg Plugin 2.0.17.0
KeePassXC - ---
KeePassXC-Browser - 1.9.1
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
You'll have to wait for the latest 1.9.1.1 version. KeePassNatMsg plugin has an error where no group information is passed to the extension at all. This caused a bug on our side that doesn't affect KeePassXC. But, it's already fixed.
