### ISSUE TITLE
Unable to Connect To Database After Reinstalling Firefox Extension

### ISSUE THREAD

**Issue by moxSedai** [keepassxreboot/keepassxc-browser#2276]
I reinstalled the extension due to some issues with changing Linux Distros from Pop OS to Kubuntu, and the extension does not seem to even understand that I have not previously connected it to a database.

## Expected Behavior
Opening Extension prompts me to select a database to connect to

## Current Behavior
Extension tries to open an extension that does not exist.

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/41652960/50decfbf-41fe-4b36-b83b-0d38e420736f)
There should be a "connect" button rather than a "reload" button

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/41652960/ebf6fd60-e2cc-484c-8faf-809e259ccd26)
Clicking the button should do something.   It does nothing.  Not even any console output.

## Debug info

KeePassXC - 2.4.7+dfsg.1-2
KeePassXC-Browser - 1.9.1
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
> due to some issues

What were those issues and why did they prompt you to reinstall the extension?

> KeePassXC - 2.4.7+dfsg.1-2

This is a VERY old version of keepassxc 

You also did not include how Firefox is installed, it matters. Did you read the troubleshooting guide? 

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

Closing until these tasks are completed.

**Comment by droidmonkey** [comment]
> due to some issues

What were those issues and why did they prompt you to reinstall the extension?

> KeePassXC - 2.4.7+dfsg.1-2

This is a VERY old version of keepassxc 

You also did not include how Firefox is installed, it matters. Did you read the troubleshooting guide? 

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

Closing until these tasks are completed.

**Comment by droidmonkey** [comment]
The strace doesn't have anything to do with the browser extension functionality, unfortunately.

**Comment by moxSedai** [comment]
I have no usr.bin.firefox file in the apparmor.d directory

**Comment by varjolintu** [comment]
You must give more information according to the Troubleshooting Guide:
- Is the script file where it should be?
- Is the script file pointing to a correct binary?
- Does it work when KeePassXC is installed via PPA?
