### ISSUE TITLE
PayPal username field not filled on `https://www.paypal.com/webapps/hermes`

### ISSUE THREAD

**Issue by Drachenkaetzchen** [keepassxreboot/keepassxc-browser#2277]
## Expected Behavior
The username should be filled on `https://www.paypal.com/webapps/hermes?intent=checkout`.

## Current Behavior
No KeepassXC-browser icon next to the username input box, also no dropdown when clicking on the field. On some PayPal links it works, but not on the one listed above.

Oddly enough, when entering the username manually, the password field on the next page is auto-filled and has full KeepassXC-browser functionality.

The xpath to the input element is `//*[@id="email"]`, the CSS selector is `#email`, the CSS path is:

```
html.desktop.js body.desktop div#main.main section#login.login div.corral div#content.contentContainer.activeContent.contentContainerBordered form.proceed.maskable div#splitEmail.splitEmail div#splitEmailSection.splitPhoneSection.splitEmailSection.adjustSection div#login_emaildiv.textInput div.fieldWrapper input#email.hasHelp.validate.validateEmpty
``` 

![image](https://github.com/keepassxreboot/keepassxc-browser/assets/162974/d96250d2-a6cf-4b20-9054-5f32e2454960)

## Steps to Reproduce (for bugs)
1. Go to mouser.com
2. Try to buy a product via PayPal
3. Get redirected to the PayPal website

## Debug info
KeePassXC - 2.7.8
KeePassXC-Browser - 1.9.1
Operating system: Win64
Browser: Mozilla Firefox 127.0

**Comment by varjolintu** [comment]
Did you enable _Username-only Detection_ for the site?

**Comment by Drachenkaetzchen** [comment]
No, I did not, I wasn't aware until now that this exists. Thank you, I'll try it, and re-open if the issue persists.
