### ISSUE TITLE
Auto-fill has stopped working for some sites

### ISSUE THREAD

**Issue by fboender** [keepassxreboot/keepassxc-browser#2278]
## Expected Behavior

For auto-fill to fill in account details on all sites it worked on previously.

## Current Behavior

Since a few days auto-fill (by clicking on the green icon in a form) no longer works for some sites on which it has always worked before. Filling with keybindings (alt-shift-u) also doesn't work anymore. Neither does right-clicking and selecting "Fill Username And Password" n the KeepassXC-browser context menu.

For example, auto-fill *does* works on:

* https://gitlab.com/users/sign_in
* https://github.com/login

But it *no longer* works on:

* https://gitlab.flusso.nl/users/sign_in
* https://login.flusso.nl

Note that this problem already started before I upgraded to Firefox v128, so I don't believe that to be the cause.

In the browser console, I see the following error on sites that no longer work, when I load the site for the first time:

```
[Error ] KeePassXC-Browser - initContentScript error: TypeError: a.group is undefined global.js:132:13
TypeError: a.group is undefined keepassxc-browser.js:419:28
```

I don't see the same error on sites that do work. Clicking the green Auto-fill button does not produce any additional messages in the console.

Things I've tried to remedy this problem:

* Restart KeepassXC
* Uninstall and reinstall KeepassXC-browser extension
* Disconnecting and reconnecting the connected Keepass database
* Manually create a new password entry in the "Root" folder in keepassXC for a failing site. On reloading the site, Keepass asks whether I want to give permission to fill in the account information, which I allow.
* Compared a few entries that do work with ones that don't work to see if any patterns emerge, but to no avail.
* Created a clean Firefox profile, installed keepassxc-browser in it as the only extension and connected to the database. Exact same behaviour.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

Not really relevant I think? But happy to provide any additional information needed.

## Debug info

Console output when loading a site that no longer works:

```
[Error ] KeePassXC-Browser - initContentScript error: TypeError: a.group is undefined global.js:132:13
TypeError: a.group is undefined keepassxc-browser.js:419:28
```

KeePassXC - 2.4.3 (from Ubuntu 20.04 package)
KeePassXC-Browser - 1.9.1
Operating system: Linux x86_64 (Ubuntu 20.04.6 LTS)
Browser: Mozilla Firefox 128.0

**Comment by fboender** [comment]
I just created an entirely new Keepass database, and added one entry for a failing site to it. Closed the main database, connected KeepassXC-browser to the clean database and now it works. I get the permission dialog, allow access and click the auto-fill icon, and it properly fills in the username and password.

This might suggest there is something corrupt with my main database or something, but I haven't really done anything weird with it. It just stopped working a few days ago.

**Comment by fboender** [comment]
Apparently this was a duplicate of https://github.com/keepassxreboot/keepassxc-browser/pull/2262, I just hadn't received the v1.9.1.1 update yet.

**Comment by varjolintu** [comment]
Btw, I suggest updating KeePassXC to at least version 2.6.x.
