### ISSUE TITLE
Other sites KeepassXC extension can't autofill the login form

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc-browser#228]
From time to time I encounter sites that the extension is not able to autofill the login forms, either using Chromium (on Linux) or Firefox: in this issue I will list some of them I've encountered lately. If that is of any help, I can split this issue in separate issues.

Now, it looks to my naive eye that you're playing cat and mouse here, fighting a moving target; although I do wholeheartely appreciate the efforts and prompt bugfixing :+1:  I wonder if there is a way to test against regressions and avoid fixing on a per case basis. As an example, could any BDD suite be useful for testing?

## Steps to Reproduce (for bugs)
Happen on both either Chromium 66.0.3359.181 and Firefox 62b
* www.xda-developers.com: username field correctly suggested but form is not correctly filled in, therefore login fails
* accounts.google.com: used to work ([this](https://github.com/keepassxreboot/keepassxc-browser/issues/118) was fixed), but now - when multiple login options are available - none is suggested. Must fill username manually, next step choose from the context menu "fill password", next step "fill TOTP".
* www.instagram.com: doens't fill neither user nor pass

## Debug info
KeePassXC-Browser Version: 1.1.7
KeePassXC Version: 2.3.3 
Operating system: Linux
Browser: Chrome+Firefox
Proxy used: YES

**Comment by varjolintu** [comment]
I have no problems filling instagram.com. Are you sure your entry has the correct URL `https://www.instagram.com/accounts/login/`?

For accounts.google.com the next release will allow you to whitelist pages with single username field. It needs some special handling. So probably the issue will be fixed then.

xda-developers.com clearly has an error detecting the fields. I'll look into it.

**Comment by apiraino** [comment]
> I have no problems filling instagram.com. Are you sure your entry has the correct URL https://www.instagram.com/accounts/login/?

Indeed. The funny thing is that if you reach that page from `https://www.instagram.com` it doesn't work anymore.

**Comment by varjolintu** [comment]
@apiraino Yes I saw that too. Trying to figure out a fix.

**Comment by varjolintu** [comment]
This happens because the front page has also a username and a password field. The fill happens already in the front page and that's why it won't happen again.

**Comment by apiraino** [comment]
ok, thanks for investigating. So, is this a sort of unintended behaviour that should be fixed or better to leave it like that (because just one peculiar case or other reason)?

**Comment by varjolintu** [comment]
It's indended behaviour that after an automatic fill it is not done second time. For these kind of pages you'd have to make on option to enable automatic filling more than once. Easier solution for this is just use the login page, not go there via the front page.

**Comment by NN---** [comment]
Is there any hacky option to fill password in http://accounts.google.com/ right now ?
Thanx.

**Comment by varjolintu** [comment]
@NN--- Yes. Go to extension Settings from the popup icon. Then go to Site Preferences tab and add a new site manually: `https://accounts.google.com/*`. Select `Enable all features` from the dropdown menu and enable `Username-Only Detection` checkbox. After that everything should work fine.

**Comment by NN---** [comment]
Thanks. Will try this.
If there was a feature to skip user name in 'choose custom credential fields' and just choose password filed, this could do the trick.

**Comment by varjolintu** [comment]
There is.

**Comment by jlczuk** [comment]
This did not work when I tried it for https://hvfcu.org and https://www.discover.com.  There seems to be some new website mechanics that are causing KeepassXC-browser to be defeated.  It is highly inconvenient.

**Comment by droidmonkey** [comment]
I think these random sites breaking have a lot more to do with other extensions interfering with ours.

**Comment by jlczuk** [comment]
I turned off tracking protections, although I really thing that one is valuable.   That didn't seem to affect Discover.  It's still working now.  The other sites are still not working.

The other potential interfering plugins are "Protect My Choices", "uBlock Origin", AdBlock and AdBlockPlus.

So... I disabled EVERYTHING, turned tracking protection off, uninstalled/re-installed the keepassXC-browser plugin.  Killed the browser and restarted it.  That didn't seem to change anything.  **THEN** I noticed something.

I was trying to use it to login to my ExxonMobil Smartcard account, which was not working either.  But then I noticed that the little flash enablement icon was showing in the address bar.  Once I enabled flash (with the remember this setting checked), it worked for that site.

The https://www.hvfcu.org login won't work no matter what I try.

**Comment by droidmonkey** [comment]
Cool, personally I would not recommend multiple ad block tools, they all pull from the same database and significantly slow down your browser. I just use Adblock as its the most transparent and best interface.

**Comment by nniesen** [comment]
I'm also having many detection issues after the 1.3.3 and 2.4.0 upgrades (Chrome 73, Win10). Uninstalling and reinstalling the extension seems to have helped some. 

However, there still seem to be a lot of issues with web sites that split the username and password across multiple screens; which has become fairly common. Sometimes I can get those working by manually setting just a username field. However, on one site the only consistent way I can get it to display the user name list is to use "Fill User + Pass", click another tab, and then use "Fill User + Pass" again. I get the feeling it is choking trying to fill the non-existent password field.

Some sites like https://myturbotax.intuit.com/ use the same URL for both the username form and the password form so I can't create separate db entries, or configure credential fields, or configure 'Site Preferences'. This is where I wish the context menu had both 'Fill User Only' and 'Fill Pass Only' and just did what I asked regardless of the field type or name.

**Comment by varjolintu** [comment]
@nniesen I tested the site you suggested and without adding it to the Site Preferences, using "Fill User + Pass" works for the login page and "Fill Password" for the password page. When I added the URL to Site Preferences and enabled the Username-only detection, then the autocomplete menu worked with both screens.

**Comment by droidmonkey** [comment]
Closing this as it seems to not be an issue anymore.
