### ISSUE TITLE
ITS: Basic ticket searches not user-friendly

### ISSUE THREAD

**Issue by Chealer** [keepassxreboot/keepassxc-browser#2283]
This issue tracker contains a large number of tickets, making it important to facilitate search. While there are several search features, it appears fairly complicated to perform even simple searches. For example, if I want to find a ticket about an OTP issue in KeePassXC, I should be able to just select an OTP tag or type "OTP" and/or "one-time password" somewhere and have only tickets about KeePassXC and having the relevant tag or "OTP" or "one-time password" in their title―such as #2243 and #2282―turn up when I launch the search, without having had to study the engine's interface.

I am not an expert of GitHub and am certainly not aware of what its future holds, but am afraid such a possibility would require switching to a proper ITS engine, such as Atlassian Jira.

**Comment by droidmonkey** [comment]
https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests
