### ISSUE TITLE
Update accessed date when entry is used to populate login fields

### ISSUE THREAD

**Issue by CarnageMarkus** [keepassxreboot/keepassxc-browser#2284]
It looks like the accessed field is only updated when editing/viewing entry directly through KeePassXC desktop app.

## Expected Behavior
When I select entry to populate login fields on site, entry should also update it's accessed date field. So that entries can be sorted by their use. Also, it would make easy to detect entries that I haven't used in long time - old logins, unused sites / accounts

## Current Behavior
Most of the entries have accessed date same as modified and/or created date, as you don't need to open them in desktop app when using this extension, making accessed fields practically useless

KeePassXC-Browser Version: 1.9.1.1
KeePassXC Version: 2.7.9 
Operating system: Win
Browser: Firefox

**Comment by droidmonkey** [comment]
Accessed isn't used and won't be used.

**Comment by CarnageMarkus** [comment]
Is there any discussion about it ? This feels the same as multiple times requested "find duplicates" feature which has been also closed because there are password strength reports already which shows that password is used "multiple times"... which is not really the same and won't help you to clear up 2k of entries... 
I feel like that's removal of QOL features. If it's removed because it's not used, but it is not used as it's not working properly in the first place? 🤷‍♂️
Rant over.
