### ISSUE TITLE
[Serious] Breaks browser styleseets for XML documents

### ISSUE THREAD

**Issue by benbucksch** [keepassxreboot/keepassxc-browser#2286]
## Expected Behavior
* The XML, as a tree, expanded (and branches collapsable).
* Stylesheets of the browser and the websites are not affected or destroyed

## Current Behavior
* The expected and correct display flashes for a split-second on the screen, then:
* The XML goes completely unstyled, and you see the tags and attributes as plaintext text, without linebreaks
* It appears that there is a stylesheet applied correctly, but then the KeePassXc browser extension comes in and removes it or breaks it.
* The XML is completely unreadable.

## Possible Solution
* Don't interfere with browser or site CSS style sheets.
* Scope your own stylesheet properly to avoid class name clashes

## Steps to Reproduce (for bugs)
1. Open https://v1.ispdb.net/office365.com in Firefox
(This URL returns XML with a Content-Type of "text/xml")

## Debug info
KeePassXC - 2.7.7
KeePassXC-Browser - 1.9.1.1
Operating system: Linux
Browser: Firefox 128.0 and earlier

**Comment by varjolintu** [comment]
Thanks. Found the reason. The extension does not check the content type before using content scripts. I made a fix where all XML files are ignored with the file extension type or checking the ContentType.

**Comment by benbucksch** [comment]
Thanks for the super fast response.

Can you use a whitelist instead of a blacklist, to avoid that other file types are broken?

**Comment by droidmonkey** [comment]
Other file types have style sheets?

**Comment by varjolintu** [comment]
> Other file types have style sheets?

I think this depends on the browser. Some file types are shown inside an internal page that can also allow some styling. At least this seem to happen with Firefox.
