### ISSUE TITLE
extension does not work on Linux selenium 6.8.0-38-generic with chromium

### ISSUE THREAD

**Issue by schaetimm** [keepassxreboot/keepassxc-browser#2288]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. see title

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
see title

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13

[NOTE]: # ( Pick choices based on your environment )
Operating System: Linux
Desktop Env: KDE

**Comment by varjolintu** [comment]
Uase the Custom Browser feature in KeePassXC to provide the path manually to the native messaging hosts folder. If you're not sure where to find it, refer to https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#find-the-native-messaging-configuration-path-with-strace
