### ISSUE TITLE
UI Change - Extension now barely usable

### ISSUE THREAD

**Issue by nascentt** [keepassxreboot/keepassxc-browser#2289]
Been using this addon for years and all of a sudden on both Edge and Chrome on Windows 10 the UI has completely changed to be triple the size barely fitting the credential options in.  And trying to intereact with the credentials to fill basically does nothing.  If i'm lucky something might happen 1/20 times I click on one of the credentials.

I've had to start copy pasting credentials from keepass to the browsers instead of using the addon as it's just barely usable.

KeePassXC - 2.6.6
KeePassXC-Browser - 1.9.1.1
Operating system: Win64
Browser: Chrome/Chromium 126.0.0.0

KeePassXC - 2.6.6
KeePassXC-Browser - 1.9.1.1
Operating system: Win64
Browser: Microsoft Edge 126.0.0.0

![keepassxd ui](https://github.com/user-attachments/assets/64f90d6e-2d53-497f-8c76-50baf6dee8b7)

**Comment by droidmonkey** [comment]
Screenshot?

**Comment by nascentt** [comment]
Ive edited the post to include a screenshot.

This is when it's the only add-on installed

**Comment by droidmonkey** [comment]
OK well that is the intended look and feel right now, we updated it.

**Comment by nascentt** [comment]
Ok. Great so you don't mind that it's now complete unusable?

Guess I'll switch back to ChromeKeePass.

**Comment by droidmonkey** [comment]
Works perfectly fine for me, you'll have to provide way more information and details on your setup and experience

**Comment by varjolintu** [comment]
Related: https://github.com/keepassxreboot/keepassxc-browser/pull/2279. The minimum width is set back to the input field's width.

**Comment by varjolintu** [comment]
Enable _Debug Logging_ from the extension settings and see if there's any errors in the JavaScript console when a fill fails?

**Comment by nascentt** [comment]
As an update, despite the tissues being closed.
I reinstalled the addin to check if there are console errors, and there are none.
I ended up switching the UI to compact mode, and this seems far more responsive, so I think the default UI must just be too much to render when you have many different credentials for sites as the menu just struggles to render.  In compact list it's very responsive.

That being said, the main issue I reported of clicking entries and nothing happening persists.  This seems less frequent with compact list but it does still happen.  No errors in console.
However ad the menu is so responsive in compact I end up just respecting the credentials and clicking it again and 2/3 times it'll work.
So if I just keep selecting entries until they fill the cred fields it's fine, as compact menu is much more tolerable.
It would be nice to get the phantom credential selection issue fixed so I'll try with debug logging

**Comment by droidmonkey** [comment]
Not experiencing your reported behavior at all. What other extensions do you have installed? What are your computer specs?

**Comment by varjolintu** [comment]
The only thing that could cause the credentials not to fill is to click a certain part of the Autocomplete Menu item. Although I already fixed an issue where clicking text or another `div` didn't fill anything before making a release. The code should detect the clicked item even if some of the child elements are being targeted.
