### ISSUE TITLE
Move the password generate icon a little bit left, now is top of "Chrome Show Password icon"

### ISSUE THREAD

**Issue by mwftts** [keepassxreboot/keepassxc-browser#229]
Now the "Password Generate icon is on the top of Chrome show password icon, please see the picture, https://imgur.com/4GgsQwC

## Expected Behavior
Move the password generate icon a little bit left.

## Current Behavior
Now is on the top of "Chrome Show Password icon", cannot click the show password icon.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. You will able to see the Chrome show password icon if you saved the password in Chrome as well.
2. Screenshot: https://imgur.com/4GgsQwC

## Debug info

KeePassXC - {2.3.3}
keepassxc-browser - {1.1.7}
Operating system: Win 7 pro x64
Browser: Chrome 67.0.3396.87 (Official Build) (64-bit)
Proxy used: YES/NO (not sure, using KeePassXC integration, no custom proxy)

**Comment by zkab** [comment]
Keepassxc just don't work for me ... it does not choose the generated password in Keepassxc but takes the one that is stored in Chrome ... what is wrong ?
Ubuntu 18.04.1 LTS & KeePassXC 2.3.4

**Comment by droidmonkey** [comment]
Don't use multiple password managers at the same time...

**Comment by varjolintu** [comment]
Seems this cannot be fixed.
