### ISSUE TITLE
Entry selection drop-down scrollbar doesn't respect theme

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#2290]
Note the light theme scrollbar even though dark theme is applied to the drop-down list itself.

![image](https://github.com/user-attachments/assets/455db01f-a10f-4824-af13-3ec2057ea293)

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Win
Browser: Chrome/Edge

**Comment by varjolintu** [comment]
I cannot reproduce this. Does this happen only with some sites?

**Comment by droidmonkey** [comment]
Seems to "only" happen on Netflix:

![image](https://github.com/user-attachments/assets/aa665013-3416-4b2a-8133-22d1359c7863)

**Comment by droidmonkey** [comment]
Adding `scrollbar-color: var(--kpxc-background-color) var(--kpxc-input-border-color)` to `.kpxcAutocomplete-container` solves the problem. Might be best to define explicit values though.
