### ISSUE TITLE
Browser extension unable to connect

### ISSUE THREAD

**Issue by MRDGH2821** [keepassxreboot/keepassxc-browser#2291]
I did a fresh install of [KDE Neon](https://neon.kde.org/) (which has Wayland as default), in which I configured firefox, keepassxc & the browser extension. But browser extension is not able to connect. 

## Expected Behavior

Extension should connect to KeepassXC

## Current Behavior

Shows :
```
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
```
After spam clicking reload button, some times it will show:
```
key exchange not successful
```
Tried on Flatpak version of firefox, APT version of firefox, none of them worked.
Flatpak version did not show `key exchange not successful` when spam clicked on reload button.

## Possible Solution

No Idea, but this screenshot can help:
![keepassxc-browser intergation not working](https://github.com/user-attachments/assets/90fed71d-12a0-4b42-8104-61b9f8ef75be)
```
[Error event.js:96] KeepassXC-Browser - changePublicKeys failed: TypeError: keepassClient.nativePort is null
```
If it wasn't null, my problem may be fixed.

## Steps to Reproduce (for bugs)

0. (Optional) Do a fresh install of [KDE Neon](https://neon.kde.org/)
1. Do a fresh installation of Firefox (v128) via APT
```
sudo apt update
sudo apt upgrade
sudo apt install nala
sudo nala install firefox
```
2. Install KeepassXC & browser extension. Configure browser integration in app.
3. Restart
4. Login to KeepassXC
5. Open extension & click reload
6. Expect connection failed error
7. Spam click reload or just wait for a while
8. Expect key exchange not successful

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Linux
Browser: Firefox

Stack trace from terminal: 
[stack trace from terminal.log](https://github.com/user-attachments/files/16325341/stack.trace.from.terminal.log)

Browser extension console log: 
[Browser extension log.log](https://github.com/user-attachments/files/16325340/Browser.extension.log.log)

<details>
<summary>OS Info from fastfetch</summary>

```bash
OS: KDE neon jammy 22.04 x86_64
Host: StarLite (1.0)
Kernel: Linux 6.5.0-44-generic
Uptime: 1 hour, 7 mins
Packages: 1886 (dpkg)
Shell: bash 5.1.16
Display (LG ULTRAGEAR): 2560x1440 @ 144Hz [External]
Display (BOE0B36): 2160x1440 @ 60Hz (as 1440x960) [Built-in] *
DE: KDE Plasma 6.1.3
WM: KWin (Wayland)
WM Theme: Breeze
Theme: Breeze (Light) [Qt], Breeze [GTK2/3]
Icons: breeze [Qt], breeze [GTK2/3/4]
Font: Noto Sans (10pt) [Qt], Noto Sans (10pt) [GTK2/3/4]
Cursor: breeze (24px)
Terminal: konsole 24.5.2
CPU: Intel(R) N200 (4) @ 3.70 GHz
GPU: Intel evice 46D0 (VGA compatible) @ 0.75 GHz [Integrated]
Memory: 4.22 GiB / 15.46 GiB (27%)
Swap: 0 B / 17.00 GiB (0%)
Disk (/): 9.59 GiB / 451.35 GiB (2%) - ext4
Local IP (wlp0s20f3): 192.168.1.11/24
Battery: 94% [AC Connected]
Locale: en_IN
```
</details>

**Comment by droidmonkey** [comment]
Follow the troubleshooting guide please: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by MRDGH2821** [comment]
The only thing remaining to try was the `apparmor` method. Didn't think that would be the culprit (with the actual culprit being me skipping the AppArmor section assuming it didn't apply to me).

I had to do one additional step to get the thing working:
```
sudo apt install apparmor-utils
```

Else I believe simple restart would suffice after following the steps.

For those using KDE Neon, this also helps with KDE Plasma integration:
https://www.reddit.com/r/kdeneon/comments/1bvn0vs/how_to_fix_1password_and_plasma_integration_in
