### ISSUE TITLE
Username updating adds the category onto the username when updating the password

### ISSUE THREAD

**Issue by omtoi101** [keepassxreboot/keepassxc-browser#2296]
## Expected Behavior
Saves username as username

## Current Behavior

Saves username as [category] username

## Possible Solution

Change which variable it is accessing the username from, without the category included

## Steps to Reproduce (for bugs)

Seems to happen when only updating the password field, without a new username
The website I found it broke on was bendigobank.com.au

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Win
Browser: Chrome

**Comment by omtoi101** [comment]
It is added in both.
![Screenshot 2024-07-31 223234](https://github.com/user-attachments/assets/7a103c12-22be-4f1b-9bf8-ff29a3d7a81d)
![image](https://github.com/user-attachments/assets/f9f7e484-4b2f-4c16-9e1f-b140ce363a87)

**Comment by varjolintu** [comment]
I cannot reproduce this. I tried creating a new credential from another site, then updating it. Also tried putting it to a different group and then updating it. I need more info and steps to reproduce this.

**Comment by varjolintu** [comment]
Will reopen if needed.
