### ISSUE TITLE
Advanced string fields should be disambiguated when there are multiple entries for the same URL

### ISSUE THREAD

**Issue by flanger001** [keepassxreboot/keepassxc-browser#2299]
## Expected Behavior

If a URL has multiple entries and those entries each have the same advanced string field, and that string field is the only difference between the entries, the "Fill Attribute" context menu should show each entry's string field.

## Current Behavior

If a URL has multiple entries and those entries each have the same advanced string field, and that string field is the only difference between the entries, the "Fill Attribute" context menu only shows one matching entry's string field.

## Possible Solution

My naïve suggestion would be to get a list of entries for a URL, and show each entry and the matching string field next to it, with maybe a short snippet of the entry ID or some other disambiguating label.

## Steps to Reproduce (for bugs)

1. Create two entries for the same URL with the same username
2. Make the entry names different (possibly optional)
3. Create the same "KPH:" string field label in each entry
4. Make the string field values different
5. Visit the URL
6. Right click on the target string field and navigate to "Fill Attribute:"
7. See there is only one value shown

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: MacIntel
Browser: Mozilla Firefox 129.0

**Comment by flanger001** [comment]
Providing screenshots might be difficult, but I think I can produce a test database for this, also.

**Comment by varjolintu** [comment]
No need for a test database. I think this is easy to reproduce.

**Comment by varjolintu** [comment]
I cannot reproduce this:
<img width="614" alt="Screenshot 2024-08-09 at 8 23 51" src="https://github.com/user-attachments/assets/a2567b8e-683e-404d-9325-8cb21e783c8f">

**Comment by flanger001** [comment]
I should have specified further: my issue is that in this case, the usernames themselves are _also_ the same. I updated the original post. The extension correctly recognizes multiple entries for the main fields, but not for the attributes:

![Screenshot 2024-08-09 at 07 11 37](https://github.com/user-attachments/assets/847934a3-7819-42e8-bd17-7a8b3f303e64)

![Screenshot 2024-08-09 at 07 09 20](https://github.com/user-attachments/assets/c068c366-4251-48b8-afe8-12567667479d)
