### ISSUE TITLE
"Save Credentials" does not save the credentials

### ISSUE THREAD

**Issue by thekief** [keepassxreboot/keepassxc-browser#2301]
## Expected Behavior

When a username and password are typed, after manually setting the respective fields, opening the context menu and clicking "Save Credentials" should add the new credentials to the database.

## Current Behavior

When a username and password are typed, after manually setting the respective fields, opening the context menu and clicking "Save Credentials" does not add the new credentials to the database.

## Possible Solution

n/a

## Steps to Reproduce (for bugs)

1. open a site with a login form, e.g. the example from W3Schools [^1]
2. choose the username and password field
3. enter the username and password in the respective field
4. right-click in the username or password field to open the context menu
5. open the `KeePassXC-Browser` to click `Save Credentials`

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Linux
Browser: Firefox

[^1]: https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_login_form_modal

**Comment by droidmonkey** [comment]
It works fine, but ONLY if the fields are detectable by the extension. When you do the "try it" way, the fields are hidden from view and you cannot save it. Look for the KeePassXC icon to know when fields are valid for these actions:

![image](https://github.com/user-attachments/assets/cbc26513-8298-4b73-9e12-232bfc9aca9d)

**Comment by thekief** [comment]
@droidmonkey I cannot confirm the named behaviour. I tried it now several times with the symbol present and the credentials are not saved. Clicking on the symbol after trying to save the credentials results in a `No logins found.` error. 

Is there maybe a special location where the context menu must be opened?

In addition, the log does not indicate either that something was saved:

```
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found 4 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found 2 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 2 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 4 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error keepass.js:256] KeePassXC-Browser - 1: Database not opened [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error event.js:12] KeePassXC-Browser - 1: Database not opened [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found 3 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error init.js:62] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist. 2 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
[Error client.js:241] KeePassXC-Browser - 15: No logins found 2 [global.js:132:13](moz-extension://8c0d94ef-43e9-4c47-8952-56019bbfa1c7/common/global.js)
```

Could it be related to the `Cannot send activated_tab message`? This message seems really weird, as I have no problems filling the credentials on other sites.

**Comment by droidmonkey** [comment]
Worked flawlessly, just tested it. Did you press "New" in the popup banner that appears at the top of the page?

**Comment by thekief** [comment]
I think now we get to the root of my confusion.

My assumption was that clicking on "Save Credentials" should suffice. I never had the banner pop up when trying to save the credentials. 

How do I debug this issue? Do you have a guess what could be the problem?

**Comment by varjolintu** [comment]
@thekief That page you linked has the actual page on the right inside an iframe, and the source code is on the left. The extension doesn't detect those fields properly after the animation happens when clicking the login button.
