### ISSUE TITLE
Cannot connect Firefox (Mozilla PPA) on (K)ubuntu 24.04

### ISSUE THREAD

**Issue by leafpool243** [keepassxreboot/keepassxc-browser#2308]
I know that this is probably the billionth of these issues so far, but . . . it doesn’t connect.  I apologise in advance for the length, but I just listed everything I have done so far to try and fix it.

## Expected Behavior

Expect that it can connect.

## Current Behavior

It doesn’t connect.  Sometimes if I delete the connection and start over, it will work, but only for a moment.  At some point, it will just suddenly stop working.
![圖片](https://github.com/user-attachments/assets/598cba0e-4ff7-47e4-b1d2-154cab9ce852)
> Are you a first time user? Please read our Getting Started Guide.
> [Getting Started Guide — Setup Browser Integration]
> KeePassXC-Browser had an error:
> Unable to decrypt message.

OR
![圖片](https://github.com/user-attachments/assets/e777d280-25eb-4c27-9c56-51032a2ef54e)
> Key exchange failed.

## Possible Solution

Unfortunately, I’m not knowledgeable in this.

## Steps to Reproduce (for bugs)

1. Install Mozilla PPA, following instructions here https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions
2. Use KeepassXC Appimage
3. Enable browser integration in KeepassXC’s settings for Firefox.
4. Try to connect.

## Debug info

KeePassXC: 2.7.9
KeePassXC-Browser: 1.9.1.1
Operating system: Ubuntu (Kubuntu) Linux 24.04
Browser: Firefox (Mozilla PPA) 129.0~build2

## What I’ve tried so far
1. Disabling and reenabling browser integration for Firefox.
2. Reinstalling Firefox and the extension.
3. Following https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide:
3.1. `org.keepassxc.keepassxc_browser.json` exists under `~/.mozilla/native-messaging-hosts/` as expected.
3.2. The json file points correctly to `~/Applications/KeePassXC-2.7.9-x86_64_09d5556e85a42ea0d6c4cf4fde417c0c.AppImage`
3.3. Running `keepass-proxy` gives me:
```
Command 'keepassxc-proxy' not found, but can be installed with:
sudo apt install keepassxc
```
Maybe this is the issue, because I am using the Appimage.

Running `sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass` returns:
```
[pid 11626] openat(AT_FDCWD, "/home/USERNAME/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json", O_RDONLY <unfinished ...>
[pid 13111] execve("/home/USERNAME/Applications/KeePassXC-2.7.9-x86_64_09d5556e85a42ea0d6c4cf4fde417c0c.AppImage", ["/home/USERNAME/Applications/Kee"..., "/home/USERNAME/.mozilla/native-"..., "keepassxc-browser@keepassxc.org"], 0x736ff6b5f400 /* 84 vars */ <unfinished ...>
[pid 13111] execve("/usr/bin/AppImageLauncher", ["/usr/bin/AppImageLauncher", "/home/USERNAME/Applications/Kee"..., "/home/USERNAME/.mozilla/native-"..., "keepassxc-browser@keepassxc.org"], 0x7ffffa645750 /* 84 vars */ <unfinished ...>
```
`/run/user/1000/org.keepassxc.KeePassXC.BrowserServer` and `/run/user/1000/app/org.keepassxc.KeePassXC/org.keepassxc.KeePassXC.BrowserServer` appear to be correct.
I am not using Firejail, so the last section of (3) does not apply.

3.4.
From about:debug to open the console:
![圖片](https://github.com/user-attachments/assets/6580f818-84b7-4dbb-b71e-aa7c0bace6af)
無法連線到 KeePassXC。請確認 KeePassXC 的瀏覽器整合功能已啟用。 = Unable to connect to KeePassXC.  Please ensure that browser integration is enabled in KeepassXC.  (and I do have it enabled)
金鑰交換失敗。 = Key exchange failed.
These two errors are the exact same as what it shows in the extension UI, so nothing useful here.

Not sure what to do for the next step, debugging the content scripts themselves, because it’s not an autocomplete problem — I can’t even connect at all.

3.5. This section does not apply as neither KeePassXC nor Firefox are Snaps on my system, but just in case, I did it anyway. `flatpak permissions webextensions` reads:
```
webextensions org.kde.plasma.browser_integration firefox_firefox yes  0x00
webextensions org.kde.plasma.browser_integration snap.firefox    yes  0x00
webextensions org.keepassxc.keepassxc_browser    firefox_firefox yes  0x00
webextensions org.keepassxc.keepassxc_browser    snap.firefox    yes  0x00
```

3.6. I ran `sudo journalctl -t audit | grep 'apparmor="DENIED"' | grep "$(which keepassxc-proxy)"`, which returned empty, so I assume I probably shouldn’t touch anything there for now.  But, for what it’s worth, `/etc/apparmor.d/usr.bin.firefox` does not exist.

3.7. And this obviously does not apply since I am not on Windows.

**Comment by leafpool243** [comment]
If there is any more information I should provide, please tell me.

**Comment by varjolintu** [comment]
Please don't create new issues about this. Try using KeePassXC from the PPA as well, or test the Flatpak version.

**Comment by leafpool243** [comment]
Understood, thank you.  Maybe then, the flatpak should be put above the Appimage, although I’m not sure how common my issue is.

**Comment by varjolintu** [comment]
You can also try disabling the AppArmor even if the config does not exist.
