### ISSUE TITLE
Firefox Extension Seemingly Broken When Trying to Autofill the "accounts.firefox.com" URL

### ISSUE THREAD

**Issue by smhatc** [keepassxreboot/keepassxc-browser#2310]
## Expected Behavior
I visit the "accounts.firefox.com" URL and the extension works as normal by showing the icon on the username field. If it does not, I then should either be able to enter the username manually and try to fill in the password through the icon method, or be able to set a custom login field for the seemingly broken website manually.

## Current Behavior
The dialogue for allowing access to the matching database entries never shows up even though the URL is matching. Also, not only does the usual extension icon not appear in the username field, it also does not appear in the password field after manually filling in the username. Furthermore, should I attempt to manually set the login fields through the extension's "Custom Login Fields" functionality, it does not work (nothing happens after clicking the button). Also tried using the "Site Preferences" feature but it seemingly does nothing as well.

## Steps to Reproduce (for bugs)
1. Visit https://accounts.firefox.com
2. Wait for the system dialogue to allow access to the matching database entries. Nothing shows, and the username field icon is not there either.
3. Click on the "Custom Login Fields" button to try to fix the issue but does nothing.
4. Try to solve the issue using "Site Preferences" but also does nothing.

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Windows 11
Browser: Firefox 129.0

**Comment by varjolintu** [comment]
The Firefox itself restricts all extensions on certain sites, including `accounts.firefox.com`. The following can help: https://support.mozilla.org/en-US/kb/addons-restricted-domains
