### ISSUE TITLE
KeePassXC-Browser fails to properly detect a Vuetify based login form (Seems like missed/filtered mutations?)

### ISSUE THREAD

**Issue by segevfiner** [keepassxreboot/keepassxc-browser#2311]
## Expected Behavior

I expect KeePassXC-Browser to detect the login form in the given example project correctly: https://stackblitz.com/edit/vitejs-vite-ekzj4h?file=src%2FApp.vue

## Current Behavior

It fails to detect the login form consistently. It only detects it sometimes after typing in the text/password fields, or hammering the "Redetect login fields" button.

## Possible Solution

I think the mutation observer is missing/filtering some of the client side rendering changes done by the app which causes it to miss the form fields.

## Steps to Reproduce (for bugs)

1. Open https://stackblitz.com/edit/vitejs-vite-ekzj4h?file=src%2FApp.vue
2. Open the preview in a new tab using the button at the top right of the preview so there is no iframe interference.
3. KeePassXC-Browser fails to detect the login form consistently. Turning on the debug log shows the the mutation observer seems to either not see the fields at all, see only the username field, or actually see them both inconsistently as you type in the fields and/or press "Redetect login fields".

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.1.1
Operating system: Mac
Browser: Chrome

```
client:495 [vite] connecting...
client:614 [vite] connected.
main.ts:13 <Suspense> is an experimental feature and its API will likely change.
global.js:124 [Debug observer-helper.js:195] KeePassXC-Browser - Input fields found:
global.js:127 []
global.js:124 [Debug observer-helper.js:195] KeePassXC-Browser - Input fields found:
global.js:127 []
global.js:124 [Debug observer-helper.js:195] KeePassXC-Browser - Input fields found:
global.js:127 [input#input-0.v-field__input]
global.js:124 [Debug observer-helper.js:195] KeePassXC-Browser - Input fields found:
global.js:127 [input#input-0.v-field__input]
```

**Comment by droidmonkey** [comment]
Is there any practical reason why this detection is necessary?

**Comment by segevfiner** [comment]
For it to detect the login form...? Which is the whole point of this extension? 😕 

This example is just a minimal reproduction of the issue from some other internal app that I can't share. The same issue that this shows can also happen in other apps that are structured like this, which would prevent using KeePassXC-Browser in them as well. I honestly believe that this simply reproduces some bug in the detection logic, regardless of whether this is a real app or not.

**Comment by segevfiner** [comment]
That's not right... There is nothing preventing the extension from working with this when you open the preview in a separate tab. I can make a local version of this if you really want. I just placed it in StackBlitz so you won't have to install stuff.... Please reopen...

**Comment by varjolintu** [comment]
I can reproduce that. The preview is a separate iframe from another hostname. Normally that's prevented by the browser itself to put any content scripts there. We allow cross-origin iframes by a separate settings, but that didn't help at all when I tested it.

**Comment by segevfiner** [comment]
The preview can be opened in a separate tab using a button at the top of it, where it won't be an iframe anymore so as not to interfere with the extension.

**Comment by varjolintu** [comment]
> The preview can be opened in a separate tab using a button at the top of it, where it won't be an iframe anymore so as not to interfere with the extension.

In that case the fields work normally if you select them using Custom Login Fields. The problem why those are not detected automatically is that those fields are not connected to each other in any way. These are not in the same form or not inside the same element.

If you want to make these work with the preview window without using a separate tab, do the following:
1) Use Custom Login Fields to select the fields (username and password) on the right side preview window.
2) Add `https://stackblitz.com/edit/vitejs-vite-ekzj4h` to Site Preferences and enable _Allow Cross-Origin iframes_ option for it.
3) Add an entry with URL `https://webcontainer.io`.

**Comment by segevfiner** [comment]
But they are in the same form element: 
<img width="1634" alt="image" src="https://github.com/user-attachments/assets/8e2facd4-29e5-4568-b38a-defc3d275047">

And they do get detected *sometimes* without custom login fields in the separate tab, it's just not consistent at all, and never seems to happen on initial load. There really seems to be a bug here with the mutation observer just not seeing those fields for some reason...?

(Getting them to work in the preview window isn't what I'm after, I already know that I can use the cross-origin iframes setting for that if I really needed that, the real site isn't in an iframe)

**Comment by varjolintu** [comment]
The reason why you must select these fields using Custom Login Fields is that the CSS `.v-text-field input` defines the `opacity` as `0`. This means the extension thinks the input field is actually transparent and fraudulent, preventing the identification.

**Comment by segevfiner** [comment]
Thanks. That might be an issue in Vuetify then using confusing, not a11y safe, CSS. I might open an issue on their repo linking to this issus to see if they have any idea

**Comment by varjolintu** [comment]
> Thanks. That might be an issue in Vuetify then using confusing, not a11y safe, CSS. I might open an issue on their repo linking to this issus to see if they have any idea

Maybe use a custom CSS class to override that? At least it could be local workaround.

**Comment by segevfiner** [comment]
Yeah. I'll have to dig into their CSS to figure out why they had to use the `opacity: 0` and see what alternative there is to it. Which could also become a pull request for Vuetify.

**Comment by varjolintu** [comment]
> Yeah. I'll have to dig into their CSS to figure out why they had to use the `opacity: 0` and see what alternative there is to it. Which could also become a pull request for Vuetify.

This is because many frontends like to specify multiple divs around the actual input field, and then they wrap the input field inside of that content with zero opacity. The text will be shown normally of course.

**Comment by segevfiner** [comment]
> > Yeah. I'll have to dig into their CSS to figure out why they had to use the `opacity: 0` and see what alternative there is to it. Which could also become a pull request for Vuetify.
> 
> This is because many frontends like to specify multiple divs around the actual input field, and then they wrap the input field inside of that content with zero opacity. The text will be shown normally of course.

Yeah. But I think a combination of `appearance: none` and reseting some other CSS props can achieve that effect without really hiding the input box which harms a11y and tools like KeePassXC-Browser.
