### ISSUE TITLE
Browser plugin to add unlimited duplicate passwords

### ISSUE THREAD

**Issue by CloverAn** [keepassxreboot/keepassxc-browser#2312]
## Overview
The reason the browser plugin adds multiple records to the library when adding new data is because it is the correct username within the database, but the browser plugin is getting an empty username.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open a website and log into a new account
2. Browser plugin prompts to add password to database or not，Click to add
3. The browser plugin prompts "Adding an empty username", but the add at the top is still there and the data has already been added to the database. You can click on Add without limit and it will repeat without limit!

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: V2.7.9

**Comment by varjolintu** [comment]
Maybe the page is deleting the HTML element where the Credential Banner is attached to. It's hard to say what happens if we don't have access to that page.

**Comment by CloverAn** [comment]
Then this is a difficult problem to troubleshoot, after all, the problem is real, whether it is a website problem or a software problem
