### ISSUE TITLE
Fails to fill out password form fields on XHTML pages

### ISSUE THREAD

**Issue by CharlemagneLasse** [keepassxreboot/keepassxc-browser#2313]
## Expected Behavior
* Filling out the form works

## Current Behavior
* username is filled out but password is not filled out

## Possible Solution
* change the check `    if (combination.password && combination.password.nodeName === 'INPUT') {` to something which is case-insensitive `    if (combination.password && combination.password.nodeName.toUpperCase() === 'INPUT') {`
* OR revert the change which introduced the regression (83d536698dcba227a22bea93100062b464637e83) from PR  #2259

## Steps to Reproduce (for bugs)
1. create page with content type XHTML and serve with `Content-Type:	application/xhtml+xml;charset=utf-8`
2.  try to auto-fill password
3. see that only the username is filled out but not the password (because its `combination.password.nodeName` is `input` and not `INPUT`)

## Debug info
KeePassXC - 2.7.4
KeePassXC-Browser - 1.9.2
Operating system: Linux
Browser: Firefox 115.14.0esr (64-bit)

**Comment by varjolintu** [comment]
This is regression from: https://github.com/keepassxreboot/keepassxc-browser/pull/2287
