### ISSUE TITLE
KeePassXC-Browser whole password

### ISSUE THREAD

**Issue by Pe0xonN** [keepassxreboot/keepassxc-browser#2316]
KeePassXC-Browser - {VERSION}

There is such a possibility to choose your own passwords not only are on the search engine 

I mean you can choose the whole password

**Comment by varjolintu** [comment]
I'm not sure if I understand what you mean. Could you give some details?

**Comment by Pe0xonN** [comment]
example when I log in to Google and I have set instead of accont only I have set myaccount it does not collect information from, the possibility of adding such an option as searching for all passwords from the entire password manager

**Comment by droidmonkey** [comment]
You need to set the url of the entries you want to use for specific sites.

**Comment by Pe0xonN** [comment]
@droidmonkey
1. There is no such option as searching for all passwords by different domains for example
,

Will there ever be such an option as adding all passwords that are in the password manager?

**Comment by droidmonkey** [comment]
It is requested already and we are considering it

**Comment by Pe0xonN** [comment]
@droidmonkey Is there a deadline for adding this when?

**Comment by droidmonkey** [comment]
No, there is not, perhaps in keepassxc 2.8.0
