### ISSUE TITLE
Passkey not registering

### ISSUE THREAD

**Issue by Tofixrs** [keepassxreboot/keepassxc-browser#2317]
## Expected Behavior

Passkey creates

## Current Behavior

Passkey fails to create

## Steps to Reproduce (for bugs)

1. Go to any site using Internet Identity (eg. https://oc.app/)
2. Try to create an account
3. Press create passkey
4. Opens native passkey dialog (if any)

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.2
Operating system: Linux
Browser: Firefox

Stack trace in console
```
TypeError: challenge is shorter than required minimum length.
    checkErrors moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys-utils.js:27
    buildCredentialCreationOptions moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys-utils.js:58
    enablePasskeys moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/keepassxc-browser.js:919
    postMessageToExtension moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:88
    postMessageToExtension moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:72
    create moz-extension://e02b9aba-2f48-473d-9855-1eebb551277c/content/passkeys.js:151
    Kg https://identity.ic0.app/spa.js:362
    create https://identity.ic0.app/spa.js:362
    r https://identity.ic0.app/spa.js:922
    t0 https://identity.ic0.app/spa.js:922
    r https://identity.ic0.app/spa.js:974
    nr https://identity.ic0.app/spa.js:361
    constructPasskey https://identity.ic0.app/spa.js:974
    s https://identity.ic0.app/spa.js:941
    handleEvent https://identity.ic0.app/spa.js:53
```

**Comment by varjolintu** [comment]
Any site? I may need some more info. It really doesn't work even with webauthn.io?

This problem should be maybe linked to https://github.com/keepassxreboot/keepassxc/issues/10374 as well.

**Comment by Tofixrs** [comment]
> Any site? I may need some more info. It really doesn't work even with webauthn.io?
> 
> This problem should be maybe linked to [keepassxreboot/keepassxc#10374](https://github.com/keepassxreboot/keepassxc/issues/10374) as well.

I did specifically said it happens on sites using internet identity(eg. https://oc.app/), maybe shouldve made it more clear, other sites work fine

**Comment by varjolintu** [comment]
I tested it and got an error: `TypeError: challenge is shorter than required minimum length.`. Seems this Internet Identity thing is using WebAuthn but it doesn't respect passkey standards. The `challenge` is only 9 bytes long. Passkey requires it to be at least 16 bytes long.

**Comment by Tofixrs** [comment]
> I tested it and got an error: `TypeError: challenge is shorter than required minimum length.`. Seems this Internet Identity thing is using WebAuthn but it doesn't respect passkey standards. The `challenge` is only 9 bytes long. Passkey requires it to be at least 16 bytes long.

Imma report it to the project then

**Comment by Tofixrs** [comment]
For anyone interested it has been fixed https://github.com/dfinity/internet-identity/pull/2561
