### ISSUE TITLE
Feature Request - Import Settings from Registry

### ISSUE THREAD

**Issue by grei-007** [keepassxreboot/keepassxc-browser#2319]
## Feature Request
We would love to see an option to distribute and read the Edge extension settings (json) from a registry key so a standardized configuration can be easily configured between multiple devices, especially for site preferences.
(Ref: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Edge\3rdparty\Extensions\pdffhmdngciaglkoonimfcmckehcpafo)

**Comment by varjolintu** [comment]
FYI: It's already possible to import and export extension settings.

**Comment by grei-007** [comment]
Hi varjolintu,
Thanks for the quick response. I have seen in the UI that json files can be imported and exported manually, but I have not seen a way to easily distribute the config over multiple devices via distributed config file, regkey or one step further an extension management setting in Intune. If you have any documentation I missed a would appreciate a pointer.
BR

**Comment by droidmonkey** [comment]
You can distribute a json file in a million ways, including all those you mentioned. That doesn't eliminate the need to do the IMPORT step to apply those settings. We don't store individual settings in the registry and we won't ever do that.

**Comment by grei-007** [comment]
> We don't store individual settings in the registry and we won't ever do that.
Hi Jonathan, that answers my question and means the issue can be resolved as it won't be implemented. We will continue to manage extension settings per computer then. Thanks again for the quick feedback!
