### ISSUE TITLE
Illegal Invocation error on getPublicKey and getPublicKeyAlgorithm calls

### ISSUE THREAD

**Issue by Keroosha** [keepassxreboot/keepassxc-browser#2322]
## Expected Behavior

Do not get Illegal Invocation error on calling **getPublicKey** and **getPublicKeyAlgorithm** methods or override them instead of inheriting from prototype 

## Current Behavior

If you trying to call **getPublicKey** or **getPublicKeyAlgorithm** methods from AuthenticatorAttestationResponse of KeepassXC app you will get Illegal invocation due to inheritance those functions via AuthenticatorAttestationResponse prototype

## Possible Solution

Fix createAttestationResponse in passkeys.js as:

```js
const createAttestationResponse = function(publicKey) {
    const response = {
        attestationObject: kpxcBase64ToArrayBuffer(publicKey.response.attestationObject),
        clientDataJSON: kpxcBase64ToArrayBuffer(publicKey.response.clientDataJSON),
        getAuthenticatorData: () => kpxcBase64ToArrayBuffer(publicKey.response?.authenticatorData),
        getTransports: () => [ 'internal' ]
    };

    // Prevent Illegal invocation error
    const responseWithProto = Object.setPrototypeOf(response, AuthenticatorAttestationResponse.prototype);
    responseWithProto.getPublicKey = undefined;
    responseWithProto.getPublicKeyAlgorithm = undefined;

    return responseWithProto;
};
```

this solution proposed via #2323 PR

## Steps to Reproduce (for bugs)

1. Initiate Registration ceremony 
2. Confirm new passkeys creation at KeepassXC interface
3. Try to call `publicKey.response.getPublicKey` or `publicKey.response.getPublicKeyAlgorithm` in userside JS code
4. get Illegal invocation Exception

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.2
Operating system: Linux
Browser: Chromium

**Comment by droidmonkey** [comment]
For background, why would those function stubs be called in the first place? Should they actually return the data indicated by the name?

**Comment by Keroosha** [comment]
> why would those function stubs be called in the first place?

Because there is no other way to verify from user code should or not you call those functions (if you trying to check response from debugger they appears as callable functions)

https://www.w3.org/TR/webauthn-3/#iface-authenticatorattestationresponse

```IDL
ArrayBuffer? getPublicKey();
```

> getPublicKey() This operation returns the DER SubjectPublicKeyInfo of the new credential, or null if this is not available. See § 5.2.1.1 Easily accessing credential data.

**Comment by Keroosha** [comment]
@droidmonkey Ah, I've get what do you mean

Yeah, I didn't found publicKey in KeepassXC response to return it via AuthenticatorAttestationResponse contract

**Comment by SagePtr** [comment]
> Yeah, I didn't found publicKey in KeepassXC response to return it via AuthenticatorAttestationResponse contract

I think it's supposed to be parsed from ```publicKey.response.attestationObject``` (```getPublicKey``` provides shortcut to getting public key instead of full CBOR parsing).

And according to [the specification](https://www.w3.org/TR/webauthn-3/#sctn-public-key-easy), it should return non-null:
> User agents MUST be able to return a non-null value for [getPublicKey()](https://www.w3.org/TR/webauthn-3/#dom-authenticatorattestationresponse-getpublickey) when the [credential public key](https://www.w3.org/TR/webauthn-3/#credential-public-key) has a [COSEAlgorithmIdentifier](https://www.w3.org/TR/webauthn-3/#typedefdef-cosealgorithmidentifier) value of:
-7 (ES256), where [kty](https://tools.ietf.org/html/rfc9052#name-cose-key-common-parameters) is 2 (with uncompressed points) and [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 1 (P-256).
-257 (RS256).
-8 (EdDSA), where [crv](https://tools.ietf.org/html/rfc9053#name-double-coordinate-curves) is 6 (Ed25519).
