### ISSUE TITLE
Allow moving Credential Banner somewhere else (to the bottom?)

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#2327]
## Expected Behavior

https://www.matkahuolto.fi/ site uses notifications which flow from the top for "wrong password" and "email sent" (password recovery).

I expect to be able to move the Credential Banner, so can check the top of the page, without dismissing it.

## Current Behavior

Credential Banner is hard-coded to the top

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
What modal are you talking about here?

**Comment by stdedos** [comment]
![image](https://github.com/user-attachments/assets/9ab9d22f-65d1-48c0-8562-8e1ab251769b)

**Comment by varjolintu** [comment]
@dilpreetsio That's exactly my idea, but I haven't decided about the UI/UX what could be the most useful thing to do here. I might be in favor or some small arrow bar/selection/checkbox instead of a normal button.

**Comment by dilpreetsio** [comment]
The ui part is a bit tricky, but having a small arrow instead of a button sounds good.
