### ISSUE TITLE
Brave macOS integration not working

### ISSUE THREAD

**Issue by agowa** [keepassxreboot/keepassxc-browser#2328]
## Expected Behavior
1. The KeePassXC browser plugin connecting to KeePassXC also for Brave on macOS
2. The Troubleshooting guide mentioning Brave for macOS

## Current Behavior
* When selecting Brave in the KeePassXC settings for integration no plugin/extension is installed in Brave
* After manually installing the Chromium Extension in Brave and clicking the button for connecting it to KeePassXC nothing happens.
* If instead one clicks onto the "Reload" button in the tooltip of the toolbar icon (which normally would also trigger the connect/reconnect workflow) also nothing happens.
* When clicking the "Reload" button multiple times (out of despair :p), it shows a hint referencing this [Troubleshooting](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) page. However Brave in the list of NativeMessaging file paths. And the other mention of Brave by "Brave browser uses the Chrome storage location for native messaging. Choose the Chrome checkbox in KeePassXC Browser integration settings" is probably outdated since by now there is a dedicated option within the GUI for Brave.

## Possible Solution
1. Improve Troubleshooting and debugging instructions in the wiki for Brave (and in this case Brave on macOS).
2. Investigate what causes this issue, probably something permission or isolation related in macOS - I'd guess.
3. Maybe it's also an architecture mismatch issue, as the KeePassXC browser plugin reports the OperatingSystem/Architecture incorrectly as `MacIntel` instead of something like `MacM3/MacArm/...`

**Edit**: When I try to look for a file similar to `~/Library/Application Support/Chromium/NativeMessagingHosts` but for Brave on my system I neither have a folder like `~/Library/Application Support/Brave` nor `~/Library/Brave`, so maybe that is the issue? And it is a bug of their specific build?

## Steps to Reproduce (for bugs)
1. Install KeePassXC
2. Install Brave
4. Enable Browser integration in KeePassXC and tick the option for Brave
5. Install the Brave browser extension from: https://chromewebstore.google.com/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk
6. 
    a. Try to connect the extension to KeePassXC by using the "Connect" button on the extensions "Connected Databases" page.
    b. Just hit the "Reconnect" button in the extensions tooltip multiple times to get the hint about the Troubleshooting page.

## Debug info
About info of KeePassXC:
```
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Debugging mode is disabled.

Operating system: macOS 14.6
CPU architecture: arm64
Kernel: darwin 23.6.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Passkeys
- SSH Agent
- KeeShare
- YubiKey
- Quick Unlock

Cryptographic libraries:
- Botan 3.1.1
```

About info of the Browser Plugin:
```
KeePassXC - unknown
KeePassXC-Browser - 1.9.3
Operating system: MacIntel
Browser: Chrome/Chromium 128.0.0.0
```

MacOS Hardware Info:
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	Mac15,7
  Model Number:	Z1AG000FBD/A
  Chip:	Apple M3 Pro
  Total Number of Cores:	12 (6 performance and 6 efficiency)
  Memory:	36 GB
  System Firmware Version:	10151.140.19
  OS Loader Version:	10151.140.19
  Serial Number (system):	********
  Hardware UUID:	*****
  Provisioning UDID:	********
  Activation Lock Status:	Disabled

System Software Overview:

  System Version:	macOS 14.6.1 (23G93)
  Kernel Version:	Darwin 23.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Computer Name:	mac001
  Username:	user001
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	3 days, 14 hours, 54 minutes
```

Java script console output after hitting "Connect" on the "Connected Databases" page:
```
[Error keepass.js:313] KeePassXC-Browser - 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.
```

Operating system: Mac
Browser: Brave (`Version 1.69.153 Chromium: 128.0.6613.85 (Official Build) (arm64)`)

**Comment by varjolintu** [comment]
Try enabling all three, Chrome, Chromium and Brave support in KeePassXC. It's a known issue that Brave tends to use settings from incorrect folder. This issue is probably also a duplicate.

**Comment by varjolintu** [comment]
> Try enabling all three, Chrome, Chromium and Brave support in KeePassXC. It's a known issue that Brave tends to use settings from incorrect folder. This issue is probably also a duplicate.

With macOS you can try using `opensnoop` to detect the correct folder: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#3-check-if-keepassxc-proxy-is-launched-and-running

**Comment by agowa** [comment]
Hi, you're right. They're using the wrong path. They're using the Google Chrome path. When I looked at their ticket to report this issue I found this ticket: [Problem creating NativeMessagingHosts directory](https://github.com/brave/brave-browser/issues/5272)

Probably nothing KeePassXC can do then besides maybe extending or rewording the mention of brave using the chrome path to something that doesn't confuse a reader to think it is outdated and only applied before the dedicated Brave option was added to the GUI. As I noted already in the initial post I at least thought it no longer applies because of this dedicated option in the GUI existing...

**Comment by odysseus9672** [comment]
Any chance of reviving this to make it work correctly? Maybe just allow the user to select the communication json it should be pointing to? I'm running into the exact same issue, and cannot use the workaround of putting the file in the global directory because I'm working on a multi-user machine.

**Comment by varjolintu** [comment]
> Any chance of reviving this to make it work correctly? Maybe just allow the user to select the communication json it should be pointing to? I'm running into the exact same issue, and cannot use the workaround of putting the file in the global directory because I'm working on a multi-user machine.

How should we do that if Brave doesn't use correct folders for the configuration? And what do you mean by "global directory"?

**Comment by odysseus9672** [comment]
ChatGPT was recommending that I copy KeePass's json to the /Library/... directory from my ~/Library/... one. I told it this solution was unacceptable, so I asked if there was a way to force it to use the correct path. It mentioned Github issues that matched this problem, so I figured I would toss in my 2¢ worth. Sounds like this is a problem with Brave, and not the plugin, then?

**Comment by varjolintu** [comment]
> ChatGPT was recommending that I copy KeePass's json to the /Library/... directory from my ~/Library/... one. I told it this solution was unacceptable, so I asked if there was a way to force it to use the correct path. It mentioned Github issues that matched this problem, so I figured I would toss in my 2¢ worth. Sounds like this is a problem with Brave, and not the plugin, then?

ChatGTP is giving you incorrect answers. Read the previous messages in this thread.
