### ISSUE TITLE
Can't intall browser plugin in Edge

### ISSUE THREAD

**Issue by GTP95** [keepassxreboot/keepassxc-browser#2330]
## Overview
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Give a BRIEF summary about your problem )

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Download KeePassXC from official website
2. Click on the link to get the Edge browser plugin
3. On Edge store's [page](https://microsoftedge.microsoft.com/addons/detail/keepassxcbrowser/pdffhmdngciaglkoonimfcmckehcpafo) click on the "Get" button.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
The browser plugin is installed

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
I get the following error message: "The add-on could not be verified as the add-on manifest file is invalid."

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION not relevant
Revision: REVISION not relevant

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 11
Edge version: 100.0.1185.36 (Official build) (64-bit)

**Comment by varjolintu** [comment]
Just tried it (version 1.9.3) and had no problems.

**Comment by GTP95** [comment]
Sorry I missed your comments. Anyway I just tried again and it worked, thanks.
