### ISSUE TITLE
Troubleshooting guide flaw

### ISSUE THREAD

**Issue by ludwigschdt** [keepassxreboot/keepassxc-browser#2331]
I tried to connect my database with the arc browser on macOS. Even if I followed the troubleshooting, I did not succeed.
## Expected Behavior
Arc should connect with the database.

## Current Behavior
Extension reports error: Connection to KeePassXC is not possible.

## Possible Solution
Eventually it worked for me that I just enabled browser integration for Chrome (in the general tab!).
I found the hint here:
https://github.com/keepassxreboot/keepassxc-browser/issues/1955#issuecomment-1688840775

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Mac 
Browser: Chromium (Arc)

Thank you for your great work! It's amazing to have passkeys in a keepass password manager!

**Comment by varjolintu** [comment]
Arc browser is Chromium-based so you need to use the Custom Browser feature or determine the path for native messaging script files based on the information in the Troubleshooting Guide.

**Comment by ludwigschdt** [comment]
Yeah, but when I tried it hat way, it did not work. It worked only with **Chrome** enabled

**Comment by ludwigschdt** [comment]
> Arc browser is Chromium-based so you need to use the Custom Browser feature or determine the path for native messaging script files based on the information in the Troubleshooting Guide.

@varjolintu Yeah, but when I tried it hat way, it did not work. It worked only with Chrome enabled
