### ISSUE TITLE
Potential flaw in troubleshooting guide

### ISSUE THREAD

**Issue by ludwigschdt** [keepassxreboot/keepassxc-browser#2336]
> Arc browser is Chromium-based so you need to use the Custom Browser feature or determine the path for native messaging script files based on the information in the Troubleshooting Guide.

@varjolintu Yeah, but when I tried it hat way, it did not work. It worked only with Chrome enabled

_Originally posted by @ludwigschdt in https://github.com/keepassxreboot/keepassxc-browser/issues/2331#issuecomment-2334014595_

**Comment by ludwigschdt** [comment]
And so did for this guy: https://github.com/keepassxreboot/keepassxc-browser/issues/1955#issuecomment-1688840775

**Comment by varjolintu** [comment]
Modified the text in the guide.

**Comment by ludwigschdt** [comment]
Thank you!
