### ISSUE TITLE
Autofill not working with ID Austria

### ISSUE THREAD

**Issue by danielwagn3r** [keepassxreboot/keepassxc-browser#2337]
## Expected Behavior
Trying to login to a page which is using ID Austria identity provider, expected that username and password at the idp's loginpage are autofilled, but this does not happen. Experiencing the same problem in Chrome and Firefox on Windows.

## Current Behavior
When logging in to a site, which uses ID Austria identity provider the autofill of username and password on the login page of the idp at https://eid.oesterreich.gv.at doesn't work. Manually configuring the login fields doesn't help, adding additional entries with the alternate URL https://service.a-trust.at doesn't help eighter.

## Steps to Reproduce (for bugs)
1. Go to https://meinesv.at or https://finanzonline.bmf.gv.at
2. Choose "Mit ID Austria anmelden"
3. Look at autofill not happening hat the idps loginpage at https://eid.oesterreich.gv.at/authHandler/public/secure/auth/start

![image](https://github.com/user-attachments/assets/bc941b17-7bb3-4545-a4b8-e0f4ae703335)

## Debug info

KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 1809
CPU-Architektur: x86_64
Kernel: winnt 10.0.17763

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1

KeePassXC-Browser - 1.9.3
Browser: Chrome 128.0.6613.120 (Offizieller Build) (64-Bit)

**Comment by varjolintu** [comment]
Solution:
- Use `https://service.a-trust.at` as the entry URL
- When at the login page, open the extension popup from the toolbar icon and you see a messagea about accepting Cross-Origin iframes for the site. Press that button and Site Preferences list should be appended with `https://eid.oesterreich.gv.at/authHandler/public/secure/auth/start` where the option is enabled.
