### ISSUE TITLE
KeePassXC-Browser extension can't connect to KeepassXC database.

### ISSUE THREAD

**Issue by hopeholdings** [keepassxreboot/keepassxc-browser#2338]
KeePassXC set up on desktop.  Installed KeypassXC-Browser extension https://chromewebstore.google.com/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk  but it will not connect to database.  Tried reinstalling several times, restarting Brave but still will not connect.  Works in another Chromium based browser, albeit it slightly spotty autofills and usually requires closing and reopening browser but mostly works.

![image](https://github.com/user-attachments/assets/234f3485-721d-4f46-ad48-6ca589a303b6)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {2.7.9}

KeePassXC-Browser - {1.9.3}
Operating system: Linux with PopOS
Browser: Brave

**Comment by varjolintu** [comment]
Make sure Brave is not installed as Flatpak, and enable Chrome and/or Chromium support in KeePassXC. This is a common issue, and many related ones should've be found using the search.

**Comment by hopeholdings** [comment]
I don't know what flatpack is and I am not going to bother looking. I installed Brave the same way I installed Vivaldi - from the Pop Shop.  And Brave and Chromium and Vivaldi are all enabled, which you should've understood by my reporting that it works in Vivaldi.  None of the things you listed are the cause unless for some reason Pop Shop loads brave differently than Vivaldi.  Thanks anyway...

**Comment by hopeholdings** [comment]
I enabled Chromium, brave doesn't use Chrome, right?  And if you don't know what Pop Shop is maybe you should check it out and see how what they are using.  It gave no option for flatpack or not, just said install.

Anyway, I don't care enough to discuss any longer.

**Comment by hopeholdings** [comment]
I did enable and "Google Chrome" and same result.  Doesn't work.

**Comment by varjolintu** [comment]
> I enabled Chromium, brave doesn't use Chrome, right? And if you don't know what Pop Shop is maybe you should check it out and see how what they are using. It gave no option for flatpack or not, just said install.

I checked it out and gave a direct link to you.

> Anyway, I don't care enough to discuss any longer.

I see.

**Comment by droidmonkey** [comment]
> And Brave and Chromium and Vivaldi are all enabled, which you should've understood by my reporting that it works in Vivaldi.

Just to point our you didn't mention anything about Vivaldi in your original post. That's beside the point, you need to do work on your end to help us help you. That includes understanding your deployment environment enough to answer basic questions. Linux is not for beginners and there are plenty of resources to help you figure this out. There are also plenty of reports about brave on Linux you should read on this issue board, please search and find.
