### ISSUE TITLE
Apple Mac - Login to iCloud Mail - Error No Logins Found - https://idmsa.apple.com

### ISSUE THREAD

**Issue by ilaw138** [keepassxreboot/keepassxc-browser#2339]
When logging into iCloud Mail using Apple's rather unique login method the error "No Logins Found - https://idmsa.apple.com appears. This is despite having both https://idmsa.apple.com and idmsa.apple.com set up as KP2A URLs. Neither User Id nor Password will auto-complete. Have also tried with the primary URL set as https://idmsa.apple.com.

## Expected Behavior
I would expect that the extension should find the credentials and complete the user name and password as required.

## Current Behavior
Nothing other than error message as discussed above.

## Steps to Reproduce (for bugs)

1. Navigate to https://www.icloud.com/
2. Click on "Sign in Button"
3. Follow sign in process.

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Mac - M1 2020 - Sonoma 14.6.1
Browser: Chromium (Brave Browser)

**Comment by varjolintu** [comment]
Click the extension icon in the toolbar and you should see a message and a button about a detected iframe. Allow that for the site and everything should work again. The extension doesn't allow iframes from another subdomains by default.
