### ISSUE TITLE
Icon covers up "show password" on some sites

### ISSUE THREAD

**Issue by MTBGCA** [keepassxreboot/keepassxc-browser#2344]
## Expected Behavior

The icon should be movable, hide, as it covers up the "show password" selection on some web sites.

## Current Behavior

When you log on to some sites it covers up the "show password" option
![image](https://github.com/user-attachments/assets/4a3db0ac-55d7-46be-9c22-c9c1a6d94d3e)
![image](https://github.com/user-attachments/assets/6500af52-7f62-4e82-be44-f014fd89d199)

## Possible Solution

Make the icon moveable or hideable

## Steps to Reproduce (for bugs)

1. Example site is Royal Bank Canada
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
We need to make an exception for that site for the icon location.
