### ISSUE TITLE
KeepassXC extension doesnt work if you dont enable Firefox even tho you set a custom value for the native messaging host config.

### ISSUE THREAD

**Issue by makuru-dd** [keepassxreboot/keepassxc-browser#2345]
## Expected Behavior

It should force activate maybe by graying it out or disabling the other, if you enable a special proxy location for custom forks of Firefox like Librewolf.

## Current Behavior

If Firefox is disabled, nothing happens to the value in custom browser configuration location, setting it confusing and not doing anything.

## Possible Solution

I could solve it by activating both browser ingratiation for Firefox and custom location.

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 129.0

**Comment by varjolintu** [comment]
Check that your Firefox is *not* installed as Snap or Flatpak.

**Comment by makuru-dd** [comment]
I had the problem that I dont use Firefox and so didnt enable that Firefox should be used for the keepassXC extension but it needed to be enabled so that Librewolf works with KeepassXC, which is confusing, I already set a setting that KeepassXC should use a custom location to account for Librewolf, why do I need to enable Firefox, so it does work?

**Comment by varjolintu** [comment]
That seems like a LibreWolf problem. Obviously they shouldn't be using Firefox's config paths, but their own.

**Comment by makuru-dd** [comment]
No, I got it working, youre UI is just a bit confusing, I need to enable KeepassXC Browser ingratiation Firefox button aditionally to setting up a custom path. I didnt think I need to enable Firefox because I dont have Firefox and I dont want it to work if i did have it for some reason.

**Comment by varjolintu** [comment]
You don't need to enable Firefox support for setting a custom path for Firefox-based browser. The browser type is just divided with Firefox and Chromium because the JSON script format differs a bit.

**Comment by shasherazi** [comment]
I faced the same issue today. I am using floorp on arch linux (btw), and I setup custom config location too, but the extension didn't detect keepassxc until I enabled Firefox in the general menu as well.

**Comment by varjolintu** [comment]
Maybe Floorp is using Firefox's paths directly?
