### ISSUE TITLE
Custom login field for subpath

### ISSUE THREAD

**Issue by terrytw** [keepassxreboot/keepassxc-browser#2348]
## Expected Behavior
Currently, custom login fields are based off domain name, but if I have several different subpath under the same domain name, e.g. https://mydomain.com/jellyfin and https://mydomain.com/somethingelse, I can only have 1 custom login field for the both of them.

## Possible Solution
Allow custom login field to match subpath as well, like site preference.

**Comment by varjolintu** [comment]
Disable _Advanced Settings -> Save Domain Only_?

**Comment by terrytw** [comment]
OK I'm blind. Sorry and thank you!
