### ISSUE TITLE
Can't create a passkey on Twitter

### ISSUE THREAD

**Issue by KwiatekMiki** [keepassxreboot/keepassxc-browser#2349]
## Expected Behavior
After trying to create a passkey on Twitter, it should ask me if I want to register it.

I have tested if it works with another website.
![image](https://github.com/user-attachments/assets/e0095a2a-0a42-4864-8599-dfb9e3b81688)

## Current Behavior
It doesn't ask me if I want to save the passkey, it just shows me this:
![image](https://github.com/user-attachments/assets/5b270e7f-6e20-4fd4-8e4a-e18d0b40f2e7)

## Possible Solution
person shrugging emoji

## Steps to Reproduce (for bugs)
1. Log into Twitter
2. Open https://x.com/i/flow/two-factor-security-key-enrollment
3. Enter your password
4. Click "Get Started"
5. Get redirected to a blank page asking you to touch your security key

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Linux
Browser: Firefox
![image](https://github.com/user-attachments/assets/63365256-62eb-4937-8d33-f47d6d72c8cd)

**Comment by varjolintu** [comment]
Twitter is already reported in here: https://github.com/keepassxreboot/keepassxc/issues/10374

**Comment by KwiatekMiki** [comment]
Didn't notice that here, sorry
