### ISSUE TITLE
Reopen database doesn't show KeePassXC window in foreground

### ISSUE THREAD

**Issue by NN---** [keepassxreboot/keepassxc-browser#235]
After database is locked, click on Reopen database shows KeePassXC window in background and not in foreground.

## Expected Behavior
KeePassXC in foreground.

## Current Behavior
KeePassXC in background flashing in taskbar.

**Comment by varjolintu** [comment]
Please give some details about the KeePassXC and KeePassXC-Browser versions you are using, including your operating system. Thanks.

**Comment by NN---** [comment]
OS: Windows 10x64
Browser: Firefox 61 x64
KeePassXC: 2.3.3
KeePassXC-Browser: 1.1.7  (https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/)

**Comment by varjolintu** [comment]
Duplicate of https://github.com/keepassxreboot/keepassxc/issues/1643.
