### ISSUE TITLE
High performance impact of Dynamic input field detection on powerful PC

### ISSUE THREAD

**Issue by pallaswept** [keepassxreboot/keepassxc-browser#2352]
## Expected Behavior
Low impact on performance.

## Current Behavior
High impact on performance

## Possible Solution
Throttle the modification of text input fields? - eg only update after x milliseconds since the object is added
'Lazy' modification of input fields? - eg only update input fields when not otherwise busy and DOM is stable
Batched modification of input fields? - eg only update if we have not already updated since x milliseconds
Multi-stage handling of input fields? - eg one lightweight handler which adds/removes newly added/removed input fields to/from a list, to be handled later. One heavy handler which handles the list when everything else is done (like ISRs)
You get the idea :)

## Steps to Reproduce (for bugs)
1. Visit https://browserbench.org/Speedometer3.0/  and run the benchmark
2. Disable dynamic input field detection
3. Run the benchmark again

I saw some people comparing browser performance recently, and just out of interest, gave the benchmark a shot. I scored very low, which was unexpected. This is a relatively fast machine, and the browser is modified for performance, and generally scores very well in benchmarks.
I did some troubleshooting, and found that the cause was this addon. Because the benchmark is very much full of text input fields, it was a torture test for the addon.

I don't think there's a huge problem here in general, most sites won't have so many input fields, so a performance problem won't ever be very big. Still, this benchmark being a torture test, did expose a good opportunity to optimise the process. 

It does occur to me, that for example, if this addon waited just a few frames between the DOM event signalling the addition of the input field, and adding its features to the field, then it would prevent this performance blowout in the initial page load, meaning pages will load faster, but the delay would still be invisible to the user, since the graphical layout will take far longer than that. Continuing on this train of thought, various commonplace methods to avoid flooding reactions to events, come to mind. 

For now I set `Use dynamic input field detection` disabled, and use the context menu to trigger password input where necessary. So I'm happy with my workaround! Thank you very much for this outstanding suite of software.

## Debug info
KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 130.0

**Comment by pallaswept** [comment]
I think you would know this to be true, better than anyone. Closing accordingly :) Thank you for your fantastic work!

**Comment by droidmonkey** [comment]
Interesting enough, I couldn't replicate your results. I tested on my Galaxy S24 using Edge and got 7.6. On my brand new laptop I got 12.6 with keepassxc fully enabled, 13 with all keepassxc features disabled for the benchmark site, and 12.7 with the extension completely disabled.

**Comment by pallaswept** [comment]
Honestly, I can't reproduce them any more, either! I had noticed some correlations, eg Dark Reader (set to 'Immediate Notify') and some of my custom CSS, which made this effect more extreme, so I disabled them for the benchmark accordingly. When I couldn't reproduce, I tried to throw it a curveball, I enabled them, and *still* can't reproduce it. 

Of course, there is a small performance hit, but not like I observed earlier. Previously, I might score 13 with this feature off, and 9 with it on. Now it's 13 off, and 12.6 on. No problem at all.

I've upgraded to Firefox 130 recently, perhaps there was a bug in 129? Anyway, apologies for the false alarm! I'm toggling this feature back on.

**Comment by varjolintu** [comment]
I'm aware that there might be some minor performance issues with the field detection, and I hope to solve them in the future. The current hit shouldn't be much though.

**Comment by pallaswept** [comment]
> The current hit shouldn't be much though.

Agreed, there's no problem here. This was an erroneous bug report and I apologise. There legitimately was an issue, which I tested thoroughly, but then I upgraded browser and didn't test again before reporting it. It was a foolish mistake.
