### ISSUE TITLE
Keepassxc-browser cannot connect to keepassxc when installed on Zen browser

### ISSUE THREAD

**Issue by bonjour81** [keepassxreboot/keepassxc-browser#2353]
## Expected Behavior
Connect with keepassxc 

## Current Behavior
On Zen browser, keepassxc-browser cannot detect keepassxc and won't connect database.
`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

works fine with Firefox on same laptop
 

Not sure if it's a keepassxc, zenbrower or flatpak issue.

## Steps to Reproduce (for bugs)
1. install Zen Browser
2. install keepassxc-browser extension
3. try to connect keepassxc

## Debug info

KeePassXC - 2.7.9
KeePassXC-Browser -  1.9.3
Operating system: Linux (Manjaro)
Browser: Zen browser 1.0.1-a.6  installed from flatpak  (Zen browser is based on firefox)

**Comment by varjolintu** [comment]
Use the Custom Browser options. Seems the document is not yet up to date, but here's the relevant text:
https://github.com/keepassxreboot/keepassxc/pull/11220/files

**Comment by bonjour81** [comment]
ok thanks for the hint.
it might be that zen browser does not support native messaging yet (not sure) 
https://github.com/zen-browser/desktop/issues/725

**Comment by varjolintu** [comment]
Then your best shot is to use Auto-Type instead.

**Comment by cmw** [comment]
Which, in turn, will not work with Wayland...

**Comment by varjolintu** [comment]
> Which, in turn, will not work with Wayland...
> 
> cf. [keepassxreboot/keepassxc#2281 (comment)](https://github.com/keepassxreboot/keepassxc/issues/2281#issuecomment-2374442403)

Then your best shot is to use another browser :)

**Comment by bonjour81** [comment]
> > Which, in turn, will not work with Wayland...
> > cf. [keepassxreboot/keepassxc#2281 (comment)](https://github.com/keepassxreboot/keepassxc/issues/2281#issuecomment-2374442403)
> 
> Then your best shot is to use another browser :)

Who use only one browser anyway ? ;)
But yes, in this case and for me, no keepass will be a no go fo Zen browser for now.

**Comment by BasicallyPolaris** [comment]
@bonjour81 after digging through other posts and documentations I found a solution that works for me when using Wayland on Fedora (while it results in some UI Bugs for the Dropdown menus on KeepassXC)

Starting KeepassXC with the `-platform xcb` flag resulted in me being able to connect the KeepassXC extension 

So consider binding a custom script that executes `keepassxc -platform xcb` on startup or add one to your PATH to allow for simple access :)

I hope this works for you as well!

**Comment by opensourcer2** [comment]
+1

**Comment by bonjour81** [comment]
Hi @BasicallyPolaris , did you do something else in addition to this command line? 
it seems not enough on my side.

**Comment by BasicallyPolaris** [comment]
Hey @bonjour81, yeah the only thing I did was start keepassxc with those parameters to enable xcb platform, that also fixed for me the issue on previous Wayland sessions on Gnome

**Comment by nenas1ya** [comment]
Works correctly on windows btw, so not a general Zen issue

**Comment by fullsizemalt** [comment]
hello from march 2026

i just had this identical issue on 1.19.3b (Firefox 148.0.2) (aarch64) running on macOS 26.4 Tahoe and here's how i got it working

 Problem: KeePassXC browser extension in Zen Browser on macOS showed "Message encryption failed" — the
  extension could reach KeePassXC but the encryption handshake failed.

  Troubleshooting steps attempted:

  1. Confirmed browser integration was enabled in KeePassXC (Tools → Settings → Browser Integration) and the
   extension in Zen
  2. Ran terminal commands to locate Zen Browser's native messaging manifest (all returned no results,
  suggesting non-standard packaging on macOS):

  find /Applications -name "manifest.json" 2>/dev/null | xargs grep -l "keepassxc" 2>/dev/null
  ls /Applications/Zen\ Browser.app/Contents/Resources/
  mdfind "kMDItemDisplayName == 'Zen Browser'" 2>/dev/null
  ls -la "/Applications/" | grep -i zen

  3. Tried restarting KeePassXC via terminal:

  killall KeePassXC 2>/dev/null; open -a KeePassXC

  4. Tried launching KeePassXC with sandbox disabled:

  open -a KeePassXC --args --no-sandbox

  Solution: A full reset — removing the KeePassXC extension from Zen, fully quitting KeePassXC (Cmd+Q),
  reopening with the database unlocked, and reconnecting the extension — resolved the encryption handshake
  failure.
