### ISSUE TITLE
ALT+SHIFT+U conflicts with Bitwarden firefox extension

### ISSUE THREAD

**Issue by AnthillSudoku** [keepassxreboot/keepassxc-browser#2354]
## Current Behavior

KeepassXC-browser assigns ALT+SHIFT+U shortcut to "Fill Username and Password", meanwhile Bitwarden Firefox extension assigns the same shortcut to open the Firefox's lateral panel.

Having both installed, if you press ALT+SHIFT+U nothing is shown. This could lead to confusion since the Firefox lateral panel  (Bitwarden) does not show and KeepassXC-browser does not show anything if you are not on a login page.

## Possible Solution

1. use another shorcut like ALT+SHIFT+L (where L could mean Login and is easy to remember).
2. Show a notification that keepassxc-browser has not found a login for the site or is not able to fill it. So at least you can recognize what's happening.

If I manually configure keepassxc-browser to use ALT+SHIFT+L nothing happen after pressing it, and I still have to figure why.

## Debug info

KeePassXC - 2.7.4
KeePassXC-Browser - 1.9.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
First of all: using two password manager browser extension will definitely affect to both of them. Second, you can just specify another shortcut for KeePassXC-Browser for that functionality manually from Firefox's extension settings.
