### ISSUE TITLE
Key exchange failed with KeepassXC 2.7.9

### ISSUE THREAD

**Issue by skibbipl** [keepassxreboot/keepassxc-browser#2355]
## Overview
I'm not sure when the issue started (because I use also bitwarden as a password manager) but recently I tried to connect KeePassXC-Browser extension to my local KeepasXC database and I'm constantly getting "Key exchange failed". It worked few weeks ago so I assume something has changed in firefox.

## Steps to Reproduce
1. Open KeePassXC-Browser UI
2. Press reload

## Expected Behavior
Connection to the opened KeepassXC database.

## Actual Behavior
Key exchange error message.

## Context
I followed Troubleshooting guide but everything seems to be working fine. I tried also with a fresh firefox profile and I'm getting the same error.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.7.9
Revision: 8f6dd13
Firefox: 133.0a1 (2024-10-03) (64 bit)
KeePassXC-Browser: 1.9.3

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by skibbipl** [comment]
I tried to re-enable Firefox integration from keepassxc. I also enabled debugging of extension but log is vague and doesn't give any details :(
```
[Error keepass.js:256] KeePassXC-Browser - 7: Message encryption failed. Is KeePassXC running? [global.js:142:13](moz-extension://9708d440-89ad-486b-b9ae-2b39922fb6b0/common/global.js)
[Error keepass.js:333] KeePassXC-Browser - No content script available for this tab. [global.js:142:13](moz-extension://9708d440-89ad-486b-b9ae-2b39922fb6b0/common/global.js)
KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser [client.js:383:13](moz-extension://9708d440-89ad-486b-b9ae-2b39922fb6b0/background/client.js)
[Error keepass.js:812] KeePassXC-Browser - 9: Key exchange failed. [global.js:142:13](moz-extension://9708d440-89ad-486b-b9ae-2b39922fb6b0/common/global.js)
[Error keepass.js:421] KeePassXC-Browser - No content script available for this tab. [global.js:142:13](moz-extension://9708d440-89ad-486b-b9ae-2b39922fb6b0/common/global.js)
```
I've translated the error messages from polish locale so they might not be 100% accurate. I would love to help debug this issue, but I don't know where to start...

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#windows

Check your registry and appdata/local/keepassxc folder. Could very well be a Firefox bug as well, are you running a beta or nightly version?

**Comment by skibbipl** [comment]
As I said, I already tried troubleshooting steps and everything seems to be fine there. Yes, I use nightly firefox, and it is not working for a week or two, so I don't think this is a Firefox bug. Maybe something something changed that affects keepassxc connectivity?

**Comment by droidmonkey** [comment]
I just installed Firefox and it worked immediately with 2.7.9
