### ISSUE TITLE
Manually Redect login fields after using Choose Custom Login Fields 

### ISSUE THREAD

**Issue by ahouse73** [keepassxreboot/keepassxc-browser#2357]
## Expected Behavior
After selecting custom login fields, the fields should be automatically detected when visiting the website

## Current Behavior
I Have to click `Redetect login fields` manually and then it gets detected

## Steps to Reproduce (for bugs)

1. Visit https://sso.itmc.tu-dortmund.de/
2. Choose Custom Login Fields (because the username input gets detected as TOTP field) and choose the username as username and password as password
3. refresh the site
4. No Field detected (before `Redetect login fields`)

## Debug info

Before manually `Redetect login fields`:
```
[
    {
        "username": null,
        "password": null,
        "passwordInputs": [
            null
        ],
        "totp": null,
    }
]
```
Afterwards:
```
[
  {
    "username": "input#idToken1.form-control.input-lg",
    "password": "input#idToken2.form-control.input-lg",
    "passwordInputs": [
      "input#idToken2.form-control.input-lg"
    ],
    "totp": null,
  }
]
```

KeePassXC - 2.7.9
KeePassXC-Browser - 1.9.3
Operating system: Win64
Browser: Chrome/Chromium 129.0.0.0

**Comment by ahouse73** [comment]
Maybe I understand the feature wrong, any help is appreciated!

**Comment by varjolintu** [comment]
Those should be automatically detected. So maybe it's a bug then, or the page contents are not loading early enough because of some animation etc.

**Comment by droidmonkey** [comment]
I can reproduce this, but I think @varjolintu is correct. They are doing some weird "hide the body until the whole page loads" bullshit. The way they are doing this causes the extension to ignore the fields. In fact, they leave behind a `display: none` style attribute on the body element. The page is poorly constructed to be honest.

![image](https://github.com/user-attachments/assets/795060c2-016f-45af-b401-ea319082813a)
