### ISSUE TITLE
Lists single entry twice in popup

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#236]
I tested KeePassXC with Firefox Nioghtly and found this bug.

## Expected Behavior

Only list one entry once.

## Current Behavior

![github](https://user-images.githubusercontent.com/11966684/43368583-cd415f0a-935f-11e8-8574-ca95a0a1061f.png)

And no, I have not saved this two times. :laughing: 

## Steps to Reproduce (for bugs)

1. Go to any website.
2. Detect credentials, if needed.

## Debug info

KeePassXC-Browser Version: 1.2.0
KeePassXC Version: 2.3.3 
Operating system: Linux
Browser: Firefox Nightly 63.0a1 (2018-07-29) 
Proxy used: yes

**Comment by varjolintu** [comment]
Anything that happens with Firefox Nightly but not with Stable is not in the fix list.

**Comment by rugk** [comment]
I thought you may be better off, when you notice bugs early. I would not be too sure, this is a bug in the nightly version. 😆

**Comment by varjolintu** [comment]
What I have learned is that nightly versions do constant API changes. Some day something works, next day it doesn't etc.. Chasing those bugs would be the end of me. So we'll stick supporting the stable releases.
