### ISSUE TITLE
Match hostname+port to differentiate services on same host

### ISSUE THREAD

**Issue by nonPointer** [keepassxreboot/keepassxc-browser#2362]
## Expected Behavior

Match credentials for services on the same host but different ports respectively.

## Current Behavior

Returns all credentials of the same host.

**Comment by varjolintu** [comment]
Does your entry URL's have the ports defined?

**Comment by droidmonkey** [comment]
You need to enable "Only return best matching credentials" on the keepassxc side

**Comment by nonPointer** [comment]
@varjolintu Yes, it does.
@droidmonkey Many thanks! It now works as expected.
