### ISSUE TITLE
Opera/Opera GX support & Password search bar

### ISSUE THREAD

**Issue by Krakovia-Dev** [keepassxreboot/keepassxc-browser#2364]
I'll be super thankful if you add **Opera & Opera GX** browser support, including a browser extension. Because of this, the **autofill** option **doesn't work at all** & it's a pain in the neck to find the password you need. Speaking of finding a password, a **password search bar** would be a very welcome addition.

**Comment by varjolintu** [comment]
Have you tried using the Custom Browser feature? So far it's documented only in here: https://github.com/keepassxreboot/keepassxc/pull/11220/files
