### ISSUE TITLE
Bring database matching in line with desktop app

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [keepassxreboot/keepassxc-browser#2369]
This is obviously just a suggestion but... I think it makes sense because at the moment, I don't see why I would use the browser extension over auto-type via the desktop app. It _could_ be more convenient if this was implemented though.

## Expected Behavior
The suggested database entries should be at least as good as via auto-type in the desktop app.

## Current Behavior
No suggestions at all for websites where the URL is not yet stored in the database.

## Possible Solution
I don't know the code bases but I'm assuming that this has to do with the extension not using the window title and not using substring matching and instead purely relying on the URL field.

Given that the browser extension actually knows more about the site than the desktop app (i.e. URL in addition to the window title), it should actually be able to find matches where the desktop app might not.

(Also, as a possible optimization for future lookups, it might of course make sense to add a given URL to the database once the user has confirmed a certain entry.)

**Comment by varjolintu** [comment]
I think your request aligns with https://github.com/keepassxreboot/keepassxc-browser/issues/218 and I'll close this as a duplicate.

The whole idea of the browser extension is that access to entries is restricted by the URL.

**Comment by s-h-a-d-o-w** [comment]
I don't think it's the same because it's not an additional feature as described in the other issue but a change in how entries are looked up. Like - if I go to "example.com" that has the window title "example.com" and there's a database entry called "example", I would expect the extension to prefill those credentials.
Or at least (since it's not an exact match) show it when I click on the keepassxc icon in the form. And if I select it from there, it is obviously safe to add the URL for it.

The Android version handles it like this already, I believe.

**Comment by varjolintu** [comment]
The matching works only against URLs, not titles or anything else. And that's not gonna change.

The closest thing you can do is to trigger the Global Auto-Type from the extension (using a keyboard shortcut or the context menu when right-clicking an input field). It will also match the URL by default but can give you the same possibilities as the normal Auto-Type.
