### ISSUE TITLE
Error processing tabId: Integer -1 is too small (must be at least 0)

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#237]
Also in Firefox Nightly (system info/etc., same as https://github.com/keepassxreboot/keepassxc-browser/issues/236) a console error that seems to happen at any time I (re)load a website:

>  [Show/hide message details.] Error: Type error for parameter details (Error processing tabId: Integer -1 is too small (must be at least 0)) for pageAction.setIcon. background.js:7708:3
makeError
resource://gre/modules/Schemas.jsm:450:14
throwError
resource://gre/modules/Schemas.jsm:2195:11
checkParameters/fixedArgs<
resource://gre/modules/Schemas.jsm:2263:9
map self-hosted:292:17 checkParameters
resource://gre/modules/Schemas.jsm:2256:17
stub
resource://gre/modules/Schemas.jsm:2339:23
updateBrowserAction
moz-extension://d5479f7d-6b50-484d-9754-8869e3240b99/dist/background.js:7708:3
processPage
moz-extension://d5479f7d-6b50-484d-9754-8869e3240b99/dist/background.js:7758:5
listener/filter.ondata
moz-extension://d5479f7d-6b50-484d-9754-8869e3240b99/dist/background.js:7778:7

![image](https://user-images.githubusercontent.com/11966684/43368611-4104e2ae-9360-11e8-81e1-67c71be59c37.png)

**Comment by varjolintu** [comment]
KeePassXC-Browser doesn't have a file named `background.js` so this is clearly some other extension.
