### ISSUE TITLE
Use different credentials for different browsers

### ISSUE THREAD

**Issue by chendf24** [keepassxreboot/keepassxc-browser#2374]
Is there any way to user different credentials for different browsers (for the same URL)? I mean add some attributes in the entry which keepassxc-brower is able to identify and choose the entry only for this browser?

Thanks!

**Comment by droidmonkey** [comment]
You can restrict groups to certain browser connections. Edit a group and go to the browser tab to see those options. You cannot change the data sent _from the same entry_ by the browser.
