### ISSUE TITLE
Flatpak support?

### ISSUE THREAD

**Issue by joao-victor-lab** [keepassxreboot/keepassxc-browser#2384]
hello, has this feature because I cant setup in my machine.

**Comment by varjolintu** [comment]
Flatpak browsers are not officially supported. See:
https://github.com/keepassxreboot/keepassxc-browser/issues/1267
https://github.com/keepassxreboot/keepassxc-browser/issues/1783

**Comment by joao-victor-lab** [comment]
thanks
