### ISSUE TITLE
Ignoring a request that came "precludes" showing another

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#2393]
1. Trigger a DB unlock
2. Ignore (Close) the KeepassXC unlock window coming up
3. Trigger another DB unlock

Expected behavior:

KeepassXC unlock window is coming up again

Actual behavior:

You must bring it up yourself, and unlock - in order for the integration to work again

IIRC, it doesn't matter how many unlocks one triggers or "how much time has passed" since ignoring. It will downright not pop-up again, until "the state" is cleared

**Comment by varjolintu** [comment]
Try the current KeePassXC snapshot. It should include this fix: https://github.com/keepassxreboot/keepassxc/pull/11435

**Comment by stdedos** [comment]
Ah, right - yes. I guess you don't have beta ppa / deb packaging, right?

But good that it was "just reported last month". Sorry for the extra spam 🙏

**Comment by stdedos** [comment]
It works 🎉 🎉 🎉
