### ISSUE TITLE
Browser Extensions Cannot Connect

### ISSUE THREAD

**Issue by QL568A6** [keepassxreboot/keepassxc-browser#2394]
OS: Fedora 41
Other OS info: Fresh install - not even two weeks old
Other other OS info: This problem was not present on my prior install
KeePassXC version: 2.7.9
Installed KeePassXC from: Fedora repo (i.e. not Flatpak) 

The KeePassXC browser extensions for Chromium (on Opera) and Firefox (on Firefox) will not connect to KeePassXC. I've gone through the entire troubleshooting guide five times and the only thing that isn't exactly how it should be is the fact that keepassxc-proxy doesn't start at startup, but starting it manually does not restore functionality.

Any advice?

**Comment by droidmonkey** [comment]
How are the browsers installed? Browsers installed as flatpak will not work.

**Comment by QL568A6** [comment]
My browsers are not installed via Flatpak. Firefox is from the Fedora repo and Opera is directly from the Opera RPM repo.

**Comment by alexismarie8314** [comment]
Hello, 
I got the same issue, with extensions installed on chromium or firefox. I have try with keepassxc installed as and not as flatpack.

My actual operating system is Ubuntu24.04.1.
Regards

**Comment by QL568A6** [comment]
I am confused to report that the Firefox extension has spontaneously started working.

Here is the error message from Oepra:
`Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

**Comment by QL568A6** [comment]
> Please check that you aren't using a beta or nightly version of opera

I'm using the latest official version. Not beta. Not nightly.

**Comment by varjolintu** [comment]
I'll test a fresh Fedora install by myself and try to reproduce this.

@alexismarie8314 Your issues is probably about Snap or AppArmor. There are already plenty of threads about it if you search for them. Let's focus to Fedoda on this thread.

**Comment by varjolintu** [comment]
I installed Fedora 41, and used `dnf` to install KeePassXC. Everything worked normally with the extension. Did the same for Chromium and had no issues.

![Image](https://github.com/user-attachments/assets/b7be38a8-aebe-4b72-9978-49da3c46a9da)

What does the `strace` section say when you go through the Troubleshooting Guide? There must be some reason why the proxy doesn't start.

**Comment by QL568A6** [comment]
> What does the `strace` section say when you go through the Troubleshooting Guide? There must be some reason why the proxy doesn't start.

`strace` produces no results.

I am confused to report that after nearly two weeks of futile troubleshooting, the Opera extension has also started working for seemingly no reason.

I have yet to confirm whether keepassxc-proxy will start by itself. I will update this thread tomorrow afternoon. (in approximately 15 hours)

**Comment by alexismarie8314** [comment]
I did this command : ```sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass``` and then try to connect my firefox keepassxc browser extension to my keepassxc database, it says again that the key exchange failed, and in the terminal, with strace, I got this : 
```/home/<user>/snap/firefox/common/.mozilla/firefox/6m76pw9b.default/extensions/keepassxc-browser@keepassxc.org.xpi", O_RDONLY <unfinished ...>```

**Comment by droidmonkey** [comment]
You can't directly strace a snap

**Comment by varjolintu** [comment]
> I did this command : `sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass` and then try to connect my firefox keepassxc browser extension to my keepassxc database, it says again that the key exchange failed, and in the terminal, with strace, I got this : `[pid 5509] openat(AT_FDCWD, "/home/<user>/snap/firefox/common/.mozilla/firefox/6m76pw9b.default/extensions/keepassxc-browser@keepassxc.org.xpi", O_RDONLY <unfinished ...>`

Please keep the Ubuntu/Snap issues in the correct thread: 
https://github.com/keepassxreboot/keepassxc-browser/issues/1426
https://github.com/keepassxreboot/keepassxc-browser/issues/1828
https://github.com/keepassxreboot/keepassxc-browser/issues/1875

**Comment by QL568A6** [comment]
> You need to run strace with sudo

I did. It produced no results.

```
me@fedora:~$ sudo strace -f -p $(pgrep firefox) 2>&1 | grep keepass | tee keepass.txt
[sudo] password for me: 
me@fedora:~$ 
```
The resulting file keepass.txt is completely empty.



KeePassXC-Proxy started by itself this time at login and both extensions are working.

**Comment by droidmonkey** [comment]
Closing since this is resolved for you. You should confirm your strace is working in general by dropping the grep for keepass as well just to be sure. The proxy executable shouldn't start until a configured browsers opened.
