### ISSUE TITLE
Non-working site: qt.io

### ISSUE THREAD

**Issue by foss-** [keepassxreboot/keepassxc-browser#2395]
While KeePassXC-Browser seems fine `KeePassXC-Browser is connected to KeePassXC and has been configured using the following identifier: xxxxxx` the login on https://login.qt.io/login does not seem to be detected at all:

![Image](https://github.com/user-attachments/assets/4b09b214-24cd-4acb-8013-743e436bdb18)

Re-detect login fields does not detect login fields.

Right-click Fill username + password or fill password only does not fill information.

Firefox 133.0
KeePassXC 2.7.9
KeePass-Browser 1.9.4

**Comment by varjolintu** [comment]
Add https://login.qt.io/login to Site Preferences and enable Improved Input Field Detection

**Comment by foss-** [comment]
Confirming adding `https://login.qt.io/login` to KeePassXC-Browser Preferences > Site Preferences and ticking `Improve Input Field Detection` brings this into working state.

Thank you 🙏
