### ISSUE TITLE
Non-working site: max.com

### ISSUE THREAD

**Issue by KucharczykL** [keepassxreboot/keepassxc-browser#2397]
The actual URL is https://auth.max.com.

No autofill works, no KeePassXC extension icons are displayed, and no fields can be detected when using the Choose Custom Login Fields feature.

**Comment by varjolintu** [comment]
As a temporary solution, add `https://auth.max.com/` to Site Preferences tab in the extension settings and enable Improved Input Field Detection for it.

**Comment by KucharczykL** [comment]
Thank you for such a fast response! The workaround works! 👍
