### ISSUE TITLE
Option to skip "Browser Confirm Access"

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#240]
## Current Behavior
The plugin pops up a dialog titled "Browser Confirm Access".  If I select "remember this decision" the plugin stores the result into the database as "additional attributes".

## Problem
This slows the user down, especially when moving to KeePassXC from another tool.  It adds to the size of the database.  For users that use multiple tools, it requires more synchronisation (the other tool won't add this record).

Personally speaking I don't regard this step as necessary.  All the entries in my database are passwords that I expect to be used in the browser.  I only click to fill the password on a page where I am happy for that to happen.  I trust that KeepassXC will only fill the password if the domain matches.

## Proposed Solution
Provide an option to skip these prompts and always allow access without writing to the database.

**Comment by varjolintu** [comment]
KeePassXC Settings -> Browser integration -> Advanced -> [x] Never ask before accessing credentials.

**Comment by AdamPS** [comment]
Perfect thanks
