### ISSUE TITLE
Не подключается база в Яндекс браузере

### ISSUE THREAD

**Issue by RuslanArestov** [keepassxreboot/keepassxc-browser#2403]
Здравствуйте!

Интеграция настроена в приложении, но в браузере не подключается. В предыдущих версиях Яндекс Браузера интеграция работала.

KeePassXC - unknown
KeePassXC-Browser - 1.9.5
Operating system: Win64
Browser: Chrome/Chromium 128.0.0.0 YaBrowser/24.10.0.0

**Comment by droidmonkey** [comment]
We don't support the yandex browser. You'll have to try our troubleshooting guide.

**Comment by RuslanArestov** [comment]
Спасибо за ответ. Где можно с руководством ознакомиться?

**Comment by varjolintu** [comment]
Only English please.

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
