### ISSUE TITLE
Allow use of {pickchars} from password in browser extension

### ISSUE THREAD

**Issue by Swazib0y** [keepassxreboot/keepassxc-browser#2407]
KeepassXC supports the AutoType sequence of {pickchars} allowing a "random" sub-selection of characters for password input. It would be great if we could get the browser extension to support this sequence as well. Not sure how to flag this as a feature request. I am also suspicious - I did a lot of searching on this topic and found nothing (google, DDG, within the issues etc.) - which makes me wonder if it's already a feature and I just can't figure out how to use it. It seems to me that it would have been requested before now...?? LOL

**Comment by droidmonkey** [comment]
We will not support this in browser extension, you will have to use auto-type. Pick characters is a hostile anti-pattern that hopefully dies soon with passkeys and other modern methods. We are not investing time into anti-patterns.

**Comment by Swazib0y** [comment]
Ah, similar discussion to the core app on this topic. FWIW while I appreciate a principled stance on various security topics - this being a good example - however it ultimately reduces the functionality and therefore usefulness of the app from a user perspective. And yes we could attempt to influence our banks and various institutions to adopt different security techniques, but we all know that that is in the single digit probability of being successful.

An unfortunately auto-type isn't an option as I am using Fedora, and I believe there are Wayland restrictions preventing auto-type from working. It's an unfortunate confluence of issues coming together.

**Comment by droidmonkey** [comment]
Luckily autotype for wayland is coming soon

**Comment by Swazib0y** [comment]
Well that's exciting! Thanks for what you all do, love the app!
