### ISSUE TITLE
"Connect" button non-responsive (Linux Brave)

### ISSUE THREAD

**Issue by tscahill** [keepassxreboot/keepassxc-browser#2408]
As indicated. No error, but also no integration. 

The floating text "Connect current active database to KeePassXC-Browser" and a darker colour change in hue occur properly when the mouse icon hovers over the button, but clicking the button provides no response.

This seems quite obviously to be a different problem from Browser integration not working (Linux Firefox) :
[//github.com/keepassxreboot/keepassxc-browser/issues/2402](https://github.com/keepassxreboot/keepassxc-browser/issues/2402)

I've ensured that Brave's "shields are DOWN for oboonakemofpalcgghocfoadofidjkkk". (While not a bug, is oddly reminiscent of the legendary monster [Ogopogo](https://en.wikipedia.org/wiki/Ogopogo). 

Also, no other plugins are installed.

_This is the code from Inspect around the browser_
[Keepass-browser code check.txt](https://github.com/user-attachments/files/18135817/Keepass-browser.code.check.txt)

_copied from KeePassXC about_ 
KeePassXC - ver. 2.7.9

_From settings | KeePass-Browser - Brave_
KeePassXC-Browser - 1.9.5
Operating system: Linux x86_64 -- OpenSUSE Leap 15.6
Browser: Chrome/Chromium 131.0.0.0

_From Brave Browser "About"_
[Version 1.73.101 Chromium: 131.0.6778.139 (Official Build) unknown (64-bit)](https://brave.com/latest/  Dec 11, 2024)

_From Info Center_

KDE Plasma Version: 5.27.11
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.4.0-150600.23.25-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-8650U CPU @ 1.90GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Dell Inc.
Product Name: Latitude 5490

**Comment by droidmonkey** [comment]
So you are saying that clicking the browser extension icon doesn't produce the popup?

**Comment by tscahill** [comment]
> So you are saying that clicking the browser extension icon doesn't produce the popup?

Exactly

**Comment by droidmonkey** [comment]
Do you have brave installed as a flatpak or snap?

**Comment by tscahill** [comment]
> Do you have brave installed as a flatpak or snap? If so, it's just not going to work.

Good Point. It is installed as a flatpak. I'm going to install Brave direct from https://brave.com/linux/#release-channel-installation. I'll report back if that works or not.

**Comment by tscahill** [comment]
> > Do you have brave installed as a flatpak or snap? If so, it's just not going to work.
> 
> Good Point. It is installed as a flatpak. Opensuse Leap doesn't have it available from a configured repository.  I'm going to install Brave direct from https://brave.com/linux/#release-channel-installation. I'll report back if that works or not.

Update: Installing using brave-browser's own repository resolved the issue, and browser integration is now working.
