### ISSUE TITLE
Allow "Fill user/password and submit"

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#241]
## Current Behavior
After I click "Alt+Shift+U" to fill the password I then have to use the mouse to click the submit button.

## Expected Behavior
It would be much faster to have a single key combination that fills and then submits.  In there are multiple matches, then it would prompt to choose one, then file and submit after.

## Proposed Solution
Add a new key combination and new action for fill and submit.

**Comment by AdamPS** [comment]
Apologies that I failed to spot the duplicate

**Comment by varjolintu** [comment]
Sorry, I saw the duplicate comment and deleted it, but it seems you deleted the other comment at the same time. Actually that feature would enable just the case you want, so you can recomment if you want but it's not necessary.
