### ISSUE TITLE
integration not work in edge

### ISSUE THREAD

**Issue by NeoxyCN** [keepassxreboot/keepassxc-browser#2413]
I have checked TroubleShooting Guide  

the value in ``HKEY_CURRENT_USER\Software\Microsoft\Edge\NativeMessagingHosts\org.keepassxc.keepassxc_browser`` point to ``org.keepassxc.keepassxc_browser_edge.json`` correctly  

But ``keepassxc-proxy.exe`` still not running, must run it by hand.  

Even I run it by hand the browser integration still not work.   

Screenshot in ProcessMonitor   
![Image](https://github.com/user-attachments/assets/37c79b15-d778-443d-9bfc-4dd790c9e283)  

``org.keepassxc.keepassxc_browser_edge.json``:
![Image](https://github.com/user-attachments/assets/63951529-7bdb-4745-a5ce-80094f6f7720)

And here is output in browser console:
    KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:168 [Error client.js:403] KeePassXC-Browser - Failed to connect: Failed to start native messaging host.
global.js:168 [Error keepass.js:939] KeePassXC-Browser - No content script available for this tab.
client.js:383 KeePassXC-Browser: Connecting to native messaging host org.keepassxc.keepassxc_browser
global.js:168 [Error client.js:403] KeePassXC-Browser - Failed to connect: Failed to start native messaging host.
global.js:168 [Error keepass.js:810] KeePassXC-Browser - changePublicKeys failed: TypeError: Cannot read properties of null (reading 'postMessage')
global.js:168 [Error keepass.js:939] KeePassXC-Browser - No content script available for this tab.
2global.js:168 [Error keepass.js:939] KeePassXC-Browser - No content script available for this tab.
8global.js:168 [Error page.js:149] KeePassXC-Browser - Cannot send activated_tab message: Could not establish connection. Receiving end does not exist.

**Comment by NeoxyCN** [comment]
if I run keepassxc-proxy.exe manually, it shows blank console window.

**Comment by varjolintu** [comment]
Browser process must start the `keepassxc-proxy.exe`. Starting it manually only verifies all libraries needed are found. Something else in your Windows is probably preventing that executable from running from the browser, or preventing Windows' pipes from working. Check your anti-virus or anti-malware software.

Also check if everything works with another browser.

**Comment by NeoxyCN** [comment]
> Browser process must start the `keepassxc-proxy.exe`. Starting it manually only verifies all libraries needed are found. Something else in your Windows is probably preventing that executable from running from the browser, or preventing Windows' pipes from working. Check your anti-virus or anti-malware software.
> 
> Also check if everything works with another browser.

Thx.  

I try Chrome and Firefox Developer just now.  It seems only not work in Chromium. Both Edge and Chrome can not use integration.  I only use the anti-malware software provided by Microsoft.  

BTW, I did not install any extension except KeePassXC-Browser in Chrome.  I don't think there is any conflict with KeePassXC-Browser.

**Comment by varjolintu** [comment]
Then you must have some kind of other preventions going on, for example https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#group-policy-changes

**Comment by NeoxyCN** [comment]
> Then you must have some kind of other preventions going on, for example https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#group-policy-changes

Thank you very much!!!

It works
