### ISSUE TITLE
Non-working site (Flexera)

### ISSUE THREAD

**Issue by solarflare1027** [keepassxreboot/keepassxc-browser#2414]
Dear all,

I would like to report a non-working site. Basically it seems the website is dead. Nothing seems to work. I cannot click into the username/password fields. Sometimes KeePassXC Browser plug-in loads the credentials but then I cannot click OK.

>>Non-working site
svm.flexera.com

>>Exact login URL and the URL of your entry or entries.
https://svm.flexera.com/svm/#Dashboard

>>Dump of console output from the page (Firefox: Tools -> Browser Tools -> Web Developer Tools / Chromium-based: Tools -> Developer -> Javascript Console). Do this only if there's KeePassXC-Browser related output.

svm/#Dashboard:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">

Best regards,
Ben Kadlecik

**Comment by varjolintu** [comment]
They have some weird script on the page that prevents even clicking the input fields. There's nothing we can do here.
