### ISSUE TITLE
Does not use with pages using basic-auth and build in auth-dialogs

### ISSUE THREAD

**Issue by tps800** [keepassxreboot/keepassxc-browser#2417]
Does not work with pages using basic-auth and browser build in dialogs (pop-up window).
- Chrome (does not work)
- Vivaldi (does not work)
- Edge (does not work)
- Chromium (does not work)
- Firefox (does not work)
- Brave (does not work)
- Pale-Moon (does not work)

Page based auth does, indeed, work (auth embeded within the page).

**Comment by tps800** [comment]
![Image](https://github.com/user-attachments/assets/610f0592-bafa-4a4a-aea8-9b67374d18d5)

**Comment by varjolintu** [comment]
Have you enabled this option in the extension..?
<img width="428" alt="Image" src="https://github.com/user-attachments/assets/75673c5c-4e79-4e60-ad9b-9d3c53c36e26" />

**Comment by tps800** [comment]
Yes, looks like it was it. After activating it works now.
