### ISSUE TITLE
Passkeys browser extension options missing all of a sudden from options page.

### ISSUE THREAD

**Issue by JohnLukeBentley** [keepassxreboot/keepassxc-browser#2419]
There are some passkeys browser extension options in a passkeys section that I've recently used and are documented at https://keepassxc.org/docs/KeePassXC_UserGuide#_enabling_passkey_support. Namely the "Passkeys" section containing  and "Enable passkeys fallback".

All of a sudden this section is missing from the browser extension options ...

Reproduce:
1. Firefox > Hamburger Menu > Settings > Extensions and Themes > Extensions (Manage your extensions) > 
KeePassXC-Browser > Three dot menu > Options.
2. General Settings. Scroll down to the section " Saving credentials". 

I expect the section "Passkeys" to be below "Saving credentials". Instead there is "Updates" ...

![Image](https://github.com/user-attachments/assets/2bfadffc-77bc-4a8f-8dda-beff7b91b2aa)

The consequence is I cannot use KeypassXC based passkeys on machines (and browsers on those machines) that haven't had the "Enable passkeys" hidden option previously ticked. On a machine/browser that I've already enabled this,  KeypassXC based passkeys continues to work ... but the "Passkeys" options section remains hidden on that machine too.

I'm getting the location of where the "Passkeys" section should be from ...

![Image](https://github.com/user-attachments/assets/d385b4b2-96bc-4ef3-9894-d75257b835c3)

https://youtu.be/8p0CBE-mMYE?si=LMY7g1N9JY0T5guz&t=242

Versions:
* Windows 10. 
* KeypassXC desktop: 2.7.9
* Firefox: 133.0.3. 
* KeePassXC-Browser Version: 1.9.5

Ninja edits: added vesions; and "I'm getting the location of where the "Passkeys" section should be" with image.

**Comment by varjolintu** [comment]
There must be some problem connecting the browser to KeePassXC. The "Updates" section should show the version if your KeePassXC installation. If that version information is missing, some features are hidden because those are not supported in the older KeePassXC releases.

**Comment by JohnLukeBentley** [comment]
For reasons that are unclear I now see the passkeys section, in the browser extension, and in the updates section "You are running KeePassXC version: 2.7.9" ...

![Image](https://github.com/user-attachments/assets/c3f0b806-2df8-494f-b9e3-ca11f6d5b9bf)

I have closed and reopened FF multiple times. 

So what you write seems correct. There seems to have been some local problem with the connection between the browser extension and KeypassXC itself.

Closing this ticket.

**Comment by solenyaresearch0000** [comment]
im also having this issue. Ive re downloaded the extension on FF multiple times but its stuck on 2.7.4. When I try to update it from the settings page it does not, despite showing 2.7.10 as the latest version.

Edit: Never mind. This issue is with me running debian 11. I installed keepass via flatpak to solve for this issue

**Comment by alexn-cyber** [comment]
I ran into this as a first time keepass user. I had installed the extension and told it never to check for updates. The latest available keepassxc browser version was unavailable. I clicked 'check for updates' and disabled/re-enabled the extension in my browser, the passkeys section appeared and I was able to enable passkey support in the extension.

- Having the extension show the passkey settings when the keepassxc version is unknown OR checking for updates is off OR at least showing a 'looking for passkeys? please check for updates at least once' type message would help this not confuse users
- Having an installation option of 'enable passkey support? it adds a script ' message on user onboarding would work too
- IDK how long versions of keepassxc are supported, as of my install it was 2.7.12 - can this behavior 'assume' only supported versions of keepassxc by default and only hide those settings if a version is detected that is older?

**Comment by varjolintu** [comment]
@alexn-cyber That is exactly what the option does: hides it if the KeePassXC version is too old (feature does not exist) or KeePassXC version is not recognized. Even if no updates are checked, the KeePassXC version should be parsed when the extension makes the connection to the main application.

**Comment by alexn-cyber** [comment]
> [@alexn-cyber](https://github.com/alexn-cyber) That is exactly what the option does: hides it if the KeePassXC version is too old (feature does not exist) or KeePassXC version is not recognized. Even if no updates are checked, the KeePassXC version should be parsed when the extension makes the connection to the main application.

That is true, I left my comment above to help anyone who also may be surprised ("footgunned?") by the unintuitive link between "don't automatically check for version updates" and the resulting "silently hide all passkey settings", so they encounter less onboarding friction than I did when switching password managers.
