### ISSUE TITLE
def-shop.com error

### ISSUE THREAD

**Issue by SunnyCueq** [keepassxreboot/keepassxc-browser#2425]
### Have you searched for an existing issue?

- [x] Yes, I tried searching and reviewed the pinned issues

### Brief Summary

The login autofill functionality in KeePassXC does not work as expected for the website `https://www.def-shop.com/login`. Despite entering the correct URL in KeePassXC, the login fields are not autofilled. Instead, an error message appears:  The error references a different URL, `https://checkout.def-shop.com`, which seems unrelated to the login page. However, if the URL in KeePassXC is manually changed to `https://checkout.def-shop.com`, autofill partially works, but this behavior is inconsistent and unintended.

A screenshot is provided for reference (see attached).![Image](https://github.com/user-attachments/assets/b357a960-c272-4c07-adf7-00c72a53a40e)

### Steps to Reproduce

1. Save credentials in KeePassXC for `https://www.def-shop.com/login`.
2. Open `https://www.def-shop.com/login` in a browser.
3. Attempt to autofill the login credentials using KeePassXC.
4. (Optional) Change the URL in KeePassXC to `https://checkout.def-shop.com` and retry autofill.

### Expected Versus Actual Behavior

KeePassXC should detect the saved credentials for `https://www.def-shop.com/login` and autofill the "E-Mail-Adresse" and "Passwort" fields on the login page.

**Actual Behavior:**  
KeePassXC does not detect the saved credentials and displays the error: 
This error incorrectly references `https://checkout.def-shop.com`. If the KeePassXC entry is manually adjusted to this URL, autofill works partially, but this is not the intended login behavior.

- Browser: Firefox

### KeePassXC Debug Information

```Text
KeePassXC - Version 2.7.9
Revision: 8f6dd13

Qt 5.15.11
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 11 Version 2009
CPU-Architektur: x86_64
Kernel: winnt 10.0.26100

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- Passkeys
- SSH-Agent
- KeeShare
- YubiKey
- Schnelle Entsperrung

Kryptographische Bibliotheken:
- Botan 3.1.1
```

### Operating System

Windows

### Linux Desktop Environment

None

### Linux Windowing System

None

**Comment by varjolintu** [comment]
Just change your entry URL to `https://def-shop.com` and you are good to go. It will match all subdomains too.
