### ISSUE TITLE
The addon doesn't work with waterfox.

### ISSUE THREAD

**Issue by Bundy01** [keepassxreboot/keepassxc-browser#243]
KeePassXC - {2.3.3}
keepassxc-browser - {1.2.0}
Operating system: ArchLinux
Browser: Waterfox 56.2.2 (64 bits)
Proxy used: YES (keepassxc)

I have the following error `Timeout or not connected to KeePassXC` with Waterfox and keepassxc-browser, as if the proxy did not communicate.
I also have Firefox-dev, but with this browser communication goes well.

Debug message: 
```
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:892:5
Failed to connect: Unknown error keepass.js:868:5
Error 5: Timeout or not connected to KeePassXC keepass.js:976:5
Error 5: Timeout or not connected to KeePassXC keepass.js:976:5
Content Security Policy: "x-frame-options" ignored due to the "frame-ancestors" directive.  (unknown)
Content Security Policy: The frame-src directive is obsolete. Please use the "child-src" directive instead.
```

**Comment by droidmonkey** [comment]
We do not officially support Waterfox (or other Firefox derivatives). You will have to manually move the generated json file into the Waterfox user settings directory.
