### ISSUE TITLE
Not catching credentials on some sites

### ISSUE THREAD

**Issue by sakishrist** [keepassxreboot/keepassxc-browser#247]
## Expected Behavior
I should be able to add new credentials for the site in question (see video below).

## Current Behavior
The prompt/event for adding password was not fired up

Please note that I believe the site is dynamically proceeding with the login without a refresh, so if the event for adding a password is fired only when a new page is accessed, then this might be it.

If I add the password manually to the database, it is then filled in the page as expected.

Side notes: there are a few mini status icons on the keepassxc addon icon, but I do not know what each of them means at any given time. Having a text representation of what is going on would be nice. Note how in the video, the icon changes colours and icons many times and not even consistently at times, and I have no idea if that means something's wrong or if just a glitch.

## Steps to Reproduce (for bugs)

1. Access a vmware docker harbor site.
2. Insert some credentials (whether it would be on the sign-up or login forms)
3. Press login/signup.

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.2.0 (From the store)
Tried with github version but apparently I cannot run it due to some ID checking ... I'm not sure.
Operating system: Linux
Browser: Chromium
Proxy used: Internet Proxy? NO KeepassXCs own proxy binary, YES.

**Video demonstration: https://youtu.be/CPHK1nzgIWs**

I'll be happy to provide more details.

## Affected sites
This is a list of the sites I encounter that keepassxc-browser has issues catching the credentials, just for reference and testing material.
* https://demo.goharbor.io/harbor/sign-in
* http://torrentinvites.org/forum.php (either the small login form or the full page one)

**Comment by varjolintu** [comment]
The new credentials should be detected on form submit. However, the support for Ajax form submits is not perfect yet. Those kind of submits can go unnoticed.

The icons don't have an explanation yet in the FAQ or manuals (actually this would be a very nice addition to the manual I'm writing). The plus sign means there's an KeePassXC update available (which is logical because you are using 2.3.1). The x with red background in the bottom right means there are no logins detected for the site. However, I think we are missing one icon because here the background is grey. It should be green if the database is opened.

**Comment by sakishrist** [comment]
OK, I see. If there is any way I can help, please let me know.

I was going to suggest to spin up a container with that site, but from what I see, there is one already (their own demo container) which is located here: https://demo.goharbor.io/harbor/sign-in

**Comment by wengole** [comment]
I feel it's worth pointing out that until this (and other related new/update password triggers) is fixed, you should not be so aggressive with the deprecation of the "Legacy Browser Integration" in KeePassXC. As it stands I am completely unable to use this extension, as it simply doesn't work

**Comment by varjolintu** [comment]
@wengole So you are saying that new/updated password always work with the legacy extension? Or what extension are you using with Legacy Browser Integration?

**Comment by wengole** [comment]
@varjolintu New/updated password prompt works 99% of the time with legacy plugin (and always flashes). Currently this plugin (keepassxc-browser) has stopped prompting ever (it will still fill in passwords). I have tweaked the settings to allow -1 redirects and flash for 10+ seconds and it still doesn't even flash.
I've switched to ChromeIPass and that works as described before (99% of the time)

**Comment by wengole** [comment]
@droidmonkey When you say the "legacy" plugin, what do you mean? I've been using chromeIPass with KeepassXC's legacy integration and that works as described above.

**Comment by varjolintu** [comment]
@wengole That's strange. Can you give any site examples where chromeIPass works and this extension doesn't? Thanks.

**Comment by varjolintu** [comment]
I would still like to know more :)
