### ISSUE TITLE
KeePassXC-Browser messes up fonts on some sites in FireFox

### ISSUE THREAD

**Issue by Freekers** [keepassxreboot/keepassxc-browser#248]
## Expected Behavior
KeePassXC-Browser should leave site specific font settings alone.

## Current Behavior
With KeePassXC-Browser enabled, the fonts on some sites, such as Google and Tweakers.net, are messed up. 
Screenshot: https://i.imgur.com/H39N3MZ.png

When I disable KeePassXC-Browser, the fonts return back to normal. 
Screenshot: https://i.imgur.com/wNtj8iJ.png

## Steps to Reproduce (for bugs)
1. Enable KeePassXC-Browser in Firefox
2. Visit Google and perform a random websearch or go to Tweakers.net
3. Font should look different than with KeePassXC-Browser disabled.

## Debug info
KeePassXC - 2.3.3 (portable)
keepassxc-browser - 1.1.8
Operating system: Windows 10 64-bit.
Browser: FireFox 61.0.1 (64-bit)
Proxy used: YES

**Comment by Nothing4You** [comment]
Please perform a check for updates, this has already been resolved and is a duplicate of #244

**Comment by Freekers** [comment]
Thanks, after forcing an update check, I can confirm the issue has been resolved.
