### ISSUE TITLE
"Not a valid MatchPattern" when adding a site preference for subdomain.fe.vendor.tld

### ISSUE THREAD

**Issue by binarious** [keepassxreboot/keepassxc-browser#249]
## Expected Behavior
I should not get console errors.

## Current Behavior

I'm seeing a console error:
```
Uncaught (in promise) TypeError: https://subdomain.fe.myvendor.de is not a valid MatchPattern
    at matchPatternToRegExp (global.js:48)
    at siteMatch (global.js:91)
    at browser.runtime.sendMessage.then (keepassxc-browser.js:1431)
```

## Steps to Reproduce (for bugs)

1. Add a site preference for a domain like `subdomain.fe.vendor.tld`
2. Open any website and look into the console

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Mac
Browser: Chrome
Proxy used: NO

**Comment by varjolintu** [comment]
Does your original URL match this document?
[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns)

**Comment by binarious** [comment]
What do you mean by "match this document"?

I'd like to block this specific subdomain though. `*://subdomain.*.vendor.tdl`  or `*://subdomain.*.vendor.tdl/*` didn't work as well.

**Comment by varjolintu** [comment]
I mean does your URL match the Match Pattern structure described in the page.

`https://mozilla.*.org/` is an invalid match pattern. `"*" in host must be at the start.`. As you can see, this implementation is not perfect, but it's a start. Do you know any real URL that corresponds the URL you are using so I could test it?

**Comment by binarious** [comment]
Narrowed it down a bit: The url actually was `https://subdomain.fe.vendor.tld` (without a `/` at the end). It does work with a slash at the end. But the entry was added by clicking on "never ask for this page again".

**Comment by rkfg** [comment]
Also, when this error happens the entire extension breaks, i.e. it doesn't fill the fields anymore and doesn't suggest any credentials. Indeed, it only happens after clicking "never ask for this page again" and it doesn't when manually adding a URL. I managed to fix it by removing the offending entry from site preferences.

**Comment by varjolintu** [comment]
@rkfg That's exactly what happens. Luckily that will be fixed in the next version.
