### ISSUE TITLE
Extension icon is missing HiDPI support

### ISSUE THREAD

**Issue by ArchangeGabriel** [keepassxreboot/keepassxc-browser#25]
The icon is pixellised.

## Expected Behavior
The icon should be crisp on HiDPI display.

## Current Behavior
The loaded icon does not seem to take into account HiDPI.

## Possible Solution
Other extensions do it, so it should be easy.

## Steps to Reproduce (for bugs)
1. Open Firefox in HiDPI mode.
2. See all icons being crisp excepted for keepassxc-browser.

## General Info
KeePassXC - N/A
keepassxc-browser - 1.0

Operating system: Linux
Browser: Firefox (Nightly)
Proxy used: N/A

**Comment by varjolintu** [comment]
FYI: Chromium doesn't support SVG icons in the manifest.json.
This means a different manifest.json should be used for WebExtension and Chromium based browsers. So let's put this to a wishlist.

**Comment by ArchangeGabriel** [comment]
Is this supposed to be fixed in 1.3.3? Because it does not seems so…
![addons](https://user-images.githubusercontent.com/490531/55336853-220e5f80-548d-11e9-94e1-aea7dff4f69c.png)

**Comment by ArchangeGabriel** [comment]
Also, below is on Chromium, and even if it does not support SVG, why does Decentraleyes and uBO look OK and keepassxc-broswer does not?
![chromium](https://user-images.githubusercontent.com/490531/55337000-67329180-548d-11e9-8966-1a488a7301c4.png)

This is a minor nitpicking, but this is one of the only flaw of this extension. ;)

**Comment by varjolintu** [comment]
No it's not fixed yet. It's in the next release. Sorry or closing this.

We need to make some testing and see which one of the icons is suitable for Chromium so it doesn't look blurred.

**Comment by ArchangeGabriel** [comment]
@varjolintu Oh OK I see, the commit only allowed to fix this, but actually does not, correct?

Maybe you should ask Decentraleyes dev, @Synzvato? Or @gorhill.

**Comment by varjolintu** [comment]
I think it would be ok to just include all possible sizes to `manifest.json`. I don't have a HiDPI display so I cannot directly test it though.

**Comment by varjolintu** [comment]
I just noticed that when icons are changed dynamically in the code, the size 19x19 is always used. I'll fix this to the No jQuery branch. Of course the size of those icons must be much bigger than that.
