### ISSUE TITLE
Expired credentials are shown

### ISSUE THREAD

**Issue by sphh** [keepassxreboot/keepassxc-browser#250]
## Expected & Current Behavior

I have two entries in the KeepassXC database, one has an expiration date of 2013. Both credentials are shown in Firefox. I would expect that the expired entry does not show up in Firefox.

## Steps to Reproduce (for bugs)

1. Have two entries for the same website in the KeepassXC database.
2. Set the expiration date of one to a data in the past.
3. Open the website and click into the username field.
4. Both credentials are shown.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Linux
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
Already fixed:
https://github.com/keepassxreboot/keepassxc/pull/2116

**Comment by sphh** [comment]
Excellent! Thanks.
