### ISSUE TITLE
Icon blinks red but no popup to save or update credentials on Firefox

### ISSUE THREAD

**Issue by samueltardieu** [keepassxreboot/keepassxc-browser#253]
## Current Behavior

On Firefox62.0b14/ArchLinux (but I noticed that on earlier versions too), creating/changing a password or explicitly asking to save credentials will make the KeepassXC-browser icon blink red, as it should, but no popup will be presented to save the credentials. Only the regular "Settings / choose credentials / close db" choices are available.

I've tried disabling all my extensions, as well as adding a dummy site to the ignore list as was suggested in an earlier issue for password save problems to no avail. Clicking the icon once, twice or more during the blinking delay does not change the situation.

## Expected Behavior

The popup allowing to save or update credentials should appear when clicking the blinking red icon.

## Steps to Reproduce (for bugs)

1. Install a recent Firefox (such as 62.0b14) on Linux (or maybe other systems)
2. Install keepassxc-browser
3. Connect to a keepassxc database
4. Go to https://secure.nikonsso.com/create-nikon-account (easy to create account, correctly auto-detected fields, no captcha) and fill up the fields manually or using the password generator icon
5. Either choose "KeepassXC-Browser / Save credentials" from the page contextual menu, or just submit the form.
6. KeepassXC-Browser icon will blink red, clicking it will not make the popup for saving the credentials appear.

## Debug info
KeePassXC-Browser Version: 1.2.0
KeePassXC Version: 2.3.3 
Operating system: Linux (ArchLinux/x86_64)
Browser: Firefox (62.0b14)
Proxy used: no

**Comment by varjolintu** [comment]
A possible duplicate issue: https://github.com/keepassxreboot/keepassxc-browser/issues/211

**Comment by samueltardieu** [comment]
@varjolintu I don't think so, in #211 nothing happens (not even the blinking red icon) as far as I can tell. Here the password change / save request is recognized, the problem is the missing popup.

**Comment by samueltardieu** [comment]
Indeed, looks like it.

**Comment by varjolintu** [comment]
Please follow the issue in the thread linked earlier.
