### ISSUE TITLE
Sometimes the add new/update password dialog doesn't open when it's supposed to

### ISSUE THREAD

**Issue by qcksilver** [keepassxreboot/keepassxc-browser#254]
## Expected Behavior

When I login to a site that I haven't saved an entry in KeePassXC (or if I update the password to a website), the browser extension icon is supposed to flash, and when clicked on it should show the add new/update password dialog.

## Current Behavior

In chrome when I login to a site that I haven't saved an entry in KeePassXC (or if I update the password to a website), the browser extension icon flashes as it is supposed to, but when I click on it sometimes the icon stops flashing and the regular extension dialog opens instead of the add new/update password. It doesn't always happen, but I would say it happens more than 50% of the time. Sometimes I think I see the add new/update password dialog flash for a sec and then close.

I haven't set up the browser extension in firefox yet (though I plan to) so I don't know if it also happens in firefox.

## Steps to Reproduce (for bugs)

It seems to happen randomly and I haven't found a reliable way to replicate it unfortunately.  

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Win 10
Browser: Chrome
Proxy used: not sure - I use the default browser extension settings to connect to KeePassXC.

**Comment by varjolintu** [comment]
A duplicate issue. We are following this at https://github.com/keepassxreboot/keepassxc-browser/issues/211.
