### ISSUE TITLE
Request: Compatibility with Firefox ESR (52.6.0)

### ISSUE THREAD

**Issue by Ketrel** [keepassxreboot/keepassxc-browser#26]
## Expected Behavior
Addon should be marked compatible with Firefox ESR (Currently: 52.6.0)

## Current Behavior
Addon reports incompatible with ESR and requires 55+

## Possible Solution
Mark compatible with 52.6.0 ESR

## Steps to Reproduce (for bugs)
n/a

## Debug info
I used Nightly Tester Tools to force addon compatibility to allow the install.  The Addon appears functional in this state, so barring any major back end changes, it should already be compatible in everything but the name.

**Comment by Ketrel** [comment]
Hmm, could you give examples of what I should see if those worked, and which settings would need to be on for it to function?

(Also worst case if it's not possible, could it still be marked compatible, with the caveat that some features may not work fully?)

**Comment by varjolintu** [comment]
The first one is simple: just check if the right mouse click shows the KeePassXC context menu.
With the second one you must use [this](https://www.httpwatch.com/httpgallery/authentication/) page for testing the HTTP Auth (or some similar page) and make a temporary entry to your database to test it.

**Comment by Ketrel** [comment]
Ok, I checked both, and they do appear to be issues.
Since this version of the ESR is feature frozen, would the second option (to allow the install, but note limitations on functionality) be feasible so one doesn't have to use nightly tester tools to install?

(A good deal of people are sticking with the ESR due to legacy extensions, such as Tab Mix Plus, and FlashGot which haven't/can't be updated for Webextensions yet)

**Comment by varjolintu** [comment]
I think a notification about the limitations would be enough. Next ESR which is based is already going to be released at May, but that's not soon enough.
