### ISSUE TITLE
Can't read error message

### ISSUE THREAD

**Issue by neopostmodern** [keepassxreboot/keepassxc-browser#261]
## Expected Behavior
If there is an error connecting I should be able to read the error message. 

## Current Behavior
The error message immedeatly (<100ms) disappears.

## Possible Solution
Make it not disappear!

## Steps to Reproduce (for bugs)
1. Click on icon (Browser pop-up opens)
1. Click connect (Browser pop-up closes)
1. Connect fails
1. Click on icon (Browser pop-up opens)
1. Error message immediately disappears

## Debug info

KeePassXC - 2.3.1 (from repo)
keepassxc-browser - 1.2.0
Operating system: Linux (Ubuntu 18.04)
Browser: Firefox 61
Proxy used: YES

**Comment by varjolintu** [comment]
So what is shown in the popup when the error message disappears?

**Comment by neopostmodern** [comment]
The same as in step 1 (I can click connect etc.)

**Comment by varjolintu** [comment]
Why does the connection error happen? Do you click Cancel in KeePassXC or what's the behaviour here?

**Comment by neopostmodern** [comment]
I can't figure out, that's the entire point.
No pop-up opens in KeePassXC itself.

(It has somehow magically solved itself btw since I restarted and I have successfully connected now, but that's not the point of this bug report.)

**Comment by varjolintu** [comment]
IIRC, there's no separate error message if the connection fails. The connect button just stays visible. Maybe this error message flash was just because of the element hiding was too slow in the popup.

**Comment by neopostmodern** [comment]
Do you mean "the element hiding was too *fast* in the popup."?
But yes, the error message was part of the pop up (browser extension side).

**Comment by varjolintu** [comment]
I still mean: too slow. Was the background red?

**Comment by neopostmodern** [comment]
Yes.

**Comment by varjolintu** [comment]
Then it's the error message for KeePassXC upgrade. And because it's flashing, hiding the element is too slow.

**Comment by neopostmodern** [comment]
Ah, so the error I was experiencing was never propagated to the UI while on the other hand the non-error that I should update was visible because it didn't hide in time?
Now I understand why this conversation took such a weird path. Which means there is at least one fixable issue (hiding the element in time) and another issue (the unknown error I was experiencing) which we can't fix since I can't troubleshoot.

**Comment by varjolintu** [comment]
That's the weird part because all the elements should already be hidden at the popup load. I need to verify that and try to reproduce it.

For troubleshooting the connecting issue itself, please see [this guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself).

**Comment by neopostmodern** [comment]
As stated above, the connecting issue magically disappeared after a restart, so I unfortunately can't help.

As for the disappearing warning: It happens even now that I'm connected. Knowing what it says, I can confirm (from the milliseconds its visible) that is in fact the "outdated version" thing. Do you want a screengrab or something?

**Comment by varjolintu** [comment]
Still having this issue? A screengrab would be helpful, and of course if you can debug the popup itself, it would help even more.
