### ISSUE TITLE
Automatic fill-in for golem.de doesn't work

### ISSUE THREAD

**Issue by sam1919** [keepassxreboot/keepassxc-browser#262]
Automatic fill-in for golem.de doesn't work:

URL: https://forum.golem.de/login.php?119965
URL in the KeePassXC entry for the site: https://forum.golem.de/
There's only one entry in KeePassXC for this site.

If I right-click on the username field and select "Fill User+Pass" the fields will be filled in successfully.

KeePassXC - 2.3.3-snapshot
keepassxc-browser - 1.2.0
Operating system: Linux
Browser: Chromium

**Comment by varjolintu** [comment]
This happens because we check the minimum element size in the page and ignore any input fields that are too small to see. The value was 16 pixels which is still quite large (forum.golem.de as 14px), so in the future the value will be half of it.
