### ISSUE TITLE
FR: Autoreload

### ISSUE THREAD

**Issue by gerroon** [keepassxreboot/keepassxc-browser#264]
Hi

It would be very nice if the addon does reloads regularly, and once it find an open databse it connects to it automatically. At the moment when it looses connection to the database I have to first reload from the interface and I need to click connect database.

Can these steps be automated?

thanks

**Comment by varjolintu** [comment]
This can be possible after release of KeePassXC 2.3.4.

**Comment by gerroon** [comment]
@varjolintu  Awesome, sounds great.
