### ISSUE TITLE
Clarification:  Should KeePassXC "Enable Auto-Type for this entry" affect Browser Auto-Fill?

### ISSUE THREAD

**Issue by k8oi** [keepassxreboot/keepassxc-browser#265]
It seems that the browser extension does not "use" the "Enable Auto-Type..." flag in the KeePassXC entry.

I think it makes sense for the Auto-Fill to be consistent between the KeePassXC app and the browser plugin.

Thoughts?

**Comment by k8oi** [comment]
For example:
I have 2 entries for a single url  www.abc.xyz
One entry is for web/http access and has the "Enable Auto-Type" flag selected
Other entry is ssh userid/password and has the "Enable Auto-Type" flag NOT selected

When visiting http://www.abc.xyz I am given both entries as drop down options on the webpage.

**Comment by varjolintu** [comment]
Just deny the access to the entry you don't want to see in the page (via attributes)?

**Comment by k8oi** [comment]
I'm sorry, I don't understand how to deny access.

What attributes are you describing? Where are they located? 

Point me to a URL and I'll read, I just can't find any info on this.

Thank you!

**Comment by k8oi** [comment]
Got it - thank you for the help!

I moved the url from the Allow to the Deny setting within the KeePassXC-Browser Settings and all works well!
