### ISSUE TITLE
[support] Can’t connect KeePassXC-Browser with KeePassXC - custom browser location

### ISSUE THREAD

**Issue by omega3** [keepassxreboot/keepassxc-browser#266]
I can't connect KeePassXC-Browser with KeePassXC. I use Firejail with option --private which creates a fake like /home location as a jail environment. 
I run it by:
firejail --noprofile --private=/home/user_name/custom_folder_name/ chromium

I use Chromium and Opera on Manjaro Linux.

I set KeePassXC like in guidelines
https://i.imgur.com/rwMPCZT.png

I followed KeePassXC wiki but I have no idea where to find
`src/proxy/keepassxc-proxy`

I don't even know if this any file on system?
There is no /src location in Manjaro root file system tree.
What should be a full path?

https://keepassxc.org/docs/keepassxc-browser-migration/

> select your custom proxy application

I have no idea what is the name of proxy application on Manjaro.

Just pasting it in “Use a custom proxy location” doesn’t work.

If you go to KeePassXC-Browser settings there is Connected databases menu and I have “No connected databases found.”

If you use KeePassXC please give me detailed instructions and proper paths for Manjaro.

Other user of Manjaro report that if they have default location it works for them. So it only a matter of pasting appropriate data, I think.

Please, help.

**Comment by varjolintu** [comment]
See [this](https://github.com/keepassxreboot/keepassxc/issues/1820) issue for a possible solution.

**Comment by omega3** [comment]
Although this linked solution works it limits functionality of firejail. Using --private option is another layer of security. 

I run Firefox like this
`firejail --private=/media/data/jail/  /usr/lib/firefox/firefox`

Even if I run keepassxc in the same –private as Firefox, Firefox extension can’t connect to keepassxc database even if it is moved to the same path (private home)

Would it be possible to make browser extensions to read .config/keepassxc and whatever is necessary from the same private jail location that Firefox is run? For example:
/media/data/jail/.config/keepassxc

Is this a problem of .config/keepassxc or something else? It would be nice if I could only copy .config/keepassxc from default home to private /media/data/jail/.config/keepassxc

Forgive me my ignorance. I hove no idea how this browser extensions connect to database.

**Comment by varjolintu** [comment]
@omega3 Extensions does not read KeePassXC configuration files. You need to make sure where the sockets and Native Messaging script files are.

For more info, read https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging and https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide.

**Comment by droidmonkey** [comment]
You could use the snap version of KeePassXC which puts the socket communication file in ```~/snap/keepassxc/common/```

**Comment by omega3** [comment]
@varjolintu 
That inspired me to check what is happens in .mozilla folder when I click on connect to database. I opened Firefox normally, I mean from terminal: firefox (without any firejail) and I noticed it creates:
native-messaging-hosts folder. I moved this folder to my firejail custom home path (in my case /media/data/jail/.mozilla). And it works. Thank you. 

@droidmonkey
Good to know. Thank you.
