### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by gyuris** [keepassxreboot/keepassxc-browser#27]
Please make this extension translatable. It would be great here: https://www.transifex.com/keepassxc/public/

**Comment by varjolintu** [comment]
I opened a PR for this. You can follow the progress there.
https://github.com/keepassxreboot/keepassxc-browser/pull/37

**Comment by gyuris** [comment]
It's great to see that we have `_locales/en/messages.json`. Can you upload language file to Transifex please? Can we start to translate?

**Comment by droidmonkey** [comment]
Your wish is my command: https://www.transifex.com/keepassxc/keepassxc-browser/dashboard/

**Comment by droidmonkey** [comment]
I believe you can request access, no?

**Comment by gyuris** [comment]
Normally I should have access when I am part of a team. I can only request a language. I requested Hungarian to KeePassXC-Browser project. Can you accept?

Maybe to problem is that in KeePassXC there are 47 languages and in the KeePassXC-Browser only 25.

**Comment by droidmonkey** [comment]
Gotcha, fixed it. I removed a bunch of languages to narrow down the scope initially.
