### ISSUE TITLE
KeePassXC-Browser has encountered an error:  Timeout or not connected to KeePassXC

### ISSUE THREAD

**Issue by metsatron** [keepassxreboot/keepassxc-browser#270]
## Expected Behavior

The KeePassXC plugin should communicate between the web browser and the KeePassXC client.

## Current Behavior

KeePassXC-Browser has encountered an error:
Timeout or not connected to KeePassXC

## Possible Solution

Possible solution would be to add support for non-proprietary or black-box binary containing web browsers.

## Steps to Reproduce (for bugs)

1. Install the KeePassXC plugin on any privacy focused Firefox or Chromium fork.
2. Restart the browser.
3. Try to connect to KeePassXC Database.
4. Receive timeout warning..

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: GNU/Linux
Browser: Waterfox/Iceweasel-Hardened/Iridium/Ungoogled-Chromium/Tor Browser
Proxy used: NO

**Comment by varjolintu** [comment]
Related issue: https://github.com/keepassxreboot/keepassxc/issues/1594.

As said in https://github.com/keepassxreboot/keepassxc-browser/issues/269, at this point it's the easiest way to copy or make a symbolic link of the native messaging script file to the browser's configuration directory.

Or you can use the following [template](https://github.com/keepassxreboot/keepassxc-browser/wiki/Native-messaging-script-files).
