### ISSUE TITLE
Allow use of AutoType patterns from browser plugin

### ISSUE THREAD

**Issue by stratacast** [keepassxreboot/keepassxc-browser#274]
## Expected Behavior

Currently, I see only options for username and password, pass only, or totp. It would be nice if the extension could also collect custom autotypes from the database. Especially since websites are so awesome and don't understand that a sign in form should just be username/password.

## Current Behavior

Currently, using the existing behavior, there are some websites that you can't use the browser integration with because you require a custom autotype to sign into the website, which means you have to go straight to the database. 

## Possible Solution

Collect custom autotype information from the database and let it be used with the associated website.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Linux
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
@droidmonkey I'm not sure if this has anything to do custom attributes.

@stratacast You mean retrieving Auto-Type info for the page instead of usin Global Auto-Type?

**Comment by droidmonkey** [comment]
I had to read it 5 times, but that's what I understood from the expected behavior.

**Comment by stratacast** [comment]
Sorry I was sick as I was trying to type this <grin> basically, if an entry has a custom autotype sequence, have it use that instead just entering info into the username/password fields. This would resolve issues like signing into websites such as Amazon, which have you go {USERNAME}{ENTER}{PASSWORD}{ENTER}. So if a user has a custom defined auto-type sequence, they can apply that from the right-click menu. I hope that clears things up.

**Comment by varjolintu** [comment]
@stratacast That does. But I'm not sure how it's more efficient than use the Global Auto-Type.

**Comment by droidmonkey** [comment]
AutoType and browser plugin are two separate beasts entirely. I wouldn't cross breed this functionality.

**Comment by varjolintu** [comment]
That may be even possible. We can of course investigate this. It could solve problems with pages that have some strange frames/code/etc that prevents the input field detecting.

**Comment by droidmonkey** [comment]
It would also solve the problem of the window matching for websites

**Comment by varjolintu** [comment]
The biggest problem here is that if the extension doesn't identify any input fields on some page, there's no way to select the correct credential on which to use the Auto-Type. It would work if the extension could trigger the Global Auto-Type, but then again it's easier to use the keyboard shortcut set in KeePassXC.

**Comment by varjolintu** [comment]
I tested this a little bit. It works quite nicely. If no URL is set to the entry Auto-Type still works with the window title set.

**Comment by varjolintu** [comment]
As there are multiple requests for this, let's see if this could be done for the next release.

The plan is:
- Use a keyboard shortcut from KeePassXC-Browser that triggers Auto-Type
- If no credential fields are found for the page, trigger a global Auto-Type instead

**Comment by varjolintu** [comment]
Replaced by: https://github.com/keepassxreboot/keepassxc-browser/issues/1191
