### ISSUE TITLE
No credentials from KeePassXC 2.3.4

### ISSUE THREAD

**Issue by Hativ** [keepassxreboot/keepassxc-browser#275]
After upgrading from KeePassXC 2.3.1 to 2.3.4 using the official Ubuntu ppa keepassxc-browser doesn't get credentials anymore. After downgrading to 2.3.1 it works again. Using "Fill User + Pass" gives the notification "No logins found" (or something like that, out of my head).

What can I provide to find the issue?

## Debug info
KeePassXC - 2.3.4
keepassxc-browser - 1.2.0
Operating system: Kubuntu 18.04
Browser: Chromium 68.0.3440.106
Proxy used: YES

**Comment by varjolintu** [comment]
With 2.3.4 the entry URL scheme is more restricted. So please check that your entry has a correct scheme in the URL in comparison to the web page URL.

**Comment by Hativ** [comment]
Ok, that's it. But that is a rather unfavorable change. So now I have to go over thousands of credentials and add https..

**Comment by varjolintu** [comment]
That is a PITA. Another option is to uncheck "Match URL scheme" but it seems the option has been broken a long time. The easiest option is to add this [PR](https://github.com/keepassxreboot/keepassxc/pull/2232) and compile the sources.
