### ISSUE TITLE
Extension seems to automatically open KeePassXC on browser start

### ISSUE THREAD

**Issue by nebulon42** [keepassxreboot/keepassxc-browser#276]
## Current Behavior
When having the extension enabled in Firefox on Ubuntu 18.04 it seems to automatically start KeePassXC, which then comes to front. Is this the expected behavior? I find this a bit annoying and I'm not sure if this is necessary.

## Possible Solution
I can imagine that for some automatically starting KeePassXC would be nice or even required, but maybe add a switch in the extension settings that is checked by default and where one can disable the autostart behavior.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Ubuntu GNU/Linux 18.04
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
This kind of autostart happens only if you have disabled the proxy option in the Browser Integration settings. The default behaviour is to enable the proxy. Then the browser extension doesn't control KeePassXC directly via native messaging API.

**Comment by nebulon42** [comment]
I think the proxy is enabled or at least I didn't change the settings (the checkbox at "proxy between extension and KeePassXC" is there). What I forgot to mention is that I use the Flatpak variant of KeePassXC. I first used the shipped variant which was 2.3.1, but it complained that my version is outdated. So I changed to the Flatpak variant. Seems like the proxy isn't running:

```
xyz   3971  3806  0 17:48 tty2     00:00:00 /usr/lib/flatpak/flatpak-bwrap --args 30 command-wrapper.sh /home/xyz/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
xyz   3978  3971  0 17:48 tty2     00:00:00 /usr/lib/flatpak/flatpak-bwrap --args 30 command-wrapper.sh /home/xyz/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
xyz   3979  3978  0 17:48 tty2     00:00:00 /bin/sh /app/bin/command-wrapper.sh /home/xyz/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
xyz   3980  3979  0 17:48 tty2     00:00:02 keepassxc /home/xyz/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
```
I'm new to the whole Flatpak/Snap/whatever thing so I'm not sure what is going wrong.

**Comment by varjolintu** [comment]
Maybe [this thread](https://github.com/flathub/org.keepassxc.KeePassXC/issues/13#issuecomment-400784869) will help you.

**Comment by nebulon42** [comment]
Thanks for your help! I have now switched to your PPA. Now the proxy is running and I don't see the behavior any more, like you said.

**Comment by rugk** [comment]
FYI, for everyone following: I have found a working around involving some manual steps you need to do though for KeePassXC<->Firefox communication, if Firefox is flatpaked/sandboxed (works if KeePassXC is sandboxed or not). [Read the full write-up/tutorial here.](https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437?u=rugk)
