### ISSUE TITLE
"String fields #" not working

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#279]
## Steps to Reproduce
1. Visit https://nationwide.onlineips.co.uk/logon/logon.aspx
2. Choose custom credential fields in this order: Client reference; Password; Day; Month; Year.  Storage.js now contains `["jQuery342845639","jQuery342845640","ctl00_ctl00_ctl00_BaseContentPlaceHolder_BaseContentPlaceHolder_MainContentPlaceHolder_ucLogon_ucLogin_datDOB_txtYear"]`
3. Create an entry in the database with a user name (anything you like).  As explained in #122, create 3 additional attributes of the form "KPH: " for the three date fields.  Leave the password blank (this is a financial site, so I'm just using KeePassXC to remember the other 4 fields and save me typing them, then I type the password by hand).
4. Press AS+U.
5. Hard refresh the page and press AS+U again.

## Expected Behavior
4 fields are filled both times.

## Current Behavior
4 fields are filled the first time.  Only the username is filled the second time.  If the cursor is in the year field, that field will be filled too, but not the day/month.

If I Choose custom credential fields again, I get one more try that works, then after that it doesn't work again.

## Debug info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.11.1
- libgcrypt 1.8.3

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
I tried this with both Firefox and Chromium but I couldn't reproduce the problem. Even autofill works normally. Could you debug the extension content script to see if anything strange happens? (Right click the page, select `Inspect element` or `Inspect`, depending on the browser.

**Comment by AdamPS** [comment]
@varjolintu Thanks for your time.

In function fillInStringFields
`const currentField = _fs(fields[i]);`
Returns null for each of 
```
jQuery342845639
jQuery342845640
ctl00_ctl00_ctl00_BaseContentPlaceHolder_BaseContentPlaceHolder_MainContentPlaceHolder_ucLogon_ucLogin_datDOB_txtYear
```
This seems to be because `data-cip-id` is only set on the username (client reference) field on not on any other field.

I don't know the code at all, so it's hard for me to figure out where to look next.

**Comment by varjolintu** [comment]
Have you tried to delete the Custom credential fields for the page and add them again? I had `data-cip-id` set on each element.

**Comment by AdamPS** [comment]
Yes absolutely, if I configure the custom credential fields again it sets `data-cip-id`.  But next time I load the page they are missing again.  At the moment I would have to configure the custom fields every time I want to log in.

**Comment by varjolintu** [comment]
Are you using Chrome/Chromium or Firefox? If latter, can you try to make a new temporary profile and try if everything works? I still cannot reproduce this.

**Comment by AdamPS** [comment]
Thanks @varjolintu it seems like this was a strange local problem.

- I am using Firefox and it worked in the temporary profile.
- Back in the main profile I turned off all other add-ons but still broken.
- I removed the KeePassXC-Browser extension entirely and installed again, and it _seems to be working_.
