### ISSUE TITLE
Efficient logon with keyboard

### ISSUE THREAD

**Issue by AdamPS** [keepassxreboot/keepassxc-browser#280]
## Expected Behavior
I would like to login as fast as possible:

- Press AS+U to fill fields
- If there are multiple logins, can press enter to select the first one
- Press Enter to submit form

## Current Behavior
Often it doesn't work so easily:

- AS+U only works if an input has focus, so I have to use the mouse to give focus.
- If there are multiple logins I have to press an extra cursor down before I can use enter to select the first one.
- After selecting one of the multiple logins, there is still a prompt to select which login to use, and sometimes I have to press enter again to get past it.
- Sometimes after KeePassXC has filled fields, the focus is lost, so I have to use the mouse again.

## Possible Solution
Make it work reliably as described in Expected Behavior.

## Debug info
KeePassXC - Version 2.3.3
Revision: 0a155d8

Libraries:
- Qt 5.10.1
- libgcrypt 1.8.2

Operating system: Windows 7 SP 1 (6.1)
CPU architecture: x86_64
Kernel: winnt 6.1.7601

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by droidmonkey** [comment]
This is more a website issue. We should not be forcing focus on login fields.

**Comment by varjolintu** [comment]
Using Global Auto-Type would be much quicker for situations like this. It handles the focusing too.

**Comment by AdamPS** [comment]
> This is more a website issue. We should not be forcing focus on login fields.
OK, fair point.  However most of my points seem to be valid even so

- Allow AS+U to work in all cases, without caring where the input focus is.  Surely if the user presses AS+U then they want the login to be filed.
- If the user has just chosen one of multiple logins (i.e. there is now an exact match of username), then don't prompt again to select.

**Comment by varjolintu** [comment]
> Allow AS+U to work in all cases, without caring where the input focus is. Surely if the user presses AS+U then they want the login to be filed.

This could be done. If there's no focus to the username field, using the keyboard shortcut focuses to it before filling.

> If the user has just chosen one of multiple logins (i.e. there is now an exact match of username), then don't prompt again to select.

Indeed the reopening of the menu is not needed after credentials have been just selected.

**Comment by AdamPS** [comment]
> Using Global Auto-Type would be much quicker for situations like this. It handles the focusing too.

OK, now I'm confused!  When I use Global Auto-Type, I find that I have to put the focus into the username field first.  That's what I expect - after all it's just going to type Username, TAB, Password, ENTER.

My situation is merely that I want to fill logins.  If I should use Global Auto-Type for that, then I don't understand when I would use the browser plug-in.

The browser plug-in seems like a much better approach, as it can actually look into the web page and understand all the fields in the form.  I would expect that features such extra string fields would be very difficult without a browser plug-in.

**Comment by AdamPS** [comment]
Summary of discussion:

As @droidmonkey points out, we must not force focus when the page loads or anything like that.

However if the user presses AS+U That's different - that is a clear indication that we should fill in the fields as efficiently as possible.  It's hard to see that a user will complain "I pressed AS+U without focus in a field so I expected nothing to happen - why did it fill the fields".

UI studies have shown that switching from mouse to keyboard is a _big_ slow down.  So it would be great to enhance AS+U so that it works if no field is focused.  Thanks!

**Comment by varjolintu** [comment]
@AdamPS I'll make some adjustments to the next version. Thanks for the suggestions!

**Comment by AdamPS** [comment]
Many thanks.  Once that's done I'll send you guys a donation for  your good work.  I'm very happy to test a pre-release version.

**Comment by varjolintu** [comment]
I tried to fill the credentials from keyboard without having focus to the username field. It can still fill it correctly. In these cases the extension detects the username & password input field combination and fills it. So the detection is already there. If you wish you can debug the extension content script keepassxc-browser.js starting from line 1638 (cip.fillInFromActiveElement function) and see what really happens. Or is the page(s) you are trying to use the ones with only username field visible?

**Comment by AdamPS** [comment]
OK sorry for the confusion.  As you helped me discover on another issue, my profile was broken for 1 week, but I didn't realise it.  Here is a new report now my profile is back working again.

1) After I have filled credentials with AS+U, I would like to submit.  If an input has focus then I can press enter, but otherwise I have to use the mouse which is slow.  Ideas:
a) AS+U could leave the focus on one of the fields that it filled.  Possibly @droidmonkey would class this as "forcing focus" and say we shouldn't do it.
b) Even better/faster and cleaner: create a new key combination (e.g. AS+S) for "fill+submit".  I would be very happy with this one:-)

2) If there are multiple matching logins, AS+U prompts me to select from a list.  It's great that KeePassXC allows me to configure the sort order, so I can make the one I use 90% of the time come up first.  However the select list initialises with no item selected, so I have to press cursor down to get to the first item then enter to select it.  If KeePassXC could start with the first item selected then it would be faster, I could just press enter.

3) After I select one of the matching logins, KeePassXC should not immediately prompt again.

In my work as a web designer I log on to different websites a lot, so every little saving really helps.

**Comment by varjolintu** [comment]
I have been making some improvements to autocomplete with the [No jQuery](#128 ) PR.
Autocomplete has the following improvements:
- First item is always selected by default
- It can be used without a mouse: `Backspace` or `Delete` opens the list when input field has no value. Arrows and `Enter` selects the credentials. Using `Escape` or `Tab` (focus disappears) closes the autocomplete.

**Comment by AdamPS** [comment]
That's great news, I look forward to the next release with it in.  The link above didn't work for me - hopefully this one will:  #128

**Comment by varjolintu** [comment]
Closing this as all the improvements have been implemented.

**Comment by AdamPS** [comment]
@varjolintu Great work I confirm that items 2 and 3 are fixed, and I have sent a donation via PayPal.  However as far as I can see item 1 is not fixed.  Please can you reopen?  Or I can raise a new issue.  You are doing great work and I will donate again if you can fix this last part.  Thanks!

**Comment by varjolintu** [comment]
@AdamPS Extension settings -> Auto-submit login forms.

**Comment by varjolintu** [comment]
And a big thank you for donations!

**Comment by AdamPS** [comment]
@varjolintu Amazing thanks.  Works perfectly except I found #511.
