### ISSUE TITLE
Passwords are no longer filled for subdomains

### ISSUE THREAD

**Issue by joe776** [keepassxreboot/keepassxc-browser#283]
## Expected Behavior
If I'm on the login page on a sub-domain, I want to be able to fill in the credentials from the top level domain. For example, i have stored credentials for `company.com` and I'm on a login dialog on `service.company.com`. I want to use the same credentials there.

## Current Behavior
No credentials are offered. This used to work in version < 2.3.4

## Possible Solution
Match sub-domains again/make the URL matching a suffix matching. Possibly as (global) option.
Saving the same credentials for all sub domains would work as workaround, but is annoying when passwords change.

## Debug info
KeePassXC - 2.3.4
keepassxc-browser - 1.2.0
Operating system: MacOS 10.13
Browser: Chrome
Proxy used: NO

**Comment by varjolintu** [comment]
This may have worked before because also the entry title was approved as a match. But it's indeed broken now. As a workaround, you can make a clone of the original entry with username and password as a reference, but then change the URL.

**Comment by joe776** [comment]
Thanks! I never noticed the clone+reference option. Works like a charm as workaround.

**Comment by SmoochiesBoss** [comment]
Also confirming this as a bug. I can't make clones of each entry for every possible subdomain. Too many entries. Hopefully this will get fixed sooner rather than later!

**Comment by varjolintu** [comment]
I'll try to fix this ASAP.

**Comment by droidmonkey** [comment]
@SmoochiesBoss If you just remove the subdomain then it will match.

**Comment by SmoochiesBoss** [comment]
Definitely not working for me, even for my entries with no subdomains.

E

**Comment by varjolintu** [comment]
Related PR here: https://github.com/keepassxreboot/keepassxc/pull/2253.

**Comment by mhow2** [comment]
Hi there, could we have the PR merged please ? I'm having cloned-by-reference copy of my entries all over the place :)

**Comment by varjolintu** [comment]
@mhow2 While waiting for 2.4.0, let's hope that PR gets merged soon so you can use [snapshot build](https://snapshot.keepassxc.org/) for a workaround solution.
