### ISSUE TITLE
HTTP auth with multiple logins stopped working on Firefox 62

### ISSUE THREAD

**Issue by vanous** [keepassxreboot/keepassxc-browser#284]
## Expected Behavior

When multiple logins are available, upon clicking KPXcBrowser, selection appears to choose correct credentials entry. This worked on until update of Firefox to 62.

## Current Behavior
When landing on a page with HTTP auth dialog, the KPXc message about multiple credentials is displayed, but upon clicking on KPXc icon, selection does not show up and it's therefore not possible to select credentials.

## Debug info

KeePassXC-Browser Version: 1.2.0
KeePassXC Version 2.3.3
Operating system: Debian
Browser: Firefox Quantum 62.0b16 (64-bit)
Proxy used: NO

**Comment by varjolintu** [comment]
Please upgrade to the latest beta and try again.

**Comment by vanous** [comment]
Thank you, will do. Excuse my ignorance but where do i get the beta from? Searching and browsing didn't reveal anything.

Thank you

**Comment by varjolintu** [comment]
Firefox Beta. The latest version is 20. If it's not found from your default repository, I suggest you download it manually from [https://www.mozilla.org/en-US/firefox/channel/desktop/](https://www.mozilla.org/en-US/firefox/channel/desktop/) or some other source.

**Comment by vanous** [comment]
OK, thank you. I am on 62.0~b16-1 and will wait for .19 to trickle to debian repos.

cheers
