### ISSUE TITLE
Confirm Access window is triggered every time the tab is visible and ignores allow, deny and cancel

### ISSUE THREAD

**Issue by sudhirkhanger** [keepassxreboot/keepassxc-browser#287]
## Expected Behavior

Allow, deny, and dismiss the option of the confirm access window should be honored.

## Current Behavior

Supposed I have two windows open. Window one has is where password can be filled and window two can be anything. If I switch between the two windows I will be constantly shown then the confirm access dialog. I can allow, deny or dismiss. It doesn't matter as long as I switch between the tab I will be shown the confirm access dialog.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/841656/45008782-1c998580-b022-11e8-9804-5a0f2c41d1ff.gif)

## Steps to Reproduce (for bugs)

1. Tab 1 where password is to be filled
2. Tab 2 any tab
3. Make sure the confirm access will be displayed.
4. Switch between the tabs.

## Debug info

KeePassXC - 2.3.3
keepassxc-browser - 1.2.0
Operating system: Linux Fedora 28 with KDE 5.13.4
Browser: Chrome 68.0.3440.106 (Official Build) (64-bit)
Proxy used: NO

**Comment by varjolintu** [comment]
It will be honored if the enable the checkbox `Remember this decision`.

**Comment by sudhirkhanger** [comment]
@varjolintu oh! Is that so? Where is this remember this decision is saved if I change my mind?

**Comment by varjolintu** [comment]
You can modify the setting from editing the Entry, and then go to Advanced tab from the left panel. There should be a `KeePassXC-Browser Settings` attribute. Modify its value or delete the whole attribute.
