### ISSUE TITLE
Cannot access right-click menu in custom credential fields

### ISSUE THREAD

**Issue by srwareham** [keepassxreboot/keepassxc-browser#29]
## Expected Behavior

After setting custom credentials fields for a webpage, the user should be able to right click on a newly-designated credential field to access the KeepassXC-Browser dialog. Symmetrically, right clicking on a field no longer designated for credentials should not prompt for the menu (secondary concern).

## Current Behavior

Right clicking on "old" credentials fields will always present the KeepassXC-Browser dialog. Right clicking on a newly designated credentials field will not present the KeepassXC-Browser dialog. This is particularly problematic if a page were to contain no preexisting credentials fields (the user would then be unable to access the KeepassXC-Browser dialog at all).

## Steps to Reproduce (for bugs)

1. Open a webrowser to any webpage with at least 3 fields.
2. Click KeepassXC-Browser extension icon->Choose own credential fields for this page
3. Select a new username (and/or new password) field.
4. Right click on old, now defunct username field. Observe right click menu dialog for KeepassXC-Browser is present
5. Right click a newly-designated username field. Observe right click menu dialog for KeepassXC-Browser is not present

## General Info
KeePassXC fork - 2.3.0 (default settings)
keepassxc-browser - 1.0.0 (default settings)

Operating system: macOS 10.13.3
Browser: Firefox 58.0.2 (64 bit)
Proxy used: No

**Comment by varjolintu** [comment]
There's a known bug in Firefox that all editable fields doesn't show the context menu. This is already fixed but will be present when Firefox 60 is released. Could you test if this happens with Firefox Nightly? Alternatively you can test the same with Chromium where this kind of bug doesn't exist.

**Comment by srwareham** [comment]
Just tested on Firefox Nightly and the no context-menu issue seems to be resolved. From the current behavior, I assumed the dialog was only meant to be visible on credential fields. Having it available from all fields seems reasonable to me, though.

One question: what is the desired behavior for when the user accesses the dialog from a non-credential field? In my limited testing right now, it seems that the username will be whichever field is right-clicked on. What if the user designates custom credentials fields for the page? Should it not pull from the username-designated field and not the one clicked on? How about the password in that situation?

**Comment by varjolintu** [comment]
I need to do some testing with those kind of situations. It shouldn't be possible to fill a password to a non-password field. The only thing that you can fill to any field you seletect is TOTP. This is because TOTP fields cannot be identified 100%. They haven't got an unique input type.

**Comment by varjolintu** [comment]
Firefox 60 is finally released, so closing this issue.
