### ISSUE TITLE
Handle single field login forms without error

### ISSUE THREAD

**Issue by Gunni** [keepassxreboot/keepassxc-browser#290]
When a site provides username field and password field as seperate pages, handle that gracefully.

## Expected Behavior
When a page only has a username field, don't give an error about not finding a password field.

## Current Behavior
If a page only has a username field, the addon emits a "Cannot find field to fill in" error

## Possible Solution
Ignore that error, assume the user is right, especially if the field definition is manual and either username or password is not defined by user.

## Steps to Reproduce (for bugs)
Go to https://portal.office.com/ (as an example), it has a form like i described, and i just witnessed the reported error.

Log in with a test account or your office account using the addon. You may need to chose custom fields due to the addon not detecting the username field.

## Debug info
Just the browser-polyfill.min.js but that's been there for months, on all sorts of domains, then just: `Navigated to https://adfs.example.com/...`.

KeePassXC - `2.3.4`
keepassxc-browser - `1.2.0`
Operating system: Win
Browser: Chrome
Proxy used: NO

**Comment by varjolintu** [comment]
You are right, that error is not needed.

**Comment by generic-user** [comment]
This happens on google login forms as well.

**Comment by varjolintu** [comment]
Will fix that tomorrow. The fix list for next release is looking quite good already. Thanks for reporting the issues :)

**Comment by generic-user** [comment]
Hi, thanks for the fix. ;)

## But...
It is working now in the password field, but I still can't let it fill in my username.

Oh, this is on the google login page.

**Comment by varjolintu** [comment]
@generic-user Have you added the site (`https://accounts.google.com/*`) to your Site Preferences and enabled the Username-Only option?

**Comment by generic-user** [comment]
OK, thanks. Did not know I had to add it manually.

**Comment by varjolintu** [comment]
Luckily a proper manual will pe published that contains this info. Username-only login pages will need to be added there because it needs a special kind of handling which cannot be enabled by default.

**Comment by varjolintu** [comment]
@dgnuff That would be a nice improvement indeed. I'll try to do it for the next version. Currently auto-fill works only once. On username-only sites it would have to work twice.
