### ISSUE TITLE
Why does this extension load jquery and jquery ui on EVERY page?

### ISSUE THREAD

**Issue by garygreen** [keepassxreboot/keepassxc-browser#295]
I'm looking for an alternative to something like LastPass, thought keepassxc looked pretty lightweight and seems to work well, but upon inspecting the codebase for this extension it's loading jQuery and jQuery UI on EVERY page... the question is, why? I can understand it being a requirement for the options page, possibly, but certaintly not needed for the main frontend functionality of filling form elements etc.

![image](https://user-images.githubusercontent.com/1702638/45242269-46370300-b2e7-11e8-80d6-bf6163beba08.png)

In theory, NOTHING except bare minimal functionality should be loaded until;

1. A direct action from the user telling it to fill passwords, or perform some action from the chrome extension bar
2. A password / credential type fields have been detected on the page

**Comment by droidmonkey** [comment]
Please see #128

**Comment by varjolintu** [comment]
jQuery is needed for the password generator, autocomplete menu and selecting custom credential fields. The PR linked above will eventually replace all jQuery code. It will be in a higher priority after the next release.

**Comment by Esteban-Rocha** [comment]
Thanks for being actively working on this, I had been using this for a while and I realized this was the reason of some lag and more issues of my setup. I rely heavily on this, keep the hard work! :muscle:
