### ISSUE TITLE
Timeout or not connected to KeePassXC because of misplaced manifest

### ISSUE THREAD

**Issue by Redsandro** [keepassxreboot/keepassxc-browser#298]
Long user of KeepassX, trying KeepassXC for the first time. Getting the famous "Timeout or not connected to KeePassXC" bug, which needs no introduction.

This is Linux Mint 19 AKA Ubuntu 18.04 LTS.

Turns out I am using Chrome 70 (`google-chrome-unstable`), and the manifest is installed to the Chrome 68 (`google-chrome`) directory:

`~/.config/google-chrome/NativeMessagingHosts/`

I don't even have the stable chrome installed.

It's common for Linux users to work with the beta or unstable version of Chrome because of reasons. The installer should check for the existence of `google-chrome-beta` and `google-chrome-unstable` and also install the manifest there.

If you don't want to manually copy the manifest over to the other directory on 50 machines, you can use ansible to automate this action on the computers you manage.

**Comment by varjolintu** [comment]
Maybe the easiest solution for this is to make symbolic link to the `~/.config/google-chrome/NativeMessagingHosts/` directory. We cannot support all beta/develop versions that use different paths.

**Comment by Redsandro** [comment]
Makes sense. Although users might not know different chromes use different config directories because by using an account the configuration will be synced and it will look like the same configuration.

Long story short: It might be a good idea to mention this in the docs at the sections about chrome.

**Comment by varjolintu** [comment]
There is a official manual coming to the documentation near KeePassXC 2.4.0 release. It might be a nice addition to mention about the possibility of these kind of issues.

**Comment by Redsandro** [comment]
This issue could use `documentation` label.

**Comment by droidmonkey** [comment]
IMO, if you use beta or unstable version of software, that is on you to correct any integration issues. There is a reason these versions say "not for use in production".
