### ISSUE TITLE
Match URLs without http/s

### ISSUE THREAD

**Issue by mschrimpf** [keepassxreboot/keepassxc-browser#302]
## Expected Behavior
I have an entry with the URL `github.com`.
When I visit https://github.com/login, I would like this entry to auto-fill.

## Current Behavior

The credentials are not filled in automatically because of the missing `https://` in the entry's URL.
If I change the URL to be prefixed with `https://`, it works.

## Possible Solution

I was hoping that disabling the "Match URL scheme" option in `Settings > Browser Integration` could take care of this case.
Updating all my entries to be prefixed with http/s:// is not feasible. The reason they are in this format is because KeePass expected them this way.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.2.0
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
Already fixed in the next KeePassXC version. See:
https://github.com/keepassxreboot/keepassxc/pull/2232
https://github.com/keepassxreboot/keepassxc/pull/2253
