### ISSUE TITLE
Problem with https://www.clippercard.com

### ISSUE THREAD

**Issue by dgnuff** [keepassxreboot/keepassxc-browser#303]
This site makes it hard for KeePassXC Browser to find the username and password fields

For all other sites if set up so far, by the time I'm done I can hit the login page, click on the username field, select from the dropdown, and get both username and password auto populated.  It wouldbe nice to get that same simple flow on this site.

## Current Behavior

At a guess, this is caused by that site's use of some sort of overlay or popup that contains the username and password fields.

As shown in the steps to reproduce, it's somewhat troublesome logging into this site.  TL;DR is that automatic login doesn't happen, but there is a way to get this to work.  It's just slightly clunky.

## Steps to Reproduce (for bugs)

1. Create an entry for https://www.clippercard.com
2. Navigate to https://www.clippercard.com
3. Allow KeePassXC browser to access the entry
4. Click on the "Login" button at the right end of the menu bar.  Observe the "popup" that appers.
5. Note that the username and password fields are not auto detected.
6. Click on "Choose custiom credential fields for this page"
7. Note that the standard dimming behavior is seen, but that the username and password entry fields cannot be clicked on.
8. Click on "Dismiss"
9. Note that most of the screen restores to non-dimmmed, except the popup remains dimmed, and that the username and password flelds can now be clicked on.
10. Refresh the page to reset it, and then click "Login" again.
11. Now click on "Redect credential fields".
12. Click on the username field, and note how it is correctly populated, and that selecting your email address then correctly fills the password.

This last step does allow a workaround, in the event that they are doing something really hideous that isn't possible or easy to work around.

## Debug info

These are the only messages displayed during the above process, after clearing the console:

unreachable code after return statement  general.js:53:1
Loading failed for the <script> with source “https://www.googletagmanager.com/gtm.js?id=GTM-T6GRSFG”.  index.do:1
An unbalanced tree was written using document.write() causing data from the network to be reparsed. For more information https://developer.mozilla.org/en/Optimizing_Your_Pages_for_Speculative_Parsing  index.do:71
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.min.js:16:31260
TypeError: fieldStyle is null  keepassxc-browser.js:900:1

KeePassXC - Version 2.3.4
KeePassXC-Browser - Firefox, can't find the version number.  However it's the latest as far as I know.
Operating system: Windows 10
Browser: Waterfox, using the Firefox plugin.

**Comment by 0xpr03** [comment]
@varjolintu I have a similar issue on https://forum.golem.de/login.php , I don't see an iframe but still can't even manually select the input fields.
<details>
  <summary>screenshot</summary>

![screenshot_20181001_153658](https://user-images.githubusercontent.com/1280209/46291876-d9cebd00-c58f-11e8-931f-33fb96821a64.png)
</details>

**Comment by varjolintu** [comment]
@0xpr03 The next extension version works without any problems with that site.
