### ISSUE TITLE
Different behavior after database unlock on macOS and Windows

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc-browser#305]
## Expected Behavior
KeePassXC-Browser should show the matching credentials on a page after the database is unlocked. This is working as expected with Firefox on Windows.

## Current Behavior
After the database is unlocked, users need to switch tabs back and forth or click "Redetect credential fields" to retrieve the credentials for the current site.

## Steps to Reproduce
1. Open Firefox with KeePassXC-Browser
2. Open KeePassXC
3. Make sure the extension shows "Database not opened"
4. Open a site with credential fields with a matching entry in the KeePassXC database, e.g. https://github.com/login
5. Click into the username field (no credentials will be suggested as the database is locked)
6. Switch to KeePassXC and unlock the database
7. Return to Firefox

On Windows, the matching credentials will now be listed below the username field. On macOS, the credentials are not shown.

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.2.0
Operating system: Mac
Browser: Firefox

**Comment by varjolintu** [comment]
Can you reproduce this with the latest 1.3.0 release?

**Comment by whisdol** [comment]
Yes, 1.3.0 also requires a reload/tab switch after unlocking the database on macOS.
I tried my hand at debugging this and noticed that:
1. On the first database unlock when `cip.detectDatabaseChange` gets called, response.new is not equal to response.old (as expected). The credentials are only received/displayed under the login field if I debug the javascript file with some breakpoints in the `cip.detectDatabaseChange` and `cip.initCredentialFields` functions. If I do not set any breakpoints, the credentials are not received/displayed.
2. If I then lock the database, keep the browser open, (reload the page,) and unlock the database again, the credentials are never received. In the `cip.detectDatabaseChange`-function, response.new now equals response.old, so `cip.initCredentialFields` is not called again.
3. (Unrelated to this issue) If credentials are loaded and I lock the database via the lock button in the extension, the credentials are not cleared.

Hope that helps a bit. Let me know if there is anything I should dig into more.

**Comment by droidmonkey** [comment]
This sounds like a race condition or a discarding of a promise.

**Comment by varjolintu** [comment]
@whisdol Thanks. That helps a lot! I'm already investigating the issue.

**Comment by varjolintu** [comment]
Fixed. The database hashes were not properly updated to content scripts when using the popup icon.
