### ISSUE TITLE
Credential selection not working for some websites on first visit

### ISSUE THREAD

**Issue by Hativ** [keepassxreboot/keepassxc-browser#31]
## Expected Behavior
Credentials should be selectable on first page visit.

## Current Behavior
I have to switch to another tab and back on some* websites to get selectable credentials.

\* So far these two:
https://signin.ebay.de/ws/eBayISAPI.dll
https://www.huk24.de/login.do

## Steps to Reproduce (for bugs)
1. Add entry for sigin.ebay.de
2. Disable auto-fill
2. Go to https://signin.ebay.de/ws/eBayISAPI.dll 
3. No credentials are selectable (but question mark on icon blinks briefly)
4. Switch to another tab
5. Switch back to latest tab
6. Credentials are selectable

## Debug info
No errors in console.

## General Info
KeePassXC fork - 2.3.0
keepassxc-browser - 1.0.0

Operating system: elemantary OS 0.4.1
Browser: Chromium 64.0.3282.167
Proxy used: No

**Comment by varjolintu** [comment]
Does your entry have exactly those URL's? I tested these and both worked normally.

**Comment by Hativ** [comment]
My entries have the urls "sigin.ebay.de" and "huk24.de".

Have you tested it with the same Chromium version?

On both websites I see other errors in the console. Maybe they interfere with keepassxc-browser?

All other browser extensions are disabled.

signin.ebay.de:
```
eBayISAPI.dll?SignIn&UsingSSL=1&pUserId=&co_partnerId=2&siteid=77&ru=http%3A%2F%2Fmy.ebay.de%2Fws%2FeBayISAPI.dll%3FMyEbayBeta%26MyeBay%3D%26guest%3D1&pageType=3984:1 [DOM] Found 2 elements with non-unique id #ru: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" name=​"ru" id=​"ru" value=​"http:​/​/​my.ebay.de/​ws/​eBayISAPI.dll?MyEbayBeta&MyeBay=&guest=1">​ <input type=​"hidden" name=​"ru" id=​"ru" value=​"http%3A%2F%2Fmy.ebay.de%2Fws%2FeBayISAPI.dll%3FMyEbayBeta%26MyeBay%3D%26guest%3D1">​
eBayISAPI.dll?SignIn&UsingSSL=1&pUserId=&co_partnerId=2&siteid=77&ru=http%3A%2F%2Fmy.ebay.de%2Fws%2FeBayISAPI.dll%3FMyEbayBeta%26MyeBay%3D%26guest%3D1&pageType=3984:1 [DOM] Found 2 elements with non-unique id #srt: (More info: https://goo.gl/9p2vKq) <input type=​"hidden" name=​"srt" id=​"srt" value=​"010002000000400a4a032a60a6afbb6d04bf46101f2ea4c732322b0e710adbbc99db84b9ee335b456019b0d8f04cafa36c10694b1c2062697063c487001f9fa6f44cfca16b60f8">​ <input type=​"hidden" name=​"srt" id=​"srt" value=​"010002000000400a4a032a60a6afbb6d04bf46101f2ea4c732322b0e710adbbc99db84b9ee335b456019b0d8f04cafa36c10694b1c2062697063c487001f9fa6f44cfca16b60f8">​
fb-all-prod.pp.min.js:1 XHR finished loading: POST "https://c.paypal.com/v1/r/d/b/p1".
AjaxRequest.sendSameDomain @ fb-all-prod.pp.min.js:1
AjaxRequest.send @ fb-all-prod.pp.min.js:1
i @ fb-all-prod.pp.min.js:2
e @ fb-all-prod.pp.min.js:2
postMessage (async)
o @ fb-all-prod.pp.min.js:2
postMessage (async)
(anonymous) @ fb-all-prod.pp.min.js:2
runFb @ fb-all-prod.pp.min.js:2
document.body.window.onload @ fb-all-prod.pp.min.js:2
fb-all-prod.pp.min.js:1 XHR finished loading: POST "https://c.paypal.com/v1/r/d/b/p2".
AjaxRequest.sendSameDomain @ fb-all-prod.pp.min.js:1
AjaxRequest.send @ fb-all-prod.pp.min.js:1
o @ fb-all-prod.pp.min.js:2
a @ fb-all-prod.pp.min.js:2
u @ fb-all-prod.pp.min.js:2
i @ fb-all-prod.pp.min.js:2
e @ fb-all-prod.pp.min.js:2
postMessage (async)
o @ fb-all-prod.pp.min.js:2
postMessage (async)
(anonymous) @ fb-all-prod.pp.min.js:2
runFb @ fb-all-prod.pp.min.js:2
document.body.window.onload @ fb-all-prod.pp.min.js:2
```
huk24.de:
```
Error parsing header X-XSS-Protection: 1; mode=block; report=https://www.google.com/appserve/security-bugs/log/youtube: insecure reporting URL for secure page at character position 22. The default protections will be applied.
```

**Comment by varjolintu** [comment]
You need to have those exact URL's for the entries. I mean these two:
- https://signin.ebay.de/ws/eBayISAPI.dll
- https://www.huk24.de/login.do

**Comment by Hativ** [comment]
That doesn't matter, I always save only the key part of the URL.

But I have tried it with the full URL's (like you wrote) also, but it's exactly the same issue.

**Comment by varjolintu** [comment]
I guess this is related to a bug I already fixed but the extension haven't been updated yet.
It's fixed with https://github.com/keepassxreboot/keepassxc-browser/commit/48e07d96c1c2c9a95a09b8d6cc0cc88046edb778.

**Comment by Hativ** [comment]
That commit is in 1.0.0, right? My installed extension is 1.0.0.

**Comment by varjolintu** [comment]
That commit has been made after the release.

**Comment by varjolintu** [comment]
Does the popup show the credentials if you switch the tab from another and then back? Or with page refresh? Those were the situations that caused the popup to work again, before the fix. I cannot reproduce the problem with 1.0.1.

**Comment by Hativ** [comment]
When I open one of the pages the small question mark icon on the keepassxc-browser icon in the top right appears briefly and then disappears. If I then switch to another tab and back again (no page refresh!) the small question mark icon is back and I can select the credentials. I'm on keepassxc-browser 1.0.1.

**Comment by varjolintu** [comment]
I cannot reproduce this with the latest version. Have you tried to download the sources from here and try to load this as a temporary add-on and see if the issue is still there?

**Comment by Hativ** [comment]
The extension from the sources does not work for me. I can't connect to a database. Do I have to pay attention to anything special?

But when I use the extension from the Chrome Web Store and enable Developer Mode and Capture errors, the following error will be listed for these both sites:

```
Uncaught Error: cannot call methods on autocomplete prior to initialization; attempted to call method 'search'

Stacktrace
jquery-3.3.1.min.js:2 (error)
jquery-ui.min.js:6 (Anonyme Funktion)
jquery-3.3.1.min.js:2 (each)
jquery-3.3.1.min.js:2 (each)
jquery-ui.min.js:6 (t.fn.(anonymous function))
keepassxc-browser.js:161 (cipAutocomplete.onFocus)
jquery-3.3.1.min.js:2 (dispatch)
jquery-3.3.1.min.js:2 (y.handle)
```

**Comment by varjolintu** [comment]
Yes you have to modify the native messaging script with the correct extension ID. Otherwise it's not accepted.

That autocomplete error shouldn't affect to the credential fetching.

**Comment by Hativ** [comment]
Where do I do that?

**Comment by varjolintu** [comment]
There are some changes coming to the next release and I'm certain this won't happen in the future.

**Comment by Hativ** [comment]
It's partially fixed.

If I go to https://signin.ebay.de/ws/eBayISAPI.dll, the question mark on the icon still disappears. But I can select the credentials in the form field and at the same time the question mark on the icon appears again. Looks like the redetection gets triggered by clicking in the form fields.

**Comment by varjolintu** [comment]
Indeed the question mark icon disappears. Autocomplete seems to work still.

**Comment by varjolintu** [comment]
Still having the problem with 1.3.0?

**Comment by Hativ** [comment]
Yes, still the same on https://signin.ebay.de/ws/eBayISAPI.dll for me.

**Comment by varjolintu** [comment]
Closing this as it's a known issue that eBay does some heavy scripting with their login page and makes the input field modification quite difficult. One workaround is to disable JavaScript for the login page.
