### ISSUE TITLE
Keepassxc browser plugin loses association with database after update.

### ISSUE THREAD

**Issue by omnipossum** [keepassxreboot/keepassxc-browser#310]
## Expected Behavior

Up until the last update the plugin would remember its connection to a keepassxc database after the initial setup/key association, even if keepassxc or the browser were closed. 

## Current Behavior

After the update the plugin asks to connect even if there's an existing entry in its settings. It works until either keepassxc or the browser is closed and then asks to be connected to a database again, each time adding a new unique entry into its list of connected databases.

I've tried removing the database entries in the plugin's settings, disconnecting all browsers from the keepassxc application side, wiping the stored permissions, deleting the browser plugin entry on the application side and purging both the application and deleting/reinstalling the plugin with, with no effect.

## Steps to Reproduce (for bugs)

1. connect keepassxc to browser plugin
2. close either keepassxc or the browser
3. start application again

## Debug info

KeePassXC - 2.3.1 from the Ubuntu repository
KeePassXC-Browser - 1.3.0
Operating system: Ubuntu 18.04
Browser: Firefox 62.0.3 (64-bit)

**Comment by varjolintu** [comment]
Update the KeePassXC. Use the official PPA or AppImage.

**Comment by omnipossum** [comment]
Thanks, it's working now.
