### ISSUE TITLE
Autofill no longer works after last update

### ISSUE THREAD

**Issue by gwerbin** [keepassxreboot/keepassxc-browser#311]
A few days ago, KeepassXC-browser self-updated in Firefox. Then it requested that I update KeepassXC because it was out of date.

After updating KeepassXC, autofill no longer works.

## Context

Entry in KeepassXC:

```
username: gwerbin
password: ball123
url: github.com
```

Navigate to `https://github.com` and make sure I am logged out.

## Expected Behavior

I am prompted to autofill the username and password. Occasionally the plugin "misses" and I need to press "redetect credential fields", but otherwise things "just work".

## Current Behavior

No autofill at all.

## Possible Solution

No idea.

## Steps to Reproduce (for bugs)

Honestly not sure. Be me, I guess.

## Debug info

KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.4 
Windows 7 Enterprise SP1
Firefox 62.0.3

No error in KeepassXC, nothing in browser JS console.

**Comment by varjolintu** [comment]
Change your entry URL to `https://github.com`

**Comment by gwerbin** [comment]
@varjolintu is this new behavior? Or perhaps a [spacebar heating](https://xkcd.com/1172/) bugfix?

Will `https://example.com` work on subdomains like `www` or will I need a separate reference entry for those?

**Comment by varjolintu** [comment]
The URL matching was broken and fixed with 2.3.4 but one bug remains, and that's the subdomain matching. See https://github.com/keepassxreboot/keepassxc/pull/2253. If your entry's scheme is `http` it will no longer work with `https`. When the subdomain fix is merged, then `http://example.com` with match with `https://*.example.com` etc.

So for now, there is no workaround for it.

**Comment by gwerbin** [comment]
I see. Whatever the behavior is, a note somewhere on the website about URL/domain matching behavior would be appreciated (and help make KeepassXC more accessible to non-technical users)
