### ISSUE TITLE
Onboarding: tell users to enable browser integration when extension cannot connect

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#312]
After some trials with - apparently - legacy extensions, I found KeepassXC and the accompanying browser extension. After first launch of both, the browser extension wouldn't recognise my installation. Only an error was shown in the extension's settings as well as the extension's icon in the browser's top bar.

Instead of or in addition to this warning, it would be nice to display a small hint, something like "Did you enable browser integration in KeepassXC yet?", or a notification like "Don't forget to enable browser integration in KeepassXC. Here is how..." on new installs. Then information from [this page](https://keepassxc.org/docs/keepassxc-browser-migration/) could be shown.

**Comment by keunes** [comment]
Ok, I would swear this wasn't shown, but now trying to capture a screenshot, I do see such message. In any case, presenting some onboarding info would still be helpful. It could be considered for example to load the aforementioned page after install (like distill loads a page after install/update). I'm also thinking the combination of a red error text and a blue 'information' blub would attract more attention.

**Comment by varjolintu** [comment]
The error messages surely need some update so it would be more clear to the user what is needed.
