### ISSUE TITLE
Make input field type detection case insensitive

### ISSUE THREAD

**Issue by alperencaliskan** [keepassxreboot/keepassxc-browser#313]
## Expected Behavior

Input fields declared as type="PASSWORD" (with capital letters) should be recognized as password fields.

## Current Behavior

Input fields as type="PASSWORD" (with capital letters) is not recognized as password field.

Yes, it doesn't seem normal to me declaring type in capital letters, but both chrome and firefox accept it as password field and w3c validator doesn't complain about this.
[w3c validation](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.namesilo.com%2Flogin.php&charset=%28detect+automatically%29&doctype=Inline&group=0)

## Possible Solution

Comparing input type case-insensitive

## Steps to Reproduce (for bugs)

The page i am experiencing the issue:
[https://www.namesilo.com/login.php](https://www.namesilo.com/login.php)
1. Enter the page,
2. Password field doesn't being recognized.
3. "Choose custom login field for this page" fails to select password input because it is not selectable in the page.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
This would impact any combination of cases.
