### ISSUE TITLE
No logins found

### ISSUE THREAD

**Issue by jfx2006** [keepassxreboot/keepassxc-browser#315]
I'm not exactly sure when this started happening, it's been in the past week or so. KeePassXC-browser is no longer finding logins for any website.
I'll note that Firefox updated to 62.0.3 on October 2, and KeePassXC-browser updated to 1.3.0 on October 8.

## Current Behavior
When I click on a login form, I no longer get the drop down of logins from KeePassXC. I'm testing on a site with a really simple login form, no fancy javascript or anything. The user/password fields themselves are detected as I see the key icon in the password field.

## Debug info
The only thing I see in the Firefox extension debugger is "Error 15: No logins found".
As I said, this worked great before what I'm guessing is one of the recent updates.
The debugger confirms that I am connecting to the proxy:
Connecting to native messaging host org.keepassxc.keepassxc_browser
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
This is probably a duplicate issue. See https://github.com/keepassxreboot/keepassxc-browser/issues/311#issuecomment-429513576.

**Comment by jfx2006** [comment]
Okay. I thought it might be different because I have most of my entries set up like:
URL: usps.com
without an http or https in front. That's only matching http it looks like.

**Comment by justin-julicher** [comment]
Why is this issue closed? I'm having lots of issues with the latest 2.6.0 including this.
