### ISSUE TITLE
"KeepassXC-Browser has not been configured" even though it has

### ISSUE THREAD

**Issue by Mrfiregem** [keepassxreboot/keepassxc-browser#316]
## Expected Behavior

After connecting the extension and KeepassXC program by naming and accepting the association request key, the extension will remember that it's been connected the next time Firefox restarts.

## Current Behavior

After restarting the browser, KeepassXC-Browser asks again to connect to KeepassXC. When looking in the extension's settings page, the key is already listed under connected databases.

## Steps to Reproduce (for bugs)

1. Enable Firefox browser integration in KeepassXC
2. Install KeepassXC-Browser from the AMO
3. Click Connect, name and accept key
4. Expect extension to remember that it's been configured after restarting Firefox

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - 1.3.0
Operating system: Xubuntu 18.04.1 LTS x86_64
Browser: Firefox 62.0.3 (64-bit) [From apt repo]

**Comment by varjolintu** [comment]
Update the KeePassXC. Use the official PPA or AppImage.

https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by Mrfiregem** [comment]
Solved. Using ppa rather than outdated repo fixed it.

**Comment by jsachs** [comment]
@varjolintu can you briefly explain why this happens? We maintain a fork of KeePassXC and are seeing this issue, and would like to correct it ourselves.

**Comment by varjolintu** [comment]
@jsachs It's been a long time since 2.3.1, so I really don't have a valid anwser for that. Wouldn't it be easier to update your fork?

Looking at the history since 2.3.1, it might be related to this:
https://github.com/keepassxreboot/keepassxc/pull/1720
