### ISSUE TITLE
Plugin doesn't Connect automatically anymore

### ISSUE THREAD

**Issue by ntnsndr** [keepassxreboot/keepassxc-browser#317]
## Expected Behavior

Whenever I am logged into KeePassXC, the connected browser should connect to it

## Current Behavior

When I first started using the plugin, for several months, this wasn't a problem. But now, every time I start up my computer again, when Firefox and KeePassXC are open, I have to re-click the Connect button in the plugin. Then I have to enter the name of the connection again (I use "Firefox" every time, and it asks me if I want to overwrite the existing thing by that name). Then it works normally.

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - 1.3.0
Operating system: Linux/Xubuntu 18.04
Browser: Firefox 60.2

**Comment by yewnicorn** [comment]
I have had much the same problem for months, Firefox will randomly refuse to connect to the database - clicking the connect button has no effect

I resort to using the auto-complete from KeePassXC to fill in password fields

**Comment by droidmonkey** [comment]
First off, please update to the latest KeePassXC version (2.3.4), there were several fixes applied in this area. If you are being asked to connect to the database over and over that implies your plugin settings are being reset or deleted OR your KeePassXC-Browser Settings entry in the root folder is being deleted.

Secondly, for @yewnicorn, if you are continually unable to connect that leads me to believe that you need to reapply the checkbox within KeePassXC to make the plugin work correctly. Just uncheck it and check it again to reset the connection with Firefox.

**Comment by ntnsndr** [comment]
Oh darn—hopefully the Ubuntu repository will update its version soon... Thanks!

**Comment by venorz** [comment]
Under Ubuntu 18.04, the same version of all apps, and the same problem.But I remember it did works before. AFAIK, Ubuntu might not update the new version of software, so you may need use  PPA or something. But I prefer Ubuntu's own repository much. There is a workround for me, I download 2.3.4 AppImage  from official site,and connect it with the plugin then I re-open 2.3.1 KeePassXC on my system,it works again.Very weird. For me, the only thought is configure related.

**Comment by varjolintu** [comment]
I recommend using the official PPA with Ubuntu:
https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by johannesschweig** [comment]
Updating to 2.3.4 solved it for me. Thanks @droidmonkey and @varjolintu
