### ISSUE TITLE
Enable simultaneous usage of multiple databases

### ISSUE THREAD

**Issue by mrmeszaros** [keepassxreboot/keepassxc-browser#318]
## Expected Behavior

If multiple databases are open in KeePassXC and connected, all should be able to provide entries.

## Current Behavior

Currently, when 2 (or more) databases are open, only the focused db tab is used for entries.

## Possible Solution

Iterate through all connected databases when searching for matching entries?

## Steps to Reproduce (for bugs)

1. Open two non-empty databases (eg. `db1.kdbx` and `db2.kdbx`) in KeePassXC and connect both to the browser plugin
2. Focus the `db1.kdbx` tab in KeePassXC
3. Try to use an entry from `db2.kdbx`
4. Focus the `db2.kdbx` tab in KeePassXC
5. Try to use an entry from `db1.kdbx`

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
KeePassXC Settings -> Browser Integration -> Advanced tab -> Check `Search in all opened databases for matching credentials`.

**Comment by mario0511** [comment]
The suggested solution does not work for me

Has something changes since then?

**Comment by lhurt** [comment]
Same for me I'll open another issue.

**Comment by ThomasSteinbach** [comment]
Update 2021:

KeePassXC Settings -> Browser Integration -> **_General_** tab -> Check `Search in all opened databases for matching credentials`.

**Comment by lhurt** [comment]
> 
> 
> Update 2021:
> 
> KeePassXC Settings -> Browser Integration -> **_General_** tab -> Check `Search in all opened databases for matching credentials`.

Thanks. It's already closed.
It turned out that the [real issue was that](https://github.com/keepassxreboot/keepassxc-browser/issues/659).

**Comment by ThomasSteinbach** [comment]
@lhurt that should just be a note for others browsing this issue ;)
