### ISSUE TITLE
No connected databases found.

### ISSUE THREAD

**Issue by Psudocrypt** [keepassxreboot/keepassxc-browser#323]
## Expected Behavior

The database that I created using the keepassxc application, should show up in the keepassxc-brower's
Settings -> Connected databases.

## Current Behavior
It says "No connected databases found."

## Debug info
![image](https://user-images.githubusercontent.com/44508206/47607676-b25cfa00-da40-11e8-8525-337838d62331.png)

It says it is connected but the databases are not synced.
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Windows
Browser: Google Chrome Beta

**Comment by droidmonkey** [comment]
Have you tried creating to the connection again?

**Comment by Psudocrypt** [comment]
Yes this is what happens,
I connect it, it gets added,
Then when I go to lock the database from the kpxc-browser, it says Database not opened, and then it opens the Unlock database in the desktop app.

I unlock it, add it again, and the issue repeats.

**Comment by droidmonkey** [comment]
Yah we don't support beta or nightly browsers.
