### ISSUE TITLE
Is there a way to change this icon?

### ISSUE THREAD

**Issue by Psudocrypt** [keepassxreboot/keepassxc-browser#324]
Hey, I wanted to know if there was a way to change this icon.

![image](https://user-images.githubusercontent.com/44508206/47611631-2f16c500-da8f-11e8-88b7-88c477daebb1.png)

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Windows 10
Browser: Chrome

**Comment by varjolintu** [comment]
So the user can change it dynamically to some other icon? Currently there's no way to do that.

**Comment by Psudocrypt** [comment]
I'm new to the js environment, but I can see that in the icons folder ( https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/icons/key.png )

The key.png can be replaced.

But I have no idea, how to combine it into a chrome extension.

**Comment by droidmonkey** [comment]
Suggest a new icon in here and we can tell you if we like it.

**Comment by varjolintu** [comment]
I personally don't hate it or like it. Just used to it. I had a SVG version of it at some point but I didn't make a PR about it. If we really want to replace that icon at some point, I'd suggest a SVG icon instead.

**Comment by whisdol** [comment]
What kind of icon do you have in mind?
Generic keys?
Ionic: <img src="https://ionicons.com/ionicons/svg/md-key.svg" width="25px" height="25px" alt="Ionic">
ForkAwesome: ![image](https://user-images.githubusercontent.com/5374166/48287997-fac9de00-e46a-11e8-8cae-3bf8a1f2cb22.png) (excuse the screenshot)


Something with arrows (that would indicate some kind of "change" or "generation"), like is used in this app icon? (Probably rotated by 90°)
<img src="https://user-images.githubusercontent.com/5374166/48289002-45992500-e46e-11e8-8911-518d934be883.png" width="75px">

**Comment by droidmonkey** [comment]
I like the ForkAwesome one. We could make it the KeePassXC green color.

**Comment by varjolintu** [comment]
I like the ForkAwesome icon too. I'll make a PR for this soon.

**Comment by varjolintu** [comment]
The latest modifications:
![screen shot 2018-11-16 at 14 57 04](https://user-images.githubusercontent.com/24570482/48622660-1889cc80-e9b0-11e8-9c3a-0a5886afca31.png)
![screen shot 2018-11-16 at 14 57 12](https://user-images.githubusercontent.com/24570482/48622664-19baf980-e9b0-11e8-80dd-3affad2f5e4c.png)

I ended up scaling the SVG itself because in that way centering and adjusting the icon doesn't need any JavaScript magic.
