### ISSUE TITLE
Automatically open popup if needed

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#327]
## Expected Behavior

Open popup automatically, if needed.

It should, however, be obvious that the popup is being opened and not opened "out of nowhere".

## Current Behavior

Just blinks…

## Possible Solution

The API is there, at least Firefox supports it: https://developer.mozilla.org/de/Add-ons/WebExtensions/API/browserAction/openPopup

## Steps to Reproduce (for bugs)

1. Right-click -> "Save credentials"

AFAIK here it is possible to trigger this API as it is a user action that the menu click triggers.

**Comment by droidmonkey** [comment]
This should be configurable.
