### ISSUE TITLE
Extension blocking date-picker (calendar) on thalys.com

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#328]
## Expected Behavior
When going to www.thalys.com, on the homepage it should display a date-picker (or: calendar) when clicking on the date field (My dates), as follows:
[![Date picker](https://user-images.githubusercontent.com/12184325/47921764-10b12f00-debe-11e8-99e1-1283bba22129.gif)](https://user-images.githubusercontent.com/12184325/47921764-10b12f00-debe-11e8-99e1-1283bba22129.gif)

## Current Behavior
Instead of opening the calendar, nothing happens upon clicking the date field. I figured it was KeePassXC because I created a fresh Firefox profile and added & removed extensions one by one (many thanks to the people over at Webcompat to [help debug the issue](https://github.com/webcompat/web-bugs/issues/20641l)).

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux (Ubuntu 18.04)
Browser: Firefox 63.0

**Comment by varjolintu** [comment]
This happens because of a faulty ignore element function that ignores some jQuery classes. It's fixed in the branch that doesn't use jQuery but we need a temporary fix for this until that PR is merged.

**Comment by momu** [comment]
Seems to be the same issue with using the Amazon Seller Central. When accessing the page where [the personal information][0] (e.g. birth date) is entered there should be a date picker. But when KeePassXC-Browser 1.3.0 is enabled in Firefox the date picker will not show up.

Error in debug console is:

```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://f5f1983f-db1e-4419-8a1f-9106e5b2ca29/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map[Learn More]
```


[0]: https://sellercentral-europe.amazon.com/gp/express-boarding/account-info/components/kycpoc.html?ref_=macs_xxkycpoc_cont_acinfohm

**Comment by varjolintu** [comment]
@momu I'm quite sure it's the same issue with jQuery.
