### ISSUE TITLE
HTTP auth dialog multiple credentials

### ISSUE THREAD

**Issue by Hativ** [keepassxreboot/keepassxc-browser#33]
## Expected Behavior
If multiple credentials are available on HTTP auth dialogs I should be able to select the right one.

## Current Behavior
Currently keepassx-browser chooses one of the saved credentials on HTTP auth dialogs, resulting in using the wrong credentials.

## Possible Solution
Show selection if multiple credentials on HTTP auth dialogs are available.

**Comment by varjolintu** [comment]
Does the popup have any info about the credentials in this case?

**Comment by pfoo** [comment]
Are you sure about this ? Just tried, got a notification stating that multiple credentials are detected and I should click on the plugin icon to select the right one.
That being said, the behaviour of Kee (formerly keefox) regarding http auth dialog is way more intuitive.

**Comment by varjolintu** [comment]
So did the popup show the multiple credentials which you could select? I agree that this behaviour could be a lot better.

**Comment by pfoo** [comment]
The notification does not, but the popup (after clicking on the plugin icon) shows the multiple matching credentials (and they are submitted as they should as far as I can tell).

**Comment by Hativ** [comment]
Ok, I was wrong. I thought keepassxc-browser used the wrong credentials again and again because the page was loading endless. But Chromium shows "Waiting for KeePassXC-Browser extension.." in the bottom left and I can select the credentials from the icon. I didn't noticed this because I had disabled the notifications.

**Comment by varjolintu** [comment]
So it works now? Anything other related to this?

**Comment by Hativ** [comment]
Yes, can be closed.
