### ISSUE TITLE
Doesn't work with LinkedIn

### ISSUE THREAD

**Issue by keunes** [keepassxreboot/keepassxc-browser#330]
## Expected Behavior
Correctly detect login fields & take the credentials that I manually entered in KeePassXC when right-clicking the field and 

## Current Behavior
The browser extension says 'No logins found' when right-clicking the email field on linkedin.com, and selecting 'fill username and password', even though I've manually created a LinkedIn entry (which includes LinkedIn in the title and www.linkedin.com as the url). 

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux (Ubuntu 18.04)
Browser: Firefox

**Comment by droidmonkey** [comment]
Works for me. Change the URL to https://linkedin.com

**Comment by varjolintu** [comment]
Make sure the URL scheme in your entry matches.

**Comment by keunes** [comment]
Thanks both, that helped.
