### ISSUE TITLE
Password field not detected on ANZ website

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#331]
## Expected Behavior
Able to fill credentials on https://www.anz.com/INETBANK/bankmain.asp

## Current Behavior
It appears the password field is not detected.  Right clicking and "fill username and password" does not work.  When trying the "choose custom login fields for this page", the password seems to be detected as a possible username field (in addition to the real username field), and after selecting the username field, there is no possible password field detected.

## Steps to Reproduce (for bugs)

1.  Visit https://www.anz.com/INETBANK/bankmain.asp after saving in some dummy credentials for the site in keepassxc.

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/pull/314 fixes this.
