### ISSUE TITLE
New username/passwd detection fails in Firefox

### ISSUE THREAD

**Issue by anillohchab** [keepassxreboot/keepassxc-browser#334]
KeepassXC Browser addon fails to detect new username password for some websites. Websites which it fails consistently : 
- https://www.kohls.com
- https://www.doordash.com/

## Expected Behavior
It should show a notification for the new username password which could be saved.

## Current Behavior
It doesn't show any notification for new username password.

## Possible Solution
Unclear, I could not debug this issue. Need some information about I can debug this addon.

## Steps to Reproduce (for bugs)
1. Goto a website where it doesn't work for e.q. kohls.com
2. Login using a username password which is not stored in keepassxc
3. Note that the addons fails to show notification to store new credentials

## Context
Irritatingly I need to store this password manually for those cases. 

## Debug Info
KeePassXC-Browser Version: 1.3.0 
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu 18.04.1 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-39-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

Debugging the content scripts work via right mouse click (on a page) and select Inspect from the context menu. You can find the extension from the Debugging tab.
