### ISSUE TITLE
Restarting Firefox leads up to --> KeePassXC: Neue Schlüsselverbindungsanfrage

### ISSUE THREAD

**Issue by BeamMeUpTo** [keepassxreboot/keepassxc-browser#335]
Everytime I start or restart Firefox the KeePassXC - Plugin asks me for a new name for the key to connect to database even though the name and key are already known.
 
## Expected Behavior

Once connected to KeePass the key is known an no more asking for new names an "new" keys.

## Current Behavior

Plugin asks me for a new name for the key even though the name an key are already known every time i start/restart Firefox

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Firefox 60.0.3 (64-Bit)

**Comment by varjolintu** [comment]
Update your KeePassXC to the latest version. I assume you are using Ubuntu or some of its variants because the version is only 2.3.1.
See: https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc

**Comment by BeamMeUpTo** [comment]
Yes, 
this solved it ;)

And yes, its kubuntu 18.04 LTS...

I was not shure if there were alternative repos... So now I know ;))

Thanks
