### ISSUE TITLE
Fill in TOTP code using autocomplete dropdown

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#337]
Right now the ways to fill in TOTP code looks like right-click and fill or a keyboard shortcut. I think I read somewhere that TOTP form names aren't the same everywhere but neither are they for username/passwords really and I think most sites will use same or similar names just like for username/password. Can there be a way to just click and add TOTP using autocomplete to fill in the appropriate TOTP code for whichever username is used (just like it is done for the password)? It would be very convenient to fill in the TOTP code this way.

**Comment by varjolintu** [comment]
I can inspect this further of course, but for now I haven't found a proof way to detect these fields. Sometimes the type can be `text`, sometimes `num`. And there's no standard way the pages determine the maximum length of these input fields.

Maybe this could be improved, for example, using Custom Credentials Fields where the could be a "Set TOTP field" option? If such is set, the autocomplete would work for it automatically.

For now, the only way to get these work is via autofill and String Fields (but I assume is not the way you want to use the extension). See https://github.com/keepassxreboot/keepassxreboot.github.io/blob/564120a8619b70f73f720fffd293f45282f06f5d/docs/keepassxc-browser-manual.md#17-fill-additional-values-using-string-fields (WIP manual) for more info. You could just select one String Field from the page and add an attribute `KPH: {TOTP}` to your entry.

**Comment by sebast889** [comment]
Currently using the right click and fill option which sometimes doesn't work and making string fields for all the sites using TOTP also doesn't work sometimes/is more tedious to set up. An autocomplete way to choose from the dropdown if it is possible would definitely be appreciated.

**Comment by varjolintu** [comment]
So it seems. In some cases the TOTP page is loaded dynamically within the same URL. Sometimes it's redirected to another page, which then loses the previously loaded credentials. A way must be found to maintain the credentials even if these kind of things happen. Cloning the entry with TOTP setup with a different URL (the 2FA page URL) is not very handy workaround.

**Comment by rugk** [comment]
Maybe save some values [in the tab data](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sessions/setTabValue) in the meantime. This should survive redirects (and even browser restarts). Respectively save it in the background script.

**Comment by varjolintu** [comment]
@rugk It's not supported by Chromium, so it's not a viable solution.
