### ISSUE TITLE
keepassxc-browser doesn't autofill custom placeholders

### ISSUE THREAD

**Issue by Generator** [keepassxreboot/keepassxc-browser#34]
**This issues is not related with "Fill TOTP" from context menu**

keepassxc-browser doesn't auto-fill custom placeholders when specified with "[Choose own credential fields](https://github.com/smorks/keepasshttp-connector/blob/master/documentation/KeePassHttp-Connector.md#43-settings-specified-credential-fields)"

## Expected Behavior

When a page have their specified credential fields, should [auto-fill all custom fields](https://github.com/smorks/keepasshttp-connector/blob/master/documentation/KeePassHttp-Connector.md#37-fill-in-additional-values-via-string-fields) (username/password/KPH placeholders)

## Current Behavior

Only username and password is filled.

## Possible Solution

Custom placeholders working without issues with [KeePassHttp-Connector](https://github.com/smorks/keepasshttp-connector)

## Steps to Reproduce (for bugs)

1. Create a new entry to https://python-totp.herokuapp.com/
2. Register and setup TOTP
3. On new entry go to "Advanced" and create a new attribute `KPH: 1 - TOTP`, with value `{TOTP}`
4. On login page from keepassxc-browser icon "Choose your own credential fields", select username field (skip password) and string field
5. Reload page (if doesn't fill username try to redetect credential fields)

## General Info
KeePassXC - Version 2.3.0 Revision: 4c0ed74
keepassxc-browser - Version: 1.0.0

Operating system: Archlinux
Browser: Firefox 58.0.2
Proxy used: NO

**Comment by olifre** [comment]
Same here, Gentoo, Firefox 58.0.1, same versions of KeePassXC and keepassxc-browser.

**Comment by TheZ3ro** [comment]
Maybe related to #28 ?

**Comment by olifre** [comment]
To cite @Generator 

> This issues is not related with "Fill TOTP" from context menu

So I don't believe it's related. 

I also can't get any other custom fields to work. For example, for a page which takes an additional string field, I can select this using `Choose your own credential fields:`, and select that string field - but it will never be filled automatically. 
I have created an associated attribute called `KPH: 1 - Pin` with corresponding value. The very same attribute worked fine with https://addons.mozilla.org/de/firefox/addon/keepasshttp-connector/ .

**Comment by Generator** [comment]
@TheZ3ro I've tried using an attribute as described [here](https://github.com/keepassxreboot/keepassxc-browser/issues/28#issuecomment-369494014) but didn't work. But the "Fill TOTP" works.  
Also it should work with any `KPH:` attribute (e.g. name: `KPH: Test` value: `SomeText`)

**Comment by varjolintu** [comment]
I'll look into it.
