### ISSUE TITLE
Add multiple url's for login

### ISSUE THREAD

**Issue by janw-me** [keepassxreboot/keepassxc-browser#344]
I have _website.com_ and a local _website.test_ I'd like to both match the login.

## Expected Behavior
I create a login in keepass and connect it. It works.
Next edit the advanced json from

    {"Allow":["website.com"],"Deny":[],"Realm":""}

And add

    {"Allow":["website.com", "website.test"],"Deny":[],"Realm":""}

Save keepass. In browser go to test url.
Doesn't show anything.

Is this not supported, of am I misunderstanding the feature?

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser -1.3.0
Operating system: Ubuntu 
Browser: Firefox

**Comment by varjolintu** [comment]
There is already PR for this: https://github.com/keepassxreboot/keepassxc/pull/1769.

**Comment by janw-me** [comment]
Ahh nice.
Lives on there.
