### ISSUE TITLE
Constant CPU usage and energy impact reported in Firefox

### ISSUE THREAD

**Issue by Gert-dev** [keepassxreboot/keepassxc-browser#348]
## Expected Behavior
When not connected (i.e. KeePassXC isn't even opened or conencted to the extension), the extension would not be doing anything or keeping a very low profile and thus not impact the browser - or CPU, indirectly.

## Current Behavior
Currently looking in the Firefox task manager - in my case this is in Firefox 64, which has altered the look somewhat - via `about:performance` reveals that KeePassXC-browser is constantly reported as having a "low" and sometimes "moderate" energy impact, which is odd seeing as the extension is not connected to any database, nor is KeePassXC even open.

At first I assumed the disconnected extension was polling to see when I start KeePassXC, but nothing changes in the extension once I start it and I still explicitly have to click `Reload`, so that doesn't appear to be the case either.

I'm not sure if this has already been reported, I found #171 which seems to be related but not quite the same.

## Possible Solution
When not connected or KeePassXC isn't detected, don't poll anything. Alternatively, poll at a much lower interval or make the interval configurable - in my case KeePassXC is only on when I need to enter passwords and off most of the day.

## Steps to Reproduce (for bugs)
1. Install and enable KeePassXC in Firefox
2. Open `about:performance`

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.0
Operating system: Linux
Browser: Firefox 64

Thanks for maintaining this great extension and the application itself!

**Comment by droidmonkey** [comment]
This could be because the plugin is scanning the page for credential fields even if there is not an active database connection. I am not sure about this though.

**Comment by varjolintu** [comment]
This happens because of https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/background/init.js#L141 loop. When I disabled it, the energy impact is not even reported. And because this loop is mainly used just for a blinking icon and other not-so-important-stuff, there's a room for refactoring. These kind of events should happen asyncronously and not via polling.

Thank you for reporting this!

**Comment by varjolintu** [comment]
@droidmonkey Asynchronous MutationObserver replaced the credential field polling while ago.
