### ISSUE TITLE
KeePassXC-Browser don't work with Iridium Browser

### ISSUE THREAD

**Issue by diffusae** [keepassxreboot/keepassxc-browser#35]
KeePassXC-Browser don't work with Iridium Browser.

Iridium seems to be a privacy enhanced browser based on Chromium.
Don't know how active the project is actually.
https://github.com/iridium-browser/tracker/wiki/Differences-between-Iridium-and-Chromium
Current version is 2017.10
(based on Chromium 61.0.3163.100)

## Expected Behavior

KeePassXC-Browser Integration asking for credentials.

KeePassXC-Browser Integration should work with Iridium

## Current Behavior

After integration of KeePassXC-Browser nothing happens. No database is detected.
It doesn't ask for credentials. It only has encountered an error:
"Timeout or not connected to KeePassXC"

## Possible Solution

Maybe it happens only because of the name of the browser?

If I should file the issue to the Iridium project, please give a short reply.

After creating the directory ~/.config/iridium/NativeMessagingHosts and copying org.keepassxc.keepassxc_browser.json from Chromium it seems to work.

keepassxreboot/keepassxc#1559

## Steps to Reproduce (for bugs)

1. Install latest Iridium Browser
2. Add KeePassXC-Browser extension to Iridium
3. Plugin is running, but nothing more
4. KeePassXC-Browser has encountered an error

## Debug info

There is nothing in the JavaScript console 

KeePassXC-Browser has encountered an error:
Timeout or not connected to KeePassXC

## General Info
KeePassXC fork - Version 2.3.0
Revision: 4c0ed74
keepassxc-browser -  Version 1.0.0

Operating system: Ubuntu 16.04.4 LTS
Browser: Firefox, Chromium, Iridium
Proxy used: NO

**Comment by diffusae** [comment]
After creating the directory ~/.config/iridium/NativeMessagingHosts and copying  org.keepassxc.keepassxc_browser.json from Chromium it seems to work.

https://github.com/keepassxreboot/keepassxc/issues/1559

**Comment by varjolintu** [comment]
This is correct. If you use any browser that has a different configuration location you'll have to copy the .json script manually.

**Comment by antonin-lebrard** [comment]
For anyone like me who want to find the `org.keepassxc.keepassxc_browser.json` file without going through the steps of installing a normal version of chromium, then re-install this extension :<br>

You can find the file in `~/.config/google-chrome/NativeMessagingHosts/`. As this was the only file, and only directory inside `~/.config/google-chrome/` I suppose that by default the extension creates one directly in the directory `google-chrome/NativeMessagingHosts`

**Comment by antonin-lebrard** [comment]
And the default one has this content inside it (if you want to just create it):
```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```
