### ISSUE TITLE
KeepassXC browser extension doesn't appear to recognise login fields after update to Firefox 64.0

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#352]
@Xubuntufan commented on [Wed Dec 12 2018](https://github.com/keepassxreboot/keepassxc/issues/2548)

It seems that after updating Firefox to 64.0 (on Xubuntu Linux) KeepassXC browser extension no longer recognises the [previously recognised] login fields.

Clicking on 'redetect login fields' doesn't appear to solve the problem. 
I am running KeePassXC version: 2.3.4

---

@varjolintu commented on [Thu Dec 13 2018](https://github.com/keepassxreboot/keepassxc/issues/2548#issuecomment-446844229)

Does this happen with all sites? Have you tried to create a new temporary profile in Firefox and see if the update has somehow messed up your default profile?

**Comment by Xubuntufan** [comment]
my sincere apologies - the problem described disappeared after rebooting... should have done this before posting! - Varjonlintu - thanks for your prompt response... sorry could't respond earlier due to work.

**Comment by droidmonkey** [comment]
Ebay is using some ridiculous JavaScript defeat code for password managers
