### ISSUE TITLE
Wrong password saved or don't save any password

### ISSUE THREAD

**Issue by lan542662** [keepassxreboot/keepassxc-browser#356]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( Do not include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( If you're describing a bug, tell us what should happen )
[NOTE]: # ( If you're suggesting a change/improvement, tell us how it should work )

## Current Behavior
[NOTE]: # ( If describing a bug, tell us what happens instead of the expected behavior )
[NOTE]: # ( If suggesting a change/improvement, explain the difference from the current behavior )
I only just test two websites and both have questions. 
https://shimo.im when i login,it don't display save the password.
http://bbs.pcbeta.com when i save the password. it saved a wrong password.

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug, )
[NOTE]: # ( or ideas how to implement the addition or change )

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1.
2.
3.

## Context
[NOTE]: # ( How has this issue affected you? What are you trying to accomplish? )
[NOTE]: # ( Providing context helps us come up with a solution that is most useful in the real world )

## Debug Info
[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - VERSION
Revision: REVISION

Libraries:
- LIBS

Operating system: OS
CPU architecture: ARCH
Kernel: KERNEL

Enabled extensions:
- EXTENSIONS

**Comment by varjolintu** [comment]
What password it saved then if it was the wrong one? Username instead, or an empty string?

**Comment by lan542662** [comment]
Yes, saved with the password "Lianna542662" but i checked keepassxc,it is
"574549b527e03b5b19443c6f3158756d". then i login with keepassxc, ofcourse
it is wrong. because it used "574549b527e03b5b19443c6f3158756d"(the website
is : http://bbs.pcbeta.com)
Another website is https://shimo.im/ Keepass didn't display save password.
this website is use for keep note by md. a very cool website in China.

My system is Archlinux , Chrome 71.0.3578.98

I don't trust latepass and bitwarden, although they are free and there's no
any questions so far(Didn't miss any website and the password is  correct).
but they are online password manage.
So I have tested Enpass today. It's could sync the password on local
directory or on google drive. It's so friendly. There is no problems on
firefox, but it couldn't connect to chrome. OMG

So i will keep use keepassxc and support keepassxc.

Many thanks to Keepassxc team. I love you.

Sami Vänttinen <notifications@github.com> 于2018年12月27日周四 下午2:56写道：

**Comment by droidmonkey** [comment]
I wonder if this is a UTF-8 encoding issue

**Comment by lan542662** [comment]
I have also tested in windoes10, the same problem, and keepassxc also save
the wrong password "574549b527e03b5b19443c6f3158756d". So i think if the
website feedback the wrong password to keepassxc,i mean the website has
some problems. but lasspass and other password manage is correct.

Jonathan White <notifications@github.com> 于2018年12月28日周五 上午12:14写道：

**Comment by droidmonkey** [comment]
I cannot replicate this issue using a test login form: https://bootsnipp.com/snippets/featured/login-form

**Comment by lan542662** [comment]
Dear Jonathan,

I have tested with https://bootsnipp.com/snippets/featured/login-form , i
checked the password keepassxc it saved, it is correct. You could test
these two websites. http://bbs.pcbeta.com  https://shimo.im/ maybe you will
happen the same problem.

Jonathan White <notifications@github.com> 于2018年12月28日周五 上午9:58写道：

**Comment by droidmonkey** [comment]
I can replicate on bbs.pcbeta.com but I see the reason. The password is hashed before it is sent to the server. There is nothing we can do about this because the website itself is mangling the password.

**Comment by lan542662** [comment]
But it is no problem with lasspass , bitwarden or dashlane .

Jonathan White <notifications@github.com> 于2018年12月29日周六 上午7:02写道：

**Comment by lan542662** [comment]
Yeah, i just save my password directly with these websites. I wish
keepassxc could own those magic tricks.  Bitwarden ,  Dashlane, google
password manage , etc.

Thank you very much.

Jonathan White <notifications@github.com> 于2018年12月29日周六 上午9:24写道：

**Comment by varjolintu** [comment]
Haven't tested this yet but I'm pretty sure if the page hashed the password to the input field that's the value KeePassXC-Browser reads. The only way to prevent this is to save the password to the memory instead of reading the input field value, and use that saved value for comparison.
