### ISSUE TITLE
Credentials available from Locked database after logging in (User) with KP database locked from being logged out

### ISSUE THREAD

**Issue by iverik-no** [keepassxreboot/keepassxc-browser#357]
I was able to fill in credentials with a locked database (actually closed Keepass!)

I use Protonmail in my example, though this wasn't the site on which I initially encountered the issue. I tested a few sites, and found the error to be present at Protonmail too. As it's more likely that someone here with debugging/testing/dev knowledge will have an account at Protonmail, I reasoned it makes more sense to refer mainly to that page.

It doesn't seem to happen every time. I had it occur many times in a row now while prodding at it, but then it stopped.

## Expected Behavior

To have to open the database before being able to fill in UN/PW.

## Current Behavior / What I observed

KeePassXC setting "Lock database when session is locked or lid is closed" is enabled.

What happened:
- I unlock my PC several hours after it locked itself (screensaver --> lock on resume).
- I have Firefox running (from before).
- I click on an already open tab, in which I'm not currently logged in.
- I click a credentials field
- The KeePass dropdown for filling in Username/Password appears (both entries I have for the site in question).
- I click one of them, and it supplies the username and password, thus logging me in.
- All the while KeePassXC wasn't running.

Testing, by unlocking KP database, locking user session, logging in user session, and then checking websites for the logins, I found these three different results happening:

1. I see the credentials dropdown already dropped down, ready for filling credentials. I found this on Protonmail.
2. I click the username field, as for "normal" Keepass login. Then credential options appear in the dropdown.
3. ...or nothing happens, as intended.

## Steps to Reproduce (for bugs)
1. Open database
2. Make Firefox detect it
3. Lock user session
4. Log back in
5. Go to e.g. Protonmail
6. Click the username field for credentials
7. Credentials appear

It doesn't seem to happen every time. I had it occur many times in a row, but then it stopped.

## Debug info

KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.4 
Operating system: Linux / Ubuntu --> Kuuntu
Browser: Firefox 64

**Comment by droidmonkey** [comment]
This sounds like the credentials are being cached and not cleared when the database is locked.

**Comment by iverik-no** [comment]
Did a few tests just now, and refreshing the page does remove/clear the credentials from the page.
And they do clear "by them selves" after a short time when I start clicking in and out of the credentials fields.

**Comment by varjolintu** [comment]
I'm quite sure this has something to do with autocomplete caching the values. Of course those should be also cleared when the database is locked.

**Comment by varjolintu** [comment]
Fixed it. It seems that the `document.visibilityState` is `hidden` when the screen is locked. That kind of situation was not handled. Now all credentials are cleared just in case if the document ever goes to that state when databases are locked/unlocked or switched.
