### ISSUE TITLE
Library usage?

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc-browser#359]
I'd like to use this protocol to interact with KeePassXC from scripts (end goal is automated encrypted backup), so is there some kind of library to do this without having to implement it myself? Otherwise, would it be possible to extract the protocol part of this extension into a library for others to use?

I'm looking for something similar to the python libraries that are out there for the KeePassHTTP protocol.

**Comment by varjolintu** [comment]
Currently there's no client library available. Of course we can make one, but it's still low priority at this point. Python and C++ would be the first ones available.

**Comment by varjolintu** [comment]
I quickly made a simple Python client library for this. Feel free to collaborate.
https://github.com/varjolintu/keepassxc-browser-client

**Comment by piegamesde** [comment]
Thank you a lot, it already has all the features I need to get my project working.

**Comment by varjolintu** [comment]
Also check this Python 3 version: https://github.com/hrehfeld/python-keepassxc-browser
