### ISSUE TITLE
KeePassXC Browser not working on sites, where login is split into multiple sites

### ISSUE THREAD

**Issue by t-aus-m** [keepassxreboot/keepassxc-browser#36]
KeePassXC Browser (aswell as KeePasshttp before) is not working on sites, where login is split into multiple sites. Most known example for this would be Google.

## Expected Behavior
The browser plugin detects credential fields correctly

## Current Behavior
On sites like Google, where the login is split into zwo seperate sites, the plugin does not work properly. You have to type your email adress manually. Selecting the password works though.

## Possible Solution
Eighter hardcode a behavior for the few sites that use multiple sites for login into the plugin, or maybe add a way to make custom credential fields work with those sites.

## General Info
KeePassXC fork - 3.2.0
keepassxc-browser - 1.0.0

Operating system: Win 10, Ubuntu 17.10 _(does not matter)_
Browser: 59.0b13 (64-Bit) _(does not matter)_
Proxy used: NO

**Comment by varjolintu** [comment]
You are correct. Google page really has some difficulties even when I try to choose my own credential fields. If I use `https://accounts.google.com/signin/v2/sl/pwd` as a URL for the entry the popup detects the credentials but nothing happens when choosing them. Autocomplete doesn't work. So there's a room from improvement. At some point this worked though.

**Comment by pfoo** [comment]
Isn't this related to the missing multiple-url-entries feature of keepassxc ?

**Comment by varjolintu** [comment]
Actually no. I can retrieve the same credentials from both login and password page. Still I have troubles with the input fields. I'm not sure if Google has added some nasty JavaScript to disable this kind of behaviour from content scripts etc. Separate login/password pages like http://addons.mozilla.org/ works normally.

**Comment by seekM** [comment]
This issue still exists for me: The username field is not detected for me when opening https://accounts.google.com. However, when I enter my username manually and press enter I am forwarded to a new webpage. The passwort field on this webpage (still https://accounts.google.com) is detected. I am using KeePassXC-Browser 1.5.1 / Firefox 69.0.2 on Windows / KeePassXC 2.4.3.

**Comment by varjolintu** [comment]
@seekM Have you enabled the Username-only support for the site through Site Preferences? Correct URL for that page is `https://accounts.google.com/*`.

**Comment by seekM** [comment]
I did not! Thank you, it works now.

**Comment by varjolintu** [comment]
@seekM Glad it works! The popup should also inform you if it's possible to add the current site automatically to Site Preferences and enable the Username-only support.

**Comment by seekM** [comment]
I'm not 100% sure when and where the popup is supposed to appear - I removed the entry from site peferences again, but no popup appears when I visit https://accounts.google.com

**Comment by varjolintu** [comment]
Sorry, I meant that when you click the extension popup, it should show an option to add the site to Site Preferences. It doesn't appear anywhere automatically.

**Comment by seekM** [comment]
I see, thanks, that works indeed!

**Comment by qo4on** [comment]
Still does not work on my.visualstudio.com
