### ISSUE TITLE
Firefox can't keep connection to keepassxc

### ISSUE THREAD

**Issue by Sec42** [keepassxreboot/keepassxc-browser#363]
## Expected Behavior
browser integration continues to work once set up 

## Current Behavior
whenever keepassxc closes / locks the database, the browser integration forces me to re-connect, telling me 

"KeePassXC-Browser has not been configured. Press the connect button to pair with KeePassXC."

having to do this every single time makes keepassxc is very annoying.

## Possible Solution
only solution i could find is to use keepass and not keepassXC.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - : 1.3.0
Operating system: Linux
Browser: Firefox

**Comment by phoerious** [comment]
Please upgrade to KeePassXC 2.3.4.

**Comment by varjolintu** [comment]
The latest KeePassXC-Browser update that is released soon will fix the bug with KeePassXC 2.3.1.
