### ISSUE TITLE
Question: How does this plugin find the input fields it wants?

### ISSUE THREAD

**Issue by ForsakenHarmony** [keepassxreboot/keepassxc-browser#368]
I tried going through the code, but it's a huge mess (to me)

Thought I could improve some parts, but never figured out how any of it works

**Comment by varjolintu** [comment]
The input field detection happens in `keepassxc-browser.js`file.
Basically only the function `cipObserverHelper.getInputs()` is used. It returns all input fields from the target element, which can be for example a `div` or the whole `document`. This function is called from several places, but also dynamically from `MutationObserver` when new elements are added or removed from the page.

Four additional checks are made in that function, which are:
- Checks the target element `nodeType` and returns if it's not an element
- Adds all non-hidden type input elements to an array (it's faster to ignore hidden elements here)
- Only include first hundred input fields from the element/document (even that is quite.. suspicious)
- Accept only input fields with type `text`, `email`, `password`, `tel`, `number` and fields without type set

The same detection is used in `cipFields.getAllFields()` but it extends the function above by ignoring any input fields that are not visible in the page or are not identified as a search field.

**Comment by rugk** [comment]
I guess you can close this. Question answered. :smiley:

**Comment by varjolintu** [comment]
I want to leave this open for visibility :)

**Comment by ForsakenHarmony** [comment]
People can always search for it, thanks btw
