### ISSUE TITLE
Have to recconnect to database everytime I reload browser

### ISSUE THREAD

**Issue by BrianD91** [keepassxreboot/keepassxc-browser#370]
## Expected Behavior
I expect that once I've clicked "connect database" in the browser extension that I won't really ever have to do that process again so long as I'm using the same database. 

## Current Behavior
But everytime I close and re-open the browser (Ungoogled Chromium 71.0.3578.98 on Kubuntu 18.04) I have to click "connect database" and setup the same database connection. Is this what's supposed to happen? It says the database connection was created yesterday (which is true, that's when I started using the browser extension), but I have to reconnect to it every time and it creates a new key everytime. Seems like  time-sink to have to do this manually every time I open the browser.

## Debug info
KeePassXC-Browser Version: 1.3.0
KeePassXC Version: 2.3.1
Operating system: Kubuntu 18.04
Browser: Ungoogled Chromium 71.0.3578.98

**Comment by varjolintu** [comment]
This is already fixed and will be with the next release (no due date yet). The workaround is to install KeePassXC 2.3.4 from the official [PPA](https://launchpad.net/~phoerious/+archive/ubuntu/keepassxc).

**Comment by DocKDE** [comment]
I have the exact same issue on all of my systems (Manjaro and Arch) with the latest keepassxc (2.4.3) and keepassxc-browser (1.4.6) in Firefox. 
Is it possible that the issue is due to the fact that my database resides in a Cryptomator vault?

**Comment by varjolintu** [comment]
@DocKDE Have you tried to disable Auto-Reconnect? I don't think it matters where the database resides. Where and how KeePassXC is used is what matters.

**Comment by DocKDE** [comment]
It was never activated in the first place. Tried it out yesterday to see
if it would change anything but no.

**Comment by varjolintu** [comment]
When the situation happens and a reconnect is needed, are there any keys saved in the extension settings?

**Comment by DocKDE** [comment]
Yes, just checked. I always use the same identifier when this happens,
which overwrites the already existing one. The key is also right there.

**Comment by varjolintu** [comment]
This kind of situation would need debugging both KeePassXC and the extension side to really see where the problem happens.

**Comment by DocKDE** [comment]
I see. Any suggestions where I should start?

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/wiki/Set-up-Build-Environment-on-Linux

The easiest way to debug is to use Qt Creator. I would do this myself, but I haven't been able the reproduce the kind of situation you described.
