### ISSUE TITLE
KeePassXC-Browser breaks PrimeNG dropdown component

### ISSUE THREAD

**Issue by MikeCoats** [keepassxreboot/keepassxc-browser#372]
I use PrimeNG components in a web application I'm developing and I noticed that when I had the KeePassXC-Browser extension enabled their dropdown component rendered incorrectly.

My initial tests were on a work-issued laptop running the current, up-to-date, Chrome on Windows 7 - but I leave that computer in the office, so I can't reproduce screenshots & version numbers from that one just now. Luckily (or un-luckily, I suppose) the bug is observable in Firefox & Chromium on my personal Debian laptop. The following screenshots and versions are from that computer.

I initally diagnosed it as an extension bug, rather than my own broken css, by reloading the page in an incognito window with no extensions. I then narrowed it down by turning off all other extensions and turning them on and off, one-by-one, to see which extension caused the corruption. Their appears to be a conflict between PrimeNG components and KeePassXC-Browser.

## Expected Behavior

The PrimeNG dropdown component should work just like it does when the extension isn't installed or enabled.

See the full-width dropdown "Select a city" under the "Single" heading:

![keepassxc--003](https://user-images.githubusercontent.com/37802088/50792616-84582980-12bd-11e9-91bf-4bd5d2dfa625.png)

See the full-width options under the "Select a city" dropdown:

![keepassxc--004](https://user-images.githubusercontent.com/37802088/50792638-920daf00-12bd-11e9-9fe7-f36dc2ccb0a8.png)

## Current Behavior

When the extension is installed and enabled, the PrimeNG downdown component is corrupted.

See the truncated, broken dropdown under the "Single" heading:

![keepassxc--001](https://user-images.githubusercontent.com/37802088/50792595-786c6780-12bd-11e9-8f28-29d899587c42.png)

See the truncated options under the truncated, broken dropdown:

![keepassxc--002](https://user-images.githubusercontent.com/37802088/50792622-88844700-12bd-11e9-9b01-f959e2338bd6.png)

## Steps to Reproduce
1. Disable the KeePassXC-Browser extension.
2. Visit [the PrimeNG dropdown component demo page](https://www.primefaces.org/primeng/#/dropdown).
3. Observe the component render correctly.
4. Enable the KeePassXC-Browser extension.
5. Refresh the page.
6. Observe the broken component.

## Debug info
KeePassXC - 1.3.0
KeePassXC-Browser - 2.3.4
Operating system: Debian GNU/Linux buster/sid
Browser: Firefox Developer Edition 65.0b8 (64-bit) &
Browser: Chromium Version 70.0.3538.67 (Developer Build) built on Debian buster/sid, running on Debian buster/sid (64-bit)

An example of the bug in Chromium on Linux can be seen below too:

![keepassxc--005](https://user-images.githubusercontent.com/37802088/50792680-b073aa80-12bd-11e9-8db4-06c12fb8247f.png)

**Comment by varjolintu** [comment]
Confirmed that the No-jQuery PR will fix this.
