### ISSUE TITLE
Using secretbox method

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#373]
It looks like the box method is done using tweetnacl-js currently but is it possible to use the secretbox method instead? Looks like it could probably be suitable for the extension and provide more security by encrypting messages. What are your thoughts?

**Comment by varjolintu** [comment]
The difference here is that secret box method uses a single key for encrypting and decrypting, but public key method needs a keypair. And with keypair, only the public is key is transferred. Secret box method would share the actual and only key needed for encrypt/decrypt. 

The secret key of the keypair always stays hidden, and it ensures the messages are kept private. Using with just one key that is also shared sounds like a less safe method.

**Comment by sebast889** [comment]
Thanks for the explanation @varjolintu
