### ISSUE TITLE
Export/Import settings option

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#377]
Can there be added a way to export/import keepassxc-browser settings so that it can be used for other computers or backups?

**Comment by pstorch** [comment]
I also thought about this. Why not storing it in the keepass db? In my case this synced across my devices anyway.

**Comment by varjolintu** [comment]
@pstorch That's another possibility yes. The question is that in which format? Maybe an extra entry with attributes, or just plain custom data straight to the database settings.

**Comment by sebast889** [comment]
>I also thought about this. Why not storing it in the keepass db? In my case this synced across my devices anyway.

It would be slightly more of a hassle for users who have multiple Keepass DBs. Changing a setting will require changing that setting on all DBs.

**Comment by pstorch** [comment]
> > I also thought about this. Why not storing it in the keepass db? In my case this synced across my devices anyway.
> 
> It would be slightly more of a hassle for users who have multiple Keepass DBs. Changing a setting will require changing that setting on all DBs.

Ah, good point. There are global settings for sure. I was just thinking about the custom credential fields. These belong to an entry in the keepass db in my opinion.

**Comment by AdamPS** [comment]
Syncing could be difficult or buggy in complex scenarios.  A user may have multiple databases.  Multiple users may share a database.  A user might have a separate tool that syncs their browser settings (typically the browser software includes this option).  Is it even going to be possible to be sure which is the correct/newest setting - local copy or database copy?

So for sure there can be a sync option, but it's not going to be suitable for everyone.

However there is another option that I think does work for everyone.  In the case where data is specific to one database entry, then store the data in the database as an attribute on the entry.  In particular this applies to the "Custom login fields" .

**Comment by varjolintu** [comment]
PR has been made for the basic feature.
