### ISSUE TITLE
Always fill password/TOTP when option is selected from right-click menu

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#378]
Currently, there are times where the username, password or TOTP does not automatically fill in and even right-click and selecting "Fill TOTP" for example does not fill it in. I read somewhere (I think) that this was restricted based on form names/types but my thought is if the user explicitly right-clicked on a field and clicked the fill password/TOTP option from the submenu that keepassxc-browser should always fill it in the input field that was focused/selected. Especially with TOTP because it really isn't that sensitive of information and should be pretty safe to fill in when the user explicitly clicked the option to do so.

**Comment by varjolintu** [comment]
Have you tried to setup an `KPH: {TOTP}` attribute with value `{TOTP}` to your entry, if it helps?

The only restriction here is that the credentials have to be selected before filling the TOTP.

**Comment by sebast889** [comment]
Yes, I have that in my entries. Even after filling in username/password automatically or with right-click option fill TOTP option is quite hit or miss and doesn't fill in anything for a few sites.

**Comment by varjolintu** [comment]
If you don't have the possibility to debug these yourself, could you give the site URL's?

**Comment by sebast889** [comment]
Sure, once I see which ones they were I will post the URLs. 

One thing I'm thinking is maybe the ones that didn't fill in the TOTP were the ones where user/pass didn't automatically fill in and I had to use the "Fill Username/Password" option instead. Which may not have made keepassxc-browser take it as an indicator that user/pass credentials were already selected/filled in.

**Comment by sebast889** [comment]
Been logging into some services over the week and so far no problems with right-click and fill TOTP. I may need to just log out and log back in all my accounts just to try reproduce this but that is too much effort for now.

I think the last update must have been a good one that maybe solved this. Can close this if you want. I will post if I come across any site which doesn't fill properly.
