### ISSUE TITLE
Firefox plugin pestering for a new version of KeePassXC 

### ISSUE THREAD

**Issue by agsteele** [keepassxreboot/keepassxc-browser#379]
My setup is as follows:

I use the original KeePass program (not XC) combined with a plugin KeePassNatMsg which communicates with the Firefox version of XC-Browser.

Over the weekend I noticed that XC-Browser is pestering for a a new version of KeePasXC. Since I've never used this and don't wish to do so I'd expect to be able to disable the pestering for updates to KeePassXC.

## Debug info

KeePassXC - Not installed but XC-browser reporting 1.3.2
KeePassXC-Browser - 2.0.3.0
Operating system: Win
Browser: Firefox

**Comment by phoerious** [comment]
There is no KeePassXC-Browser version 2.0.3.0. The current version is 2.3.4. The current KeePassXC-Browser version is 1.3.2. You can disable update checks in the browser extension settings.
