### ISSUE TITLE
Enhance security by looking at the protocol (http/https)

### ISSUE THREAD

**Issue by Davide95** [keepassxreboot/keepassxc-browser#380]
## Current Behavior
Now keepassxc-browser allows to fill in the credentials no matter if the URL is http://... or https://.

## Possible Solution
A solution could be having a flag in the settings allowing the user to choose between a normal usage or a stricter rule (e.g. a checkbox that allows or not the extension to fill in the input fields if the website is browsed trough HTTP or it has a wrong certificate.

In this way it can avoid MITM attacks and password spoofing.

**Comment by varjolintu** [comment]
Actually the URL scheme matters. Entry with a HTTPS URL doesn't work with HTTP sites. KeePassXC has this setting enabled by default (`Match URL scheme` in Browser Integration settings). And please note that disabling the matching is broken with 2.3.4. A 2.4.0 snapshot is needed for it to work. But matching works normally. The only exception is that if the entry has no scheme at all, then it is matched with both HTTP and HTTPS.

So my question is, how are you able to fill credentials with HTTPS URL to non-HTTPS site? Is there a bug somewhere? You didn't mention any KeePassXC or KeePassXC-Browser versions.

**Comment by Davide95** [comment]
Hi @varjolintu. Ok thank you for the information, now it is clear. That happened because I've not inserted any scheme in the database.
I'm using the latest version of both.

So is it correct to say that it will not fill in the input fields if the HTTPS certificate is invalid?
Thank you in advance.

**Comment by phoerious** [comment]
If the certificate is invalid, your browser will refuse to show you the web page, so no.

**Comment by Davide95** [comment]
@phoerious that's not always true. For instance, Google Chrome (latest version) only show you the alert message once. If it's ok for you the first time, then it'll not ask you again if you want to proceed.
Unfortunately that's happening a lot when I have to connect to a network which re-route my requests to a web interface until I do a login before browsing, etc.
It would be great to browsing on these conditions without being worried.
I know that's a not common corner case, but...

OT: sorry for my bad English but I'm not native

**Comment by droidmonkey** [comment]
There is a huge difference between invalid certificate and HTTP vs HTTPS.

**Comment by Davide95** [comment]
Ok guys, thank you for your explanations.
I'll close this ticket. Thank you for giving me your time.
