### ISSUE TITLE
Allow selection of KeePassXC group when creating new entry

### ISSUE THREAD

**Issue by wohali** [keepassxreboot/keepassxc-browser#382]
## Expected Behavior
When creating a new entry, I should be able to select the group within which I place the entry. For instance:
* Work (Job 1)
* Work (Job 2)
* Personal
* Financial
* Government
* Online Retailers
* Gaming

etc.

These would map to the groups inside of KeePassXC.

The dialogue could even allow for creation of new groups inside of KeePassXC.

## Current Behavior
All browser passwords are placed in a single group, KeePassXC-Browser Passwords. The user must then manually drag these to the group after creation - not convenient.

## Possible Solution
Provide a popup window on creation of entry that allows selection of group.

## Steps to Reproduce (for bugs)
Not a bug.

## Debug info
Not a bug.

**Comment by varjolintu** [comment]
This would be very nice. We need to discuss if this would be more convenient to add to the KeePassXC side instead.

**Comment by wohali** [comment]
I can see adding the bulk of the functionality to KeePassXC, but the point is that you can pick the group at the instant you create the new entry, which occurs in the dropdown in the browser.

Inspiration of course comes from Kee:

![mwsnap 2019-01-22 10_38_16](https://user-images.githubusercontent.com/112292/51546290-deb2c780-1e31-11e9-8797-0ee0a2baf040.png)

**Comment by varjolintu** [comment]
That would be possible too. KeePassXC 2.40 is released soon so I'll try to add this behaviour before that (just a basic support for a group parameter: if it's set, then use a group set by the user, otherwise use the default).

**Comment by droidmonkey** [comment]
We can also aim for 2.4.1 to add the hook. But if you can make it ready before the beta this week that would be awesome.

**Comment by wohali** [comment]
@varjolintu would the group list be exposed to the browser plugin as well, to populate the dropdown? Icons are only a nice to have.

**Comment by varjolintu** [comment]
@wohali That would be needed, yes.

**Comment by varjolintu** [comment]
It's done. See https://github.com/keepassxreboot/keepassxc-browser/pull/396 and https://github.com/keepassxreboot/keepassxc/pull/2637.
