### ISSUE TITLE
Allow ability to save latest login after submission, or at least autosave all generated passwords

### ISSUE THREAD

**Issue by wohali** [keepassxreboot/keepassxc-browser#383]
## Expected Behavior
It is too easy to enter a username and a password, generated by KeePassXC, on a website, then submit them, and forget to right click to save the credentials. In this situation, a user may have created a new account or changed a password on a website, and no longer be able to retrieve those credentials without going through a password recovery workflow provided external to KeePassXC.

## Current Behavior
Saving credentials entered into a form must be done *before* form submission, while the form is filled in.

## Possible Solution
Provide a Kee-style menu where "Save latest login" is possible.

Yes, I realize this requires caching the credentials in memory for at least one more page load per tab. It could be an opt-in option.

An alternative solution would be to always save passwords whenever autogenerated by the browser plugin.

## Steps to Reproduce (for bugs)
Not a bug.

## Debug info
Not a bug.

**Comment by wohali** [comment]
I see the blink, but saving at that point doesn't seem to work, especially not if it's an update. Is this a bug?

I have definitely filled in a u/p in a form, submitted, gone to the popup and not seen anything about saving.

**Comment by varjolintu** [comment]
So the popup displays normally but nothing is saved? It's a bug for sure, even if it displays the default popup when clicked during the blinking.

**Comment by wohali** [comment]
I can't reproduce this; closing for now.

**Comment by Tamce** [comment]
After submitting login form, some websites redirect more than 2 times, then extension's window will not show up, or it just showed up in the first page redirected for a very short time.
In such case, providing such opt will be useful.
@wohali

**Comment by varjolintu** [comment]
@Tamce That option has been already implemented and will be in the next release.

**Comment by Tamce** [comment]
Got it, thank you!
