### ISSUE TITLE
Key icon overlaps buttons on the right side of a Textbox

### ISSUE THREAD

**Issue by livingsilver94** [keepassxreboot/keepassxc-browser#384]
Key icon overlaps buttons on the right of a Textbox
## Expected Behavior
The Key icon should not prevent you from using buttons on the right of a Textbox.

## Current Behavior
Sometimes, the key icon overlaps said buttons, so that only the key icon is clickable.

## Possible Solution
Maybe place the key icon outside the Textbox, possibly only when a button is detected.

## Steps to Reproduce (for bugs)
1. Go to https://register.mailbox.org/en
2. Click somewhere next to the key icon

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
For now, there's no way to check if the key icon intersects with another image/SVG. This would need implementing `IntersectionObserver` to the combination input fields.

**Comment by varjolintu** [comment]
Possible duplicate with https://github.com/keepassxreboot/keepassxc-browser/issues/229, but here the key icon is put to the site by the site itself.

**Comment by kakra** [comment]
I could use the stylus extension to fix this on some sites manually but the icon already has CSS "left:###px" set, so I cannot use "position:relative;left:-16px".

**Comment by varjolintu** [comment]
@kakra That's too much job for such a small feature. #351 already hides the password generator icons by default, but the password generator can still be accessed via context menu or keyboard shortcut.
