### ISSUE TITLE
Cannot save authentication data in Chrome+Vivaldi

### ISSUE THREAD

**Issue by Lalarian** [keepassxreboot/keepassxc-browser#388]
Hello! I enter data into any registration form, and confirm.
The KeepassXC-Browser symbol flashes red, showing that it has recognized new authentication data to store. I click on the KeepassXC-Browser-Icon and it takes like 7 seconds until the little window opens, with KeepassXC-Browser showing the data it just captured.
Then I click on "New" for the extension to add the new authentication data to the connected database and the little window disappears, like it had save the data successfully - but it hasn't. The data I just entered i not in the connected database.

## Current Behavior

The newly added data is not addes to the database, despite all signs saying that it was

## Possible Solution
I don't know. Seems to be a bug, I think in the extension, and not in KeepassXC itself, because it's working fine from Waterfox/Firefox.

## Steps to Reproduce (for bugs)
1. enter registration data on web.de (but any other website is same!)
2. Confirm correctness of your personal data
3. Click the red flashing KeepassXC icon
4. Click 'new'
5. Check the databse for the freshly created account and see: Its not there.

## Debug info

KeePassXC - 2.4.0-snapshot Revision: 726bbb2
KeePassXC-Browser - Version: 1.3.2
Operating system:Linux - Xubuntu 18.04
Browser: Chrome+Vivaldi

**Comment by varjolintu** [comment]
Seems to work from the context menu with no problems. #387 is possible fix for this. Could you try it?

**Comment by jenzinger** [comment]
I have the exact same issue. I am on MacOS with KeePassXC 2.3.4 and XC Browser 1.3.2 in Chrome 71.0.3578.98.

I made 2 curious observations:

1. It worked once, but then never again, not even after reinstalling extension. The same behavior occured when I used KeePassHttp-Connector. It saved once to the KeePassXC database, then never again. This makes me wonder whether this is something more general with the communication with the main application?

2. When I click on save credentials in the extension pop-up, the database file seems to be modified, according to the entry for the file on my hard drive. Also I am syncing the database file and the sync updates the file on my remote drive - however the new password entry is not seen when I open the database. Closing and reopening KeePassXC does not change that.

**Comment by droidmonkey** [comment]
just to make sure, did you look in the right folder?

![image](https://user-images.githubusercontent.com/2809491/51794103-9e3cac00-2199-11e9-9856-63487f0743f0.png)

**Comment by Lalarian** [comment]
It wasn"t just a single occurence. It's like this 100% reproducible. All passwords I generated since I started using Vivaldi are gone. I look them up by using the search bar.

**Comment by jenzinger** [comment]
> just to make sure, did you look in the right folder?
> 
> ![image](https://user-images.githubusercontent.com/2809491/51794103-9e3cac00-2199-11e9-9856-63487f0743f0.png)

droidmonkey, that was a good one. First I thought, of course I did! But then I checked and here is what happened: I had moved the "KeePassXC Browser Passwords" group after a first test to the recycle bin and then all the new credentials were saved to the group inside the recycle bin! So thanks for the hint! I guess one could still call this a bug though - once inside the recycle bin, it should not be used to save new credentials. Instead a new entry should be created...

**Comment by droidmonkey** [comment]
For sure that is a bug, a new folder should be created in that case under root. This may be overcome by the "select a group" PR.

**Comment by jenzinger** [comment]
What is PR? Can I select a group when saving or will this be a new feature?
Btw. Is that Old Faithful blasting out of your hand?

**Comment by droidmonkey** [comment]
No it's a geyser across the ravine from old faithful called the beehive geyer that rarely blows (its about 2-3 times higher than old faithful).

A PR is a Pull Request which means a proposed feature or bug fix that is being reviewed.

**Comment by varjolintu** [comment]
I'll make the necessary fixes to #396. Folders under Recycle Bin should be invisible, and if KeePassXC-Browser Passwords is moved there, a new group should be generated.
