### ISSUE TITLE
Can't connect to KeePassXC on Windows 7 using Firefox 59

### ISSUE THREAD

**Issue by jagmoreira** [keepassxreboot/keepassxc-browser#39]
## Expected Behavior

The keepassxc-browser extension for Firefox should connect to KeePass portable on Windows 7.

## Current Behavior

The keepassxc-browser extension for Firefox cannot find running instance of KeePass portable on Windows 7.

## Steps to Reproduce (for bugs)

1. Download KeePassXC portable for Windows 7.
1. Install keepassxc-browser extension for Firefox
1. Start KeePassXC. Enable browser integration
1. "Connect" button does not appear. Instead "timeout or not connected to KeePassXC" message displays and the "Reload" shows up.
1. Click "Reload" button. Nothing happens.
1. Go to extension settings, then "Connected Databases". No databases are listed. Click "Connect" button. Still nothing happens.

## Debug info

After enabling add-on debugging (about:debugging) there's some error messages.

After clicking on the "Reload button":
![debugger_console](https://user-images.githubusercontent.com/13685125/36936177-10d7e350-1ec7-11e8-9492-45e54a6a994f.png)

## General Info
KeePassXC - 2.3.0
keepassxc-browser - 1.0.0

Operating system: Windows 7 64 bits
Browser: Firefox 59.0b14 (64-bit)
Proxy used: YES

* Tried KeePassXC portable and installer. Same behavior.
* Tried with and without proxy. Same behavior.
* Tried with a fresh Firefox profile with no other extensions. Same behavior.
* Interestingly, I also enabled "Legacy Browser Integration" and installed KeePassHttp-Connector extension. That extension works without any issues.

**Comment by varjolintu** [comment]
Please check if [these steps](https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900) help.

**Comment by varjolintu** [comment]
For these kind of situations please enable the `Updata native messaging manifest files at startup` option from Browser Integration's Advanced settings. It rewrites the new location to the .json scripts at every startup. Then you can move the portable folder freely.

**Comment by varjolintu** [comment]
Still having the issue?

**Comment by jagmoreira** [comment]
Problem was solved after you shared that link.

Closing issue now. thanks!
