### ISSUE TITLE
Add a "Fill Attribute" option to context menu

### ISSUE THREAD

**Issue by ceptonit** [keepassxreboot/keepassxc-browser#390]
## Expected Behavior
Add a option "Fill Attribute" to the context menu.
Here's a case scenario:
I have a Protonmail account that is protected by 2 passwords: a login password and a mailbox password.
Because there's no way to save 2 passwords in KeePassXC, I just added an additional attribute named "mailbox pass" and have the 2nd password saved to it.
So when Protonmail asks me for my Mailbox password, it'd be nice to just right-click the password field and "KeePassXC-Browser > Fill Attribute > mailbox pass".
If KeePassXC has more than 1 attribute for the website, display all of them one below another.
If there's no additional attributes for the site, hide the option or grey it out.

## Current Behavior
When you right click to a text field, you can choose between "Fill User + Pass", "Fill Pass Only", "Fill TOTP" "Show Password Generator Icons" and "Save credentials" but not "Fill Attribute".

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux Debian 9
Browser: Firefox 64.0.2

**Comment by varjolintu** [comment]
There's a simple workaround for this: Add a second entry with the mailbox password page URL.

Alternatively you can use Fill TOTP to fill any attribute (a little hacky way). Add the second password to your entry to a new attribute and name it `KPH: {TOTP}`.

**Comment by sebast889** [comment]
Can this be reopened? There is one gov site which asks me to fill in different pre-entered security question answer every time I log in. I'm sure there are more backwards banking/other gov sites out there that follow this method. "KeePassXC-Browser > Fill Attribute > attribute name" would make it easier to deal with these sites.

**Comment by varjolintu** [comment]
Sure, let's reopen this. The easiest solution for your problem is to select the security question input field as a String Field. Then it will be filled normally when filling username and password.

To get it work:
- Select `Choose custom login fields for this site`
- Select username and password fields (you can also skip one or both of these)
- After that select the security question input field (it will be selected as a String Field)
- Add a new attribute to your entry that starts with `KPH: ` (include the space)
- Value of that attribute will be filled automatically with the username and password now when the String Field is used

If the security question has its own page, then just make a new entry with the different URL.

**Comment by sebast889** [comment]
Thanks @varjolintu will try it out. But will that work for multiple attributes? They are asking for different security question answers every time not the same question.

**Comment by varjolintu** [comment]
It won't. Sorry.

**Comment by sebast889** [comment]
Oh ok then. In that case, a "Fill Attribute" option in the context menu would still be useful to make this less of a hassle.

**Comment by tremby** [comment]
Very keen on this feature. Do you bump feature requests up the queue for donations?

**Comment by varjolintu** [comment]
@tremby Sure. However, it should be decided if all attributes is allowed for filling or just the ones with a custom prefix (that could be much better IMO).

**Comment by tremby** [comment]
Decided to have a shot at it myself, over in #722.

**Comment by libklein** [comment]
What is the current state of this issue? The PR seems to be stalled. 
I could submit a new PR which works with the current version. 

Whats your stance on which attributes should be fillable? Should we continue to support only "KPH: "-prefixed attributes? Otherwise a PR to the client

**Comment by varjolintu** [comment]
I also looked at this PR today. It's not a big thing to get it finished. We should support only `KPH: ` prefixed attributes.

**Comment by varjolintu** [comment]
Feel free to test #1023.

**Comment by tremby** [comment]
Wow, thanks. While I'm still very interested in the feature, realistically I'm not going to have time to test any time soon. Hopefully @libklein can?
