### ISSUE TITLE
support the new thunderbird (with webextensions)

### ISSUE THREAD

**Issue by eike-fokken** [keepassxreboot/keepassxc-browser#393]
## Expected Behavior

I think with the coming thunderbird, it should be easier to make this addon work and would love to see this happening.

## Current Behavior

In Thunderbird 65 (beta) keepassxc-browser is installable from the xpi file but doesn't really work with the password prompts.

## Possible Solution

As the addon is installable, maybe it is not much work to incorporate the credentials for imap. If so and you have the time and energy, please do this.

**Comment by varjolintu** [comment]
Related thread from KeePassXC side: https://github.com/keepassxreboot/keepassxc/issues/1683

**Comment by varjolintu** [comment]
Closing this as the relevant issues are:
https://github.com/keepassxreboot/keepassxc/issues/1683
https://github.com/keepassxreboot/keepassxc/issues/7838

And the repository for Thunderbird extension:
https://github.com/kkapsner/keepassxc-mail
