### ISSUE TITLE
Login/password fields are not detected.

### ISSUE THREAD

**Issue by wolandtel** [keepassxreboot/keepassxc-browser#395]
## Expected Behavior
Detect login/password fields after they are rendered or by clicking on «Redetect…»

## Current Behavior
Login/password fields are not detected on login.aliexpress.com neither automatically nor by «Redetect…». I tried to specify custom fields but in that mode, the extension doesn't show any fields to select.

## Steps to Reproduce (for bugs)

1. Go to https://login.aliexpress.com.
2. Click «Redetect login fields»
3. Click «Choose custom login fields for this page».

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Chrome

**Comment by varjolintu** [comment]
Change your entry URL to `https://passport.aliexpress.com/`.

Alternatively with KeePassXC 2.4.0 (snapshot) to `https://aliexpress.com/`.

**Comment by hailfinger** [comment]
aliexpress.com is either still broken or broken again with
KeePassXC-Version: 2.4.3
KeePassXC-Browser-Version: 1.4.6
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

**Comment by varjolintu** [comment]
@hailfinger Cannot reproduce it. Sign in page works perfectly if your entry has the `https://passport.aliexpress.com/` as URL.

**Comment by hailfinger** [comment]
@varjolintu aliexpress.com logins with KeepassXC work perfectly in Chromium, and fail all the time (no credentials are available for selection) in Firefox. Other sites work fine in both browsers. The entry has https://passport.aliexpress.com/ as URL like you suggested.

**Comment by varjolintu** [comment]
@hailfinger I actually tested this with Firefox. With my own profile with all the extensions, and then via `web-ext` without any extensions and a new profile.

Does the page show the password generator icon in the login field?

**Comment by hailfinger** [comment]
No, the password generator icon is not shown in the password field of the "Login" tab. The icon is only shown in the password field of the "Register" tab.
So saving the credentials on registration should work, but filling them for actual login does not.

**Comment by varjolintu** [comment]
Does "Redetect credential fields" help? Or filling the credentials from the context menu?

These kind of errors are hard to track if we cannot reproduce them. Does the JavaScript console show any errors?

**Comment by hailfinger** [comment]
OK, this is weird. Same machine, different user account, same firefox version, same KeepassXC version, and it works.
"Redetect login fields" has no effect. Filling in the credentials from the context menu does not have any effect either (nothing is filled in).
If I right-click on the password field and select "show only this frame", KeepassXC can fill in the username/password in the page perfectly. Maybe the iframe acts as some sort of boundary...

**Comment by varjolintu** [comment]
Nowadays browsers won't allow extensions to access frames from another host, but this is not the case here.

Have you tried to make a new temporary profile to Firefox with the problematic user account, and see if it works too? Its not the first time I hear Firefox profiles can have strange problems without any good reason.

**Comment by hailfinger** [comment]
Here are the browser console messages:

LoginRecipes: getRecipes: falling back to a synchronous message for: https://passport.aliexpress.com LoginRecipes.jsm:239:9
this._recipeManager is null LoginManagerParent.jsm:91
nsLoginManager: searchLogins: `formSubmitURL` or `httpRealm` is recommended LoginManager.jsm:392:13
LoginRecipes: getRecipes: falling back to a synchronous message for: https://passport.aliexpress.com LoginRecipes.jsm:239:9
this._recipeManager is null LoginManagerParent.jsm:91
nsLoginManager: searchLogins: `formSubmitURL` or `httpRealm` is recommended LoginManager.jsm:392:13
Error: Nonce compare failed 4 keepass.js:1062:17
Error 14: Keine URL angegeben keepass.js:1078:13
Error: Promised response from onMessage listener went out of scope 4 init.js:79:27

**Comment by varjolintu** [comment]
Only strange thing I see there is that the frame URL might be missing from the request, which is strange. I wonder if there's some other extension that causes the error. I suggest you to try a new temporary profile.

**Comment by hailfinger** [comment]
You're right. With a new temporary Firefox profile, credential fields are detected and it works. Now the really interesting question is which Firefox setting is causing this problem.

**Comment by varjolintu** [comment]
I really don't have any idea about any experimental Firefox settings that could cause this. Have you tried uninstalling and reinstalling the extension?

**Comment by hailfinger** [comment]
Uninstalling and reinstalling the extension fixed it. I have no idea why, but now it works.
Thank you!
