### ISSUE TITLE
Firefox doesn't show the running version

### ISSUE THREAD

**Issue by icf20** [keepassxreboot/keepassxc-browser#399]
## Expected Behavior
this is the expected behaviour 
![image](https://user-images.githubusercontent.com/17784575/51799271-c1aa3a00-221f-11e9-9e3b-b2d09cf97dbf.png)

## Current Behavior
this is firefox 64.0.2
![image](https://user-images.githubusercontent.com/17784575/51799279-db4b8180-221f-11e9-9d1a-b05fcfef7d0f.png)

## Steps to Reproduce (for bugs)

1. install keepassxc
2. install https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/
3. click settings-> Connected Databases

for chromium

![image](https://user-images.githubusercontent.com/17784575/51799299-3d0beb80-2220-11e9-9bda-e31b5d9e569a.png)

for firefox
KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
![image](https://user-images.githubusercontent.com/17784575/51799310-4bf29e00-2220-11e9-865b-68d456fef00f.png)

so yea firefox cant detect the version running 

Operating system: /Linux
Browser: /Firefox/Chromium

**Comment by varjolintu** [comment]
Connect the database to your Firefox and try again.

**Comment by icf20** [comment]
> Connect the database to your Firefox

connection dont work like the image above shows 

![image](https://user-images.githubusercontent.com/17784575/51821874-d4357980-22da-11e9-84fb-65cde88b229e.png)

**Comment by varjolintu** [comment]
So, Firefox doesn't connect to your database at all? Have you enabled Firefox support from KeePassXC's Browser Integration settings?

The KeePassXC version won't be shown in the Settings page if the extension is not connected to KeePassXC. That's why Chromium shows the version normally.

**Comment by icf20** [comment]
> Firefox doesn't connect to your database at all?

not anymore, it did connect before, i dont recall if last firefox update has broken this or was something else 

> Have you enabled Firefox support from KeePassXC's Browser Integration settings?

yep

**Comment by varjolintu** [comment]
Please check through the [Troubleshooting Guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and reply your findings to this thread.
