### ISSUE TITLE
Make the 'password generator' box have a length for password generated

### ISSUE THREAD

**Issue by TheGoddessInari** [keepassxreboot/keepassxc-browser#400]
I'm using Firefox, so I'm not sure if it's the same with other browsers.

KeePassXC Browser appears to use the user-set settings set from KeePassXC? But there's no way to configure the password length in-browser. This is important as some sites have strange password length limits, and the password generated often needs to meet those specific length requirements.

If it's indeed using the user-set settings, the entropy estimation appears to be broken as it's just saying 800 bits of entropy, even when the actual entropy estimation is lower than that.

**Comment by mlavi** [comment]
Displaying the current password length generated would be a useful first (and easier) step, that would be my request!

**Comment by varjolintu** [comment]
Closing this because with KeePassXC 2.7.0 its own password generator dialog is used instead. The one in the extension will be removed within a year.
