### ISSUE TITLE
Do not make CTRL and ALT mandatory for keyboard shortcuts

### ISSUE THREAD

**Issue by Floflobel** [keepassxreboot/keepassxc-browser#401]
Hello

Would it be possible to remove the requirement to have an ALT or a CTRL in keyboard shortcuts?
Under firefox when I press ALT, I have the menu that appears.
![menu](https://user-images.githubusercontent.com/13889750/51986562-c7fb1900-24a0-11e9-8deb-479450422707.png)

The CTRL key is used for many shortcuts in the browser.

**Comment by Floflobel** [comment]
Thanks for these informations.
Ok I understand the obligation to use these keys then.
I think the error message is not enough when we do not use these mandatory keys. It may be necessary to modify it slightly by saying that these keys are mandatory.
I did not understand why it did not accept another key combination.

`Error: Shortcut for fill-totp has not been changed!`

**Comment by varjolintu** [comment]
Make sure the same shortcut isn't already used. For example for TOTP, if you try to trigger Ctrl+Shift+T instead of ALT+Shift+T, that won't work. Ctrl+Shift+T is used for opening a recently closed tab.
