### ISSUE TITLE
Credentials not refreshed after reconnect to database

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#402]
Basically that KeePassXC-Browser often, *not always*, doesn't work at all :laughing:

If KeePassXC isn't running, I expect KeePassXC-Browser to tell me that KeePassXC isn't running. It does, so no issue here.

After starting KeePassXC and unlocking my database, I expect KeePassXC-Browser to do what it's supposed to do: After clicking in the username field I expect KeePassXC-Browser to list all known logins for this website. I understand that this doesn't work automatically right now due to https://github.com/keepassxreboot/keepassxc-browser/issues/397#issuecomment-456793502, so no issue here.

:bug: Thus I click the "Reload" button manually. However, KeePassXC-Browser still doesn't work, even though the addon's modal tells me that it has successfully connected to KeePassXC - *and this is the issue*! No logins are shown. Nothing. There's no workaround to make KeePassXC show the logins. I have to manually lock and unlock my database. After doing so, all known logins for this website are shown correctly (most of the time at least, not always). So, definitely nothing wrong with "https://" or the stored URLs in general, otherwise it would fail all the time, not just randomly.

KeePassXC-Browser just randomly refuses to show any logins, even though KeePassXC-Browser tells me that everything is fine, there are matching logins in the database, the database is unlocked and KeePassXC is running. It should work. But doesn't.

I've no idea how to debug this, the only information I can provide is what KeePassXC-Browser prints in `about:debugging` and that's virtually nothing. Is there some sort of debug mode?

_Originally posted by @PhrozenByte in https://github.com/keepassxreboot/keepassxc-browser/issues/397#issuecomment-459477743_

**Comment by droidmonkey** [comment]
Bottom line: when a reconnect occurs, the extension needs to requery the database for the credentials available for the current tab as if the tab itself refreshes.

**Comment by varjolintu** [comment]
This is broken because of https://github.com/keepassxreboot/keepassxc-browser/pull/371.  I'm adding the fix to https://github.com/keepassxreboot/keepassxc-browser/pull/387. We should make a new release soon after I've made the necessary changes.
