### ISSUE TITLE
Feature Request: Reset inactivity time after used for fill

### ISSUE THREAD

**Issue by gerroon** [keepassxreboot/keepassxc-browser#403]
Hi,

I think that at the moment, the inactivity is calculated based on the interaction with gui. But it would be nice if browser refills are considered as activity so suc h activity actually resets the inactivity timer.

I might be wrong on this, since I am not a dev, talking based on interaction with it.

thanks

**Comment by droidmonkey** [comment]
This is a KeePassXC application issue. It is also already reported, thank you though.
