### ISSUE TITLE
Fetch 2FA code through the browser extension

### ISSUE THREAD

**Issue by lazycrypt** [keepassxreboot/keepassxc-browser#404]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Since the KeepassXC entries can be set up to generate 2FA codes like TOTP it would be convenient to be able to have the browser extension copy them at the user's request. This would be more convenient than having to manually go to the database and having to find the entry and copying the code.

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
Similar to accessing the database through the browser extension the extension would also be able to fetch TOTP codes by copying them into the clipboard or perform an autofill though I imagine the latter would be trickier to implement.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Like mentioned, it could work similarly to how the browser already fetches login info but it would also offer to get the 2FA code (if it detects the entry having it set up).

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Purely about convenience.

**Comment by varjolintu** [comment]
It has been implemented a long time ago. Use the context menu -> Fill TOTP or a keyboard shortcut ALT+Shift+T.

For 2.3.4 you need to add an extra attribute to your entry to get this work.
Add an attribute named `KPH: {TOTP}` with value `{TOTP}`. With 2.4.0 beta this should work without any extra steps.
