### ISSUE TITLE
Neither automatic nor manual login field detection works at support.mozilla.org

### ISSUE THREAD

**Issue by aib** [keepassxreboot/keepassxc-browser#406]
Using KeePassXC-Browser 1.3.2 on Firefox 65.0, "Choose custom login fields for this page" does not work at https://support.mozilla.org/ . The page doesn't darken, the "1. Choose a username field" instruction doesn't appear. Which is weird, given file:///dev/null works. Some kind of protection on Mozilla's part? Special page detection gone awry?

**Comment by varjolintu** [comment]
Yes. Mozilla has prevented content scripts for certain pages. See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

**Comment by aib** [comment]
Ah, okay then. I figured it wouldn't hurt to have this documented here, even if it weren't an actual bug.
