### ISSUE TITLE
Multiple matches when 'Search in all opened databases' is selected

### ISSUE THREAD

**Issue by TomSpidge** [keepassxreboot/keepassxc-browser#409]
## Expected Behavior
When matching credentials, only one entry in the options should exist for each entry in the database(s)

## Current Behavior
When the option 'search in all opened databases for matching credentials' is selected (Browser Integration, Advanced), there are three entries in the browser for each entry in the database. This disappears when the option is turned off, however then I have to keep skipping back to KeepassXC itself to select the correct database.
This applies in the list of matched credentials both in the access request and when offering to fill in the login fields. It's not serious, but when there are multiple credentials available means the list gets very long quickly, and also because there are still three options when filled in, the extension's dropdown regularly covers the submit/login button on many sites. You have to click away from the login field before you can submit the page.

## Steps to Reproduce (for bugs)
1. Set the option 'search in all opened databases for matching credentials' on.
2. Browse to website with single credential available
3. Three copies of the same credential are available.

## Debug info

{No errors/messages in the console}
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Firefox (3 copies) - Vivaldi (seems to be 2 copies)

**Comment by varjolintu** [comment]
Please try the latest KeePassXC 2.4.0 beta and see if this still occurs.

**Comment by TomSpidge** [comment]
Seems to behave as expected in 2.4.0, in fact on a brief use it seems much more willing to give me a password without having to go looking for it so better all round.
Is this a known issue, or just something that happens to have gone away in 2.4?

**Comment by varjolintu** [comment]
It's a known issue. There were multiple fixes for the matching options in 2.4.0. Closing the issue.
