### ISSUE TITLE
Error: No logins found

### ISSUE THREAD

**Issue by brud** [keepassxreboot/keepassxc-browser#412]
## Expected Behavior

1. Open page with URL that fully match URL in KeePassXC DB (https://<company_name>.okta.com schema matched too)
2. Press ctrl + shift + I (or ctrl + shift + U)
3. ???
4. **LOGIN (PROFIT)**

## Current Behavior

1. Open page with URL that fully match URL in KeePassXC DB (https://<company_name>.okta.com schema matched too)
2. Press ctrl + shift + I (or ctrl + shift + U)
3. ???
4. **Error: No logins found** (JS console is empty)

 **I'm trying to _redetect login fields_ and _choosing custom login fields on this page_ - this didn't help.**

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: MacOS 10.14.2
Browser: Chrome

**Comment by varjolintu** [comment]
Check if the login form is actually inside an iframe. The URL for it can differ from your main entry.

With KeePassXC 2.4.0 beta you can try to set your entry URL as `https://okta.com` which works as a wilcard.

**Comment by brud** [comment]
Thanks for quick response :)
Form isn't in iframe, I'm will be waiting for release 2.4.0 for checking wildcard

**Comment by varjolintu** [comment]
2.4.0 is released. Can you test it?

**Comment by brud** [comment]
sorry for long response, it's all right)

**Comment by waznico** [comment]
This error still exists. If I use Chromium Version 79.0.3945.130 (Official Build) Arch Linux (64-bit) and KeePassXC 2.5.3 I can connect the database but it always says "no logins found" e. g. when I want to login to GitHub.

**Comment by varjolintu** [comment]
@waznico What is your entry URL for GitHub?

**Comment by waznico** [comment]
@varjolintu Forgot it. Entry URL is https://github.com

**Comment by varjolintu** [comment]
@waznico I need more info. Can you debug the extension to see what happens?

**Comment by waznico** [comment]
Alright I don't know what happened. After restarting Chromium the extension couldn't reconnect to my KeePassXC database. I should run a reconnect and after that it now works. 
@varjolintu Don't think I can rerun this issue.

**Comment by varjolintu** [comment]
@waznico It could've been because of browser upgrade. In some cases the keys are not regenerated and the connection is not working properly until restart.
