### ISSUE TITLE
"Fill password only" does wrong thing

### ISSUE THREAD

**Issue by nazar-pc** [keepassxreboot/keepassxc-browser#413]
2 instances where "Fill password only" is broken on https://restream.io in Firefox.

## Expected Behavior
Expected behavior is to literally "Fill password only" in exact field I specified and not touching anything else anywhere.

## Current Behavior
**1 password recovery**
It fills username in both fields for some reason.
**2 password change**
It overrides password I typed in "Old password" field (which I didn't ask it to do) and filled username in both "New password" and "Confirm password" fields, which is ridiculous.

## Steps to Reproduce (for bugs)
**1 password recovery**
Go to https://restream.io/password_recovery type email from your account and follow link from email (you should have an account before doing that obviously).
You'll get to https://restream.io/reset_password/xyz page
I click on each field, select "Fill password only", select desired account (I had multiple added).
Change fields types to see what happened instead.

**2 password change**
Go to https://restream.io/auth/change_password
Type 123455 in "Old password" field
Select "Fill password only" with desired account (I had multiple added) in "New password" and "Confirm password" fields.
Change fields types to see what happened instead.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Firefox Nightly

**Comment by varjolintu** [comment]
Can you check the input field types if it's `password` or something else where username is filled instead of the password. Also, does this happen with Firefox Stable?

**Comment by nazar-pc** [comment]
Yes, it is `type=password` in all cases. Can't test Firefox Stable easily and I do not expect it to be different.

**Comment by droidmonkey** [comment]
Cannot replicate on Firefox with latest version of browser extension.
