### ISSUE TITLE
Doesn't find all form values (onba.ch)

### ISSUE THREAD

**Issue by bermeitinger-b** [keepassxreboot/keepassxc-browser#415]
## Expected Behavior
Should fill the correct values (username and password) into their respective fields at:
https://www.onba.ch/login/login?bank=sgkb

## Current Behavior
It does not find the fields to enter the credentials. When manually selecting "Fill Username and Password", only the username is set. Filling the password afterwards results in the message "no password field found".
Also, using the manual field selector, after selecting the username field as username, it doesn't allow me to select the password field; it is greyed out and not active.

## Steps to Reproduce (for bugs)
1. Have credentials at https://www.onba.ch/login/login?bank=sgkb
2. Try to autofill all credendials.
3. Only username is filled
4. Password is missing.

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Chrome and Firefox

**Comment by varjolintu** [comment]
I can reproduce this. It's happening because as a precaution, maximum number of input fields are set to 100. This page has much more of them, but those are hidden in sight. The scripting just modifies those in a way that they are "visible" which messes up the detection.

**Comment by droidmonkey** [comment]
Perhaps when we perform the field enumeration we should ignore those that are hidden.

**Comment by varjolintu** [comment]
I'll investigate if the visibility detection can be made a little earlier, even if it costs some performance.
