### ISSUE TITLE
"login.live.com" login page no username detected

### ISSUE THREAD

**Issue by yvanmoriame** [keepassxreboot/keepassxc-browser#419]
Site "login.live.com"  
"Username-only detection"  option is set 
"Custom login fields" username is set 
but however the error "no logins found" is received.

## Steps to Reproduce (for bugs)

1. go to https://loging.live.com/ 
2. 1st login page appear 
3. push alt+shift+u
--> error :     No logins found

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: windows 10
Browser: Chrome Version 72.0.3626.109 (Build officiel) (64 bits)

**Comment by varjolintu** [comment]
I cannot reproduce it. Does your entry have the correct scheme `https` in the URL? For me the site works even without the Username-only detection.

**Comment by yvanmoriame** [comment]
Yes, everything seems correct in the database but effectively, I deleted everything about "login.live.com" in the database. I recreated a new login for https://Login.live.com via keepassxc-browser in chrome and now everything is working again. Weird ...

**Comment by yvanmoriame** [comment]
The problem comes from the "KeePassXC-Browser Settings" in the old "entry" for login.live.com that I erased and rewritten  {"Allow":[],"Deny":["login.live.com"],"Realm":""}   
Now even the old undeleted entry works.
