### ISSUE TITLE
Cannot set property 'cssText' of undefined

### ISSUE THREAD

**Issue by Lukas-Kullmann** [keepassxreboot/keepassxc-browser#420]
## Expected Behavior

The extension never throws an error.

## Current Behavior

Sometimes, jQuery-UI throws an error. It's actually [this line](https://github.com/jquery/jquery-ui/blob/1.12.1/ui/effect.js#L180) that throws the error:

> Uncaught TypeError: Cannot set property 'cssText' of undefined
>    at jquery-ui.min.js:13
>    at jquery-ui.min.js:13
>    at jquery-ui.min.js:6
>    at jquery-ui.min.js:6

This happened on my website (not public, sorry) when there is HTML inserted into the DOM (via `element.innerHTML = '...';`) after the page was loaded.

## Possible Solution

Get rid of jQuery-UI. (Why is this used anyway?)

## Debug info

KeePassXC - 2.3.1
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Chromium

**Comment by varjolintu** [comment]
Let's add this issue to the list that will be solved by #128.
