### ISSUE TITLE
Connect/reconnect when user uses fill option in right-click menu

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#422]
If a user is a on a website login page but has not opened KeepassXC yet they will need to open their DB, click connect/reconnect in keepassxc-browser and if the credentials aren't showing up then they have to click redetect logins (or in my experience more than usual you have to reload the page if the login fields don't show any username/password or credentials dropdown automatically after reconnecting). 

If a user explicitly clicks any fill option (like Fill Username/Password) and the DB is not recognized as connected then keepassxc-browser should try to connect/reconnect to the DB and perform the fill action. This makes it easier to use and saves not doing a few of the steps mentioned above that can be done automatically when using the fill options.

**Comment by varjolintu** [comment]
This will be handled by https://github.com/keepassxreboot/keepassxc-browser/pull/355.

**Comment by sebast889** [comment]
@varjolintu

I upgraded to the latest extension version but I still get the issue where the extension won't connect automatically whenever I open KeepassXC after I've opened Firefox. Only when I start the application before the browser is opened does it connect automatically.

**Comment by varjolintu** [comment]
Hmm. It's possible that the default setting for reconnecting is not triggered. Try to disable/re-enable the reconnect setting?

**Comment by sebast889** [comment]
Same result even after disabling/re-enabling the reconnect setting in the extension page.

**Comment by varjolintu** [comment]
What's the error message you are seeing? Can you debug the extension and see what the console shows?

**Comment by sebast889** [comment]
Error message in popup was Message encryption failed. Is KeePassXC running?

I tried debugging the extension then opened KeepassXC and the DB and there still wasn't any console messages except Error 7: Message encryption failed. Is KeePassXC running? keepass.js:1086:13.

**Comment by varjolintu** [comment]
I'll try to reproduce this.

**Comment by Bruceforce** [comment]
@varjolintu 
I have the same problem and error message with Chrome. 

What works
- start KPXC BEFORE opening the browser
- let Chrome open, close KPXC and restart KPXC
- --> automatically reconnects

What doesn't work
- close Chrome completely 
- restart it and AFTER that open KPXC
- --> not reconnecting

It works if I click the `reconnect` button in the browser extension then but only for one single time. If I restart KPXC after "manually reconnecting" I have to reconnect manually again to make it work.

**Comment by varjolintu** [comment]
@Bruceforce I found the bug. Adding it to a PR that fixes multiple issues.

**Comment by sebast889** [comment]
@varjolintu

Just wondering, was the PR for this already merged or not yet?

**Comment by varjolintu** [comment]
@sebast889 There's one PR that fixes a double reconnect, but doesn't fix this issue yet. I'll have to make a separate PR for that, but haven't had the time for that yet.

**Comment by Bruceforce** [comment]
@varjolintu I think we should re-open this one here until you find time to make a PR, since in the current state the issue here is still valid.

**Comment by varjolintu** [comment]
@Bruceforce I'll make a new issue about it later. The actual description differs.

**Comment by sebast889** [comment]
@varjolintu

Was this supposed to be fixed in the latest version? I'm still facing the same issue

**Comment by varjolintu** [comment]
@sebast889 1.4.5 changed the reconnect behavior a little bit. Now triggering the popup doesn't try reconnecting automatically. It caused more problems than any good.

**Comment by sebast889** [comment]
For me it solved the double reconnect issue and clicking reload connects to the database correctly instead of giving me wrong error messages so I think it wasn't all bad :) 

Only automatic reconnect is the only one I see not working for me. Maybe if I try logging in to more websites I'll see more issues.

**Comment by varjolintu** [comment]
@sebast889 I tested the automatic reconnect with a site that had credentials. Quitting KeePassXC cleared the credentials (and the popup icon went to gray). When I reopened KeePassXC, the icon changed to green with a question mark and the input fields were regognized normally. Autocomplete menu also worked instantly.

Could you elaborate how it doesn't work for you? The input fields are not regognized?

**Comment by sebast889** [comment]
1. Open Firefox
2. Open website login page with credentials
3. Open KeePassXC and open DB
4. Go back to website login page and see it isn't connected to the DB (only clicking Reload from popup or opening a new tab and going to login page reconnects it)

I wonder if install method and platform could have anything to do with it (I tested on Firefox, windows, portable install)

**Comment by varjolintu** [comment]
@sebast889 That sounds like the auto-reconnect feature is not enabled at all. I need to recheck this behaviour on Windows.

**Comment by sebast889** [comment]
Automatically reconnect to KeePassXC is ticked in settings page just to be sure.

**Comment by varjolintu** [comment]
@sebast889 I had to disable/re-enable the setting to get it work properly under Windows. I must check if there's something that messes up the default setting.

**Comment by sebast889** [comment]
I couldn't get it to work even after enabling/disabling. Are you closing Firefox after doing that? Because after I enable/disable then close Firefox then repeat the steps I mentioned above it's the same result.
