### ISSUE TITLE
Input field type email is ignored as possible credential field.

### ISSUE THREAD

**Issue by KonradDeskiewicz** [keepassxreboot/keepassxc-browser#423]
When login field is specified as email type KeepassXC doesn't detect it as possible credential field.

**Comment by droidmonkey** [comment]
You need to provide more details. Website URL? Is this a multi-part login form that shows username alone, then password on next page?

**Comment by KonradDeskiewicz** [comment]
Login form is provided via modal window. There are two inputs: email & password.
KeepassXC only detect password field. Once I change input type from email to text KeepassXC detects both fields.

**Comment by varjolintu** [comment]
Email field is normally detected without problems (see [https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_email](https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_email). Could you give the site URL if possible?

**Comment by KonradDeskiewicz** [comment]
Unfortunately this is still local dev. Maybe fact that this is Vue component that is dynamically added has something to do with that...

**Comment by KonradDeskiewicz** [comment]
![image](https://user-images.githubusercontent.com/17060750/53352591-5a1d0280-3923-11e9-86fe-9787be097502.png)
No email fields detected on my browser...

**Comment by varjolintu** [comment]
This happens because of iframe. What I meant was:
![screen shot 2019-02-25 at 18 35 09](https://user-images.githubusercontent.com/24570482/53352783-1a0e4d80-392c-11e9-84fe-16037be7c019.png)

**Comment by KonradDeskiewicz** [comment]
![image](https://user-images.githubusercontent.com/17060750/53354201-9736c400-3926-11e9-953a-aa1ebb35f28f.png)
cip-id is there...

**Comment by varjolintu** [comment]
Could you elaborate some more please? Is this custom login field thing the only one that doesn't find the field, or cannot you fill any credentials? I can see the password icon is also visible, so there shouldn't be any problems filling something.

**Comment by KonradDeskiewicz** [comment]
Exacltly like this: password is OK, but login (e-mail) field is not detected. When I try to re-detect fields for credentials the only one that is "highlighted" is password field

**Comment by varjolintu** [comment]
Well that's strange. It would help if I could test it myself.

**Comment by bermeitinger-b** [comment]
It says `type='e-mail'` instead of email. Could this be the problem?

**Comment by KonradDeskiewicz** [comment]
OMG... that's it. I'm so embarrassed. Sorry for the trouble.
