### ISSUE TITLE
Redetect login fields does not work

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc-browser#425]
## Expected Behavior

Clicking on »Redetect login fields« should request login credentials on pages they contain a login form.

## Steps to Reproduce (for bugs)

1. Go to a page with login form
1. When KeePassXC pops up the dialogue for the credentials press *Cancel*
1. Press the toolbar icon and select *Redetect login fields*
1. Expected: KeePassXC's dialogue should pop up, but it doesn't happen.

## Debug info
KeePassXC-Browser Version: 1.3.2
KeePassXC Version: 2.4.0
Operating system: Linux
Browser: Firefox 56

**Comment by varjolintu** [comment]
If you have pressed cancel for the credential request, a plain Redetect login fields will not retrigger it. You must reload the page.

**Comment by jo-so** [comment]
I have the same problem, when the database is locked, I open a page, unlock the database and press "redetect login fields" which doesn't trigger a redetect. Is this expected, too?

**Comment by varjolintu** [comment]
No, that's not expected. It's possible that #358 solves this too.

Does this happen on a page that I can test?

**Comment by jo-so** [comment]
Yes, it happens, for example, on https://www.ebay-kleinanzeigen.de/m-einloggen.html

**Comment by varjolintu** [comment]
I cannot reproduce the error with that site. The credential dialog will be displayed right after I unlock the database.

**Comment by whisdol** [comment]
I can reproduce this on this site (and others), but I believe this is the same issue [we discussed before](https://github.com/keepassxreboot/keepassxc-browser/pull/387#issuecomment-459958575). So yes, #358 should solve this as well.

**Comment by varjolintu** [comment]
Can you test this with 1.3.3?
