### ISSUE TITLE
Extend debug info for bug reports

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc-browser#426]
## Expected Behaviour

The *About* page in the settings should contain all debug informations requested in an issue report. And a direct link to a [new issue](https://github.com/keepassxreboot/keepassxc-browser/issues/new) might be helpful.

Reporting new bugs should be as easy as going to the *about* page, copying the debug infos, clicking on new issue and pasting the debug info.

BTW: You should bump the copyright year to 2019.

## Debug info

KeePassXC-Browser Version: 1.3.2
KeePassXC Version: 2.4.0 
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Thanks for the tip! I'll include these to #416.
