### ISSUE TITLE
Set default group for saving new logins

### ISSUE THREAD

**Issue by wolftune** [keepassxreboot/keepassxc-browser#427]
## Expected Behavior

I should be able to name the main group where logins are saved and have new ones go to that group.

## Current Behavior

Each new entry keeps creating a group called "KeePassXC-Browser Passwords".

Side-note: I wish you'd move UI and naming stuff to "passphrase" instead of "password" in general.

## Possible Solution

Related to #382 — but I don't want to have to choose a group every time, I'd like to just have a default group that saved items go to (probably with a preference of whether to ask which group vs use the default)

**Comment by droidmonkey** [comment]
This is a duplicate

**Comment by varjolintu** [comment]
I'll add this option to the existing PR https://github.com/keepassxreboot/keepassxc-browser/pull/396.

**Comment by varjolintu** [comment]
A following new setting has been added to the PR:
![Screen Shot 2019-03-09 at 10 32 40](https://user-images.githubusercontent.com/24570482/54071373-6df62c00-4274-11e9-8d92-3c5918ac4da1.png)
