### ISSUE TITLE
No credentials saved when connecting on a website

### ISSUE THREAD

**Issue by trollepierre** [keepassxreboot/keepassxc-browser#428]
## Expected Behavior

I would expect if I connect to a website, that KeePassXC-Browser will save the credentials for next connections. 

## Current Behavior

WHEN I connect to a website, no credentials are saved

## Possible Solution

No idea. First use

## Steps to Reproduce (for bugs)

1. My database has no entries.
2. I connect to Gmail. 
3. No password, login are saved into the database KeePassXC

## Debug info

KeePassXC - 2.34
KeePassXC-Browser - 1.3.2
Operating system: Mac
Browser: Chrome/Firefox/

**Comment by droidmonkey** [comment]
I am assuming you are thinking that the connect button is for the website itself, it isn't. The connect button connects the browser extension to your KeePassXC database. You need to actively log into an account to trigger a "save event" which will flash the extension icon. At that point, click the flashing icon and you can create a new entry.

**Comment by trollepierre** [comment]
ok, it works here for the first time. Thanks
