### ISSUE TITLE
jQuery bug for selectors with special characters

### ISSUE THREAD

**Issue by dxdc** [keepassxreboot/keepassxc-browser#429]
When visiting this site: `https://app.onpay.com/app/login`, I see a number of jQuery errors in the console and the autofill login. This is caused by the ID selectors `widget_core/ui/ALabelBox_0` and `widget_core/ui/ALabelBox_1`, which contain the special character `/`.

This leads to the following console stacktrace:

```
jquery-3.3.1.min.js:2 Uncaught (in promise) Error: Syntax error, unrecognized expression: input#core/ui/ALabelBox_0
    at Function.oe.error (jquery-3.3.1.min.js:2)
    at oe.tokenize (jquery-3.3.1.min.js:2)
    at oe.select (jquery-3.3.1.min.js:2)
    at Function.oe [as find] (jquery-3.3.1.min.js:2)
    at w.fn.init.find (jquery-3.3.1.min.js:2)
    at new w.fn.init (jquery-3.3.1.min.js:2)
    at w (jquery-3.3.1.min.js:2)
    at Object.cipFields.setUniqueId (keepassxc-browser.js:746)
    at Object.cipFields.getAllFields (keepassxc-browser.js:847)
    at browser.runtime.sendMessage.then (keepassxc-browser.js:1390)
```

## Possible Solution
I am going to submit a PR that I tested that seems more robust, using `jQuery.escapeSelector` instead of individual regex replacements. It seems the problem is the lack of support for many special characters in the function `cipFields.prepareId`.

https://github.com/keepassxreboot/keepassxc-browser/blob/c3a36027b53b908c36e8ccc6d9e1ebf62ae979db/keepassxc-browser/keepassxc-browser.js#L836-L838

## Debug info

KeePassXC-Browser Version: 1.3.2
KeePassXC Version: 2.3.4
Operating system: Mac
Browser: Chrome

**Comment by droidmonkey** [comment]
We are eliminating jQuery

**Comment by dxdc** [comment]
@droidmonkey OK. You can extract the jQuery functions. It will provide far more robust handling.

I looked it up, jQuery.escapeSelector is a reference to `Sizzle.escape`. This code could just be incorporated as is then.

```js
var rcssescape = /([\0-\x1f\x7f]|^-?\d)|^-$|[^\0-\x1f\x7f-\uFFFF\w-]/g,
    fcssescape = function(ch, asCodePoint) {
        if (asCodePoint) {

            // U+0000 NULL becomes U+FFFD REPLACEMENT CHARACTER
            if (ch === "\0") {
                return "\uFFFD";
            }

            // Control characters and (dependent upon position) numbers get escaped as code points
            return ch.slice(0, -1) + "\\" + ch.charCodeAt(ch.length - 1).toString(16) + " ";
        }

        // Other potentially-special ASCII characters get backslash-escaped
        return "\\" + ch;
    };

Sizzle.escape = function(sel) {
    return (sel + "").replace(rcssescape, fcssescape);
};
```

**Comment by dxdc** [comment]
Added new commit: 038a33a

**Comment by varjolintu** [comment]
Closing this because of a pull request that already eliminates jQuery from the content scripts.

**Comment by dxdc** [comment]
@varjolintu I reviewed #128. It does *not* fix this bug, and is the same problem. The `prepareId` function is not properly escaping all characters.

Please see my commit here, which can be easily tweaked to integrate to `prepareId` to cure this bug: 038a33a

```js
kpxcFields.prepareId = function(id) {
    return id.replace(/[:#.,\[\]\(\)' "]/g, function(m) { return '\\'+m; });
};
```
