### ISSUE TITLE
Javascript error on Ungoogled-Chromium v72.0.3626.121

### ISSUE THREAD

**Issue by Gladuin** [keepassxreboot/keepassxc-browser#431]
Hello,

I am using ungoogled-chromium v72.0.3626.121 on my computer and I wanted to try out KeePassXC-Browser today.
I've checked in Appdata/Local/keepassxc and it has the json with the correct info
The registry key is present.

When I debug the extension while I press the reload button I get this error:
![chrome_2019-03-06_20-46-07](https://user-images.githubusercontent.com/34450360/53909016-ebd9ed80-4050-11e9-8ff6-b4525f0bb6fe.png)

I also checked in task manager if keepassxc-proxy.exe had started but it didn't. After I had manually started keepassxc-proxy.exe it still didn't work.

I hope you can help me out because I am seriously stuck

**Comment by droidmonkey** [comment]
Are you on Linux, Mac, or Windows?

**Comment by Gladuin** [comment]
On windows, for some reason the issue template didn't show up for me but I'll make sure to use it next time

**Comment by droidmonkey** [comment]
This could be because "ungoogled-chromium" is using a different registry key for native application interfaces than the "googled" version

**Comment by Gladuin** [comment]
That's probably not it because there are other registry keys in the folder
![image](https://user-images.githubusercontent.com/34450360/53911249-34e07080-4056-11e9-9182-47d3acf797f7.png)

**Comment by varjolintu** [comment]
What's behind the NativeMessagingHosts folder? Check if that points to a right location.

**Comment by adnion** [comment]
I get exactly the same error on linux with the ungoogled-chromium appimage.
Couldn't test it with the google-chrome appimage yet.

**Comment by droidmonkey** [comment]
Is this still an issue with the latest version?

**Comment by adnion** [comment]
Solved for normal Ungoogled-Chromium (71+) and KeePassXC-Browser 1.4.3.

For me it does not work when both apps are AppImages:
AppImage Ungoogled-Chromium 71.0.3578.98-2 
AppImage KeePassXC 2.4.1

Note that **if I only use one appimage** of the above and install the other application locally **it does work**.

**Comment by droidmonkey** [comment]
Great. The appimage issues is probably related to app armor or similar issue.

**Comment by probonopd** [comment]
Are the two applications supposed to communicate somehow? The application inside AppImage 1 does not see the application inside AppImage 2 because both are mounted to different mountpoints with no knowledge about each other.

**Comment by adnion** [comment]
Yes there's a proxy between KeePassXC and the browser extension KeePassXC-Browser.
https://github.com/keepassxreboot/keepassxc/pull/1530
