### ISSUE TITLE
Can't detect fields on sirsi library sites

### ISSUE THREAD

**Issue by wolftune** [keepassxreboot/keepassxc-browser#433]
My local library site: https://lincc.ent.sirsi.net/client/en_US/lincc

No attempt can identify the fields in the popup that show when I click to log in

## Expected Behavior

At least with the custom option, I should be able to detect the fields and thus save and also enter my creds. The custom option only finds the search field.

## Steps to Reproduce (for bugs)

1. Go to the link
2. Try to use keepassxc-browser

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux (KDE Neon 18.04
Browser: Firefox

console stuff:
```
Loading failed for the <script> with source “https://www.google.com/books/jsapi.js”. lincc:8:1
Loading failed for the <script> with source “https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit”. lincc:162:1
TypeError: I is undefined[Learn More] core.js:1:15724
Stylesheets without CSSOM changes reparsed to check for errors. Refresh the page to also see errors from stylesheets changed from CSSOM and from style attributes.
XHRGEThttps://lincc.ent.sirsi.net/client/en_US/lincc/search/patronlogin:loggedIn?_=1552084571394
[HTTP/2.0 200 OK 256ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/ctx//client/css/images/ui-icons_222222_256x240.png
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/en_US/lincc/search/patronlogin/$N
[HTTP/2.0 200 OK 93ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/core/tree.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/ctx//client/css/jquery-ui-1.8.12.custom.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/core/default.css
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/ctx//client/css/jquery-selectable.custom.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/core/tapestry-console.css
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/ctx//client/css/vse/css/Discovery_base.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/ctx//client/css/format-types.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/app/components/search/suggest.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/core/t5-alerts.css
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/custom/web/CLCK_custom001.css
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/app/pages/search/PatronLogin.js
GEThttps://lincc.ent.sirsi.net/client/js/jquery-1.5.1.min.js
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/stack/en_US/core.js
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/stack/en_US/CoreSearchStack.js
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/assets/5.0.0/stack/en_US/SearchTemplateStack.js
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/custom/web/CLCK_custom.js
[HTTP/2.0 200 OK 0ms]
GEThttps://lincc.ent.sirsi.net/client/js/ui/jquery-ui-1.8.12.custom.js
[HTTP/2.0 200 OK 0ms]
GEThttps://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css
GEThttps://clck.ent.sirsi.net/client/css/vse/boxed.css
GEThttps://clck.ent.sirsi.net/client/css/vse/css/boxed_webapp.css
[HTTP/2.0 200 OK 0ms]
GEThttps://clck.ent.sirsi.net/client/css/images/sirsidynix/alert-overlay.png
[HTTP/2.0 302 Found 81ms]
GEThttps://lincc.ent.sirsi.net/custom/web/content/images/lincc_logo_login_banner3.png
[HTTP/2.0 200 OK 0ms]
GEThttps://clck.ent.sirsi.net/client/en_US/lincc
[HTTP/2.0 200 OK 214ms]
```

**Comment by varjolintu** [comment]
This happens because the login dialog is actually inside an iframe. Those kind of situations are tricky to detect and sometimes doesn't work properly. We are trying to improve the extension to be more fluent with iframes.

**Comment by wolftune** [comment]
Thanks for the clarity. Tangentially: is it appropriate for me to complain about such iframes to the specific web developers? I'll do so when I can… ;)  There's a lot of garbage out there in how people build sites. In this case, the site also fails to keep me logged in for even a few minutes and I have to constantly log in…

**Comment by varjolintu** [comment]
Clearly that's an issue in the web design. Still, we should have a proper support for iframes. It would be much easier for us if standards were used properly :)

**Comment by bondjames007** [comment]
Same issue with chase.com.

**Comment by varjolintu** [comment]
chase.com has been mentioned several times in the issues. No jQuery branch works a bit better for that site. But sometimes I still have to redetect the credentials from the main page. The other login page works just fine.

**Comment by dl200010** [comment]
Another site is https://www.mysynchrony.com/

It is very stupid they put the form inside iFrames, but the companies use this bad design.

**Comment by varjolintu** [comment]
@dl200010 Generally iframes should work normally, but in this case it's not regognized properly. As a workaround you can select the username field and use context menu or keyboard shortcut to fill the credentials. That will work.

**Comment by dl200010** [comment]
@varjolintu The context menu for this page does not work either. I click on the "Fill Username and Password" and it does nothing but say the fields are invalid. Nothing fills in.

**Comment by varjolintu** [comment]
@dl200010 Try to set the URL in your entry to `https://mysynchrony.com` removing the `www`.

**Comment by dl200010** [comment]
@varjolintu I have tired this before. On many sites that have their login form inside an iframe. Never works. I have also found another one that uses an iframe and doesn't work. https://www.chase.com/

**Comment by varjolintu** [comment]
@dl200010 chase.com uses a different subdomain for the iframe. If you change your entry URL to `https://chase.com` you can fill the credentials using the context menu or keyboard shortcut.

**Comment by dl200010** [comment]
So, this time chase.com worked. I have tried this before, but always had issues until now. With the mysynchrony.com I found the problem isn't with the plugin, but with the fact that they block pasting into forms. How they do this, I am unsure of. I just installed a plugin (https://addons.mozilla.org/en-US/firefox/addon/don-t-fuck-with-paste/) that prevents paste blocking. I had to activate it on the main site and open the iframe in new tab (right click > this frame > open frame in new tab) and activate the plugin on the iframe host.

**Comment by varjolintu** [comment]
@dl200010 I got mysynchrony.com working with the following steps:
- Change the entry URL to `https://mysynchrony.com` (so it wildcards the subdomain the login form has)
- Enable JavaScript only for the main site (uBlock Origin's Advanced mode can do this)

Without the Advanced mode, or JavaScript blocked totally the login form doesn't even open.

Alternatively, you can use the URL `https://consumercenter.mysynchrony.com/consumercenter/welcomeAction.do?subActionID=1000&amp;RETURN_URL=https://www.mysynchrony.com/mysyf/home.html` for that site instead of the main page.

**Comment by varjolintu** [comment]
I finally had some time to do research.

The Sirsi site login detection fails because the form action contains a string `search` and we are ignoring those forms. You can still fill the credentials "by force" using the context menu.

I also have a fix ready for `mysynchrony.com` and `chase.com`. In my tests those sites now work as they should.
