### ISSUE TITLE
Ignored site still have "green keys" on password fields.

### ISSUE THREAD

**Issue by rkozka** [keepassxreboot/keepassxc-browser#434]
I have added my bank site to ignored sites with option "Disable all features" but "green keys" icons are still shown on password fields.

## Expected Behavior

I would like plugin to completly ignore a site url i have provided in ignore settings.

## Current Behavior

"Green keys" still shown on ignored site with "disable all features" option.

Screenshots:
![site](https://user-images.githubusercontent.com/9077931/54084521-2635da00-4332-11e9-8c99-abe1ee4ca83f.PNG)

![password](https://user-images.githubusercontent.com/9077931/54084567-86c51700-4332-11e9-8ef2-720d8b7ebe71.jpg)

## Steps to Reproduce (for bugs)

1. Add ignored site URL https://system.aliorbank.pl/ and select "disable all features".
2. Go to site https://system.aliorbank.pl/sign-in
3. Provide login 50501111 (i randomly choosed this but its valid)
4. Green keys are shown on all password field.

I have also tried adding ignore url "https://system.aliorbank.pl/sign-in/password" but this changes nothing.

## Debug info

KeePassXC-Browser Version: 1.3.2
KeePassXC Version: 2.3.4 
Operating system: Windows 10
Browser: Firefox 65.0.2

**Comment by varjolintu** [comment]
Well.. changing the ignore URL to the last one you mentioned fixes this for me. You can also set the URL to `https://system.aliorbank.pl/*`

**Comment by rkozka** [comment]
Well this is awkward... it worked for me this time o_O Much apologies for the problem.
