### ISSUE TITLE
Chrome integration with KeePassXC-Browser intermittently requires restarting of web browser

### ISSUE THREAD

**Issue by patrick0057** [keepassxreboot/keepassxc-browser#435]
## Expected Behavior
When the KeePassXC database is unlocked, I expect at all times for the KeePassXC-Browser integration to work.

## Current Behavior
Intermittently after locking my mac I find that my KeePassXC-Browser no longer offers usernames and passwords from the database.  The only solution is to quit Chrome and restart it.  I've tried "Redetect login fields" and "Reload database" options in the chrome extension menu however those don't usually fix the problem.

## Steps to Reproduce
1. Setup KeePassXC-Browser integration
2. Lock computer a few times, leave it running over night and eventually it will stop working thus requiring a restart of the Chrome browser.

## Debug Info
KeePassXC - Version 2.3.4
KeePassXC-Browser Version: 1.3.2
Revision: 6fe821c

Libraries:
- Qt 5.9.3
- libgcrypt 1.8.2

Operating system: macOS 10.14
CPU architecture: x86_64
Kernel: darwin 18.2.0

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by varjolintu** [comment]
This is probably solved with https://github.com/keepassxreboot/keepassxc-browser/pull/358.
