### ISSUE TITLE
Support Brave browser

### ISSUE THREAD

**Issue by guedressel** [keepassxreboot/keepassxc-browser#436]
Today I installed [Brave](https://brave.com) and sure enough I added the KeepassXC Browser Extension immediately at the first run.
But apparently it wasn't able to connect it with my KeepassXC Wallet:

    KeePassXC-Browser has encountered an error:
    Timeout or not connected to KeePassXC.

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Linux
Browser: Brave (Version 0.61.50 Chromium: 73.0.3683.67 (Official Build) unknown (64-bit))

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/2414.
