### ISSUE TITLE
A little bit of usage documentation :)

### ISSUE THREAD

**Issue by lydell** [keepassxreboot/keepassxc-browser#44]
Currently, neither the README nor the Chrome/Mozilla installation pages say what the addon actually does.

Would be nice with just a couple of sentences or a bullet list stating what the main features are. Perhaps a screen shot or two.

I found this which is really good: https://github.com/pfn/passifox/blob/master/documentation/chromeIPass.md

It does not have to be so comprehensive, but I'm sure there's some good stuff in there that could be used for starters.

Finally, it would also be nice if there was a short section discussing the difference between global auto-type and this addon, both UX wise and security wise.

Thanks!

**Comment by varjolintu** [comment]
How about this?
[https://keepassxc.org/docs/keepassxc-browser-migration/](https://keepassxc.org/docs/keepassxc-browser-migration/)

**Comment by lydell** [comment]
That's a great guide for configuring the addon! It doesn't say what the addon actually does, though.
