### ISSUE TITLE
Starting Firefox on Windows 10 doesn't start keepassxc-proxy

### ISSUE THREAD

**Issue by blu28** [keepassxreboot/keepassxc-browser#440]
I have KeePassXC and KeepassXC-browser installed on a Windows 10 system with Firefox. 
KeePassXC is version 2.3.4
KeepPassXC-browser is 1.3.2
When I start Firefox the database is not connected.

## Expected Behavior
I expect that when Firefox is started it and I attempt to use the KeePass icon in the toolbar it will start the proxy which in turn will start KeePassXC and connect the database. 

## Current Behavior
The icon shows the database is not connected. It shows a message "Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?"
If I start KeePassXC manually and then start the proxy manually, I can click on settings and "Connect" and get it to connect. Am I wrong about the expected behavior? Do I need to start the program and the proxy manually?

**Comment by droidmonkey** [comment]
The proxy does not launch KeePassXC, you have to launch the main application yourself.

**Comment by blu28** [comment]
Okay, so what is the exact sequence of events? Does it matter if the main app is launched before or after the browser?

**Comment by varjolintu** [comment]
Most fluent way is to start KeePassXC before the browser. If you do it backwards you have to reconnect the browser extension from the popup icon (and select Reload).

Automatic reloading is coming soon to the extension. There are still few things we must solve with the pull request.

**Comment by varjolintu** [comment]
This is fixed with #128.
