### ISSUE TITLE
Can't connect to Database after upgrade to KeePassXC 2.4.0

### ISSUE THREAD

**Issue by pstorch** [keepassxreboot/keepassxc-browser#441]
Maybe I was to fast with the upgrade and have to wait for a newer release of the Browser Extension. But I just updated to KeePassXC 2.4.0 and the Extension can't connect anymore. 

The upgrade process told me that it had to restructure the Browser keys and that a reboot might be necessary. I agreed and rebooted. But still no connection possible:

![image](https://user-images.githubusercontent.com/5598124/54667986-0ea6e000-4aee-11e9-895f-c7969b8c4186.png)

I also removed the old connection and tried to setup a new one, but with no success.

## Debug info
KeePassXC-Browser Version: 1.3.2
KeePassXC Version: 2.4.0 
Operating system: Win 7
Browser: Firefox

**Comment by varjolintu** [comment]
The browser extension should work with both versions. From KeePassXC side you can see the connected browsers from the Database settings. Previously those were visible in the Browser Integration settings. Try to remove all of the connetions (from the extension too) and try again.

**Comment by pstorch** [comment]
Thanks, removing all Browser Integrations on KeePassXC side solved the issue.
