### ISSUE TITLE
KeepassXC-browser reports new version availability (macOS) but latest release not yet available for platform

### ISSUE THREAD

**Issue by newyork10023** [keepassxreboot/keepassxc-browser#442]
KeepassXC-browser reports new version availability (macOS) but latest release not yet available for platform

Note: Cross-posted to KeepassXC issues.  Sorry.

## Expected Behavior
Wait to notify of new releases when the platform's (macOS) latest release exists.

## Current Behavior
Notifies before latest release exists for platform

## Possible Solution
Check platform's release not just general availability on any/one platform

## Steps to Reproduce
Running KeepassXC-browser in Firefox, I receive notification I am not on latest version.

## Context
Spent time checking and downloading an old release, determining availability on other platforms, thought of the 88 lbs of plastic injested by a dead beached whale and whether it might have been saved were it not for this bug, and then writing this report.

## Debug Info
KeePassXC - Version 2.3.4
Revision: 6fe821c

Libraries:

    Qt 5.9.3
    libgcrypt 1.8.2

Operating system: macOS Sierra (10.12)
CPU architecture: x86_64
Kernel: darwin 16.7.0

Enabled extensions:

    Auto-Type
    Browser Integration
    Legacy Browser Integration (KeePassHTTP)
    SSH Agent
    YubiKey

**Comment by varjolintu** [comment]
It will be available soon. See duplicate: https://github.com/keepassxreboot/keepassxc/issues/2807
