### ISSUE TITLE
The addon suggests me to update even if there is no new version

### ISSUE THREAD

**Issue by nicexe** [keepassxreboot/keepassxc-browser#443]
## Expected Behavior

The addon should suggest to upgrade when there is a new KeePassXC version.

## Current Behavior

The addon suggests me to update KeePassXC but when I visit the project page I get offered the same version I have installed

## Possible Solution

Check the KeePassXC version against the platform (Mac/Linux/Windows) before suggesting to upgrade KeePassXC

## Steps to Reproduce (for bugs)

1. Have MacOS
2. Have KPXC v2.3.4
3. Have KPXC-Browser v1.3.2 on Firefox
4. Start Firefox

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.3.2
Operating system: Mac
Browser: Firefox

**Comment by droidmonkey** [comment]
Duplicate.
