### ISSUE TITLE
Icon does not stay where it is put

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [keepassxreboot/keepassxc-browser#444]
## Expected Behavior
When I move the browser addOn's icon, the icon should stay where I have moved it.

## Current Behavior
After restarting Firefox, the icon goes back to its _original_ position.

## Possible Solution
Don't know, but the addOn Https Everywhere has the same problem - see [this bug report, filed against Firefox itself](https://bugzilla.mozilla.org/show_bug.cgi?id=1534282).

## Steps to Reproduce (for bugs)
1. Install keepassxc-browser.
2. Configure it.
3. Move its icon to e.g. immediately to the left of the URL bar.
4. Restart Firefox.

## Debug info

KeePassXC - 2.4
KeePassXC-Browser - 1.3.2
Operating system: Win 8.1.
Browser: Firefox

**Comment by droidmonkey** [comment]
This sounds like a FIREFOX problem.

**Comment by LinuxOnTheDesktop** [comment]
> This sounds like a FIREFOX problem.

It does seem to be, yes. Still, I thought it was worth making you aware of the problem and having a note here on this bugtracker about the problem.

**Comment by droidmonkey** [comment]
I appreciate the information, but it does not make sense to create an issue for our extension when it is entirely the other program's fault.

**Comment by LinuxOnTheDesktop** [comment]
No, I would not; yet, you see, Firefox does _not_ do it for _every_ extension, but rather only, to my present knowledge, for _two_ icons.

**Comment by droidmonkey** [comment]
I actually cannot replicate this behavior on Firefox in Windows. I added a bunch of extensions, plus the two offending ones, and they all stay put after multiple restarts.

**Comment by LinuxOnTheDesktop** [comment]
Right. It's my fault, in this sense: I discover that actually, and for some reason, _any_ changes that I make to my Firefox iconbar are not sticking. Apologies.

**Comment by droidmonkey** [comment]
It could be a permissions issue with your Firefox config or profile. Strange as that may be

**Comment by LinuxOnTheDesktop** [comment]
Thank you. However, a kind Firefox developer helped me to fix the problem. The cause was that, somehow, I'd ended up with a load of stuff that belongs in Firefox's `prefs.js` in `user.js` instead. Er, I think.
