### ISSUE TITLE
Wildcards in the URL field lead to wrong suggestions of logins

### ISSUE THREAD

**Issue by abeham** [keepassxreboot/keepassxc-browser#445]
## Expected Behavior

I go to https://myemaildomain.com and am presented the one and only one login that matches the URL field "https://myemaildomain.com" 

## Current Behavior

I go to myemaildomain.com and get suggestions for all sites to which myuser@myemaildomain.com is a user name. I even don't get the one entry that actually matches the URL pattern. Why is username field even matched!?

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Debug info

KeePassXC - 2.4.0
KeePassXC-Browser - 1.3.2
Operating system: Win
Browser: Vivaldi

**Comment by abeham** [comment]
I should note that the domains suggested have URL patterns of the form `https://*.*.sitea.com` or `https://*.siteb.com` for instance.

**Comment by droidmonkey** [comment]
We don't do username matching. I assume this has everything to do with the wildcards.

**Comment by abeham** [comment]
Potentially there is an issue when wildcards appear in the URL field.

**Comment by varjolintu** [comment]
We don't have a wide wildcard support yet. The only "wildcard" supported is `https://sitea.com` which means `https://*.sitea.com`.

**Comment by CueHD** [comment]
I just noticed this as well. It did not occur in previous versions that I can recall; though it is possible that I did not have wildcards in my URL fields back then.
Perhaps it would be helpful to add a tooltip over the URL field in KeepassXC that cautions against the use of wildcards until they are implemented.

**Comment by varjolintu** [comment]
Well. Perhaps a tooltip would be helpful, but after all, we have never said we even support wildcards in the URL field. Still people are trying to use them.

**Comment by abeham** [comment]
But then how come the weird behavior. If you don't support wildcards, you should have a no match, but that's not the case. Instead when the URL where you login and the e-mail domain coincide, one obtains a list of all logins to all sites for which there is the "*" character in the URL field.

**Comment by varjolintu** [comment]
@abeham The matching didn't work as it should have. We are releasing 2.5.1 soon, and it will fix all of those issues.
