### ISSUE TITLE
Desktop app version checking doesn't take OS into account

### ISSUE THREAD

**Issue by ThinkChaos** [keepassxreboot/keepassxc-browser#449]
## Expected Behavior

I shouldn't be notified of a new version when it hasn't come out for my OS yet.

## Current Behavior

I was seeing the "You use an old version of KeePassXC. Please download the latest version from keepassxc.org." message even though there was no update for macOS yet.

**Comment by droidmonkey** [comment]
This was a one time artifact due to unforeseen circumstances. We never intend to release a different version on a specific OS.
