### ISSUE TITLE
Support for more specific URLs

### ISSUE THREAD

**Issue by berezovskyi-oleksandr** [keepassxreboot/keepassxc-browser#450]
I have several credentials:
- `companyname.com`
- `subdomain.companyname.com`
- `subdomain.companyname.com:8080`
## Expected Behavior
Once I go to `subdomain.companyname.com:8080`, credentials for `subdomain.companyname.com:8080`, `subdomain.companyname.com` and `companyname.com` are returned.

## Current Behavior
Once I go to `subdomain.companyname.com:8080`, credentials for `companyname.com` are returned.

## Steps to Reproduce (for bugs)

1. Create credentials for some URL (e.g. for `site.com`).
2. Create credentials for more specific URL (e.g. for `sub.site.com` or `sub.site.com:8080`).
3. Get list of suggested credentials when on `sub.site.com`.
4. List returns credentials only for `site.com`.

## Debug info

KeePassXC - 2.4.0
KeePassXC-Browser - 1.3.2
Operating system: Mac
Browser: Firefox

**Comment by varjolintu** [comment]
Try KeePassXC Settings -> Browser Integration -> [x] Return only best-matching credentials.
