### ISSUE TITLE
Confirm Access "Window"  is shown even though the "KeepassXC-Browser Settings" is already there

### ISSUE THREAD

**Issue by spacemanspiff2007** [keepassxreboot/keepassxc-browser#451]
I get the Confirm Access "Window" everytime I visit a homepage after updating to KeepassXC2.4.0. and a corresponding database update.
Under Entry -> Properties there is already a Key with "KeePassXC-Browser Settings" and it does show the website.

## Expected Behavior
Popup should not be shown, selection should be remembered.

## Current Behavior
Popup is shown every time, checkbox doesn't change anything

## Steps to Reproduce (for bugs)
1. Visit Webpage
2. Popup appears, click "allow" and "remember"
3. Logout
4. Reload page
5. Popup appears again

## Debug info

KeePassXC - 2.4.0
KeePassXC-Browser - 1.3.2
Operating system: Win
Browser: Firefox

**Comment by droidmonkey** [comment]
Is it a basic http auth dialog?

**Comment by spacemanspiff2007** [comment]
Yes - you are correct.
Other entries seem to work

**Comment by droidmonkey** [comment]
This is by design. You can disable the behavior in the advanced browser integration settings in KeePassXC.

**Comment by spacemanspiff2007** [comment]
But I want KeepassXC to fill out the basic http auth dialog and I have the information in the database.
This is why I have selected ```Automatically fill in HTTP Basic Auth dialogs and submit them.``` in the KeepassXC-Browser Extension.
Do you mean I have to select "Do not ask permission for HTTP Basic Auth", in KeepassXC too?

**Comment by varjolintu** [comment]
The permission is asked every time for HTTP Basic Auth. This change was made because there can be sites which have HTTP Basic Auth and the login form in the same page, and in this way the permissions are distinguished.

If you have a single entry for a site and you want it autofilled every time, selecting _"Do not ask permission for HTTP Basic Auth"_ will do the job.

**Comment by spacemanspiff2007** [comment]
Okay, I'll try it out. The german translation was also very misleading.
