### ISSUE TITLE
Firefox66, KPXC-browser1.3.3, KPXC2.4.0 : don't work together

### ISSUE THREAD

**Issue by Piteur57** [keepassxreboot/keepassxc-browser#452]
Hi.

On Windows 10, I was using KeepassXC up to now in combination with Firefox Quantum and the KeepassXC-browser addon.

Current versions:
• Windows 10 Home 1803
• Firefox 66.0.1
• KeePassXC 2.4.0 (in installed version)
• KeepassXC-browser 1.3.3

I have no more communication between the addon and KeepassXC: "reload" doesn't give anything. However :
• the base is open,
• the option "Enable Integration" is checked in KeepassXC configuration.

Where can the fault come from, which is quite painful because, under Windows 10, it is impossible to constantly keep KeepassXC in the foreground (to copy / paste)?

[ For information, I installed the addon in Vivaldi 2.3.1440.61 and everything works fine! ]

**Comment by varjolintu** [comment]
And Firefox is enabled in the Browser Integration settings?

**Comment by Piteur57** [comment]
Yes, as I said it... I make the assumption of a change in Firefox, when upgrading to version 66 ...

**Comment by varjolintu** [comment]
Check [this guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and see everything is correctly set.

**Comment by Piteur57** [comment]
On target ! The 'org.keepassxc.keepassxc_browser.json' file was not searched in the right folder: it was the file of an old portable version, while I installed an installable version. I made the change in the Windows registry [ HKEY_CURRENT_USER > Software > Mozilla > NativeMessagingHosts ] and everything is back in order!

Why the installable version did not change the registry key data? Mystery!

Thanks.

**Comment by varjolintu** [comment]
Maybe the installed version detected the registry entry and didn't modify it because it thought it's already installed. Possibly disabling and enabling the Firefox support would have done the trick also.

**Comment by Piteur57** [comment]
> 
> 
> Possibly disabling and enabling the Firefox support would have done the trick also.

No, I tried it (with Firefox restart, with OS restart), without success.

By the way, I installed the installable version because the communication between the addon and the portable version was no longer working! — But, whatever, it's restored!
