### ISSUE TITLE
KeePassXC will not open

### ISSUE THREAD

**Issue by CraigOrrell** [keepassxreboot/keepassxc-browser#453]
KeePassXC 2.4.0 will suddenly not open

## Expected Behavior
After I clicked on the app on windows 10 it usually opens a screen that asks for my Master Password. Then i have access to my database.

## Current Behavior
It does not bring up the screen requesting my Master password and therefore i can't open my password database. It does show up in the taskbar at the bottom of the screen on the left. If i click on the icon it just disappears and the icon that is on the right changes from being shaded green to grey. Hovering over the icon on the left it shows a blank applicaiton screen and has 'KeePassPasswords.kdbx [locked] - KeePassXC" above it.

## Possible Solution
I don't know if this is related but i did upgrade the version of KeePassXC last week.  It worked fine for about 5 days and then this happened.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - unknown (I upgraded it from 2.3.4 to 2.4.0 five days ago, it worked for 4 days)
KeePassXC-Browser - 1.3.3 
Operating system: Win32 
Browser: Chrome/Chromium 73.0.3683.86

**Comment by varjolintu** [comment]
Make in issue to https://github.com/keepassxreboot/keepassxc/issues if this is not related to the extension.
