### ISSUE TITLE
"Choose custom login fields" creates one overlay per frame

### ISSUE THREAD

**Issue by whisdol** [keepassxreboot/keepassxc-browser#454]
## Expected Behavior
After clicking "Choose custom login fields for this page", I should be able to select the username field on https://appleid.apple.com

## Current Behavior
I am unable to select the username field on https://appleid.apple.com. Instead, the Info-screen is displayed twice.
![grafik](https://user-images.githubusercontent.com/5374166/55105498-f83fec00-50cc-11e9-80fe-c5aaec0e5646.png)
After pressing <kbd>Esc</kbd>, one overlay (in the frame with the last click?) gets dismissed.

## Possible Solution
Only show the info-screen in the outermost frame.
Allow selection of input fields in all frames.

## Steps to Reproduce (for bugs)
1. Open https://appleid.apple.com
2. Choose the option "Choose custom login fields for this page"
3. Press <kbd>Esc</kbd>

Alternatively:
1. Open https://appleid.apple.com
2. Click into username field
3. Choose the option "Choose custom login fields for this page"
4. Press <kbd>Esc</kbd>
5. Notice that the overlay of the inner frame gets dimissed.

## Debug info
KeePassXC - 2.4.0 
KeePassXC-Browser - 1.3.3 
Operating system: MacIntel 
Browser: Chrome/Chromium 74.0.3729.28

**Comment by varjolintu** [comment]
This is a known bug. It has happened always, and it's because content scripts are used in every frame.

**Comment by varjolintu** [comment]
Anyone wondering why this issue is still open:
- The main page's content script is not allowed to make any modifications to iframes from another location, thus the same content script must be run on each frame.
- Using `postMessage` is not allowed to deliver messages between domains. It could've been used to deliver the input fields in the iframe to the main page.

**Comment by varjolintu** [comment]
This is finally fixed in the upcoming 1.8.0 :)
