### ISSUE TITLE
can't input the password in some websites

### ISSUE THREAD

**Issue by happyZYM** [keepassxreboot/keepassxc-browser#459]
When I visited WordPress.com , KeePassXC-Browser couldn't help me input the password because the username field and the password field were in different pages.
![](https://happyzym.github.io/pic/p/2019-03-31-18-13-50-978.png)
And it seems that I can't solve the problem by choosing custom login fields for this page.

How can I solve the problem?

infomation for debugging:
```
KeePassXC - Version 2.4.0
Revision: c51752d

Libraries:
- Qt 5.12.1
- libgcrypt 1.8.4

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.17134

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
```
```
KeePassXC-Browser Version: 1.3.3
Browser: firefox 66.0.2 x64
```

**Comment by varjolintu** [comment]
Go to extension settings and to the Site Preferences tab. Add the site URL to the list and enable _Username-only detection_ checkbox.

**Comment by happyZYM** [comment]
@varjolintu Thanks!The problem has been solved.
