### ISSUE TITLE
KeePassXC Browser extension for Microsoft Edge browser

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#46]
Are there plans to create a version of KeePassXC Browser for the Microsoft Edge browser?

**Comment by varjolintu** [comment]
It could be possible, but not in the roadmap right now.

**Comment by Stephan-P** [comment]
Thanks for the prompt response.
I'm trying to promote KeePassXC + KeePassXC Browser within my (school) organisation and, though the majority is using Chrome, support for the Edge browser would definitely help making the case stronger.
At the same time I realise that there aren't too many Edge extensions out there, so it'd probably not be a trivial task to take up.

**Comment by vpontin** [comment]
Looking forward this (i'm switching my KeePassHTTP and related plugins to KeePassNatMsg and XC Browser) in hopes one day Edge will be supported too.

**Comment by droidmonkey** [comment]
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging

We'd have to create a special proxy for edge using the UWP toolset.

**Comment by vpontin** [comment]
So a possible solution for this would be similar to the one discussed on https://github.com/pfn/passifox/issues/495 ??

**Comment by droidmonkey** [comment]
That's a huge thread, which comment in particular

**Comment by vpontin** [comment]
> Considering that loopback is disabled by design for pure-JS extensions, it looks like Edge will need a different solution to connect with KeePass, one that provides a UWP messaging component and possibly even a different plugin in KeePass itself to communicate with it.

https://github.com/pfn/passifox/issues/495#issuecomment-353709108

> According to microsoft (https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8984919/) the preferred way for Edge is to include a native messaging UWP companion app: https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/native-messaging .The API is available since the Creators Update

https://github.com/pfn/passifox/issues/495#issuecomment-315526372

**Comment by droidmonkey** [comment]
Closing this since Edge browser is going away to be replaced by a Chromium version that will support KeePassXC-Browser out of the box (hopefully).

**Comment by MathPlayer** [comment]
Follow-up:

For now the extension can be installed on Microsoft Edge (for example from the Chrome store), but the connection to the database of the desktop app fails with the following error:

<img width="456" alt="Screenshot 2019-06-19 at 11 24 30" src="https://user-images.githubusercontent.com/1119787/59753658-e5c8ef00-9284-11e9-8270-8300b72833d9.png">

I have the browser integration enabled in [KeePassXC] preferences for Google Chrome, Chromium and Firefox.
The same extension installed in Firefox can be connected to the database.

Debug info from the extension installed in Microsoft Edge:
KeePassXC - unknown
KeePassXC-Browser - 1.4.6
Operating system: MacIntel
Browser: Chrome/Chromium 76.0.3809.12

Debug info from the extension installed in Firefox:
KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.6
Operating system: MacIntel
Browser: Mozilla Firefox 67.0

Additional info:
OS: macOS Mojave 10.14.5
Browsers:
- Microsoft Edge - Version 76.0.182.6 (Official build) Dev (64-bit)
- Mozilla Firefox - 67.0.3 (64-bit)

I am not sure if this should be a follow-up for the extension or for https://github.com/keepassxreboot/keepassxc/issues/1633.

[keepassxc]: https://github.com/keepassxreboot/keepassxc/

**Comment by varjolintu** [comment]
This is because we haven't added the Edge support yet to KeePassXC (meaning the location for Native Messaging script files). So for now, you have to copy the files manually to the correct location (which for me is unknown at this point, because I haven't looked at the issue at all).

**Comment by varjolintu** [comment]
For macOS the dev version location is `~/Library/Application Support/Microsoft Edge Dev/NativeMessagingHosts/`. You can just copy the Chrome/Chromium `org.keepassxc.keepassxc_browser.json` to that path (it's found under the same Application Support under Chrome or Chromium).

**Comment by droidmonkey** [comment]
We will wait until Edge-Chrome goes stable

**Comment by MathPlayer** [comment]
Indeed, even the beta might have with a different name than the release. Thanks for the instruction on how to address my problem with the dev version.

**Comment by kbudde** [comment]
Workaround on Windows to enable KeepassXC Extension in MS Edge Dev (Chromium)
- Goto Chrome Web store (https://chrome.google.com/webstore/search/keepassxc)
- Enable Installation from store (top blue bar)
- Install Keepassxc extension
- Open: %AppData%\..\Local\keepassxc in one browser (msi installation)
- Copy org.keepassxc.keepassxc_browser_chromium.json
- Create folder: %AppData%\Microsoft\Edge Dev\NativeMessagingHosts
- Copy file into this folder
- Restart edge

**Comment by varjolintu** [comment]
Here's the PR for the Edge support: https://github.com/keepassxreboot/keepassxc/pull/3359. All the paths used are verified after a stable version is released.

**Comment by droidmonkey** [comment]
Edge is releasing "1.0" on January 15th

**Comment by szymonbr** [comment]
> Workaround on Windows to enable KeepassXC Extension in MS Edge Dev (Chromium)
> 
> * Goto Chrome Web store (https://chrome.google.com/webstore/search/keepassxc)
> * Enable Installation from store (top blue bar)
> * Install Keepassxc extension
> * Open: %AppData%..\Local\keepassxc in one browser (msi installation)
> * Copy org.keepassxc.keepassxc_browser_chromium.json
> * Create folder: %AppData%\Microsoft\Edge Dev\NativeMessagingHosts
> * Copy file into this folder
> * Restart edge

As that workaround works well the thread could be resolved to not confuse others.

**Comment by Stephan-P** [comment]
I installed KPXC-B on Edge Dev from the Chrome Web Store and it just works, without copying files.
Let's forget about the old Edge browser. The new one is coming shortly.

**Comment by varjolintu** [comment]
The official URL for the extension is https://microsoftedge.microsoft.com/addons/detail/pdffhmdngciaglkoonimfcmckehcpafo

I'm currently wrapping up the KeePassXC side support for the next release.

**Comment by varjolintu** [comment]
KeePassXC 2.5.3 with Edge support has been released.
