### ISSUE TITLE
"Reopen database" immediately closes db again

### ISSUE THREAD

**Issue by azrdev** [keepassxreboot/keepassxc-browser#461]
## Steps to Reproduce

1. configure browser integration with firefox, connect a keepassx db
2. lock the keepass database
3. in the browser plugin, click "reopen database" (or use auto-fill on a password field, which requests the same)
4. type your db password into the keepass window

## Current Behavior
if the password is correct, the window is minimized as if the db were unlocked, but the tray icon still shows the "locked" variant, and the browser extension gets no account/password information

## Expected Behavior
the db is unlocked and the browser plugin can get credentials

This broke until recently, before it worked.

## Debug info

KeePassXC - 2.4.0-1
KeePassXC-Browser - 1.3.3
Operating system: Archlinux
Browser: Firefox 66.0.1-1

**Comment by droidmonkey** [comment]
Do you have lock database on minimize enabled? Are you using the proxy (ie, KeePassXC runs independent of your browser). Need way more information to diagnose this.

**Comment by azrdev** [comment]
> Do you have lock database on minimize enabled? 

Yes

> Are you using the proxy (ie, KeePassXC runs independent of your browser). 

Yes

> Need way more information to diagnose this.

Sorry for not providing them in the first place, what else do you need?

**Comment by droidmonkey** [comment]
Turn off lock database when minimized.

**Comment by azrdev** [comment]
@droidmonkey sorry for disagreeing here, but even though it works, I don't consider this a valid fix.
When I manually minimize/hide the keepassxc window because I don't need access to it any more for the moment, I want it to be locked. But when I access it through the browser, I want it to a) stay in background and b) let it be unlocked as long as the browser needs that.

I suppose that's actually something in the code of keepassxc, not the browser plugin?

**Comment by droidmonkey** [comment]
It is in KeePassXC itself. The browser extension returns the window to its previous position before unlocking. If it was minimized before, it minimizes again. In the tray? Back to the tray. 

I recommend that you set the auto lock timer to something small like 1 minute. Or make sure the window is not minimized before reopening from the browser.
