### ISSUE TITLE
Feature Request: Don't enable db password field by default

### ISSUE THREAD

**Issue by 7usr7local** [keepassxreboot/keepassxc-browser#462]
When using a database only secured by a key file or a Yubikey, I don't need to enter a password.
However, when opening KeepassXC 2.4, the password field is enabled by default (meaning: the hook left to the field is set) when I simply press "ok" I get an "wrong key" error because an empty password is something different then an unset password.

That's been different up to KeepassXC 2.3.4 where the field became enabled only when I started typing a password, thus saving me one click (to disable the password).

I would appreciate if I could get back the old behaviour.

Thanks for reading,
/usr/local

**Comment by varjolintu** [comment]
This is a known issue and will be fixed in the future versions. Closing this also because the issue repository is wrong. Please use https://github.com/keepassxreboot/keepassxc/issues in the future, thanks.

**Comment by 7usr7local** [comment]
Sorry, my bad. Actually I did believe I was creating it in the other queue. Glad to hear, it's already on your list.
