### ISSUE TITLE
Optional monochrome (b/w) favicon to fit into browser-design 

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#465]
For Firefox, it would be nice to switch to a black/white (monochrome) version for the browser icon, so it fits into the other icons of your browser.

I'll mostly talk about Firefox, here, e.g. look how it looks when you have some adjusted add-ons and current Firefox icons:

![image](https://user-images.githubusercontent.com/11966684/55669932-970eda00-587d-11e9-83c8-19eb33191131.png)

(Nightly screenshot)

---

See https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements for how it should be done.

---

I could take this on, if you want. :smiley:

**Comment by whisdol** [comment]
I like the idea! Maybe this could also switch the autocomplete color back to monochrome (white?), for people who don't like the new no_jquery look.

**Comment by sebast889** [comment]
I'm not a fan of this. Monochrome icons won't really fit into other icons better if you use the default/lighter themes. Majority of users don't use custom CSS or dark theme and unless there is a way to change icons automatically based on themes, the current colored icons will still look much better imo.

**Comment by rugk** [comment]
It works for light and dark themes. And, personally, I would always want a **switch** in the settings, so this here should be optional, for users who don't want colored icons.

> autocomplete color

I don't know what you mean, but I rather think this is off-topic.

**Comment by varjolintu** [comment]
The only problem with this suggestion is that in the current version monochrome icon means there's no connection to KeePassXC (with one exception I still haven't fixed though..), and the coloured one means the connection is currently active.

If this is implemented, we have to find another way to use different statuses in the icon, or just not use them at all, which doesn't seem like a good idea.

**Comment by rugk** [comment]
Ah, status things is something yes. You could use colored badges for that somehow, or don't use it at all. (or only an error icon in the corner if there is an error; and otherwise just the monochrome version)

**Comment by varjolintu** [comment]
I'll make some testing. Maybe it's possible to use a monochrome icon with more contrast when connection is active etc.

**Comment by rugk** [comment]
No, not more contrast, then the color changes again and that should be fixed. As per [Firefox Photon guide](https://design.firefox.com/photon/visuals/color.html#icons-and-other-elements) the color should be `rgba(12, 12, 13, 0.8)` for the light icon version and `rgba(249, 249, 250, 0.8)` for the dark one.

In Firefox you can then use [`theme_icons`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#Syntax) to statically define the light/dark version of the icon.

**Comment by varjolintu** [comment]
Ah, of course. Thanks for clearing that out.

**Comment by rugk** [comment]
BTW, one issue in Firefox that may be useful to be resolved first (if you also think so, please upvote or add useful information/ use cases if there are more):
* let us adjust `theme_icons` dynamically, so these status indicators are possible again: https://bugzilla.mozilla.org/show_bug.cgi?id=1416871

Also, I've had this thread about the whole topic, it includes some more (bugzilla) links to issues that are also there about this topic of browser-integrated icons:
https://discourse.mozilla.org/t/how-to-correctly-design-color-icon-to-be-visible-across-themes/27713?u=rugkx

**Comment by rugk** [comment]
BTW as an alternative/workaround you could use badges instead of status indicators in the icon itself. (something like red `x` and green `+` is totally possible…)

**Comment by neon64** [comment]
I've implemented monochrome icons with badge overlay here.

https://github.com/neon64/keepassxc-browser/commit/0075d631d8f93b2e3dda607eec846bf21a469b5c

Still needs to be made optional though for those who wouldn't like the change.

Looks like this now in Firefox:

![screenshot_2020-11-11_18-43-57_673265515](https://user-images.githubusercontent.com/7961339/98783977-7d1c7c80-244e-11eb-8422-dee62880c3c8.png)

**Comment by phoerious** [comment]
You should use our monochrome icons, not a custom one.

**Comment by varjolintu** [comment]
This issue has been fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1938.
