### ISSUE TITLE
Folder option for autocomplete

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc-browser#466]
## Expected Behavior
Show folder name in auto complete. Sometimes i have multiple logins to same service and sorted by folder. One folder per project and Login name is auto increment and name is the Software like Control Panel XY.
I found no option or even template with variables in settings.

## Current Behavior
Shows username (title)

## Possible Solution
Autocomplete with username (title / folder)

## Debug info
KeePassXC - 2.4.0
KeePassXC-Browser - 1.3.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

**Comment by rugk** [comment]
> I found no option or even template with variables in settings.

A template might indeed be a good idea, as it allows a lot of flexibility while other users (who only use the root folder or so anyway), do not need to adjust it. :smiley:
