### ISSUE TITLE
Failed to save credentials

### ISSUE THREAD

**Issue by vasyugan** [keepassxreboot/keepassxc-browser#467]
## Expected Behavior

After logging in to a site, when the little red lock blinks on the menu bar, Keepassxc browser  should be able to click "new" and save my entry.

## Current Behavior

I never have been able to save credentials with KeePassXC, the "new" and "update" options are unavailable every single time. The only active button is "dismiss", and yes, I have triple-checked that the database is open

## Steps to Reproduce (for bugs)
1. Login to a page
2. see the blinking lock on the menu bar
3. Click on it before it stops blinking
4. Find that the New and Update buttons can't be clicked

## Debug info
KeePassXC - Version 2.4.0
Revision: c51752d
Distribution: Snap

Libraries:
- Qt 5.9.5
- libgcrypt 1.8.1

Operating system: Ubuntu Core 18
CPU architecture: x86_64
Kernel: linux 4.18.0-17-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
Operating system: Linux Ubuntu Cosmic
Browser: Firefox 66.0.2

**Comment by varjolintu** [comment]
Is this a situation where you don't have any existing credentials with the URL and you are trying to save new ones just using the password field with an empty username? Or could you give the page URL so I can try to reproduce it? Thanks.

**Comment by vasyugan** [comment]
Am 10.04.19 um 12:35 schrieb Sami Vänttinen:
>
> Is this a situation where you don't have any existing credentials with
> the URL and you are trying to save new ones just using the password
> field with an empty username?
>
I have just generated a password via the generate buttons that
Kepassxc-browser adds to password fields and now the password is in the
clipboard and I want to save it without having to manually add an entry
in KeePassXC

> Or could you give the page URL so I can try to reproduce it? Thanks.
>
Actually, I don't work for me at /any/ URL, but this time I tried at
https://www.eventbrite.de/

**Comment by varjolintu** [comment]
I'm sorry but I cannot reproduce it. This would need debugging from your side.

**Comment by vasyugan** [comment]
Am 10.04.19 um 13:48 schrieb Sami Vänttinen:
>
> I'm sorry but I cannot reproduce it. This would need debugging from
> your side.
>
If you advise what I need to do, I gladly will, because this has annoyed
me for many months already.

**Comment by varjolintu** [comment]
With Firefox you will have to go to `about:debugging` and launch the debug for KeePassXC-Browser. Then you must find the file `popup/popup_remember.js`. Put a breakpoint to the start of the main `_initialize` function and see what values the `tab.credentials` has when you open the popup dialog after icon blinking.

**Comment by vasyugan** [comment]
I am not sure where to find popup/popup_remember.js. It isn't selectable in the left pane. Or am I in the wrong place?

![Bildschirmfoto von 2019-04-10 14-07-45](https://user-images.githubusercontent.com/3313208/55877347-17914b80-5b9a-11e9-8ebb-72f9714c96c5.png)

**Comment by vasyugan** [comment]
I see the file when I open the subfolder popups in the XPI file, but I don't see it in the debugger. How do I get it?

**Comment by varjolintu** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging#Debugging_popups

Or just open the popup once so the code loads to the debugging screen.

**Comment by vasyugan** [comment]
> 
> 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Debugging#Debugging_popups
> 
> Or just open the popup once so the code loads to the debugging screen.

Will try. Meanwhile I have thefollowing:
```

Error: Type error for parameter options (Property "buttons" is unsupported by Firefox) for notifications.create. browserAction.js:266:13
Error: Promised response from onMessage listener went out of scope
```

**Comment by varjolintu** [comment]
Those are known issues.

**Comment by vasyugan** [comment]
OK, I still haven't managed to bring up the variables pane even though I have set a breakpoint. I guess I'll stop searching for now.

**Comment by rugk** [comment]
> OK, I still haven't managed to bring up the variables pane even though I have set a breakpoint

When you have the code, you can just hover over the variable, if it is currently visible, or simply add that variable to the watched expressions, like this:
![image](https://user-images.githubusercontent.com/11966684/56592894-c5194b80-65eb-11e9-8fd4-f5769740ec18.png)

**Comment by enkore** [comment]
I'm observing this as well. It works exactly one time, then I have to restart KeePassXC, which will make it work one time again etc.

**Comment by enkore** [comment]
After seeing it several times in a row, and restarting KeepassXC a few times, it hasn't happened the last ~dozen or so times I tried. I did notice however that occasionally the extension icon and its status popup report that it couldn't connect to KeepassXC.

I suspect this might be a wider, sporadic issue with the KeepassXC connection and it just becomes more obvious when you get the "failed to save credentials" error message/popup.

**Comment by varjolintu** [comment]
The next version has a fix for the popup connection issue.

**Comment by brondsem** [comment]
I have done the above debugging steps, and it looks like frequently there is no username present in the `tab.credentials` variable, which is what makes the buttons disabled.  Not sure why it gets the username on some sites but not on other sites.

**Comment by varjolintu** [comment]
The whole credential saving is being redesigned and refactored, so any fixes for this will be handled in #351.

**Comment by varjolintu** [comment]
Still having the issue?

**Comment by vasyugan** [comment]
> Still having the issue?

seems to be fixed. Thanks!
