### ISSUE TITLE
2 key icons appear on Lastpass Yubikey 2fa Authentication dialog

### ISSUE THREAD

**Issue by luixxiul** [keepassxreboot/keepassxc-browser#469]
**Description of the issue**: 2 key icons appear on Lastpass Yubikey 2fa Authentication dialog.

## Steps to Reproduce (for bugs)
1. Open https://lastpass.com/?ac=1&nk=1
2. Log in with your credential
3. Set up 2FA with your Yubikey
4. Log out
5. Re-log in with your credential

## Expected Behavior

There should only be the key icon inside of the input box.

## Current Behavior

![Clipboard01](https://user-images.githubusercontent.com/3362943/56022378-7dbad180-5d46-11e9-9581-497a79d4bba7.png)

## Debug info

KeePassXC - 2.4.0 
KeePassXC-Browser - 1.3.3
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
This happens if the page has a visible input element but the style makes it "invisible" while it's visible when inspecting the DOM. You can open the Web Inspector and if you write `document.querySelectorAll('input');` to the console, you can see and inspect all the input elements in the page.

**Comment by luixxiul** [comment]
OK- so is this going to be `wontfix`?

**Comment by varjolintu** [comment]
Yes, for now.
