### ISSUE TITLE
accept "KeePassHttp Settings" attribute 

### ISSUE THREAD

**Issue by yennor** [keepassxreboot/keepassxc-browser#47]
## Expected Behavior
I used the keepasshttp extension before to access password out of my browser. With the new version keepassxc changed to the new "keepass browser" protocol. It would be absolutely great if it would accept the "KeePassHttp Settings" from the previous extension, or just directly converts them (after asking the user) to the new "KeePassXC-Browser Settings" attribute.

## Current Behavior
It does not accept the previous setting. and on every page it asks me if I want to accept access to the password or not, it drives me nuts. I've got dozens, if not hundreds, of page logins stored, with some allow and deny rules. To update them all by hand would take forever.

## General Info
KeePassXC fork - 2.3

**Comment by varjolintu** [comment]
There's already a PR opened that does this. It includes a button to the Browser Integration settings window that does the conversion automatically to the new extension.

See: https://github.com/keepassxreboot/keepassxc/pull/1497

**Comment by droidmonkey** [comment]
This will be fixed on the KeePassXC side.
