### ISSUE TITLE
can't untick the  proxy option

### ISSUE THREAD

**Issue by Cherkah** [keepassxreboot/keepassxc-browser#472]
the snap app do not let me untick the "enable proxy" option cause it is greying out

## Expected Behavior
get access to the proxy option so as to untick it

## Current Behavior
 previous version (2.3.X) worked well (repo app)

## Possible Solution
i do not want use the proxy stuff, i would like to get a direct communication between the snap app and KeePassXC-Browser 

## Debug info

KeePassXC - {2.4.1} snap
KeePassXC-Browser - 1.3.3
Operating system: Linux debian/kde 4.19.28-2 experimental
Browser: Firefox quantum 66.0.1

**Comment by droidmonkey** [comment]
You cannot do that, hence why it is disabled.
