### ISSUE TITLE
Extension hogs BasicAuth, even if it has no credentials to provide (if used in conjuction with chromeIPass)

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#473]
_Disclaimer: I am using chromeIPass **and** KeePassXC-Browser at the same time, for different databases. It's either this affecting, or the fact that KeePassXC DB that's locked._

I have a website, requesting BasicAuth. For that website KeePass-DB has the data, not KeePassXC-DB. KeePassXC-DB is locked, KeePass-DB is unlocked.

Navigating to the webpage does not provide me (or chromeIPass) a prompt to fill the data that are requested, and page loads forever

## Expected Behavior

* KeePassXC either prompts me to unlock the DB. If I choose to unlock, then:
  * If credentials are found, KeePassXC-Browser fills and submits.
* If credentials are not found, or I opted not to unlock the DB, then:
  * Give the next "hook" a chance, or\
  * At least return me the prompt

## Current Behavior

Page is _gray-loading_ forever

## Possible Solution

_See expected_

## Steps to Reproduce (for bugs)

_See first 3 paragraphs_

## Debug info

KeePassXC - 2.3.4 (I have updated 2.4.1, but haven't restarted the browser during that time. Could it be that it's cached on start?)
KeePassXC-Browser - 1.3.3 
Operating system: Linux x86_64 / Ubuntu 16.04.5
Browser: Chrome/Chromium 73.0.3683.103

**Comment by varjolintu** [comment]
May I ask why do you use different extensions for handling multiple databases? You can just enable the option "Search in all opened databases for matching credentials" from the Advanced tab of Browser Integration settings.

**Comment by varjolintu** [comment]
Could you try to disable HTTP Auth for the extension you don't use it. Or do you actually need it to be activated in both? I think those extensions will collide, both trying to handle the situation simultaneously.

**Comment by stdedos** [comment]
That would be KeePassXC then. I know I am doing something wrong from the start, I am just wondering it's worth investigating or not.

I'll try tomorrow to check if disabling it on chromeIPass, would give the expected functionality instead.

**Comment by stdedos** [comment]
I ran the following independent tests: For both extensions BasicAuth is enabled, KeePass has my DB loaded and unlocked, KeePassXC has no DB unlocked:

- I disabled BasicAuth for `chromeIPass`, still doesn't work i.e. `KeePassXC-Browser` does not yield `BasicAuth`.
- Disabling `chromeIPass` altogether, `KeePassXC-Browser` yields `BasicAuth` to user.
- I disabled BasicAuth for `KeePassXC-Browser`,  `chromeIPass` authenticates successfully
- Disabling `KeePassXC-Browser`, even during loading the page, yields to `chromeIPass` (and it authenticates normally etc etc)

-------------

- I try authenticate with KeePassXC (copy + migrate DB), but for some reason it doesn't work.

It could be my fault, but I am not sure how to connect a new DB, or check if the opened DB is connected to `KeePassXC-Browser` (and queried). KeePassXC doesn't even prompt me to unlock the opened ones (which, in the end, would discover that one of them has the legacy bindings). I already have "two DBs" connected, although I have no idea which are they :confused:. _I'll assume the extension is not 100% broken and I am just doing something wrong._

While certainly not a major bug, there seem to be instances of wrongdoing or undeterministic behavior.

**Comment by varjolintu** [comment]
To connect a new DB, switch KeePassXC tab to that DB and open it. Using the extension popup (or Settings' Connected Databases page) should show a Connect button.

If you are now certain what databases are connected and what not, clear the connected keys from KeePassXC (Database settings -> Browser integration) and the extension. Then reconnect them using the same ID names.

**Comment by stdedos** [comment]
> To connect a new DB, switch KeePassXC tab to that DB and open it. Using the extension popup (or Settings' Connected Databases page) should show a Connect button.
> 
> If you are now certain what databases are connected and what not, clear the connected keys from KeePassXC (Database settings -> Browser integration) and the extension. Then reconnect them using the same ID names.

It seems that, that DB was already connected. However, there was no indication of searching it, no prompt to unlock it - and in the end, it failed to detect the binding (which chromeIPass just breezes through). But, that already starts to feel like a different issue, I guess. We can move this discussion to e.g. GitChat or another issue or IRC or something. Feel free to prompt the correct place for this.

If you want to close this issue as wont-fix, please add at least a FAQ entry or a "warning" somewhere for whoever will do the same as me.

**Comment by varjolintu** [comment]
I haven't been able to reproduce this issue at all. Is it still haunting you?

**Comment by stdedos** [comment]
I can check on Monday again. Since I haven't been using the KeePassXC-db a lot, I seem to have forgotten its password 😓

**Comment by varjolintu** [comment]
Please suggest reopening the issue if the problem still persists.
