### ISSUE TITLE
Retrieving a generated password

### ISSUE THREAD

**Issue by 07416** [keepassxreboot/keepassxc-browser#475]
I generated a password for a website and keepassxc-browser either didn't prompt me to save the credentials or I didn't notice the browser icon. Because this website doesn't require an email address there's no way of reseting the password.

Are generated passwords saved or cached anywhere? I haven't closed my browser, but clipboard has been cleared.

**Comment by varjolintu** [comment]
In this cases, if you want to make sure the credentials are updated, use the context menu (right mouse click the input field after filled) and choose _Save credentials_.

**Comment by 07416** [comment]
> 
> 
> In this cases, if you want to make sure the credentials are updated, use the context menu (right mouse click the input field after filled) and choose _Save credentials_.

I see, I'll certainly make sure that the password is saved and backed up in the future.

But as I asked, are generated passwords stored anywhere if the user has not saved the credentials?

**Comment by varjolintu** [comment]
The only place the password is stored is the password generator itself. If it's closed and reopened, it should show the last password generated.

**Comment by dreua** [comment]
> In this cases, if you want to make sure the credentials are updated, use the context menu (right mouse click the input field after filled) and choose _Save credentials_.

That is good advice. I think the UX around this could be improved. Maybe prompt the user if they want to save the "applied" password? Some sites (peertube among them) unfortunately don't trigger the "save credentials" bar during registration.
