### ISSUE TITLE
Browser-Extention only in english

### ISSUE THREAD

**Issue by MegaV0lt** [keepassxreboot/keepassxc-browser#476]
## Expected Behavior

Extension should ust the systemlangauge (German in my case)

## Current Behavior

Extention and popup menu is in english

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.3.3
Operating system: Linux Mint 19.1
Browser: Firefox 66.0.2 - 64bit

**Comment by varjolintu** [comment]
This is fixed in the next version after #457 is merged.
