### ISSUE TITLE
Filter username while typing in username field

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#478]
It is currently possible to filter usernames using the icon popup but is there a way to do this while typing in the username field? It would be a easier way than always going to the popup first.

**Comment by varjolintu** [comment]
That's currently missing. I'll fix that soon.

**Comment by varjolintu** [comment]
Just giving an update: I've been working this for a while and it already works quite nicely. Still need to refactor a lot of code for it, so this will be delayed a little bit.

**Comment by andreasmihm** [comment]
Any updates on this one? This missing feature is a blocker for me

**Comment by varjolintu** [comment]
@andreasmihm Sorry but no. I ran to issues and the Autocomplete Menu has been refactored so I'll have to start from a scratch.

**Comment by amrecords** [comment]
cool, when can I expect this to be released?

**Comment by varjolintu** [comment]
I'm expecting to release 1.8.0 in mid-April or early May.
