### ISSUE TITLE
KeePassXC-Browser 1.4.0 auto-submits login forms

### ISSUE THREAD

**Issue by olifre** [keepassxreboot/keepassxc-browser#479]
Since upgrading to 1.4.0 of the plugin, it autosends forms after filling in the user data,
instead of letting me submit the login form myself. This is really problematic in case other fields / checkmarks need to be set. 
In the last version, this was working fine. 

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.0
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
I am not experiencing this on any website and I am fairly certain we did not program this behavior in. In fact we discussed specifically NOT supporting this behavior.

**Comment by olifre** [comment]
I'm experiencing it on all websites after the upgrade. 
Any extra information I can provide? I have autofilling on in case there's only a single user name for a page.

**Comment by olifre** [comment]
Interesting! 
I can confirm this "autosubmit" only happens if autoFillSingleEntry is on. 
If I disable autoFillSingleEntry, I can select the entry to fill, and afterwards no autosubmission takes place. 

So to be more concrete: With 1.4.0 and autoFillSingleEntry, the login form is not only autofilled, but also autosubmitted.

**Comment by droidmonkey** [comment]
OK good information, and I can confirm that this does happen when autoFillSingleEntry is enabled. Good report!

**Comment by varjolintu** [comment]
My bad. It's fixed with the PR that adds the option for it.
