### ISSUE TITLE
Vivaldi on Windows using NativeMessagingHosts of Google Chrome

### ISSUE THREAD

**Issue by LittleHuba** [keepassxreboot/keepassxc-browser#48]
Vivaldi is using the messaging hosts declared in registry directory of Google Chrome. Therefore selecting Vivaldi in the settings of KeePassXC will fail to enable the plugin.

## Expected Behavior

Activating browser integration for Vivaldi in the settings of KeePassXC sets the NativeMessagingHost for Vivaldi and the extension can connect to the browser.

## Current Behavior

The NativeMessagingHost ist set in a directory of the registry that is never queried, therefore no NativeMessagingHost is registered. The extension does say so when being debugged.

## Possible Solution

Just do the same for Vivaldi on Windows as you are doing when activating browser support for Google Chrome, e.g. create the NativeMessagingHost not in "\HKCU\Software\Vivaldi\NativeMessagingHosts\org.keepassxc.keepassxc_browser" but in "\HKCU\Software\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser"

## Steps to Reproduce (for bugs)

1. Use Windows
2. Enable Browser integration for Vivaldi
3. Install extension in vivaldi
4. Try to connect to database (fails with silent error ->debugging says no native host found)

## General Info
KeePassXC fork - 2.3.0
keepassxc-browser - 1.0.1

Operating system: Win10
Browser: Vivaldi
Proxy used: YES (but obviously the same with no proxy)

**Comment by varjolintu** [comment]
Thank you for the info. I'll do the fix.

**Comment by Stephan-P** [comment]
That's odd. KeePassXC Browser is working perfectly in my Vivaldi 
Windows 10 Home 64-bit
Vivaldi 1.15.1111.3 - win64
KeePassXC - Version 2.3.0 - Rev: 4c0ed74
KeePassXC Browser - 1.01

**Comment by LittleHuba** [comment]
@Stephan-P Could it be that you have additionally Google Chrome installed and therefore activated the Chrome integration in KeePassXC?
I'm using the same Vivaldi build, therefore it should query the same regiostry directories.

**Comment by Stephan-P** [comment]
Yes, I have Chrome installed alongside Vivaldi, but the KeePassXC Browser extension is ONLY installed in Vivaldi. I couldn't tell if this would activate things the way you describe.

Maybe KeePassHttp has to do with it. I did have the KeePassHttp extension installed in Vivaldi, but with the new version 2.3 of KeePassXC I first disabled it and two days later removed it altogether.

**Comment by LittleHuba** [comment]
Would you mind checking your Registry, where your NativeMessagingHost entry resides? Both directories ar listed in the original issue report.

And are you on stable, beta or snapshot of Vivaldi?

**Comment by Stephan-P** [comment]
I'm on snapshot versions of Vivaldi
I've got both registry keys:
"\HKCU\Software\Vivaldi\NativeMessagingHosts\org.keepassxc.keepassxc_browser"
"\HKCU\Software\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser"

![snipaste_2018-03-06_18-02-44](https://user-images.githubusercontent.com/10008599/37046572-f816a5f0-2168-11e8-93a0-7f2f026e7f2b.png)
![snipaste_2018-03-06_18-03-21](https://user-images.githubusercontent.com/10008599/37046574-fa3be1ba-2168-11e8-86e8-40b1fc1998a4.png)

**Comment by LittleHuba** [comment]
Intereseting, but this explains why you can use the plugin even if only Vivaldi is enabled in KeePassXC.
If you want to check, you could remove the key (Chrome) from the registry and try the plugin in Vivaldi again. It should be broken after deleting the key.

**Comment by Stephan-P** [comment]
- Closed Vivaldi
- Removed "\HKCU\Software\Google\Chrome\NativeMessagingHosts\org.keepassxc.keepassxc_browser" from registry
- Started Vivaldi again and clicked KeePassXC icon
- Error: Time out or not connected to KeePassXC
![snipaste_2018-03-06_20-19-12](https://user-images.githubusercontent.com/10008599/37053392-4fa46984-217c-11e8-93ad-8a6ec30f8512.png)
- Removed KeePassXC Browser extension from Vivaldi
- Closed and restarted Vivaldi
- Re-installed KeePassXC Browser extension from the Store
- Again the error: Time out or not connected to KeePassXC
- Closed Vivaldi
- Re-installed registry key (I'd exported beforehand ;-)
- Started Vivaldi again and KeepassXC Browser is well connected to KeePassXC

I don't know for sure how that registry key ...\Chrome\Native... was came up. 
I'm pretty pretty sure I have NOT installed KeePassXC Browser in Chrome. (But maybe I'm getting more forgetfull as I'm getting older...)

**Comment by Stephan-P** [comment]
@LittleHuba Question in return:
Do you have Chrome installed alongside Vivaldi? This could be a distinctive factor.
Did you enable browser integration with Chrome in KeePassXC?

Hunch:
When I installed KeePassXC 2.3, I immediately enabled browser integration for Vivaldi AND Google Chrome.
Next I installed the KeePassXC Browser extension in Vivaldi.
Could it be that both registry entries were installed because of this combination and sequence of events?

**Comment by LittleHuba** [comment]
I do not have Chrome installed, therefore I did not activate Chrome in KeePassXC. When you activated both integrations for Vivaldi and Chrome in KeePassXC, it is no wonder, that the NativeMessagingHost (NMH) for Chrome is installed. Vivaldi will just use this NMH along with Chrome and the one in the registry folder of Vivaldi is ignored (e.g. never seen)
The installation of the browser should have no influence, since KeePassXC is creating the registry entries uncorrelated to the installed/non-installed browsers, when you activate the setting in KeePassXC.

**Comment by fenume** [comment]
Have same problem: extension read HKCU\Software\Google\Chrome\NativeMessagingHosts, not HKCU\Software\Vivaldi\NativeMessagingHosts

![procmon64_2018-08-02_10-09-00](https://user-images.githubusercontent.com/2872377/43567989-220d8b1a-963c-11e8-854a-d4815644618a.png)

**Comment by varjolintu** [comment]
I'm aware of this issue and I'd like to fix this for 2.3.4 but I'm still uncertain how to make the fix because it only affects Windows.

**Comment by varjolintu** [comment]
Suggestion:
Disable the whole Vivaldi selection under Windows and show Chrome as Chrome/Vivaldi.
