### ISSUE TITLE
Cannot click on password dropdown in Threema Web 

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#482]
[TIP]:  # ( Provide a general summary of the issue in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

Click should work.

## Current Behavior
[NOTE]: # ( Tell us what actually happens )

![fail](https://user-images.githubusercontent.com/11966684/56495485-34147880-64f6-11e9-8f76-a0d7673ff5f4.gif)

## Possible Solution
[NOTE]: # ( Not required, but suggest a fix/reason for the bug )

FYI: It worked before the refactoring to use jQuery (where the design was still white of this popup).

And it works if I click/choose the same in the popup of KeePassXC.

## Steps to Reproduce (for bugs)

1. Use https://github.com/threema-ch/threema-web/ or public web.threema.ch to setup a connection with a password (maybe the initial password field also works, did not test) 
2. Save a password in KeePassXC.
3. Try the things seen above: fill password with click.

## Debug info

KeePassXC - 1.4.0
KeePassXC-Browser - 2.4.0
Operating system: Linux
Browser: Firefox

no new console errors seem to be triggerred _on the page_.

**Comment by varjolintu** [comment]
I used the front page of web.threema.ch and could not reproduce this. Can you debug the content scripts and see what happens when trying to fill?

**Comment by rugk** [comment]
Could reproduce it on web.threema.ch with the home page actually.

First of all, (possibly a new issue), when I have the dev tools open, it does position the dropdown a little wrong:
![grafik](https://user-images.githubusercontent.com/11966684/56560911-00912700-65a6-11e9-8e3c-9e98d264ca7d.png)

Some debugging:
* `fillInStringFields` is triggered, but all params are basically empty/undefined:
  ![grafik](https://user-images.githubusercontent.com/11966684/56561222-f6235d00-65a6-11e9-9b43-5ce4d0965c29.png)
  ![grafik](https://user-images.githubusercontent.com/11966684/56561308-3256bd80-65a7-11e9-85b9-f1d32533d010.png)
* Checking things done before, I find that this code is triggered is strange (after all, it _is_ only a password!):
  ![grafik](https://user-images.githubusercontent.com/11966684/56561647-eb1cfc80-65a7-11e9-9a18-8402bec42cce.png)
* also, what is interesting or maybe all correct is that `setValueWithChange` the event dispatcher triggers some angular JS stuff of the web page. (well, I think this is expected)
* `pField === null`:
  ![grafik](https://user-images.githubusercontent.com/11966684/56561868-5cf54600-65a8-11e9-83e7-00603c3ecaee.png)

Thus, quickly checking when I do enter some username in KeePassXC, it works.

Actually, it first (wrongly) fills in the username in the field:
![grafik](https://user-images.githubusercontent.com/11966684/56562445-a2fed980-65a9-11e9-8a8e-91be1e829b44.png)

…and only afterwards, the correct one:
![grafik](https://user-images.githubusercontent.com/11966684/56562513-c9bd1000-65a9-11e9-8b46-34cf93acca84.png)

And here is what results why one input field is considered to be a password and a username:
![grafik](https://user-images.githubusercontent.com/11966684/56562574-f8d38180-65a9-11e9-9ea6-e70400c3f5ac.png)

----

So I'll checked where this `combination` comes from:
![grafik](https://user-images.githubusercontent.com/11966684/56562711-4d76fc80-65aa-11e9-9404-7861935be49b.png)

Somehow, ehm, something like this…
![grafik](https://user-images.githubusercontent.com/11966684/56562963-f6255c00-65aa-11e9-9921-de1e107883b0.png)

**Comment by varjolintu** [comment]
Nice find! This should work better:

```diff
function fillPassword(value, index) {
        const fieldId = input.getAttribute('data-kpxc-id');
        kpxcFields.prepareId(fieldId);
+        const givenType = input.type === 'password' ? 'password' : 'username';
+        const combination = kpxcFields.getCombination(givenType, fieldId);
-        const combination = kpxcFields.getCombination('username', fieldId);
        combination.loginId = index;

        kpxc.fillInCredentials(combination, false, false);
        input.setAttribute('fetched', true);
    }
```

It only tries to fill the password if autocomplete is used from a password field.

**Comment by varjolintu** [comment]
See if it works now. New version is just released.

**Comment by rugk** [comment]
Works. Thx for the fast fix!
