### ISSUE TITLE
KPXC-Browser auto-login fails for some sites

### ISSUE THREAD

**Issue by jo-so** [keepassxreboot/keepassxc-browser#483]
At first, a very big **thank you for implementing auto-login.** This eases handling of logins very much and gives a better user experience.

## Expected Behaviour

I don't know what <https://nebenan.de/login> does with the submit, but the auto-login doesn't work. I end in an endless loop.

Also the login field detection on <https://launchpad.37signals.com/signin> doesn't work. The username and password don't get filled in when opening the page.

## Possible Solution

Maybe, you can add something to detect such loops. Could you mark a tab as *auto-login used* and don't do auto-login for the same site a second time. This would also prevent an auto-login after logout. Some sites like [LPI](https://cs.lpi.org/caf/Xamman/auth/login) redirect to the login form after logout.

## Debug info
* KeePassXC-Browser-Version: 1.4.0
* KeePassXC-Version: 2.5.0 
* Operating system: Linux
* Browser: Firefox

**Comment by varjolintu** [comment]
Actually the auto-login (auto-submit) was left there be accident. The No jQuery PR was such a big change. There's a PR that fixes this situation and disables it with auto-filling for single logins because of the endless loop.

**Comment by jo-so** [comment]
Why not keep the auto-submit, but leave it disabled by default? It works in most cases.

**Comment by varjolintu** [comment]
It depends on the site, and we want to prevent those kind of endless loop situations, or a second auto-login after a logout.

**Comment by varjolintu** [comment]
Closing this as the behaviour for this has changed. Reopen and edit or make a new issue if there's still some problems.
