### ISSUE TITLE
Firefox Account page

### ISSUE THREAD

**Issue by Shorono** [keepassxreboot/keepassxc-browser#484]
I'm having a weird issue on Firefox's account page, but only there, everywhere else 
it works as expected.

on the https://accounts.firefox.com/signin page it doesent recognize the login fields. Which isn't that wierd it happens. But when i click use custom login fields, i expect the loging field wizard to pop up, but it doesnt. In fact not any of the KeePassXC functions work on this page.

I'm using Firefox Quantum 66.0.3 (64-bit)
I'm using KeePassXC-Browser 1.4.0
I'm using KeePassXC 2.4.1 rev. 7bafe65 (64-bit)
I'm using Windows 10.0.17763

**Comment by droidmonkey** [comment]
Mozilla restricts **all** plugins from accessing their pages.
