### ISSUE TITLE
KeePassXC-Browser not working with Firefox on Mac

### ISSUE THREAD

**Issue by adit-s** [keepassxreboot/keepassxc-browser#485]
Hello. I started using KeePassXC earlier this week and haven't been able to get the KeePassXC-Broswer add-on to work with Firefox. The versions of each are
Mac - 10.13.6 (17G6030)
Firefox - 66.0.3 (64-bit)
KeePassXC - 2.4.1
KeePassXC browser add-on - latest version.

## Expected Behavior
To save new entries to the opened KeePassXC db.

## Current Behavior
The notification indicates with a red lock there is an entry to save ("Username or password changed! Save it?"), but the new and update boxes are greyed out (per attached).

## Possible Solution
Being new to the app, I've spent a few hours trying to figure it out in case I'm missing something basic, but haven't been able to figure out why it's not working. Sorry, but I don't have any possible explanations or solutions.

## Steps to Reproduce
Go to any url and enter the userid and password. When the KeePassXC browser lock turns red, click.

## Context
I can't use it.

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.2
Debugging mode is disabled.

Operating system: macOS High Sierra (10.13)
CPU architecture: x86_64
Kernel: darwin 17.7.0

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey
- TouchID

Cryptographic libraries:
 libgcrypt 1.8.4

Enabled extensions:
AdBlock+, Disconnect

Thanks in advance,
Adit

<img width="454" alt="Screen Shot 2019-04-21 at 1 52 21 PM" src="https://user-images.githubusercontent.com/8761424/56473700-cf491780-643c-11e9-8b12-f5dff160422d.png">

**Comment by adit-s** [comment]
Hello. Is there any other information I can provide which can help you isolate the problem; like a debug output? 
I tried a bunch of things including disabling all of the other Firefox addons but I still can't get it to work.

Thanks,
Adit

**Comment by varjolintu** [comment]
1) Go to `about:debugging` and click Debug under the extension
2) Trigger the credential popup once and it should appear in the new debugger window
3) Put a breakpoint right after the `_initialize()` function
4) Check if the `tab` variable has any credentials

**Comment by BartlomiejSkwira** [comment]
@adit-s on which websites do you experience this?

I have the same issue. One of the sites on which this happens https://www.lot.com/pl/en/register

**Comment by varjolintu** [comment]
With the upcoming major changes to the credential saving, #351 seems to trigger the credential banner normally for that site.

**Comment by varjolintu** [comment]
Are you still having this issue with the latest extension version?
