### ISSUE TITLE
Partly breaks Rust documentation in Firefox

### ISSUE THREAD

**Issue by necabo** [keepassxreboot/keepassxc-browser#486]
A few days ago I noticed that most of the expand/collapse buttons in the Rust documentation no longer work. Weirdly enough very few buttons work just fine. Disabling the KeePassXC-Browser Add-on solves the issue. 

I also tested the same KeePassXC-Browser version (2.4.1) in Google Chrome and the Rust documentation works just fine there. I didn't (yet) notice any issues on other websites. 

## Expected Behavior
Clicking the expand/collapse buttons in the Rust documentation (`[ + ]` and `[ - ]`) should expand/collapse the corresponding documentation.

## Current Behavior
Clicking most of the buttons doesn't seem to do anything.

## Steps to Reproduce (for bugs)
1. Navigate to e.g. https://doc.rust-lang.org/std/fs/struct.File.html in the Rust documentation
2. Click on some of the expand/collapse buttons (`[ + ]` and `[ - ]`)

## Debug info
There are no JavaScript console messages and errors when executing the reproduction steps.
KeePassXC - 2.4.1
KeePassXC-Browser - 2.4.1
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Found the bug. Fixed in the next version. Thanks for reporting!
