### ISSUE TITLE
Unable to populate username/password on 1.4.0

### ISSUE THREAD

**Issue by nevets1219** [keepassxreboot/keepassxc-browser#490]
## Expected Behavior
Expect the addon to work as expected in 1.3.3 - allowing populating username and password.

## Current Behavior
After the recent update to 1.4.0 from 1.3.3, the browser is unable to show options for populating username and passwords. The green key icon for generating password also no longer shows up.

I've tried re-detecting the username and password fields, I've restarted the browser, and I've disconnected and re-connected the database. Nothing seem to work. I didn't see any particular errors logged into the console either.

I couldn't find any more information to add, please let me know what logs I can provide to help troubleshoot.

## Possible Solution
None that I know of, I downgraded to 1.3.3 and that's working for me right now.

## Steps to Reproduce (for bugs)
Use 1.4.0 and try to login (I tried https://www.capitalone.com/)

## Debug info
KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.0
Operating system: Windows 10
Browser: Cyberfox 52.9.1 (Firefox) - I have NoScript if that matters.

**Comment by nevets1219** [comment]
The other integration do seem to work (e.g. re-open database and connect)

**Comment by nevets1219** [comment]
Sorry, I looked at wrong console log:
```
IntersectionObserver is not defined  pwgen.js:27
	<anonymous> moz-extension://73d943c8-a460-4549-9be0-5eff1ee2fbe5/content/pwgen.js:27:1
	tryInject resource://gre/modules/ExtensionContent.jsm:263:20
	execute resource://gre/modules/ExtensionContent.jsm:411:5
	triggerScripts resource://gre/modules/ExtensionContent.jsm:427:7
	trigger resource://gre/modules/ExtensionContent.jsm:769:9
	DocumentManager.handleEvent resource://gre/modules/ExtensionContent.jsm:618:7

TypeError: kpxcPassword.init is not a function[Learn More]  keepassxc-browser.js:874:9
```

**Comment by droidmonkey** [comment]
I cannot replicate this on Firefox 66.0.3 on the capitalone website.

**Comment by droidmonkey** [comment]
Recommend you uninstall cyberfox and install a supported web browser. Cyberfox hasn't seen an update since June 2018 and it looks deader than dead (not to mention insecure).

**Comment by varjolintu** [comment]
IntersectionObserver needs at least Firefox 53. We need to bump up the minimum requirement from 52.

**Comment by nevets1219** [comment]
Please support Firefox up to 56 (I believe that's the latest non-Quantum version).

**Comment by varjolintu** [comment]
#491 fixes this anyway.
