### ISSUE TITLE
Problem with https://www.inoreader.com

### ISSUE THREAD

**Issue by skilleter** [keepassxreboot/keepassxc-browser#492]
## Expected Behavior

When you click on a headline in an RSS feed in InoReader the article content or summary should appear and the article should be marked as having been read

## Current Behavior

The article content or summary does not appear, but the article is still marked as read.
In some cases (not easy to consistently reproduce) the headlines are not displayed correctly and overlap vertically.

Disabling or removing the KeePassXC-Browser plugin restores correct behaviour of InoReader.

I have tested this on 4 different installations of Firefox - 1 on Windows and 3 on Ubuntu 18.04

For the moment, I've switched to using KeePass and the Kee plugin and InoReader is working correctly.

## Steps to Reproduce (for bugs)

1. Log in to https://www.inoreader.com
2. Subscribe to at least one feed (e.g. BBC News - 
s: | http://news.bbc.co.uk/rss/newsonline_uk_edition/sci/tech/rss.xml
-- | --

3. View the feed in list view mode
4. Click on an article title to view content or summary 
5. The article is marked as read, but the content or summary is not shown.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
This will be fixed in the next release. Related PR: #487.
