### ISSUE TITLE
CodeStriker broken - Permission denied to access property "toString"

### ISSUE THREAD

**Issue by guanprco** [keepassxreboot/keepassxc-browser#494]
## Expected Behavior
In a CodeStriker code review, when clicking on a line number, an overlay pop-up appears to add a code comment. 

## Current Behavior
No pop-up appears. 

## Possible Solution
The symptoms looks similar to the one described in #487, however the issue affects keepassxc-browser 1.4.1 that is supposed to include this pull. 
So it looks like a different but similar issue, presumably with a similar solution (using addEventListener in keepassxc-browser)

## Steps to Reproduce (for bugs)
1. Download [codestriker-code-review-example.zip](https://github.com/keepassxreboot/keepassxc-browser/files/3107288/codestriker-code-review-example.zip) which contains a exported dummy code review. Or download, setup CodeStriker, and create a dummy review. 
2. Click on a line number (eg 1)

## Debug info

The following error appear in the console: 
> Error: Permission denied to access property "toString"[Learn More] overlib.js:99:95
>     olMouseCapture http://internal-host/codestrikerhtml/overlib.js:99
>     overlib http://internal-host/codestrikerhtml/overlib.js:30
>     add_comment_tooltip http://internal-host/codestrikerhtml/codestriker.js:613
>     eo http://internal-host/codestrikerhtml/codestriker.js:57
>     <anonymous> javascript:eo('2','85','1'):1

KeePassXC - 2.4.0
KeePassXC-Browser - 1.4.0 and 1.4.1
Operating system: Win10
Browser: Firefox

**Comment by varjolintu** [comment]
I found the bug for this also. It's only affected with Firefox that overwrites any direct calls to `document` events.
