### ISSUE TITLE
Permission denied to access property

### ISSUE THREAD

**Issue by drone540** [keepassxreboot/keepassxc-browser#496]
The login button no longer works at the following website:
https://ww14.autotask.net/Mvc/Framework/Authentication.mvc/Authenticate

## Expected Behavior
Clicking login should actually attempt to login to the website

## Current Behavior
When clicking the login button. Nothing appears to happen at all. Only started today after I've noticed the browser extension was updated to 1.4.0. The developer console shows this error:

```
Error: Permission denied to access property "apply"[Learn More] JQuery:6:3062
    jQuery 5
    
    trigger
    
    trigger
    
    each
    
    each
    
    trigger
    submitFormAndInvokePasswordManager https://ww14.autotask.net/Mvc/Areas/Framework/Content/Authentication/Authentication.js?v=20372:1
    onclick https://ww14.autotask.net/Mvc/Framework/Authentication.mvc/Authenticate:1

```

## Possible Solution
Not sure on possible solution at this time as I have not checked what has changed.

## Steps to Reproduce (for bugs)

1. https://ww14.autotask.net/Mvc/Framework/Authentication.mvc/Authenticate
2. Fill in username and random password
3. Try to login

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.0
Operating system: Linux (Ubuntu Mate)
Browser: Firefox

**Comment by varjolintu** [comment]
Fixed in 1.4.2 which is just released. Update the addons from `about:addons` if it's not downloaded automatically.
