### ISSUE TITLE
Dropdown autocompletion with tab breaks own auto-type feature

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#497]
## Steps to Reproduce (for bugs)

1. Following use case: You have **one entry** for a website saved and keepassxc-browser shows you a dropdown.
  Now, for security reasons or so, you have a different database (or even the same one) with a different entry that is (_deliberately_) not suggested there.
2. So you now want to use the auto-type feature of KeePassXC to type that one in – _instead_ of the one that is suggested to you.
3. You focus the username input.
4. You go to KeePassXC and do <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>.

## Expected Behavior

Auto-type works and enters different entry.

## Current Behavior

(Using the default auto-type sequence, obviously.)

What auto-type actually does:
* type in username
* <kbd>tab</kbd> (to jump to password field)
* keepassxc-browser actually recognizes <kbd>tab</kbd> as selecting the suggested entry -> enters username and password; in my test also selected whole password entry, like this on Twitter:
  ![image](https://user-images.githubusercontent.com/11966684/56595008-23dfc480-65ee-11e9-928e-cd7cf4eff9f6.png)
* so now auto-type goes on entering the password

**The result:** It uses the username from the dropdown, and password from auto-type. Login thus (~likely~ hopefully :wink:, if you don't re-use the passwords) fails.

## Possible Solution

Remove selection by tab?
Or somehow conditionally disable it, so it at least does not trigger for own auto-type?

## Debug info

Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
You are my favourite bug hunter! I'm quite sure this happens because we made a change that the first entry is always activated by default. Previously none was activated and tab just closed the autocomplete and you could enter a password manually.
