### ISSUE TITLE
CSS errors when error is shown in in-website popup

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#499]
## Expected Behavior

Well… no `<br>`? No CSS overflow…

## Current Behavior

![grafik](https://user-images.githubusercontent.com/11966684/56615659-d417f200-661b-11e9-88a4-0ebf144b7cad.png)

## Possible Solution

Strip HTML?
Why is there even HTML included (in the error?) at the first place…
…

## Steps to Reproduce (for bugs)

I am not sure why this is triggered, and this is likely an issue on it's own (KeePassXC is actually running, only the add-on claims it is not.)
Maybe I can reproduce it later.

You likely now a way how to fake an error such as this one though. :smile: 

I.e. make sure it's disconnected.

But right-click -> "Show password generator icons" -> (Right-click -> "Show password generator" OR click new icon in password field.)

## Debug info
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
This is an error in the translation. The original English .json file doesn't have this HTML element in the text. This must be reported in Transifex.

**Comment by rugk** [comment]
Okay, but even if so, should not the popup not increase in size then (if it has more text) and the text should not just overflow it?

Also could find it on Transifex, but there also the English source string contains the `<br>` (the `1` there):
![grafik](https://user-images.githubusercontent.com/11966684/56637763-b58e1700-666c-11e9-9ab3-b72d9578ef5b.png)

**Comment by varjolintu** [comment]
Then the JSON there is not up to date. Going to update it soon.

**Comment by rugk** [comment]
Well… then you cannot blame the translators. :rofl: 

(also I'd still argue there is a CSS error)

**Comment by varjolintu** [comment]
I though I updated the translation resource but I was wrong 😑.

I think the CSS error is related to this: https://github.com/keepassxreboot/keepassxc-browser/issues/400

**Comment by rugk** [comment]
Okay thx.

> I think the CSS error is related to this: #400

Sorry, but I don't think so. This rather seems to be about the number of characters included in the password generator field. (in my case, this as not even shown)

**Comment by varjolintu** [comment]
Well, not directly, but the password generator's width should be auto-adjusted by the message or the password lenght.
