### ISSUE TITLE
Extension blocks and waits forever in HTTP access

### ISSUE THREAD

**Issue by the-nic** [keepassxreboot/keepassxc-browser#5]
When a website requires HTTP access control (as configured typically in in `.htaccess` files), chrome will wait forever for KeePassXC-Extension, probably for a password.
## Expected Behavior

It should at least fail at some point when the Database does not have

## Current Behavior

Its stuck, as described

## Steps to Reproduce (for bugs)

1. Have a website with HTTP access control (the site I tested was over HTTPS with a client certificate, dont know if its relevant)
2. Password input field is never shown and status bar shows "waiting for KeePassXC-Extension.."

## General Info
KeePassXC - 83f1a53d32916f31a70462c54beea07b863f7936
keepassxc-browser - 0.5.1 (23-01-2018

Operating system: Ubuntu 16.04
Browser: Chrome 64
Proxy used: NO

**Comment by varjolintu** [comment]
Related issue [here](https://github.com/varjolintu/keepassxc-browser/issues/52).

**Comment by varjolintu** [comment]
Same question here:
Does anything happen if you click the extension icon?

**Comment by the-nic** [comment]
No, that doesnt change anything. However, when retrying it later chrome was not blocked anymore, probaply running into an internal timeout (on any site with simple auth). 
I had to retry on another system, where nothing changed when clicking on the extension icon

**Comment by varjolintu** [comment]
I assume this happens when you don't have credentials for the page requesting HTTP Auth?

**Comment by the-nic** [comment]
Yes, for the pages that I tested, I dont have any credentials stored

**Comment by varjolintu** [comment]
Fixed with https://github.com/varjolintu/keepassxc-browser/commit/aa800d5aa14c97bfd32c9cfcc3166e7b83afdcec. New release 0.5.2 online soon.
