### ISSUE TITLE
XML pretty-print gets broken by the extension (Firefox)

### ISSUE THREAD

**Issue by z3ntu** [keepassxreboot/keepassxc-browser#50]
## Expected Behavior
Pretty print should work like it does on xml documents

## Current Behavior
![image](https://user-images.githubusercontent.com/3768500/37036583-620c3380-2150-11e8-90eb-b7211e766304.png)
This issue is mitigated partially by https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/manifest.json#L45-L48 so it was "fixed" on documents with .xml and .xsd endings but is still present when the xml document doesn't contain that extension.
Some more information (e.g. that jQuery is the issue) is at https://github.com/smorks/keepasshttp-connector/issues/32

## Steps to Reproduce (for bugs)

1. Open an xml document without the .xml or .xsd extension with the extension enabled

**Comment by varjolintu** [comment]
From jQuery:
>jQuery can manipulate an XML document and can run in an XHTML document but it's not meant to be included into an XML document directly. I'm not very familiar with Firefox plugins but this page seems to indicate the script is being injected into the plain XML page. That is not a scenario I'd expect to work at all.

**Comment by varjolintu** [comment]
Eventually this will be solved when #128 is merged in the future.
