### ISSUE TITLE
Password generator access in context menu is redundant

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#500]
## Expected Behavior

Features should be useful… (UX etc.)

## Current Behavior

There are two entries:

But right-click -> "Show password generator icons"
AND
Right-click -> "Show password generator"

in German like this:
![grafik](https://user-images.githubusercontent.com/11966684/56616138-ffe7a780-661c-11e9-8309-16138452049c.png)

Actually, to be even able to use the "Show password generator" you first have to choose "Show password generator icons" if icons are not already there… :smile: 

They are also worded very similar, which is quite confusing when first looking at it…

## Possible Solution

Unify these items?

Also, for better UX hide/disable the entries that do not make sense (if e.g. generator icons are already shown, you likely do not need such a context menu).

## Steps to Reproduce (for bugs)

But right-click -> "Show password generator icons"
AND
Right-click -> "Show password generator"

## Debug info

Operating system: Linux
Browser: Firefox/

**Comment by varjolintu** [comment]
I agree. I want to clean these up a little bit anyway. Extension don't allow many keyboard shortcuts and there must be room for more.

**Comment by varjolintu** [comment]
Closing this as the password generator icons context menu item is already gone, but showing the password generator item stays, because now the icons are disabled by default.
