### ISSUE TITLE
Force detect/autocomplete password fields

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#501]
[TIP]:  # ( Provide a general summary of the feature in the title above ^^ )
[TIP]:  # ( DO NOT include screenshots of your actual database! )

On KeePassXC 2.3.4 / KeePassXC-Browser 2.4.0

## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
1. There are some sites that block autocomplete
2. There are some sites that autocomplete / "new login detected" doesn't work (not external unfortunately ==> cannot provide a URL, Developer Console is clean apart from some nonce fails and "Error 15: no logins detected". Willing to provide additional diagnostics / help)

1. Even though I have chromeIPass installed (using _also_ KeePass), it doesn't seem to interfere with this process (and exhibits the same issue i.e. no detection, no offer to save credentials)
2. It seems that both of the extensions properly, automatically detect the credential fields (however, no visual prompt from "redetect login fields", https://github.com/keepassxreboot/keepassxc-browser/issues/424#issuecomment-482001951)

I don't know if [1] and [2] are somehow related, but my offending site appears to have both issues. (I am willing to test a known website that blocks autocomplete, to check if [1] is not related to [2])

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
If [1] is causing [2], then have some way to work around it, so that it prompts to save logins (and then offer them for autocomplete, if applicable). It can be manually-triggered, if so wanted.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by varjolintu** [comment]
I'm having a hard time to find a site where the autocomplete doesn't work at all and it fails every time. Mozilla's sites (and eBay) are not accepted because those just use scripts to prevent modifying the input fields.

**Comment by stdedos** [comment]
Is there somehow a way to enable verbose debugs, which I can then send to you?

Preferably nothing "indicating" the site or its explicit layout; something like (non-exhaustively):
* Found 'x' field as username / password
* https://github.com/keepassxreboot/keepassxc-browser/issues/424#issuecomment-482001951 to become an issue and solved
* "User logged in"
* "Extension prompted to save credentials, site URL: xyz.lol"

**Comment by varjolintu** [comment]
Are you still having this issue with the latest version?

**Comment by stdedos** [comment]
Would you kindly explicitly define "latest version"?

I am on:
```
KeePassXC-Browser Version: 1.5.2
KeePassXC Version: 2.4.3
```

**Comment by varjolintu** [comment]
That is the latest, yes.

**Comment by stdedos** [comment]
I am trying to replicate the issue, with "clean and full console"

I have noticed this issue if I have a page open, and I refresh "background page":
![image](https://user-images.githubusercontent.com/133706/66906906-1e998a80-f011-11e9-807b-7fa6030aba0f.png)

then the extension menu is not opening:
![image](https://user-images.githubusercontent.com/133706/66906938-2eb16a00-f011-11e9-9413-1dfd423fc2ed.png)

I need to refresh the page in order for that to work.

I don't know if it's related, a real issue, or an issue you care about.

**Comment by stdedos** [comment]
First of all: Even though login is detected, I get this:
![image](https://user-images.githubusercontent.com/133706/66907310-cfa02500-f011-11e9-970d-59eee36c7e23.png)

I have tried 2 cases back to back: first with autodetection and logging in; (check that there is no prompt to save the password and) logout; then with explicitly selecting the fields and logging in; (check that there is no prompt to save the password and) logout

![image](https://user-images.githubusercontent.com/133706/66907486-1261fd00-f012-11e9-9378-823fb9036fa4.png)

None seems to work. With or without chromeIPass extension activated.

**Comment by varjolintu** [comment]
What is the site, and what is your entry's URL?

**Comment by stdedos** [comment]
The site is an internal one, so, even if I provide you with a URL, it will not work :smiley:

I don't know what technology is that site developed with, but it is one of those one-page sites (everything under `//hostname/#/`). I only know it is using from `node.js`.

There is no URL entry; I am expecting that KeePassXC will pickup the new login and prompt to save. If I create one manually, it does pick it up though - even with chromeIPass activated at the same time.

**Comment by varjolintu** [comment]
This would need debugging of the extension to get further and see where the problem really is.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
