### ISSUE TITLE
[Firefox Extension] Fill username and password only fills username in multi-step forms

### ISSUE THREAD

**Issue by ashucg** [keepassxreboot/keepassxc-browser#502]
I am on Fedora 29, latest Firefox Nightly edition and since the recent extension update I am not longer able to autofill both, username and password, using context menu or keyboard shortcut keys in multi-steps form.

### Steps to reproduce:
- Go to https://www.upwork.com/ab/account-security/login
- Try to autofill username and password

### Results
Only username gets filled

### Expected Results
Both, username and password, should be filled

It was working fine before the recent update, but now, it doesn't.

**Comment by ashucg** [comment]
Actually, I have not added any custom login fields, it worked fine earlier on, so I never had to do that.

![image](https://user-images.githubusercontent.com/11291284/56658752-eed57f80-668a-11e9-96dc-134212c1ea0e.png)

**Comment by varjolintu** [comment]
Could not reproduce it. I tried the keyboard shortcuts and the context menu items. Can you check everything works with Firefox Stable?

**Comment by ashucg** [comment]
Tried on Firefox stable, these errors came up in browser console for [GoDaddy Login](https://sso.godaddy.com/)
![image](https://user-images.githubusercontent.com/11291284/56660212-8f796e80-668e-11e9-9535-1c35fa05a3c6.png)

**Comment by varjolintu** [comment]
The username field of GoDaddy's site uses type `username` which is not part of the standard. But I guess we could add that one to the list of accepted types because it can be quite common.

**Comment by droidmonkey** [comment]
GoDaddy not adhering to standards? Say it ain't so!

**Comment by ashucg** [comment]
I tried on Upwork using Firefox stable, but had same issue - only filled username field, password field remained empty.

**Comment by varjolintu** [comment]
Adding the type `username` to the accepted types list solves this. There's no workaround because even custom field selection follows the same type list.

**Comment by ashucg** [comment]
I am even having this issue with login form at https://bugzilla.mozilla.org/
You can see the issue in this [screencast](https://streamable.com/d8a6q)

**Comment by varjolintu** [comment]
@ashucg That is caused by another issue when detecting username/password field combinations. I found the reason for that too.
