### ISSUE TITLE
Permission denied to access property "apply"

### ISSUE THREAD

**Issue by maxauvy** [keepassxreboot/keepassxc-browser#503]
## Expected Behavior
Hitting "Enter" after entering user/password (with keepassxc-browser's dropdown menu or not) proceed to authentication. Same for the "Login" button.

## Current Behavior

Hitting "Enter" after entering user/password generates an error in the Firefox Console : Permission denied to access property "apply"

![Capture](https://user-images.githubusercontent.com/2428307/56663173-ba22f180-66a5-11e9-9fcd-2a3c0b5c031a.PNG)

## Possible Solution

Deactivating KeepassXC-browser extension solves the problem. But that's not really a solution 😉 
Using Chromium/Brave works too, but that's not a solution too 😄 

## Steps to Reproduce (for bugs)

1. Open Firefox and go to some page with a login form, in my case [Rainloop Webmail](https://rainloop.open-freax.fr/)
2. Open the console (F12)
3. Fill the two fields (user / password)
4. Hit "Enter" or click the login button
5. See that nothing happens but the error appearing in the console

## Debug info

KeePassXC - 2.4.1 (work) / 2.40. (home) 
KeePassXC-Browser - 1.4.2
Operating system: Win 10 (work) / Linux (Solus - home)
Browser: Firefox 66.0.3 (both home/work)

**Comment by varjolintu** [comment]
Firefox's WebExtension can override page's own scripts.. just need to find what overrides are affected this time :)

**Comment by varjolintu** [comment]
Found it. #495 fixes it.

**Comment by maxauvy** [comment]
So nice! (and quick)
Thanks, I'll just have to wait for this PR to be merged :)

**Comment by AdamPS** [comment]
I hit this problem too.  This bug breaks any javascript based overlay forms on any page/site - even a page with no login/password fields.  Disabling KeePassXC add-on is the only workaround that I found.  Thanks for a speedy PR - looking forward to a new release:-)

**Comment by varjolintu** [comment]
I'm making a new release right away when #495 is accepted.

**Comment by AdamPS** [comment]
Confirmed fixed in new release - many thanks for a quick response
