### ISSUE TITLE
Tags: Whislist vs feature request?

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#506]
What is actually the difference between a blue-tagged "feature request" and a green "wish list" issue, here?

**Comment by droidmonkey** [comment]
Nothing really.

**Comment by rugk** [comment]
Well… then you should try to unify it and use one tag. It totally confuses and breaks workflows on GitHub otherwise.

**Comment by droidmonkey** [comment]
Removed wishlist
