### ISSUE TITLE
Credentials asked to update on password-only field

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#507]
## Expected Behavior

When entering a password-only field the extension will ignore updating the entry (unless the password is changed).

## Current Behavior

A password-only field, such as "sudo mode" in GitHub, causes the extension to offering updating the existing entry with a blank username.

## Possible Solution

Fix the logic error

## Steps to Reproduce (for bugs)

1. Go to GitHub Settings
2. Go to a page that requires re-entering your password
3. Fill the password, submit
4. Observe the entry update dialog suggesting a blank username

## Debug info

KeePassXC - 2.4.2-Snapshot
KeePassXC-Browser - 1.4.2
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
The popup doesn't show a username because it cannot know it beforehand. After selecting Update the password is updated to KeePassXC correctly.

If the password is not changed, the update is ignored (like it should be, IMO). Why would it need updating if anything hasn't changed? Could you elaborate?

**Comment by droidmonkey** [comment]
What I mean is if the password is NOT changed it still asks to update the entry. My assumption was that it thought the username field was now blank.

**Comment by varjolintu** [comment]
It just happens because it doesn't know what credentials you are updating. Of course this could be improved by detecting the username if you have only one entry for the page, and ignore a possible update then if the password wasn't changed.

**Comment by droidmonkey** [comment]
That would be acceptable.
