### ISSUE TITLE
Support for non-standard input field types

### ISSUE THREAD

**Issue by olifre** [keepassxreboot/keepassxc-browser#508]
## Expected Behavior
I have a (non-public) page which provides a login form requiring filling an input field in addition to the usual "text" field for the username and the "password" field for the password. 
That input field is on purpose using a non-standard `type` to prevent autofilling tools from filling the field. In case a field type is not known, browsers assume `text` and still allow to edit the field, but those fields indeed stay hidden to this extension. 

## Current Behavior

Input-fields with non-standard `type` are ignored. 

## Possible Solution

Add the possibility to fill input fields with non-standard / broken `type` as custom input fields, i.e. allow to (optionally) select any input field in the DOM independent of the actual `type` when selecting custom fields to fill. 

PS. Of course I request something here which is an exotic case, and outside of the standard, but since browsers interpret invalid `type` as `text`, this might help with compatibility in general. Feel free to neglect this idea, though!

**Comment by varjolintu** [comment]
I think the best idea of implementing this would be to extend the possibility to select any type of input field with Custom login field selection. Then the extension would normally ignore those, but use them when specified to do so.

**Comment by olifre** [comment]
@varjolintu I fully agree, this sounds ideal. It might also prevent the need for other special cases like https://github.com/keepassxreboot/keepassxc-browser/commit/d0b24aff932671c04ea9e39d0cb6e3479290c1a6 which may pop up in the future. Thanks for considering it!

**Comment by LightTemplar** [comment]
I have a site, where KeePassXC doesn't put in username, also if I choose custom fileds. Password filed is set, only username not. Is this issue related? Site: https://manage.voximplant.com/auth

**Comment by varjolintu** [comment]
@LightTemplar With the `develop` branch that site works normally. So the next release will work with it. Still, this is not related to this issue. It's just a regression bug that's already fixed.
