### ISSUE TITLE
Settings background color

### ISSUE THREAD

**Issue by xf-** [keepassxreboot/keepassxc-browser#509]
## Expected Behavior

Set a font and background color or nothing

## Current Behavior

Set a font color with System background color
![image](https://user-images.githubusercontent.com/1295633/56773182-660b3080-67bd-11e9-9b8a-476278f4d329.png)

No background with inherit font color
![image](https://user-images.githubusercontent.com/1295633/56773221-9357de80-67bd-11e9-8741-0a265e27af99.png)

## Possible Solution

Set background color OR use bootstrap intended form-control class

## Steps to Reproduce (for bugs)

1. Open setting with a dark system theme

**Comment by varjolintu** [comment]
Dark system theme meaning... macOS dark theme? Some Linux DE dark theme? Browser's own dark theme?

**Comment by xf-** [comment]
KDE breeze theme.I think windows dark theme works the same way. No clue about OSX.

**Comment by varjolintu** [comment]
At this point we don't have a separate themes or detection for dark themes, even if they are provided by the system. Saved as a feature request.

**Comment by xf-** [comment]
Should be fixed with #322
