### ISSUE TITLE
KeepassXC Browser breaks todoist.com

### ISSUE THREAD

**Issue by dinandmentink** [keepassxreboot/keepassxc-browser#510]
There is some unexpected behaviour, specifically on todoist.com when KeepassXC is active.

## Expected Behavior
I would expect keepassxc browser not to interfere with website behaviour.

## Current Behavior
When keepassxc browser is active ordering tasks is broken on todoist.com. Having the database active or changing settings makes no difference. Just the addon being active is enough.

## Possible Solution
Maybe it would be nice to blacklist domains, on those domains all behaviour from keepassxc is stopped.

## Steps to Reproduce (for bugs)
1. Login to todoist.com (with or without using keepassxc) while keepassxc browser is enabled.
2. Try to order a task, it will not work. 
3. Disable keepassxc browser. 
4. Try to order a task, it will work as expected.

## Debug info
```
Error: Permission denied to access property "apply"[Learn More]
```

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.2
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
The next release will fix this. Just wait for it.
