### ISSUE TITLE
Unable to connect with KeePassXC

### ISSUE THREAD

**Issue by shrpstck** [keepassxreboot/keepassxc-browser#518]
## Expected Behavior

Clicking on KeePassXC-Browser icon results in this message, "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." Clicking Reload does nothing.
KeePassXC browser integration is enabled.  The Connect button in the Setting > Connected Databases does nothing.  I never see the Connect button appear when clicking on the KeyPassXC-Browser icon.

KeePassXC and KeePassSC-Browser newly installed to replace KeePass, KeePassHTTP and ChromeIPass.
Tried with an existing database and a newly created one.  
Tried uninstalling/removing everything, including KeePass and KeePassHTTP, then reinstalling.

KeePassXC appears to be working properly
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.3
Operating system: Windows
Browser: Chrome  72.0.3626.121
KeePassXC-Browser has encountered an error:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

**Comment by droidmonkey** [comment]
What browser?

**Comment by droidmonkey** [comment]
Did you do this:

![image](https://user-images.githubusercontent.com/2809491/57097854-c5e66780-6ce6-11e9-9881-0e97f18a6e85.png)

**Comment by shrpstck** [comment]
Yes, I tried selecting only Chrome, Vivaldi, and Brave  and selecting all 3 choices.

**Comment by varjolintu** [comment]
Please go through the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) and tell us what you found.

**Comment by sebast889** [comment]
I faced a similar issue (maybe same issue) to this a few times using the newest extension version. I get the same "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." error and clicking reload once or even refreshing the page shows the same error. I "fix" it whenever it happens by refreshing the page sometimes more than once and clicking reload 2-4 times until I get a "Database is not open [Reopen Database]" error (even though my DB is already open) and when I refresh the page after that then KeepassXC is connected.

**Comment by varjolintu** [comment]
@shrpstck Are you using a portable version of KeePassXC?

**Comment by shrpstck** [comment]
Not using portable version.

Trouble Shooting:
1) Found org.keepasscx.keepassxc_browser_chrome.json in AppData\Local\keepassxc and similar for all the browsers.  Found registry entry: HKEY_CURRENT_USER\\Software\\Google\\Chrome\\NativeMessagingHosts\\

2) chrome json file snippets: 
"path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",  and it is correct
and    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
I see no way to do this: "With Chromium-based browsers you can check that the extension ID is the same with what is shown at the extensions page."

3) keepassxc-proxy.exe not running, started manually
Started KeePassXC then clicked KPXC icon in Chrome, got same error, after a couple Reload attempts got error: "Key exchange was not successful."
Tried without proxy feature as described -- gets the same error and KeePassXC not started.
???? When/How should keepassxc-proxy.exe be started?

4) Not tried ... yet

**Comment by varjolintu** [comment]
@shrpstck keepassxc-proxy.exe should be started by the browser itself, not manually. You can see the extension id from chrome://extensions. If it doesn't show, set the extension debugging on. Does disabling automatic reconnect from the extension's settings help?

**Comment by shrpstck** [comment]
Extension id:  "oboonakemofpalcgghocfoadofidjkkk"

Disable automatic reconnect from extensions settings -> new error "Message encryption failed. Is KeePassXC running?"  It is running.  Clicking Reload a couple times results in "Key exchange was not successful."

**Comment by shrpstck** [comment]
1. Closed everything.  Restarted system.
2. Restarted Chrome.
3. Restarted KeyPassXC.
4. Confirmed browser integration enabled in KeePassXC
5. Confirmed KeyPassXC-Browser enabled in Chrome
6. Reloaded web page with login.
7. Clicked KeyPassXC-Browser Icon -> Error: Message encryption failed. Is KeePassXC running?
8. Clicked Reload multiple times -> Error: Key exchange was not successful.
9. Noticed keypassxc-proxy.exe not running, started manually
10. Repeated steps 4 through 8 with same results.

**Comment by shrpstck** [comment]
When I click the icon (step 7) in the Windows task manager I see several instances of this process appear and disappear: keepassnatmsg-proxy.exe
Is this part of KeePassXC or a left over from something else?
I found it in AppData\Local\KeePassNatMsg along with JSON files like kpnm_chrom.json
Content is:
{
  "name": "org.keepassxc.keepassxc_browser",
  "description": "KeepassXC integration with Native Messaging support",
  "path" : "keepassnatmsg-proxy.exe",
  "type": "stdio",
  "allowed_origins": [
    "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
    "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
  ]
}

**Comment by droidmonkey** [comment]
Whoa, I think you may be victim of a spoofed native messaging extension. We do not EVER have a "keepassnatmsg-proxy.exe" as part of our software.

**Comment by droidmonkey** [comment]
OR did you install this: https://github.com/smorks/keepassnatmsg-proxy

You must install the KeePassXC extension: https://chrome.google.com/webstore/detail/keepassxc-browser/oboonakemofpalcgghocfoadofidjkkk?hl=en

**Comment by shrpstck** [comment]
I don't recall installing keepassnatmsg-proxy but it sure looks like I did. )-:
The KeePassXC extension with that ID  is installed, or so says Chrome extensions.
Any suggestions on how to get rid of keepassnatmsg-proxy?

**Comment by droidmonkey** [comment]
Delete all the native messaging registry keys and files on disk that mention that program. Then redo the settings enable/disable for the keepassxc-browser in keepassxc

**Comment by varjolintu** [comment]
You could try to enable "Update native messaging manifest files at startup" from Browser Integration's Advanced settings tab.

**Comment by akanter** [comment]
> You could try to enable "Update native messaging manifest files at startup" from Browser Integration's Advanced settings tab.

Some combination of this setting plus restarting KeepassXC fixed my issue. Thanks, @varjolintu !

**Comment by shrpstck** [comment]
It is working!
Deleted all files of that name on the disk.  Deleted one registry entry.  Enabled "Update native messaging manifest files at startup" in KeePassXC.   Disabled KeePassXC-Browser in Chrome. Restarted KeePassXC.  Renabled KeePassXC-Browser.   
Then I tried a site with a login.  It presented the Connect button and I connected and everything is working great.
Thank you all for the help.

**Comment by lalop** [comment]
I've the same issue, this didn't fixed it.
I'm on firefox/osx, when I go on about:debugging I see this message  `Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.`

**Comment by varjolintu** [comment]
@lalop That's not what the debug log should display. That looks like the extension page's error listing. That unexpected property is because we use the same manifest file for both Firefox and Chromium. That actual property could be removed because we use build scripts now.

**Comment by lalop** [comment]
Yes I don't see this error in logs but in the about:debugging page.
So is this only a notice that I can ignore ?

**Comment by varjolintu** [comment]
@lalop Yes. Just ignore it. You must inspect the background page (of the extension) from the same page to get the actual debug view.

**Comment by lalop** [comment]
hey, so now I see the same error  `Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.`

**Comment by lalop** [comment]
@shrpstck which files did you delete ?

**Comment by shrpstck** [comment]
It's been a while so I don't recall them all. Definately keepassnatmsg-proxy.exe

**Comment by lalop** [comment]
it's fixed with keepassxc 2.4.3

**Comment by nddipiazza** [comment]
I notice that this issue sometimes happens on Firefox + Linux. What I found is that if I stopped the keepassxc application and opened it again fresh, then went into the browser extension Settings -> Connected Databases. I hit the "connect" button and it worked then.
