### ISSUE TITLE
KeePassXC-Browser blocked by firefox after 66.0.3

### ISSUE THREAD

**Issue by JayDi85** [keepassxreboot/keepassxc-browser#519]
## Expected Behavior

KeePassXC plugin must works

## Current Behavior

KeePassXC plugin blocked in firefox

## Possible Solution

All plugins must be signed by Mozilla:
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

## Steps to Reproduce (for bugs)

1. Firefox disable plugins today;
2. If you try to update then it's reports error about sign;

## Debug info

KeePassXC-Browser - 1.4.3 (26-04-2019)
Operating system: Windows 7 x64
Browser: Firefox 66.0.3

**Comment by varjolintu** [comment]
This has nothing to do with the extension itself.
