### ISSUE TITLE
Plugin no longer allowed by Firefox

### ISSUE THREAD

**Issue by JohannesBraams** [keepassxreboot/keepassxc-browser#521]
## Expected Behavior

The extension communicates with the KeePassXC application to fetxh username/password

## Current Behavior

As of today Firefox has disabled the extension KeepassXC0Browser, claiming it isn't properly signed. Therefor the communication with the application is blocked

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {2.4.1}
KeePassXC-Browser - {1.4.3}
Operating system: Mac/Win
Browser: Firefox

**Comment by varjolintu** [comment]
This is not the extension's problem, but Mozilla's.

**Comment by JohannesBraams** [comment]
Mozilla cases the problem true, but your extension no longer works so I
have to find another solution?

Op za 4 mei 2019 19:10 schreef Sami Vänttinen <notifications@github.com>:

**Comment by droidmonkey** [comment]
ALL extensions are currently broken because Mozilla did not update their certificate. You cannot do anything about it (except for low-level modifications) and neither can we. You just have to wait until Mozilla fixes THEIR problem.

**Comment by varjolintu** [comment]
https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
