### ISSUE TITLE
Automatic and broken form submission occurs when filling in fields

### ISSUE THREAD

**Issue by mehrdadn** [keepassxreboot/keepassxc-browser#522]
I just started testing out PR #128 and for some bizarre reason, with my particular combination of settings, I seem to actually get an automatic form submission (?!?!) when I fill in the password. And even worse, it's a broken submission, so the browser just reloads the page entirely when I try to fill something in credentials, and if I try to refresh, warns me that it would resubmit the form. (For example, this happens on Bank of America.)

I'm using 3fef9eb; my settings are:

- [ ] Always ask where to save new credentials
- [ ] Activate password generator.
- [ ] Automatically retrieve credentials.
- [ ] Automatically reconnect to KeePassXC.
- [x] **Automatically fill in single-credential entries.**
- [x] Activate autocomplete for username fields.
- [x] Show notifications.
- [ ] Show a notification when new credentials can be saved to the database.
- [x] Save domain only.

I think the issue is with **Automatically fill in single-credential entries**, because without it, it seems to work much better. Though even without that, it's still flaky and I still have issues autodetecting and filling in certain sites.

## Debug info
KeePassXC - KeePass 2.39
KeePassXC-Browser - 1.4.0
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
#128 is already merged and the current extension version is 1.4.3. So stop using that branch and use the official stable release instead.

**Comment by mehrdadn** [comment]
Oh I just pulled the latest `master`; didn't realize there were later released versions under `develop`. You might want to move forward master in that case—currently it's at 1.4.0 whereas develop is at 1.4.3.

But yes, 1.4.3 seems to work better, thanks. I still see some flakiness on BofA when I pause a few seconds before filling in, but otherwise it seems pretty decent. (P.S. there's an issue where I get `TypeError: "accounts.google.com" is not a valid MatchPattern` presumably because it doesn't start with `http[s]`... not sure if that's expected or not, but I had that setting leftover from earlier.)

**Comment by varjolintu** [comment]
Delete that settings. The new version shouldn't even allow entering URL's without a scheme.

**Comment by mehrdadn** [comment]
Yeah I did. Now I'm having trouble getting it to work with KeePass... it constantly requests unlocking when it shouldn't, then it tells me it's not associated when it is. Have you tested it with KeePass or just KeePassXC?

**Comment by mehrdadn** [comment]
Nope can't get it to work. It keeps thinking it's unpaired until I cancel the pairing and then it thinks it's paired until the next time I close Chrome and open it again. Have to go back to the old version.

**Comment by varjolintu** [comment]
Try if disabling Auto-Reconnect from the extension settings help. We are only maintaining the connection between the extension and KeePassXC. Any wrappers or 3rd party proxies with KeePass are not in our scope.

**Comment by mehrdadn** [comment]
I already tried that, it didn't help.

What am I as a user of KeePass+KeePassNatMsg supposed to do?

**Comment by mehrdadn** [comment]
Any chance you could test your software against KeePassNatMsg? If you find bugs with that software then of course you can't fix them, but there's a good chance you'll uncover bugs in this extension too...

**Comment by varjolintu** [comment]
As a KeePassNatMsg user you need to make an issue to their repo.

**Comment by mehrdadn** [comment]
I think I worked it out actually, it seems that the association from previous versions wasn't working well for some reason (the hash checks might have changed?). Creating a new association seems to have resolved the issue. Thanks!!
