### ISSUE TITLE
KeePassXC-Browser will only work if KeePass was launched beforehand

### ISSUE THREAD

**Issue by asia73** [keepassxreboot/keepassxc-browser#523]
If KeePass 2 wasn't launched prior to launching Browser the extension doesn't work. I have to disable the extension and then enable it again to make it work.

## Steps to Reproduce (for bugs)

1. Launch Browser
2. Launch KeePass 2
3. KeePassXC-Browser is gray (Reload, Can't decrypt message)
4. Disable/Enable the extension to get it to work

KeePass - 2.41
KeePassXC-Browser - 1.4.3
Operating system: Win 7
Browser: Opera

**Comment by varjolintu** [comment]
We don't officially support KeePass 2.

**Comment by asia73** [comment]
Any ideas who can cause trouble? The connection seems to be established.

**Comment by varjolintu** [comment]
You are probably using KeePassNatMsg? Make an issue to their repo. As a workaround you can try to disable Auto-Reconnect from the extension settings.

**Comment by varjolintu** [comment]
This is possible fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/529. So wait for the next version or try the current dev branch.

**Comment by asia73** [comment]
1.4.4 didn't fix this

**Comment by varjolintu** [comment]
@asia73 No it didn't. That's why opened a new issue for it yesterday: https://github.com/keepassxreboot/keepassxc-browser/issues/544

**Comment by sebast889** [comment]
@varjolintu

I still need to click Reload twice to reconnect in the latest version. Any ideas?
