### ISSUE TITLE
macOS's dark theme makes entries unreadable

### ISSUE THREAD

**Issue by ko-dever** [keepassxreboot/keepassxc-browser#524]
## Expected Behavior
With dark theme enabled, entries and their properties should be as readable as they are when dark theme is disabled.

## Current Behavior
Entries and their properties are not readable. I have to select all the text in a field to see its content. See screenshot below :

![kpxc-dark-theme-add-entry](https://user-images.githubusercontent.com/4114656/57199927-82089200-6f74-11e9-8301-d8e83596409e.png)

![kpxc-dark-theme-edit-entry](https://user-images.githubusercontent.com/4114656/57199975-f5aa9f00-6f74-11e9-88f5-a50fa75c059d.png)

## Steps to Reproduce (for bugs)
1. Open **System Preferences.app** > General > Appearance > Select "Light"
2. Open KeePassXC > Create a new entry > Type some text into the field "Title" and leave the window as it without saving.
3. Open **System Preferences.app** > General > Appearance > Select "Dark"
4. Switch back to KeePassXC, the text typed in the field "Title" is not visible anymore (but still exists).

## Debug info
KeePassXC - Version 2.4.1 / Revision: 7bafe65
KeePassXC-Browser - **Not related to browsers.**
Operating system: Mac
Browser: **Not related to browsers.**

**Comment by droidmonkey** [comment]
You need to restart the application after changing the system theme.

**Comment by ko-dever** [comment]
I am using [f.lux](https://justgetflux.com/) to automatically switch between light and dark themes based on the current time, it is counterproductive and very annoying to restart KeePassXC each time...

**Comment by droidmonkey** [comment]
Its not anything we can do about it, this is handled by Qt.
