### ISSUE TITLE
Firefox deactivated and removed addon

### ISSUE THREAD

**Issue by truelai** [keepassxreboot/keepassxc-browser#527]
Firefox Quantum 66.0.3
Ubuntu 18.04

Firefox automatically removed the plugin from my browser. When going to download and install it again from the Addons website, I get an error: 

> Download failed. Please check your connection.

In [the reviews of the addon](https://addons.mozilla.org/en-US/firefox/addon/keepassxc-browser/reviews/), I can see another user who recently had the same experience:

> by Firefox user 14928318, 8 hours ago
> Somehow, Firefox deactivated the plugin today out of nowhere, needed to reinstall Firefox completely. Still, one of the best-working password-vaults I've used so far. Would be great, to be able to choose name/pw/submit fields with the html, not just with this field.

I tried:
> apt install --reinstall firefox 

But this did not solve the issue.

**Comment by varjolintu** [comment]
This is a Firefox issue, not ours.

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
