### ISSUE TITLE
KeePassXC-Browser plugin does not work with Gmail

### ISSUE THREAD

**Issue by JtwoA** [keepassxreboot/keepassxc-browser#528]
## Expected Behavior
List of email addresses from db from which to choose
Dialogue asking to approve the creds
Logging in

## Current Behavior
Nothing.  Zip.  Nada.  Doesn't recognize the Gmail username field.

## Steps to Reproduce
1.  mail.google.com or gmail.com
2.  
![image](https://user-images.githubusercontent.com/12992040/57257725-40392380-7028-11e9-9735-bf858ee05708.png)

3.  Nothing.  There's no prompting, nothing happens.

Operating system: Win10
Happens in both Chrome and FF browsers.

**Comment by varjolintu** [comment]
Add the URL `https://accounts.google.com/*` to extension's Site Preferences tab and enable Username-only detection for the URL.

**Comment by JtwoA** [comment]
Thx.  If I have time to reinstall XC and XC-Browser I'll give this a
try.  It's a real deal-breaker for me if it cannot do this login.

**Comment by droidmonkey** [comment]
This works if you setup the username only detection.

**Comment by varjolintu** [comment]
@JtwoA Btw, the next version (1.4.4) will allow you to use keyboard shortcuts for the page without any extra configuring.
