### ISSUE TITLE
Credentials are available even KeepassXC was locked

### ISSUE THREAD

**Issue by kiesel** [keepassxreboot/keepassxc-browser#531]
## Expected Behavior

Once the database was locked in the main Keepassxc application, no credentials should be useable in the browser any more.

## Current Behavior

When a webpage is loaded that Keepassxc has credentials available for, these credentials are available even after the database was locked.

## Possible Solution

Credentials seem to be injected into the website / extension cache / ... (?) when the page is being loaded. If not the full credentials would be cached, but only the key title and username would be, and once the user chooses to make use of these credentials they'd be loaded from keepassxc in that instant, then a locked database would actually keep the credentials safe and no longer available.

## Steps to Reproduce (for bugs)

1. Open keepassxc, open a database
2. Open a webpage for which credentials exist, go to the login form (the extension must already detect the form)
3. Lock the database in the keepass application (by use of keepass itself, not the lock button)
4. Now, click the username field and let the extension fill in the credentials.

## Debug info

KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.12.3
Debugging mode is disabled.

Operating system: Arch Linux
CPU architecture: x86_64
Kernel: linux 5.0.12-arch2-1-ARCH

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.4

Browser: Firefox

**Comment by droidmonkey** [comment]
What version of the extension are you using

**Comment by varjolintu** [comment]
This was already fixed in 1.3.3.

**Comment by kiesel** [comment]
Ok, thanks. Sorry for the noise, then.

Strangely, my Firefox extension update didn't update it - and also doesn't update it when I request to do so now.

**Comment by varjolintu** [comment]
That is Firefox/Mozilla problem, which still seems to be unresolved for some.
