### ISSUE TITLE
Get login by UUID

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc-browser#533]
## Expected Behavior
I'd like to have a protocol action `get-login`, that takes an entry's UUID instead of an URL as request.

## Current Behavior
Currently, I have to use `get-logins` and provide an URL. This does not work well with entries that are not meant to be logins to online services. It also has the ambiguity of possibly returning multiple entries.

**Comment by varjolintu** [comment]
This is a good suggestion.
