### ISSUE TITLE
Pressing tab in a random textbox in Google Calendar triggers database unlock

### ISSUE THREAD

**Issue by mehrdadn** [keepassxreboot/keepassxc-browser#536]
## Expected Behavior
Pressing TAB in a random box shouldn't trigger fill-ins.

## Current Behavior
When I press TAB in some text boxes, the extension tries to trigger a database unlock and fill in boxes.
This doesn't happen with all text boxes; only some.

## Possible Solution
Not sure, but debugging shows that `index` is `-1` here:

    _index = kpxcAutocomplete.elements.findIndex(c => c.value === input.value);

But this code shouldn't be triggered in the first place. Not sure why `combinations` includes some text boxes and not others.

## Steps to Reproduce (for bugs)
1. Enable _Activate autocomplete for username fields_. (Leave `Automatically retrieve credentials` 
and `Automatically reconnect to KeePassXC` and `Auto-submit login forms` disabled.)
2. Start creating a new Google Calendar event.
3. Add 2 notifications.
4. Click on the text box for the 2nd notification.
5. Press TAB.

## Debug info
KeePassXC-Browser - 1.4.3
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
I could not reproduce it. You can try to add the URL `https://calendar.google.com/` to extension's Site Preferences list and select "Ignore all features" from the Ignore settings.

**Comment by mehrdadn** [comment]
I just disabled `Activate autocomplete for username` instead, but I feel like these are both the wrong solutions...

**Comment by varjolintu** [comment]
Have you got Username-only detection on for Google's sites? The right way to disable the extension functionality for certain sites is to use Site Preferences like said in my previous message.

**Comment by mehrdadn** [comment]
No I don't, and I'm saying I shouldn't have to do this. It feels like suggesting I reinforce my doors with concrete to prevent my car from randomly crashing into my house...

**Comment by mehrdadn** [comment]
I'll report back here if I can narrow down the issue more for you I guess. Would be nice to leave this open in the meantime in case anyone else comes across a similar issue.

**Comment by mehrdadn** [comment]
@varjolintu is this line correct?

	// Return if value is not in the list
	if (input.value !== '' && kpxcAutocomplete.elements.some(c => c.value !== input.value)) {

Just going based on the comment it sounds like you intended to write

	if (input.value !== '' && !kpxcAutocomplete.elements.some(c => c.value === input.value)) {

since right now you're checking if there exists a different value in the list, not if the value is in the list.

**Comment by varjolintu** [comment]
Nice find! That is indeed why the <kbd>Tab</kbd> doesn't work correctly when username is set manually. Not sure though if it affects to this issue.

Combinations are identified by using input fields with type `text`, `email`, `password`, `tel`, `number`, `username` and fields without type set.

**Comment by mehrdadn** [comment]
I think it definitely affects this issue, but whether it's the sole cause, I don't know. There may be more than one bug.

**Comment by varjolintu** [comment]
The combination should trigger database unlock only if one password field or username&password fields are found. You can debug the content script to see what input fields are inside the combination.

**Comment by mehrdadn** [comment]
Ohh wait I found it! It's including other text fields and it's because of my own code :-) I'd applied some local patches I had before and not realized one of them actually included more text fields than before. Specifically the patch was to change `inputQueryPattern` as follows:

    kpxcFields.inputQueryPattern = 'input[type=\'text\'][name*=\'id\' i], input[type=\'text\'][name*=\'user\' i], input[type=\'text\'][name*=\'login\' i], input[type=\'text\'][name*=\'logon\' i], input[type=\'text\'][name*=\'email\' i], input[type=\'email\'], input[type=\'password\'], input[type=\'tel\'], input[type=\'number\'], input[type=\'username\']';

I'm not sure if I still need it, maybe I'll remove it to see how it works without that. I used to need it in earlier versions.

**Comment by varjolintu** [comment]
So using the Site Preferences for that URL didn't work?

**Comment by mehrdadn** [comment]
I think it worked (at least it currently it does show a drop-down; I forget what it was like back then exactly), I just don't want to do it on every site and I think it shouldn't be necessary since the key combo is enough information for the extension to know to fill in the current box.
