### ISSUE TITLE
selecting custom fields 

### ISSUE THREAD

**Issue by XtraLarge** [keepassxreboot/keepassxc-browser#540]
Hello,
I've found a little bug on the dialog to define custom logon fields.

I use the proxmox system for hosting virtual machines. The logon screen shows 6 fields.
![0 Original](https://user-images.githubusercontent.com/20318559/57547234-5dd6f780-735e-11e9-9188-bc1f80175758.PNG)

By selecting the button to define the fields they will be detected correctly.
![1 vorher](https://user-images.githubusercontent.com/20318559/57547252-629bab80-735e-11e9-98a7-e48ba6e7fa06.PNG)

After select the username field as user for the username only on field remains.
![2 nachher](https://user-images.githubusercontent.com/20318559/57547271-6a5b5000-735e-11e9-943d-6bc5366a454f.PNG)

So I can't define the custom fields :(

## Expected Behavior
define used custom fields

## Current Behavior
after selecting username some fields vanishes

## Possible Solution
don't use custom fields :(

## Steps to Reproduce (for bugs)
N/A

## Debug info
N/A

**Comment by varjolintu** [comment]
Does it help if you select "Mehr anzeigen" after selecting the username? If that doesn't work correctly, you'll have to wait for the next release. https://github.com/keepassxreboot/keepassxc-browser/pull/530 was merged recently and it fixes some of that behaviour.

**Comment by XtraLarge** [comment]
After selecting the "username" field and then pressing "Mehr anzeigen" .... some field appear, but not all and specially not the right for me :)
![2a mehr anzeigen](https://user-images.githubusercontent.com/20318559/57567640-987f7500-73dc-11e9-9d35-14df3c95c8d3.PNG)

**Comment by varjolintu** [comment]
Please check if the latest version 1.4.4 fixes the issue.

**Comment by XtraLarge** [comment]
Hi,

in version 1.4.4 the field 5 and 6 (from the second picture of this post) vanishes if i choose the username field, but then if i select "show more" they appears.

So .... I did'n know if this is expected, but it resolves my problem. 

Should I close this issue? .... and thx for the fast reaction!!!

best regards 
Willi Werres

**Comment by varjolintu** [comment]
The fix worked as it should be. So let's close this one.
