### ISSUE TITLE
Fails to find any credentials occasionally

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#543]
## Steps to Reproduce (for bugs)

Not always reproducible. But I've had this at least twice now, so here are some information. 

## Expected Behavior

Should always find my credentials.

## Current Behavior

It shows me a notification "no logins found".
![image](https://user-images.githubusercontent.com/11966684/57640593-39278d80-75b3-11e9-9d5b-88654a19262f.png)

It fails to find them. And to begin with: It's _not_ https://github.com/keepassxreboot/keepassxc-browser/issues/535, as it's _not_ about entries with expire time set, but it really seems to affect _all_ of them.

**Important**: A workaround is to restart Firefox.

Also important: Sorry, but I could only test it in Firefox Nightly. However, i doubt it is a nightly bug, as well… I could reproduce it twice with some time in between.

### Processes

Firefox seems to have started KeePassXC-proxy a little too often:
![image](https://user-images.githubusercontent.com/11966684/57640476-ebab2080-75b2-11e9-9bff-d72f76b80bd3.png)

```
rugk     15556  0.0  0.0 265120 11336 tty2     SN+  17:57   0:00  \_ /usr/bin/keepassxc-proxy /home/rugk/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
rugk     15558  0.0  0.0 265120 11100 tty2     SN+  17:57   0:00  \_ /usr/bin/keepassxc-proxy /home/rugk/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
rugk     15559  0.0  0.0 265272 11220 tty2     SN+  17:57   0:00  \_ /usr/bin/keepassxc-proxy /home/rugk/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
```

## add-on

Per try I force KeePassXC to check for creds, I get _two_ console logs:
>  Error 8: KeePassXC-Verbindung fehlgeschlagen, bitte erneut versuchen 7 keepass.js:1088:13

![image](https://user-images.githubusercontent.com/11966684/57640634-58261f80-75b3-11e9-80b4-7f1df914bafc.png)

Setting some brekapoints, it seems to get some messages successfully, however:
![image](https://user-images.githubusercontent.com/11966684/57640940-fa460780-75b3-11e9-878b-27eeaf2a61a3.png)

(file keepass.js) 

But the first (one?) message is undefined:
![image](https://user-images.githubusercontent.com/11966684/57641007-2f525a00-75b4-11e9-804e-be7d329bb1c1.png)

Ah, and then later I get this:
![image](https://user-images.githubusercontent.com/11966684/57641034-3f6a3980-75b4-11e9-9ded-97229c5baa35.png)

## Possible Solution

* Try to fix this bug.
* Another thing: Please differentiate between "no creds found" and "no connection could be established to add-on" when showing the error to the user.

## Debug info

KeePassXC - 1.4.3
KeePassXC-Browser - 2.4.1
Operating system: Linux
Browser: Firefox 68.0a1

**Comment by varjolintu** [comment]
The next version will fix the extra proxy launching, and this is probably the reason for the undefined message.

**Comment by Riamse** [comment]
Is there a dev version we can apply ourselves locally?

**Comment by varjolintu** [comment]
@Riamse Yes. You can download the develop branch and load it locally.

**Comment by varjolintu** [comment]
Still having the issue with 1.4.6?

**Comment by varjolintu** [comment]
Still having the issue? Without any replies, this issue will be closed.

**Comment by varjolintu** [comment]
@rugk Just a thumbs down? :( I'd appreciate any information about the current state of the issue.

**Comment by rugk** [comment]
That should mean "no" – cannot reproduce it anymore.
