### ISSUE TITLE
Reconnect issues

### ISSUE THREAD

**Issue by varjolintu** [keepassxreboot/keepassxc-browser#544]
## Expected Behavior

The extension should reconnect to KeePassXC in all situations.

## Current Behavior

Auto-reconnect only works properly if KeePassXC is started before the browser.

## Possible Solution

This is a tricky one. Fixing the actual behaviour here is easy, but when I inspected the case some more I noticed a few problems:
- Reconnect causes memory leaks (that I could not remove totally, thanks JavaScript).
- There's no way to detect a situation where keepassxc-proxy exits right away (I tried it to send messages to stdout when this happens, the extension didn't get any of those), meaning it cannot connect to KeePassXC. It's uncertain if the proxy exits "too quick" so the `onDisconnect` listener doesn't have time to attach to the event.

The possible fix would be using the solutions above, but for now it's a dead end. One possible (and the best) solution is to modify `keepassxc-proxy` that it can handle the reconnect instead of the extension. These attempts have also been unsuccessful and I need more time to inspect this solution.

## Steps to Reproduce (for bugs)

1. Start your browser with Auto-Reconnect enabled
2. See the mag.. nothing happens

## Debug info

KeePassXC - 2.4.2
KeePassXC-Browser - 1.4.4 (dev)
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
I would be more than happy with a keyboard shortcut that performs a "Connect Request". I think auto-reconnect is a little too advanced for the state of the code.

**Comment by varjolintu** [comment]
@droidmonkey Those are both good ideas and worth investigating. Thanks!

**Comment by varjolintu** [comment]
When giving some thought to those suggestions, a heartbeat would not work because a Native Messaging connection would have to be established before a "ping" could be event sent to KeePassXC. This means launching the new proxy process, so it wouldn't really differ from the current implementation.

**Comment by droidmonkey** [comment]
Gotcha, makes sense

**Comment by varjolintu** [comment]
I'm still trying to make the reconnect work inside the proxy. My test code already can reconnect without no problems but it needs a lot more debugging.

**Comment by lusitania** [comment]
FYI Once v1.4.5 was deployed to my Chrome (this morning) I started seeing the "reconnect issue". I had to manually reconnect using the extension's icon next to the address bar. My work-around is to disable "Auto-Reconnect". After that I can sign-in, again.
