### ISSUE TITLE
*Document* the matching, *thoroughly*

### ISSUE THREAD

**Issue by georgehank** [keepassxreboot/keepassxc-browser#548]
## Expected Behavior

Not having to guess wildly why a website apparently doesn't match an existing entry in the database.

## Current Behavior

Please copy/paste the browser's JavaScript console messages and errors here: 
No errors, no console, and WTF anyway; it's a documentation "bug".

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.4
Operating system: Win 7 x64
Browser: Chrome

**Comment by droidmonkey** [comment]
The matching is based on url. The more specific you make the url in the entry, the less it will match.

github.com > api.github.com > api.github.com/login

**Comment by lhurt** [comment]
I doubt this very much. See at this.
![Screen Shot 2019-05-20 at 11 31 00](https://user-images.githubusercontent.com/379072/58012577-15090680-7af5-11e9-9d5e-d9533b5c73e7.png)
There are some entries in keepassxc that exactly match the URL, but none of them is displayed in the selection list.
Return only best matching credentials is checked.

If I uncheck this option, the expected entries are at least part of the list. This is totally unexpected

**Comment by droidmonkey** [comment]
It looks like you have an old version of the extension?

**Comment by lhurt** [comment]
![Screen Shot 2019-05-20 at 12 49 44](https://user-images.githubusercontent.com/379072/58016387-c9a72600-7afd-11e9-803f-64e2c4fee503.png)
I don't think so.

**Comment by droidmonkey** [comment]
@lhurt your experience here is quite unique. What I find interesting in your screenshot is the fact that it seems to returning duplicate entries. I just checked the code, and we do only search the entry url field for a match. The code to actually find entries is a bit sloppy, there is room for improvement here.

**Comment by varjolintu** [comment]
I have some improvements for this in my TODO list, including how the matches are made. But the list is growing longer day by day so might take a while.

**Comment by lhurt** [comment]
One more interesting thing. There seems to be a difference between *nix systems and Windows, because the screenshot below is from my Windows PC with the very same KeepassXC database and the same versions as on Mac and Linux, but there are no duplicate entries and the sort order is also different.
![image](https://user-images.githubusercontent.com/379072/58042251-7606fd80-7b3a-11e9-8aa0-c546baf97685.png)
Hope that helps

**Comment by varjolintu** [comment]
@lhurt Interesting. Thanks for letting us know!
