### ISSUE TITLE
KeePassXC Version Detection

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#55]
## Expected Behavior

A higher version than the last known highest version wouldn't trigger the out of date alert.

## Current Behavior

Observed the extension notifying me of my "out of date" KeePassXC version. The status eventually cleared which may have been when the extension pulled the latest info from the server. Also the error message should probably read "You are using an older version of KeePassXC, recommend you update to the latest version."

![browser_version_detect](https://user-images.githubusercontent.com/2809491/37091561-a653a024-21d6-11e8-89ce-42f023e315c0.png)

## Possible Solution

Check the numbers and if they are greater than or equal to what the extension knows is the latest, do not alert the user.

## General Info
KeePassXC fork - 2.3.1
keepassxc-browser - 0.5.2

Operating system: WINDOWS
Browser: CHROME
Proxy used: YES

**Comment by phoerious** [comment]
> keepassxc-browser - 0.5.2

You should pull the latest 1.0.1 from the Chrome Webstore.

**Comment by dnlsrl** [comment]
I'm not sure if this should have its own separate issue, but even the updated extension doesn't recognize the database and one needs to revoke the database to get it working again.

To be quite specific, it says that there is a database connected but the dropdown of credentials won't appear with the login forms, and the "Redetect credential fields" doesn't help either. When inputting the credentials manually though, the extension does give a notification (can't remember what it says exactly, can't seem to be able to make it appear now). What solves the problems is, just as I said, to revoke the database and connect to it again.

It happened to me first using Linux (Fedora 28 on FF 58/AppImage build) and I dismissed it as a Linux only issue, but it happened to me with Windows 10 Chrome 64 as well.

**Comment by varjolintu** [comment]
@dnlsrl Are you sure you wrote to a correct issue? See this thread instead: https://github.com/keepassxreboot/keepassxc-browser/issues/49

**Comment by droidmonkey** [comment]
Closing this for now since I was running an ancient version of the browser plugin 😆
