### ISSUE TITLE
Autocomplete dropdown position changes depending on page scroll position

### ISSUE THREAD

**Issue by sebast889** [keepassxreboot/keepassxc-browser#550]
I noticed that sometimes after clicking the username field the autocomplete dropdown options aren't shown properly below the username field. It looks like whether or not it shows properly depends on how far up or down from the login fields the page is scrolled.  I saw this happening on an internal page but I'm pretty sure it could happen on other websites. I've even seen the dropdown options shown way above the login fields.

**Comment by varjolintu** [comment]
Thanks for letting us know. Maybe the same IntersectionObserver the password icon uses can be used here also.

**Comment by fgimian** [comment]
I can confirm this problem on my end too in Chrome on Windows 10
