### ISSUE TITLE
Chrome: (Re-)Connection Bug

### ISSUE THREAD

**Issue by benjaminwolkchen** [keepassxreboot/keepassxc-browser#551]
## Expected Behavior
That the connection is established without reconnecting every time.

## Current Behavior
When i connected the Extension with one Database, after a reboot it needs to reconnect the Database, with setting the Key.

## Steps to Reproduce (for bugs)

1. Open Chrome/Chromium and install the KeePassXC-Browser Extension.
2. Connect to a Database.
3. Reboot the Computer
4. Open Chrome and open KeePass XC and unlock the Database.
5. Try to connect with the Database with the Extension.

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.4
Operating system: Win
Browser: Chrome/Chromium

## Additional Infos
KeePassXC Browser Integration Settings:
![keepass-xc-browser-integration-settings](https://user-images.githubusercontent.com/42138517/58346585-a9f46280-7e5b-11e9-8ffb-7a67f4b99989.jpg)
KeePassXC Advanced Browser Integration Settings:
![keepass-xc-browser-integration-settings-advanced](https://user-images.githubusercontent.com/42138517/58346614-c395aa00-7e5b-11e9-8d7e-63f3fb086af5.jpg)
Connect Dialog in the Extension:
![connect-browser](https://user-images.githubusercontent.com/42138517/58346635-d8723d80-7e5b-11e9-8e4c-9bc9434dc112.jpg)
Windows Version and Build:
![winver](https://user-images.githubusercontent.com/42138517/58346708-05beeb80-7e5c-11e9-9d23-d662001ec8fb.jpg)
Windows 10 Version 1809 Build 17763.503

Windows is activated.

**Comment by varjolintu** [comment]
Do you have some other extension or 3rd party application installed that cleans the cookies or temporary files from browsers?

**Comment by benjaminwolkchen** [comment]
@varjolintu No i dont have any other Extension installed except of uBlock origin and KeePassXC Browser. And no 3rd party applications that affect Chrome or KeePass XC.

**Comment by varjolintu** [comment]
Can you check if the connected ID is actually stored in the extension after a reboot? Found in the extension's settings page in Connected Databases tab. And you can also check if that ID is identical to the one in your database's settings (Database Settings -> Browser Integration).

**Comment by benjaminwolkchen** [comment]
Okay, thats strange - now it works perfectly, I've done nothing to my Browser but it works. Also after a reboot. That's strange.
But very thanks to you!
