### ISSUE TITLE
Browser extension disconnects from database after some time

### ISSUE THREAD

**Issue by fgimian** [keepassxreboot/keepassxc-browser#557]
After a period of inactivity, the Chrome brower extension shows the message below:

![image](https://user-images.githubusercontent.com/1811813/58480385-9a4b8580-819d-11e9-967e-ce13417d7dc1.png)

However, KeePassXC is running in the system tray and browser integration is already enabled.  Clicking **Reload** resolves the issue for a while longer, until it happens again.

## Expected Behavior

The browser extension should not lose connectivity with the KeePassXC client while it's running.

## Current Behavior

After a period of time, it seems that the browser extension stops connecting to the client and a reload is required.

## Possible Solution

I'm not aware of any.

## Steps to Reproduce (for bugs)

I'm still struggling to understand exactly what triggers this, so forgive me if the steps below lack some info.

1. Ensure KeePassXC is running and the browser plugin is installed and connected
2. Ensure you can login to a website with KeePassXC
3. Stop using KeePassXC for several minutes
4. Notice that the browser plugin disconnects with the screenshot shown above

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.5
Operating system: Win
Browser: Chrome

Any help is greatly appreciated, this is the only issue I've encountered with this otherwise wonderful software! 😄 

Huge thanks
Fotis

**Comment by varjolintu** [comment]
Does it help if you disable Automatic reconnect from the settings? It has been a PITA lately.

**Comment by fgimian** [comment]
> Does it help if you disable Automatic reconnect from the settings? It has been a PITA lately.

Thanks for the reply, I'm afraid that **Automatically reconnect to KeePassXC.** is already enabled 😢

**Comment by varjolintu** [comment]
Yes, but does it help if you **disable** it?

**Comment by fgimian** [comment]
> Yes, but does it help if you **disable** it?

I'm so sorry, I misread your message.  I'll attempt this and let you know how it goes.

**Comment by fgimian** [comment]
So far so good it!  However, I don't want to jump the gun so I'll continue to use the app in this state for the next day or two before confirming that this was the cause.

Thanks heaps
Fotis

**Comment by fgimian** [comment]
I can confirm that the issue has never occurred for me since disabling the option above so it absolutely seems to be related.  Any ideas folks?

**Comment by varjolintu** [comment]
We need to disable the reconnect tries from the popup also. This is the reason for the behaviour.

**Comment by varjolintu** [comment]
Please try the current 1.4.6 version.

**Comment by varjolintu** [comment]
Does this still happen? If there's no reply for the issue, it will be closed.

**Comment by roded** [comment]
Not sure this is the same issue, but for me with `Automatically reconnect to KeePassXC` setting set to off, once in a while the extension notifies me that the database has been disconnected and a new connection identifier needs to be specified.

**Comment by varjolintu** [comment]
@roded Does this happen with the KeePassXC 2.5.0 snapshot also? There was an issue that the database hash was calculated including the recycle bin hash, which is just stupid. So any deletion or recreation of recycle bin can cause this.

**Comment by roded** [comment]
@varjolintu I'm on 2.4.3. Will gladly test 2.5.0 once it's out.

**Comment by varjolintu** [comment]
@roded If you don't want to wait: https://snapshot.keepassxc.org/latest/

**Comment by roded** [comment]
@varjolintu, thanks! Though I get my KeePassXC via pacman so I'm not sure I have that option. Any idea when 2.5.0 will be out? Thanks

**Comment by varjolintu** [comment]
@roded Pretty soon. In a week or two.

**Comment by roded** [comment]
I'm now running KeePassXC 2.5.1 and KeePassXC-Browser 1.5.3 and this issue is still present unfortunately. I've tried playing with the "Automatically reconnect to KeePassXC" option as well.

I'm using both Firefox and Firefox-Dev to connect to the same KeePassXC data base. When attempting to fill in login details, it is usually the case that the KeePassXC-Browser is not connected to the database and a new connection needs to be established. (of course, I'm using a different connection ID for each browser).

**Comment by varjolintu** [comment]
@roded When this happens, does the Connected Databases tab still show both connections?

**Comment by roded** [comment]
@varjolintu, once connected each browser shows itself in the Connected Databases tab. I.e., on my Firefox I see the 'firefox' connection I've created for it and on my Firefox Developer Edition I see its 'firefox-dev' connection. These connections don't seem to be shared between the browsers in my case.

Also, at the point when a browser is disconnected from the database and asks me to pair with KeePassXC, the Connected Databases tab shows the last connection.

And another issue: My Firefox browser is currently not connected to the KeePassXC database. The following is shown in the Connected Databases tab:

![image](https://user-images.githubusercontent.com/903037/70222351-9ef78480-1752-11ea-89a8-1b40e9c4392f.png)

If I delete the connection and recreate it with the same name, it doesn't necessarily overwrite the previous connection. The first time I tried I did not see a overwrite warning and the connection reappeared with the same creation date at the last, the second time I've tried it did actually overwrite the connection. Actually, as my existing connections are rather old, I'll try recreating them to see if that helps.

**Comment by varjolintu** [comment]
@roded I suggest you to try removing all the connection keys from KeePassXC (Database Settings -> Browser Integration) and from both browsers. If that doesn't help, try a new temporary database and see if you can reproduce the problem with that one.

**Comment by varjolintu** [comment]
Please suggest reopening the issue if the problem still persists.

**Comment by rocketraman** [comment]
I still have this issue with 2.6.6. I've recreated connection keys many times. I have now *unchecked* the "Automatically reconnect to KeePassXC" setting and will see if that helps, but as I understand the comments above, that should no longer be necessary.

**Comment by rocketraman** [comment]
BTW, locking and re-opening the database seems to be the only way to solve this normally.

**Comment by varjolintu** [comment]
@rocketraman If you'll have to recreate connection keys very often it usually means one of the following:
- Something prevents saving your browser's localStorage (can be verified from Connected Databases settings)
- Somethings prevents saving the keys to KeePassXC (doubt that)
- Something intereferes with `keepassxc-proxy` and the connection drops (however, it shouldn't require new keys)

**Comment by rocketraman** [comment]
> @rocketraman If you'll have to recreate connection keys very often it usually means one of the following:
> 
> * Something prevents saving your browser's localStorage (can be verified from Connected Databases settings)

Not the issue, connected databases is fine.

> * Somethings prevents saving the keys to KeePassXC (doubt that)

Also not the issue. The app works just fine normally.

> * Something intereferes with `keepassxc-proxy` and the connection drops (however, it shouldn't require new keys)

I think this is the issue. I don't require new keys when this happens. Locking the database and re-opening it is sufficient to restore correct operation. How can I help debug to determine what the underlying issue might be here?

**Comment by varjolintu** [comment]
@rocketraman Can you verify `keepassxc-proxy` is up and running? Some other application can sometimes shut it down (anti-virus, anti-malware software etc). You didn't tell your OS or any other information so this is just speculation.

**Comment by rocketraman** [comment]
Linux (Fedora 35). Yes, keepassxc-proxy is up and running:

```
raman    1326415   16907  0 Dec11 ?        00:00:00 /usr/bin/keepassxc-proxy chrome-extension://oboonakemofpalcgghocfoadofidjkkk/
raman    2892788   16907  0 Dec13 ?        00:00:00 /usr/bin/keepassxc-proxy chrome-extension://oboonakemofpalcgghocfoadofidjkkk/
```

I suspect there are two because I run the KeepassXC browser extension in two different Chrome profiles. I wonder if that is related?

I don't run any automatic anti-virus or anti-malware software that would shut down keepassxc-proxy. I don't see anything in dmesg/journalctl about OOMs or anything like that. I also see no logs from keepassxc-proxy.

**Comment by varjolintu** [comment]
@rocketraman Running with two profiles can be related. But in this case I mostly suspect that you have two databases where the newer one is a clone of the older one, am I right? If this is true, select one of the databases, go to Database Settings, Browser Integration page and select "Refresh database group ID".

**Comment by rocketraman** [comment]
> Running with two profiles can be related. But in this case I mostly suspect that you have two databases where the newer one is a clone of the older one, am I right?

@varjolintu No, actually I connect both profiles to the same single database.

**Comment by varjolintu** [comment]
@rocketraman Can you confirm the Database Settings also shows same equivalent keys with the extension's Connected Databases tab?

**Comment by rocketraman** [comment]
@varjolintu Yes, though I did notice one inconsistency: in one of the two profiles, there were two "Connected Databases" with the same Identifier but different keys. The database contains only one of the two keys.

**Comment by rocketraman** [comment]
@varjolintu One other possible complexity: I do have two other databases that I pull data from into my main database via KeeShare. There are two keys present from those two databases, though I believe those are legacy. I no longer connect from the browser extension to those databases directly.

**Comment by varjolintu** [comment]
@rocketraman And you are connecting your two different profiles with different identifier names? I suggest to cleanup your database: delete all the keys, and connection from the extension from both profiles. Then reconnect the database with different identifiers for both profiles.

**Comment by rocketraman** [comment]
> And you are connecting your two different profiles with different identifier names

Yes they were already two different identifier names. However, I've done as you suggested anyway, and now have two keys in the database with unique ids, one for each profile.
