### ISSUE TITLE
Reopening database with KeePassXC-Browser triggers Yubikey udev rule

### ISSUE THREAD

**Issue by jeremyj** [keepassxreboot/keepassxc-browser#558]
## Expected Behavior
I expect KeePassXC-Browser not to trigger the udev rule

## Current Behavior
I have a udev rule that locks my screen when my Yubikey is removed

`ACTION=="remove", ATTRS{idProduct}=="0407", ATTRS{idVendor}=="1050", RUN+="/bin/loginctl lock-sessions"`

Whenever I click on the KeePassXC-Browser button in my browser to unlock the database this triggers the udev rule and my screen gets locked.
Furthurmore after this the udev rule stops working until I unplug and plug the Yubikey again.

I have tested this with:
KeePassXC-Browser 1.4.5
Brave Browser 0.64.77
Firefox 67

This is the output of `udevadm monitor`:
https://pastebin.com/gcHTwXiW

## Possible Solution
Unlock the database directly from the the app

## Steps to Reproduce
1. configure yubikey/lockscreen udev rule
2. plug in yubikey
3. click on KeePassXC-Browser then "Reopen database"

## Debug Info
KeePassXC - Version 2.4.1
Revision: 7bafe65

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.2 LTS
CPU architecture: x86_64
Kernel: linux 4.18.0-20-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by droidmonkey** [comment]
This did belong in the other repo. I reopened it.
