### ISSUE TITLE
keepassxc-browser interferes with Proxy SwitchyOmega

### ISSUE THREAD

**Issue by saru-man** [keepassxreboot/keepassxc-browser#56]
## Expected Behavior

Should not try to send credentials for proxies SwitchyOmega (PSO) already have correct ones.

## Current Behavior

When trying to access a sites that PSO routes through a basic authentication secured proxy server which credentials have already been entered in the PSO settings keepassxc-browser still tries to overrule the PSO credentials. But if you don't have the proxy credentials stored in the password database keepassxc-browser tells that it has multiple credentials (which is not true as it does not have any) and the basic authentication at the proxy fails, One then has to enter the credentials manually which leads to storing them in Chrome itself.

chromeIPass as an example does not interfere with PSO (don't know why ;)).

## Possible Solution

keepassxc-browser should not send credentials for proxies PSO already have them in it's own settings.

## Steps to Reproduce (for bugs)

1. Install keepassxc-browser and PSO
2. Configure PSO to automatically route some sites through a Squid proxy with basic authentication turned on
3. Try to access the sites
4. Look at keepassxc-browser's error message and take a look at Google Chrome's extensions (orange exclamation mark should be visible saying that PSO wasn't able to send credentials becaus keepassxc-browser already sent some)

## Debug info

Don't have any right now.

## General Info
KeePassXC fork - 2.3.1
keepassxc-browser - 1.0.1

Operating system: MS Windows 10
Browser: Google Chrome
Proxy used: YES

**Comment by varjolintu** [comment]
chromeIPass handles the HTTP Auth differently. Takes some time to reproduce exactly the same steps. Is it possible for you to debug the extension and see what httpAuth.js does in these situations?

**Comment by saru-man** [comment]
Sorry, I'm not a developer and have absolutely no idea how to debug anything (shame on me ;)). But if you tell me what to do I can provide further information.
