### ISSUE TITLE
1.4.5 completely breaks on Windows

### ISSUE THREAD

**Issue by derula** [keepassxreboot/keepassxc-browser#562]
## Expected Behavior
1. The extension initializes `keepass.currentKeepassXC` as a blank string.
2. The extension enables automatic reconnects before connecting even once.
3. Eventually, a connect occurs because the extension realizes it's not connected.
4. Everyone is happy!

## Current Behavior
1. The extension initializes `keepass.currentKeepassXC` as a blank string.
2. The extension attempts to enable automatic reconnects before connecting even once.
3. Some legacy code, intending to block out old versions of KeePassXC on Windows, determines that the empty string is a lower version number than 2.3.4.
4. Therefore, automatic reconnects are never actually enabled, and the extension never connects.
5. Everyone is very sad.

## Introduced by Commit
https://github.com/keepassxreboot/keepassxc-browser/commit/9a5408e366c6422b557b0802704a4aa80664a447

## Possible Solution
Either remove the block-out code in `keepass.enableAutomaticReconnect`, or perform one manual connect before enabling auto-reconnect, like was done in earlier versions of the extension.
Or if you want to get really fancy, re-write the block-out code to work with the new reconnect logic. Though I can't tell if this is overkill, since I'm not sure why it's there in the first place.

## Steps to Reproduce
Try to use the extension version 1.4.5 on Windows.

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.5
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
This fix is released soon.

**Comment by Uriziel01** [comment]
Is there any manual workaround for this issue before new version hits the ChromeWebStore? I'm just evaluating the whole Keepassxc environment and this issue blocked the process all together.

**Comment by varjolintu** [comment]
@Uriziel01 Two options:
1) Wait for the next release
2) Download the https://github.com/keepassxreboot/keepassxc-browser/pull/561 branch and load it to your browser locally and use it until the next release.

**Comment by derula** [comment]
@Uriziel01 there's also a more involved workaround if you know how to deal with dev tools. You can use the extension debugger to set a breakpoint in `keepass.enableAutomaticReconnect` (in keepass.js), then disable and re-enable the extension, and when the breakpoint hits, type `keepass.currentKeepassXC = '2.4.1'` in the console and hit enter before resuming execution. It will work until the extension is next reloaded, at which point you will have to repeat the workaround.
