### ISSUE TITLE
keepass-proxy  error

### ISSUE THREAD

**Issue by ydf** [keepassxreboot/keepassxc-browser#563]
mac os   
KeePassXC - Version 2.4.2
Operating system: macOS Mojave (10.14)
CPU architecture: x86_64
Kernel: darwin 18.6.0

 KeePassXC-Browser Version: 1.4.6

KeePassXC Version: unknown 

 /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
dyld: Library not loaded: /usr/local/opt/libsodium/lib/libsodium.23.dylib
  Referenced from: /Applications/KeePassXC.app/Contents/MacOS/keepassxc-proxy
  Reason: image not found
Abort trap: 6

**Comment by droidmonkey** [comment]
Please see https://github.com/keepassxreboot/keepassxc/issues/3209#issuecomment-498074589
