### ISSUE TITLE
KeepassXC cannot connect and closes

### ISSUE THREAD

**Issue by nicexe** [keepassxreboot/keepassxc-browser#564]
Its easier to show a video
https://youtu.be/jQ-QegtRCOI

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.6
Operating system: Mac
Browser: Firefox

**Comment by varjolintu** [comment]
Enable the proxy from Browser Integration - Advanced tab. Or if you want to use KeePassXC directly from the extension, shut down KeePassXC and then reload from the extension popup.

**Comment by nicexe** [comment]
Enabling proxy worked. I had this working before without it enabled though.

**Comment by varjolintu** [comment]
If you want to use the extension without the proxy, it has never worked in a way that it could connect to KeePassXC on-the-fly. Native Messaging API (the way to connect the extension to an application) must always launch a new process where the message transfer can be initialized.
