### ISSUE TITLE
"Connect" to database button doesn't work in Firefox Developer Edition

### ISSUE THREAD

**Issue by BartlomiejSkwira** [keepassxreboot/keepassxc-browser#565]
When using Firefox Developer Edition and trying to connect a KeePassXC database by clicking "Connect" in "Connected Databases" nothinig happens and I can't connect a database. FYI: This works in regular Firefox but not in Developer Edition.

## Expected Behavior
Go to KeePassXC browser extension `Settings` -> section `Connected Databases` and click `Connect` -> the plugin should prompt for a KeePass db connection. 

## Current Behavior
Clicking `Connect` doesn't do anything. Take a look a look https://streamable.com/52etb

I have browser extension enabled in KeePassXC:
![image](https://user-images.githubusercontent.com/1316517/59022387-f8d3cc00-884d-11e9-8175-4b459904f12c.png)

## Steps to Reproduce (for bugs)

1. Inatall Firefox Developer Edition on a Mac https://www.mozilla.org/en-US/firefox/developer/
2. Install KeePassXC Firefox plugin
3. Go to plugin `Settings` -> `Connected databases` -> click `Connect` -> nothing happens

## Debug info

KeePassXC - 2.4.1
KeePassXC-Browser - 1.4.6
Operating system: Mac 10.14.4 Mojave
Browser: Firefox Developer Edition

**Comment by varjolintu** [comment]
We only support stable versions of each browser. Firefox Developer Edition is considered as Beta, and some APi's in it might have changes that won't work with the extension. Also, this kind of problems can occur. Your best bet is to check if the Native Messaging scripts are saved to a different location than the stable Firefox. If that's the case, you must copy the script manually to the Developer Edition location.

**Comment by BartlomiejSkwira** [comment]
I wasn't aware that Firefox DE is like a beta, thought this is just aimed at web devs. I guess I'll stick to regular Firefox then. Thanks
