### ISSUE TITLE
Unable to fill password

### ISSUE THREAD

**Issue by AriaLyy** [keepassxreboot/keepassxc-browser#568]
## Expected Behavior
Reopen keepassxc via plugin, I can fill the password correctly on the webpage

## Current Behavior
If my Keepassxc database is down, I reopen the database in the plugin, but I can't fill the password correctly.
If I want to use it normally, I can only delete the connection and recreate the new connection.

![image](https://user-images.githubusercontent.com/10437293/59669396-b5ce0d00-91ec-11e9-90d7-fc7da9048bdf.png)

## Possible Solution
reason for the bug

## Steps to Reproduce (for bugs)
1. close keepassxc db
2. open web url and click keepassxc plugin
3. reopen keepassxc db
4. fill password

## Debug info
keePassXC - 2.4.3 
KeePassXC-Browser - 1.4.6
Operating system: Mac
Browser: Chrome

## Recurring operation
![github](https://user-images.githubusercontent.com/10437293/59669224-6ab3fa00-91ec-11e9-8aad-64e034097c95.gif)

**Comment by varjolintu** [comment]
This is possibly a bug that can be seen when you are reopening database using the popup button (I haven't made an issue about it yet but I've reproduced it). Instead, try to switch to KeePassXC and unlock the database from there. After that try to access the autocomplete menu normally.

**Comment by AriaLyy** [comment]
Yes, if I open the database in keepassxc first, it can be filled normally.
However, if I use the plugin to start keepassxc to open the database, it will not fill properly.
