### ISSUE TITLE
Browser extension: RAM leak (+1GB) and CPU hogging (100%)

### ISSUE THREAD

**Issue by maniqui** [keepassxreboot/keepassxc-browser#57]
When launching the browser, KeePassXC-Browser extension consumes 22MB of RAM and almost no CPU.
After a few hours running, the RAM consumption goes up to more than 1GB (and it would have kept raising if I didn't killed the extension) and the CPU usage is 100%.

See picture:
![image](https://user-images.githubusercontent.com/333695/37129183-6e9dbdb4-225c-11e8-94bb-587cd6cfb6f4.png)

## Expected Behavior

The extension should not leak memory nor hog 100% of CPU.

## General Info
KeePassXC Version: 2.3.1
KeePassXC-Browser Version: 1.0.1

Operating system: elementary OS 0.4.1 "Loki" (Linux)
Browser: Chromium Version 64.0.3282.167 (Official Build) Built on Ubuntu , running on elementary 0.4.1 (64-bit)
Proxy used: No

**Comment by varjolintu** [comment]
I found the function where this happens. Fixing ASAP.

**Comment by varjolintu** [comment]
Found another bug related to this. I couldn't get the exact point where this memory leak happens but it's clear that it's a `tab` object.

The exact point this happens is https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/keepassxc-browser.js#L1172. If everything else is commented out but the `sendMessage` is left, the objects still leak. It's probably related to event.js's `kpxcEvent.invoke`. I'll do more testing when I have the time.

**Comment by varjolintu** [comment]
Btw, I noticed that with Chrome/Chromium setting the icon leaks some stuff. This is a bug inside their browser implementation. Haven't found a better way to change the icon dynamically.
