### ISSUE TITLE
Unable to connect to database via browser extension after changing KeepassXC install location

### ISSUE THREAD

**Issue by elderpyre** [keepassxreboot/keepassxc-browser#570]
## Expected Behavior

KeepassXC-Browser Chrome addon 1.4.6 should be able to connect to a database via KeepassXC 2.4.3

## Current Behavior

After updating from a portable KeepassXC installation to an installer based installation, the Chrome browser addon is unable to connect to the database, even after ensuring the settings in the new install were correct for browser integration according to the quickstart guide (https://keepassxc.org/quickstart/). Is the install path being stored in the browser addon config somewhere separate from the database connection config that isn't surfaced in the UI?

## Possible Solution

Tried removing the existing connection in the browser addon, then adding a new connection via the settings page to no avail. No dialog or such is shown when clicking "connect". Also, no messages are generated in the console.

## Steps to Reproduce (for bugs)

1. Set up and connect to a portable install of KeepassXC with the Chrome addon
2. Delete portable install of KeepassXC and install an installer-based version.
3. Try to connect to a database via the new install after configuring KeepassXC via the Quickstart Guide.
4. Browser addon is unable to detect new version of KeepassXC.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.6
Operating system: Windows 10 Professional version 1809
Browser: Chrome 75.0.3770.100 (Official Build) (64-bit)

**Comment by droidmonkey** [comment]
Simple uncheck and re-check the browser checkbox in the browser integration settings. You can also ensure this doesn't happen in the future by enabling this setting:

![image](https://user-images.githubusercontent.com/2809491/60226733-73df3f80-985a-11e9-966b-b58b3f018dd0.png)

**Comment by elderpyre** [comment]
For what it's worth, I did have "Update native messaging manifest files at startup" box checked, but it didn't seem to take until after I unchecked both that and the browser integration, then re-enabled them.
