### ISSUE TITLE
Allow to save browser passwords in root

### ISSUE THREAD

**Issue by Ana06** [keepassxreboot/keepassxc-browser#574]
I would like to save the browser password directly in root instead of in a group. It doesn't seem to be possible.

Btw, what is the benefit/reason of storing browser passwords in a different group?

**Comment by varjolintu** [comment]
This is possible if you enable "Always ask where to save new credentials" from the extension settings and then choose Root folder when saving.

But yes, it seems that if you set the default folder name to Root it creates a new group instead. So that's clearly a bug.

**Comment by droidmonkey** [comment]
I believe you can set the group to '/' to achieve this. That is non-obvious though.

**Comment by Ana06** [comment]
@droidmonkey

> I believe you can set the group to '/' to achieve this.

This work! :tada: Thanks!! 

>  That is non-obvious though.

Adding the explanation to the configuration will solve it :wink:

**Comment by varjolintu** [comment]
I'll fix this with #351.
