### ISSUE TITLE
update password broken in change password form

### ISSUE THREAD

**Issue by Ana06** [keepassxreboot/keepassxc-browser#576]
When having a form like the following to change the password, updating the password from the browser extension doesn't work properly.

```
Current
New
Confirm new
```

## Expected Behavior
`New` password is saved.

## Current Behavior
`Current` password (the old one) is saved.

## More info

Related to https://github.com/keepassxreboot/keepassxc-browser/issues/575

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.6
Operating system: Linux (openSUSE Leap 15.1)
Browser: Mozilla Firefox 60.7.2

**Comment by varjolintu** [comment]
I'm going to fix this with #351 as it updates the whole saving process.
