### ISSUE TITLE
Connection attempt when using hotkey/context menu fill

### ISSUE THREAD

**Issue by krmax44** [keepassxreboot/keepassxc-browser#580]
## Expected Behavior

When using the shortcut or context menu for filling in a password field a connection attempt to KeePass XC should be made if it isn't already connected.

## Current Behavior

You have to click on the extension icon, click on "Connect" and press the shortcut again.

## Possible Solution

When using the shortcut/context menu, check whether a connection is already established, try to connect if not, else proceed as usual.

## Steps to Reproduce (for bugs)

Make sure you aren't connected to KeePass, then try the steps above.

## Debug info

KeePassXC - 2.4.2
KeePassXC-Browser - 1.4.6
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Have you tried to enable Automatic Reconnect for this behaviour? If it doesn't cause any problems for you of course.

**Comment by krmax44** [comment]
Oh, I completely missed that option, thanks! :+1:

**Comment by 3nt3** [comment]
That option doesn't exist anymore, should this be reopened? @krmax44

**Comment by varjolintu** [comment]
@3nt3 No. The feature is removed because it doesn't work properly. Another issue needs to be solved to get it back.

**Comment by 3nt3** [comment]
Yeah but this is another issue than auto connect, right? I just want a way to connect that doesn't involve using the mouse

**Comment by varjolintu** [comment]
@3nt3 Click the username icon.

**Comment by 3nt3** [comment]
> doesn't involve using the mouse
@varjolintu

**Comment by varjolintu** [comment]
@3nt3 Ah. Gotta check that the reconnect happens when using a fill from keyboard shortcuts also.

**Comment by 3nt3** [comment]
I'd be happy to open a PR if that functionality doesn't exist yet

**Comment by varjolintu** [comment]
@3nt3 Created an issue about it: https://github.com/keepassxreboot/keepassxc-browser/issues/1727
