### ISSUE TITLE
Missing quotes in defaultSettings

### ISSUE THREAD

**Issue by Fuddl1** [keepassxreboot/keepassxc-browser#584]
Hi,

keepassxc-browser/background/page.js misses quotes around the default update interval: checkUpdateKeePassXC: 3,

should be

checkUpdateKeePassXC: '3',

Cheers - Bruno

**Comment by varjolintu** [comment]
Thanks for noticing, but actually the problem is in https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/options/options.js#L126 because it saves a string instead of integer.

**Comment by Fuddl1** [comment]
Am Freitag, den 26.07.2019, 23:30 -0700 schrieb Sami Vänttinen:
> Thanks for noticing, but actually the problem is in 
> https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/options/options.js#L126
> because it saves a string instead of integer.
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> [
> {
> "@context": "http://schema.org",
> "@type": "EmailMessage",
> "potentialAction": {
> "@type": "ViewAction",
> "target": "
> https://github.com/keepassxreboot/keepassxc-browser/issues/584?email_source=notifications\u0026email_token=AMXEFNK2HUFQVLTES4B7K7LQBPTQTA5CNFSM4IHIRB62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26E25Q#issuecomment-515657078
> ",
> "url": "
> https://github.com/keepassxreboot/keepassxc-browser/issues/584?email_source=notifications\u0026email_token=AMXEFNK2HUFQVLTES4B7K7LQBPTQTA5CNFSM4IHIRB62YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD26E25Q#issuecomment-515657078
> ",
> "name": "View Issue"
> },
> "description": "View this Issue on GitHub",
> "publisher": {
> "@type": "Organization",
> "name": "GitHub",
> "url": "https://github.com"
> }
> }
> ]

Oops, then my idea wasn't a solution but an ugly workaround. However,
it helped to achieve my desired effect to set another default value for
fresh installations.

Cheers - Bruno
