### ISSUE TITLE
keepas XC browser Firefox in Windows unable to connect to app

### ISSUE THREAD

**Issue by dariopuerot** [keepassxreboot/keepassxc-browser#585]
Installed the extension and the message it returns is that the key exchange is unsuccessful, in Portuguese "a troca de chaves não foi bem sucedida"

the keepassxc app starts warning something is happening all the time, blinking on the taskbar, but no dialog window asking for the name of the connection ever appears.

Also, the browser extension does not recognise the app version.

browser extension version 1.4.7
app version 2.4.3
firefox version 68

in another computer running a synced firefox and keepass database, everything works fine

I went through checklist of keepassxreboot/keepassxc#1559.. Nothing appears to be wrong.

Anyone has an idea?

**Comment by varjolintu** [comment]
What's your OS? Are you using a portable version under Windows?

**Comment by dariopuerot** [comment]
No, it is an installed version, with MSI

**Comment by varjolintu** [comment]
Have you tried to delete the connection from both KeePassXC and your browser, and reconnect everything?

**Comment by dariopuerot** [comment]
I have uninstalled and reinstalled, how do I delete the connection?

**Comment by dariopuerot** [comment]
following information in 
https://github.com/varjolintu/keepassxc-browser/issues/19
I have looked for nativemessaginghosts in the registry.
 In all brwosers there is a folder with an REG-SZ with value not defined

looking for keepassxc, found this entry end the file it is directed to does not exist
![image](https://user-images.githubusercontent.com/16033292/62392756-9beb4e00-b53e-11e9-8ff4-33f04d1cd927.png)

I have also found these two in firefox and they direct to existing files:
![image](https://user-images.githubusercontent.com/16033292/62393003-52e7c980-b53f-11e9-888f-af0bd18bfd3e.png)
![image](https://user-images.githubusercontent.com/16033292/62393021-62ffa900-b53f-11e9-8772-9c9d7a0b5a8f.png)

**Comment by varjolintu** [comment]
The last picture has the correct value. If you see my username in the .json file, it's the old one from the time before it wasn't officially under the KeePassXC project. So please rename those, or disable/re-enable the support from your browser from KeePassXC settings.

**Comment by dariopuerot** [comment]
I have deleted registry entries with varjolintu. And also removed a com....json file in program files/keepassxc/ that had varjolintu in the name.

No changes in firefox behaviour

**Comment by dariopuerot** [comment]
I have been looking at what was different between my two installations, and I found that my settings were like these:
![image](https://user-images.githubusercontent.com/16033292/62434520-fd621700-b70e-11e9-8d13-74e48a25d165.png)

and I changed them to 
![image](https://user-images.githubusercontent.com/16033292/62434507-f20eeb80-b70e-11e9-83d7-ed88101ef5c1.png)

Now, it is working.

Thank you for your help. I wait for your answer to close the thread
