### ISSUE TITLE
When using with Chrome keepassxc-proxy crashes after closing keepassxc

### ISSUE THREAD

**Issue by Szewcson** [keepassxreboot/keepassxc-browser#586]
## Expected Behavior

When closing KeepassXC connected to Chrome extention proxy should close itself without errors.

## Current Behavior

After closing KeepasXC popup appears. The message says that "application keepassxc-proxy.exe has stopped working" and the system will shut it down.

## Steps to Reproduce (for bugs)

1. Open database in keepassxc
2. Connect Chrome extention to keepassxc database
3. Close KeepassXC
4. Watch popup

## Debug info

KeePassXC - {1.4.7}
KeePassXC-Browser - {2.4.3}
Operating system: Windows 10
Browser: Chrome

**Comment by varjolintu** [comment]
Interesting. Is Auto-Reconnect disabled?

**Comment by Szewcson** [comment]
Yes.

**Comment by varjolintu** [comment]
Does disabling it solve the problem?

**Comment by Szewcson** [comment]
I have this problem on another machine. It happends everytime on every database. I'm almost certain that this option was disabled. I just try to replicate this scenerio on machine on wich I normaly used Firefox. Downloaded Chrome, install extention, create new database, connect this database to extention. No crash with Auto-Reconnect disabled and same with enabled...

**Comment by Szewcson** [comment]
Ok, I was check today the options. Auto-Reconect was disabled all the time. Problem ocures only on Chrome and as I said before occures everytime. Windows Logs shows that the problem lays in the Qt5Network.dll. (version 5.12.3.0). Exception code is 0xc0000005, and the fault offset is 0x0000000000ad894

**Comment by varjolintu** [comment]
That doesn't tell much. I've never encountered this behaviour before. Are you able to setup a debugging environment?

**Comment by Szewcson** [comment]
Unfortunately not on this machine.

**Comment by varjolintu** [comment]
Does this still happen? If so, please check if any anti-virus or anti-malware software causes it.

**Comment by varjolintu** [comment]
Please suggest reopening the issue if the problem still persists.
