### ISSUE TITLE
Question : What alternative to "keepassxc-browser" do I have for the Palemoon browser

### ISSUE THREAD

**Issue by sebma** [keepassxreboot/keepassxc-browser#587]
Question : What alternative to "keepassxc-browser" do I have for the Palemoon browser ?

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - cannot install for Palemoon
Operating system: Linux
Browser: Palemoon

**Comment by droidmonkey** [comment]
There is none, you will have to use the Auto-Type feature. We have no plans to support legacy extension formats.
