### ISSUE TITLE
秘钥没有交换成功

### ISSUE THREAD

**Issue by qiyongxiao** [keepassxreboot/keepassxc-browser#588]
![image](https://user-images.githubusercontent.com/7349963/62747294-5e2e7e00-ba86-11e9-96e6-f689d07bc373.png)
这个怎么处理呢

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by guoqiao** [comment]
我也遇到了这个问题。
在设置里，你不仅要启用浏览器扩展，还要进一步允许你的浏览器，比如 Chrome.

**Comment by HWD789** [comment]
我也遇到这个问题了 2.7.5 插件1.8.6.1
按照文档看了一遍, 注册表和json文件都没有问题, 但就是提示不成功
我另起了一台Windows虚拟机测试完全没有问题, 但在宿主机上怎么也不好使

**Comment by varjolintu** [comment]
> 我也遇到这个问题了 2.7.5 插件1.8.6.1 按照文档看了一遍, 注册表和json文件都没有问题, 但就是提示不成功 我另起了一台Windows虚拟机测试完全没有问题, 但在宿主机上怎么也不好使

https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#group-policy-changes

**Comment by HWD789** [comment]
这个只是针对edge的吧 那Chrome和fox 呢

**Comment by zghk** [comment]
edge浏览器做如下设置，把keepass设为开机启动
不要问我是谁，我叫雷锋
[KeepassXC-Browser](https://www.baidu.com/link?url=KmAw25uWpu1uNINifN_6vcf0-wDysimnbSXlrC-vO42xrTHEL5pr-tCU-wxuhzazsZuhjBqKv0DU1P25ey4Msy5JQYKzBTOksppZfVgF-1K&wd=&eqid=b9dc8b2d00047c710000000665e197e0)

**Comment by zghk** [comment]
edge浏览器做如下设置，把keepass设为开机启动
不要问我是谁，我叫雷锋
![image](https://github.com/keepassxreboot/keepassxc-browser/assets/1520015/d8aebc89-8b02-4b55-a175-af6bea3a77ff)
