### ISSUE TITLE
KeePassXC-Browser  This extension may have been corrupted.

### ISSUE THREAD

**Issue by ciobancai** [keepassxreboot/keepassxc-browser#589]
## Expected Behavior
In Chrome in can see this `KeePassXC-Browser  This extension may have been corrupted. `

## Current Behavior
The KeepassXC-browser disappears after of couple of minutes from the Chrome and in the Extension meniu I can see the above error, works to repair it but the same behavior appears after a couple of minutes 

## Steps to Reproduce (for bugs)

1. Install KeePassXC-Browser from chrome store
2. Configure with KeePassXC app 
3. After a couple of minutes the extension gets the following error `This extension may have been corrupted. `
4.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.7
Operating system: MAC
Browser: Chrome Beta Version 77.0.3865.19 (Official Build) beta (64-bit)

**Comment by varjolintu** [comment]
We don't officially support beta browsers because many kind of things can happen. If you cannot replicate this issue with a stable build of Chrome, please close the issue.

**Comment by ciobancai** [comment]
Thank you for your answer, I will switch to stable Chrome.
