### ISSUE TITLE
Database not connecting (Chromium, Debian-Stretch, KeePassXC 2.31)

### ISSUE THREAD

**Issue by eudaimonstro** [keepassxreboot/keepassxc-browser#59]
## Expected Behavior
With an open KeePassXC database, KeePassXC-Browser should be able to detect the open database and begin the connection process.

## Current Behavior
Plugin does not recognize open database, clicking reload does nothing, and database cannot connect
![screenshot from 2018-03-08 14-02-41](https://user-images.githubusercontent.com/5083012/37179255-e9c1da20-22d9-11e8-8441-a3e3f60ad8a5.png)
![screenshot from 2018-03-08 14-03-31](https://user-images.githubusercontent.com/5083012/37179267-f023a93e-22d9-11e8-8ad1-671f4b2a9353.png)

## Debug info
No Error Messages
## General Info
KeePassXC fork - 1.0.1
keepassxc-browser - 2.3.1

Operating system: Debian - Stretch
Browser: Chromium 64.0.3282.119
Proxy used: No

**Comment by eudaimonstro** [comment]
Somehow fixed itself...

**Comment by fcore117** [comment]
Somehow 2.3.1 wont work with chromium too or is it fixed now? portable location i use for my Chromium
chromium.woolyss.com

**Comment by varjolintu** [comment]
@fcore117 Does the portable version use a different location for NativeMessagingScripts?

**Comment by fcore117** [comment]
Lastest update seems to be working, i had to exit browser and after that it connected. Case closed.

This extension acts different little bit compared to old.

**Comment by varjolintu** [comment]
@fcore117 Compared to what version? There are lots of fixes since the release went official.

**Comment by fcore117** [comment]
varjolintu: Compared to old KeePassHTTP

**Comment by varjolintu** [comment]
@fcore117 Yes. Much more. Some documentation links in [here](https://github.com/keepassxreboot/keepassxc-browser/issues/44).

**Comment by fcore117** [comment]
varjolintu: thanks for response. KeepassXC great for info storage and password manager as Chrome developers from Google refused to integrate master password based local storage. 

Keep up good work.

**Comment by varjolintu** [comment]
@fcore117 Thank you! Btw, there's an extension called [Keywi](https://github.com/LEDfan/keywi) that supports encrypting the local storage. I have planned a similar feature for over six months (called "Paranoid mode") but still haven't had the time to do it.
