### ISSUE TITLE
Firefox: KeePassXC-Browser Wont connect with database

### ISSUE THREAD

**Issue by Kaissner** [keepassxreboot/keepassxc-browser#591]
## Expected Behavior
It should connect to the database normally

## Current Behavior
When I click the KeepassXC browser extension it shows me the following message:

KeePassXC-Browser has encountered an error:
Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 
After I press reload it just says: Key exchange was not successful.

Pressing connect database in the extension settings doesn't do anything.
It started to happen after I re-installed firefox, I tried both using the portable and normal KeePassXC windows application and it wont work in either of them.

## Steps to Reproduce (for bugs)
1. Start firefox
2. Click the KeePassXC browser extension icon.

## Debug info
KeePassXC - Both the newest portable and normal 64 bit version downloaded today.
KeePassXC-Browser - 1.4.7 (Downloaded today as well)
Operating system: Windows 10 64-bits
Browser: Firefox

**Comment by varjolintu** [comment]
Check this guide for the registry paths and check everything else too:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by Kaissner** [comment]
I checked it and everything seems in place, I dont fully understand everything tho

**Comment by varjolintu** [comment]
The most important part is to check the registry paths and the files in those paths. Those should hold a variable that tells where `keepassxc-proxy.exe` is located.

**Comment by Kaissner** [comment]
Both the registry paths and the files are there, they all point to the file inside my installation folder

**Comment by varjolintu** [comment]
The next step is to debug the extension via `addons:debugging` and see what the console prints.

**Comment by Kaissner** [comment]
I got these errors:

![Untitled](https://user-images.githubusercontent.com/54112206/63137377-e4d6e400-bfcd-11e9-8d02-246f294c8f9a.png)

but browser integration is enabled

**Comment by varjolintu** [comment]
Few things to try:
1) Delete all connections from KeePassXC and the extension side and reconnect everything again.
2) Check that "Update native messaging manifest files at startup" is enabled in Settings -> Browser Integration -> Advanced

**Comment by Kaissner** [comment]
After deleting the connections and turning on update native messaging manifest files at startup turned off it's working again, thank you so much for your help!
