### ISSUE TITLE
Chrome Add-On works but not Firefox

### ISSUE THREAD

**Issue by NginUS** [keepassxreboot/keepassxc-browser#593]
## Expected Behavior
Clicking the Add-On icon provides access to open database

## Current Behavior
Errors occur in this order with <Reload> pressed between:

1. KeePassXC-Browser has encountered an error:
Message encryption failed. Is KeePassXC running? 

2. KeePassXC-Browser has encountered an error:
Key exchange was not successful.

## Possible Solution
Unknown

## Steps to Reproduce

1. Install KeyPassXC
2. Enable Browser Integration fro Chrome & Firefox
3. Install Add-On(s)
4. Restart Firefox
5. Click Add-On's icon
6. Click <Reload> after first error to see the second

## Context
Can use in Chrome, not Firefox (yet)

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Distribution: AppImage

Qt 5.10.1
Debugging mode is disabled.

Operating system: Linux Mint 18.3
CPU architecture: x86_64
Kernel: linux 4.15.0-58-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (only unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

Operating system: Linux Mint 18.3 (Ubuntu 16.04 LTS)
CPU architecture: x86_64
Kernel: Linux rc 4.15.0-58-generic keepassxreboot/keepassxc#64 16.04.1-Ubuntu
Firefox version: 68.0.1
Add-On version: 1.4.7

Add-On Debug Console Output:
```
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:1013:13
Error 9: Key exchange was not successful. keepass.js:1098:13
error occurred while processing 'sources: TypeError: can't access dead object
Stack: webExtensionTargetPrototype._allowSource@resource://devtools/server/actors/targets/webextension.js:292:5
TabSources/this.allowSource@resource://devtools/server/actors/utils/TabSources.js:25:39
_addSource@resource://devtools/server/actors/thread.js:1652:23
onSources@resource://devtools/server/actors/thread.js:1090:12
onPacket@resource://devtools/server/main.js:1291:58
receiveMessage@resource://devtools/shared/transport/child-transport.js:66:16
Line: 292, column: 5
```

**Comment by varjolintu** [comment]
Few things to try:
1) Delete all connections from KeePassXC and the extension side and reconnect everything again.
2) Check that "Update native messaging manifest files at startup" is enabled in Settings -> Browser Integration -> Advanced

**Comment by NginUS** [comment]
> Few things to try:
> 
>     1. Delete all connections from KeePassXC and the extension side and reconnect everything again.

Not sure exactly what this means, so I closed the database in the app, then disabled the extension in Firefox. After that I opened the existing database & enabled the extension in Firefox. Same errors occur on the Firefox side despite the database having been opened successfully in the app.

>     2. Check that "Update native messaging manifest files at startup" is enabled in Settings -> Browser Integration -> Advanced

This is the case.

**Comment by NginUS** [comment]
Firefox updated today to 68.0.2 & I'm experiencing the same error.

**Comment by varjolintu** [comment]
That's even more weird if a Firefox update caused this. I'd suggest to remove and reinstall the whole extension.

**Comment by NginUS** [comment]
> remove and reinstall the whole extension.

1. Here's what I did step-by-step:
2. Removed KeyPassXC-Browser Add-On
3. Exited Firefox
4. Watch & wait for all Firefox threads to close in Htop
5. Start Firefox
6. Install KeyPassXC-Browser Add-On
7. Exited Firefox
8. Watch & wait for all Firefox threads to close in Htop
9. Unlock Database in KeyPassXC AppImage executable
10. Start Firefox
11. Click KeyPassXC-Browser Add-On's icon

It still returns the following errors:
```
KeePassXC-Browser has encountered an error:
Message encryption failed. Is KeePassXC running?
```

Click "Reload" Button
```
KeePassXC-Browser has encountered an error:
Key exchange was not successful.
```

**Comment by NginUS** [comment]
For the sake of completeness, I rebooted & tried again- to no avail.

Am able to use the extension to create entries in the app from in Chrome Version 76.0.3809.100 (Official Build) (64-bit), & still get the same aforementioned errors from the Firefox Add-On.

**Comment by varjolintu** [comment]
Can you check with `strace` (or some other tool) that the path Firefox uses for its settings and NativeMessagingHosts really points to a correct place?

**Comment by NginUS** [comment]
> Can you check with `strace` (or some other tool) that the path Firefox uses for its settings and NativeMessagingHosts really points to a correct place?

That sounds a bit over my head, but I know how to view it's "about:support" where some of its settings paths are defined. I've attached its output, hopefully that helps.
[2019-08-18_Firefox-about_support.txt](https://github.com/keepassxreboot/keepassxc-browser/files/3513352/2019-08-18_Firefox-about_support.txt)

**Comment by varjolintu** [comment]
That output is not very helpful. One thing you could try is to make a temporary new profile for Firefox and check if it works correctly.

**Comment by NginUS** [comment]
I figured out what the problem was.

I start Firefox [0] with a script [1] so it runs at a higher priority, in an attempt to reduce its tendency to hang occasionally. As soon as I ran it at the default priority it worked.

[0]
`echo password |sudo -S sh /home/db/Scripts/Firefox_Medium-Priority.sh`



[1]
```
#!/bin/sh
nice -n -5 su -c 'screen -d -m firefox' db &
```

**Comment by droidmonkey** [comment]
Whoa!!! You were running Firefox as root?????

**Comment by NginUS** [comment]
> Whoa!!! You were running Firefox as root?????

No. It would show up in htop as me not root.
Hence the "`su -c 'command' db &`" to switch user back once nice is set.

**Comment by droidmonkey** [comment]
I think the problem here is using screen and not nice if that is the case.

**Comment by dmt0** [comment]
Just had similar behavior. Works on Chrome, but not Firefox.
Firefox: 101.0.1
KeepassXC: 2.7.1
macOS: 11.6.5

Presumably it happened after a Firefox upgrade. Mitigated like so:

1. Removed KeyPassXC-Browser Add-On
2. Exited Firefox, waited for full exit
3. Start Firefox
4. Install KeyPassXC-Browser Add-On
Everything initialized automatically
