### ISSUE TITLE
Login with email instead of user name

### ISSUE THREAD

**Issue by piegamesde** [keepassxreboot/keepassxc-browser#595]
## Expected Behavior

If there is a site where you log in with email+password instead of username+password, the plugin should recognize this and fill in the email address instead of the user name. If automatic recognition of such cases is not possible, there should be an option to manually set this for the size, either in the KeePass entry itself or using the "Choose custom login fields for this page" menu.

## Current Behavior
On sites where you log in with email+password, the extension fills in the username in the email field.

## Steps to Reproduce (for bugs)
1. Go to a site where login with email address instead of user name is required (tried with Mastodon instances)
2. Log in

## Debug info

KeePassXC - 1.4.7
KeePassXC-Browser - 2.4.3
Operating system: Arch Linux
Browser: `Chromium 76.0.3809.100 Arch Linux`

**Comment by varjolintu** [comment]
Database entries has only the username, not a separate email field. So, use the email address in the username field instead.

**Comment by piegamesde** [comment]
I don't feel really great about putting my email as username, if the email *isn't* my username. There are sites where the email *is* the username, and it works in those cases, but most of the times both are separate concepts and I won't mix them just because external tools can't handle it.

**Comment by varjolintu** [comment]
You can always put your username to the entry title. Username field itself is your login username, whether it's an username or an email address.

If you really want to do it your way, your only option is to use Custom Login Field. When choosing them, skip the username field, select the password field, and select the username field as a String Field after that. Then put `KPH: username` to your entry's attributes with our username as the value.

**Comment by piegamesde** [comment]
Thank you, it works. Maybe this could at least be documented somewhere for those who need it.

------
> Your email is your username for the login process, because that is used along with your password in the login window.

I still disagree though. You take a purely login-based perspective, in which case the email indeed may be compared to a username. But I think about my entries in a more broad sense. For me, the username is the name of my account at a given organization, my *identity*, even if I log in with the email address or phone number.

**Comment by varjolintu** [comment]
> I still disagree though. You take a purely login-based perspective, in which case the email indeed may be compared to a username. But I think about my entries in a more broad sense. For me, the username is the name of my account at a given organization, my _identity_, even if I log in with the email address or phone number.

Entries are meant for saving credentials, which consists username and/or password, not the account name. You can compare the situation to e.g. Facebook where you login with your email address but your real name is your account username.
