### ISSUE TITLE
Firefox/KeePassXC-Browser does not save database connection

### ISSUE THREAD

**Issue by franzhartwig** [keepassxreboot/keepassxc-browser#596]
Every time I start my Firefox, KeepassXC-Browser shows: "KeepassXC-Browser wurde nicht konfiguriert. Drücken Sie auf die Schaltfläche Verbinden, um eine Verbindung mit KeePassXC herzustellen."

## Expected Behavior
KeepassXC-Browser should connect to KeePassXC on startup. KeepassXC-Browser with Chromium does so.

## Current Behavior
KeepassXC-Browser complains, it is not configured. This happens after restarting the computer. If I restart Firefox, KeepassXC-Browser connects as expected.

Maybe important: In about:config there is no configuration related to KeepassXC.

## Steps to Reproduce
[NOTE]: # ( Provide a link to a live example, or an unambiguous set of steps to )
[NOTE]: # ( reproduce this bug. Include code to reproduce, if relevant )
1. Start Computer
2. Open KeepassXC, unlock database
3. Start Firefox. KeepassXC-Browser should connect to the database
4. Keepass-XC-Browser says, it is not configured.
5. Close Firefox. Start Firefox again. KeepassXC-Browser connects to the database.
6. Restart computer. Start KeepassXC, unlock database.
7. Start Firefox. KeepassXC-Browser is not connected.

## Debug Info
KeePassXC - Version 2.4.3
Revision: 5d6ef0c
Qt 5.5.1
Debugging mode is disabled.
Operating system: Ubuntu 16.04.6 LTS
CPU architecture: x86_64
Kernel: linux 4.4.0-159-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.1

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.7
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

**Comment by varjolintu** [comment]
You have two options here:
1) Open the popup in Firefox using the extension icon, then press "Reload" button. No need to restart the whole browser.
2) Enable Automatic Reconnect from the extension's settings. It will connect automatically to KeePassXC when it's detected.

**Comment by franzhartwig** [comment]
I know that it is not nessecary to restart the browser. I wanted to explain, that the problem only occurs after restarting the computer. After restarting the browser the connection to keepassxc is established.

The option Automatic Reconnect is checked. But when I reconnect keepassxc-browser to keepassxc, the option is unchecked, again. The same happens with the option "HTTP-Basisauthentifizierungsdialoge automatisch ausfüllen und absenden." It is checked after starting the computer and Firefox, after connecting to the database the option is unchecked.

I checked about:config once again. There are some entries regarding to keepassxc. They are the same I see on my Windows computer (browser.uiCustomization.state, extensions.webextensions.uuids, Extensions.webextensions.ExtensionStorageDB.migrated.kepassxc-browser@kepassxc.org).

**Comment by varjolintu** [comment]
So there's something that cleans up the extension settings? Is your configuration directory something non-standard or do you use a script or something else to start Firefox?

**Comment by franzhartwig** [comment]
Yes, there is something cleaning the extension settings. My profile directory is default:
~/.mozilla/firefox/snwkaplp.default
I am starting Firefox via the default firefox.desktop file:
```
...
Exec=firefox %u
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=firefox
...
```
There is nothing non-standard. Active non-Mozilla extensions are:
Cisco Webex Extension	1.5.0	true	ciscowebexstart1@cisco.com
KeePassXC-Browser	1.4.7	true	keepassxc-browser@keepassxc.org
uBlock Origin	1.21.2	true	uBlock0@raymondhill.net
Web Developer	2.0.1	true	{c45c406e-ab73-11d8-be73-000a95be3b12}

**Comment by franzhartwig** [comment]
I created a new profile in Firefox, it seems to work now. My profile was very old, some settings and old data from deinstalled add-ons and from old, no longer supported add-ons. Maybe, something legacy was interfering.
