### ISSUE TITLE
Auto-filling username and password doesn't work on the informIT site

### ISSUE THREAD

**Issue by brainplot** [keepassxreboot/keepassxc-browser#597]
First of all, I don't know if this is a problem with the site itself, since it's the only site so far where I'm experiencing this issue, or it's something to do with the extension. I'm just opening this issue so that you guys can perhaps further investigate. Thank you for this amazing extension, it makes logging in so much easier! :)

## Expected Behavior
Being able to successfully log in to the informIT site.

## Current Behavior
I get the pop window saying that the site has requested access to my username and password, I click on "Allow" and then on the e-mail field in order to get the form auto-filled. It gets auto-filled correctly but when I click on the red "Sign In" button, the site says that my e-mail and password are incorrect. **I know my credentials are correct because if I try to fill the form with the AutoType feature or by simply copying in my username and password, I can log in with no problems.**

## Steps to Reproduce (for bugs)
1. Go to the [informIT site](http://www.informit.com/)
2. Click on the Sign In link at the top right corner
3. Use the KeePassXC-Browser extension to auto-fill the form
4. Watch it fail because of incorrect credentials

**Note**: I tried to autotype my credentials in my text editor and auto-fill the form with the extension. Once the form was filled, I tried editing the HTML of the password field to an `<input type="text">` so that I could copy the password in my text editor from there and, to my surprise, the two passwords matched up so I really have no idea why the site is rejecting it.

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.7
Operating system: Linux x86_64 (I tried on Windows too and I can reproduce the issue)
Browser: Chrome/Chromium 76.0.3809.132

**Comment by varjolintu** [comment]
I made a test account for the site and I couldn't reproduce the problem. I even took a look at the scripts that validate the login, and there's nothing that modifies the input field values.

**Comment by brainplot** [comment]
Hi, thank you for trying to investigate the issue. Unfortunately, I just realized that this extension has nothing to do with it so I'm sorry for opening this issue here.
I have Keeppass2Android installed on my Android device, with the auto-fill service turned on. I tried to access the site on mobile and it's the same thing: works if I manually copy and paste but doesn't work when I try to auto-fill my credentials.
There must either be something wrong with the site (I'm thinking maybe they check if you actually type something in, no idea how since I'm not a web developer) or it's something to do with my passwords or the way it's stored in my database. I'll try to change it and report back.
Is there something I can do on my end to help pinpoint what the cause is?

**Comment by varjolintu** [comment]
It's possible that there's some JavaScript in the background that checks [Event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted) and that prevents any scripts to fill the credentials. That would explain why Auto-Type still works.

I'm using uBlock Origin with Chromium (non-advanced mode), but for me everything worked even if I disabled uBlock for the page. So you could try to disable JavaScript(s) for the current page and hope the login still works after that.

**Comment by brainplot** [comment]
Looks like I've solved the problem. My password was 31 characters long and, by going through the process of my changing it, I noticed that the requirements allow a maximum of 25 characters (not sure how I've been able to log in until now).
I shortened my password and everything worked fine after that.

**Comment by droidmonkey** [comment]
I experienced the same issue with my bank. On the password change form it had a maximum number of characters in the field. On the login form they allowed unlimited characters. So my password was the truncated version, but KeePassXC filled the full version. I notified them of their bug and ridiculous length limitations.

**Comment by vlcinsky** [comment]
This issue helped me to resolve my issue with logging into my router. The password in KeePassXC was 15 characters long, when I pasted it into password field, it got truncated (without visible notice) to 14 and I could get in, but when autofilled by KeePassXC, it went through in full length and the login process has failed.

When I shortened the password in KeePassXC to 14 chars, I could log in without an issue.

**Comment by varjolintu** [comment]
@vlcinsky Is there a limit for the password in the HTML code? We actually have a check for the limit in the old password generator code. It could be transferred to the filling side so user will see a notification if the password filled is too long.

**Comment by vlcinsky** [comment]
@varjolintu unfortunately I am unable to reproduce the problem as it was on OEM TP-Link TL-WDR4300 firmware which I have currently reinstalled to OpenWRT one, which does not suffer from this problem.
