### ISSUE TITLE
login.vivaldi.net This site cannot save credentials

### ISSUE THREAD

**Issue by qian-jiahong** [keepassxreboot/keepassxc-browser#598]
## Steps to Reproduce (for bugs)
1. Visit https://login.vivaldi.net/authenticationendpoint/login.do
2. Enter your username and password and click "Sign in".
3. The KeePassXC-Browser extension does not prompt to save, and the icon of the toolbar has not changed. As a result, the website login credentials cannot be saved.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser -1.4.7
Operating system: Win 7
Browser: Vivaldi

**Comment by varjolintu** [comment]
This is probably fixed with #351.
