### ISSUE TITLE
Shows Same Notification (over and over) through libnotify on each autotype

### ISSUE THREAD

**Issue by stef204** [keepassxreboot/keepassxc-browser#6]
Every single time I use autotype, the following notification appears  through libnotify:

`(A) KeePassXC-Browser
Create or modify the credentials by clicking on the extension icon`

## Expected Behavior

Do not show this notification every single time autotype is used.

Stop sending this notification each time autotype is used and/or disable notification via libnotify.
This could be a browser issue as opposed to keepassxc-browser extension issue (not sure.)

Could also be keepassxc itself sending the notification (but I doubt it.)

## Current Behavior

See above.
Every single type autotype is used, the following notification appears  through libnotify:
`(A) KeePassXC-Browser
Create or modify the credentials by clicking on the extension icon`

Remove this notification.

## Possible Solution

Reason: just annoying to get this obvious notification over and over again.
Fix: Disable notifications via libnotify?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## General Info
KeePassXC fork - VERSION=keepassxc-git 2.2.4.r469.ga5745eee
keepassxc-browser - VERSION=2.3.0-snapshot Revision: a5745ee

Operating system: Linux 4.15.1 (x86_64)
Browser: FF 58.0.2
Proxy used: NO

**Comment by varjolintu** [comment]
You can disable notifications from the extension settings page.

**Comment by stef204** [comment]
Sorry, I completely missed that. Thanks.

Without opening new thread, can I disable to key symbol appearing on each password field?

**Comment by varjolintu** [comment]
Yes you can :) Disable "Activate password generator" from the same page.

**Comment by stef204** [comment]
I saw that and deleted the question but you caught it in between. ( I reinserted the question, so that there is a track of it even in closed issues.) 
Thanks. Lets close this.
