### ISSUE TITLE
Password field detection not working on citi

### ISSUE THREAD

**Issue by ramenchef** [keepassxreboot/keepassxc-browser#60]
The username is detected, but not the password field. Site does not recognize the username as being filled even when it appears to be filled visually.

## Expected Behavior
The username and password field are detected and autofilled after being dynamically generated.

## Current Behavior
Username is autofilled but not the password field.
Website does not recognize that the username has been entered, so you have to use the shortcut to fill it in again.

## Possible Solution
Add further password field detection. Make website recognize that the username field has been filled.

## Steps to Reproduce (for bugs)
1. enable Automatically fill-in single credentials entry.
2. visit citi.com which redirects to https://online.citi.com/US/login.do
3. 
4.

## General Info
KeePass Version 2.38
keepassnatmsg 2.0.0.9
keepassxc-browser - KeePassXC-Browser Version: 1.0.1

Operating system: Windows 10 pro 1709 64bit
Browser: Chrome Version 64.0.3282.186 (Official Build) (64-bit)
Proxy used: NO

**Comment by varjolintu** [comment]
I'm pretty sure the page does some nasty JavaScript checking and modification to the input fields that messes up the content script. So far I haven't been able to find a way for this to work.

**Comment by droidmonkey** [comment]
This works with the latest version

**Comment by nickpj** [comment]
Is it possible to make autofill also work on the Australian Citibank site, as well as the US one, please? Link is: https://www.citibank.com.au/AUGCB/JSO/signon/DisplayUsernameSignon.do
(I'm using the KeePassXC-Browser add-on for Firefox, and don't get either autofill on either field)

**Comment by varjolintu** [comment]
@nickpj That site works just fine if you select _Choose custom login fields_ from the popup and choose the username and password field (then confirm). For some reason that sites has two forms, one for each input, so it gets a little messed up.
