### ISSUE TITLE
Support specific urls / login pages

### ISSUE THREAD

**Issue by Zocker1999NET** [keepassxreboot/keepassxc-browser#601]
This would allow to have different credentials for different login forms for example for the service `example.com/alpha/login` and `example.com/beta/login`.

## Expected Behavior

1. Insert credentials for the urls `example.com/alpha/login` and `example.com/beta/login`
2. Visit `example.com/alpha/login`
3. Addon retrieves only first credential and provides only first / filled in the password if auto fill-in is enabled
4. Visit `example.com/beta/login`
5. Addon retrieves only second credential and provides only first / filled in the password if auto fill-in is enabled
6. Visit `example.com/gamma/login`
7. Addon retrieves no credential

## Current Behavior
* Addon retrieves on both credentials on all 3 visits (steps 2, 4 and 6 from above)

## Possible Solution
Add an option to enable a more specific search for credentials so that the described expected behavior shows. You can maybe also let credentials for urls like `https://example.com` show on all 3 visits from above while credentials for urls like `https://example.com/` (trailing slash) only appear on the root page.

## Background
I use KeepassXC-Browser with Auto Fill-in but do not let the application remember my decision so that I get always showed the "Confirm Access"-popup window if a password field with a known credential shows. This is quite handy and a little bit more secure cause Firefox / the addon can not retrieve any credentials without my confirmation to the main application. But on some pages which are no login pages this is disturbing cause the popup appears on each click because of a "password" field somewhere. It is the same problems on webpages with a small login form on the top if I do not want to login.

## Debug info
KeePassXC - 1.4.7
KeePassXC-Browser - 2.3.4
Operating system: Linux (Debian Unstable)
Browser: Firefox

**Comment by droidmonkey** [comment]
I believe this already exists:

![image](https://user-images.githubusercontent.com/2809491/64138644-cba2a580-cdcb-11e9-9e6e-d46c4e60080b.png)

**Comment by varjolintu** [comment]
If you want to limit the extension's access to a certain pages, you can add the site to Site Preferences (extension's settings) and select "Disable all features" from the Ignore setting.

**Comment by Zocker1999NET** [comment]
@droidmonkey I already have enabled this option enabled but it still tries to retrieve the "wrong" credentials when I visit a subpage without stored credentials. One of my specific cases is GitLab (on a private instance, url is blacked out), I set the url for the entry to `https://gitlab.example/users/sign_in`, if I then visit `/users/sign_in` KeePassXC fills in my credentials as expected, however it does also fill in my credentials on the settings pages of repositories (`/user_name/repo_name/-/settings/repository`) which it is not expected to.

![browser_conf](https://user-images.githubusercontent.com/1645646/64474320-f0a06b00-d173-11e9-9282-23a8bd1bd333.png)
![url_field](https://user-images.githubusercontent.com/1645646/64474312-da92aa80-d173-11e9-8c6d-37fff14db81e.png)

@varjolintu This is an acceptable workaround for my use case, thank you. But it does not solve the main problem, as it will be some work to add all affected pages.

**Comment by sunfish** [comment]
I already have enabled "Return only best matching credentials", but I get all credentials for the Domain and not only for the stored URL. 
Are further settings necessary? Is it a problem if the KeePassXC browser settings have {"Allow":["www.domain.com"]}. Unfortunately I can't find a detailed description anywhere.

**Comment by varjolintu** [comment]
@sunfish Do you have multiple credentials for the same domain then? And one of them is a more specific one? That allow setting is always for the domain itself.

**Comment by sunfish** [comment]
Yes,  I have several projects with multiple credentials for the same domain. User accounts on a login page and another specific one for editor access to the CMS system. 
Kee - Password Manager extension offers the possibility to store a regex printout for the URL of the respective login page. Is there a comparable setting option for KeePassXC browser?

**Comment by varjolintu** [comment]
There's currently no regex or wildcard support for the entry URL's.

**Comment by varjolintu** [comment]
FYI, you can now use multiple URL's in KeePassXC. Edit an entry, and there's a separate settings page for Browser Integration.
