### ISSUE TITLE
Not possible to modify a remembered rule?

### ISSUE THREAD

**Issue by pt8o** [keepassxreboot/keepassxc-browser#602]
I was on a website and got the popup dialog asking me if I wanted to use a username/password saved in KeePassXC, and whether I wanted KeePassXC-browser to remember this decision. I accidentally pressed "Deny" instead of "Accept." Now I can't find a place where I can edit that rule, so I'm unable to use that login via KeePassXC-browser; I need to manually copy it from my desktop application.

I've looked through all of the settings on both KeePassXC on desktop and KeePassXC-browser and have not found where I can edit a previously remembered URL or rule. I have disconnected the database from the browser and then reconnected it, and I've also edited the database entry to have a different URL and then changed it back; neither has allowed KeePassXC-browser to use that entry on this site again.

## Expected Behavior
There should be some place where I can edit remembered rules.

## Current Behavior
There is no place where I can edit remembered rules.

**Comment by droidmonkey** [comment]
![image](https://user-images.githubusercontent.com/2809491/64495270-e8285d00-d265-11e9-9da7-97d079da3981.png)

We are cleaning this up with a dedicated browser settings page for entries in an upcoming version.
