### ISSUE TITLE
can not choose where to save new info

### ISSUE THREAD

**Issue by cmmei** [keepassxreboot/keepassxc-browser#603]
I can not choose where to save new info using KeePassXC-Browser in Chrome. 

I have select the item that always asking where to save new info, But there is no choice list.

Another problem is that it does not show when I create one connected-databases within keePassXC-Browser. I must refresh that page.

## Debug info

KeePassXC - {2.4.3}
KeePassXC-Browser - {1.4.7}
Operating system: Win
Browser: Chrome

**Comment by varjolintu** [comment]
The choice list appears in the popup where you can save/update the credentials. Can you confirm this is shown to you?

These both will be fixed (or adjusted) with #351.

**Comment by varjolintu** [comment]
Issue will be reopened if it still happens with the refactored credential saving.
