### ISSUE TITLE
Unable to disable 'fill credentials from keepassxc' icon

### ISSUE THREAD

**Issue by pysen** [keepassxreboot/keepassxc-browser#605]
Is it possible to disable this icon?

https://imgur.com/a/r1dJzb5

It clutters the login field and provides no new functionality. I  prefer the drop down menu from which the record can be chosen.

**Comment by varjolintu** [comment]
It does have a new functionality. It opens the dropdown menu if there are multiple credentials. If only single credentials are available, it fills them automatically without the menu.

Currently that icon cannot be disabled, but we can make an update that makes it optional.

**Comment by AdamPS** [comment]
Yes please make it optional.  This is an important usability bug for me as it severely blocks access to small input fields especially "pick chars".  The new button will not actually fill the right information (it fills my main password not the picked char from my extra data) and it makes it very difficult to select the field.

![Screenshot from 2019-09-26 19-34-40](https://user-images.githubusercontent.com/5490095/65715525-2eb6ed80-e095-11e9-8887-d53790edd2f5.png)

**Comment by droidmonkey** [comment]
Oooh, add another check in there to only show the icon if the input field is wider than a certain minimum size.

**Comment by AdamPS** [comment]
Yes the minimum size check is a good idea, but please also can we have the option to remove it always?  I think that an add-on should not force changes to page appearance. Same as the OP I will never click it and it just clutters up the UI.  As a web developer I need to see my sites as they will look to everyone without any alteration.

**Comment by varjolintu** [comment]
@AdamPS The icon is optional in the next version. We'll release it today.

**Comment by AdamPS** [comment]
Excellent many thanks

**Comment by varjolintu** [comment]
@droidmonkey We are already ignoring all fields that are smaller than 8px.

**Comment by AdamPS** [comment]
Great thanks
