### ISSUE TITLE
TOTP shortcut is not working

### ISSUE THREAD

**Issue by Booteille** [keepassxreboot/keepassxc-browser#606]
## Expected Behavior

I used Alt + Shift + T to fill an TOTP field, and expect KeepassXC Browser to recognize the shortcut and fill the field.

## Current Behavior

Instead, firefox thinks it's the shortcut to open tools. So the field is not fill.
I tried to change the shortcut key, but the page is a lot buggy (When I try to change one shortcut, it sometimes just don't recognize I am typing keys, other times, when AltGraph+Shift+Ŧ is recognized by the field, I can't save it. I get this error in logs `Cannot change shortcut: Error: Type error for parameter detail (Error processing shortcut: Error: Value "AltGraph+Shift+Ŧ" must consist of either a combination of one or two modifiers, including a mandatory primary modifier and a key, separated by '+', or a media key. For details see: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Key_combinations) for commands.update.`).

## Steps to Reproduce (for bugs)

1. Access to a TOTP field
2. Use Alt+Shift+T Shortcut
3.
4.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.4.7
Operating system: Linux
Browser: Firefox Nightly (71.0.a1)

**Comment by droidmonkey** [comment]
We cannot override a built-in shortcut from the browser...

**Comment by Booteille** [comment]
It's not overriding it by just using Alt+Shift+T (which is the default shortcut, btw), is it?

**Comment by droidmonkey** [comment]
Btw firefox nightly is full of bugs. We don't recognize issues that occur on that version channel. Try this on normal Firefox and report back pls.

**Comment by varjolintu** [comment]
Please see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations. It doesn't list <kbd>AltGraph</kbd> as a modifier key, so you cannot bind that combination as a shortcut.

**Comment by Booteille** [comment]
> Please see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations. It doesn't list AltGraph as a modifier key, so you cannot bind that combination as a shortcut.

My bad for this one, then. I should've check that before. Sorry.



> Btw firefox nightly is full of bugs. We don't recognize issues that occur on that version channel. Try this on normal Firefox and report back pls.

It's not working in a clean Firefox 69.0 neither. I have the exact same issue.

**Comment by droidmonkey** [comment]
I believe this can be closed then?

**Comment by Booteille** [comment]
Hmm. In fact, my main issue (being the fact I can't use the default shortcut Alt+Shift+T on Firefox) is still not resolved. As I stated, it's not working on 69.0 neither.

**Comment by droidmonkey** [comment]
Also, as I mentioned, we cannot override the behavior of built-in shortcuts. The same is true for Chrome as well.

**Comment by Booteille** [comment]
Okay. So it's not a bug, it's just Alt+Shift+T should not be choosed as a default shortcut?

**Comment by varjolintu** [comment]
We can define different shortcuts for different OS's. I can check that this shortcut really works as it should under Linux.

**Comment by Booteille** [comment]
Yup. I think it's a good idea.

Thank you for your time, all of you!
