### ISSUE TITLE
New release seems to break some pages

### ISSUE THREAD

**Issue by pferreir** [keepassxreboot/keepassxc-browser#607]
## Expected Behavior
This is[ the page where I first noticed this problem](https://indico.cern.ch/event/763185/).
![image](https://user-images.githubusercontent.com/2699/65689831-1c758900-e06e-11e9-849c-67acdf803b36.png)

## Current Behavior
Stuff which rendered OK before looks just broken when the KeePassXC extension is enabled.

![image](https://user-images.githubusercontent.com/2699/65689777-036cd800-e06e-11e9-8663-037e0a8259b2.png)

## Possible Explanation
I imagine that the plugin is injecting some HTML or CSS into the webpage, which breaks things.

## Steps to Reproduce (for bugs)
The link provided above should be enough...

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.0
Operating system: Mac
Browser: Firefox

**Comment by varjolintu** [comment]
Thanks for the report! I'll look into it. We are trying to move all DOM related content to Shadow DOM in the next release, so any HTML or CSS injected shouldn't affect to the page at all.

**Comment by Cqoicebordel** [comment]
I came here to file the same bug. The issue is in banner.css, where the .separator leaks to pages.
```
.separator {
    border-left: 1px solid #ccc;
    height: 100% !important;
    margin: 10px !important;
}
```

**Comment by varjolintu** [comment]
@Cqoicebordel Yes. That's the issue. A separate `kpxc-separator` should've been used instead.

**Comment by pferreir** [comment]
> @Cqoicebordel Yes. That's the issue. A separate `kpxc-separator` should've been used instead.

Please name any injected CSS classes as weirdly as possible. If you can add a random extremely-unlikely-to-guess-by-chance string to them, even better ;)

**Comment by droidmonkey** [comment]
Everything should be prepended with kpxc-

**Comment by krzyhook** [comment]
I have the same issue on Azure DevOps - i cannot see left menu items.
![devops-bug](https://user-images.githubusercontent.com/6848262/65748656-bdaf1e80-e104-11e9-9436-eed893437209.png)

**Comment by varjolintu** [comment]
I'm making a fix today, so hold your horses.

**Comment by novusidea** [comment]
You can see the same problem in the admin area of WordPress:

![grafik](https://user-images.githubusercontent.com/3848541/65753763-ed175880-e10f-11e9-9c63-d04ec1e8b896.png)

**Comment by pinonpierre** [comment]
Same issue about Azure DevOps.
Happy to see that the issue is already fixed.

Waiting the new version ;-)

**Comment by Cqoicebordel** [comment]
Confirmed fixed :)
Thanks !
