### ISSUE TITLE
Extension is read only

### ISSUE THREAD

**Issue by XakepSDK** [keepassxreboot/keepassxc-browser#618]
Firefox 70.0b10
Addon 1.5.1
Keepassxc 2.4.3
Extension is read only, i can't use "update" ~~or "create"~~(this works) button from extension. How do i fix this?

**Comment by varjolintu** [comment]
If you can reproduce this with stable Firefox build, I'll reopen the issue. We don't support nightly or beta builds because they often break some API's.

**Comment by XakepSDK** [comment]
Happens in 69.0.1 too, i click on update and nothing happens.

**Comment by varjolintu** [comment]
Could you open the page inspector and see if the JavaScript console has any messages?

**Comment by XakepSDK** [comment]
No messages at all. Also create new entry works on 70.0b10 too.

**Comment by varjolintu** [comment]
This would need debugging of the popup scripts. Please do so if possible.

**Comment by XakepSDK** [comment]
I think it's same as https://github.com/keepassxreboot/keepassxc-browser/issues/619
I reopen if issue isn't fixed.
