### ISSUE TITLE
Password change on Github -> "Update is grayed out"

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc-browser#619]
If I change my password on Github, then login with the new password, the top bar shows New | Update | Dismiss. But if I try and click Update it grays out before I have clicked it.

If I am very very quick I can click the Update button, but it does not update the database.

**Comment by macau23** [comment]
I can make a video?

**Comment by droidmonkey** [comment]
Sure can

**Comment by varjolintu** [comment]
It's possible that the Update is greyed out because credentials cannot be received for that page URL (there's no input fields or anything that could trigger the credential retrieval).

I'll try to reproduce this with a test account.

**Comment by varjolintu** [comment]
I was able to reproduce this and now know the cause. Fix will be coming soon. Thanks for finding this one!
