### ISSUE TITLE
Extension does not seem to work in Tor Browser

### ISSUE THREAD

**Issue by bitcoinx2** [keepassxreboot/keepassxc-browser#622]
I recently switched from Firefox (+ Tor routing) to Tor Browser. The KeepassXC configuration didn't change, but when installing the extension in Tor Browser, it fails to connect to KeepassXC. Browser integration for Firefox is enabled in KeepassXC.

## Expected Behavior
When installing the extension in Tor Browser, I expect that it just works fine like in normal Firefox.

## Current Behavior
The extension displays `Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.` When going to the extension settings and clicking on "Connect database", nothing happens.

## Possible Solution
* If necessary, add a new checkbox entry in the "Browser integration" menu in KeepassXC that allows the extension to connect with Tor Browser.
* Maybe it might be necessary to change a security setting of Tor Browser that prevents it from making the connection with KeepassXC? Only with the user's explicit permission of course.

## Debug info
There is no web console output in Tor Browser.
KeePassXC - 2.3.4
KeePassXC-Browser - 1.5.1
Operating system: Fedora 30 / Qubes OS.
Browser: Tor Browser 8.5.5 (based on Mozilla Firefox 60.9.0esr) (64-bit)

**Comment by droidmonkey** [comment]
You either need to manually move the configuration to the Tor Browser config folder or upgrade to 2.4.3 which supports tor browser in the browser plugin settings.

**Comment by paveltretyakovru** [comment]
> You either need to manually move the configuration to the Tor Browser config folder or upgrade to 2.4.3 which supports tor browser in the browser plugin settings.

@droidmonkey,  hello!
What are you mean with "manually move the configuration to the Tor Browser config folder"? I have the same problem
Thank you.

**Comment by varjolintu** [comment]
@paveltretyakovru For now we check `/torbrowser/tbb/x86_64/tor-browser/Browser/TorBrowser/Data/Browser/.mozilla/native-messaging-hosts` folder by default. If it's something else, you must the Custom Browser feature in KeePassXC to setup the correct path.

Another user posted this today for Brave. The configuration is almost similar, except the browser type is Firefox:
https://github.com/keepassxreboot/keepassxc-browser/issues/1783#issuecomment-3450226547
