### ISSUE TITLE
Auto launch KeepassXC upon Firefox start

### ISSUE THREAD

**Issue by catfluoride** [keepassxreboot/keepassxc-browser#624]
Hi!

Unless I'm missing something, KeepassXC has to be launched independently of the browser.

I think that an option to auto-launch KeepassXC upon browser start would be very handy.

A simple check button and an (optional) text field for the KeepassXC executable pattern should do it.

Thanks a lot in advance!

C.F.

**Comment by varjolintu** [comment]
That option already exists. You can enable this behaviour by disabling _Settings -> Browser Integration -> Advanced (tab) -> Use a proxy application between KeePassXC and browser extension_.

Please note that this means the Native Messaging API owns the KeePassXC process. KeePassXC starts when you start your browser, and closes if you close your browser.

**Comment by catfluoride** [comment]
Oh, thanks a lot. I didn't know what that option was for.

Sorry for the noise.

C.F.
