### ISSUE TITLE
How to configure RedirectAllowance?

### ISSUE THREAD

**Issue by lauripiisang** [keepassxreboot/keepassxc-browser#627]
## Expected Behavior
I'd expect to be able to save passwords even when the site redirects me. However this is not the case, as the banner disappears, so I have to be quick or do it via the desktop client ( annoying UX).

## Current Behavior
I'm having same issue as https://github.com/keepassxreboot/keepassxc-browser/issues/172 

## Possible Solution

I'd accept the proposed solution there (some RedirectAllowance config/slider), but I cannot find anywhere to configure it. I don't see a reason for the dialog to close at all, unless I close it or choose one of the actions there.

## Debug info
KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.1
Operating system: Mac
Browser: Firefox

**Comment by varjolintu** [comment]
There's no such settings anymore. The banner should recover after one redirect. We need to make some changes if there are several. Maybe we could show the banner always until it's dismissed, even if the redirects happen again and again.

**Comment by lauripiisang** [comment]
> Maybe we could show the banner always until it's dismissed, even if the redirects happen again and again.

Yes, PLEASE take this approach! There's no gain to be had from hiding it...

**Comment by lauripiisang** [comment]
Feels like a bug rather than a missing feature. If I don't click the banner super fast, on most sites, it disappears and my newly generated password is lost unless I copied it.

**Comment by varjolintu** [comment]
Is there some site this happens every time? It would help testing the fix.

**Comment by lauripiisang** [comment]
I've tried with the sites I remember to have had the issue with (Challonge.com and getpostman.com) and didn't experience the issue anymore. I wonder if the KeepassXC application's state has anything to do with it, as I remember having the new entry open previously, while now I didn't. Also, previously I hadn't had visited the sites before, so that might  factor into things, who knows. 
In any case, it would be a welcome change to see the dialog stay present

**Comment by varjolintu** [comment]
@lauripiisang I just made a few local test pages with redirects, and I'm trying to get this fixed.

**Comment by intika** [comment]
> Maybe we could show the banner always until it's dismissed, even if the redirects happen again and again.

Yes many site are doing several redirect before landing on the login page... i guess this is a good approach or at least at an option for it :)

**Comment by hhoefener** [comment]
Any news on this? Updating or saving passwords is impossible on many sites for me right now

**Comment by varjolintu** [comment]
@hhoefener I'm trying to get this to the next version.

**Comment by varjolintu** [comment]
The pull request is ready. Feel free to test it.

**Comment by PatRiot1337** [comment]
I have the same problem even with infinite redirect amounts on some websites.... is it already fixed?

**Comment by varjolintu** [comment]
@PatRiot1337 I haven't been able to reproduce the issue. On what page you see this behavior?

**Comment by PatRiot1337** [comment]
@varjolintu for example https://www.immobilienscout24.de or https://www.ebay-kleinanzeigen.de , but there were a lot more. I try to find them out again!
