### ISSUE TITLE
RFE: Use the same database for several users

### ISSUE THREAD

**Issue by moobyfr** [keepassxreboot/keepassxc-browser#63]
We use internally keepass/keepassxc on a synced storage (with Seafile, a dropbox clone) between several users, to store user/login for the IT service.
We currently don't use any browser extension to autofill entries, but we are thinking about it.

can the same database be used with several users/browser ? it seems that an entry at root is added:
```KeePassXC-Browser Settings```

**Comment by droidmonkey** [comment]
Yes, everytime you connect a new browser it creates a new attribute on that special entry. This attribute requires a unique name and stores the encryption key to secure comms. So make sure you tell everyone to use a unique name (their username?) when registering their browser.
