### ISSUE TITLE
Unable to save new credentials with banner disabled

### ISSUE THREAD

**Issue by aib** [keepassxreboot/keepassxc-browser#633]
## Expected Behavior

KeePassXC-Browser should be able to save new credentials without blocking the top, usually navigational part of *every single site I log in to*. This used to be possible by using the tiny extension icon whose location is user-configurable.

## Current Behavior

With the content-blocking popup disabled, there is no longer a way to save new credentials, one of the two things I use the browser extension for.

## Possible Solution

Bring back the controls accessible by using the extension button which takes up 32x32 pixels of *non-website-content* screen real estate.

## Steps to Reproduce (for bugs)

1. Click on the extension button, go to "Settings"
2. Uncheck "Show a banner on the page when new credentials can be saved to the database."
3. Log in to a new website or with a new password to one already in the database
4. Try to save the new/updated credentials

## Debug info

KeePassXC - 2.3.4
KeePassXC-Browser - 1.5.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 69.0

**Comment by varjolintu** [comment]
Sorry to inform you but the popup from extension icon is not coming back. It was not working properly for a long time, and it was almost impossible to get work even if fixed.

I'd suggest some minimal banner/icon that would be displayed on the page instead of the whole banner, if user wishes so.

Before the banner, you could also disable saving from the popup, so there's nothing new about the setting itself.

**Comment by aib** [comment]
Thank you for informing me. I can now train myself to tolerate it knowing that there's no alternative :|

Looking back at my report, I'm wondering whether it sounds sardonic. I apologise if so; I was trying to give rationale for my request to roll back a change someone obviously spent valuable time doing, and might have shifted tones without noticing.

I did not realize the setting disabled saving altogether; I thought it might be a way to switch between the popup (old) and the banner (new) mode—another reason I filed this bug report.

Thank you

**Comment by varjolintu** [comment]
I agree the banner is not perfect, but it's still more reliable than the previous popup method. And I understand the banner can be annoying for some, so I'll try to improve things a little bit in the future, or at least provide some alternative method for credential saving.
