### ISSUE TITLE
Username is not being filled if associated `input` doesn't have the `type` attribute set

### ISSUE THREAD

**Issue by Talv** [keepassxreboot/keepassxc-browser#636]
## Expected Behavior
Extension should correctly detect input associated with username, in forms where such input doesn't have the `type="text"` attribute set explicitly.

Example of affected form:
```html
<form action="/login_check" method="post">
    <input type="hidden" name="_csrf_token" value="XXX" />
    <div class="form-group">
        <label for="login_username">Username</label>
        <input class="form-control" id="login_username" name="_username" required="required">
    </div>
    <div class="form-group">
        <label for="login_password">Password</label>
        <input class="form-control" id="login_password" name="_password" type="password" required="required">
    </div>
    <button type="submit" class="btn btn-primary btn-block">Login</button>
</form>
```

Changing 
`<input class="form-control" id="login_username" name="_username" required="required">` 
to 
`<input type="text" class="form-control" id="login_username" name="_username" required="required">`
makes the extension behave as expected.

## Current Behavior
In provided example, KeePassXC icon appears near `password` input, instead of `username`. After accepting provided login information, only password is filled.

![image](https://user-images.githubusercontent.com/6976458/66819087-a5c9fe00-ef3e-11e9-8648-0daa0944a04f.png)

Mapping form fields manually doesn't help - still only pass is filled.

The only way to fill username is through the context menu action: `Fill Username and Password`.

## Possible Solution
I'm pretty sure this is a regression, as it was working completely fine couple days/weeks ago.

## Steps to Reproduce (for bugs)
Use provided HTML code for repro - can't link anything online. But one of the affected websites where I've experienced this problem uses https://www.adminer.org v4.7.3

## Debug info
KeePassXC Version: 2.4.3
KeePassXC-Browser Version: 1.5.2
Operating system: Linux
Browser: Chrome and Firefox (tested both, same behavior)

**Comment by varjolintu** [comment]
This might be a regression yes. A lot of big changes have been merged recently. The extension should also include input fields without any type.

Trying to solve the issue soon if I can reproduce it.

**Comment by varjolintu** [comment]
Aaand.. it's fixed.

**Comment by Talv** [comment]
Awesome, thanks!

Just tested and can confirm that this indeed fixes the issue.

![image](https://user-images.githubusercontent.com/6976458/66823498-b0889100-ef46-11e9-8311-a1f44a0c7fac.png)
