### ISSUE TITLE
Chrome plugin - Most time displaying errors: no logins found/ failed to save

### ISSUE THREAD

**Issue by lethefrost** [keepassxreboot/keepassxc-browser#639]
## Expected Behavior
Just as expected it should auto-fill the fields, or, when I manually log in/ create an account to a website whose data are not currently saved in database, it should save them into the database

## Current Behavior
However most time it just displays "errors: no logins found" or it cannot save these data to database, no matter I use hotkey like ⌃⇧U or mouse click the icon on field. I am sure that keepassXC is opened and unlocked when I do so, and the icon of browser plugin is green, instead of grey. How could things like these happen? I didn't change the default settings concerning authorizing or connecting, in neither keepassXC nor its browser plugin. Very rarely, in keepassXC it shows a pop-up dialog box, which asks me whether to authorize the website to get data, after confirming it, data are successfully auto-filled into the website fields. I also encountered cases that do not ask me for confirming but still works well in filling data, as long as keepassXC is unlocked(I guess case like this is the normal and perfect behavior)... But most time, if the dialog box unluckily doesn't show up, it just shows the error....

Is there anything wrong with my operation and usage? It must be a well-refined app because it has been developed for such long time and has good reputation. However, for me, from these days using I just felt it doesn't work at all... I therefore tend to believe it is my fault mistakenly using it in wrong way. So, I apologize sincerely for disturbing if it is not a bug and could you please show me the correct thing to do? Thank you so much!

## Possible Solution
I didn't find a way to steadily solve this situation but I found that after deleting all cookies and restart Chrome it magically works. I don't know how long it can last for this time.

## Steps to Reproduce (for bugs)

1.I can't tell a way to reproduce it... It just happens...
2.
3.
4.

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.2
Operating system: MacIntel
(for more details, I just updated the OS to 10.15 Catalina... Does it matter when considering the behavior of keepassXC?)
Browser: Chrome/Chromium 77.0.3865.120

**Comment by varjolintu** [comment]
I'm not sure about possible Cataline bugs, but please check the following:

1. Your database is opened and _associated_ with the extension, meaning you have used the Connect button for create a key pair.
2. Make sure the entry URL in KeePassXC is correct. This means the scheme must match by default, so `http://www.example.com` differs from `https://www.example.com`.
3. Make sure that the entry URL is correct, meaning if the login URL has some subdomains, you can match all the subdomains using `https://example.com`, so using just the hostname after the scheme.
4. Database must be **open** and **associated** with the extension before any data can be retrieved or saved/updated.

**Comment by lethefrost** [comment]
> I'm not sure about possible Cataline bugs, but please check the following:
> 
> 1. Your database is opened and _associated_ with the extension, meaning you have used the Connect button for create a key pair.
> 2. Make sure the entry URL in KeePassXC is correct. This means the scheme must match by default, so `http://www.example.com` differs from `https://www.example.com`.
> 3. Make sure that the entry URL is correct, meaning if the login URL has some subdomains, you can match all the subdomains using `https://example.com`, so using just the hostname after the scheme.
> 4. Database must be **open** and **associated** with the extension before any data can be retrieved or saved/updated.

Thank you for your reply, and I double checked what you mentioned. I am now pretty sure these requirements are met. Extension is connected to KeepassXC, database is opened and KeepassXC is unlocked. http and https difference is always paid attention to.  :( I am sad

**Comment by varjolintu** [comment]
Database is opened, but is it _connected_ to the extension? Meaning you have pressed the _Connect_ button from the popup or the extension settings page, and your database shows in the _Connected Databases_ tab?

**Comment by lethefrost** [comment]
> Database is opened, but is it _connected_ to the extension? Meaning you have pressed the _Connect_ button from the popup or the extension settings page, and your database shows in the _Connected Databases_ tab?
> 
> Being associated means this.

Yes it is connected. I noticed the icon turns green and every time for ensuring it is connected, I do it manually. The extension popup said it KeePassXC browser is connected to KeePassXC and has been configured by identifier below: xxxx....

Thanks!

**Comment by varjolintu** [comment]
If you still have the problem details would be needed:

- What's the site URL you are having the problem?
- What's the entry URL for that site?

**Comment by lethefrost** [comment]
> If you still have the problem details would be needed:
> 
> * What's the site URL you are having the problem?
> * What's the entry URL for that site?

Yes I still have this problem. It's not for any specific website, it occurs on every site. Cannot read or write in the database... for example, for github I manually add the entry `https://github.com/` but it still shows no logins found.

**Comment by varjolintu** [comment]
This doesn't sound normal at all. Only thing that could help is for you to debug the extension's background script `keepass.js` and see if the requests are sent properly, and response is received normally.

**Comment by varjolintu** [comment]
I would also suggest trying to reinstall the extension.

**Comment by lethefrost** [comment]
> I would also suggest trying to reinstall the extension.

Sorry for the late reply...
I am so confused. I reinstalled the extension for several times and this situation has not improved. hmm... Some weird cases happened, and I cannot figure out why or make sure they steadily work. But so far it looks like every time after I clean the caches, cookies...etc. of chrome(and caused chrome log out) or I restart my OS, the extension works for a time period. Some time later then, it breaks down again.... 

I can't find the `keepass.js` file... Is it the correct path for the extension? `/Users/***/Library/Application Support/Google/Chrome/Default/Extensions/oboonakemofpalcgghocfoadofidjkkk` I find under this folder with a long name, there are 2 sub folders, named respectively `1.5.3_0` and `1.5.2_0`. Are these different version of the extension? Is it safe to remove 1.5.2_0?

**Comment by varjolintu** [comment]
1.5.3 is the latest version. I'm not sure why the older version is kept.

For "finding" `keepass.js` see https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

**Comment by lethefrost** [comment]
> 1.5.3 is the latest version. I'm not sure why the older version is kept.
> 
> For "finding" `keepass.js` see https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide#4-debug-the-extension-itself

Thank you for all the time it takes... I am so confused and don't know why, but eventually it magically works, though I haven't done anything since then...
