### ISSUE TITLE
Making a connection to a copied database fails

### ISSUE THREAD

**Issue by varjolintu** [keepassxreboot/keepassxc-browser#640]
## Expected Behavior

1) Two databases are open in KeePassXC, and the second one is a copy of the first
2) Connect the first one to the extension
3) Connect the second one to the extension

## Current Behavior

1) Two databases are open in KeePassXC, and the second one is a copy of the first
2) Connect the first one to the extension
3) Second connection fails. Connect button doesn't do anything.

## Possible Solution

Database hashes are calculated using root group UUID. A copy of a database doesn't change this UUID, so the database hash calculated by the extension stays identical. We need to find a way to know if a database is a copy without breaking the hash calculation.

The only workaround for this is to make a fresh database and copy entries to it.

## Debug info

KeePassXC - Any
KeePassXC-Browser - 1.5.2
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by schlimmchen** [comment]
Interesting. This is the exact reason I created a new database which lead to #647 in the first place (was going to split a database into two). So +1 on this.

If you are going to try to associate the two databases with the browser extension, you'll first need to open and unlock them first. Maybe that's the moment in which KeePassXC should ask the user whether or not it should generate a new root UUID for the duplicated database?

Of course, the copy is still shown as "connected" if the user only opens the copy and tries to associate it with the browser, because it is indistinguishable from the original.

**Comment by varjolintu** [comment]
In my opinion generating a new root UUID doesn't sound like a solution. It definitely wouldn't pass the "Grandma test". Identifying the database should be done in the background without any further user interaction.

Still, your suggestion could work.

**Comment by schlimmchen** [comment]
I understand and agree! Let me point out though, that this is not a "Grandma" kind of use-case :stuck_out_tongue: :wink:

Let's assume the user created a copy of the database using a file system explorer. If the file contents are identical, you'll have to look at file meta-data. Doing that opens a huge can of worms, given that KeePassXC is portable and that OSes and even file systems and even options influence how this and that meta-data is handled.

I am curious what your approach eventually will be.

**Comment by varjolintu** [comment]
I was thinking in what point KeePassXC should ask for the UUID update, because it cannot happen anytime. The following solution could work:
1) Add database hash to `database-unlocked` message sent by KeePassXC
2) If two `database-unlocked` messages are received with identical hashes (this cannot happen if you don't have duplicates, or if you lock -> unlock), update a state variable that will pass a `duplicate: true` parameter to the association request when needed Otherwise put the state to false.

**Comment by schlimmchen** [comment]
Allow me to point out the following, which might help to shape a solution:

The browser extension might not forever be the only product which must identify databases through the proxy (maybe it already is not?). Hence I think that the browser extension is the wrong place to address this issue. Future products would have to solve this problem again.

Maybe a global and more aggressive approach is better suited? The root UUID of a database should play a more prominent role, i.e., be displayed prominently in the Database Meta Data section of the Database Settings dialog. Maybe there should be a "Regenerate" button next to the UUID field of the root group Edit Dialog. The Save-As Dialog could have an option to save with a new UUID.

And finally, KeePassXC could prohibit opening two databases with the same root group UUID. After decrypting the database and before the database is made available through the proxy, there could be a check which tests for opened databases with the same root group UUID. If that were the case, KeePassXC could prevent loading the database, explain the situation to the user and offer to re-generate the root group UUID.

This way all current and future users are guaranteed that no more than one database with a particular root group UUID is loaded at a time, which makes this problem obsolete for the browser extension in particular.

Regarding the "Grandma test": If grandma manages to externally copy a database file and open it in a new tab while the original was unlocked in the previous session, grandma should be prepared to press the "OK" oder "Yes" button :wink:

**Comment by varjolintu** [comment]
I agree these steps would indeed work:
- If two databases have same root group UUID, generate a new one for the second
- Make a button/option to renegenerate the UUID manually

In this way grandma's will be happy. And no changes in the extension is needed.

**Comment by gxfgbo** [comment]
I was recently tripped up by this bug after splitting a DB into two. Splitting a DB seems like a sensible use case to me. I can also see a scenario in which an archived copy of a DB might want to be opened at the same time as a current copy, so a hard block of opening DBs with a common UUID isn't something that would be ideal.

Combining a few points from other suggestions above and expanding, a solution could be:
- Present a keepassxc warning if two open DBs have the same UUID
- Allow the user to generate a new UUID and update the newer of the two DBs upon request.
- lLnk out to a newly created FAQ entry about how to properly clone/split a DB to avoid the duplicate UUID (or other) issues
- Perhaps create a collection of "Database Operations" functions to group the existing Merge/Import/Export functions with new Split and Clone functions.
- Enhance the error code returned to keepassxc-browser to indicate duplicate UUIDs if encountered.

**Comment by droidmonkey** [comment]
The split and clone options will be taken care of by the "Export Group" feature that is requested on another issue. Its the most robust method and avoids the bad practice of copying the kdbx file and deleting unwanted entries.
