### ISSUE TITLE
Cannot create new entries on chromium/catalina

### ISSUE THREAD

**Issue by janlimpens** [keepassxreboot/keepassxc-browser#643]
In macOS Catalina, I cannot create new entries. Could be just me, could be some new security feature.
Maybe some else could try to confirm?

I am using the Brave browser (based on Chromium and the extension is from the Google chrome store). The message is that new data cannot be saved in a locked database. 
However, the database at this point of time is unlocked.

**Comment by varjolintu** [comment]
Is the database associated (meaning connected to the extension)?

**Comment by janlimpens** [comment]
My mistake! Somehow the kdbx file just had messed up permissions. Sorry, should have checked that before posting here.
