### ISSUE TITLE
Pasting OTP behind password, it replace pw instead to append to it

### ISSUE THREAD

**Issue by mhbacks** [keepassxreboot/keepassxc-browser#648]
## Expected Behavior
On some devices, i must enter password and otp in password field concatenated. When i choose the correct account, i click at the position to fill otp and paste the otp manually with shift + control + t behind it. In password field, the password and otp is present in password field

## Current Behavior
When i paste the otp, the password is removed and the otp is filled in

## Possible Solution
let the field, where the otp is filled in untouched and insert otp at cursor possition only

## Steps to Reproduce (for bugs)

1. On login page choose account, that the credentials are filled in the correct fields
2. Position cursor behind password
3. paste otp with shortcut

## Debug info

KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.3
Operating system: Mac - Only Tested it on Mac
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Kind of rare use case.

**Comment by droidmonkey** [comment]
Very rare. You should just use Auto-Type for this scenario

**Comment by mhbacks** [comment]
What do you mean with Auto-Type? The automatic fill-in when i click on the keepass icon in username field?

**Comment by varjolintu** [comment]
Auto-Type is another feature of KeePassXC.

**Comment by mhbacks** [comment]
# Workaround wit Auto-Type

for those, who doesnt heared from Auto-Type before:

1. Under *Global Settings*, set a shortcut for *Auto-Type*
2. in the KeePassXC Account Entry
    1. Set under *Auto-Type* -> Activate Auto-Type for this entry
    2. Set special sequence `{PASSWORD}{TOTP}`
    3. Add a new Window Setting with a matching *Window Title*
3. In Browser choose user credentials
4. Set cursor in password field
5. Press global *Auto-Type* shortcut

**Comment by droidmonkey** [comment]
You can also bypass all that global setup (keyboard shortcut and window title) and press Ctrl+Shift+V to Auto-Type into the last selected window.
