### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by christophetd** [keepassxreboot/keepassxc-browser#65]
Hi, 

Is there a way to build the extensions from source instead of downloading them from the chrome / firefox store?

Thanks!

**Comment by phoerious** [comment]
You don't have to build anything. Just load the raw source folder (in develop mode) or pack it into a ZIP or CRX file. But note that KeePassXC won't work with your manually packaged version unless you add its extension ID to the native messaging manifest file.

**Comment by christophetd** [comment]
Gotcha, thanks!
