### ISSUE TITLE
Firefox & Chrome Autofill on wrong fields

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc-browser#653]
Hello,
I´m already logged in for example the CMS Joomla. On Login Screen all works.
But when I create/edit for example a User, there are also username & password fields and they gets autofilled but shouldn´t!
If I edit an existing user and I was not paying attention, userdata are overwritten. This is very bad.
In old KeePass2 I could specify, which field IDs oder Form IDs autofill should work or not.
I only can specify to ignore complete sites but also if I entered this site it is in Chrome and also Firefox not working. It autofills every time this fields...

**Comment by varjolintu** [comment]
Anything will be not autofilled unless autofill is enabled in the extension settings, or you click the username field icon, or use the autocomplete menu.

If you update an existing user, of course the data is overwritten. You can revert the changes using the history feature in KeePassXC.

If you want to manually select what fields will work with the extension, you can use the extension popup and select _Choose custom login fields for this page_.

**Comment by varjolintu** [comment]
Please suggest reopening the issue if the problem still persists.
