### ISSUE TITLE
Integration in brave not working - installed from ppa

### ISSUE THREAD

**Issue by LordJABA** [keepassxreboot/keepassxc-browser#654]
The plugin didn't work so i updated from ubuntu provided version to 2.5.0 from your ppa.
The browser blugin still shows "can't connect to keepassxc" message
Tried to use your "snap" script - but no effect.

## Steps to Reproduce (for bugs)
1. add ppa from downloads site
2. install keepassxc
4. enable browser integration in keepassxc
3. install keepassxc-broweser plugin
4. can't connect to keepassxc

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Kubuntu 19.04
Browser: Brave 0.70.121

**Comment by varjolintu** [comment]
The snap script doesn't help if you browser is installed via snap. It's only for the snap version of KeePassXC.

**Comment by LordJABA** [comment]
Sorry for that - i tend to think better after I file a bug report.
SOLVED: https://github.com/keepassxreboot/keepassxc-browser/issues/541#issuecomment-519403279

> Removing
~/Library/Application\ Support/BraveSoftware/Brave-Browser/NativeMessagingHosts/org.keepassxc.keepassxc_browser.json
solved the issue for me.
