### ISSUE TITLE
Every site requests access to one specific unrelated password entry

### ISSUE THREAD

**Issue by amc2002** [keepassxreboot/keepassxc-browser#657]
## Expected Behavior
Navigating for the first time to a site with login credentials, KeePassXC-browser asks permission to access the related password entry.

## Current Behavior
No matter which site I visit, KeePassXC-browser always asks for permission to access my Roku account password. This happens whether or not I select the "Remember" checkbox. I updated to the new KeePassXC today, but the issue is still occurring. 

## Possible Solution
Will probably end up deleting this entry and re-adding it, but wanted to see if there's any debugging I can do for the team first. 

## Steps to Reproduce
Don't think I can reproduce, except on my system. 

## Debug Info
KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Win32
Browser: Chrome/Chromium 77.0.3865.120

Qt 5.13.1
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18362

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment]
What's the entry URL? I've never heard this kind of case before.

**Comment by droidmonkey** [comment]
Remove all asterisks from the url of that entry and make sure the url field doesn't contain multiple URLs.

**Comment by amc2002** [comment]
Doesn't matter what the entry URL is. Any URL I visit I get the request to allow access to the Roku entry. Then both entries are available to be put in the field via the selection. 

@droidmonkey - yes, first think I did was make sure that entry was clean. 
![Untitled4](https://user-images.githubusercontent.com/14333663/67698401-ae7bf480-f980-11e9-87b2-1b0fd7e53e42.png)

**Comment by varjolintu** [comment]
Does it help if you go Properties page of the entry and delete the Plugin Data that holds the KeePassXC-Browser Settings?

**Comment by varjolintu** [comment]
Also, do you happen to have some Roku-related browser extension in use that could possible inject some content from roku.com to every page you visit?

**Comment by amc2002** [comment]
There are two entries there, and it only allowed me to delete one. The "LAST MODIFIED" field could not been deleted.

Deleting the other entry did not resolve the issue.

**Comment by amc2002** [comment]
Just wondering why this issue was closed? If you're not interested in fixing it, that's fine, it could very well be some local corruption. I can delete the entry, remove and reinstall the plugin if you all have better things to work on. I totally understand.

**Comment by amc2002** [comment]
> Remove all asterisks from the url of that entry and make sure the url field doesn't contain multiple URLs. This has been reported over on the KeePassXC issue board already.

I did look on that issue board but didn't see my issue. The URL field in my case does not contain multiple URL's. The entry is totally clean.

**Comment by varjolintu** [comment]
The only explanation I could think for this is that you have some entry with a `KP2A_URL` attribute that holds the roku URL.

**Comment by amc2002** [comment]
It's literally every site I visit and attempt to log in to for the first time (before selecting the "Remember" box). But then even when I have the remembered box selected, the Roku entry keeps coming up, while the "Remember" seems to be remembered for the real username/password combo.

**Comment by droidmonkey** [comment]
So does the Roku entry have ANY url information? Are you sure that's the only one? It's incredibly hard to diagnose your specific issue with little bits of information, unfortunately.

**Comment by amc2002** [comment]
> So does the Roku entry have ANY url information? Are you sure that's the only one? It's incredibly hard to diagnose your specific issue with little bits of information, unfortunately.

I know, I apologize I can't offer more help. I just didn't know if it might be something obvious or if there was something else I could do. 

The Roku entry is the only one with the issue. The URL information is simply https://www.roku.com but I switched it to https://roku.com hoping if perhaps I changed it, it would stop coming up. 

There is nothing unusual at all about this entry. I looked in the other fields (Advanced, Properties, etc.) and everything is pretty blank.

**Comment by droidmonkey** [comment]
If you change the url to a different domain (eg, https://notroku.com), does the problem go away?

**Comment by amc2002** [comment]
Just tried it. No, it does not go away.

**Comment by droidmonkey** [comment]
Try searching your db for `url:roku` to see if any other entries pop up. Also make sure you refresh the page to do a re-polling of credentials from kpxc.

**Comment by amc2002** [comment]
There is only one other Roku entry - for the forums. It's not the one coming up. 
I refreshed the page, even cleared my browser and restarted Windows. The Roku prompt still comes up for every password field, no matter the URL. Is there something else I can enable to get more debugging info?

**Comment by Genji-tech** [comment]
I have the same problem and it began with the update to KeepassXC v2.5.0 -- the same database worked fine before.  I can provide a KeepassXC DB with three sample entries that exhibit the weird new behavior -- the Firefox browser plugin asks for access to these three for EVERY new website, and always uses one specific login. Chrome only asks for and uses the specific login 

That one specific entry has:
- URL: https:///www.usaa.com
- Nothing in the "Advanced" tab
- Nothing checked and no entries in the Browser Integration tab
- No plugin data in the Properties tab (until you grant access to any of the many webostes that ask for it)

**Comment by droidmonkey** [comment]
Take out a slash from the url

**Comment by amc2002** [comment]
Yes, I just noticed that my home machine hadn't updated to 2.5.0 yet and I wasn't getting the issue on that machine.

Sure enough, after update, having the same issue with my home machine as with my work machine.

**Comment by Genji-tech** [comment]
Doink!  Yeah, removing the extra slash from my URL does stop the problem from happening. Not sure how I missed that.... thank you

**Comment by amc2002** [comment]
Taking a clue from @Genji-tech - I completely removed the URL from the Roku entry, saved the database, confirmed the prompt for all websites was gone. Re-added the entry, saved database, still gone. So emptying the URL field and re-entering it works as a workaround. I'm good here - please feel free to close ticket if that's acceptable as a "fix." Thanks!

**Comment by droidmonkey** [comment]
We have an issue on the KeePassXC main issue board to track flaky url matching in 2.5.0.

**Comment by varjolintu** [comment]
@droidmonkey I will look into it. We should do URL validation both in the edit entry GUI and during the matching.

**Comment by pvredeveld** [comment]
Had the same issue  here. The solution pointed me to an invalid url entry (https:://mijn.jiba.nl) Note the double :: After correcting this the problem was gone. Thanks.
