### ISSUE TITLE
[Question] Why is auto-fill considered insecure?

### ISSUE THREAD

**Issue by christophetd** [keepassxreboot/keepassxc-browser#66]
The settings state `Warning! Using auto-fill is not safe. Use at your own risk`. Could you elaborate?

Thanks a bunch for this extension, it's absolutely awesome.

**Comment by droidmonkey** [comment]
There are proven cases of ad networks deploying fake hidden credential fields to steal your username and password. Disabling auto fill ensures user interaction is required to use your credentials.

**Comment by mehrdadn** [comment]
Could this be relaxed when *"Automatically retrieve credentials"* is disabled?
It seems kind of pointless in that case there has already been user interaction.

**Comment by droidmonkey** [comment]
I can agree with that because to me it is cumbersome to click basically three times to fill the fields.

**Comment by runiq** [comment]
I think it'd be a good idea to put [this information](https://github.com/keepassxreboot/keepassxc-browser/issues/66#issuecomment-372055984) directly after the "Use at your own risk" warning, to give it some weight.
