### ISSUE TITLE
Automatically unlock multiple databases by manually unlocking a single database

### ISSUE THREAD

**Issue by ReallyReally17** [keepassxreboot/keepassxc-browser#660]
In order to make it convenient when working with a set of Databases for a period of time - I should not have to constantly re-unlock the same databases every time I boot the computer.

## Expected Behavior
Upon unlocking database 1, a trigger uses passwords stored in database 1 to unlock databases 2 and 3.

**Comment by droidmonkey** [comment]
Uh no thank you. The whole entire point of our application is that your data is fully encrypted at all times except when it is in RAM while you are using the application.

**Comment by ReallyReally17** [comment]
I don't understand what part of my description means that the data is not fully encrypted at all times except when it is in RAM.

It seems to me that it should only involve automatically decrypting databases when the user logs in.

**Comment by varjolintu** [comment]
Opening databases automatically without needing the password and/or keyfile is never going to happen.

**Comment by phoerious** [comment]
You cannot encrypt without a key, which in the case of KeePassXC is your master password. We relax this concept a bit on macOS with TouchID, but only as long as the user does not lock his session.

**Comment by ReallyReally17** [comment]
What if the databases are automatically decrypted using passwords that are held in another database? Everything still has a password in this case.

**Comment by phoerious** [comment]
You can already do that.

**Comment by ReallyReally17** [comment]
how?

**Comment by droidmonkey** [comment]
What operating system are you using. The answer is dependent on that information

**Comment by ReallyReally17** [comment]
Windows 10 1903

**Comment by droidmonkey** [comment]
I don't think there is a way to get credentials from Windows credential manager from the command line. I searched and came up empty.

**Comment by ReallyReally17** [comment]
Can it be done in PowerShell?
https://gallery.technet.microsoft.com/scriptcenter/Accessing-Windows-7210ae91

**Comment by droidmonkey** [comment]
Sure you can use that!

**Comment by ReallyReally17** [comment]
I still don't know what I'm supposed to be doing or why I need to involve the Windows credential manager. 

In a previous post, Phoerious said that it is possible, using KeePassXC, to automatically unlock multiple databases when one database is manually unlocked. I assume this would require some sort of trigger and configuration, but I don't see where I can do this in KeePassXC. 

If this is possible, how can I accomplish this?

**Comment by droidmonkey** [comment]
This discussion is so confusing! Auto unlocking other databases when you unlock one is called auto open.

**Comment by ReallyReally17** [comment]
That's exactly what I needed. Thank you!
