### ISSUE TITLE
Urls with an asterix will be used on all websites

### ISSUE THREAD

**Issue by NoXPhasma** [keepassxreboot/keepassxc-browser#661]
## Expected Behavior
Asterix in urls should be used as wildcard only for that particular domain. This was the behaviour before the last update.

## Current Behavior
When an Url has an asterix as wild card ( i.e. `htpps://*.test.com`) it brings the Authorization window up on every website which has a login form. Showing all logins having an asterix in the URL.

I'm not sure if the Update of the Browser extension or KeePassXC itself triggert it, but since it only affects the Webextension I post it here.

## Possible Solution

Revert that behaviour.

## Steps to Reproduce (for bugs)

1. Create a new entry with an asterix in the url ( i.e. `htpps://*.test.com`), does not need an actual available url.
2. Go to a webpage with a login form

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3 (21-10-2019)
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
Duplicate issue
