### ISSUE TITLE
Extended Java / Javascript Funtionality for Websites Like This....

### ISSUE THREAD

**Issue by XyjpcpXNF6UGaQ** [keepassxreboot/keepassxc-browser#663]
My local library website (online catalogue) has a particularly nasty interface that cannot be made to work with KeepassXC (even using Choose custom fields for this page - which, I admit, is largely incomprehensible in the way that it works with pages or, more accurately, does not).

The two screenshots show the usual login process and the page itself is located here:

https://wales.ent.sirsidynix.net.uk/client/en_GB/gwynedd_en/?#

Ideally KeepassXC should recognise the https://wales.ent.sirsidynix.net.uk page and populate the popup fields, but it does not and it does not appear to be possible to make it do so, either.

I also have no idea how a fix would be implemented for this, as I suspect that there is some kind of Java protection in place to prevent anything but keyboard interaction with the login popup.

![llyfrgell](https://user-images.githubusercontent.com/57239348/67994673-51ad6200-fc3e-11e9-9dd6-4c8ed6e23e7d.png)

![llyfrgell_login](https://user-images.githubusercontent.com/57239348/67994672-51ad6200-fc3e-11e9-8d04-9b0e6599985a.png)

**Comment by varjolintu** [comment]
That's a nasty site. If your entry URL is `https://wales.ent.sirsidynix.net.uk/` you can fill the credentials to that login popup using the context menu or keyboard shortuct as a workaround.

**Comment by XyjpcpXNF6UGaQ** [comment]
Thanks for your help with this. Unfortunately the keyboard cannot be used to fill this in: the fields are detected on the main page **only**, - not those on the popup; hence my request (KeepassXC is not currently able to handle these page configurations).

**Comment by varjolintu** [comment]
Ok then. Reopening this.

Problem with that popup is that after it's launched, the iframe doesn't have any input fields, so none are regognized. They appear only after a small delay. CSS animation waiting (or something else) is probably needed.

**Comment by XyjpcpXNF6UGaQ** [comment]
If that would fix the problem that would be great ...and I guess that would also mean that there would be no need to use the keyboard, either, seeing as Keepass itself should recognise the fields once they are detected following the CSS animation waiting.

**Comment by varjolintu** [comment]
I took a look at this again and it seems the iframe is loaded from another domain, and content scripts won't work properly with cross-domain frames.
