### ISSUE TITLE
Cannot connect to keepassxc on my device

### ISSUE THREAD

**Issue by kineita** [keepassxreboot/keepassxc-browser#664]
## Steps to Reproduce (for bugs)

Always notify Key exchange was not successful

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Make a proper issue with good details.

**Comment by kineita** [comment]
I'm sorry for this problem, I saw the bug because I installed my browser from snap package. Many thanks you again, I love this app :D
