### ISSUE TITLE
Fill failed

### ISSUE THREAD

**Issue by AriaLyy** [keepassxreboot/keepassxc-browser#665]
## Steps to Reproduce (for bugs)
Cannot be filled on this site
site：https://secure.assrt.net/user/logon.xml

I have created an account in keepassxc
![image](https://user-images.githubusercontent.com/10437293/68065901-d2697c80-fd6a-11e9-885b-0894ada5cac5.png)

But it can't be filled on this site.
![image](https://user-images.githubusercontent.com/10437293/68065908-e0b79880-fd6a-11e9-99c3-1ab25e4d28aa.png)

## Debug info
KeePassXC - 2.5
KeePassXC-Browser - 1.5.3
Operating system: Mac
Browser: Chrome

**Comment by varjolintu** [comment]
This happens because we exclude XML files in the extension manifest. That restriction can be now removed because we are no longer using jQuery in the content scripts.

**Comment by AriaLyy** [comment]
goof👍🏿
