### ISSUE TITLE
Easier way to connect a new extension to KeePassXC

### ISSUE THREAD

**Issue by belaviyo** [keepassxreboot/keepassxc-browser#667]
As of version 0.4.3, my [KeePassHelper](https://addons.mozilla.org/en-US/firefox/addon/keepasshelper/) extension supports the native messaging to be used with KeePassXC. Currently, I need to ask the users to edit the manifest file manually which is inconvenient. Would it be possible to have the extension id in your manifest file or alternatively allow the user to insert the ID in the UI and the manifest files get updated automatically? For instance, we can have a checkbox in the browser integration tab to allow KeePassHelper access.

Note that since there are many cases where the manifest file might get overwritten by KeePassXC, the one-time manual modification of all manifest files is not an option.

**Comment by varjolintu** [comment]
Why do you need to use KeePassXC-Browser's manifest files? You can always create your own and use it to launch `keepassxc-proxy`. Or alternatively make your own proxy app.

Our manifest files only include one extra ID and that's already obsolete. We are not adding any ID's for other extension to the files.

**Comment by varjolintu** [comment]
Btw, your extension is linking to the older KeePassHTTP extension. I recommend using: https://addons.mozilla.org/en-US/firefox/addon/keepasshttp-connector/
