### ISSUE TITLE
URLs with ports are always suggested

### ISSUE THREAD

**Issue by virhonestum** [keepassxreboot/keepassxc-browser#669]
## Expected Behavior

An entry with the URL set to `example.com:1234` should only be suggested on `example.com` or even `example.com:1234`.

## Current Behavior

The entry will be suggested on any website you visit.

## Steps to Reproduce (for bugs)

1. Create an entry and add a url wich also contains a port.
2. Visit any website which has login fields.
3. The entry will be suggested, no matter what website you're on

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Win32
Browser: Mozilla Firefox 70.0

**Comment by varjolintu** [comment]
This already has a fix coming.
