### ISSUE TITLE
Keep site interactible while choosing custom login fields

### ISSUE THREAD

**Issue by chaptergy** [keepassxreboot/keepassxc-browser#670]
## Expected Behavior

Many websites have an SSO login flow, so the email input is on a different screen than the password input. I should be able to move along in this flow when I choose custom login fields.

## Current Behavior

The site becomes non interactable, which makes it impossible to set both username and password fields for autofill.

## Possible Solution

Maybe add a button to the window which toggles between the input selection mode and the normal webpage view?

## Steps to Reproduce (for bugs)

1. Go to amazon.com, google.com or any website which uses an SSO login flow
2. Open the KeePassXC browser extension and click on "choose custom login fields"
3. Try to select both the right username as well as the right password field

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Win32
Browser: Mozilla Firefox 70.0

**Comment by droidmonkey** [comment]
You mean split login flow, username and password are on different screens. When yo see that just click on the "setup single login page for this domain" button in the pop window for the extension. Then to have to refresh the page.

**Comment by virhonestum** [comment]
That's exactly what I mean, yes.
And what do I do after I enabled "setup single login page for this domain"? It seems, that nothing has changed on the page, even after multiple refreshes, I am still not prompted to select a username on `amazon.com`. To be honest, apparently I don't really understand the "Username-only Detection" flag? I thought it was for websites where you don't have a password at all, just a username.

**Comment by virhonestum** [comment]
Ohh, okay, I then need to select the custom login fields, I got it. Thanks! But maybe then change the text to something a little more clear? 
Currently it says 

> Only a single username field was detected. Add the URL to Site Preferences with Username-only option enabled?

Maybe change it to something like this

> Only a single username field was detected. If the password field is on a separate page, add a Username-Only option to this site.

**Comment by droidmonkey** [comment]
It should do all this for you. There is a bug in the username detection button, and I thought it was just me. When you click that button it should do everything necessary to make it work.

**Comment by varjolintu** [comment]
@droidmonkey Hmm? What bug are you talking about? Have I missed something?

**Comment by droidmonkey** [comment]
When clicked it does not rescan the page for the username field and add the keepassxc icon as appropriate. To use the page after adding it requires a page refresh.

**Comment by Tremolo4** [comment]
I'm having this exact problem (on 2.6.2). I'm unable to find the "setup single login page for this domain" button.

**Comment by varjolintu** [comment]
Again: sites with split login pages work you add the site URL to Site Preferences tab in the extension settings and enable _Username-only Detection_. Most common sites are supported automatically.

If you open the extension popup from the toolbar icon, there's also a button in the bottom that allows you to setup this with a single click if a single username field is detected.

**Comment by Tremolo4** [comment]
Maybe I'm misunderstanding.

My problem is as follows: I have enabled the username-only option for amazon.co.uk, because amazon uses split login. KeePassXC-Browser extension now detects the search bar as a username field. I want to prevent that. To that end, I attempted to manually select the correct input fields using "Choose custom login fields". However I'm unable to select both the username and the password field of the amazon login pages with this (only one or the other).

**Comment by varjolintu** [comment]
@Tremolo4 For now you'll have to disable the Predefined Sites from the extension settings as a workaround. I've already fixed the problem and plan to release 1.7.3 asap. It's an annoying bug.

**Comment by Tremolo4** [comment]
I see, thanks a lot!

I wonder if there could exist a website where we would need this functionality though. That is, being able to customize the login fields for split-login sites (that are not pre-defined (?)).

**Comment by varjolintu** [comment]
The only way to "Customize" these is to add the site manually to the Site Preferences tab and enable _Username-only detection_. Under the main tab you can see _Predefines sites_ settings with a site list. If there's a problem with a predefined site, it's easiest to disable the option for now. But 1.7.3 will definitely fix most of the annoyments.

**Comment by varjolintu** [comment]
This is now under work. Trying to make it for 1.7.10.

**Comment by varjolintu** [comment]
Anyone who wants to help and has a site with problems, please test the branch where https://github.com/keepassxreboot/keepassxc-browser/pull/1390 is created from. It would help a lot to catch any remaining problems with the new implementation before the new release. Thanks :)
