### ISSUE TITLE
Credentials saved from Firefox doesn't require confirmation

### ISSUE THREAD

**Issue by rapenne-s** [keepassxreboot/keepassxc-browser#672]
## Expected Behavior
On a fresh 2.5.0 install (tried on OpenBSD 6.6 and Windows 10 with Firefox 70.0 and plugin).
I start keepassxc to create a database and I enable browser integration.
Connecting keepassxc and firefox plugin is OK.

I visit a page, say https://github.com/login
I fill my username / password and right click in the field and save credentials in Keepassxc. Credentials are correctly saved.

If I go back to https://github.com/login and that I click the keepassxc icon, the fields are filled with my credentials, without any prompt/confirmation and doesn't reflect what the user guide says in 5.1.2 bullet 7 showing a "KeePassXC-Browser Confirm Access" window.

If I add the entry manually from keepassxc, I'm prompted for confirmation when visiting the url.

My keepassxc.ini file contains this for the browser part

```
[Browser]                        
AllowExpiredCredentials=false
AlwaysAllowAccess=false
AlwaysAllowUpdate=false 
BestMatchOnly=false
CustomProxyLocation=
Enabled=true   
HttpAuthPermission=false                                                                                                                                                                                           
MatchUrlScheme=true                                                                                                                                                                                                
NoMigrationPrompt=false                                                                                                                                                                                            
SearchInAllDatabases=false                                                                                                                                                                                         
ShowNotification=true                                                                                                                                                                                              
SortByUsername=false    
SupportBrowserProxy=true
SupportKphFields=true  
UnlockDatabase=true 
UpdateBinaryPath=true      
UseCustomProxy=false 
```

## How to solve

I found one way to make keepassxc asks confirmation for every website:
Database => database settings => browser integration => forget all site-specific settings on entries

After this, I get the confirmation popup for every recorded site I visit. But if I add a new site, I never get the confirmation popup until I reset everything in the database.

After adding a new entry from Firefox, I tried comparing it with another asking confirmation, I see no difference between them (no new fields, checkboxes are identicals).

**Comment by droidmonkey** [comment]
The confirm access dialog is technically meant for entries that match the website url, but may not have originated from a relationship with the browser extension. This gives you the chance to deny access if necessary. Since you created the entry with the extension, it is logical that you want to use that entry with the extension, thus auto allow.

**Comment by varjolintu** [comment]
If you create an entry via KeePassXC, the permission will be asked when the page is loaded. Otherwise, just like said above.

**Comment by rapenne-s** [comment]
I'm fine with the explanation, but why isn't there any difference when checking at the entry?

If I allow an entry added manually, it gets the new property
```
KeePassXC-Browser-Settings = { "Allow":["github.com"], "Deny":[], "Realm":""}
```

Entries added from the web browser should have that entry too.

**Comment by varjolintu** [comment]
Entries added from the web browser does have that property set. I just checked it.

**Comment by rapenne-s** [comment]
> Entries added from the web browser does have that property set. I just checked it.

indeed, sorry for my confusion. I can confirm the same! I don't know why I was mistaken.
Thank you.

**Comment by varjolintu** [comment]
Glad everything is solved. Btw. last time I tried the extension with OpenBSD I was unable to debug anything via Firefox (using `about:debugging`). Does this still happen?

**Comment by rapenne-s** [comment]
> Glad everything is solved. Btw. last time I tried the extension with OpenBSD I was unable to debug anything via Firefox (using `about:debugging`). Does this still happen?

I'm not familiar with about:debugging but looking at Keepassxc extension I get a warning

> Reading manifest: Error processing version_name: An unexpected property was found in the WebExtension manifest.

The inspect button seems to works.

**Comment by varjolintu** [comment]
Thanks for the info. Closing this again.
