### ISSUE TITLE
Cant detect fields on Aliexpress.com

### ISSUE THREAD

**Issue by cr33dk1ller** [keepassxreboot/keepassxc-browser#673]
## Expected Behavior
Should detect username and password field on aliexpress.com

## Current Behavior
Field detection doesnt work on aliexpress.com, trying to define them manually doesnt work cause the correct boxes cant be selected.
I should note its been this way since I started using keepassxc extension more than 5 months ago.
I have no doubt this is because of the convoluted way Aliexpress has coded their website, its also exceedingly bloated.
Using context menu for entry still works and its how I will continue to login till hopefully KeepassXC-Browser can detect them.

## Steps to Reproduce (for bugs)
1. create a fake entry in database for aliexpress.com
2. open aliexpress.com login page
3. attempt "Choose custom login fields for this page"

## Debug info
KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Windows 10 Enterprise LTSC
Browser: Firefox 70.0.1 (64-bit)

**Comment by varjolintu** [comment]
This is already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/652. Just wait for the next release.

**Comment by cr33dk1ller** [comment]
thank you
