### ISSUE TITLE
Adding a new database connection deletes an existing connection

### ISSUE THREAD

**Issue by michelesr** [keepassxreboot/keepassxc-browser#674]
This issue seems to have been introduced recently, as in the past it was possible to have two database connections stored in the "Connected databases" section of the settings.

## Expected Behavior
It should be possible to add a new database connection without affecting the existing connections stored in the extension data.

## Current Behavior

Adding a new database connection deletes the existing connection. When having to deal with multiple databases, you have to add a new connection every time you switch to between each of them.

## Steps to Reproduce (for bugs)

1. Go to "Settings -> Connected Databases"
2. Add a database connection by pairing with KeepassXC. The connection should be displayed in the list now.
3. Add another connection to a different database, with a different identifier. Now both are displayed on the list.
4. Refresh the settings page and go back to the "Connected Databases" page: now only the latest connection is displayed, where the connection added initially has been deleted.

## Debug info

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Is your second database a clone/copy of the first one? Currently those won't work.

**Comment by michelesr** [comment]
No, they are two separate databases, which different password entries (a part for a small amount of them that are duplicated across both, for convenience, but I added them manually in both databases, I haven't copied from a database to another, so they're technically different entries, referring the same website domain)

**Comment by varjolintu** [comment]
I suggest that you try to remove all the databases from the _Connected databases_ list, as well forget all browser settings from KeePassXC's _Database settings_, and try it from the start. If that doesn't help, you can try to make a third new temporary database and try to add that one after the first or second one you are using. This way you could test if there's something weird in the first or second database.

**Comment by michelesr** [comment]
I tried removing everything and didn't help. However adding new empty databases seemed to work, as they are now all displayed in the "Connected Databases" section.

Does that mean that the two databases are in conflict with each other somehow? How can remove the conflict then?

**Comment by droidmonkey** [comment]
You need to give unique names to the connections

**Comment by michelesr** [comment]
They have unique names, but they conflict anyway.

**Comment by michelesr** [comment]
They're indeed having the same group id, how is this possible? :O

**Comment by michelesr** [comment]
Right... I've managed to fix this by creating a new empty database and use the merge from option to merge it with one of the old databases. Now the two databases have different root group id and I can add both of them to the browser extensions. Thanks for you help!

**Comment by f03el** [comment]
Exactly this problem has puzzled me for a long time. Great to finally find the reason!

**Comment by eicher31** [comment]
Thanks!
