### ISSUE TITLE
CIMBClicks.com.my login issue

### ISSUE THREAD

**Issue by cr33dk1ller** [keepassxreboot/keepassxc-browser#675]
## Expected Behavior
Autofill password / context menu insert for password field

## Current Behavior
KeepassXC-Browser doesnt detect the field is there, right clicking the field for context menu fill also doesnt work "Warning! Error: Unable to find a password field"

## Steps to Reproduce (for bugs)
1. Create fake entry for cimbclicks.com.my in database.
2. Go to https://www.cimbclicks.com.my/clicks/#/ and attempt to login
3. Username field will be detected but not password.

## Debug info
KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: Windows 10 Enterprise LTSC
Browser: Firefox 70.0.1 (64-bit)

**Comment by varjolintu** [comment]
Click the extension popup and use the Username-only option it suggests.

Alternative you can enter the URL to extension's Site Preferences and enable the Username-only option. But the popup does this automatically.

**Comment by cr33dk1ller** [comment]
> 
> 
> Click the extension popup and use the Username-only option it suggests.
> 
> Alternative you can enter the URL to extension's Site Preferences and enable the Username-only option. But the popup does this automatically.

username works ok, once entered i can click login, but now at the password screen is the problem, password field detection doesnt work

**Comment by varjolintu** [comment]
I tested the site and after it was added to the Site Preferences with Username-only detection enabled, both username and password field (after filling the username) worked just fine. Are you filling the password using the icon in the input field?

**Comment by cr33dk1ller** [comment]
> 
> 
> I tested the site and after it was added to the Site Preferences with Username-only detection enabled, both username and password field (after filling the username) worked just fine. Are you filling the password using the icon in the input field?

thank you very much for your help, turns out because i had long ago tried selecting specific fields manually, those settings were conflicting, once i deleted them it now works as expected.
