### ISSUE TITLE
keepassxc-browser suggest all user-password in the database since KeePassXC 2.5.0 upgrade  [Chrome]

### ISSUE THREAD

**Issue by kidpixo** [keepassxreboot/keepassxc-browser#679]
##  Expected Behavior
keepassxc-browser should suggest the user-password pairs matching current url.

## Current Behavior
Since KeePassXC 2.5.0 upgrade, keepassxc-browser suggest all user-password in the database.

I played with KeePassXC Browser Integration settings :

- Enabled: request to unlock the database if it is locked
- Enabled: Match URL scheme (e.g., https://...)
- Disabled: return only best-matching credentials

with no luck.

## Possible Solution
No idea.
Maybe the 2.5.0 changed something when retrieving the URL and keepassxc-browser didn't adapt ?

## Steps to Reproduce (for bugs)
1. upgrade KeePassXC to 2.5.0
2. open a website with login field
3. select login field
4. see the list of all your entries from KeepassXC

## Debug info

No error generated in the Javascript Console.

KeePassXC - 2.5.0
KeePassXC-Browser - 1.5.3
Operating system: MacIntel - macOS Sierra 10.12.6 (16G2136)
Browser: Chrome/Chromium 78.0.3904.97

**Comment by droidmonkey** [comment]
This is corrected in 2.5.1, which should be out tonight.

**Comment by kidpixo** [comment]
@droidmonkey this was fast , thanks 👍
