### ISSUE TITLE
Credential drop down select not shown on initial page load

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc-browser#68]
## Expected Behavior

After you press "Allow" from the credential pick list from KPXC the credential list should appear when you focus on the username/password field on the page.

## Current Behavior

The credential list does not appear unless you reload the page, press "redetect credential fields", or tab in/out.

## Possible Solution

Automatically perform a credential detection on the loaded page after KPXC sends credentials.

## Steps to Reproduce (for bugs)

1. Load a login page (https://twitter.com/login)
2. When the credential list appears, press Allow
3. Focus on the Username field
4. Nothing appears that lets you fill in the credentials

## General Info
KeePassXC fork - 2.3.1
keepassxc-browser - 1.0.1

Operating system: WIN
Browser: Chrome
Proxy used: YES

**Comment by varjolintu** [comment]
Well this is a tricky one.. the situation I saw with Windows (only with Windows) is that if the delay from the dialog response is too long the length variable from STDIN is zero, and after that keepassxc-proxy.exe just quits (no crash, it quits). I tried to put some breakpoints here and there but couldn't catch the exact point where it quits.

Can you confirm the keepassxc-proxy.exe quits in your situation too?

**Comment by droidmonkey** [comment]
There should be some form of a continuous heartbeat if you break the connection due to lack of input.

**Comment by varjolintu** [comment]
There's already a while loop that doesn't break until EOF is met (or running has stopped but that's not the case). I'll take a look at this later and try to figure out what exactly happens here.

**Comment by droidmonkey** [comment]
Yah, try not to put in magic delays and such to fix this... We control the protocol so let's make it robust.

**Comment by varjolintu** [comment]
I won't. This is an asynchronous method so STDIN shouldn't get EOF in any situation because this means the browser shuts the connection down. I confirmed that `onDisconnect()` hits with an unknown error. And this only happens with Windows.

**Comment by phoerious** [comment]
Has this been fixed?

**Comment by varjolintu** [comment]
Probably needs some more testing so let's reopen this.

**Comment by varjolintu** [comment]
Re-tested this. Everything works fine.
