### ISSUE TITLE
Autofill retrieves too many options

### ISSUE THREAD

**Issue by beingmrkenny** [keepassxreboot/keepassxc-browser#681]
## Expected Behavior

When clicking the little keepass logo (the one that appears in the username field) to get a list of possible login credentials, it should return the credentials that match the domain of the site you're on.

## Current Behavior

The list that comes back seems to include anything that vaguely resembles the domain. My workplace uses a lot of subdomains, e.g.

service.internal.example.com
anotherthing.internal.example.com
somethingelse.int.example.com

When I visit service.internal.example.com I only want the credentials for that exact subdomain. Currently it seems to be returning anything where the domain contains example.com — which in my case is nearly 30 different logins.

This only started happening when I upgraded the desktop app to 2.5.1.

## Possible Solution

If this is an intended feature, added to allow fuzzy matching on domains, please give the option to switch it off. In my use case it renders keepass ten times more annoying to use.

## Steps to Reproduce (for bugs)
1. Setup credentials for many subdomains on the same domain.
2. Visit one subdomain
3. Click keepass logo in username

## Debug info

No console errors.

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: MacIntel
Browser: Mozilla Firefox 70.0

**Comment by varjolintu** [comment]
This needs a fix to KeePassXC side, and I've already done that, plus an issue exists for this. You can try to enable the setting _Return only best-matching credentials_ from KeePassXC as a workaround.

**Comment by beingmrkenny** [comment]
Thanks @varjolintu, any idea when that might be released?

**Comment by varjolintu** [comment]
Not yet. Probably with KeePassXC 2.5.2 so it will have to wait a while.
