### ISSUE TITLE
I can not make a connection between keepassxc and keepassbrowser extension in firefox or chrome

### ISSUE THREAD

**Issue by bandi30** [keepassxreboot/keepassxc-browser#683]
KeePassXC - unknown
KeePassXC-Browser - 1.5.3
Operating system: Linux x86_64
Browser: Mozilla Firefox 70.0 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Please provide some details. What is your KeePassXC version? Are you using snap or the official PPA, or AppImage?

**Comment by burkemw3** [comment]
I am having the same issue. I am using KeePassXC v.2.5.1 via AppImage, with Firefox v70, and KeePassXC-Browser v1.5.3.

I can't remember if things broke after a firefox upgrade, keepass upgrade, or something else. When things broke, KeePassXC-Browser said something like 'key exchange failed' (with keepassxc). When I looked at KeePassXC-Browser settings, it was still detecting an outdated KeePassXC. In KeePassXC-Browser, I tried removing the existing Connected Database. I couldn't reconnect after that, though. Nothing on the screen changes when I click the "Connect" button. I restarted both FireFox and KeePassXC. Now, in KeePassXC-Browser, no databases are listed in Connected Databases tab, and KeePassXC Version is unknown on the About tab.

**Comment by varjolintu** [comment]
@burkemw3 Please check the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by burkemw3** [comment]
@varjolintu org.keepassxc.keepassxc_browser.json's path option pointing to an older KeePassXC binary was my issue. Pointing to the latest resolved it for me. Thanks for the link and resolution!

**Comment by TomPradat** [comment]
Hi, I do have the issue with a snap version. It seems that the extensions cannot connect with the snap.

KeePassXC version 2.5.1
KeePassXC-Browser version 1.5.4

The connection doesn't work on Firefox 71.0 nor Chrome 79.0

On both browsers, I always get the same two errors :
```
Error 7: Échec du chiffrement du message. KeePassXC est-il lancé ? keepass.js:1062:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:979:13
Error 9: L’échange de clé a échoué.
```
I followed the troobleshooting guide and I do have the correct `org.keepassxc.keepassxc_browser.json` files

My keepassxc-proxy is up for each browser

I double checked that the "active integration to browsers" was checked in KeePassXC.

**Comment by varjolintu** [comment]
@TomPradat Use the Snap helper script: https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh

**Comment by TomPradat** [comment]
It works :tada:, thanks a lot :)

**Comment by droidmonkey** [comment]
Should this be closed?
