### ISSUE TITLE
Subdomains are ignored

### ISSUE THREAD

**Issue by varjolintu** [keepassxreboot/keepassxc-browser#686]
This is a temporary pinned issue for the current subdomain handling bug.

This is related to KeePassXC, not the extension. We tried to fix the URL matching for 2.5.1 that has been broken for a long time. Subdomain matching wasn't fixed properly, but there's already a fix. See https://github.com/keepassxreboot/keepassxc/pull/3854. For the issue opened to KeePassXC side, see https://github.com/keepassxreboot/keepassxc/pull/3854.

Please wait until KeePassXC 2.5.2 is released. In the meanwhile you can try to tackle the issue by enabling _Return only best-matching entries_ from KeePassXC's Browser Integration settings.

Thank you for the patience.

**Comment by Nothing4You** [comment]
Hi,

when I select "Return only best-matching entries" in KeePassXC I only get one of the accounts for the site as an option. Is that related to this issue or is this a separate problem?

**Comment by varjolintu** [comment]
It should only return the best matching credential for the site. You can try to make another entry with a similar URL for testing, and it should then return that one too. Less-specific URL's are ignored if a better match is found.

**Comment by Nothing4You** [comment]
I see, that was my issue, thanks.
One was https://domain/ and the other one was just https://domain.

**Comment by varjolintu** [comment]
This fix has now been merged to KeePassXC side. Keeping this issue open until KeePassXC 2.5.2 is released.

**Comment by alexanderadam** [comment]
@varjolintu I'm not quite sure whether this is the same bug or another:
Since a while the "subdomain" handling is buggy. I even got a dialogue on `app.box.com` while the affected entries had `https://www.dropbox.com/login` in the url.

Should I open another issue for this if this is unrelated?

Also: I accidently answered allow + remember because I didn't read properly. Can I somehow bulk revert this or 'bulk correct' this?

**Comment by droidmonkey** [comment]
All of the problems are already fixed in 2.5.2 branch, no need for a new issue

**Comment by alexanderadam** [comment]
@droidmonkey thank you for the fast response of one of my questions.

I accidentally answered allow + remember because I didn't read properly. Can I somehow bulk revert this or 'bulk correct' this?

**Comment by varjolintu** [comment]
@alexanderadam Database settings -> Browser Integration page -> "Disconnect all browsers" and "Forger all site-specific settings on entries".

**Comment by varjolintu** [comment]
KeePassXC 2.5.2 has been released. Closing the issue.
