### ISSUE TITLE
Auto-submit (complete login) inoperative

### ISSUE THREAD

**Issue by bigalgeorge** [keepassxreboot/keepassxc-browser#688]
KeePassXC-Browser Version: 1.5.3
KeePassXC Version: 2.5.1 
Operating system: Linux
Browser: Firefox

[x] Auto-submit login forms
Automatically submits selected credentials. This is disabled for single entry auto-fill.
## Current Behavior
Doesnt auto submit eg complete the login automatically as expected. Yes, I understand the risks.
Fills in user and password perfectly, but does not complete login action.

**Comment by varjolintu** [comment]
What is the site where this is happening?

**Comment by bigalgeorge** [comment]
All sites. Im not sure if auto-submit means the user and password fields are only auto-filled, but I wouldnt think so. I have about 100 sites and daily use about 10 and none complete the logins.
https://login.aliexpress.com/ this one always expects me to fill password with keepassxc menu function.
https://secure.bnz.co.nz/auth/personal-login this one fills both username and password, but doesnt complete the login, unless I click [fill credentials] (this is the usual behaviour Im finding).

**Comment by varjolintu** [comment]
The BNZ site will work with the next version. That aliexpress login site will work better too, but it requires some additional login stuff even if the credentials are submitted automatically.

**Comment by varjolintu** [comment]
So, I have no idea how this could work with aliexpress.com because it needs user to use a slider with a mouse etc.

Still, every site you encounter will help improve the feature.

**Comment by bigalgeorge** [comment]
Im assuming if you are a non-registered, the old slider verification pops up on Aliexpress. I dont see this as Im a registered user and get the one instance as below:
![Selection_427](https://user-images.githubusercontent.com/6935387/69264415-28c03180-0c2c-11ea-9a33-8dd892d349c6.jpg)

**Comment by varjolintu** [comment]
@bigalgeorge Then it will work properly with the next version. You can try the develop branch if you want to test it yourself.

**Comment by bigalgeorge** [comment]
Hi I can only see the 1.5.3 version (same as mine) which is zip. Is there a FAQ how to use the dev version/change to an xpi? Would be happy to check it out unless I have to do a rebuild.

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

No need to build anything. The sources work directly.

**Comment by bigalgeorge** [comment]
Heaps better only problem is firefox doesnt want to make the temporary load permanent, unless there is a trick Ive missed. I added the signature to .json:
`{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/opt/keepassxc/KeePassXC.AppImage",
    "type": "stdio",

    "allowed_origins": [
        "chrome-extension://kdggfocfphncghpalgjiecgcnpgglmef/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ]
}`

**Comment by varjolintu** [comment]
With Firefox the temporary extension always unloads after browser is closed. With Chromium you can make it persistent.
