### ISSUE TITLE
Unable to connect ("Key exchange was not successful.") using browser installed via Snap

### ISSUE THREAD

**Issue by rwanwork** [keepassxreboot/keepassxc-browser#689]
## Expected Behavior

I am unable to connect to the KeePassXC database.

## Current Behavior

After opening KeePassXC and entering my password, I start Chromium.  I click on the icon and then "Reload" and I get the error "Key exchange was not successful."

Previously, it worked.  This problem started happening after I upgraded my Ubuntu OS from 19.04 to 19.10 .  During this period, I was using the Ubuntu package for keepassxc.  I am now using the official PPA -- version 2.5.1 .  And it still doesn't work yet.

I have gone through the [troubleshooting](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide) guide.  I can confirm:

* Browser integration for Chromium is checked
* "Use a proxy application" has been checked.
* ~/.config/chromium/NativeMessagingHosts is present
* the `path` variable points to an executable which does exist

I do not see a `keepassxc-proxy` running when I type "ps -aef".  I tried running it, but the program exits.  Unfortunately, I do not know how to debug the extension; where is the check box for "Developer mode"?

## Possible Solution

New to Ubuntu 19.10 seems to be Chromium via snap instead of apt.  I'm not sure if that's the problem.  But if so, it should affect others, too?

I can confirm that it works under Firefox.  But that's because before, I never used Firefox (i.e., I just started now to test it).  So, I guess it isn't a problem with keepassxc or the connection, but something left over between my upgrade of Ubuntu.  Perhaps an additional setting that needs to change?

## Steps to Reproduce (for bugs)

As mentioned above,
1. Start up Keepassxc and enter password.
2. In the browser, click on the keepassxc-browser icon.  It currently shows "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
3. Click "Reload".
4. The error "Key exchange was not successful." appears.

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.5.3
Operating system: Linux x86_64
Browser: Chrome/Chromium 78.0.3904.97

**Comment by varjolintu** [comment]
The Chromium installed via snap is the problem. It doesn't allow the Native Messaging API to launch another program outside the sandbox, meaning keepassxc-proxy.

**Comment by varjolintu** [comment]
Many have reported this issue, so I'm gonna take a look if there's something we can configure to get Chromium to access the proxy.

**Comment by rwanwork** [comment]
I see.  Sorry, I did not realise that others have reported this issue before.  

Indeed, it seems they are [moving](https://snapcraft.io/blog/chromium-in-ubuntu-deb-to-snap-transition) to snap for good and we can't opt out.

Thanks for the prompt reply as I've been trying several things, thinking it's my fault.

**Comment by varjolintu** [comment]
Linking a few related bugs:
https://forum.snapcraft.io/t/chrome-gnome-shell-does-not-work-with-chromium-snap/3377
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1741074

**Comment by Q3p6v9j7PX7XBjSj9xgC5LJViFxuKqg5cpfg93x** [comment]
No choice but to use outdated KeepassXC

**Comment by varjolintu** [comment]
@Q3p6v9j7PX7XBjSj9xgC5LJViFxuKqg5cpfg93x Not so fast. You can always install your browser without snap or flatpak using the package manager and then everything works.

**Comment by rwanwork** [comment]
@Q3p6v9j7PX7XBjSj9xgC5LJViFxuKqg5cpfg93x @varjolintu Another "option" is to give up on Chromium.  I've switched over to Google Chrome, which is installed by apt still.  It's not a solution to the problem, but at least I am fine with this solution.  Hopefully that doesn't move to snap (I'm not sure if they are phasing out apt in favour of snap?).

Thank you both for your thoughts!

**Comment by onichandame** [comment]
Just for anyone who wants to install Chromium from Snap and wishes to use keepass in Chromium, there is an alternative solution.

**Comment by varjolintu** [comment]
Related comment:
https://github.com/keepassxreboot/keepassxc-browser/issues/1426#issuecomment-1198974234
