### ISSUE TITLE
Connected Databases remove button removes all connections

### ISSUE THREAD

**Issue by DeCaMil** [keepassxreboot/keepassxc-browser#690]
If there are multiple data base connections, a `Remove` button is displayed for each connection.

When clicked, the user is prompted "Do you really want to remove the following identifier from the database list?" and the database identifier id displayed.

When `Yes, remove now` is clicked, **ALL** database identifiers are removed.

## Expected Behavior
`Yes, remove now` should only remove the selected database identifier.

## Current Behavior
When `Yes, remove now` is clicked, **ALL** database identifiers are removed.

## Steps to Reproduce (for bugs)
1. Open two databases in KeePassXC
2. Select the first database in KeePassXC
3. Click `Connect` in KeePassXC-Browser
4. Enter the identifier `AAA`
5. Select the second database in KeePassXC
6. Click `Connect` in KeePassXC-Browser
7. Enter the identifier `BBB`
8. Click `Remove` next to either `AAA` or `BBB`.
9. Click `Yes, remove now` and both `AAA` and `BBB` are removed

## Debug info
KeePassXC: 2.5.1
KeePassXC-Browser:1.5.3
Operating system: Win
Browser: Chrome
No messages are logged to the JS console when deleting a database identifier.

**Comment by DeCaMil** [comment]
Observation from additional poking:
All the database identifiers are getting the same hash.
The select is done by hash, so all are deleted.

**Comment by varjolintu** [comment]
This is related to this issue: https://github.com/keepassxreboot/keepassxc-browser/issues/640

The workaround is to make a new database and merge entries from the old one.
