### ISSUE TITLE
Banner fills reCAPTCHA frame

### ISSUE THREAD

**Issue by r0ar** [keepassxreboot/keepassxc-browser#695]
## Expected Behavior
Banner should stay on the top and not fill any frames.

## Current Behavior
If login info is different from the database, the banner appears on the top and asks you to update the credentials. If the site you are logging into shows a reCAPTCHA after the banner is present, the reCAPTCHA frame is quickly filled with the banner's content and dismissing the banner on the top will not remove it from the reCAPTCHA frame.

## Steps to Reproduce
Can be done on any site that asks for a reCAPTCHA after the login was successful but I'll use discord here because it is easily reproducible.
1. Go to https://discordapp.com from a different location (Use a VPN or proxychains)
2. Remove your username from the keepassxc database (or if you don't have it saved it's even better!)
3. Now log in. The banner should appear on the top.
4. Discord will show a reCAPTCHA frame because you are not logging in from the usual location.
5. Banner fills the reCAPTCHA frame.
6. Dismiss banner. See that the reCAPTCHA frame is still filled.

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Arch Linux
Browser: Firefox 70.0.1 (64-bit)

**Comment by varjolintu** [comment]
Maybe we should modify the banner that it will only show in the main page, not inside frames at all.

**Comment by r0ar** [comment]
@varjolintu I think that is the expected behavior. But I don't know... Is there a way to make sure there is only 1 instance of the banner? Maybe that will work. 
Also one time (I don't know what site it was so I can't reproduce it) but the banner just went outside the top screen bound and couldn't be clicked on.
Instead of a banner can you automatically open the extension window (the one that opens under the icon when you click it) and show the options there? I think that would be ideal and way cleaner than a banner.

**Comment by varjolintu** [comment]
@r0ar Multiple banner are seen because content scripts are separately in each iframe. We just have to make sure it only appears on the main page.

We just got rid of the credential saving in the extension popup. It was always unreliable and had many bugs. Also, all browsers don't support opening the extension popup via API.
