### ISSUE TITLE
Keyboard shortcuts don't work in Vivaldi

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#697]
## Expected Behavior
After setting the Keybord Shortcut to - say - CTRL-SHIFT-K for Fill Username and Password, I should have expected that using this key combination would fill in the credentials.
(Yes, the browser extension is connected to KeePassXC and its database)
(Yes, there is a credential for the login in the database)
(The KeePassXC icon in the login field proves that all is in order)

## Current Behavior
Presing the key combination doesn't do anything.
BTW, I've tried setting different key combinations for Fill Username and Password, but I can't get any to work with Vivaldi.
I also tried with Edge Dev and there the shortkeys do work as expected.

## Possible Solution
I'll also check with Vivaldi Development team

## Steps to Reproduce (for bugs)
1. Open Vivaldi browser
2. Navigate to https://outlook.live.com/owa/?nlp=1
3. Press the shortkey that is set up for Fill Login Name and Password
4. And then nothing

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Win32 (Incorrect: Win64)
Browser: Chrome/Chromium 79.0.3945.45

**Comment by varjolintu** [comment]
You can try to modify the shortcuts from the settings. Maybe our defaults collide with Vivaldi's shortcuts.

**Comment by Stephan-P** [comment]
A brief experiment with Google Chrome showed the same results as with Edge Dev. Shortkey settings work fine there.

**Comment by Stephan-P** [comment]
Back in Vivaldi, I removed CTRL-SHIFT-L from Bitwarden autofille and enabled this for KeePassXC-Browser. This shortkey has always worked fine for Bitwarden, so no conflict there. Reassigned to KPXC, no luck: nothing.
Does this ring a bell, or should I report this issue with Vivaldi? (Note that CTRL-SHIFT-L used to work fine for BW and so it does again, now that I re-assigned it)

**Comment by varjolintu** [comment]
This would almost need some debuggin of the background script to see if the keyboard shortcut triggers at all.

You can put a breakpoint here: https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/background/init.js#L122

**Comment by Stephan-P** [comment]
Oh dear, I have no experience whatsoever with debugging extensions. 
I've opened the extension background page and hit F12.
In the tab Sources I've selected init.js and inthere I think I've managed to place a breakpoint at line 122. (Mind you, it's been 25 years ago that I did my last debugging)
Then back to another browser tab for the outlook.com login, I hit CTRL-SHIFT-K.
What should happen now? I don't think I see anything happening in the Developpers Tools window.

**Comment by varjolintu** [comment]
The breakpoint should trigger. You can try some other shortcut (if you haven't changed them). For example filling a password is ALT+SHIFT+I. Showing a password generator is ALT+SHIFT+G.

**Comment by Stephan-P** [comment]
No, also for ALT-SHIFT-G, I don't think that I see anything happening here. 
Wait, let me try that within Edge Dev as well. 
BAM! CTRL-SHIFT-K hits the breakpoint alright. (So, that's what it should look like)
Nope, nothing like this in Vivaldi.

**Comment by Stephan-P** [comment]
It sounds like Vivaldi and KPXC-Browser are not on speaking terms

**Comment by Stephan-P** [comment]
I dug into the Bitwarden extension, managed to find the line where shortkeys arrive and managed to trigger the breakpoint.
Vivaldi and Bitwarden are on speaking terms.

**Comment by varjolintu** [comment]
I'll download Vivaldi and see if I can figure out where the error is.

**Comment by varjolintu** [comment]
I managed to get the keyboard shortcut working when I changed the "in Vivaldi" option to "Global".

**Comment by Stephan-P** [comment]
Nice!
Funny that this only seems to play between Vivaldi and KPXC-B.
In Chrome or Edge Dev, the option does not need to be "global".
In Vvaldi, the Bitwarden extension also manages quite nicely with the option "in Vivaldi".
So is this a Vivaldi issue or KPXC-B's?

**Comment by varjolintu** [comment]
I think it has something to do with Vivaldi's way to handle keyboard shortcuts. It's different from normal Chromium. And Bitwarden seems to hook to another non-standard callback with Vivaldi (that didn't work for me when I tried it).

So for now, I think it's Vivaldi's issue if the standard event doesn't work properly. And they have no documentation how to really use it with extensions.

**Comment by Stephan-P** [comment]
Exactly what I was thinking of: 
- different methods of passing shortkey messages (are there?)
- I've filed a bug report with Vivaldi (ref. VB-60719)
