### ISSUE TITLE
Key exchange was not sucessful

### ISSUE THREAD

**Issue by superwinni2** [keepassxreboot/keepassxc-browser#698]
## Current Behavior
I always get the error message "Schlüsselaustausch war nicht erfolgreich" (sorry for german :P ) which means as much as "Key exchange was not successful".
Sometimes it's working, sometimes not. No changes made between.

Reproduce (for bugs)
1. Open Chrome
2. Type in Passwort in KeePassXC
3. Open age with login credentials
4. Try to insert password via KeePassXC

#### Console Output:
keepass.js:977 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:947 Failed to connect: Error when communicating with the native messaging host.
keepass.js:1060 Error 9: Schlüsselaustausch war nicht erfolgreich.

#### System Data
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Auto connection is OFF!
Operating system: Windows 7
Browser: Chrome

**Comment by varjolintu** [comment]
- Are you using portable KeePassXC?
- Is "Update manifest files on startup" enabled in the Browser Integration Advanced settings?
- Have you checked the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)?

**Comment by superwinni2** [comment]
Using local installed KeePassXC with passfile in Nextcloud synchronized with nextcloud program.

Sorry I only see the german language... I think the thing you mean is that the connection will be automatic reconnected if it's going to be detected? (In german it's the 5th checkbox or other said, the first with experimental warning)

I also already checked the Troubleshooting Guide.
Entrys in regedit are all right.
The debug ist what I posted in "Console Output"

**Comment by varjolintu** [comment]
The errors in the console suggest that the Browser Integration is not enabled correctly. Where does your registry path point? What's in the .json file it points to?

I mean the third checkbox from the bottom in KeePassXC's Browser Integration settings, Advanced tab.

**Comment by superwinni2** [comment]
Registy point to -> C:\Users\my_user\AppData\Local\KeePassXC\org.keepassxc.keepassxc_browser_brave.json

Json contains
```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\KeePassXC.exe",
    "type": "stdio"
}
```

ID fits with Chrome...

Here a Image of my Settings... Maybe you can ready something out of it....
![Extension](https://user-images.githubusercontent.com/42318077/70046528-86f2fa00-15c6-11ea-8f31-0801a66eda0b.png)

**Comment by varjolintu** [comment]
That path in .json means it's trying to start KeePassXC directly, not the `keepassxc-proxy.exe`. Have you disabled the proxy setting in the Advanced tab? Enable it if so.

If you use KeePassXC without the proxy, KeePassXC needs to be closed before starting the browser. It's not a preferred choice.

**Comment by superwinni2** [comment]
Yes it was disabled.
I've enabled it now. And I also could connect directly after switching it on.
But after a restart of Chome now I get the message "Nachricht kann nicht entschlüsselt werden" (Message can't be decrypted)
I restartet KeePassXC also and now it's working for the moment...

Thanks for your help!
I'm going to watch it a few days. Hopefully it doesn't happen anymore.

**Comment by varjolintu** [comment]
If the Auto-reconnect is disabled, you need to reconnect the extension manually using the popup and Reload button after KeePassXC has been restarted. It shouldn't be necessary to restart the browser.

Closing the issue for now. Write here again if you are having more problems.
