### ISSUE TITLE
User/password input field detection doesn't work for dropdown menus

### ISSUE THREAD

**Issue by cryptomilk** [keepassxreboot/keepassxc-browser#70]
User/password input field detection doesn't work for drop down menus when credentials for the site are stored in keepassxc.

A good example is:

https://build.opensuse.org/

## Debug info
KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Firefox 58.0.2
Proxy used: NO

**Comment by varjolintu** [comment]
Does redetecting credential fields help?

**Comment by cryptomilk** [comment]
Yes, it does.

**Comment by varjolintu** [comment]
If you save those specified credential fields does it solve the issue?

**Comment by cryptomilk** [comment]
I need to 'redetect credential fields' each time I want to log in.

**Comment by varjolintu** [comment]
Cannot reproduce this with Chromium. The dropdown login menu works just fine without any tweaking. However I could reproduce this with Firefox.

**Comment by varjolintu** [comment]
I know a solution to this but I need to make some more testing. I don't like the idea of looping `setInterval`.

**Comment by cryptomilk** [comment]
Thanks for looking into this!
