### ISSUE TITLE
KeePassXC-Browser only checking domain and not URL

### ISSUE THREAD

**Issue by MaxXor** [keepassxreboot/keepassxc-browser#700]
I have lots of different services on different subdomains and directories hosted on the same domain. All entries in the KeePassXC database have set the URL field to the full URL like https://sub.domain.com/service/. KeePassXC-Browser extension shows all entries for whole domain instead of checking the complete URL. This has worked fine a while ago.

## Expected Behavior
Only show the correct matching URL like it was in the previous versions.

## Current Behavior
It shows a complete list of all entries for one domain.

## Possible Solution
Check the complete URL.

## Steps to Reproduce (for bugs)
1. Add entry for https://domain.com/dir1/ and one for https://domain.com/dir2/
2. Visit https://domain.com/dir1/
3. KeePassXC-Browser will show all entries for that domain

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Arch Linux
Browser: Firefox 70.0.1

**Comment by varjolintu** [comment]
KeePassXC bug. Already fixed for 2.5.2.

**Comment by MaxXor** [comment]
Thanks.

**Comment by NathanSweet** [comment]
I'd actually like this feature. I migrated passwords from elsewhere and many have URLs with a long path. I'd like to match only on domains, not the path or subdomain.
