### ISSUE TITLE
Website requesting permission for all of the password in the database

### ISSUE THREAD

**Issue by themightydeity** [keepassxreboot/keepassxc-browser#703]
## Expected Behavior
Website doesn't even have any entry for it to be requesting password from keepassxc

## Current Behavior
Website when completly loaded is requesting permission to access all of the password that are in keepassxc database.

## Possible Solution
I couldn't figure out why this is happening.

## Steps to Reproduce (for bugs)
1. Connect to a test database instead of real one,  I have a feeling some tracking/ad network they are using are trying to circumvent keepassxc-browser's vunerablilites.  
2. Open `https://supersleeperpro.com.au/` in your browser
3. Wait for it load and request permission for all the keys in your database.

## Debug info
Console log
```
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. supersleeperpro.com.au
Loading failed for the <script> with source “https://dev.visualwebsiteoptimizer.com/j.php?a=430180&u=https%3A%2F%2Fsupersleeperpro.com.au%2F&f=1&r=0.816960094602772”. supersleeperpro.com.au:1:1
Loading failed for the <script> with source “https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=L3MLfe”. supersleeperpro.com.au:1241:1
downloadable font: OS/2: Bad sTypoLineGap, setting it to 0: -32 (font-family: "Pe-icon-7-stroke" style:normal weight:400 stretch:100 src index:1) source: https://cdn.shopify.com/s/files/1/0098/8915/3081/t/26/assets/Pe-icon-7-stroke.woff?d7yf1v unknown:1:900
Loading failed for the <script> with source “https://static.klaviyo.com/onsite/js/klaviyo.js?company_id=L3MLfe&shop=supersleeperpro.myshopify.com”. supersleeperpro.com.au:1:1
Loading failed for the <script> with source “https://connect.facebook.net/en_US/fbevents.js”. supersleeperpro.com.au:1:1
Loading failed for the <script> with source “https://www.googletagmanager.com/gtag/js?id=AW-870293803”. supersleeperpro.com.au:1:1
Loading failed for the <script> with source “https://cdn.shopify.com/shopifycloud/boomerang/boomerang-latest.min.js”. supersleeperpro.com.au:1:1
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://monorail-edge.shopifysvc.com/v1/produce. (Reason: expected ‘true’ in CORS header ‘Access-Control-Allow-Credentials’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.mixpanel.com/decide/?verbose=1&version=1&lib=web&token=b76159566274795f611156bc76391e75&ip=1&_=1575456861308. (Reason: CORS request did not succeed).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://web-analytics.smile.io/collect?data=eyJ0eXBlIjoic2Vz…dnB4NHZNaHlyWnpMR2siLCJkYXRhX2pzb24iOm51bGx9&u=1575456861640. (Reason: CORS request did not succeed).

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
```
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.3
Operating system: Linux
Browser: Firefox and Chromium both

I have uBlock origin and tracking protection enabled

**Comment by varjolintu** [comment]
I had no problems with the site. Please make sure your entry has `https://supersleeperpro.com.au/` as its URL.

**Comment by pbulteel** [comment]
I have the same issue. I just went to the above URL and I get keepassxc-browser to popup asking for not all but a LOT of my passwords. I noticed this since the 2.5.1 upgrade. This seems to happen with other internal sites. In some instances it asks for 5 passwords, other times 2 (sometimes it's the same entry twice!) IF I accept it then the drop-down will display ALL the entries that were in the popup. I came to look for this particular issue (or was going to open it.)

**Comment by pbulteel** [comment]
Oh, and to make it clear - I do NOT have the above URL in ANY password entry. So the fact it's requesting them is unnerving.

**Comment by varjolintu** [comment]
@pbulteel That is related to https://github.com/keepassxreboot/keepassxc-browser/issues/686. This is caused a bug in KeePassXC 2.5.1 where invalid URL can cause such behaviour.

This issue has been already fixed for 2.5.2 but it's not released yet. So your options are:
- Downgrade to 2.5.0 until there's a new release
- Modify any invalid URL's away from your entries (this takes time..)

**Comment by themightydeity** [comment]
@varjolintu 

I didn't have any entry for that URL at all, but like you suggested downgrading to 2.5.0 fixed the issue

**Comment by varjolintu** [comment]
@themightydeity Not at this point, but KeePassXC 2.5.2 will show you a red URL field in the entry if it's invalid.

**Comment by cpauls** [comment]
Hi,
what are your plans to release version 2.5.2? I'm struggling with this issue too.

regards

**Comment by varjolintu** [comment]
@cpauls At this point it seems 2.5.2 is released at the earliest at the end of the year. Possibly at the start of the next decace (finally had the chance to say this).

**Comment by phoerious** [comment]
You can always install a snapshot build in the meantime.
