### ISSUE TITLE
Allow selection of existing keepassxc entry for page

### ISSUE THREAD

**Issue by jhesketh** [keepassxreboot/keepassxc-browser#71]
## Expected Behavior

This is a feature request.

When encountering a password field, rather than just looking for a matching database entry from URL and/or page title also provide the option to manually select from any entry in the database (and have the option to remember the selection for a particular page).

This is useful where one credential is used across multiple websites (due to shared backends, not poor password reuse). It also allows the user to sort their credentials in names and folders outside of the "KeePassXC-Browser Passwords" group.

This is additionally useful for users of keepassxc who have just installed the browser extension and may not have their existing entries named appropriately enough to match.

## Current Behavior

If an entry doesn't match properly I am unable to enter it using the plugin.

**Comment by varjolintu** [comment]
This goes against the database permissions. KeePassXC-Browser doesn't have any access to entries you don't give permissions, and I would see it problematic if the extension would have access to **all** entries, meaning full access.

Please just change the entry URL to match the site.

**Comment by jhesketh** [comment]
Right, I see your point. Perhaps more of a feature request for keepassxc then for a way to expose certain records on request.

Sometimes an entry needs to match multiple URL's, that is the tricky part.

**Comment by layanto** [comment]
Something similar is available in Keepass2Android app. If an entry is not found, it gives you the option to select an entry manually or to create a new entry. Would be great if I can do the same on desktop with KeePassXC Browser.

**Comment by varjolintu** [comment]
I’ll look into it if it’s possible to do.

**Comment by CrendKing** [comment]
Changing entry URL to match the site may not be available. For example, Chase bank's login widget is an iframe whose URL is something like secure03c.chase.com, secure07a.chase.com, etc (seems to be dumb idea for load balancing). They could use as many different subdomain as they want, and asking regular user to create 20 entries just for Chase is not feasible.

Instead, if this feature is implemented, ideally we could specify a mapping from a wildcard/regexp of URL to specific entry in database. For instance, secure03c.chase.com to www.chase.com (or whatever we enter in the URL field of Chase entry in database).

**Comment by varjolintu** [comment]
@CrendKing I'm about to add a wildcard support to the next release.

**Comment by shuhaowu** [comment]
Another website that does the iframe approach is digikey. If you're on digikey.ca, the login page is an iframe from digikey.com. Having multiple URLs/even with KeepassXC-Browser Settings will be very useful.

**Comment by varjolintu** [comment]
In the upcoming release of KeePassXC this will be resolved (see https://github.com/keepassxreboot/keepassxc/pull/2253).

It's not a pure wildcard support yet, but will resolve issues like this one. Entries with url `https://chase.com` would match with `https://*.chase.com`.
