### ISSUE TITLE
KeePassXC-Browser for Firefox settings and... 

### ISSUE THREAD

**Issue by unnamedsos** [keepassxreboot/keepassxc-browser#713]
Settings for KeePassXC-Browser for Firefox are all empty ....
I do get a connection  request from firefox to keepass but it fails everything else
on my machine it works for vivaldi and chromium.

Firefox 71.0 (64-bit)
plugin is the newest from firefox

KeePassXC - Version 2.5.1
Revision: 0fd8836

Qt 5.12.5
Debugging mode is disabled.

Operating system: Fedora 30 (Thirty)
CPU architecture: x86_64
Kernel: linux 5.3.15-200.fc30.x86_64

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.5

see attachments for all other info i could gather.
![Screenshot from 2019-12-12 10-51-02](https://user-images.githubusercontent.com/9324488/70702286-1dfa3900-1cce-11ea-8096-9a3641d16bce.png)
![Screenshot from 2019-12-12 10-51-14](https://user-images.githubusercontent.com/9324488/70702287-1e92cf80-1cce-11ea-8619-8adb97331a39.png)

**Comment by dkadashev** [comment]
I'm getting the same with Firefox 71 on Debian bullseye/sid (testing+unstable). Manually assigning login fields make it work via hotkey, but I have to do that for every page (it used to work everywhere automatically).

The output in JS console is shorter for me.

![keepassxc-console](https://user-images.githubusercontent.com/1396608/70711282-b8c93680-1d13-11ea-873f-f18e99f30d78.png)

**Comment by varjolintu** [comment]
I'm sure this is the same bug as #704. Please update the Firefox or downgrade to version 70.

**Comment by unnamedsos** [comment]
new update from fedora firefox fixed the problem for me :-)
