### ISSUE TITLE
Small 2FA fields covered with KeepassXC symbols at GOG

### ISSUE THREAD

**Issue by ericschdt** [keepassxreboot/keepassxc-browser#714]
It is convenient to have a symbol marking a field which can be filled by KeepassXC.

However, the one time password field for 2FA of `https://gog.com` are just so small that the symbols cover almost  the whole field:

![gog](https://user-images.githubusercontent.com/43318127/70833353-72490a00-1def-11ea-8021-431607644003.png)

And actually they are not necessary at all here as KeepassXC is not supported for 2FA here afaik.

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.5.4
Operating system: Manjaro Linux
Browser: Firefox

**Comment by varjolintu** [comment]
You can disable the icons from the extension settings.

We need to make some changes and make sure these icons are not filled to input fields that are for single numbers, or too small. Thanks for the report.
