### ISSUE TITLE
Credentials dropbox styles should be important!

### ISSUE THREAD

**Issue by slayer** [keepassxreboot/keepassxc-browser#717]
## Expected Behavior
Dropbox items should be visible

## Current Behavior

Dropbox css is overriden

![image](https://user-images.githubusercontent.com/57521/70901315-37b7bb00-2003-11ea-8f08-5b5d22f715c4.png)

## Possible Solution
make css `important!`

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Chrome/Chromium 78.0.3904.108

**Comment by varjolintu** [comment]
This will be fixed with the next version that introduces Shadow DOM so we can get rid of CSS overrides.
