### ISSUE TITLE
Fill fields using shortcut does not work on Mac

### ISSUE THREAD

**Issue by GMTA** [keepassxreboot/keepassxc-browser#72]
## Expected Behavior
I should be able to use the Alt + Shift + U or Alt + Shift + P shortcuts to automatically fill in the username and password or just the password respectively on a macOS system.

## Current Behavior
The shortcuts, they do nothing. Instead they insert characters like "¨∏". Using the context menu to fill in the fields _does_ work.

## Possible Solution
* Change the shortcuts to something that works
* Show the correct shortcuts in the Settings dialog

## Steps to Reproduce (for bugs)
1. Go to a username and password form where normal username and password filling through the context menu works as intended.
2. Use the Alt + Shift + U/P shortcut

## Debug info
No errors/warnings in console.

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Mac
Browser: Firefox
Proxy used: No

**Comment by varjolintu** [comment]
Actually the shortcuts for macOS use MacCtrl instead of Alt. Try them out.

**Comment by GMTA** [comment]
So indeed Ctrl + Shift + U fills out my username. Ctrl + Shift + P does not work, however.

Two issues still remain:
* The text in the Settings dialog is wrong on Mac
* The Ctrl + Shift + P shortcut does not work

**Comment by varjolintu** [comment]
Does it matter if you do the filling on the password or usename field?

You are right, the shortcut descriptions are wrong with macOS.

**Comment by GMTA** [comment]
Ctrl + Shift + P does not work on either the username or password field.

**Comment by varjolintu** [comment]
Strange. Not for me too. I wonder if Firefox has changed some shortcuts that overrides that one. I'll get back to it.
