### ISSUE TITLE
Popup is too small if extension is pinned to overflow menu in Firefox

### ISSUE THREAD

**Issue by FWDekker** [keepassxreboot/keepassxc-browser#721]
The popup is too small to be useful after pinning it to the overflow menu in Firefox.

## Expected Behavior
In Firefox I can [pin extensions to the overflow menu](https://support.mozilla.org/en-US/kb/customize-firefox-controls-buttons-and-toolbars). That way, they don't take up space when I don't need them to. When I click the KeePassXC icon while it's in the overflow menu I expect it to behave exactly like it would when it isn't pinned to the overflow menu. Observe the normal behaviour in the following screenshot.

![The size of the popup when it is not pinned to the overflow menu.](https://user-images.githubusercontent.com/13442533/71154686-62408880-223c-11ea-9923-50e9a615f9f7.png)

## Current Behavior
After pinning KeePassXC-Browser to the overflow menu, the popup is much narrower than before, as shown in the screenshot below. As a result, the "Connect" button is now invisible and cannot be pressed. Horizontal scrolling (that is, scrolling while holding <kbd>Shfit</kbd>) or dragging my text selection to the right both don't seem to work.

![The size of the popup when it is pinned to the overflow menu.](https://user-images.githubusercontent.com/13442533/71154706-6cfb1d80-223c-11ea-9d3e-578bebcea190.png)

## Possible Solution
The best solution would be to make the popup the same size before and after pinning it to the overflow menu. However, an alternative would be to prevent the overflow of elements to make sure elements are never hidden, but this has the drawback that the popup may become too tall. Maybe both should be done.

## Steps to Reproduce (for bugs)
1. Install the KeePassXC-Browser plugin.
2. Pin the plugin icon to the overflow menu.
3. Open the plugin popup from the overflow menu.
4. Observe its size.

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Windows 10
Browser: Firefox 71.0

**Comment by varjolintu** [comment]
Seems like this is a Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1373490

**Comment by furious** [comment]
Removing `min-width` should help...

https://github.com/keepassxreboot/keepassxc-browser/blob/b08966c6fd709e334962e661e43b40ce1345ddfe/keepassxc-browser/popups/popup.css#L8
https://github.com/keepassxreboot/keepassxc-browser/blob/b08966c6fd709e334962e661e43b40ce1345ddfe/keepassxc-browser/popups/popup.css#L14

![image](https://user-images.githubusercontent.com/3678215/75370510-f0bc3080-58a3-11ea-8473-019481052fd5.png)

**Comment by xf-** [comment]
looks fixed in nightly
![image](https://user-images.githubusercontent.com/1295633/75548503-baaab800-5a2d-11ea-8f93-6ee9c25461b5.png)
