### ISSUE TITLE
Don't observe mutations when not needed

### ISSUE THREAD

**Issue by vphantom** [keepassxreboot/keepassxc-browser#725]
## Expected vs Current Behavior

In playing with some "drag & sort" functionality for our intranet I realized that it became very sluggish (near-unusable) when shuffling around complex DOM bits which include input fields.  Profiling revealed that all of the CPU usage was in KeepassXC-Browser.

It appears that the extension is constantly monitoring the DOM, and unchecking its automation settings does not resolve the issue.  I expected that it would.

Possibly related to #368, #545 and #629.

## Possible Solution

When none of the "Activate *" and "Automatically *" settings are checked, `kpxcObserverHelper` should not monitor the DOM at all.  The DOM should be inspected only once, when the toolbar icon is clicked or when a context menu item is selected.  (Or when the context menu is created, if that's dynamic; I haven't investigated that bit.)

Profiling reveals that most of the wasted time is spent in:

* 40.2% `kpxc.initCredentialFields`
* 37.1% `kpxcFields.getAllFields`
* 21.2% `kpxcFields.isSearchField`
* 13.6% `kpxc.getForm`
* 11.4% `kpxcFields.isVisible`

…it seems to me that avoiding use of the observer when not needed would be the most effective way to eliminate that overhead.

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux 4.16.0-0.bpo.2-amd64 #1 SMP Debian 4.16.16-2~bpo9+1 (2018-06-26) x86_64 GNU/Linux
Browser: Chrome 76.0.3809.100 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
I agree the MutationObserver is not a perfect solution, but in handles the DOM popups and other elements that are added after the page load quite good. Still, there might be some room for improvement, especially if it takes too much CPU.

A workaround for this is to add the site URL to *Site preferences* tab in the extension settings and enable the option *Disable all features*. It still triggers the MutationObserver but `kpxc.initCredentialFields` will return before anything major is done.

**Comment by droidmonkey** [comment]
Can we add a change delay? The first mutation observer hit would start a timer, say 150 ms, then subsequent hits would be ignored. When the timer ends the DOM would be parsed.

**Comment by varjolintu** [comment]
@droidmonkey That could be possible. I need to investigate some solutions for this.

**Comment by vphantom** [comment]
I was hopeful, but _Disable all features_ yields no measurable reduction in CPU usage on that page.

A spin on @droidmonkey's throttle idea could be to avoid mutations while the mouse/touch is down and to catch up with the DOM when the mouse/touch comes back up. That would eliminate issues with drag&drop entirely without incurring a delay nor forcing users to disable advanced features for performance.

That said, I assume that re-checking the whole DOM is not actually feasible in the current code structure, which seems to rely solely on mutations to parse relevant bits of the DOM.  So I don't expect "hands off" timeouts to be any more practical to implement than making the mutation observer optional to begin with. :thinking:

**Comment by vphantom** [comment]
Note for future readers hitting this issue: there was a _huge_ need for optimization in the drag&drop handler we were using! Our naïve implementation fired several tens of useless `element.insertBefore()` calls every second even when the net element order didn't need to change, which triggered as many useless mutations for all observers, KeePassXC's being the heaviest.

While a means to avoid the observer would be useful in this extension (for users dealing with sites they cannot control), in our case we were definitely compounding the issue pretty badly.

**Comment by droidmonkey** [comment]
Good to know, although your error exposed a weakness on our side too. Win-Win!

**Comment by varjolintu** [comment]
Thanks for the feedback guys. I'll see what I can do to decrease the CPU usage and make things useful again.

**Comment by varjolintu** [comment]
@vphantom I created a WIP PR: https://github.com/keepassxreboot/keepassxc-browser/pull/729. Test it out if you can :)

**Comment by vphantom** [comment]
I'd like to give it a shot, but I never worked on Chrome extensions (except a quick Twitter-modifying hack I only ran locally). What would be the most efficient way for me to test that PR?

**Comment by varjolintu** [comment]
Download the branch and use these instructions: https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually

Basically you just load the extension temporarily from the sources and add the temporary ID to the Native Messaging manifest script.

**Comment by vphantom** [comment]
Sorry it took me a while to muster the courage to re-break our code in my dev setup to try this. :stuck_out_tongue:  I can confirm that this PR seems to constrain the issue as I can no longer reproduce it.

**Comment by varjolintu** [comment]
That's good news! If there's anything else to improve or fix in the extension's performance, please let us know.

**Comment by Campano** [comment]
Glad you are working on this, I was blaming Firefox because I was getting 5s difference on some apps, until I discovered the "Show Gecko Data" in the performance tab...

Is there a plan for an option to disable all automatic operations and have keepass work on demand only?

**Comment by varjolintu** [comment]
@Campano That could be added as an option to the PR. It's not reviewed yet so there's still time.

**Comment by varjolintu** [comment]
@Campano The feature is added to the PR. When observer is disabled, the only option to fill credentials is to use keyboard shortcuts or the context menu. I'll add another commit later that also allows to fill the credentials using the popup.
