### ISSUE TITLE
Exclude special fields or subpages

### ISSUE THREAD

**Issue by RolandSM** [keepassxreboot/keepassxc-browser#726]
Hello,

on a Joomla CMS page I use the https://mydomain.de/administrator for login.
This works.

But if I work inside with views, where the browser plugin detects credential fields like email, password, username a.s.o. this fields are autofilled!

For example:
https://mydomain.de/administrator/index.php?option=com_config&view=component&component=com_sppagebuilder
I have to exclude from autofill or also the user handling sites in com_users

In normal Keepass2 Integration I can define in the Browser Plugin, a blacklist of fields, fieldsets or form names/id/classes.

**Comment by varjolintu** [comment]
Have you tried to put `https://mydomain.de/administrator/*` to the *Site Preferences* and select *Disable all features* from the combo box? The main login page should still work normally.

**Comment by RolandSM** [comment]
Yeah this works. Thanks.
