### ISSUE TITLE
OTP field value never inputs

### ISSUE THREAD

**Issue by mustaqimM** [keepassxreboot/keepassxc-browser#727]
## Expected Behavior

TOTP codes added to OTP field 

## Current Behavior

TOTP codes are not added to OTP fields. If I click the TOTP icon, it never adds the code from the database. The field name for example in Protonmail is `twoFactorCode` and on GitHub it's `otp`. The icon shows up but the nothing is inputted.

I even tried adding: `KPH: {TOTP}` with the value `{TOTP}.

## Steps to Reproduce (for bugs)

1. Click icon or right click add OTP

## Debug info

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Does it copy the TOTP normally if you right-click the entry in KeePassXC and use *TOTP... -> Copy TOTP*?

**Comment by mustaqimM** [comment]
Ya, that's how I have to do it now

**Comment by varjolintu** [comment]
Strange, because I use Protonmail daily with this feature and it has always worked.

One thing you could try is to select the credentials again using the extension popup from the icon when you are in the 2FA page, then try to fill TOTP again.

**Comment by mustaqimM** [comment]
That works. If I don't re-select the credential, the TOTP code won't input

**Comment by varjolintu** [comment]
If you can, please open the Web Developer Inspector and see if there's any error messages in the console during the login in process. The only reason this might not work is that saving the filled credentials are not saved properly for the 2FA page, but I haven't seen such behaviour yet.

**Comment by tomac4t** [comment]
I have the same issue. And there is no error message in the console.

KeePassXC-Browser Version: 1.5.4
KeePassXC Version: 2.3.4 
Operating system: Debian Buster
Browser: Firefox ESR 68

![2019-12-31_00-22](https://user-images.githubusercontent.com/47532693/71590541-e1e72500-2b63-11ea-9750-8162052daabf.png)

**Comment by varjolintu** [comment]
I could not reproduce this. GitHub site works normally for me. The only way to see where the problem possible is, is to debug the content script and check what happens inside `keepassxc-browser.js` at `kpxc.fillInFromActiveElementTOTPOnly`.

**Comment by tomac4t** [comment]
I can see the `kpxc.credentials` have my username and password, but `'KPH: {TOTP}'` and `kpxc.credentials[index].totp` value are `undefined`. (I have no idea how to debug with that.)

![2019-12-31_15-08](https://user-images.githubusercontent.com/47532693/71613620-88720b00-2be2-11ea-9004-99be341bdb0d.png)

**Comment by varjolintu** [comment]
@tomac4t Just noticed that you are using KeePassXC 2.3.4. Please upgrade and try again. Still, the KPH: {TOPT} method should work with the older release, so that might be a bug.

**Comment by tomac4t** [comment]
> Just noticed that you are using KeePassXC 2.3.4. Please upgrade and try again. Still, the KPH: {TOPT} method should work with the older release, so that might be a bug.

I build the Keepassxc 2.5.1 from source and try it. KeePassXC-Browser extension is work for input the OTP field now. Thanks. @varjolintu

**Comment by OneOfOne** [comment]
Running 2.5.2, `KPH: {TOTP}` no longer works, I was running 2.5.0 before and it worked fine for paypal/github.

**Comment by varjolintu** [comment]
@OneOfOne Just tested it. Works normally.

**Comment by OneOfOne** [comment]
There are no errors or anything in the browser console, it just doesn't work, clicking the icon that extension puts on OTP fields does nothing.

**Comment by varjolintu** [comment]
@OneOfOne Can you do the same debugging that is made in the comments above?

Some sites can be problematic with this, and if you can select the credentials again using the popup, try that and then try to fill again. I haven't had any problems with the GitHub site.

**Comment by mustaqimM** [comment]
At last inputting TOTP codes works! I'm currently on:
```
KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
```
