### ISSUE TITLE
New credentials from the browser are not saved

### ISSUE THREAD

**Issue by apiraino** [keepassxreboot/keepassxc-browser#73]
When I perform a signup on a new site, the new credentials are not saved into KeePassXC

## Expected Behavior
After completing the signup and clicking the blinking toolbar icon, the new credentials should be immediately available when alt-tabbing to KeePassXC

## Current Behavior
New credentials are not saved

## Steps to Reproduce (for bugs)
1. Signup on any new site (e.g. [here](https://www.signupgenius.com/index.cfm?go=w.Welcome&loadsecure=true))
2. perform signup (also using suggested pwd)
3. toolbar icon blinks prompting to click to save new pwd entry into DB
4. alt-tab to KeePassXC, new credentials not saved

## Debug info
KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system:  Ubuntu 17.10 (64-bit) 
Browser: Chromium 64.0.3282.167+ Firefox 60b2
Proxy used: YES
Other: Tools > Settings > Automatically save after every change: ON

Thanks!

**Comment by varjolintu** [comment]
Did you check out the KeePassXC-Browser Passwords group? The credentials should be under it.

**Comment by apiraino** [comment]
Damn, you're right :-( Now I understand why those credentials do not pop up in my searches.

I had thrown away in the Recycle Bin the "KeePassXC-Browser Passwords" group folder months ago because at the time I didn't understand the purpose. Searching for passwords does not include the Recyble Bin folder (which makes sense, I guess).

Both these may be slightly "edge" test cases but worth clarifying in the documentation (if not already done).

Would you accept a small PR on the documentation about this?

Thank you and sorry for unintentionally "misusing" your tool and reporting false issues. I like it and want to use it to its full extent!
