### ISSUE TITLE
Fill TOTP doesn't work on codeberg.org

### ISSUE THREAD

**Issue by vanous** [keepassxreboot/keepassxc-browser#731]
Trying to get the right click → `Fill TOTP` to work on https://codeberg.org/user/two_factor , but nothing is filled in.

Generally, TOTP works for me on other sites. On Codeberg, i can right click in KeepassXC and do Show TOTP, which works (so TOTP is set up correctly).

## Steps to Reproduce (for bugs)
1. create an account on https://codeberg.org
2. enable 2FA
3. save account for codeberg and set up TOTP in KepassXC
4. try to log in

## Debug info
KeePassXC-Browser Version: 1.5.4
KeePassXC Version: 2.5.1 
Operating system: Debian Linux
Browser: Firefox 71.0 (64-bit)

Let me know if i can help in any way. And thank you for all the work!

**Comment by varjolintu** [comment]
Tested the site with both Chromium and Firefox and I had no problems with it (tested with KeePassXC 2.5.2 which is released very soon, plus used the extension version 1.5.4 and 1.5.5dev). Please ensure that the TOTP is correctly setup and you can retrieve it for the entry via KeePassXC.

**Comment by vanous** [comment]
Thank you. Codeberg uses gitea and i have found no reported issues related to it either.

> Tested the site with both Chromium and Firefox and I had no problems with it (tested with KeePassXC 2.5.2 which is released very soon,

Is there a 2.5.2 preliminary AppImage somewhere so i can test?

> plus used the extension version 1.5.4 and 1.5.5dev). Please ensure that the TOTP is correctly setup and you can retrieve it for the entry via KeePassXC.

Yes, TOTP code for Codeberg can be retrieved from KPXC and works when manually typing in or copy/paste.

I have noticed, that **after** i click the Fill TOTP menu or button ![2020-01-02_17-55](https://user-images.githubusercontent.com/3680926/71679934-112aab80-2d89-11ea-847f-95a145cd462b.png), TOTP is not filled in but KP-Browser icon shows the red question mark  ![2020-01-02_17-54](https://user-images.githubusercontent.com/3680926/71679935-112aab80-2d89-11ea-9930-e8aa7d25f73c.png) as if it didn't know which site to use.

**Comment by droidmonkey** [comment]
Do you have your TOTP entry stored in a separate database or different entry from your username/password?

**Comment by vanous** [comment]
Hmm, very strange, upon reloading database, the TOTP setup is **not** there. This appears to be an issue with KPXC, as the entry was clearly there, together with backup code and it worked (100% confirmed before). No sync could overwrite it. I will try to add TOTP and re-test codeberg.

**Comment by vanous** [comment]
Upon re-setting TOTP all works so i will close this issue now, thank you for getting back very quickly, much appreciated.

Just to add, because it looks like a `user error`: i had previously verified that both KBXC on my desktop and FreeOTP on my phone generate the same OTP code, so i am absolutely 100% sure this was done correctly before. Why was the database not saved correctly is not clear to me, but unfortunately i have seen multiple issues with various KeePass implementations over the years on Linux/Android platforms. Hopefully things will keep improving in the future.

**Comment by varjolintu** [comment]
I wonder if this is related to https://github.com/keepassxreboot/keepassxc/issues/4060.

**Comment by vanous** [comment]
Not sure. I did it via the menu... unfortunately, while re-saving, it generated more then 10 revisions, so i could not see when the info got lost...
