### ISSUE TITLE
[Feature] reopen database keyboard shortcut

### ISSUE THREAD

**Issue by heitorPB** [keepassxreboot/keepassxc-browser#732]
## Current Behavior
There are shortcuts for:
- Fill Username and Password
- Fill Password Only
- Fill TOTP
- Show Password Generator

but not to reopen database.

## Possible Solution

Implement a keyboard shortcut to reopen the database. To follow the default ones, i suggest `Alt+Shift+R`

## Debug info

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: FIrefox

**Comment by varjolintu** [comment]
For some reason the extension specifications only allow four keyboards shortcuts defined by default. So this one could be added, but the user must always define the shortcut to it manually.

**Comment by heitorPB** [comment]
What if each of those shortcuts first tried to reopen the database and only then perform their action?

**Comment by varjolintu** [comment]
That could be possible. Must test it if it works properly.

**Comment by Kratacoa** [comment]
> That could be possible. Must test it if it works properly.

Any updates?

**Comment by varjolintu** [comment]
@Kratacoa Haven't had time to do it yet.
