### ISSUE TITLE
Cannot connect to KeePassXC in Firefox

### ISSUE THREAD

**Issue by iwasherefirst2** [keepassxreboot/keepassxc-browser#734]
## Expected Behavior
I expect KeePassXC-Browser to connect do my KeePassXC database.

## Current Behavior
KeePassXC-Browser can't connect to my database
clicking on the icon
![image](https://user-images.githubusercontent.com/1765602/71764506-e9eaf000-2ee8-11ea-8815-546eb9032697.png)
shows the text

> Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings.

When I click on refresh I get

> Key exchange was not successful.

## What I tried so far
I found related issues:
#35 
#559 
and https://github.com/keepassxreboot/keepassxc/issues/1559 
I tried to follow instructions from https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900 and noticed that the folder `NativeMessagingHosts` is missing. Tried to reinstall the plugin, but folder was not created. THus, I created  the folder  `NativeMessagingHosts`  with the file `org.keepassxc.keepassxc_browser.json`  by hand with the content:

```
{
    "allowed_origins": [
        "chrome-extension://iopaggbpplllidnfmcghoonnokmjoicf/",
        "chrome-extension://oboonakemofpalcgghocfoadofidjkkk/"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "/usr/bin/keepassxc-proxy",
    "type": "stdio"
}
```
but it is still not working.

## Steps to Reproduce (for bugs)
Follow instructions at https://keepassxc.org/docs/keepassxc-browser-migration/, i.e.

1. Enable browser integration in the"Browser Integration settings
![grafik](https://user-images.githubusercontent.com/1765602/71764429-12261f00-2ee8-11ea-84e0-7eee88881e79.png)

Note: its mentioned in the instructions, that I have select all Browsers that I want to use automatically, but there is no check box to do so (see above screenshot).

2.Unlock database 

3. Click reload in KeePassXC-Browser - but still cant connect

## Debug info
No errors in JS console
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux (Ubuntu 18.04.3 LTS)
Browser: Mozilla Firefox 71.0 (64-Bit)

**Comment by varjolintu** [comment]
Have you installed Firefox via Snap? This might also be the reason: https://github.com/keepassxreboot/keepassxc-browser/issues/718. Can you confirm it's not one of those?

**Comment by iwasherefirst2** [comment]
@varjolintu I belive Firefox is already installed when installing Ubuntu? 

I just checked at "Ubuntu Software" and found it was installed there. So I removed it and installed it from terminal by 

    sudo apt-get install firefox

I restarted my machine and started Firefox (bookmarks, plugins sync etc. all remained, but I double checked and its no longer listed in  Snap Store).

Unfortunately, its still not connecting. Same error as before.

I have installed KeePass also through Snap Store. Is this an issue?

**Comment by varjolintu** [comment]
If you are using KeePassXC as a Snap, you need to use this script to install the browser:
https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh (the link is visible here: https://keepassxc.org/download/#linux)

This is needed because the Snap package cannot do the install outside the sandbox.

**Comment by iwasherefirst2** [comment]
@varjolintu omgosh. Thank you it works now.

**Comment by kekukui** [comment]
I experience the same issue in Firefox for Windows every day: even when the database is unlocked, the browser extension does not connect until I press the '`Reload`' button twice.

![image](https://user-images.githubusercontent.com/20834957/75289653-bcd20400-57ec-11ea-9f7e-e587660fa3af.png)

![image](https://user-images.githubusercontent.com/20834957/75289681-cce9e380-57ec-11ea-964d-c9a0e61d91eb.png)

**Comment by varjolintu** [comment]
@kekukui I cannot reproduce this with Win+Firefox. Please make a new issue with more detailed info.
