### ISSUE TITLE
Still saving full URL instead of domain

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [keepassxreboot/keepassxc-browser#736]
## Expected Behavior
That only the domain saves when saving an entry and the domain only option is enabled.

## Current Behavior
The full URL is always saved.

## Possible Solution
n/a

## Steps to Reproduce (for bugs)

1. Enable save domain only option
2. Save credential

## Debug info

KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: Win
Browser: Firefox

**Comment by varjolintu** [comment]
Must be a regression bug. I'll check it out. Thanks for reporting!

**Comment by varjolintu** [comment]
Actually this has been always saving the domain only when choosing Custom Fields for input fields, not when saving new credentials. So actually the info text is totally wrong.

But instead of changing the text, I'll add the feature.
