### ISSUE TITLE
Nothing happen when trying to save credentials

### ISSUE THREAD

**Issue by pgmillon** [keepassxreboot/keepassxc-browser#737]
## Expected Behavior
Prompt for new or update credentials, etc.

## Current Behavior
Nothing, no errors no nothing.

![Peek 06-01-2020 17-08](https://user-images.githubusercontent.com/715479/71831260-cbcbee00-30a8-11ea-95b7-9068f138923a.gif)

## Steps to Reproduce (for bugs)
1. Browser to any site with existing saved credentials
2. fill username/password
3. right click on the username field > KeePassXC-Browser > Save Credentials

## Debug info
KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Manjaro Linux 18.1.5
Browser: Firefox 71.0

I tried to put a breakpoint at keepass.addCredentials but it never got triggered.

**Comment by varjolintu** [comment]
Cannot reproduce. Put a breakpoint to `kpxc.contextMenuRememberCredentials()` instead (keepassxc-browser.js, line 1567). You can access the content script using the Debugging tab shown in your gif.

**Comment by pgmillon** [comment]
Hi,
Sorry but I can't find keepassxc-browser.js, I only have a keepass.js at about:devtools-toolbox?type=extension&id=keepassxc-browser%40keepassxc.org.

![image](https://user-images.githubusercontent.com/715479/71852243-92ab7200-30d8-11ea-94d8-0ca7ceacc2fe.png)

From the debugging tab I can't access anything related to the extension.
I may be missing something, sorry.

**Comment by varjolintu** [comment]
Open the Inspector from the web page itself, not by debugging the extension. It should show the content scripts:

![Screen Shot 2020-01-07 at 8 26 51](https://user-images.githubusercontent.com/24570482/71873299-7f73c300-3127-11ea-9a60-c37825b4bb3e.png)

**Comment by pgmillon** [comment]
Hi, I had to enable debugging of extensions within the dev tools (not enabled by default).
By debugging I found out that the notification options were disabled (no idea why).
I re-enabled them and obviously problem is now gone.
Thanks for the assist.
