### ISSUE TITLE
About Specified credential fields

### ISSUE THREAD

**Issue by extrajoker** [keepassxreboot/keepassxc-browser#74]
Page URL
https://www.jpb.co.jp/xxx/AAA.do
https://www.jpb.co.jp/xxx/BBB.do
https://www.jpb.co.jp/xxx/CCC.do
...

The place of AAA, BBB, CCC, ... is random.
It is impossible to register everything.

I want to register Page URL,
https://www.jpb.co.jp/xxx/

**Comment by varjolintu** [comment]
This is because I made a change to the code that uses the actual URL for specified credential fields, not just the host. I need to find a solution that you could use both options at the same time. Maybe a checkbox to the settings page if you want to use the exact URL.

**Comment by droidmonkey** [comment]
Add support for wildcard

**Comment by extrajoker** [comment]
I think so too.
Can I edit Page URL fields?

**Comment by jankatins** [comment]
Yes, you can put an url of domain.com inside and it will matxh www. And login.
