### ISSUE TITLE
100% CPU usage in both Firefox and Chrome on specific page

### ISSUE THREAD

**Issue by ergo** [keepassxreboot/keepassxc-browser#745]
## Expected Behavior
Normal cpu usage expected on login page.

## Current Behavior
Constant 100% CPU in the tab in both Firefox and Chrome during password screen.

## Steps to Reproduce (for bugs)

Visit: https://system.aliorbank.pl/sign-in
using login 8141111111

## Debug info
KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 71.0/ Chrome 79.0.3945.88

**Comment by varjolintu** [comment]
That page runs over 2000 mutations at once, which is huge. I'll try to see what I can to to reduce the CPU load.

**Comment by ergo** [comment]
@varjolintu Thanks, I'm perfectly fine with disabling the plugin on that page but even with this specific domain is set to "disable all features" it still seems to hog.

**Comment by varjolintu** [comment]
The PR that's linked to this issue solves that bug. And it also makes this site usable without the 100% CPU load.

**Comment by ergo** [comment]
@varjolintu Thanks, awesome work, is there a chance for a release in near future?

**Comment by varjolintu** [comment]
Two more PR's to merge for the next release. So, it's soon.

**Comment by ergo** [comment]
Hello I would like to reopen this ticket, since the page from above is still hanging firefox for me - even if I disable the functionality completely. I have https://system.aliorbank.pl/ and https://aliorbank.pl/ blocked with "disable all features".

Debug info:

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 78.0.1 (64-bit)
