### ISSUE TITLE
Convert FF-Addon configuration site in to about:addons

### ISSUE THREAD

**Issue by tradewatcher** [keepassxreboot/keepassxc-browser#747]
Why don't move the Settings "moz-extension://f1bfebf8-0337-4feb-a6fb-d0f8aeb18ffd/options/options.html" in to about:addons "Options" like most addons? 

Firefox 72 KeepassXC Addon 1.5.4.

**Comment by varjolintu** [comment]
What do you mean exactly? `about:addons` show a burger menu for each extension, and the options page is opened normally if you click Preferences.

**Comment by tradewatcher** [comment]
![Options](https://user-images.githubusercontent.com/32960881/72059982-5f810280-32d3-11ea-9b4a-7c719c97c597.jpg)

**Comment by varjolintu** [comment]
It's intended behaviour that we open the options page inside a normal browser tab instead of integrating it to the addon page. You can still access the options using the hamburger menu and selecting Preferences.
