### ISSUE TITLE
Firefox account login not recognize

### ISSUE THREAD

**Issue by Tanerx** [keepassxreboot/keepassxc-browser#748]
Hello.
Kepassxc not working with https://accounts.firefox.com/

Firefox 72.0.1 (64 bit)
Osx 10.14.6 (18G1012)
KeePassXC-Browser 1.5.4
KeePassXC 2.5.2

**Comment by varjolintu** [comment]
Mozilla has hardcoded Firefox so that certain sites are not allowed to run any content scripts. Meaning all extensions are disabled for modifying anything on that page.

See https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts for the full URL ignore list.
