### ISSUE TITLE
How to connect proxy to KeePassXC when Firefox started as sandboxed user?

### ISSUE THREAD

**Issue by dr-diem** [keepassxreboot/keepassxc-browser#749]
## Expected Behavior
_N.B. I guess this should be desired behaviour rather than expected behaviour since this is a request for info rather than a bug report._

I would like to work out how to allow a sandboxed Firefox process (and therefore the child keepassxc-proxy process) open its socket to a KeePassXC process owned by a non-sandboxed user. 'Sandbox' in my case simply means executing Firefox as alternate, low-privilege, user while granting it the right to interact with the X session of the non-sandboxed user (per this howto: https://wiki.gentoo.org/wiki/Simple_sandbox ).

## Current Behavior
Though KeePassXC is running and the database unlocked, the add-on reports `Message encryption failed. Is KeePassXC running?` and then upon clicking Reload `Key exchange was not successful.`

I am assuming this is because  KeePassXC is running as a different user. I admit ignorance of the Unix socket API; is there a way to change ownership of the socket (or perhaps the group of KeePassXC?) such that the connection can be made?

Thanks for any pointers you might have.

## Possible Solution
If you could point me to where keepassxc-browser outputs errors (or how I could configure it to do so) this might help me dig towards a workaround?

## Steps to Reproduce (for bugs)
1. Set up sandboxed Firefox as per this guide: https://wiki.gentoo.org/wiki/Simple_sandbox
2. Attempt to connect to KeepassXC as normal

## Debug info
_No relevant JS console messages to include_
KeePassXC - 2.4.3
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
So the keepassxc-proxy still opens normally inside the sandboxed Firefox? The socket is normally opened to a standard temporary location, but you can override it using `XDG_RUNTIME_DIR`.

keepassxc-proxy doesn't have any output for errors, sorry. The only way to see what happens is to use `strace`.

**Comment by dr-diem** [comment]
Yes, I see keepassxc-proxy running as a child of Firefox. What is the socket's name? I'm sure I can work out my system's standard location for socket 'files'. `strace` eh? I'll read up on using that. Beyond that, how does the proxy know what to look for? As in, how does it identify the KeepassXC process in order to open the socket to it?

**Comment by varjolintu** [comment]
The socket name is `kpxc_server`. KeePassXC is the one that creates and listens to it. `keepassxc-proxy` only sends a message to that socket and waits or a reply.

**Comment by dr-diem** [comment]
I couldn't find `kpxc_server` anywhere in the filesystem, but did find `/tmp/keepassxc.socket` which seems to fit the bill! It was permission 700 for my user account, so I tried changing it to 777 (yes, I know that this is a huuuge security hole, done for test purposes only!) but still my sandboxed keepassxc-proxy failed to get a connection. To date I have not managed to sniff the socket in use with `strace`, `netstat` or `ss`, even from keepassxc-proxy running in Firefox under my account rather than my sandbox user. I'll report back if I work out anything further; in the meantime I hope someone else trying to achieve the same thing manages to find a solution :o)
