### ISSUE TITLE
KeepassXC browser doesn’t connect with KeepassXC 2.5.2

### ISSUE THREAD

**Issue by user67x** [keepassxreboot/keepassxc-browser#751]
Hello,

I have installed the last version of KeepassXC : the 2.5.2 (msi format) to use my password database
I have activated too the KeepassXC-Browser v1.5.4 on a Firefox 72.0.1 on Windows 10.
I have activated the browser integration in parameter in KeepassXC

When I clic on the extension that appear in my Firefox module's bar, I have this message:
https://pix.toile-libre.org/?img=1578924202.png
![2020-01-13_14-13-52](https://user-images.githubusercontent.com/13274746/72258806-4055de00-360f-11ea-9881-ccf2ac45f45d.png)

In parameter, I have this message:
![2020-01-13_14-17-32](https://user-images.githubusercontent.com/13274746/72258953-a2164800-360f-11ea-8cca-bfa2926af4d0.png)

## Debug info

KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: Windows 10
Browser: Firefox

I don’t know why the integration doesn’t work.

Regards

**Comment by varjolintu** [comment]
Please check the https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by user67x** [comment]
I have read the page you give and I'm still trying to figure it out.
On the other hand, under Chrome, I have no problem and the extension finds my instance of KeepassXC well.

**Comment by varjolintu** [comment]
Then please make sure the Firefox registry entries for NativeMessagingHosts exists and it points to a file that exists. Plus the path inside that file must point to keepassxc-proxy.exe.

Not sure why Chrome works out-of-the-box but Firefox doesn't.

**Comment by user67x** [comment]
Sorry, I have found what was the problem: I have desactivated this option in Firefox and now it works like Chrome !
![2020-01-13_15-51-14](https://user-images.githubusercontent.com/13274746/72265340-a6952d80-361c-11ea-9e89-d78a76d0caf7.png)

**Comment by keizah7** [comment]
https://github.com/keepassxreboot/keepassxc/discussions/7669#discussioncomment-6694506
