### ISSUE TITLE
select credentials also by subdomain

### ISSUE THREAD

**Issue by jucajuca** [keepassxreboot/keepassxc-browser#752]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

It would be great if the browser extension could select credentials also by subdomain. For example

myservice.mydomain.com
otherapp.mydomain.com
awesome.mydomain.com
great.mydomain.com

## Desired Behavior
[NOTE]: # ( Tell us how the new feature should work, be specific )
The problem is that if I have many subdomains, I get a large list of passwords.

## Possible Solution
[NOTE]: # ( Not required, but suggest ideas on how to implement the addition or change )
Add option or make the selection including subdomains.

**Comment by varjolintu** [comment]
And your enty URL consists that subdomain? If so, it won't match the other ones, unless your entry URL is `mydomain.com`.

**Comment by droidmonkey** [comment]
Make sure you are running 2.5.2

**Comment by varjolintu** [comment]
@jucajuca Please don't delete the issue template. Can you tell us what version you are running?

**Comment by jucajuca** [comment]
The following debug info can be used:

KeePassXC - 2.5.1
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 71.0

I'll upgrade KeePassXC to 2.5.2 and try again

**Comment by jucajuca** [comment]
2.5.2 solved the issue.
thx!
