### ISSUE TITLE
No chance to save credentials from KeePassXC-Browser

### ISSUE THREAD

**Issue by Skeeve** [keepassxreboot/keepassxc-browser#755]
## Expected Behavior

When logging in to a site I would like to be able to save my credentials. 

## Current Behavior

I tried on gmx.net and on webmailer.hosteurope.de and both do not give me any option to save my credentials.

On gmx.net I see a banner at the top popping up for a fraction of a second when I log in, but I do not have any chance at all to reach one of the buttons, let alone read what the texts say.

On webmailer.hosteurope.de there is no banner at all and nothing is save in my KeePassXC Database.

## Possible Solution

Could the icon in the username field, which activates the "fill from KeePassXC" check whether or not the fields are already filled and ask the user whether he wants to update/save the credentials from the fields to the DB? 

## Steps to Reproduce

1. Go to https://www.gmx.net/ or https://webmailer.hosteurope.de/login.php
2. Enter your credentials
3. log in

## Context

The Database is stored on a windows share, mounted on a Mac.

## Debug Info

KeePassXC - 2.5.2
KeePassXC-Browser - 1.5.4
Operating system: MacIntel
Browser: Mozilla Firefox 72.0 

Libraries:
???

Operating system: MacOS 10.14.6
CPU architecture: Intel
Kernel: ???

Enabled extensions:

For testing I disabled all extension except for KeePassXC-Browser

**Comment by varjolintu** [comment]
For the first site it's probably an extra redirect which needs to be handled. If you enter wrong credentials, the banner shows normally.

With the second site wrong credentials just launches an error page. Using Save Credentials from the context menu works.

I need to create test accounts for both sites and try this again later.

**Comment by Skeeve** [comment]
Thanks a lo @varjolintu. I always tried the Context menu, but always when the pointer was on the KeePassXC icon in the username field because that was the most logical place for me. But there is nothing in the context menu for KeePassXC-Browser. See:

![image](https://user-images.githubusercontent.com/725404/72516071-594dd180-3851-11ea-8e30-4636bf3838f8.png)

When moving away from the icon, it works:

![image](https://user-images.githubusercontent.com/725404/72516158-80a49e80-3851-11ea-879b-6ab4469169f9.png)

**Comment by varjolintu** [comment]
The context menu works only with input fields, not on images.

**Comment by Skeeve** [comment]
When you explain it, it's obvious ;) But until then it wasn't obvious to me. Sorry for the confusion.

**Comment by droidmonkey** [comment]
I've found that the banner goes away very easily lately. It should survive a couple redirects and subdomain name changes.

**Comment by varjolintu** [comment]
I'll make the support for extra redirects when I have the time.

**Comment by matthiasdusch** [comment]
I can also confirm the issue with the fast redirect on several pages.
And I just created an account with a generated password and "secure answer" which I was not able to safe in the database because of that...

I came here to suggest a feature which allows to safe credentials before pressing "register" or "login". Turns out this already exists with the context menu. That's great!
Maybe it would be nice to "advertise" this feature a bit more or make it easier accessible like through the button in the firefox-menu. 

Anyway thanks for your work!

**Comment by swdee** [comment]
I also experience the same problem when logging in and the popup "save credentials" dialog disappears before I have time to read or click on the buttons due to the website being logged in doing redirects.

**Comment by georgehank** [comment]
Yup, something changed *somewhere* (I suspect it could be Chrome), but the banner disappears on correct password before you have any chance of interacting.

Given that I just changed my password and then couldn't enter the change (or rather, new account)… that's bad.

**Comment by varjolintu** [comment]
Hang on tight. We are releasing the next version soon.
