### ISSUE TITLE
Bug: Impossible connection to KeepassXc, Key exchange failed

### ISSUE THREAD

**Issue by zZ-Top59** [keepassxreboot/keepassxc-browser#757]
## Debugging informations:
**KeePassXC - 2.3.4**
Opened database file stored in Google Drive, in a folder shared with Linux, mounted under:
mnt/chromeos/GoggleDrive/MyDrive/Applications/KP2A/[filename].kdbx
The database file is read/write OK.
In KeepassXc setup, the web browser integration with Google Chrome is activated.
**KeePassXC-Browser - 1.5.4**
**Operating system: Linux x86_64 (within Chrome OS)**
**Browser: Chrome/Chromium 78.0.3904.106**

## Expected Behavior
Seamless connection of KeePassXC-Browser extension to the KeePassXc database file

## Current Behavior
Message retruned by the extension:
"Unable to connect to KeePassXC. Make sure browser integration is enabled in KeePassXC settings."
And after reloading:
"The key exchange failed."

## Possible Solution
Well, I just understand that the browser integration can't find the database file mounted under Linux partiton hosted in Chrome OS file system.

## Steps to Reproduce (for bugs)

1. Under Chrome OS: Install Linux;
2. Under Linux: Install KeePasssXc;
3. In Google Drive: Copy the KeePassXc database file in a shared folder with Linux;
4. In KeePassXc: Open the database file stored in Google Drive;
5. In KeePassXc Setup: Activate the browser integration in setup;
6. In Google Chrome: Install KeePassXC-Browser extension;
7. What else? Should work this way...

**Comment by varjolintu** [comment]
Upgrade to KeePassXC 2.5.2.
