### ISSUE TITLE
Conflict with default TOTP keyboard shortcut (Alt+Shift+T)

### ISSUE THREAD

**Issue by articlecat** [keepassxreboot/keepassxc-browser#759]
The keyboard shortcut Alt+Shift+T is currently the default shortcut for filling in the TOTP code. On a Linux system running GNOME, typing Alt+Shift+T into Firefox toggles the Tools menu in the browser instead of triggering the KeepassXC-Browser extension.

One possible solution would be to make the default TOTP shortcut something that doesn't conflict with a browser menu shortcut, such as Alt+Shift+O.

Another solution would be to use a different combination than Alt+Shift. Ctrl+Alt would work for all of the default combinations (Ctrl+Alt+U, Ctrl+Alt+I, Ctrl+Alt+T, and Ctrl+Alt+G). Ctrl+Shift is not ideal, because Ctrl+Shift+T restores the last closed tab in Firefox.

KeepassXC-Browser version: 1.5.4

Related: #606

**Comment by varjolintu** [comment]
Does this happen only with Chrome? You can always configurate the keyboard shortcuts by yourself.

Defining these shortcuts is not easy. Quite often they collide with something pre-defined.

Btw, you can also fill the TOTP by using the new icon.

**Comment by articlecat** [comment]
This only happens in Firefox. Chrome doesn't have a default keyboard shortcut for TOTP, and it's unset.

I've already reconfigured the shortcuts on my browsers, and this suggestion is intended to benefit new users of KeepassXC-Browser.

**Comment by varjolintu** [comment]
Sorry, I meant does this happen only with Gnome? My brains switched the word.

**Comment by articlecat** [comment]
I just confirmed that this also happens in KDE. Firefox opens the Tools menu when Alt+Shift+T is pressed, which overrides the default keyboard shortcut in KeepassXC-Browser. The shortcut is inherent to Firefox, and not GNOME.

There's no conflict on macOS (since menus can only be selected with keystrokes after typing Ctrl+F2). I don't have a Windows computer handy at the moment.

**Comment by varjolintu** [comment]
I guess it would be enough to change the Linux shortcut. Of course we must check Windows behaviour also.

**Comment by articlecat** [comment]
I've tested this on Windows, and I can confirm that Alt+Shift+T also triggers the Firefox Tools menu instead of the KeepassXC-Browser action on Windows.

**Comment by varjolintu** [comment]
Thank you for testing this!

**Comment by varjolintu** [comment]
> Another solution would be to use a different combination than Alt+Shift. Ctrl+Alt would work for all of the default combinations (Ctrl+Alt+U, Ctrl+Alt+I, Ctrl+Alt+T, and Ctrl+Alt+G). Ctrl+Shift is not ideal, because Ctrl+Shift+T restores the last closed tab in Firefox.

This will not work because:

> Note: All key combinations must include either Ctrl* or Alt. Combinations that involve Ctrl+Alt are not permitted in order to avoid conflicts with the AltGr key.
