### ISSUE TITLE
Can't connect between FF 72.01 & Keepassxc 2.5.3

### ISSUE THREAD

**Issue by arnauldb** [keepassxreboot/keepassxc-browser#760]
Hello,

Suddenly (this morning) I can't connect between the browser (Firefox) and Keepassxc. Everything was working fine yesterday and I didn't update anything between.

Thank you as I don't know where to look for to solve this.

## Debug info

KeePassXC - 1.5.4
KeePassXC-Browser - 2.5.3
Operating system: Linux Mint 18.3 Sylvia
Browser: Firefox

**Comment by varjolintu** [comment]
Check: https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by arnauldb** [comment]
Thank you. It worked again today. For no reasons...
