### ISSUE TITLE
One Entry in KeePassCX menu for each URL

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc-browser#761]
## Summary
I recognized that for entries where I have multiple URLs in KeePassXC stored, there are also multiple entries in the KeePassXC menu (that is shown in the login fields).

## Details
In KeePassXC I have some entries that have multiple URLs in one entry.
For example the website "Meine Allianz".
Here I have on the page "Entry" the following URL stored: https://meine.allianz.de/
On the page "Browser Integration" I have the following URLs stored:
- https://allianz.de
- https://cim.allianz.de/

When I open the URL https://meine.allianz.de/ in Chrome then the URL changes to:
https://cim.allianz.de/ui/login/de/allianz/start?....
I truncated the URL at the end.

If I click on the KeePassXC icon in the field "Username" I see the same entry two times:

![image](https://user-images.githubusercontent.com/8037790/73609410-980fb580-45cd-11ea-862c-7a68103fdf78.png)

For Amazon I also see two entries for my account.
For the Amazon Account of my wife I see 3 entries.

![image](https://user-images.githubusercontent.com/8037790/73609453-12d8d080-45ce-11ea-8b7b-ca9d87f78cd4.png)

## Expected Behavior
I expect that I see only one entry for each account.
So for Allianz I see no popup menu (where I select the account) because there is only one account available.
For Amazon I expect to see only two entries: my account and the account of my wife.

## Debug info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC-Browser - 1.5.4
Browser: Chrome Version 79.0.3945.130 (Offizieller Build) (64-Bit)

**Comment by droidmonkey** [comment]
Good find!

**Comment by varjolintu** [comment]
The next release seems already quite big, but let's squash some bugs also. I'm trying to fix this soon.

**Comment by OLLI-S** [comment]
Maybe I should apply for a job in the team as
- creativity manager (the guy with many ideas)
- ux expert
- bug hunter
- most common stupid user 

:stuck_out_tongue_winking_eye:

**Comment by droidmonkey** [comment]
We don't pay very well :wink:

**Comment by OLLI-S** [comment]
I help for free because I love KeePassXC.

**Comment by varjolintu** [comment]
This actually needs a fix to the KeePassXC side also. But for now, I'll just hide any duplicates appearing as a dirty workaround.

**Comment by OLLI-S** [comment]
@varjolintu You are amazing, that you created a fix (workaround) so quickly.
Can't wait to test this when the update is released.
