### ISSUE TITLE
Password is not being refreshed after creating a new one in KeePassXC

### ISSUE THREAD

**Issue by Beneter** [keepassxreboot/keepassxc-browser#765]
I am changing passwords on existing accounts and using the KeePassXC-GUI password generator (instead of the one of keepassxc-browser) because I want to configure the generation settings. So here are my steps:
1. Login with current credentials through keepassxc-browser
2. Open "change password"-dialogue
3. Fill the "current password" form through keepassxc-browser
4. Switch to KeePassXC-GUI
5. Generate a new Password for this entry in KeePassXC-GUI
6. Switch to Browser
7. Fill the "new password" form through keepassxc-browser

## Expected Behavior
The freshly generated password is inserted in the "new password" form.

## Current Behavior
The old password is inserted in the "new password" form.
This might remain unnoticed until trying to login again.

## Possible Solution
1. Automatically send a refresh from KeePassXC-GUI to keepassxc-browser.
2. Automatically refresh keepassxc-browser every time a password is being inserted.
3. Add a refresh button to keepassxc-browser.
4. Allow change of generation settings in keepassxc-browser.

I guess solution 1 would be preferred but a bit harder to implement then solution 2.
I have not inspected the code yet but I imagine keepassxc-browser currently grabs all matching entries when the website loads, right?

## Workaround
A possible but unpleasant workaround is to perform steps 1 - 6, then lock the database via keepassxc-browser and unlock it again.

## Debug info
KeePassXC - 2.3.4
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

**Comment by droidmonkey** [comment]
This is a good catch but might run into trouble because of the way the browser integration works. The browser has no knowledge of changes in KeePassXC and KeePassXC has no knowledge that the browser needs to be sent new information.

**Comment by Beneter** [comment]
Added a workaround in the initial post.

**Comment by Beneter** [comment]
Added a workaround in the initial post.

@droidmonkey This would only affect solution 1 right?

**Comment by varjolintu** [comment]
The best workaround for now is to reload the page. This causes the extension to retrieve credentials.

**Comment by Beneter** [comment]
@varjolintu But this also removes the content of the "current password" field...

**Comment by varjolintu** [comment]
This should be already fixed.

**Comment by Beneter** [comment]
@varjolintu I just checked and I am still facing the same issue with version 1.7.8.1.

**Comment by varjolintu** [comment]
Let's re-check this then.

**Comment by quicktrick** [comment]
I can confirm the same issue with 1.7.8.1.  It also needs to be refreshed after renaming the entry.  What's more, if you save the new entry in one browser (e.g. Opera) and then try to use it in another one (e.g. Chrome), you cannot see the new entry until you reconnect to the database (i.e. refresh it).

**Comment by varjolintu** [comment]
Still having the problem?

**Comment by quicktrick** [comment]
The problem seems to be gone. Thanks for your concern.
