### ISSUE TITLE
Improvement: No "Fill TOTP from KeePassXC" in postal/zip_code fields

### ISSUE THREAD

**Issue by bwbroersma** [keepassxreboot/keepassxc-browser#768]
See
![image](https://user-images.githubusercontent.com/4252918/74044580-8e21f400-49cb-11ea-8820-695977c227c0.png)

When there is a `<input name=postal_code id=zipcode>` where `code` is included in name or id, the "Fill TOTP from KeePassXC" is triggered.

## Expected Behavior
No "Fill TOTP from KeePassXC" on zipcode or postalcode fields.

## Current Behavior
"Fill TOTP from KeePassXC" on postal or zipcode fields.

See https://github.com/keepassxreboot/keepassxc-browser/blob/b01ab1e8352d16ef7ea17faca1bdb05d6c856c2a/keepassxc-browser/content/keepassxc-browser.js#L9-L17
and
https://github.com/keepassxreboot/keepassxc-browser/blob/b01ab1e8352d16ef7ea17faca1bdb05d6c856c2a/keepassxc-browser/content/keepassxc-browser.js#L996-L998

## Possible Solution
Change to regex with some negative check:
```javascript
/^(((?!zip|post).)*code.*)|(.*(2fa|auth|challenge|mfa|otp|token).*)$/i
```
The `otp` and `mfa` are very short identifiers, see:
```bash
$ aspell -d en dump master | aspell -l en expand | grep -iE 'otp|mfa'
```
Maybe a score calculation is possible:
* higher score if it's a separate word
* higher score if `type=number`
* higher score if `maxlength=6` (or 8)

Or skip this all and just rely on [`autocomplete=one-time-code`](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete)

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 74.0

**Comment by varjolintu** [comment]
Support for `autocomplete=one-time-code` has been already added with PR: https://github.com/keepassxreboot/keepassxc-browser/pull/723.

Some negative check might indeed be needed because most sites are not using that autocomplete property at all.

**Comment by bwbroersma** [comment]
More stuff going wrong:
https://digid.nl/inloggen_app
```html
<input type="text" autocomplete="off" class="code_box code_box_length_4" placeholder=" " id="app_verification_code_verification_code_field_0" maxlength="1">
```
is recognized as TOTP (note the `maxlength="1"`)
![image](https://user-images.githubusercontent.com/4252918/75157232-faaf2980-5713-11ea-969d-60aeac3c5340.png)


The password field in https://digid.nl/inloggen_basis is also recognized as TOTP because of:
```html
<input hide_required_indicator="true" class="form__item__field" placeholder=" " autocomplete="off" data-required="true" type="password" name="authentication[password]" id="authentication_password">
```
![image](https://user-images.githubusercontent.com/4252918/75156917-6644c700-5713-11ea-85a9-b9b46961d892.png)

Also filling in a SMS token on https://digid.nl/sms_controleren triggers the TOTP again:
```html
<input type="number" autocomplete="off" class="code_box code_box_length_6" placeholder=" " id="smscode_smscode_field_0" maxlength="1">
```
![image](https://user-images.githubusercontent.com/4252918/75157102-c0458c80-5713-11ea-840b-3a41ac251c3d.png)

**Comment by varjolintu** [comment]
Too short `maxlength` is already fixed for the next release.

What makes using the regex difficult, is that for example `<input name="code" id="zipcode">` is accepted even if the `id` has `zip` before `code`, but `<input name="zipcode" id="code">` is not accepted. So even the order messes it up and that cannot be used as it is.

The TOTP icon on the password input field missed a check for `type === 'password'`, so that is something that we can fix easily.

**Comment by varjolintu** [comment]
I made a PR that should solve this issue. Instead of one big regex I just used a simpler one and checked both name and id before creating the icon. This should cover all possible situations.
