### ISSUE TITLE
Small red message flickers when opening popup

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#77]
## Expected Behavior

No flickering, but "smooth" opening of the popup without visual distractions.

## Current Behavior

![redthing](https://user-images.githubusercontent.com/11966684/37431425-84821b24-27d5-11e8-9b6d-9227a5be8bdb.gif)

## Possible Solution

Show such a warning message later.

Or introduce a less visually distracting "loading" message or so.

## Steps to Reproduce (for bugs)

1. Open the popup.

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Linux
Browser: Firefox
Proxy used: yes

**Comment by varjolintu** [comment]
No so smooth indeed.. I reproduced this so working on it.
