### ISSUE TITLE
KeepassXC Browser Integration non-existent

### ISSUE THREAD

**Issue by Q3p6v9j7PX7XBjSj9xgC5LJViFxuKqg5cpfg93x** [keepassxreboot/keepassxc-browser#770]
## Expected Behavior
1. Enable browser integration in KeepassXC
2. Download KeepassXC Browser in Firefox
3. Connect database

## Current Behavior
1. Enable browser integration in KeepassXC
2. KeepassXC instructs to obtain special script for new version on keepassxc.org
3. There is no special script on keepassxc.org
4. Documentation on keepassxc.org says to download "KeePassHttp-Connector", nothing about any script

## Possible Solution
1. Provide accurate instructions and update your documentation when it becomes invalid?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
So you are using Firefox as a snap? Install it from your package manager instead.

If you are using KeePassXC as a snap, the helper script is available at https://keepassxc.org/download/ (the KeePassXC-Browser Helper Script link).

Where exactly is KeePassHttp-Connector mentioned?

**Comment by phoerious** [comment]
Your KeePassXC version is vastly outdated. Please upgrade to 2.6.3.
