### ISSUE TITLE
Import Settings no effect

### ISSUE THREAD

**Issue by Carsten3000** [keepassxreboot/keepassxc-browser#771]
## Expected Behavior
I can manually sync my KeePassXC Browser stettings between multiple clients.

## Current Behavior
I can export the stettings into a .json file. File content looks good.
The import results in no action.

## Steps to Reproduce (for bugs)
1. create defined-custom-field definition
2. export stettings 
3. delete defined-custom-field defintion
4. import stettings 

Definition is still missing

## Debug info
JavaScript console message:

Error: Not a KeePassXC-Browser settings file. (options.js.:186)
Exported keepassxc-browser_settings.json file:
```json
{
    "autoCompleteUsernames": true,
    "autoFillAndSend": false,
    "autoFillSingleEntry": false,
    "autoReconnect": false,
    "autoRetrieveCredentials": true,
    "autoSubmit": false,
    "checkUpdateKeePassXC": 3,
    "defaultGroup": "",
    "defaultGroupAlwaysAsk": false,
    "defined-custom-fields": {
        "https://www.amazon.de": {
            "fields": [],
            "password": null,
            "username": "ap_email"
        }
    },
    "saveDomainOnly": true,
    "showLoginFormIcon": true,
    "showLoginNotifications": true,
    "showNotifications": true,
    "showOTPIcon": true,
    "sitePreferences": [],
    "usePasswordGeneratorIcons": false
}
```

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Win
Browser: Chrome/Vivaldi

**Comment by varjolintu** [comment]
I found this error yesterday, and I'm providing a fix today. The next version will have it.
