### ISSUE TITLE
Icons can overlap text

### ISSUE THREAD

**Issue by slayer** [keepassxreboot/keepassxc-browser#775]
Icons in small inputs overlap text

![2020-02-17_14-47](https://user-images.githubusercontent.com/57521/74655569-39cdff80-5195-11ea-8ed5-28e8578f8f67.png)

## Steps to Reproduce (for bugs)
go to sites with small inputs

## Debug info
The following debug info can be used:

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Chrome/Chromium 79.0.3945.130

**Comment by varjolintu** [comment]
Already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/716. Wait for the next version.
