### ISSUE TITLE
Passphrase for database is displayed in clear text in the browser extension menu

### ISSUE THREAD

**Issue by wesselma** [keepassxreboot/keepassxc-browser#776]
## Expected Behavior

Keypassxc brower should never show my database passphrase in clear text.

## Current Behavior

When I press the keypassxc browser extension button, the popup shows my database passphrase in clear text as a connection identifier to the database.

## Steps to Reproduce (for bugs)

1. start keypasssxc
2. enter passphrase to unlock database
3. start chrome browser with keypassxc browser installed
4. click on keypassxc browser icon. My German version displays
"KeePassXC-Browser ist mit KeePassXC verbunden und wurde mit dem folgenden Bezeichner konfiguriert: <here is my personal secret database passphrase in clear text and even highlighted in greeen>"

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: MacIntel
Browser: Chrome/Chromium 79.0.3945.130

**Comment by droidmonkey** [comment]
You made the identifier for your database your master password??

Just remove all connections:
![image](https://user-images.githubusercontent.com/2809491/74678300-9c6cce80-5188-11ea-9585-693af3e7fea0.png)

Then re-connect the browser extension to your database and **do not use your password**!

**Comment by wesselma** [comment]
ah thanks... i guess i'm one of those users... maybe a warning dialog could
help guys like me not to do such stupid things?

sorry for the inconvenience

cheers
markus

Jonathan White <notifications@github.com> schrieb am Mo. 17. Feb. 2020 um
19:23:
