### ISSUE TITLE
Auto-fill does not work for Amazon AWS login

### ISSUE THREAD

**Issue by carestad** [keepassxreboot/keepassxc-browser#778]
## Expected Behavior

Icon in input fields appearing, filling in username and password to work.

## Current Behavior

Only username is filled, but only works via context menu.

## Possible Solution

Not sure how to fix this. I can't seem to manually edit the custom inputs in the extension's settings though. Maybe if I knew how they were stored (selectors perhaps?) I could maybe adjust them so they would work.

## Steps to Reproduce (for bugs)
1. Go to [console.aws.amazon.com](https://console.aws.amazon.com)
2. Notice that username is not auto-filled (if you have the `Automatically fill in single-credential entries` setting enabled) or no KeepassXC icon is available in the username input
  2.1. Right clicking and using the context menu to select `Fill username and password` fills the input
  ![image](https://user-images.githubusercontent.com/65263/74845954-0378b780-5330-11ea-85f2-35459a5766a6.png)
3. When clicking `Next` and the password field appears, notice that password won't auto-fill (if that setting is enabled though), only the password generator icon is present, and the context menu options `Fill username and password` _and_ `Fill password only` do nothing.
4. Trying to set custom inputs for username/password does not work as the username and password fields are not shown at the same time.
5. Clicking the `Add username-only option for the site` does not help either.

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Mozilla Firefox 73.0 (the exact same happens in Chrome/Chromium 80.0.3987.116)

**Comment by varjolintu** [comment]
Add the following URL to extension's Site Preferences settings and enable Username-only detection: `https://signin.aws.amazon.com/*`

**Comment by carestad** [comment]
> Add the following URL to extension's Site Preferences settings and enable Username-only detection: `https://signin.aws.amazon.com/*`

That helps with the icon showing up and the username being filled automatically, but the password won't fill at all on the next step though.

**Comment by varjolintu** [comment]
For some reason the fill icon shows on the username field even when it's not available anymore. Filling the password works only if you have `https://amazon.com` in your entry URL because the subdomain is not the same for the password input site. It changes to plain `www.amazon.com` after the username input. You can also add the URL to the Additional URL's so you don't have to create another entry.

The user input field has an attribute `readonly`. Adding support for ignoring those fields fixes the problem. Making the required PR right away. Thanks for finding the bug!

**Comment by varjolintu** [comment]
After adding the Additional URL you should be able to fill the password from the context menu as a workaround.

**Comment by carestad** [comment]
> For some reason the fill icon shows on the username field even when it's not available anymore. Filling the password works only if you have `https://amazon.com` in your entry URL because the subdomain is not the same for the password input site. It changes to plain `www.amazon.com` after the username input. You can also add the URL to the Additional URL's so you don't have to create another entry.

Weird. I tried changing the entry URL to just `https://amazon.com` but that did not seem to help on the password-filling. The original URL I had for my entry was `https://signin.aws.amazon.com`.

> The user input field has an attribute `readonly`. Adding support for ignoring those fields fixes the problem. Making the required PR right away. Thanks for finding the bug!

Nice! Thanks for the quick response!

> After adding the Additional URL you should be able to fill the password from the context menu as a workaround.

Strange. I am not able to fill the password by doing this though.

Just for your reference, this is the entry I have:

```
Username: foo@bar.com
Password: *****
URL: https://signin.aws.amazon.com
Additional URLs: https://amazon.com/
```

Having the additional URL makes the entry list twice, btw: 

![image](https://user-images.githubusercontent.com/65263/74866399-1f418500-5353-11ea-9ff8-40e87eb8db3f.png)

**Comment by varjolintu** [comment]
Showing the entry list twice is already fixed for the next release. Using the context menu should fill the password if the Additional URL is set. It works for me.

**Comment by carestad** [comment]
> Showing the entry list twice is already fixed for the next release. Using the context menu should fill the password if the Additional URL is set. It works for me.

That's strange.

I do however notice that if I click Amazon's `Sign in to a different account` link under the password input, which shows the username input again, the filling of both username and passwords work after that. But on a hard refresh of the login page, it won't(?).

Could it be some settings that I have turned on/off that you don't?

![image](https://user-images.githubusercontent.com/65263/74868095-0be3e900-5356-11ea-8b67-3516420b8475.png)

And from KeepassXC:

![image](https://user-images.githubusercontent.com/65263/74868156-1d2cf580-5356-11ea-9cc9-96ab29f43ea0.png)

![image](https://user-images.githubusercontent.com/65263/74868177-21f1a980-5356-11ea-9e86-bde673234d6b.png)

**Comment by varjolintu** [comment]
The settings are be fine, but you could try to disable "Return only best-matching credentials" and try again.

I tested the login successfully with Firefox & stable extension version, and Chromium with the upcoming 1.5.5.

**Comment by carestad** [comment]
I am having problems with the AWS login again now. Username is filled out, but password refuse to be filled even if I right-click inside the input and chose `Fill password only`. `Fill Username and Passowrd` does not work either. `Fill TOTP` does actually work in the password input.

**Comment by droidmonkey** [comment]
I also experience this and couldn't get it to work no matter what. I think Amazon is to blame though.

**Comment by varjolintu** [comment]
Strange. It works for me. Please note that the URL changes at the password screen. You'll have to use them both in your entry.

**Comment by carestad** [comment]
I do not see that the URL changes though? At least not the domain. Are we looking at the [same AWS login](https://signin.aws.amazon.com/signin?redirect_uri=https%3A%2F%2Fconsole.aws.amazon.com%2Fconsole%2Fhome%3Fstate%3DhashArgs%2523%26isauthcode%3Dtrue&client_id=arn%3Aaws%3Aiam%3A%3A015428540659%3Auser%2Fhomepage&forceMobileApp=0&code_challenge=HqEJxF-AA6WssjFH2Z4uxf6SLoIf5cGRoy-9Aac2Mn4&code_challenge_method=SHA-256)? I use the "root login" there.

The entry has set `https://signin.aws.amazon.com` as its URL.

![image](https://user-images.githubusercontent.com/65263/86633126-901ace00-bfd0-11ea-99fa-d2e008083c4f.png)

Right-clicking here, selecting `KeepassXC > Fill Username and Password` fills the username correctly. Then clicking `Next` and trying the same with anything else than TOTP fails in the password input. Even though I see the KPXC attributes are set on the password element: `<input id="password" type="password" class="aws-signin-textfield" autocorrect="off" autocapitalize="off" data-kpxc-id="password" kpxc-password-generator="true" kpxc-pwgen-next-field-exists="false">`. It shows the password generation icon though.

![image](https://user-images.githubusercontent.com/65263/86633981-a1180f00-bfd1-11ea-9220-06c58f984304.png)

This is in Firefox btw. It does not work for me in Chrome either.

This used to work after the re-designed extension was released, but has stopped working at some point. I am not quite up to date with any recent changes in the extension though.

**Comment by ashokrajput** [comment]
There is smple hack to see the saved password.
Just type any letter and use backspace to remove and you can see that autosuggestion work.
