### ISSUE TITLE
Save new password dialog may not stay up enough

### ISSUE THREAD

**Issue by stdedos** [keepassxreboot/keepassxc-browser#781]
## Expected Behavior

Using an `https://www.okta.com/free-trial/` domain (e.g. https://dev-000000.oktapreview.com/login/login.htm), I am trying to sign in - db is open and detected, and it is offering me unrelated usernames.

I login with non-saved credentials, and I see the "new credentials" prompt. I am trying to "comprehend" the dialog, and save the new credentials to the db.

## Current Behavior

As soon as I am trying to click a button, it disappears

## Possible Solution

Prompt should stay up for at least 15 seconds (if not interacted with), even if redirected to a new page within that time (SAML flow accepts a post, and then "tells" the browser to post something again).

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Linux x86_64
Browser: Chrome/Chromium 80.0.3987.106

**Comment by varjolintu** [comment]
The next version adds a Redirect Allowance for the Credential Banner, and it should solve these kind of issues. See https://github.com/keepassxreboot/keepassxc-browser/pull/767.

**Comment by georgehank** [comment]
Next version would be?  Because I see this still in 1.6.3 with Linked.In (I mean, I saw it *JUST NOW*)

**Comment by varjolintu** [comment]
@georgehank Have you tried to increase the value of the Redirect Allowance?
