### ISSUE TITLE
Loading icon has wrong background color

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#79]
## Expected Behavior

Everything should have the same background color.

## Current Behavior

Grey background behind loding icon, white otherwise:
![grafik](https://user-images.githubusercontent.com/11966684/37454085-e6f77c86-2839-11e8-97dc-15a6beda27de.png)

## Steps to Reproduce (for bugs)

1. Open popup when it is loading somehow.

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Linux
Browser: Firefox
Proxy used: yes

**Comment by varjolintu** [comment]
Wanted: free transparent background loading icon :)

**Comment by rugk** [comment]
https://openclipart.org/search/?query=loading
Maybe https://openclipart.org/detail/274088/animated-loading-icon

Would just need some CSS (or js, but that may not be so performant) for rotating. And svgs are always better than pixel graphics.
