### ISSUE TITLE
Login-Problems at Mathäser Cinema

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc-browser#795]
## URLs stored in KeePassXC
If I edit the password entry in KeePassXC, then I have on the page "**Entry**" the following URL stored:
http://www.mathaeser.de/

On the page "**Browser Integration**" I have stored the following URL:
https://www.mathaeser.de/mm/mein-konto

## Current Behavior
I have KeePassXC running (ans also unlocked) and also KeePassXC-Browser has a connection to KeePassXC.
When I open the URL of the website (http://www.mathaeser.de/) and click on "Anmelden" (means: login) then the following URL is shown in the browser:
https://www.mathaeser.de/mm/mein-konto

Here I see only at the field "password" the KeePassXC icon, but if I click it, the following error message is shown:
> Error!Keine Anmeldungen gefunden, (this means: Error!No Logins were found)

Even when I enter my email address manually and then click on the KeePassXC icon in the filed "Password", the error message is shown.
When I press the Auto-Type hot key then KeePassXC is logging me in normally (but I have not added any Window-Association stored in KeePassXC).

## Debug info from KeePassXC
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

## System Specs
**Operating System**: Windows 10 Professional Version 1909 (Build 18363.657)
**Browser**: Microsoft Edge (Chromium Engine) version 80.0.361.62
**KeePassXC-Browser**: Version 1.5.4

**Comment by varjolintu** [comment]
That site uses an iframe for login. So the actual URL for your entry should be `https://kino-ticketshop.de/`.

Also, the username field has an invalid type `user`, but you can still fill the credentials using the shortcuts.

**Comment by OLLI-S** [comment]
> That site uses an iframe for login. So the actual URL for your entry should be https://kino-ticketshop.de/

I think from the user perspective: is there a way for users to find this out easily?
Means that you add the URL in the error message:

> Error!Keine Anmeldungen gefunden für: https://kino-ticketshop.de/
> Error!No Logins were found for: https://kino-ticketshop.de/

This would make the process more transparent to users (they see why the login is not working).

> Also, the username field has an invalid type user, but you can still fill the credentials using the shortcuts.

I am not an expert and also not a programmer.
But would I be an idea to add the type "user" to the list of fields that are detected as username?
So KeePassXC-Browser fills here also the username?

**Comment by varjolintu** [comment]
@OLLI-S That would be a nice solution indeed. Currently you'll have to inspect the input field to see the source. Displaying the page/iframe URL in the error message would be a great improvement.

**Comment by OLLI-S** [comment]
Thank you @varjolintu 
And this is the reason why I preferred one separate topic for each site... :wink:
