### ISSUE TITLE
Bug: Browser extension have problems to fill out nextcloud pasword prompts 

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#803]
Nextcloud has the (security)feature that after a while when a user didn’t do any action on the webui and than e.g. after two hours he perform a task that require a password , Nextcloud displays a separate password prompt (see picture) . 

The browser extension in Firefox and chrome can’t recognize this single password prompt and can’t fill it out .

The second bug is that the password fill out button (the red/green one) are duplicated here .

![44668AF8-EBD0-429F-A5CE-D8536665D5FB](https://user-images.githubusercontent.com/8161283/76329496-f3c80f80-62ec-11ea-9869-b98d83564a59.png)

**Comment by varjolintu** [comment]
Wow. I'd like to see the page source code around the login form. I've seen icons behaving like that when there are some canvas elements. The observer that should hide them cannot access the canvas.

**Comment by F3000** [comment]
@# Here are some more screenshots and the code:

![3F59FA42-C0BF-4F9D-AA4E-726AFC4C5BD0](https://user-images.githubusercontent.com/8161283/76571124-10b03e80-64b7-11ea-84c9-ded9ca3f6b23.png)
![5A2FC957-E0CC-4C27-86A9-9E507B3474AE](https://user-images.githubusercontent.com/8161283/76571130-11e16b80-64b7-11ea-975c-24918a6d72e9.png)

**Comment by varjolintu** [comment]
What about the source code of those hoovering icons where database is closed?

**Comment by varjolintu** [comment]
Any difference with the latest 1.6.5 release?

**Comment by varjolintu** [comment]
And what about https://github.com/keepassxreboot/keepassxc-browser/releases/tag/1.7.0-beta1 ? I have my own NextCloud now so I can do some more testing. Is the only way to get that password prompt to just wait?

**Comment by madpilot78** [comment]
With 1.7.0 I'm seeing nextcloud has problems detecting the nextcloud TOTP field when using the "Two-Factor TOTP Provider" nextcloud plugin. The button to paste the TOTP does not appear anymore.

This used to work before 1.7.0.

Not sure if this is related.

**Comment by varjolintu** [comment]
@madpilot78 Gotta test that one too.

**Comment by madpilot78** [comment]
@varjolintu I noticed that with version 1.7.1, while the icon for the TOTP is still not appearing in the nextcloud totp login field, I now can paste it via the context menu, which is more practical than manual cut&paste from the keepassxc window.

**Comment by varjolintu** [comment]
@madpilot78 Not good enough :) I'll try to fix it for 1.7.2.

**Comment by varjolintu** [comment]
@madpilot78 This is fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/1022.

**Comment by varjolintu** [comment]
This is now tracked in #1358.
