### ISSUE TITLE
[Firefox flatpak] key exchange failed

### ISSUE THREAD

**Issue by vasyugan** [keepassxreboot/keepassxc-browser#804]
## Expected Behavior

The keepassxc extension should just work (tm) with flatpak packaged firefox as with native firefox builds

## Current Behavior

I just installed the official firefox flatpak from flathub

`flatpak install https://flathub.org/beta-repo/appstream/org.mozilla.firefox.flatpakref`

I see that it can't connect to my keepassxc. The debugger says:

```
Error 5: Die Verbindung zu KeePassXC ist nicht möglich. Überprüfen Sie, ob die Browser-Integration in den KeePassXC-Einstellungen aktiviert ist. keepass.js:1062:13
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:979:13
Failed to connect: Unknown error keepass.js:949:13
Error: No content script available for this tab. keepass.js:1180:25
Error 9: Schlüsselaustausch war nicht erfolgreich. keepass.js:1062:13
```

## Debug info

KeePassXC -2.5.3
KeePassXC-Browser - 1.5.4
Operating system:  Linux
Browser:  Firefox (official flatpak from flathub-beta)

**Comment by varjolintu** [comment]
AFAIK, Native Messaging doesn't work with flatpak or snap. KeePassXC can be installed as a snap or flatpak though, but your browser must be installed via the package manager.

**Comment by vasyugan** [comment]
It seems, this [needs a change in XDG desktop portal and Firefox](https://github.com/flatpak/xdg-desktop-portal/issues/283), see this [comment by a mozilla developer](https://bugzilla.mozilla.org/show_bug.cgi?id=1591387#c36) .

**Comment by droidmonkey** [comment]
That's a great response!
