### ISSUE TITLE
Add "Fill User Only" to context menu

### ISSUE THREAD

**Issue by sedrubal** [keepassxreboot/keepassxc-browser#81]
## Expected Behavior

Add a option "Fill User Only" to the context menu.
This was a nice feature for login pages where you can only enter the password only after filling in and confirming the username.

## Current Behavior

When you right click to a text field that is recognized as user or password field, you can choose between "Fill User + Pass" and "Fill Pass Only" (and "Fill TOTP") but not "Fill User Only".

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Firefox
Proxy used: NO

**Comment by varjolintu** [comment]
Have you tried to use `Fill User + Pass` for these input fields? It should do the same, just ignores the password because no input field is found.

**Comment by sedrubal** [comment]
Ah yes that works.
