### ISSUE TITLE
keepass auto connection while opening browser

### ISSUE THREAD

**Issue by rzenv** [keepassxreboot/keepassxc-browser#811]
There should be an option to choose auto connection to keepass app while opening browser. It is very good experience if it will connect to keepass while autofilling user/pass. We can disable this auto connection to app. It can be manually do it while filling user/pass data. Because when i open browser or new tab it will ask me to unlock db. It is bad experience.

**Comment by aalhitennf** [comment]
There is `Automatically reconnect to KeePassXC.` in settings. Doesn't work well in windows tho.

**Comment by rzenv** [comment]
it not about automatically reconnection. it should not connect while opening browser by the way that setting is closed for me.

**Comment by varjolintu** [comment]
You removed the issue template so we have no details. What's your OS and KeePassXC version?

**Comment by rzenv** [comment]
i used normal keepass verison and keepassnatmsg plugin. because it has widows hello support. when i open my browser it will ask me winhello unlock everytime.

**Comment by varjolintu** [comment]
That problem is because of KeePassNatMsg, and we don't officially support it.
