### ISSUE TITLE
[Feature Request] Add "Save to Credential" button in addon's popup

### ISSUE THREAD

**Issue by Tamce** [keepassxreboot/keepassxc-browser#813]
Now we have "Save to Credential" menu when right clicking the input box.
But in some cases login form are not recognized properly, or after register, there is no popup reminding me to save the credential.
Like the "Allow redirect times" option, hope to provide a button to force reading last submitted form and save that credential.

## Expected Behavior
1. Login or Register
2. After 0(ajax) or n redirects, (Maybe no popup shows up)
3. Click the addon icon, select "Save last credential"
4. popup and confirm adding credential

## Current Behavior
1. Login or Register (using password generator)
2. The popup doesn't show up
3. Open KeePassXC manually and add credential manually

## Possible Solution
Maybe watch for every form submitted including ajax requests, within N redirects last submitted form's informations are saved in localstorage or somewhere.
When clicking "Save last credential", just read the fields from last form, then just pop up the save credential popup as usual.

## Steps to Reproduce (No popup shows up)
register a new account in www.GOG.com, I found no popup showed up here.

## Debug info
KeePassXC - 2.5.3
KeePassXC-Browser - 1.5.4
Operating system: Mac
Browser: Chromium(Microsoft Edge Beta)

**Comment by varjolintu** [comment]
That option has been already implemented, and it will be in the next version (we will release it soon).
