### ISSUE TITLE
Since version 1.6.0, custom text fields not filled anymore

### ISSUE THREAD

**Issue by olifre** [keepassxreboot/keepassxc-browser#818]
## Expected Behavior
While this worked fine for most sites before version 1.6.0, I can't make it work with any site as of now :-(. 

## Current Behavior
Custom fields ignored. 

## Steps to Reproduce (for bugs)
1. Visit any page requiring a custom text field. 
2. Have that in the database prefixed with "KPH:". 
3. Observe it's not filled. 

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.0 / 1.6.1 (both fail)
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
And it doesn't help if you select String Fields again for the same page? I tested this with my test site and everything worked normally. Can you give the site URL?

**Comment by olifre** [comment]
Reselecting did not help, I tried. Sadly, both pages I have at hand are internal only. 
Can you tell me a public test page? Maybe I can reproduce there.

**Comment by varjolintu** [comment]
https://meine.deutsche-bank.de/trxm/db/ is a good page to test it because there are multiple fields. I usually select the last two for username and passwd, and the first two for String Fields.

**Comment by olifre** [comment]
Got it, that's the cause:
https://github.com/keepassxreboot/keepassxc-browser/commit/d36d4f4c36bc8873d4ce7ea1e597fb4ca0eb4d66#diff-412b80e8f63d0bb8ff5dcc811ec72823
The field on my page is "readonly" since it is filled by Javascript and not by typing usually. However, KeepassXC could fill it just fine before.

**Comment by olifre** [comment]
My page has something like this:
https://jsfiddle.net/cptcrunchy/ezs7n4o8/16/
in addition to username / password.

**Comment by varjolintu** [comment]
The extension also showed icons for readOnly input fields that couldn't be filled. We'll maybe have to make a fix where this could be still allowed for String Fields. Still, I think `readonly` should be respected.

**Comment by olifre** [comment]
It's sadly common practice on some pages to have such a javascript pin in addition to username / password, so I'd really love it if for string fields explicitly selected by the user, "readonly" could be ignored. For username / password, I agree of course.

**Comment by droidmonkey** [comment]
Read-only is read only, we should not be filling those fields

**Comment by olifre** [comment]
I fully get your point, but it breaks pages with numpad entry, unless the extension can emulate clicks on buttons (or run Javascript to fill those fields). That would certainly be more correct, since it honours `readonly`, but I think that is out of scope of this extension. 
I'm fine either way, it just means the extension is not useful anymore to me on some pages.

**Comment by varjolintu** [comment]
You can actually force the fill by using attribute name `KPH: {TOTP}` with your PIN as a value. Then use the context menu "Fill TOTP". It's a hacky way, but a valid workaround.

**Comment by droidmonkey** [comment]
Sorry I misread your post. If the action is explicit from the user than we should fill it.

**Comment by varjolintu** [comment]
We can just make a change that we don't show the icons with `readonly` fields, but the filling still works if user makes the action.

**Comment by olifre** [comment]
The context menu actions seem to disable themselves on `readonly` fields, so that sadly does not work. But I like the suggestion by @varjolintu and I'm in no hurry ;-).
