### ISSUE TITLE
Browser extension injects stylesheets to the webpage

### ISSUE THREAD

**Issue by chuangzhu** [keepassxreboot/keepassxc-browser#819]
For a webpage that using a CSS variable `--link-color`, KeePassXC browser integration will inject a stylesheet and overwrite the variable set by webpage. 

## Expected Behavior

![Screenshot_20200323_150359](https://user-images.githubusercontent.com/31200881/77290626-7ef6cb80-6d17-11ea-8dfc-fac7088364bb.png)

## Current Behavior

![Screenshot_20200323_150435](https://user-images.githubusercontent.com/31200881/77290665-959d2280-6d17-11ea-8cfe-9ea66df33312.png)

## Steps to Reproduce (for bugs)

1. A webpage for reproducing: https://keepassxc-style-inject-536b23q17.now.sh/

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.0
Operating system: Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Already fixed with 1.6.1. Update the extension from AMO.
