### ISSUE TITLE
Make allowed characters for pw generator configurable

### ISSUE THREAD

**Issue by sedrubal** [keepassxreboot/keepassxc-browser#82]
## Expected Behavior

Some websites allow only a limited set of characters for passwords.
The password generator of keepassxc-browser should have the same options as the keepassxc program itself and this should be configurable for each password and not as global plugin configuration.

## Current Behavior

![screenshot_20180316_154912](https://user-images.githubusercontent.com/5571650/37527137-9343513e-2931-11e8-8855-634eaf06d842.png)

## Possible Solution

![screenshot_20180316_155058](https://user-images.githubusercontent.com/5571650/37527219-d284213e-2931-11e8-8bd9-4fb673adce95.png)

## Debug info

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Firefox
Proxy used: NO

**Comment by droidmonkey** [comment]
I think the password generator should include a button that opens the KeePassXC standalone generator which can pass the password back to the browser using native messaging.

**Comment by rugk** [comment]
Indeed.
Maybe it should just always use KeePassXC's generator. (behind the scenes, i.e. via native messaging) Also e.g. to abide to the default settings for passwords, which one can configure.

In any case, I'd like to configure the default settings for password generation, too. It can just use KeePassXC's ones.

**Comment by TheZ3ro** [comment]
> Maybe it should just always use KeePassXC's generator. (behind the scenes, i.e. via native messaging) Also e.g. to abide to the default settings for passwords, which one can configure.

It's already using KeePassXC's generator, but it's using custom settings. I agree we should centralize settings and use KeePassXC one

**Comment by varjolintu** [comment]
Using custom settings? AFAIK the password generator uses exactly the same settings configured in KeePassXC.

**Comment by varjolintu** [comment]
Once you close the password generator in KeePassXC the settings are saved. This doesn't happen on-the-fly.

**Comment by sedrubal** [comment]
Indeed, it seems to use the settings from keepassxc. But I wanted to suggest that either all buttons (to select character classes) should be shown in the in-browser dialogue or the desktop app should open to have full control.

**Comment by rugk** [comment]
I'd prefer the second approach. Have a button "More options", which opens the desktop pw gen app and displays the password, and when clicking on OK it should be passed back to the browser extension and pasted into the field. I think, this saves implementation time than remaking the whole PW generator in the browser add-on (and maintaining it, if new additions come to it).

**Comment by carestad** [comment]
The generator in the browser extension does not seem to take into account what you add in the `Also choose from` input though.

For example, if I set this:

![image](https://user-images.githubusercontent.com/65263/145395051-a649c9e2-e24a-43a4-823b-09bd8a4a4cec.png)

... it generates passwords according to my length preference, and the other pre-defined character groups, but _not_ what I added to `Also choose from`:

![image](https://user-images.githubusercontent.com/65263/145395168-b5fad145-3bc0-48ff-a571-0d1d67b8d8ce.png)

**Comment by varjolintu** [comment]
The password generator is deprecated due to https://github.com/keepassxreboot/keepassxc-browser/pull/1329. Closing the issue.
