### ISSUE TITLE
Can't Input Login & Password at www.verizon.com/home/myverizon/

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc-browser#824]
Hello, Everyone, I hope everyone is having a great day!  It's a nice sunny day here.  And, I love this community!

## Expected Behavior
1. I go to https://www.verizon.com/home/myverizon/.
2. I see the KeePass login and password icons next to the correct fields.
3. I click the KeePass login icon and immediately to the above-left, a selection box appears with all the possible logins I have stored in my KeePass database.
4. I click one of the logins and the proper login and password automatically appear in the respective fields.
5. I click the "Sign in" button and I enter my online Verizon account.

## Current Behavior
1. I go to https://www.verizon.com/home/myverizon/.
2. I see the KeePass login and password icons next to the correct fields.
3. I click the KeePass login icon and immediately to the above-left, **a pink box appears.  I guess this box usually contains the possible Verizon logins but it's just an empty pink box.  If I click the pink empty box, nothing happens.**
**4. I try to turn off all possible browser extensions that might interfere with KeePass and reload.  Nothing changes.**
**5. If I click the KeePass password icon instead, a cut-off dialog box appears to the immediate bottom-right which contents I can't read or see.**
6. If I cut and paste the login and passwords, I can log into my online Verizon account.

## Possible Solution
I'm not sure if this is the reason but this Verizon page has a weird feature.  If you hover your mouse over the top banner, the top banner expands to about half the page, covering the login and password.  I don't know if this has an effect on KeePass's system.

## Steps to Reproduce (for bugs)
N/A

## Debug info
KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.1
Operating system: Win32
Browser: Chrome/Chromium 80.0.3987.149

*Btw, my Operating System is 64 bit so I don't know why it says Win32 right above.  Don't know if this has any bearing.

**Comment by droidmonkey** [comment]
I hope it will be sunny later today, currently cloudy and chilly.

Can we get a couple screenshots of what you are seeing?

**Comment by varjolintu** [comment]
It's an error box, but the text doesn't show for some reason. Just change your entry URL to `https://verizon.com` or `https://ssoauth.verizon.com` and you're good to go. The login iframe has a different domain.

**Comment by CerebralFreeze** [comment]
Sure, my friend.  I will pray for you.  Now, expect a sunny day later!

Here are some screenshots, just as you requested!

![image](https://user-images.githubusercontent.com/24355773/77431189-bcf4fd80-6db2-11ea-9498-cc9ad32dc51a.png)

![image](https://user-images.githubusercontent.com/24355773/77431142-afd80e80-6db2-11ea-871f-3588da04ed4e.png)

**Comment by CerebralFreeze** [comment]
> It's an error box, but the text doesn't show for some reason. Just change your entry URL to `https://verizon.com` or `https://ssoauth.verizon.com` and you're good to go. The login iframe has a different domain.

Okie.  Dokie.  I will try it and report what happens.  If it fixes the problem, I will reward you.  I'll think of a way...

**Comment by CerebralFreeze** [comment]
> > It's an error box, but the text doesn't show for some reason. Just change your entry URL to `https://verizon.com` or `https://ssoauth.verizon.com` and you're good to go. The login iframe has a different domain.
> 
> Okie. Dokie. I will try it and report what happens. If it fixes the problem, I will reward you. I'll think of a way...

Hmm....I did exactly what you suggested.

First, when I typed in https://verizon.com, I got redirected to:  https://www.verizon.com/?lid=//global//residential.  On that website, it was an exact replica of the original problem website so the same pink box appeared again.  :(

Second, when I typed in: https://ssoauth.verizon.com, I got this scary-looking box!

![image](https://user-images.githubusercontent.com/24355773/77431754-89ff3980-6db3-11ea-8828-88831b314f67.png)

Here is your reward.  

https://media.giphy.com/media/bcl5yVYiti4ik/giphy.gif

I'm pretty old-school and take misbehavior seriously.

**Comment by droidmonkey** [comment]
lol. Put the verizon.com url in your entry in KeePassXC, not the browser address bar.

**Comment by varjolintu** [comment]
That's definitely the best reward I've ever had for a correct answer!

**Comment by CerebralFreeze** [comment]
@droidmonkey @varjolintu 
Holy Toledo!  It worked!  I have to admit I had doubts about you two.  I'm not going to lie, you both proved me totally wrong and I feel stupid.  I don't know what to say.  I'm flabbergasted.  I'm NEVER wrong.

I have arranged a meeting between you two and President Trump and Putin.  They have pleaded to help them come up with a solution to this Coronavirus pandemic but I've been too busy.  I'll private-message you their private numbers.  Call Trump immediately.  He's been hiding in his room and won't come out.

![image](https://user-images.githubusercontent.com/24355773/77437296-dd28ba80-6dba-11ea-8ecd-0c9ef4d49ea9.png)

By the way, sorry the reward is not "fun" but we need you.

**Comment by droidmonkey** [comment]
This issue is like reddit meets GitHub
