### ISSUE TITLE
Username field not detected on https://ego.studiopini.it/default.asp

### ISSUE THREAD

**Issue by MindWithCake** [keepassxreboot/keepassxc-browser#825]
When I open this site, the username field is not filled. The keepass icon is shown on the password field only. Even when I manually choose login fields the username input is not selectable.

![immagine](https://user-images.githubusercontent.com/10020251/77514161-98faf000-6e76-11ea-9d7e-a5e61a237cc8.png)

## Expected Behavior
When I setup custom login fields the username input should be selectable

## Current Behavior
When I setup custom fields only the passwrod input can be selected.
During navigation, if I right click on the username field and select `keepassXC browser -> fill username and password`, the username is filled. If I do the same starting from the password input element it is not.

## Possible Solution
The username field has a `type="Input"`, with capital 'i'. Could it be the cause? I tried to manually change it with the browser tools, but it didn't help

## Steps to Reproduce (for bugs)
1. Go to https://ego.studiopini.it/default.asp
2. try to add custom login fields and select the username input

## Debug info
KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.1
Operating system: Linux x86_64
Browser: Mozilla Firefox 74.0
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by varjolintu** [comment]
Using type `input` is not a standard. So for now you need to use the context menu of keyboard shortcut for filling. But I agree that the custom field selection is maybe too strict for these kind of situations.
