### ISSUE TITLE
2FA Code not filled for VulnDetect.com

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc-browser#826]
## Current Behavior
When I log into VulnDetect.com using my username and my password and press on "Login", then the page is shown where I have to enter my 2FA code (I have set up 2FA in KeePassXC for this site).
But here no "Paste 2FA Code" icon is shown here.

Here a screen shot of the login mask:
![image](https://user-images.githubusercontent.com/8037790/77583929-30495d00-6ee2-11ea-812c-acbdaeedfbc2.png)

Here some HTML Code from the login page:
`<input maxlength="6" placeholder="Pin Code" type="text" class="form-control" value="" data-kpxc-id="kpxcpw342845641">`

@varjolintu tell me if you need more HTML code from the website...

## Expected Behavior
There should be the KeePassXC "Paste 2FA Code" icon visible in the 2FA field like you see it in GitHub:
![image](https://user-images.githubusercontent.com/8037790/77586123-e8c4d000-6ee5-11ea-88e6-4e2ef0486093.png)

## KeePassXC Debug info
KeePassXC - Version 2.5.3
Revision: f8c962b

Qt 5.13.2
Debugging mode is disabled.

Operating system: Windows 10 (10.0)
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

## KeePassXC-Brwoser info
KeePassXC-Browser Version 1.6.1
Browser: Microsoft Edge Chromium Version 80.0.361.69 (Offizielles Build) (64-Bit)

**Comment by varjolintu** [comment]
This happens because there's nothing in the input field that would tell that it's a 2FA field. Only the placeholder gives a hint about it.

The basic support looks for these strings either in the `name` or `id` (and later ignores some using regex): https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js#L9

**Comment by OLLI-S** [comment]
@varjolintu So what should be changed in this field so KeePassXC shows the "Paste 2FA Code" icon?
I will contact the developers of this website.

**Comment by varjolintu** [comment]
Yes, adding that would be enough. However, I'd suggest using `autocomplete="one-time-code"`.

**Comment by varjolintu** [comment]
Another non-standard check we could do is to check for `maxlength="6"`.

**Comment by OLLI-S** [comment]
> Another non-standard check we could do is to check for `maxlength="6"`.

I would **not** implement this feature, because relying on the field length could be dangerous.
I am not a security expert but I think checking the field name is much safer than the length.

**Comment by varjolintu** [comment]
@OLLI-S I agree. I just brought it up that it's possible to do that. But I agree that it shouldn't be done.

**Comment by OLLI-S** [comment]
I reported the issue to the developers of VulnDetect, so I close this issue now.
There is nothing that KeePassXC can do here...

**Comment by OLLI-S** [comment]
The developers at VulnDetect.com changed the 2FA field in a test-instance.
Now the login field has the following source:
```
<input autocomplete="one-time-code" id="otp" maxlength="6" name="otp" placeholder="Pin Code" type="text" 
class="form-control" value="" data-kpxc-id="otp">
```
But unfortunately **no KeePassXC icon is shown in the 2FA field**:

![image](https://user-images.githubusercontent.com/8037790/90684081-dc139080-e267-11ea-8743-06edf90271c0.png)

Am I right that ```data-kpxc-id="otp"``` is added by the KeePassXC browser extension?

When I look at the 2FA field of GitHub, then I see the following additional attribute: ```kpxc-totp-field="true"```
I think this is the reason why the KeePassXC icon is shown in GitHub but not in VulnDetect, right?

So, why is there no KeePassXC Icon shown?
And why is the attribute: ```kpxc-totp-field="true"``` not shown?

### Here some additional data:
* The test-instance of VulnDertect is located at https://test.vulndetect.com/#/
* In KeePassCX I have 4 entries for VulnDetect and one for the test instance.
* In the field **URL** I have the URL https://test.vulndetect.com/ 
* In the field **Additional URLs** I have stored the URL https://test.vulndetect.com/#/
* In KeePassXC I added 2FA yesterday (in VulnDetect I selected to see the key instead of the QR-Code and then I added 2FA by right-clicking the entry in KeePassXC -> TOTP -> Set up TOTP

### KeePassXC Version:
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

### Browser Data
Microsoft Edge (Chromium Engine) Version 84.0.522.61
KeePassXC Browser Extension **loaded from the Microsoft Extension Store** 
KeePassXC Browser Extension Version 1.6.6

**Comment by droidmonkey** [comment]
Please check when using the "Big Refactor" branch

**Comment by OLLI-S** [comment]
@droidmonkey Sorry, I really don't know what the "Big Refactor" branch is...

**Comment by varjolintu** [comment]
@OLLI-S I tested this with the upcoming 1.7.0 version (which is the Big Refactor) and the 2FA field works just fine.
