### ISSUE TITLE
Question: how can I save new items created by the browser extension directly in root folder

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#827]
At the moment the browser extension creates a new group “browser passwords” . How can I deactivate this behavior?

**Comment by varjolintu** [comment]
Go to extension settings, section _Saving credentials_, and set the default group for saving passwords to either `/` or `Root`.

**Comment by F3000** [comment]
@varjolintu  Thanks for the hint . But doesn’t work on Firefox for me

**Comment by varjolintu** [comment]
Seems there's some problem with the setting saving. We've having a lot of these kind of issues with Firefox lately.

**Comment by F3000** [comment]
Ok . When can I exspect it in the extension ?

**Comment by varjolintu** [comment]
@F3000 The fix is already in, and 1.6.2 is released.

**Comment by F3000** [comment]
@varjolintu  thanks for the fast answer 👍 can I force update it ? 

Can you add a visuell sign , that a user can see that this is saved ?

**Comment by varjolintu** [comment]
There's already a notification when credentials are succesfully saved.

**Comment by F3000** [comment]
For me not . Tested in Firefox and Edge Chromium . 


and I have made your suggestion but with no effect . 
All items get saved into a sub folder
