### ISSUE TITLE
Features "Dynamic Input Fields" needs KeePassXC-Version: 2.6.0

### ISSUE THREAD

**Issue by Oekel** [keepassxreboot/keepassxc-browser#829]
## Expected Behavior
# Update to KeePassXC-Version: 2.6.0

## Current Behavior
# Newest Version of KeePassXC: 2.5.3

## Steps to Reproduce
1. chrome-extension://oboonakemofpalcgghocfoadofidjkkk/options/options.html
2. Config for Advanced Users
3. "Dynamische Eingabefelderkennung verwenden"
4. read INFO-BOX

## Context
 Benötigt KeePassXC-Version: 2.6.0

## Debug Info
KeePassXC - 2.5.3
Revision: f8c962b

Libraries:
- LIBS

Operating system: Ubuntu 18.04
Architecture:  x86_64
Kernel: linux 4.15.0-91-generic

Enabled extensions:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey
- Secret-Service-Integration

**Comment by varjolintu** [comment]
That warning is for showing the group name option. It doesn't have anything to do with the dynamic detection.
