### ISSUE TITLE
Slider nib for “max redirections “ is misplaced

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#830]
See photo: 

![image](https://user-images.githubusercontent.com/8161283/77798446-2d31a680-7073-11ea-834f-13e7fb04bb92.jpeg)

**Comment by F3000** [comment]
Tested on MS Edge on OS X . Extension version 1.6.2

**Comment by varjolintu** [comment]
Cannot reproduce this. Plus, that is purely Bootstrap. How this page looks for you? https://getbootstrap.com/docs/4.4/components/forms/#range-inputs

**Comment by droidmonkey** [comment]
I noticed this as well on Edge browser

**Comment by varjolintu** [comment]
On what macOS versions this happens?

**Comment by F3000** [comment]
> On what macOS versions this happens?

I use 10.15.3 


Later I will test it on Windows

**Comment by F3000** [comment]
> Cannot reproduce this. Plus, that is purely Bootstrap. How this page looks for you? https://getbootstrap.com/docs/4.4/components/forms/#range-inputs

Thanks . I will try it later 👍

**Comment by droidmonkey** [comment]
Played around with the CSS in Edge and found that the padding-left applied to the range from the col-* classes causes this offset. I am calling this an Edge bug. You can just override the padding-left though on the input.

**Comment by varjolintu** [comment]
Cannot reproduce this on macOS or with Windows.
