### ISSUE TITLE
Since the upgrade to 1.62, FF/Chrome do not save passwords to the DB

### ISSUE THREAD

**Issue by azrek** [keepassxreboot/keepassxc-browser#831]
Since the upgrade to 1.62, FF and Chrome do not save passwords to the DB. Both plugins were updated today (29 March).

Steps:
1. Enable KeePassXCBrowser - i.e. I entered my password in KeepPassXC to allow the browser access.
2. I log into a site (with user/password credentials) that is new to KeepPassXC DB.
3. It brings up the New/Update buttons at the top. 
4. I click New 
5. It does not save to DB and New/Update buttons continue to appear at the top.

I see no errors in the console. I've restarted FF and Chrome. It does not ask me to reauthenticate myself in the DB. It just does nothing.

## Debug info
KeePassXC - 2.3.1
KeePassXC-Browser - 1.6.2
Operating system: Linux x86_64  (Ubuntu 18.04)
Browser: Mozilla Firefox 74.0
Browser: Chrome Version 80.0.3987.149 (Official Build) (64-bit) 

## Fix
Upgrade KeePassXC - 2.5.3 as per README file.

**Comment by varjolintu** [comment]
So I assume it was fixed when you upgraded? Closing the issue.

**Comment by azrek** [comment]
We're not actually allowed to upgrade to that version as it's not on the office Ubuntu repo.

I only assume it will be fixed if on the 2.5.3 version.

**Comment by varjolintu** [comment]
So it's not possible to use the AppImage either?

**Comment by azrek** [comment]
Sorry, I haven't tried.

**Comment by azrek** [comment]
Hi @varjolintu ,

Is there any way this plugin can be made backwards compatible with the KeyPassXC 2.3.1 version - the official supported release in the Ubuntu repo?

There are known issues with the 2.5.3 version + Ubuntu. KeePass loses its database after an Ubuntu update. We've had several people report this in our company.

Just asking...

Thanks,
Ghada

**Comment by droidmonkey** [comment]
What, losing your database?? Are you referring to the snap installation? Don't store your database in the snap folder.

**Comment by azrek** [comment]
hi @droidmonkey ,

Version 2.5.3 is in the Snap repo.  We don't store the db in the snap folder. It usually lives in ~/keepassxc

Several people have this issue when they apply an Ubunu update.

Thanks.
Ghada

**Comment by droidmonkey** [comment]
Will need more specifics about this problem, first I have heard of it to be honest.

**Comment by arjenlentz** [comment]
Snap often causes hassles. I'm generally not too interested in jumping down that rabbit hole.
A more practical solution for this is:
sudo add-apt-repository ppa:phoerious/keepassxc
sudo apt update
and you'll be good, including with updates. That repo is by the maintainer, so it's just a bit ahead of distros.

**Comment by azrek** [comment]
Thank you @arjenlentz

Then, a 'sudo apt upgrade'

And, it works as expected.

@droidmonkey  / @varjolintu  - it was due to the KeePassXC version. 

Thanks,
Ghada
