### ISSUE TITLE
Bug : browser extension recognize only first url saved for a item

### ISSUE THREAD

**Issue by F3000** [keepassxreboot/keepassxc-browser#833]
I have some database entries where I have saved more as one URL entry . 

But the browser extension fill out the correct password only for the first URL field ;( 

On iOS I use Strongbox safe and here it s possible . This app check all fields (also custom) for title like “URL1,URL2 etc..” . 

Is this also possible with your program ?

**Comment by droidmonkey** [comment]
Setup your additional URLs in the browser integration tab while editing an entry.
