### ISSUE TITLE
Update password button not working

### ISSUE THREAD

**Issue by trameathia** [keepassxreboot/keepassxc-browser#838]
## Expected Behavior

When changing my password I expect the update password button to update the password in my keepassxc database.

## Current Behavior

When the bar pops up across the top if you click the update button nothing happens.  If you click the new button it will save it but then you have multiple entries.

## Possible Solution

fix the button? :-)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
Operating system: Win32
Browser: Chrome/Chromium 80.0.3987.149 - actually running Brave

**Comment by varjolintu** [comment]
In this situation KeePassXC should prompt you for the credential update. Does this happen with every site?

**Comment by trameathia** [comment]
So today it's no longer happening.  Not sure if maybe something was messed up on my end with the proxy service maybe but the update button is working fine today on every site I try it with.  Sorry for the inconvenience.
