### ISSUE TITLE
[Feature] redetect login fields shortcut

### ISSUE THREAD

**Issue by ramenchef** [keepassxreboot/keepassxc-browser#839]
## Current Behavior

- existing shortcuts to fill in username/pasword, activate extension, fill TOTP, Password Generator

- No shortcut to redetect login fields

## Possible Solution

- implement shortcut to redetect login fields

**Comment by varjolintu** [comment]
This can be added, but the shortcut must be configured manually by the user. Extensions are allowed to use only four pre-defined shortcuts per extension.

**Comment by droidmonkey** [comment]
I don't think it is necessary, we detect the fields very well in the recent releases

**Comment by ramenchef** [comment]
I have had trouble with certain websites even with the latest releases. For instance, US Bank, Citibank, and Capital One are hit and miss for me. I notice it a lot more often with tabs that load in the background.

**Comment by varjolintu** [comment]
I've also noticed that when a tab loads in the background, the content scripts can have problems identifying the fields. I'll take a look at it.
