### ISSUE TITLE
 Option to match only only on full URL 

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#84]
Followup of https://github.com/smorks/keepasshttp-connector/issues/64

How do I do that in the new extension? In the KeePassXC settings, there is no such checkbox anymore.

**Comment by varjolintu** [comment]
Has there been that kind of button ever anywhere?

**Comment by rugk** [comment]
See the linked issue. In KeepassHttp you could enable it in the settings of KeePassX(C). It did not work properly, but the whole option seems to be gone with KeePassXC-Browser.

**Comment by varjolintu** [comment]
I'll fix this one too.

**Comment by varjolintu** [comment]
https://github.com/keepassxreboot/keepassxc/pull/1822.
