### ISSUE TITLE
Error in banner.js (Cannot read property '0' of undefined)

### ISSUE THREAD

**Issue by isgroup** [keepassxreboot/keepassxc-browser#841]
User is unable to save new entries using the Chrome extension on Version 80.0.3987.162 (Official Build) (64-bit) / Linux.

## Expected Behavior

Save function work by clicking the appropriate button in the banner.

## Current Behavior

Nothing happens due to JS runtime error.

## Possible Solution

Fixing "if (result.groups[0].children.length === 0 && result.defaultGroup.toLowerCase() === 'root') {" in "banner.js".

## Steps to Reproduce

1. Open a website with a login;
2. Put username and password in the form;
3. Click on New in the JS banner to save the entry.

## Context

Extension is updated on Chrome on Linux.

## Debug Info

Hi Devs!

I detected an error in:

```
chrome-extension://XXXX/content/banner.js
```

The error os:

```
VM42 banner.js:156 Uncaught (in promise) TypeError: Cannot read property '0' of undefined
    at Object.saveNewCredentials (VM42 banner.js:156)
```

Commenting the following code fix the issue:

```
kpxcBanner.saveNewCredentials = async function(credentials = {}) {

[..]

        // If root group is defined by the user, and there's no default browser group, save the credentials to the root group
        // if (result.groups[0].children.length === 0 && result.defaultGroup.toLowerCase() === 'root') {
        //  args.push(result.groups[0].name, result.groups[0].uuid);
        // }
```

I don't have a better fix as I'm not proficient in JavaScript but can beta test the release.

Chrome extension information: 1.6.2
Size: 2.0 MB
Permissions: Read your browsing history, Display notifications, Modify data you copy and paste, Communicate with cooperating native applications

**Comment by varjolintu** [comment]
I couldn't reproduce this but it's possible to modify the if sentence to a better one.

**Comment by isgroup** [comment]
Cool @varjolintu Can't wait to test it once released on Chrome Web Store :)
