### ISSUE TITLE
TOTP Value calculated with first calculated time, never updated on button repress

### ISSUE THREAD

**Issue by pkolmann** [keepassxreboot/keepassxc-browser#847]
## Expected Behavior
I have a login page where I need to specify username, password and TOTP token. I have also tested it with TOTP enabled github account.

I have setup the custom fields to automatically fill out TOTP token. If I click and let the TOTP be generated and wait with sending off the form (after the TOTP Period switched) and I try to update the TOTP token, it stays at the old value, not the current one.

My guess is, that these values are only fetched one from KeePassXC and never refreshed.

## Current Behavior
TOTP Values are only once calculated, but never updated, even if the TOTP period has run out and therefore TOTP fails.

## Possible Solution
If known, that a field could contain TOTP token, always update the value and not cache it.

## Steps to Reproduce (for bugs)
1. enable gitbub TOTP login
2. login with user and password
3. click totp icon to get token generated
4. wait for the totp period to timeout (best viewed with TOTP show) and click again
5. TOTP token stays at the old value, not updated to the current one

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
Operating system: Win
Browser: Chrome and Firefox tested

**Comment by droidmonkey** [comment]
This is not a bad idea, the easiest way to do this is to continually request a new TOTP value from KeePassXC every second after:

1. The user fills in a TOTP field on a page
2. The submit button has not been pressed
3. The page address has not changed

**Comment by varjolintu** [comment]
We probably need just a new command that always retrieves the TOTP instead of getting it only when receiving the credentials.

**Comment by droidmonkey** [comment]
Yes even better

**Comment by pkolmann** [comment]
@varjolintu Has this issue been fixed or why have you closed it? Thanks
