### ISSUE TITLE
Firefox 68 Key exchange was not successful. 

### ISSUE THREAD

**Issue by boundless-thread** [keepassxreboot/keepassxc-browser#849]
## Expected Behavior

KeePassXC-Browser to connect to KeePassXC

## Current Behavior

KeePass XC-Browser gives error message:

```
Key exchange was not successful. 
```

## Steps to Reproduce (for bugs)

1. Run Firefox 68 from APT ( I am on Debian: `firefox-esr/stable,now 68.6.1esr-1~deb10u1 amd64 [installed]`)
2. Run KeepassXC 2.5.3 as Snap
3. Run browser integration script
4. Restart browser
5. Try to connect to database

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.6.2
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

File **.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json**
```
{
    "name": "org.keepassxc.keepassxc_browser",
    "description": "KeePassXC integration with native messaging support",
    "path": "/snap/bin/keepassxc.proxy",
    "type": "stdio",
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ]
}
```

PS Output:

```
user      4334  0.7  1.2 1071300 102960 ?      SLl  12:57   0:05 /snap/keepassxc/687/usr/bin/keepassxc -style fusion
user     16999  0.0  0.0  78552  7396 ?        S    13:07   0:00  \_ /snap/keepassxc/687/usr/bin/keepassxc-proxy /home/user/.mozilla/native-messaging-hosts/org.keepassxc.keepassxc_browser.json keepassxc-browser@keepassxc.org
```

**Comment by mvhconsult** [comment]
Same error/problem, but on Win10 64, with FireFox 75 and KeepassXC 2.5.4. Tried several restarts/reinstalls.

KeePassXC - Version 2.5.4
Revision: c023bf9

Qt 5.14.2
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

**Comment by varjolintu** [comment]
@mvhconsult Did you try the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide)?

**Comment by mvhconsult** [comment]
Thanks for the link. Proxy is running, json content:

{
    "allowed_extensions": [
        "keepassxc-browser@keepassxc.org"
    ],
    "description": "KeePassXC integration with native messaging support",
    "name": "org.keepassxc.keepassxc_browser",
    "path": "C:\\Program Files\\KeePassXC\\keepassxc-proxy.exe",
    "type": "stdio"
}


I went to the debugger and get this 
Warning details

Reading manifest: Warning processing version_name: An unexpected property was found in the WebExtension manifest.

Extension ID
    keepassxc-browser@keepassxc.org
Internal UUID
    99ee3487-c191-4726-bc75-21e6e5f6163d
Manifest URL
    moz-extension://99ee3487-c191-4726-bc75-21e6e5f6163d/manifest.json

**Comment by varjolintu** [comment]
@mvhconsult That manifest content has nothing to do with this problem. Did the Firefox's Native Messaging registry entry pointed to the correct JSON file?

**Comment by mvhconsult** [comment]
Sorry for being thorough.

Yes, and the link is working/correct.

**Comment by varjolintu** [comment]
@mvhconsult Has it been working before? If so, delete all connections from KeePassXC and extension and try to reconnect. Another thing you can try is to make a new temporary profile to Firefox and see if the extension can connect then.

**Comment by mvhconsult** [comment]
Yes, it has been working before (I am a long long time user)

So now I found out there are actually tabs in the settings area (why decided to use white letters on a white background?)

There, the connected database field now is empty and I see the green connect button there (not in the toolbar area.). Pressing it does nothing really...

![kp](https://user-images.githubusercontent.com/10559457/79442153-758c1680-7fd8-11ea-85b3-7fbc1993bd98.jpg)

**Comment by mvhconsult** [comment]
Ok, so maybe something was halting it. Now, 19 minutes later, the connect button pops up again and I am able to create a connection.
Sorry for all the trouble. Can I leave the white letter white background here, or should I start a new bug for that one?

**Comment by varjolintu** [comment]
Well, it shouldn't be white. Have you got some other extension or your own font preferences that could override that? It should be just a basic Bootstrap page. I suggest using the Web Inspector and see if there's any messages in the console etc.

**Comment by boundless-thread** [comment]
@varjolintu Any suggestions on how to get this to work?

**Comment by varjolintu** [comment]
@boundless-thread I have no idea why it shouldn't work. I guess I'll have to put a Debian VM and try to reproduce this myself.

**Comment by varjolintu** [comment]
@boundless-thread The easiest solution for you would be just use the official AppImage instead.

**Comment by boundless-thread** [comment]
Tested the AppImage and it works.  Thanks.
