### ISSUE TITLE
Connection KeePassXC and KPXC-Browser

### ISSUE THREAD

**Issue by guillermosuarez** [keepassxreboot/keepassxc-browser#854]
(Excuse my English, please)

Comming from https://addons.mozilla.org/es/firefox/addon/keepassxc-browser/reviews/1519516/

KeePassXC running, DB created, click in the KeePassXC-Browser icon and it shows:

> KeePassXC-Browser ha encontrado un error:
> No se puede conectar a KeePassXC. Compruebe que la integración del navegador esté habilitada en la configuración de KeePassXC.

The integration in KeePassXC configuration is checked. If I click in the Refresh button in the Browser, the message changes to:

> Intercambio de claves no tuvo éxito.

And, as I said at Mozilla, there is no native-messaging-hosts folder or org.keepassxc.keepassxc_browser.json file. I've even tried to unckeck and check the integration checkbox but nothing changed.

KeePassXC 2.5.4
KeePassXC-Browser 1.6.2
Ubuntu 18.04.4 LTS
Firefox 75.0

**Comment by varjolintu** [comment]
Please check that your Firefox is NOT installed via Snap or Flatpak.

**Comment by varjolintu** [comment]
If you are running KeePassXC as a Snap, please use this helper script to get the browser extension working:
https://raw.githubusercontent.com/keepassxreboot/keepassxc/master/utils/keepassxc-snap-helper.sh

**Comment by guillermosuarez** [comment]
> Please check that your Firefox is NOT installed via Snap or Flatpak.

It's not snap, I installed it from the repository.

**Comment by varjolintu** [comment]
And what about KeePassXC itself?

**Comment by guillermosuarez** [comment]
F**k me, that was it. Sorry man, I just looked for the newest version and didn't check the origin. In fact, I learned what is a snap version yesterday, by your answer.

Thanks for your time... and patience.

**Comment by varjolintu** [comment]
You can still use the Snap version if you use the helper script I linked in the previous reply.
