### ISSUE TITLE
TOTP icon for name=author|coupon_code|postcode|bankcode|activationcode

### ISSUE THREAD

**Issue by bwbroersma** [keepassxreboot/keepassxc-browser#855]
## Expected Behavior
No TOTP icon for
```html
<input name=author>
```

## Current Behavior
TOTP icon
![image](https://user-images.githubusercontent.com/4252918/79057628-a2040380-7c63-11ea-8c4e-76114729653b.png)

## Possible Solution
https://github.com/keepassxreboot/keepassxc-browser/blob/4a04055bb47823c6fc16d1c32f55466eda47bcad/keepassxc-browser/content/totp-field.js#L4
A fix would to add `author` to the ignore regex:
```javascript
/(zip|postal).*code|author/i
```
but that would include quite some other maybe auth-y words like `authori[sz]e` and `authori[sz]ation`:
```bash
aspell -d en dump master | aspell -l en expand | grep -iE 'author'
```
so it might ignore too much. A bit more complex regex that does work:
```javascript
/(zip|postal).*code|author([^a-z]|s|$)/i
```
But maybe I'm over-engineering now, and we should just ignore author?

## Debug info
KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.2
Operating system: Linux x86_64
Browser: Mozilla Firefox 77.0

**Comment by bwbroersma** [comment]
Found some others too:
```html
<input name=coupon_code>
```
![image](https://user-images.githubusercontent.com/4252918/79058510-59524780-7c6f-11ea-89d6-9303271dcf4d.png)
And the Dutch postalcode variant (on the large https://www.marktplaats.nl/):
```html
<input name=postcode>
```
![image](https://user-images.githubusercontent.com/4252918/79058535-9a4a5c00-7c6f-11ea-8a81-aa5d6e518a25.png)

So the new regex could be:
```javascript
/(zip|post|coupon).*code|author([^a-z]|s|$)/i
```

**Comment by varjolintu** [comment]
Ignoring all possible wrong input fields is going to be hard.. I would create a separate JavaScript file for the extension that could hold the white- and blacklists for these kind of cases.

**Comment by bwbroersma** [comment]
Some more:
`bankcode` for BIC code, found on Microsoft payment page
`activationcode` found on software activation page
`actiecode` Dutch translation for discountcode

In the bankcode case, the icon appeared on a disabled input, but I should probably add a bug report for that.

**Comment by xf-** [comment]
With translations the list is endless with translations.

**Comment by varjolintu** [comment]
@xf- True. I'm in favor to make things easier for users, but I also encourage people to report non-standard or otherwise difficult 2FA input fields to the page developers.
