### ISSUE TITLE
Extend TOTP icon field detection

### ISSUE THREAD

**Issue by gmoirod** [keepassxreboot/keepassxc-browser#857]
Some important websites use other field names than those tested to detect TOTP.
Atlassian JIRA and Confluence names : "2fpin"

## Expected Behavior
1. Connect to JIRA or Confluence with a 2FA account
2. TOTP field displayed with icon 

## Current Behavior
1. Connect to JIRA or Confluence with a 2FA account
2. No icon in TOTP field

## Possible Solution
Extend the matching pattern list of 'acceptedOTPFields'

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.2
Operating system: Win
Browser: Chrome

**Comment by grenzor** [comment]
It would nice to have that list be editable by the user. I've come across a few websites with field names that are unique to the websites themselves and it doesn't really seem practical to request to add them to the default list (which won't be able to cover all cases).

**Comment by varjolintu** [comment]
@grenzor That would be a nice addition.

**Comment by gmoirod** [comment]
See #859
