### ISSUE TITLE
Automatically download favicon for new entries 

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#86]
See https://github.com/smorks/keepasshttp-connector/issues/79

**Comment by varjolintu** [comment]
@droidmonkey Does KeePassXC still has this feature? I cannot find it anywhere.

**Comment by droidmonkey** [comment]
We don't have this feature

**Comment by tenzap** [comment]
Hello. What's the status on this? Could keepassxc-browser tell keepassxc to download the favicon when the browser extension creates a new entry?

**Comment by varjolintu** [comment]
@tenzap It's on my TODO list (still).
