### ISSUE TITLE
Unable to decrypt message

### ISSUE THREAD

**Issue by CarFla** [keepassxreboot/keepassxc-browser#862]
## Expected Behavior
Connect Firefox to keepass database

## Current Behavior
Keepass addon run, but indicate Unable to decrypt message

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.2
Operating system: Linux Fedora 31 x64
Browser: Firefox 75.0 64 bit

**Comment by varjolintu** [comment]
More info is needed. Is you Firefox Snap or Flatpak? Is your KeePassXC installed via AppImage, Snap, Flatpak, or what? Is Browser Integration enabled and support for Firefox checked?

Also, check the [Troubleshooting guide](https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide).

**Comment by CarFla** [comment]
I read Troubleshooting guide, run manually keepassxc-proxy, after that firefox connect to database correctly. I try to stop keepass proxy and seems all is ok. 
Thank you
