### ISSUE TITLE
Crash with Vivaldi 3.0 RC1 Linux x86_64 (snapshot 1874.11)

### ISSUE THREAD

**Issue by lcd047** [keepassxreboot/keepassxc-browser#866]
## Current Behavior
Opening the URL to a site that requires HTTP basic authentication crashes the browser.

This happens with Vivaldi 3.0 RC1 (a.k.a. snapshot 1874.11, release candidate for 3.0), but not with Vivaldi 2.11 (currently the latest stable version).

## Steps to Reproduce (for bugs)
1. Find a site the requires HTTP basic authentication
2. Browse said site
3. Kaboom.

## Debug info
KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.2
Operating system: Linux x86_64
Browser: Vivaldi 3.0 RC1 (snapshot 1874.11)

**Comment by varjolintu** [comment]
We don't support any Beta, Develop or RC build browsers because of various reasons. One is that they often break some API's.

Does the HTTP Basic Auth crash without the extension?

**Comment by lcd047** [comment]
> We don't support any Beta, Develop or RC build browsers because of various reasons. One is that they often break some API's.

Well it has crashed pretty reliably for the last ~10 snapshots or so. :smile:

> Does the HTTP Basic Auth crash without the extension?

No.  Disabling the extension eliminates the crash.

**Comment by varjolintu** [comment]
That probably means that Vivaldi has broken something in their snapshot build. If the bug cannot be reproduced with a stable version, we are not going to fix anything.

**Comment by lcd047** [comment]
My point was to let you know the problem is highly likely to be present in the next stable version, to be released in a couple of days.  But sure, I won't waste your time with advanced warnings in the future.

**Comment by varjolintu** [comment]
@lcd047 You should report the error to Vivaldi dev team. Extensions aren't (and shouldn't be) able to crash the whole browser.
