### ISSUE TITLE
Firefox hight CPU usage 2.6 - 6.5

### ISSUE THREAD

**Issue by YoranSys** [keepassxreboot/keepassxc-browser#869]
## Expected Behavior
Low cpu usage if no password prompt in current page .

## Current Behavior
When the module is enabled, he is in the top 5 in the `about:performance`.

## Steps to Reproduce (for bugs)
1. Install the module from firefox add-on
2. Connect some database 
3. Open tab 
4. Open `about:performance` to show the result

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.2
Operating system: Linux Ubuntu 20.04 (64bits)
Browser: Firefox 75.0

**Comment by varjolintu** [comment]
Already fixed with https://github.com/keepassxreboot/keepassxc-browser/pull/836.
