### ISSUE TITLE
Display error for high-entropy passsword in generator

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#87]
## Expected Behavior

Width of entropy status must be large enough to contain input.

## Current Behavior

On the first look, looks like 40 bits… :wink: 

![grafik](https://user-images.githubusercontent.com/11966684/37568993-d781f3e4-2adc-11e8-85d4-87a459babec5.png)

## Possible Solution

Maybe adjust width dynamically and do not make it so static?

## Steps to Reproduce (for bugs)

1. Password generator with high entropy.

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Linux
Browser: Firefox
Proxy used: yes

**Comment by varjolintu** [comment]
Can you test this branch to see if it's any better? https://github.com/keepassxreboot/keepassxc-browser/tree/password_gen_fixes

**Comment by rugk** [comment]
I can test a release/pre-release version on AMO.
Apart from that I think it's easy to verify whether it works, should maybe just be a bit css or so.
