### ISSUE TITLE
Search entries in KeePassXC by Title and URL 

### ISSUE THREAD

**Issue by arneee** [keepassxreboot/keepassxc-browser#870]
## Expected Behavior
I switched from "classic" KeePass with passifox Chrome extension to KeePassXC with this Chrome extension. I have hundreds of sites in my KeePass DB, but none of the have the URL field since the previous extension also searched by title. I find the URL field redundant, since if the entry is named ebay.com it is already clear what it is for.

## Current Behavior
Unfortunately this extension only searches by URL, so it does not find any entries.

## Possible Solution
Include the _title_ in the search.

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.2
Operating system: Win
Browser: Chrome

**Comment by droidmonkey** [comment]
We are not going to match by title. This was a decision that we made very early in the development of our extension.

**Comment by phoerious** [comment]
Matching by URL only protects you from phishing.

**Comment by arneee** [comment]
Just to be clear, I mean the title fields in KP, not the title of the browser or website.

**Comment by droidmonkey** [comment]
I knew what you meant
