### ISSUE TITLE
Key exchange was not successful.

### ISSUE THREAD

**Issue by regor-mulb** [keepassxreboot/keepassxc-browser#875]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
