### ISSUE TITLE
Can't use with latest Torbrowser Update

### ISSUE THREAD

**Issue by blackpidgeon** [keepassxreboot/keepassxc-browser#876]
## Expected Behavior
Today unattended upgrades installed a Tor Browser update.
```
Commandline: /usr/bin/unattended-upgrade
Upgrade: torbrowser-launcher:amd64 (0.3.2-9, 0.3.2-10)
End-Date: 2020-04-30  16:20:22
```
Afterwards I can't connect to Keepass anymore. It used to work before.

The error console says:
TypeError: can't access dead object   in   webconsole.js:297:9

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC-Browser - 1.6.3
Operating system: Debian Bullseye
Browser: Tor Browser

**Comment by varjolintu** [comment]
See this thread https://github.com/keepassxreboot/keepassxc/issues/4123 if it could help you.

**Comment by varjolintu** [comment]
This will be fixed in the next KeePassXC release. The only workaround for now is to manually adjust the Native Messaging scripts.

**Comment by blackpidgeon** [comment]
Ok, I found the problem:

I had already symlinked the file before. But with TorBrowser 9.0.10, Debian started to download a Tor Browser with my system locale. 

That changed the path from tor-browser_en-US to tor-browser_LOCALE . 

Maybe this could or should be reflected in the wiki?
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide

**Comment by varjolintu** [comment]
That guide already says: "(for en_US)" for the manual installation part, concerning the locale.
