### ISSUE TITLE
Error 9: Key exchange was not successful.  Win7 / Chrome

### ISSUE THREAD

**Issue by ramit99** [keepassxreboot/keepassxc-browser#877]
## Expected Behavior
Installed Portable KeePassXC and Chrome browser extension.
Expected the browser extension to work in Chrome.

## Current Behavior
Chrome provides and error message:
KeePassXC-Browser has encountered an error:
Key exchange was not successful.

## Possible Solution
?? 

## Steps to Reproduce (for bugs)
1.Launch KeePassXC
2.Launch Chrome
3.Check / click on icon to the right of the address field.
4. If available, click the "reload" button, and will not have a functioning link between the app and browser.

## Debug info

KeePassXC - {2.5.4 VERSION}
KeePassXC-Browser - {1.6.3 VERSION}
Operating system: Win7
Browser: Chrome Version 81.0.4044.129 (Official Build) (64-bit)

I have followed the trouble shooting guide and confirmed that the registry entry is there.
I have confirmed that the json files are in the correct folder with the installed program and under user..
I have confirmed the paths are correct.
I have confirmed that the Browser integration is checked and Chrome is checked.
I have confirmed that the keepassxc-proxy.exe is running.
from the background page console: 

Connecting to native messaging host org.keepassxc.keepassxc_browser
Error 7: Message encryption failed. Is KeePassXC running? keepass.js:1065
(at this point I click the "reload" button)
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982
Error 9: Key exchange was not successful.  keepass.js:1065

I have rebooted my PC.
I have reinstalled the program into a location with a far shorter path string, just under the root.
I doubled checked the .json files in both locations and registry key to be sure the paths were correct.

I uninstalled the browser extension, deleted the .json files, and registry key... and restarted the program and let the json files rebuild, and checked , them, all good and registry key is all good.
All this with NAV and it's firewall disabled.

Still same results..

Based on all the threads I've read, here's some screen grabs of points commonly discussed...

![Capture2](https://user-images.githubusercontent.com/64673802/80853979-a2f4d900-8c02-11ea-8864-10cfeded9827.JPG)

![Capture4](https://user-images.githubusercontent.com/64673802/80854029-f8c98100-8c02-11ea-860f-db7ef3e1b152.JPG)

![Capture5](https://user-images.githubusercontent.com/64673802/80854059-2e6e6a00-8c03-11ea-87a3-35651f036d2c.JPG)

![Capture7](https://user-images.githubusercontent.com/64673802/80854176-f74c8880-8c03-11ea-8050-0102f1243833.JPG)

![Capture6](https://user-images.githubusercontent.com/64673802/80854108-7d1c0400-8c03-11ea-9906-32bf1eaee6e8.JPG)

Was really looking forward to getting this working, but just banging the keyboard for the last couple of hours chasing this silly problem...
Would appreciate some help,, TIA.
Bob

Edit: for groans and giggle, enable for FF and added extension to FF, and it has the same results...

**Comment by ramit99** [comment]
Some more playing around..
Was using "KeePassXCPortable.exe" to launch the program, that is in the first folder of the path..
C:\KeePassXCPortable

So tried more hunting and pecking...
found..
KeePassXC.exe
That is in..
C:\KeePassXCPortable\App\KeePassXC

and low and  behold, when I hit the icon on the browser, it how asks to finish the setup and make a key for each browser,,,, and it's working.

So pray tell, why is C:\KeePassXCPortable\KeePassXCPortable.exe there..
When I needed to use..
C:\KeePassXCPortable\App\KeePassXC\KeePassXC.exe 

?

**Comment by varjolintu** [comment]
So let's make this clear: are you using the KeePassXC's official ZIP package as a portable solution, or some 3rd party package (like PortableApps)? I assume it's the latter because there is no `KeePassXCPortable.exe` in our package, AFAIK.

**Comment by ramit99** [comment]
Affirmative, the latter. I was under the impression that the PA group / website , integrated the apps with the participation of the original developers...

**Comment by varjolintu** [comment]
To clarify, KeePassXC is already portable if you just download the ZIP file, not the installed. No need to support any 3rd party solution. We do not co-operate with them.

**Comment by ramit99** [comment]
Thank you  varjolintu

**Comment by droidmonkey** [comment]
When you run the portable executable it intercepts registry changes to put them into a portable registry, among other things. This prevents your browsers from seeing the proper registry setting to support native messaging. We have absolutely no affiliation or involvement with PortableApps.

**Comment by ramit99** [comment]
Disabled the browser extensions.
Removed the PA version.
Downloaded KeePassXC-2.5.4-Win64-portable.zip from https://keepassxc.org/ .
Placed in a directory of my choosing, started it, pointed it to my DB, re-enabled the extensions on the browsers, and green lights..
Well, at least if people search this same issue, they'll find the reason the disconnect from the 3rd party offering..
