### ISSUE TITLE
Browser addon only autofills the username field for a certain bank website (Bank of the Philippine Islands)

### ISSUE THREAD

**Issue by vincejv** [keepassxreboot/keepassxc-browser#879]
## Overview
The browser addon (KeePassXC-Browser v1.6.3 on Microsoft Edge Version 81.0.416.68 Chromium based) does **not** autofill the password field for my bank website [BPI Online](https://online.bpi.com.ph/portalserver/onlinebanking/sign-in)

I have reproduced the issue using Firefox with the latest addon versionv1.6.3, same issue

## Steps to Reproduce

1. Setup a login information (username and password) on KeePassXC and url
2. Go to [BPI Online](https://online.bpi.com.ph/portalserver/onlinebanking/sign-in)
3. Click on KeePassXC Icon besides the username field
4. Select which credential to fill 
4. Only the username field is correctly populated, the password field remains blank.

## Expected behavior

Password field should contain the value of the password from the KeePass database credential information

## Actual behavior

Password field is empty after clicking the autofill button

## Context

Successfully reproduced the issue with Firefox 75 with the same addon version.
I've tried to use the custom login fields feature to manually select the fields but the password field still remains blank.

**Comment by varjolintu** [comment]
This happens because of https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/content/keepassxc-browser.js#L1434. That's old code from the old chromeipass implementation. I think that could be removed without it affecting anything.

**Comment by varjolintu** [comment]
This is now tracked in #1358.

**Comment by varjolintu** [comment]
Checked that this site works with the latest version :) Removing this from the non-working sites list.
