### ISSUE TITLE
Persisting connexions to keepassxc

### ISSUE THREAD

**Issue by theonlydoo** [keepassxreboot/keepassxc-browser#88]
I often have to re-establish my link between the browser and keepassXC, as if I had close the app

## Expected Behavior
Avoid re-establishing connexion, if keepassxc is still present

## Current Behavior
Browsing internet, having to log in on a website, have to refresh keepassxc connexion.

## Possible Solution
Maybe a reconnect attempt on a page refresh would be an acceptable workaround?

## Steps to Reproduce (for bugs)
Fedora 27, google-chrome-stable-65.0.3325.162-1.x86_64, firefox-59.0.1-1.fc27.x86_64, keepassxc-2.3.1-1.fc27.x86_64
![](https://dooby.fr/y/34nw8cq)

**Comment by mhow2** [comment]
Hi, same observation with same version of KeepassXC components on my side but on FF 59.

**Comment by varjolintu** [comment]
Please check if keepassxc-proxy is present or it has shutdown when this happens.

**Comment by theonlydoo** [comment]
I just have to hit "reconnect" on the extension, so I guess that keepassxc-proxy is running, I never have to restart keepassxc to fix that

**Comment by theonlydoo** [comment]
same here after check

**Comment by varjolintu** [comment]
To clear this up:
- If browser is started before KeePassXC the connection must be re-established
- If KeePassXC is started before browser the connection is established right away

This is needed because native messaging needs to create a new pipe for every connection. At this point re-establishing the connection is not automatic. But it may be in the future (or opt-out).

**Comment by theonlydoo** [comment]
@varjolintu Indeed, it seems quite right

the issue is quite different tho : even without quitting the browser, even without locking the session, even without locking keepassxc, the proxy vanishes and it becomes necessary to hit "connect" again on the extension

**Comment by varjolintu** [comment]
So it seems the proxy crashes or quits (there are other issues related to this). There's some fixes in the upcoming KeePassXC 2.3.2 release so if you have a chance to test a snapshot, please do so.

**Comment by theonlydoo** [comment]
can't wait for an upstream update, this is SO annoying:

![](https://dooby.fr/y/a4xku3c)

**Comment by varjolintu** [comment]
At this point I have no idea when 2.3.2 is going to be released. But I suggest you try to compile it by yourself and see if the changes solve issue. I still cannot reproduce them.

**Comment by theonlydoo** [comment]
works fine thank's :-)
