### ISSUE TITLE
Automatic submits on single entry

### ISSUE THREAD

**Issue by Smallinger** [keepassxreboot/keepassxc-browser#880]
Hello,
I know the risk behind the function, but i search a alternative to lastpass or dashlane, that automatic fill the forms and submit it.

i have more then 25 tabs open everyday and get automatic logout if my pc goes into sleep mode.
so every day i start my routine or i make a small break i must press enter on all tabs.

is it possible to add a checkbox with redtext with a warning to enable the submit for single entry ?

so that if i open the tab i didn't must press enter or the login button.

**Comment by droidmonkey** [comment]
Already a setting...
