### ISSUE TITLE
OTP fails to be filled on gitlab.com

### ISSUE THREAD

**Issue by xeropresence** [keepassxreboot/keepassxc-browser#883]
## Expected Behavior

OTP field to be filled out either by hotkey or pressing the button

## Current Behavior
OTP icon appears adjacent to the field, pressing the otp hotkey or clicking the button does nothing

## Steps to Reproduce (for bugs)
1.Visit https://gitlab.com
2.Supply username/password
3. Proceed to the otp phase
4. Attempt to fill in otp either by hotkey or pressing the icon

## Debug info
KeePass - 2.44
KeeTrayTOTP - 0.105.0.0
KeePassNatMsg - 2.0.9.0
KeePassXC-Browser - 1.6.3
Operating system: Win32
Browser: Chrome/Chromium 81.0.4044.129

Otp codes are generated correctly for other sites such as protonmail
No error messages appear in the console
Manually selecting it as the otp field does not help

**Comment by varjolintu** [comment]
Can you reproduce this without KeePassNatMsg?

**Comment by xeropresence** [comment]
How? KeePassNatMsg facilitates the connection between the browser and keepass.

**Comment by droidmonkey** [comment]
We don't provide support for integration with a third party plugin.

**Comment by varjolintu** [comment]
If this happens only with KeePass & KeePassNatMsg combo, it's not an issue in the extension, but in KeePassNatMsg.

**Comment by droidmonkey** [comment]
You could also have not defined the OTP properly in your GitLab entry in your database.

**Comment by xeropresence** [comment]
I tried creating a new entry, as well as copying the entry that works for protonmail.
