### ISSUE TITLE
Still can't use the whole solution for its purpose.

### ISSUE THREAD

**Issue by ha3flt** [keepassxreboot/keepassxc-browser#884]
While everything is moving under snap, at least in Ubuntu, after several years KeePassXC is still unusable with a snap-installed FireFox, nothing can make it work. Developers tell you not to use Snap for the browser... Of course, you should change the whole environment instead of solving the problem. Also, the Android app is cringy, it can't open the DB by the stored path again after re-open the app. That's a failure.

**Comment by varjolintu** [comment]
Duplicate issue: https://github.com/keepassxreboot/keepassxc-browser/issues/689.

Also, we don't have our own Android app, so it's unclear which one you are referring to.

**Comment by droidmonkey** [comment]
Take it up with the snap programmers. They have not added a plug for native messaging between snaps.

**Comment by ha3flt** [comment]
Yes, and there is no communication through the snap and the browser, no ports, no shared files, nor anything...
