### ISSUE TITLE
Can't connect to keepassxc when user-data-dir is different in google chrome.

### ISSUE THREAD

**Issue by justin-julicher** [keepassxreboot/keepassxc-browser#885]
Startup chrome in kubuntu (or ubuntu probably) with:

--class=google-chrome-work --user-data-dir=$home/.config/google-chrome/work/

and I can't connect to keepassxc: 

error on background page is: 

Failed to connect: Specified native messaging host not found.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Specified native messaging host not found.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Specified native messaging host not found.
keepass.js:982 Connecting to native messaging host org.keepassxc.keepassxc_browser
keepass.js:952 Failed to connect: Specified native messaging host not found.

I have copied the org.keepassxc.keepassxc_browser.json file to ~/.config/google-chrome/work/native-messaging-hosts  and also tried /etc/opt/chrome/native-messaging-hosts

but am still experience the issue (I killed all instances of chrome). 

KeepassXC is running and db is unlocked. 

Although keepassxc-proxy is under /usr/bin it is never run by that instance. 

Works fine under the default directory and settings. 

any ideas? 

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Linux x86_64
Browser: Chrome/Chromium 81.0.4044.138

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
KeePassXC-Browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium

**Comment by droidmonkey** [comment]
If you set a custom data directory then it is on you to manually move the native messaging configuration file that we create in the standard location.

**Comment by varjolintu** [comment]
Use the Custom Browser feature in KeePassXC 2.6.0 and later for this.

**Comment by kasumiru** [comment]
@varjolintu I use many different user-data-dirs. Should I list them separated by commas?

**Comment by kasumiru** [comment]
I checked, it works with a space separator. Oh, I'm tired. Thank you so much for the wonderful tool for integrating passwords with a local database! It was difficult to find this parameter to make user-data-dirs work.
