### ISSUE TITLE
keepassxc-browser cannot connect to database

### ISSUE THREAD

**Issue by dr-inair** [keepassxreboot/keepassxc-browser#886]
current behaviour.
keepassxc works ok independently.
keepassxc-browser icon is greyed out on browser toolbar and in webpage password fields.
clicking on toolbar icon brings up "cannot decrypt message".
'reload' option opens keepassxc app. if app already unlocked kpxc-browser icon remains greyed. if app locked then kpxc-browser still greyed once app unlocked.

troubleshoot.
all checks out ok until point 3.
ie, found and ran keepassxc-proxy binary but no changes noticed.
ran recommended command for binary linking check resulting in 'invalid path . . .' and no reference to qtnetwork or qtcore.
the following paragraph of troubleshoot then confused me. 

only other curious point i noted during above steps was the .json displays with a tor browser icon despite changing this to 'open with' firefox as default.

debugging
about:debugging opens a 'setup' tab. when 'this firefox' selected the keepassxc-browser is listed but has only an 'inspect' option. this opens a 'toolbox exension'. and i have no clue from here.

thanks.

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Macos 10.13.6
Browser: Firefox

**Comment by varjolintu** [comment]
Are you using the proxy setting in KeePassXC's Browser Integration settings? It should be enabled. If reload button open KeePassXC application, then something is not working properly.

**Comment by dr-inair** [comment]
no. under 'advanced' the only checked box is "return advanced string fields . . . "
i've now checked . . . and it appears to be fixed. duh. many thanks!

**Comment by e-t-l** [comment]
> Are you using the proxy setting in KeePassXC's Browser Integration settings? It should be enabled. If reload button open KeePassXC application, then something is not working properly.

Which option are you referring to exactly? I'm having a similar problem, but under Browser Integration > Advanced, the only setting that mentions a proxy is "Use a custom proxy location:" which requires entering a custom filepath.
