### ISSUE TITLE
Backblaze website does not auto fill the username when having extra parameters in URL

### ISSUE THREAD

**Issue by trettet** [keepassxreboot/keepassxc-browser#887]
## Expected Behavior

Should show the plugin icon in username field and let the user autofill for both URLs.

URL with extra parameters: https://secure.backblaze.com/user_signin.htm?netid=1589634318617
URL with no params: for https://secure.backblaze.com/user_signin.htm

## Current Behavior

Does not show the plugin icon and does not autofill **if there are parameters** in the URL, but when entering any valid email, then clicking next, it shows the plugin icon and auto fill is possible.
![image](https://user-images.githubusercontent.com/1276544/82120449-cc903180-97b8-11ea-9910-ecd58e25865c.png)
![image](https://user-images.githubusercontent.com/1276544/82120540-8b4c5180-97b9-11ea-8c7d-8518d2228944.png)
![image](https://user-images.githubusercontent.com/1276544/82120542-91423280-97b9-11ea-95e5-d676393a4f79.png)

## Steps to Reproduce (for bugs)

1. Go to https://secure.backblaze.com/user_signin.htm?netid=1589634318617
2. Type in any username (plugin does not detect the field or it detects it but no icon is shown)
3. Click the "Next ->" button
4. Autofill is enabled for password
5. Click the "(Change)" button to change username
6. Autofill is now enabled for username which was not detected on step 2

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 2.5.4
Operating system: Windows 10 x64 
Browser: Edge Chromium 81.0.416.72 (Stable) and Firefox 75.0

**Comment by varjolintu** [comment]
Go to extension settings, Site Preferences tab, add `https://secure.backblaze.com/*` to the list and enable "Username-only detection" for it.

**Comment by trettet** [comment]
Oh, had to add the wildcard..
