### ISSUE TITLE
spurious TOTP and Generator icons at https://www.neowin.net

### ISSUE THREAD

**Issue by Stephan-P** [keepassxreboot/keepassxc-browser#889]
When vitising https://www.neowin.net the KeePassXC Broswer extension shows the green TOTP and Generator icons where there are no corresponding entry fields.

**Comment by varjolintu** [comment]
This is because the email field has `id` and name with `auth` which doesn't make any sense.

**Comment by Stephan-P** [comment]
Okay, and what about the locations of these two icons?
(I will try to report this oddity with their webmaster)

**Comment by varjolintu** [comment]
That's a bug. The input field visibility is not checked properly.

**Comment by Stephan-P** [comment]
I reported the issue with neowin.net, underlining that this is the only website that I know of where this occurs
