### ISSUE TITLE
Show notification about saving passwords only once

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#89]
## Expected Behavior

The notification that/how you can save passwords should only be shown once.

## Current Behavior

It is shown each time you can copy a password.

## Steps to Reproduce (for bugs)

1. Enter a password somewhere and submit the form.

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1

**Comment by varjolintu** [comment]
Could not reproduce this one. I can always see the notification only once. Is there a certain site that causes this?

**Comment by droidmonkey** [comment]
Perhaps it would be nice to remember which sites you have shown it on and only show it twice (in case they missed it the first time)

**Comment by rugk** [comment]
It is always reproducible for me. At each password saving it is shown once, but when you enter another password it is shown again. That's what is annoying and I think you got how the thing works the first out second time you saw the notification.

Also I don't think you have to have a counter for each site. I mean the user understands the feature it independently of the site. So maybe only show it three times in general?

The problem with three notification is that - in contrast to the blinking icon - it does not disappear automatically on many systems (depending on the browser's implementation), by you have to click it away manually. That's what is annoying for the user and does not make the use of the add-on fun.

**Comment by varjolintu** [comment]
So changing the blink time from the settings doesn't affect to it?

**Comment by rugk** [comment]
Whaaat? :open_mouth: 

Why it should it affect that? A "blink time" should be aboute blinking, not about notifications or so.
And no, here it does not do that. (using GNOME notifications here)

And even if it would, I hardly can imagine that I want the same time for blinking and showing the notification.
The notification may be shown for one second, while I really really need a longer time for blinking, so I can click on it while it is blinking, because AFAIK when it ends to blink, I cannot save the credentials anymore. (may be wrong about this, but generally the times may differ)

As said, no one wants to see this notification again and again. And we have the solution: Just limit it.

**Comment by varjolintu** [comment]
There's already a PR for this (https://github.com/keepassxreboot/keepassxc-browser/pull/54) where you can disable just this notification.

Blink time is just for that: you can have a longer blinking time so you can click the icon when it's blinking. The default is just 7,5 seconds.

**Comment by rugk** [comment]
Ah okay, great. So this issue is already solved, I'd say. An option to disable the notifications also helps.
