### ISSUE TITLE
Extension consumes all CPU and increasing amount of memory when hovering reaction in Slack

### ISSUE THREAD

**Issue by nazar-pc** [keepassxreboot/keepassxc-browser#893]
##  Expected Behavior
Extension should never lock the tab with 100% CPU usage

## Current Behavior
Like in #888, but all CPU usage, not jus high.
I found one case where extension reliably starts consuming all CPU dedicated to the tab to the point I can only kill the process of the tab from task manager.
It happens when hovering reactions in Slack. For some reason not all reactions are affected, but some are persistently even after page reload, and those were always with reaction from one person, not multiple.
It also eats memory, about 50MiB/s, I let it consume 20GiB before I killed the process.
Disabling dynamic input field detection, as mentioned, does nothing.

## Possible Solution
I believe there must be an infinite loop somewhere.

## Steps to Reproduce (for bugs)
1. Go to Slack web version
2. Hover reactions with one person reacting
3. At some point reaction hovering will cause extension to consume 100% CPU and increasing amount of memory
4. With that reaction found you can reliably trigger the issue from that point onwards (adding more people to reaction will break reproducibility)

## Debug info
KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Linux
Browser: Firefox Nightly

**Comment by varjolintu** [comment]
I've seen some weirdness with Slack also, so I'm already investigating this.

**Comment by thePanz** [comment]
Under Firefox v76.0.1, I had the warning that KeepassXC browser extension was causing the tab to hang: the tab was a Slack chat.
I tried to set `https:\\apps.slack.com` to "Disable all features" under the configuration, but did not help

**Comment by varjolintu** [comment]
Adding `https://app.slack.com/*` should do the trick. I tested web Slack using `about:performance` but I'm unable to see any energy impact.

**Comment by nazar-pc** [comment]
It is not a minor one, it doesn't happen at idle. It locks up the whole page until process it killed. You'll definitely notice when it happens.

**Comment by varjolintu** [comment]
@nazar-pc I'll try to reproduce it. The whole tab itself (Slack) is also very slow. The worst hiccups I've seen happen when I press <kbd>Up</kbd> and try to edit the previous message quickly.

**Comment by varjolintu** [comment]
This should be already solved.
