### ISSUE TITLE
No autofill for flatex.de

### ISSUE THREAD

**Issue by sam1919** [keepassxreboot/keepassxc-browser#894]
My KeepassXC is configured that it recognizes the login fields and prompts a popup window.

This does not work for https://www.flatex.de/kunden-login/

There's no KPXC icon in the first field I can select "Fill username and password" from the menu. That works.

## Expected Behavior

Popup should appear with the entries for the website.

## Steps to Reproduce (for bugs)

1. go to https://www.flatex.de/kunden-login/

## Debug info

KeePassXC - 2.5.3
KeePassXC-Browser - 1.6.3
Operating system: Linux
Browser: Chromium

21:05:58.792 klrgzgb0w3.kameleoon.eu/kameleoon.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
21:05:58.807 www.googletagmanager.com/gtag/js?id=AW-820243761:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
21:05:58.833 webtrekk_v3.1572451608.js:207 A parser-blocking, cross site (i.e. different eTLD+1) script, https://responder.wt-safetag.com/resp/api/get/370212450674777?url=https%3A%2F%2Fwww.flatex.de%2F, is invoked via docu
ment.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console messa
ge. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ webtrekk_v3.1572451608.js:207
21:05:58.834 webtrekk_v3.1572451608.js:207 A parser-blocking, cross site (i.e. different eTLD+1) script, https://responder.wt-safetag.com/resp/api/get/370212450674777?url=https%3A%2F%2Fwww.flatex.de%2F, is invoked via docu
ment.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If
 blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details.
(anonymous) @ webtrekk_v3.1572451608.js:207
21:05:58.837 370212450674777:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
21:05:58.842 bat.bing.com/bat.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
21:05:58.956 (index):1 [DOM] Found 2 elements with non-unique id #tx-solr-search-form-pi-results: (More info: https://goo.gl/9p2vKq) <form method="get" class="tx-solr-search-form-pi-search" id="tx-solr-search-form-pi-results" action="/suche/" data-suggest="/suche/?type=7384" data-suggest-header="Top Results" accept-charset="utf-8">…</form> <form method="get" class="tx-solr-search-form-pi-search" id="tx-solr-search-form-pi-results" action="/suche/" data-suggest="/suche/?type=7384" data-suggest-header="Top Results" accept-charset="utf-8">…</form>
21:05:58.963 w3.flatex.de/370212450674777/wt?p=445,de.flatex.kunden-login,1,1920x1080,24,1,1590519958849,0,1443x776,0&la=de&cg1=de&cg2=flatex&cg10=kunden-login&cp6=de&np=&pu=https%3A%2F%2Fwww.flatex.de%2Fkunden-login%2F:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
21:06:07.848 keepassxc-browser.js:438 Uncaught (in promise) TypeError: usernameField.getAttribute is not a function
    at Object.kpxcFields.getCombination (keepassxc-browser.js:438)
    at Object.kpxc.prepareFieldsForCredentials (keepassxc-browser.js:1137)
    at Object.kpxc.retrieveCredentialsCallback (keepassxc-browser.js:1105)
    at Object.kpxc.initCredentialFields (keepassxc-browser.js:1048)
kpxcFields.getCombination @ keepassxc-browser.js:438
kpxc.prepareFieldsForCredentials @ keepassxc-browser.js:1137
kpxc.retrieveCredentialsCallback @ keepassxc-browser.js:1105
kpxc.initCredentialFields @ keepassxc-browser.js:1048
async function (async)
kpxc.initCredentialFields @ keepassxc-browser.js:991
(anonymous) @ keepassxc-browser.js:886
attributes (async)
addClass @ merged-4de212eba050f2e5d723c4400d7ad98e-4b9a5916d57912cb2dfc20f6ddb341d8.js.1547243099.gzip:27
a.suspend @ merged-fd5e8cd51fa46f11b59b97223d150fca-84ec54b23d568682331679f84db4f01c.js.1569602982.gzip:133
a.checkBreakpoint @ merged-fd5e8cd51fa46f11b59b97223d150fca-84ec54b23d568682331679f84db4f01c.js.1569602982.gzip:133
(anonymous) @ merged-fd5e8cd51fa46f11b59b97223d150fca-84ec54b23d568682331679f84db4f01c.js.1569602982.gzip:133

**Comment by varjolintu** [comment]
There's a slight delay in the page scripts for loading the content. If you choose "Redetect login fields" from the popup the icon appears normally.
