### ISSUE TITLE
Extension breaks some layouts

### ISSUE THREAD

**Issue by SamWhited** [keepassxreboot/keepassxc-browser#896]
## Expected Behavior

If a website uses the body element to layout content, the div added by this extension to the end should not modify that layout.

## Current Behavior

If the body uses flexbox to creates a column including a header, main block, and footer, the div inserted at the end of the body by this extension will become part of that layout and make the footer balance towards the middle of the document, or if the layout adds padding, margins, positioning, etc. to all the elements in the body it can cause the div to take up space in the layout (eg. using a `body > *` rule).

## Possible Solution

I'm not a web person, but adding `display: absolute` or `display: fixed` to the div should remove it from the normal document flow, then it can be forced off the screen with normal positioning.

## Steps to Reproduce (for bugs)

I couldn't remember where I'd seen this in the wild, but the following example should trigger it:

```
<style>
body {
	border-bottom: 1px solid black;
	display: flex;
	flex-direction: column;
	min-height: 50vh;
}

header {
	height: 2rem;
	background-color: red;
}

main {
	background-color: purple;
	flex: 1;
}

footer {
	background-color: lime;
	height: 2rem;
}

/* The sites I've seen that have a problem use some variation on this which
	 gives the keepassxc div a size. */
body > * {
	padding: 1rem;
}

/* This is the keepassxc div, try triggering on and off the position element to see the possible fix. */
footer + div {
	background-color: blue;
	/* position: absolute; */
	right: 200vw;
}
</style>

<body>
	<header>Top</header>
	<main>
		<label for="password">Password</label>
		<input id="password" type="password"/>
	</main>
	<footer>Bottom</footer>
</body>
```

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Linux
Browser: Firefox

**Comment by xf-** [comment]
This is insane
```css
/* The sites I've seen that have a problem use some variation on this which
	 gives the keepassxc div a size. */
body > * {
	padding: 1rem;
}
```

Would add a passing to every a span or other element. No normal website will use such a rule.

**Comment by varjolintu** [comment]
I find this interesting because every div added by the extension is added to Shadow DOM, and correct me if I'm wrong but the layout shouldn't have any information what the content or its size is? All the icons, autocomplete menu, password generator etc are already using `position: absolute`. Only the Credential Banner and notifications are using `position: fixed`.

**Comment by SamWhited** [comment]
> All the icons, autocomplete menu, password generator etc are already using position: absolute. Only the Credential Banner and notifications are using position: fixed.

Whatever this div is, it always seems to be right at the end of pages just before the `</body>` and is not `position: absolute` or `position: fixed`.

**Comment by varjolintu** [comment]
@SamWhited For me it's the username icon. You can inspect it by yourself to see what it really is. That div uses `kpxc-username-icon` class which defines `position: absolute`.

**Comment by SamWhited** [comment]
For me it's an empty div containing `#shadow-root`. The div itself does not appear to be position: absolute though, nor does it have any sort of identifying ID or anything on it (but it only shows up on login pages and goes away when the keepassxc plugin is disabled).

**Comment by varjolintu** [comment]
@SamWhited Could you disable the icons from the extension settings and then enable them one by one so you can verify what icon it is? If you open the `#shadow-root` you should see the actual div.

**Comment by SamWhited** [comment]
Ah, I see. Inside of `#shadow-root` is a div with `class="kpxc kpxc-username-icon lock-disconnected"`, but its' the div around the `#shadow-root` that's causing the problem. Disabling the username icon does in fact make the whole thing go away and the page layout returns to normal.

**Comment by Delta-official** [comment]
Why was this closed? The issue is still there and breaks layouts.

**Comment by varjolintu** [comment]
> Why was this closed? The issue is still there and breaks layouts.

What could be the solution for this? The CSS rule doesn't even make sense. And it doesn't help even if the icon's style is set with `!important`. The icon position is even returned using `getBoundingClientRect()`.

**Comment by Delta-official** [comment]
Presumably the solution should involve setting `position: absolute` on the div containing the `#shadow-root`, as that's what's actually causing the problems,

**Comment by varjolintu** [comment]
> Presumably the solution should involve setting `position: absolute` on the div containing the `#shadow-root`, as that's what's actually causing the problem.

That is not solution for the problem. It only makes the div go to the bottom of the page, and of course depends on the site what else it possibly does.

**Comment by Delta-official** [comment]
What are you talking about? `position: absolute` would exclude the div from the layout of the page and thus mitigate the issue.

**Comment by varjolintu** [comment]
> What are you talking about? `position: absolute` would exclude the div from the layout of the page and thus mitigate the issue.

I'm talking about the thing that it doesn't work as expected. I tried it.

**Comment by Delta-official** [comment]
But it does work. The div is no longer influencing the layout if `position: absolute` is applied to it.

**Comment by varjolintu** [comment]
> But it does work. The div is no longer influencing the layout if `position: absolute` is applied to it.

Did not work for me. I went to a site, added the `body > * ` CSS rule using developer tools so it's effective immediately. Then appended `position: absolute` to the `div` that holds the Shadow DOM content.

**Comment by Delta-official** [comment]
Please take a look at the following pen to see that it *does* work.
https://codepen.io/delta-official/pen/KKjdmoN

**Comment by varjolintu** [comment]
> Please take a look at the following pen to see that it _does_ work. https://codepen.io/delta-official/pen/KKjdmoN

You'll have to modify the extension's div, and not make any global CSS rules.

**Comment by Delta-official** [comment]
Yes I'm aware. But this is just a demonstration of the fact that it *does* work and that this *is* a solution.

**Comment by varjolintu** [comment]
> Yes I'm aware. But this is just a demonstration of the fact that it _does_ work and that this _is_ a solution.

Again. This is not the solution. I modified the extension code and applied the `position: absolute` to the `div`. That only broke pages and the icon position was not correct.

If you don't believe me, try it yourself. If you keep pushing, I'll just lock the thread.

**Comment by Delta-official** [comment]
I made a quick and dirty [fork](https://github.com/Delta-official/keepassxc-browser). I implore you to visit the codepen I made earlier and (while keeping the line commented out) compare my fork and the baseline versions of the extensions. While yes, the icon positioning logic is broken, that is to be expected as the extension probably assumes that the wrapper element is included in the normal flow of the page. But you can see a clear difference in that in my fork, the extension wrappers are *not* included in the normal flow and thus *do not* change the way the page is meant to be displayed.

**Comment by SamWhited** [comment]
I don't know if this is the solution or not, but please don't close this issue. There may be another solution that would work, and it's still a problem many of us users are having. It feels really bad to have a maintainer be this dismissive of an actual bug, even if the particular solution posed by someone doesn't work (or maybe it does, I dunno, but either way it's a real issue that I'm still experiencing).

**Comment by varjolintu** [comment]
> I made a quick and dirty [fork](https://github.com/Delta-official/keepassxc-browser). I implore you to visit the codepen I made earlier and (while keeping the line commented out) compare my fork and the baseline versions of the extensions. While yes, the icon positioning logic is broken, that is to be expected as the extension probably assumes that the wrapper element is included in the normal flow of the page. But you can see a clear difference in that in my fork, the extension wrappers are _not_ included in the normal flow and thus _do not_ change the way the page is meant to be displayed.

I did that too, and it's not the actual solution, but a part of it. I have alredy figured out how to make it correctly though. It just needs more testing.
