### ISSUE TITLE
Support multiple TOTP fields in KeePassXC Browser plugin

### ISSUE THREAD

**Issue by frederickjh** [keepassxreboot/keepassxc-browser#902]
## Summary
[TIP]:  # ( DO NOT include screenshots of your actual database! )
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add support for TOTP entry with multiple fields to the KeePassXC Browser plugin. ie. one field for each digit of the TOTP code .

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
I currently have one login with a TOTP entry that has multiple fields for the TOTP. If I copy the TOTP code from the KeePassXC database and paste it into the first field, the digits from the 2nd digit on move into the other fields and the TOTP validates.

If use the **Choose custom login fields** and set the first digit TOTP field as the TOTP field. I can then use the Alt-Shift-O shortcut key to paste the TOTP code, however it just sits there and does not validate. If I hit **enter** the TOTP code is cleared from the field. Also the **Validate** button is  "grayed-out" as it is inactive, so I cannot click it to validate.

![image](https://user-images.githubusercontent.com/864159/83892827-7b3be800-a74f-11ea-978a-be24f9ee16b7.png)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am using Firefox 76.0.1 (64-bit).
It looks like the browser plugin is using an different method to paste the TOTP code in than the user's paste method. I am guessing this is what is causing the TOTP entry with the browser plugin to not work for multiple fields.

One possible solution would be to allow setting multiple TOTP entry fields, one for each digit of the TOTP code.

The account I have with mulitple fields for the entry of the TOTP at login is at [Infomaniak.com](https://login.infomaniak.com). It is possible to setup a free account there to test.

**Comment by droidmonkey** [comment]
This form of OTP entry is extremely hostile to password managers. It probably relies on javascript to go from box to box when you type. The fields also do not have `maxlength=1` defined!

**Comment by varjolintu** [comment]
This could be done indeed if websites would use the `maxlength` value. Otherwise it will be a little difficult to identify, as it could identify any six input fields in a row as TOTP.

**Comment by frederickjh** [comment]
@droidmonkey  true the site has:
```css
minlength="1" maxlength="6"
```
defined on these fields. What should I put in a bug report with the website?

Here is the code from the TOTP fields in the Firefox inspector, in case it helps.

![image](https://user-images.githubusercontent.com/864159/83908772-f0b3b280-a767-11ea-9902-d67824126b86.png)

**Comment by droidmonkey** [comment]
maxlength should be 1 otherwise their website cannot work with password managers filling in TOTP fields.

**Comment by frederickjh** [comment]
Thanks @droidmonkey ! I tested this out in browser and changed all the `maxlength` to 1, but found that the form acted exactly the same as before when using Alt-Shift-O to enter the TOTP code. So I am not sure even this would fix it.

----

I am not sure I understand the reasoning that one uses to come up with a reason to separate the TOTP code entry field into multiple fields. Do they figure that this is more secure? 

I find multiple fields for a TOTP code entry a pendulum swing. For years we have had very stupid user interfaces for credit card number entry on many sites, forcing you to enter all 16 digits squashed together, even though the credit card companies realized that this is difficult to read and check, so they printed the numbers in groups of four on their cards. Now days it is common to see good credit card entry interfaces that also group the numbers this way. An now we are swinging even further with the pendulum and have TOTP entry fields with one number per field.

**Comment by droidmonkey** [comment]
Sorry I didn't mean that would fix it for keepassxc. We would still need to code support for multiple fields. However, looking at how they setup that page and the field names, this really looks like a hopeless endeavor. It will be a lot of code for not much gain.

**Comment by frederickjh** [comment]
:ok_hand:  @droidmonkey I think that I will just file bug report and ask them to consider switching to a single field for the TOTP entry. Thanks again for your help!

One other question, about the one idea that I suggested in my OP:

> One possible solution would be to allow setting multiple TOTP entry fields, one for each digit of the TOTP code.

Would this be a feasible solution  in the browser plugin or would this be a lot of work too to allow assigning multiple fields for the TOTP code entry?

**Comment by droidmonkey** [comment]
Its a lot of work because it is an exception to every other site on the internet :-)

**Comment by varjolintu** [comment]
I've made a draft PR for supporting this feature.

**Comment by baekelite** [comment]
Just wanted to chime in with another example: www.newegg.com

**Comment by droidmonkey** [comment]
Binance as well.
