### ISSUE TITLE
Can’t connect to Browser: "Failed to connect: Unknown error" Firefox/Win

### ISSUE THREAD

**Issue by Christoph-Wagner** [keepassxreboot/keepassxc-browser#905]
Trying to connect the extension to KeePassXC, the KeePassXC Taskbar Icon blinks but doesn’t prompt me for a connection.
Integration is enabled in KeePassXC and Firefox selected.
`HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\` has `C:\Users\chris\AppData\Local\KeePassXC\org.keepassxc.keepassxc_browser_tor-browser.json`, changing it to `org.keepassxc.keepassxc_browser_firefox.json` does nothing, but the files contain the same data.

I did install FF with chocolatey, but from what I can see FF is still installed as if it were installed normally.

## Expected Behavior
A popup should ask me to name the browser I want to connect.

## Current Behavior
The Taskbar icon lights up.

## Steps to Reproduce (for bugs)
1. Open Extension
2. Click Reload

## Debug info
KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Windows 10 2004
Browser: Firefox 77.0.1 (64-bit)
Extension error-log:

    Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ iconupdater.js:46:8
    Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
    Failed to connect: Unknown error keepass.js:952:13
    Error: No content script available for this tab. keepass.js:1185:25
    Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
    TypeError: PrecompiledScript.executeInGlobal: Argument 1 is not an object. ExtensionContent.jsm:567:25
    Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
    Failed to connect: Unknown error keepass.js:952:13
    Error 9: Key exchange was not successful. keepass.js:1065:13
    Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 3 keepass.js:1065:13
    sendRemoveListener on closed conduit {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}.412316862021 ConduitsChild.jsm:108
    Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
    Failed to connect: Unknown error keepass.js:952:13
    Error 9: Key exchange was not successful. keepass.js:1065:13
    Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. 2 keepass.js:1065:13
    sendRemoveListener on closed conduit {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}.412316862908 ConduitsChild.jsm:108
    Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
    Failed to connect: Unknown error keepass.js:952:13
    Error 9: Key exchange was not successful. keepass.js:1065:13
    Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8
    Error 5: Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings. keepass.js:1065:13
    sendRemoveListener on closed conduit {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}.412316863775 ConduitsChild.jsm:108
    Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:982:13
    Failed to connect: Unknown error keepass.js:952:13
    Error: No content script available for this tab. keepass.js:1185:25
    Error 9: Key exchange was not successful. keepass.js:1065:13

**Comment by Christoph-Wagner** [comment]
I had "Use a proxy application between KeePassXC and browser extension" unchecked. Checking it again fixed it. Typical layer 8 error :/

**Comment by varjolintu** [comment]
Glad it got solved. The next version of KeePassXC (2.6.0) doesn't have the optional proxy option anymore so these kind of situations will not happen in the future. You're not the first one who has reported about that option being unchecked.
