### ISSUE TITLE
totp icon on page o2online.de in user-field

### ISSUE THREAD

**Issue by Exilhamburger** [keepassxreboot/keepassxc-browser#907]
## Expected Behavior
keepassxc-icon in username-field

## Current Behavior
totp-icon in username-field

## Possible Solution
Can I change it and where can I change it

## Steps to Reproduce (for bugs)
https://login.o2online.de/auth/login
Reproduce with firefox-addon and chrome addon.

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Win32
Browser: Mozilla Firefox 76.0
or
Browser: Chrome/Chromium 83.0.4103.97
![o2 2020-06-09 120422](https://user-images.githubusercontent.com/66671965/84139843-e982f200-aa50-11ea-85dd-edb6f2456ac8.JPG)

**Comment by varjolintu** [comment]
I'm not surprised it's identified as a 2FA field because its name and ID are `IDToken1`. We will have a fix for the next version that allows you to override this properly via Choose Custom Fields.
