### ISSUE TITLE
Default group for saving new passwords doesn't work when there are no groups in KeePassXC

### ISSUE THREAD

**Issue by smorks** [keepassxreboot/keepassxc-browser#908]
## Expected Behavior

When you enter a group in "Default group for saving new passwords" option, it should save in that group whether or not you have any groups defined in your password database.

## Current Behavior

If you have a password database with no groups, and you enter a group in "Default group for saving new passwords", then you create a new entry, it puts in the entry in the default "KeePassXC-Browser Passwords" group.

When you add an entry the second time, then it prompts to create the specified group.

## Steps to Reproduce (for bugs)

1. Create new database, turn on Browser Integration
2. Connect browser to database
3. Enter a group in "Default group for saving new passwords"
4. Login to a site, in the Save banner, select "New"
5. Password is saved to "KeePassXC-Browser Passwords" group, not specified group
6. Login again, select "New" in Save banner
7. This time it's saved to the specified group, because one group exists

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.3
Operating system: Win10
Browser: Chrome

**Comment by varjolintu** [comment]
Hmm. I thought I already fixed this. Gotta check it again.

**Comment by smorks** [comment]
i think i saw it was fixed for saving to the root group, but not if you specify your own group. i could be wrong.

**Comment by varjolintu** [comment]
Yes that should be fixed. Should've tested that kind of situation also.
