### ISSUE TITLE
Firefox 77 breaks the plugin

### ISSUE THREAD

**Issue by FlyveHest** [keepassxreboot/keepassxc-browser#910]
## Expected Behavior

Keepass-XC browser just workin :)

## Current Behavior

After being auto upgraded to 77.0.1 (77.0 breaks it as well), both password field interaction and the settings pages stop workin.

## Possible Solution

Downgrade to FF 76.0.1

## Steps to Reproduce (for bugs)

1. Upgrade FF to v77
2. Try to get a stored credential or open the settings pages

## Debug info

KeePassXC-Browser - 1.6.3
Operating system: Windows
Browser: FireFox

When I try to open settings, I get the following in console.log

`Error loading options page: Error: undefined options.js:22:17`

When I try and get a stored credential on a page, I get the following in console.log

`Error: Cannot load extension settings keepassxc-browser.js:843:17`

The bug looks a lot like #704 

Downgrading FF is a bit cumbersome, you have to delete compatability.ini from your FF profile folder to avoid having FFs downgrade protection kick in and creating a new profile for you.

Furthermore, disabling autoupgrades to avoid it just re-downloading the v77 update requires either setting up a GPO in the registry (at least on Windows), or possibly using policies.json (but I could not get that to work)

**Comment by varjolintu** [comment]
Have you tried to set a new temporary profile and see if that happens there? If you can debug `options.js` via the Web Developer -> Debugger, it would also help. Just set breakpoint at the start of the first async function.

**Comment by FlyveHest** [comment]
I haven't done any debugging, no, and I haven't tried installing a new profile either (found this bug at work, and initially just needed to get my passwords working again ;)

I'll see if I can try doing a bit more digging when I get home, where I have a bit more control over the OS.

**Comment by varjolintu** [comment]
Tagging this with Windows only because I've been using the latest Firefox releases with macOS and Linux without any problems.

**Comment by droidmonkey** [comment]
Could be a group policy setting if your work enforces that

**Comment by FlyveHest** [comment]
@droidmonkey I don't think this bug is related to that, as mentioned, I rolled back to 76.0.1 and the extension works as it always has.  I had some issues with disabling autoupgrade due to GPO settings, though.

Nothing in the v77 changelog for FF indicates a change in anything related to extensions, as far as I can see.

**Comment by FlyveHest** [comment]
Well, I just got home, and here the are no issues with v77.0.1 and the extension, so it must be something with my particular installation on the other PC.

Sorry for all the commotion.
