### ISSUE TITLE
Remembering Nothing with unstoppabledomains.com

### ISSUE THREAD

**Issue by faxotherapy** [keepassxreboot/keepassxc-browser#916]
## Expected Behavior

I'd like to detect username and password field on unstoppabledomains.com site. Add-on successfully detects username through “Choose custom login fields”, but when the login panel switch to password field only, plug-in can no longer detect it via “Choose custom login fields”.

## Current Behavior

I added `https://unstoppabledomains.com/auth` to plug-in site preferences. Then, I used “Choose custom login fields” to detect the fields. Plug-in successfully detected the username field, but when the login panel change to password-only field, plug-in cannot detect password field even though I still use “Choose custom login fields”.

## Steps to Reproduce (for bugs)

1. Visit https://unstoppabledomains.com/auth
2. Use “Choose custom login fields” feature to detect “Email Address” field.
3. Repeat with Password field (but should not work)

Even though “Email Address” has been detected successfully with “Choose custom login fields”, plug-in does not remember anything.

Conclusion: I always need to manually enter login credential on this site.

## Debug info
> Please copy/paste the browser's JavaScript console messages and errors here.

OK, could you please provide a step-by-step guide for the average Joe? Thank you.
Other than this, I can see the Firefox console, but can I just copy anything I see in the console even though it does not include anything related to the plug-in?

KeePassXC - **2.5.4**
KeePassXC-Browser - **1.6.4**
Operating system: **Mac**
Browser: **Firefox**

**Comment by varjolintu** [comment]
So the _Username-only Detection_ options doesn't work for you? Can you fill the password using the context menu without using any Custom login fields?

**Comment by faxotherapy** [comment]
Thx for your prompt reply. On the sign-in page, contextual menu does not show “Fill username only” (which is, in this case, an e-mail that I must enter).

Once on the password page, right click again and choose “Fill password only”. This time, add-on says “Warning! Error: Unable to find a password field"

I kept hammering and torturing KeepassXC-Browser to remember:
1. on the first page (sign-in with e-mail address), the login field using the “choose custom…” feature of the add-on. But, it works only once. Then, afterwards, add-on forgets it. Even though I went to Settings and add domain to enable all features.
2. on the second page of the login (to put password); again I tortured the add-on to remember this password field. It's OK the first time. Then, later, add-on forgets it.

So, I'm afraid the add-on does not work at all with this site.

**Comment by varjolintu** [comment]
I used _Username-Only Detection_ with URL `https://unstoppabledomains.com/auth` and it detected the username field without any problems. As I don't have an account, I cannot view the password page. Can you copy/paste the HTML element content here? I'm curious to see why it's not identified as a password field.

If the _Choose custom login fields_ forgets the input field, maybe its content, attributes etc. are changed every time the page is loaded.

**Comment by faxotherapy** [comment]
In my case, I had to deselect _Username-only Detection_. Now, it works great on the _username_ (e-mail) page, but on the password page, I must right click on the field to bring the contextual menu and select _Fill Password Only_. Otherwise, plug-in does not automatically detect the password field. However, it detects well “Search Domains” field…

![PasswordPage](https://user-images.githubusercontent.com/6538008/85284408-0ffc5080-b487-11ea-805c-ab0ec8a354e2.jpg)

Panel section:
```html
<p class="MuiTypography-root jss717 MuiTypography-body1">Welcome Back!</p>
<form kpxcform-initialized="true" kpxcusername="kpxcpw342845640" kpxcpassword="password">
   <div class="MuiFormControl-root jss722 MuiFormControl-fullWidth">
      <p class="MuiTypography-root MuiTypography-body1" style="font-weight: 600; font-size: 18px;">2fa@use.startmail.com</p>
   </div>
   <div class="MuiFormControl-root jss722 MuiFormControl-fullWidth">
      <label class="MuiFormLabel-root MuiInputLabel-root jss726 MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-shrink MuiFormLabel-filled" data-shrink="true" for="password">Password</label>
      <div class="MuiInputBase-root MuiInput-root jss723 jss733 MuiInputBase-formControl MuiInput-formControl MuiInputBase-adornedEnd">
         <input aria-invalid="false" id="password" type="password" class="MuiInputBase-input MuiInput-input MuiInputBase-inputAdornedEnd" value="" data-kpxc-id="password" kpxcfields-onchange="true" unchanged="true" kpxc-username-field="true">
         <div class="MuiInputAdornment-root MuiInputAdornment-positionEnd">
            <button class="MuiButtonBase-root MuiIconButton-root" tabindex="0" type="button" aria-label="Toggle password visibility" title="Show Password">
               <span class="MuiIconButton-label">
                  <svg class="MuiSvgIcon-root" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="presentation">
                     <path d="M12 4.5C7 4.5 2.73 7.61 1 12c1.73 4.39 6 7.5 11 7.5s9.27-3.11 11-7.5c-1.73-4.39-6-7.5-11-7.5zM12 17c-2.76 0-5-2.24-5-5s2.24-5 5-5 5 2.24 5 5-2.24 5-5 5zm0-8c-1.66 0-3 1.34-3 3s1.34 3 3 3 3-1.34 3-3-1.34-3-3-3z"></path>
                  </svg>
               </span>
               <span class="MuiTouchRipple-root"></span>
            </button>
         </div>
      </div>
   </div>
   <button class="MuiButtonBase-root MuiButton-root jss729 MuiButton-contained MuiButton-containedPrimary MuiButton-fullWidth" tabindex="0" type="submit"><span class="MuiButton-label">Sign In</span><span class="MuiTouchRipple-root"></span></button>
</form>
<hr class="MuiDivider-root jss728">
<div class="jss734"><button class="MuiButtonBase-root MuiButton-root MuiButton-outlined MuiButton-fullWidth" tabindex="0" type="button" style="text-transform: none; height: 50px;"><span class="MuiButton-label"><img src="/static/images/oauth/google-oauth-icon.svg" style="margin-right: 0.5em;">Continue with Google</span><span class="MuiTouchRipple-root"></span></button></div>
<div class="jss731"><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary" tabindex="0" type="button" style="text-transform: none;"><span class="MuiButton-label">Reset Password</span><span class="MuiTouchRipple-root"></span></button></div>
<div class="jss731"><button class="MuiButtonBase-root MuiButton-root MuiButton-text" tabindex="0" type="button" style="text-transform: none;"><span class="MuiButton-label">Back</span><span class="MuiTouchRipple-root"></span></button></div>
```

**Comment by varjolintu** [comment]
@faxotherapy Thanks for the info. I'll see what I can do to improve the login flow.

**Comment by varjolintu** [comment]
Are you still having this problem with the latest version?

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
