### ISSUE TITLE
Bug?  How to Log into a Website with Multiple URL's with Common Domains?

### ISSUE THREAD

**Issue by CerebralFreeze** [keepassxreboot/keepassxc-browser#919]
## Overview
I don't know if this is a bug issue or not because I _believe_ that I was able to log into different URL's with the same login and password as long as the domain was the same.  But, it seems that starting from a week or so ago, I can't log into websites that have the same domain but the URL is slightly different.  Am I going crazy?

For example, I _thought_ that I could log into _verizon.com/signin_ or _signin.verizon.com/logintomyaccount_ by using the same KeePassXC entry but I don't definitely remember.  If not, would I have to create two separate KeePassXC entries for each URL that requests a password?  In other words, do I have to make a KeePassXC entry for _verizon.com/signin_ and then make a totally separate KeePassXC entry for _verizon.com/logintomyaccount_?

I also tried adding alternate URLs by editing an entry, going to the Browser Integration section, clicking the Add button all the way to the right, and then adding the alternate URL into the **Additional URL's section** (by the way, according to strict rules of grammar, it should really state Additional URLs although some people use it your way), but that didn't seem to make a difference.  The login and password wouldn't work in Chrome unless the URL exactly matched the one in the **URL:** field in the **Entry** section.

## Steps to Reproduce
1. I go to https://www.verizon.com/home/myverizon/. 
2. I try to log in with my Verizon Fios entry in which the URL is stated to be https://ssoauth.verizon.com.  I also added https://verizon.com as an additional URL in the **Browser Integration** section.
3. The website doesn't initially recognize the website and does not list my verizon logins and passwords.  I use the extension option, Choose custom login fields but that has no effect.  After playing for it for 5 minutes, I press Escape at one point and then suddenly, the website recognizes all my verizon logins and passwords.

## Expected Behavior
As long as the main domain is the same, the login and password should be able to log into any of the domain's websites.

## Actual Behavior
Weird.  KeePassXC sometimes seems to recognize all various URLs as long as the domain name, Verizon.com is the same.  Sometimes it doesn't even seem to recognize the login and password fields and I have to play with it.  

## Context
It seemed to just start doing this about a week or so ago.  It actually decreases my productivity a lot as I try to correct the recognition of the login and password fields.  I can just open KeePassXC directly and cut and paste but that would be too logical and simple for me.  I am what some people call a stubborn idiot.

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.5.4
Revision: c023bf9
KeePassXC-Browser Version: 1.6.4

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows 10
Desktop Env: I use a program called Dexpot that creates virtual desktops.  Is that relevant?
Windowing System: I don't know what this even means.

**Comment by varjolintu** [comment]
Strange. I made an entry with https://ssoauth.verizon.com/ and it works without any problems. I also tried the same with https://verizon.com as the entry URL and everything worked.

Seems that the username field is identified as a 2FA field but that could be overridden with Custom Login Fields.

**Comment by CerebralFreeze** [comment]
varjolintu,

I replied to you but I don't know what happened to it.  I constantly play with the settings so I might have inadvertently changed something.  It might be that I checked the "Return only best matching credentials".  I'll see if it keeps doing it and I'll let you know.  Thanks for being so responsive!

John

**Comment by varjolintu** [comment]
@CerebralFreeze Btw, I used 2.6.0 for testing this and it has some fixes for the domain matching, especially with _"Return only best-matching credentials"_ enabled. You should also give it a try.

**Comment by varjolintu** [comment]
Closing the issue. Will reopen if the problem still exists.
