### ISSUE TITLE
usability improvement for most common login use case flow

### ISSUE THREAD

**Issue by awesomer** [keepassxreboot/keepassxc-browser#922]
## Expected Behavior

- Assuming KeepassXC is running, but locked
- Clicking the icon for KeepassXC-browser brings up a dialogue which says "Database not Opened" and has a button to click "Reopen Database."
- When one clicks on "Reopen Database" the KeepassXC window foregrounds and focuses, and one unlocks it
- When tabbing back to the browser, the keepassxc-browser is aware that the database is now unlocked and allows one to fill in the password.

Not coincidentally, this is the exactly flow that I am accustomed to coming from 1password + 1password browser plugin.

## Current Behavior

- Assuming KeepassXC is running, but locked
- Clicking the icon for KeepassXC-browser brings up a dialogue which says "Database not Opened" and has a button to click "Reopen Database."
- When one clicks on "Reopen Database" the KeepassXC window flashes in the taskbar, but does not focus or foreground
- One then alt-tabs or clicks on KeepassXC in the taskbar, and unlocks KeepassXC
- When tabbing back to the browser, the "Database not Opened" dialogue remains, with no awareness that the database is now unlocked
- One must then re-click the icon in order to get the "is connected" message, and to be able to enter passwords.

All of this extra clicking occurs every single time keepassxc-browser is used with a locked database, which seems like it at very least doubles the average time it takes to log in anywhere.

## Possible Solution

Make it work like expected, and like other similar products do.

## Steps to Reproduce (for bugs)
See above.

## Debug info
KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.4
Operating system: Windows 10 (insider preview fast branch, fwiw)
Browser: Chrome and Firefox

## Additional notes
Thanks for maintaining this very awesome tool, I greatly appreciated being able to free myself from 1password's predatory subscription based model with a fully featured browser plugin. Apologies if I have missed an existing issue which covers this topic.

**Comment by droidmonkey** [comment]
This is already fixed in 2.6.0

**Comment by awesomer** [comment]
Unfortunately, I am unable to reproduce this being fixed in 2.6.0.

I downloaded a nightly build of 2.6.0 for Windows, and here's what happens when I first start Chrome, then start KeepassXC 2.6.0 and try to log into a site with KeepassXC 2.6.0 still locked.

1) Click plugin icon, get "Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings." 
2) Click "reload" and get "Database not Open" dialogue.
3) Click "re-open database" and get a popup window which is foregrounded and seems to be ready for input, but does not accept keystrokes. Tabbing away and back makes it accept input, as does all subsequent "re-open database," it only doesn't accept input on the first "re-open database" attempt.
4) Enter the password, and focus is brought back to the plugin, which still says "Database not Open."
5)  Clicking "re-open database" again makes the "Re-detect login fields" button appear, but still says "Database not Open" and clicking "Re-detect login fields" does nothing.
6) Re-click plugin icon, and get correct login choices to click on.

It's a lot better than 2.5.4, but it still does not reflect the smoothest/fastest flow.

**Comment by droidmonkey** [comment]
That is the best we can do on windows unfortunately, foregrounding windows is hit or miss

**Comment by awesomer** [comment]
In step 5 and 6, are you clicking on the icon for the extension in the extension-toolbar area, or in the login box?

To be clear, when I reproduce that behavior, I am clicking on the icon in the extension-toolbar area.

**Comment by ComodoHacker** [comment]
I experience similar behavior. My scenario is:

1. Open Firefox, load some website's login page.
1. Click KeepassXC icon in the login input field.
1. KeepassXC  pops up with Unlock Database dialog. While KeepassXC  window does pop up to the foreground, half or most of the time _it doesn't receive focus_. The focus remains in the browser window, typically in the login field.
1. If you, unaware of that, type in your KeepassXC database password and press Enter, you end up sending your KeepassXC database password _to the website in cleartext!_.

I can't say what exactly triggers this behavior, but I noticed most of the time it's the first time KeepassXC is invoked in my current Windows session (I have 'Launch KeepassXC at system startup' enabled in settings). Looks like in subsequent invocations KeepassXC window receives focus, but I'm not 100% sure.

This is not only usability issue, but also a security one. Leaked master password can cost someone very much.
Please reopen this issue or let me know if I should create a new one.

______________________
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 7 Version 6.1 (Build 7600)
CPU architecture: x86_64
Kernel: winnt 6.1.7600

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5
