### ISSUE TITLE
Disable auto-open database on browser launch

### ISSUE THREAD

**Issue by sang-ook** [keepassxreboot/keepassxc-browser#925]
## Overview
When I launch Firefox browser, KeePassXC launches as well.

Is there a way to disable auto-open database feature? I don't seem to find it in extension settings.

**Comment by varjolintu** [comment]
Enable the proxy.

**Comment by sang-ook** [comment]
I have proxy enabled, yet database still opens on browser launch.

![Screenshot from 2020-07-04 13-50-52](https://user-images.githubusercontent.com/67825889/86511911-e62f1c00-bdec-11ea-8e22-e898de00e5c0.png)

**Comment by varjolintu** [comment]
Then you're probably using some kind of Snap manager which has modified the program launch so it does't find the proxy but KeePassXC itself. The easiest solution for this is to use the official PPA or AppImage.
