### ISSUE TITLE
KeepassXC doesn't detect login form for CTemplar Email on the first load

### ISSUE THREAD

**Issue by superdev0714** [keepassxreboot/keepassxc-browser#926]
KeepassXC doesn't detect login form for [CTemplar](https://mail.ctemplar.com/signin) on the first load.
If try to write something on `username` or `password` fields or hit the `Redetect Login Fields` button on the Extension, detection get to success.

## Expected Behavior
KeepassXC should detect login form after first loaded CTemplar.

## Current Behavior
KeepassXC doesn't detect login form.

## Step to Reproduce
1. Empty the `username`, `password` fields
2. Reload the sign in page

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.4
Operating system: Windows 10, Ubuntu 18.04
Browser: Chrome/Firefox

Thank you for your support

**Comment by varjolintu** [comment]
That is only because the page is already loaded, but for some reason they want to show a div with full of hidden links to advertisers, and that div doesn't even do anything. It just slows the page loading.

**Comment by superdev0714** [comment]
Got it, Thank you
