### ISSUE TITLE
MutationObserver is created each tab focus, sites eventually crawl

### ISSUE THREAD

**Issue by fatalis** [keepassxreboot/keepassxc-browser#927]
## Expected Behavior
Sites shouldn't slow down dramatically after the tab has been focused many times

## Current Behavior
Sites slow down dramatically after the tab has been focused many times

## Possible Solution
https://github.com/keepassxreboot/keepassxc-browser/blob/7cf428c3d3ea3b8e86e3f01a9ccbab4b35bb70fc/keepassxc-browser/content/keepassxc-browser.js#L2026

This line claims that: "Doesn't run a second time because of _called.initCredentialFields set to true" but if you check how many times initcb -> initObserver is called, this is false

## Steps to Reproduce (for bugs)

1. Go to a site with dynamic DOM
2. Hold ctrl+tab to force tabbing in and out of the tab many times
3. Hundreds of MutationObservers will now cause DOM to crawl

## Debug info

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.4
Operating system: Linux
Browser: Chromium

**Comment by droidmonkey** [comment]
Didn't I comment on this?? 😭

**Comment by varjolintu** [comment]
Ouch. My bad. Fixed.
