### ISSUE TITLE
Firefox Browser Add-Update-Dismiss bar disappears too quickly

### ISSUE THREAD

**Issue by jerryhall** [keepassxreboot/keepassxc-browser#929]
I have become accustomed to adding a new or updated email address and password in form fields, then moving my mouse up under the bookmarks bar in Firefox with one hand, and clicking Enter with the other hand. 

The problem is I get only a very brief few seconds when the bar to Add-Update-Dismiss pops up to allow me to store the login information.

Is this something I can control via settings? 

Using Firefox 77.0.1 64-bit on current Windows 10.
I do use PrivacyBadger but, get the same results with or without it running.

Thanks!

**Comment by varjolintu** [comment]
Try to increase the Redirect Allowance in the extension settings.
