### ISSUE TITLE
Passwords not saved

### ISSUE THREAD

**Issue by rugk** [keepassxreboot/keepassxc-browser#93]
## Steps to Reproduce (for bugs)

1. Go to https://bugs.documentfoundation.org.
2. Register and save password.

## Expected Behavior

Password saved in group "KeePassXC-Browser" or so.

## Current Behavior

The group is not even created. Only the old "KeePassHttp Passwords" is still there.

Also the popup showed no reaction when clicking on "New". It did not disappear.

## Possible Solution

Maybe related to other bugs?

## Debug info

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
Operating system: Linux
Browser: Firefox 59
Proxy used: yes

**Comment by macau23** [comment]
What happens when you click twice? Might be #80

**Comment by guido4000** [comment]
I have the same problem. On some sites the 'New' button does not react at all (even on multiple clicks).

**Comment by lordraiden** [comment]
I have the same problem,  sometimes the "new" button does nothing.
I think it happens when despite being linked to keepassXC there must be something broken because you can not add new passwords, and it looks like the pluging isn't able to access the databese either although in the interface it looks like it can, becase is not detecting websites either.

**Comment by woj-tek** [comment]
Same problem here.

KeePassXC-Browser Version: 1.0.1
KeePassXC Version: 2.3.1 
macOS High Sierra

**Comment by varjolintu** [comment]
Cannot reproduce this. Is is possible for you to debug the extension? Put breakpoints to `keepass.js` lines 172 and 173. See if any parameters are empty in the `messageData`.

**Comment by z3ntu** [comment]
![image](https://user-images.githubusercontent.com/3768500/38209232-00645fc6-36b4-11e8-8da9-97d8011813fe.png)
Can reproduce the issue on https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_signup_form_modal

**Comment by varjolintu** [comment]
@z3ntu That site works just fine for me (both new and update). I even tried to delete the password group from my database and a new one was created. So this is a bit strange.

**Comment by varjolintu** [comment]
Those `background.js` related errors are from different extension, not KeePassXC-Browser.

**Comment by rugk** [comment]
Thanks, I've reported it to the author of that add-on.

**Comment by varjolintu** [comment]
@rugk Btw, your error messages show that the extension is not even connected to the database you're trying to save the credentials to.

**Comment by rugk** [comment]
Indeed it does say that. Please read what I wrote:
> BTW the localized message "KeePassXC-Verbindung fehlgeschlagen, bitte erneut versuchen ", whcih states the KeePassXC connection failed, is surprising, because AFAIK the connection worked and the UI never indicated or suggested me to reconnect the session.

**Comment by cdancette** [comment]
I have the same issue : I can't save any password on any site with this extension

**Comment by varjolintu** [comment]
@cdancette Can you download the sources of this branch and give it a try? https://github.com/keepassxreboot/keepassxc-browser/tree/release_102

To load the extension manually, go to `about:debugging` and click "Load Temporary Add-on", and select `manifest.json` from the folder.

**Comment by cdancette** [comment]
When I login to a website, the icon becomes grey with a red dot and says "Timeout or not connected to KeepassXC" (but i am connected)

**Comment by varjolintu** [comment]
@cdancette Can you monitor what happens with keepassxc-proxy process during this behaviour? Does it quit by itself?

**Comment by mannp** [comment]
I have the same issue, pressing the button on any webpage never save new details to the database.

**Comment by varjolintu** [comment]
@mannp Same instructions to you: check the behaviour of keepassxc-proxy process and try KeePassXC 2.3.2 (build from the sources) if possible.

**Comment by mannp** [comment]
@varjolintu will do, will try and look after work today. I am using the lastest git on arch, so that does seem to solve it for me.

Unless the 2.3.2 is a differant branch, not sure.

**Comment by varjolintu** [comment]
@mannp It's a different branch.

**Comment by mannp** [comment]
@varjolintu yes its the develop branch, which I thought was ahead of any pre release branches, or have I misunderstood?

Thanks

**Comment by z3ntu** [comment]
For me it worked now on https://www.w3schools.com/howto/tryit.asp?filename=tryhow_css_signup_form_modal
![image](https://user-images.githubusercontent.com/3768500/39918807-e62b403a-5511-11e8-916e-f38d3d7909ae.png)

But I had to press three times on the extension icon, the first time the normal popup came, then had to close it again and then the password dialog came up which worked (see https://youtu.be/aX-NjgT9gwY)

**Comment by varjolintu** [comment]
For some pages the popup doesn't show on a first try (there's a separate issue for this: #67). @rugk, are you still having the issue with saving the credentials? I'm tempted to close this issue and focus to continue #67.

**Comment by rugk** [comment]
Yeah…

**Comment by herexf** [comment]
I got same issue, 

Cannot save password to database, even I clicked credentials under right button "KeePassXC-Browser".
All running with latest versions.

Thanks

**Comment by rugk** [comment]
Inded, I can reproduce this again.

**Comment by varjolintu** [comment]
Still having the problem?

**Comment by rugk** [comment]
no
