### ISSUE TITLE
KeepassXC does not populate all accounts in list

### ISSUE THREAD

**Issue by pakar** [keepassxreboot/keepassxc-browser#930]
## Expected Behavior
When you have multiple accounts for a single server it should present all available accounts.

## Current Behavior
I have 5 accounts for a single service, but when the drop-down list gets populated only 4 accounts shows up.

## Debug info
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.4
Operating system: Linux
Browser: Brave (Chrome based)

All accounts have the same URL configured. Title, username and passwords are of course different.

**Comment by droidmonkey** [comment]
Check that the fifth account does not have the "disable for this site" custom data (Edit entry - > properties)

**Comment by pakar** [comment]
Oh.. Did not know about that flag that shows up in the plugin, but it's still weird that it got set on a new install and import of a csv (only used "allow all selected" without deselecting any individual items).
This config is only available in the plugin data as a json string as far as i can see. There is no option to edit this from the KeePassXC-browser plugin?

I'll keep an eye on it and reopen a issue if it appears again and/or if i can find a way to reproduce the behaviour.

**Comment by dreamlayers** [comment]
I have this problem myself now. I'm using KeepassXC-Browser 1.7.8.1 in Firefox 89.0 in Ubuntu 21.04 with KeepassXC 2.6.2. On https://www.tradingview.com it kept repeatedly popping up the confirmation prompt for fetching credentials, even when I was logged in to the site. So I clicked "Disable for this site". Now I can't fetch passwords for that site from the browser, and I don't see where to re-enable this.

**Comment by varjolintu** [comment]
@dreamlayers Extension settings, Site Preferences tab.
