### ISSUE TITLE
Option to turn off version checking is not displayed/available

### ISSUE THREAD

**Issue by agsteele** [keepassxreboot/keepassxc-browser#935]
I understand that the KeepassXC-browser add-on for Firefox should have an option to turn off version checking.

I've done my best to locate the option in the add-on settings but, unless I am missing something obvious, it has disappeared from my version.

I go to the add-on settings and check all the options and the version checking option isn't present.

I have worked around this by the option in KeepassNatMsg plugin but the option in the Firefox add-on would sgtill be useful.

KeePassXC-Browser - 1.6.4
Operating system: Win32
Browser: Mozilla Firefox 78.0

Because I have the workaround in place 
KeePassXC reports as version 2.6.0

**Comment by varjolintu** [comment]
Under Updates card on the General tab, _Check for updates of KeePassXC_. Set that to _Never_.
