### ISSUE TITLE
Login Fields are not recognized since KeePassXC-Browser 1.65

### ISSUE THREAD

**Issue by XtraLarge** [keepassxreboot/keepassxc-browser#936]
I've a private login system, with a nice html-login forrm, embedded Javascript and a css for styling. You can take a look on https://login.derwerres.de. 

Since 2 years keepassxc-browser works perfectly and recognized the login fields, but since version 1.65 the login field were not detected, so that I can not choose the login information. (no green symbol to choose).

I've found a workaround ... take the Context-Menu (right button) and choose KeePassXC-Browser to fill username and password. After that action the green icon apears so I can choose my login informations and the field were filled correctly.

Also I've tried to find which part of the page results the problem, it seems that the javascript in combination with a part of the css is the problem, but I can not find a solution and I think it is not the right way to tune the login page.

Please help!

I've you want the source code of the login page I can attach it on request.

## Debug info
KeePassXC - Version 2.6.0
KeePassXC-Browser -Version 1.6.5
Operating system:  Win Version 2004
Browser: Chrome Version 83.0.4103.116

**Comment by XtraLarge** [comment]
I've tried also Firefox Version 78.0.2 with KeePassXC-Browser 1.63 and the result is fine. The login field were detected correctly!

**Comment by varjolintu** [comment]
This is probably caused by the new high CPU related fixes, and I have a good idea why this might happen. Gonna fix it soon.

**Comment by XtraLarge** [comment]
thx, that would be great!
