### ISSUE TITLE
2FA authenticator field not recognized at HEY.COM

### ISSUE THREAD

**Issue by OLLI-S** [keepassxreboot/keepassxc-browser#938]
## Current Behavior
At hey.com the field for entering my 2FA key is not recognized by KeePassXC Browser.
Here the field information:

```
<input class="input input--underlined align--center txt--xx-large txt--bold" autofocus="autofocus" autocorrect="off" autocapitalize="off" required="required" autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]*" size="12" type="text" name="code" id="code">
```

The name ```code``` could be anything, so I don't know if you want to change anything here.

## Debug info from KeePassXC
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 2004
CPU architecture: x86_64
Kernel: winnt 10.0.19041

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

## System Specs
**Operating System**: Windows 10 Pro 64-Bit Version 2004 (Build 19041.329) 
**Browser**: Microsoft Edge (Chromium Engine) version 83.0.478.61 (Offizielles Build) (64-Bit)
**KeePassXC-Browser**: Version 1.6.4

**Comment by varjolintu** [comment]
Does the latest version 1.6.6 fixed the issue?

**Comment by OLLI-S** [comment]
I have downloaded the extension from the Microsoft Edge-Add-Ons:
https://microsoftedge.microsoft.com/addons/detail/keepassxcbrowser/pdffhmdngciaglkoonimfcmckehcpafo
Here **1.6.4** is available.

**Comment by varjolintu** [comment]
@OLLI-S Microsoft validates the extension's really slow. It can take 2-7 days.

**Comment by OLLI-S** [comment]
Now **1.6.5** is available in the Microsoft Edge-Add-Ons and here it works!
**Issue solved**.
Thank you very much, @varjolintu
