### ISSUE TITLE
Custom login fields cannot be selected on openmediavault

### ISSUE THREAD

**Issue by tophee** [keepassxreboot/keepassxc-browser#939]
## Overview
Login fields are not detected openmediavault login page (which is probably their fault), but when I want to manually select the custom login fields, it is not possible, i.e. no fields are detected at all.

## Steps to Reproduce
1.  Navigate to the login page of your openmediavault instance (and logout if you are already logged in).
2.  In the the klick on the browser extension and select "Choose custom login fields"
3. None of the login fields will be selectable.

## Expected Behavior
I can click on both the username and the password field to select each of them as a custom field. (This works when using Keepass 2 and ChromeIPass)

## Actual Behavior
Neither of them is selectable

Screenshot:
![image](https://user-images.githubusercontent.com/3662750/87257735-c60ef500-c49d-11ea-8d0d-c2f229ca4c6e.png)

## Context
![image](https://user-images.githubusercontent.com/3662750/87257751-d9ba5b80-c49d-11ea-9698-c2ef065c121c.png)

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.5
Operating system: Win32
Browser: Chrome/Chromium 83.0.4103.116

[NOTE]: # ( Pick choices based on your environment )
Operating System: Windows

**Comment by varjolintu** [comment]
"Show more" doesn't help?

**Comment by tophee** [comment]
No, pressing M or "Show more" does absolutely nothing.

**Comment by bunnybooboo** [comment]
@tophee as your experience matches one of the issues unearthed during my bug testing, please take a look at #942 I wonder if the credentials you are attempting here are "expired" for this site?

**Comment by tophee** [comment]
@bunnybooboo I don't see so much similarity between issue #942 and mine. My problem concerns the detection of login fields, not retrieval of anything from the database. 

The credentials for this site are definitely not expired because the problem occurred when I was trying to create them by logging into the site and then accepting the question from KeepassXC whether I want to save those new credentials. When KeepassXC didnt ask me, I logged out again and started by clicking on "Redetect login fields" and when that didn't do anything, I clicked on "Choose custom login fields" which didn't work either so that's when I decided to create the bug report (and because I knew that the old KeePass plugin had no problem detecting the fields on that site).

In the mean time I found the flugin to behave even weirder on another site (the cockpit login page of my local cockpit instance). The plugin failed to detect the login fields and "redetect" didn't help either. And when I went to set them manually , I got this:

![image](https://user-images.githubusercontent.com/3662750/87567251-5c246480-c6c4-11ea-9dd6-4a4dee5a9781.png)

No, this is not a collage that I created, that is entirely the work of the plugin. I nevertheless actually managed to set the fields correctly and auto-type now works on that page. In order to succeed, I had to do click on the larger version of the respective login field (the small one wasn't clickable) and once I had gone through all three steps of the process, I was able to do the same procedure once again, this time clicking on the small version on the fields (i.e. the actual fields on the page). So it was as if the plugin put an extra enlarged layer over the actual page... Never seen anything like it.

It's a pity, because after having used KeePass for more than 10 years, I was glad to find a more modern app to switch to but it seems that while the app is better the browser plugin has failed me more often in the past few days than the ChromeIPass plugin did in the past years. I think there is exactly one type of login page that the old plugin didn't work with and that is the login page for Discourse discussion forums. Everything else has just been working, so, assuming that it is open source, I'm wondering why you can't just use (and further improve) the code from the functioning plugin?

**Comment by tophee** [comment]
> The collage you see is happening because content scripts are executed in each iframe. It's not currently possible (and I'm not sure if that's possible at all) to show it only on the mainframe and still be able to select content inside the iframe. (hembanken2.danskebank.se).

It's good that you seem to have identified the source of the problem but I don't think it's impossible solve this. I am not a developer, but ChromeIPass works flawlessly on both of them so I'm inclined to say: KeePassXC is doing something wrong here.

> Actually our extension has forked from ChromeIPass but the input field detection and everything else has been changed quite a bit. ChromeIPass detected all input fields in the page in 500 ms intervals and it didn't ignore fields that are hidden, outside the page etc. 

How ironic, because the only sites where ChromeIPass doesn't work for me (discourse forums) have a hidden loginpage (i.e. the login modal is loaded but remains hidden until the user clicks on "login"). So the hidden state of the login fields is not the reason for the failure. Anyway, KeePassXC works in that case.

> I tested the Danskebank site and I could still fill the credentials using the context menu. It can be used to force the filling.

There are many ways of logging on at Danskebank. The one where KeePassXC was failing me was this one: 
 https://danskebank.se/privat/kundservice?n-login=pbmobid

Is that what you tested? 

And remember that the problem I am reporting is not about not being able to fill in credentials but about not being able to properly select custom login fields. 

Just to be clear: I understand that no algorithm for detecting login fields is perfect (which is why it's great to have the option to manually choosing them is great!), so this bug report is entirely about the "Choose custom user fields" feature, so this is irrelevant here:

> EDIT: Also, because the iframe is in another subdomain, your entry URL needs to be `https://danskebank.se`.

(But yes, my URL is (and has always been `https://danskebank.se` and once I managed to tell KeePassXC where the login field is auto-type does work just like it did with ChromeIPass before).

**Comment by varjolintu** [comment]
@tophee For me ChromeIPass shows the same kind of overlay on both iframes, just like our extension, and I can select the input fields normally with both extensions.

I think you're just affected by the bug in 1.6.5 which was fixed immediately with 1.6.6. Please verify you're using the latest version.

The bug with the overlays is already covered in here: https://github.com/keepassxreboot/keepassxc-browser/issues/454

**Comment by tophee** [comment]
Yes, that overlay bug looks indeed similar. And indeed, when I created the issue, I was on 1.6.5 (as shown in the first post) and now I'm on:

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Chrome/Chromium 83.0.4103.116

Strangely, I don't recall upgrading, and all this most have happened in the past few days. But I guess you found the cause and and so I'll close this for now, hoping that things will work more smoothly from now on. Thanks for your time!
