### ISSUE TITLE
Username+password field detection not working on personalcapital.com

### ISSUE THREAD

**Issue by nbartos** [keepassxreboot/keepassxc-browser#94]
The login page is here:  https://home.personalcapital.com/page/login/goHome.  This is a multi-step form with username first then password second.  When using the chromeIPass extension, I can use the right click "fill user+pass" for the username field, and right click "fill pass only" for the password field.

## Expected Behavior
There should be the ability to fill form data in one form or another, as there is with chromeIPass.

## Current Behavior
I have tried doing "choose own credentials for this page" and also right clicking with "fill user+pass" and "fill pass only", but I cannot data to contently fill in the username or password fields.

## Possible Solution
Allow the right click "fill user+pass" and "fill pass only" options to work as they do in chromeIPass.

## Steps to Reproduce (for bugs)
1.  Create credential entry in keepassxc for home.personalcapital.com.
2.  Go to https://home.personalcapital.com/page/login/goHome
3.  Right click on username field and go to keepassxc -> fill user+pass
4.  Observe that the credentials are not filled in the form

KeePassXC - 2.3.1
keepassxc-browser - 1.0.1
Operating system: Linux
Browser: Chrome
Proxy used: YES

**Comment by varjolintu** [comment]
Cannot reproduce this. Filling the user from the context menu works without any problems. Also works from the popup.

**Comment by varjolintu** [comment]
I ran some new issues with this page. Trying to make some necessary fixes.

**Comment by nbartos** [comment]
I have found that the problem is intermittent.  Sometimes when I do a reload of the page, it works.  Often I have the problem on paypal.com when completing a transaction from another site.  I also hit it on many other sites, it's really getting annoying.  Whenever I use the old chromeIPass, the right click "fill user+pass" and "fill pass only" work very reliably.

**Comment by varjolintu** [comment]
I think I may have broken something if chromeIPass still works. However, I found a reason for it. Usually credentials are identified with a username and password combination. And there's no situation handled (properly) when only username field is visible. Earlier I added a support for just identifying the password field.

And the good news is that I already have a fix under development, and for now it seems to work every time. I still need to verify it with multiple sites though.

**Comment by nbartos** [comment]
That makes sense, it's possible that I've only been hitting this on sites that split out the username and password into separate pages (as that's getting a lot more common these days).  If you have a test build of the extension I can install, I'd be happy to test.

**Comment by varjolintu** [comment]
You can try the extension by using the sources of this branch https://github.com/keepassxreboot/keepassxc-browser/tree/username_fields. It fixes the issue (and also solves the usage of autocomplete on Google Accounts page)

Guide: [https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually](https://github.com/keepassxreboot/keepassxc-browser/wiki/Loading-the-extension-manually)

**Comment by nbartos** [comment]
So far I'm able to fill in values for each website I've tried.

**Comment by varjolintu** [comment]
Nice! I'll make that fix to a PR.
