### ISSUE TITLE
Slimjet support

### ISSUE THREAD

**Issue by haqk** [keepassxreboot/keepassxc-browser#940]
Please add Slimjet (Chrome) browser integration, thanks.

**Comment by droidmonkey** [comment]
You can use the custom browser feature in the advanced browser settings in KeePasXC. This is only available under Mac and Linux at this time. Otherwise we will not be adding additional niche browsers.

**Comment by haqk** [comment]
I got it to work for Slimjet in Ubuntu and here's how. I'm guessing this should work for any browser that supports native messaging.

**In KeePassXC:**
- Tools > Settings > Browser Integration > Advanced > Use a custom browser configuration location: /home/<username>/.config/<browser>/NativeMessagingHosts
- Click OK

**In browser:**
- Connect to the database from KeePassXC Browser
