### ISSUE TITLE
Not detecting login fields after upgrading to 2.6.0

### ISSUE THREAD

**Issue by scottman01** [keepassxreboot/keepassxc-browser#941]
## Overview
I upgraded to 2.6.0 and now none of the login fields for any of the websites seems to work. 
KeePassXC-Browser Version: 1.6.5
Chrome version Version 81.0.4044.122 (Official Build) (64-bit)
Windows 10

**Comment by varjolintu** [comment]
This can be because of the high CPU fixes in the extension's new 1.6.5 release or because of improvements in the URL matching in KeePassXC 2.6.0.

Is the extension connected to your database? Does the extension popup give you any hints?

**Comment by mbunkus** [comment]
Same issue for me. The extension isn't detecting login fields anymore, neither automatically nor when I select the entry from the context menu.

Before the latest update (not sure if KeePassXC or KeePassXC-Browser) this used to work at least most of the time.

The extension does say that it is connected to the database as usual. The popup doesn't show anything out of the ordinary, just the  usual "connected to database as…" message.

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.5
Operating system: Win32
Browser: Chrome/Chromium 83.0.4103.119

**Comment by varjolintu** [comment]
You can try KeePassXC 2.5.4 so we can verify if the problem is indeed in the extension. Does Web Inspector / JavaScript console say anything?

**Comment by mbunkus** [comment]
Frustratingly things started to work pretty much two minutes after having posted my earlier comment, while they didn't work all of yesterday & today until five minutes ago.

When/if it happens again, I'll try downgrading KeePassXC.

**Comment by scottman01** [comment]
So, everything is connected/loaded that i can tell. It works on the Github website and a few others, but for like my bank's website and Outlook nothing. I can right click and populate the fields that way. I will try going back to 2.5.4 and let you know.

**Comment by varjolintu** [comment]
@scottman01 I'm pretty sure https://github.com/keepassxreboot/keepassxc-browser/pull/937 fixes this. Gonna make a new release soon because it seems many are affected by this.

**Comment by scottman01** [comment]
Ok, still having the problem with 2.5.4. Looking forward to #937.

Thanks!

**Comment by varjolintu** [comment]
@scottman01 1.6.6 is released. Please give an update when you have time to test it.

**Comment by scottman01** [comment]
This seems to be working now. Thank you! I really appreciate all that you and everyone else affiliated with keepassxc have done. It is a great password manager!
