### ISSUE TITLE
[Bug] Browser Integration lost since KeePassXC v2.6.0

### ISSUE THREAD

**Issue by bunnybooboo** [keepassxreboot/keepassxc-browser#942]
## Expected Behavior
In Firefox: with an unlocked KeePassXC DB (v2.6.0), and KeePassXC-Browser (v1.6.6), I expect full integration between login fields in the browser with the credentials saved in KeePassXC.

## Current Behavior
Unable to get KeePassXC to fill credentials.

## Steps to Reproduce (for bugs)
1. Open Web Browser
2. Unlock KeePassXC
3. Toolbar icon turns GREEN (indicating correctly connected DB)
4. Navigate to login page (tested on https://github.com/login AND https://www.reddit.com/login/)
5. Login field credentials icon turns GREEN (indicating login field is also recognised)
6. When interacting (click in login field, tab through fields) no corresponding DB entry is identified
7. Clicking the GREEN toolbar icon
`KeePassXC-Browser is connected to KeePassXC and has been configured using the following identifier: {user defined}`
8. Clicking the GREEN login field icon
`Error! no logins found`
9. Right click in login field >> KeePassXC-Browser >> Fill Username and Password
`Error! no logins found` 

## Debug info
Security Error: Content at https://github.com/login may not load or link to moz-extension://{user-defined}/js/content/inject.js.
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). -- content.js:40:10
KeePassXC - v2.6.0
KeePassXC-Browser - v1.6.6
Operating system: Arch Linux
Browser: Firefox (tested in Release [78.0.2] and Nightly [80.0a1]), Chrome (83.0.4103.116) / Chromium (83.0.4103.116)

**Comment by varjolintu** [comment]
I assume browser restart did not fix the issue? Could you also verify the entry settings for example for GitHub, and double check if there's anything set in the Browser Integration tab of the entry. If that doesn't help, try creating a new temporary profile if the same happens there.

> Security Error: Content at https://github.com/login may not load or link to moz-extension://{user-defined}/js/content/inject.js.
Content Security Policy: The page's settings blocked the loading of a resource at inline ("script-src"). -- content.js:40:10

These are not from our extension.

**Comment by DavideRossi** [comment]
Same for me. I also tried to remove & recreate the database connection but when I click on "Connect" to create a new connection after removing the old one nothing happens.

**Comment by varjolintu** [comment]
Does 2.5.4 still work?

**Comment by bunnybooboo** [comment]
Tested: https://player.bfi.org.uk/ - extension integration worked as expected.
>I assume browser restart did not fix the issue?

This assumption is correct.
>Could you also verify the entry settings for example for GitHub, and double check if there's anything set in the Browser Integration tab of the entry.

I have no `site preferences` set anywhere.
>try creating a new temporary profile if the same happens there

(presuming new profile for KeePassXC) As part of my problem solving I had already created a new connection to the DB.
(presuming new profile for Web browser) I did this already for Firefox and the issue persists.

**Comment by varjolintu** [comment]
Can you give me an example of a site that does not work, and the entry URL used for it?

**Comment by bunnybooboo** [comment]
Potentially noteworthy: sites where integration has worked for me (Amazon, BFI, Google, Paypal) are those where I have multiple credentials stored. Sites with only one credential stored seem to be those experiencing problems.

For Google, however, I have four credentials stored in KeePassXC. The extension integration picks up only three of these, leaving my day to account needing manual intervention.

**Comment by bunnybooboo** [comment]
@varjolintu some example site login URLs not functioning as expected for me:
https://www.reddit.com/login/
https://github.com/login
https://www.netflix.com/gb/login
https://profile.theguardian.com/signin
https://myaccount.thameswater.co.uk/login

**Comment by varjolintu** [comment]
Please verify that those entries doesn't have any Browser Integration specific settings enabled in KeePassXC. You can view these when editing and entry and choosing the Browser Integration page.

This doesn't sound normal because all those sites work normally for me.

**Comment by bunnybooboo** [comment]
Oh hang on.. are expired credentials now handled differently?? If I uncheck any sites with expired dates the integration returns.

**Comment by varjolintu** [comment]
Check KeePassXC settings -> Browser Integration -> [ ] Allow returning expired credentials.

**Comment by bunnybooboo** [comment]
YES!! That's it fixed. Was not intuitive to me at least on transitioning to v2.6.0.

**Comment by bunnybooboo** [comment]
@DavideRossi is this perhaps reflected in your setup?

**Comment by DavideRossi** [comment]
This was possibly the same problem. But at this point my main problem is to restore my connection to the database that I erased with the idea of creating a new one. Which I do not remember anymore how should be done. The relevant information seem to be linked from the docs as "How to connect KeePassXC-Browser with KeePassXC" but the link is broken...

**Comment by varjolintu** [comment]
@DavideRossi KeePassXC -> Database Settings. There you can delete the connected browser keys. Do the same in the extension settings, with Connected Databases tab.

Link to the new documentation is here:
https://keepassxc.org/docs/KeePassXC_UserGuide.html#_setup_browser_integration

**Comment by DavideRossi** [comment]
Good, so now I restored by browser connection. 
And yes, now that I can test it, "Allow returning expired credentials" was indeed my original problem!
