### ISSUE TITLE
"Key exchange was not successful" - connect in settings does not work.

### ISSUE THREAD

**Issue by jarss** [keepassxreboot/keepassxc-browser#943]
## Expected Behavior

Clicking the extension icon and then "Reload" should lead me to connect to the database. KeePass-XC database unlocked, browser integration checked. 

## Current Behavior

error: "Key exchange was not successful." 

## Possible Solution

This is probably the result of downloading KeePass-XC snap after already pairing with apt version of the app. Followed troubleshooting guide to find json file, deleted, still same error. I probably need to re-create keys. Not sure how. When in the extension settings (click icon > Settings ) clicking "connect" does not do anything. 

## Steps to Reproduce (for bugs)

1. click the extension icon
2. "cannot connect" error. Click Reload.
3. "key exchange not successful" error

## Debug info

KeePassXC - unknown
KeePassXC-Browser - 1.6.6
Operating system: Linux x86_64
Browser: Mozilla Firefox 68.0

**Comment by varjolintu** [comment]
https://keepassxc.org/download/#linux - Use the Helper script for Snap.
