### ISSUE TITLE
keepassxc-browser (Brave) doesn't work for https://connect.garmin.com/signin/

### ISSUE THREAD

**Issue by gadabout84** [keepassxreboot/keepassxc-browser#946]
## Expected Behavior

The form-fields for the credential-values should be recognized and filled in properly.

## Current Behavior

The fields are not recognized and filled in properly and a red warning/error pane appears above the login-form without any (readable) info.
![image](https://user-images.githubusercontent.com/5605669/87697186-12a24b00-c792-11ea-85e9-d58197cdc874.png)

Redetecting the login-form-fields automatically or manually doesn't work too.

## Steps to Reproduce (for bugs)

1. With an open KeePassXC-instance and a database opened, open Brave (Version 1.10.97 Chromium: 83.0.4103.116 (Official Build) (64-bit))
2. Navigate to https://connect.garmin.com/signin/
3. Try to use already existing login-credentials for Garmin Connect from your database.

## Debug info

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Win 10
Browser: Brave Version 1.10.97 with Chromium: 83.0.4103.116 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
That's an iframe from URL `https://sso.garmin.com/sso/signin`. You need to modify your entry URL to `https://garmin.com/`.

**Comment by gadabout84** [comment]
@varjolintu, thanks for your very quick response! Much appreciated.

I could have thought about iFrames myself too, sorry!
