### ISSUE TITLE
Failing to identify input fields (regression)

### ISSUE THREAD

**Issue by mactalla** [keepassxreboot/keepassxc-browser#948]
## Expected Behavior
The user should be able to specify the username/password fields using "Choose custom login fields" on the website https://client.raymondjames.ca/

## Current Behavior
No input fields are identified as candidates to select.  "M" Show More does not identify any candidates, either.
The result is that nothing is selectable.

NOTE: The input fields are identified and can be selected in version 1.6.4, but versions 1.6.5 and 1.6.6 are broken.

## Possible Solution
Currently I've downgraded to version 1.6.4.

## Steps to Reproduce (for bugs)
1. Browse to https://client.raymondjames.ca/
2. Select "Choose custom login fields"
3. Note the inability to select either the username or password fields

## Debug info
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Linux x86_64
Browser: Chrome/Chromium 83.0.4103.116￼

**Comment by varjolintu** [comment]
This happens because we added an extra check for element CSS opacity for the input fields, and for some reason both login input fields on that page have `opacity: 0`. Plus the password input fields has `type=text`.

Of course these settings should not affect to "Choose custom login fields". It should ignore those faulty designs when using "Show more".

**Comment by Harrass** [comment]
I have a similar problem. I can no longer choose custom login fields at https://online.citi.com/US/login.do. I have to use autotype to enter credentials at that site.

Debug info
KeePassXC - 2.6.0
KeePassXC - Browser - 1.6.6
Operating System: Windows 10 (version 1909, OS Build 18363.900)
Browser: Chrome - 84.0.4147.89

**Comment by VinnieNZ** [comment]
I've also got this problem with a site.  I've checked the elements and don't have opacity: anything defined, nor is type=text for the password input field (it's type=password in this case).

I'm not able to provide the URL in a public place however, not sure how to get it to your privately, if you want it.

**Comment by varjolintu** [comment]
@VinnieNZ You can send me a private message at IRC/Matrix on Freenode's KeePassXC channel.

**Comment by sbadux** [comment]
I can't select the login fields on https://www.raiplay.it/ too. I don't know if this is related, because I've just started to use KeePassXC

**Comment by varjolintu** [comment]
@sbadux Those fields are inside a Shadow DOM which is not supported yet. Feature request is here: https://github.com/keepassxreboot/keepassxc-browser/issues/446

**Comment by mactalla** [comment]
I just tried out 1.7.1 and can confirm this is fixed.  Thanks!
