### ISSUE TITLE
[Whishlist] Never store credentials on some pages

### ISSUE THREAD

**Issue by szyb** [keepassxreboot/keepassxc-browser#95]
I never save passwords to my bank accounts. I wish to have a list of URLs that I don't want to query KeepassXC when new password is detected and want to save it.
Don't really know whether this option should be placed in the extension or KeepassXC it self, so I'm open to discussion about that feature.

## Expected Behavior

When I enter username & password on a specific page I would like to have option like "never store password on this page", so when I choose it and there won't be prompt next time.

## Current Behavior

Every time I enter a page that I don't want to store password there is prompt and notification about new password discovery.

## Possible Solution

Feature with list of  URLs that won't get or set password from or to KeepassXC database.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC Version: 2.3.1
KeePassXC-Browser Version: 1.0.1
Operating system: Win
Browser: Chrome/Opera
Proxy used: NO

**Comment by varjolintu** [comment]
I have been thinking the same kind of functionality. So let's keep this on the wishlist.

**Comment by newgoliath** [comment]
Yes,please include!

**Comment by varjolintu** [comment]
It will be in the next release :)
