### ISSUE TITLE
"Key exchange was not successful" on MacOS with Brave Browser

### ISSUE THREAD

**Issue by DoDoENT** [keepassxreboot/keepassxc-browser#950]
## Expected Behavior

Brave Browser should connect to the running instance of the KeePassXC, as it does on my Linux box.

## Current Behavior

Connection fails with "Key exchange was not successful" error.

## Debug info

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Mac
Browser: Brave Browser Version 1.11.97 Chromium: 84.0.4147.89 (Official Build) (64-bit)

**Comment by varjolintu** [comment]
Does enabling support in KeePassXC for Chrome and or Chromium solve the issue?

**Comment by DoDoENT** [comment]
I tried disabling brave and enabling only chromium - same behaviour. After that, I've enabled only Google Chrome (all other integrations were disabled). After that, I did not get the same error anymore. Instead, it kept saying that browser integration is not enabled in KeePassXC.
After that, I've enabled all chromium-based integrations (Chrome, Chromium, Vivaldi and Brave), clicked the refresh button in browser extension and nothing happened. However, then I opened extension's settings and navigated to "Connected databases" and clicked "Connect" and then it detected the running KeePassXC instance and successfully connected to the database.

Just to make sure I'm not mad, I've disabled all browser extensions in KeePassXC, except for Brave browser, restarted the KeePassXC and now extension no longer can exchange keys with the KeePassXC. Then, I switched back to enabling only "Google Chrome" browser integration (all other disabled) and key exchanging now works.

So, it appears that Brave browser on Mac requires KeePassXC to have "Google Chrome" browser integration enabled, instead of the one for the Brave browser.

**Comment by varjolintu** [comment]
I find it strange that Brave browser is using Chrome's application settings folder, and not its own. This is not the first time I've heard of this. A bug report should be filed to Brave.

**Comment by DoDoENT** [comment]
Thank you for noting that. I am also using Brave Browser on my Linux machine and there it works with "Brave browser integration" option, so I'd guess that there they are using chromium's (or their own) application settings folder?

**Comment by varjolintu** [comment]
Seems they are using different setting folders on different operating systems. That doesn't make sense.

**Comment by thel3l** [comment]
Issue persists even one year later. For a temporary fix for those looking, enabling the Chrome integration solves the problem when using Brave on MacOS 11.

**Comment by varjolintu** [comment]
This is a Brave issue. Why are they using Chrome's setting paths?
