### ISSUE TITLE
Browser integration stopped working after upgrade to 2.6 - Key exchange was not successful 

### ISSUE THREAD

**Issue by ntuckley** [keepassxreboot/keepassxc-browser#951]
## Expected Behavior
Running Mint 19 ( linux kernel 5.3.0-62) and all was well with KeePassXC and integration in firefox, chrome and chromium and also Andriod.  Since the upgrade to Keepass 2.6 integration has stopped working.

## Current Behavior

When I start a browser KeePass will start and enter the db password, but the browser extension will not connect
"Cannot connect to KeePassXC. Check that browser integration is enabled in KeePassXC settings."
If I reload then I'll get 
"Key exchange was not successful."
 
The extension will show no connected databases and will not connect to a db

Within the keepass db I can see the key for the the browser.
If I remove this it has no effect and the key is lost.

I have also tried this with a new unpopulated db with the same effect

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC -2.6.0
KeePassXC-Browser - 1.6.6   
Operating system:Linux
Browser: Chrome/Firefox/Chromium

**Comment by Meztihn** [comment]
I'm having same issue in Firefox on Windows 10. Versions are the same. All files mentioned in troubleshooting guide seem to be in place and keepass-proxy is running. But there are some differences:
- there is only single registry entry and it points to tor's json file (`org.keepassxc.keepassxc_browser_tor-browser.json`);
- the json files has a suffix with browser name (`org.keepassxc.keepassxc_browser_firefox.json`);
- the path variable points to keepassxc-proxy.exe.
Console in a debug tab displays repeated error messages:
```
Connecting to native messaging host org.keepassxc.keepassxc_browser 175 keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
Connecting to native messaging host org.keepassxc.keepassxc_browser 470 keepass.js:984:13
Error 7: Message encryption failed. Is KeePassXC running? keepass.js:1067:13
Connecting to native messaging host org.keepassxc.keepassxc_browser 148 keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
Connecting to native messaging host org.keepassxc.keepassxc_browser keepass.js:984:13
Error: No content script available for this tab. keepass.js:1188:25
```
and it goes on.

Another thing: the error remains the same and doesn't suggest to connect a db even after deleting all connected dbs in the extension settings. "Connect" button in the tab does nothing.

**Comment by varjolintu** [comment]
@Meztihn Clearly your registry entry is pointing to a wrong file. Change the registry file name to the correct one. I have no idea why this would've been changed due the upgrade.

**Comment by Meztihn** [comment]
@varjolintu sounds reasonable but what if I want to use extension in multiple browsers? Do I need a registry entry for each file? Won't they clash?

**Comment by varjolintu** [comment]
@Meztihn Each browser use its own registry entries and JSON files. They won't clash. Each browser needs to be connected with a unique name/id though.

**Comment by Meztihn** [comment]
@varjolintu Firefox and Tor share same entry in Windows registry (HKEY_CURRENT_USER\\Software\\Mozilla\\NativeMessagingHosts\\) and use different files (though contents are the same). I tried to change entry's value to Firefox but it was overwritten back to Tor automatically. Not a problem now, but might shoot in a leg in the future.
The problem fixed itself after changing the registry entry and rebooting but the entry's value was rolled back even before the reboot so I don't know what fixed the problem. Maybe deleting all connected dbs and rebooting.

**Comment by ntuckley** [comment]
Okay, so I now have KeePassXC working with mozilla.
I was using the flatpack version.  
I have added the PPA and installed that version and all works fine

I still cant get Brave working, but couldn't before so no change, and that I think is a different issue.
I would like to close this big, but it is being used for what appears a different issue.  May that should be raised as a new bug

**Comment by varjolintu** [comment]
@ntuckley Brave is a little odd bird because sometimes it seems to use Chrome or Chromium's configuration paths instead of Brave's own. You can try to enable support for those two browser too and see if it works.

**Comment by ntuckley** [comment]
And now I have just removed brave-browser-beta and reinstalled the stable
Added the extension
And KeePassXC working perfectly
So fully integrated in the browsers, my de-google journey continues!

**Comment by varjolintu** [comment]
@ntuckley We don't support any Beta or Develop versions of any browser. Glad the stable works.
