### ISSUE TITLE
the password generator is not showing but enable

### ISSUE THREAD

**Issue by x0rld** [keepassxreboot/keepassxc-browser#954]
the button for generate password is not on the input like on [gitlab](http://gitlab.com)
![image](https://user-images.githubusercontent.com/45242856/88304809-04f84280-cd09-11ea-9034-afb3083cf018.png)
I have no log about password generator

KeePassXC - 2.5.4
KeePassXC-Browser - 1.6.6
Operating system: Linux x86_64
Browser: Chrome/Chromium ( Vivaldi) 83.0.4103.119

**Comment by varjolintu** [comment]
Just to make sure, have you enabled password generator icon from the settings? Did you know that you can trigger the password generator to any input field using the context menu?

**Comment by x0rld** [comment]
It's enable, I used it few times, and like 2 day ago it disapear.
![image](https://user-images.githubusercontent.com/45242856/88369098-90b4b200-cd8f-11ea-8978-826458b05047.png)
it's in french but there is the check

I didn't know i can trigger the generator with the context menu, thx to the tips i will use that

**Comment by dvi7ik** [comment]
same prob

**Comment by varjolintu** [comment]
You can use the context menu for generating and filling a new password for now. Forms with two password fields are a bit difficult because it's not always known if the combo is new/confirm or old/new.

I'm using 1.7.0-beta1 to test this and it shows an username icon on the first field, because it always handles the first password field as "old/current" password.

**Comment by bkonia** [comment]
I have all the field icons enabled in the settings, but none of them are displayed in any form.

**Comment by varjolintu** [comment]
@bkonia I need more info than that. OS, browser, any errors in the Javascript console etc.

**Comment by bkonia** [comment]
I tried it in Windows 10, Chrome 87 and Edge 89. No icons in any username/password fields, no JS errors in the console. I tested a bunch of different sites, on both the login forms and registration forms. The fields work fine when you use the context menu, but I never get any icons. Let me know if you have a specific page you want me to test it on.

**Comment by droidmonkey** [comment]
You might have a conflicting extension.

**Comment by bkonia** [comment]
My Chrome is a clean install with no extensions.

It turns out the icons are there, but they're invisible. I can click the icon and it becomes visible if I manually set the background color in the CSS.

**Comment by droidmonkey** [comment]
Chrome may be clean but your profile might not be.

**Comment by bkonia** [comment]
Totally reset Chrome using "Restore settings to their original defaults", deleted all caches, cookies, etc... Still doesn't show the icons.

**Comment by varjolintu** [comment]
The password generator is deprecated and will be removed in some of the future releases. With KeePassXC 2.7.0 its own password generator dialog is used instead.
