### ISSUE TITLE
Wrong TOTP on one site

### ISSUE THREAD

**Issue by MBurchard** [keepassxreboot/keepassxc-browser#955]
## Overview
I use TOTP on some sites, like GitHub and it works perfectly well.  
But on one website I have a weird problem.  
https://{my-synology-name}.synology.me:5001/  
On this site, the browser button for inserting the current 6 numbers inserts 6 different numbers then the KeepassXC dialogue shows. So if I copy the numbers from the KeepassXC dialogue the login works. If I use the button inside the browser it doesn't.  
This Problem is under Windows 10 and Linux Mint 20.  
This Problem is in Firefox and in Vivaldi.  

![grafik](https://user-images.githubusercontent.com/4256302/88386932-b6eb4980-cdb1-11ea-95fd-667b6707195c.png)

## Context
[NOTE]: # ( Give us any additional information you may have. )

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Diagnosemodus ist deaktiviert.

Betriebssystem: Windows 10 Version 2004
CPU-Architektur: x86_64
Kernel: winnt 10.0.19041

Aktivierte Erweiterungen:
- Auto-Type
- Browser-Integration
- SSH-Agent
- KeeShare (bestätigtes und unbestätigtes Teilen)
- YubiKey

Kryptographische Bibliotheken:
 libgcrypt 1.8.5

Browser Extension:  
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Mozilla Firefox 78.0

**Comment by varjolintu** [comment]
Are the numbers still different if you fill them right after loading the page and entering your credentials?

**Comment by MBurchard** [comment]
I'm not able to fill it right after entering the page because login takes up to 5 seconds.  
I'm not sure either, but I think the loading time of the page should be irrelevant, because the token might have just changed. Therefore the button in the browser should request and enter the token from the KeepassXC application only at the moment of the click.

**Comment by varjolintu** [comment]
Currently TOTP is only received when the page is loaded, so it should be valid for some time. It's in the TODO list to do the TOTP request again when the icon is clicked and check if it's expired.

**Comment by varjolintu** [comment]
This is fixed with 1.7.0.
