### ISSUE TITLE
Password generator password disappear

### ISSUE THREAD

**Issue by kris7453** [keepassxreboot/keepassxc-browser#956]
## Expected Behavior

Filled password should stay in field.

## Current Behavior

Filled password from password generator disappear after a second.

## Steps to Reproduce (for bugs)

1. Open a website e.g. Jira sign up page: <https://www.atlassian.com/try/cloud/signup?bundle=jira-software&edition=free>
2. Summon context menu on a password field
2. Choose *KeePassXC-Browser*
3. Choose *Show Password Generator*
4. Click *Fill password*, to fill in field with password

## Debug info

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Windows 10
Browser: Firefox

**Comment by x0rld** [comment]
I have the same issue on many website i think that's cause a script type de password cause when i click on copy the password then paste manually on the input it work

**Comment by varjolintu** [comment]
Could not reproduce this with 1.7.0-beta1.

**Comment by varjolintu** [comment]
Reproduced it, and it seems the password is deleted when switching focus to another field.

**Comment by varjolintu** [comment]
Reproduced it. Probably the page script checks if the password has been entered via keyboard and not by a script. Gotta find a way to trick that.

**Comment by varjolintu** [comment]
Nothing we can do about this issue. Auto-Type is preferred instead.
