### ISSUE TITLE
detect textarea as input field

### ISSUE THREAD

**Issue by tolot27** [keepassxreboot/keepassxc-browser#957]
Some websites like QNAP NAS Webinterface using `<textarea .../> elements rather than `<input ... />` as username or password fields. Currently, KeePassXC does not detect textarea elements.

Example:

```html
<textarea class="qStr" data-qstrph="LDAP_SERVER_STR12" id="username" autocomplete="off" placeholder="Benutzername"></textarea>
```

**Comment by droidmonkey** [comment]
This is not a good idea it will raise tons of false positives

**Comment by tolot27** [comment]
> This is not a good idea it will raise tons of false positives

Even if it is restricted to certain IDs like "username" and (close) adjacency to the detected password input?

I should be more precise: It would be sufficient if textarea fields can be selected on chosing user defined fields.

**Comment by varjolintu** [comment]
I agree, adding this to the Custom Login Fields should be enough.

**Comment by OdinVex** [comment]
I use a NAS as well that uses a <textarea> for username. The ability to override in Custom Login Fields would be most appreciated indeed. Maybe automatically detect <input> and allow all components for Custom Login Fields. I saw one login page that required a combobox (input select) be set to a specific item from its list.

**Comment by varjolintu** [comment]
@OdinVex Support for `<textarea>` could be added to the Custom Login Fields, yes.

**Comment by OdinVex** [comment]
I've managed to get KeePassXC to recognize the textarea as a username input by choosing “Custom Login Fields” and pressing M, but I'm faced with another problem. The “Login” button is a non-form regular <button> element and doesn't trigger KeePassXC to remember the login information of the same exact NAS login page as @tolot27 has too. (I believe we're both using QNAP NAS and the login page is weird.) Perhaps adding a “Custom Login Fields” option for selecting a button to assume as submitting the form would be an idea?

**Comment by idontusenumbers** [comment]
> I've managed to get KeePassXC to recognize the textarea as a username input by choosing “Custom Login Fields” and pressing M, but I'm faced with another problem. The “Login” button is a non-form regular element and doesn't trigger KeePassXC to remember the login information of the same exact NAS login page as @tolot27 has too. (I believe we're both using QNAP NAS and the login page is weird.) Perhaps adding a “Custom Login Fields” option for selecting a button to assume as submitting the form would be an idea? I've manually created an entry for the URL and manually selected the fields, and it works (to any QNAP user doing this, the login will fail if you click into the password field after it has been filled, just click “Login”.)

With your suggestion to press M on the custom login fields screen plus manually added the URL in KeyPassXC I was able to get it working on QNAP.

**Comment by OdinVex** [comment]
> > I've managed to get KeePassXC to recognize the textarea as a username input by choosing “Custom Login Fields” and pressing M, but I'm faced with another problem. The “Login” button is a non-form regular element and doesn't trigger KeePassXC to remember the login information of the same exact NAS login page as @tolot27 has too. (I believe we're both using QNAP NAS and the login page is weird.) Perhaps adding a “Custom Login Fields” option for selecting a button to assume as submitting the form would be an idea? I've manually created an entry for the URL and manually selected the fields, and it works (to any QNAP user doing this, the login will fail if you click into the password field after it has been filled, just click “Login”.)
> 
> With your suggestion to press M on the custom login fields screen plus manually added the URL in KeyPassXC I was able to get it working on QNAP.

Glad I could help. I've been running into many websites that split fields across multiple pages and use dynamic inputs and/or mixed with non-password inputs, and frankly they're quite frustrating to deal with, let alone they trash accessibility-access and rights. Hoping for some legal standardization...someday. Highly doubt it'll happen. Glad KeePassXC can somewhat combat it. :)
