### ISSUE TITLE
I was able to disable KeePassXC for a site from the browser but not to re-enable it

### ISSUE THREAD

**Issue by hermarman** [keepassxreboot/keepassxc-browser#959]
## Expected Behavior
I inadvertently hit the "Disable for this site" button from the KeePassXC prompt dialog (actual label might be different, I'm using it in another language). As expected, KeePassXC stopped working on that site. I dug into the extension options and menus and was unable to find a way to undo the change. If I'm able to disable it from the browser I find reasonable to be able to re-enable it from the browser as well.

## Current Behavior
I'm unable to re-enable it from the browser.
Turns out that the only way I found to undo that change was from the desktop application using an option hidden in the entry properties: Edit entry > Properties > Addon data > Remove (again, actual labels might be different)
I would expect that to be too much _obscure_ for many users to find out.

## Debug info
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Mozilla Firefox 78.0

**Comment by varjolintu** [comment]
Extension settings -> Site Preferences -> The site has a combo box, select "Enable all features".

**Comment by hermarman** [comment]
Thanks!
In my case that list is not showing the disabled site

**Comment by varjolintu** [comment]
Oh you mean it doesn't ask the credential permission for that site? That needs to be deleted from the KeePassXC side yes.
