### ISSUE TITLE
W10 KeePassXC does not recognize the login fields and ignores login data

### ISSUE THREAD

**Issue by ineuw** [keepassxreboot/keepassxc-browser#964]
## Overview
Using KeepassXC v2.60, in Windows 10, Firefox 79. All KPXC settings and connections were properly set up in both KeePassXC the KeePassXC browser of Firefox, but it fails to recognize the URL and the login fields. 

## Steps to Reproduce
1. KeePass is loaded on Startup and I logged in before opening the browser. Also verified that the login parameters of the web site I want are correct.
2. Opened Firefox 79.
3. KeePassXC browser icon is displayed as being active.
4. Navigated to the website but KPXC ignored the website, the login fields and the data. The KPXC icon is not displayed by the login field.

## Expected Behavior
Recognize the URL, the login fields and fill it with data.

## Actual Behavior
Does nothing. There is no problem to login manually.

## Context
This is a new issue because I am using KPXC successfully to log in elsewhere, including this website

[NOTE]: # ( Paste debug info from Help → About here )
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

Operating System: Windows 10
Desktop Env: Windows 10

**Comment by varjolintu** [comment]
Please take a look at the Web Inspector's console log and see if there's any error mesages. Are there any sites in your Site Preferences settings? How's your main settings page? Is there icons disabled etc? Also, does this happen with a new temporary profile, or does it work with another browser?

**Comment by ineuw** [comment]
Please ignore this issue. I am closing it. Thanks
