### ISSUE TITLE
Can't connect to database on Google Chrome running Windows 10 under version 2.6.0

### ISSUE THREAD

**Issue by fbleitao** [keepassxreboot/keepassxc-browser#966]
## Expected Behavior
When I click on the green "Connect to database" button in the Chrome extension a pop-up should appear to create a new db connection.

## Current Behavior
When I click on the green "Connect to database" button in the Chrome extension nothing happens.

## Debug info
KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.15.0
Debugging mode is disabled.

Operating system: Windows 10 Version 1909
CPU architecture: x86_64
Kernel: winnt 10.0.18363

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey

Cryptographic libraries:
 libgcrypt 1.8.5

KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Chrome/Chromium 84.0.4147.105

**Comment by varjolintu** [comment]
Check the troubleshootin guide:
https://github.com/keepassxreboot/keepassxc-browser/wiki/Troubleshooting-guide
