### ISSUE TITLE
Extension only finds credentials when connected database is focused in KeePassXC

### ISSUE THREAD

**Issue by garymoon** [keepassxreboot/keepassxc-browser#968]
Thank you for KeePassXC-Browser! :blue_heart: 

## Expected Behavior
When I have multiple databases, and my browser is connected to a subset of them, the extension should search the ones it is attached to regardless of which is in focus in KeePassXC.

## Current Behavior
I have multiple databases. I use several instances of Firefox and connect each to one database. If the database for the browser I'm using is not in focus in KeePassXC, KeePassXC-browser reports no logins found. If the relevant database is in focus, it works as expected.

## Steps to Reproduce (for bugs)
1. Open multiple databases in KeePassXC and unlock them (ensure they are not copies/clones, and that "Search in all opened databases for matching credentials" is checked)
2. Connect one of them to a browser instance
3. Save a credential in this database
4. Switch to a different database tab in KeePassXC
5. Attempt to login to the same site again (KeePassXC reports no logins found)

## Debug info
Browser: Firefox 79 (not snap)

KeePassXC - Version 2.6.0
Revision: 0765954

Qt 5.9.5
Debugging mode is disabled.

Operating system: Ubuntu 18.04.4 LTS
CPU architecture: x86_64
Kernel: linux 4.15.0-36-generic

Enabled extensions:
- Auto-Type
- Browser Integration
- SSH Agent
- KeeShare (signed and unsigned sharing)
- YubiKey
- Secret Service Integration

Cryptographic libraries:
 libgcrypt 1.8.1

**Comment by varjolintu** [comment]
KeePassXC settings -> Browser Integration -> [x] Search in all opened databases for matching credentials.

**Comment by garymoon** [comment]
@varjolintu I specifically mentioned that was checked in the original report. I'd appreciate any further suggestions you might have.

**Comment by droidmonkey** [comment]
I'm certain that feature works, I tested it on numerous occasions in 2.6.0

**Comment by garymoon** [comment]
@droidmonkey Yep, I'm sure it does or there'd be more tickets about it surely. If you have any suggestions as to what might be interfering in my case I'd be much obliged! Cheers.

**Comment by droidmonkey** [comment]
I just tested this and it worked fine. I have no ideas since it works when the db is focused.

**Comment by garymoon** [comment]
Okay, thank you @droidmonkey!

**Comment by garymoon** [comment]
After further testing it seems to search other databases if the one in focus has been connected to, but not otherwise. I'm wondering if that's expected behavior and my original post wasn't clear enough?

**Comment by droidmonkey** [comment]
No that's not expected so there is a bug here potentially.
