### ISSUE TITLE
Option to migrate passwords from Firefox

### ISSUE THREAD

**Issue by macau23** [keepassxreboot/keepassxc-browser#97]
It's confusing that there are two password stores for Firefox when using keepassxc-browser - could you offer to migrate passwords from firefox to keepassxc on first-run?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Debug info

KeePassXC - {VERSION}
keepassxc-browser - {VERSION}
Operating system: Mac/Win/Linux
Browser: Chrome/Firefox/Vivaldi/Chromium
Proxy used: YES/NO

**Comment by droidmonkey** [comment]
Only you can access those passwords. You'll have to export them to csv and import them into KeePassXC.

**Comment by achimwagenknecht** [comment]
There seems to be a solution for KeePass: https://github.com/JanisEst/KeePassBrowserImporter
Maybe this could be implemented in KeePassXC, too?
