### ISSUE TITLE
"Add Username-only option for the site" doesn't work as expected

### ISSUE THREAD

**Issue by vaindil** [keepassxreboot/keepassxc-browser#971]
## Expected Behavior
Clicking the "Add Username-only option for the site" button should add the option to my settings in such a way that it immediately works (or works after a hard page refresh).

## Current Behavior
The current site is added without any query string parameters, which causes the extension to fail to recognize the setting and the username-only button is therefore pretty useless. 

## Possible Solution
Maybe match the username-only option against the current site without any query string parameters, but I don't know if that has any other implications.

## Steps to Reproduce (for bugs)
1. Go to the [AWS console](https://console.aws.amazon.com) (no account needed). You should be redirected to `https://signin.aws.amazon.com/signin` with a bunch of query string parameters.
2. Open the extension's popup and click "Add Username-only option for the site".
3. See that nothing happens on the page, because the button added a URL that doesn't match the current page.

## Debug info
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Windows 10
Browser: Firefox 80

**Comment by varjolintu** [comment]
This has been already fixed for the next release.

**Comment by vaindil** [comment]
Oh, perfect, thanks! Sorry, I tried searching but I must've searched poorly.

**Comment by varjolintu** [comment]
It's ok. I actually forgot to put this fix to the list of #961.
