### ISSUE TITLE
keepassxc-browser addon tries to start a new instance of keepassxc every second

### ISSUE THREAD

**Issue by leo-b** [keepassxreboot/keepassxc-browser#972]
Since upgrading from keepassxc 2.5.4 to 2.6.0, the browser plugin seems to fail in detecting the running instance of keepassxc.
It loops in starting new keepassxc instances. (If "Start only a single instance of KeePassXC" is enabled, keepassxc grabs the focus every second. If it is not enabled, a new keepassxc window appears every second.)

I am running keepassxc as a flatpak binary on centos 7 so I guess this could be a problem with flatpak sandbox settings but up to keepassxc version 2.5.4, everything worked fine.

Unfortunately I don't know how the browser extension tries to contact keepassxc, so I don't know how to further debug the problem...

KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Centos Linux 7
Browser: Chrome or Firefox

**Comment by varjolintu** [comment]
Browser should not start the KeePassXC instance so there's something wrong with your flatpak settings. It should start keepassxc-proxy instead.

Check https://github.com/keepassxreboot/keepassxc-browser/issues/297#issuecomment-429235866 and https://github.com/flathub/org.keepassxc.KeePassXC/issues/13

**Comment by droidmonkey** [comment]
Known issue with flatpak, we dont support that deployment method at this time.
