### ISSUE TITLE
Issue with single login forms

### ISSUE THREAD

**Issue by Excalibus2** [keepassxreboot/keepassxc-browser#975]
I am noticing some issues with the program filling out forms that have a single login field followed by another one after the first one is submitted. One such example is Google (has its own issue wit auto submit not working) or https://auth.ioeducation.com/users/sign_in

## Current Behavior
When filling these forms out the plugin fails to do so automatically and in the case of Google gos to the forgot password page instead of submitting.

## Possible Solution
Not quite sure. I used dash lane previously and they filled these forms nicely. Still had some issues with Google but they were less consistent.

## Steps to Reproduce (for bugs)
1. Save a few passwords for Google
2. Attempt to use auto fill
3. End up on forgot password page
4. Go back and disable auto submit and manually submit
5. Be taken to a password page where you are again asked what account to use

## Debug info
KeePassXC - 2.6.0
KeePassXC-Browser - 1.6.6
Operating system: Win32
Browser: Mozilla Firefox 79.0

Thank you for your time

**Comment by varjolintu** [comment]
With Google and other single login form sites you must add the page to Site Preferences in the extension settings and enable _Usename-only detection_ for it.

**Comment by yichangshengwu** [comment]
another example : https://accounts.firefox.com/

**Comment by a14219** [comment]
@varjolintu I have the same problem on Google and Amazon websites. The password field works fine, but the username is not detected.
I'm using KeePassXC 2.6.1 and extension version 1.7.0.

![image](https://user-images.githubusercontent.com/64659987/92113618-de412780-edef-11ea-8b8a-87fb713de1d8.png)

**Comment by varjolintu** [comment]
@a14219 I cannot reproduce that. Both sites work normally for me. You can try to set the Amazon URL to `https://www.amazon.com/*` instead.

**Comment by Excalibus2** [comment]
I only tend to have an issue with the password being filled if I unhide the field. If I do then it fills the password field with my username instead of a password. The real issue is that when it auto submits on Google I get taken to the forgot password screen.

**Comment by a14219** [comment]
>You can try to set the Amazon URL to `https://www.amazon.com/*` instead.
Thanks. Surprisingly, that worked.
