### ISSUE TITLE
Please don't force users to upgrade!

### ISSUE THREAD

**Issue by aadrian** [keepassxreboot/keepassxc-browser#977]
Please don't force users to upgrade KeePassXC. Since the browser extensions usually get updated automatically,
it's also forcing all the time the users to update KeePassXC Application too, since it stops working  :( .

However for many users this is not possible to do, since they have no control over the install/update process of system applications !

Because of this, evrytime there's a KeePassXC update, for a few days the browser integration is unusable :( 

Thank you.

**Comment by x0rld** [comment]
I'm using KeePassXC on linux and the last release is not package but i juste have a pop up you warn me i should upgrade it and I can still use the apps without any problem. I don't know for the browser extensions

**Comment by aadrian** [comment]
@x0rld This project **is** a browser extension. 

On different Firefox and Chrome Versions (Windows, Ubuntu, Pop_OS!, Debian, MacOS) it stops working correctly all the time there's a new update, until the two versions (the application and the browser extension)  are in sync.

The message from the screenshot is displayed, and it can't detect and fill fields as before. 
![keepassxc_browser_issue](https://user-images.githubusercontent.com/140953/91020809-39ef0200-e5f3-11ea-8eb5-fbd295eb9a09.png)

This happened all the time in the last 2 year's updates (not just now with 2.6.1) :( .

**Comment by x0rld** [comment]
I have the same message but it still works

**Comment by varjolintu** [comment]
Users are not forced to upgrade. You can still use older versions, and you can disable the warning from the settings when you put check for updates to _Never_.

**Comment by aadrian** [comment]
> Users are not forced to upgrade. 

Well, that's the impression of most users, since that red warning is the only thing displayed, and nothing else works with the browser extension.

> When KeePassXC and/or the extension updates and there's some strange problems with it, restart both KeePassXC and your browser to ensure the connection has not been invalidated between the upgrade.

Maybe this sentence should be the "warning" not the current error message? :)

**Comment by varjolintu** [comment]
Showing the warning, or upgrading KeePassXC shouldn't affect how the extension works. The 2.6.1 sadly included a bug with Best-Matching credentials enabled. It's already fixed for the next release.

**Comment by aadrian** [comment]
> Showing the warning, or upgrading KeePassXC shouldn't affect how the extension works. 

Sure, but being in red, the users perceive it as an error, not a warning :).

**Comment by varjolintu** [comment]
> > Showing the warning, or upgrading KeePassXC shouldn't affect how the extension works.
> 
> Sure, but being in red, the users perceive it as an error, not a warning :).

Not a big thing to change the color :) Let's do exactly that so the message doesn't seem so critical.
