### ISSUE TITLE
KeepassXC-Browser suddenly only returns "Error: No logins found"

### ISSUE THREAD

**Issue by Popkornium18** [keepassxreboot/keepassxc-browser#978]
The browser integration stopped working completely and only returns "Error: No logins found". The database is connected and the entries are not expired.

## Expected Behavior
When I click on a username field I get a selection of matching entries.

## Current Behavior
"Error: No logins found" is returned

## Debug info
No JS-Console errors.
KeePassXC - 1.6.6
KeePassXC-Browser - 2.6.1
Operating system: Arch Linux
Browser: Firefox

**Comment by varjolintu** [comment]
Does these help:
- Disable Best-Matching credentials from KeePassXC
- Restart both KeePassXC and the browser

**Comment by Popkornium18** [comment]
Yes, this fixes the problem. But why? I did not change anything.

**Comment by varjolintu** [comment]
Which one did you do? Both? Sometimes the update needs a restart from both sides.

**Comment by Popkornium18** [comment]
Disabling Best-Matching fixed it. Restarting did not.

**Comment by varjolintu** [comment]
There's a bug related to Best-Matching in 2.6.1. It's already fixed for 2.6.2. Sorry about the fuzz. For now it's best to keep it disabled, or if you definitely need it, downgrade to 2.6.0 and wait for 2.6.2.

**Comment by Popkornium18** [comment]
Alright, thanks for your help!

**Comment by RolandSM** [comment]
I can confirm this bug, Disabling "Best-Matching" fix that issue so far.
