### ISSUE TITLE
Ability to restrict keepassxc-browser to specific sub-tree

### ISSUE THREAD

**Issue by roweryan** [keepassxreboot/keepassxc-browser#98]
I'd like to restrict keepassxc-browser to a sub-tree, it doesn't need access to my ssh passwords.

**Comment by droidmonkey** [comment]
This is an excellent idea. Ideally, though, this would be implemented on the KeePassXC side, not the browser plugin side.

**Comment by kd8bny** [comment]
+1

**Comment by roweryan** [comment]
@droidmonkey should I move my issue?

**Comment by droidmonkey** [comment]
Yes please!

**Comment by roweryan** [comment]
Thanks.

Moved to https://github.com/keepassxreboot/keepassxc/issues/1789
