### ISSUE TITLE
Problem with site fanficton.net

### ISSUE THREAD

**Issue by Esse78** [keepassxreboot/keepassxc-browser#988]
## Expected Behavior
When I try to use the filter for a category I expect the filter window to open

## Current Behavior
When I try to use the filter for a category the filter window doesn't appear but if I try to open the filter window when the page is still loading it works.

## Steps to Reproduce (for bugs)
1. Go to a "category" page (example https://www.fanfiction.net/anime/Naruto) and click on Filters.

## Debug info
KeePassXC - {1.7.0}
KeePassXC-Browser - {2.6.1}
Operating system: Win
Browser: Chrome/Firefox (I tried both)

**Comment by varjolintu** [comment]
As a workaround, ignore the site via Site Preferences tab or disably Dynamic Input Field detection. Seems the `transitionend` event is overridden by the extension, and that should not happen.

**Comment by Esse78** [comment]
It still doesn't work.

**Comment by Esse78** [comment]
Sorry it works but I need to input all the pages
