### ISSUE TITLE
Keepassxc-browser doesn't work on Firefox if FF Multiaccount-Containers extension present

### ISSUE THREAD

**Issue by bungabunga** [keepassxreboot/keepassxc-browser#99]
It seems that Keepass-browser extension doesn't work on Mozilla Firefox if Firefox Multiaccount-Containers extension is installed. FF Multiaccount-Containers extension by Mozilla is a great privacy feature in FF since it keeps logins/cookies for different sites separated in different containers.

## Steps to Reproduce (for bugs)
1. Have Keepassxc-browser installed and set up in FF and KeepassXC on your computer
2. Install Firefox [Multiaccount-Containers extension](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/?src=search)
3. Delete cookies and active logins in FF
4. Open KeepassXC and try to log in to some site > "Time out or not connected to KeepassXC"

## Debug info
KeePassXC 2.3.1
keepassxc-browser 1.0.1
Operating system: Ubuntu 17.10
Browser: Firefox 59.0.1

**Comment by varjolintu** [comment]
I’ll test it out. Actually I’ve been using the same extension without any problems for months, but I haven’t cleared my cookies even once.

**Comment by bungabunga** [comment]
I figured out it was a false alarm, the issue was with the update of appimage file. Closing, sorry!
