### ISSUE TITLE
Autocomplete Menu is shown but it cannot be used from keyboard

### ISSUE THREAD

**Issue by philipreimer** [keepassxreboot/keepassxc-browser#991]
## Expected Behavior

When using keepassxc-browser on a page, for which I have multiple logins, I can use the keyboard shortcut `Alt+Shift+U` to show the list of available logins in a popup. **But** I **cannot** select the login to use via the keyboard's up and down arrows anymore.
This was working before version 1.7.0.

## Current Behavior

The popup with the list of logins does not react to any key strokes. It does not seem to have focus. Focus / Cursor remains in the login form.
I can only select a login from the list of logins by clicking on it with the mouse.
The browser console does not show any errors.
Apart from this KeepassXC and keepassxc-browser are working as expected.

## Steps to Reproduce (for bugs)

1. Go to a website for which you have saved multiple logins in KeepassXC
2. Press `Alt+Shift+U` to trigger login selection
3. keepassxc-browser will display a "popup" with the list of available logins for that website
4. Press `down` and `up` arrows on the keyboard to select the login you want to have entered in the login form --> nothing happens
5. Press `space bar` on the keyboard and you will notice that the cursor moves to the right in the login form

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux x86_64
Browser: Mozilla Firefox 79.0

**Comment by varjolintu** [comment]
I cannot reproduce this with Firefox or Chromium.

**Comment by philipreimer** [comment]
I have tried with all other extensions disabled but the issue is still there.

I am using Manjaro Linux Gnome Edition

Attached are my keepassxc settings
[keepassxc-browser_settings.zip](https://github.com/keepassxreboot/keepassxc-browser/files/5170531/keepassxc-browser_settings.zip)

**Comment by infomaniac50** [comment]
This was happening to me as well. I opened DevTools for the extension and the console was saying 'Error: Nonce compare failed'. Somehow the nonces got out of sync and the extension rejected the credentials list.

I fixed it by removing the database association and adding it back again. I can see a list of credentials in the username field again.

**Comment by varjolintu** [comment]
If the extension updates on-the-fly, it might break the connection or database association. Although, if the association breaks, the extension popup should just show the Connect button for the database.

**Comment by infomaniac50** [comment]
It was in the verifyResponse function. The console message came from line [1102 of keepass.js](https://github.com/keepassxreboot/keepassxc-browser/blob/f8373b1b1acc26d9499459baa275d543e12e8028/keepassxc-browser/background/keepass.js#L1102)

**Comment by infomaniac50** [comment]
I get the feeling these are all related.

- https://github.com/keepassxreboot/keepassxc/issues/5351
- https://github.com/keepassxreboot/keepassxc/issues/5376
- https://github.com/keepassxreboot/keepassxc-browser/issues/992

I use the original KeePass so I thought it might have been a compatibility issue at first.

**Comment by varjolintu** [comment]
@infomaniac50 Wait, so you use original KeePass with KeePassNatMsg?

**Comment by infomaniac50** [comment]
Yes.

**Comment by infomaniac50** [comment]
KeePassXC is looking mighty fine. I might have to try it out again for a couple of days. 

I know I'm going to miss that Floating Panel plugin. It comes in real handy when the URLs do not match up. 

It seems KeePassXC doesn't have an SSH agent builtin. It's just a client that adds the keys to an external agent. It would be nice if it could start the agent automatically if it can't find one.

**Comment by varjolintu** [comment]
@infomaniac50 Just to clarify, we don't support KeePassNatMsg officially, so any strange behaviour with it that cannot be reproduced with KeePassXC is something we don't inspect any further.

**Comment by infomaniac50** [comment]
Right. That's why I thought it might be a compatibility issue. Those other issues all sound the same even if they were caused by something else. For me it was the nonce counter but maybe it's something else for KeePassXC.

I have 1439 entries in my database and I rely on it everyday. So I'm resistant any changes in my setup. I worry about compatibility every time I open my database.

**Comment by philipreimer** [comment]
@infomaniac50 @varjolintu Just to avoid any potential misundestanding I would like to clarify that my KeepassXC and the browser extension are working just fine. The browser extension can connect to the database without problems, and shows me the correct list of logins for any page. Using the mouse and clicking I can select the right login, and it is entered correctly in the login form. I can even use all the KeepassXC-browser extension's keyboard shortcuts.

The **only** thing that is not working is that I cannot navigate the list of logins that is displayed on the web page using my keyboard - i.e. up and down arrows.
It seems that the keyboard/cursor/focus remains in the login form and is not moved to the list of logins.
I do **not** see any error messages in the browser console.

**Comment by varjolintu** [comment]
@philipreimer Can you check if this breakpoint triggers when you enable it for the same line? Also, check the value of `e.key`.

<img width="2058" alt="Screenshot 2020-09-04 at 11 24 12" src="https://user-images.githubusercontent.com/24570482/92218181-616e8600-eea1-11ea-8cb7-7e65af41ae07.png">

**Comment by philipreimer** [comment]
@varjolintu how do I do that? In my debugger I only see the entries 
* github.githubassets.com
* resource://gre

**Comment by varjolintu** [comment]
@philipreimer Right mouse click on the page -> Inspect Element -> Debugger tab. It should show all extensions in use.

**Comment by philipreimer** [comment]
Sorry, I don't see it. Do I have to manually install the extension from source for that?

![debugger](https://user-images.githubusercontent.com/5737222/92221183-5fa2c380-ee9d-11ea-906b-209a161705fb.png)

**Comment by varjolintu** [comment]
@philipreimer No, that's not necessary. I can see all extensions for example if I inspect this page during writing this reply. Does a page reload help when the debugger is active?

**Comment by philipreimer** [comment]
Ok. Found it. I had to enable the "Debugger Tools for Browser Chrome and Add-ons" in the Firefox Debugger Settings - very well hidden...

Anyway, the breakpoint is not hit.

**Comment by varjolintu** [comment]
@philipreimer I assume the line 32 still hits when creating the Autocomplete menu? Not sure why the EventListener is not triggering for you.

**Comment by philipreimer** [comment]
No, line 32 is not hit. Not even line 13.

**Comment by varjolintu** [comment]
@philipreimer Sorry, line 41 should hit when the Autocomplete Menu is triggered visible. The earlier function should hit when you load the page, database is unlocked and credentials are detected.

**Comment by philipreimer** [comment]
I noticed that `kpxcAutocomplete.create` is never called because `autoCompleteUsernames` is `false`?

```
    if (!kpxc.settings.autoCompleteUsernames) {
        return;
    }
```
If I change `autoCompleteUsernames` to `true` selection with up and down arrows are working again.

However, this setting has always been `false` in my case.

Also, when `autoCompleteUsernames == true` the list of logins is immediately shown when clicking into the login form. Not only when I press the shortcut `Alt-Shift-U`.
Can I somehow restore the old behaviour? 

Also, I noticed that now the list of logins is not shown any more when clicking on the keepassxc-browser toolbar icon.

**Comment by philipreimer** [comment]
> If I change `autoCompleteUsernames` to `true` selection with up and down arrows are working again.

But when selecting an entry from the list it now only fills the username into the login form. Not the password.
So setting `autoCompleteUsernames` to `true` makes the plugin useless if you don't use a mouse.

**Comment by varjolintu** [comment]
> > If I change `autoCompleteUsernames` to `true` selection with up and down arrows are working again.
> 
> But when selecting an entry from the list it now only fills the username into the login form. Not the password.
> So setting `autoCompleteUsernames` to `true` makes the plugin useless if you don't use a mouse.

You're lucky because I fixed that bug earlier today. I noticed the filling using Enter didn't pass the credential UUID correctly. Filling with mouse works.

**Comment by philipreimer** [comment]
> I'm confused because in your original post you said you see the menu but cannot navigate it?

Yes. In the settings "Trage Anmeldedaten ein" ("Filling credentials" in English I assume) I have only checked the first box "Automatically retrieve login data"(?). All the other checkboxes are not checked.

Pressing `Alt+Shift+U` shows me the list of logins for a page. But I cannot navigate in it or select an entry from it using the keyboard.
I have to use the mouse and click on entry so that it gets entered into the page's login form.

**Comment by varjolintu** [comment]
The second box is where the Autocomplete Menu option is. If that's disabled, then it's a bug if that is still shown when using keyboard shortcuts.

**Comment by varjolintu** [comment]
Just enable the Autocomplete Menu option and everything will work.

**Comment by philipreimer** [comment]
Ok. I'll wait for version 1.7.1 and try again.

**Comment by varjolintu** [comment]
> Ok. I'll wait for version 1.7.1 and try again.

You don't have to wait. Just enable the option.

**Comment by philipreimer** [comment]
As I wrote above `autoCompleteUsernames == true` breaks the functionality to fill the selected login data into the login form. 

> when selecting an entry from the list it now only fills the username into the login form. Not the password.

**Comment by philipreimer** [comment]
Version 1.7.1 seems to have fixed the issue.

**Comment by philipreimer** [comment]
Looks like 1.7.1 does not completely fix the issue, or introduced some regression - see #1013
