### ISSUE TITLE
Extension doesn't work on Brave after upgrade to 1.7.0

### ISSUE THREAD

**Issue by pattisahusiwa** [keepassxreboot/keepassxc-browser#992]
Neither keyboard shortcuts nor icon click work on any site after upgrade to 1.7.0 on brave browser. Javascript console message doesn't show any messages or errors.

![github](https://user-images.githubusercontent.com/11484016/92109179-86241880-ee23-11ea-9b15-c737a2dec722.png)

However, the same keepassxc version works on Vivaldi.

Brave browser:
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux x86_64
Browser: Brave 1.5.123 (Chrome/Chromium 80.0.3987.163)

Vivaldi browser:
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux x86_64
Browser: Vivaldi 2.11.1811.49 (Stable channel) (64-bit) (Chrome/Chromium 80.0.3987.158)

## Expected Behavior

Popup appears with saved login credentials.

## Current Behavior

Popup doesn't show up.

## Steps to Reproduce (for bugs)

1. Open any site (https://github.com/login)
2. Click on username
3. Use keyboard shortcut or click on the icon
4. Nothing happens

## Debug info

KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux x86_64
Browser: Brave 1.5.123 (Chrome/Chromium 80.0.3987.163)

**Comment by varjolintu** [comment]
Do you have _Automatically retrieve credentials_ disabled? If so, there's already fix pending for it.

**Comment by pattisahusiwa** [comment]
> Do you have _Automatically retrieve credentials_ disabled?

Yes. Ok, I'll waiting for the PR to be merged.

**Comment by pattisahusiwa** [comment]
**Additional info:**

I can fill the login credentials from contextual menu. After that, keyboard shortcut and icon click worked as expected. However, after refreshing the page or opening another page, the extension won't work again.
