### ISSUE TITLE
Average CPU usage and energy impact reported in Firefox when KeePassXC is not running

### ISSUE THREAD

**Issue by Gert-dev** [keepassxreboot/keepassxc-browser#995]
## Expected Behavior
The CPU usage and energy impact should be very low whilst KeePassXC is not running.

## Current Behavior
If I open Firefox, and go to `about:performance`, I see an average energy impact (1,5 up to 2,5) reported for KeePassXC-Browser.

This seems to be tied to the fact that KeePassXC itself is not running. If I start KeePassXC, the energy impact goes down to low (usually around 0,1).

I can even reproduce this when restarting Firefox and landing on `about:performance`, at which point all tabs are still unloaded - as they only load when you select them by default. This means there are no (?) website DOMs to scan yet.

Another observation is that closing KeePassXC again after the energy impact went down, does not immediately make it go up again, but clicking the KeePassXC-Browser icon in Firefox will update its status and make it detect KeePassXC is no longer open, which will then make the energy impact go up again.

## Possible Solution
I'm not familiar with the code and this may be completely wrong, but this may be related to the extension polling to see if KeePassXC has started. Perhaps the frequency of this polling can be reduced.

## Steps to Reproduce (for bugs)
1. Start Firefox whilst KeePassXC is not running. 
2. Go to `about:performance`.
3. Notice the energy impact of the extension.
4. Start KeePassXC.
5. Wait a couple of seconds to see the energy impact go down.

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux
Browser: Firefox

May be related to #348.

**Comment by varjolintu** [comment]
Do you have Automatic Reconnect enabled? That's the only feature that polls for KeePassXC. One reason why it's experimental is that it can cause some energy impact or memory rise.

**Comment by Gert-dev** [comment]
Thanks for your quick response! I do indeed have that enabled. I've turned it off and now the energy impact has indeed dropped to expected levels.

I was going to say: perhaps the polling can be increased to about once every second, since it takes time for the user to switch back anyway, but [a glance at the source](https://github.com/keepassxreboot/keepassxc-browser/blob/develop/keepassxc-browser/background/keepass.js#L1203) seems to imply that that's already the case.

Perhaps it would be interesting to mention the rise in energy impact in the warning on the settings page that it's experimental, so users realize this can be have a larger impact.

Is there perhaps another ticket already that's tracking the energy impact of this new feature that I can follow?

**Comment by varjolintu** [comment]
The Auto-Reconnect feature will be removed when I find out how to do the reconnect inside keepassxc-proxy. So far I haven't succeeded in my attempts.

There's no other issue about this. The impact happens because now we have to launch the keepassxc-proxy once per second to see if KeePassXC is connected. If and when the feature is finished, keepassxc-proxy is always active and handles the disconnect/reconnect situations automatically.

**Comment by Gert-dev** [comment]
Good to know, thanks for the info and your time!

The workaround is sufficient for me, so feel free to close this ticket, or leave it open to track the underlying problem, whichever suits your needs best. If you decide to leave this ticket open, I'll monitor it in case you need someone to test changes.
