### ISSUE TITLE
Credentials with only the domain are not found anymore

### ISSUE THREAD

**Issue by micw** [keepassxreboot/keepassxc-browser#996]
## Expected Behavior
I have stored credentials with the domain only (without the path part) for some pages which have changing login URLs. I'm pretty sure that these credentials where auto-completed a while ago.

## Current Behavior
Credentials are not found (The plugin logs "error 15" with a message that no credentials could be found.

## Possible Solution
Fix it?

## Steps to Reproduce (for bugs)
Create an entry in keepass-xc for "https://mydomain.com". Visit "https://mydomain.com/login/" -> credentials are not found.

## Debug info
KeePassXC - 2.6.1
KeePassXC-Browser - 1.7.0
Operating system: Linux 
Browser: Firefox 80.0 (64 bit)

**Comment by varjolintu** [comment]
See https://github.com/keepassxreboot/keepassxc/issues/5299.

**Comment by micw** [comment]
That was a fast response. Sorry, I did not know that's a keepass-xc issue, so I did not search there.
Thank you for clarification.
