### ISSUE TITLE
exchange of keys fails

### ISSUE THREAD

**Issue by herrdeh** [keepassxreboot/keepassxc-browser#997]
I read some comments on this issue, but could not find a solution for me - sorry.
I'm on a clean install ubuntu 20, Firefox 75, keepassxc 2.4.3.

With the extension installed, whenever I try to connect it to the running keepassxc, it reports "exchange of keys fails". What should I do?

Cheers,
Wolf

**Comment by herrdeh** [comment]
Thank you for your attention. No, I think it's not a snap version.
![Bildschirmfoto von 2020-09-04 12-42-28](https://user-images.githubusercontent.com/7152847/92230947-32a9dd00-eeac-11ea-9de1-a11798f577e7.png)

**Comment by varjolintu** [comment]
Then I suggest you go through the docs and troubleshooting guide in the wiki.

**Comment by herrdeh** [comment]
Ah. Thanks for that hint. I found that the sync feature was not activated in my KeePass.
Thanks for all!

**Comment by varjolintu** [comment]
Sync feature..?

**Comment by herrdeh** [comment]
I had this one disabled. Stupid me...

![Bildschirmfoto von 2020-09-04 21-13-05](https://user-images.githubusercontent.com/7152847/92277707-d79bd880-eef3-11ea-8e18-bde34e18b8a1.png)
