### ISSUE TITLE
Password is not filled when selecting username in dropdown

### ISSUE THREAD

**Issue by FlyveHest** [keepassxreboot/keepassxc-browser#998]
## Expected Behavior

When I go to a page with a stored login, I can select the username I want to use to log in, and then the password should automatically be filled.

## Current Behavior

When I select the username from the dropdown, nothing happens, I have to use the shortcut shift-alt-i to fill in the password.

Also, I can use the same hotkey to fill in a password, before I have selected the username I want to use.

The change happened with the last update to the addon, i've only experienced it the lasst couple of days.

## Steps to Reproduce (for bugs)

1. Go to a page with a stored login
2. Select login in username field, using up/down arrows
3. Password box is not filled

## Debug info

KeePassXC - 2.45
KeePassXC-Browser - 1.7.0
Operating system: Win
Browser: Firefox 76.0.1 (Older version, due to company restrictions)

**Comment by martinbartin** [comment]
Got the same issue with various sites. Seems that not all sites are affected.

**Comment by varjolintu** [comment]
Fixed the problem. Entry UUID was missing when doing the fill using the keyboard. Filling using a mouse still worked normally.

**Comment by FlyveHest** [comment]
Wow, that was incredibly fast, thanks a lot 👍

**Comment by martinbartin** [comment]
Also from my side .. thanks a lot!
